### ISSUE TITLE
Add system overview diagram

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#10]
@philbooth asked for a system overview diagram, and @shane-tomlinson said he had one - let's get it linked into the docs here in whatever form it's in, and we can iterate as necessary from there.

**Comment by shane-tomlinson** [comment]
![firefox_accounts_ecosystem](https://cloud.githubusercontent.com/assets/848085/8568440/89318ad0-2565-11e5-93de-d97c84d2e4f1.png)

**Comment by shane-tomlinson** [comment]
I believe that is Louvre quality artwork there.

**Comment by philbooth** [comment]
It's the drop shadows that make it extra special. Without those it's ordinary. :)

**Comment by rfk** [comment]
best. arrows. ever.

**Comment by chilts** [comment]
I think the horizon is wonky! :/
