### ISSUE TITLE
Config variables inconsistent across various repos

### ISSUE THREAD

**Issue by michielbdejong** [mozilla/fxa#100]
Compare https://github.com/mozilla/fxa-profile-server/blob/master/lib/config.js#L162 with https://github.com/mozilla/fxa-content-server/blob/master/server/lib/configuration.js#L364, one has `'/v1'` at the end, the other doesn't.

It's not a real problem, just not so beautiful :)

**Comment by vladikoff** [comment]
Checked this out, profile seems to be the odd one out, but the change to it will require updating 3-4 repos, so probably gonna leave it be for now. reopen if becomes a problem.
