### ISSUE TITLE
View localized emails with Storybook

### ISSUE THREAD

**Issue by Yogita98** [mozilla/fxa#10019]
We've setup storybook locally to preview `auth-server` emails in the new templating stack. We've also replaced gettext with fluent for localization. It'd be nice to preview emails translated in atleast one locale other than the default with storybook.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3820)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Lauren Zugai should this be in an epic?

**Comment by Yogita98** [comment]
Closing this issue as it was completed as part of #10018
