### ISSUE TITLE
[fxa-content-server] Update DOWNLOAD_LINK_PAIRING_APP for Firefox Preview

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1003]
Currently we are on Ref Browser in https://github.com/mozilla/fxa/blob/8e64ab317436ad4f3c6cb46795684e515b1c144e/packages/fxa-content-server/app/scripts/lib/constants.js#L111

**Comment by vbudhram** [comment]
from mtg:

Are you working on this @vladikoff , if so move from backlog.
