### ISSUE TITLE
Update product link in 123done (PRO)

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1004]
See [this code](https://github.com/mozilla/fxa/pull/1002/files#diff-f131e4184892365038f8b6a7566fb882R74), a followup to #1002

**Comment by lmorchard** [comment]
Yeah, good callout - this is essentially blocked by #926

**Comment by lmorchard** [comment]
This should be done: https://github.com/mozilla/fxa/commit/4bb5fe887f94848b98453db42f2a6bba152f125c#diff-5926642c3563b747c17382436ec16752R14
