### ISSUE TITLE
[FxA-Settings] “Step 1 of 2” and “Step 2 of 2” text is not displayed on the Secondary email pages (improvement)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10058]
**Build:**
Stage (Train 1.212)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net and login using an existing account.
1. Go to “Secondary email” section and click “Add” button.
1. Observe the page.
1. Enter email address and click “Save” button.
1. Observe the second page.

**Actual result:** 
“Step 1 of 2” and “Step 2 of 2” text is not displayed on the Secondary email pages. There is no consistency with the other section’s pages.

**Expected result:**  
“Step 1 of 2” and “Step 2 of 2” text is displayed on the Secondary email pages. There is consistency with the other section’s pages.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3829)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15918/2ndary+email+improvement.PNG">2ndary email improvement.PNG</a>

**Comment by Ayushsunny** [comment]
> ┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3829)
> ┆Attachments: [2ndary email improvement.PNG](https://mozilla-hub.atlassian.net/secure/attachment/15918/2ndary+email+improvement.PNG)

Hello, @data-sync-user I was checking this to work.
And why I'm not allowed to see [this](https://mozilla-hub.atlassian.net/secure/attachment/15918/2ndary+email+improvement.PNG) image

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

PR https://github.com/mozilla/fxa/pull/10541 ( https://github.com/mozilla/fxa/pull/10541|smart-link )
