### ISSUE TITLE
Uplift SubPlat Stripe's required metadata fields to the docs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10075]
Any chance we can uplift [https://github.com/mozilla/fxa/blob/a0c7ac2b4bad0412a0f3a25fc82b5670922f8957/packages/fxa-auth-server/lib/routes/validators.js#L396-L437](http://example.com) of required metadata fields to the docs at https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-subscription-platform ?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3833)

**Comment by biancadanforth** [comment]
Closed by mozilla/ecosystem-platform#147.
