### ISSUE TITLE
"Cerrar sesion" (sign out) button does not fit in button on mobile

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1008]
<img width="138" alt="Screenshot 2019-05-03 at 11 04 36" src="https://user-images.githubusercontent.com/848085/57131149-70b45f80-6d93-11e9-8b3b-6e130af67bc7.png">

cc @johngruen

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-71)
┆Issue Number: FXA-71

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Closing, old settings bug
