### ISSUE TITLE
[subplat] Card’s field placeholder not aligned properly on “Set up your subscription” page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10085]
**Affected versions**:

* Safari;

**Affected FxA versions**:

* 1.212.0;

**Prerequisites**:

* Be in a country where the Mozilla VPN is available;
* Have an FxA account without a subscription;
* Be logged in;

**Steps to reproduce**:
1. Access https://www-dev.allizom.org/en-US/products/vpn/#pricing, and select any price plan;
2. Observe the “Name as it appears on your card” field placeholder;

**Expected result**:

* The placeholder is vertically centered;

**Actual result**:

* The placeholder is not vertically centered;

**Notes**:

* Not reproducible on Firefox and Chrome;
* See the attached screenshots;

!Screenshot 2021-08-11 at 13.27.38.png|thumbnail! 
 !Screenshot 2021-08-11 at 13.24.04.png|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3835)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15944">Screenshot 2021-08-11 at 13.24.04.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15945">Screenshot 2021-08-11 at 13.27.38.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
