### ISSUE TITLE
[subplat] Implement P3 metrics for passwordless flow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10098]
From https://docs.google.com/document/d/1x0lYak98rM8ickwDciTn99Sd9-r1j6PmvAa8SP7CxGg/edit#

We should implement the P3 metrics

* How many users try to sign in without a password set.
* This is a guardrail metric. 
* How long does it take from subscribing for a user to set their password?
* How many users Download the VPN before they’ve set their password. 
* How many users click “Change Plan” and go back to change their plan. 
* How many users have to send a follow-up set password email.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3841)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
