### ISSUE TITLE
Previous tab “Reset email sent” changes to “Authorize this sign-in” after the user resets the password

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10094]
**Build:**
Stage [Train 1.212]

**Affected platforms:**
Windows 10 64-bit

**Preconditions:**
2FA is enabled.

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net and enter your email address.
1. Click “Forgot password?” link.
1. Enter your email address and click “Begin reset” button.
1. Check your inbox for the Reset your password email and click “Create new password” button.
1. Enter the new password and click “Reset password”.
1. Observe the previous tab.

**Actual result:** 
The previous tab refreshes to Authorize this sign-in page but the user is able to log in after entering the 2FA security code.

**Expected result:** 
The previous tab remains as it was or gets closed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3836)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15951/previous+tab+issue.gif">previous tab issue.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
