### ISSUE TITLE
Create storybook for PaymentLegalBlurb component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10102]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3844)

**Comment by biancadanforth** [comment]
This is a follow-up from #9794 .

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Follow-up to https://mozilla-hub.atlassian.net/browse/FXA-3715 ( https://mozilla-hub.atlassian.net/browse/FXA-3715|smart-link ).
