### ISSUE TITLE
[Train-136]Sending a tab on iOS from Desktop doesn't work

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1010]
Environment:
Build: Stage [Train 136];
Devices: iPhone SE 12.1.4;

Prerequisites:
You are logged with the same account on Desktop and iOS device.

Steps to reproduce: 
1. Right click on an opened tab from your Desktop;
2. Move the cursor on 'Send Tab to Device';
3. Click on your iOS device;

Expected results:
On your iOS device, it appears a pop-up with the link sent from your Desktop.

Actual results:
The pop-up doesn't appears.

Notes: 
- Not reproducible if you send the tab from an Android device;
- Not reproducible on production;

**Comment by vbudhram** [comment]
from mtg:

@vbudhram to try and reproduce issue.

**Comment by vbudhram** [comment]
@sv-sdeiac I tested this with FF66 and FF iOS 16 (both point to stage servers) and was able to send a tab from desktop to iOS.

On iOS did you allow push notifications?

**Comment by sv-sdeiac** [comment]
Hello, It seems that I can't reproduce anymore this issue on Train 136 using iPhone SE. Due to that, I'll close this issue, thanks.
