### ISSUE TITLE
Sub Plat customer is receiving duplicate emails on both primary and secondary addresses

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10116]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1725681

> User subscribed to Mozilla VPN is receiving email notifications (marketing, payment confirmations) to both the primary email associated with the subscription and to the secondary email added to FxA account.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3847)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Juan Zapata gave me the primary/secondary emails that reported this issue.  I can confirm:

  * The accounts are verified and in good standing
  * Both accounts are receiving emails the Subscription Platform is sending

In 2021, we’ve sent these emails which have been received by both addresses:

subscriptionSubsequentInvoice
subscriptionSubsequentInvoice
subscriptionSubsequentInvoice
downloadSubscription
subscriptionFirstInvoice
newDeviceLogin

The first delivered as far back as May 21, the most recent on Aug 11.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
