### ISSUE TITLE
[content-server] color variables in app/styles/variables don't match those used by design team

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10126]
This came up in [FXA-3715] and FXA-3669; for example, the [MVP designs](https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=1064%3A15109) for the terms and privacy links at the bottom of the new passwordless checkout flow are listed as `$grey-50` (#3D3D3D), but `$grey-50` when imported from `fxa-content-server/app/styles/variables` is much lighter (#737373).

This comes from a node package, `photon-colors`, where none of the greys are #3D3D3D.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3850)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This will get fixed with tailwind.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
