### ISSUE TITLE
Verify appropriate emails are sent to primary and secondary accounts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10139]
Let's audit our email sending code to make sure the emails we send go to the right primary and secondary accounts.  

While we're at it, maybe we make some documentation about which emails get sent to which addresses!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3853)

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

The CAD script is sending to the wrong address after changing the primary

**Comment by Ludwigsfeld** [comment]
I can only approve: I changed my primary email address, removed the old one, but still get messages to my old email address, for example, i still get the "friendly reminder on how to sync my mobile phone" email on my old address.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
