### ISSUE TITLE
[subplat] After introducing a password for the new account user is not redirected directly to Download page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10167]
**Affected browser versions:**

* All Chrome;

**Affected FxA versions:**

* 1.213.1;

**Prerequisites:**

* Have a VPN set to Germany location;
* Have a subscription made for a passwordless account;

**Steps to reproduce:**
1. Go to your email and click the “Create password” button;
2. Enter/Confirm a password;
3. Click “Create password” button;

**Expected result:**

* Download page is loaded.

**Actual result:**

* User is redirected to a Sign in FxA page. **After entering the new email, the user is redirected to the download page that shows an error**.

**Notes:**

* The Download page is loaded with success if the URL is used directly, or if the flow was finalized for a previous account.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3864)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16016/nodown.gif">nodown.gif</a>

**Comment by biancadanforth** [comment]
> The Download page is loaded with success...if the flow was finalized for a previous account.

Can you clarify what you mean by "if the flow was finalized for a previous account"? What are the STR for that where the page loaded successfully?

**Comment by biancadanforth** [comment]
In general, I see two potential issues of differing severities here:
* [S3] Indirect access to the download page. Is the indirection to the download page required? That deviates from the MVP designs which show going from the finish setup page directly to the download page.
* [S2] Download page has an error when redirected through the intermediary page above, but not when the URL is visited directly.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Valentina Virlics The Download page is successfully loaded if the same flow is followed twice. I think this is because the user is actually logged in to Download page even if the error page is displayed. So, following the same steps again, triggers a successfully Download page.

Also, I agree with your 2 potential issues.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I worked with Sarah Bird on this, and she has fixed the issue on the Guardian site.  And on our end, https://mozilla-hub.atlassian.net/browse/FXA-3875 ( https://mozilla-hub.atlassian.net/browse/FXA-3875|smart-link ) should fix the signed in state after the user set the password on the new account.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified this as fixed on v. 1.213.3 - Staging. After setting the password for the account, the user is redirected to the Download page.
