### ISSUE TITLE
[subplat] Buttons from error page look inactive

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10163]
**Affected browser versions:**

* All Chrome;

**Affected FxA versions:**

* 1.213.1;

**Prerequisites:**

* Have the a VPN set to Germany location;
* Have an FxA account with no active subscription;

**Steps to reproduce:**
1. Open VPN homepage https://www-dev.allizom.org/de/products/vpn/;
2. Click “Get Mozilla VPN” and choose any plan;
3. Fill all mandatory fields and use a credit card from Romania to subscribe.
4. Observe “Try again” button;

**Expected result:**

* The button is blue and active.

**Actual result:**

* The button is grayed out.

**Notes:**

* The  button is active, only looks disabled because of the color.
* Reproducing for all buttons from error pages;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3861)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16013/Screenshot+from+2021-08-19+13-06-08.png">Screenshot from 2021-08-19 13-06-08.png</a>

**Comment by biancadanforth** [comment]
Thanks for filing. I can reproduce this in Firefox 93 (Nightly) as well.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

This should be verifiable in Train 213.4.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified this on Train 1.213.5, on Chrome. The button is blue and active. See the attached screenshot. 

!Screenshot 2021-08-24 111211.jpg|width=763,height=797!
