### ISSUE TITLE
[subplat] FxA ToS and PN available in “Subscription confirmation” page for old users

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10171]
**Affected browser versions:**

* All Chrome;

**Affected FxA versions:**

* 1.213.1;

**Prerequisites:**

* Have a VPN set to Germany location;
* Be in the old "Subscription confirmation" page;

**Steps to reproduce:**
1. Observe footer;

**Expected result:**

* There are no FxA Tos and PN links available.

**Actual result:**

* The FxA Tos and PN links are displayed.

**Notes:**

* Both links redirect to a “Not Found” page ~~https://payments~~stage.fxa.nonprod.cloudops.mozgcp.net/products/undefined/legal/privacy;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3868)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16035/ToS+and+PN+not+found+for+FxA.gif">ToS and PN not found for FxA.gif</a>

**Comment by biancadanforth** [comment]
Thanks for filing.

Developer note: This is because the `showFXALinks` flag in the `TermsAndPrivacy` component should be conditionally set based on `accountExists` in the `PaymentConfirmation` component.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Bianca Danforth The FxA ToS and PN links in the new “Subscription confirmation“ page also redirect to a “Not found“ page.

!ToS and PN not found for FxA.gif|width=1905,height=1012!

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thank you fellow Bianca (first time for everything).

Dave Justice is working on this fix. Dave, can you take a look? He is on PTO today and Monday, but he will be back Tuesday.

If I get some bandwidth before he’s back, I can look at it as well.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

fixed in https://github.com/mozilla/fxa/pull/10179 ( https://github.com/mozilla/fxa/pull/10179|smart-link )

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

This should be verifiable in Train 213.4.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Verified as fix on Train 1.213.5, on Chrome. There are no FxA Tos and PN links available for old users.
