### ISSUE TITLE
Settings redirects totp users to the wrong code screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10181]
If a totp user lands on /settings with an unverified session, they'll get redirected to /signin_token_code (the email 2fa page) instead of the totp 2fa page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3873)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
