### ISSUE TITLE
Back-association of uids to flow_ids in amplitude breaks in some cases

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#1018]
I'm unsure at this point if this breakage is due to us or to amplitude. Filing an issue here until we know for sure.

On about:welcome (entrypoint = activity-stream-firstrun) the page pings our metrics endpoint to obtain `flow_id` and `flow_begin_time`. Then the page appends those values as query parameters when the user continues the flow to accounts.firefox.com. This allows us to track the user's flow starting on the reiler's site (about:welcome, in this case).

Here is an example of [a flow](https://sql.telemetry.mozilla.org/queries/62593/source) showing that the method generally works, at least for re:dash. The `flow.enter-email.view` event is logged, associated with the same `flow_id` and then back-associated with the same `uid`. here, the user's funnel is complete.

However this doesn't seem to work in amplitude - the email-first form view gets associated with a different amplitude user id than does the rest of the funnel: 

see [here](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D85703851806) and [here](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D85703912247?eventFilter=fxa_reg+-+view). These show the same flow_id as the re:dash query above; the two amplitude user ids have the same value for `flow_id` but get incorrectly associated with different user ids. 

one consequence of this is that it breaks [our funnel charts](https://analytics.amplitude.com/mozilla-corp/chart/m5avm0b/edit/hv5n7hj) because the same user id isn't carried through all steps in the funnel.

@philbooth my only thought here is that this is because `flow_time` for the email-first event is much higher than the corresponding values for the other events - maybe amplitude is looking at this value to reconstruct the event timeline, and then sees that it's not consistent with the other events that are associated with the same `flow_id`, and so gives it a different user id?

it would be good to fix this if possible, since it will help @davismtl and I more easily analyze the performance of trailhead.

**Comment by irrationalagent** [comment]
FYI this issue will also block amplitude visualization of trailhead signups/logins starting on about:welcome ([for example](https://analytics.amplitude.com/mozilla-corp/chart/j0mp6zx)) cc @davismtl

**Comment by philbooth** [comment]
Missed this in my bugmail last week, sorry @irrationalagent.

The problem is with the device id, not the flow id. We'll need to include it in the response from `GET /metrics-flow` and tell the consuming end to pass it back to us in the query string along with the flow id.

The first part of that is just a one-liner. Who do we need to reach out to for the second part?

**Comment by irrationalagent** [comment]
I'll file an issue in the trailhead repo

**Comment by philbooth** [comment]
> I'm guessing we will want to make the change on our end first before they do?

Yep, PR for train 136 is coming any second now.

**Comment by clouserw** [comment]
This works.  Thanks!
