### ISSUE TITLE
Design and work breakdown for FxA-46: sms install link

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#102]
Let's get cracking on an initial feature description [1] for the "sms me an install link" feature recently proposed on the mailing list [2].  We can start by scoping out the intended flows and how we'll measure success, then assign a follow-up bug to @ryanfeeley for UX treatment.

Some thoughts on things to consider:
* Will we run this as a formal experiment?  What will we compare against?
* How will we decide what users to include/exclude from the experiment?
* How will we measure success?  Can we concretely detect that a user successfully connected a second device by following one of these links?
* Do we need to consult with legal, or the growth team, or others?

@seanmonstar as discussed, assigning to you to drive this forward.

[1] https://github.com/mozilla/fxa/tree/master/features
[2] https://mail.mozilla.org/pipermail/dev-fxacct/2016-January/001831.html

**Comment by rfk** [comment]
> Will we run this as a formal experiment? What will we compare against?

Hmmm...actually this would make it an experiment on logged-in users, which I recall triggering legal/privacy/compliance concerns.  From memory, we're not supposed to run experiments on logged-in users without giving them a way to opt-out.  @ckarlof do you recall any more of the details there, and whether it's still a concern?

**Comment by shane-tomlinson** [comment]
@seanmonstar - can you triage this as you see fit?
