### ISSUE TITLE
[subplat] Users can create passwords repeatedly for an account without being notified that they have already created a password for that account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10209]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.213.3;

**Prerequisites**:

* Be in a country where the Mozilla VPN is available;
* Have no FxA account; 

**Steps to reproduce**:
1. Access https://www-dev.allizom.org/en-US/products/vpn/#pricing, and subscribe to any subscription plan;
2. Open your email for the account just created and click on the “Welcome to Mozilla VPN: please set your password” mail.
3. Click on the “Create a Password” button;
4. Fill in both fields with the same password and click on the “Create Password” button;
5. Go back to the “Welcome to Mozilla VPN: please set your password” mail and click again on the “Create a Password” button;
6. Fill in both fields with a different password then the previous time;
7. Observe the behaviour; 

**Expected result**:

* The user is not able to set another password for the account. The user should be informed that he already created a password for the account. 

**Actual result**:

* The user is able to set another password for the account without being informed that he already created a password. 

**Notes**:

* The user is able to log in only with the first password created;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3882)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16615/image-20210927-202010.png">image-20210927-202010.png</a>

**Comment by data-sync-user** [comment]
➤ Zachery Sutton commented:

Hi Barry Chen Here is a quick walkthrough video and potential solution. Please let me know your thoughts.

Walkthrough Video ( https://cln.sh/NtLb8p )

Prototype Here ( https://www.figma.com/proto/ARS3HjtJZBOdfBNvjnK5vl/Sign-in?page-id=0%3A1&node-id=13%3A106&viewport=270%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=13%3A106&show-proto-sidebar=1 )

Thanks

Zachery

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Hi Zachery, thanks for the video!

I’m not sure if I understand the difference between the two options.  The pages with the alert and the form appear to be the same.  (The page following really depends on whether the user’s signed in or not.)

I think a general comment is that since we do not want the user to enter a password, I think we shouldn’t even give them the option?

And please feel free to get in touch if you ever want to talk about this or other Subscription Platform issues in Real Time (tm).

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Zach for the helpful video explaining your thoughts on this.

Like Barry, I definitely appreciate your thinking about what may be the simplest thing to do to help users. Certainly showing a message on the existing page is one option. We might also want to disable the submit button on the form.

Barry made a good point that we might not want to show the form at all in this case. Perhaps we can use the same page, but instead of showing the form, we could have the message (and the signin link) in that same, central area?

We can discuss this more sync at our check-in later today as well.

**Comment by data-sync-user** [comment]
➤ Zachery Sutton commented:

Thanks, Barry Chen and Bianca Danforth  , for your awesome feedback and suggestions! I have updated the design for us to look over in our sync today. See you in a few!

**Comment by data-sync-user** [comment]
➤ Zachery Sutton commented:

Hi Chris Rooney here is a link to the updated design. You should have edit rights to add your copy in. If you run into any issues please let me know.

Figma File  ( https://www.figma.com/file/ARS3HjtJZBOdfBNvjnK5vl/Already-created-a-password?node-id=0%3A1 )

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Wow I posted to the wrong ticket last week; please see this comment in https://mozilla-hub.atlassian.net/browse/FXA-3656?focusedCommentId=463343 ( https://mozilla-hub.atlassian.net/browse/FXA-3656?focusedCommentId=463343|smart-link )  for an existing screen we could leverage here with different copy.

**Comment by data-sync-user** [comment]
➤ Zachery Sutton commented:

Hi Bianca Danforth ,  no worries all good! I added some placeholder copy in the design.

!image-20210927-202010.png|width=66.66666666666667%!

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Should we move this to Chris Rooney as the assignee? Looks like he’s up next.

**Comment by data-sync-user** [comment]
➤ Brian Yee commented:

Lower priority edge case.  Assume user can use a forgot password link if they can’t log in. - can be behind FXA-3655

**Comment by data-sync-user** [comment]
➤ Chris Rooney commented:

Zachery Sutton 

Header: You've already created a password
Body: Your Firefox account already has a password.
CTA: Forgot password?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Moving back to To Do since the bug hasn’t been fixed.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
