### ISSUE TITLE
[fxa-content-server] Add pairing test for unverified sesions

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1020]
ref https://github.com/mozilla/fxa/pull/949/files

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-73)
┆Issue Number: FXA-73

**Comment by vbudhram** [comment]
from mtg:

@vladikoff were you working on this, can you triage?

**Comment by vbudhram** [comment]
"Nah" - Vlad probably
