### ISSUE TITLE
[fxa-content-server] In pairing, instead of going to CAD go to Sync Signin in all cases

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1021]
Ref: https://github.com/mozilla/fxa/pull/949#discussion_r280811299

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-74)
┆Issue Number: FXA-74

**Comment by vbudhram** [comment]
from mtg:

@vladikoff were you working this, can you triage?

**Comment by vbudhram** [comment]
Looks like this was fixed https://github.com/mozilla/fxa/blob/3f5ea06792c07db3f3ce54964a67d4274e166477/packages/fxa-content-server/app/scripts/views/pair/index.js#L43
