### ISSUE TITLE
Get Storybook to reload stories when SCSS, FTL, other files change

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10216]
Currently Storybook does not update when changes to email files (SCSS, FTL, even JS template files) are modified. The solution right now is to use nodemon and restart Storybook entirely, but this is very heavy-handed and time consuming.

Find a way to get Storybook to force reload just the active story when a file is modified/recompiled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3884)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

I’m stuck with this. I started by asking in a few spots:

  * https://github.com/storybookjs/storybook/discussions/15873 ( https://github.com/storybookjs/storybook/discussions/15873|smart-link ) 
  * https://stackoverflow.com/questions/68822257/watch-and-reload-storybook-when-specific-files-change ( https://stackoverflow.com/questions/68822257/watch-and-reload-storybook-when-specific-files-change|smart-link ) 

No dice (yet).

I also attempted to roll my own file-watching websocket setup that Storybook listens to and force reloads on file change: https://github.com/mozilla/fxa/compare/jh/storybook-reload?expand=1 ( https://github.com/mozilla/fxa/compare/jh/storybook-reload?expand=1|smart-link ) 

This works to the extent that the story reloads, but for some reason it’s still not updating the story contents.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
