### ISSUE TITLE
Set up MJML server for deployed auth-server Storybook builds

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10218]
FxA has a mechanism for building and deploying our Storybook instances, however auth-server’s Storybook relies on a separate server to render and return compiled MJML/ERB templates. Locally this is accomplished with `yarn storybook-mjml`, which starts the server and Storybook. However when deployed it’s just a static Storybook build, no server.

Set up the MJML server, or find an alternate way for the static Storybook builds to render and display MJML/ERB templates.

Additionally, remove references to `localhost` when building for deployment, if there's an env var we can check or some straightforward way. This could be done in a separate ticket if preferred, or we can just change all `localhost:3030` references to `accounts.firefox.com`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3886)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

{quote}find an alternate way for the static Storybook builds to render and display MJML/ERB templates.{quote}

FWIW, I think that’s what will need to be done here. The little server I prototyped is only intended for local dev machines and not for any kind of external deployment. For a static storybook build, we’d need to do a static rendering of all the templates. It could be possible to come up with a webpack plugin that builds a list of templates from stories and renders them out as static files

**Comment by Yogita98** [comment]
@jodyheavener @LZoog I can try to look into this if it isn't already picked up

**Comment by jodyheavener** [comment]
Thanks @Yogita98! This was stumping me yesterday, so if you've got an idea I'd love to see it :)

**Comment by Yogita98** [comment]
Hey @jodyheavener 
I did a little digging into a few webpack plugins and how we can create one to solve this issue. Do we want to handle fluent localization and ejs compile step as well as part of that plugin? I came across a[ mjml plugin](https://github.com/tdeNL/tde-webpack-mjml-plugin) and it's loading the file and exporting final html contents. We could extend this and add ejs compilation and fluent localization in it or we can make use of [mjml-browser](https://www.npmjs.com/package/mjml-browser) package. The only downside of using this package is that we won't be able to use `<mj-include>` tags as mentioned in the docs. However, we could probably overcome that with the help of [juice](https://github.com/Automattic/juice) library. Basically, we can look for the `<mj-include>` components in the file, extract the name of the stylesheet from it, and pass it down to juice. Juice will load the file and inline the styles wherever required. Let me know which approach do you think would efficiently handle this problem.

**Comment by jodyheavener** [comment]
Sorry for the delay @Yogita98!

That first option sort of sounds like what we're doing with the `write-emails` commands, no? It's just compiling it down to static HTML? If so, that sounds like what we may need to do. The unfortunate thing is that we then lose the ability to fiddle with controls in Storybook and it's no longer dynamic.

mjml-browser looks promising and I would probably try that one first :)

**Comment by Yogita98** [comment]
Apologies for not being able to make any progress on this issue, we had a long festival going on here in India. I'll go through all the new changes, update my fork and update you with a PR soon!
