### ISSUE TITLE
Add subscriptions server to fxa-dev for test deployments

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1024]
So we can test the subscriptions functionality, we will need to add the subscription server to fxa-dev so that it is deployed along with the rest of the stack.

**Comment by clouserw** [comment]
We need to clarify which server this is talking about.  Subhub or the payment pages server?  Or probably should be both, I guess :)

**Comment by shane-tomlinson** [comment]
> We need to clarify which server this is talking about.  Subhub or the payment pages server?

Payments pages at a minimum, and something it could talk to that simulates Suhub. We could use the same approach we use with Basket and have a fake-Subhub server running for testing purposes, the server could be generated using it's OpenAPI spec.

**Comment by clouserw** [comment]
There is another issue open for subhub, so we'll say this one is for payments pages and is done.
