### ISSUE TITLE
[subplat] Users with passwordless accounts are asked for a password from “Already a subscriber?” button

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10258]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.213.5;

**Prerequisites**:

* Be in a country where the Mozilla VPN is available;
* Have a passwordless account with subscription;

**Steps to reproduce**:
1. Go to https://www-dev.allizom.org/en-US/products/vpn/ and click on the “Already a subscriber?” button;
2. Enter the email address used for the passwordless account from the prerequisites, and then click on the “Continue” button;
3. Observe the behaviour;

**Expected result**:

* The user should be redirected to the “Create Password” form and then redirected to the Download page. 

**Actual result**:

* User is asked to enter the password for the passwordless account.

**Notes**:

* If the user is entering a password, the “Authorize this sign-in” prompt is displayed and an authorization code is received on email. After entering the authorization code, an “Invalid password” red banner is displayed, and the user is redirected to the sign-in prompt.
* See the attached video.

[^Screen Recording 2021-08-25 at 14.41.56.mov]

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3908)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16117/Screen+Recording+2021-08-25+at+14.41.56.mov">Screen Recording 2021-08-25 at 14.41.56.mov</a>

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks for filing. Madalin Cotetiu , Can you confirm for the prerequisites that the account is unverified at this point (I am assuming as much from your expected results).

I’m not sure I agree with what the expected results should be here. At this point, for an unverified account, we don’t yet know if this email address is owned by this user, so we wouldn’t want someone who doesn’t come from an email link to be able to set a password for that stub account.

This issue was raised in Slack ( https://mozilla.slack.com/archives/CG0AJ6E77/p1626129051050800 ) as well, and we have a support article that we can direct users to thanks to FXA-3725. We can also direct users to check their email in case they did receive a “Finish Setup” email, though that raises the security question I mentioned in my previous comment. I think we should talk about this at the next design check-in. CC Zachery Sutton

**Comment by madalincm** [comment]
Yes, the account from the prerequisites is unverified (passwordless) at that point.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Hi Brian Yee - after discussing with engineering and design I feel that this is very much an edge-case and we should likely consider wont-fixing. As can be seen in the linked ticket, we do have SUMO articles explaining the next steps for users impacted here. If you can provide some product metrics showing this is not an edge case, that would be helpful, if not I would suggest we won’t fix.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per Benjamin Bangert , this is intended and expected behavior. To meet the “expected results” here would actually present a security issue. With this in mind, we will wontfix this issue - thank you for filing!
