### ISSUE TITLE
Better handling for when a user tries to click get mozilla vpn and already has a subscription.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10270]
As a user if I have a Mozilla VPN subscription and am signed in on the web (not browser) and click “get 12 month” subscription when I already have a 12 month subscription I am taken to a screen that says “this subscription plan change is not supported”. and the only call to action is manage my subscription. 

Can we change the copy if a user is selecting a plan they already have to something more contextual? Also if a user already has a subscription can we add a call to action to download the VPN client as well as manage my subscription.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3910)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
