### ISSUE TITLE
Relax content-server's navigation-timing endpoint payload validation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10272]
The validation errors are causing a ton of Sentry error reports.  Let's make the validation less strict and just not send timing stats if the payload doesn't have the correct data.

The error is often "ValidationError: child “domainLookupStart” fails because [“domainLookupStart” must be larger than or equal to 0]"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3914)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
