### ISSUE TITLE
[Train 136] [Win] "Page not found" if we click on "Turn on Sync" from toolbar

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1027]
Environment:
Platform: Win 10x64
Build: Nightly 68.0a1 (2019-05-05) - stage server [Train 136]

Steps to reproduce:
1. Launch Nightly and go to the Firefox account icon from the toolbar.
2. Click on the avatar.
3. Click on "Turn on Sync".

Expected results: "[Sign in to continue to Sync](https://accounts.firefox.com/signin?service=sync&context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email)" page is displayed.

Actual results: Page not found.
![Screenshot_7](https://user-images.githubusercontent.com/24588037/57231673-a40d1d80-7023-11e9-9d48-0d1743cf17a0.jpg)

Note: not reproducible on production.

**Comment by vbudhram** [comment]
from mtg:

@vbudhram will try to replicate this bug.

**Comment by vbudhram** [comment]
@SorinaFlorean I could not replicate this locally. The url that is opened from the toolbar menu is 

`https://accounts.stage.mozaws.net/?service=sync&context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email`

What configuration value are  you using to launch the stage environment?

**Comment by SorinaFlorean** [comment]
Sorry for the late reply here.  
![Screenshot_8](https://user-images.githubusercontent.com/24588037/57753714-8744aa00-76f5-11e9-9911-f0ec2a79c496.jpg) here are the stage settings.

**Comment by vbudhram** [comment]
@SorinaFlorean I believe the config `identity.fxaccounts.remote.root` should be `https://accounts.stage.mozaws.net` for the stage environment. Can you give that a try?

**Comment by SorinaFlorean** [comment]
Tested again and updated the config and the page was displayed. Closing this issue based on the new findings. Thanks, @vbudhram!
