### ISSUE TITLE
Set LOG_LEVEL for stage fxa-auth-server to 'debug'

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10287]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3918)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

One of the complicating factors for debugging https://mozilla-hub.atlassian.net/browse/FXA-3865 ( https://mozilla-hub.atlassian.net/browse/FXA-3865|smart-link ) was that part of the issue was configuration re: SNS message filtering for Basket (the service that handles our newsletter subscriptions).

Since we don’t log beyond 'info' and 'error', I couldn’t verify that the 'newsletters:update' event ('debug') was being pushed to SNS from the auth server (see this comment ( https://mozilla-hub.atlassian.net/browse/FXA-3865?focusedCommentId=453810 )).

Being able to look up debug level logs for fxa-auth-server stage in BigQuery would have helped, and I'm sure there are other situations where these logs would be helpful as well.

**Comment by biancadanforth** [comment]
Closed via https://github.com/mozilla-services/cloudops-deployment/pull/4372.
