### ISSUE TITLE
[L10n] Refresh status button from 'Account recovery' not translated in Polish/Polski

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1028]
Build: Release 66.0.2;
Devices: iPhone SE	(12.1.4);

Prerequisites:
Your FF is set on Polish / Polski language;

Steps to reproduce:
1. Go to https://accounts.firefox.com/settings;
2. Tap on the 'Enable' button from the Account recovery line;
3. See the behavior;

Expected results:
The 'Refresh status' button is translated into Polish;

Actual results:
The 'Refresh status' button is not translated;

Note:
- Also, the Refresh button from Devices & apps is not translated;

**Comment by vbudhram** [comment]
from mtg:

@flodolo Is there anything we can do to help resolve this issue?

**Comment by vbudhram** [comment]
@dannycoates to investigate this a little more.

**Comment by flodolo** [comment]
@peiying2 is the PM in charge of that project for localization

**Comment by flodolo** [comment]
Having said that, it was translated 9 days ago
https://pontoon.mozilla.org/pl/firefox-accounts/all-resources/?search=refresh&string=198154

I don't think there should be bugs filed for incomplete translations, but I'll leave the rest of the conversation to Peiying.

**Comment by dannycoates** [comment]
This is fixed in train-136
