### ISSUE TITLE
Create missing l10n files for hus, ixl, lus, meh, tl

### ISSUE THREAD

**Issue by mathjazz** [mozilla/fxa#10292]
L10n files and folders for the following locales [enabled in Pontoon](https://pontoon.mozilla.org/projects/firefox-accounts/) are missing:
* hus
* ixl
* lus
* meh
* tl

Pontoon is [unable](https://bugzilla.mozilla.org/show_bug.cgi?id=1728082) to create files and folders itself when the project contains a mix of monolingual (.ftl) and bilingual (.po) files, as is the case here.

The fix for this issue is to add 5 folders with the locale names listed above and set them up with empty .po files. Fluent files don't need to be added.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3922)

**Comment by clouserw** [comment]
I will move this issue to the FxA repository so it gets processed in our triage.  Thanks for filing.

**Comment by clouserw** [comment]
@jodyheavener this says it was assigned to you 2 days ago, but I don't see that you're actually assigned to it.  I also can't assign it to you, oddly...?  

It also doesn't have a link to jira in it.  So, I don't know what's going on, but let's not lose to track of it please.  /cc @chelsea-lewis
