### ISSUE TITLE
Alternative for Sentry JS stacktraces

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#1030]
From discussion earlier, Mozilla will be disabling Sentry with javascript source fetching. FxA uses this to help send exception stack traces. Some quick thoughts

* Is there an alternative we can use to get this information? 
* Do we use this?

**Comment by shane-tomlinson** [comment]
I personally find the Sentry stack traces more or less useless. There have been a couple of times they've been helpful, but on the whole, not so much.

**Comment by clouserw** [comment]
- Let's remove the client side source fetching

**Comment by clouserw** [comment]
@meandavejustice fixed our sourcemaps
