### ISSUE TITLE
If the account being deleted has subscriptions, immediately send subscription deletion related emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10305]
When an account of a subscription customer is deleted, send the subscription cancellation email(s) immediately.  By the time the Stripe webhooks arrive, we won't be able to find the account.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3929)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
