### ISSUE TITLE
Handle POSTing to invalid content server URL

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#10308]
The associated Sentry error is occurring because you can POST to an invalid URL and get a 500 error. It should just 404.

---

https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/11397125/?referrer=github_plugin

```
SyntaxError: Unexpected token u in JSON at position 1
  ?, in JSON.parse
...
(5 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3932)

**Comment by dannycoates** [comment]
Sentry issue: [FXA-CONTENT-SERVER-PROD-69M](https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/11422756/?referrer=github_plugin)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
