### ISSUE TITLE
Broadcast password change upon logout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10327]
The event-broker currently broadcasts a password-change event when it gets a FxA service notification event of either password reset or password change (https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/service_notifications.md). The course of action an RP must take after getting this is to remove the login sessions from before this event was seen.

When the new attached client disconnect event is received, the same password-change event should be broadcast so that RPs remove the current sessions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3940)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
