### ISSUE TITLE
Add Client Logout event

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10328]
The service notifications in FxA have a device disconnect, but no associated attached client disconnect (back-channel logout). A new event for client logout should be created and documented. It should be triggered on attached client disconnect in auth-server and broadcast the client logout event with the clientId.

Device disconnect:
[https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/service_notifications.md#device-disconnection-event](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/service_notifications.md#device-disconnection-event)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3941)

**Comment by clouserw** [comment]
dup of #9442 maybe

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
