### ISSUE TITLE
Show non-secret relying party information in the admin panel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10339]
Let's add a simple page to the admin panel that lists relying party information in a table.  Any non-secret information should be shown; off the top of my head: id, name, redirectUri, date added, date modified (if available), etc.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3943)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
