### ISSUE TITLE
Still receiving some mails to an address that is removed from account

### ISSUE THREAD

**Issue by Ludwigsfeld** [mozilla/fxa#10337]
## Description

I changed the primary email address and completely removed the old address on the account.
However, i still get some emails on that old and removed address.

### Steps to reproduce

Primary Email address A, Adding a secondary email address B. Changing Address B to primary Email Address. Deleting the old address A from account. Now there is only one primary email address B.

### Expected result

Receiving every kind of mail message to the primary email address B.

### Actual result

Still receiving some email messages to the old and already removed address A.

### Environment

Windows 10 20H2 , Firefox 91.0.2 (64-Bit).
![2021-08-30-03-27-57-973853](https://user-images.githubusercontent.com/73795103/131806930-13ea9bdd-411a-491d-83e4-36ba9d477939.png)
![Unbenannt](https://user-images.githubusercontent.com/73795103/131807517-5d9e7502-f5d8-406d-922b-3d71a9393a46.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3942)

**Comment by dannycoates** [comment]
Thank you for the report @Ludwigsfeld we are looking into it.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
