### ISSUE TITLE
Update Sign-Out pop-up to indicate logouts are not immediate

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10340]
When clicking sign-out on a service in the Connected Services section of the Settings page, we indicate you have been logged out of the service. However, for relying parties purely for SSO purposes, they may not talk to FxA for the duration of the access tokens validity (6 hours). This means that the user is not logged out of the service immediately, but it can take up to 6 hours.

The pop-up should take into account access token expiration to clearly indicate the sign-out takes time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3944)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
