### ISSUE TITLE
Support Panel 500 error: "event.request.query_string.replace is not a function"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10353]
See https://sentry.prod.mozaws.net/operations/fxa-support-panel-prod/issues/12843850/

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3950)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
