### ISSUE TITLE
[subplat][firestorecleanup] Delete feature flag and metadata conversion script

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10365]
Once the feature’s been successful in prod, clean up by removing the feature flag and the metadata conversion script.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3962)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
