### ISSUE TITLE
[subplat][firestorecleanup] Remove the product and price metadata in Stripe

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10360]
This can be a manual process, to be done _after_ production’s been using Firestore docs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3958)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

This is optional - it will no longer be leveraged by SubPlat

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
