### ISSUE TITLE
Audit Stripe webhook handlers to ensure we are not ignoring legitimate errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10367]
This came up in FXA-3777 (see [this comment](https://github.com/mozilla/fxa/pull/10351#discussion_r701935013)).

I noticed some of our webhook handlers have their own `try..catch` block and others don't. For those that do, are we correctly rethrowing legitimate errors? E.g. [handleInvoicePaidEvent](https://github.com/mozilla/fxa/blob/7078624f185784f0cbfacfcdfe84660bd09a3121/packages/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.ts#L399-L402) only logs the error to Sentry without rethrowing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3963)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
