### ISSUE TITLE
Password Strength Bubble Not Displaying the Latest

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1036]
I currently see this password strength bubble:

![image](https://user-images.githubusercontent.com/19537086/57331654-facf3180-70cd-11e9-8d06-0487c76cca78.png)

However, @ryanfeeley had designed these ones that we were supposed to roll out. (can't find bug anymore)

![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/7aa4f077-d28f-45bb-b877-27e362de0570)

![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/f80616af-fdb9-4958-a8ec-8db7feb5d15d)

If this is a dupe, please close it. Ryan recently mentioned how we still display the wrong password strength bubbles but I can't find anything open regarding updating them.

**Comment by davismtl** [comment]
@ryanfeeley please provide the missing design details. (I'm sure I'm forgetting many)

**Comment by shane-tomlinson** [comment]
This is a dup of #607
