### ISSUE TITLE
Delete Unverified Accounts After X amount of days

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1038]
Alicia Gray has requested that we look into deleting unverified accounts after x amount of days. (x to be period)

We currently send reminder emails but likely after 1 month, they will not answer. We should not keep these emails.

Let's look at cleaning up existing records and automating it moving forward.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-76)
┆Issue Number: FXA-76

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Unclear how much space saving this would give us. Users who attempt to create an account from an unverified account gets sent a new email.
