### ISSUE TITLE
[subplat][2fa-reset] Create DB migration for 2fa reset requests table

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10387]
The table should have the following columns:

* id: a UUID to identity the request
* uid: the UID of the user whose 2FA device is being reset
* email: the email address the user used to request the reset
* amountA: random number 0.01 - 0.99
* amountB: random number 0.01 - 0.99
* createdAt: a timestamp of when the request was first created by the support agent
* updatedAt: a timestamp of when the request was last updated
* haltedAt: a nullable timestamp of when the request was halted by the user

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3969)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
