### ISSUE TITLE
[subplat][2fa-reset] Add a new endpoint to the auth-server to send an email to the user to give them the option to halt the reset process

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10393]
* The endpoint should use the shared secret between the auth-server and the Support Panel to authenticate the request.
* The endpoint will insert a new record into the 2fa reset requests table.
* The JWT should contain the reset request's UUID.
* The link goes to a page on the content-server.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3975)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
