### ISSUE TITLE
[subplat][2fa-reset] Update Support Panel integration in Zendesk to pass in the email address of the customer

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10390]
This is a configuration task to be performed by whoever has admin access to Zendesk.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3972)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
