### ISSUE TITLE
question on fxa-customs dataflow subscription pattern

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1039]
Excuse me if I garble the terminology. The customs server currently sets up like so:
```
   const { PubSub } = require('@google-cloud/pubsub')
   const pubsub = new PubSub({ projectId })
   const subscription = pubsub.subscription(subscriptionName)
   subscription.on('message', fn)
   subscription.on('error', fn)
```
to connect to an existing subscription to the dataflow topic.

Q. Is the intent for the dataflow notifications to be distributed among all the customs-server round-robin-ish, or for each customs-server to get each dataflow notification. I think we're currently doing the former.

**Comment by shane-tomlinson** [comment]
> Is the intent for the dataflow notifications to be distributed among all the customs-server round-robin-ish

The former, the messages only need to be processed once.
