### ISSUE TITLE
[subplat][2fa-reset] Add a new content-server page to send the halt request and display a confirmation to the user

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10396]
This is the page linked in the email to the user

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3978)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
