### ISSUE TITLE
[subplat][2fa-reset] Update the Support Panel to display a list of 2FA reset requests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10392]
Display the user's 2FA reset requests, the random amounts, and their halt status in reverse chronological order.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3974)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
