### ISSUE TITLE
Bring back about:accounts testing with marionette

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#104]
We had some tests before, we should bring those back. 
- Signup
- Signin 

for starters

**Comment by vladikoff** [comment]
Blocked by 

https://github.com/jgraham/wires/issues/46 

and 

https://bugzilla.mozilla.org/show_bug.cgi?id=1244761

**Comment by vladikoff** [comment]
Some code that works with Stable today https://github.com/vladikoff/fxa-sync-e2e but not the whole e2e flow yet due to bugs above.

**Comment by vladikoff** [comment]
need to add context

**Comment by vladikoff** [comment]
There seems to be some progress in https://github.com/jgraham/wires/tree/profile I will see if we can start using that and unblock this.

**Comment by vladikoff** [comment]
Did some updates to this, this is now blocked by https://github.com/jgraham/wires/issues/46#issuecomment-215889883

**Comment by vladikoff** [comment]
thanks to people in #automation we finally figured it out:

Instead of using geckodriver we should just use the `firefox-ui-functional` command. 

Steps to remember:

* Download Nightly and `common.tests.zip` for that same build
* do the `virtualenv` dance, `cd config` in the common zip and run `pip install -r firefox_ui_requirements.txt --no-cache-dir
` 
* run:

> firefox-ui-functional firefox-ui/tests/functional/locationbar --binary /Users/vladikoff/Desktop/firefox-51.0a1.en-US.mac.common.tests/FirefoxNightly.app/Contents/MacOS/firefox-bin

* if that works, substitute existing tests with our new tests.

**Comment by shane-tomlinson** [comment]
This sounds complex. Can we automate it?

**Comment by vladikoff** [comment]
> This sounds complex. Can we automate it?

Yeah, that's the plan :) but at least we don't have to check out `moz central`

**Comment by vladikoff** [comment]
```
there is --profile to select a profile, 	otherwise try --help

```

**Comment by vladikoff** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1287904

**Comment by shane-tomlinson** [comment]
I tried using Marionette again last week, with much more success than previously. Two problems remained:

1) Using Fx 49, when the browser starts, I had to manually click into the URL bar and type `about:` for the tests to start.
2) The real `Raven` still causes failures, I had to use `RavenMock` from https://github.com/mozilla/fxa-content-server/compare/shane-tomlinson/marionette-geckodriver?expand=1.

**Comment by vladikoff** [comment]
Sorry this issue is different, this is for about:accounts tests, not Selenium tests. Copying your comment into there: https://github.com/mozilla/fxa-content-server/issues/3995

**Comment by vladikoff** [comment]
to unblock the marionette bug we should use the `https://accounts.firefox.com/signin?context=fx_context_v3&service=sync` and just navigate straight to the website.

**Comment by vladikoff** [comment]
This is now live at https://github.com/mozilla-services/fxa-testing-e2e and https://circleci.com/gh/mozilla-services/fxa-testing-e2e
