### ISSUE TITLE
Remove any payment information for detached payment methods

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#10409]
[https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/12974112/?referrer=github_plugin](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/12974112/?referrer=github_plugin)

```java
WError: An internal server error occurred
  ?, in runMicrotasks
```

`Error: No such PaymentMethod: 'card_1H89ABJNcmPzuWtRXaKMkquD'`

The backend in this case should not error and instead return an error message to the front-end that there's no payment method attached so that the user can be alerted to change the card information.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3983)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

If payment deteched, remove anything from our end, do not send back to stripe.
