### ISSUE TITLE
[subplat] "Error: Account already exists" for new passwordless flow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10400]
Referencing this and similar errors: [https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/12679965/](https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/12679965/)

[FXA-3486] created a new subscription flow that creates a Firefox account at the same time as creating a subscription. Just after we deployed this new feature to production (8/25), we started getting some "Account already exists" errors in Sentry.

This is because (at least in part) it's possible to submit the form  with an unverified account that has an active subscription. This causes the `/account/stub` endpoint to [throw the error](https://github.com/mozilla/fxa/blob/8ceeb57b322f15c60a72ac833d41ef0c792fbe75/packages/fxa-auth-server/lib/routes/account.ts#L91-L99). We should fix this.

- - -
**STR**

1. With an email unassociated with an FxA account, sign up for a subscription using the new passwordless flow.
  1. Note the email address used.
1. Refresh the page to reload a blank passwordless sign up form.
1. Enter the same email address from Step 1 into both email fields.
  1. Note the white on red “You already have an account. Sign in” toolbar message.
1. In the first email field, replace the last character with another different alphanumeric character. E.g. “22@22.2” becomes “22@22.3”.
1. Without blurring the first email field, Repeat step 4 but replace the last character with another, different alphanumeric character. E.g. “22@22.3” becomes 22@22.4”.

Expected:

* Email fields don’t match, so receive an e-mail field’s don’t match error tooltip, and submit button is disabled.

Actual:

* No tooltip error message is displayed, and the submit button is enabled.

- - -
Quoting myself from Slack:
> ...if a user manages to resubmit the payment form after already signing up (it shouldn't be possible, but it is currently if you copy/paste your email in quickly via the keyboard), `/account/stub` will throw in `deleteAccountIfUnverified`, since the [email is primary, unverified, but has an active subscription]([https://github.com/mozilla/fxa/blob/8ceeb57b322f15c60a72ac833d41ef0c792fbe75/packages/fxa-auth-server/lib/routes/account.ts#L91-L99)](https://github.com/mozilla/fxa/blob/8ceeb57b322f15c60a72ac833d41ef0c792fbe75/packages/fxa-auth-server/lib/routes/account.ts#L91-L99)).

> I think the problem is that we are [debouncing the check that the account exists](https://github.com/mozilla/fxa/blob/8ceeb57b322f15c60a72ac833d41ef0c792fbe75/packages/fxa-payments-server/src/components/NewUserEmailForm/index.tsx#L72-L75), so if the first email field can be updated quickly enough (<300ms currently) after the last check, we miss it.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3980)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
