### ISSUE TITLE
Payments front-end should handle card not attached error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10410]
If the front-end gets an error when attempting an invoice retry that there's no payment method, it should ask the user to update the card shown and attach the payment method before retrying the invoice.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3982)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
