### ISSUE TITLE
Allow users to revoke signup from verification email

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1042]
There are probably some number of accounts that are created by people who do not own the address being signed up for, e.g., bots, attackers. Adding a link to the email that allows users to immediately revoke the signup would allow us to immediately delete the account as well as provide additional signals to customs/dataflow to minimize fraud.

ref #1038 as part of the same discussion

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-77)
┆Issue Number: FXA-77

**Comment by clouserw** [comment]
There will be some trade off to complexity of our emails (eg. will people click the wrong link?  or give up reading more text?).  Marking needs:ux to either support or close this.
