### ISSUE TITLE
Inconsistent entrypoint parameter logging. 

### ISSUE THREAD

**Issue by YeonjooSmith** [mozilla/fxa#10431]
## Description
1. There is a huge traffic with unspecified entrypoint coming from the VPN product site. 
2.  Through the FxA funnel, for some events, entrypoint is logged and for some other events it is missing. I found a case where one event_type was repeated twice, one time with entrypoint and the other time without.  @vbudhram 
(refer to the example with flow_id ='0ac878035bb633a99ccdacd0a8cf8d08f422bf92e93e1def63b69685a8d3e438' in the notebook.)
<img width="484" alt="Screen Shot 2021-09-13 at 5 28 45 PM" src="https://user-images.githubusercontent.com/49305857/133158919-45015281-8e93-4be9-9d95-36951d9c49d7.png">

### Steps to reproduce
[This notebook includes the clear steps with the examples](https://colab.research.google.com/drive/1GbKrk3lspmECBrwL9iNUJTau318cYMSI?usp=sharing)
Clear steps describing how to reproduce the issue. Providing a URL, screenshot.
Step 1. Found flow_ids that have a missing entrypoint at any step of the FxA funnel.
Step 2. Found flow_ids that have an entrypoint at any step of the FxA funnel.
Step 3. Inner join two sets: A set of flow_ids that have missing entrypoint for some but not all steps during the FxA funnel.
Step 4. Query the events with the flow_ids then sort them by the order of events using timestamp.

### Expected result

What should happen?
When the entrypoint is passed from the VPN service, it should consistently appear throughout FxA Funnel. 
### Actual result
Included in the description

### Environment

What browser and operating system are you using?
Firefox Nightly and Mac OS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3990)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

This might be fixed with the incoming P2 metrics bug for passwordless flows.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
