### ISSUE TITLE
Allow users to revoke signins from verification email

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1043]
Similar to #1042, but for signins.

Adding a link to the verification email that allows users to immediately revoke a signin would allow us to immediately revoke the session and any related tokens as well as provide additional signals to customs/dataflow to minimize fraud.

ref #1038 as part of the same discussion

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-78)
┆Issue Number: FXA-78

**Comment by clouserw** [comment]
There will be some trade off to complexity of our emails (eg. will people click the wrong link?  or give up reading more text?).  Marking needs:ux to either support or close this.
