### ISSUE TITLE
Prune expired OAuth codes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1044]
OAuth authorization codes are only valid for [15 minutes](https://github.com/mozilla/fxa/blob/bb2730009d581d35a8a4939c2a92bd83d18ba874/packages/fxa-auth-server/fxa-oauth-server/lib/config.js#L148). As a way of keeping the DB tidy, we should prune tokens that have expired.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-79)
┆Issue Number: FXA-79

**Comment by clouserw** [comment]
Much of the `prune tokens` script could be reused here to prune codes

**Comment by jrgm** [comment]
There is no actual expiresAt timestamp on `codes` rows. I suppose use `createdAt` + 15 minutes?

**Comment by clouserw** [comment]
That makes sense

**Comment by shane-tomlinson** [comment]
createdAt + 15 minutes seems reasonable. That's exactly how the [/token endpoint determines whether an authorization code is valid](https://github.com/mozilla/fxa/blob/e3be7a6f31a6071673fd33aa9e066f9b85314bb8/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js#L296).
