### ISSUE TITLE
Support multiple redirectURIs per Relying Party

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1045]
We currently only allow RPs to specify a single redirectURI. As part of the Lockbox->Lockwise name transition, the team would like to change redirectURIs while keeping the same client_id. One way to do this would be to allow a 2nd redirectURI to the list of allowed redirectURIs for a transition period while folks are updating their apps, and after the transition period is over, remove the original.

The DB stores [redirectUri as a VARCHAR(256)](https://github.com/mozilla/fxa/blob/768d1145761d6d3463b226d388a89d237c891a64/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/schema.sql#L16), and the check for the match in the /authorization route [is done here](https://github.com/mozilla/fxa/blob/768d1145761d6d3463b226d388a89d237c891a64/packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorization.js#L218).

The content server [does a similar check](https://github.com/mozilla/fxa/blob/768d1145761d6d3463b226d388a89d237c891a64/packages/fxa-content-server/app/scripts/models/reliers/oauth.js#L234) but then [builds it's OAuth redirectUri](https://github.com/mozilla/fxa/blob/768d1145761d6d3463b226d388a89d237c891a64/packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js#L149) based on the redirectUri passed in via the query parameters.

If we allowed the stored redirectUri to be a comma separated list of URIs, we could achieve this functionality w/o too much fuss. VARCHAR(256) might be a bit short to allow for more than a couple URIs, though the clients table is small and enlarging this column should not be much trouble if we ever find we need to.

We should use exact matches, if the specified redirectUri matches any of those provided, then allow it. We would probably not want to go full pattern matching, there are a [bunch of gotchas](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-12#section-4.1.1).

If multiple redirectUris are allowed and none is specified in the /authorization request, use the first registered URI as the default.

For good background info on securing a redirect flow, see [the latest OAuth Best Common Practices draft](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-12#section-3).

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1547323

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-80)
┆Issue Number: FXA-80

**Comment by shane-tomlinson** [comment]
cc @linuxwolf, @rfk

**Comment by clouserw** [comment]
This is still something we want to do, but let's make it space separated instead of comma.  See https://github.com/mozilla/fxa/issues/5488

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm marking this our lowest priority as there are no  teams that are requesting this right now.
