### ISSUE TITLE
[subplat] “Send” button from Contact Support form is disabled when a text is entered by “Paste” click option 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10460]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.215.1;

**Prerequisites**:

* Be in a country where the Mozilla VPN is available;
* Have an FxA account with an active subscription for Mozilla VPN;
* Be on Subscription Management page;

**Steps to reproduce**:
1. Click on the “Contact Support” button;
2. Complete all mandatory fields, except for the “Description of issue” text field.
3. Paste a text in the description field using the right-mouse click option;
4. Observe the behaviour;

**Expected result**:

* The “Send” button becomes active.

**Actual result**:

* The “Send” button stays inactive.

**Notes**:

* If you edit the inserted text, the button becomes active;
* If you press “Ctrl+V” the button becomes active;
* See the attached video.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3997)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16466">2021-09-16_16h18_51.gif</a>

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

My suspicion is we may be listening for keyboard events but not the onPaste or similar event that fires when text is pasted from the clipboard.

Do we enable the button onBlur? We should check to see if there’s content in the Description field and enable the button in that case (assuming the other fields are complete and valid).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
