### ISSUE TITLE
[subplat] “Subscribe now” button from Set up your subscription page is enabled for incomplete billing details

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10467]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.215.1;

**Prerequisites**:

* Be in a country where the Mozilla VPN is available;
* Be on the new Set up your subscription page;

**Steps to reproduce**:
1. Complete all mandatory fields, except for the “ZIP” text field;
3. Copy the card number entered in the field;
4. Delete the card number;
4. Paste the card number into the field;
5. Observe the behavior;

**Expected result**:

* The “Subscribe now” button is disabled.

**Actual result**:

* The “Subscribe now” button is enabled without introducing a ZIP code. No banner is displayed informing the user that the ZIP code needs to be entered.

**Notes**:

* If you press on the “Subscribe now” button, “Error confirming subscription...Something went wrong. Please try again later” screen is displayed;
* Reproducible on the old Set up your subscription as well;
* See the attached video.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3999)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16476">Screen Recording 2021-09-17 at 08.47.50.mov</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21806">Screen Recording 2022-03-18 at 09.37.33.mov</a>

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Thank you for the head up Anna Sobiepanek We will take a look at this as soon as posible.

CC: Bianca Hidecuti Madalin Cotetiu

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Anna Sobiepanek , I am still able to reproduce this issue on Train 1.228.1 - Staging, on both old and new subscription flow.

Attaching a video. 

!Screen Recording 2022-03-18 at 09.37.33.mov|width=1918,height=1176!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
