### ISSUE TITLE
expose reset and passwordChange events to AMO's sqs queue

### ISSUE THREAD

**Issue by eviljeff** [mozilla/fxa#10468]
to implement https://bugzilla.mozilla.org/show_bug.cgi?id=1730485 AMO needs 2 additional events added to the existing SQS queues that amo uses - `reset` and `passwordChange`

we use the following queues:
https://sqs.us-east-1.amazonaws.com/927034868273/amo-account-change-dev 
https://sqs.us-west-2.amazonaws.com/361527076523/amo-account-change-stage
https://sqs.us-west-2.amazonaws.com/361527076523/amo-account-change-prod

The code on AMO consumes and ignores any unknown events so should be okay to expose them straight away, but to be safe, please hold off on `amo-account-change-prod` until everything has been QA'd on dev/stage first.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4000)

**Comment by jbuck** [comment]
Done for stage

**Comment by eviljeff** [comment]
> Done for stage

Great.  I'll need https://sqs.us-east-1.amazonaws.com/927034868273/amo-account-change-dev too as it's the only one I have auth credentials to access, to do local development.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is there any more to do here? Jon Buckley

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

cc: Dustin Lactin perhaps could help here?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks.  We talked in the ops meeting and decided to close this.  Please let us know if there is any more to do.
