### ISSUE TITLE
Sentry Joi validation error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10491]
https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/6602579/events/98263991d5bb49539d8ceb6e1d5511fc/

```
ValidationError: child "domainLookupStart" fails because ["domainLookupStart" must be larger than or equal to 0]
```

http://accounts.firefox.com/navigation-timing

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4007)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
