### ISSUE TITLE
fxa repo doesn't run npm test correctly and fails tests

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1049]
The README instructions do not work as written. This appears to be because several of the packages repo do not have npm install run in them. There's a separate issue with fxa-oauth-console needing a package downgrade to work correctly due to gulpjs/gulp#2280.

Steps taken to fix:
* Add the following lines to `_scripts/install_all.sh`:
  ```
   cd fxa-js-client; npm ci; cd ..

   cd fxa-customs-server; npm ci; cd ..

   cd fxa-oauth-console; npm ci; cd ..

   cd fxa-payments-server; npm ci; cd ..
   ```
* Then `cd packages/fxa-oauth-console` and `npm install natives@1.1.6`.
* Running `npm test` then runs the tests correctly, though two fail.

The failing tests:
```
  11 passing (5s)
  2 failing

  1) fxa-geodb
       returns an object with location data when supplied with a valid ip address:

      City returned correctly
      + expected - actual

      -Mountain View
      +San Francisco
      
      at Context.it (test/fxa-geodb.js:45:12)

  2) fxa-geodb
       returns an object with partial location data when complete data is not available:
     AssertionError: Timezone undefined: expected 'America/Chicago' to equal undefined
      at Context.it (test/fxa-geodb.js:66:12)
```

I can make a PR for the scripts/_postinstall script fix, but I'm not sure the best way to fix the natives issue.

CircleCI does not appear to test that a 'normal setup' as described in the README actually works, should we have Travis or CircleCI validate that these commands run correctly?

**Comment by vbudhram** [comment]
```
  11 passing (5s)
  2 failing

  1) fxa-geodb
       returns an object with location data when supplied with a valid ip address:

      City returned correctly
      + expected - actual

      -Mountain View
      +San Francisco
      
      at Context.it (test/fxa-geodb.js:45:12)

  2) fxa-geodb
       returns an object with partial location data when complete data is not available:
     AssertionError: Timezone undefined: expected 'America/Chicago' to equal undefined
      at Context.it (test/fxa-geodb.js:66:12)
```

We have seen a similar issue before in https://github.com/mozilla/fxa-auth-server/pull/2611. In this case we could do [this](https://github.com/mozilla/fxa-auth-server/pull/2611/files#r215768286) and pull into a shared constant, or even just updating the IP in fxa-geodb to `63.245.221.198`.

> should we have Travis or CircleCI validate that these commands run correctly?

I think that might be worthwhile, and probably help new contributors as well.

**Comment by bbangert** [comment]
@vbudhram Just checking before I re-open this, I had meant to only reference it. As the test failure still exists. Should this be re-opened or a separate issue filed to fix the failing test?
