### ISSUE TITLE
Enable/verify PKCE flows

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10494]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4010)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Vijay Budhram is this to pick up their listening of our deletion events? I understand THAT is done per Daniel & https://getpocket.atlassian.net/browse/INFRA-94 ( https://getpocket.atlassian.net/browse/INFRA-94|smart-link ) if so; in which case, we need to determine…when will we do this? (I fully recognize I could be conflating issues here!) cc: Wil Clouser

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
