### ISSUE TITLE
Notify Basket whenever a user signs in to an OAuth Relying Parties with cached credentials

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1050]
I realized this morning that our solution in https://github.com/mozilla/fxa-auth-server/issues/2915 to notify the Mozmeao whenever a user signs into a service is incomplete. `login` events are only sent when a user has to enter their password, i.e., when /account/login and /session/reauth are called. A user that signs into Sync and then into Monitor calls neither of these endpoints and instead [uses the cached Sync credentials to generate OAuth credentials](https://github.com/mozilla/fxa/blob/6be0bd05351ed4641bf8d061d906a0e16560b399/packages/fxa-content-server/app/scripts/models/account.js#L480). We never notify Basket of the "login" because no actual FxA login occurs, just a Monitor "login".

It seems to make sense to notify Basket whenever a new access token is returned in a call to the OAuth server's /authorization endpoint or /token endpoint when an authorization code is traded for an access token or refresh token. @rfk, thoughts?

The wrinkle in this approach is that the OAuth server is not currently set up to emit events over SNS.

cc @pmac, @lniolet, @davismtl, @bbangert

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-81)
┆Issue Number: FXA-81

**Comment by rfk** [comment]
Good catch.

> It seems to make sense to notify Basket whenever a new access token is returned in a call to the
> OAuth server's /authorization endpoint or /token endpoint when an authorization code is traded
> for an access token or refresh token. @rfk, thoughts?

Agreed, I think this makes sense. There will be some amount of finessing to do, either on our side or in basket, to avoid "double counting" the cases where we do both a `/login` and a `/token` exchange.

**Comment by rfk** [comment]
I feel like we're moving towards the use of a log post-processing step to keep Mozmeao up-to-date, e.g. via the [daily export to CDP](https://bugzilla.mozilla.org/show_bug.cgi?id=1573359). With that in place, do we still need this kind of front-channel notification to basket?
