### ISSUE TITLE
[l10n] billing interval (planInterval) is not localizable 

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa#10545]
## Description
![圖片](https://user-images.githubusercontent.com/6090393/135139152-d4cb1542-7937-4a56-b7b9-a3b86a30d468.png)

Notice that `month` is in English
### Steps to reproduce

https://pontoon.mozilla.org/zh-TW/firefox-accounts/all-resources/?string=224251 this is the string used in the above screenshot. 

### Expected result

Make sure `(planInterval)` is not hardcoded or localizable somewhere.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4035)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
