### ISSUE TITLE
content-server Sentry prod body-parser errors - unexpected token in JSON

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10544]
These may be different errors / might call for separate issues once someone digs in, but these issues...

* https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/11422756/
* https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/11397125/

... error with Unexpected token : or t :, in the `body-parser` package with the console message "Proxy created: /  ~~> http://localhost:3000". I'm not sure why we're ever proxying from localhost in production or why that's getting logged, in `fxa~~content-server.js` we have the following:

```
  if (config.get('env') === 'development') {
    app.use(settingsPath, useSettingsProxy);
  } else {
    app.get(settingsPath + '/*', modifySettingsStatic);
  }
```

where `useSettingsProxy` has a target of `localhost:3000`.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4034)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
