### ISSUE TITLE
Allow "^" in package.json version numbers

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1055]
Most of our package.json files use hard coded versions of dependencies, eschewing ["^" and "~"](https://github.com/npm/node-semver#tilde-ranges-123-12-1), both of which allow updates to packages.

The PITA comes when installing new packages using `npm install --save`, npm automatically adds the `^` prefix, and we have to go remove it. Manually removing the "^" seems silly to me when we use npm-shrinkwrap and package-lock so that dependencies are the same for everyone.

This becomes even more silly when running `npm run shrink` because so many of our direct dependencies use `^` on their dependencies. Every invocation of `npm run shrink` causes a zillion sub dependencies get updated anyways. Why not let *our* direct dependencies update too when doing an `npm run shrink`?

**Comment by philbooth** [comment]
I'm in favour of this. And we already use `>=` for all the version strings in `Cargo.toml` in this repo, so there is local precedence.

**Comment by jrgm** [comment]
> ... using npm install --save, npm automatically adds the ^ prefix, and we have to go remove it.

`$ npm config set save-exact true`
https://docs.npmjs.com/misc/config#save-exact

**Comment by clouserw** [comment]
From meeting:  let's do it

**Comment by clouserw** [comment]
Is there work to do here?  This just seems like a policy change (that we've made).

**Comment by philbooth** [comment]
> Is there work to do here?

Is it worthy of an ADR? Otherwise no, we can close it.

**Comment by clouserw** [comment]
I don't recall there being much (any?) disagreement about it, and since it's there by default when using `--save` and we're moving to the default I don't think we need an ADR for it.  Thanks
