### ISSUE TITLE
Blue button text is "Click here" in all emails instead of "Manage account"/ "Create new password"/ "Set up next device", etc.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10586]
**Build:**
Stage (Train 1.216.0)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.8

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and log in using an existing account.
1. Go to “Secondary email” section and add a secondary email.
1. Enter an email address and click the “Save” button.
1. Verify your inbox for the verification code.
1. Copy the verification code and paste it in the field.
1. Click the “Verify” button.
1. Go to inbox and verify the "Secondary email added" email.

Actual result: 
The button text is "Click here" instead of "Manage account" in this case.

Expected result:
The button text is "Manage account" in this case.

**Note:**
This issue can be found in all emails that have a blue button.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4046)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16707/email+button+text+issue.PNG">email button text issue.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16706/pwdResetAccountRecovery.PNG">pwdResetAccountRecovery.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16705/Recovery+key+generated+email+issue.PNG">Recovery key generated email issue.PNG</a>

**Comment by LZoog** [comment]
commenting to cross-link: https://github.com/mozilla/fxa/commit/be131108421ea523403a98652f594d34fd025842#r57369209

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

NOTE: we thought we had this fixed, but it will actually be fixed when https://mozilla-hub.atlassian.net/browse/FXA-4372 ( https://mozilla-hub.atlassian.net/browse/FXA-4372|smart-link ) is closed this sprint. I would reopen this ticket since the bug isn’t fixed, but, then we’d have two tickets open for the same issue, so I’ll leave this one closed and just cross-link here instead. 🤷‍♀️

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on stage [Train 224.1] under Windows 10 64-bit.  The correct text is displayed on the button depending on the email sent.

!blue button emails - new situation.PNG|width=656,height=407!

!blue button emails - new situation2.PNG|width=625,height=464!

!blue button emails - new situation3.PNG|width=647,height=389!
