### ISSUE TITLE
Missing icons for MDN Plus product

### ISSUE THREAD

**Issue by escattone** [mozilla/fxa#10590]
### Issue

The MDN team is adding a product called MDN Plus, and we don't yet have any logo assets to use on the Fxa CDN.

### Success criteria:

- [ ] Add an SVG version of the MDN Plus logo.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4048)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Hey Ryan; we’re going to assign this ticket to you, since you’ve already opened a PR.
