### ISSUE TITLE
[subplat] Two different errors for currency mismatch depending on subscription flow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10598]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.216.0;

**Prerequisites**:

* Be in a country where the Mozilla VPN is available;
* Have an FxA account without a subscription and be signed in;
* Be on old Set up your subscription page;

**Steps to reproduce**:
1. Complete all the mandatory fields;
2. Use a card number number from a country with a different currency than the one you are in (example: 4000006420000001);
3. Click on “Subscribe now” button;
4. Observe the error message;
5. Sign out from this account;
6. Go to [homepage](https://www-dev.allizom.org/en-US/products/vpn/) and subscribe to Mozilla VPN using the new flow (same card number from step 2 - 4000006420000001);
7. Observe the error message;

**Expected result**:

* The error message displayed while subscribing through both flows is the same;

**Actual result**:

* “Error confirming subscription...The currency of this subscription is not valid for the country associated with your payment.” error message is displayed while subscribing through the old flow. 
* “Error confirming subscription...Something went wrong. Please try again later” error message is displayed while subscribing through the new flow. 

**Notes**:

* If using a card number from an unsupported country, the error message is the same as the one displayed when using a card number with a different currency (available for both flows);
* See the attached screenshots;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4051)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16728/Screenshot+2021-10-04+at+08.49.36.png">Screenshot 2021-10-04 at 08.49.36.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16727/Screenshot+2021-10-04+at+08.53.00.png">Screenshot 2021-10-04 at 08.53.00.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16817/Screenshot+2021-10-08+at+10.10.30.png">Screenshot 2021-10-08 at 10.10.30.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16816/Screenshot+2021-10-08+at+10.11.40.png">Screenshot 2021-10-08 at 10.11.40.png</a>

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks for filing.

Note: The VPN website tries to figure out the country/currency-appropriate plan before the user gets to FxA.

Can you clarify what product/plan you are testing with for your steps to reproduce?

I don’t know that I agree that this is an S2 severity, but let’s get some more information first. Ideally the errors should be the same between the old flow and the new flow.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Barry: When you’re signed in, we might be checking your customer , but for the new flow, we don’t have a customer to check. There may be a previous payment method on the existing FxA user’s account if so.

Madalin Cotetiu : Did the existing FxA account ever have an active subscription prior to the steps to reproduce?

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

Hello,

Bianca Danforth, the tested product is Mozilla VPN - monthly plan, but this is reproducible for all the available plans. 

The existing FxA account did not have an active subscription prior to the steps to reproduce. 

Hope this helps. If you need more information, please let me know.

Thank you.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
