### ISSUE TITLE
[chore][subplat] Replace subscription-reminders cron job with invoice.upcoming webhook

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10592]
Ben noticed there is a configurable `invoice.upcoming` Stripe webhook that can be set in the dashboard to e.g. 15 days. This means Stripe would tell us 15 days before a subscription is up for renewal.

This config can be seen at https://dashboard.stripe.com/settings/billing/automatic under Prevent Failed Payments.

Consequently, we can greatly simplify our subscription reminders logic (FXA-3166) by configuring this webhook and sending the reminder email out in a handler for applicable subscriptions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4050)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
