### ISSUE TITLE
Close out the "choose what to sync" feature description

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#106]
I'd like to start being more deliberate about "closing out" feature development and making sure we reflect on what was or was not achieved.  I made a first stab at this over in https://github.com/mozilla/fxa/pull/105, but let's try it out on a couple more features and see how it feels.

@vladikoff, can you please take a moment to wrap up our work on the choose-what-to-sync feature by making a PR that:

* Moves the feature description into the "shipped" sub-directory
* Adds an "Outcomes" section near the top of the document with a summary of what we achieved, and anything else of note such as:
  * Any observed changes in our metrics, or other measures of success
  * Any follow-up work that we should look into

**Comment by shane-tomlinson** [comment]
CWTS still needs to be added to the firstrun flow. See https://github.com/mozilla/fxa-content-server/issues/3365

**Comment by rfk** [comment]
Thanks @shane-tomlinson; so I think that sort of thing is a great bit of context to note for historical reference when we're done with this feature, e.g. "it will be used in XYZ Firefox version under ABC circumstances".
