### ISSUE TITLE
https://accounts.firefox.com/settings "+" in email address backup account 

### ISSUE THREAD

**Issue by Y-Wachtarczyk** [mozilla/fxa#10609]
If i add email name.lastname+label@server.com (which is valid format), firefox account does not sent email with confirmation code. 

### Expected result

Email with confirmation link will be sent and delivered. 

### Actual result

Email is not sent. Tested on gmail and tutanota. Both servers did not receive it. If i send email to this accounts from different service with same email format, email is delivered.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4054)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

I tested adding a backup email (gmail based) from our settings page using the + and I was able to recieve the code.

Please try again, closing the issue for now.

**Comment by Y-Wachtarczyk** [comment]
Actually... It does not work every time... 

In browser i see 

https://api.accounts.firefox.com/v1/recovery_email/secondary/resend_code
[HTTP/1.1 429 Too Many Requests 840ms]
