### ISSUE TITLE
Server error on `POST /account/device` with invalid oauth token

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1060]
@grigoryk discovered this while testing send-tab for Fenix. STR as I understand them:

* Sign in to a build of Fenix with send-tab enabled.
* Change your account password on another device.
* Sync Now on Fenix, to check for new received tabs

The result is:
```
reqwest::async_impl::response: Response: '500 Internal Server Error' for https://api.accounts.firefox.com/v1/account/device
```

The corresponding sentry error appears to be here:

https://sentry.prod.mozaws.net/operations/auth-prod/issues/5712792/?environment=prod

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-private/issues/18

**Comment by rfk** [comment]
Let's uh..let's do the opposite and close this one in favour of the private one.
