### ISSUE TITLE
Make Storybook emails more prod-like (UTM params etc.), potentially retire `yarn write-emails`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10601]
This is an exploratory task that might break into 2+ tasks, if this is even feasible. Right now, we currently pass in mock variables into our templates and don't attach UTM parameters to links. This makes retiring `yarn write-emails` in favor of just using Storybook less appealing because right now, you can run that command and see more production-like emails (with generated links from the server + UTM params) than by using Storybook, though Storybook shows all available templates while the write-emails command renders some templates conditionally based on the values passed in to the mailer. We will have to maintain passing in mock variables in `write-emails-to-disk.js` as well as in Storybook until we use one exclusively.

For tests and the `write-emails` command, we create an instance of our mailer to save the templates to disk or to check the output against these tests. Hopefully there's a way to do something similar for what's generated for Storybook.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4053)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I may be grabbing this next sprint, but just wanted to comment and say one fun alternative approach could be to add a button in Storybook for each template that on click, sends the email to you (to view in maildev?), only for local dev and not for storybook deployments (though that’d be a cool follow up probably not worth the hassle). We basically just want a way to preview what’s actually going to get sent out to phase out yarn write-emails usefulness.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
