### ISSUE TITLE
[subplat][2fa-reset][admin-server] Add mutations to admin-server to reset the user's 2FA and account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10611]
Add mutations to the reset a user’s 2FA and account to the admin-server.  The request payload should contain the 2FA Reset Request id (FXA-3969).  Upon successful resets, set the `resetAt` timestamp on the 2FA Reset Request database record.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4056)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
