### ISSUE TITLE
[subplat][2fa-reset][admin-panel] Add a button to the Admin Panel to reset the account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10613]
Add a button for the most recent 2FA reset request, if it has not been halted or completed, to trigger the reset.  Clicking the button sends a request to the admin-server to perform the reset.  The payload of the request is the 2FA Rest Request id.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4058)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
