### ISSUE TITLE
Variables not rendered in plaintext in staging 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10619]
In plaintext emails you can see variables not being rendered correctly, and in emails that use a partial (such as "button") you can see the localization not being used at all (falling back to the fallback text).

This may be fixed when [https://mozilla-hub.atlassian.net/browse/FXA-4052](https://mozilla-hub.atlassian.net/browse/FXA-4052|smart-link) is fixed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4063)

**Comment by LZoog** [comment]
This should be fixed when the PR for #10600 is in but I'm not entirely sure if that'll fix the plaintext variable problem.
