### ISSUE TITLE
[subplat][2fa-reset][admin-server] Set up Redis

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10616]
Add the dependencies and configuration for Redis in admin-server.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4061)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
