### ISSUE TITLE
[subplat][2fa-reset][admin-panel] Display a user's list of 2FA resets in the Admin Panel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10612]
In the user details section of the Admin Panel, when the user has any 2FA reset requests, display them in reverse chronological order.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4057)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
