### ISSUE TITLE
[subplat] Error banner from Payments page is completely covering the Firefox breadcrumb menu

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10610]
**Affected platforms**:

* iOS 14.7.1;
* Android 10;

**Affected FxA versions**:

* 1.216.0;

**Prerequisites**:

* Have an FxA account with a daily subscription paid via PayPal for Mozilla VPN;

**Steps to reproduce**:
1. Go to [accounts](https://accounts.stage.mozaws.net/) and sign in with the account from the prerequisites;
2. Click on the “Paid Subscription” option;
3. Click on “Change” button from Payment information section and cancel the pre-approved payments;
4. Go back to Subscription management page and refresh the page;
5. Observe the content of the page;

**Expected result**:

* The Firefox logo and the “Account Home > Subscription” menu are correctly displayed on top of the page, with no format or layout issues;

**Actual result**:

* The Firefox logo and the “Account Home > Subscription” menu are completely covered by the red banner regarding the invalid payment information;

**Notes**:

* On Windows and MacOS only the Firefox logo is covered by the banner;
* See the attached screenshots;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4055)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16814/image-20211007-192156.png">image-20211007-192156.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16754/Screenshot+2021-10-05+at+09.53.59.png">Screenshot 2021-10-05 at 09.53.59.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/16755/Screenshot+2021-10-05+at+09.56.40.png">Screenshot 2021-10-05 at 09.56.40.png</a>

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Zachery Sutton , we have a couple of options here:

  1. Move the banner to be below the header.
  2. Make the banner dismissable.
  3. Both 1 and 2.

Do you have any thoughts regarding which is better? We can discuss this in our next check-in as well.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
