### ISSUE TITLE
[subplat][2fa-reset][auth-server] Add a new endpoint to auth-server for 2FA and account reset

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10614]
Add a new endpoint to the auth-server to reset a user’s 2FA and account.  This endpoint is for the Support Panel only.  The request will be authenticated with the shared secret between the Support Panel and the auth-server, and the payload contains the 2FA Reset Request id.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4059)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
