### ISSUE TITLE
[subplat][2fa-reset][admin-panel] Add a button to the Support Panel to reset the account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10615]
Add a button to the Support Panel for a user with a 2FA reset request that has not been halted or completed.  Clicking the button will send a request to the auth-server to perform the request; the endpoint for this request will be added in [https://mozilla-hub.atlassian.net/browse/FXA-4059](https://mozilla-hub.atlassian.net/browse/FXA-4059|smart-link).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4060)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
