### ISSUE TITLE
flow.finalize throws and error when not set

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#10620]
If flow.finalize isn't set, it doesn't need to be an error.

https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/12971021/?referrer=github_plugin

```
Error: WebChannel error: TypeError: flow.finalize is not a function

WebChannel error: TypeError: flow.finalize is not a function
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4064)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
