### ISSUE TITLE
The user is disconnected from the Sync after signing out from the Firefox Accounts page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10633]
[Affected versions]:

* Firefox Nightly 95.0a1 (Build ID: 20211006094130)
* Firefox Beta 94.0b2 (Build ID: 20211005185813)
* Firefox Release 93.0 (Build ID: 20210927210923)

[Affected Platforms]:

* Mac 11.5.1
* Windows 10 x64
* Ubuntu 20.04 x64

[Prerequisites]:

* Have the latest Firefox browser installed and opened.
* Have a valid Firefox Account.

[Steps to reproduce]:
1. Sign in to Sync using the Firefox Account from prerequisites.
2. Click on the Firefox Account toolbar button and select the “Manage account” option.
3. Click on the Firefox account menu and select the “Sign out” option.
4. Restart the browser and observe what happens.

[Expected result]:

* Nothing happens, the user is still logged in to Sync.

[Actual result]:

* The Firefox account is disconnected.

[Notes]:

* This issue is also reproducible when just waiting ~ 5 min after signing out from the Firefox Account page without restarting the browser.
* Attached is a screen recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4067)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16789/FirefoxAccount_Disconnected2.gif">FirefoxAccount_Disconnected2.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
