### ISSUE TITLE
Dockerize fxa-payments-server for deployments

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1063]
To deploy the payments server, Ops will want it to be dockerized.

ref #1024

**Comment by lmorchard** [comment]
Part of this should include a static build via `npm run build`, but should also include running the express server via `npm start` at runtime.

**Comment by lmorchard** [comment]
Additionally, we'll need to figure out CSP rules and such - the pages need to talk to the OAuth, Auth, and Profile servers as well as including Stripe JS. Anything else?

**Comment by shane-tomlinson** [comment]
> Additionally, we'll need to figure out CSP rules and such - the pages need to talk to the OAuth, Auth, and Profile servers as well as including Stripe JS. Anything else?

If any of the static resources are deployed to the CDN, that'll need to be allowed too.

**Comment by clouserw** [comment]
This is deployed via docker already
