### ISSUE TITLE
[subplat] Pasting an email address in the email field triggers the “Your email address is invalid.” message

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10661]
Affected Fxa version:*

* 1.216.2;

**Affected Platforms:**

* All;

**Preconditions:**

* Have VPN installed and connected to one of the VPN availability locations;
* Be on new “Set up your subscription” page;

**Steps to reproduce:**
1. Paste a valid email address in the field;

**Expected result:**

* The email address is correctly validated;

**Actual result:**

* A message error is displayed “Your email address is invalid.”

**Additional notes:**

* The error message disappears after backspacing after .com;
* Pasting the email address from the email client does not trigger the error;
* See the attached screen record;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4073)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16862">Peek 2021-10-11 12-22.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
