### ISSUE TITLE
[subplat] Success payment details available in the “Please set your password” for an unprocessed payment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10660]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.216.2;

**Prerequisites**:

* Have the VPN set to US;
* Be in the new subscription flow;

**Steps to reproduce**:
1. Subscribe to Mozilla VPN monthly plan using a 3D Secure card: 4000008260003178;
2. Open your email and check the “Please set your password” email;
3. Observe the content of the email;

**Expected result**:

* The content of the “Please set your password” email reflects that the user has NOT been charged. 

**Actual result**:

* The content of the “Please set your password” email reflects that the user has been charged.

**Notes**:

* Stripe lists that the user is not actually charged. (https://dashboard.stripe.com/test/invoices/);
* The payment confirmation email is not received;
* See the attached screenshots;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4072)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16859">Screenshot 2021-10-11 at 12.13.43.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16858">Screenshot 2021-10-11 at 12.14.41.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16939">Screen Shot 2021-10-14 at 5.50.29 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Madalin Cotetiu  can u double check if this is still an issue.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Anna Sobiepanek , Verified this on Train 1.233.1 - Staging and this issue is still reproducible as described above.

Used FXA account: bhidecuti+4072a@mozilla.com ( mailto:bhidecuti+4072a@mozilla.com )

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

It’s not possible to accurately reflect the current state of processing in the email at this stage for 3d Secure. So there’s a few options:

  1. Delay sending the finish setup email until the invoice was paid.
  2. Update the text of the email to show that it hasn’t been processed yet, or something similar.
  3. Remove all the text referring to the fact that the user has paid (which they may not have finished yet).

I originally attempted to resolve this using method 1, however there’s insufficient data for setting up the reminder emails and such when the invoice paid webhook fires, so #1 is not a viable solution.

We could update the initial email to say something about how the transaction has started, but hasn’t completed, except the email is sent when the 3d Secure process starts, at which point its always in this state, so if a user finishes payment, then views the email, the state in the email is no longer accurate. So I don’t think #2 is viable either, because we don’t know when the user is going to view the email, so even though it wouldn’t have been processed in this case, if it is processed before you view the email, the email is inaccurate again.

My proposed solution is therefor #3. This email should not mention the status of the payment at all, instead it should indicate that they have started the VPN subscription sign-up (or something similar), and mention that when they complete payment an invoice email will be sent to them. We will need copy for the email update along with new translations.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I should note one other option…. we accept that people paying with 3d Secure have a sub-optimal sign-up experience if they fail to finish the process successfully. Very few people use 3d Secure at the moment, and the amount of people that see this is very small.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
