### ISSUE TITLE
WError: An internal server error occurred

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#10677]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/7843129/?referrer=github_plugin

```
WError: An internal server error occurred
  ?, in runMicrotasks
...
(5 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4079)

**Comment by jodyheavener** [comment]
🎉
