### ISSUE TITLE
[subplat] Return 200 on Stripe Webhooks for Deleted Customers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10684]
Whenever we receive webhooks for a user whose customer record has been deleted, we should return a 200 to Stripe so that it'd stop retrying as the retries will never succeed.  If the missing customer record is an exception then report an error to Sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4084)

**Comment by chenba** [comment]
Sentry issue: [FXA-AUTH-PROD-E5](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/13667940/?referrer=github_plugin)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Reino Muhl I don’t recall seeing issues with deleted customers recently.  What do you say to we canceling this issue, and open new issue(s) to address any bugs as they appear in the future?

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

Yup, I agree with that! I’m happy to cancel this ticket.
