### ISSUE TITLE
Restoring iOS on a New Phone shows as signed in when in fact it's not

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#10708]
## Description

I just got a new iPhone. I restored from iCloud. Firefox showed my avatar so I thought I was automatically signed in. When I clicked on my own avatar, it asked me to sign in with pairing.

### Steps to reproduce

- Backup old phone to iCloud
- Restore backup to a new phone
- Look at hamburger menu, your personal avatar should be displayed
- Click on avatar
- You'll be asked to sign in

### Expected result

Probably show me as signed out. I suspect that backing keys to iCloud is not something we'd want.

### Actual result

You're shown as signed in but not.

### Environment

iOS 15
Migration fro iPhone XS Mas to iPhone 13 Pro Max

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4095)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
