### ISSUE TITLE
Fix pocket stage test failing

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#10705]
Ref https://app.circleci.com/pipelines/github/mozilla/fxa/23654/workflows/30ce54a7-323f-4a1d-b059-d2f8653701d9/jobs/272342

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4091)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
