### ISSUE TITLE
Clicking to Manage Account on iOS is Unverified Session

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#10735]
## Description
For a strange reason, I needed to re-auth again today on iOS. I'd authed just days ago via pairing (because when I restored my phone from backup, I was signed out) so it's strange that I had to do it again.

This time, it did not offer the pairing flow. The URL it directed me to also didn't have `service=sync` in the address so it was an unverified session and likely did not turn on sync as a result of not having that URL parameter.

Screenshot login form:
![IMG_0071 2021-10-18 18_55_44](https://user-images.githubusercontent.com/19537086/137790259-14917325-8fe1-49bd-b2f2-871ed3c65f77.PNG)

### Steps to reproduce

- from a disconnected state (unintentional), try to sign back in
- if you are directed to a login form rather than pairing, observe the URL.

### Expected result

I expect to be linked to a Sync login page.

### Actual result

It had the message that asked if I was looking for Sync.

### Environment

iOS 15.02
iPhone 13 Pro Max
Firefox version 39.0 (6392)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4109)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Vijay Budhram will try to repro

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
