### ISSUE TITLE
fxa-admin-panel tweaks: external-icon not rendering, search input has grey bar

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#10764]
The suggestions list should be hidden if it doesn't have content:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/13018240/137968153-7bd52453-ae36-49c0-a2d8-7b51933915b0.png">

And, the external link icon in the corner isn't rendering:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/13018240/137968207-c533d43d-326d-4833-9009-16a9e8109f46.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4128)

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Breaking this out into individual tickets
