### ISSUE TITLE
Settings TS linting not failing CI or pre-commit hook?

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#10762]
In at least `BentoMenu/index.test.tsx`, `ConnectAnotherDevicePromo/index.test.tsx`, `ConnectedServices/index.tsx`, `ConnectedServices/index.test.tsx`, and `Profile/index.test.tsx`, VSCode complains about some Typescript issues.

We need to fix these and any others, and investigate why CI is allowing these to pass. If there's a lot more than what's listed here, this can be broken up into 2+ tasks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4126)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
