### ISSUE TITLE
Add prettier-plugin-organize-imports to Settings, format files

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#10761]
This plugin will help Settings keep its imports more organized and removes unused imports, of which we have several scattered about.

Add this plugin and run it on all Settings files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4125)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
