### ISSUE TITLE
Capture additional Sentry data on Stripe webhooks

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10766]
The webhook handler should have a try/catch around it extended to report the sentry error itself with additional scope context including the event id and request id from the event object.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4129)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
