### ISSUE TITLE
Fix Settings lint complaint about CSF Storybook syntax + convert at least 1

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#10771]
In `fxa-settings`, when trying to use the newer [CSF Storybook syntax](https://storybook.js.org/docs/react/api/csf), our linter complains with no-anonymous-default-export and Storybook doesn't load it:

![image](https://user-images.githubusercontent.com/13018240/137986217-99c66e96-fa36-4708-a698-182890042f3f.png)

We can use the new syntax in the Storybook set up in `fxa-auth-server` without disabling that eslint rule. [Experimenter nimbus-ui](https://github.com/mozilla/experimenter/tree/main/app/experimenter/nimbus-ui) uses both syntaxes. This might be a TS config thing but either way it's probably easily fixed.

We should use the new format for new stories and do our best to update old stories whenever we touch other story files. For this issue, let's make sure we can use both formats and convert an existing `.stories` file, or fix this with another issue and make the new story with the CSF format.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4134)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
