### ISSUE TITLE
[Pocket migration] Logo missing from "Enter verification code Continue to Pocket" page and other "Continue to Pocket" pages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10783]
**Build:**
Stage (Train 217.2)

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Go to Pocket stage server: [https://fxa-staging.web.readitlater.com/signup__ffbp=temp.backend.web.fxa_signup](https://fxa-staging.web.readitlater.com/signup__ffbp=temp.backend.web.fxa_signup)
1. Enter email and click "Sign up" button.
1. Enter valid credentials and click "Create account" button.
1. Observe the "Enter verification code Continue to Pocket" page.

**Actual result:**
Pocket logo is missing from the page. There is no consistency.

**Expected result:**
Pocket logo is displayed on the page. Pocket logo is displayed on the other similar pages.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4138)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/17870/logo+displayed+on+verification+code+page.PNG">logo displayed on verification code page.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/17005/logo+not+displayed+on+verification+page.PNG">logo not displayed on verification page.PNG</a>

**Comment by vbudhram** [comment]
@jodyheavener Lets add this to the `confirm_signup_code` template. In general, I think the longer term solution would happen when we migrate away from using Backbone. We should be able to come up with a more generic solution.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on stage [Train 219.2] under Windows 10 64-bit. I confirm that pocket logo is displayed on the “Enter your verification code“ page. For the other similar templates please see comments below.

!logo displayed on verification code page.PNG|width=404,height=473!
