### ISSUE TITLE
Subscription management button should only appear when user has at least one active subscription

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1078]
The [subscription managment button](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/settings/subscription.js) will always be shown, once we enable the subscriptions feature. This button should be hidden unless the user has at least one subscription active.

Some comments in the wireframe about this:

https://mozilla.invisionapp.com/share/K2RBDY3VU9X#/screens/355610597/comments/114028740

**Comment by clouserw** [comment]
Do we want to hide this button even if they used to have a subscription and it has lapsed (like, if they had a payment problem)?  /cc @johngruen

**Comment by ianb** [comment]
Note there's a language check for the button currently, and that check should be removed (it's up to product pages to filter their audience appropriately).

**Comment by clouserw** [comment]
If a subscription has lapsed, don't show the button.  We can make that more graceful after the MVP
