### ISSUE TITLE
[subplat][docs] Document the webIconBackground metadata

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10788]
The `webIconBackground` sets the background color of the element where the product icon is displayed but it's not listed on https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform.  We need to document it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4139)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
