### ISSUE TITLE
[subplat] Remove old legal docs directories

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10816]
We have some old directories that we should remove from `assets/legal`, as it makes uploading new legal docs a little confusing (e.g. FXA-4102).

In particular: `/Mozilla_VPN_ToS` and `mozilla_vpn_privacy_notice` can be removed, since we are using a new file structure now and have been for many months. It looks like `Firefox_Private_Network_ToS` is still used based on that product's metadata.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4141)

**Comment by advaith-unnikrishnan** [comment]
Hey @data-sync-user  I would like to work on this issue
