### ISSUE TITLE
handlePlanUpdatedEvent - Plan "price_1JmROfJNcmPzuWtR6od8OfDW"'s metadata failed validation

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fxa#10827]
[https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/14057704/?referrer=github_plugin](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/14057704/?referrer=github_plugin)

```java
handlePlanUpdatedEvent - Plan "price_1JmROfJNcmPzuWtR6od8OfDW"'s metadata failed validation
```

Until we have UI for [https://mozilla-hub.atlassian.net/browse/FXA-3655,](https://mozilla-hub.atlassian.net/browse/FXA-3655,) this will still be an issue, so we should update the error message in the meantime to say which key/value failed validation. This is already contained in the `error` object's `message` prop.

~~Ensure that Joi doesn’t abort early on error.  The validation error details are potentially in the ‘details’ prop.  If available, include all the error detail in the Sentry error name.~~ (handled by FXA-4144)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4145)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

https://mozilla-hub.atlassian.net/browse/FXA-4144 ( https://mozilla-hub.atlassian.net/browse/FXA-4144|smart-link ) already handled abortEarly: false, so this ticket is now to update the Sentry error message to include as much actionable information as possible about the validation errors encountered.
