### ISSUE TITLE
WError: An internal server error occurred

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fxa#10828]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/14046502/?referrer=github_plugin

```
WError: An internal server error occurred
  ?, in Array.reduce
  ?, in new Promise
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe-firestore.js", line 52, in StripeFirestore.retrieveAndFetchSubscription
    const subscription = await this.stripe.subscriptions.retrieve(subscriptionId);
  ?, in runMicrotasks
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe.js", line 1724, in async StripeHelper.processWebhookEventToFirestore
    await this.stripeFirestore.retrieveAndFetchSubscription(invoice.subscription);
...
(11 additional frame(s) were not displayed)
```

Not entirely sure why the subscription id is `null` here. Has only happened once so far in the last 30 days.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4146)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

It’s possible that an invoice is created without a subscription.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

A patch should be in for 219 that includes more payload details for us to locate the Stripe data and verify what is happening.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
