### ISSUE TITLE
one of the sign-in CTA for existing FxA users in the VPN payment page does not emit the appropriate event type

### ISSUE THREAD

**Issue by YeonjooSmith** [mozilla/fxa#10838]
## Description

There are two CTAs for existing FxA users to sign in at the VPN payment page. When one of them were clicked, the event type `fxa_pay_account_setup - other` is supposed to be emitted show up in the prod table(`moz-fx-fxa-prod-0712.fxa_prod_logs.stdout_20*`)  but when the CTA in the second image was clicked, it did not get emitted. 
  
![CTA1](https://user-images.githubusercontent.com/49305857/139089312-475b0afc-804b-4abf-ad36-09becc409407.png)

![CTA2](https://user-images.githubusercontent.com/49305857/139089369-b9ea6a98-66b2-4148-804c-3c35bd550e64.png)

### Steps to reproduce & Expected result& Actual result
I created a test FxA account and went through the VPN subscription process using both CTAs. 
1. When I used the CTA in the first image(flow_id= 'f84614cc3eca675c8e6a840b0b234494ef86f94fce935243bea6c653a01ceed4'), I get  `fxa_pay_account_setup - other`in the list events emitted. 
2. When I used the CTA in the second image(flow_id = 'b43232c5e400b663a16e6e1607ccf13d03dab2cb940894b81da3e4fe17e06573'), I don't get the event type in the list of events emitted. 

### Environment
Mac OS X, Safari

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4147)

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

HiYeonjoo Yoo 

This issue should be resolved in Train 219 and will be in production in the next couple of days.

cc Anna Sobiepanek
