### ISSUE TITLE
Add the Trailhead UI changes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1084]
We need the bit on the right.

<img width="697" alt="Screenshot 2019-05-13 at 12 01 35" src="https://user-images.githubusercontent.com/848085/57616779-f778f180-7576-11e9-8f3e-cbf0df7b0778.png">

cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
The above design is replaced with:

### set password

<img width="734" alt="Screenshot 2019-05-13 at 15 59 17" src="https://user-images.githubusercontent.com/848085/57631814-1f2c8180-7598-11e9-9b9a-d076406c26ca.png">

### Setup Firefox

<img width="571" alt="Screenshot 2019-05-13 at 16 00 08" src="https://user-images.githubusercontent.com/848085/57631859-33707e80-7598-11e9-8a9b-c1509c22f24e.png">

### Confirm email

<img width="687" alt="Screenshot 2019-05-13 at 15 59 28" src="https://user-images.githubusercontent.com/848085/57631881-408d6d80-7598-11e9-89bf-af738c57a15a.png">

### Send SMS

<img width="604" alt="Screenshot 2019-05-13 at 15 59 32" src="https://user-images.githubusercontent.com/848085/57631890-45522180-7598-11e9-9d7a-2a1042326720.png">

Still needed:

* [ ] Verify on a 2nd device
* [ ] Connect another device (non-SMS)
* [ ] New Firefox logo SVG
* [ ] SVGs for the progress indicator
* [ ] Latest illustration SVGs
* [ ] Colorized logos for screen 2

**Comment by shane-tomlinson** [comment]
@ryanfeeley's invision designs: https://mozilla.invisionapp.com/share/J7K17501851M69#/screens/362776357

**Comment by jpfaller** [comment]
We've got MKTG and legal alignment on the opt in language. Attaching the text and full copy deck (changes in green).

Subhead: Practical knowledge is coming to your inbox
Copy: Sign up for more:

<check box>Be safer and smarter online
<check box>Test new Firefox products
<check box>Take action to keep the internet healthy

https://docs.google.com/document/d/1jQwIsAMz7gFDUa0f22LVoAhKxo5vr2I3_xf8Kib2MVs/edit?usp=sharing

**Comment by antlam** [comment]
Specifically, the "get involved" section changes to the above^ (not sure if this is where we should stick this but got this link from channel)

![Screen Shot 2019-05-17 at 1 38 40 PM](https://user-images.githubusercontent.com/1994820/57957924-e4d22580-78b2-11e9-80e6-f74fa6649adf.png)

Screenshot for reference
@clouserw @ryanfeeley @shane-tomlinson @davismtl

**Comment by shane-tomlinson** [comment]
BOOM. The last one merged. There are follow ons filed for hooking up the newsletters and new email types. Closing this one.
