### ISSUE TITLE
Poll Stripe Events API for events that failed all webhook retries

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10870]
[FXA-3699] added a Grafana alert with a Slack integration to notify the FxA team on failed webhooks.

One limitation of the alert is that it fires for every failed webhook, including ones that will be [retried](https://stripe.com/docs/webhooks/best-practices#retry-logic) and may succeed on a retry. I spoke with Ben about this, and the easiest solution would be to have a cron job that calls the Stripe Events API to see if an event ID failed more than 3 days ago and still hasn’t been successfully delivered.

We would want to run this cron job at least daily in prod and stage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4160)

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Benjamin Bangert do we have a ticket for that yet?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

I linked the other ticket, https://mozilla-hub.atlassian.net/browse/FXA-4424 ( https://mozilla-hub.atlassian.net/browse/FXA-4424|smart-link ) as being blocked by this one.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
