### ISSUE TITLE
[subplat] Write a cloud function to republish Google Play test/prod notifications

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10894]
In [FXA-3767] and FXA-4105, QA verification depends on receiving Google Play RTDNs (real-time developer notifications) to our FxA stage services. Unfortunately, we are currently not receiving any of these events in FxA stage, so QA verification is not possible.

Why? The Google Play Store only allows for one PubSub application URL and sends all events there, testing or not. This means we only get events to FxA prod, since the PubSub URL was updated to point to FxA prod (from stage) after the initial Google IAP support epic ([FXA-3738]) was complete. How can we get test events from the VPN Google Play Store app to FxA stage?

Options discussed with Ben:

1. The VPN team creates two apps in the Google Play store, one for testing and one for production.
  1. This is not the supported workflow by the Google Play Store for app testing.
  1. The VPN team currently only maintains a single app.
  1. This would mean any IAP app in the future (e.g. MDN) would also have to maintain two separate release/build pipelines.
1. We could have multiple subscribers, one that publishes to stage and one to prod.
  1. This would pose possible security risks, as we would be sending prod data to stage (to presumably be filtered out).
1. We could have one subscriber that directs test events to FxA stage otherwise prod.

Option 3 seems like the best option.

This would likely be two [google cloud functions](http://cloud.google.com/functions/docs/samples): one to take a message and one to publish a message. We would publish to either the Stage or the Prod topic (stored in environment variables) depending on if the testing flag is present in the message. There would likely be a lot of configuration involved on the Ops side, so we would need to work closely with jbuck and/or dlactin.

Some open questions:

* Is there prior art for this in our CloudOps repo?
* Is there a preferred language the cloud function should be written in?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4169)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
