### ISSUE TITLE
Implement l10n for fxa-payments-server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1089]
We want to use [the React bindings for Fluent](https://github.com/projectfluent/fluent.js/wiki/React-Bindings) to support l10n in fxa-payments-server.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-86)
┆Issue Number: FXA-86

**Comment by lmorchard** [comment]
Making this issue a bit more generic - we probably also want to ensure things like date formats can be localized, too: https://github.com/mozilla/fxa/pull/1584#discussion_r295024411

**Comment by clouserw** [comment]
@johngruen will drive a conversation with the other Product leads to answer questions about edge cases
