### ISSUE TITLE
Broken/non-grammatical HTML <title> on sign-in pages (shown in tab title)

### ISSUE THREAD

**Issue by dholbert** [mozilla/fxa#11000]
## Description

The `<title>` for FxA sign-in pages (maybe other pages as well) has two phrases (title+subtitle) smooshed together, and feels like broken English as a result, which makes the site feel less trustworthy / more suspicious.

### Steps to reproduce
1. Visit https://accounts.firefox.com/ in a browser where you're not already signed in (or e.g. in a private browsing window)
2. Look at the tab title (which shows the page's `<title>`).  Hover it to show the full title (beyond the ellipsis).

### Expected result
The title should say something like "Sign in to Firefox Accounts" or something like that.

### Actual result

The title says `Enter your email Continue to Account Settings`, which feels like broken English and feels possibly suspicious (e.g. like maybe you're getting phished).

### Environment

Firefox Nightly 96.0a1 on Linux (though I don't think this is browser-specific)

Note: if I perform the STR in a session where I am already signed in, it instead says `Sign in Continue to Account Settings`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4196)

**Comment by dholbert** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/426803/141596745-bd8beb20-3275-4250-af99-103dfb1deee5.png)

**Comment by dholbert** [comment]
Possible easy improvement: we could just add some sort of separator, e.g. `|` between the two sentences, so it would then say:
`Enter your email | Continue to Account Settings`

It looks like these strings are taken from (or shared with) the content on the page -- see screenshot below[1]. It looks fine there, since the two distinct phrases are clearly separated by being on different lines and having different font sizes. But it looks broken & feels suspicious when the two phrases are smooshed together with no separator, as is currently happening in the tab title (from `<title>`).

![image](https://user-images.githubusercontent.com/426803/141596963-dbb523fb-82b3-4ce5-9d34-1db39542934f.png)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
