### ISSUE TITLE
Deliver a URL to the Support Panel

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#1100]
IT needs a URL for the support panel.  /cc @marty331

**Comment by lmorchard** [comment]
I'm personally fuzzy on where this will live - but this might be related: https://github.com/mozilla/fxa/issues/797#issuecomment-491388769

TL;DR: the URL could be https://subscriptions.firefox.com/premium-support ?

Probably needs a nod from someone product-wise though.

**Comment by shane-tomlinson** [comment]
> TL;DR: the URL could be https://subscriptions.firefox.com/premium-support 

Do users need to be authenticated to view the support form? The wireframes imply yes. I'd put the page as a panel on the content-server as the path of least resistance. The subscription services doesn't yet keep sessions nor does it yet act like a full fledged RP that supports signing in. The content-server already has a sessionToken and logic to redirect back to an internal page if a user is not signed in.

**Comment by lmorchard** [comment]
> Do users need to be authenticated to view the support form? The wireframes imply yes. I'd put the page as a panel on the content-server as the path of least resistance. The subscription services doesn't yet keep sessions nor does it yet act like a full fledged RP that supports signing in.

Well, all the pages on the payments-server require auth via a token that we're using as a defacto short-lived session. 

Main reason I'm assuming the support form lives alongside subscription payment pages is that it's shown that way in wireframes. The subscription management page links to it and the support form returns to the subscription management page after submission:

https://mozilla.invisionapp.com/share/K2RBDY3VU9X#/screens/356896707

But, if we can finesse the appearance & navigation & etc for it to live on content-server - then there's no other good reason for it to live on payments-server. (i.e. no 3rd party JS for payment widgets, etc.)

**Comment by clouserw** [comment]
The support epic is a bit muddled and we spent some time yesterday to decipher it.  So, to offer some clarity:

When we talk about the Support Form we are talking about issues #797 (the backend) and #798 (the frontend).  That's the form in the wireframes that end-users are interacting with.  (It wouldn't be crazy just to move these to the Payment Pages epic if that helps put things in the right boxes)

When we talk about the Support Panel, we're talking about a very simple page that takes a query parameter and displays details about a user.  This page will be iframed by zendesk and used by the support personnel to look up details about users.  That is all the rest of the issues hanging off the support epic in #697 aside from the two mentioned above.

This issue (#1100) is about what that URL to the Support Panel is, so IT can put it in their iframe.

It took me a long time yesterday to get this straightened out in my head, so, if this isn't clear please let me know and I'll answer any other questions.

**Comment by lmorchard** [comment]
> When we talk about the Support Panel, we're talking about a very simple page that takes a query parameter and displays details about a user. This page will be iframed by zendesk and used by the support personnel to look up details about users.

Hmm, FWIW, this sounds like something that could easily expose PII if not behind a VPN and ends up being discovered. (Maybe that's already been considered, though it *does* very much affect the URL and iframe-ability of it.)

**Comment by clouserw** [comment]
VPN is one of the requirements.  See https://github.com/mozilla/fxa/issues/702

**Comment by shane-tomlinson** [comment]
> This issue (#1100) is about what that URL to the Support Panel is, so IT can put it in their iframe.

Thanks for the clarification @clouserw and @lmorchard.

> though it does very much affect the URL and iframe-ability of it.

Soon, accounts.firefox.com [*will not be able to be iframed*](https://bugzilla.mozilla.org/show_bug.cgi?id=1539595) because the entire domain will be process isolated within Firefox. If the desire is to show user info within an iframe, then hosting that iframe on accounts.firefox.com is a non-starter. 

If the content is hosted on a standalone page that the support team loads, we could pull that off, but as @lmorchard says we'd have to put very strict access controls on it. We don't want any goon being able to look up another user's information.

**Comment by clouserw** [comment]
Assign to Ian because he had a shell for this already done.

We'll need to put this on a separate domain.  The domain doesn't matter, since it is only internal (and VPN'd).  @jbuck @jrgm for visibility here

**Comment by clouserw** [comment]
Is #702 good enough for tracking deploying this, or does it include things that aren't done yet and I should file a separate issue?  Thanks @ianb @jbuck

**Comment by jbuck** [comment]
#702 is good enough for me
