### ISSUE TITLE
Add support for Trailhead "Beta" program

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1102]
Summarizing @chuckharmston and @davismtl in Slack:

A new "Beta" program is being launched with Trailhead that gives users a sneak peek at upcoming technologies. Users can opt-in to the program through several touch points, each of which require creating or signing in to a Firefox account.

~~### From an external RP such as send.~~

~~- banner displayed on send.firefox.com to join Beta~~
~~- User click is sent to accounts.firefox.com~~
~~- user logs in or registers to join the beta program~~

### User signs up for Sync

- User clicks "sign up" for Sync, is sent to accounts.firefox.com
- On the ["Set up your Firefox Account" screen](https://github.com/mozilla/fxa/issues/1084), user sees a new checkbox "Invite me to test new Mozilla products"
- User selects checkbox and joins the beta program

The [PRD](https://docs.google.com/document/d/1nZ6MoXG0_cbH3P7KbZeADjdP82KiFWUwkrR4wXdIoRI/edit) for this feature.

**Comment by chuckharmston** [comment]
Thanks, Shane!

In addition to what you'd listed, we'd like to make sure that all the `utm_` parameters for new accounts are able to be preserved for conversion rate and funnel analysis. My understanding is that this is already in place, but it is an important requirement.

**Comment by shane-tomlinson** [comment]
There are multiple parts to this. We need UX support, and possibly backend, and Basket support.

First, the front end.

There will be two primary flows. First, as a banner displayed on one of our sites. I can imagine "Firefox Beta Program" being an OAuth RP of sorts. When the user clicks on the link, the user is redirected to FxA w/ the beta program's client_id, and a scope that indicates "opt the user into the newsletter". If the user is signing up to FxA, automatically check the "Invite me to test new Mozilla products" checkbox on the "Set up your Firefox Account" screen. If the user is signing in... I'm not totally sure, maybe show the authorization checkbox screen to allow the user to change their mind. Once the user completes either, redirect to an *internal* page similar to [how we do for Fenix](https://accounts.firefox.com/oauth/success/a2270f727f45f648) that says "You are now signed up to the Firefox beta newsletter". We'll need UX support for this. I'm sure @chuckharmston and @ryanfeeley have some thoughts here.

We won't need a button within /settings/communication_preferences because that is being [replaced with a generic link to a user's communication preferences](https://github.com/mozilla/fxa/issues/962).

Second, the backend and Basket.

The Mozmaeo team will be responsible for sending the newsletters. To make this possible, we will need a way to notify Basket of the user's intent to signup for the beta newsletter. 

We currently have two ways of informing basket the user wishes to opt-in to a newsletter. 

1. On signup, we send a generic [`marketingOptIn` flag when notifying Basket](https://github.com/mozilla/fxa/blob/e3be7a6f31a6071673fd33aa9e066f9b85314bb8/packages/fxa-auth-server/lib/routes/emails.js#L424). On the basket end, this opts users into the ["Firefox hints and tips" newsletter](https://github.com/mozmeao/basket/blob/8ffa8f16145136788e7de7c1feb7a304756b6050/basket/settings.py#L372-L373).
2. From the /settings page, if a user clicks "Subscribe", we call [basket's /subscribe endpoint with an OAuth access token and the `firefox-accounts-journey` newsletter ID](https://github.com/mozilla/fxa/blob/e3be7a6f31a6071673fd33aa9e066f9b85314bb8/packages/fxa-content-server/app/scripts/views/settings/communication_preferences.js#L108).

We could use the 2nd approach as part of the signin flow, but not the signup flow where a user may confirm their email on a 2nd device. To be bulletproof, we'd want an expanded version of the first. Instead of sending a boolean `marketingOptIn`, we'd want to send a list of newsletters IDs the user is opting into.

Perhaps for the MVP, we could sacrifice some of the robustness of the first approach so that we can move more quickly. We can avoid changes to Basket and the auth-server if we say that it's OK if we only capture users who verify on the same device in which they sign up. We would be able to use the 2nd approach for these users to create OAuth tokens that allow us to subscribe the user to the newsletter.

cc @pmac

**Comment by chuckharmston** [comment]
> Once the user completes either, redirect to an internal page similar to how we do for Fenix that says "You are now signed up to the Firefox beta newsletter". We'll need UX support for this. 

Can you help me understand what the UX need will be? Given how tight the timeline is, I'm trying to piggyback on any existing workflows, and would be pretty happy with the Fenix one + slightly different messaging.

**Comment by pmac** [comment]
For option 2 you don't need the OAuth access token since you'll no longer need to get the `token` in the response after #962 lands. So you can just post to [`basket.mozilla.org/news/subscribe/`](https://basket.readthedocs.io/newsletter_api.html#news-subscribe) with an email address and some other metadata and it'll work fine. We can get more fancy with the queue integration later if we need to.

**Comment by davismtl** [comment]
> Given how tight the timeline is, I'm trying to piggyback on any existing workflows, and would be pretty happy with the Fenix one + slightly different messaging.

Normally, we don't have any product-specific messaging in the accounts flows because it's not scalable for us and then we become a blocker for any future changes. Sync is the exception due to how deeply the two products were integrated into one another.

I'm not saying we should or shouldn't do this but it's important to note that this type of work is near certainly automatic technical debt for us that will likely need to be undone after.

**Comment by clouserw** [comment]
This issue now only covers adding 1 (or 2?) checkboxes to the form.  Nothing additional.

**Comment by vbudhram** [comment]
From slack:

New email marketing slugs:

```
Sub: Knowledge is Power
Slug: knowledge-is-power

Sub: New Product Testing
Slug: test-pilot

Sub: Take Action for the Internet
Slug: take-action-for-the-internet
```

Ref: https://docs.google.com/spreadsheets/d/1CdsuwXBhXhJ9LBMthRMDx9ATEGWDiKXlZoPFWLjjKzI/edit#gid=0

**Comment by shane-tomlinson** [comment]
When verifying, the newsletter IDs are propagated to the backend. 

@pmac - Is there an SQS hookup to the basket stage environment to verify the newsletter opt-ins are correctly propagated?

**Comment by pmac** [comment]
Yes, it does look like there is a stage queue called `basket-account-change-stage` that basket-stage is listening to and processing. You should be able to get to the newsletter preferences for the user by going through the new https://basket.allizom.org/fxa/ flow and see which newsletters are checked.
