### ISSUE TITLE
fxa-auth-server does not work with SMTP server without AUTH

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#11041]
## Description

Due to #10532 , without env  `smtp_user`  and `smtp_pass` ,  fxa-auth-server forces use AWS SES , and node mailer raises an  error   `ses.sendRawEmail is not a function` because of lacking  env `AWS_ACCESS_KEY`.

fxa-auth-server does not work with SMTP server without AUTH . However  `AUTH` is not a must for a smtp server. 

I think we should choose SES only when `SMTP_HOST` is unset , but not `SMTP_USER` and `SMTP_PASS` is unset.

### Expected result
Work with smtp server which do not require `AUTH` with `smtp_user`  and `smtp_pass` , for example self host mail relay server

### Actual result
node mailer raises an  error  `ses.sendRawEmail is not a function`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4207)

**Comment by LZoog** [comment]
During our triage, we discussed this and don't think the request is unreasonable. PRs for it are welcome, but it's not currently on our roadmap so we are moving this into our issue backlog. Thank you for filing. :)

**Comment by jackyzy823** [comment]
Dear @LZoog 

I have a question about your production server ' s configuration . 

In your production server, if you choose `SES direct API` , will you set `SMTP_HOST` to an empty string?

If `SMTP_HOST`  is not an empty string, there's no way to determine use `SES direct API` or  `self host stmp server without AUTH`. 

Thanks.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
