### ISSUE TITLE
[subplat] Add a pre-defined accepted languages list for the legal-docs redirect endpoint

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11043]
The Payments server's legal-docs endpoint previously used FxA's supported languages to filter the accept-language value.  That was removed in FXA-4204 due to a mismatch between FxA's supported languages for web content and translated product legal docs.

We should restore an allow-list of language to limit what the endpoint will process.  Here are a couple potential approaches:

* FxA's supported languages list with additional, manually maintained, languages (e.g. `ms` from FXA-4204)
* languages that can be set in Firefox: https://searchfox.org/mozilla-central/source/intl/locale/language.properties

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4209)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

cc Bianca Danforth

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
