### ISSUE TITLE
[Train 137]Dotted square presented on the view of changing picture 

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1107]
Environment:
Builds: Stage [Train 137];
Devices: Android, Windows 10 ;

Prerequisites:
You are logged on a valid account.

Steps to reproduce:
1. Go to Manage account;
2. Tap on 'Change' button from the Account picture section;

Expected results:
The change picture pop-up menu is displayed without any issues.

Actual results:
The change picture pop-up menu is displayed but a dotted square is presented on view.

Notes:
- Not reproducible on production;
- Video
![20190515_150116](https://user-images.githubusercontent.com/40264165/57775762-6fd1e500-7726-11e9-85b6-cc5531b6d079.gif)

**Comment by ryanfeeley** [comment]
@clouserw Bump… 
![v3ruz45nrt4x](https://user-images.githubusercontent.com/68213/60831777-5f6b4300-a188-11e9-841a-a2969aa84968.jpg)

**Comment by vbudhram** [comment]
from mtg:

We have some ideas on how this can be fixed. Bumping to next train until then.
