### ISSUE TITLE
Add remote auth server tests for subscription endpoints

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1110]
Unless I'm missing something there are no remote tests in the auth server for the subscription endpoints.

This is a problem because the remote tests are really the only ones we have for proving stuff actually works. The local tests mock aggressively and don't really prove correctness in a behavioural sense. They're more about asserting certain properties that are difficult to verify through the API, such as whether metrics are emitted correctly. They're also fast which makes them more convenient to run regularly when refactoring etc.

**Comment by lmorchard** [comment]
> Unless I'm missing something there are no remote tests in the auth server for the subscription endpoints.

There are some minimal remote tests for a critical path of creating a subscription and ensuring capabilities are listed in the user profile here: https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/test/remote/account_profile_tests.js#L318

These don't call every API, though, so there could be more remote tests added.

**Comment by philbooth** [comment]
Ah, thanks for the pointer! I just assumed they'd be in their own module, didn't think to actually grep for them...

**Comment by lmorchard** [comment]
Yeah, was kind of a weird but convenient place for the tests since it intersects with additions to the profile :/
