### ISSUE TITLE
Host Trailhead images on CDN for emails

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#1111]
From https://github.com/mozilla/fxa/pull/1087 we will need to host the Trailhead logo and connect another devices images.

This is similar to https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/senders/partials/base/base.html#L15 which I'm guessing we shall be able to host under same images domain?

This is waiting on the svg graphics.

**Comment by vbudhram** [comment]
Hey @jbuck @jrgm, when you get a moment can you host the attach images [email-images.zip](https://github.com/mozilla/fxa/files/3183924/email-images.zip) to `https://image.e.mozilla.org/lib` or someplace similar?

**Comment by jbuck** [comment]
I've emailed bhaack to do the image upload

**Comment by jbuck** [comment]
bhaack has reported back that SFMC doesn't support SVG images - could we get a PNG version at the appropriate size(s)?

**Comment by vbudhram** [comment]
This has been fixed, images have been hosted:

firefox-masterbrand.png
https://image.e.mozilla.org/lib/fe9915707361037e75/m/4/096479d0-ac88-4108-9620-e00d565d2189.png

firefox-masterbrand@2x.png
https://image.e.mozilla.org/lib/fe9915707361037e75/m/4/11c1e411-7dfe-4e04-914c-0f098edac96c.png

choose_which_to_sync_devices@2x.png
https://image.e.mozilla.org/lib/fe9915707361037e75/m/4/9f34e2a3-7947-4b5b-9c73-98faf8f49df6.png

choose_which_to_sync_devices.png
https://image.e.mozilla.org/lib/fe9915707361037e75/m/4/5dfd63b6-6498-4504-aa8a-5801622b704f.png
