### ISSUE TITLE
Vailidation error, `"deviceId" must be a string`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11134]
See https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/9592006/

Looks like deviceId is showing up as `None`. During triage, Vijay mentioned this might be because a push notification is attempting to occur when there isn't a device available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4258)

**Comment by LZoog** [comment]
Related, at least as far as `deviceId` goes: #13031

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
