### ISSUE TITLE
[Train 137]"Terms of service" and "Privacy Notice" - right aligned on Manage account page

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1114]
Environment:
Android, Win10
Stage server - Train 137

Steps to reproduce:
1. Log in with a Firefox account;
2. Go to Manage account page;
3. Scroll to the bottom of the page.

Expected results: "Terms of service" and "Privacy Notice" are on the center of the page.

Actual results: "Terms of service" and "Privacy Notice" are right aligned on the page.

Screenshot: 
![Screenshot_2019-05-15-16-00-35](https://user-images.githubusercontent.com/24588037/57786777-c813e180-773c-11e9-9b98-39bc941f2e8a.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-88)
┆Issue Number: FXA-88

**Comment by SorinaFlorean** [comment]
On https://drive.google.com/drive/u/1/folders/1QgDyzTzUAtOV8TuYkiDLMZ3sUNJ-hNwJ, both "terms of service" and "privacy notice" are right aligned, but on iOS are centered. Wouldn't look much better if there were centered? @shane-tomlinson what do you think?

**Comment by shane-tomlinson** [comment]
> both "terms of service" and "privacy notice" are right aligned, but on iOS are centered. Wouldn't look much better if there were centered? @shane-tomlinson what do you think?

It would be, I made the same comment [over in the original PR too](https://github.com/mozilla/fxa/pull/864#issuecomment-486090848). I thought this was fixed, I mustn't have re-tested thoroughly enough.
