### ISSUE TITLE
[FxA-Settings] Mistyped email warning message is not translated when Arabic language is selected

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11164]
**Build:**
Stage (Train 220)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.8

**Steps to reproduce:**

1. Set the browser's language to Arabic.
1. Navigate to https://accounts.stage.mozaws.net/ and enter an email address with a wrong domain name.
1. Click “Continue” button.
1. Observe the warning message displayed.

**Actual result:**
The warning message is not translated in Arabic.

**Expected result:** 
The warning message is translated in Arabic.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4266)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18201">arabic - no translation mistyped email.PNG</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Firefox Accounts is only 40% translated into Arabic ( https://pontoon.mozilla.org/ar/firefox-accounts/ ), including this string ( https://pontoon.mozilla.org/ar/firefox-accounts/LC_MESSAGES/client.po/?search=mistyped&string=205806 ).  We generally don’t leave issues open for missing strings as it’s not something the engineering team can change.  We should close this, but leaving open as Lauren Zugai is still triaging.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
