### ISSUE TITLE
[Train 137][iOS] Mozilla logo not displayed on Sign in page

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1116]
Environment:
iOS - iPhone SE(12.1.4) 
Stage server - Train 137

Steps to reproduce:
1. Go to Sign in page.
2. Observe the Mozilla logo.

Expected results: Mozilla logo is displayed at the bottom of the screen, left aligned.

Actual results: Mozilla logo is not displayed.

iOS:
![Image-1](https://user-images.githubusercontent.com/24588037/57789302-512d1780-7741-11e9-9edf-e379b0c50587.jpg)

Android:
![Screenshot_2019-05-15-16-40-50](https://user-images.githubusercontent.com/24588037/57789340-64d87e00-7741-11e9-9b69-1900a4beeedf.png)

**Comment by clouserw** [comment]
This is by design.  /cc @johngruen just in case it's an accident
