### ISSUE TITLE
[iOS][Train 137] "Disconnect" word have no padding

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1117]
Environment:
iOS - iPhone SE(12.1.4) 
Stage server - Train 137

Steps to reproduce:
1. Log in with a Firefox account.
2. Go to manage account page.
3. Go to "Devices and &apps" sections and tap on "Show".
4. Observe the "Disconnect..." button.

Actual results: the content is at the margin of the box.

Screenshot: 
![Image-1 (1)](https://user-images.githubusercontent.com/24588037/57789923-8128ea80-7742-11e9-8a99-606a911e22f3.jpg)

**Comment by dannycoates** [comment]
I can't reproduce this as of train-138
