### ISSUE TITLE
Update Zendesk user on e-mail changes

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1118]
When a user's preferred e-mail changes, it should be set as the primary e-mail on any corresponding Zendesk user record that corresponds to it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-89)
┆Priority: Medium
┆Issue Number: FXA-89

**Comment by jackiemunroe** [comment]
Zendesk API Resources for managing User Primary Identifier (email) and searching users by custom fields:
https://developer.zendesk.com/rest_api/docs/support/users#search-users
https://support.zendesk.com/hc/en-us/articles/203663216#topic_pyt_m1s_vk
https://support.zendesk.com/hc/en-us/articles/226555868-Set-primary-email-for-a-user-via-API-
https://developer.zendesk.com/rest_api/docs/support/user_identities#update-identity

The custom field we will be using will be the firefox user id (Key: fxa_user_id). Feel free to contact me if you need any assistance.
