### ISSUE TITLE
[subplat] The checkout form should not consider an unverified stub account an "existing" Firefox account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11197]
When someone uses the checkout form to create an account and subscribe to a plan (the "new flow"), we check whether the email address belongs to an existing account.  And if so, we require the user to sign in before continuing to subscribe.

On the same form, we'd create a unverified, stub account on submit for the user as a FxA account is required for a Stripe customer.  When an subscription attempt fails, this stub account is considered an existing account on subsequent existing account checks.

STR:
1. Visit the checkout page for a plan
2. Use an email address that does not belong to any account in the testing env 
3. Use `4000000000000341` for the CC number
4. Fill out the rest of the form with valid values
5. Submit the form
6. Dismiss the error message by pressing "Try again"
7. Place a cursor into the first email address input and then tab out of it, or repeat steps 1 and 2 by reloading the page or using a new tab

Expected:
The user is allowed to the use the same email address that was previously used in the failed subscription attempt

Actual:
The user is told that they have an existing account, despite that the user never set a password or verified the email address.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4273)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

We need to determine whether or not we can delete an account. If this occurs because of a pending authorization, deleting the account will cause them to lose access when the payment may eventually complete.

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-GC](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/15647824/?referrer=github_plugin)

This was previously linked to #10303, but we're still seeing the error after the fix for that ticket got into prod, so I'm linking the second ticket in its place in Sentry to more easily track whether it is resolved once this issue hits prod in Train 226.
