### ISSUE TITLE
GQL prod POST sentry error: Non-Error exception captured

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11191]
Non-Error exception captured with keys: code, errno, error, info, message

https://sentry.prod.mozaws.net/operations/fxa-graphql-prod/issues/11138784/?query=is%3Aunresolved

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4272)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
