### ISSUE TITLE
[subplat] The checkout form is retrying an existing invoice with a new Stripe customer 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11198]
STR:
1. Visit the checkout page for a plan
2. Use an email address that does not belong to any account in the testing env 
3. Use `4000000000000341` for the CC number
4. Fill out the rest of the form with valid values
5. Submit the form
6. Dismiss the error message by pressing "Try again"
7. Enter a valid CC number, e.g. (42)* and a zip code
8. Submit the form

Expected:
The user successfully subscribed to the plan.

Actual:
The user sees an other error.  This is due to a 400 response on a request to `/oauth/subscriptions/invoice/retry`.  In that request, the invoice id is from the initial subscription attempt, which belongs to another/the previous FxA user / Stripe customer.  (We create a new FxA user / Stripe customer pair on subscription retries from a new user.)

Additionally, the user will receive the welcome email even though the subscription failed.  That should not be the case.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4274)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Likely caused by what is happening in 4273. Possibly rectified by whatever we do to fix 4273.

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-FV](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/14925291/?referrer=github_plugin)

I'm hoping this error will be fixed with #11198 and #11197. Another instance of the same email address having multiple Stripe customers and uids all created on the same day within ~30 minutes. One customer has an active sub while the other doesn't.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Changed this to a 5 pointer since we are also sending the welcome email even though teh initial invoice hasn’t been paid.  In other words, while the user is getting an error on the browser, we are sending a welcome email.
