### ISSUE TITLE
Document Stripe triage process

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11190]
We're missing the Stripe triage portion of our triage doc: https://docs.google.com/document/d/1wfbNGg4OPL4UeZ6YPIiiuNSYDOSW21W_kF07vpRBIyg/edit#

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4271)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
