### ISSUE TITLE
Subscription cancellation email has incorrect details in German

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11205]
I just cancelled a German users yearly subscription on my end because the device is not compatible . I have refunded the amount and ended the subscription
the user got an auto mailer confirming the cancellation but it seems with the wrong content:
"*Your subscription has been cancelled.
We have cancelled your Mozilla VPN subscription because multiple payment attempts failed. To regain access, start a new subscription with an updated payment method."
Is anyone here who can review that the confirmation mailer in German are set up correctly ?

**Possible cause:**

We are sending the subscriptionFailedPaymentsCancellation email instead of the subscriptionCancellation

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4275)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18426">image-20211207-131437.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18453">image-20211208-145934.png</a>

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Rebecca Billings can we get QA to try to reproduce this please.

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

Madalin Cotetiu would you [or someone else on the team] please try to repro this?

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Hello,

I have tested this today by following the below steps:

  * created an yearly Mozilla VPN subscription using the DE Mozilla page and a VPN to locate me in Germany (using the conversion funnel flow - new subscription flow)
  * canceled the subscription from Stripe, immediately with refund for latest payment

This is the email that was received after canceling:

!image-20211207-131437.png|width=1519,height=510!

Translation:

Your subscription has been canceled
We canceled your Mozilla VPN subscription because multiple payment attempts failed. To regain access, start a new subscription with an updated payment method.

Please help us improve our services by completing this short survey.

Please let us know if there is anything else you need for this.

Thank you.

CC: Valentina Virlics Madalin Cotetiu

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Madalin Cotetiu Luminita Buruian would you be able to reproduce this using an EN locale (preferably EN_US) to see if you get a similarly incorrect email? Trying to narrow down if the wrong email is sent or if its a translation error?

Rebecca Billings for visibility.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Ivo Plamenac We have checked this today for an US account with French and a US account with English. The email content is the same, is does not seem to be a translation issue. See English email below.

!image-20211208-145934.png|width=1510,height=466!

Please let us know if you need anything else.

CC: Madalin Cotetiu Rebecca Billings

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Magdalena Schwaighofer How did you cancel. I tested this by logging into my staging fxa account, navigating to paid subscriptions, and pressing the cancel button on one of my subscriptions. I checked my email contents seemed correct “Sorry to see you go We’ve cancelled your Mozilla VPN subscription. Your final payment of $1.00 was paid on 03/29/2022. Your service will continue until the end of your current billing period, which is 03/30/2022.”

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

Hey Anna Sobiepanek  I cancelled the subscription in Stripe - we have no other way of cancelling a users subscription from support side, sorry if that wasn't clear. 

Also: this was an immediate cancellation and refund request within the 30 days - it was not set to cancel at the end of the subscription cycle.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
