### ISSUE TITLE
Subscription Manage button should only be visible to people with payments

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1120]
Right now we hide it from non-en_US, but really according to UX spec we should only show it to people that have an active subscription.

**Comment by lmorchard** [comment]
I think this is a dupe of #1078?

**Comment by ianb** [comment]
Oh cool, I forgot about this and suddenly remembered it, so I wanted to get it down before I forgot about it again, but didn't need to ;)

**Comment by clouserw** [comment]
removing estimate and epic since it's a duplicate
