### ISSUE TITLE
Align process for creation of recovery codes

### ISSUE THREAD

**Issue by dschom** [mozilla/fxa#11227]
## Description
Due to changes introduced while address #9530, we now generate recovery codes on the client side in the workflow that replaces Recovery codes (found in fxa-settings component Page2faReplaceRecoveryCodes). This means the same approach can be used for initialization of recovery codes (found in fxa-settings component PageTwoStepAuthentication). Doing so would allow the following things to be cleaned up:

* Removal of the GET /recoveryCodes end point in the fxa-auth server. 
* Removal of the code that generates recovery codes in the fxa-auth-server/lib/db (the functions replaceRecoveryCodes and createRecoveryCodes).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4286)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
