### ISSUE TITLE
Consolidate generation of randomized base32 strings

### ISSUE THREAD

**Issue by dschom** [mozilla/fxa#11225]
## Description

There are multiple places where random strings are generated, most of which are base32. These should be consolidated to the approach provided in fxa-shared/crypto/random. There are several reasons to do so. First, the base 32 strings found in that module are Crockford base 32 which is a nice UX touch. Secondly this code properly uses the crypto library as opposed to simply doing a math.random across a string array. Finally, that library can easily be put under test. 

There are also places where base32 strings are validated with a base36 regex. This is probably a by-product of some strings using Crockford base32 and others using regular base 32. Because of backward compatibility concerns this may never go away, but a best effort could be taken to phase out base36 validation where possible, e.g. when newly generated codes are provided to the server.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4284)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
