### ISSUE TITLE
[fxa] fxa_activity - oauth_access_token_created event uses the wrong region

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11222]
While working on FXA-4218, and I created a new FxA user in stage to test a BigQuery query for ops that filters metrics logs for user location (derived by their IP address). I am definitely in Pennsylvania, but I noticed there was one event in the results table, `fxa_activity - oauth_access_token_created`, where the `region` was listed as Virginia.

Below is the query I used:

```
    SELECT
      jsonPayload.fields.user_id AS uid,
      jsonPayload.fields.region AS state,
      jsonPayload.fields.country,
      jsonPayload.fields.event_type
    FROM
      `moz-fx-fxa-nonprod-375e.fxa_stage_logs.docker_fxa_auth_20211202`
    WHERE
      jsonPayload.fields.user_id='f88452c6257647d796b6f8826cbf57fe'
      AND jsonPayload.fields.region IS NOT NULL
      AND jsonPayload.fields.country IS NOT NULL;
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4280)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Per jbuck, our stage servers are hosted in AWS in Virginia.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Lauren Zugai / Danny Coates : I noticed this was triaged to an S4, but I’m concerned perhaps the issue is higher severity than that for a few reasons:

  * Even after omitting this event from my ticket (FXA-4218), I still see a lot of likely erroneous location data for Virginia, US from other metrics events after querying our prod logs, so it seems more widespread.
  * This location data is derived from the client’s IP address, which IIUC is used for:
    * Fraud detection (CC Benjamin Bangert )
    * Determining suspicious logins at least for Sync.
    * Setting the user’s locale (which I don’t think we have a mechanism to change after the fact).

What do you think?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
