### ISSUE TITLE
[Train 137] Primary and the secondary account is the same after tapping on "refresh status"

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1123]
Environment:
iOS - iPhone SE(12.1.4), Android, Win
Stage server - Train 137

Steps to reproduce:

1.Log in with a Firefox account on all platforms.
2. Go to manage account page -> Secondary email.
3. Add and verify the new secondary email.
4. Tap on "Make primary" on desktop.
5. On iOS and Android tap on "Refresh status".

Expected results: The secondary account is now the primary account.

Actual results: The primary and secondary account is the same.

Video:
https://drive.google.com/open?id=1Z0WX_At6AGZFkAfaWYwFg8EXbP59ZYFM

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-90)
┆Issue Number: FXA-90

**Comment by clouserw** [comment]
@vbudhram to investigate.  Are we sure this wasn't just slow to change?
