### ISSUE TITLE
Delete Stripe Account Info Locally If Subscription Fails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11268]
We are getting errors trying to find accounts locally after their subscription failed (due to insufficient funds).
We should clean up the local records/data to avoid throwing this error.

https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/15647824/events/84029870/

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4296)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
