### ISSUE TITLE
The 'Sign-out' button doesn't appear on Manage Account

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1126]
Environment:
Builds: Stage [Train 137], production;
Devices: Windows 10 ;

Prerequisites:
You are logged on a valid account.

Steps to reproduce:
1. Go to Manage account;
2. Watch the right part of the site;

Expected results:
1. A 'Sign-out' button is presented;

Actual results:
2. The 'Sign-out' button is not presented;

Notes:
![Screenshot_12](https://user-images.githubusercontent.com/40264165/57863435-c280cf00-7802-11e9-98dc-d0828dedc628.png)
- Train 137
![Screenshot_13](https://user-images.githubusercontent.com/40264165/57863477-da585300-7802-11e9-9529-3f7a479681a5.png)

**Comment by clouserw** [comment]
This is by design, if you are logged in from the browser.  Please reopen if that's not the STR.
