### ISSUE TITLE
[FxA-Settings]“This email was already verified by another user” warning message is not localized

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11277]
**Build:**
Stage (Train 220.5)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Preconditions:**
No secondary email is added.

**Steps to reproduce:**

1. Launch Firefox using a fr, ge, cy, etc. build (or set the desired language from about:preferences -> Choose your preferred language for displaying pages).
1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in using an existing account.
1. Go to "Secondary email" section and add an email that was already added as a secondary email by another account.
1. Observe the warning message displayed.

**Actual result:** 
The warning message and its tooltip “This email was already verified by another user” are not translated in the corresponding language.

**Expected result:**
The warning message and its tooltip “This email was already verified by another user” are translated in the corresponding language.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4298)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18454">2ndary email message not translated to French.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18455">2ndary email message not translated to german.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
