### ISSUE TITLE
Protect against some out-of-order messages for incoming SQS subscription messages

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1129]
This is a followup to #1122

We protect against an out of order message where there's a unsubscribe message generated at T-3, received at time T, and a subscribe message generated at T-2 and delivered at T-1. In this case we keep the subscription.

The other order however doesn't work, where there's a subscribe at T-3, received at time T, and an unsubscribe at T-2 received at time T-1. This isn't as bad (at least no one's subscription is invalidly cancelled). We don't have a record in auth-server of the unsubscribe time, which makes this out-of-order situation harder to catch.

See this test:
https://github.com/mozilla/fxa/blob/7fc6afadb10c800ea11fcb72e66facd5c8f44f9a/packages/fxa-auth-server/test/local/subhub/updates.js#L97-L117

And this code for the first case: 

https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/subhub/updates.js#L45-L56

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-91)
┆Issue Number: FXA-91

**Comment by lmorchard** [comment]
Would a sync algo ala Issue #1148 help here? i.e. any change event results in not an add or delete but a full comparison against current stripe/subhub and FxA state and any necessary reconciliation.

**Comment by clouserw** [comment]
This is blocked on architecture 2.0
