### ISSUE TITLE
[fxa-content-server] The /pair may still fail with 'Unverified session'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1130]
![image](https://user-images.githubusercontent.com/128755/57887602-dc6be300-77fd-11e9-9c1c-f5d14b6c0812.png)

Vesta has reported in Slack that she got a `Unverified session` when going to `/pair` on 

```
{
  "commit": "39875bc8cc974987cbccf8bd543a6220ccad8938",
  "version": "1.136.5",
  "l10n": "cba64f5829a9fa89d3d329b904725c5a6b383ef9",
  "tosPp": "e25ae12c4465163f2021d52899d7ed5947d2bcc0",
  "source": "https://github.com/mozilla/fxa"
}
```

@shane-tomlinson @rfk Should we be worried that this conditional is not enough https://github.com/mozilla/fxa/blob/dcf8db2529513409bfa767840ef56b281f9f1b18/packages/fxa-content-server/app/scripts/views/pair/index.js#L37  ?

**Comment by rfk** [comment]
Hrm, does `account.get('verified')` tell you whether the *account* has been verified or whether the *session* has been verified?

**Comment by vladikoff** [comment]
yea it could be the fact that this is not the `sessionStatus`

**Comment by vladikoff** [comment]
We might be hitting this https://github.com/mozilla/fxa/blob/4e5eb5fcca7c4b30116d7962910dcfe698cb88e9/packages/fxa-auth-server/lib/routes/totp.js#L201

**Comment by vladikoff** [comment]
@shane-tomlinson I think we did this wrong https://github.com/mozilla/fxa/pull/1017/files#diff-4049384315c40af3b9b8f2c28a651eb3R728 because the `/pair` URL does not validate as `isDevicePairingAsAuthority` ( https://github.com/mozilla/fxa/commit/91cf730c4c3f01730545b92e2540323ce6fb55f1#diff-0370004e39359bfe3201953deacddcacR641 )

**Comment by vladikoff** [comment]
The fix we did was not enough, Firefox still uses the wrong  token
