### ISSUE TITLE
Fix customs-server test

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11320]
The "failed logins are cleared" test in `password_reset_clears_bad_logins.js` started being flaky. There's probably a race, either in the test or the server.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4315)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

From mtg:

Lets see if mocking Date would help this?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
