### ISSUE TITLE
chore(settings) Include currently ingored files in test coverage thresholds

### ISSUE THREAD

**Issue by dschom** [mozilla/fxa#11339]
## Description

This is a follow up to #10774. Now that test coverage thresholds are in place, we need to be proactive about maintaining test coverage.  The first task involves the following:
- Get rid of the directive that ignores non-testing files from the jest config (`!src/components/*(ScrollToTop|UnitRowRecoveryKey|PageAvatar|App)/*`). 
- Add tests to these files, so they meet the current thresholds.

### Expected result

Files that are not specifically for testing are all included in the test coverage checks. 
Passing threshold coverage.

_It's possible that some files need to remain ignored. Hopefully this is not the case, but if something simply cannot be put under test in a reasonable way, this can be raised as a potential exception._

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4325)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
