### ISSUE TITLE
QuotaExceededError: The quota has been exceeded.

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#11333]
This started on December 3 which might correspond to a release.

https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/15647771/?referrer=github_plugin

```
QuotaExceededError: The quota has been exceeded.
  at testStorage (./lib/storage.ts:95:15)
  at startApp (./lib/storage.ts:109:13)
  at testLocalStorage/< (./app.js:14:12)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4320)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
