### ISSUE TITLE
Error: Zendesk Error (422): Unprocessable Entity

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#11336]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11482422/?referrer=github_plugin

```
Error: Zendesk Error (422): Unprocessable Entity
  File "/fxa/node_modules/node-zendesk/lib/client/client.js", line 295, in checkRequestResponse
    error = new Error('Zendesk Error (' + statusCode + '): ' + failCodes[statusCode]);
  File "/fxa/node_modules/node-zendesk/lib/client/client.js", line 310, in requestCallback
    checkRequestResponse(self, response, result, function (err, res) {
  File "/fxa/node_modules/node-zendesk/lib/client/client.js", line 128, in Request._callback
    return requestCallback(self, err, response, result, callback || stdCb);
  File "/fxa/node_modules/request/request.js", line 185, in Request.self.callback
    self._callback.apply(self, arguments)
  File "events.js", line 400, in Request.emit
...
(10 additional frame(s) were not displayed)
```

We should verify we are using the email update API correctly or determine if this has changed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4322)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Joseph Anthony Cuevas What would the consequences be if we had the wrong email for a user in Zendesk? Looks to be very infrequent right now.

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Per Joe: this is more of a headache for customer success because it’d break the history of the tickets. This needs testing though to confirm that the ticket can be submitted with the correct email address. Whoever does testing, please coordinate with Joseph Anthony Cuevas .

**Comment by chenba** [comment]
Sentry issue: [FXA-AUTH-PROD-N0](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/17836899/?referrer=github_plugin)

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-N8](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/17956617/?referrer=github_plugin)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
