### ISSUE TITLE
Show oauth errors on fxa

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11342]
Instead of redirecting straight back to the relying party when an authentication error occurs we should show the error on an fxa error page and link back to the RP. This is an anti-phishing measure that we'll need if we allow 3rd party RPs and a good practice anyway.

https://www.proofpoint.com/us/blog/cloud-security/microsoft-and-github-oauth-implementation-vulnerabilities-lead-redirection

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4328)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

This came out of a security issue, not super important right now since we don’t have 3rd party, but we will soon. We should show error on FxA and give option to go back to original RP.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
