### ISSUE TITLE
chore(settings) Improve test coverage

### ISSUE THREAD

**Issue by dschom** [mozilla/fxa#11340]
## Description

This is a follow up #11339. Now that all files are under test, we would like to incrementally improve testing coverage. Currently, coverage varies between 45% and 65%. For the initial pass, let’s try to get coverage up to 65% for global coverage and component coverage on both branches and lines.

## Expected Result

- Thresholds are set 65% across the board (global & components, lines & branches).
- Thresholds are met.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4326)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
