### ISSUE TITLE
[FxA-Settings] “Account already exists” secondary email warning message not translated in the corresponding language

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11352]
**Build:**
Stage (Train 221)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Preconditions:**
No secondary email is added.

Steps to reproduce:

1. Launch Firefox using a fr, ge, cy, etc. build (or set the desired language from about:preferences -> Choose your preferred language for displaying pages).
1. Navigate to https://accounts.stage.mozaws.net/ and log in using an existing account.
1. Go to "Secondary email" section and add an email that was already added as a primary email by another account.
1. Observe the warning message displayed.

**Actual result:** 
The warning message “Account already exists” is not translated in the corresponding language.

**Expected result:**
The warning message “Account already exists” is translated in the corresponding language.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4331)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18632">2ndary email message not translated to german 2.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18633">2nd email warning message not translated French.PNG</a>

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

From mtg:

This should be translated so there might be something else going on? Might not have correct localization id or wrapped in Localized component.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by Gotstawork** [comment]
This article might have well been written in another language. Regardless of the number of times read it did nothing to solve the problem of trying to add a secondary email that returns: "Account already exists". I simply want to have a primary email that corresponds with the email I log in with. How do I fix this? I do have the option of changing browsers.
