### ISSUE TITLE
Firefox Relay product description on "Enter your email" page is not localized

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11351]
**Build:**
Stage (Train 221)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Preconditions:**
N/A

Steps to reproduce:

1. Launch Firefox with a new profile using a fr, ge, cy, etc. build (or set the desired language from about:preferences -> Choose your preferred language for displaying pages).
1. Navigate to https://accounts.stage.mozaws.net/ and observe the Firefox Relay product description.

**Actual result:** 
The Firefox Relay product description is not translated in the corresponding language.

**Expected result:**
The Firefox Relay product description is translated in the corresponding language.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4330)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/18630/FF+Relay+text+not+translated.PNG">FF Relay text not translated.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/18631/FF+Relay+text+not+translated+Ge.PNG">FF Relay text not translated Ge.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/19872/Fr+text+translated+FF+relay.PNG">Fr text translated FF relay.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/19871/Ge+text+translated+FF+relay.PNG">Ge text translated FF relay.PNG</a>

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

From mtg:

These strings are translated but we haven’t pushed it yet, we wouldn’t find out until next push which would be next year.

**Comment by groovecoder** [comment]
Any update here? Are these localized now?

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

I verified this issue on stage [Train 224.1] under Windows 10 for all the languages that are 100% translated in Pontoon ( https://pontoon.mozilla.org/projects/firefox-accounts/ ) (FxA). I confirm that the description is translated for those.

!Fr text translated FF relay.PNG|width=380,height=497!

!Ge text translated FF relay.PNG|width=381,height=492!
