### ISSUE TITLE
Device manager (connected services) doesn't highlight my current device

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#11363]
## Description

When looking at connected devices/ services, it doesn't show me which one is my current device.

I had various work computers connected to my account with non-descript names and it was a pain to figure out which ones to disconnect. The top one on the list doesn't seem to be my current device either.

### Steps to reproduce

Visit device/service manager and observe that it doesn't display which is your current device.

### Expected result

It should be clearer. The old fxa preferences used to do this.

### Environment

It's the same when accessing fxa preferences from Mac or Windows from Firefox.
I navigated to the preferences through the hamburger menu.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4334)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
