### ISSUE TITLE
Fix hack in sync functional test

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#11368]
https://github.com/mozilla/fxa/pull/11302 includes a workaround for signing out of the browser because playwright isn't getting the push message to disconnect the device. This is probably from a line in the playwright browser config here: 

```js
pref("dom.push.serverURL", "");
```
https://github.com/microsoft/playwright/blob/main/browser_patches/firefox/preferences/playwright.cfg#L47

We should find a way to override that config. Unfortunately, I don't think [firefoxUserPrefs](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-firefox-user-prefs) can override it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4338)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
