### ISSUE TITLE
Device manager displays incorrect device name

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#11366]
The name of my iPad in the device list is incorrect. I suspect I changed the device name about 6 months ago (likely the day I set it up) but the change is not reflected in the device manager list. It still displays the default device name.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4337)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Ankita Shrivastava is this something you or QA team could reproduce?

**Comment by Bianca-O** [comment]
Hello,
I verified this on production [Train 221.0] and stage [Train 221.3] under Windows 10 64-bit and iOS 14.8 (iPhone 11). If I change the name of the devices that name is displayed in the Connected services list. See gif below:

https://user-images.githubusercontent.com/79697848/147061384-797e524c-4d3a-478e-9f27-3a6181b32a49.mp4

![device name changes](https://user-images.githubusercontent.com/79697848/147061068-97ffdb00-5172-40fc-8344-0b1cd07f2dd5.gif)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
