### ISSUE TITLE
Device manager (connected services) doesn't show the location of my devices

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#11364]
The locations of my devices are not being displayed. It somehow displays it for a 6 month old device though.

<img width="978" alt="Screen Shot 2021-12-16 at 9 54 57 AM" src="https://user-images.githubusercontent.com/19537086/146423752-f3b61061-2fc2-45fd-9118-9be26fd179d6.png">

### Expected result

I expect to be able to see the location of all of my devices so I can more easily tell if one of them might be malicious.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4335)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

Hey Alex, thanks for the report, this might be a dupe but we can look into it.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Drive by comment: it looks like this was probably an issue in old settings too, see this comment ( https://github.com/mozilla/fxa/issues/3577#issuecomment-568495934 ).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
