### ISSUE TITLE
Device missing from device manager (connected services)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#11365]
In the screenshot below, I am accessing the device list from my former Mozilla MBP laptop that I re-installed 6 months ago. It has the same name as it did before I left Mozilla. (i.e. Hulkbuster)

When I look at the device list, it doesn't display my current device. It's nowhere to be found. It displays my old device (and its location). Perhaps it's because they have the same name?
<img width="978" alt="Screen Shot 2021-12-16 at 9 54 57 AM" src="https://user-images.githubusercontent.com/19537086/146425331-a9c0c230-48ff-4626-803e-2b18a1049685.png">

(note that the other desktop is a different computer which was initially hard to identify due to the fact I had many of them connected. I filed a different bug about that.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4336)

**Comment by davismtl** [comment]
I proceeded to signing out the old MBP device. When doing so, it refreshed the device list and my reinstalled MBP started to show up in the device list. 

<img width="963" alt="Screen Shot 2021-12-16 at 10 06 13 AM" src="https://user-images.githubusercontent.com/19537086/146425524-4e34e8db-b8d7-4ebc-880b-35a67394690d.png">

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

From mtg:

Unfortuantely, we roll up sessions in scenario scenarios in the new settings page. This is something we could improve.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
