### ISSUE TITLE
Investigate/add formatting for MJML/EJS files

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11428]
When working on the new MJML email templates we can’t leave prettier to auto format or else it does some not particularly nice looking formatting...

Before auto format (sorry, Jira won’t let me format as nicely as the one below it for some reason):
{{<%# This Source Code Form is subject to the terms of the Mozilla Public

1. License, v. 2.0. If a copy of the MPL was not distributed with this
1. file, You can obtain one at http://mozilla.org/MPL/2.0/. %>

<mj-section>
  <mj-column>
    <mj-text css-class="text-header"><span data-l10n-id="verify-title">Activate the Firefox family of products</span></mj-text>
  </mj-column>
</mj-section>

<mj-section>
  <mj-column>
    <mj-text css-class="text-body"><span data-l10n-id="verify-description">Confirm your account and get the most out of Firefox everywhere you sign in starting with:</span></mj-text>
  </mj-column>
</mj-section>

<%- include('/partials/location/index.mjml') %>
<%- include('/partials/button/index.mjml') %>
<%- include('/partials/automatedEmailNoAction/index.mjml') %>}}

After current auto format:

```
<%# This Source Code Form is subject to the terms of the Mozilla Public #
License, v. 2.0. If a copy of the MPL was not distributed with this # file, You
can obtain one at http://mozilla.org/MPL/2.0/. %>

<mj-section>
  <mj-column>
    <mj-text css-class="text-header"
      ><span data-l10n-id="verify-title"
        >Activate the Firefox family of products</span
      ></mj-text
    >
  </mj-column>
</mj-section>

<mj-section>
  <mj-column>
    <mj-text css-class="text-body"
      ><span data-l10n-id="verify-description"
        >Confirm your account and get the most out of Firefox everywhere you
        sign in starting with:</span
      ></mj-text
    >
  </mj-column>
</mj-section>

<%- include('/partials/location/index.mjml') %> <%-
include('/partials/button/index.mjml') %> <%-
include('/partials/automatedEmailNoAction/index.mjml') %>
```

I believe there was also at least one case where leaving it autoformatted like so^ caused issues functionally before we disabled it, but I can't recall what that was. We need to investigate and implement a nicer looking autoformat for these files.

I'm hoping there's some sort of prettier config we can set for MJML, even if it's to tell it to treat it as something like HTML and then set specific formatting for HTML in the auth server. It _may_ be possible to make the extension .ejs instead, but I'm not certain (would that still work with our Storybook set up?) and it'd touch a lot of files (maybe we could at least use `git mv` to make sure git doesn't show deletions/additions but file renamed), so that's probably not a good solution even if there is good formatting for .ejs including mjml.

We need to investigate what the best solution for this is and apply the format to all MJML files. Even a VS code extension to format for us is probably better than no solution, if a prettier solution doesn't exist and a VS code extension does then we can include it in the recommended vs code add ons for fxa.

If this doesn't appear supported at all, close this ticket with a summary comment with findings so we have it documented as to why we're not formatting these files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4357)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
