### ISSUE TITLE
Increase section padding to align with avatar

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1142]
Increase section padding from 16px to 32px on desktop so that aligns with the avatar.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/68213/57949650-ff0c0380-78b2-11e9-9081-379512907425.png">

On mobile, I think 16px across the board looks best.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/68213/57949728-37abdd00-78b3-11e9-8186-5026ae39a4df.png">

**Comment by ryanfeeley** [comment]
Looks like the section heading got the treatment, but the body did not. <img width="281" alt="Screen Shot 2019-06-11 at 10 21 40 AM" src="https://user-images.githubusercontent.com/68213/59279910-bdad1080-8c32-11e9-9874-c0e1a28b15a6.png">

**Comment by shane-tomlinson** [comment]
Already noted in #1555, closing.
