### ISSUE TITLE
Deploy UI changes for testing

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1145]
Deploy the PR in #1084 to a dev box for testing by QA.

Blocked by https://github.com/mozilla/fxa-dev/issues/455

**Comment by jrgm** [comment]
try deploying with the docker-ansible-2.8 branch from the https://github.com/mozilla/fxa-dev/pull/458 PR

**Comment by shane-tomlinson** [comment]
This is in latest.dev.lcip.org
