### ISSUE TITLE
Implement a subscriptions sync algorithm between auth-server and subhub?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1148]
While working through #719, it occurred to me that we could implement a small "sync" algorithm to help make subscriptions consistent between FxA, subhub, and Stripe:

1. Fetch all the subscription rows for a user from FxA database
1. Fetch the customer record from subhub, which includes current subscriptions
1. Compare the two lists
1. Where subhub reports a subscription ID that FxA doesn't have, create the corresponding FxA subscription
1. Where FxA reports a subscription ID that subhub doesnt have, delete the corresponding FxA subscription

I imagine this wouldn't run very frequently per user, but it would be interesting to work out where it would be useful to do so. For example, on a visit to the payment pages with a fresh access token might be a good point to run it - that might help resolve any inconsistencies just before a user tries to manage subscription.

This would be in addition to #713 as a kind of belt-and-suspenders way to maintain consistency

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-92)
┆Priority: Medium
┆Issue Number: FXA-92

**Comment by lmorchard** [comment]
@ian and @bbangert might have thoughts on this.

**Comment by bbangert** [comment]
I think this makes sense to do on-demand during login and/or visiting the Account Management page. This provides another way to ensure any event handling mismatches repair themselves quickly.

1) On account management load, if SubHub subscription status doesn't match local, then
2) Generate subscription state change event (#1103) to force RP syncs

We should also ensure that any means we have that a user can trigger to force sync should be known by Support so that any issues a user may experience with inconsistent subscription status propagation can be easily resolved for the few users that may be affected.

**Comment by lmorchard** [comment]
Haven't looked at this issue in awhile, but the thing I've been thinking lately: We probably want to drop the subscriptions table in FxA auth-server altogether.

All the relevant information for subscriptions is in the subhub customer record. So, auth-server should just cache this resource to save traffic against subhub & stripe, then use *that* data to calculate subscription capabilities. That way, there's no granular *sync* per se, just cache revalidation

**Comment by bbangert** [comment]
I'm fine caching it, though just like with the other cache issue in profile-server, we need some fairly well defined policies for when the cache is cleared, and mechanisms that will guarantee a clearing of it if a user experiences a problem.

**Comment by lmorchard** [comment]
More thinking: Writing a sync algo for the current DB arrangement would be quicker than switching to a cache of customer data.

So I think I'm going to open a different issue for that - maybe we can move to that as a part of #2026 since the subhub APIs may change fairly significantly by then anyway.

**Comment by lmorchard** [comment]
Closing in favor of #3808
