### ISSUE TITLE
Better organize email tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11489]
The test for the new email templates are all included in `fxa-auth-server/test/local/senders/mjml-emails.ts`. While it was adapted from the test for the previous email template, there is room for improvement (e.g., separating tests to individual files and/or directories), as there is currently a lot of repetition.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4377)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
