### ISSUE TITLE
[subplat] "Reactivate subscription" link label and redirection could be improved

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11488]
**Build:**
Stage (Train 222)

**Affected platforms:**
Windows 10 64-bit

**Preconditions:**
The user has made a subscription for a product using a card that expires at the end of the month.

Steps to reproduce:

1. When the month is over go to your inbox and verify the content of the email "Your {product name} subscription has been cancelled".
1. Observe the "Reactivate subscription" link in the footer.
1. Click the link.

**Actual result:** 
"Reactivate subscription" link is displayed and redirects the user to Settings page.

**Expected result:**
The name of the link could be improved. We think "Resubscribe" is more appropiate in this context than "Reactivate subscription".
The link redirects the user to the product homepage, pricing section.

**Note:**

“Update billing information“ link is also redirecting to Settings page.

Same issue occurs for subscriptionCancellation template.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4376)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18915">label improve.PNG</a>

**Comment by LZoog** [comment]
Note to subplat triage folks: when we confirm we want to do this, let's wait on fixing until new templates are in production so we don't have to fix this in the old _and_ new templates.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Resubscribe and reactivate are two different things.  Once the subscription ended, it’s resubscribe, but before that, it’s reactivate.  Currently we do not handle the resubscribe use case.

For this to work, that is, a link that can handle both reactivate and resubscribe, we need some logic to determine which we need and redirect/handle accordingly.  We don’t have anything like that at the moment.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Brian Yee What do you think?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Whoa ok, I’m very sorry, I must’ve crossed some wires in my brain.  Yes, for this particular email, a Resubscribe link that take the user to product checkout page make sense.

Brian Yee Sorry, I described the wrong thing to you earlier.  (It was still accurate, it was just not the use case this issue is referring to.)

**Comment by data-sync-user** [comment]
➤ Brian Yee commented:

So after a user is out of contract,  they get an email that gives them a “resubscribe” button…which then goes to the product checkout page.   Makes 100% sense.  Thanks Barry Chen

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
