### ISSUE TITLE
[FxA-Settings] "Continue" button in 2FA recovery codes confirmation page (when replacing the existing codes) has different size and it's not colored

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11511]
**Build:**
Stage (Train 222)

**Preconditions:**
2FA is enabled.

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and log in using an existing account.
1. Go to 2FA section and click “Change” button.
1. Click “Change” again in the “Change recovery codes?” modal.
1. Observe the “Continue” button and compare it with the “Continue” button from the 2FA page when codes are generated for the first time.

**Actual result:**
The “Continue” button has a different size and it is not colored.

**Expected result:**
The “Continue” button has the same size and it is blue.

**Additional note:**
The number of recovery codes displayed is different than in the 2FA page (when codes are generated for the first time). It is larger than 3. On Stage there should be only 3.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4383)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/18977">replace recovery codes button issue.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
