### ISSUE TITLE
Audit the existing content-server functional tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11528]
We currently manually shard our content server functional tests into six buckets on circleci.  We also have functional tests in playwright which don't necessarily overlap, but may.  I'd like to audit all the functional tests with a goal of identifying/determining:

* Test is effecient, useful, **isolated**, and appropriate in scope
* Test should be modified to become ^
* Test should be deleted

Eventually we'd like to replace all the old functional tests with equivalent tests in playwright that are able to run in parallel.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4393)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
