### ISSUE TITLE
Propagate `style` query parameter to backend to control email styling

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1152]
With #1073, several emails will support Trailhead styles. We need to pass the `style` query parameter to several backend calls so the correct emails are sent.

Will require updates to the content server and fxa-js-client.

**Comment by vbudhram** [comment]
Whoops didn't see this was assigned to you, I've got a PR for it over in https://github.com/mozilla/fxa/pull/1221.

**Comment by shane-tomlinson** [comment]
This is done and verified. Closing.
