### ISSUE TITLE
Enable parallelization and sharding for playwright and unit tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11527]
Please enable [Parallelization](https://circleci.com/docs/2.0/parallelism-faster-jobs/) for the playwright and unit tests.  

Please enable [Sharding](https://playwright.dev/docs/test-parallel) for the playwright tests.

If the unit tests can't handle it, we can revert them and file a bug.  Thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4392)

**Comment by dannycoates** [comment]
We don't have enough tests to benefit from sharding yet. I increased parallelism to 3 which seems about the max a `large` instance can do https://app.circleci.com/pipelines/github/mozilla/fxa/26678/workflows/960db53c-08d0-43d4-a109-f0219deffa87/jobs/298881/resources 

As is right now with 3 workers the test execution accounts for only a little over one minute of the run time with the bulk being install and service startup.

After adding more tests it'll probably be best to increase the instance size and parallelism until we're max out there before we shard to multiple CI instances.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

In the original description I was talking about CircleCI parallelism.  At our scale there may be little difference but I’d be curious what benefits we’d gain by using that vs more workers on the same instance.  Is that something you’ve looked into?  At a minimum it seems like we could go over 3 (we’re paying for 200 with our plan).

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

For now our CircleCI run time is dominated by the serial parts, 5 of the current 6 minutes won’t benefit from CI parallelism. We should enable CI parallelism / playwright sharding when the test time dominates the run time.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Please also review FXA-2927

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

one more try: FXA-4478
