### ISSUE TITLE
Creating FxA account using @mozilla domain doesn’t work

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11540]
**Affected browsers:**

* All;

**Affected FxA versions:**

* 1.223.0;

**Prerequisites:**

* Be in a country where Mozilla VPN is available;
* Be on the FxA Account Sign Up page; 

**Steps to reproduce:**
1. In https://accounts.stage.mozaws.net/signup type an email address which is part of the @mozilla.com domain;
2. Fill all mandatory fields;
3. Click “Create account” button;

**Expected result:**

* The account is created with success;

**Actual result:**

* An error message is displayed;

**Additional notes:**

* this is a qa-blocker issue for QA as we are not able to test couponing feature completely;
* this is a qa-blocker for users because they cannot create an account or make a subscription as long as they use a @mozilla email address;
* see the attached screenshot;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4400)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/19023/Screenshot+from+2022-01-06+16-13-55.png">Screenshot from 2022-01-06 16-13-55.png</a>

**Comment by LZoog** [comment]
Thanks for filing. We have a patch in place and this will be fixed with a dot release this morning very soon. I'll manually verify it's working as expected and close this out then.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

This is verified as fixed in FxA Train 1.223.1 - Staging using Firefox, Safari and Chrome browsers.
