### ISSUE TITLE
[subplat][email templates] Text in HTML version and plaintext could be improved for subscriptionAccountReminderFirst template

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11555]
**Build:**
Stage (Train 223.1)

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest version

**Prerequisites:**
Have VPN set in a country where Mozilla VPN is available.
The user doesn't have a Firefox account.

**Steps to reproduce:**

1. Navigate to [https://www-dev.allizom.org/en-US/products/vpn](https://www-dev.allizom.org/en-US/products/vpn).
1. Click Get Mozilla VPN and then select a plan.
1. Fill in a valid email address that doesn't have associated a FF account.
1. Complete the subscribing process.
1. Wait a day until you receive the "Reminder: Finish setting up your account" email.
1. Observe the HTML version.

**Actual result:**
The text in the HTML version could be improved. The user didn't set up a password yet so he doesn't have what to reset.

**Expected result:**
The text in the HTML version is more appropiate.

**Notes:**

Same issue occurs for **plaintext version**.

! Another issue was filed for differences between HTML and plaintext [here](https://mozilla-hub.atlassian.net/browse/FXA-4405). Fixing this ticket might fix the other one too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4406)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19081">accountReminderFirst HTML text issue.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19082">plaintext version issue.PNG</a>

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Bianca Oltean  , we have added this to our Confirmation Needed doc. Thank you for bringing this to our attention!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
