### ISSUE TITLE
[subplat][mobile] Thank you container is larger than the other containers on the page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11557]
**Affected versions**:

* All;

**Affected FxA versions**:

* 1.223.1;

**Affected Platforms:**

* Android and iOS;

**Prerequisites:**

* Have one FxA account without subscription;
* Be in a country where VPN is available;

**Steps to reproduce:**
1. Perform a subscription using a mobile device;
2. Take a look at the containers on the Subscription Confirmation page;

**Expected result:**

* The containers have the same size and shape throughout the page;

**Actual result:**

* The Thank you container is larger than the other containers on the page (Subscription Confirmation container and Mozilla VPN product container);
Please see more in the attached video.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4408)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19085">20220107_153726.mp4</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
