### ISSUE TITLE
Install grunt-cli as a per-repo dependency?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1156]
Over in https://github.com/mozilla/fxa/pull/1155 I added a comment about installing grunt-cli globally, which @lmorchard pointed out would break if we ever depended on particular versions in particular repos.

Should we add grunt-cli as a dev dependency in the repos that need it so that we don't cause bustage?

**Comment by clouserw** [comment]
Let's not have different versions for each repo. :)

**Comment by shane-tomlinson** [comment]
Re-opening, we have at least one case where not [having grunt-cli installed in a repo causes test failures](https://github.com/mozilla/fxa/commit/a9340e18121dd98639ae6ec4962882f7a6e33845#commitcomment-33629661).

**Comment by 6a68** [comment]
I'm running into errors running the fxa-js-client tests in the monorepo, and it seems to be connected to this issue. I'm not sure why this was re-closed, so I'm re-reopening.

**Comment by 6a68** [comment]
Hmm, on second thought, I'll just open a fresh bug.
