### ISSUE TITLE
Update password reset warning to call out Pocket

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#11572]
Update our password reset langauge to meantion no data will be lost for Pocket.

```
When resetting your password, you may lose logins and bookmarks saved in Firefox — Pocket data will not be affected.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4415)

**Comment by chelsea-lewis** [comment]
@vbudhram Copy approved by Pocket Product (ehellweg) [here](https://mozilla.slack.com/archives/C022HUNDWTB/p1641853693090700?thread_ts=1641595663.076100&cid=C022HUNDWTB), we can proceed with this ticket.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Thanks Vijay 🙂

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This change is verified on stage [Train 224.1] under Windows 10 64-bit and iOS 15.2. I confirm that the new text is added to Reset password and Create new password screens.

!reset pwd - pocket mention.PNG|width=391,height=470!

!create new pwd - pocket mention.PNG|width=406,height=485!
