### ISSUE TITLE
Propagate `style` query parameter to metrics

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1157]
Brought up by @philbooth in https://github.com/mozilla/fxa/pull/1154#issuecomment-494012857, and seems like a totally sensible idea.

I'm not sure what all is involved here, so haven't given it an estimate.

**Comment by philbooth** [comment]
- [ ] Add `style` to `event_properties` in `fxa-shared`.
- [ ] Include `style` in the payload to `POST /metrics`.
- [ ] Ensure the content server backend is passing `style` to the Amplitude code in `fxa-shared`.

Estimating `3` based on the above.

**Comment by clouserw** [comment]
We can track this via the initial entrypoint already, so marking this as a P2

**Comment by clouserw** [comment]
Closing this in favor of the Skyline deliverable to get trailhead styles everywhere.
