### ISSUE TITLE
Make difference between recovery codes and recovery keys clearer

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11590]
It seems like the discrepancy between 'recovery key' and 'recovery code' may be confusing to some people. 

Adjust the wording so that we refer to ‘recovery keys’ as ‘account recovery keys' and make places where 'recovery codes’ are required more explicit. 

Acceptance criteria:

* All instances of the term ‘recovery keys’ are replaced with ‘account recovery keys’
* On the screen where recovery codes are requested, the instructions should be: 
Please enter a recovery code that was provided to you during setup of two step authentication.

Note:

_Here’s the related Bugzilla ticket that spawned this. (note that it’s just a single user):_
[https://bugzilla.mozilla.org/show_bug.cgi?id=1728356](https://bugzilla.mozilla.org/show_bug.cgi?id=1728356)
[https://bugzilla.mozilla.org/show_bug.cgi?id=1747669](https://bugzilla.mozilla.org/show_bug.cgi?id=1747669)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4423)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19275">Screenshot from 2022-01-12 15-20-33.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19277">Screenshot from 2022-01-12 15-20-59.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19276">Screenshot from 2022-01-12 15-21-39.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19278">Screenshot from 2022-01-12 15-25-03.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
