### ISSUE TITLE
Investigate issue with Pocket Kobo reader and FxA

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#11593]
See slack [thread](https://mozilla.slack.com/archives/C022HUNDWTB/p1641920402124600), but Pocket Kobo reader does not work with FxA Oauth flows. This is most likely because they do not support some javascript methods.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4426)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Note this is not blocking for the Jan 18th pocket launch - this is noted as having been broken in production since Nov 2021.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

I’m going to wontfix this until/unless Daniel Brooks and team lets us know that we should move forward.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Currently declining as this is a bit of a can of worms based on kobo's lack of extensive javascript support. Letting our colleagues at Pocket take the lead on what next steps will be to support, and will reopen if that is proven fruitful. Thanks!
