### ISSUE TITLE
Implement GET /oauth/clients for full RP list with subscription capabilities

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1159]
The event broker needs access to a list of all the OAuth clients to determine which RPs to notify depending on subscription capabilities. This list should be secured behind an ops configured token.

**Comment by philbooth** [comment]
Adding some context from the meeting:

* Response should be the static list of capabilities from config.
* Authentication should be some kind of shared secret internal thing.

**Comment by lmorchard** [comment]
It sounds like the data source for the response is [`config.subscriptions.clientCapabilities`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/config/index.js#L633). 

An example of this in use is [over here in `lib/routes/utils/subscriptions.js`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/utils/subscriptions.js#L18) where we calculate the intersection between subscription capabilities available to a user and capabilities relevant to a client.

**Comment by philbooth** [comment]
While implementing, it's occurred to me this endpoint will probably be easier to consume if it returns an array of `{ clientId, capabilities }` objects rather than a dictionary of `clientId:capabilities` mappings.
