### ISSUE TITLE
[subplat] Store Stripe webhook events in our database

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11591]
We get a lot of inquiries from our support staff e.g. for a PayPal user not receiving a refund, where the event in question occured well over the 15 day retention period that Stripe's dashboard has for webhook events. As a result, it can be very difficult to troubleshoot what may have went wrong, as we have no webhook event data to look at. For this reason, Stripe recommends we store this data in our database.

While we [recommended the support team update their process](https://mozilla.slack.com/archives/CG0AJ6E77/p1641926713047200?thread_ts=1641882494.043900&cid=CG0AJ6E77)[1] in this one specific instance, it doesn't solve the general issue.

[1]: Process change exerpt from the Slack conversation for posterity:
...[C]heck the invoice metadata for the paypalRefundTransactionId . This should be added [within a minute] to the invoice in Stripe. If it's not, please ask in the channel then.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4424)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
