### ISSUE TITLE
Adjust default download filenames for account recovery keys and two step authentication recovery codes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11614]
When users download their account recovery key or two step authentication recovery codes, the default filename is identical. Since there has been some confusion around the difference between recovery keys and recovery codes, having the download file name reflect what's being downloaded would be helpful.

Acceptance Criteria:

Case 1:

1. Go to the account settings page 
1. Enable recovery keys
1. In step 2, download the recovery key (click the down arrow)

Expect that the file downloaded file be called: $email Firefox Account Recovery Key.txt

Case 2:

1. Go to the account settings page
1. Enable 2FA
1. Follow through to step 2.
1. Download the recovery codes (click the down arrow)
Expect that file download be called: $email Firefox Recovery Codes.txt. 

Case 3:

1. Go to account settings page
1. For two step authentication, click 'change'.
1. Download the genereated recovery codes (click the down arrow)
Expect that file download be called: $email Firefox Recovery Codes.txt. 

Notes: 

* _$email is just a placeholder for the user's email._
* _Perhaps it should be Two Step Authentication Recovery Codes, rather than just Recovery Codes, but this is a rather long file name._

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4436)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
