### ISSUE TITLE
A response of success:false from /session/verify/totp goes unchecked

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11617]
This Bugzilla report surfaced a UI bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1739872. 

It appears that the 'success' field in the the response from /session/verify/totp goes unchecked, resulting in the behavior the user shows in their video capture.

Steps to reproduce

1. Make sure 2FA is disabled on your account
1. Make sure you have a OTP app on your machine (for example, on linux you could use otpclient) 
1. Set your system clock so that it's a few minutes fast.
1. Go to settings page, and enable 2FA.
1. Go through the steps using the OTP app on your machine. (This is important. The OTP application must be running a system with a clock that is off by a couple minutes.)
1. Fill in the provided code from the OTP app and finish the wizard.
1. Observe that it looks like 2FA has been successfully enabled.
1. Refresh the settings page and observe that the setting didn't actually stick.

Expected behavior: An error should have been displayed indicating that the code was not verified successfully.

Note:
Open dev tools so the response from `/session/verify/totp` can be observed. If the steps above were followed correctly, the body should be { success: false }

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4439)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
