### ISSUE TITLE
Investigate Auth database CPU spike in train 223

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#11612]
Reference slack [converstation](https://mozilla.slack.com/archives/CLV3KMZ8B/p1642013280203200) 

The new `fetchEmailBounces_2` stored procedure seems to be taking a lot longer than expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4434)

**Comment by jbuck** [comment]
@vbudhram noted that this isn't the first time we've run into this bug: https://github.com/mozilla/fxa/blob/9e781441883bc92c6b6442f000512ce780c548af/packages/db-migrations/databases/fxa/patches/patch-091-092.sql#L32 

After testing in stage we found that converting the table to `utf8mb4` fixed the performance issue: `ALTER TABLE emailBounces CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;` . I've applied this migration in prod as well, but @vbudhram will backfill a migration in a PR for completeness.
