### ISSUE TITLE
Remove recovery code count from deployment config

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11613]
The default for `fxa_auth::recovery_code_count` now defaults to 8 for stage and production. This is also the default value in the config file in the code, so there is really no reason for this config anymore.

This task is to phaseout the `fxa_auth::recovery_code_count` setting completely from /mozilla-services/cloudops-deploy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4435)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
