### ISSUE TITLE
Add check to validate users clock prior to enabling 2FA

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11616]
Two step authentication is time based. Therefore if the user's system clock is off, it can result in failing and/or strange behavior. (See this Bugzilla report: [https://bugzilla.mozilla.org/show_bug.cgi?id=1739872)](https://bugzilla.mozilla.org/show_bug.cgi?id=1739872))

Therefore, a safeguard should be put in place. There are probably several approaches to validating an end user's clock. As long as the approach ensures the clock is within a couple seconds of our servers clock, it is valid.

Acceptance Criteria:

* Routine is created that can validate the users system clock is within a few seconds of our server's clock.
* Use this routine when two step authentication is being enabled.
* If the users clock is detected to be out of sync. Issue an error/warning message.

Note: The user’s clock needs to be within 60s of the server’s clock. Therefore, simply comparing client and server timestamps is good enough.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4438)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
