### ISSUE TITLE
[subplat] null customer in some payment_method.card_automatically_updated webhook events

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#11611]
In some `payment_method.card_automatically_updated` webhook events the customer is null.  This causes an error with our attempt to backfill missing data based on the customer.  We should skip the event handling when the customer is null.

[https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/16941896/?referrer=github_plugin](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/16941896/?referrer=github_plugin)

```java
WError: An internal server error occurred
  ?, in Array.reduce
  ?, in new Promise
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe-firestore.js", line 88, in StripeFirestore.fetchAndInsertCustomer
    this.stripe.customers.retrieve(customerId),
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe-firestore.js", line 223, in StripeFirestore.insertPaymentMethodRecordWithBackfill
    await this.fetchAndInsertCustomer(paymentMethod.customer);
  ?, in runMicrotasks
...
(11 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4433)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Does a customer that is null mean the Stripe customer was deleted? Why might we still be getting a payment_method.card_automatically_updated webhook events for payment methods on deleted customers?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Payment methods are created by the front-end, they only require our public key, and then they’re in our account, floating around. They can be used as a one-off, or attached to a customer for repeating payments. We have a separate API the front-end calls that associates a payment method id to a customer, which we then attach on the back-end, if however that code errors, or doesn’t get called for whatever reason, then we end up with a payment method that has no customer. Stripe will then tell us when that payment method gets updated, which is what is happening, but we only care if its attached to a customer, so we can ignore these.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Ben; IIUC this also explains why we can have orphaned customers with no payment method. Since we get the zip code for Stripe customers off the payment method, if there isn’t one attached, we can’t lookup a state/province for example which is one of the failure modes we see in https://mozilla-hub.atlassian.net/browse/FXA-4446 ( https://mozilla-hub.atlassian.net/browse/FXA-4446|smart-link ) (see this comment ( https://mozilla-hub.atlassian.net/browse/FXA-4446?focusedCommentId=502829 ) specifically).
