### ISSUE TITLE
[pocket migration] After login the user is redirected to Pocket sign up page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11636]
**Build:**
Production

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
N/A

**Steps to reproduce:**

1. Navigate to [https://getpocket.com/login?__ffbp=temp.backend.web.fxa.upgrade.signin](https://getpocket.com/login?__ffbp=temp.backend.web.fxa.upgrade.signin). 
1. Enter your email address and click "Next" or use "Continue with Firefox button".
1. Enter your password and log in.
1. Log out.
1. Repeat steps 1-3 a few times.

**Actual result:**
The user is redirected to Sign up page instead of his account.

**Expected result:**
The user is redirected to his account.

**Additional notes:**
The issue is not always reproducible. I was not able to figure out the exact steps for reproducing. But it occured after I logged in and logged out a few times while testing the flows (more than 10 times logging in and out approximately)
It doesn't occur very often and it occurs only after playing with the flows for a bit.

It also happened on the sign-up server - [https://getpocket.com/signup?__ffbp=temp.backend.web.fxa_signup](https://getpocket.com/signup?__ffbp=temp.backend.web.fxa_signup|smart-link) .

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4442)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19359">user redirected to pocket sign up page .gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
