### ISSUE TITLE
String changes for subscription page

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#1163]
# Number One
On the actual payments page, this one:
![image](https://user-images.githubusercontent.com/80098/58046162-63b89f80-7af9-11e9-82de-db0a18fea040.png)
Please change this language:
> I authorize Mozilla, maker of Firefox products, to charge this payment method at $2 per month, according to `Payment Terms`, and until I cancel my subscription.

to this:
> I authorize Mozilla, maker of Firefox products, to charge this payment method at $2 per month each month until I cancel my subscription, according to `Payment Terms`.

# Number Two
In the receipt email, we currently say 
> Your payment is currently processing and may take up to four business days to complete.

Could we change that to 
> Your payment is currently processing and may take up to four business days to post to your account.

**Comment by lmorchard** [comment]
Is this related to #718? We haven't actually started putting final strings into the pages yet. Also, I thought payment-related emails (like receipts) were handled by another system
