### ISSUE TITLE
"Passwords do not match" warning displayed for the first password field

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11644]
**Build:**
Stage (Train 223)

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
Have the VPN set in a country where Mozilla VPN is available.

**Steps to reproduce:**

1. Navigate to https://www-dev.allizom.org/en-US/products/vpn and click "Get Mozilla VPN" button.
1. Select a plan.
1. Enter an email address that doesn't have associated a FF account and fill in all the other data to make a subscription.
1. Click "Subscribe now". 
1. Go to inbox and open the "Welcome to Mozilla VPN: Please set your password" email.
1. Click the "Create password" button in the email.
1. Enter different passwords in the 2 fields and click "Create Password".

**Actual result:**
The warning message is displayed for the first password field instead of the second one. Compare with "Create a Firefox account Continue to Firefox Accounts" page.

**Expected result:**
The warning message is displayed for the second field (the confirmation one).

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4445)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19441">Create a FF account page.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19442">warning displayed on 1st pwd field.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
