### ISSUE TITLE
Cannot find a postal code for customer cus_KvJ5Br8b6qjbMI

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fxa#11650]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/17125290/?referrer=github_plugin

```
Cannot find a postal code for customer cus_KvJ5Br8b6qjbMI
```

Let's remove the customer ID from the message name, so Sentry groups these errors together. Right now they're all treated as separate events.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4449)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Per this Slack conversation ( https://mozilla.slack.com/archives/C4D36CAJW/p1642720592086200 ), I plan to roll the message change into my current ticket, https://mozilla-hub.atlassian.net/browse/FXA-4454 ( https://mozilla-hub.atlassian.net/browse/FXA-4454|smart-link ).

CC Anna Sobiepanek , as this will add one point to the sprint. It shouldn’t affect my ability to close both of the tickets previously assigned to me, so I don’t plan to kick anything out. Please let me know if you disagree.
