### ISSUE TITLE
Admin Panel Autocomplete on email address not working

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11653]
Steps to reproduce:

* Go to admin panel
* Start typing email
* Observe that emails are suggested
* Open dev tools. Look at network requests and observe that graphql queries  to query getEmails() are returning empty responses

Expected result: List of suggested emails are returned

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4452)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Per triage meeting, sometimes this can take a very long time (40+ seconds?). We should probably just remove it.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
