### ISSUE TITLE
Update code around APIs to flag them as public use

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11667]
The APIs should have comments around them saying they are being used publicly and changes need to be managed/communicated according to our policies.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4458)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Right now none of our APIs are public.  The VPN team is planning on hitting our oauth endpoints directly so we need to flag them as public and start treating them that way.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
