### ISSUE TITLE
Add API consistency tests that alert for changes to public APIs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11668]
We should have some unit tests that run on APIs that external groups are using.  The tests should fail if the output changes and highlight that any changes need to be communicated to our notification list and follow our policies.  (then the test can be updated with the new changes)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4459)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
