### ISSUE TITLE
[subplat] Fix React unmounted component console warnings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11688]
When working in payments recently I saw at least 3 warnings in the console:

After signing up for subscription:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. in SubscriptionCreate (at Product/index.tsx:319)`

Cancelling a subscription:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. in CancelSubscriptionPanel (at SubscriptionItem.tsx:66) in div (at SubscriptionItem.tsx:60) in div (at SubscriptionItem.tsx:59) in SubscriptionItem (at Subscriptions/index.tsx:327) in div (at Subscriptions/index.tsx:287) in div (at Subscriptions/index.tsx:286) in div (at Subscriptions/index.tsx:215)`

I saw at least one other warning but am not sure how I pulled it up. It’s probably a good idea to click around different flows with the console open and see if there’s other warnings to fix too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4464)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
