### ISSUE TITLE
Broken login to addons.mozilla.com 

### ISSUE THREAD

**Issue by lovasoa** [mozilla/fxa#11708]
## Description

Login to addons.mozilla.com is broken for my account. Feel free to close if this is not the right place to report the bug.

Initially, I was reporting an infinite redirection on accounts.firefox.com after trying to log in from addons.mozilla.org. I logged out of accounts.firefox.com and logged in again, and the bug changed to the following.

### Steps to reproduce

1. I open https://addons.mozilla.org
2. I click "log in"
3. If I open my dev tools, I see the following URLs being loaded:
    
![image](https://user-images.githubusercontent.com/552629/150651950-c3ee2597-5e93-45d7-8a52-51caca1f783c.png)

4. I am redirected to the original page (https://addons.mozilla.org/en-US/firefox/) without being logged in.

If I try to reproduce in a private window, I get a different error: 

1. since I am not logged in on https://accounts.firefox.com in the private window, it asks me for my email address and my password.
2.  I give them, and then it asks me to add 2FA to my account. I have the choice between "cancel setup" and "continue". It is not clear to me whether "cancel setup" is meant to cancel just the setup of 2FA or the entire login procedure. 
3. If I click "cancel setup", I am redirected to addons.mozilla.org without being logged in
4. If I click "continue", it gives me a QR code. 
5. I scan the QR code in "google authenticator" on my phone.
6. google authenticator recognizes the code, and adds a new "Firefox" entry to my list of codes, associated with a 6-digit code
7. I enter the code below the QR code, and it tells me it is not valid. The code changes regularly, and I tried multiple times, entering the code as soon as it appears, and then  as soon as it changed, and the result is always the same.
![image](https://user-images.githubusercontent.com/552629/150652692-56d2e80a-4e41-477f-8139-5da39747811a.png)

### Expected result

After the final redirection, I should be logged in addons.mozilla.org 

### Actual result

I am not logged in. The page header still displays a "log in" button

![image](https://user-images.githubusercontent.com/552629/150652036-f4964425-c159-4f50-be80-b1b23d616b84.png)

### Environment

firefox 96 - fedora

![image](https://user-images.githubusercontent.com/552629/150652049-4c1c3b60-f9bb-4136-a36f-c436ab17857c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4470)

**Comment by lovasoa** [comment]
I tried to reproduce the issue in chromium, and accounts.firefox.com seems completely broken (CORS issue) in chromium : 

![image](https://user-images.githubusercontent.com/552629/150653067-3f738df0-9316-4d52-8daa-3a19cf2c93d2.png)

**Comment by LZoog** [comment]
Hey @lovasoa, will you check your computer's date and time? If it's too far off from our server's clock, it can cause issues with 2FA.

**Comment by lovasoa** [comment]
@LZoog : Thank you ! Resynchronizing my computer's clock with the network did not change the time in a visible manner, but it fixed the issue. The clock must have been just a few seconds off. Maybe fxa should check if the browser's time is not too far from the server and warn the user ? Because otherwise, I don't see how I could have fixed the problem on my own...

And since there seem to be a CORS error  when loading sentry, you would probably not have been warned either.

**Comment by lovasoa** [comment]
Do you want to keep this issue open to investigate the original error (not in a private window), where I was just redirected to amo without being logged in ?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
