### ISSUE TITLE
Update .prettierignore configs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#11702]
## Description

Another "peter classic"(tm). 
I'm still trying to understand where/if the linting is happening, and if we do it on CI or just via a Husky commit hook. But I was seeing one of the packages has a different <kbd>prettier</kbd> than the others. Which led me to figure out that Prettier was throwing formatting errors when trying to format .nsprc files and LICENSE files since they aren't recognized file extensions. Which then led me to discover that .prettierignore doesn't seem to be used when running <kbd>npm run format</kbd> from within a package directly since it _appears_ to be searching for the .prettierignore file locally instead of in ../../.prettierignore.

### Steps to reproduce

```diff
git diff package.json
diff --git a/packages/fxa-event-broker/package.json b/packages/fxa-event-broker/package.json
index 41a6fdb75..ffcbe48dc 100644
--- a/packages/fxa-event-broker/package.json
+++ b/packages/fxa-event-broker/package.json
@@ -6,7 +6,7 @@
     "audit": "npm audit --json | audit-filter --nsp-config=.nsprc --audit=-",
     "prebuild": "rimraf dist",
     "build": "nest build",
-    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
+    "format": "prettier --write --config ../../_dev/.prettierrc '**'",
     "start": "../../_scripts/check-url.sh localhost:9000/__heartbeat__ && pm2 start pm2.config.js",
     "start:prod": "node dist/main",
     "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix", 
```

```sh
npm run format

> fxa-event-broker@1.224.0 format
> prettier --write --config ../../_dev/.prettierrc '**'

[error] No parser could be inferred for file: .nsprc    ## Ignore?
.vscode/launch.json 16ms    ## Ignore .vscode/ files?
.vscode/tasks.json 3ms    ## Ignore .vscode/ files?
architecture.md 14ms
CHANGELOG.md 149ms
config/development.json 6ms
[error] No parser could be inferred for file: LICENSE    ## Ignore?
nest-cli.json 1ms
package.json 3ms    ## Probably best to not let prettier reformat package.json files since npm/yarn should manage those.
pm2.config.js 11ms
README.md 20ms
...
```

### Expected result

We can reference the root .prettierignore using the `--ignore-path` flag, and ignore unknown files using `-u` flag.

```sh
# Shim the `--ignore-path` and `-u` flags in, but ideally this should be set directly in the
# package.json's `format` script (in all packages).
npm run format -- --ignore-path ../../.prettierignore -u

> fxa-event-broker@1.224.0 format
> prettier --write --config ../../_dev/.prettierrc '**' "--ignore-path" "../../.prettierignore" "-u"

.vscode/launch.json 18ms    ## TODO
.vscode/tasks.json 4ms    ## TODO
architecture.md 15ms
CHANGELOG.md 149ms
config/development.json 6ms
nest-cli.json 1ms
package.json 3ms    ## TODO
pm2.config.js 12ms
README.md 21ms
```

In order to fix those remaining `# TODO`s (if we want to), we need to modify the root .prettierignore file and add the following:

```diff
.yarn
*.mjml
+package.json
+.vscode/
# NOTE: we don't need to add "LICENSE" or .npsrc" here since those are ignored via the `-u` flag. 
```

What should happen?

All of these `yarn format` commands in package.json's would need to add the [`--ignore-path`](https://prettier.io/docs/en/cli.html#--ignore-path) and [`-u` (ignore unknown)](https://prettier.io/docs/en/cli.html#--ignore-unknown) flags.

```sh
git grep "prettier " | grep "package.json:"
```

| PACKAGE | COMMAND | NOTES
|:----|:----|:----:|
123done  |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`
browserid-verifier    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'",`
fortress    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`
fxa-admin-panel    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'",`
fxa-auth-server    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'",`
fxa-content-server    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`
fxa-customs-server    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`
fxa-event-broker    |  `"format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",` | ⚠️ I'm different!
fxa-geodb    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`
fxa-payments-server    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'",`
fxa-profile-server    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`
fxa-react    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'",`
fxa-shared    |  `"format": "prettier --write --config ../../_dev/.prettierrc '**'"`

### Actual result

Magic!

### Environment

Node 17.x, but not super relevant here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4468)

**Comment by pdehaan** [comment]
Complication: It doesn't seem like I can specify multiple `--ignore-path` flags for prettier (which might make it challenging to use a global .prettierignore as well as project specific .prettierignore files). Ref: https://github.com/prettier/prettier/issues/8048

Probably makes the most sense to just use the project specific files and live with a bit of redundancy rather than trying to force everybody to fit the ignore patterns into a global ignore config file.

```sh
git ls-files | grep \.prettierignore

.prettierignore
packages/123done/.prettierignore
packages/browserid-verifier/.prettierignore
packages/fortress/.prettierignore
packages/fxa-admin-panel/.prettierignore
packages/fxa-auth-server/.prettierignore
packages/fxa-content-server/.prettierignore
packages/fxa-customs-server/.prettierignore
packages/fxa-geodb/.prettierignore
packages/fxa-payments-server/.prettierignore
packages/fxa-profile-server/.prettierignore
packages/fxa-react/.prettierignore
packages/fxa-settings/.prettierignore
packages/fxa-shared/.prettierignore
```

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
