### ISSUE TITLE
Unable to register paypal-payment for Firefox⁩ ⁨Relay Premium⁩

### ISSUE THREAD

**Issue by jotha4** [mozilla/fxa#11716]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
I want to Upgrade to ⁨Firefox⁩ ⁨Relay Premium. 
I'm a german user and i'm using Windows 10 and Firefox 96.0.1. 
But most time i'm living in switzerland. So i'm using a swiss ip-address.
Thatswhy I have to pay 1 CHF per month. I think so.
But i can't register a paypal-account or a credit card

### What happened?
When i'm registering a paypal-account. Then paypal is doing well.
But after that from this side='https://subscriptions.firefox.com/products' i get this error messages from Firefox:
    Fehler beim Bestätigen des Abonnements…
    
    30 Tage Geld-zurück-Garantie
    error icon
    
    Die Währung dieses Abonnements gilt nicht für das Land, das mit Ihrer Zahlung verknüpft ist.

### What did you expect to happen?
i expected to register paypal-payment-method to Firefox⁩ ⁨Relay Premium⁩
btw. i also tried a credit-card. But there it didin't activate the send-button. But Maybe the expiry date was to old

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)
![2022-01-15 08_25_46-Firefox-Konten](https://user-images.githubusercontent.com/91859486/149613553-2056c1c9-9448-40e2-8407-169bdedbe39e.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4472)

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Me and Reino tracked down one of these in the logs and were able to get a uid 7b4b6ae9954a47b688ba7e7c43b3e1f3. We need help further looking into the logs to see if this user exists or if we had an issue creating their account. Cannot find this uid in stripe.

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

From the sounds of it they are trying to pay with a German PayPal account, for the Swiss product, since they often work in Switzerland.

Unfortunately, at the moment we do not support this use case.

As a work around, could we ask the user to use the Germany Premium URL link? I’ll provide the URL for the Germany product separately.

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

This issue was discussed in more detail in the following Slack thread ( https://mozilla.slack.com/archives/CG0AJ6E77/p1642149446066800 ).

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

Joseph Anthony Cuevas apologies for the delay. As a temporary work around, could you please ask the user to navigate to the German product URL.

To do this, please ask the user to do the following.

  1. Navigate to the subscription page
  2. In the navigation bar, change the plan_id from “price_1JmRM0JNcmPzuWtRzCJ2LQHP” to “price_1JmRTDJNcmPzuWtRnJavIXXX“
    1. Their URL should look similar to this, most likely with a few additional parameters. https://subscriptions.firefox.com/products/prod_KGizMiBqUJdYoY?plan=price_1JmRTDJNcmPzuWtRnJavIXXX ( https://subscriptions.firefox.com/products/prod_KGizMiBqUJdYoY?device_id=a73d34841cc84ed5842a3db3ccd77715&flow_begin_time=1643993654163&flow_id=cbda15f16ecfffce1cb61c7c77dcc36d4137050f070362d5ee6b6df786b3122e&plan=price_1JmRTDJNcmPzuWtRnJavIXXX )

  3. This should load the German Relay Premium product, and should allow them to complete the subscription with their German credit card.

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

Created and linked ticket https://mozilla-hub.atlassian.net/browse/FXA-4560 ( https://mozilla-hub.atlassian.net/browse/FXA-4560|smart-link ) to this story, to discuss a permanent fix for this issue.

**Comment by data-sync-user** [comment]
➤ Magdalena Schwaighofer commented:

Hey Reino Muhl I have asked the user to follow the steps but without success. They say that after trying to purchase the Premium subscription they still get an error “failed to confirm subscription..”

the URL used from his side after editing was  https://subscriptions.firefox.com/products/prod_KGizMiBqUJdYoY?device_id=e51c0bf068654b6d8ce34bd3319dec29&flow_begin_time=1644839646438&flow_id=23a2d3b4bcbe8f0142088368bffc5efc67e56ef57d9bdb57d8390cd1f803a3eb&plan=price_1JmRTDJNcmPzuWtRnJavIXXX ( https://subscriptions.firefox.com/products/prod_KGizMiBqUJdYoY?device_id=e51c0bf068654b6d8ce34bd3319dec29&flow_begin_time=1644839646438&flow_id=23a2d3b4bcbe8f0142088368bffc5efc67e56ef57d9bdb57d8390cd1f803a3eb&plan=price_1JmRTDJNcmPzuWtRnJavIXXX ) 

I am currently also dealing with a user from Switzerland who is unable to purchase the Premium subscription with the error “something went wrong” - I am asking for the console logs now and will get back to you.

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

Magdalena Schwaighofer thank you very much for the update. I’ll start looking into this later today.

If its possible, could you please privately share the userId or email address of the affected user? That should make it easier to investigate this issue.
