### ISSUE TITLE
Add global `yarn lint` script which calls each packages' `lint` script

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#11718]
But I like this <kbd>yarn workspaces foreach [-p --verbose] run format</kbd> trick!
We should ~~arguably~~ definitely add one for the "lint" task so we can easily lint all packages in CI.

```sh
node --experimental-json-modules lint-linter.mjs
```

| PACKAGE | HAS "lint" SCRIPT
|:----|:----|
123done | `eslint .`
browserid-verifier | `eslint .`
db-migrations | ❌ 
fortress | `npm-run-all --parallel lint:eslint lint:style`
functional-tests | ❌ 
fxa-admin-panel | `eslint .`
fxa-admin-server | `eslint *`
fxa-auth-client | ❌ 
fxa-auth-server | `eslint .`
fxa-content-server | `eslint app server tests --cache`
fxa-customs-server | `eslint .`
fxa-dev-launcher | ❌ 
fxa-event-broker | `eslint "{src,apps,libs,test}/**/*.ts" --fix`
fxa-geodb | `eslint .`
fxa-graphql-api | `eslint *`
fxa-payments-server | `npm-run-all --parallel lint:eslint lint:sass`
fxa-profile-server | `eslint .`
fxa-react | ❌ 
fxa-settings | `npm-run-all --parallel lint:eslint lint:sass`
fxa-shared | `eslint .`
fxa-support-panel | `eslint *`

---

```js
"lint": "yarn workspaces foreach -p --verbose run lint",
```

```sh
yarn lint
echo $? # 1
```

```sh
yarn lint > lint.log
cat lint.log | grep "Process exited "
```

| PACKAGE | MESSAGE | CODE | RESULTS
|:----|:----|:----:|:----|
[123done] | Process exited (exit code 0), completed in 1s 911ms | 0 ✅  | 
[browserid-verifier] | Process exited (exit code 0), completed in 2s 50ms | 0 ✅  | 8 problems (0 errors, 8 warnings)
[fortress] | Process exited (exit code 0), completed in 2s 869ms | 0 ✅  | 
[fxa-admin-panel] | Process exited (exit code 0), completed in 3s 22ms | 0 ✅  | 2 problems (0 errors, 2 warnings)
[fxa-admin-server] | Process exited (exit code 2), completed in 1s 673ms | 2 ❌  | ESLint couldn't find a configuration file.
[fxa-auth-server] | Process exited (exit code 1), completed in 2s 699ms | 1 ⚠️  | 1 problem (1 error, 0 warnings)
[fxa-content-server] | Process exited (exit code 0), completed in 1s 772ms | 0 ✅  |
[fxa-customs-server] | Process exited (exit code 1), completed in 1s 312ms | 1 ⚠️ | 5 problems (5 errors, 0 warnings)
[fxa-event-broker] | Process exited (exit code 2), completed in 1s 245ms | 2 ❌  | ESLint couldn't find a configuration file.
[fxa-geodb] | Process exited (exit code 0), completed in 0s 955ms | 0 ✅  |
[fxa-graphql-api] | Process exited (exit code 2), completed in 1s 241ms | 2 ❌  | ESLint couldn't find a configuration file.
[fxa-payments-server] | Process exited (exit code 1), completed in 1s 308ms | 1 ⚠️  | ERROR: Task not found: "lint:sass"
[fxa-profile-server] | Process exited (exit code 1), completed in 1s 563ms | 1 ⚠️ | 1 problem (1 error, 0 warnings)
[fxa-settings] | Process exited (exit code 1), completed in 1s 94ms | 1 ⚠️ | ERROR: Task not found: "lint:sass"
[fxa-shared] | Process exited (exit code 0), completed in 1s 288ms | 0 ✅  | 
[fxa-support-panel] | Process exited (exit code 2), completed in 0s 869ms | 2 ❌  | ESLint couldn't find a configuration file.

_Originally posted by @pdehaan in https://github.com/mozilla/fxa/issues/11709#issuecomment-1019643994_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4475)

**Comment by pdehaan** [comment]
And because I still have my lint.log file open in VSCode, here's the TLDR on the errors/warnings&hellip;

Nothing too shocking or concerning, IMHO (but I am blind on 6 packages currently).

```sh
➤ YN0000: [browserid-verifier]: /Volumes/Dev/github/mozilla/fxa/packages/browserid-verifier/lib/version.js
➤ YN0000: [browserid-verifier]:   35:52  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]:   41:9   warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]: 
➤ YN0000: [browserid-verifier]: /Volumes/Dev/github/mozilla/fxa/packages/browserid-verifier/tests/force-issuer.js
➤ YN0000: [browserid-verifier]:    40:7  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]:    73:7  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]:   106:7  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]: 
➤ YN0000: [browserid-verifier]: /Volumes/Dev/github/mozilla/fxa/packages/browserid-verifier/tests/unverified-email.js
➤ YN0000: [browserid-verifier]:    37:7  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]:    68:7  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]:   105:7  warning  Expected error to be handled  handle-callback-err
➤ YN0000: [browserid-verifier]: 
➤ YN0000: [browserid-verifier]: ✖ 8 problems (0 errors, 8 warnings)

➤ YN0000: [fxa-admin-server]: ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

➤ YN0000: [fxa-admin-panel]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/server/lib/html-middleware.ts
➤ YN0000: [fxa-admin-panel]:   9:1  warning  Unexpected default export of anonymous function  import/no-anonymous-default-export
➤ YN0000: [fxa-admin-panel]: 
➤ YN0000: [fxa-admin-panel]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
➤ YN0000: [fxa-admin-panel]:   114:37  warning  'disableLoading' is assigned a value but never used  @typescript-eslint/no-unused-vars
➤ YN0000: [fxa-admin-panel]: 
➤ YN0000: [fxa-admin-panel]: ✖ 2 problems (0 errors, 2 warnings)

➤ YN0000: [fxa-customs-server]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-customs-server/bin/customs_server.js
➤ YN0000: [fxa-customs-server]:   27:11  error  Identifier 'server_shutdown' is not in camel case  camelcase
➤ YN0000: [fxa-customs-server]: 
➤ YN0000: [fxa-customs-server]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-customs-server/pm2.config.js
➤ YN0000: [fxa-customs-server]:   15:7  error  Identifier 'max_restarts' is not in camel case  camelcase
➤ YN0000: [fxa-customs-server]:   21:7  error  Identifier 'filter_env' is not in camel case    camelcase
➤ YN0000: [fxa-customs-server]:   23:7  error  Identifier 'min_uptime' is not in camel case    camelcase
➤ YN0000: [fxa-customs-server]: 
➤ YN0000: [fxa-customs-server]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-customs-server/test/remote/too_many_bad_logins.js
➤ YN0000: [fxa-customs-server]:   165:4  error  'req' is assigned a value but never used  no-unused-vars
➤ YN0000: [fxa-customs-server]: 
➤ YN0000: [fxa-customs-server]: ✖ 5 problems (5 errors, 0 warnings)

➤ YN0000: [fxa-event-broker]: ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

➤ YN0000: [fxa-graphql-api]: ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

➤ YN0000: [fxa-payments-server]: ERROR: Task not found: "lint:sass"

➤ YN0000: [fxa-auth-server]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-auth-server/scripts/bulk-mailer.js
➤ YN0000: [fxa-auth-server]:   45:1  error  Parsing error: 'return' outside of function
➤ YN0000: [fxa-auth-server]: 
➤ YN0000: [fxa-auth-server]: ✖ 1 problem (1 error, 0 warnings)

➤ YN0000: [fxa-settings]: ERROR: Task not found: "lint:sass"

➤ YN0000: [fxa-profile-server]: /Volumes/Dev/github/mozilla/fxa/packages/fxa-profile-server/lib/routes/display_name/post.js
➤ YN0000: [fxa-profile-server]:   29:3  error  Unexpected control character(s) in regular expression: \x00, \x1f  no-control-regex
➤ YN0000: [fxa-profile-server]: 
➤ YN0000: [fxa-profile-server]: ✖ 1 problem (1 error, 0 warnings)

➤ YN0000: [fxa-support-panel]: ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
```

I think next steps would be:
- Removing [two] references to missing "lint:sass" tasks which are seemingly preventing "lint:eslint" from running, and see which errors/warnings might be a happenin'.
- Fixing the [four] repos which are reporting "ESLint couldn't find a configuration file." and decide which configs make sense (and then fix up the errors/warnings/rules).
- Poke away at remaining errors/warnings by tweaking code/rules/configs.
- Add `"lint": "yarn workspaces foreach -p --verbose run lint",` to root package.json `scripts`.
- Enable the <kbd>yarn lint</kbd> (and <kbd>yarn format</kbd>) in a CI task so it runs [loudly] on every PR?

**Comment by pdehaan** [comment]
Modified **fxa-settings**/package.json and **fxa-payments-server**/package.json "lint" scripts locally to just be `"lint": "eslint .",` and reran the global `yarn lint` script:

```sh
➤ YN0000: [fxa-settings]: ✖ 58 problems (41 errors, 17 warnings)
➤ YN0000: [fxa-settings]:   0 errors and 1 warning potentially fixable with the `--fix` option.

➤ YN0000: [fxa-payments-server]: ✖ 214 problems (63 errors, 151 warnings)
➤ YN0000: [fxa-payments-server]:   52 errors and 14 warnings potentially fixable with the `--fix` option.
```

Numbers look kind of big, but they're mostly the same handful of warnings/errors, so either easy fixin' or just need to adjust the ESLint configs.

But I can't think of an easy way/reporter to summarize the errors/warnings by rule, and not sure I want to bother writing the RegExp to parse the ESLint output to extract rule names to create another Markdown table.

**Comment by pdehaan** [comment]
Here was another fun experiment which [ab]uses the ESLint "json" reporter and then some `jq` filtering to return the set of files linted by ESLint. Sure, it's pretty obscure, but might be better served by moving it into the package.json scripts section once we get all that sorted. But might be an interesting tool to see which files are and aren't being linted.

```sh
npx eslint packages/fxa-content-server -c _dev/.eslintrc --format=json | jq '[.[] | .filePath]'

[
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/Gruntfile.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/app.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/head/boot.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/head/startup-styles.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/app-start.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/auth-errors.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/channels/base.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/channels/duplex.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/channels/fx-desktop-v1.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/channels/inter-tab.js",
  "/Volumes/Dev/github/mozilla/fxa/packages/fxa-content-server/app/scripts/lib/channels/notifier-mixin.js",
  ...
]
```

I was working on a script which diffed the ESLinted files versus the supported file formats in git, but that script was a bit sketchy since a couple repos have some ESLint config issues currently and I was trying to parse ESLint debug logs to get parsed files instead of using the JSON reporter which is a better solution.

> ```sh
> # WARNING: Not a good solution... output was sent to stderr which was trickier to grep through and
> # handle fatal ESLint errors. Probably best to stick w/ the JSON formatter trick above if anybody else
> # wants to hack on this.
> DEBUG=eslint:cli-engine npx eslint packages/fxa-content-server -c _dev/.eslintrc --ext=.{js,jsx,ts,tsx}
> ```

Anyways, here was my dirty `git ls-files` hack for reporting all ".js", ".jsx", ".ts", and ".tsx" files.
```sh
git ls-files packages/fxa-content-server | grep -E "\.[jt]sx?$"

packages/fxa-content-server/Gruntfile.js
packages/fxa-content-server/app/scripts/app.js
packages/fxa-content-server/app/scripts/head/boot.js
packages/fxa-content-server/app/scripts/head/startup-styles.js
packages/fxa-content-server/app/scripts/lib/app-start.js
packages/fxa-content-server/app/scripts/lib/auth-errors.js
packages/fxa-content-server/app/scripts/lib/channels/base.js
packages/fxa-content-server/app/scripts/lib/channels/duplex.js
packages/fxa-content-server/app/scripts/lib/channels/fx-desktop-v1.js
packages/fxa-content-server/app/scripts/lib/channels/inter-tab.js
packages/fxa-content-server/app/scripts/lib/channels/notifier-mixin.js
```

Then I was basically ~~piping both those outputs to local JSON files~~ calling those commands via `shelljs.exec()` [to avoid temp files], normalizing the paths in Node, and trying to diff arrays to determine:
- files-in-git-but-not-eslinted (ie: are we ignoring globs or hidden files or .tsx files).
- files-eslinted-but-not-in-git (ie: are we linting dist/ files or fxa-content-server-l10n/ folders that should be added to .eslintignore).

**Comment by pdehaan** [comment]
Here's the output of yet-another-garbage-pdehaan-script. Also, my script [ignorantly] assumes that ESLint is parsing the `(js|jsx|ts|tsx)` file extensions, which might not be true. But this stuff below is probably the easiest low-hanging fruit. But the actual results may vary and we might see that some directories aren't linting TypeScript files at all once we figure out how to create a cleverer linterer.

<details>
<summary>fxa-admin-panel</summary>

- I think ESLint ignores hidden files by default, so we'd need to add some clever negation rules to .eslintignore to unignore hidden files/folders. For example `!.rescriptsrc.js` and `!.storybook`.

```js
{
  pkg: 'fxa-admin-panel',
  inGitButNotESLinted: [
    'packages/fxa-admin-panel/.rescriptsrc.js',
    'packages/fxa-admin-panel/.storybook/main.js',
    'packages/fxa-admin-panel/.storybook/preview.js',
    'packages/fxa-admin-panel/.storybook/webpack.config.js'
  ],
  eslintedButNotInGit: []
}
```
</details>

<details>
<summary>fxa-auth-client</summary>

- Add `dist` to .eslintignore.

```js
{
  pkg: 'fxa-auth-client',
  inGitButNotESLinted: [],
  eslintedButNotInGit: [
    'packages/fxa-auth-client/dist/browser/browser.d.ts',
    'packages/fxa-auth-client/dist/browser/browser.js',
    'packages/fxa-auth-client/dist/browser/lib/client.d.ts',
    'packages/fxa-auth-client/dist/browser/lib/client.js',
    'packages/fxa-auth-client/dist/browser/lib/crypto.d.ts',
    'packages/fxa-auth-client/dist/browser/lib/crypto.js',
    'packages/fxa-auth-client/dist/browser/lib/hawk.d.ts',
    'packages/fxa-auth-client/dist/browser/lib/hawk.js',
    'packages/fxa-auth-client/dist/browser/lib/recoveryKey.d.ts',
    'packages/fxa-auth-client/dist/browser/lib/recoveryKey.js',
    'packages/fxa-auth-client/dist/browser/lib/utils.d.ts',
    'packages/fxa-auth-client/dist/browser/lib/utils.js',
    'packages/fxa-auth-client/dist/server/lib/client.d.ts',
    'packages/fxa-auth-client/dist/server/lib/client.js',
    'packages/fxa-auth-client/dist/server/lib/crypto.d.ts',
    'packages/fxa-auth-client/dist/server/lib/crypto.js',
    'packages/fxa-auth-client/dist/server/lib/hawk.d.ts',
    'packages/fxa-auth-client/dist/server/lib/hawk.js',
    'packages/fxa-auth-client/dist/server/lib/recoveryKey.d.ts',
    'packages/fxa-auth-client/dist/server/lib/recoveryKey.js',
    'packages/fxa-auth-client/dist/server/lib/utils.d.ts',
    'packages/fxa-auth-client/dist/server/lib/utils.js',
    'packages/fxa-auth-client/dist/server/server.d.ts',
    'packages/fxa-auth-client/dist/server/server.js'
  ]
}
```
</details>

<details>
<summary>fxa-auth-server</summary>

- Add negated `!.mocharc.js` and `!.storybook` to .eslintignore.
- Add `fxa-content-server-l10n` to .eslintignore.

```js
{
  pkg: 'fxa-auth-server',
  inGitButNotESLinted: [
    'packages/fxa-auth-server/.mocharc.js',
    'packages/fxa-auth-server/.storybook/main.js',
    'packages/fxa-auth-server/.storybook/preview.js'
  ],
  eslintedButNotInGit: [
    'packages/fxa-auth-server/fxa-content-server-l10n/Gruntfile.js',
    'packages/fxa-auth-server/fxa-content-server-l10n/grunttasks/l10n-lint.js',
    'packages/fxa-auth-server/fxa-content-server-l10n/scripts/ci-creds.js'
  ]
}
```
</details>

<details>
<summary>fxa-content-server</summary>

 - Add `fxa-content-server-l10n` to .eslintignore

```js
{
  pkg: 'fxa-content-server',
  inGitButNotESLinted: [],
  eslintedButNotInGit: [
    'packages/fxa-content-server/fxa-content-server-l10n/Gruntfile.js',
    'packages/fxa-content-server/fxa-content-server-l10n/grunttasks/l10n-lint.js',
    'packages/fxa-content-server/fxa-content-server-l10n/scripts/ci-creds.js'
  ]
}
```
</details>

<details>
<summary>fxa-react</summary>

- Add negated `!.storybook` to .eslintignore

```js
{
  pkg: 'fxa-react',
  inGitButNotESLinted: [
    'packages/fxa-react/.storybook/main.js',
    'packages/fxa-react/.storybook/preview.js',
    'packages/fxa-react/.storybook/webpack.config.js'
  ],
  eslintedButNotInGit: []
}
```
</details>

<details>
<summary>fxa-settings</summary>

- Add negated `!.rescriptsrc.js` and `!.storybook` to .eslintignore
- Add `fxa-content-server-l10n` to .eslintignore

```js
{
  pkg: 'fxa-settings',
  inGitButNotESLinted: [
    'packages/fxa-settings/.rescriptsrc.js',
    'packages/fxa-settings/.storybook/design-guide/Copiable.tsx',
    'packages/fxa-settings/.storybook/design-guide/Header.tsx',
    'packages/fxa-settings/.storybook/design-guide/Page.tsx',
    'packages/fxa-settings/.storybook/design-guide/Snippet.tsx',
    'packages/fxa-settings/.storybook/design-guide/main.stories.tsx',
    'packages/fxa-settings/.storybook/design-guide/pages/Breakpoints.tsx',
    'packages/fxa-settings/.storybook/design-guide/pages/Colors.tsx',
    'packages/fxa-settings/.storybook/design-guide/pages/Introduction.tsx',
    'packages/fxa-settings/.storybook/design-guide/pages/Spacing.tsx',
    'packages/fxa-settings/.storybook/design-guide/pages/Typography.tsx',
    'packages/fxa-settings/.storybook/fxaTheme.js',
    'packages/fxa-settings/.storybook/main.js',
    'packages/fxa-settings/.storybook/manager.js',
    'packages/fxa-settings/.storybook/preview.js',
    'packages/fxa-settings/.storybook/webpack.config.js'
  ],
  eslintedButNotInGit: [
    'packages/fxa-settings/fxa-content-server-l10n/Gruntfile.js',
    'packages/fxa-settings/fxa-content-server-l10n/grunttasks/l10n-lint.js',
    'packages/fxa-settings/fxa-content-server-l10n/scripts/ci-creds.js'
  ]
}
```
</details>
<details>
<summary>fxa-support-panel</summary>

- Add `dist` to .eslintignore

```js
{
  pkg: 'fxa-support-panel',
  inGitButNotESLinted: [],
  eslintedButNotInGit: [
    'packages/fxa-support-panel/dist/app.module.js',
    'packages/fxa-support-panel/dist/app/account-query.dto.js',
    'packages/fxa-support-panel/dist/app/app.controller.js',
    'packages/fxa-support-panel/dist/auth/auth-header.decorator.js',
    'packages/fxa-support-panel/dist/auth/auth-header.guard.js',
    'packages/fxa-support-panel/dist/config.js',
    'packages/fxa-support-panel/dist/database/database.module.js',
    'packages/fxa-support-panel/dist/database/database.service.js',
    'packages/fxa-support-panel/dist/main.js',
    'packages/fxa-support-panel/dist/remote-lookup/remote-lookup.service.js',
    'packages/fxa-support-panel/dist/remote-lookup/remote-responses.dto.js'
  ]
}
```
</details>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
