### ISSUE TITLE
Remove orphaned code from metrics pipeline improvement

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11717]
A couple years ago there was some effort to improve our metrics pipeline.  That’s been obviated by the adoption of Looker.  But there’s still code around from that epic.  Here are the two commits that I remember:

* https://github.com/mozilla/fxa/commit/f4a3fd3542b8f101f25061ecf870297c1bcc5686
* https://github.com/mozilla/fxa/commit/63dadbc2c64269eeb2894ad5811553bee58c87f7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4473)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
