### ISSUE TITLE
Consider allowing subscription products to pass metrics into FxA pipeline.

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#1172]
idea for the backlog for now, but putting this in for the record. 

We currently have metrics spec'd for the subscription setup and management interface that lives within FxA, but these metrics don't cover anything product-specific. 

If a product requires regular checking of authentication during use, we could consider piggybacking on that to allow subscription products to submit us their core metrics so we can do more than just track subscription signups and management (or implement some other way for them to give us metrics, idk.). This would allow us to have some insight into e.g. why someone cancels their subscription (rather than just the fact that they did). We could also pass those metrics to the marketing folks.

**Comment by davismtl** [comment]
@loines should we close this?

**Comment by vladikoff** [comment]
cc @irrationalagent

**Comment by irrationalagent** [comment]
im going to close this, this was sort of related to https://github.com/mozilla/fxa/issues/963

If we want reliers to be able to log other metrics by pinging our metrics endpoint, that is a broader discussion we should have.
