### ISSUE TITLE
[subplat] Use React.StrictMode in payments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11726]
React in Strict Mode (`<React.StrictMode>`) can help identify problems while in development. We're using it in `fxa-settings` and should wrap payment-server's application in it too.

Docs: [https://reactjs.org/docs/strict-mode.html](https://reactjs.org/docs/strict-mode.html|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4480)

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

If adding React.StrictMode causes multiple errors/warnings, create separate tickets to fix those issues. Should not be completed as part of  this ticket, if it’s too many.

**Comment by LZoog** [comment]
@StaberindeZA It does break at least one test (I can't remember how many honestly), but it didn't seem like it was too many for one ticket when I looked, and broken tests would be kind of hard to break up from the task. I didn't try it out and see what new warnings were logged, those could definitely be separate tickets.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
