### ISSUE TITLE
[subplat] Use AppErrorBoundary & AppErrorDialog from `fxa-shared`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11725]
This is blocked by [https://mozilla-hub.atlassian.net/browse/FXA-4477](https://mozilla-hub.atlassian.net/browse/FXA-4477|smart-link) and whatever tickets come out of adding Fluent to `fxa-react`.

`AppErrorBoundary` and `AppErrorDialog` in `App.tsx` in payments is identical to the one in `fxa-shared` except  it's localized and at the time of writing the one in `fxa-react` is not. Once it’s ready, we should import and use the one in `fxa-shared` instead.

Also consider moving `AppErrorBoundary` to be more top-level. It should catch all errors that aren’t handled furthered down and are bubbled up to it - it should probably be in `src/index.tsx` and wrap the app there.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4479)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
