### ISSUE TITLE
[subplat] False assumption of `stripeHelper` always existing

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/fxa#11758]
In 233de634204547fbe166f066faa46ebc1837ec13, `stripeHelper` was used w/o checking for its existence first.

We're seeing errors caused by this roughly a dozen of times a day in Sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4493)

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

Hector Zhao thank you for raising this. Do you happen to have a link to the Sentry error you are getting?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
