### ISSUE TITLE
Add a /contribute.json file to accounts.firefox.com?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#11751]
Ref: https://www.contributejson.org/ and https://github.com/mozilla/contribute.json

We've used it in the past on a few projects and it has been helpful for quickly finding the dev/stage/prod URLs or links to bugbases, etc.
- https://monitor.firefox.com/contribute.json
- https://www.mozilla.org/contribute.json
- https://www.contributejson.org/contribute.json (so meta!)
- https://addons.mozilla.org/contribute.json

Not sure if this was the best answer, but I found the stage/dev URLs in https://mozilla.github.io/ecosystem-platform/platform/sub-plat/integration-with-subscription-platform#setting-up-your-marketing-pages (although now I see it is also in the /CONTRIBUTING.md docs at https://github.com/mozilla/fxa/blob/main/CONTRIBUTING.md#servers)

---

**UPDATE:** Ha! I knew this sounded vaguely familiar: https://github.com/mozilla/fxa-content-server/issues/2767

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4492)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Thanks for filing Peter. We're going to "won't fix" this since we have the contributing.md file per our triage meeting.
