### ISSUE TITLE
[subplat] incorrect amounts shown in invoice email for non zero amounts below Stripe minimums

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11789]
**Background**

For subscriptions that cost less than the Stripe minimum amounts, the invoice amount due will be $0.00, and the subscription cost will be added as a credit to the customers record in Stripe, and added to subsequent invoices.

As a result, the email we sent to the customer for the first invoice, incorrectly shows that they were charged the subscription cost.

**Requirements**

Update the invoice email…

* To ensure the amount in the email is the same as in the invoice. (Should be $0.00)
* Indicate to the customer the subscription cost will roll over, until the minimum amount is reached.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4509)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19968">Screenshot 2022-01-26 at 12-19-26 (6) MailDev.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19969">Screen Shot 2022-01-28 at 1.36.22 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

there does not seem to be an immediate product need for this until we support the $0 invoice.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
