### ISSUE TITLE
Investigate performance issue in auth-server for train 224

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#11799]
See slack https://mozilla.slack.com/archives/CLV3KMZ8B/p1643640401183249

We landed several things in the auth-server for this train, ref https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/CHANGELOG.md#12240

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4513)

**Comment by LZoog** [comment]
Might be unrelated but in addition to that changelog, metrics collection opt-out was enabled this train, we had a [bug for fixing an unexpected amount of db calls](https://github.com/mozilla/fxa/pull/10990) a couple of months ago
