### ISSUE TITLE
Work out how to handle account migration conflicts in AMO

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#118]
(Spinning off discussion from https://github.com/mozilla/fxa-content-server/issues/3489#issuecomment-181655330)

The AMO migration flow has a state that detects whether the user switches their account to one that's already completed the AMO migration flow; it's the screen in [1] with an error message saying `""This account already exists on AMO. Why?"`.

An obvious way to implement this screen would be for FxA to ask AMO whether the account has already migrated.  But this adds tight coupling between FxA and one specific relier, adding complexity and setting a bad precedent for the complexity of future migrations.

Let's figure out a better option.

[1] https://raw.githubusercontent.com/mozilla/addons/master/docs/images/fxa-migration.png

**Comment by rfk** [comment]
The current behaviour in this case seems to be that the migration silently fails; STR:

1) On AMO, choose "log in" and enter an account that exists but has not yet been migrated.
2) You're prompted for your existing AMO password, enter it.
3) You're prompted to migrate to Firefox Accounts, choose "continue".
4) On the FxA signin form, change the email address and sign in as a different account, one that already exists in AMO and has been migrated
5) You're redirected back to AMO and are still logged in as the original user.  (This is OK, because you entered the password for that user back in step 2.  But it was definitely surprising!)
6) Log out, and log back in to AMO as the same user.  You're again prompted to migrate to Firefox Accounts.

If in step (4) you choose an email that *doesn't* exist in AMO, the migration appears to succeed and the account email in AMO is updated.

**Comment by rfk** [comment]
@mstriemer is working on displaying an error on the AMO side over in [1].  @ryanfeeley can you please weigh in on whether that's sufficient, or you'd like further tweaks to the flow on our side as well?

[1] https://github.com/mozilla/addons-server/pull/1656

**Comment by ryanfeeley** [comment]
@rfk I think @mstriemer is handling it the right way. A red error message, and way for the user to try with a different address. It's unlikely to happen very often so I think this experience is sufficient for the few that get it. As long as we can make sure that the users account data is being properly migrated the first time (otherwise a lot of people will see this and be unhappy).

**Comment by rfk** [comment]
Thanks @ryanfeeley, I'm glad we took the time to check this out.  Closing here in favour of the handling on the AMO side.
