### ISSUE TITLE
[email templates] cadReminderSecond email is not received in stage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11802]
While the cadReminderFirst email is received in both stage and prod, cadReminderSecond was only received in prod for both mozilla and non-mozilla emails.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4515)

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

When this is fixed, please also update its story description:

https://github.com/mozilla/fxa/pull/11831 ( https://github.com/mozilla/fxa/pull/11831|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
