### ISSUE TITLE
[subplat] Block new subscriptions to "archived" plans

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11805]
Our list of plans is updated through Stripe webhooks.  We currently not handling the change in a plan’s `active` property.  When a plan’s `active` status changes from true to false, we _might_ be able remove it from the cached list.  HOWEVER, we should verify that doing so will not affect existing subscriptions of the removed plan.  (E.g., is the subscription still displayed correctly in the Subscription Manage page?  What about emails? etc.)

If we cannot remove it, then we need to update the plans endpoint to expose the plan `active` status and have our frontend block accordingly.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4517)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

We might not be able to remove it from the list since we may be using it elsewhere.

Can we remove a plan from the cached list even it has active subscriptions? If so, remove it from cached list. If not, we need to expose active status and the FE needs to behave accordingly.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
