### ISSUE TITLE
[email templates] Difference between HTML and plaintext version for postAddTwoStepAuthentication and postRemoveTwoStepAuthentication

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11825]
**Build:**

Stage [Train 224.4]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Prerequisites:**

2FA is disabled.
**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and log in using an existing account.
1. Go to 2FA section and add 2FA authentication.
1. Go to your inbox and verify the “Two-step authentication enabled“ email both HTML and plaintext versions.

**Actual result:**

There is a difference between HTML and plaintext. In plaintext: “Security codes from your authentication app will now be required at each sign-in“ is displayed before the device info. 

Also the “You have successfully enabled two-step authentication…“ sentence is a little bit different from HTML - “…from the following device:” is missing in plaintext.

**Expected result:**

“Security codes from your authentication app will now be required at each sign-in“ is displayed after the device info. 
“…from the following device:” is added to the first sentence in plaintext.

Storybook should also be updated.

**Notes:**

postRemoveTwoStepAuthentication is also affected.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4521)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20092">2FA enabled email diff HTML&amp;plaintext.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
