### ISSUE TITLE
[email templates] Handle gmail-added .im classes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11820]
Email text is sometimes wrapped with `im` class, which makes the text appear purple. While this was previously filed, fixed, and verified with [https://mozilla-hub.atlassian.net/browse/FXA-4494](https://mozilla-hub.atlassian.net/browse/FXA-4494|smart-link) for list items, this occurrence was in a span; this bug is currently difficult to reproduce. The screenshot provided below was in Chrome.

Possible fix: add {{.im { color: inherit !important }}}

` This might happen if your code has a TABLE with more than one TR. To get around this, rather than several TRs in one TABLE, use several TABLEs with one TR in each.`

Source: Lauren and [https://stackoverflow.com/questions/16689882/gmail-wraps-certain-html-elements-in-a-class-called-im](https://stackoverflow.com/questions/16689882/gmail-wraps-certain-html-elements-in-a-class-called-im|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4520)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20083">image (1).png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20726">Screen Shot 2022-02-19 at 1.01.54 AM.png</a>

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Note that this is specific only to Gmail and is not reliably reproducible, I only saw it once in Chrome. I think the previous fix was verified because it doesn’t happen every time, I’m not convinced the fix actually fixed it for that instance. 😬

I think the only way adding our own .im style would work is if we don’t add it to our regular SCSS files to be inlined, as in have it present/pulled into our layout files to always be there, because Gmail adds this class after the email is rendered. Though, this might incidentally make all “replies” in gmail non-purple when they should be…

I think the ask here is to audit our MJML files (Storybook is probably easiest) and see where we can change multiple TRs in tables, and/or file an issue in the MJML repo if one’s not already filed. MJML is designed to take care of weird email stuff for us so maybe it’s something they’d want to address 🤷‍♀️

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Another sighting of purple strings! This was spotted in the recovery email template. The  im class was applied to the span (but left out the time 🤨 )

!Screen Shot 2022-02-19 at 1.01.54 AM.png|width=961,height=883!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
