### ISSUE TITLE
Add eslint-plugin-import configs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#11832]
https://www.npmjs.com/package/eslint-plugin-import

Oddly I see this under `resolutions` in package.json currently, but not sure where/if it's being used by any of the packages.
Only reference I see is in fxa-event-broker, but I don't see an .eslintrc* config file to see if that plugin is being used somewhere:

https://github.com/mozilla/fxa/blob/cff7aa72a4303d86f1cbdb573b87944064134993/packages/fxa-event-broker/package.json#L96

Not sure if we should add this to the core _dev/.eslintrc file or possibly move it into the "plugin:fxa/recommended" rules (and let packages opt-out or override as needed).
> **NOTE:** Probably easiest to hardcode into _dev/.eslintrc initially and see what errors shake out before migrating into fxa/recommended and having to push new releases to npm, etc.

But might be nice to add this to the maintenance backlog for when we overhaul the code linting in this repo.

---

Here's a list of all the current ESLint plugins and their respective packages:

```sh
git grep "eslint-plugin-" **/package.json
```

| FILE | PLUGIN | SEMVER
|:----|:----|:----
package.json |    "eslint-plugin-fxa" | "^2.0.2",
package.json |    "eslint-plugin-jest" | "^24.5.2",
package.json |    "eslint-plugin-react" | "^7.26.1",
package.json |    "eslint-plugin-import" | "^2.25.2"
packages/123done/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/browserid-verifier/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fortress/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-admin-panel/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-admin-panel/package.json|   "eslint-plugin-jest"| "^24.5.2",
packages/fxa-admin-panel/package.json|    "eslint-plugin-react"|"^7.26.1",
packages/fxa-auth-server/package.json|   "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-content-server/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-customs-server/package.json|   "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-event-broker/package.json|    "eslint-plugin-import"| "^2.25.4",
packages/fxa-geodb/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-payments-server/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-payments-server/package.json|   "eslint-plugin-jest"|"^24.5.2",
packages/fxa-payments-server/package.json|    "eslint-plugin-react"| "^7.26.1",
packages/fxa-payments-server/package.json|   "eslint-plugin-jest"|"^24.5.2",
packages/fxa-profile-server/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-settings/package.json|    "eslint-plugin-fxa"| "^2.0.2",
packages/fxa-settings/package.json|    "eslint-plugin-jest"| "^24.5.2",
packages/fxa-settings/package.json|    "eslint-plugin-react"| "^7.26.1",
packages/fxa-shared/package.json|   "eslint-plugin-fxa"| "^2.0.2",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4524)

**Comment by pdehaan** [comment]
I took a quick look at this today while investigating some other ESLint issues and this seems like a visually pleasant config.

```js
"import/order": ["error", {"newlines-between": "always", "alphabetize": {"order": "asc", "caseInsensitive": true}}]
```

But it will be pretty chaotic trying to add it in since it will touch thousands of files. Vast majority of the issues can be automatically fixed via something like <kbd>yarn workspace fxa-content-server run lint --fix</kbd>, but that still left about 50 issues (in fxa-content-server alone) that needed to be resolved manually by reordering `require()` statements between other `const` definitions.

I also wasn't able to add the rule to the root `_dev/.eslintrc` file since it doesn't look like the <kbd>yarn workspace fxa-content-server run lint --fix</kbd> command references the global/shared ESLint config at all (but maybe that file is being used by the husky git hooks (sometimes; *.js only, not *.ts?), so we probably get different results when you run linting directly vs when you rely on hooks only)

https://github.com/mozilla/fxa/blob/feee364ad7e386f1b4c69bee64916cd9b7f02b86/package.json#L55-L62

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
