### ISSUE TITLE
Return `auth_at` and `expires_in` in the `/verify` oauth endpoint

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11844]
From 

[https://mozilla.slack.com/archives/C4D36CAJW/p1643728145416489](https://mozilla.slack.com/archives/C4D36CAJW/p1643728145416489|smart-card)

This change would help simplify Relay authentication code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4544)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Verify what the spec says this endpoint should return.

**Comment by vbudhram** [comment]
@groovecoder that sounds good, please close if introspection endoint does what you need.

**Comment by groovecoder** [comment]
The introspection endpoint has everything we need. Thanks!
