### ISSUE TITLE
[subplat] On subscription page, allow customers to select a different country or currency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11855]
*Background*

Customers who use a credit card from a country that’s different than the country they are currently in, will receive an error similar to this one.

`Funding source country does not match plan currency.`

*Requirements*

On the subscription page, allow customers to change the country (meaning the Stripe product), so that they can use their credit card to pay for their subscription.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4560)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
