### ISSUE TITLE
Add message about disconnecting services when resetting password

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11866]
On our password change page there are a few bullet points.  We’d like to add one to warn users that resetting their password will not automatically disconnect users.  The scenario of concern here is if your password gets stolen and you reset it you might think you’re protected, but if one of your devices or services was already compromised the attacker would still have access, whereas if you disconnect all your devices they would not.

An idea for a message is “*Changing your password will not automatically disconnect services which use your account.*”  but the header for the list of bullet points is “Your Password: “ so that doesn’t really work.  Input welcome\!

The bullet points change as the user is typing their password (see second screenshot).  For this bullet point it should remain static - just the lock image.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4566)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20270">image.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20269">image-20220207-163616.png</a>

**Comment by data-sync-user** [comment]
➤ Meridel Walkington commented:

Hi! Unfortunately, I don’t think adding an additional bullet point to this screen solves the issue. It’s a bit of a copy band-aid for a potentially significant security issue.

Katie Caldwell (UX designer) and I chatted. Without a great deal of context, what we’d expect to happen, and what would be more secure ( ? ) would be to disconnect users to other devices and services when they reset their password. And to let them know this happened with an option to see what devices and services have been disconnected: "For your security, you've been disconnected from all Firefox services and other devices. You'll need to sign back in <link to “Show connected devices and services”>.  

What are the services that would get disconnected, by the way? For Firefox Monitor, for example, I would not expect to be disconnected because I have signed up for that service but I don’t use my FxA login to access it. Right?

This request needs both interaction/visual and content design. This might be something that me plus a visual designer could knock out fairly quickly but we need staffing from the visual/IX side of the house. Raja would be point of contact for that.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It could be any of the devices or services under “Connected Services” on the Account Settings ( https://accounts.firefox.com/setting ) .  But that’s part of the reason we just wanted to do the messaging – which do you disconnect?  If you change your password do you expect to have to relogin to your phone?

**Comment by data-sync-user** [comment]
➤ Meridel Walkington commented:

Yes, I’d expect to be disconnected from any device or servcie using my FxA password (aside from my current device/Firefox browser). I would not expect to be disconnected from things like Monitor if they don’t use my FxA password.

**Comment by data-sync-user** [comment]
➤ Frida Kiriakos commented:

Hello Meridel Walkington , I wanted to check if there are any updates regarding this issue, whether any decisions have been made. Thanks.

**Comment by data-sync-user** [comment]
➤ Meridel Walkington commented:

Chelsea Lewis We need UX design resourcing on this, too, to partner with content. Can you please share any updates based on your conversation with Raja? Thank you!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
