### ISSUE TITLE
Inconsistent behavior when user is logged in on two different browsers after changing password

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11863]
*Build:*

Stage

*Affected platforms:*

Windows 10 64-bit

macOS 10.14

macOS 12.1

*Steps to reproduce:*

# Open [https://addons-dev.allizom.org/en-US/firefox/|https://addons-dev.allizom.org/en-US/firefox/|smart-link]on two different browsers (e.g. Chrome & Nightly) and Log in.
# From one of the browsers click on your username in the upper right corner and select “Edit My Profile".
# Click “Manage Firefox Accounts…”.
# Go to “Password” section and change the password.
# Go back to AMO page on that browser and log in.
# Go to AMO page on the other browser and log in.

*Actual result:*

When connecting with the account to which I just changed the password in the browser where I initiated this action, “Confirm your account“ screen is displayed. 

Email with verification link is received only after you click Resend.
On the other browser after trying to Log in with this account it asks me only for my new password and everything works fine.

*Expected result:*

On any browser after changing the password you need to be asked for your new password and if any Confirmation account message appears an automatic mail should be triggered.

*Notes:*

The issue is not always reproducible. Using a gmail address increases the chances of reproducing it.

Rate of reproducibility: 6/10

!confirm your account screen displayed on one browser.gif|width=1905,height=1012!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4563)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/20266">confirm your account screen displayed on one browser.gif</a>

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

For AMO users, this might be related to 2FA. Does your account on stage have 2FA enabled?

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Vijay Budhram 2FA is not enabled.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
