### ISSUE TITLE
Responsive view too wide on short windows

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1186]
Noticed this today when resizing my window.
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/68213/58110537-b8255300-7bbd-11e9-9709-f0260d525168.png">

**Comment by shane-tomlinson** [comment]
I think this is due to the breakpoint changes from #864

**Comment by dannycoates** [comment]
fixed in #2404
