### ISSUE TITLE
Filter out irrelevant client side errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11865]
There are many errors on the client side coming through sentry that appear to be noise. This task involves trying to find an elegant way to filter out these errors. Initially we may want to consider tagging these irrelevant errors instead of filtering them out completely. This way we can double check that important errors are not incorrectly identified as irrelevant.

Here’s a list of things to investigate that may help decrease ‘noise’ in the client side error:

* Are there better client side sentry libraries that work with our frameworks? (@sentry/react is a good example.)
* Can the call stack be used to filter out errors?
* Can we make sure we are throwing strongly typed errors, ie throw new FxaTypeError('Boom') vs throw new Error('boom');

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4565)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
