### ISSUE TITLE
Rename `productName` to `productId` in `accountSubscriptions` table

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1187]
In PR #1174, I kind of tangled up renaming a column (good idea) and adding a column (not quite needed). Decided to just close that PR and run with the existing column in other PRs. As follow-up work, it might be good to circle back to actually just rename `productName` to `productId`

Mainly pushing this off as a follow-up because there's a lot of paperwork between fxa-auth-db-mysql and everything downstream from there that needs doing to reflect the change.

**Comment by lmorchard** [comment]
FWIW, this is the PR that I withdrew and filed this issue instead:

https://github.com/mozilla/fxa/pull/1174

In that PR, I renamed `productId` to `productName` and then added a new `productId`. Ended up being a +176 patch (not 300-400 like I overexaggerated in the last meeting)

Might be worth just dusting off that branch and seeing about shepherding it to a merge.

**Comment by philbooth** [comment]
Sticking my face on this, I have a branch ready to PR when we start the train 145 cycle...

**Comment by lmorchard** [comment]
FWIW, there's going to be some spots in fxa-payments-server that use productName too. I tried to [stick todo comments by them](https://github.com/mozilla/fxa/search?q=productName+todo&unscoped_q=productName+todo), but it's very likely I missed a bunch

**Comment by philbooth** [comment]
Yep, I picked up the ones in the auth server (I think that's what you meant?) and the event broker in my branch. PR coming shortly. The db change itself will be in two parts, so that the migration can run without breaking the existing stored procedures.

**Comment by philbooth** [comment]
Oh wait, no, you did mean the payments server sorry, just grepped. Okay, I'll pick those up tomorrow, thanks.
