### ISSUE TITLE
[subplat] Do Not Send a Subscription Cancellation Email on First Failed PayPal Subscription for Existing FxA User

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11873]
When an existing FxA user tries to subscribe to a product using PayPal, if the initial payment failed, their subscription won’t be successful.  However, they will incorrectly receive a subscription cancellation email.  That email is from the service deleting the subscription for which the payment attempt failed.  The deletion triggers a webhook event.  For unverified users using the “passwordless” flow, this bug is being fixed in [https://mozilla-hub.atlassian.net/browse/FXA-4489|https://mozilla-hub.atlassian.net/browse/FXA-4489|smart-link].  For existing FxA users, we need to ensure that the subscription was never successful in order to skip the cancellation email.  (Unfortunately the subscription delete even does not have the previous subscription status it its even data.)

To replicate in a test env: go to personal paypal account, and once you press pay with paypal in the checkout simultaneously remove payment source from the account.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4571)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
