### ISSUE TITLE
fxa-content-server does not pickup my custom URL, alway redirects me to http://localhost:9000/v1/account/status

### ISSUE THREAD

**Issue by AndiCorradi** [mozilla/fxa#11880]
I try to sign up for an new fxa account. After i enter the E-Mail address (http://mycustomurl:3030) , Firefox sends a request to http://localhost:9000/v1/account/status instead of http://mycustomdomain:9000/v1/account/status.
The Firefox Developer Tools shows that the request is comming from ../../../fxa-auth-client/dist/browser/lib/client.js/fetchOrTimeout/
I cant find any reference on how to modify the URL. I did change the URL in  /fxa/packages/fxa-content-server/server/config/local.json
but its not picked up. How i am supposed to change the URL ?
If i start firefox on the Serverinstance itself, it works just fine using the localhost URL
(Setup as outlined on: https://mozilla.github.io/ecosystem-platform/tutorials/development-setup)
thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4574)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
