### ISSUE TITLE
Update functional tests to FF 91.5 ESR

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11883]
This task is to update all our functional tests to FF 91.5 ESR (latest).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4579)

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

This is the PR : https://github.com/mozilla/fxa/pull/11876 ( https://github.com/mozilla/fxa/pull/11876|smart-link )

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

Not currently working on it.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
