### ISSUE TITLE
Design SMS Install Link Form

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa#119]
Merge designs into FxA-46 README.md

**Comment by ryanfeeley** [comment]
@seanmonstar Can you post screenshots of the experience you see in the US? If I avoid designing blind we'll have less issues.

**Comment by seanmonstar** [comment]
# Initial SMS Form

![sms form](https://cloud.githubusercontent.com/assets/51479/12956661/f090f9ae-cfdd-11e5-93c6-a991ca63b1b3.png)

# Error State

![error state](https://cloud.githubusercontent.com/assets/51479/12956685/0c596590-cfde-11e5-816a-adc39b0f6c76.png)

# Success

![success](https://cloud.githubusercontent.com/assets/51479/12956708/1bb90c84-cfde-11e5-9d75-da7af55c2bfa.png)

**Comment by seanmonstar** [comment]
To be clear, we will have our own form on the verification page, not link out to another page that has this. So experience would be:

1. Verification success! Good job, user!
2. Oh hey, by the way, would you like Firefox on your mobile? You can enter your phone number in this here form and we'll send you a custom link to install it!
3. Or maybe you'd like links to the Store pages instead?
4. But good on you!

**Comment by vladikoff** [comment]
cc @rfk is this still pending?

**Comment by seanmonstar** [comment]
Nope.
