### ISSUE TITLE
[subplat] [docs] Update coupons doc to avoid error in which a coupon makes purchase value too low for Stripe fees but above zero

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11942]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4614)

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Chelsea Lewis Anna Sobiepanek Could you please let us know what the QA needs to do on this one, if anything?

CC: Maria Berlinger Madalin Cotetiu

**Comment by annasob** [comment]
No tasks for the QA just be aware of https://mozilla.github.io/ecosystem-platform/relying-parties/reference/sub-plat-coupons page of coupon info.
