### ISSUE TITLE
Finish retiring gettext in the auth-server

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11960]
In [https://mozilla-hub.atlassian.net/browse/FXA-4371|https://mozilla-hub.atlassian.net/browse/FXA-4371|smart-link]

, we set up the infrastructure to retire gettext.

We still need to:

* Take the remaining {{subject}}s and {{action}}s which are set in {{emails.js}} to live in their own template directories, following the pattern set in [https://mozilla-hub.atlassian.net/browse/FXA-4371|https://mozilla-hub.atlassian.net/browse/FXA-4371|smart-link]

* Take the strings from at least {{sessions.js}} that use the {{gettext}} function, and use the new {{localizeString}} function from the new Localizer class to translate them. Create a new {{en.ftl}} file for these strings and probably place them in the {{l10n}} directory, update the grunt task to include this path
* Remove gettext and possibly other dependencies like po2json, remove outputting the entire l10n repo in the build since Fluent references {{public/locales}}
* Can we remove {{translator}} from being passed into the mailer?
* Add some more test coverage

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4623)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

The story points for this issue was a 5, but it’s being reduced to a 3 because the first bullet point was split to FXA-4674

**Comment by LZoog** [comment]
For tests, also consider throwing an error if `subject` is missing. [See comment](https://github.com/mozilla/fxa/pull/12057#discussion_r819893887).
