### ISSUE TITLE
Custom Sign-in behavior for MyFirefox

### ISSUE THREAD

**Issue by rtestard** [mozilla/fxa#11980]
## Description

We're looking to expose a Sign-in/up button to FxA on MyFirefox. This button will get users to enter the existing FxA flow on https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync (existing URL that users reach when accessing the FxA flow from the hamburger menu).
At the end of this flow users who have connected another device (this is our goal) end up on https://accounts.firefox.com/pair/auth/complete?client_id=[CLIENT_ID]&scope=profile+https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync+https%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&email=[EMAIL]&uid=[UID]&channel_id=[CHANNEL_ID]&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob%3Apair-auth-webchannel
where they are told to manage their devices.

In the MyFirefox case we want users to get back to the MyFirefox tab that they came from.

### Steps to reproduce
1 Sign-up with https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync
2 Add a device
3 Get to https://accounts.firefox.com/pair/auth/complete?client_id=[CLIENT_ID]&scope=profile+https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync+https%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&email=[EMAIL]&uid=[UID]&channel_id=[CHANNEL_ID]&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob%3Apair-auth-webchannel

### Expected result

1 SIgn-up with a custom URL, I assume that MyFirefox should use a custom entrypoint parameter:
 https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=myfirefox&action=email&service=sync
2 Add a device
3 Get to a new page that congratulates users and shows a visual indicating them where they should go next - Click the "MyFirefox" tab

### Actual result

This is not supported currently, this issue is a request for an improvement

### Environment

Firefox on all systems

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4633)

**Comment by rtestard** [comment]
This is not the final UX (final UX will be addressed once our UX resources complete the MyFirefox experience but this should give an idea of what is expected UI-wise: 
![image](https://user-images.githubusercontent.com/866979/155322656-3472b0a7-4d91-4637-9345-8744f7dc5849.png)

**Comment by clouserw** [comment]
@rtestard I think this is doable in your timeline.  When will you have the final designs?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Hi Romain Testard we’re doing Q2 planning and need to confirm your requested timeframe.

  1. When will designs be finalized?
  2. When is the requested go-live date for this effort?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per Romain,  ( https://mozilla.slack.com/archives/C4D36CAJW/p1648057650461259 )go live is targeted for Fx 106 (Nightly start 8/22/22). Design team is focused on other priorities for at least the next four weeks, so earliest we could conceivably pick this up would be FxA Sprint 232, much more likely FxA Sprint 233. I’ll move this ticket to 233 accordingly, and we will await final design timelines before commitments.

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Chelsea Lewis is this already done?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Hi Vesta, not yet - it’s scheduled in FxA Train 235 (planning is on Wednesday)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Vesta Zare Chelsea Lewis and Wil Clouser  to talk about this

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

We will take care of this requirement in FXA-5321 ( https://mozilla-hub.atlassian.net/browse/FXA-5321 )
