### ISSUE TITLE
[FF Monitor] Can’t change email preferences from Firefox Account

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1202]
**Clone of [952]**(https://github.com/mozilla/blurts-server/issues/952)

**Affected versions:**
Firefox 67.0, 69.0a1

**Affected Platforms:**
Windows 10 x64
macOS 10.13
Ubuntu 18.04 x64
Android

**Steps to reproduce:**
1. Navigate to https://fx-breach-alerts.herokuapp.com/
2. Sign in with a valid account.
3. Click on the profile picture and select Firefox Account.
4. Look down the page and click on "Change..." button from the "Email preferences" section.

**Expected result:**
"Subscribe" and "cancel" options are displayed.

**Actual result:**
An error is displayed on the page.

****Notes:** not reproducible on https://monitor.firefox.com/**

![EmailPreferencesError](https://user-images.githubusercontent.com/24588037/58171220-24778380-7c9e-11e9-8eb5-10f0c44dcf7e.jpg)

**Comment by shane-tomlinson** [comment]
fx-breach-alerts points to stable.dev.lcip.org, which has no way of getting the information needed to open the communication preferences or opt the user into any newsletters. Only the production FxA instance is able to do so.

**Comment by shane-tomlinson** [comment]
ref https://github.com/mozilla/fxa/issues/656
