### ISSUE TITLE
Update text for unlinking third party account

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12028]
From https://github.com/mozilla/fxa-content-server-l10n/pull/554, we should update the text per l10n request.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4652)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This ticket is verified as done on Production [Train 227.1] under Windows 10 64-bit. The text is correctly updated. See new situation:

!unlink account modal.PNG|width=359,height=288!
