### ISSUE TITLE
Performance gainz in new email Renderer/Localizer, add more test coverage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12045]
In [this PR](https://github.com/mozilla/fxa/pull/11962), we split the FluentLocalizer class into Renderer and Localizer.

We made a couple of performance gains using `Promise.all` where we could, but there’s even further optimizations that could be done:

* We can run `setupLocalizer` less often, perhaps placing it on the constructor for reference or memoizing it
* ~We do _not_ need to attempt localizing messages if the `acceptLanguage` is `en` or `en-US` from within the browser context. These should use the English fallback text within the MJML files and shouldn’t be checked against the Fluent Bundle. However, we want this localization to occur in Storybook since our tests test the fallback text and we use Storybook to double check what we have in Fluent files. We have “bindings-node” and “bindings-browser” to place a check for if we should attempt to localize English or not.~
  * Edit: at the time of writing we've talked about deploying en/en-US strings [in this spike|FXA-4477], so we might want to consider that at this time
  * Edit2: we’re deploying these strings now, so this bullet point no longer applies
* Can we parallelize any other calls in `Localizer` or `Renderer`? There’s at least one place in the Renderer bindings that has an `if (layout) { // other promise`  we should look at. Also double check that our `Promise.all`s are doing what we expect them to… do we actually need to change our `fetchResource` to become the async version of `readFileSync`?
  * Can/should we actually be using dynamic `import` instead of reading files, in any places? It looks like `require` and `import` cache the results while reading the file from fs does not.

Edit: also see comments on this ticket

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4654)

**Comment by LZoog** [comment]
Be sure to look at [this comment](https://github.com/mozilla/fxa/pull/12167#discussion_r837779011) as well as other mentions in other PRs. Also, are there any places we can use `formatValues` instead of `formatValue`?

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I’m bumping this up to a 5 pointer because ** we should also make an effort to increase our test coverage in the Renderer and Localizer files**.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
