### ISSUE TITLE
r.print is not a function is not a function in GetDataTrio

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12049]
[https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10991564/?query=is%3Aunresolved](https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10991564/?query=is%3Aunresolved)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4656)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
