### ISSUE TITLE
Performance Observer Is Not Defined

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12048]
[https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10988260/?query=is%3Aunresolved](https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10988260/?query=is%3Aunresolved)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4655)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
