### ISSUE TITLE
[fxa-auth-server] Prettier autoformats files with single or double quotes depending on the directory in VS Code

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12085]
In normal development, I have the root `fxa` folder open in VS Code, and prettier prefers single quotes there. However, when I need to debug an auth server test, I open the fxa-auth-server dir, and prettier prefers double quotes there.

The consequence is any file I open/touch gets automatically reformatted and saved in contradiction to the other workspace's quote config.

If we don't want the same quote preferences for the whole project, we should give priority to the config of the furthest down directory or remove the autoformatting.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4677)

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

We should have one top-level prettier config and not others - use wherever we run prettier.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
