### ISSUE TITLE
Use AWS SES libraries instead of SMTP

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12095]
With the move to sending emails with fxa-auth-server we started talking SMTP to SES instead of using their libraries.  This resulted in a change to some of our reporting, but arguably more importantly, also changed the order of bounce processing so we are at risk of lowering our reputation score until we switch back to using their libraries.  It doesn’t take much work, so let’s do it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4680)

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Ready for SRE review https://github.com/mozilla-services/cloudops-deployment/pull/4554 ( https://github.com/mozilla-services/cloudops-deployment/pull/4554|smart-link )

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I wonder if there was a related patch for the fxa repository that didn’t land here

**Comment by clouserw** [comment]
This should be hitting https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/email.js#L261 and firing up SES.  

The errors were 502 / gateway errors.  We'll investigate more on Thursday.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

In the SRE meeting last week we were aiming to get this done by that Friday.  Did we make any progress here?  Is there a new ETA?

**Comment by data-sync-user** [comment]
➤ Dustin Lactin commented:

Deployed SES changes to stage, sending mail returns the following error: 

{
  "textPayload": "TypeError: ses.sendRawEmail is not a function",
  "insertId": "4fymf4erimxh",
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "moz-fx-fxa-nonprod-375e",
      "zone": "us-east-1a",
      "instance_id": "i-01e709eecc809c65a"
    }
  },
  "timestamp": "2022-04-14T20:09:57.442648982Z",
  "labels": {
    "type": "auth_server",
    "stack": "default",
    "application": "fxa",
    "env": "stage",
    "compute.googleapis.com/resource_name": "fxa-stage-default-auth_server"
  },
  "logName": "projects/moz-fx-fxa-nonprod-375e/logs/docker.fxa-auth",
  "receiveTimestamp": "2022-04-14T20:09:58.909588072Z"
}Issue on the node mailer repo with the same error: https://github.com/nodemailer/nodemailer/issues/1293 ( https://github.com/nodemailer/nodemailer/issues/1293|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
