### ISSUE TITLE
Subscription Platform emails aren't using emailTypes like FxA emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12098]
[https://mozilla-hub.atlassian.net/browse/FXA-4682](https://mozilla-hub.atlassian.net/browse/FXA-4682|smart-link)  has some context

If you look at the [EMAIL_TYPES constant](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/metrics/amplitude.js#L22) you’ll see a mapping of `emailTemplate` to `emailType`.  The `emailType` is a rough category that lets people see related emails when looking at logs/metrics.  You can see this if you look at the older FxA emails in the same EMAIL_TYPES dictionary.

The Subscription Platform emails are mapping the template names to types of the same name.  I would expect them to map to a few broad categories like the FxA emails.  Is this a mistake or on purpose?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4683)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

SubPlat is pretty sure we use the emailTypes to monitor if specific emails have been sent out (e.g. subscription reminder, payment failed). If we implement broader categories for emailTypes, we should be able to use the template name but we need to look into this.

Are there docs for how FxA makes use of these categories?  Do we want to coordinate cross teams on the use of these?

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Anna Sobiepanek what kinds of categories are we looking for here for subplat emails? From a metrics/amplitude perspective what would be good to track?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

There are outdated docs at https://docs.telemetry.mozilla.org/datasets/fxa_metrics/emails.html ( https://docs.telemetry.mozilla.org/datasets/fxa_metrics/emails.html|smart-link )  .  I have  PR up to update them.  I don’t have a PR for the subplat emails yet.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
