### ISSUE TITLE
The emailTypes table should be emailTemplates

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12097]
I stumbled into some confusion over email_template, email_type, EMAIL_TYPES and more, so I’m writing this as much to get my thoughts in order as to get this documented for anyone else searching for these strings.  

In our logs we have two fields set for each email we send:  `email_template` and `email_type`.  The template is the actual name of the template we’re sending (with “Email” appended for some reason, but that’s not what this bug is about…), like `verifyEmail` or `newDeviceLoginEmail`.  The type is a broad category that collects related templates together, like `registration` or `secondary_email`.  You can find that mapping in the [fxa-auth-server’s amplitude.js](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/metrics/amplitude.js#L22). 

There is also a [database table called emailTypes](https://github.com/mozilla/fxa/blob/main/packages/db-migrations/databases/fxa/patches/patch-114-115.sql#L17) but it’s **filled with the template names** instead of the types.  Since holding the template names is the right use of the table, it should be renamed to emailTemplates.

Since this affects the database and foreign keys I don’t want to just change it without some discussion.  I think the solution to this issue could be any of:

1. We make a migration to rename emailTypes to emailTemplates including the foreign key references
1. We decide it’s not worth dealing with this and add some comments in the code and wontfix this issue
1. Maybe something else :slightly_smiling_face:

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4682)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
