### ISSUE TITLE
Short URL with smart redirect to app stores for SMS install

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa#121]
Do we use `https://mzl.la`? Something more descriptive like `get.firefox.com`?

The page is redirects to will need to redirect to the appropriate Store based on OS. This could be as simple as an apache config to redirect with User Agent matching.

**Comment by rfk** [comment]
> The page is redirects to will need to redirect to the appropriate Store based on OS.
> This could be as simple as an apache config to redirect with User Agent matching.

It's probably useful for us to control this endpoint and emit metrics events when it is accessed.

**Comment by shane-tomlinson** [comment]
@seanmonstar - can you triage these as you see appropriate?

**Comment by rfk** [comment]
I discovered today that this exists and seems to do the right thing on all platforms:  https://firefox.com/m

It also appears to take utm_* parameters that we may be able to use for metrics purposes.

**Comment by vladikoff** [comment]
from meeting: need to confirm we can get metrics from https://firefox.com/m

cc @ryanfeeley

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/3497#issuecomment-228806222
