### ISSUE TITLE
Tests can pass yet docker build in deploy stage can fail

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12104]
In the following build we can see that all tests have passed, yet the build failed. This is due to a type script compilation in the docker build process. [https://app.circleci.com/pipelines/github/mozilla/fxa/28178/workflows/66599e37-f27c-4842-9861-85f19eff3ded/jobs/313226](https://app.circleci.com/pipelines/github/mozilla/fxa/28178/workflows/66599e37-f27c-4842-9861-85f19eff3ded/jobs/313226)

It appears that there are slight differences between what running a test through esbuild will allow and what the typescript compiler (`tsc --build`) will allow. 

We should add a ‘build’ pipeline to our regular ci, that runs `yarn workspaces foreach --topological-dev --verbose run build` to ensure this sort of scenario doesn’t arise.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4686)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
