### ISSUE TITLE
Tweak our release process docs in ecosystem-platform (patch releases)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12105]
Mostly based on helping out with release ownerships the last few weeks, I believe the dot release section of our release process docs is a little confusing or at least, we can tweak it to be more explicit. We can at least document that the tag automatically deploys to staging (if we don’t note that), how to handle situations like what happened this week where we needed a 227.1 and a 226.5, etc.

I sent a message containing this recently to someone and while we do document the first two scenarios here, I think it can be tweaked to be a bit more explicit.

We generally have a couple ways of doing the dot release.

1. Create an uplift branch, like `train-227-uplift-1`, branched off of `train-227`
  1. On the uplift branch, cherry-pick the needed commits [todo: figure out if it’s always merge commit, normal commit, etc…?]
  1. Get a PR up to merge `train-227-uplift-1` into `train-227`
  1. After approval, tag with the `patch` release command on `train-227` and follow the instructions printed out, PR `train-227` back into `main`

1. Cherry-pick in the commit directly into `train-227`, then follow 1c

1 ensures all changes and commits are reviewed before the release is actually tagged, and **is recommended** in most cases, but also fine once you get comfortable if it’s only one commit to just go straight to step 2.

There’s also another case to know about, where someone may know they need something in a dot release, so they actually PR directly into the uplift branch like `train-227-uplift-1` instead of PR’ing into `main`. This can make it easier on the release owner, because they can basically skip to the second option mentioned there^ rather than cherry-pick in stuff manually and getting approval

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4687)

**Comment by biancadanforth** [comment]
Quoting Dan's comment in a related Slack thread, since this also came up recently for SubPlat:
> Also should we have more guide lines about what scenarios Merritt a dot release. For example, a regression clearly does, but what if you just barely miss the train. I feel like I’ve seen us do a dot releases for that kind of thing, but I could be mistaken. It seems like more of an exception that a rule though.
