### ISSUE TITLE
Not all the information in the support tichet confirmation modal is translated

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12110]
**Affected FxA versions**:

* 1.227.1;

**Prerequisites**:

* Have a FXA account with an active subscription for Mozilla VPN;
* Be in a Mozilla VPN EU supported country (in this case NL);
* Have the browser language or system language set to NL;
* Be on Subscription Management page;

**Steps to reproduce**:

1. Click on "Contact Support" button;
1. Complete all mandatory fields and click on the Send button;
1. Take a look at the confirmation modal;

**Expected result**:

* All the information in the modal is displayed in the user language;

**Actual result**:

* The support ticket reason is displayed in English, regardless of the user language;

**Notes**:

* See the attached screenshot.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4690)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21350">image_2022_03_08T13_13_07_661Z.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
