### ISSUE TITLE
Paypal processor logs are filled with warnings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12115]
This is a small sample from today (docker_fxa_paypal_processor_20220308):

|textPayload|timestamp|
|----|----|
|Update this package.json to use a subpath pattern like "./*".|2022~~03~~08 04:15:06.889139 UTC|
|(Use `node -~~trace~~deprecation ...` to show where the warning was created)|2022~~03~~08 04:15:06.889190 UTC|
|(node:1) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /fxa/node_modules/fxa~~shared/package.json.\|2022~~03-08 04:15:06.889067 UTC|
|(node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/fxa/node_modules/po2json/package.json' of './lib/po2json'. Please either fix that or report it to the module author|2022~~03~~08 04:15:06.889238 UTC|
|Update this package.json to use a subpath pattern like "./*".|2022~~03~~08 05:15:06.624495 UTC|
|(node:1) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /fxa/node_modules/fxa~~shared/package.json.\|2022~~03-08 05:15:06.624373 UTC|
|(Use `node -~~trace~~deprecation ...` to show where the warning was created)|2022~~03~~08 05:15:06.624551 UTC|
|(node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/fxa/node_modules/po2json/package.json' of './lib/po2json'. Please either fix that or report it to the module author|2022~~03~~08 05:15:06.624704 UTC|
|(node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/fxa/node_modules/po2json/package.json' of './lib/po2json'. Please either fix that or report it to the module author|2022~~03~~08 02:15:06.41531 UTC|
|(node:1) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /fxa/node_modules/fxa~~shared/package.json.\|2022~~03-08 02:15:06.40695 UTC|
|Update this package.json to use a subpath pattern like "./*".|2022~~03~~08 02:15:06.40787 UTC|
|(Use `node -~~trace~~deprecation ...` to show where the warning was created)|2022~~03~~08 02:15:06.40863 UTC|
|(node:1) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /fxa/node_modules/fxa~~shared/package.json.\|2022~~03-08 02:15:05.243412 UTC|
|(node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/fxa/node_modules/po2json/package.json' of './lib/po2json'. Please either fix that or report it to the module author|2022~~03~~08 02:15:05.244258 UTC|
|(Use `node -~~trace~~deprecation ...` to show where the warning was created)|2022~~03~~08 02:15:05.244222 UTC|
|Update this package.json to use a subpath pattern like "./*".|2022~~03~~08 02:15:05.243832 UTC|
|"minify" option is deprecated in mjml~~core and only available in mjml cli.\|2022~~03-08 02:15:58.882908 UTC|

I’m assuming these are all warnings.  I don’t see these in other logs.  Is our loglevel higher on the paypal processor?  Is that on purpose?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4692)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I actually see this in the docker_fxa_subscription_reminders_* tables as well.  Let me know if I should file a separate issue.

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Wil Clouser is the concern here that these are cluttering the logs or making them harder to parse? The logs for prod are set to info (and therefore include warnings). I assume we want to capture warnings.

Per Bianca Danforth we see these in CI and result from depracated features/packages.

Should we be fixing these issues as opposed to omitting them from the logs?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Well, my main concern is:  are these on purpose?  Since I didn’t see them from other servers I thought it was worth asking.  I wonder if the other servers are set to loglevel info.

Secondarily, they do clutter things up, but that’s not as critical.  Are these an expected side effect of running a node service? If so this can probably be wontfixed as we’re never going to have 100% of our packages caught up at all times.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

{quote}Since I didn’t see them from other servers I thought it was worth asking.{quote}

I think that is due to the fact that you are looking at the logs of a script and these errors appear at startup.  You don’t see them as often with services.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Filed and linked two jiras.  Closing this one.

**Comment by rusackas** [comment]
Did you guys find a solution to the po2json warnings? I can't see the JIRAs, but still running up against the same issue, so 🤞

**Comment by pdehaan** [comment]
> Did you guys find a solution to the po2json warnings? I can't see the JIRAs, but still running up against the same issue, so 🤞

@rusackas Which version of po2json are you using?
I found https://github.com/mikeedwards/po2json/pull/97 which might imply that it it was "fixed" 3 years ago, but the last npm publish might have been 4 years ago: https://www.npmjs.com/package/po2json so maybe that change never made it into a published version.

Although digging deeper, I found https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/package.json#L92 which might also lead me to think we're using https://github.com/mozilla-fxa/grunt-po2json#2f415c8ac0435bf8942dc7131c3916ecd1684a46 instead of the other po2json lib directly.

**Comment by rusackas** [comment]
Thanks for looking into it @pdehaan! I think your detective work is accurate, and the fix was made after the last version published. 

Good to know about `grunt-po2json` as well... although that seems like it hasn't seen much repo activity either.

I wonder if there are newer/current tools for working with .pot/.po files, or if that's all just passé at this point and in need of some major revamp ¯\\\_(ツ)_/¯

**Comment by rusackas** [comment]
Oh, almost forgot to mention, we're using po2json 0.4.5, the "newest" version :D
