### ISSUE TITLE
[pocket migration] FAQ link is displayed on "Enter your email" page instead of "Create a Firefox account" page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12127]
**Build:**

Production [Train 227.1]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Prerequisites:**

N/A

**Steps to reproduce:**

1. Go to [http://getpocket.com](http://getpocket.com|smart-link)  and click Sign up for Pocket button.
1. Enter an email address that doesn’t have associated an account and click Sign up.
1. Observe the “Create a Firefox Account Continue to pocket” page.
1. Click Change email and then observe the “Enter your email Continue to pocket” page.

**Actual result:**

The FAQ “Why do I need to create this account? [Find out here](https://support.mozilla.org/en-US/kb/pocket-firefox-account-migration)” is displayed on “Enter your email” page instead of “Create a Firefox Account” page.

**Expected result:**

The FAQ “Why do I need to create this account? [Find out here](https://support.mozilla.org/en-US/kb/pocket-firefox-account-migration)” is displayed on “Create a Firefox Account” page. (see [Figma](https://www.figma.com/file/Kbsn8uiEwqSLueQh5tAycQ/FxA---Design-Changes-2022?node-id=62%3A281))

**Notes:**

! Also the “Sign in” page displays the wrong FAQ text - according to [Figma](https://www.figma.com/file/Kbsn8uiEwqSLueQh5tAycQ/FxA---Design-Changes-2022?node-id=62%3A281) it should be “Why do I have to use this account? Find out here“.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4699)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21455">Create account page.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21453">Enter email - FAQ link.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21454">FXA sign in - FAQ link.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
