### ISSUE TITLE
Add documentation for expectations around test data in stage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12125]
This is coming out of the stage instability last week due to an account with a large number of sessions.  We discussed it in our SRE meeting and decided on filing this issue.

We should add to our documentation:

* Customers are expected to clean up any test data left on FxA platforms in a reasonable fashion.  A single account from someone manually testing isn’t a big deal but any kind of integration with automated testing should be cleaning up data.  This likely just means deleting any accounts made, as that will include any session data that was made.
* We should also add a short example of how to do this to our docs.  Danny found an example: [https://github.com/mozilla/fxa/blob/main/packages/functional-tests/lib/fixtures/standard.ts#L45](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/lib/fixtures/standard.ts#L45|smart-link) 
`target.auth` here is a `fxa-auth-client` 
[https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-client/lib/client.ts#L535](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-client/lib/client.ts#L535|smart-link) 
* If they’re using PyFxA there is a `destroy_account()` api: [https://pypi.org/project/PyFxA/#testing-email-addresses](https://pypi.org/project/PyFxA/#testing-email-addresses|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4696)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
