### ISSUE TITLE
[google auth][FxA-Settings] Google Play badge issue on iOS and Safari browser

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12123]
**Build:**

Production

**Affected platforms:**

iOS 15.2

Windows 10 - Safari browser

**Browsers tested on:**

Firefox, latest release

Safari, latest release

**Prerequisites:**

The user has a Google account linked to FxA account.

The user is logged in to Pocket and FxA settings page.

**Steps to reproduce:**

1. Go to the Connected Services section and observe the Google Play badge.

**Actual result:**

The logo on the badge is missing the blue color.

**Expected result:**

The logo on the badge is correctly displayed.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4694)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21415">Google Play badge issue on iOS.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
