### ISSUE TITLE
Signing Into Pocket Shows Line for Why Account Should Be Created

### ISSUE THREAD

**Issue by lolrepeatlol** [mozilla/fxa#12138]
## Description

Signing into Pocket with your *existing* Firefox account brings up a line saying "Why do I need to create this account? Find out here"

### Steps to reproduce

1. Go to https://getpocket.com/
2. Click "sign in."
3. Click "Continue with Firefox"
4. Observe the line asking why I need to create an Fx account.

### Expected result

The line should not appear for existing accounts -- only for ones in the process of being created.

### Actual result

The line appeared for an existing Firefox account.

### Environment

What browser and operating system are you using?
Firefox Nightly 100 (2022-03-11) on Fedora Linux 35

![image](https://user-images.githubusercontent.com/17863082/158000599-b8d22a68-f1a2-4d75-ab91-d78f0fb5ebe6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4701)

**Comment by vbudhram** [comment]
@lolrepeatlol Looks like this was in the orginal design [spec](https://www.figma.com/file/Kbsn8uiEwqSLueQh5tAycQ/FxA---Design-Changes-2022?node-id=62%3A281). However, I think your proposal makes sense and we shouldn't show for exisiting users.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on Stage [Train 230] under Windows 10 64-bit. I confirm that FAQ link is not displayed on “Sign in Continue to Pocket” page anymore when using an existing account.

!no FAQ link on Sign in page.png|width=366,height=502!
