### ISSUE TITLE
Move Subscription Display to SubscriptionItem component from CancelSubscriptionPanel component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12149]
Currently, if there is an active subscription in the manage subscription page, the display logic for the subscription info (price and renewal) is handled by the CancelSubcriptionPanel component that switches what is returned based on whether or not the subscription is active or not. 

Since we are now using the subsequent invoice for pricing, we should move the display logic to the SubscriptionItem component to avoid having to do a bunch of checks and price determination in the CancelSubscriptionPanel component.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4704)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
