### ISSUE TITLE
Tests failing for CI checks while updating to FF 91.5 ESR

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12150]
This is the PR: 
There are 2 ‘Pairing’ tests that are failing for the checks on every try. This is only happening for Stage and it passes locally for me.

Actions taken to fix it:

* I tried upgrading the Selenium version, but that didn’t help.
* I verified that the FF 91.5 ESR upgrade has nothing to do with it
* I tried running the checks multiple times which didn’t help

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4705)

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

I tried updating the ESR version to 91.6 locally and I don’t think it had any effect since previously also everything was passing locally for me and this time too it did.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
