### ISSUE TITLE
Improve the spacing of the App and Play Store badges

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1215]
UX team request to cease the hard right/left alignment of our App and Play Store badges on all screens that contain them.

CURRENT
![Screen Shot 2019-05-22 at 3 15 34 PM](https://user-images.githubusercontent.com/68213/58202762-64426900-7ca6-11e9-960f-56c37aa6df29.png)

PROPOSED (centered, 1/2 height of badge apart, 22px)
![Screen Shot 2019-05-22 at 3 20 45 PM](https://user-images.githubusercontent.com/68213/58202773-699fb380-7ca6-11e9-98d7-7d3134874109.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-99)
┆Issue Number: FXA-99

**Comment by kunalmohan** [comment]
Hi! I would like to work on this issue. I would need some guidance, like the url for the above webpage.

**Comment by PrachiSarda** [comment]
Hey! Can I take up this issue?

**Comment by 6a68** [comment]
@ryanfeeley Hey, I'm curious why UX would want to do this. Doesn't moving buttons closer together increase the likelihood of a user clicking the wrong button?

**Comment by vbudhram** [comment]
Hey @kunalmohan Are you still interested in this issue? If not @PrachiSarda you are welcome to take it.

If you open the page https://accounts.firefox.com/connect_another_device in Chrome or any non-Firefox browser, you will see the screen above. The css for the elements are located [here](https://github.com/mozilla/fxa/blob/c4ffbda3ff9ddc90d43516a03e624ae23e5739fb/packages/fxa-content-server/app/styles/modules/_marketing.scss#L1).

Hope that helps!

**Comment by kunalmohan** [comment]
I am not working on this issue. @PrachiSarda feel free to take this up.

**Comment by SaumyaSinghal** [comment]
I'm fairly new to this but I'd love trying to fix it. Can I take this up?

**Comment by victorphoenix3** [comment]
Are you working on this @SaumyaSinghal ? Can I work on this?

**Comment by clouserw** [comment]
@jodyheavener should this issue be closed?

**Comment by jodyheavener** [comment]
Yes, thanks.
