### ISSUE TITLE
Upgrade Tailwindcss (tailwind) from 1.9.1 to 3.0.23

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12154]
Upgrade Tailwindcss from 1.9.1 to 3.0.23 - this might require separate tickets, as there needs to be upgrades in the following:

* fxa-admin-panel
* fxa-payments-server
* fxa-settings

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4707)

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

In case it might save you some time, we might need to upgrade react-scripts before upgrading to Tailwind 3. Similar issue ( https://stackoverflow.com/questions/70403408/tailwind-css-3-0-5-classes-is-not-working-with-react )

**Comment by pdehaan** [comment]
Probably not 100% relevant since we're migrating from 1.x to 3.x, but this is a pretty good read&hellip; https://daily-dev-tips.com/posts/upgrading-tailwind-v2-to-v3/

```sh
git ls-files packages | grep "tailwind.config.js"
  # packages/fxa-admin-panel/tailwind.config.js
  # packages/fxa-payments-server/tailwind.config.js
  # packages/fxa-react/tailwind.config.js
  # packages/fxa-settings/tailwind.config.js

git grep '"tailwindcss":' packages | cat
  # packages/fxa-admin-panel/package.json:    "tailwindcss": "^1.9.1",
  # packages/fxa-payments-server/package.json:    "tailwindcss": "1.9.1",
  # packages/fxa-react/package.json:    "tailwindcss": "^1.9.1",
  # packages/fxa-settings/package.json:    "tailwindcss": "^1.9.1",
```
