### ISSUE TITLE
Node DEP0148 in fxa-shared/package.json

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12168]
{quote}[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /fxa/node_modules/fxa-shared/package.json.{quote}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4715)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
