### ISSUE TITLE
Apple Auth follow ups

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12163]
From https://github.com/mozilla/fxa/pull/12148/files there were a couple items that we should tackle in a follow up issue.

- [ ] Add documentation to eco system docs about what the configs do and mean

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4711)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Vijay Budhram is this gonna be follow up past this sprint or in this sprint?

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This is a dupe
