### ISSUE TITLE
Missing documentation for /v1/session/verify_code

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12162]
This endpoint is currently used by the FxA web-client and by Mozilla VPN to verify a session code received by email.
It's a POST request, with a JSON body containing:

* code
* service: the FxA client id
* scopes: an array of scopes, percent-encoded.

It would be nice to have the documentation page updated.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4710)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
