### ISSUE TITLE
Pricing missmatch when using the FR locale

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12174]
**Affected FxA versions:**

* 1.228.0;

**Prerequisites:**

* Have the browser language or system language set to FR;
* Be in a Mozilla VPN EU supported country (FR);
* Have a FxA account withount a subscription;

**Steps to reproduce:**

1. Open the Mozilla man page: [https://www-dev.allizom.org/fr/products/vpn/](https://www-dev.allizom.org/fr/products/vpn/|smart-link)  ;
1. Select each of the plans and confirm the price on the Set up your subscription page (Configuration de votre abonnement);

**Expected result:**

* The prices on the page match;

**Actual result:**

* The prices on the pages do NOT match; 

**Notes:**

* See the attached video

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-1995)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21759">2022-03-17_14h02_28.mp4</a>

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

i'm not sure the dev server is meant to be correct? in particular it often points to a $1/day plan for testing. Valentina Virlics - thoughts?

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

As far as I have seen, for other locales the plans from the main page match the ones from Set up your subscription page, except the ones where the monthly plan is set to 1$ daily, to help with testing.

In this particular case, neither of the plans match and the monthly plan is indeed monthly.

The matching is nice to have, since we have tests in our test suites to check for that 🙂 

Thank you.

CC: Valentina Virlics

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Moving this to the VPN project as there doesn’t appear to be anything that FxA or SubPlat can do for this as this is not our landing page.

It sounds like the desired action would be that the one which points to $1/day has copy that indicates it’s a daily plan, I believe that’s what Luminita is asking for here. Betty Fleming FYI that I’ve moved this, please adjust as necessary.

**Comment by data-sync-user** [comment]
➤ Betty Fleming commented:

Brian Yee

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Hello, 
Thank you for looking into this.
For the FR locale, the monthly is actually monthly, which is ok. We do not need it to be daily.

What the issue is about is that the prices in the landing page do not actualy match the prices on the subscription page at all, for neither plans. Please see video for more details.

Thank you.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,
This is reproducible for DE locale too.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

As a note, these issues need to be also reported on bedrock and/or fxa depending on which one is wrong. But it’s good to report here so we can keep track of it.

That said, I would personally only recommend reporting if they’re an issue in production. I would not have expected the dev / staging servers to be guaranteed to be correct on actual price amounts.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Hello,
This is reproducible for CH locale too.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
