### ISSUE TITLE
Export errors in FxA since mid-December

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12172]
There is an `export_errors_*` table in `moz-fx-fxa-prod-0712.fxa_prod_logs` that has data going back to mid-December.  It looks like mostly stuff coming out of the customs server.  

/cc [~accountid:6047cbd9ad0d2e0068412955] [~accountid:60c368e4d5dde80071a4207c]

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4719)

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

The reason this happens is that JSON keys with the same name must have the same type for Big Query to store them. In this case, jsonPayload.err is a String in some log messages, and an Object in other log messages. Looking at the code, a quick fix might be changing https://github.com/mozilla/fxa/blob/5c505840c59d83ad2fba5c9944ede02fe3c16523/packages/fxa-customs-server/lib/server.js#L351 ( https://github.com/mozilla/fxa/blob/5c505840c59d83ad2fba5c9944ede02fe3c16523/packages/fxa-customs-server/lib/server.js#L351|smart-link )  to err: err.toString()

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
