### ISSUE TITLE
Node DEP0128 in po2json

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12170]
{quote}(node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/fxa/node_modules/po2json/package.json' of './lib/po2json'. Please either fix that or report it to the module author{quote}

We need to submit a patch or maybe even fork.  The module hasn’t been updated in at least a couple years.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4716)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
