### ISSUE TITLE
Pocket FAQ redirects to english only

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12175]
From [slack](https://mozilla.slack.com/archives/C022HUNDWTB/p1647536268537499), this should redirect to the language set in browser.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4722)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

The following languages were verified on Stage [Train 230] under Windows 10 64-bit: German, French, Spanish (es), Italian (it), Japanese, Polish, Chinese (China), Russian. I confirm that the FAQ link is redirecting the user to the FAQ page correctly localized.

!italian pocket FAQ.png|width=678,height=527!

!Japanese pocket FAQ.png|width=680,height=494!

!german pocket FAQ.png|width=682,height=584!

!french pocket FAQ.png|width=668,height=527!

!spanish es pocket FAQ.png|width=670,height=549!
