### ISSUE TITLE
Subscription IDs are being recorded in the fxa-auth-server logs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12186]
For some reason the auth server emits an event for every request (!!) including the URL.  Whether or not that’s a good idea, it means the logs have a bunch of `route./oauth/subscriptions/active/sub_xxxxx.yyy` events in them.

We should add that regex to the [ignore list](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/metrics/events.js#L69).

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4727)

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

We have graphs that use URLs and aggregate requests per URL, so having lower cardinality is desired rather than including URLs with unique ids.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
