### ISSUE TITLE
Login screen has odd layout at certain breakpoints

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12194]
## Description

Unexpected UI when page width is 576px to 640px pixels wide.

### Steps to reproduce

1. Go to https://accounts.firefox.com/ and resize your browser width.

### Expected result

More consistent UI when making the page wider or narrower.

### Actual result
![Screen Shot 2022-03-21 at 12 12 02 PM](https://user-images.githubusercontent.com/557895/159347056-04726de5-35f8-424e-9714-211149d4c476.png)
**Figure 1:** <=520px viewport. Everything fine up until 520px wide.

![Screen Shot 2022-03-21 at 12 13 38 PM](https://user-images.githubusercontent.com/557895/159347195-4753ba23-d60c-4e5b-8a9e-4bf76681ef6f.png)
**Figure 2:** 510px <=> 575px viewport. Everything fine up until 575px wide (we go from full page to a panel UI).

![Screen Shot 2022-03-21 at 12 14 38 PM](https://user-images.githubusercontent.com/557895/159347304-b96534fe-f188-46fd-8d7b-3c782a1ed285.png)
**Figure 3:** 576px <=> 640px viewport. Oddly at 576px wide (1px wider than **Figure 2** above), the UI gets SMALLER and we lose all top padding. This UI seems to be the same from 576 <=> 640px wide.

![Screen Shot 2022-03-21 at 12 15 53 PM](https://user-images.githubusercontent.com/557895/159347597-c85a079e-fab4-492d-9b57-f46e34e624d2.png)
**Figure 4:** 640px viewport (same behavior as above).

![Screen Shot 2022-03-21 at 12 17 31 PM](https://user-images.githubusercontent.com/557895/159347909-756004ab-e549-40e2-a95a-01a91d7ef150.png)
**Figure 5:** >=641px viewport. Seems to match the UI of the 510px <=> 575px viewport.

### Environment

macOS 12.2
Firefox Beta (and Chrome)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4732)

**Comment by pdehaan** [comment]
Oh, that's interesting! It also seems to be height based.
![Screen Shot 2022-03-21 at 12 24 35 PM](https://user-images.githubusercontent.com/557895/159348779-c1825e21-7c70-46fc-9c53-bc2cfa212cd7.png)
**Figure 6:** 576px wide by 575px high.

![Screen Shot 2022-03-21 at 12 25 18 PM](https://user-images.githubusercontent.com/557895/159348909-f1f45ddf-5519-4051-8119-8464ce240391.png)
**Figure 7:** 576px wide by 576px high (1 px taller than previous screenshot)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

We have standardized our breakpoints in at least Settings, this config is in tailwind.js, but they’re not shared with content-server right now.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
