### ISSUE TITLE
FxA should remember "Looking for Firefox Sync?" banner state

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12197]
## Description

"Looking for Firefox Sync?" banner keeps reappearing after being dismissed.

### Steps to reproduce

1.  Go to https://accounts.firefox.com/ (make sure you're not logged in)
2. Dismiss that "_Looking for Firefox Sync? **Get started here**_" banner under the header.
3. Refresh the page.

### Expected result

Banner was dismissed. Not sure if we should set a cookie or something and remember that decision for at least 24h.

### Actual result

Banner keeps reappearing on each page reload.

![Screen Shot 2022-03-21 at 11 35 28 AM](https://user-images.githubusercontent.com/557895/159341135-9e115e90-7c39-48a0-83e8-82cc95531106.png)

A small-_ish_ nit, but I was swapping accounts over and over and it was getting annoying that it kept reappearing.

### Environment

macOS 12.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4733)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
