### ISSUE TITLE
Please obtain positive confirmation that the user understands the implications of resetting their password

### ISSUE THREAD

**Issue by unforgettableid** [mozilla/fxa#12201]
### Steps to reproduce

* Go to https://accounts.firefox.com/
* Enter your Firefox account's email address.
* Click "Forgot password".

### Actual result

You'll see a ["Reset password" screen](https://accounts.firefox.com/reset_password).  This screen includes some warning text about how you may lose your history and your synchronized passwords.

![image](https://user-images.githubusercontent.com/10241454/159417702-c970c147-21bf-4eaf-8195-51482577cb8c.png)

The warning text was added thanks to mozilla/fxa-content-server#6213 by @rfk, and is definitely helpful.

Unfortunately, some people don't read very carefully, so I suppose they might ignore the warning text.

### The problem

Users may be expecting to just reset their password, and may not be expecting to lose data from the sync server.

I may be overthinking things, and worrying unnecessarily (which I sometimes do).  But I suspect that, for a case like this, it's best to obtain positive confirmation that the user understands that they'll lose data.  This is probably better than just showing some warning text and hoping that the user reads it.

### Expected result

As Jakob Nielsen [suggests](https://www.nngroup.com/articles/confirmation-dialog/#:~:text=For%20particularly%20dangerous%20operations%2C%20require%20a%20nonstandard%20action%20from%20the%20user%20to%20confirm.), I think it might be a good idea to require users to take a nonstandard action, to make sure they're aware that they may lose data.  For example, FxA could tell the user:

Please enter your email address:  `_________________`

If any history, bookmarks, and/or synchronized passwords are stored on the server, they will be permanently erased from the server when your password is reset.  This is because we encrypt your data with your password, to protect your privacy.  You’ll still keep any subscriptions you may have, and Pocket data will not be affected.

Please enter the word "erase" into this input box, to confirm that you are willing to lose any bookmarks and/or synchronized passwords stored on the server:  `__________`

`[ Begin reset ]`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4734)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Thanks for filing. We agree your suggestion would be more ideal.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
