### ISSUE TITLE
Some pages super wide on Latest

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1220]
We noticed in Sync Fest that if browser height is reduced, some pages, like this one, are super wide. They should not get wider.
![superwide](https://user-images.githubusercontent.com/68213/58205587-dd44bf00-7cac-11e9-8f72-a8c42c5b4bf5.gif)

**Comment by shane-tomlinson** [comment]
I think this is due to the breakpoint changes from https://github.com/mozilla/fxa/pull/864

**Comment by shane-tomlinson** [comment]
Dup of #1186.
