### ISSUE TITLE
The "Refresh connected services" button doesn't stop spinning on https://accounts.firefox.com/settings

### ISSUE THREAD

**Issue by mkaply** [mozilla/fxa#12222]
## Description

If you login to FxA and navigate to https://accounts.firefox.com/setting and then scroll down and click "Refresh connected services" in the "Connected Services" section, it switches to a beachball and never returns. The browser is responsive, and everything works, it just stays spinning.

### Steps to reproduce

1. Login to FxA
2. Navigate to https://accounts.firefox.com/setting
3. Scroll down to "Connected Services" section
4. Click "Refresh connected services"

### Expected result

The cursor should spin for a moment and then things should refresh and it should stop spinning

### Actual result

The cursor stayed spinning forever.

### Environment

I tried Firefox as well as Edge with two different Firefox accounts and saw the same results.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4744)

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Dan Schomburg fyi not sure if this was part of ur work that went out

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Hello, this seems to be a duplicate of https://mozilla-hub.atlassian.net/browse/FXA-3454 ( https://mozilla-hub.atlassian.net/browse/FXA-3454|smart-link )

**Comment by mkaply** [comment]
I'm fine with duping, but that ticket is almost a year old now.
