### ISSUE TITLE
Add support @sentry/react for react apps

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12235]
Sentry will capture richer traces for react applications using this integration. Where ever we use react apps this should be applied.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4752)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
