### ISSUE TITLE
Consolidate Sentry Initialization for HAPI services

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12231]
During the sentry migration it became apparent there was quite a bit of boilerplate code for sentry copy and pasted between projects. This task is to reduce this code by moving common boilerplate to fxa-shared.

Acceptance Criteria:

* Redundant sentry initialization code is consolidated across services using HAPI
* Error handling code for HAPI errors is consolidated across services using HAPI

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4749)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
