### ISSUE TITLE
Update Firefox logo to master brand logo globally

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1223]
Per our discussion @shane-tomlinson , let's update the Firefox logo everywhere with the new master brand logo. (old flows, new flows, all entrypoints, mobile, etc)

https://docs.google.com/presentation/d/1DdpZ2BUJxmThph8quqhZF80TT_SBADHlB6SGa4klKLE/edit#slide=id.g5a28a9fc8d_7_464

I'm 99% confident that this can go out on June 3rd with the rest of the release. It seems that we're a few teams wanting to roll out the branding changes a day early since June 4th release is very early morning.

CC @ryanfeeley

**Comment by shane-tomlinson** [comment]
@vbudhram - mind taking care of the email template portion of this?

**Comment by vbudhram** [comment]
> mind taking care of the email template portion of this?

Done!

@ryanfeeley Does this include the favicon logo? If so could you provide the favicon.ico?
