### ISSUE TITLE
Possible to use fxa-geodb on requests to get-metrics-flow?

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#1224]
So I've realized that we don't have country attribution on top-of-funnel for hosted forms (e.g. the registration email form on about:welcome). So we only attribute country once the user has entered the FxA funnel proper. 

When we kick off a form view event based on a request to `metrics-flow` would it be possible to attribute the requester's country to the resulting amplitude `fxa_email_first - view` event?

The result is that we can currently only calculate conversion rates (flow completes/hosted form views) only globally. 

https://github.com/mozilla/fxa/blob/0bac0db9d6097c565a069c06d36e74c2c5c5a766/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js

Since trailhead is focused on US, UK, CA, FR and DE it would be nice to be able to do this segmentation. 

CC @davismtl

**Comment by philbooth** [comment]
Fwiw, looks like the code should be all there in `server/lib/amplitude.js` for this to just work, so it seems like an actual bug that it's not working. Maybe some property is named incorrectly along the journey from the front-end to the back or something. Probably a straightforward fix.

**Comment by irrationalagent** [comment]
So here's what I think is happening:

This line is setting the `metricsData` to be whatever's contained in the request's query parameters (?):
https://github.com/mozilla/fxa/blob/0bac0db9d6097c565a069c06d36e74c2c5c5a766/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js#L77

The query parameters don't contain any location data. `metricsData` then passed as the `data` argument to amplitude here:
https://github.com/mozilla/fxa/blob/0bac0db9d6097c565a069c06d36e74c2c5c5a766/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js#L98

`server/lib/amplitude.js` then looks for a `.location` property of `metricsData` here:
https://github.com/mozilla/fxa/blob/793f90b557e1f98ff378d8ccbd0103a76bf87d49/packages/fxa-content-server/server/lib/amplitude.js#L152

It doesn't find one, so there's nothing to log. 

assuming I'm right about this (def could be wrong), I think the solution is to is to import `geolocate` to `get-metrics-flow.js` and do something like 

```js
metricsData.location = geolocate(req);
```

Then the rest **should** work?

**Comment by philbooth** [comment]
Spot-on analysis, that!

> I think the solution is to is to import `geolocate` to `get-metrics-flow.js` and do something like 
> 
> ```js
> metricsData.location = geolocate(req);
> ```

Yep, I think this is probably the right approach, because the amplitude code is also called from `flowEvent.js` which already does its own geolocation call.
