### ISSUE TITLE
Upgrade sass-loader dependency from 10.1.11 to 13.0.2+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12247]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12080](https://github.com/mozilla/fxa/pull/12080)

The number of failures doesn't look too bad.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4758)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
