### ISSUE TITLE
Explore and Instrument Slow Routes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12248]
We are seeing sporadic slowdowns on the token server and auth sever. There was a meeting with SRE this morning, where we investigated metrics graphs and tried to gain insight into what might be the root cause of the issue. Here’s a quick summary of the findings.

1. Issue can be alleviated by changing CPU scaling thresholds. 
1. During a latency spike, average CPU rate appears to be falling.
1. During a latency spike, there doesn’t appear to any major spike in redis or mysql; however, we are seeing a lot of activity and some slowness on the refresh tokens queries.

The above behaviors seem to indicate some sort of blocking behavior on the server that isn’t CPU bound. This could be due to DB calls, lack of caching in some scenarios, cache misses, or certain users that trigger abnormally large amounts of data getting pulled from the DB.

This task has a couple components, with a desired outcome of gaining better insight into the code.

1. Audit the current code paths that query / update the refresh tokens table, because this table appears to be the table under contention.  
1. Add sentry instrumentation around SQL queries. 
1. Add sentry instrumentation around Redis queries.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4759)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
