### ISSUE TITLE
Two MDN Plus headers in upgrade email

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12242]
## Description
Bought a $5/mo subscription to MDN this morning on production with my LDAP email and personal credit card (hold for applause) Shortly after, I upgraded to an annual subscription at $50/yr. When the upgrade email came in, I noticed that it had two MDN Plus logos in the header area
 
### Steps to reproduce
1. Buy a $5/mo subscription to MDN Plus.
2. Upgrade your subscription to $50/yr.
3. Wait for emails from FxA.
 
### Expected result
ONe logo
 
### Actual result
Two MDN Plus logos in header

![Screen Shot 2022-03-24 at 3 18 40 PM](https://user-images.githubusercontent.com/557895/160019821-92fbd773-c1d1-4d2e-acd5-2971a2dde628.png)
 
### Environment
macOS 12.2

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4757)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22312">arrow_between_icons_upgrade.png</a>

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Peter. Reino observed there’s also an issue with one of our template values ($5 per interval is not substituting correctly). Let’s also fix that while we’re in here.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Reino also pointed out that perhaps there are two logos here, because the upgrade could be between two different products. I.e. perhaps there’s supposed to be an arrow in between here.

We should look at the original upgrade specs for this email to see what the original expectation was.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Whoever works on this should investigate if this is the same resolution as https://mozilla-hub.atlassian.net/browse/FXA-4755 ( https://mozilla-hub.atlassian.net/browse/FXA-4755|smart-link ).

**Comment by pdehaan** [comment]
> Thanks Peter. Reino observed there’s also an issue with one of our template values ($5 per interval is not substituting correctly). Let’s also fix that while we’re in here.

Yeah, sorry I missed the triage meeting. Don't worry about the template variable issue. See
- https://github.com/mozilla/fxa/issues/12239 (https://mozilla-hub.atlassian.net/browse/FXA-4755)

@peiying2 already fixed that in pontoon and caught it in 5 other locales as well, so we should have that covered. ❤️

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Peter deHaan can we put this on ur list to recheck when the new translations come out? I believe april 13th.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Per [one of the original upgrades design specs](https://app.zeplin.io/project/5d49cdb7b9c7ee31343591e7/screen/5dd57d2d56cd633730c788fe ( https://app.zeplin.io/project/5d49cdb7b9c7ee31343591e7/screen/5dd57d2d56cd633730c788fe|smart-link ) ), while no emails are shown, there is an arrow between the two icons in the web content, so perhaps we can add an arrow to the email.

!arrow_between_icons_upgrade.png|width=664,height=751!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
