### ISSUE TITLE
Remove or modify `linkAttributes` in email.js

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12259]
In `email.js`, `linkAttributes` ([see in code](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/email.js#L150)) is the following:

      function linkAttributes(url) {
        // Not very nice to have presentation code in here, but this is to help l10n
        // contributors not deal with extraneous noise in strings.
        return `href="${url}" style="color: #0a84ff; text-decoration: none; font-family: sans-serif;"`;
      }Since we’ve refactored our l10n as well as our email templates, this can likely be modified/refactored.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4761)

**Comment by LZoog** [comment]
Closing this ticket in favor of #13439

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
