### ISSUE TITLE
WError: Email account hard bounced

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fxa#12264]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/19059119/?referrer=github_plugin

```
WError: Email account hard bounced
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/error.js", line 787, in Object.AppError.emailBouncedHard
    return new AppError(
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/bounces.js", line 69, in null.<anonymous>
    throw ERRORS[type](tally.latest);
  ?, in Array.forEach
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/bounces.js", line 59, in applyRules
    bounces.forEach((bounce) => {
  ?, in runMicrotasks
...
(3 additional frame(s) were not displayed)
```

Since it was an unhandled promise rejection, we are missing any useful information like who the customer is that didn't get the email as a result of this error.

We should catch these errors, so that we can log some information that would allow us to e.g. contact the customer via Support or retry in the case of soft bounces.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4766)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
