### ISSUE TITLE
Create account flow is blocked after going backwards from the “Create a Firefox Account” page 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12269]
**Build**: 

Stage [Train 228.4]

**Affected platforms**: 

macOS Monterey Version 12.2.1

Windows 10 64-bit

**Browsers tested on**: 

Nightly Version 96.0.3 (64-bit)

Firefox, latest release

**Preconditions**: 

User is logged in [https://addons-dev.allizom.org/en-US/firefox/](https://addons-dev.allizom.org/en-US/firefox/|smart-link).

**Steps to reproduce**:

1. Sign out from [https://addons-dev.allizom.org/en-US/firefox/](https://addons-dev.allizom.org/en-US/firefox/|smart-link)  .
1. Click on the “Login in” button.
1. Click on “Use a different account”.
1. Type a new email address which contains @softvision.com or @mailinator.com and does not have associated a Firefox Account and click on the “Continue” button.
1. Click on the browser Back button.
1. Click on the “Continue” button.

**Expected results**: 

The user is redirected to “Create a Firefox Account” page.

**Actual results**: 

“Continue” button is not working anymore. The user is not forwarded to the next account creation step.

**Notes**: 

Reproducible for @softvision.com or @mailinator.com email addresses.

Not reproducible with emails that have a Firefox account associated.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4767)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22211">Screen Recording 2022-03-25 at 10.08.51.mov</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Does this affect any emails besides softvision and mailinator?  Is production affected?

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Wil Clouser Production is also affected for @softvision.com and @mailinator.com addresses. We tested with other email addresses (gmail, yahoo, mozilla, outlook) but these are not affected.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
