### ISSUE TITLE
Set NodeRendererBindings as default constructor value in Localizer and Renderer

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12260]
Wherever we instantiate `Localizer` or `Renderer`, we have to pass in `NodeRendererBindings` or `BrowserRendererBindings` (storybook only). We should be able to set `NodeRendererBindings` as the default so we don’t have to import those bindings in everywhere, but whenever I’ve tried doing this in the parameter list or in the constructor itself, the browser bindings for Storybook (running `yarn storybook` inside `fxa-auth-server`) don't appear to get set for whatever reason.

See [here for example](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/email.js#L303):

`this.renderer = new Renderer(new NodeRendererBindings());`

We should be able to just use `new Renderer()` instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4762)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
