### ISSUE TITLE
Users with 3rd party authentication are prompted for a non-existent password

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12283]
To reproduce:

1. Log in with a 3rd party account (eg. Google)
1. Log Out
1. Go back to [accounts.firefox.com](http://accounts.firefox.com) and you’ll get the password prompt with the pre-filled email address.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4776)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23503">image-20220504-211929.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

To reproduce:

  1. https://accounts.stage.mozaws.net/?forceExperiment=thirdPartyAuth&forceExperimentGroup=google ( https://accounts.stage.mozaws.net/?forceExperiment=thirdPartyAuth&forceExperimentGroup=google )
  2. Click “Continue with Google” and go through Google’s flow
  3. Log out
  4. Load https://accounts.stage.mozaws.net/ ( https://accounts.stage.mozaws.net/ ) and type in your Google email address and click Continue
  5. You are prompted for a password but your account doesn’t have one locally so you won’t be able to log in

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

An idea: After step 4, we can check if their account doesn’t have a password and if it has any linked accounts.  If they have a single linked account we redirect to that login flow as if they had clicked the “Log in with _____” button.  If they have multiple linked accounts we show the log in form without the email option.  Example:

!image-20220504-211929.png|width=651,height=441!

We should probably add the email they are using and the “Use a different email” on link on there too.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
