### ISSUE TITLE
Update wording on prompt when unlinking accounts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12280]
We should revisit the wording on the 3rd party account unlinking text.  A quick fix would be to replace “those services” with “your connected services”.

!s2D9cMdP8776fMZSnFSkVcuXmLyWT-FkYJiUFFT1pQqp1VUgeqdXbFqkwKe7aIeCp48OqczIwftKu7zq9YafGlZSBd1Q3Ab7ra_aNSXtTogusknlCMyW-hgV6U7gZmgscKGuBnTP|width=886,height=558!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4773)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22248">s2D9cMdP8776fMZSnFSkVcuXmLyWT-FkYJiUFFT1pQqp1VUgeqdXbFqkwKe7aIeCp48OqczIwftKu7zq9YafGlZSBd1Q3Ab7ra_aNSXtTogusknlCMyW-hgV6U7gZmgscKGuBnTP</a>

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Do we need product or content verification here, or good to go, Wil Clouser ?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let’s go with what’s in comment 0

**Comment by millsoper** [comment]
Found a conflict between the copy hardcoded into the jsx and the copy in the l10n file, so pausing to follow up on which to keep (the conflict is just a comma present in the jsx and absent elsewhere)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on Stage [Train 232] under Windows 10. The wording on account unlinking text is updated. “those services“ is replaced with “Connected Services“. Comma is added after “To do that…“. See new situation:

!unlink prompt new situation.png|width=346,height=254!
