### ISSUE TITLE
[FxA-Settings] Profile photo is not correctly displayed when the photo is rotated

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12296]
**Build:**

Stage [Train 229]

**Affected platforms:**

Windows 10 64-bit

macOS 10.14

Android 12

iOS 15.2

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

N/A

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and log in with an existing account.
1. Go to Profile picture section and click Add.
1. Add a photo and then rotate it once.
1. Click Save.
1. Observe the profile picture.

**Actual result:**

The photo is incorrectly displayed when rotated and then saved.

**Expected result:**

The photo is correctly displayed when rotated.

**Notes:**

Same issue occurs when a photo taken with the camera si rotated.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4783)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22337">issue when rotating photo.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
