### ISSUE TITLE
Audit list of supported languages in fxa-shared

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12294]
## Description

We have a list of supported languages at: https://raw.githubusercontent.com/mozilla/fxa/main/packages/fxa-shared/l10n/supportedLanguages.json, but many of these locales have ~35% translation rates currently. 
Per https://pontoon.mozilla.org/projects/firefox-accounts/, many of these locales seem to be below the 70% translation rate (mentioned in https://mozilla.github.io/ecosystem-platform/reference/localization#future-directions--possible-improvements).

Not sure if we should disable them on production until the number is closer to 70-80%.

### Steps to reproduce

```js
import axios from "axios";
import pontoonql from "pontoonql";

const supportedLanguages = await getSupportedLanguages();
const pontoonStats = await pontoonql("firefox-accounts", 0);

const localeMap = pontoonStats.reduce((map, item={}) => {
  return map.set(item.locale.code, item);
}, new Map());

const res = supportedLanguages.map(lang => {
  const {progress, locale} = localeMap.get(lang) || {};
  let warn;
  if (progress === 100) {
    warn = ":tada:";
  } else if (progress === 0 || progress === undefined) {
    warn = "Alias?";
  } else if (progress < 70) {
    warn = ":warning:";
  }
  return { lang, name: locale?.name, percent: pctFormat(progress), warn };
});

for (const r of res) {
  const name = r.name ? ` (${r.name})` : "";
  console.log(`[${r.lang}](https://pontoon.mozilla.org/${r.lang}/firefox-accounts/)${name} | ${r.percent} | ${r.warn || ""}`)
}

async function getSupportedLanguages() {
  const res = await axios.get("https://raw.githubusercontent.com/mozilla/fxa/main/packages/fxa-shared/l10n/supportedLanguages.json");
  return res.data;
}

function pctFormat(value=0, precision=1) {
  if (value === 100 || value === 0) {
    precision = 0;
  }
  return `${value.toFixed(precision) }%`;
}
```

### Expected result

Fewer supported languages in production?

### Actual result

| LOCALE | PROGRESS | NOTES
|:----|----:|:----| 
[ar](https://pontoon.mozilla.org/ar/firefox-accounts/) (Arabic) | 34.1% | ⚠️ 
[ast](https://pontoon.mozilla.org/ast/firefox-accounts/) (Asturian) | 31.3% | ⚠️ 
[az](https://pontoon.mozilla.org/az/firefox-accounts/) (Azerbaijani) | 32.0% | ⚠️ 
[be](https://pontoon.mozilla.org/be/firefox-accounts/) (Belarusian) | 64.9% | ⚠️ 
[bg](https://pontoon.mozilla.org/bg/firefox-accounts/) (Bulgarian) | 30.6% | ⚠️ 
[bn](https://pontoon.mozilla.org/bn/firefox-accounts/) (Bengali) | 32.0% | ⚠️ 
[ca](https://pontoon.mozilla.org/ca/firefox-accounts/) (Catalan) | 48.4% | ⚠️ 
[cak](https://pontoon.mozilla.org/cak/firefox-accounts/) (Kaqchikel) | 74.3% |
[cs](https://pontoon.mozilla.org/cs/firefox-accounts/) (Czech) | 86.0% |
[cy](https://pontoon.mozilla.org/cy/firefox-accounts/) (Welsh) | 100% | 🎉 
[da](https://pontoon.mozilla.org/da/firefox-accounts/) (Danish) | 99.4% |
[de](https://pontoon.mozilla.org/de/firefox-accounts/) (German) | 100% | 🎉 
[dsb](https://pontoon.mozilla.org/dsb/firefox-accounts/) (Sorbian, Lower) | 99.5% |
[el](https://pontoon.mozilla.org/el/firefox-accounts/) (Greek) | 100% | 🎉 
[en](https://pontoon.mozilla.org/en/firefox-accounts/) | 0% | Alias?
[en-GB](https://pontoon.mozilla.org/en-GB/firefox-accounts/) (English (Great Britain)) | 100% | 🎉 
[en-CA](https://pontoon.mozilla.org/en-CA/firefox-accounts/) (English (Canada)) | 100% | 🎉 
[en-US](https://pontoon.mozilla.org/en-US/firefox-accounts/) | 0% | Alias?
[es](https://pontoon.mozilla.org/es/firefox-accounts/) (Spanish) | 49.2% | ⚠️ 
[es-AR](https://pontoon.mozilla.org/es-AR/firefox-accounts/) (Spanish (Argentina)) | 100% | 🎉 
[es-CL](https://pontoon.mozilla.org/es-CL/firefox-accounts/) (Spanish (Chile)) | 100% | 🎉 
[es-ES](https://pontoon.mozilla.org/es-ES/firefox-accounts/) (Spanish (Spain)) | 100% | 🎉 
[es-MX](https://pontoon.mozilla.org/es-MX/firefox-accounts/) (Spanish (Mexico)) | 100% | 🎉 
[et](https://pontoon.mozilla.org/et/firefox-accounts/) (Estonian) | 69.2% | ⚠️ 
[eu](https://pontoon.mozilla.org/eu/firefox-accounts/) (Basque) | 62.0% | ⚠️ 
[fa](https://pontoon.mozilla.org/fa/firefox-accounts/) (Persian) | 36.7% | ⚠️ 
[ff](https://pontoon.mozilla.org/ff/firefox-accounts/) (Fulah) | 26.6% | ⚠️ 
[fi](https://pontoon.mozilla.org/fi/firefox-accounts/) (Finnish) | 99.7% |
[fr](https://pontoon.mozilla.org/fr/firefox-accounts/) (French) | 99.7% |
[fy](https://pontoon.mozilla.org/fy/firefox-accounts/) | 0% | Alias?
[fy-NL](https://pontoon.mozilla.org/fy-NL/firefox-accounts/) (Frisian) | 100% | 🎉 
[gn](https://pontoon.mozilla.org/gn/firefox-accounts/) (Guarani) | 99.8% |
[he](https://pontoon.mozilla.org/he/firefox-accounts/) (Hebrew) | 93.3% |
[hi](https://pontoon.mozilla.org/hi/firefox-accounts/) | 0% | Alias?
[hi-IN](https://pontoon.mozilla.org/hi-IN/firefox-accounts/) (Hindi) | 50.1% | ⚠️ 
[hr](https://pontoon.mozilla.org/hr/firefox-accounts/) (Croatian) | 74.6% |
[hsb](https://pontoon.mozilla.org/hsb/firefox-accounts/) (Sorbian, Upper) | 99.5% |
[hu](https://pontoon.mozilla.org/hu/firefox-accounts/) (Hungarian) | 100% | 🎉 
[ia](https://pontoon.mozilla.org/ia/firefox-accounts/) (Interlingua) | 100% | 🎉 
[id](https://pontoon.mozilla.org/id/firefox-accounts/) (Indonesian) | 56.4% | ⚠️ 
[it](https://pontoon.mozilla.org/it/firefox-accounts/) (Italian) | 99.8% |
[ja](https://pontoon.mozilla.org/ja/firefox-accounts/) (Japanese) | 66.1% | ⚠️ 
[ka](https://pontoon.mozilla.org/ka/firefox-accounts/) (Georgian) | 99.1% |
[kab](https://pontoon.mozilla.org/kab/firefox-accounts/) (Kabyle) | 79.3% |
[kk](https://pontoon.mozilla.org/kk/firefox-accounts/) (Kazakh) | 28.7% | ⚠️ 
[ko](https://pontoon.mozilla.org/ko/firefox-accounts/) (Korean) | 83.7% |
[lt](https://pontoon.mozilla.org/lt/firefox-accounts/) (Lithuanian) | 34.0% | ⚠️ 
[lv](https://pontoon.mozilla.org/lv/firefox-accounts/) (Latvian) | 15.9% | ⚠️ 
[nl](https://pontoon.mozilla.org/nl/firefox-accounts/) (Dutch) | 100% | 🎉 
[nb-NO](https://pontoon.mozilla.org/nb-NO/firefox-accounts/) (Norwegian Bokmål) | 60.1% | ⚠️ 
[nn-NO](https://pontoon.mozilla.org/nn-NO/firefox-accounts/) (Norwegian Nynorsk) | 78.1% |
[pl](https://pontoon.mozilla.org/pl/firefox-accounts/) (Polish) | 100% | 🎉 
[pt](https://pontoon.mozilla.org/pt/firefox-accounts/) | 0% | Alias?
[pt-BR](https://pontoon.mozilla.org/pt-BR/firefox-accounts/) (Portuguese (Brazil)) | 100% | 🎉 
[pt-PT](https://pontoon.mozilla.org/pt-PT/firefox-accounts/) (Portuguese (Portugal)) | 93.0% |
[rm](https://pontoon.mozilla.org/rm/firefox-accounts/) (Romansh) | 99.1% |
[ro](https://pontoon.mozilla.org/ro/firefox-accounts/) (Romanian) | 70.6% |
[ru](https://pontoon.mozilla.org/ru/firefox-accounts/) (Russian) | 100% | 🎉 
[sk](https://pontoon.mozilla.org/sk/firefox-accounts/) (Slovak) | 100% | 🎉 
[sl](https://pontoon.mozilla.org/sl/firefox-accounts/) (Slovenian) | 92.9% |
[sq](https://pontoon.mozilla.org/sq/firefox-accounts/) (Albanian) | 97.0% |
[sr](https://pontoon.mozilla.org/sr/firefox-accounts/) (Serbian) | 66.2% | ⚠️ 
[sr-LATN](https://pontoon.mozilla.org/sr-LATN/firefox-accounts/) | 0% | Alias?
[su](https://pontoon.mozilla.org/su/firefox-accounts/) (Sundanese) | 52.3% | ⚠️ 
[sv](https://pontoon.mozilla.org/sv/firefox-accounts/) | 0% | Alias?
[sv-SE](https://pontoon.mozilla.org/sv-SE/firefox-accounts/) (Swedish) | 100% | 🎉 
[te](https://pontoon.mozilla.org/te/firefox-accounts/) (Telugu) | 30.1% | ⚠️ 
[th](https://pontoon.mozilla.org/th/firefox-accounts/) (Thai) | 68.6% | ⚠️ 
[tr](https://pontoon.mozilla.org/tr/firefox-accounts/) (Turkish) | 98.3% |
[uk](https://pontoon.mozilla.org/uk/firefox-accounts/) (Ukrainian) | 100% | 🎉 
[vi](https://pontoon.mozilla.org/vi/firefox-accounts/) (Vietnamese) | 100% | 🎉 
[zh-CN](https://pontoon.mozilla.org/zh-CN/firefox-accounts/) (Chinese (China)) | 99.4% |
[zh-TW](https://pontoon.mozilla.org/zh-TW/firefox-accounts/) (Chinese (Taiwan)) | 100% | 🎉 

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4782)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I went ahead and added this ticket to the “Modernize Localization” epic. There’s more notes in the spike in that epic about this ticket: FXA-4477 ( https://mozilla-hub.atlassian.net/browse/FXA-4477 )
