### ISSUE TITLE
Mozilla logo not displayed on settings

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1231]
Ref #1181, #536 

We added a Mozilla logo with a link to mozilla.org everywhere but the /settings page. Should we add it?

<img width="1386" alt="Screenshot 2019-05-23 at 11 08 02" src="https://user-images.githubusercontent.com/848085/58245060-d91bae80-7d4b-11e9-9736-a5b7c42d822e.png">

**Comment by ryanfeeley** [comment]
Is this a regression from @johngruen changes?

**Comment by johngruen** [comment]
I think i took it out per a request from @shorlander ... i am gonna close this in lieu of the pending settings redesign
