### ISSUE TITLE
Retrieve mapping of oauth clients and names from database to pass to metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12344]
Barry pointed out we map RP names in our metrics but we have to maintain that list manually.  We should pull it from the database (once, not on every page load!) so we have a single source of truth.

!image-20220401-174723.png|width=385,height=529!

Barry’s links are:

* [https://github.com/mozilla/fxa/blob/main/packages/fxa-shared/metrics/amplitude.js#L192](https://github.com/mozilla/fxa/blob/main/packages/fxa-shared/metrics/amplitude.js#L192|smart-link) 

* [https://mozilla-hub.atlassian.net/browse/FXA-4588?focusedCommentId=530574](https://mozilla-hub.atlassian.net/browse/FXA-4588?focusedCommentId=530574|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4790)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22414">image-20220401-174723.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
