### ISSUE TITLE
lastAccessTime should not be undefined

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#12373]
## Description
While doing a self hosting with v1.228.7, sync service do not work.  i found in `about:sync-log`  that it is related to `/account/devices` endpoint with error  `"status":500,"errno":999,"path":"/v1/account/devices"`

after some digging, i found that 
https://github.com/mozilla/fxa/blob/b89234128aec9d71181aeda16eef6dd84f0f6d9e/packages/fxa-shared/connected-services/util.ts#L95-L97 is conflicting with 
https://github.com/mozilla/fxa/blob/b89234128aec9d71181aeda16eef6dd84f0f6d9e/packages/fxa-auth-server/lib/routes/devices-and-sessions.js#L506

`lastAccessTime : undefined` is not allowed (by Joi validator)  in response of '/account/devices'

so maybe replacing `undefined` with `null` will work.

```javascript
 lastAccessTime: lastAccessTimeEnabled 
   ? mergedInfo.lastAccessTime 
   : null, 
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4814)

**Comment by jackyzy823** [comment]
Update:
Previous code is correct:
https://github.com/mozilla/fxa/blob/6e0607bd56c08d0b3b0473bf27261983c3d1068a/packages/fxa-auth-server/lib/db/index.js#L221-L223

**Comment by jackyzy823** [comment]
for now i use LASTACCESSTIME_UPDATES_SAMPLE_RATE=1 in env as a workaround.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
