### ISSUE TITLE
Firefox.com is recording very old email address and won't let people to delete the account!

### ISSUE THREAD

**Issue by MozillaSpywareDetected** [mozilla/fxa#12372]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

https://support.mozilla.org/en-US/questions/1372988

This is clear that your server is logging every single emails I assigned to your firefox account after the user delete it. This is clear violation of GDPR and also double standards of your statement talking about we-care-your-privacy.

### Expected result

What should happen?

Let user delete the account as it should be.

### Actual result

What happened.

You know what happened because you are blocking it right? Why? 

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4813)

**Comment by vbudhram** [comment]
Hey @MozillaSpywareDetected this is actually part of our work in https://github.com/mozilla/fxa/issues/9517. A workaround until we can land those fixes would be to reset your password and then delete your account.
