### ISSUE TITLE
Local storage account object has invalid `originalLoginEmail`

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12393]
## Description

The `originalLoginEmail` is incorrect after creating and swapping multiple secondary email and setting a new primary email. This should be unset when a user logs out.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4819)

**Comment by vbudhram** [comment]
We have encounter similar type bugs before, see https://bugzilla.mozilla.org/show_bug.cgi?id=1635027.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This was fixed in https://github.com/mozilla/fxa/pull/12453 ( https://github.com/mozilla/fxa/pull/12453|smart-link )
