### ISSUE TITLE
Don't allow login with secondary email to get to the signin screen

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12394]
## Description

We currently allow a user to enter a secondary email at the email first screen even though they can not actually login with it. We should show them an error along those lines.

Currently shown

![image](https://user-images.githubusercontent.com/1295288/161843049-927d311b-6328-4ae1-81ef-6847cefcc3cd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4818)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
