### ISSUE TITLE
Find a way to report on the number of unverified accounts 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12410]
The number of unverified accounts can inform us of how our system is getting used. Lets figure out a way to display this data so its readily available and maybe set up some threshold to alarm against so that we can investigate. 

Also we should run a script of all currently unverified accounts that also have a stripe account to see if we can uncover all of the fraudulent accounts. 

[~accountid:6047cbd9ad0d2e0068412955] [~accountid:60c368e4d5dde80071a4207c]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4831)

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

This is to capture unverified accounts, and unverified accounts that have an active subscription.

It should also capture  information like, when the account was created, etc.

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Reino Muhl What query should I be running to join the unverified accounts to the stripe customers? I don’t think I can do that, I see very few subscriptions in the accountSubscriptions table in prod.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Benjamin Bangert can you weigh in here?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
