### ISSUE TITLE
[L10n]: Remove obsolete strings from localized .po files

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa#12412]
## Description

There are tons of obsolete strings in localized `client.po` and `server.po` files. They don't show up on Pontoon, and they only exist in localized files, not in English. Here are the examples from `zh-TW` locale:

- https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/zh_TW/LC_MESSAGES/client.po#L2048
- https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/zh_TW/LC_MESSAGES/server.po#L96

### Steps to reproduce

Here are the examples from `zh-TW` locale:

- https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/zh_TW/LC_MESSAGES/client.po#L2048
- https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/zh_TW/LC_MESSAGES/server.po#L96

Look for strings starting with `#~`.

### Expected result

Remove the strings starting with `#~`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4832)

**Comment by peiying2** [comment]
@clouserw

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
