### ISSUE TITLE
Question about default avatar logic

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#12426]
## Description

I do not quietly understand the logic of `nextAvatar`

https://github.com/mozilla/fxa/blob/7c3d59f4fe48b9b8a8affa44d7f6c20138a56417/packages/fxa-profile-server/lib/routes/profile.js#L27-L30

Is `result.avatar.startsWith(monogramUrl)` necessary?

The situation is i'm working on self hosting.

I use url rewrite to make fxa-profile-server ( ie monogram avatar url https://profile.example.local/v1/avatar/k )  and fxa-profile-static (ie  uploaded avatar https://profile.example.local/img/a/<avatarid>)  sharing same domain.

So the logic of `nextAvatar` ( because monogramUrl is ` https://profile.example.local` here same as fxa-profile-static's prefix url )  make changing avatar not work under this situation.

So i hope that you could rethink about this logic. or at least use more clear determination like ```result.avatar.startsWith(`${monogramUrl}/v1/avatar/`) ```

Thanks.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4834)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
