### ISSUE TITLE
Loosing some fxa_pay_setup - 3ds_success events in the payment logs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12434]
While making a looker dashboard I noticed a discrepancy in our logs vs Stripe. I  picked a date in the past and queried both BigQuery and Stripe to see the MDN product numbers. BigQuery showed 3 events and Stripe showed 7.

Big query query 

    SELECT jsonPayload.fields.event_type, jsonPayload.fields.event_properties  
    FROM `moz-fx-fxa-prod-0712.fxa_prod_logs.stdout_20220408` where 
    jsonPayload.fields.event_type in ("fxa_pay_setup - 3ds_success") and 
    ( jsonPayload.fields.event_properties  like '%price_1KeG02JNcmPzuWtRlrSiLTI6%' or jsonPayload.fields.event_properties  like '%price_1KeG02JNcmPzuWtRuAnIgNHh%' 
    or jsonPayload.fields.event_properties  like '%price_1KeG02JNcmPzuWtRslZijhQu%' or jsonPayload.fields.event_properties  like '%price_1KeG02JNcmPzuWtR1oBrw8o6%')

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4838)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22742">Screen Shot 2022-04-11 at 4.05.48 PM.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22740">Screen Shot 2022-04-11 at 4.11.52 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Sarah Bird just in case ur curious

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
