### ISSUE TITLE
[L10n]: "x month discount" doesn't work for l10n; incorrect in English, too.

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa#12438]
## Description

This string needs to be updated in order to work for l10n: `{ $discountDuration } month Discount: -{ $invoiceDiscountAmount }`

They appear in these places:
https://github.com/mozilla/fxa-content-server-l10n/blob/9089b87179e8a744a0e0a044f2efa84c687db30a/locale/templates/auth.ftl#L461

https://github.com/mozilla/fxa-content-server-l10n/blob/9089b87179e8a744a0e0a044f2efa84c687db30a/locale/templates/auth.ftl#L593

### Expected result

Grammatically, the string is incorrect in English. Should be variable and unit should be hyphenated so it reads like `1-month discount:` or `3-month discount:`

`{ $discountDuration }-month Discount: -{ $invoiceDiscountAmount }`

### Actual result
x month can be 1 month or 2+ months. 

@clouserw

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4840)

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Peiying Mo  can you double check the pull request.

**Comment by peiying2** [comment]
> ➤ Anna Sobiepanek commented:
> 
> Peiying Mo can you double check the pull request.

Looks good. I will wait for it to show up on the weekly push to l10n. Thanks for the quick fix.

**Comment by clouserw** [comment]
Thanks @annasob

**Comment by peiying2** [comment]
@annasob additional feedback on this is that x-month discount creates issues for some languages. Basically we have two variables, one for `month` and one for `discount`. The current string addresses the amount correctly, but the duration still creates issues for some languages.

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Peiying Mo do you have further suggestions on the duration part?

**Comment by peiying2** [comment]
> ➤ Anna Sobiepanek commented:
> 
> Peiying Mo do you have further suggestions on the duration part?

I don't. I thought about the possibilities but couldn't come up with any. Just want to point it out.

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello Anna Sobiepanek ,

This is verified as fixed in Train 1.230.3. For the subscriptions with a coupon applied with a 3 month duration the hyphen is displayed.

See the attached screenshot.

!image-20220415-131900.png|width=658,height=550!
