### ISSUE TITLE
[email templates] Revise how we set up an email's `action`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12436]
A bit of cleanup is needed within our email templates regarding setting the fluent id, name of the text, and URL for an email’s `action`. It is currently hard-coded in more than one file for each template (`includes.json` and `index.mjml`) - e.g., currently `downloadSubscription` has two different `action` s - ‘Download <%productName%>’ (which is being used for metrics) and 'Get started' (which is the text that shows up in the email). It would be better to set/update `action` in one file. Also, we should potentially clean up `oneClickLink`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4839)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
