### ISSUE TITLE
Resetting a password deletes recovery key

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12452]
In the FxA Live session today we noticed that changing a password would also remove any recovery key for the account.  Since the two have separate controls in the interface they shouldn’t be tied together in this way.

STR:

1. Log in to your account
1. Set a recovery key
1. Change your password
1. Refresh the page - see that you no longer have a recovery key

Expected Results:

The recovery key should persist beyond password changes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4841)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Ben suggests this is by design:

A recovery key is generated based on the password that is on the account (which is why you need to enter your password to generate a recovery key) and allows a user to decrypt their data if their password is lost.  So, changing the password deletes the recovery key as it’s no longer valid.

So, the task here should be:

If a user has a recovery key set and they change their password we should have some UI that strongly suggests they create a new recovery key.  It would be good to have some advice from a UX person on the best way to go about this.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
