### ISSUE TITLE
[apple auth] Login and Create account screens do not display FxA or Pocket logo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12461]
**Build:**

Stage

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

N/A

**Steps to reproduce:**

1. Go to [https://accounts.stage.mozaws.net/?forceExperiment=thirdPartyAuth&forceExperimentGroup=google](https://accounts.stage.mozaws.net/?forceExperiment=thirdPartyAuth&forceExperimentGroup=google) and click “Continue with Apple” button.
1. Observe the logo and the text on Sign in page.

**Actual result:**

“Apple“ logo is displayed and no mention of Pocket in the text.

**Expected result:**

Shouldn’t the Pocket or FxA logo be displayed? And a mention that the user will be redirected to Pocket?

**Notes:**

Same for “Create account” page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4844)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22799">Apple sign in with FxA1.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22798">Create FxA account using AppleID.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23875">firefox-logo.svg</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Vijay Budhram please leave a comment about what needs to happen here and then reassign to Dustin Lactin

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Let's do 4548 in favor of this - Mill Sopercan you audit this ticket to ensure we're covering all of the requirements here for both Apple and Google support in 4548? Thank you!

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

(Disregard last/deleted comment from me)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

According to Apple developer docs, this icon will be automatically set to the primary app id of the developer account. Dustin Lactin when you get a moment could you check what the primary app is and if it has an icon set?

I would like to use this as the logo if possible.

!firefox-logo.svg|thumbnail!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
