### ISSUE TITLE
Allow RP to report malicious users and domains

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1246]
We currently have an IP block list. We'd like to explore expanding that to include:
- blocking specific accounts/emails
- block modifiers of an email if it was blocked (alex@gmail.com blocked would also block alex+123@gmail.com)
- blocking specific email domains (and their wildcard subdomains)

RP would like to be able to report these to us, even if it's just by email at first.

Context:
AMO is experiencing bots creating a lot of accounts on their sites to submit malicious add-ons. We need to help slow that down as they resolve the underlying issues.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-101)
┆Issue Number: FXA-101

**Comment by clouserw** [comment]
I think this is now being reported to the IPrep system (maybe that's not the right name?) and then we'll get notified from there.  @jvehent is that correct?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Yes, this should flow through iprepd
