### ISSUE TITLE
Add prettier-plugin-organize-imports to Payments, format files

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12467]
This plugin will help Payments keep its imports more organized and removes unused imports, of which we have several scattered about.

Add this plugin and run it on all Payments files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4847)

**Comment by pdehaan** [comment]
Interesting! TIL: there is also a native ESLint rule about this: https://eslint.org/docs/rules/sort-imports
Also seems to be https://www.npmjs.com/package/eslint-plugin-unused-imports for unused imports and vars.

**Comment by biancadanforth** [comment]
We currently have a [recommended extension, TS Hero](https://github.com/mozilla/fxa/blob/ccb45c5e3a5c46a4934d54d4011defb9ffe4e4f3/.vscode/extensions.json#L3), which sounds very similar to this plugin. I wonder if we need both?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
