### ISSUE TITLE
See if `--runInBand` applies to other tests.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12479]
When Ben fixed [https://github.com/mozilla/fxa/issues/9236](https://github.com/mozilla/fxa/issues/9236|smart-link)  it ended up making the tests run _way_ faster.  We should see if we can apply the same fix to other tests.

Context for this issue is 

[https://mozilla.slack.com/archives/CLV3KMZ8B/p1649880834478989](https://mozilla.slack.com/archives/CLV3KMZ8B/p1649880834478989|smart-card)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4854)

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

This option is available for all our packages that use Jest for their test runner.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
