### ISSUE TITLE
Add .eslintrc configs to React projects

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12481]
It was recommend that we add our defacto .eslintrc to the admin panel. However, doing so resulted in some errors being thrown around syntax in .tsx files. 

As part of this task, we should get to the bottom of what rule in the fxa eslint plugin resulted in these errors and either adapt our code or update the fxa eslint plugin accordingly.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4855)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
