### ISSUE TITLE
Audit npm package: chosen-js@https://github.com/mozilla-fxa/chosen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12494]
This package references a git hub repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4859)

**Comment by clouserw** [comment]
This is a fork with no local changes, but the upstream library is deprecated so we should figure out a replacement.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

If memory serves, it was to make some mobile related style updates and A11y related changes.  chosen-js hasn’t been updated in a few years?  is the current version newer?

Moreover, it’s currently in content-server, which I believe we plan to remove altogether?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
