### ISSUE TITLE
Audit npm package: Audit npm package grunt-po2json@https://github.com/mozilla-fxa/grunt-po2json

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12496]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4861)

**Comment by clouserw** [comment]
We have a couple of local patches here but they don't look important.  I think we could upgrade to the upstream library.

That said, I think we could also wontfix this in favor of finishing getting rid of gettext completely.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
