### ISSUE TITLE
Audit npm package: gobbledygook@https://github.com/mozilla-fxa/gobbledygook

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12495]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4860)

**Comment by clouserw** [comment]
I don't think we're even using this package anywhere...?

**Comment by pdehaan** [comment]
Odd, I only see it in package.json and the yarn.lock, but not any usages:

```sh
git grep -in "gobbledygook" | cat

package.json:87:    "gobbledygook": "https://github.com/mozilla-fxa/gobbledygook.git#354042684056e57ca77f036989e907707a36cff2",
yarn.lock:24144:"gobbledygook@https://github.com/mozilla-fxa/gobbledygook.git#354042684056e57ca77f036989e907707a36cff2":
yarn.lock:24146:  resolution: "gobbledygook@https://github.com/mozilla-fxa/gobbledygook.git#commit=354042684056e57ca77f036989e907707a36cff2"
yarn.lock:25865:    gobbledygook: "https://github.com/lloyd/gobbledygook/tarball/354042684056e57ca77f036989e907707a36cff2"
```

But I think it was just used back in the day to test fake-translations before strings had landed:

> _"This project contains a node.js implementation of "fake translation", which makes it easier to debug the internationalization of software."_

```sh
npm install gobbledygook
$ node
> require('gobbledygook')('Hello World!');
'¡pʅɹoＭ oʅʅǝH'
```

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
