### ISSUE TITLE
Users can lose access to their data in Firefox Account while resetting password.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12491]
Users can lose access to their data in Firefox Account while resetting password.
While we do notify them that they might lose their data, at this point they are already having no other way, unless they have Recovery Codes.

There is no mention of Recovery Codes anywhere during onboarding or password change flows. User has to figure out themselves to visit Firefox Account > Profile > Security > Recovery key in order to protect themselves in the future.

Suggestion 1: force creation/download of Recovery Key right after password is created/changed. This is similar to what 1Password is doing to ensure users are not locked out from their data.

Suggestion 2: send recovery code with account verification email when creating a new account.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4850)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Moving this to “New” as it cannot be considered triaged with multiple suggestions to move forward. 

Sergey Galich is this the same request as https://bugzilla.mozilla.org/show_bug.cgi?id=1762200 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1762200|smart-link )  ? If so - thank you for filing here, as our feature requests are completed in Jira.

Which team is making this request? What is the priority of this request? Does it relate to any other milestones or projects that we should be aware of?

**Comment by data-sync-user** [comment]
➤ Sergey Galich commented:

Chelsea Lewis yes, this is the same request as the linked Bugzilla bug.

This request comes from Credential Management team. Users report these issues to us when they realize they have lost access to all their saved passwords on all their linked devices.

I’d recommend high priority, because we are not helping users to restore access to their data.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Thank you Serg! We’ll review with our product manager and assess this priority relative to the upcoming projects.

**Comment by data-sync-user** [comment]
➤ Sergey Galich commented:

Related issue https://mozilla-hub.atlassian.net/browse/FXA-4990 ( https://mozilla-hub.atlassian.net/browse/FXA-4990|smart-link )

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Met with Lauren to go through the current flow. Will discuss with a user experience designer and propose a solution here to discuss in triage in 2 weeks.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
