### ISSUE TITLE
Audit npm package: browserid-crypto@https://github.com/mozilla-fxa/browserid-crypto

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12493]
This package references a git hub repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4858)

**Comment by clouserw** [comment]
This has a local patch but I don't think it's important.  That said, it's probably easier to wontfix this and ride along until we remove browserid-crypto support completely.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
