### ISSUE TITLE
Destroying a `refresh_token` should destroy all `access_tokens` that were created from it

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1249]
Ref https://github.com/mozilla/blurts-server/issues/992#issuecomment-495366822

If an RP destroys their refresh token, they might still have some active access tokens, and hence might still show up in the "devices and apps" list despite considering themselves "signed out".

It seems reasonable to me that destroying a `refresh_token` should also destroy any `access_tokens` that were created from it.

Implementing this would be complicated by two things:
* We don't currently link access tokens back to their originating refresh token, if any
* We're trying to reduce the lifetime of access tokens, and if the lifetime gets sufficiently small, perhaps there's no benefit to explicitly revoking them at all.

**Comment by shane-tomlinson** [comment]
I thought this was mentioned in the spec too.

> We're trying to reduce the lifetime of access tokens, and if the lifetime gets sufficiently small, perhaps there's no benefit to explicitly revoking them at all.

I doubt we'll drop the default below 24 hours any time soon, so revoking will still be beneficial. There is already [confusion around what revoking OAuth credentials means](https://github.com/mozilla/fxa/issues/1203), anything we can do to minimize surprises is beneficial.

**Comment by groovecoder** [comment]
FWIW I've got a PR to fix the issue for Monitor by revoking both access tokens when someone removes Firefox Monitor. https://github.com/mozilla/blurts-server/pull/999 So, no big pressure from our side.

**Comment by rfk** [comment]
Hrm, I'll probably need to figure something out for this as part of #1262 because otherwise disconnecting a refresh-token client will not work correctly.

**Comment by shane-tomlinson** [comment]
Now that access token pruning takes place and the tokens table, adding new columns to the table shouldn't be too difficult. We could of course add a new table with the bindings too.

**Comment by rfk** [comment]
Would it be unreasonable for destroying a refresh token to destroy *all* access tokens for the associated `client_id`? That risks destroying tokens held by other instances of the same client, but they should be prepared to handle those tokens being invalidated anyway and just generate some new ones.

**Comment by shane-tomlinson** [comment]
> Would it be unreasonable for destroying a refresh token to destroy all access tokens for the associated client_id?

I'm not sure about this, it feels sloppy and like it pushes work onto RPs that we should be doing ourselves.

**Comment by shane-tomlinson** [comment]
> I'm not sure about this, it feels sloppy and like it pushes work onto RPs that we should be doing ourselves.

I misunderstood the suggestion, in hindsight this feels reasonable to me and might be the easiest thing we can do to address #3017. The alternatives involve DB migrations or pushing refresh->access token mappings into some persistent storage.

**Comment by shane-tomlinson** [comment]
We already have a query [to delete all access tokens for a given uid and client_id](https://github.com/mozilla/fxa/blob/b51e33e58bb63dacb62fa70f582975089d894ac5/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js#L258):

> const DELETE_ACTIVE_TOKENS_BY_CLIENT_AND_UID =
  'DELETE FROM tokens WHERE clientId=? AND userId=?';

We could slot that in to [deleteClientRefreshToken](https://github.com/mozilla/fxa/blob/b51e33e58bb63dacb62fa70f582975089d894ac5/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js#L604) method in the OAuth server's database and hopefully away we go.

@rfk, does that seem reasonable?

**Comment by rfk** [comment]
👍
