### ISSUE TITLE
Audit npm package: node-uap@https://github.com/mozilla-fxa/node-uap

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12498]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4863)

**Comment by clouserw** [comment]
This is a fork-of-a-fork-of-a-fork-of-an-unmaintained package.  We should look into replacing this with something else.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

https://mozilla-hub.atlassian.net/browse/FXA-1218 ( https://mozilla-hub.atlassian.net/browse/FXA-1218|smart-link ) suggests using ua-parser2 and this probably ends up being a dupe of that issue.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
