### ISSUE TITLE
Audit npm package: webcrypto-liner@https://github.com/mozilla-fxa/webcrypto-liner

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12504]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4867)

**Comment by clouserw** [comment]
I don't think there are any differences between this fork and upstream.  This was likely forked to hold it at a certain revision because we forked webcrypto-core.  If we fix #12502 we can probably remove this package for free.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I tried to upgrade at https://mozilla-hub.atlassian.net/browse/FXA-5282?focusedCommentId=555266 ( https://mozilla-hub.atlassian.net/browse/FXA-5282?focusedCommentId=555266|smart-link )

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It looks like we have an fxa branch which we are using with more commits in it: https://github.com/mozilla-fxa/webcrypto-liner/tree/fxa ( https://github.com/mozilla-fxa/webcrypto-liner/tree/fxa|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
