### ISSUE TITLE
Audit npm package: ua-parser-js@https://github.com/mozilla-fxa/ua-parser-js

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12501]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4864)

**Comment by clouserw** [comment]
I don't see any local patches for this and we're way behind the upstream.  Let's just try an upgrade: https://www.npmjs.com/package/ua-parser-js
