### ISSUE TITLE
Audit npm package: uap-core@https://github.com/ua-parser/uap-core

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12500]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4865)

**Comment by clouserw** [comment]
This is already pointing to the maintainer's repository.  Maybe this wasn't on NPM at the time?  It's there now: https://www.npmjs.com/package/uap-core

Although, I don't think we are using this package anywhere...?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
