### ISSUE TITLE
Audit npm package: webcrypto-core@https://github.com/mozilla-fxa/webcrypto-core

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12502]
This package references a github repo instead of NPM. Look into why this is case. If the package was forked, try to understand the reason and figure out if we can safely upgrade to the current NPM package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4866)

**Comment by clouserw** [comment]
Looks like this was forked to [add HDDF](https://github.com/mozilla-fxa/webcrypto-core/commit/8e0152a66d3ae6329cf080ccb3085eb06637070f)

The upstream library [added support for HKDF in 2019](https://github.com/PeculiarVentures/webcrypto/pull/7).  So, in theory we could upgrade, but we'd have to be careful about it.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
