### ISSUE TITLE
Set profile avatar of new FxA user via 3rd party auth

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12506]
The user’s profile image is returned as part of the oauth response but we currenty don’t do anything with it. Currently, the account uses our fallback image (first letter of email).

To do this, we will probably need to expose a new endpoint in profile server to accept a url or stream and then set properites in database.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4869)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Duplicated teh Google version of this ticket (fxa-4548) as another nice-to-have but I don’t think either of these tickets block launch.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

At a minimum this is display name an image.

**Comment by data-sync-user** [comment]
➤ Mill Soper commented:

Vesta Zare I think it might be useful to map out the user story here in more detail. The questions that came to mind for me were 1. Is a user’s avatar updated whenever they link a 3rd party account, or only when they are linking a 3rd party account and also creating a new Firefox account? 2. Should the user be prompted to opt-in/opt-out of having their 3rd party account information set as the default for their Firefox account? 3. If a user then changes their profile avatar in the 3rd party authenticator (say, their Google avatar) should we update it in FxA also? 4. Do we only update a field when there isn’t a value in that field already?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
