### ISSUE TITLE
Add language to be inclusive of users who have not yet set a password at login

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12516]
A user must provide an email address and password at login at most points of entry for a Firefox Accounts; however, with the addition of Google and Apple auth, and stub accounts created through the Subscription Platform, users may _not_ have set a password by time they attempt their next log in. While SubPlat stub accounts are sent an email which asks them to set a password (and sends them through the reset password flow), the Google and Apple Auth FxA users will never be asked to create a password unless attempting to log in to accounts for another purpose (such as Sync or another Accounts Relying Party).

In this case, these users who have not created a password would have no options that quite fit their needs - what we want them to do here is select “Forgot Password” which will place them in the reset password flow, allow them to set a password for the first time, and have the ability to sign in via email address and password, or via their preferred Google/Apple Auth provider if in a flow that allows that.

!Screen Shot 2022-04-15 at 2.19.07 PM.png|width=567,height=702!

How can we make this experience more friendly to users? Is a content change here enough, should we audit/request updates from our RPs? [~accountid:60482f83bfef95006bc8ad2d] looking forward to your thoughts here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4873)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23610">image-20220507-042315.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22917">Screen Shot 2022-04-15 at 2.19.07 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Shouldn’t they just be able to login via their Google/Apple Auth provider everytime? Do they need to set a password? Wondering why not direct them to a page like below every time they attempt to sign back in? 

!image-20220427-182507.png|width=480,height=466!

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

At least for now, users will only be able to sign in with google or apple via the pocket flow. All other relying parties would require a password for sign in.

Wil Clouser I’m curious, do we know what the lift would be to enable this for other RPs? I know certain RPs (Sync, for example) will always require a password for hashed IDs, but I’m curious if this is something we could poll the RPs to see if they would like us to enable and flip it on along with Pocket?

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Followed up with Wil and got more clarification on this use case and various scenarios. Will map out the flow and respond in the ticket.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

should be easy

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

I agree that we should look into enabling Google/Apple auth for other services, and in the meantime we can improve the user flow for these users. In this instance, would it make sense to create a new screen that behaves the following way?

So when a user attempts to log into their Fx account, we check to see if they previously logged in with google/apple but has never set a password. If that’s the case, then we take them to a page like below + add copy that indicates why they need to set a password (e.g. Set a password to unlock all the privacy benefits of a Firefox account and Sync your data)

!image-20220507-042315.png|width=374,height=501!

Let me know what you think.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Can you say more about the user gets to that screen?  They are trying to log in?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
