### ISSUE TITLE
Add support for U2F

### ISSUE THREAD

**Issue by TannerFilip** [mozilla/fxa#1251]
U2F is now enabled by default on Firefox (since 67), so it'd be nice if fxa supported it as well. There probably aren't a ton of people that'd use it though, unless there are a lot internal folks that have Yubikeys or similar. Since this seems to be the first request for it, I'm guessing there aren't.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-102)
┆Issue Number: FXA-102

**Comment by shane-tomlinson** [comment]
I thought we had a bug for this, but I don't see it anywhere.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this is being tracked at https://jira.mozilla.com/browse/FXA-2083
