### ISSUE TITLE
Investigate deprecated @types/assert package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12521]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### @types/assert
> See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
- packages/fxa-auth-client/package.json:    "@types/assert": "^1.5.4",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4879)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
