### ISSUE TITLE
Investigate deprecated @types/nock package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12529]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### @types/nock
> This is a stub types definition. nock provides its own type definitions, so you do not need this installed.
- packages/fxa-auth-server/package.json:    "@types/nock": "^11.1.0",
- packages/fxa-payments-server/package.json:    "@types/nock": "^11.1.0",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4887)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
