### ISSUE TITLE
Investigate deprecated @types/get-stream package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12524]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### @types/get-stream
> This is a stub types definition. get-stream provides its own type definitions, so you do not need this installed.
- packages/fxa-graphql-api/package.json:    "@types/get-stream": "3.0.2",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4881)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
