### ISSUE TITLE
Investigate deprecated leftpad package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12537]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### leftpad
> Use the built-in String.padStart function instead
- packages/fxa-auth-server/package.json:    "leftpad": "0.0.1",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4895)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
