### ISSUE TITLE
Investigate deprecated @types/storybook__addon-links package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12533]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### @types/storybook__addon-links
> Deprecated
- packages/fxa-payments-server/package.json:    "@types/storybook__addon-links": "^5.2.1",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4890)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
