### ISSUE TITLE
Investigate deprecated redux-devtools-extension package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12539]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### redux-devtools-extension
> Package moved to @redux-devtools/extension.
- packages/fxa-payments-server/package.json:    "redux-devtools-extension": "^2.13.9",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4893)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
