### ISSUE TITLE
Investigate deprecated @types/testing-library__react-hooks package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12535]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### @types/testing-library__react-hooks
> This is a stub types definition. @testing-library/react-hooks provides its own type definitions, so you do not need this installed.
- packages/fxa-settings/package.json:    "@types/testing-library__react-hooks": "^4",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4891)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
