### ISSUE TITLE
Investigate deprecated babel-eslint package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12536]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### babel-eslint
> babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
- packages/fxa-content-server/package.json:    "babel-eslint": "^10.1.0",
- packages/fxa-payments-server/package.json:    "babel-eslint": "^10.1.0",
- packages/fxa-react/package.json:    "babel-eslint": "^10.1.0",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4896)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
