### ISSUE TITLE
Investigate deprecated subscriptions-transport-ws package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12542]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### subscriptions-transport-ws
> The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
- packages/fxa-settings/package.json:    "subscriptions-transport-ws": "^0.11.0",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4898)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
