### ISSUE TITLE
Investigate deprecated superagent package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12543]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### superagent
> Deprecated due to bug in CI build https://github.com/visionmedia/superagent/pull/1677\#issuecomment-1081361876
- packages/fxa-auth-server/package.json:    "superagent": "^7.1.1",
- packages/fxa-graphql-api/package.json:    "superagent": "^7.1.1",
- packages/fxa-shared/package.json:    "superagent": "^7.1.1",
- packages/fxa-support-panel/package.json:    "superagent": "^7.1.1",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4899)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
