### ISSUE TITLE
Fill in API documentation for routes in Miscellaneous and Subscriptions sections in Auth Server API

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12549]
There are routes that were not listed in the previous Firefox Accounts Authentication Server API documentation that now have been autogenerated into the new API documentation using the Swagger plug-in - they could use details if applicable.

Routes that appeared to belong in the [Subscriptions section](https://mozilla.github.io/ecosystem-platform/api#tag/Subscriptions) have been moved to that section and the remaining routes are listed within the [Miscellaneous section](https://mozilla.github.io/ecosystem-platform/api#tag/Miscellaneous) in Ecosystem Platform.

Ben also suggested that it would be useful to make a `config/docs.json` to easily enable routes purely for doc purposes (Swagger cannot see routes that need IAP enabled).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4902)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
