### ISSUE TITLE
Investigate deprecated time-grunt package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12544]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### time-grunt
> Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
- packages/fxa-content-server/package.json:    "time-grunt": "2.0.0",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4900)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
