### ISSUE TITLE
Investigate deprecated request-promise package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12541]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### request-promise
> request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
- packages/fxa-content-server/package.json:    "request-promise": "4.2.6",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4897)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
