### ISSUE TITLE
Investigate deprecated request package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12540]
Ref: https://github.com/mozilla/fxa/issues/12477

I saw a rogue usage of the [**request**](http://npm.im/request) module in one of the package.json files so I built a thing which checks for deprecated things and found some things.

### request
> request has been deprecated, see https://github.com/request/request/issues/3142
- packages/123done/package.json:    "request": "^2.88.2"
- packages/browserid-verifier/package.json:    "request": "^2.88.2",
- packages/fxa-auth-server/package.json:    "request": "^2.88.2",
- packages/fxa-content-server/package.json:    "request": "^2.88.2",
- packages/fxa-customs-server/package.json:    "request": "^2.88.2",
- packages/fxa-geodb/package.json:    "request": "^2.88.2"
- packages/fxa-profile-server/package.json:    "request": "^2.88.2",

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4892)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
