### ISSUE TITLE
Upgrade css-loader dependency from 1.0.0 to at least 6.7.1

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12552]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12442](https://github.com/mozilla/fxa/pull/12442|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4904)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

We are using CSS loader 3.6+ in other packages, it’s just content-server that needs the significant 1.0 to 6.7.1 upgrade.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
