### ISSUE TITLE
Upgrade sinon dependency from 4.5.0 to 14+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12553]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12511](https://github.com/mozilla/fxa/pull/12511|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4905)

**Comment by LZoog** [comment]
Updated the title since v14 is now out. Failed dependabot PR for v14: https://github.com/mozilla/fxa/pull/12855

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
