### ISSUE TITLE
Verify the Pocket link is correct in the connected devices section

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12569]
When you connect your account to Pocket and look in the Connected Devices section of [accounts.firefox.com](http://accounts.firefox.com), it lists Pocket but:

1. The link is hardcoded to English
1. It links to [https://www.mozilla.org/en-US/firefox/pocket/](https://www.mozilla.org/en-US/firefox/pocket/|smart-link) - should it link to the product instead of the mozilla.org  page since they’ve already signed in to the product?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4912)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22979">image-20220419-180652.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

!image-20220419-180652.png|width=509,height=154!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
