### ISSUE TITLE
Security events in the admin panel are sorted the wrong way

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12580]
If I look up an account in the admin panel I see:

!image-20220419-215218.png|width=472,height=390!

But if I look at[ this page|https://accounts.firefox.com/security_events] for that account I see:

!image-20220419-215316.png|width=310,height=454!

It looks like the admin panel has a limit of 10 events as well as being sorted by ASC instead of DESC.  We should fix the sorting and make the limit, like, 200?  At some point we’ll need pagination, but I don’t think we’re there yet.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4921)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22992">image-20220419-215218.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22991">image-20220419-215316.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
