### ISSUE TITLE
Disallow deleting security events

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12581]
On [https://accounts.firefox.com/security_events](https://accounts.firefox.com/security_events) we have a “Delete events” button.  We should remove that button and all supporting code/tests.  I don’t think the option to delete these should be exposed to end users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4922)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
