### ISSUE TITLE
vendors~fxaClient failed

### ISSUE THREAD

**Issue by farhan787** [mozilla/fxa#1260]
While signing up with my android device over same wifi network on this 192.168.1.80:3030/signup, this below error is there for signup for a new account and signin for an existing account in my database.

![Screenshot_2019-05-25-18-34-55-160_org mozilla firefox](https://user-images.githubusercontent.com/38656082/58370088-1cc71180-7f20-11e9-8e7d-f454b445d883.png)

**Comment by shane-tomlinson** [comment]
We expect the local development content server to be run on 127.0.0.1:3030. If you want to run on an IP other than 127.0.0.1, you need to update [public_url in configuration](https://github.com/mozilla/fxa/blob/914ef06de8ee7930091c0f8ec09bb123e0e1626f/packages/fxa-content-server/server/lib/configuration.js#L456).

**Comment by farhan787** [comment]
@shane-tomlinson got it.
