### ISSUE TITLE
Update Firefox Accounts Authentication Server API documentation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12622]
* Update [https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md|smart-link) to include link to API documentation to Ecosystem Platform
* There is information in the Authentication Server API documentation that is out-of-date.
  * One example of outdated information is  “HAWK-authenticate with session token”, as [FxA deprecated HAWK](https://github.com/mozilla/fxa/blob/main/docs/adr/0022-deprecate-hawk.md) almost two years ago.

Note: We do inform readers of the API documentation that there may be out-of-date information.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4948)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
