### ISSUE TITLE
isLocalHost function in fxa-auth-server/lib/routes/oauth/authorization.js checks "localhost" twice

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12628]
Randomly spotted while looking at some other PR.

https://github.com/mozilla/fxa/blob/1f003a51c4d643f10f39216511b4687d81eb8348/packages/fxa-auth-server/lib/routes/oauth/authorization.js#L24-L27

Not sure why `return host === 'localhost' || host === 'localhost';` did we mean to check something other than "localhost" on the right hand side the second time?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4953)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
