### ISSUE TITLE
Add checkout-type metric for old flow.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12624]
From this commit [https://github.com/mozilla/fxa/commit/b9c210361c319ac94cda466e100d178426c0a640](https://github.com/mozilla/fxa/commit/b9c210361c319ac94cda466e100d178426c0a640|smart-link)  it seems that checkout-type metric is only getting tracked for the new passwordless flow. Lets also add it to the old flow.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4950)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
