### ISSUE TITLE
ecosystemAnonId cannot be set on an Account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12630]
Looks like this started in the latest push: [https://sentry.io/organizations/mozilla/issues/3211206243/?project=6231069&query=is%3Aunresolved+ecosystemanonid&statsPeriod=14d](https://sentry.io/organizations/mozilla/issues/3211206243/?project=6231069&query=is%3Aunresolved+ecosystemanonid&statsPeriod=14d)

I’m not sure if it is noticable by end users or not, so I’m going to mark this an S2 but we can bump it down if it’s not.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4954)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23218">Screen Shot 2022-04-27 at 10.17.30 AM.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23416">Screen Shot 2022-05-03 at 17.01.48.png</a>

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Downgrading from a three to a two pointer. The fix was pretty straight forward.

**Comment by ioanarusiczki** [comment]
@enjikaka as a workaround try to delete data/cookies and it should work again after. It worked for me. I also ran into this issue when I tried to login back to https://addons-dev.allizom.org/en-US/firefox/ 

![server error](https://user-images.githubusercontent.com/33448286/165531713-029ba534-505d-492a-aefa-68429cb6a931.png)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

After some discussion on Slack I don’t think this is the same issue.  We didn’t get any more helpful error messages but https://mozilla-hub.atlassian.net/browse/FXA-5024 ( https://mozilla-hub.atlassian.net/browse/FXA-5024|smart-link ) is a likely culprit

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

It seems that the issue in the comment below is not related to the error described in this ticket. Will put this back on Done.
