### ISSUE TITLE
[email/l10n] Email localized in Japanese should not have Korean translations (investigate CLDR lib)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12635]
It was reported that an email (postAddTwoStepAuthentication) that was expected to be localized in Japanese also had Korean in it. The email was accessed from Japan with Firefox Nightly build's UI language in English and acceptLanguage set to ja-JP, en-US, en.

The userInfo partial used in the email is in Korean in the postAddTwoStepAuthentication.

Bonus? - Knowing that emails default to English if there are missing translations, why does a partial appear in a different language in different emails (e.g, the partial is in Korean in postAddTwoStepAuthentication yet in English in postRemoveTwoStepAuthentication). Shouldn’t a partial appear in the same language in all emails?

[https://bugzilla.mozilla.org/show_bug.cgi?id=1766207](https://bugzilla.mozilla.org/show_bug.cgi?id=1766207|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4955)

**Comment by pdehaan** [comment]
Need to check if the translations exist in https://github.com/mozilla/fxa-content-server-l10n/tree/master/locale or https://pontoon.mozilla.org/projects/firefox-accounts/.
