### ISSUE TITLE
(future) storage strategy for oauth tokens

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1264]
We've discussed this in the past, but I can't find an issue, so filing this one.

Anyways, the oauth `tokens` would perhaps be better either (1) stored in something like Redis, or (2) signed in some way.

Currently they are stored in a mysql table and the IO write volume in maintaining a short expiry is not trivial.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-104)
┆Issue Number: FXA-104

**Comment by clouserw** [comment]
Activity occuring at https://github.com/mozilla/fxa/pull/3278 and https://github.com/mozilla/fxa/pull/3385

/cc @dannycoates

**Comment by clouserw** [comment]
Tokens are in redis, as of today.  They'll move again in the future, but no need to keep this issue open.
