### ISSUE TITLE
Different terms used for "Data Collection and Use" when Interlingua language is selected

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12653]
**Build:**

Stage

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The browser’s language is set to Interlingua.

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and log in using an existing account.
1. Go to Firefox account menu and observe the translation for Data Collection and Use.
1. Scroll to the bottom of the page and observe the translation for Data Collection and Use.

**Actual result:**

There are different terms used for Data Collection - “Recolta” vs “Collecta”.

**Expected result:**

The same term is used.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4960)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23178">interlingua translation 1.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23179">interlingua translation 2.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23396">new situation.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Peiying Mo what is your advice?

**Comment by peiying2** [comment]
Indeed, the term not translated consistently throughout: https://pontoon.mozilla.org/ia/firefox-accounts/all-resources/?search=Data+Collection&string=234349. Let me bring this to the contributor's attention.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

It seems that the issue is fixed now. The same term is used when Interlingua language is selected - “Recolta e uso de datos“.

!new situation.png|width=824,height=205!
