### ISSUE TITLE
[subplat] Add SUMO capabilities to every product

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12658]
Support needs to be able to tell what all subscriptions a user has. When RPs request a user’s subscriptions, we return a filtered list based on the configured product capabilities, so in order for [http://support.mozilla.org](http://support.mozilla.org|smart-link)  to know about all the subscriptions a user has, each product needs to have a `capabilities[${SUMO_clientId}]` key with a value of the Stripe `productId` . You can see this in the [VPN product’s metadata](https://dashboard.stripe.com/products/prod_FvnsFHIfezy3ZI) for example.

Rather than manually add this metadata in the Stripe dashboard for each product, we should automatically add this capability in our code. This means also updating the newer `ProductConfig`objects.

Ben suggested this could be an auth server config value where any clientId in the provided list will get notified about everything.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4964)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

+1.  But instead of having it added in the product config, can we simply merge it in in the capability service?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
