### ISSUE TITLE
Upgrade to Jest 28

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12668]
Jest 28 has a long list of breaking changes: [https://github.com/facebook/jest/releases/tag/v28.0.0](https://github.com/facebook/jest/releases/tag/v28.0.0|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4969)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

yarn why suggests this is used in a lot of FxA packages and in one case as a nested dep that’s two major versions behind. I’m going to estimate this as 3 points, but let me know if you disagree.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
