### ISSUE TITLE
Brands should be coded as placeables in main.ftl

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa#12669]
## Description

This source string contains brands that are not treated as placeables. It generated many errors in the l10n linter report:

`payment-confirm = I authorize Mozilla, maker of Firefox products, to charge my payment method <strong>${ $amount } per { $interval }</strong>, according to <termsOfServiceLink>Terms of Service</termsOfServiceLink> and <privacyNoticeLink>Privacy Notice</privacyNoticeLink>, until I cancel my subscription.`

Because of the error in the source string, these locales have the same issue: zh-TW, uk, sv-SE, sv, sq, pt-PT, pt, pl, nn-NO, kab, id, ia, gn, fy-NL, de, cy, 

### Steps to reproduce

(https://github.com/mozilla/fxa-content-server-l10n/blob/6d13a17cd5d626c920203aaf18b00848e8cb0af6/locale/templates/main.ftl#L156)

### Expected result

Treat `Mozilla` and `Firefox` as brands and coded according to Fluent guideline.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4970)

**Comment by peiying2** [comment]
@clouserw @LZoog

**Comment by LZoog** [comment]
cc @chenba, since this is coming from the Subplat FTL file. I'll mark it as SubPlat component so it'll be triaged accordingly, thanks @peiying2.

**Comment by LZoog** [comment]
Aw man, I think this is an issue in `settings.ftl` too, we probably need a separate issue for it: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/templates/settings.ftl

@peiying2 Can you think of why some placeables might not get copied over correctly? I was checking out #12558 which I know we were pinging about in Slack, but it looks like some of those placeables are just completely [missing from `es`](https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/es/settings.ftl) and I wonder if that's the case in other locales.

**Comment by peiying2** [comment]
> @peiying2 Can you think of why some placeables might not get copied over correctly? I was checking out #12558 which I know we were pinging about in Slack, but it looks like some of those placeables are just completely [missing from `es`](https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/es/settings.ftl) and I wonder if that's the case in other locales.

The completion of `es` is very low compared to other `es-*` flavors.  

I also noticed that some of the ## line items are empty in the templates: https://github.com/mozilla/fxa-content-server-l10n/blob/6d13a17cd5d626c920203aaf18b00848e8cb0af6/locale/templates/settings.ftl#L315. And you can spot quite a few of them in the file.

**Comment by peiying2** [comment]
> ➤ Bianca Danforth commented:
> 
> Can you share what the linter errors are?
> 
This is updated regularly https://github.com/mozilla-l10n/mozl10n-linter/actions/workflows/fxa.yaml.

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

For a more long term fix, how do we replicate these linter errors?

**Comment by flodolo** [comment]
This one fixed through https://github.com/mozilla/fxa/issues/12726

There's a linter running on localized files, which should catch most of the errors, You can see the badge in the README
https://github.com/mozilla/fxa-content-server-l10n

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
