### ISSUE TITLE
fxa-graphql-api: Update Subscription "created" type, consider changing name

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12675]
`created` cannot be `null`, but the [Subscription model](https://github.com/mozilla/fxa/blob/main/packages/fxa-graphql-api/src/gql/model/subscription.ts#L8) in `fxa-graphql-api` states it can be.

Additionally, Subscription is a [reserved word](https://dgraph.io/docs/graphql/schema/reserved/) in GQL. If we ever need to autogenerate TS types for this package like we do for the fxa-admin-server, naming this class `Subscription` will cause type generation issues. We could change this now to avoid issues later, in the admin-panel we named a similar class `moz-subscription`.

See [this comment](https://github.com/mozilla/fxa/pull/12637/files#r858859546) for more info.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4973)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
