### ISSUE TITLE
Paypal-Processor: Record last success run to automatically move grace period to handle missing runs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12674]
If the paypal processor does not run for a period of time, then when it runs again it needs its grace period pushed forward. This can be difficult to remember, and while a run-book can help reduce the odds we run it incorrectly, this would be more reliable if the code itself knew to push forward the grace period. To do this, the paypal-processor should record that it ran successfully (in our mysql db prolly), and when starting, query its last run period to see if its been recently enough that its grace period does not need to be increased.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4972)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
