### ISSUE TITLE
Update CONTRIBUTING.md 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12678]
Our CONTRIBUTING file is a little out of date.

* We should explain that contributors must PR from forks but a member of the FxA team will need to open a separate PR for CI to run properly (see [comment](https://github.com/mozilla/ecosystem-platform/pull/198#discussion_r850721433) / that section of ecosystem-platform docs)
* There’s at least one broken ecosystem-platform link
* I don’t think we have dev/testing “servers” any longer. + should we move the stage/prod link to the front page readme?
* We mention NPM and not yarn 
* Anything else you see when reading through it

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4974)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
