### ISSUE TITLE
Cannot use `@import` in admin-panel CSS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12671]
I’m not sure why - maybe it’s a Tailwind thing, or a postCSS thing - but we can’t seem to `@import` CSS files in the admin-panel, meaning any additional CSS we need is all going into the global `tailwind.css` file. See [this comment](https://github.com/mozilla/fxa/pull/12637/files#r858039304).

If it’s feasible to [upgrade admin-panel to Tailwind 3](https://mozilla-hub.atlassian.net/browse/FXA-4707), I think we should do that first, in case that resolves this problem for us for free.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4971)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
