### ISSUE TITLE
A couple suspicious import/export statements in fxa-auth-server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12687]
Well, this is interesting...
I would have almost expected ESLint to catch this, but...

```js
// .eslintrc.js
module.exports = {
  env: {
    node: true,
  },
  extends: ["eslint:recommended"],
  parserOptions: {
    ecmaVersion: "2020",
    sourceType: "module",
  },
};
```

```js
// index.js
import DESCRIPTION from '../docs/swagger/shared/descriptions';

const isA = require('@hapi/joi');
const validators = require('./routes/validators');
const error = require('./error');

if (error) {
  console.log(DESCRIPTION, isA, validators);
}
```

And this doesn't throw any errors w/ mix of `require()` and `import`.

But it WILL throw an error if I change the `parserOptions.sourceType` from "module" to "script" (default).

```sh
npx eslint index.js

/private/tmp/eslint-test/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 1 problem (1 error, 0 warnings)

The terminal process "/bin/zsh '-c', 'npm run lint'" terminated with exit code: 1.
```

Now, if I change the ./packages/fxa-auth-server/.eslintrc file to use `"sourceType": "script"` I get a couple suspicious parsing errors (since we're mixing `require()` with `import`/`export`):

```sh
yarn workspace fxa-auth-server run lint

/Volumes/Dev/github/mozilla/fxa/packages/fxa-auth-server/test/local/payments/util.js
  39:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/Volumes/Dev/github/mozilla/fxa/packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js
  4:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 2 problems (2 errors, 0 warnings)
```

https://github.com/mozilla/fxa/blob/feee364ad7e386f1b4c69bee64916cd9b7f02b86/packages/fxa-auth-server/test/local/payments/util.js#L39-L47

https://github.com/mozilla/fxa/blob/feee364ad7e386f1b4c69bee64916cd9b7f02b86/packages/fxa-auth-server/test/local/routes/subscriptions/mozilla.js#L4-L11

_Originally posted by @pdehaan in https://github.com/mozilla/fxa/issues/12685#issuecomment-1111563852_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4980)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
