### ISSUE TITLE
Encourage users to set a Recovery Key in Settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12682]
When we first started on the new Settings project, UX and Product expressed that they would like for there to eventually be a way to encourage users to set up important security features, like a recovery key, whether that be a green dot or some kind of visual border, or even some sort of icon with a tooltip to bring that section to the user’s attention if they don’t have a key set yet.

To help prevent users from getting locked out of their account or losing their sync data by resetting their password, it seems like this could be an easy way. If we don’t use a tooltip, we should consider some sort of explainer on why it’s important. I’m not sure “Restore your information when you forget your password.” is clear enough, given the number of issues we have around resetting passwords + sync data.

We may also want to at least mention the importance of creating a recovery key in the sign up flow, or when an account is verified.

Out of scope for this issue, but we could also potentially send users a new email a week or so after account creation encouraging them to set a recovery key, and _maybe_ send existing users without one an email as well, but that would be an additional 2-3 separate issues. Edit: We could also instead, _possibly_ create a recovery key at account creation time, but I’m currently unsure of implications for doing that could be, and that’d definitely warrant additional tasks.

Read more: [https://support.mozilla.org/en-US/kb/reset-your-firefox-account-password-recovery-keys](https://support.mozilla.org/en-US/kb/reset-your-firefox-account-password-recovery-keys|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4979)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
