### ISSUE TITLE
Send altered version of `lowRecoveryCodes` email when user consumed the last one

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12681]
We should be _strongly encouraging_ users to regenerate their recovery codes when they’ve reached 0. Instead, we send the same email as having 1-2 left. I think we should replace the word “Low” with “Zero” and use some phrasing to inform the user if they don’t do this, they will be unable to log into their account if they lose their 2FA authentication device.

Be sure to add the new state to Storybook.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4978)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23231">image-20220427-175947.png</a>

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Do we have data on how frequently the low recovery code emails are triggered?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
