### ISSUE TITLE
Connected Services page shows the incorrect OS version

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12698]
## Description

https://accounts.stage.mozaws.net/settings#connected-services displays my wrong macOS version.

### Steps to reproduce

1. Logged in to Stage FxA
2. Went to https://accounts.stage.mozaws.net/settings#connected-services
3. I noticed that it displays my OS version as "macOS 10.15" (Firefox) and "macOS 10.15.7" (Chrome), even though I'm on macOS 12.2. (where 10.15.x seems to have been macOS Catalina)

### Expected result

Report my macOS as 12.2.

### Actual result

macOS version is reported as 10.15 or 10.15.7.

### Environment

macOS 12.2 (Firefox Nightly and Chrome Stable)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4989)

**Comment by pdehaan** [comment]
![Screen Shot 2022-04-28 at 10 45 57 AM](https://user-images.githubusercontent.com/557895/165830240-8f854cfc-e7ba-4114-afe8-ba1b085e4eaf.png)

Oh interesting. Maybe this is just a generic default user agent string problem. Meh.
https://whatismyip.live/user-agent-information reports my UA as:
- Nightly: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0`
- Chrome: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

Even though I'm an a non-Intel macOS 12.2 laptop. The Internet is a wild place, but presumably this is to reduce their ability to track me via user agent through space and time.

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

This seems like an issue with the user agent string. There isn't anything we can do to correct this value on behalf of the client.
