### ISSUE TITLE
[l10n] “Create a Firefox account” section has UI issues when displayed in ES language 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12691]
**FxA version:**

* 1.231.3;

**Affected Browsers:**

* Chrome;
* Edge;

**Prerequisites:**

* Have the browser language set to ES;
* Have VPN set to Spain;
* Be in “Set up your subscription” page;

**Steps to reproduce:**

1. Observe the “Create a Firefox account” title;

**Expected result:**

* The “Crear una cuenta de Firefox” strings are correctly displayed, with no UI issues;

**Actual result:**

* The “Crea una cuenta de ⁨{-brand-name-firefox}⁩” strings are displayed instead of “Crear una cuenta de Firefox”;

**Notes:**

* This is also reproducible for the  “Me gustaría recibir actualizaciones de productos de ⁨Firefox” checkbox;
* See the attached screenshot;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4983)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23663">image-20220510-145100.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23262">Screenshot 2022-04-28 140753.png</a>

**Comment by data-sync-user** [comment]
➤ Hermina Condei commented:

Wil Clouser Do you think you could look into this? Seems like an FxA issue to me. Anna Sobiepanek FYI

**Comment by data-sync-user** [comment]
➤ Hermina Condei commented:

Florian Dieminger

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It looks like this is the same problem as https://mozilla-hub.atlassian.net/browse/FXA-4970 ( https://mozilla-hub.atlassian.net/browse/FXA-4970|smart-link ).  It affects more languages than just es also.

https://github.com/mozilla/fxa/blob/be04f844099684fb435201fc0c68c3d9be693db2/packages/fxa-payments-server/src/routes/Checkout/index.tsx#L344 ( https://github.com/mozilla/fxa/blob/be04f844099684fb435201fc0c68c3d9be693db2/packages/fxa-payments-server/src/routes/Checkout/index.tsx#L344|smart-link ) 

https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/es/main.ftl#L130 ( https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/es/main.ftl#L130|smart-link )

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Lisa Chan  do we have a fix for this?

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Anna Sobiepanek I don’t believe we have a fix for this yet, but this sounds like it could be related to this ticket as well - https://mozilla-hub.atlassian.net/browse/FXA-4906 ( https://mozilla-hub.atlassian.net/browse/FXA-4906|smart-link )

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

We should verify if this is browser specific or occuring in FF as well.

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

I had a quick look at this yesterday, and I was able to replicate this in Firefox and Brave.

I did also notice that on Pontoon language es is only 40% translated, where as the country specific one’s are all translated 100%.

The reason this started showing up is that a es translation, which included a brand placeable, was recently included in the localization files, however no translation was available for the placeable. Once a translation is provided for the placeable, this issue should be resolved.

!image-20220510-145100.png|width=1017,height=400!

**Comment by LZoog** [comment]
See [this comment](https://github.com/mozilla/fxa/issues/12558#issuecomment-1112412326). We can easily fix this by what Reino explained above, but I did have a question on if that's a bandaid fix.

**Comment by flodolo** [comment]
The specific issue for es should be fixed by https://github.com/mozilla/fxa-content-server-l10n/pull/597

**Comment by data-sync-user** [comment]
➤ Maria Berlinger commented:

Hello,

This is verified as fixed in Train 1.234.0. There are no UI issues displayed in ES language. See the attached screenshot.

!image-20220609-070828.png|width=846,height=807!
