### ISSUE TITLE
Most options on the "Site navigation menu" have no response

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12695]
[https://bugzilla.mozilla.org/show_bug.cgi?id=1765547](https://bugzilla.mozilla.org/show_bug.cgi?id=1765547|smart-link) 

Reproduced on production. A couple notes during explorarty testing:

* The window size must be smaller than 1010px wide for hamburger menu to be displayed, which seems to be the crux of the issue. When screen width is greater than 1010px the menu is hidden thereby making the bug non-reproducible. 
* I am not sure why the menu is hidden. Is this intentional, if so what’s the history here.
* Finally, as noted in ticket, the back arrow icon (left of profile picture text) is non functional in this case, so perhaps that should be hidden as well?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4986)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
