### ISSUE TITLE
[fxa-event-broker] Relying Party proxy from Pub/Sub

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1269]
- Add an API endpoint that GCP Pub/Sub will hit using HTTPS
- Verify Pub/Sub JWT signature
- Sign new message with FxA JWT and send to RP (webhook URL will be on the message)

**Comment by shane-tomlinson** [comment]
[@bbangert's question in #1288](https://github.com/mozilla/fxa/issues/1288#issuecomment-496985783):
> That does bring up the question you cited though, do we have a JWT signing system in FxA?

Yup, see https://github.com/mozilla/fxa/blob/9ca5c4057cde5da1e2866cb9515e88bb18e5fb2b/packages/fxa-auth-server/fxa-oauth-server/lib/grant.js#L170.
