### ISSUE TITLE
Copy changes to reset password screen to adequately inform users

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12699]
The goal is to communicate more sternly that resetting the password on your FF account removes all user data.   This is the page in question: [https://accounts.firefox.com/reset_password](https://accounts.firefox.com/reset_password).

Please refer to this document for specific Ask and desired copy changes: [https://docs.google.com/document/d/1-xT-ax9JoCz7tBhLXO1gV4qG4Qj35YVouChypObve2U/edit#heading=h.5xtqllmbstbb](https://docs.google.com/document/d/1-xT-ax9JoCz7tBhLXO1gV4qG4Qj35YVouChypObve2U/edit#heading=h.5xtqllmbstbb|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4990)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
