### ISSUE TITLE
Update Localization page of ecosystem-platform docs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12694]
We added some l10n docs within our new emails docs with [https://mozilla-hub.atlassian.net/browse/FXA-4124](https://mozilla-hub.atlassian.net/browse/FXA-4124|smart-link)  #10758. However, the Localization page is still a bit out of date. We can probably copy (or move) some docs from emails over, and add some additional info on that page with a little more info on the Pontoon page, Fluent project docs and things to know, how we concat all our FTL files per package, Gettext to Fluent migration gotchas/mention that the content-server is the only package still using gettext, and communication with the l10n team.

This strongly relates to [https://mozilla-hub.atlassian.net/browse/FXA-2914](https://mozilla-hub.atlassian.net/browse/FXA-2914|smart-link) / #9089 and could be done around the same time as a collab task.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4985)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
