### ISSUE TITLE
Investigate low key-fetch completion rate

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#127]
Here's an interesting stat I pulled out of the auth-server kibana dashboards: for every 100 creations or logins that request a keyfetch token, there are only 79 requests to actually fetch the keys:

![screen shot 2016-03-07 at 16 01 34](https://cloud.githubusercontent.com/assets/34695/13561251/dd5a5eec-e47e-11e5-881f-b5048ad9c884.png)

For reference, the two queries compared here are:

* `status:200 AND (request:"POST /v1/account/create?keys=true" OR request:"POST /v1/account/login?keys=true")`
* `status:200 AND request:"GET /v1/account/keys"`

Does this indicate that a full 20% of sync signin attempts fail to actually get the device connected?  That's a scary thought, so I'm filing this bug to track further investigation of the topic.

**Comment by rfk** [comment]
@shane-tomlinson can you confirm that the content-server will only pass `key=true` if it knows the relier will actually attempt to fetch and use the keys?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson can you confirm that the content-server will only pass key=true if it knows the relier will actually attempt to fetch and use the keys?

Yes. Sync by default [wants keys](https://github.com/mozilla/fxa-content-server/blob/90289d85a66b11de9955b63689bef81b8b063f4b/app/scripts/models/reliers/sync.js#L63), OAuth reliers can specify they want keys with the [`keys=true` query parameter](https://github.com/mozilla/fxa-content-server/blob/90289d85a66b11de9955b63689bef81b8b063f4b/app/scripts/models/reliers/oauth.js#L123).

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this as you see appropriate?

**Comment by rfk** [comment]
On reflection, I wonder if these are mostly accounts that never verify.  Will take another look in kibana.

**Comment by rfk** [comment]
Comparing these two queries:
* `status:200 AND (request:"POST /v1/account/create")`
* `status:200 AND request:"POST /v1/recovery_email/verify_code"`

Shows a precisely 50/50 split, which suggests that almost all accounts are eventually verified.  I'm not quite sure I believe that given our overall percentage of unverified accounts remains at 20%, but the ratio seems pretty stable over different time periods.

**Comment by rfk** [comment]
Our kibana logs go back to early January.  Here's the breakdown week by week:

* Jan 10 - 17, 53% login/create to 47% keyfetch
* Jan 17 - 24, 54% login/create to 46% keyfetch
* Jan 24 - 31, 55% login/create to 45% keyfetch
* Jan 31 - Feb 7, 56% login/create to 44% keyfetch
* Feb 7 - 14, 56% login/create to 44% keyfetch
* Feb 14 - 21, 56% login/create to 44% keyfetch
* Feb 28 - Mar 6, 56% login/create to 44% keyfetch

Firefox 44 went to release on January 26; I'll keep on eye on this as 45 rolls out just in case there's some regression making its way through the trains...

**Comment by rfk** [comment]
FWIW this seems to be holding steady at 56% to 44%, which is not great, but at least is not declining further.

**Comment by rfk** [comment]
It's still holding steady; I'm putting this back in the backlog for now, we can dig it out again for further investigation if we notice any trouble

**Comment by rfk** [comment]
The ratio as of today is 55% to 45%, which seems stable, so I'm going to close this out
