### ISSUE TITLE
Subscription renewal date uses Month-Day-Year format for EU users

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12701]
Following the deployment of [https://mozilla-hub.atlassian.net/browse/FXA-3166](https://mozilla-hub.atlassian.net/browse/FXA-3166|smart-link) the Support Team observed an increase in EU post-30 day cancellations (+20 tickets in 1 week). EU users were confused that they were being reminded for the renewal sooner than they expected as the renewal date in FXA does not display in day-month-year format.

!image-20220428-210458.png|width=771,height=427!

(Re attached screenshot) As an EU user, It’s unclear if the renewal date is December 9th, 2022 or September 12th, 2022.

**Possible Solution**

If we stick to using numerical dates in the app we can use [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString|smart-link)  

```javascript
const date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));

// formats below assume the local time zone of the locale;
// America/Los_Angeles for the US

// US English uses month-day-year order
console.log(date.toLocaleDateString('en-US'));
// → "12/20/2012"

// British English uses day-month-year order
console.log(date.toLocaleDateString('en-GB'));
// → "20/12/2012"

// Korean uses year-month-day order
console.log(date.toLocaleDateString('ko-KR'));
// → "2012. 12. 20."
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4991)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23295">image-20220428-210458.png</a>

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Both the website and email should include the localized appropriate format for the user.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per Anna, we have to do it everywhere but we also need to choose a library that will  mutate that for us. See related issues.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
