### ISSUE TITLE
[subplat][product config] Disable form submission for inactive plans

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12708]
Our Firestore based product configurations have an “active” property.  When it is false, disable the form elements on the check out pages.  This would be useful for product manager to “preview” their plans.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4999)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
