### ISSUE TITLE
[subplat][product configs] Do Not Allow Subscriptions on Inactive Plans

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12707]
The configuration documents in Firestore has an “active” property, when it is false, do not allow a subscription to be created for the plan via any of the subscription creation endpoints on the auth server.

This is a Jira for the work to be completed on the server side.  There’s another Jira for the front end.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4998)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
