### ISSUE TITLE
[sentry] Update non-error event that is being captured as an error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12725]
Found on Sentry - update so this is not captured as an actual error.

```
TypeError https://accounts.firefox.com/settings
NetworkError when attempting to fetch resource.
```

[https://sentry.io/organizations/mozilla/issues/3211230240/events/048905befa854163a1ed98cc39338b4e/?project=6231069](https://sentry.io/organizations/mozilla/issues/3211230240/events/048905befa854163a1ed98cc39338b4e/?project=6231069)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5014)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
