### ISSUE TITLE
Missing markup in payment-confirm string

### ISSUE THREAD

**Issue by flodolo** [mozilla/fxa#12726]
CC @LZoog @clouserw 

I've started running linters on some of our projects, and there's one issue that should be fixed in code.

https://github.com/mozilla/fxa-content-server-l10n/pull/427

This pull request changed `payment-confirm` without a new ID, adding markup.

```
-payment-confirm = I authorize Mozilla, maker of Firefox products, to charge my payment method <strong>${ $amount } per { $interval }</strong>, according to payment terms, until I cancel my subscription.
+payment-confirm = I authorize Mozilla, maker of Firefox products, to charge my payment method <strong>${ $amount } per { $interval }</strong>, according to <termsOfServiceLink>Terms of Service</termsOfServiceLink> and <privacyNoticeLink>Privacy Notice</privacyNoticeLink>, until I cancel my subscription.
```

As a consequence, we have 20+ locales with the wrong translation. That string should be update, using a new ID, so that we can force retranslation.

P.S. can someone from your team keep an eye out for dependabot pull requests?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5015)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23821">Screen Shot 2022-05-13 at 2.46.31 PM.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23822">Screen Shot 2022-05-13 at 2.46.46 PM.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23820">Screen Shot 2022-05-13 at 2.47.12 PM.png</a>

**Comment by flodolo** [comment]
The original string was introduced here
https://github.com/mozilla/fxa/commit/33e59c64d422aa27e84140ee15251623d7709de5

I can't spot anything in the code that uses that, even in that changeset?

Also, why is a function returning [hardcoded English text](https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/lib/formats.ts#L167)?

**Comment by pdehaan** [comment]
@flodolo I think it's used here: https://github.com/mozilla/fxa/blob/9eeee25ca2a92bd6f59a9cbdd26bd7f403456eb1/packages/fxa-payments-server/src/components/PaymentConsentCheckbox/index.tsx#L41-L48

**Comment by flodolo** [comment]
> @flodolo I think it's used here:

As far as I can tell, I only see the variants with time used there, not the generic one.

**Comment by clouserw** [comment]
@annasob can help with questions
