### ISSUE TITLE
"minify" option is deprecated in mjml-core and only available in mjml cli

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12737]
Noticed that this is now being logged in auth-server. We should find out what the alternatives are.

Ref https://app.circleci.com/pipelines/github/mozilla/fxa/29883/workflows/99b443ba-f38c-4e7d-a6cf-8b1af4616c20/jobs/329867

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5022)

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Dupe of https://mozilla-hub.atlassian.net/browse/FXA-4596 ( https://mozilla-hub.atlassian.net/browse/FXA-4596|smart-link ) - thanks for filing!

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Duplicate of FXA-4596 - thanks for filing!
