### ISSUE TITLE
Testing local storage results in sentry.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12733]
When testing local storage, we should handle any potential exceptions that occur gracefully. This method is clearly designed to validate if localstorage is enabled and working. Upon determining that local storage is disabled, we should fail gracefully, and we shouldn’t be reporting this failure to sentry.

`https://sentry.io/organizations/mozilla/issues/3211348673/?environment=prod&query=is%3Aunresolved&sort=freq&statsPeriod=24h`

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5019)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
