### ISSUE TITLE
Implement reactivation of cancelled subscription before end of current term

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1273]
Follow up to Issue #981 - we need a button to reactivate a cancelled subscription that has not yet ended:

<img width="315" alt="Capture" src="https://user-images.githubusercontent.com/21687/57025610-9f043480-6c05-11e9-9830-16072e0dd5b7.PNG">

Blocked by this issue in subhub: https://github.com/mozilla/subhub/issues/68

**Comment by lmorchard** [comment]
Bumping up the estimate on this. It's going to require adding a reactivation API resource to fxa-auth-server for use in fxa-payments-server. There may also be subhub blocking issues involved in cancel / reactivate:

https://github.com/mozilla/subhub/issues/95

**Comment by philbooth** [comment]
[Subhub reactivation API](https://github.com/mozilla/subhub/blob/a675893ea607f08d106b468614c5c44257c70e2d/subhub/subhub_api.yaml#L194-L226):

```yaml
  /customer/{uid}/subscriptions/{sub_id}:
    post:
      operationId: subhub.api.payments.reactivate_subscription
      tags:
        - Subscriptions
      summary: Reactivate a Subscription
      description: Reactivate a subscription that's been cancelled but hasn't yet ended.
      security:
        - PayApiKey: []
      produces:
        - application/json
      responses:
        '200':
          description: Subscription already active
          schema:
            type: object
            properties:
              message:
                type: string
        '201':
          description: Subscription reactivation successful
          schema:
            type: object
            properties:
              message:
                type: string
        '404':
          description: Subscription or User could not be found
          schema:
            $ref: '#/definitions/Errormessage'
      parameters:
        - $ref: '#/parameters/uidParam'
        - $ref: '#/parameters/subIdParam'
```
