### ISSUE TITLE
Gracefully handle 'A different user is signed in' errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12734]
This error seems to be an intentional error state and should there for be handled gracefully and not reported to sentry.

[https://sentry.io/organizations/mozilla/issues/3211224374/?environment=prod&query=is%3Aunresolved&sort=freq&statsPeriod=14d](https://sentry.io/organizations/mozilla/issues/3211224374/?environment=prod&query=is%3Aunresolved&sort=freq&statsPeriod=14d)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5021)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
