### ISSUE TITLE
Invalid value being posted to /metrics for duration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12732]
There appears to be an issue with the payload that some users are posting to the metrics endpoint. This could be problematic because the error rate is high enough that it could be impacting the metrics.

[https://sentry.io/organizations/mozilla/issues/3192605968/?environment=prod&project=6231069&query=is%3Aunresolved](https://sentry.io/organizations/mozilla/issues/3192605968/?environment=prod&project=6231069&query=is%3Aunresolved)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5018)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
