### ISSUE TITLE
Typo in admin panel: Unkown

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12746]
I feel like we already had this issue filed but I couldn’t find it.  Anyway, there are some typos in the admin panel - search for “Unkown”.

!image-20220503-165703.png|width=624,height=395!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5029)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23424">image-20220503-165703.png</a>

**Comment by pdehaan** [comment]
I think this was addressed in https://github.com/mozilla/fxa/pull/12279
