### ISSUE TITLE
invalid errno reported to sentry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12742]
I’ve only seen this in stage but it might be elsewhere too.  On this report: [https://sentry.io/organizations/mozilla/issues/3191901815/?environment=stage&query=is%3Aunresolved](https://sentry.io/organizations/mozilla/issues/3191901815/?environment=stage&query=is%3Aunresolved) you can see the errno reported was invalid.  Unfortunately, it doesn’t say what it was :confused: 

!image-20220503-151439.png|width=940,height=931!

For an aborted operation we don’t have an errno I think, so, maybe we just leave the field out?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5025)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23418">image-20220503-151439.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
