### ISSUE TITLE
[FxA-Settings] [l10n] Text on button not fully visible when in Saving mode

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12740]
**Build:**

Stage [Train 231.4]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The browser’s language is set to Estonian/ Finnish/ German/ Greek/ Guarani/ Interlingua/ Italian/ Polish/ Russian/ Slovenian/ Turkish/ Ukrainian/ Spanish etc.

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and log in using an existing account.
1. Go to Profile picture section and click “Add/ Change“.
1. Add a photo and click “Save”.
1. Observe the “Save” button when in Saving mode.

**Actual result:**

The text on the button is not fully visible.

**Expected result:**

The text on the button is fully visible.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5023)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23398">estonian - saving text not fully visible.gif</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23400">german - save button.gif</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23401">greek - text not visible on button.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23399">turkish - save button.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
