### ISSUE TITLE
[subplat][Apple IAP] Enable Apple IAP on stage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12758]
Once [https://mozilla-hub.atlassian.net/browse/FXA-3968](https://mozilla-hub.atlassian.net/browse/FXA-3968|smart-link) merges, which adds a feature flag for the Apple IAP integration, we need to set `SUBSCRIPTIONS_APP_STORE_API_ENABLED` default `false` in all environments but `true` in stage.

Steps:

* Open a CloudOps PR for SRE
* Update the deploy doc for the desired train
* Link the PR in this ticket and assign this ticket to the SRE to review and merge the PR.

This ticket blocks QA testing in stage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5034)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

I opened a cloudops PR ( https://github.com/mozilla-services/cloudops-deployment/pull/4615 ) and updated the deploy doc for Train 232.

Consequently, I’m reassigning this ticket to Dustin Lactin and moving myself to Collaborator.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Benjamin Bangert:

I was testing the Apple IAP registration endpoint ( https://github.com/mozilla/fxa/blob/d84af5eee500ca68d1f39dbf150216826046d9be/packages/fxa-auth-server/lib/routes/subscriptions/apple.ts#L133 ) in stage yesterday to answer a question ( https://mozilla.slack.com/archives/C038CH2JBPU/p1659991417806279 ) from the VPN team, and I hit an error ( https://github.com/mozilla/fxa/blob/d84af5eee500ca68d1f39dbf150216826046d9be/packages/fxa-auth-server/lib/payments/iap/iap-config.ts#L82 ) in IAPConfig.getBundleId. I noticed that we need to add the bundleId property to the guardian-vpn document in the fxa-auth-${stage|prod}-iap-config collection.

How is this collection populated? I don’t see it happening anywhere in the source code, though the data largely overlaps with what’s returned by our oauth/subscriptions/iap/plans/${appName} endpoint. Should I add this property manually from the GCP console?

For reference, the bundleId value is found in App Store Connect ( https://appstoreconnect.apple.com/ ).

**Comment by jbuck** [comment]
Populated by https://github.com/mozilla-services/cloudops-infra/blob/master/projects/fxa/tf/nonprod/envs/stage/resources/google_play_iap_transformed.json and https://github.com/mozilla-services/cloudops-infra/blob/master/projects/fxa/tf/prod/envs/prod/resources/google_play_iap_transformed.json

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Ah thanks Jon Buckley ! This is an example of where we update Firestore documents with Terraform. I will open a cloudops PR to update these two files with this new property.

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

I’ve applied this change in stage, if everything looks good I’ll apply it in prod and then merge it

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Yes everything looks good in Stage; thank you!

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Applied in prod, merged
