### ISSUE TITLE
Unhandled excpetion on email bouncing coming off PayPalNotificationHandler.handleMpCancel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12751]
A promise is not awaited properly and results in an unhandled application error. 

[https://sentry.io/organizations/mozilla/issues/3246748051/events/1d9ce5f0b67c4179968df7c2b9208618/?project=6231056](https://sentry.io/organizations/mozilla/issues/3246748051/events/1d9ce5f0b67c4179968df7c2b9208618/?project=6231056)

I do wonder if this is something a linter or other static analysis could catch for us?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5032)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
