### ISSUE TITLE
Follow up refactor of StripeHelper with some clean up

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12764]
The initial refactor of StripeHelper to better support the admin panel was done in such a way as to minimize the number of changes to the code base. Once that code has landed and has settled, we should take another pass to clean this up. Clean up items are:

1. Remove empty pass through modules and update imports in fxa-auth-server accordingly. For example, [this module’s](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/payments/iap/apple-app-store/subscription-purchase.ts) only purpose was limit the number of import statements that needed to be changed during the refactor.
1. Move any applicable tests to fxa-shared. Since the udnerlying class structure in fxa-auth-server was left unchanged by the refactor, the tests were more or less left unchanged as well. Some of the tests cases, which only rely on methods that have now been moved to base classes, could be ported over to fxa-shared as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5037)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
