### ISSUE TITLE
Migrate existing Pocket Apple Auth users to FxA Apple Auth

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12763]
To support the Pocket user migration we will need to migrate all current Pocket Apple user identifiers over to FxA Apple account.

From [https://docs.google.com/document/d/19z_9n73UeWnaZBzOUoapWgx8KlXZrlhd_qEL7o1DZuM/edit](https://docs.google.com/document/d/19z_9n73UeWnaZBzOUoapWgx8KlXZrlhd_qEL7o1DZuM/edit|smart-link) 

{quote}The following information was shared by Nicole Zeltzer, as informed by Pocket’s Apple Rep: 

_Users will still be able to use Sign-in with Apple, however the user identifier after transferred to the new team will be different from the old team. In order to associate same users, the old team should generate user’s transfer identifier for the new team (can generate early before the transfer) and after transfer new team can convert the transfer Identifier to the new team’s user identifier._

Further information can be found in Apple developer documentation: (1) [+Transferring Your Apps and Users to Another Team+](https://developer.apple.com/documentation/sign_in_with_apple/transferring_your_apps_and_users_to_another_team), (2) [+Bringing New Apps and Users into Your Team+](https://developer.apple.com/documentation/sign_in_with_apple/bringing_new_apps_and_users_into_your_team){quote}

On the FxA side of things, we will need to create a script to perform the user transfer as outlined in the Apple documentation.

Once those users have been transferred, we can enable allowing Pocket users to initiate the Apple authentication from Pocket homepage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5036)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

We had a discussion with Pocket and don’t have a set timeline to migrate the exisiting users yet. Moving out of the current train.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
