### ISSUE TITLE
Available language translations strings differ between stage/production and localhost

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12769]
When testing locally, en-US language translation strings can be resolved even though this file is never actually deployed. This can lead to slightly different behaviour during local development and result in issues like [https://mozilla-hub.atlassian.net/browse/FXA-4772](https://mozilla-hub.atlassian.net/browse/FXA-4772|smart-link) being overlooked.

We should make sure that the locally the set of languages available for translation matches what is deployed to stage/production.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5041)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23515">1THnRAHAvMaxiapieLYQNwgV5fP9xoHsZgRGSp_5f6VC6fJQYKO47jOzj0V9ZMVVcYZz1VjvheJf9kRsUituJeAI4N2SuBP-V0NBEG3mu46C4MxaOVraeip6QugpsnfCv1X4WqV8vt-9Fde7Hw</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
