### ISSUE TITLE
Update copy on unblock screen to reflect that the user has been rate limited

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#12775]
The unblock code screen (used for rate limiting) and our signin code screen (used to allow a login) are very similar but serve different purposes. We should make these screens different and better call out the intended purpose.

Unblock screen
<img width="517" alt="Screen Shot 2022-05-05 at 12 14 35 PM" src="https://user-images.githubusercontent.com/1295288/166967250-0545a19c-44c1-4b7b-b424-a4bcfe456fb7.png">

Instead of `Authorize this sign-in` we could say `Too many sign-in attempts, please verify your email`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5044)

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

How many failed attempts is required to trigger this?

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Vesta Zare  i have a Jira https://mozilla-hub.atlassian.net/browse/FXA-4956 ( https://mozilla-hub.atlassian.net/browse/FXA-4956|smart-link )  that requests more documentation around this rate limiting behaviour.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
