### ISSUE TITLE
Duplicate Fluent string payment-details

### ISSUE THREAD

**Issue by flodolo** [mozilla/fxa#12773]
`payment-details` is defined in two files:
* packages/fxa-auth-server/lib/senders/emails/partials/paymentPlanDetails/en.ftl
* packages/fxa-auth-server/lib/senders/emails/templates/subscriptionAccountFinishSetup/en.ftl

Luckily they have the same text, but we shouldn't have two definitions, given the files are later concatenated into one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5042)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Lisa Chan Looks like this bug was done as part of the email migration
