### ISSUE TITLE
Need a new string ID for new string

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12787]
A one line fix from [https://github.com/mozilla/fxa/pull/12731#discussion_r866477722](https://github.com/mozilla/fxa/pull/12731#discussion_r866477722|smart-link) .  Filing this so we can get it in this sprint so it doesn’t mix up L10n when we extract.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5049)

**Comment by data-sync-user** [comment]
➤ Mill Soper commented:

Moving this back to In Progress since this was pulled out of the train.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
