### ISSUE TITLE
Russian date formatt observed in email for user with only German locales

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12806]
This was reported in Matrix on May, 5th. [https://app.element.io/#/room/#fxa:mozilla.org](https://app.element.io/#/room/#fxa:mozilla.org|smart-link) . The user indicates they are seeing a Russian formatted date in their email, and provided this screen shot:

!image-20220509-165907.png|width=834,height=328!

!image-20220509-165821.png|width=540,height=576!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5053)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23629">image-20220509-165821.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23630">image-20220509-165907.png</a>

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Anna Sobiepanek Vaguely reminds me of  https://mozilla-hub.atlassian.net/browse/FXA-4754 ( https://mozilla-hub.atlassian.net/browse/FXA-4754|smart-link ) aka GitHub #12238. But yeah, definitely curious why only that ONE translation/date format is inconsistent.

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Lauren Zugai  looks like we have another occurrence of language mismatch.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
