### ISSUE TITLE
[payments] Add feature flagging to payment frontend

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1281]
In #1275 we set feature flag data, but it isn't read from anywhere. We should read it, and set it. #1280 will cover reading it in the browser.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-106)
┆Issue Number: FXA-106

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Not on the roadmap
