### ISSUE TITLE
Refactor Settings from using reach/router to react-router v6

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12847]
Settings is the only package that uses `reach/router`. We chose Reach originally because it was a smaller, simpler, and supposedly faster version of react-router, but as of react-router v6, `reach/router` has merged with `react-router`.

See [https://reach.tech/router/](https://reach.tech/router/|smart-link) :

{quote}Reach Router and it’s sibling project React Router are merging as React Router v6. In other words, Reach Router v2 and React Router v6 are the same. There is more information [on the maintainers website](https://reacttraining.com/blog/reach-react-router-future/).{quote}

And [https://reactrouter.com/](https://reactrouter.com/|smart-link) :

{quote}Closing in on a decade of client-side routing, React Router v6 takes the best features from previous versions—and its sister project, Reach Router—in our smallest and most powerful package yet.{quote}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5071)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
