### ISSUE TITLE
Settings Storybook: some styles differ from actuality + Fluent IDs are showing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12848]
In Settings Storybook, some elements like “Firefox Accounts” in the header as well as headings on the page, and external links, don’t seem to be rendering identically as far as margin or padding goes. Also, on the “Settings” page (and “Security” section), the FTL IDs are showing.

We should poke through Storybook and see if there’s anything else to fix too.

!image-20220511-204902.png|width=394,height=406!

!image-20220511-204820.png|width=622,height=471!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5072)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23724">image-20220511-204820.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23725">image-20220511-204902.png</a>

**Comment by LZoog** [comment]
Fluent IDs were fixed here: #12861

We still need the styles fixed, though.
