### ISSUE TITLE
[FxA-Settings] Variables are not replaced with the corresponding data in Stage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12857]
**Build:**

Stage [Train 232]

**Affected platforms:**

Windows 10 64-bit

macOS 10.14

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

N/A

**Steps to reproduce:**

1. Go to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and log in using an existing account.
1. Hover over the Avatar/ Bento menu/ Help icons and observe the tooltips.
1. Go to Security section and observe the Recovery key and 2FA subsections name.
1. Scroll to the bottom of page and click Delete account button.
1. Observe the Delete account page.

**Actual result:**

The variables are not replaced with the corresponding data.

**Expected result:**

The variables are replaced with the corresponding data.

**Notes:**

Sync settings page seems to be affected too. “Null” tooltip is displayed for “last synced time”.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5075)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23747">delete account page issue.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23750">null tooltip.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23746">Recov key - UI issue.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23749">security section - layout issues.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23748">tooltip issues.png</a>

**Comment by pdehaan** [comment]
Another one when I tried to take a profile photo via my camera, but then rejected permissions request.
![Screen Shot 2022-05-12 at 10 31 33 AM](https://user-images.githubusercontent.com/557895/168134621-9c889a6a-a25d-4a0d-b270-a5f653d28260.png)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on stage [Train 232.1] on Windows 10. The strings are correctly displayed.

!warning message - new situation.png|width=522,height=359!

!tooltip - new situation.png|width=210,height=130!

!Save button - new situation.png|width=430,height=324!

!security section - new situation.png|width=848,height=215!
