### ISSUE TITLE
Upgrade apollo-server from 2.25.3 to 3.7.0+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12851]
Failed dependabot: [https://github.com/mozilla/fxa/pull/12803](https://github.com/mozilla/fxa/pull/12803|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5074)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
