### ISSUE TITLE
Page title renders as "app-page-title" on stage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12859]
Found in 1.232.0 (per https://accounts.stage.mozaws.net/__version__)

```js
{
  commit: "ce5f77fb09b795123db6b4c34eafcd3e55b8c08a",
  version: "1.232.0",
  l10n: "b31a66852963f027870fa25e3893e9d390215118",
  tosPp: "569f5c812ef288c4ebf19b8d521ba90b99e99cfc",
  source: "https://github.com/mozilla/fxa"
}
```

## Description

Page titles seem to be "app-page-title" on Firefox/Chrome for stage (works fine in prod)

### Steps to reproduce

1. Log in and go to https://accounts.stage.mozaws.net/settings/avatar
2. View page title in tab (or view inspect the DOM, if that's your thing)

### Expected result

Prod (1.231.4) says: `<title>⁨Profile Picture⁩ | ⁨Firefox Accounts⁩</title>`
Stage (1.232.0) says: `<title>app-page-title</title>`

### Actual result

![Screen Shot 2022-05-12 at 9 21 48 AM](https://user-images.githubusercontent.com/557895/168123241-c5b068e2-95e7-4a4e-8983-13011e90369e.png)

### Environment

Firefox Release and Chrome Stable

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5077)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on Stage [Train 232.1] on Windows 10. The page title in tab is correctly displayed.

!page title - new situation.png|width=830,height=580!
