### ISSUE TITLE
Localize the password created at date?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12862]
## Description

The account password's created at date isn't displayed in a locale friendly format.

### Steps to reproduce

1. Sign in to https://accounts.stage.mozaws.net/settings#security
2. Observe your Password's "Created" date.

### Expected result

We should probably localize that date to something like "April 7, 2021" (since dates like 2021-04-07 can be ambiguous).
For example, on the https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions page we show dates like "January 19, 2023" instead of "2023-01-19".

![Screen Shot 2022-05-12 at 10 22 33 AM](https://user-images.githubusercontent.com/557895/168133073-f0caf87c-df9b-4588-98cc-30d0122bd4ae.png)

### Actual result

"2021-04-07"

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5079)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

We might be able to do this with JS' localizeString.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
