### ISSUE TITLE
Upgrade fxa-settings from React 16 to 18

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12863]
This requires some changes to Portal

see #8513 / #12736 for list of failed tests

We also have React as a dependency of fxa-content-server. I think this is because we have fxa-react and fxa-settings as workspace dependencies - if this ticket is finished after the fxa-react React upgrade, let’s try to upgrade React in content-server here. If there’s hiccups, file a separate issue for it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5081)

**Comment by pdehaan** [comment]
Via my Twitter feed: https://blog.openreplay.com/an-ultimate-guide-to-upgrading-to-react-18

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
