### ISSUE TITLE
Add OpenTelemetry library to fxa-auth-server

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12865]
The sentry tracing library/configuration should be removed, and the OpenTelemetry one added and configured to work with Google Trace:

[https://cloud.google.com/trace/docs/setup/nodejs-ot#auto-instrumentation_for_web_applications](https://cloud.google.com/trace/docs/setup/nodejs-ot#auto-instrumentation_for_web_applications|smart-link) 

This should be tested locally using Google Trace with Google auth credentials to ensure the trace covers what the docs indicate, such as:

* http/https calls
* database calls (Redis, MySql, Firestore?)

A configuration variable should be used to declare a sample rate that is to be used when sampling traces.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5084)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
