### ISSUE TITLE
fxa-react Upgrade Tailwindcss (tailwind) from 1.9.1 to 3.0.23

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12864]
Upgrade Tailwindcss from 1.9.1 to 3.0.23 - this might require separate tickets, as there needs to be upgrades in the following:

* fxa-react

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5082)

**Comment by pdehaan** [comment]
Related #12154
