### ISSUE TITLE
Capture trace id in logging statements

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12867]
The global tracer can be fetched as shown here:

[https://cloud.google.com/trace/docs/setup/nodejs-ot#creating_a_custom_span](https://cloud.google.com/trace/docs/setup/nodejs-ot#creating_a_custom_span|smart-link) 

It can be used to fetch the trace id, so we can add it to logging statements.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5086)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
