### ISSUE TITLE
Add OpenTelemetry library to fxa-settings-server

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12866]
The sentry tracing library/configuration should be removed, and the OpenTelemetry one added and configured to work with Google Trace:

[https://cloud.google.com/trace/docs/setup/nodejs-ot#auto-instrumentation_for_web_applications](https://cloud.google.com/trace/docs/setup/nodejs-ot#auto-instrumentation_for_web_applications|smart-link) 

This should be tested locally using Google Trace with Google auth credentials.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5085)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
