### ISSUE TITLE
Add eslint-plugin-jest plugin's `valid-expect` rule to detect future `.toBeTruthy` issues

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12893]
## Description

Second part of https://github.com/mozilla/fxa/issues/12868 (where we add the ESLint plugin to catch future incidents/typos)

### Steps to reproduce

Not sure if we add it to each package that uses Jest, or if we try shimming it into the [eslint-plugin-fxa](https://github.com/mozilla/eslint-plugin-fxa) package.

### Expected result

Fix _future_ uncalled `.toBeInTheDocument` and `.toBeTruthy` references in tests (where they should be `.toBeTruthy()`).

### Actual result

See https://github.com/mozilla/fxa/pull/12892 PR which fixes the current issues, but this ticket/task should ideally make sure we don't make similar typos in the future.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5095)

**Comment by pdehaan** [comment]
Quick little <kbd>git grep</kbd> command to detect which packages are likely using Jest.

```sh
git grep -nE '"jest": "([[:digit:]]+\.?){3}"' packages/*/package.json | cat

packages/fxa-admin-panel/package.json:101:    "jest": "27.5.1",
packages/fxa-admin-server/package.json:88:    "jest": "27.5.1",
packages/fxa-event-broker/package.json:99:    "jest": "27.5.1",
packages/fxa-graphql-api/package.json:97:    "jest": "27.5.1",
packages/fxa-payments-server/package.json:101:    "jest": "27.5.1",
packages/fxa-react/package.json:72:    "jest": "27.5.1",
packages/fxa-shared/package.json:65:    "jest": "27.5.1",
packages/fxa-support-panel/package.json:73:    "jest": "27.5.1",
```

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa/issues/12978

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
