### ISSUE TITLE
Checkbox selections are not remembered when browsing to TOS/PP and back

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1291]
Noticed while testing Trailhead, but this applies equally to the existing CWTS screen.

STR

1. Create a profile set up for stage:
  * in about:config change `identity.fxaccounts.autoconfig.uri` and `browser.newtabpage.activity-stream.fxaccounts.endpoint` to `https://accounts.stage.mozaws.net`
  * restart browser
2. Open about:welcome, fill out an email, submit
3. Fill out a password, vpassword, age.
4. Select a couple of newsletters
5. Click on the "Terms of Service" link.
6. Scroll to the bottom of the screen, click "back"
7. The password, vpassword and age fields are all remembered, none of the newsletters are.

![newsletters-not-remembered](https://user-images.githubusercontent.com/848085/58544069-7f5a2f00-81f8-11e9-83d8-1d01548b775a.gif)

In the [form-prefill-mixin](https://github.com/mozilla/fxa/blob/bd8ff27e8d9ec32b55bc43dfb8e179e752990bba/packages/fxa-content-server/app/scripts/views/mixins/form-prefill-mixin.js#L6), we do not make any affordances to correctly handle checkboxes.

I started on a fix last week, but there were more pressing things to finish.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-108)
┆Issue Number: FXA-108

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Not on our roadmap.
