### ISSUE TITLE
Investigate `celebrate` dependency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12910]
The `celebrate` dependency utilizes `joi` v17.4.0, which is the version the whole codebase is using despite the latest version of `joi` being 17.6.0. We are unable to update to `joi` 17.6.0 as one of joi’s dependency upgrades now [prevents mixing different versions of joi schemas](https://github.com/sideway/joi/issues/1913).

`celebrate` is currently only used in `fxa-payments-server` and `fxa-shared` .

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5107)

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

I’ll check again if we are able to upgrade to joi v17.6.0, as celebrate specifies they are compatible with joi 17.x.

This ticket might just be a heads-up that dependabot will notify us that there is a later version of joi to upgrade to, but celebrate would block the upgrade since it is using v17.4.0 and we would get an error (Cannot mix different versions of joi schemas).

We could either: 

(1) wait for celebrate to upgrade their dependency on joi to the latest version, or

(2) replace celebrate with another dependency

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
