### ISSUE TITLE
[a11y] Document should not have more than one banner landmark (subplat)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12918]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

1. Log into FxA and go to https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Run axe DevTools

### Expected result

Ensures the document has at most one banner landmark

### Actual result

> Document should not have more than one banner landmark ([ref](https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=AxeChrome))

This seems to be the element it flags; probably because it's the first `<header>` tag.
```html
<header id="fxa-settings-header">
  <h1 id="fxa-manage-account"><span class="fxa-account-title">Firefox Accounts</span></h1>
</header>
```

The other elements seem to be:
1. the "panel" header area w/ my profile picture, name, and email address:
    ```html
    <header id="fxa-settings-profile-header-wrapper">
      <div class="avatar-wrapper avatar-settings-view nohover">
        <img src="https://mozillausercontent.com/..." alt="Peter" class="profile-image">
      </div>
      <div id="fxa-settings-profile-header">
        <h1 class="card-header">Peter</h1>
        <h2 class="card-subheader">pdehaan@email.com</h2>
      </div>
    </header>
    ```
2. The "Subscriptions" row header:
    ```html
    <header class="settings-unit-summary">
      <h2>Subscriptions</h2>
    </header>
    ```
3. One of my subscriptions (in my case MDN Plus):
    ```html
    <header>
      <h2>MDN Plus</h2>
    </header>
    ```

Not sure if we need to wrap the main panel in a `<main>` tag so we can use multiple `<header>` tags, and then possibly put the "Subscriptions" and "MDN Plus" table-esque rows as separate `<section>` tags (since that feels slightly more semantically accurate than `<aside>` or `<article>`).

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5112)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
