### ISSUE TITLE
[a11y]  Links with the same name must have a similar purpose

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12917]
## Description

The "Settings" page has 3 buttons that all say "Change" without a lot of context for screen readers.

### Steps to reproduce

1. Log in to https://accounts.stage.mozaws.net/settings
2. Run axe DevTools

### Expected result

No a11y errors/warnings

> Fix the following:
> Check that links have the same purpose, or are intentionally ambiguous.

### Actual result

> Links with the same name must have a similar purpose

Seems to be flagging the following element, &hellip; which happens to be the Change picture/avatar button.

```html
<a class="cta-neutral cta-base transition-standard rtl:ml-1" 
    data-testid="avatar-unit-row-route"
    href="/settings/avatar?deviceId=...&amp;flowBeginTime=...&amp;flowId=...&amp;broker=web&amp;context=web&amp;isSampledUser=false&amp;service=none&amp;uniqueUserId=..."
>Change</a>
```

The other two elements it flags are:

1. the Change display name button:
    ```html
    <a class="cta-neutral cta-base transition-standard rtl:ml-1"
      data-testid="display-name-unit-row-route"
      href="/settings/display_name?deviceId=...&amp;flowBeginTime=...&amp;flowId=...&amp;broker=web&amp;context=web&amp;isSampledUser=false&amp;service=none&amp;uniqueUserId=..."
    >Change</a>
    ```

2. the Change password button:
    ```html
    <a class="cta-neutral cta-base transition-standard rtl:ml-1 mobileLandscape:mr-9"
      data-testid="password-unit-row-route"
      href="/settings/change_password?deviceId=...&amp;flowBeginTime=...&amp;flowId=...&amp;broker=web&amp;context=web&amp;isSampledUser=false&amp;service=none&amp;uniqueUserId=..."
    >Change</a>
    ```

Axe refers me to https://dequeuniversity.com/rules/axe/4.4/identical-links-same-purpose?application=AxeChrome

So maybe the easiest solution is to add more specific `aria-label=""` attributes to better describe the buttons, like:
- "Change profile picture"
- "Change display name"
- "Change password"

But that might allow us to improve accessibility without impacting the UI/layout by altering the visible button labels.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5111)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
