### ISSUE TITLE
[a11y] Invalid ARIA attribute value: aria-controls="drop-down-bento-menu"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12915]
## Description

Ran axe via DevTools and spotted this.

### Steps to reproduce

Install axe add-on and run on https://accounts.stage.mozaws.net/settings

> _"Ensures all ARIA attributes have valid values"_

```
<button data-testid="drop-down-bento-menu-toggle"
    title="Firefox Bento Menu"
    aria-controls="drop-down-bento-menu"
    class="rounded p-1 w-7 mx-2 border-transparent hover:bg-grey-200 transition-standard desktop:mx-8">
```

### Expected result

No a11y issues.

### Actual result

https://github.com/mozilla/fxa/blob/c62c0dd814c37afb8d9772f2683ccf274c12f480/packages/fxa-settings/src/components/BentoMenu/index.tsx#L33-L42

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5109)

**Comment by data-sync-user** [comment]
➤ Meghan Sardesai commented:

@pdehaan are you still seeing this issue? I could initially reproduce a week ago but am not seeing it today. It might have been fixed. Please let me know.
