### ISSUE TITLE
[a11y] Heading levels should only increase by one (subplat)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12923]
## Description

> Ensures the order of headings is semantically correct ([ref](https://dequeuniversity.com/rules/axe/4.4/heading-order?application=AxeChrome))

### Steps to reproduce

1. Log into FxA and go to https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Have a pending cancelled subscription, then click the "Resubscribe" button.
3. Run axe DevTools

### Expected result

No a11y errors/warnings.

### Actual result

> Fix the following:
> - Heading order invalid

```html
<h4>Want to keep using ⁨MDN Plus⁩?</h4>
```

Not sure if this is because we previously only had an `<h1>` and `<h2>` or something, or if we need to wrap the dialog in some landmark element like `<aside>` and then reset the headings to be an `<h1>` since it's the primary heading for the modal dialog and then fiddle with the styling since converting from an `<h4>` to `<h1>` currently changes the UI a bit too much.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5116)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
