### ISSUE TITLE
Firefox services shows on bottom of `/` page

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1292]
STR

1. Enter an email in about:welcome, submit
2. On the /signup page, click "Change email"
3. On the `/` page, the Firefox services list shows on the bottom instead of the right.

@ryanfeeley is the intent for the list of services to show to the right here too?

<img width="688" alt="Screenshot 2019-05-29 at 11 24 53" src="https://user-images.githubusercontent.com/848085/58549928-89822a80-8204-11e9-8fb6-17a82db530cb.png">

**Comment by clouserw** [comment]
This was on purpose for narrow screens, I think.  The designs changed last week.

**Comment by clouserw** [comment]
This is working as designed.
