### ISSUE TITLE
[storybook] Security errors when accessing the Security stories in Storybook

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12943]
## Description

Getting an `date value is not finite in DateTimeFormat.format()` error on the following pages:
- "Components > Security > default"
- "Components > Security > account recovery key set and two factor enabled"

### Steps to reproduce

- **Security**
  - [default](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/d734ccfda4bb7b38096bc4d0b216f2058c416de0/fxa-settings/index.html?path=/story/components-security--default)
  - [account recovery key set and two factor enabled](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/d734ccfda4bb7b38096bc4d0b216f2058c416de0/fxa-settings/index.html?path=/story/components-security--account-recovery-key-set-and-two-factor-enabled)

### Expected result

No errors

### Actual result

> date value is not finite in DateTimeFormat.format()
> Security@https://storage.googleapis.com/mozilla-storybooks-fxa/commits/d734ccfda4bb7b38096bc4d0b216f2058c416de0/fxa-settings/main.0b7b9766.iframe.bundle.js:1:156687

![Screen Shot 2022-05-18 at 4 54 47 PM](https://user-images.githubusercontent.com/557895/169173947-1fa8f1ad-6908-462a-b380-3c43b472fe16.png)

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5124)

**Comment by LZoog** [comment]
This was fixed in #12798
