### ISSUE TITLE
The failing circle tests are really annoying

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1295]
At least 50% of my Circle test runs fail for what appear to be random and unrelated reasons. Sometimes a session can't be created, sometimes the CSS doesn't seem to be built, sometimes the pairing tests fail because the QR code reader can't find enough points.

The pairing tests are by far the most common failures, perhaps 25% of the time.

Whatever the reasons, it's really annoying.

cc @vladikoff for the pairing tests.

**Comment by philbooth** [comment]
See also: #1188

**Comment by vladikoff** [comment]
Was Firefox updated at all?

**Comment by vladikoff** [comment]
WRT to pairing tests, replacing the QR scanning library should do the trick, or if we find a way to make scanning more consistent

**Comment by vladikoff** [comment]
>  replacing the QR scanning library should do the trick

Big bet on this: https://github.com/mozilla/fxa/pull/1300

**Comment by clouserw** [comment]
I think this has been addressed...  If not, please open specific issues.  Thanks.
