### ISSUE TITLE
Upgrade @testing-library/react from 12.1.3 to 13.2.0+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12968]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12856](https://github.com/mozilla/fxa/pull/12856|smart-link) 

We may need to split this out into separate issues per package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5136)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
