### ISSUE TITLE
Upgrade eslint-config-react-app from 6.0.0 to 7.0.1+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12969]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12770](https://github.com/mozilla/fxa/pull/12770|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5137)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
