### ISSUE TITLE
Upgrade react-dom from 16.14.0 to 18.1.0+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12973]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12925](https://github.com/mozilla/fxa/pull/12925|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5140)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
