### ISSUE TITLE
Upgrade jest-environment-jsdom from 27.5.1 to 28.1.0+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12970]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12924](https://github.com/mozilla/fxa/pull/12924|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5138)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
