### ISSUE TITLE
Upgrade fxa-payments-server from React 16 to 18

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12975]
Blocked by Portal changes.

see #8513 / #12736 for list of failed tests

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5142)

**Comment by pdehaan** [comment]
Via my Twitter feed: https://blog.openreplay.com/an-ultimate-guide-to-upgrading-to-react-18

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
