### ISSUE TITLE
Create test automation verifying coupons on Staging

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12971]
This is a task to create test automation to verify coupons, to be run in the Staging environment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5139)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
