### ISSUE TITLE
[Bug]: TalkBack audio for the password field in Firefox Sync reads out an error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12977]
### Steps to reproduce
1. Turn TalkBack (or the available screen reader) on
1. Open Firefox > 3-dot menu > Sign in to sync
1. Use a valid email and proceed to the password field
1. Select the password field and observe the audio

### Expected behaviour
TalkBack reads out the corresponding password input field name and available action

### Actual behaviour
The audio for the password field is "editing - enter password - edit box - error - null - password required - double tap to enter text"

### Device name
Samsung Galaxy A8

### Android version
Android 9

### Firefox release type
Firefox Nightly

### Firefox version
94.0.a1 2021-09-22

### Additional information
Also occurs on 93.0.0-beta.2 2021-09-13 and RC 92.1.1 2021-09-04

[https://user-images.githubusercontent.com/89511597/134481328-91b0006a-f565-4f7f-bef9-d5843629ccf8.mp4](https://user-images.githubusercontent.com/89511597/134481328-91b0006a-f565-4f7f-bef9-d5843629ccf8.mp4)

- - -
This was originally filed as [https://mozilla-hub.atlassian.net/browse/FNXV2-17990](https://mozilla-hub.atlassian.net/browse/FNXV2-17990|smart-link) / [https://github.com/mozilla-mobile/fenix/issues/21468](https://github.com/mozilla-mobile/fenix/issues/21468|smart-link) and closed and refiled as [https://bugzilla.mozilla.org/show_bug.cgi?id=1770097](https://bugzilla.mozilla.org/show_bug.cgi?id=1770097|smart-link)  since it’s an FxA bug. I couldn’t move the GH issue into FxA since I don’t have write access to the other repo and we can’t clone Jira tickets directly into other projects so I copied and pasted.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5144)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
