### ISSUE TITLE
Document when to call from auth-client vs GQL Mutation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12989]
Our [Account.ts model](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/models/Account.ts) sends data to the server-side through either GQL mutations, or through methods on the auth-client.

We should document:

* When and why we need to use the auth-client for some calls, vs just using a GQL mutation
* When we need to broadcast events with something like `firefox.profileChanged()`
* When we need to do anything with “legacy” account references, e.g. when we need changes to populate out into content-server
* What we use the apollo client cache for, e.g. it holds GQL-shaped data that we reference and read in the `useAccount` hook

This might be best to go into [https://github.com/mozilla/fxa/tree/main/packages/fxa-settings](https://github.com/mozilla/fxa/tree/main/packages/fxa-settings|smart-link) , since that README contains similar best practice/doc info.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5146)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
