### ISSUE TITLE
Convert support-panel from HBS to EJS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12998]
Since our emails were moved over to EJS, and with FXA-5065 / #12997 as well as future plans to move fxa-content-server over to React, support-panel would be our last package not using React or EJS. For consistency and to reduce our dependencies, as well as because the only “view” file I see is `views/index.hbs`, we should be able to convert the support-panel over fairly easily.

This was split off from discussion in [https://mozilla-hub.atlassian.net/browse/FXA-5065](https://mozilla-hub.atlassian.net/browse/FXA-5065|smart-link).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5155)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
