### ISSUE TITLE
Phase out moment/dateFormat

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12990]
We talked in triage last week about removing our dependence on `moment` and also `dateFormat` in favor of a vanilla JS solution.

We could use a utility wrapper in `fxa-shared` for any time we want to display dates in the UI, making it consistent across packages.

Interesting link: [https://github.com/you-dont-need/You-Dont-Need-Momentjs](https://github.com/you-dont-need/You-Dont-Need-Momentjs|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5147)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
