### ISSUE TITLE
Drop unneeded tokenVerification columns from DB

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12994]
After we have successfully phased out the session token’s tokenVerification fields (FXA-4856). The following columns are no longer needed and can be dropped.

* fxa.unverifiedTokens.tokenVerificationId
* fxa.unverifiedTokens.tokenVerificationCodeHash
* fxa.unverifiedTokens.tokenVerificationCodeExpiresAt

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5151)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
