### ISSUE TITLE
Upgrade graphql from 15.6.1 to 16.5.0+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13000]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12984](https://github.com/mozilla/fxa/pull/12984|smart-link) 

This probably needs to be split out into different packages before it’s worked on, but maybe upgrading the first will make upgrading other packages easier if there’s a pattern of changes to follow.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5157)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
