### ISSUE TITLE
Return error code when account attempts to login with no password set

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#13013]
Accounts  created via a third party will not have a password set. This can cause issues if they attempt to login to another service that does not show the third party login options.

We can add something similar [here](https://github.com/mozilla/fxa/blob/ac4647ecd1f6e9a7219a0a67b210691f9516b5bf/packages/fxa-auth-server/lib/routes/account.ts#L676)

```
if (!accountRecord.verifierSetAt) {
  throw error.cannotLoginNoPasswordSet();
}
```

On our UX we could surface an error message "Please reset password to continue. Click here` or something like that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5164)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
