### ISSUE TITLE
stage: reduce the reminder email interval so QA can test

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1302]
Right now reminder emails are sent after 1 day and 5 days on stage and prod. This makes it impossible for QA to test the verification reminder functionality works before Trailhead actually launches - if initiated today, the second reminder won't be sent until Tuesday after Trailhead launches.

For stage, let's reduce the interval to 10 minutes and 15 minutes, long enough most people testing won't hit them, but short enough QA can do their jobs w/o waiting the better part of a week.

**Comment by shane-tomlinson** [comment]
@jrgm just informed me that verification reminders are sent on a cronjob every 20 minutes. Setting to 10 and 15 minutes could send both at once if both are within one 20 minute cron window.

Maybe we should say 10 and 30 minutes then.

**Comment by philbooth** [comment]
I didn't think the reminders script was even running in stage, is it? For prod we had to deploy it especially to the canary instance, is a similar arrangement in place for stage?

**Comment by shane-tomlinson** [comment]
@jrgm - is the reminders cron job run on stage?

**Comment by shane-tomlinson** [comment]
This is done, closing.
