### ISSUE TITLE
Link about resetting password seems out of place under "Recovery Key" heading

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13026]
!nP3ZAeGb4hQm5NX_bLVBtRbkEfiOUk-qqJz4XIhwCz-dCAYZwnA5TdIDarWVwWfSe1DVXl6RhHMgAu-86bhQXAudeqAaHxmABGglahCvXDSetIoRDGYDt_hf7ZCeqGWpo65ISZNtS8bUjirYKw|width=664,height=338!

We have a link about resetting a password will reset data which is great information, but seems like a weird place to put it.  When a person actually goes to reset their password we have a different warning:

!image-20220525-153106.png|width=321,height=379!

Which seems better.  I think maybe we should just delete the link under Recovery Key?  [~accountid:60482f83bfef95006bc8ad2d] what do you think?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5167)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24285">image-20220525-153106.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24286">nP3ZAeGb4hQm5NX_bLVBtRbkEfiOUk-qqJz4XIhwCz-dCAYZwnA5TdIDarWVwWfSe1DVXl6RhHMgAu-86bhQXAudeqAaHxmABGglahCvXDSetIoRDGYDt_hf7ZCeqGWpo65ISZNtS8bUjirYKw</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
