### ISSUE TITLE
The device icon looks smaller than the other icons

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13027]
!nljIIu2hV3fs-8tLNJHtT0cAERv44jtDmZDiI6tStiNk_paZzcC3W8VHEJPXVsV-lHRWbtD5XbGX6XYnEA-DcUEI_AeOpay03CG9xoxTslC6wYJVzrkkDLhOyhlMEPIDOBdmZFav9jhHM0vQWg|width=50%!

Since I just did a few of these icons, I know the new ones are 24x24.  I think this icon is [https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/ConnectedServices/mobile.svg](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/ConnectedServices/mobile.svg|smart-link)  which, yeah, it’s too small.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5168)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24288">nljIIu2hV3fs-8tLNJHtT0cAERv44jtDmZDiI6tStiNk_paZzcC3W8VHEJPXVsV-lHRWbtD5XbGX6XYnEA-DcUEI_AeOpay03CG9xoxTslC6wYJVzrkkDLhOyhlMEPIDOBdmZFav9jhHM0vQWg</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Vesta Zare do you know someone who could give us a larger (24x24) version of this icon?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
