### ISSUE TITLE
Mobile nav highlight doesn't follow navigation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13029]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5169)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24289">image-20220525-154046.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
