### ISSUE TITLE
Circle tests failing because gcloud is not installed

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1303]
See https://circleci.com/gh/mozilla/fxa/25673

> install gcloud to continue installation

Why did the tests pass for https://github.com/mozilla/fxa/pull/1261 in the first place? Strange.

cc @bbangert

**Comment by bbangert** [comment]
gcloud was introduced in #1287, the tests didn't seem to catch it for unknown reasons.
