### ISSUE TITLE
[subplat] Support invoice's generated without an attached subscription

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13037]
**Background**

We currently retrieve the nextInvoiceDate by querying the invoice line item associated with the subscription. 

However this change does not work when the invoice is not associated to a subscription, such as in the case of a refund that returns unused time.

**Requirement**

Whenever we filter the Invoice line items by `type = 'subscription'` we need to add support for invoices that might not have a line item associated to a subscription.

**Additional Information**

[Sentry issue](https://sentry.io/organizations/mozilla/issues/3300039130/?project=6231056&referrer=slack)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5178)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
