### ISSUE TITLE
FxA email: postAddAccountRecovery

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13042]
This ticket includes changes to copy only, noted in **Bold.** There are no changes to images at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update the subject:【 end highlighted 】

**Account recovery key created (new)**

【 highlighted #ff5630 】Update the HTML body:【 end highlighted 】

**You created a new account recovery key (new)**

**A new key was created from: (new)**

<browser version or service name> (existing)

<location> (estimated)  (existing)

IP address: <IP address>  (existing)

<date>  (existing)

<time>  (existing)

**Not you? (new)**

[*Delete the new key*](http://localhost:3030/settings#recovery-key) **and** [*change your password*](http://localhost:3030/settings/change_password) **(new)**

Button: [Manage account](http://localhost:3030/settings) (existing)

Footer Component (existing)

【 highlighted #ff5630 】Update to TXT body:【 end highlighted 】

**You created a new account recovery key (new)**

**A new key was created from: (new)**

<browser version or service name> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

<date> (existing)

<time> (existing)

**Not you? (new)**

**Delete the new key:** [+*http://localhost:3030/settings#recovery-key*+](http://localhost:3030/settings#recovery-key) **(new)**

**Change your password:** [+*http://localhost:3030/settings/change_password*+](http://localhost:3030/settings/change_password) **(new)**

Manage account: [http://localhost:3030/settings](http://localhost:3030/settings) (existing)

Footer Component (existing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5183)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
