### ISSUE TITLE
FxA email: lowRecoveryCodes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13055]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5188)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Note that the count that triggers the low recovery code emails is currently configurable.  By hard coding “two” into the email, we effectively limit that configurable value to a max of 2.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

This Jira also does not cover the scenario where the user has used all of their recovery codes, which also will trigger the low recovery codes email.  

Vesta Zare do we have new email templates for when the user used their last recovery code?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
