### ISSUE TITLE
Migrate eslint-plugin-fxa package into a new workspace?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13051]
## Description

Not sure if it'd we should migrate https://github.com/mozilla/eslint-plugin-fxa into the monorepo to make it easier to share custom configs. 
Plus, this way we can make a change in packages/eslint-plugin-fxa and have it immediately available to other workspaces without needing to publish the package to npm.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5186)

**Comment by pdehaan** [comment]
Did some investigating on this today and copied most of the rules from Anna's Style Guide doc into a new config workspace, `packages/eslint-plugin-fxa-rules`, then added that as a dependency to a couple of the packages to try and fine tune a bit:

```js
// packages/fxa-admin-panel/.eslintrc.json
"extends": [
  "plugin:fxa-rules/recommended"
]
```

```js
// packages/fxa-admin-panel/package.json
"eslint-plugin-fxa-rules": "workspace:*",
```

```js
// packages/eslint-plugin-fxa-rules/index.js
module.exports = {
  configs: {
    recommended: {
      rules: {
        "camelcase": ["error", { properties: "never" }],
        // "complexity": ["error", { max: 20 }],
        "func-names": "error",
        "jsx-quotes": "error",
        "max-nested-callbacks": ["error", { max: 1 }],
        // "multiline-ternary": ["error", "always-multiline"],
        "no-multi-spaces": "error",
        "no-use-before-define": "off",
        "no-var": "error",
        "one-var": ["error", "never"],
        "prefer-const": "error",
        "strict": "off",
      },
      overrides: [
        {
          files: [
            "*.spec.*",
            "*.test.*"
          ],
          rules: {
            "max-nested-callbacks": "off",
          }
        }
      ]
    }
  }
};
```

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
