### ISSUE TITLE
FxA email: verify

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13053]
This ticket includes changes to copy only, noted in **Bold.** There are no changes to visual design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update the HTML body:【 end highlighted 】

**Open the internet with Firefox  (new)**

Image (existing)

Confirm your account and get the most out of Firefox everywhere you sign in starting with: (existing)

<browser version or service name> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

**<date>  (new)**

**<time>  (new)**

Button: [Confirm account](http://localhost:3030/verify_email) (existing)

Footer Component (existing)

【 highlighted #ff5630 】Update to TXT body:【 end highlighted 】

**Open the internet with Firefox  (new)**

Confirm your account and get the most out of Firefox everywhere you sign in starting with: (existing)

<browser version or service name> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

**<date>  (new)**

**<time>  (new)**

Confirm account: [http://localhost:3030/verify_email](http://localhost:3030/verify_email) (existing)

Footer Component (existing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5187)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
