### ISSUE TITLE
FxA email: newDeviceLogin

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13056]
Currently we use one template for both following conditions: new device login through Firefox VS new device login through something else. 

This ticket includes a proposal to use different copy for each email type. Changes to copy (not images) is noted in **Bold.** For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】**Email 1: New device login through Firefox**【 end highlighted 】

【 highlighted #ff5630 】Update the Condition:【 end highlighted 】

**Sent to notify the account that a new device has signed in through a Firefox browser. (new)**

【 highlighted #ff5630 】Subject:【 end highlighted 】

New sign in to Firefox (existing)

【 highlighted #ff5630 】Update the HTML body:【 end highlighted 】

**Your Firefox account was used to sign in (new)**

<browser version> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

<date> (existing)

<time> (existing)

**Not you?** [*Change your password*](http://localhost:3030/settings/change_password) **(new)**

Button: [Manage account](http://localhost:3030/settings) (existing)

Footer Component (existing)

【 highlighted #ff5630 】Update the TXT body:【 end highlighted 】

**Your Firefox account was used to sign in (new)**

<browser version> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

<date> (existing)

<time> (existing)

**Not you? Change your password:** [*http://localhost:3030/settings/change_password*](http://localhost:3030/settings/change_password) **(new)**

Manage account: [http://localhost:3030/settings](http://localhost:3030/settings) (existing)

Footer Component (existing)

【 highlighted #ff5630 】**Email 2: New device login through something else**【 end highlighted 】

【 highlighted #ff5630 】Update the Condition:【 end highlighted 】

**Sent to notify the account that a new device has signed in through another service like Firefox VPN. (new)**

【 highlighted #ff5630 】Update the Subject:【 end highlighted 】

**New sign in to <service name> (new)**

【 highlighted #ff5630 】Update the HTML body:【 end highlighted 】

**Your Firefox account was used to sign in (new)**

<service name> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

<date> (existing)

<time> (existing)

**Not you?** [*Change your password*](http://localhost:3030/settings/change_password) **(new)**

**Button:** [*Manage account*](http://localhost:3030/settings) **(new)**

Footer Component (existing)

【 highlighted #ff5630 】Update the TXT body:【 end highlighted 】

**Your Firefox account was used to sign in (new)**

<service name> (existing)

<location> (estimated) (existing)

IP address: <IP address> (existing)

<date> (existing)

<time> (existing)

**Not you? Change your password:** [*http://localhost:3030/settings/change_password*](http://localhost:3030/settings/change_password) **(new)**

Manage account: [http://localhost:3030/settings](http://localhost:3030/settings) (existing)

Footer Component (existing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5189)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

{quote}Currently we use one template for both following conditions: new device login through Firefox VS new device login through something else.{quote}

I don’t think this is true.  We only send device sign-in emails when a user is signing into sync.  I just tried logging into my personal VPN account on prod and MDN Plus on stage and neither send me an email.

I’m putting this back into New so we can discuss in triage.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
