### ISSUE TITLE
FxA email: postVerify

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13068]
This ticket includes changes to copy only, noted in **Bold.** There are no changes to visual design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update condition:【 end highlighted 】

**Sent after account is confirmed during Sync registration on a non-mobile and mobile devices. (new copy)**

【 highlighted #ff5630 】Update subject:【 end highlighted 】

**Welcome to Firefox! (new copy)**

【 highlighted #ff5630 】Update to HTML body: (all new copy)【 end highlighted 】

**We’re delighted to see you!**

Want to see the same tab on two devices?

It’s easy! Just install Firefox on another device and log in to sync. It’s like magic!

(Psst…It also means you can get your bookmarks, passwords, and other Firefox data everywhere you’re signed in.)

##### Button
[+Connect another device+](http://localhost:3030/connect_another_device)

Footer Component (existing)

【 highlighted #ff5630 】Update to TXT body: (all new copy)【 end highlighted 】

**We’re delighted to see you!**

Want to try seeing the same tab on two devices?

It’s easy! Just install Firefox on another device and log in to sync. It’s like magic!

(Psst…It also means you can get your bookmarks, passwords, and other Firefox data everywhere you’re signed in.)

[Connect another device](http://localhost:3030/connect_another_device):

[http://localhost:3030/connect_another_device](http://localhost:3030/connect_another_device)

Footer Component (existing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5202)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
