### ISSUE TITLE
FxA email: verificationReminderFirst

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13072]
This ticket includes updates to copy only. The updated copy is in **Bold** but existing copy is also provided for completeness purposes. There are no changes to design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update the subject:【 end highlighted 】

**Remember to confirm your account**

【 highlighted #ff5630 】Update the HTML body: 【 end highlighted 】【 highlighted #ff5630 】**(Update all)**【 end highlighted 】

**Welcome to Firefox!**

A few days ago you created a Firefox account, but never confirmed it. Please confirm your account within the next 15 days or it will be automatically deleted.

Don’t miss out on the browser that puts you and your privacy first.

**Button:**

[*Confirm account*](http://localhost:3030/verify_email)

<Footer Component>

【 highlighted #ff5630 】Update to TXT body 【 end highlighted 】【 highlighted #ff5630 】**(Update all)**【 end highlighted 】

**Welcome to Firefox**

A few days ago you created a Firefox account, but never confirmed it. Please confirm your account within the next 15 days or it will be automatically deleted.

Don’t miss out on tech that puts you and your privacy first.

Confirm account:

[http://localhost:3030/verify_email](http://localhost:3030/verify_email)

<Footer Component>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5206)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
