### ISSUE TITLE
FxA email: verificationReminderSecond

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13071]
This ticket includes updates to copy only. The updated copy is in **Bold** but existing copy is also provided for completeness purposes. There are no changes to design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update the Subject:【 end highlighted 】 

**Remember to confirm your account**

【 highlighted #ff5630 】Update the HTML body 【 end highlighted 】【 highlighted #ff5630 】**(all new)**【 end highlighted 】

**Don’t miss out on Firefox**

A few days ago you created a Firefox account, but never confirmed it. Please confirm your account in the next 10 days or it will be automatically deleted.

Your Firefox account lets you sync your info across devices and unlocks access to more privacy-protecting products from Mozilla.

Be part of our mission to transform the internet into a place that’s open for everyone.

**Button:**

[*Confirm account*](http://localhost:3030/verify_email)

<Footer Component>

【 highlighted #ff5630 】Update the TXT body 【 end highlighted 】【 highlighted #ff5630 】**(all new)**【 end highlighted 】

**Don’t miss out on Firefox**

A few days ago you created a Firefox account, but never confirmed it. Please confirm your account in the next 10 days or it will be automatically deleted.

Your Firefox account lets you sync your info across devices and unlocks access to more privacy-protecting products from Mozilla.

Be part of our mission to transform the internet into a place that’s open for everyone.

Confirm account:

[http://localhost:3030/verify_email](http://localhost:3030/verify_email)

<Footer Component>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5207)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
