### ISSUE TITLE
Make trailhead flows RTL friendly and compatible

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1307]
Shane called out that there will likely be work required to support RTL with the trailhead flows.

**Comment by vbudhram** [comment]
@shane-tomlinson I went through the trailhead flows in RTL and they seem to look correct (minus the translations). Was there something else you wanted to check with it?

<img width="546" alt="Screen Shot 2019-06-25 at 1 58 23 PM" src="https://user-images.githubusercontent.com/1295288/60121666-989bc000-9751-11e9-8f47-5c8abf5a9cb8.png">
<img width="533" alt="Screen Shot 2019-06-25 at 1 55 55 PM" src="https://user-images.githubusercontent.com/1295288/60121667-989bc000-9751-11e9-8675-5094632bec66.png">
<img width="587" alt="Screen Shot 2019-06-25 at 1 53 53 PM" src="https://user-images.githubusercontent.com/1295288/60121668-989bc000-9751-11e9-932e-676361e292b1.png">
<img width="547" alt="Screen Shot 2019-06-25 at 1 53 39 PM" src="https://user-images.githubusercontent.com/1295288/60121669-989bc000-9751-11e9-91f2-b600b2c06c02.png">
<img width="789" alt="Screen Shot 2019-06-25 at 1 53 18 PM" src="https://user-images.githubusercontent.com/1295288/60121671-989bc000-9751-11e9-9ced-16477dd8964a.png">
<img width="873" alt="Screen Shot 2019-06-25 at 1 52 57 PM" src="https://user-images.githubusercontent.com/1295288/60121672-99345680-9751-11e9-8569-42a0afd3391c.png">
<img width="570" alt="Screen Shot 2019-06-25 at 1 51 03 PM" src="https://user-images.githubusercontent.com/1295288/60121674-99345680-9751-11e9-9be7-526b5d8a7e4f.png">

**Comment by shane-tomlinson** [comment]
@vbudhram thanks for checking, can you also check mobile? How should we handle the 3 dot progression bar, should that be reversed in RTL too?

**Comment by vbudhram** [comment]
@shane-tomlinson I made the screenshots in https://github.com/mozilla/fxa/pull/1703#issue-295496049 from mobile, which appear to look good. Here is confirmation screen on mobile

<img width="433" alt="Screen Shot 2019-07-08 at 4 54 22 PM" src="https://user-images.githubusercontent.com/1295288/60843093-aca8de00-a1a3-11e9-92d5-e029b5ad5ca5.png">


> How should we handle the 3 dot progression bar, should that be reversed in RTL too?

I think so and made an attempt at it here https://github.com/mozilla/fxa/pull/1703
