### ISSUE TITLE
FxA email: recovery

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13074]
This ticket includes changes to copy only, noted in **Bold.** There are no changes to visual design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update to HTML body:【 end highlighted 】

**Forgot your password? (new copy)**

Click the button within the next hour to create a new password.

This request came from: **(new copy)**

<browser version or service name>

<location> (estimated)

IP address: <IP address>

<date>

<time>

##### Button: [+Create new password+](http://localhost:3030/complete_reset_password)
Footer Component (existing)

【 highlighted #ff5630 】Update to TXT body:【 end highlighted 】

**Forgot your password? (new copy)**

Copy and paste the url below within the next hour to create a new password. **(new copy)**

[Create new password](http://localhost:3030/complete_reset_password):

[http://localhost:3030/complete_reset_password](http://localhost:3030/complete_reset_password)

This request came from:

<browser version or service name>

<location> (estimated)

IP address: <IP address>

<date>

<time>

Footer Component (existing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5204)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
