### ISSUE TITLE
FxA email: verifyShortCode

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13079]
This ticket includes updates to copy only. The updated copy is in **Bold** but existing copy is also provided for completeness purposes. There are no changes to design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update the Subject【 end highlighted 】 

**Confirm your account**

【 highlighted #ff5630 】Update the HTML body:【 end highlighted 】

**Open the internet with Firefox**

**Confirm your account and get the most out of Firefox everywhere you sign in starting with:**

<browser version or service name>

<location> (estimated)

IP address: <IP address>

<date>

<time>

**Use this confirmation code:**

<insert code>

It expires in <x> minutes.

<Footer Component> (existing)

【 highlighted #ff5630 】Update to TXT body:【 end highlighted 】

**Open the internet with Firefox**

**Confirm your account and get the most out of Firefox everywhere you sign in starting with:**

<browser version or service name>

<location> (estimated)

IP address: <IP address>

<date>

<time>

**Use this confirmation code:**

<insert code>

It expires in <x> minutes.

<Footer Component>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5212)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
