### ISSUE TITLE
FxA email: verifyLogin (through Firefox)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13078]
This ticket includes updates to copy only. The updated copy is in **Bold** but existing copy is also provided for completeness purposes. There are no changes to design at this time. For reference, all copy updates are also documented [here](https://docs.google.com/document/d/18gF_7Ux-jE_qfEFciOcPml0-G1SfHkjiJSMPwh2hnSc/edit#heading=h.4cagj37vd5jd). 

【 highlighted #ff5630 】Update condition【 end highlighted 】

Sent to users to verify a new login **to a Firefox Browser**

【 highlighted #ff5630 】Update the Subject:【 end highlighted 】 

**Confirm sign in**

【 highlighted #ff5630 】Update the HTML body:【 end highlighted 】

**Did you sign in to Firefox?**

**Help us keep your account safe by confirming you signed in on:**

<browser version or service name>

<location> (estimated)

IP address: <IP address>

<date>

<time>

Button:

[+Confirm sign in+](http://localhost:3030/complete_signin)

<Footer Component>

【 highlighted #ff5630 】Update the TXT body:【 end highlighted 】

**Did you sign in to Firefox?**

**Help us keep your account safe by confirming you signed in on:**

<browser version or service name>

<location> (estimated)

IP address: <IP address>

<date>

<time>

Confirm sign in:

[*http://localhost:3030/complete_signin*](http://localhost:3030/complete_signin)

<Footer Component>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5208)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
