### ISSUE TITLE
[docs] Update CircleCI doc in ecosystem docs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13085]
[https://mozilla.github.io/ecosystem-platform/reference/tests-in-circleci](https://mozilla.github.io/ecosystem-platform/reference/tests-in-circleci|smart-link)  seems quite outdated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5216)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
