### ISSUE TITLE
auth-server on main requires stripe keys to start

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13088]
This bug was introduced during a google payments refactor where I suggested requiring the stripe helper. Previously the support routes were only loaded if stripeHelper was setup, but a prior refactor moved that check out. A correct fix would be to require the stripeHelper before loading the support routes.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5218)

**Comment by biancadanforth** [comment]
Closed by PR #13089.
