### ISSUE TITLE
[l10n] [subplat] Pages/resources not fully translated into Latvian

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13095]
While testing [https://mozilla-hub.atlassian.net/browse/QA-1490](https://mozilla-hub.atlassian.net/browse/QA-1490|smart-link) we have noticed the following pages/resources not fully translated into Latvian:

* Set  up ypour subscription page: only product name, product details (partially) and the CC placeholder text are translated

!image-20220527-123700.png|width=731,height=856!

* Payment confirmation page:
* !image-20220527-135547.png|width=1084,height=821!
* code verification page

!image-20220527-140020.png|width=956,height=779!

* Firefox accounts tab name:

!image-20220527-140239.png|width=424,height=151!

* Welcome, Payment Confirmation, Cancelation emails

!image-20220527-141531.png|width=1399,height=475!

* Firefox accounts page

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5221)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24371">image-20220527-123700.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24374">image-20220527-135547.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24378">image-20220527-140020.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24379">image-20220527-140239.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24385">image-20220527-141531.png</a>

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

This is also the case for the Lithuanin language. Only the CC placeholder text are translated on the Set up your subscription page.

**Comment by flodolo** [comment]
We really shouldn't have issues on file for incomplete localization (I would normally close them as INVALID in Bugzilla).

There is no SLA associated to localization, and it's evident from Pontoon that the localization for FxA is incomplete for these locales.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Agreed.  Thanks Flod
