### ISSUE TITLE
Customers are able to use Firefox Relay masks as FXA primary email addresses

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13111]
At least two customers have now added Firefox Relay masks as their primary email address, breaking their account. Customers are unable to receive verification emails or even delete accounts because they never receive the verification emails. 

One customer has also posted this on Twitter: [https://twitter.com/kaffeeundsalz/status/1530132982677250048](https://twitter.com/kaffeeundsalz/status/1530132982677250048|smart-link)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5229)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Luke Crouch Should this be a relay bug to not forward email to another relay address?

**Comment by data-sync-user** [comment]
➤ Luke Crouch commented:

We can do that, but we should, IMO, also prevent someone from creating a Firefox Account with a @relay.firefox.com or @mozmail.com email address too.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

→ Product.  Vesta Zare we don’t block any other providers so this would be a new policy for us.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
