### ISSUE TITLE
fxa-profile can not change head picture in my server

### ISSUE THREAD

**Issue by guojiahuiEmily** [mozilla/fxa#13117]
## Description

I install a fxa server.  Can't change head pic.
Run fxa-profile by code by pm2 start profile.

### Steps to reproduce
enter
https://account.xxxx.com/settings/account_recovery?context=web

change head pic,
refresh

### Expected result

changed head pic appear.

### Actual result
changed head pic not appear. and bug show:
https://profileimages.xxx.com/a/c1862b79a76c3c86b167d8569146cda3
{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}

### Environment

What browser and operating system are you using?
ubuntu20

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5230)

**Comment by clouserw** [comment]
I'm sorry @guojiahuiEmily but we don't have the resources to debug this.
