### ISSUE TITLE
where is syncserver:1.5

### ISSUE THREAD

**Issue by guojiahuiEmily** [mozilla/fxa#13128]
## Description

docker mozilla/syncserver:latest and mozilla/syncserver:1.7.0 not work.
the result of curl localhost:5000/1.0/sync/1.5 
is 0

and client would got error:
FxAccountSyncAdapter :: Failed to get token.
    org.mozilla.gecko.tokenserver.TokenServerException$TokenServerMalformedResponseException: org.mozilla.gecko.sync.NonObjectJSONException: value must be a JSON object

but https://token.services.mozilla.com/1.0/sync/1.5
is
{"status": "error", "errors": [{"location": "body", "name": "", "description": "Unauthorized"}]}

https://token.services.mozilla.com/
result:
{"services": {"sync": ["1.5"]}, "auth": "https://token.services.mozilla.com", "browserid": {"allowed_issuers": ["api.accounts.firefox.com"], "trusted_issuers": ["api.accounts.firefox.com"]}, "oauth": {"default_issuer": "api.accounts.firefox.com", "scope": "https://identity.mozilla.com/apps/oldsync", "server_url": "https://oauth.accounts.firefox.com/v1"}}

### Steps to reproduce

execute
https://github.com/mozilla/fxa/blob/main/_scripts/syncserver.sh

curl localhost:5000/1.0/sync/1.5 

### Expected result

{"status": "error", "errors": [{"location": "body", "name": "", "description": "Unauthorized"}]}

### Actual result

0 

### Environment

ubuntu20 , use  docker

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5235)

**Comment by clouserw** [comment]
Hi @guojiahuiEmily .  Thanks for filing a bug, but we generally don't have the resources to debug people's installations.  For this issue, I'm not sure that docker image is supported.  If you want to run the sync server, try https://github.com/mozilla-services/syncserver/
