### ISSUE TITLE
Add @storybook/addon-a11y plugin to audit a11y on Storybook stories

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13120]
## Description

We have about 4-5 projects currently using Storybook, but it might be nice to see if we can get this a11y add-on set up in the following repos so we can audit a11y at a per-component basis.

https://storybook.js.org/addons/@storybook/addon-a11y

Per https://storage.googleapis.com/mozilla-storybooks-fxa/commits/b08224d5946d1b8cbd2dd7a95fc8688a01556e0b/index.html
- [fxa-admin-panel](https://github.com/mozilla/fxa/tree/main/packages/fxa-admin-panel) (no stories?)
- [fxa-auth-server](https://github.com/mozilla/fxa/tree/main/packages/fxa-auth-server)
- [fxa-payments-server](https://github.com/mozilla/fxa/tree/main/packages/fxa-payments-server)
- [fxa-react](https://github.com/mozilla/fxa/tree/main/packages/fxa-react)
- [fxa-settings](https://github.com/mozilla/fxa/tree/main/packages/fxa-settings)

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5232)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
