### ISSUE TITLE
Fix/remove the Storybook for fxa-admin-panel

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13121]
## Description

Per a recent storybook build: https://storage.googleapis.com/mozilla-storybooks-fxa/commits/c2448f1ebfe052c659f3d6ddea14a4449ed5e34d/index.html

### Steps to reproduce

1. Click link above.
2. Select [fxa-admin-panel](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/c2448f1ebfe052c659f3d6ddea14a4449ed5e34d/fxa-admin-panel/index.html)

### Expected result

Stories.

### Actual result

> Oh no! Your Storybook is empty. Possible reasons why:
> - The glob specified in main.js isn't correct.
> - No stories are defined in your story files.

And 

> #### No Preview
> Sorry, but you either have no stories or none are selected somehow.
>
> Please check the Storybook config.
> Try reloading the page.
> If the problem persists, check the browser console, or the terminal you've run Storybook from.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5233)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
