### ISSUE TITLE
[subplat] Fix paypal processor "startup" count

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13134]
The paypal processor script needs to obtain a lock to run.  However, we increment the “startup” count even when the script cannot obtain the lock to process anything.  I think the count should reflect a successful startup, not an attempted startup.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5238)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
