### ISSUE TITLE
Upgrade ioredis to >=5.0.6

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13137]
Dependabot tried at [https://github.com/mozilla/fxa/pull/13131](https://github.com/mozilla/fxa/pull/13131|smart-link)  but lots of errors

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5240)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
