### ISSUE TITLE
Upgrade postcss-loader from 4.2.0 to 7.0.0

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13133]
Dependabot tried at [https://github.com/mozilla/fxa/pull/13005](https://github.com/mozilla/fxa/pull/13005|smart-link) but it looks like we’ve got some failing tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5237)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
