### ISSUE TITLE
[Apple auth] The user is not able to log in to Pocket via Apple auth

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13143]
**Build:**

Stage [Train 233]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

N/A

**Steps to reproduce:**

1. Navigate to [https://fxa-staging.web.readitlater.com/](https://fxa-staging.web.readitlater.com/|smart-link) and click Log in.
1. Click “Continue with Firefox.“
1. Append the flag: &forceExperiment=thirdPartyAuth&forceExperimentGroup=google to the URL and press Enter.
1. Click “Continue with Apple“.
1. Complete the flow to log in.

**Actual result:**

The user is redirected to “Enter your email page”.

**Expected result:**

The user is logged in to Pocket.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5241)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24646">wrong redirection Apple.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
