### ISSUE TITLE
[config-ui][webhook-handler] Create webhook handler for Drive API

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13158]
**Background**

We’ll be using the [Google Drive Push notifications](https://developers.google.com/drive/api/guides/push) to keep track of changes to files.

**Requirements**

Create a webhook handler in `fxa-auth-server`.

* Create hapi route
* Create handler

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5247)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
