### ISSUE TITLE
[config-ui] Create template file

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13157]
**Background**

Create template files that can be used by relying parties to populate the necessary metadata.

**Requirement**

Create template files for the following configs.

* Product
* Plan
* Locale

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5246)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
