### ISSUE TITLE
[config-ui][file-handler] Create file handler module

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13159]
**Background**

Create a new module for all logic necessary to handle, and process files from Google Drive.

**Requirement**

* Create skeleton class with constructor
* Constructor to initialize the following
  * `Config`
  * `PaymentConfigManager`
  * `Log`
* Add test file
* When is this initialized?
  * Will PaymentConfigManager be initialized? (Probably not)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5248)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
