### ISSUE TITLE
[config-ui][file-handler] Get file from Google Drive

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13161]
**Background**

Once a file has been changed in Google Drive, we need to retrieve the file to process it.

**Requirement**

* Add method to File handler module to download file from Google Drive

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5250)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
