### ISSUE TITLE
[config-ui][webhook-handler] Filter Drive API push notifications

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13167]
**Background**

Watching or changes in a shared folder might report changes to files that should not be processed. These should be filtered out before requesting the file.

**Requirement**

* Filter out changes where files do not follow the naming convention `prod_*/plan_*/price_*`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5255)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
