### ISSUE TITLE
Admin panel: display loading/error consistently, always display error details

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13160]
We can be more consistent with displaying our loading/error messages. We might be able to use a shared `Result` component [like here](https://github.com/mozilla/fxa/pull/13123/files#diff-7903f9dd11cb9375914cebfd313b7301e4d6f120ffa27ab3fdde58e9c1a90289R36) that returns loading/error or the result data/children.

More importantly, it would be very handy to display all error details since this is an internal tool which prevents us from having to open the Network panel and dig around to see error output. We could place this in a `<details>` element so we can click a caret if we want to see the fulloutput (or not - also fine to just display it IMO).

I believe we can handily mostly copy what was done in Experimenter’s ApolloErrorAlert: [https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/ApolloErrorAlert/index.tsx](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/ApolloErrorAlert/index.tsx|smart-link) 

(p.s. look back in history to find the stories done for that component, Storybook was retired from experimenter but there was a .stories file we can copy from)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5249)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
