### ISSUE TITLE
Add ErrorBoundary to fxa-admin-panel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13168]
[https://reactjs.org/docs/error-boundaries.html](https://reactjs.org/docs/error-boundaries.html|smart-link) 

We should have an error boundary in admin-panel’s front-end for slightly easier debugging during development. Test output is very long and complains/asks for one when an error occurs that would hit a global app boundary since it’s conventional and best practice to handle any errors bubbling up there, and (I’m not 100% on this without double checking but I think it’s true) when something fails to render properly, the entire page is blank instead of showing the stacktrace on the page.

If we want to report admin-panel bugs to Sentry, we can use the one from `fxa-shared`. Otherwise, we should just create a new one that doesn’t report to Sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5256)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage: Let’s use the one in fxa-shared

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
