### ISSUE TITLE
[config-ui][file-handler] Parse file to Plan base config

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13162]
**Background**

Relying parties will complete a Google Sheet with the necessary Plan configuration.

**Requirement**

This task will be parse the Google Sheet data into the PlanConfig type.

**Assumptions**

The ProductConfig parser is done.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5252)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
