### ISSUE TITLE
Admin panel HTML (tables/lists) + CSS (better shared classes) tweaks + shared utils 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13164]
We’ve got a lot of minor HTML/CSS as well as UX cleanup we can do in the admin panel.

When the tool was first created, it made sense semantically to use `ul`/ `li` s for result displays, though it also would have made sense then to use tables. Now, we've now got a mix of unordered lists and tables throughout, when it probably just makes sense to turn them all into tables at this point for consistency.

HTML/CSS cleanup:

* Refactor unordered lists to tables where appropriate, tweak/cleanup related `account-li` classes
* AccountSearch could be divided into section tags
* ResultTableRow should have a header
* Set a padding-right on tables instead of widths
* Consider applying `result-grey` class where it seems appropriate. Do we want all null/undefined/empty string values to have this?
  * Also: `redirectURI` in "relying parties" can be an empty string. We should update the type (if applicable) but display "_(empty string)_" like we are for `imageURI`
* Remove extraneous text-grey-600 classes from page containers and consider removing testids in favor of React fragments and testing for something else to check that the component rendered. Reference PageRelyingParties tests
* Page headers could have their own class

UX inconsistencies or places that could use a shared function:

* If we like our booleans to display an English-friendly “yes” or “no” instead of `true`/ `false`, like we are for most of them, we could create a helper function for this. Also make it consistent on whether or not we want table heads to have a question mark for booleans
* We could use a helper function for dates, right now we just export from Account component

Also rename pages to begin with `Page`. (Prefer `git mv` to rename to ensure the history is retained)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5253)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
