### ISSUE TITLE
[config-ui][file-handler] Parse file to Product base config

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13163]
**Background**

Relying parties will complete a Google Sheet with the necessary Product configuration.

**Requirement**

This task will be parse the Google Sheet data into the ProductConfig type.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5251)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
