### ISSUE TITLE
Admin panel: address AccountSearch tests that have a .skip (flaky tests)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13165]
Two test in the admin-panel AccountSearch are skipped due to flakiness (according to the comment above them).

We might be able to refer to RelyingParty tests to make these less flaky.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5254)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
