### ISSUE TITLE
[config-ui][file-handler] Additional Validation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13177]
**Background**

In addition to the existing `joi` validations, before processing a file, some basic validation should be performed.

**Requirements**

Add a method, in the file handler module, that performs some additional validations listed below.

* Ensure the Product/Plan ID of the file, corresponds to the correct RP.
  * Compare the file name to the folder name

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5267)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
