### ISSUE TITLE
Grant SysEng Access to FxA GCP (staging)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13176]
_To enable development and design of the system for streaming FxA's subscription data-events to CTMS  (relevant to marketing's interests)._

As a engineer from system's engineering, 
I would like to acquire access to the FxA GCP staging environment,
So that I can view the schema and determine a sustainable solution.

SysEng Team members requesting access:

* @grahamalama (Graham Beckley: [+gbeckley@mozilla.com+](mailto:gbeckley@mozilla.com))
* bsieber (Bryan Sieber: [bsieber@mozilla.com](mailto:bsieber@mozilla.com)) (GCS Firestore/Export-Import)

Requesting Permissions/Service Account for:

* Cloud Function
* PubSub
* FireStore (Import/Export)
* GCS Buckets

- - -
Slack thread on #subscription-platform:
[https://mozilla.slack.com/archives/CG0AJ6E77/p1632940039334800](https://mozilla.slack.com/archives/CG0AJ6E77/p1632940039334800)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5268)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
