### ISSUE TITLE
[config-ui][file-handler] Write Product config to Firestore

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13171]
**Background**

After parsing the data from Google Drive, write the data to Firestore.

**Requirement**

* Use `PaymentConfigManager` to write the Product config to Firestore

**Assumptions**

Data to write to Firestore is already parsed into `ProductConfig` type

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5258)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
