### ISSUE TITLE
Combine DialogMessage and Modal components

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13188]
`DialogMessage` and `Modal` can become the same component.

(Initially a part of [https://mozilla-hub.atlassian.net/browse/FXA-2463](https://mozilla-hub.atlassian.net/browse/FXA-2463|smart-link), however it is its own task)

After completion of [https://mozilla-hub.atlassian.net/browse/FXA-5604](https://mozilla-hub.atlassian.net/browse/FXA-5604|smart-link) 

* Move hooks from fxa-settings to fxa-react
* Combine DialogMessage and Modal in new component in fxa-react
* Update components that were using DialogMessage/Modal
* Add updated Storybook to new Modal component

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5273)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Lisa Chan to break up further, likely to add to the tailwind epic.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
