### ISSUE TITLE
[config-ui][file-handler] Parse file to Plan base config

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13187]
**Background**

Relying parties will complete a Google Sheet with the necessary Locales configuration for Products and Plans.

**Requirement**

This task will be parse the Google Sheet data in the Locales tab, into the type defined for locales in ProductConfig and PlanConfig types.

**Assumptions**

The ProductConfig parser is done.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5271)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
