### ISSUE TITLE
Review mozilla-fxa/jquery-modal depdendency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13194]
We include this:

[https://github.com/mozilla-fxa/jquery-modal](https://github.com/mozilla-fxa/jquery-modal|smart-link) 

But there is a newer upstream version.  Let’s consider using it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5279)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This got reverted in https://github.com/mozilla/fxa/commit/14d71f9a8e52c4f283d7c76b72527acb6cb0a240 ( https://github.com/mozilla/fxa/commit/14d71f9a8e52c4f283d7c76b72527acb6cb0a240|smart-link ) .  That links to the bug it caused

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
