### ISSUE TITLE
Add git trigger to repo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13217]
Add github action to PRs to run validation on JSON file.

Determine whether the script is in the repo and run in github vs an endpoint.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5292)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Github action exists. This ticket is to plug the script in to load the json file into firestore.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
