### ISSUE TITLE
Currency codes for subscription plans are not ISO 4216 compliant

### ISSUE THREAD

**Issue by flozia** [mozilla/fxa#13238]
## Description

The subscription plans that are being returned by the subscriptions endpoint [`/oauth/subscriptions/plans`](https://api-accounts.stage.mozaws.net/documentation#/Subscriptions/getOauthSubscriptionsPlans) have a property `currency` with a currency code as value. The currency codes are currently in lowercase. In order to be compliant with [ISO 4216](https://www.iso.org/iso-4217-currency-codes.html) they are expected to be uppercase.

### Steps to reproduce

Fetch plans from the subscriptions endpoint [`/oauth/subscriptions/plans`](https://api-accounts.stage.mozaws.net/documentation#/Subscriptions/getOauthSubscriptionsPlans).

### Expected result

Currency codes are uppercase.

### Actual result

Currency codes are lowercase.

### Environment

Swagger on https://api-accounts.stage.mozaws.net/documentation#/Subscriptions/getOauthSubscriptionsPlans

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5299)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Florian Zia we are not doing any transformation on what we receive from stripe; is there a specific need to have this ISO formatted?

**Comment by flozia** [comment]
Thank you for you reply @IvoJP. Currently there is no specific need and since there is no transformation no that value I’ll close this issue.
