### ISSUE TITLE
[FxA-Settings]"Password reset successfully" green message displayed when the reset process is not completed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13234]
**Build:**

Stage [Train 234]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user has recovery key enabled.

The user is on the Sign in page.

**Steps to reproduce:**

1. Click “Forgot password?” link.
1. Enter your email in the “Reset password” form and click “Begin reset” button.
1. Go to your inbox, open “Reset your password” email and click “Create new password“ button.
1. Click the “Don’t have a recovery key?“ link and then click the “Remember password? Sign in“ button.
1. Enter the password and sign back in.
1. Observe the green message displayed.

**Actual result:**

"Password reset successfully" green message is displayed when the password was not reset anymore.

**Expected result:**

"Password reset successfully" green message is displayed only when the user changes the pwd and completes the reset process.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5298)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24935">pwd reset successfully displayed.gif</a>

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Can you please confirm if this is prod as well?

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Hi Lisa Chan I confirm this occurs in Production too.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
