### ISSUE TITLE
Add ESLint configs for nestjs projects

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13241]
> Do you mind filing a follow up issue for possibly that `eslint-plugin-nestjs` that you found + to have custom shared configs for each project type as you also said in Slack? Would be awesome to do that after we get that style guide finalized and have a list of available fxa plugins/project types. 😎
> &mdash; _Originally posted by @LZoog in https://github.com/mozilla/fxa/pull/13112#pullrequestreview-1002944877_

Per a quick grep, it looks like we have 5 projects which use [NestJS](https://nestjs.com/):

```sh
git grep  -l "nestjs" packages/*/package.json | cat

packages/fxa-admin-server/package.json
packages/fxa-event-broker/package.json
packages/fxa-graphql-api/package.json
packages/fxa-shared/package.json
packages/fxa-support-panel/package.json
```

I found a few potential ESLint plugins on npm, but haven't had a lot of success getting them set up locally; but (a) I was on a heavily modified branch, and (b) I'm a simpleton:

| NAME | VERSION | LAST PUBLISHED | DOWNLOADS<br/>(per week)
|:----|:----:|----:|----:|
| [eslint-plugin-nestjs](https://www.npmjs.com/package/eslint-plugin-nestjs) | 1.2.3 | 4 years ago | 13,723
| [@darraghor/eslint-plugin-nestjs-typed](https://www.npmjs.com/package/@darraghor/eslint-plugin-nestjs-typed) | 3.10.1 | 23 days ago | 2,615
| [@moneteam/eslint-plugin-nestjs](https://www.npmjs.com/package/@moneteam/eslint-plugin-nestjs) | 1.6.0 | 2 months ago | 244
| [@greguintow/eslint-plugin-nestjs-typed](https://www.npmjs.com/package/@greguintow/eslint-plugin-nestjs-typed) | 1.3.2 | 11 days ago | 141
| [eslint-plugin-nestjs-framework](https://www.npmjs.com/package/eslint-plugin-nestjs-framework) | 0.0.6 | a year ago | 85
| [@authing/eslint-plugin-nestjs](https://www.npmjs.com/package/@authing/eslint-plugin-nestjs) | 0.0.2 | 4 months ago | 3
| [eslint-plugin-authing-nestjs](https://www.npmjs.com/package/eslint-plugin-authing-nestjs) | 1.0.16 | 2 months ago | 2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5301)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
