### ISSUE TITLE
[subplat] Add tests confirming modal successfully opens/closes for Cancel/Resubscribe buttons

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13256]
This issue was discovered after upgrading jquery modal.

The following tests should be added, confirming whether the modal:

* opens on Cancel (subscription)
* closes after confirming cancelled subscription
* opens on Resubscribe
* closes after resubscribing

Additional considerations:

* the modal dialog box parent (semi-transparent overlay) “closes” the modal when clicked (same action if they were to click the the ‘close icon’), but it should not display at all if the dialog box fails to display
* make sure product is cancelled/resubscribed to and email is sent only after modal is displayed successfully (i.e. user has been informed)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5309)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
