### ISSUE TITLE
Document how to Sync locally/on staging (dev-launcher)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13251]
We don’t have any docs on how to go through the Sync flow locally in the ecosystem-platform, except for Firefox for iOS.

We should have a small page with info about running `npm start` in fxa-dev-launcher (locally + for staging) and going through the Sync signup flow.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5305)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
