### ISSUE TITLE
(sentry) TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13253]
Sentry Issue: [FXA-CONTENT-YB](https://sentry.io/organizations/mozilla/issues/3279031594/?referrer=jira_integration)

```
TypeError: NetworkError when attempting to fetch resource.
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5306)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
