### ISSUE TITLE
Clarify the must-change-password.ts script usage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13269]
We have a script: [https://github.com/mozilla/fxa/blob/main/packages/fxa-graphql-api/src/scripts/must-change-password.ts](https://github.com/mozilla/fxa/blob/main/packages/fxa-graphql-api/src/scripts/must-change-password.ts|smart-link) 

It looks like it was modified to accept plain text instead of JSON, but the examples at the top were never updated and [~accountid:60c368e4d5dde80071a4207c] and I can’t figure out how to use it.  Please either adjust the comments at the top about how to use it, or change it to accept a plain text file of emails or uids separated by newlines.  (You can differentiate emails from UIDs because UIDs won’t have an `@` in them).

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5315)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
