### ISSUE TITLE
Fraudulent Account Deletion: Update current verify your account email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13264]
To the Existing Verification email, add text about how long the user has to verify their account ( this will be 16 days)

[~accountid:60482f83bfef95006bc8ad2d]  let me know if you want specific language here

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5311)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Vesta Zare do you have bandwidth prior to next Wednesday (Aug 3) to work with Content to update the verbiage in the Verify email per the request in this ticket? Storybook: https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-auth-server/index.html?path=/story/fxa-emails-templates-verify--verify-email ( https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-auth-server/index.html?path=/story/fxa-emails-templates-verify--verify-email|smart-link )

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

I’ll work with Content Design to have this ready before the next sprint. Chelsea Lewis did this requirement come from legal or the support team? Any context you could share would be helpful.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

I’ll share in our Slack, thanks Vesta!

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Content will need to be added to the following emails:

  1. verify
  2. verificationReminderFirst
  3. verificationReminderSecond

**Comment by data-sync-user** [comment]
➤ Vesta Zare commented:

Thank you so much Chelsea Lewis

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
