### ISSUE TITLE
Prettier isn't prettying all the files

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13271]
## Description

Noticed some files don't match the current Prettier configuration, so I did some digging.

### Steps to reproduce

This weirdly hideous command will lint all known files to Git, ignoring files it cannot infer a parser for, and then output the [231] files which are unformatted (per the global _dev/.prettierrc config file).

```sh
npx prettier `git ls-files` --list-different --ignore-unknown --config=_dev/.prettierrc > unpretty.txt

[error] packages/fxa-auth-server/test/.eslintrc: SyntaxError: Unexpected token (1:8)
[error] > 1 | plugins:
[error]     |        ^
[error]   2 |   - fxa
[error]   3 | extends: ../.eslintrc
[error]   4 |

[error] packages/fxa-support-panel/views/index.hbs: TypeError: Cannot read properties of undefined (reading 'loc')
[error]     at l.BlockStatement (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/parser-glimmer.js:1:135550)
[error]     at l.acceptNode (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/parser-glimmer.js:1:134077)
[error]     at l.Program (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/parser-glimmer.js:1:135040)
[error]     at l.acceptTemplate (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/parser-glimmer.js:1:134040)
[error]     at h (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/parser-glimmer.js:1:147690)
[error]     at Object.parse (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/parser-glimmer.js:1:174851)
[error]     at Object.parse$a [as parse] (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/index.js:13652:19)
[error]     at coreFormat (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/index.js:15183:16)
[error]     at formatWithCursor$1 (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/index.js:15423:14)
[error]     at Object.formatWithCursor (/Volumes/Dev/github/mozilla/fxa/node_modules/prettier/index.js:60171:12)
```

Interestingly, there were seemingly two "fatal" errors, although one of which should be fixed via a recent PR which overhauled .eslintrc* config files and converted the lone YAML config to JSON.
Unclear on whether the packages/fxa-support-panel/views/index.hbs error is a template issue, or Prettier issue, although I think I did reduce it down to something about this syntax:

```hbs
          {{#emailVerified}}yes{{/emailVerified}}
          {{^emailVerified}}no{{/emailVerified}}
``` 

The 231 files are too many to list here, but here's a rough summary:

```js
Map(12) {
  '.css' => 1,
  '.handlebars' => 1,
  '.html' => 12,
  '.js' => 103,
  '.json' => 31,
  '.md' => 9,
  '.mjs' => 3,
  '.scss' => 20,
  '.ts' => 18,
  '.tsx' => 11,
  '.yaml' => 2,
  '.yml' => 18,
}
```

```js
// unprettier_summary.mjs
import fs from "node:fs/promises";
import path from "node:path";

let files = await fs.readFile("./unpretty.txt", "utf-8");
files = files.trim().split("\n");

const extMap = new Map();
for (const f of files) {
  const ext = path.extname(f);
  const count = extMap.get(ext) || 0;
  extMap.set(ext, count + 1);
}
extMap.delete("");

console.log(extMap);
```

We could also tweak the root .prettierignore file and add a few more paths/globs if we wanted to ignore CODE_OF_CONDUCT.md files or "docs/adr", or Ansible configs in "packages/123done/ansible", etc.

### Expected result

All files should be prettiered (consistency is fun, but it's also a pretty passable basic linter for HTML errors and mismatched tags), although I think currently the prettier hook gets called on the following files/globs, per ./package.json:

```js
  "lint-staged": {
    "*.js": [ "prettier --config _dev/.prettierrc --write", ... ],
    "*.{ts,tsx}": [ "prettier --config _dev/.prettierrc --write" ],
    "*.css": [ "prettier --config _dev/.prettierrc --write" ],
    "*.md": [ "prettier --config _dev/.prettierrc --write" ]
  },
```

### Actual result

If Prettier is only called on staged/modified files, many files will be unprettied if they aren't modified. Not a big deal, but might be nice to throw into the backlog for when we get to this Style Guide work and globally reformat all the things.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5317)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
