### ISSUE TITLE
[a11y] use `title` and `aria-label`

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13282]
Re: using `title` _and_ `aria-label` attributes:

> We probably want to do this all around then. I've just been using `title` in a lot of places (instead of both) since when I tested with VO on macOS on FF it reads it, but so long as the main screen readers don't read this twice, SGTM. 👍

_Originally posted by @LZoog in https://github.com/mozilla/fxa/pull/13230#discussion_r895788940_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5319)

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

If the work for this seems to be more than 2 points, raise it with the team, and lets break it out into multiple tickets.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
