### ISSUE TITLE
Remove sentry filters

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13288]
```
*Invalid token*
*Invalid or expired verification code*
*Requested scopes are not allowed*
*Invalid unblock code*
*Unknown code*
*Unknown account*
*Unknown customer*
*Client has sent too many requests*
```

Here:  [https://sentry.io/settings/mozilla/projects/fxa-auth/filters/data-filters/](https://sentry.io/settings/mozilla/projects/fxa-auth/filters/data-filters/)

This depends on Dan’s patch to filter these in the code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5326)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
