### ISSUE TITLE
3d Secure on success after fail throws general application error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13297]
If using 3d secure, and the first confirmation is failed, and the second time through a success is used, a general application error happens. The modal for this cannot be dismissed, and there wasn’t actually an error setting up the subscription (email is sent with invoice, etc).

Sentry error from local testing of this:

[https://sentry.io/organizations/mozilla/issues/3355427474/?project=6231072&query=is%3Aunresolved](https://sentry.io/organizations/mozilla/issues/3355427474/?project=6231072&query=is%3Aunresolved)

**Expected Result**

Should display the success modal.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5331)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
