### ISSUE TITLE
Deploying fr translations

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/fxa#1329]
Hi,

Can someone update https://latest.dev.lcip.org (or stable) with the latest translations please? I would like to QA the French trailhead translations, but most are currently missing

Thanks!

**Comment by vladikoff** [comment]
b7e462652bf87e279cdaa7196cfef20c3de256ad should go on latest.dev soon, which should hopefully have the latest translations!

**Comment by TheoChevalier** [comment]
I can confirm, thanks @vladikoff & team!

**Comment by vladikoff** [comment]
:) thanks to @jbuck as well
