### ISSUE TITLE
Minify all the SVGs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13299]
> you might wanna run the svg through https://jakearchibald.github.io/svgomg/ and see if it could be optmized.

_Originally posted by @vbudhram in https://github.com/mozilla/fxa/pull/13262#pullrequestreview-1009455672_

---

I ran _all_ the SVGs through `svgo` via <kbd>npx svgo -f packages -r</kbd> and built a little reporter/formatter and looks like we can shave off about 137 KB of SVG-ness (note a huge difference, and only about 5.4% of the total 2.5MB of SVG assets).

```
Before: 2,531.9 KiB; After: 2,394.5 KiB; Diff: -137.3 KiB
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5333)

**Comment by pdehaan** [comment]
Here was my little reporter (where the svgo.out.txt was the results from the <kbd>svgo -f packages -r</kbd>):

```js
import fs from "node:fs/promises";

const results = { before: 0, after: 0 };

const content = await fs.readFile("./svgo.out.txt", "utf-8");

const files = content
  .trim()
  .split("\n\n")
  .map((file) => file.split("\n"));

for (const file of files) {
  const [name, , stats] = file;
  const [before, , after] = stats.split(/\s[-=]\s/g);
  if (after) {
    results.before += parseFloat(before, 10);
    results.after += parseFloat(after, 10);
  }
}

stats(results);

function stats(obj) {
  const before = fmt(obj.before);
  const after = fmt(obj.after);
  const diff = fmt(obj.after - obj.before);
  console.log(`Before: ${before}; After: ${after}; Diff: ${diff}`);
}

function fmt(num, suffix = "KiB") {
  const value = Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(
    num
  );
  return `${value} ${suffix}`;
}
```

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
