### ISSUE TITLE
Skip functional tests in cases where they are not beneficial.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13313]
Many of our test suites will skip execution of tests if nothing has changed that would necessitate the test suite be run. However, it appears that our functional-tests test suite does not do this. There are cases, e.g. a PR that only makes changes to the admin panel, where these tests offer no benefit and therefore could be skipped.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5337)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
