### ISSUE TITLE
Onboard RPs onto new private repo approach

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13318]
**Requirements**

* Update Ecosystem docs with instructions on how to update Product Config
* Host an informational session. (Maybe use SubPlat office hours for this)
* Create a video demonstrating how to update Product Config

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5341)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
