### ISSUE TITLE
Update POST `/oauth/authorization` to accept response type `id_token`

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#13316]
To help better support Proxy tracker requirements, we need to add the ability for a client to complete a login and get a valid JWT. This process does not require the RP to make a request to token server and could be handled on the client side only.

This also only support authentication (valid user) and not authorization (user has access).

Requirements:
* SHOULD return `id_token` when oauth `response_type=id_token`
* SHOULD NOT return authorization code, access token, or access token type
* If `redirect_uri` SHOULD redirect
* MAY include state param
  * I think we should try to support this if it isn't already
* SHOULD use specified `response_mode` (fragment encoding is default)

Ref: https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#id_token

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5339)

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Vijay Budhram , please split into smaller tasks.

**Comment by vbudhram** [comment]
The other part of this task is https://github.com/mozilla/fxa/issues/13436.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
