### ISSUE TITLE
Enable cross account protection in Google console

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13319]
This is an ops task enable cross account protection in the Google console. We will need to specific an endpoint for them to POST account events too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5343)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
