### ISSUE TITLE
(sentry) Error: Message failed: 554 Transaction failed: Invalid domain name: 'gmail.com.0927168644'.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13326]
Check regex

Should not be creating 500 error

Sentry Issue: [FXA-AUTH-6S](https://sentry.io/organizations/mozilla/issues/3361348580/?referrer=jira_integration)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5350)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
