### ISSUE TITLE
(sentry) Error: Can't send mail - all recipients were rejected: 501 Invalid RCPT TO address provided

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13325]
* Noticed there is an encoding around umlaut.

Sentry Issue: [FXA-AUTH-6Q](https://sentry.io/organizations/mozilla/issues/3357173981/?referrer=jira_integration)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5349)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
