### ISSUE TITLE
Upgrade Mailparser 0.6.1 to 3.5+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13327]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/12794](https://github.com/mozilla/fxa/pull/12794|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5351)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
