### ISSUE TITLE
Support token revoked event

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13323]
|`https://schemas.openid.net/secevent/oauth/event-type/tokens-revoked`| |*Required*: If the token is for Google Sign-in, terminate their currently open sessions. Additionally, you may want to suggest to the user to set up an alternate sign-in method.
**Suggested**: If the token is for access to other Google APIs, delete any of the user's OAuth tokens you have stored.|

This one will be tricky since we don’t currently associate our sessions with a Google session.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5347)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
