### ISSUE TITLE
Support account deleted event

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13321]
|----|----|----|
|`https://schemas.openid.net/secevent/risc/event-type/account-purged`| |**Suggested**: Delete the user's account or provide them with an alternative sign-in method.|

I’m not sure we should delete the associated FxA account in this case? But we should at a minimum remove the linked account in the database.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5345)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
