### ISSUE TITLE
Support test verification event

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13322]
|----|----|----|
|`https://schemas.openid.net/secevent/risc/event-type/verification`|state=state|**Suggested**: Log that a test token was received.|

We should implment this event first to help us verify that things are working as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5346)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
