### ISSUE TITLE
Support account disabled event

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13320]
|`https://schemas.openid.net/secevent/risc/event-type/account-disabled`|`reason=hijacking`,
`reason=bulk-account`|*Required*: If the reason the account was disabled was `hijacking`, re-secure the user's account by ending their currently open sessions.
**Suggested**: If the reason the account was disabled was `bulk-account`, analyze the user's activity on your service and determine appropriate follow-up actions.
**Suggested**: If no reason was provided, disable Google Sign-in for the user and disable account recovery using the email address associated with the user's Google Account (usually, but not necessarily, a Gmail account). Offer the user an alternate sign-in method.|

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5344)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
