### ISSUE TITLE
[subplat] Do not perform customs check on support ticket request from RPs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13337]
Our support ticket endpoint allows two authentication strategies, one being a shared secret to allow an RP to create a support ticket.  Since the RP is submitting tickets for its customers, we should not apply the standard customs server rate limits.  Let’s skip the custom server check when the auth strategy is a shared secret.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5353)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Per Ben: The customs server can have configurable rules for particular identifiers. An ops change could skip this.

If we wanted to turn this off for all IPs, that could also be done in config.

It seems like it’d be a good idea to control whether or not this check occurs via config, to avoid the possible scenario where someone finds this URL and tries to abuse it if we remove the check entirely.

This is already possible via config. Jon Buckley or Dustin Lactin is this something you can help us with?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I’m skeptical that we want to bypass all rate limiting for RPs. In fact, integrating with us comes with the expectation of respecting back-off headers ( https://mozilla.github.io/ecosystem-platform/relying-parties/reference/using-apis ) which is a good thing.  Adding the RP that was running into this to the allowlist is a band-aid for not having more flexibility in the customs detection and I think the real fix is there:  Have more knobs to turn in customs for trusted entities to allow higher thresholds.  I don’t think we should skip customs checks altogether.  So, I think this should be wontfixed and until we get more options for fine tuning adding the question to your onboarding checklist is fine.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
