### ISSUE TITLE
Upgrade @type-cacheable/ioredis-adapter from 10.0.4 to 11.0.1+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13335]
Failed dependabot PR: [https://github.com/mozilla/fxa/pull/13210](https://github.com/mozilla/fxa/pull/13210|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5355)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
