### ISSUE TITLE
Upgrade graphql-upload from 13.0.0 to 15.0.1+

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13336]
Failed dependabot PR:

[https://github.com/mozilla/fxa/pull/13233](https://github.com/mozilla/fxa/pull/13233|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5354)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
