### ISSUE TITLE
Admin Panel: Add the ability for support to unsubscribe users from mailing lists/newsletters

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13342]
Support responds to requests as well as privacy requests to be removed from mailing lists/newsletters. It would be helpful to have the functionality on the admin panel to be able to unsubscribe users from all mailing lists including Pocket.

A single button press on the admin panel would allow agents to unsubscribe an account from newsletters/mailing lists and, optimally, populate the reason as “DSAR Customer Request”

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5358)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25616">image-20220627-153522.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Paul McLanahan Do you know of an easy way to do this?  Or does this functionality already exist in basket that we could hook into?

The admin panel is behind some restricted network access so I don’t know that we could make the requests from the server, but we could embed a link to basket and the support agents could open it in a new window.

**Comment by data-sync-user** [comment]
➤ Paul McLanahan commented:

Isn’t there already a link in the admin to the users email preferences? They can unsubscribe from everything via the page that they get to from there. 

The Pocket newsletter is handeled via completely separate systems unfortunately, and basket isn’t able to affect change for those.

It might be technically possible for you to submit a call that would request an unsubscribe from all directly from FxA admin, but I think the email team would need to be involved in that decision since the user currently gets to see which subscriptions they have before deciding to unsubscribe from everything. 

Perhaps better wording or UX would help users who aren’t finding the way we currently provide to unsubscribe via the FxA admin or the links in their newsletter emails?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

!image-20220627-153522.png|width=264,height=334!

Yes, there is a direct link from the user’s setting page to basket.  This issue is about a new administrative interface that the support team is working into their flow which doesn’t have any links to basket.  I’m not sure the scenarios where support runs into the unsubscribe requests so I’ll leave it for Joseph Anthony Cuevas to reply about better UX/etc.  Thanks

**Comment by data-sync-user** [comment]
➤ Paul McLanahan commented:

Oh! I understand now. I didn’t realize this was about the ability for support staff to be able to unsubscribe on behalf of users. That is different. We used to have support personnel with the ability to login to Salesforce to handle such things, but now that we don’t use Salesforce we don’t really have such an interface. Perhaps the CTMS team has something like this planned though? Stephen Hood do you know?

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Hi Paul McLanahan These are the most common requests support receives primarily as data subject access requests which relate to GDPR and CCPA compliance. As a result, support needs the ability to act on these requests securely. Currently, the team has been generating a token ID via an application called CTSM and pasting it into a template URL that loads the communication preferences page for the specific user. This doesn’t seem secure since it permits access to the users other communication preferences. Ideally we would like a one-click solution baked into the Admin Panel that would allow us to unsubscribe users securely and, expeditiously, since these are also time sensitive requests. Happy to discuss further if needed!

**Comment by data-sync-user** [comment]
➤ Stephen Hood commented:

Regarding security: given that URL we send to users is already unsecured/unauthenticated, and that Basket has worked this way in production for a number of years, does Support truly require a secure method?

Regarding automation: certainly, the current method is a bit of a pain and doesn’t scale well (since you have to get the user’s Basket token, paste it into the URL, navigate to the page, and then unsubscribe-all. But I would think this current method could be automated via a simple Zendesk app?

If an automated and secure channel is indeed required, then that probably looks like a new CTMS API endpoint that accepts a user identifier and executes the unsubscribe action programmatically, plus a Zendesk app that calls that API. CTMS does not currently provide such an API, so this would require work from the IT team to enhance the system.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is there a way we (FxA) can get or generate a user’s token from their email address?

**Comment by data-sync-user** [comment]
➤ Paul McLanahan commented:

You can request it from basket using an API Key that we can give you. The token is a UUID4 so it can’t be calculated from the email. 

https://basket.mozilla.org/news/lookup-user/?email=dude%40example.com&api-key=<API_KEY>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
