### ISSUE TITLE
Remove unused depedencies from admin panel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13345]
depcheck indicated the following were unused. remove them and validate that it doesn’t cause a regression.

Unused dependencies

* @emotion/react
* @sentry/browser

Unused devDependencies
* @storybook/addon-actions
* @storybook/addon-links
* @storybook/addons
* @tailwindcss/postcss7-compat
* @testing-library/dom
* @testing-library/user-event
* @types/babel__core
* @types/eslint
* @types/jest
* @types/webpack
* babel-loader
* esbuild
* esbuild-register
* eslint-plugin-fxa
* jest-watch-typeahead
* webpack

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5360)

**Comment by pdehaan** [comment]
I was looking into [@tailwindcss/postcss7-compat](https://www.npmjs.com/package/@tailwindcss/postcss7-compat) and
https://v2.tailwindcss.com/docs/guides/create-react-app#install-tailwind-via-npm is one of the few references to "tailwindcss@npm:@tailwindcss/postcss7-compat" I can find.

Which lead me to https://create-react-app.dev/docs/updating-to-new-releases/ which points you towards updating and migrating react-scripts; https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md#migrating-from-40x-to-500

I think if we update to Create React App v5.0+, we can maybe drop the @tailwindcss/postcss7-compat dependency.
