### ISSUE TITLE
Admin Panel client side never hooked up to sentry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13343]
While looking for unused dependencies it became apparent that @sentry/browser was never actually used in the admin panel. (The @sentry/node was being used however.) This should be configured for the admin panel.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5359)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
