### ISSUE TITLE
Upgrade jest from 27.5.1 to 28.1.1 (fxa-admin-panel)  (dev) (X)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13359]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5376)

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Does not upgrade cleanly. Issue importing typescript from fxa-shared.

FAIL server/lib/csp.test.ts
  ● Test suite failed to run

    EISDIR: illegal operation on a directory, read

       6 | import fs from 'fs';
       7 | import path from 'path';
    >  8 | import { GuardConfig } from 'fxa-shared/guards';
         | ^
       9 |
      10 | convict.addFormats(require('convict-format-with-moment'));
      11 | convict.addFormats(require('convict-format-with-validator'));

      at Runtime.readFile (../../../node_modules/jest/node_modules/jest-runtime/build/index.js:2574:21)
      at Object.<anonymous> (config/index.ts:8:1)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
