### ISSUE TITLE
Upgrade react-scripts from ^4.0.3 to ^5.0.1 (fxa-admin-panel) (x)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13355]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5368)

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Fails build after upgrading.

➜  fxa git:(FXA-5368-upgrade-react-scripts-from-4-0-3-to-5-0-1-fxa-admin-panel) ✗ yarn workspace fxa-admin-panel build

> fxa-admin-panel@1.235.1 build-postcss
> postcss src/styles/tailwind.css -o src/styles/tailwind.out.css

Extracting externally imported component paths...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

warn - The `conservative` purge mode will be removed in Tailwind 2.0.
warn - Please switch to the new `layers` mode instead.
(node:81036) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./configs/" in the "exports" field module resolution of the package at /Users/dschomburg/Documents/code/mozilla/fxa/node_modules/fxa-react/package.json.
Update this package.json to use a subpath pattern like "./configs/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/dschomburg/Documents/code/mozilla/fxa/packages/fxa-react/configs/rescripts.js:55
    throw new Error(
    ^

Error: Could not find the Webpack loader to include additional JS import paths.
       This script may need updating if CRA has changed its base config.
    at permitAdditionalJSImports (/Users/dschomburg/Documents/code/mozilla/fxa/packages/fxa-react/configs/rescripts.js:55:11)
    at /Users/dschomburg/Documents/code/mozilla/fxa/node_modules/ramda/src/internal/_pipe.js:3:14
    at /Users/dschomburg/Documents/code/mozilla/fxa/node_modules/ramda/src/internal/_pipe.js:3:27
    at /Users/dschomburg/Documents/code/mozilla/fxa/node_modules/ramda/src/internal/_arity.js:10:19
    at /Users/dschomburg/Documents/code/mozilla/fxa/packages/fxa-admin-panel/node_modules/@rescripts/cli/patch.js:32:20
    at Object.<anonymous> (/Users/dschomburg/Documents/code/mozilla/fxa/packages/fxa-admin-panel/node_modules/react-scripts/scripts/build.js:58:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERROR: "build:client" exited with 1.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
