### ISSUE TITLE
Upgrade @types/dateformat from ^3.0.1 to ^5.0.0 (fxa-admin-panel)  (dev)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13356]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5371)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
