### ISSUE TITLE
Upgrade @testing-library/react from ^12.1.5 to ^13.3.0 (fxa-admin-panel)  (dev)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13358]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5369)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
