### ISSUE TITLE
Upgrade eslint-plugin-jest from ^24.5.2 to ^26.5.3 (fxa-admin-panel)  (dev)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13360]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5375)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
