### ISSUE TITLE
Upgrade tailwindcss from ^1.9.1 to ^3.1.4 (fxa-admin-panel)  (dev)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13364]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5378)

**Comment by pdehaan** [comment]
Ref #12154

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
