### ISSUE TITLE
The user is redirected to "Enter your email" page when using the browser's back button from Privacy notice/ ToS pages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13368]
**Build:**

Stage [Train 235]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user is on “Set your password” page.

**Steps to reproduce:**

1. Click the “Privacy notice“ or the “Terms of service” links.
1. Click the browser’s back button.

**Actual result:**

The user is taken back to the “Enter your email” page instead of the “Set your passsword” page.

**Expected result:**

The user is taken back to “Set your passsword“ page.

**Notes:**

When using the “Back“ blue button from the “Privacy notice” or “Terms of service” pages the user is taken back to “Set your password“ page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5380)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25456">user taken to first page .gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
