### ISSUE TITLE
Upgrade postcss-cli from ^7.1.1 to ^9.1.0 (fxa-admin-panel)  (dev)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13365]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5377)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
