### ISSUE TITLE
[fxa-auth-server] Script to load JSON file(s) into Firestore emulator

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13373]
It is tedious to add test data via the Firestore emulator UI (aside: this is also true for the Firestore UI in the GCP console). Additionally, any data gets cleared when fxa is stopped locally.

The current process to work around this to say, test IAP subscriptions locally[1], is to create a personal GCP project and point fxa to that project’s Firestore rather than the local emulator, which is time-consuming, error-prone and unnecessary.

Ben had the good idea of creating a loader script with some test `PlayStoreSubscriptionPurchase`(s) and `AppStoreSubscriptionPurchase`(s) and any other test data we might want. This script would populate the Firestore emulator with this data in the appropriate collections and could be executed with a yarn run command.

This ticket is to:

* Write the script
* Create the yarn run command (or similar)
* Update the fxa-auth-server’s README with instructions and example usage

[1]: To be documented in [https://mozilla-hub.atlassian.net/browse/FXA-5352](https://mozilla-hub.atlassian.net/browse/FXA-5352|smart-link).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5381)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
