### ISSUE TITLE
[fxa-content-server] UI shows a 500 error for 400 "Unknown subscription plan"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13374]
Luke was testing a new Relay product in stage, [https://accounts.stage.mozaws.net/subscriptions/products/prod_LpPDO8sOc29CGe](https://accounts.stage.mozaws.net/subscriptions/products/prod_LpPDO8sOc29CGe), with a default plan (price_1L7kOmKb9q6OnNsLOFENhJ4X) that wasn’t found by the `/productName` endpoint, resulting in a 400 “Unknown subscription plan” error.

Despite the error being a 400 (current hypothesis is that the plan is misconfigured in Stripe) in the Network monitor, the content server’s UI says the error is a 500, which is misleading for RP/FxA engineers trying to debug the issue.

The error code in the UI should match the error code from the server’s response or at least differentiate 400s (client error) from 500s (server error).

Note: The the URL above may no longer reproduce the issue once e.g. the plan configuration is updated to be valid. The issue can be reproduced with any product/plan whose plan is invalid.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5383)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25468">500_error_in_UI.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
