### ISSUE TITLE
Some price/product metadata updates are not propagated and/or delayed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13376]
This came up in a Slack conversation with Luke of the Relay team. He had created a new product with a default price, and the checkout screen at [+https://accounts.stage.mozaws.net/subscriptions/products/prod_LpPDO8sOc29CGe+](https://accounts.stage.mozaws.net/subscriptions/products/prod_LpPDO8sOc29CGe) was not loading with a 400 “Unknown subscription plan” error, despite the metadata in Stripe being valid (note: the UI shows a 500 which is wrong – see [https://mozilla-hub.atlassian.net/browse/FXA-5383](https://mozilla-hub.atlassian.net/browse/FXA-5383|smart-link) for that fix).

Triggering a bunch of noop updates (see the event history for this [product](https://dashboard.stripe.com/test/products/prod_LpPDO8sOc29CGe) for 6/23) got the checkout screen to work.

I was able to reproduce this for [another stage product](https://dashboard.stripe.com/test/products/prod_JqSgEW0LrHV90G):

**Steps to reproduce**

1. Ensure checkout loads (i.e. the metadata is valid): [+https://accounts.stage.mozaws.net/subscriptions/products/prod_JqSgEW0LrHV90G+](https://accounts.stage.mozaws.net/subscriptions/products/prod_JqSgEW0LrHV90G).
1. Remove a required Stripe metadata key/value from the product metadata.
1. Refresh the page from step 1.
1. Observe the error message in the Network tab (400 “Unknown subscription plan” from the `/productName` endpoint in the auth server).
1. Reinstate the required Stripe metadata key/value from step 2.
1. Refresh the page from step 1.

**Expected behavior**

* Checkout page loads successfully.

**Actual behavior**

* Checkout page displays the same error as in step 4.
* Some time later (I checked 1.5 hours later), refreshing the page from step 1 correctly loads the checkout page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5385)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25479">Screen Shot 2022-06-23 at 11.13.06 AM.png</a>

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

The pattern is that a invalid product is added, then an invalid price is added, then the product is fixed, and that didn’t cause the price to get updated. Ideally we reload all the prices when a product is updated, because a product can fix a price’s metadata.

Ben had to update the price to get it to load even though the product was what was invalid.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Added it to the next maintenance sprint.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
