### ISSUE TITLE
[FxA-Settings] Secondary email cannot be deleted and the user cannot sign out after entering the authorization code

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13372]
**Build:**

Stage [Train 235]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user has a secondary email added and verified.

**Steps to reproduce:**

1. Change the primary email using “Make primary” button from “Secondary email” line.
1. Click “Firefox account menu” and then “Sign out”.
1. Enter the new primary email address and click “Continue”.
1. Enter your email address as password and click “Sign in”.
1. Enter your username as password and click “Sign in“.
1. Enter your correct password and click “Sign in“.
1. Enter the authorization code from your email inbox and click “Continue“.
1. Change the primary email again.
1. Delete the secondary email.
1. Click “Firefox account menu” and then “Sign out”.

**Actual result:**

The secondary email cannot be deleted. “Sorry, there was a problem deleting this email“ error message is displayed.

The user cannot sign out. “Sorry, there was a problem signing you out“ error message is displayed.

**Expected result:**

The secondary email can be deleted. No error message is displayed.

The user can sign out. No error message is displayed.

**Notes:**

If the user doesn’t use the page for about 15 min then the secondary email is deleted and he can sign out.

If the user logs in with that account using a new browser profile then it also works.

!sign out error.png|width=733,height=264!

!secondary email cannot be deleted.PNG|width=589,height=417!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5382)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25465">secondary email cannot be deleted.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25464">sign out error.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
