### ISSUE TITLE
Update jest from 27.5.1 to 28.1.1 (fxa-admin-server) (dev) (X)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13385]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5398)

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Does not import modules cleanly. Seems as though ts-jest isn’t working properly.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
