### ISSUE TITLE
Update googleapis from 102.0.0 to 104.0.0 (fxa-admin-server) (X)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13387]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5396)

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

This was reverted due to an OOM in the build-deploy ci job. https://app.circleci.com/pipelines/github/mozilla/fxa/31448/workflows/cd09a9f0-3355-4762-a65c-ae1cab193cc0/jobs/344808 ( https://app.circleci.com/pipelines/github/mozilla/fxa/31448/workflows/cd09a9f0-3355-4762-a65c-ae1cab193cc0/jobs/344808 )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
