### ISSUE TITLE
Question: is it possible to cache gcloud/crates on Circle?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1338]
A large portion of the time running tests on Circle is installing gcloud and compiling creates for the email service. Is it possible to cache these dependencies and only have them install/compile if there are updates?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-113)
┆Issue Number: FXA-113

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We don't run the email service builds all the time so this isn't a big portion anymore
