### ISSUE TITLE
Update @nestjs/graphql from 8.0.2 to 10.0.16 (fxa-admin-server) (X)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13383]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5388)

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Upgrading grahql for nestjs also pushes up the apollo-server from verions 2 to version 3. This entails multiple things to change and update as documented here:

https://www.apollographql.com/docs/apollo-server/migration ( https://www.apollographql.com/docs/apollo-server/migration|smart-link ) 

We happen to be using the graphql-updated package listed, so multiple related libraries will all need to be updated as well. There’s 4 other graphql-* libraries that may require updates at the same time. So this is likely to be a rather substantial set of updates that all need to occur at once.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
