### ISSUE TITLE
Update graphql from 15.6.1 to 16.5.0 (fxa-admin-server) (X)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13386]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5397)

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Updating this package is more involved. Increase points and moving back to new.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
