### ISSUE TITLE
Upgrade objection from ^2.2.17 to ^3.0.1 (fxa-shared) 

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#13396]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5411)

**Comment by pdehaan** [comment]
https://vincit.github.io/objection.js/release-notes/migration.html#migration-from-objection-2-x-to-3-0

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
