### ISSUE TITLE
Upgrade find-up from ^5.0.0 to ^6.3.0 (fxa-shared) 

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#13398]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5409)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

See https://github.com/mozilla/fxa/pull/13410#issuecomment-1167853973 ( https://github.com/mozilla/fxa/pull/13410#issuecomment-1167853973|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
