### ISSUE TITLE
fxa-dev-launcher: env setting isn't working

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13427]
Should be a quick fix; the README says to run `FXA_ENV=latest npm start` but when you set this to “stage”, the endpoints still point to localhost.

While we’re at it, we should add a sentence or two about why this package is useful in the README. We have a separate ticket filed to update Sync docs in ecoystem-platform (#13251 / FXA-5305) so we don’t need to be too extensive.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5418)

**Comment by LZoog** [comment]
Closing this - it appears to be working now? ... I don't know what I ran into before but `FXA_ENV=stage npm start` works.
