### ISSUE TITLE
Upgrade @hapi/catbox-memory from ~5.0.1 to ~6.0.0 (fxa-profile-server) 

### ISSUE THREAD

**Issue by millsoper** [mozilla/fxa#13429]
This upgrade was flagged running @dschom's script for identifying dependency updates/changes. While 6.0.0 is the latest version of catbox-memory (per the github repo, committed 05-16-22) the documentation still lists 5.0.1 as the latest version, both in the [changelog](https://hapi.dev/module/catbox-memory/changelog/) and also in the [versions status](https://hapi.dev/resources/status/#catbox-memory). Given that we don’t have any record of the upgrade in the changelog, it might be better to hold off on upgrading this.

It looks like this is used to create the `cacheProvider` for the webserver in `fxa-profile-server/lib/server/web.js` if we AREN’T using redis. We choose whether or not to use redis (and thus `@hapi/catbox-memory`) in a ternary which checks `config.serverCache.useRedis`, which is set in `fxa-profile-server/lib/config.js`  to default to true. It isn’t clear to me where `useRedis` could be set to false but possibly it could be coming in from an env var?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5420)

**Comment by pdehaan** [comment]
https://github.com/hapijs/catbox-memory/compare/v5.0.1...v6.0.0

**PROTIP:** Also, <kbd>npm diff --diff="@hapi/catbox-memory@5" --diff="@hapi/catbox-memory@6"</kbd> if you're curious what _`npm`_ thinks the diff is between two versions (which I _believe_ will ignore all files/changes that aren't tracked by npm; which is why the diff is slightly different between GitHub's version and npm's version). 🔥 

```diff
diff --git a/lib/index.js b/lib/index.js
index v5.0.1..v6.0.0 100755
--- a/lib/index.js
+++ b/lib/index.js
@@ -17,7 +17,7 @@
 };
 
 
-exports = module.exports = internals.Connection = class {
+exports.Engine = class CatboxMemoryEngine {
 
     constructor(options = {}) {
 
diff --git a/package.json b/package.json
index v5.0.1..v6.0.0 100644
--- a/package.json
+++ b/package.json
@@ -1,7 +1,7 @@
 {
   "name": "@hapi/catbox-memory",
   "description": "Memory adapter for catbox",
-  "version": "5.0.1",
+  "version": "6.0.0",
   "repository": "git://github.com/hapijs/catbox-memory",
   "main": "lib/index.js",
   "files": [
@@ -12,14 +12,20 @@
     "catbox",
     "memory"
   ],
+  "eslintConfig": {
+    "extends": [
+      "plugin:@hapi/module"
+    ]
+  },
   "dependencies": {
-    "@hapi/boom": "9.x.x",
-    "@hapi/hoek": "9.x.x"
+    "@hapi/boom": "^10.0.0",
+    "@hapi/hoek": "^10.0.0"
   },
   "devDependencies": {
-    "@hapi/catbox": "11.x.x",
-    "@hapi/code": "8.x.x",
-    "@hapi/lab": "24.x.x"
+    "@hapi/catbox": "^12.0.0",
+    "@hapi/code": "^9.0.0",
+    "@hapi/eslint-plugin": "*",
+    "@hapi/lab": "^25.0.1"
   },
   "scripts": {
     "test": "lab -a @hapi/code -L -t 100",
diff --git a/LICENSE.md b/LICENSE.md
index v5.0.1..v6.0.0 100755
--- a/LICENSE.md
+++ b/LICENSE.md
@@ -1,5 +1,6 @@
-Copyright (c) 2012-2020, Sideway Inc, and project contributors  
-Copyright (c) 2012-2014, Walmart.  
+Copyright (c) 2012-2022, Project contributors
+Copyright (c) 2012-2020, Sideway Inc
+Copyright (c) 2012-2014, Walmart.
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
```

**Comment by data-sync-user** [comment]
➤ Mill Soper commented:

This package doesn't mention this new version in any of their documentation, so we'll hold off on updating.
