### ISSUE TITLE
Update content server to accept oauth `response_type=id_token`

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#13436]
We will need to update our relier model to support the new type, ref https://github.com/mozilla/fxa/blob/aea4cbe07aabb494dd53999984fbaac46c048df0/packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js#L180

In our standard oauth flow we create a user in local storage but I'm not so sure we need to complete all of that for this? An RP is explicity requesting an id token and not an access tokens. It seems like we should complete the request and just forward the token if successful.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5426)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
