### ISSUE TITLE
inform relying parties of the change

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13437]
Before we launch this we should email RP to let them know of this change. give them a rundown of what they will need to do to make changes of the metadata.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5427)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
