### ISSUE TITLE
Refactor inlined CSS (fxa-settings)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13442]
## Description

A few inlined styles in the **fxa-settings** package.
We might be able to ignore the .storybook/ folder since I'm not sure if that /design-guide/ folder is from the template.

### Steps to reproduce

```sh
git grep -n " style=" packages | grep -Ev "\.(md|svg):" | grep -v "/123done/" | grep -Ev "\.(test|stories)\."

packages/fxa-settings/.storybook/design-guide/pages/Colors.tsx:34:        style={{ backgroundColor: hex }}
packages/fxa-settings/.storybook/design-guide/pages/Spacing.tsx:186:                      style={{
packages/fxa-settings/src/components/PageAvatar/index.tsx:230:          style={{ containerStyle: { borderRadius: '8px' } }}
```

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5432)

**Comment by LZoog** [comment]
We will probably need to ignore the ones in design-guide, maybe we can stick a lint ignore in there. They're not from a template but we pull the values from the Tailwind config file and there might be a not a nice way to display the hex color as the bg with Tailwind classes, and the spacing one is similar. We should double check before we place an ignore in there but the `PageAvatar` one for sure can be updated.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
