### ISSUE TITLE
Refactor inlined CSS (fxa-payments-server)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13440]
## Description

A few inlined styles in the /packages/fxa-payments-server.

### Steps to reproduce

```sh
git grep -n " style=" packages | grep -Ev "\.(md|svg):" | grep -v "/123done/" | grep -Ev "\.(test|stories)\."

packages/fxa-payments-server/src/components/AppLayout/index.tsx:19:        style={{ opacity: 1 }}
packages/fxa-payments-server/src/components/PayPalButton/index.tsx:226:            style={styleOptions}
packages/fxa-payments-server/src/components/PlanDetails/index.tsx:88:                style={{ ...setWebIconBackground }}
packages/fxa-payments-server/src/routes/Product/SubscriptionUpgrade/PlanUpgradeDetails.tsx:116:            style={{ ...setWebIconBackground }}
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx:54:        style={webIconBackground ? { background: webIconBackground } : {}}
packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx:33:      <div className="dialog-icon" style={{ ...setWebIconBackground }}>
```

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5429)

**Comment by LZoog** [comment]
cc @StaberindeZA 

We can either close this since it should be complete with the "refactor to Tailwind" epic but you could also throw this in there and then double check everything mentioned here was addressed after the rest is closed out. 🤷‍♀️

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
