### ISSUE TITLE
Refactor inlined CSS (fxa-react)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13441]
## Description

An inlined style in the **fxa-react** package.

### Steps to reproduce

```sh
git grep -n " style=" packages | grep -Ev "\.(md|svg):" | grep -v "/123done/" | grep -Ev "\.(test|stories)\."

packages/fxa-react/components/Header/index.tsx:20:      style={props.styles}
```

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5431)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Reino Muhl Will this be covered by the Tailwind epic to be filed? Will defer to you on how to triage this.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
