### ISSUE TITLE
[FxA optimizations] "create strong passwords" link not displayed on Password requirements tooltip on mobile 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13465]
**Build:**

Stage [Train 235.1]

**Affected platforms:**

Android 12

iOS 15.4

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user doesn’t have a Firefox account.

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and enter a valid email address that doesn’t have a FF account associated with it.
1. Tap on “Continue”.
1. Tap on “Password” field and observe the tooltip.

**Actual result:**

“Stay safe - don’t reuse passwords…“ copy and “create strong passwords“ link are not displayed on tooltip.

**Expected result:**

“Stay safe - don’t reuse passwords…“ copy and “create strong passwords“ link are displayed on tooltip.

**Notes:**

Same issue when resetting the password.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5444)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/25657">link not on pwd tooltip.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
