### ISSUE TITLE
Add web-vitals library to front end to monitor web performance?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13471]
## Description
&hellip; because @annasob mentioned monitoring [web performance metrics](https://web.dev/vitals/) in the future.
I found https://www.npmjs.com/package/web-vitals (made by the Google Chrome team) which is pretty popular and can send results to Google Analytics or Google Tag Manager.

Or since we're [mostly] using React apps, https://create-react-app.dev/docs/measuring-performance/ is also pretty useful.

Not sure if we want to break though out into separate FxA and SubPlat tickets to track separately; or just mark this as a SubPlat ticket and let the FxA team decide if they want to add it too.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5446)

**Comment by pdehaan** [comment]
Also https://wanago.io/2022/02/07/measuring-performance-web-vitals-react/ is a good read for web-vitals w/ React apps.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
