### ISSUE TITLE
Remove custom Tailwind variations provided by v3

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13477]
Now that we have Tailwind v3, we have at least several custom variations in our Tailwind config that we no longer need since they're provided by Tailwind by default. We should look at our config file and see what’s provided via the [v3 docs](https://tailwindcss.com/docs/installation) and remove what’s provided by default.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5448)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
