### ISSUE TITLE
Failing functional test: recovery code - can regenerate recovery code when low

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1347]
> Screenshot saved at: https://screencap.co.uk/images/3d27f26082149d4099e92579ff7264f268145c00.png
> × firefox on mac 18.5.0 - recovery code - can regenerate recovery code when low (8.075s)
    Error: UnexpectedBrowserNotification
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1632:41>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1631:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:60:23>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:73:18>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:68:10>
      at Test.can regenerate recovery code when low [as test]  <tests/functional/sign_in_recovery_code.js:152:10>
      at <src/lib/Test.ts:263:51>

Found trying to [add all the OAuth tests to the Circle run](https://github.com/mozilla/fxa/pull/1337), though these fail locally too.

**Comment by shane-tomlinson** [comment]
cc @vbudhram

**Comment by shane-tomlinson** [comment]
The test seems wrong to me. After submitting the recovery code, the test says the browser should not be notified of the login until *after* the user has replaced the recovery codes. It seems like the browser should be notified immediately to avoid something strange happening and that signin being lost.

However, if I modify line 152 to be `testIsBrowserNotified`, the subsequent line checking for the "replace recovery codes" screen fails, instead the user is shown a "signin complete" screen.

**Comment by shane-tomlinson** [comment]
The default [recoveryCodes.count](https://github.com/mozilla/fxa/blob/3a04fbc5e2fa135b96dffa25b8bf6e85003651cb/packages/fxa-auth-server/config/index.js#L944) value is 8 locally, the test assumes 3.

**Comment by vbudhram** [comment]
Thanks for the fix! The reason for the difference was to make it easier to test [low recovery codes](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/config/index.js#L948).
