### ISSUE TITLE
Address content-server validation errors having high error rates 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13493]
There is a high error rate for validation errors in the content server. We should try to determine why these are occurring. If they are expected, we should filter them out so they are not reported to sentry. If they are not expected, we should address the root issue.

The majority of errors are coming off requests to the following end points:

* /csp-violation
* /metrics
* /navigation-timing

Currently, the sentry errors have no request body because it is being filtered out. To diagnose the underlying problem, we should consider letting the body through and filtering it with our PII Filter in fxa-shared.

Sentry Issue: [FXA-CONTENT-1PB](https://sentry.io/organizations/mozilla/issues/3336270148/?referrer=jira_integration)

```java
Error: Validation failed
  File "/fxa/node_modules/celebrate/lib/celebrate.js", line 95, in <anonymous>
    const error = new CelebrateError(undefined, internals.DEFAULT_ERROR_ARGS);
  File "/fxa/node_modules/celebrate/lib/celebrate.js", in runMicrotasks
    const HTTP = require('http');
  File "node:internal/process/task_queues", line 96, in processTicksAndRejections
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5455)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
