### ISSUE TITLE
Inform users for how long are they blocked after entering wrong FxA password many times

### ISSUE THREAD

**Issue by vcarciu** [mozilla/fxa#135]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0

Steps to reproduce:
1.Go to AMO-dev and try to login through FxA
2.Enter wrong password many times until a message saying that "Attempt limit exceeded"

Expected results:
Users should also be informed for how long are they blocked

Actual results:
This info is not displayed

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by philbooth** [comment]
Blocked until copy editor returns.

**Comment by vladikoff** [comment]
@rfk has a few ideas for this...

**Comment by rfk** [comment]
In the past we've avoided publicizing the precise details of our blocking/rate-limiting policies, but I think it's a good idea to add it to the message here.   My one requirements is that the value we show *must* be filled in dynamically based on information from the server, not hard-coded into the message itself.

IIUC the error that generates this "attempt limit exceeded" message is a `429`, which should have a repsonse body like this:

```
{
  "code": 429,
  "errno": 114,
  "error": "Too Many Requests",
  "message": "Client has sent too many requests",
  "retryAfter": 30
}
```

The `retryAfter` field here gives the time the server wants you to wait, in seconds.  Let's use that value as part of the message to the user.  (Although this may pose some interesting localization challenges...)

Assigning back to @ryanfeeley to coordinate updated copy etc.

**Comment by rfk** [comment]
@ryanfeeley @vladikoff what do you think about spinning up a small milestone to tie together the UX improvements we're making around this flow?  I can think of at least the following that seem related:

* this bug
* the captcha work
* improving messaging when blocked for reasons outside the user's control

**Comment by rfk** [comment]
> a small milestone to tie together the UX improvements we're making around this flow

On reflection, I don't think it's a good idea to tie this specific enhancement in with the captcha work.  This seems small and approachable enough to do on its own, and I can't think of a plausible metric/hypothesis that would justify us doing it as an experiment.

@ryanfeeley, I'll defer this to you for prioritization and proposed UX.  The server returns the number of seconds the user will be required to wait.  How should we change the "Attempt limit exceeded" message to reflect that information?

(Separately, we'll work on #3646 and similar in order to show this message less often.  But it'll still show up sometimes even if we have some captcha mechanism in place.)

**Comment by vladikoff** [comment]
cc @ryanfeeley  https://github.com/mozilla/fxa-bugzilla-mirror/issues/48

**Comment by rfk** [comment]
@ryanfeeley to provide improved messaging here

**Comment by vladikoff** [comment]
from mtg: 
 - we have a design a countdown animation on the button
 - it is not clear that some actions will need this, only login?
 - "sign in" authorization conflicts with this ( cc @shane-tomlinson ). @ryanfeeley user might get the countdown first and then they get "authorization" 
 - not clear about "bounces" -> how many people have lost their email? if users have no control of their email. 
 - if email bounces (via signin authorization) we should signal to the user. 
 
cc @ryanfeeley

**Comment by rfk** [comment]
> "sign in" authorization conflicts with this 

That feature is only on the specific case of login attempts.  There are other endpoints that hit rate-limiting for which we could also improve the UI, such as sending emails from the password-reset endpoint.

**Comment by vladikoff** [comment]
Closing in favour of https://github.com/mozilla/fxa-bugzilla-mirror/issues/48 because there is a bugzilla bug with that one
