### ISSUE TITLE
Lighthouse performance results for SubPlat checkout page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13504]
## Description

Did a Lighthouse audit of the subscriptions.firefox.com checkout page for a VPN subscription.

### Steps to reproduce

1. Created a clean Google Chrome profile w/o any other add-ons.
2. Navigate to https://www.mozilla.org/en-US/products/vpn/#pricing
3. Click "Get 12-month plan" button.
4. Should take you to a URL like https://subscriptions.firefox.com/checkout/prod_FvnsFHIfezy3ZI
5. Open DevTools > Lighthouse
6. Set "Device" to "Desktop"
7. Click "Analyze page load"

### Expected result

What should happen?

### Actual result

- [subscriptions-firefox-com-lighthouse.pdf](https://github.com/mozilla/fxa/files/9022333/subscriptions-firefox-com-lighthouse.pdf)
- [subscriptions.firefox.com-20220630T105040.json.zip](https://github.com/mozilla/fxa/files/9022186/subscriptions.firefox.com-20220630T105040.json.zip)

CATEGORY | SCORE
:----|----:
Performance |95
Accessibility | 96
Best Practices | 83
SEO | 80

There are a few areas we can probably boost the score a little bit:
- #### PERFORMANCE
    - [ ] Does not use passive listeners to improve scrolling performance
	    - Looks like this might be coming from some www.paypal.com URL.
	- [ ] Image elements do not have explicit `width` and `height`
	    - shield logo and 4 credit card logos
	- [ ] Registers an `unload` listener
	    - The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead.
	- [ ] Serve static assets with an efficient cache policy &mdash; 38 resources found
	    - A few of these seem to be from paypal CDN or stripe; but the majority of them are ours (or already seemingly have a 1 m Cache TTL. 🤷 )
- #### ACCESSIBILITY
    - [ ] `[aria-hidden="true"]` elements contain focusable descendents
	    - via `input.__PrivateStripeElement-input`, so maybe not in our control.
- #### BEST PRACTICES
    - [ ] Browser errors were logged to the console
- #### SEO
	- [ ] Document does not have a meta description. Description text is empty.
	- [ ] Page is blocked from indexing
	    - LOL. Whatever.

### Environment

Chrome 103.0.5060.53 (arm64) DevTools, macOS 12.4, Lighthouse 9.6.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5459)

**Comment by LZoog** [comment]
FWIW, I don't think we care about the SEO result at least, assuming payments is the same as #3884.

**Comment by pdehaan** [comment]
Here's a prettified version of the `<head>` tags.

```html
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Firefox Accounts</title>
  <meta name="description" content="" />
  <meta name="referrer" content="origin" />
  <meta name="robots" content="noindex,nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=2,user-scalable=yes" />
  <meta name="apple-itunes-app" content="app-id=989804926, affiliate-data=ct=smartbanner-fxa" />
  <meta name="fxa-config" content="%7B%22env%22%3A%22production%22%2C%22legalDocLinks%22%3A%7B%22privacyNotice%22%3A%22https%3A%2F%2Fwww.mozilla.org%2Fprivacy%2Ffirefox-private-network%22%2C%22termsOfService%22%3A%22https%3A%2F%2Fwww.mozilla.org%2Fabout%2Flegal%2Fterms%2Ffirefox-private-network%22%7D%2C%22productRedirectURLs%22%3A%7B%22prod_FvnsFHIfezy3ZI%22%3A%22https%3A%2F%2Ffpn.firefox.com%2Fvpn%2Fdownload%22%7D%2C%22sentry%22%3A%7B%22dsn%22%3A%22https%3A%2F%2Fbd67bbdfad9b46a7a2f0faf4aa02c122%40o1069899.ingest.sentry.io%2F6231072%22%2C%22env%22%3A%22prod%22%2C%22sampleRate%22%3A1%2C%22tracesSampleRate%22%3A0%2C%22serverName%22%3A%22fxa-payments-broker%22%2C%22clientName%22%3A%22fxa-payments-client%22%7D%2C%22servers%22%3A%7B%22auth%22%3A%7B%22url%22%3A%22https%3A%2F%2Fapi.accounts.firefox.com%22%7D%2C%22content%22%3A%7B%22url%22%3A%22https%3A%2F%2Faccounts.firefox.com%22%7D%2C%22oauth%22%3A%7B%22url%22%3A%22https%3A%2F%2Foauth.accounts.firefox.com%22%2C%22clientId%22%3A%2259cceb6f8c32317c%22%7D%2C%22profile%22%3A%7B%22url%22%3A%22https%3A%2F%2Fprofile.accounts.firefox.com%22%7D%7D%2C%22paypal%22%3A%7B%22apiUrl%22%3A%22https%3A%2F%2Fwww.paypal.com%22%2C%22clientId%22%3A%22Adb5V3A0jC394H-2nZL9JRBzcre0bNjxm_tqzezZDTTSheL4ANKqvG79uyDw1lwtxuXbDPK7Kdp6pMbr%22%2C%22scriptUrl%22%3A%22https%3A%2F%2Fwww.paypal.com%22%7D%2C%22stripe%22%3A%7B%22apiKey%22%3A%22pk_live_HgtiWdwlc5Uq8ZRsPAXIAyRY00CA51o613%22%7D%2C%22version%22%3A%221.235.2%22%7D" />
  <meta name="fxa-feature-flags" content="%7B%22useFirestoreProductConfigs%22%3Afalse%7D" />
  <meta name="fxa-paypal-csp-nonce" content="%2216bceee0-aefc-4c1e-bca5-3909a235008c%22" />
  <script src="https://js.stripe.com/v3/"></script>
  <style>
    body {
      background: #f9f9fa;
    }
  </style>
  <link href="/static/css/6.aa355d7d.chunk.css" rel="stylesheet" />
  <link href="/static/css/main.6cc89197.chunk.css" rel="stylesheet" />
  <script charset="utf-8" src="/static/js/1.09627b9c.chunk.js"></script>
  <link rel="stylesheet" type="text/css" href="/static/css/0.45a3d09e.chunk.css" />
  <script charset="utf-8" src="/static/js/0.e5c93b90.chunk.js"></script>
  <link rel="stylesheet" type="text/css" href="/static/css/3.4f130655.chunk.css" />
  <script charset="utf-8" src="/static/js/3.80c64461.chunk.js"></script>
  <link rel="stylesheet"  type="text/css" href="/static/css/7.79e460b6.chunk.css" />
  <script charset="utf-8" src="/static/js/7.f59540ee.chunk.js"></script>
  <script src="https://www.paypal.com/tagmanager/pptm.js?id=subscriptions.firefox.com&amp;t=xo&amp;v=5.0.320&amp;source=payments_sdk&amp;client_id=Adb5V3A0jC394H-2nZL9JRBzcre0bNjxm_tqzezZDTTSheL4ANKqvG79uyDw1lwtxuXbDPK7Kdp6pMbr&amp;vault=true" id="xo-pptm" async="" ></script>
  <link rel="stylesheet" type="text/css" href="/static/css/2.33ecf294.chunk.css" />
  <script charset="utf-8" src="/static/js/2.13b3d94b.chunk.js"></script>
  <script type="text/javascript" async="" src="https://www.paypalobjects.com/muse/muse.js"></script>
  <script charset="utf-8" src="https://js.stripe.com/v3/fingerprinted/js/trusted-types-checker-8f145f1c4f05a13814c9d72ead77e23d.js"></script>
</head>
```

We're explicitly marking "noindex,nofollow" for robots, so 100% agree that we can probably safely ignore SEO results.

The other interesting thing was the inline `<style>` tag which seems to be setting a body background color.
Apart from that, looks like we have 6 *.chunk.css files being loaded and 5 *.chunk.js files being loaded.

And a couple of the console errors were CSP violations for PayPal (the latter might be some weird tracking pixel).

> 1. Refused to load the script 'https://www.paypalobjects.com/muse/muse.js' because it violates the following Content Security Policy directive: "script-src 'self' https://js.stripe.com https://www.paypal.com 'nonce-16bceee0-aefc-4c1e-bca5-3909a235008c'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> 1. Refused to load the image 'https://t.paypal.com/ts?pgrp=muse%3Athird-party%3Aanalytics-xo%3A%3A5VJDAEPVSWA5Q-1&page=muse%3Athird-party%3Aanalytics-xo...' because it violates the following Content Security Policy directive: "img-src 'self' data: https://secure.gravatar.com https://profile.accounts.firefox.com https://firefoxusercontent.com https://accounts-static.cdn.mozilla.net".

**Comment by pdehaan** [comment]
Re: _"Image elements do not have explicit `width` and `height`"_

```html
<img src="/static/media/shield.b84338b3.svg" alt="shield">
...
<div class="accepted-cards">
  <img src="/static/media/visa.b7ac34e6.svg" alt="visa">
  <img src="/static/media/mastercard.d98c41d6.svg" alt="mastercard">
  <img src="/static/media/discover.92bf7b4e.svg" alt="discover">
  <img src="/static/media/amex.5c30c82e.svg" alt="american express">
</div>
```

The SVG logos seem to be 38&times;24 (or 39&times;24 in the case of Discover card) but render at 19:12 or 13:8 aspect ratios.

**Comment by annasob** [comment]
This report looks good. @sardesam  can u audit for potential future accessibility fixes. @StaberindeZA  lets see if we can either put this in the component update epic so we can look at this when remaking some of the pages or look over it now and file smaller tasks in the epic.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
