### ISSUE TITLE
Implement the signature verification for the addon manifest for android

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13515]
We already have the desktop and iOS implementations. This is the only missing one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/VPN-2515)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Sorry, I think data-sync might have closed this when I moved it to the VPN project.  (Also maybe lost the previous comments?)  Anyway, pinging Andrea Marchesini to look at this

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
