### ISSUE TITLE
[subplat] Remove downloadURL from metadata in Stripe Production

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13529]
Follow up to [https://mozilla-hub.atlassian.net/browse/FXA-5467](https://mozilla-hub.atlassian.net/browse/FXA-5467|smart-link) and should only be done after that ticket has landed in Production.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5468)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
