### ISSUE TITLE
DeviceId sometimes null  from push

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13527]
Sentry Issue: [FXA-AUTH-5Q](https://sentry.io/organizations/mozilla/issues/3352894564/?referrer=jira_integration)

We are seeing deviceId being posted as ‘null’ to [http://api.accounts.firefox.com/v1/account/device/commands](https://sentry.io/organizations/mozilla/issues/?project=6231056&query=url%3A%22http%3A%2F%2Fapi.accounts.firefox.com%2Fv1%2Faccount%2Fdevice%2Fcommands%22&referrer=jira_integration). There is an id in the sentry issue for an account that experiences this problem. This happens rarely, but we wanted to file it anyways.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5466)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
