### ISSUE TITLE
TypeError: this._currentView is null

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13530]
Sentry Issue: [FXA-CONTENT-ZB](https://sentry.io/organizations/mozilla/issues/3279182390/?referrer=jira_integration)

```
TypeError: this._currentView is null
  at showChildView/< (./views/app.js:166:19)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5469)

**Comment by data-sync-user** [comment]
➤ Sentry commented:

Wil Clouser wrote:

{quote}**@Barry Chen** is working on an issue to remove the /connect_another_device/why modal which is the "transaction" for this -- maybe where the problems start?  

In short, this might be fixed after Train 237.{quote}

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
