### ISSUE TITLE
TypeError: paypal.Buttons is undefined

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13532]
Sentry Issue: [FXA-PAYMENTS-8T](https://sentry.io/organizations/mozilla/issues/3360632162/?referrer=jira_integration)

```
TypeError: paypal.Buttons is undefined
  at 220 (/static/js/2.13b3d94b.chunk.js%20line%202%20%3E%20srcScript:1:475)
  at c (/static/js/runtime-main.3c465715.js%20line%202%20%3E%20srcScript:1:569)
  at onClick (/sdk/js:2:170699)
```

I don't think this is a critical bug, but this is coming from our scripts, so we should check it out and maybe handle it better in the code.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5471)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
