### ISSUE TITLE
Bugzilla 1774992 - Disable Sentry if telemetry is disabled

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13536]
[https://bugzilla.mozilla.org/show_bug.cgi?id=1774992](https://bugzilla.mozilla.org/show_bug.cgi?id=1774992|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5475)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
