### ISSUE TITLE
TypeError: annullato

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13535]
Sentry Issue: [FXA-PAYMENTS-A8](https://sentry.io/organizations/mozilla/issues/3394192501/?referrer=jira_integration)

```
TypeError: annullato
```

Why is our error message in Italian?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5474)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

If it’s on the front-end I think being localized makes some sense

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
