### ISSUE TITLE
Error: Paypal SDK could not be loaded.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13534]
Sentry Issue: [FXA-PAYMENTS-3N](https://sentry.io/organizations/mozilla/issues/3279853688/?referrer=jira_integration)

```
Error: Paypal SDK could not be loaded.
  at O/</i.onerror (lib/hooks.tsx:105:13)
```

Perhaps we can pass more information like an `error` object into the `script.onError` handler to understand what the cause(s) of these errors are?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5472)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
