### ISSUE TITLE
UI -  Stop bundle upgrades if the user has an IAP that is on the same product set

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13548]
Background:

If a user has an Apple or Google in app subscription, the user should not be able to go to the web client and upgrade to a bundle that will leave them subscribed to the same client twice. Example User has a VPN mobile subscription, they go to the web client and subscribe to the VPN + Relay Bundle. This will leave them with 2 VPN subscription paying twice. 

Solution:

Add appropriate User error messages to the checkout screen to notify the user of a issue. Do not allow the upgrade.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5480)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Adding flag to note that we need design help here - Jessica Valentine is signed on to provide. Thanks Jess!

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Design required prior to August 17.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
