### ISSUE TITLE
Expand the metrics that are stored during upgrades

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13546]
Currently the metrics we store for upgrades under the event type “fxa_pay_upgrade - success” are {"plan_id":"price_1KeG02JNcmPzuWtRlrSiLTI6","product_id":"prod_LKvr8fYGbBxcaZ","payment_provider":"stripe"}

We need to at least add previous_product_id and previous_plan_id.

In stripe the subscription id stays the same but the product and price change from the old product to the new. however Stripe does track this info. Screenshot of Upgrading from Relay Premium → Relay + VPN Bundle attached

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5478)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26024">Screen Shot 2022-07-06 at 12.23.17 PM.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
