### ISSUE TITLE
Add a querystringparameter to automatically populate a coupon when given a URL

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13550]
The checkout page already has a React hook for the coupon and setting the coupon:

`fxa/packages/fxa-payments-server/src/routes/Checkout/index.tsx Line 130` 

`  const [coupon, setCoupon] = useState<CouponDetails>();`

This coupon gets passed into the coupon form component which switches between taking in user input or the read only state with the coupon.

We could potentially grab a query string parameter and use some hook like `useEffect` to parse the URL and call the coupon API endpoint to retreive the coupon and set it on page load. 

The only UI quirk would be that we can’t set the `CouponForm` error state from the parent component so if an invalid coupon code was passed in the URL we wouldn’t have a way to show that to the user unless we refactored the `CouponForm` component as well (which would change the estimate of this ticket).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5481)

**Comment by annasob** [comment]
QA has a list of coupons. if more are needed we can add them to this doc https://docs.google.com/spreadsheets/d/11J5OvxkaeLkBwP1GaROFr1UARQRLBTNoZxeY6Cfz6LY/edit#gid=1939661370

**Comment by data-sync-user** [comment]
➤ Meghan Sardesai commented:

Chelsea Lewis Just to confirm, that wouldn’t involve any additional code changes and would only be a matter of adding the invalid coupon link to the product? If that’s the case, that shouldn’t be a problem. Unless I might have missed taking something into consideration Ivo Plamenac ? Let me know!

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

I dont want to speak for Chelsea Lewis but I think an invalid coupon code is just one that doesnt exist. So hypothetically if like there was an actual 100% off coupon for people named Meg with a code of MEGGETS100OFF then something like http://moz.com/checkout?discount=MEGGETS100OFF would take you to the checkout page with the coupon already applied where as entering http://moz.com/checkout?discount=GIMMEDATDISCOUNT would just take you to the checkout page with the coupon form empty (presumably GIMMEDATDISCOUNT is not a valid code that was entered in stripe for that product).

I think this might be what youre getting at but just wanted to double check.
