### ISSUE TITLE
[subplat]  “Emails do not match” tooltip not displayed when entering 2 different email addresses and the subscription can be finalized

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13566]
**Affected FxA versions:**

* 1.236.0;

**Prerequisites:**

* Be on [+Set up your subscription page+](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/checkout/prod_FiJ42WCzZNRSbS?device_id=6c6ea7aa9b62464aaca67f8248a4e7df&flow_begin_time=1657283296639&flow_id=115956412bf0e62b1d31393c5326fe7e168fe708c08c30c7d5853f6f3165e990&plan=price_1J0owvKb9q6OnNsLExNhEDXm&entrypoint=www.mozilla.org-vpn-product-page&form_type=button&service=e6eb0d1e856335fc&utm_source=www.mozilla.org-vpn-product-page&utm_medium=referral&utm_campaign=vpn-product-page&data_cta_position=pricing) (new flow);

**Steps to reproduce:**

1. Click on the “Enter your email” field and enter an email address that is not associated with a FXA account;
1. Click on the “Confirm your email” field and enter the same email address that was entered at step 1;
1. Click again on the “Enter your email” field and replace one letter from the entered email address;
1. Observe the behavior;
1. Fill in all the mandatory fields and finalize the subscription;

**Expected result:**

* For step 3:  “Confirm your email” field is bordered in red. “Emails do not match” tooltip is displayed next to the field. 
* For step 5: The user is NOT able to finalize the subscription after filling in all the mandatory fields, as the entered email addresses are not the same.

**Actual result:**

* For step 3: “Confirm your email” field is NOT bordered in red. “Emails do not match” tooltip is NOT displayed next to the field. 
* For step 5: The user is able to finalize the subscription after filling in all the mandatory fields. Subscription confirmation page displays the altered email address.

**Notes:**

* Emails are being received for the email address displayed on the Subscription confirmation page (from “Enter your email” field);
* See the attached video.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5498)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26126">Screen Recording 2022-07-08 at 15.41.46.mov</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
