### ISSUE TITLE
Service property missing from fxa_activity - cert_signed (most of the time)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1356]
Moving forward we will understand usage across services by combining activity from `fxa_activity - cert_signed` and `fxa_activity - access_token_checked`. 

The problem is that we don't seem to be logging the service in `cert_signed` most of the time.

https://analytics.amplitude.com/mozilla-corp/chart/new/a0ufl5t

This makes it harder to understand usage across our services.

CC @irrationalagent

**Comment by irrationalagent** [comment]
Is this a dupe of https://github.com/mozilla/fxa/issues/493 ?

**Comment by davismtl** [comment]
Yes, yes it is...

It is a dupe of #493
