### ISSUE TITLE
Clear cached Stripe data from Firestore on /account/destroy

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13562]
[https://mozilla-hub.atlassian.net/browse/FXA-4815](https://mozilla-hub.atlassian.net/browse/FXA-4815|smart-link) restored the behavior of our `expandResources` helper to fetch the latest Stripe resource even if caching fails (e.g. for a deleted customer).

One observation we made during review was that the `/account/destroy` handler doesn’t clear any cached Stripe data in Firestore. This means for example that a deleted Stripe customer would still be in our cache, and consequently, `expandResource` would still try to update the cache when we receive Stripe webhooks after they were deleted (e.g. `payment_method.card_automatically_updated` for customers deleted prior to [https://mozilla-hub.atlassian.net/browse/FXA-4636](https://mozilla-hub.atlassian.net/browse/FXA-4636|smart-link)). We should clear any data in Firestore on `/account/destroy`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5494)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
