### ISSUE TITLE
[FxA-Settings] Focus border changed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13579]
**Build:**

Stage [Train 236.1]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

N/A

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and login using an existing account.
1. Go to Recovery key section and click Create.
1. Enter the correct password and click Continue.
1. Click the Download/ Copy/ Print buttons and observe the focus border.

**Actual result:**

The focus border changed. The dots are bolded and bigger.

**Expected result:**

The focus border is like before.

**Notes:**

Please see the other sections and buttons too.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5507)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26199">focus border.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26202">focus border 2.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26200">focus border 3.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26201">focus border Before.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26198">mobile focus border.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
