### ISSUE TITLE
Request deletion of IT RunBook for SubPlat; replace with contacts for SubPlat in the Firefox Ecosystem Engineering space

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13578]
Deleted our former request so re-stating here. I will be requesting the deletion of IT’s SubPlat runbook as it’s out of date since the 2020 rearchitecture of SubPlat.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5506)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

IT has requested the specified page; a draft is in-progress for the creation of the new page.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
