### ISSUE TITLE
Some existing FxA users cannot subscribe to any products

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13576]
Edit #2: Copying [Dan’s STR](https://mozilla-hub.atlassian.net/browse/FXA-5503?focusedCommentId=571483) to the description, which we both can reproduce 100% of the time in production:

{quote}Alright, after testing this a bunch of different ways, I found the exact case that triggers the problem. It doesn’t require 2FA. It doesn’t even require multiple accounts or older accounts. And, most importantly, it is reproducible every time. Here are the steps:

1. Sign into your account from the browser’s menu (firefox hamburger menu > sync and save data > sign in)

2. Once on the[ |http://accounts.firefox.com][+accounts.firefox.com+](http://accounts.firefox.com) settings page, sign out.

3. Now go to[ |https://developer.mozilla.org/en-US/][https://developer.mozilla.org/en-US/](https://developer.mozilla.org/en-US/|smart-link)

4. Click 'Already a subscriber?' link (If you are signed in on MDN, you can sign out at this time in order to see this link again.)

5. Complete the sign in process.

6. Now go directly to[ |https://accounts.firefox.com/subscriptions/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtR1oBrw8o6][+https://accounts.firefox.com/subscriptions/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtR1oBrw8o6+](https://accounts.firefox.com/subscriptions/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtR1oBrw8o6).

**7. Result: Observe that you get redirected to the checkout page,** [+*https://subscriptions.firefox.com/checkout/prod_LKvr8fYGbBxcaZ*+](https://subscriptions.firefox.com/checkout/prod_LKvr8fYGbBxcaZ)**.** {quote}

- - -
(Original text from ticket filed)

Edit: After doing some testing with Dan, I cannot reproduce this with a brand new FxA account with 2FA enabled, though I can with my years old personal FxA account. Also, I disabled 2FA on my personal FxA account, and I can still reproduce the issue, so it may not be related to 2FA at all.

~~TL;DR: The auth redirect for existing FxA users with 2FA is broken in two places, meaning they can’t subscribe to any product/plan.~~

First place: While testing [https://mozilla-hub.atlassian.net/browse/FXA-5500](https://mozilla-hub.atlassian.net/browse/FXA-5500|smart-link) in production with an existing FxA account with ~~2FA enabled~~, I was redirected to the new user checkout page instead of the existing user checkout page after logging in.

STR:

1. Have an FxA account ~~with 2FA enabled~~.
1. Sign out of the FxA account from #1.
1. Go to [https://developer.mozilla.org/en-US/plus](https://developer.mozilla.org/en-US/plus|smart-link) 
1. Click “Already a Subscriber”
1. Sign in with the account from #1 ~~using 2FA~~, which redirects you to [https://developer.mozilla.org/en-US/plus](https://developer.mozilla.org/en-US/plus|smart-link) .
  1. Note that your FxA account avatar is displayed in the top right corner now instead of the “Already a Subscriber” CTA.
1. Until [https://mozilla-hub.atlassian.net/browse/FXA-5500](https://mozilla-hub.atlassian.net/browse/FXA-5500|smart-link) is fixed to update the URLs on the landing page, go directly to [https://accounts.firefox.com/subscriptions/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtR1oBrw8o6](https://accounts.firefox.com/subscriptions/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtR1oBrw8o6).

Expected:

* The content server detects that I am logged in and redirects me to the existing FxA user checkout page ([https://subscriptions.firefox.com/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtRslZijhQu](https://subscriptions.firefox.com/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtRslZijhQu)).

Actual:

* The content server does not detect that I am logged in and redirects me to the new user checkout page: [https://subscriptions.firefox.com/checkout/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtRslZijhQu](https://subscriptions.firefox.com/checkout/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtRslZijhQu).
* Secondary bug (can be split from this one) – second place auth redirect is broken:
  * Clicking on the “Sign in” link on the new user checkout page forces me to sign in again ~~with 2FA~~.
  * After successfully signing in, I am redirected to FxA Settings rather than the existing FxA user checkout page for the MDN product/plan I was trying to subscribe to.
  * **The combination of these two bugs means there is no workaround for existing FxA users** **~~with 2FA enabled~~** **to subscribe to a product.**

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5503)

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Bianca Danforth I just did some exploratory testing. Of the two incorrect actual behaviors I can only reproduce the second. Maybe we can pair so I can see I can see this being reproduced. Either I am misinterpreting one of the instructions or it is some how account specific. 

For the issue, the one where with the redirect on the ‘Sign In’ link on the /checkout page does not redirect properly, this is actually pretty easy to address. I'll start a branch for this bug and at least try to get that fix up by EOD.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thank you Dan for looking into this. I can reproduce the first bug on my personal FxA account with 2FA; I just tried it again. Interestingly, I can’t reproduce it for a brand new FxA account with 2FA enabled.

I will DM you the primary email addresses I used for both of these FxA accounts. Perhaps it only affects older accounts?

I’m happy to pair if helpful.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Dan Schomburg for the investigation and the detailed explanation of what is happening here.

IIUC, you’re saying there is a different authn strategy when one is signed into accounts.firefox.com ( http://accounts.firefox.com ) compared to the strategy used by RPs like MDN (OAuth).

My expectation as an end user is, if I am signed into FxA anywhere (e.g. MDN’s website), I am signed into FxA everywhere (e.g. accounts.firefox.com ( http://accounts.firefox.com ), VPN’s website, etc.).

Certainly one solution is for RPs to detect if the user is signed in on their website, and conditionally append the signin=true query parameter to the URLs on their landing pages. I am also wondering, however, if it is possible for FxA to perform this check on behalf of the RP without the need for the additional logic and effort on their part. In other words, instead of only checking if the user is signed into accounts.firefox.com ( http://accounts.firefox.com ) during this redirect, check if the user is signed into the RP via OAuth and if so, take them through the same path as currently happens when signin=true or when the user is authenticated to accounts.firefox.com ( http://accounts.firefox.com ). This would make the behavior more consistent across all RPs. What do you think?

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hi,

I followed the steps described in the Dan’s[ comment|https://mozilla-hub.atlassian.net/browse/FXA-5503?focusedCommentId=571483], on Stage environment - Train 1.237.3, and I am still able to reproduce the issue.

Also, I am reproducing the redirect to Settings page while logging in with a FXA account with 2FA enabled, by clicking on the “Sign in” link from the new user checkout page (Secondary bug from the description of the issue).

Bianca Danforth / Dan Schomburg , has the fix landed in Train 237? Thank you.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Reopening per Bianca Hidecuti 's comments.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Hi Bianca Hidecuti . You are so diligent in checking! Thank you for the question.

Dan’s proposed solution pertains to the primary bug reported here (not the secondary one), and it would require the RP landing page checkout URLs to be appended with signin=true. As such, the fix would only be evident with a code change on the RP’s websites.

I proposed an alternative solution in this comment ( https://mozilla-hub.atlassian.net/browse/FXA-5503?focusedCommentId=572085 ), which wouldn’t require any RP code changes (assuming it’s feasible), but I haven’t heard back from Dan Schomburg about it.

Dan, if we go with the solution that requires the RP code change, can part of the fix include updating our docs accordingly (if not already updated) and communicating this requirement out to RPs?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

fwiw I was not able to reproduce on production with Dan’s STR.

Bianca Hidecuti What are the stage URLs that I should use to try reproduce?  Thanks!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Bianca Danforth , thank you for replying so quickly! 

Barry Chen , in order to reproduce this on stage, go to Firefox browser → about:config → change the preference “identity.fxaccounts.autoconfig.uri” to “https://accounts.stage.mozaws.net ( https://accounts.stage.mozaws.net )”, and restart the browser. 

After that follow the steps described by Dan:

  1. Sign into your account (FXA account without subscription) from the browser’s menu (firefox hamburger menu > sync and save data > sign in)
  2. Now go directly to[ |http://accounts.firefox.com]https://accounts.stage.mozaws.net/ ( https://accounts.stage.mozaws.net/signin ) and sign in.
  3. Once on the https://accounts.stage.mozaws.net/settings ( https://accounts.stage.mozaws.net/settings ) settings page, sign out.
  4. Now go to[ |https://developer.mozilla.org/en-US/]https://developer.allizom.org/plus ( https://developer.allizom.org/plus|smart-link )  (stage)
  5. Click 'Already a subscriber?' link (If you are signed in on MDN, you can sign out at this time in order to see this link again.)
  6. Complete the sign in process.
  7. Now go directly to[ |https://accounts.firefox.com/subscriptions/products/prod_LKvr8fYGbBxcaZ?plan=price_1KeG02JNcmPzuWtR1oBrw8o6]https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/checkout/prod_Jtbg9tyGyLRuB0?plan=price_1JFoTYKb9q6OnNsLalexa03p ( https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/checkout/prod_Jtbg9tyGyLRuB0?plan=price_1JFoTYKb9q6OnNsLalexa03p ) - redirects to New checkout flow.

Hope this helps! Let me know if something is unclear. Thanks.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Thank you, Bianca Hidecuti.  I was able to reproduce it on stage using your steps.  Dan already explained in one of his comments why it works this way, so I’m just going to show myself out.

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Bianca Danforth sorry for not addressing your feedback sooner. I do think you have a point about a UX issue that exists at the moment. Sorry if I made it sound like this was not the case. When a user signs in through `oauth/signin`, we could also make sure they are signed into accounts.firefox.com ( http://accounts.firefox.com ). The fact we don’t do this is either a bug or an oversight in my opinion. I’d like to consult with other teammates (Barry Chen thoughts appreciated?) before changing this though, as there might be some reason this works the way it does.

Just to fully explore this idea a bit more… you said that, ‘if I am signed into FxA anywhere (e.g. MDN’s website), I am signed into FxA everywhere (e.g.[ |http://accounts.firefox.com]+accounts.firefox.com+ ( http://accounts.firefox.com ), VPN’s website, etc.)’ While I generally agree, I do have one point about this statement, that I’d like to express.

By nature oauth is adhoc. As a result I don’t think there is a way to ‘automatically’ sign someone into VPN when they sign into accounts.firefox.com ( http://accounts.firefox.com ). This is because the client(s) must initiate the oauth request. This whole process can be very seamless, and maybe it feels like the user is signed in everywhere. However, if you were to look at the database after a signin on accounts.firefox.com ( http://accounts.firefox.com ), you would only see a new token for that authn request, not for all potentially connected RP clients, and I think this behavior is correct.

So what does that mean exactly? Well, if we look at websites like MDN using FxA oauth, it means when you oauth through using your browser, I think your browser should automatically be signed into FxA, even though it appears not to happen right now. I think automatically signing into FxA should be possible,  because the oauth requests literally run through accounts.firefox.com ( http://accounts.firefox.com ). However, the converse is not true. If you sign into accounts.firefox.com ( http://accounts.firefox.com ), you still need to at least initiate a login on the RP’s site (i.e. MDN). This login process should seem automatic, because FxA will recognize you and won’t require you fill out a username/password, but you still be required to initiate the login. I tested this notion out on other sites that use oauth, and it seemed to hold true.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Soooo I noticed two things.  One is that signing into MDN+ does sign the user into FxA.  And two is that the STR (for stage) is using a direct Payments URL for the checkout page; that’s not the expected user experience.  A user should be taken to the content-server so that they can be redirected back to the checkout page with an access token (if they are signed in).  I think that’s why I was not able to reproduce on production; I used a content-server URL in my step to go to the checkout page.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Barry Chen : Thanks for weighing in here. The conversation has kind of meandered a bit since I originally filed the ticket, making it difficult to follow along. I’ll try to clarify a few things.

{quote}One is that signing into MDN+ does sign the user into FxA.{quote}

I had previously updated the description to say that I could not reproduce this for new FxA accounts, but I could reproduce this in production for my personal FxA account, which is several years old. One of Dan’s previous comments ( https://mozilla-hub.atlassian.net/browse/FXA-5503?focusedCommentId=571483 ) also has a way to reproduce this 100% of the time (I just reproduced it again in production). I will update the description to use his STR.

{quote}And two is that the STR (for stage) is using a direct Payments URL for the checkout page{quote}

QA’s STR are different from the STR in the description and Dan’s STR referenced above. We are linking to accounts.firefox.com ( http://accounts.firefox.com ) to trigger the redirect.

Dan Schomburg : Thank you for the detailed reply; it’s extremely helpful as someone less familiar with the sign in process in different places.

What I’m proposing is slightly different from what you are proposing, though your proposal sounds like it would definitely solve the issue.

What I was proposing is that, rather than changing the behavior of logging a user into accounts.firefox.com ( http://accounts.firefox.com ) once they have OAuthed into an RP website, update the behavior of the +`isSignedIn`+ ( https://github.com/mozilla/fxa/blob/a3624ab3976d24663e5e377860d313471f7e128c/packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js#L35 ) check (or add another check) to return true if the user is signed into the referring RP's website via OAuth. Of course it's possible that an Oauth signin alone does not grant sufficient authorization for the user to create a subscription, in which case only your proposal would work.

Either way, looking back at +(some) history of the `signin=true` query parameter+ ( https://github.com/mozilla/fxa/pull/9931/files#r675257771 ), it was intended for use in our new user checkout flow if the user already had an FxA account but was signed out. We never explicitly discussed it being used by RPs on their landing pages.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Thank you, Bianca.  I was able to reproduce on production.

I agree with Dan that we should log the user into FxA when they log into an OAuth RP.  I don’t know why this isn’t the case; maybe it’s a (regression?) bug or maybe there was A Decision.

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Thanks for the feedback Barry Chen. If you are in agreement, I guess we can get this into an upcoming sprint, make the change, and test the impact. ATM, I can’t think of a reason why logging into FxA when going through an oauth flow would cause a problem.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
