### ISSUE TITLE
[subplat][tailwind] Component - PlanDetails - Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13589]
**Requirements**

1. Replace all CSS/SCSS with Tailwind utility classes
1. Remove .css and .scss files
1. Rework Storybook files as discussed in [https://mozilla-hub.atlassian.net/browse/FXA-5080](https://mozilla-hub.atlassian.net/browse/FXA-5080|smart-link)

Additional Notes

* Breaking this story up into 2.
  * Replace all existing classes
  * Rework responsive logic

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5522)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
