### ISSUE TITLE
[subplat] [l10n] [ro] “{payment-method-header}” strings displayed on Set up your subscription page 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13580]
**Affected FxA versions:**

* 1.236.1;

**Prerequisites:**

* Have the system language / browser language set to Romanian;

* Be on [+Set up your subscription page+](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/checkout/prod_FiJ42WCzZNRSbS?device_id=b93a12fb829f46cf9c9ae2a063389e28&flow_begin_time=1657549119525&flow_id=b0ef184308856e74d5d76c98481fd0157b98ae8b0f80b40f57c574a014b0a95b&plan=price_1J0Y1iKb9q6OnNsLXwdOFgDr&entrypoint=www.mozilla.org-vpn-product-page&form_type=button&service=e6eb0d1e856335fc&utm_source=www.mozilla.org-vpn-product-page&utm_medium=referral&utm_campaign=vpn-product-page&data_cta_position=pricing) (new flow);

**Steps to reproduce:**

1. Observe the “Choose your payment method” title from Set up your subscription page;

**Expected result:**

* “Choose your payment method” title is correctly displayed;

**Actual result:**

* “{payment-method-header}” strings are displayed instead of “Choose your payment method” title;

**Notes:**

* This is not reproducible for the old flow;

* See the attached screenshot.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5508)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26207">Captură de ecran din 2022-07-11 la 16.55.29.png</a>

**Comment by data-sync-user** [comment]
➤ Peter deHaan commented:

Possibly related: https://pontoon.mozilla.org/ro/firefox-accounts/main.ftl/?string=237541 ( https://pontoon.mozilla.org/ro/firefox-accounts/main.ftl/?string=237541|smart-link ) 

Looks like that string is translated for Romanian, but… I think the {{{ payment-method-header }}} string isn’t translated yet; https://pontoon.mozilla.org/ro/firefox-accounts/main.ftl/?string=236962 ( https://pontoon.mozilla.org/ro/firefox-accounts/main.ftl/?string=236962|smart-link )

**Comment by data-sync-user** [comment]
➤ Reino Muhl commented:

The translation ID for the highlighted section has ID payment-method-header-second-step, and a translation was recently provided for it.

However, this specific ID is dependent on a separate translation with ID payment-method-header. Unfortunately a translation has not been provided yet for this ID, which is why the variable placeholder, “{ payment-method-header }” is shown, instead of the translated text.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
