### ISSUE TITLE
fxa-graphql-api throwing error in destroySession()

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13581]
This started June 28 and happens regularly but not often.

Sentry Issue: [FXA-GRAPHQL-API-N](https://sentry.io/organizations/mozilla/issues/3389539905/?referrer=jira_integration)

```
Error: Non-Error exception captured with keys: code, errno, error, info, message
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5511)

**Comment by data-sync-user** [comment]
➤ Sentry commented:

Wil Clouser wrote:

{quote}Looks related to https://sentry.io/organizations/mozilla/issues/3389539856/{quote}

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
