### ISSUE TITLE
[subplat][tailwind] Page - Checkout - Responsive Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13582]
**Requirements**

1. Replace all CSS/SCSS with Tailwind utility classes
1. Remove .css and .scss files
1. Rework Storybook files as discussed in [FXA-5080](https://mozilla-hub.atlassian.net/browse/FXA-5080)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5515)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
