### ISSUE TITLE
[chore][react-style-guide] Add section dicussing our Context usage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13597]
**Background**

We recently added a React style guide to our Firefox Ecosystem docs, and would like to add some additional sections.

**Requirements**

Add a section covering our Context usage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5527)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
