### ISSUE TITLE
[chore][react-style-guide] Add section discussing l10n

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13599]
**Background**

We recently added a React style guide to our Firefox Ecosystem docs, and would like to add some additional sections.

**Requirements**

Add a section covering l10n and the Localization module we use.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5529)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
