### ISSUE TITLE
[chore][react-style-guide] Add section discussing A11y

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13598]
**Background**

We recently added a React style guide to our Firefox Ecosystem docs, and would like to add some additional sections.

**Requirements**

Add a section covering A11y.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5528)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Lauren Zugai would you mind adding some notes here on what you think would be best to document in this section of the style guide?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
