### ISSUE TITLE
Display Prorated Amount on PlanDetails Component on Subscription Upgrade

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13609]
Display the prorated amount when a user is upgrading their subscription with a coupon. The preview invoice API endpoint should already be retreiving the necessary information but the PlanDetails component will need to be changed to display this information. 

Acceptance Criteria:

* Component is updated to display prorated amount
* FE tests to check that amount is displayed
* BE tests to verify information is present in response
* Stories updated for changed component(s)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5538)

**Comment by data-sync-user** [comment]
➤ Jessica Valentine commented:

hi there! same question I have for FXA-5539 can we get an example of what this should look like or what the exact meta data is here that needs to be added into the UI? Im trying to update the spec to reflect this and im having some trouble figuring out what this info is and where it needs to be placed, thank you!

Here are the specs: https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=1532%3A17660 ( https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=1532%3A17660|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
