### ISSUE TITLE
ValidationError: "unblockCode" length must be 8 characters long

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13608]
This isn't something we need to be logging to Sentry.

Sentry Issue: [FXA-AUTH-7P](https://sentry.io/organizations/mozilla/issues/3406195016/?referrer=jira_integration)

```
ValidationError: "unblockCode" length must be 8 characters long
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5537)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
