### ISSUE TITLE
Add Feature Flag to Display/Access Coupon on Subscription Upgrade

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13607]
Add feature flags to both fxa-payments-server and fxa-auth-server to hide the coupon form from the UI as well as block access to any business logic changes in the auth server.

Acceptance Criteria:

* Feature flags in both packages
* Tests 

See [https://github.com/mozilla/fxa/pull/11048/files](https://github.com/mozilla/fxa/pull/11048/files|smart-link)  for reference

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5536)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
