### ISSUE TITLE
Add CouponForm Component To SubscriptionUpgrade Component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13613]
The CouponForm component needs to be added to the template of the SubscriptionUpgrade component. Additionally, the coupon object from the Product page needs to be passed into the SubscriptionUpgrade component. 

Acceptance Criteria:

* CouponForm visible on subscription upgrade
* Clicking Apply in CouponForm updates displayed prices
* FE tests to verify CouponForm interacts with SupscriptionUpgrade component as desired
* Add promotionCode to payload for `PUT /oauth/subscriptions/active/{subscriptionId`}
* Update stories

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5544)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXA-5544

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
