### ISSUE TITLE
Add promotionCode parameter to updateSubscription Call

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13614]
The `PUT /oauth/subscriptions/active/{subscriptionId`} endpoint needs to accept `promotionCode` , pass it into the corresponding handler and stripe helper methods (`changeSubscriptionPlan` and `updateSubscriptionAndBackfill`)

Acceptance Criteria:

* Optional parameter on payload for endpoint
* Parameter optional on subsequent method calls and passed along
* Auth server tests

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5545)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXA-5545

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
