### ISSUE TITLE
Remove Feature Flags for Displaying CouponForm on Subscription Upgrades

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13615]
Remove the feature flags added for this epic.

Acceptance Criteria:

* Feature flags removed from auth and payments packages
* Tests around feature flags removed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5546)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
