### ISSUE TITLE
Remove fxa-support-panel

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13612]
A long time ago we built the fxa-support-panel which is an iframe’d site within the Zendesk application.  You can read more about it in [the README](https://github.com/mozilla/fxa/tree/main/packages/fxa-support-panel).

The support team is ready to stop using the fxa-support-panel in favor of the already existing admin panel.  **This issue is to remove the fxa~~support~~panel completely.**

In addition to removing the code, please make sure SRE knows this is going away in the sprint that it is so they can fix deployment scripts.  I think there is also an LDAP group which could be removed, and there is a project in sentry that can be deleted.  If you come across other touchpoints please speak up so we can clean them up too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5543)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXA-5543

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Support Panel has been disabled in Zendesk.

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Remove the package and update build/deploy scripts accordingly.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
