### ISSUE TITLE
Add a query string parameter to automatically populate coupon for subscription upgrade

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13616]
We need to do the same work as [https://mozilla-hub.atlassian.net/browse/FXA-5481](https://mozilla-hub.atlassian.net/browse/FXA-5481|smart-link)  for the Product page/subscription upgrade. The page is set up similarly as the checkout page so the same approach should work here as well.

Acceptance Criteria:

* The same query string parameter is used for the URL as in the checkout page
* Adding the parameter will automatically populate the coupon/discount form on page load
* Stories updated accordingly
* FE/payment server tests

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5549)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FXA-5549

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
