### ISSUE TITLE
Remove `version` from package.json

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13631]
A long time ago we distributed [some of our packages on NPM](https://www.npmjs.com/search?q=fxa) and as part of that system they needed to be versioned.  So, all of our packages have a version field in the package.json ([example](https://github.com/mozilla/fxa/blob/main/packages/fxa-admin-panel/package.json#L3)).  

The [documentation is clear](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#version):

{quote}If you don't plan to publish your package, the name and version fields are optional.{quote}

Since we no longer publish to NPM, we don’t need to have that version field.  

We also have `__version__` URLs ([example](https://accounts.firefox.com/__version__)).  These json files are [built when we build the containers](https://github.com/mozilla/fxa/blob/main/_scripts/create-version-json.sh) and use CircleCI variables to get the git tag, so, they should continue to work as expected.  

I consulted with [~accountid:60c368e4d5dde80071a4207c] and the SRE team does not use these version fields for anything.

So, why get rid of them?  Aside from just reducing line count/complexity these are the last thing that the build script automatically adds to every package.  Removing them will mean fewer [“junk” commits](https://github.com/mozilla/fxa/commit/714f9305e272b32925984841fb925950ec093f31) that do nothing but increment this number.

This issue is to remove the version in each package.json and the code in build.sh that increments them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5553)

**Comment by pdehaan** [comment]
Not sure if we want to add `private: true` to each package.json while we're at it (although I can't imagine anybody accidentally doing a <kbd>npm publish</kbd> in any of the packages/ folders).

```js
import cp from "node:child_process";
import fs from "node:fs/promises";

const pkgs = cp.execSync("git ls-files packages/*/package.json").toString().trim().split("\n");

console.log("`name` | `version` | `private`\n-----|--------:|:------:");
for (const pkg of pkgs) {
  let jsonStr = await fs.readFile(pkg);
  const res = JSON.parse(jsonStr);
  console.log([res.name, res.version || "-", res.private || "-"].join(" | "));
}
```

`name` | `version` | `private`
-----|--------:|:------:
123done | 0.0.2 | true
browserid-verifier | 0.10.1 | -
db-migrations | 1.214.1 | true
fortress | 0.0.2 | true
functional-tests | 1.218.5 | true
fxa-admin-panel | 1.236.3 | -
fxa-admin-server | 1.236.3 | -
fxa-auth-client | 1.185.1 | -
fxa-auth-server | 1.236.3 | -
fxa-content-server | 1.236.3 | -
fxa-customs-server | 1.236.3 | -
fxa-dev-launcher | 1.0.0 | -
fxa-event-broker | 1.236.3 | -
fxa-geodb | 1.236.3 | -
fxa-graphql-api | 1.236.3 | -
fxa-payments-server | 1.236.3 | -
fxa-profile-server | 1.236.3 | true
fxa-react | 1.236.3 | -
fxa-settings | 1.236.3 | true
fxa-shared | 1.236.3 | -
fxa-support-panel | 1.236.3 | true

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
