### ISSUE TITLE
Add `private:true` to all package.json files since we don't publish to npm

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13634]
Not sure if we want to add `private: true` to each package.json while we're at it (although I can't imagine anybody accidentally doing a <kbd>npm publish</kbd> in any of the packages/ folders).

```js
import cp from "node:child_process";
import fs from "node:fs/promises";

const pkgs = cp.execSync("git ls-files packages/*/package.json").toString().trim().split("\n");

console.log("`name` | `version` | `private`\n-----|--------:|:------:");
for (const pkg of pkgs) {
  let jsonStr = await fs.readFile(pkg);
  const res = JSON.parse(jsonStr);
  console.log([res.name, res.version || "-", res.private || "-"].join(" | "));
}
```

`name` | `version` | `private`
-----|--------:|:------:
123done | 0.0.2 | true
browserid-verifier | 0.10.1 | -
db-migrations | 1.214.1 | true
fortress | 0.0.2 | true
functional-tests | 1.218.5 | true
fxa-admin-panel | 1.236.3 | -
fxa-admin-server | 1.236.3 | -
fxa-auth-client | 1.185.1 | -
fxa-auth-server | 1.236.3 | -
fxa-content-server | 1.236.3 | -
fxa-customs-server | 1.236.3 | -
fxa-dev-launcher | 1.0.0 | -
fxa-event-broker | 1.236.3 | -
fxa-geodb | 1.236.3 | -
fxa-graphql-api | 1.236.3 | -
fxa-payments-server | 1.236.3 | -
fxa-profile-server | 1.236.3 | true
fxa-react | 1.236.3 | -
fxa-settings | 1.236.3 | true
fxa-shared | 1.236.3 | -
fxa-support-panel | 1.236.3 | true

_Originally posted by @pdehaan in https://github.com/mozilla/fxa/issues/13631#issuecomment-1183763089_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5554)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
