### ISSUE TITLE
Create set password route

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13646]
Currently there’s a createAccount route in account.ts that handles creating a new account with a set of password hash data. We need a new route that allows a stub account to set a password, this route requires an access token like the one created by the accountStub route. It should include a parameter that indicates whether it should send a verify code email after setting the password as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5556)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
