### ISSUE TITLE
Audit flow metrics for account handlers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13647]
With the additional usage of the account routes in varying context, we should audit the flow functions to ensure they’re emitting the correct events given the different flow contexts they’re used in.

As an example, it appears the accountStub function currently emits a flow complete signal of `account.verified`, when the account has not actually been verified.

We will likely need some help with this from [~accountid:6047c5e143eac6006f71ff05] to ensure our flow metrics are correct given the contexts they’re now used in (accountStub from VPN and Checkout page, new passsword set route, etc).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5557)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Can this/should this be split into multiple tasks to de-risk it, as it’s currently sitting at 5sp? Bianca Danforth / Benjamin Bangert

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

We could possibly have one ticket for auditing each subscription creation flow:

  * New user (AKA “passwordless”), web
  * New user (AKA “passwordless”), mobile
  * Existing user, web
  * Existing user, mobile

Though the points may not add up cleanly to 5. For example, broken up this way, I’d probably give each ticket 2 points thinking some may end up as 1 pointers, others as 3 depending on what we find.

I think part of the reason this is 5 is because neither Ben nor I are terribly familiar with how this is implemented and how this is supposed to work, so we’d have to do some research and testing.

For these reasons, I’m inclined to keep it at 5 points. What do you think, Ben?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
