### ISSUE TITLE
Prevent stub accounts with IAP from deletion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13648]
Currently the `deleteAccountIfUnverified` function in our account handler does not account for IAP when determining if a stub account can be deleted. It should prevent account deletions if the user has an IAP active.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5558)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
