### ISSUE TITLE
Implement UX flow and styles for user signup/signin leading to product subscription

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1364]
We need to implement styles and ensure the UX flow works from RP product page, through FxA signin/signup, through to fxa-payment-server product payment page. I think some of this is already implemented in FxA, but may need some tweaks.

- [ ] [Accept email address submitted from an RP's product page](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/360811492)
- [ ] Use email address to pre-fill signin/signup page.
- [ ] Email confirmation that mentions the product during new account confirmation 
- [ ] After signup & confirm or signin, user lands on product payment page (via Issue #926 / PR #1310 and followup #1723)
- [ ] Product payment page displays "account activated" banner for [new signup](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/357410550) vs just their profile for [existing signin](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/357410549)

https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/360811492
https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/357427885
https://app.zeplin.io/project/5cb61701d1f8c9af80fc61eb/screen/5cf1b045cee3f113e9bbb234

Refinement of #718

**Comment by clouserw** [comment]
Feel free to split this apart if it's too big

**Comment by philbooth** [comment]
> - [ ] After signup & confirm or signin, user lands on product payment page (via Issue #926 / PR #1310)

This one looks like it is now covered by #1723.

**Comment by philbooth** [comment]
So, linking bullets from this issue description to bits of code I think can do it for them:

> - [ ] [Accept email address submitted from an RP's product page](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/360811492)
> - [ ] Use email address to pre-fill signin/signup page.

The content server already supports an `email` query param that does this.

> - [ ] Email confirmation that mentions the product during new account confirmation 

Not done yet but after #927 lands it will be trivial (it shares the same subscription-specific email layer as that issue).

> - [ ] After signup & confirm or signin, user lands on product payment page (via Issue #926 / PR #1310)

Covered by #1723.

> - [ ] Product payment page displays "account activated" banner for [new signup](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/357410550) vs just their profile for [existing signin](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/357410549)

I haven't thought about this one yet.

**Comment by clouserw** [comment]
This is mostly covered in #1723 and Les is going to file a version 2 issue for the last checkbox.
