### ISSUE TITLE
Confusing margins in fxa-settings ConnectedServices mobileLandscape rtl margins

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13666]
Was casually looking at breakpoint-specific styling (as one does) and noticed this one curiosity in [fxa/packages/fxa-settings/src/components/ConnectedServices/index.tsx](https://github.com/mozilla/fxa/blob/1395478bc756e64d462e9401868317a4b194175c/packages/fxa-settings/src/components/ConnectedServices/index.tsx#L189-L192); where both the "rtl" and "ltr" specify the same _left_ margin:

```sh
mobileLandscape:ltr:ml-6
mobileLandscape:rtl:ml-6
```

Not sure if one of those should be an `mr-6`, since it feels odd that the "mobileLandscape" `ltr` and `rtl` use the same value.
But, considering the generic "ltr" specifies `ml-6` and `ml-4`, so I'm guessing that the "rtl" styling should be `mobileLandscape:rtl:mr-6` since we also specify `rtl:mr-4`:
```sh
mobileLandscape:ltr:ml-6 ltr:ml-4
mobileLandscape:rtl:ml-6 rtl:mr-4
```

https://github.com/mozilla/fxa/blob/1395478bc756e64d462e9401868317a4b194175c/packages/fxa-settings/src/components/ConnectedServices/index.tsx#L189-L192

```sh
git grep -Eno "\b(desktop(Xl)?|tablet|mobileLandscape):[a-z0-9:-]+\b" | grep -v "/\.storybook/" | grep -v "\.stories\." | grep -v "\.md:[[:digit:]]"
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5564)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

I think this should be mobileLandscape:rtl:mr-6. Thanks for catching!

**Comment by pdehaan** [comment]
I foolishly left this tab open, which means I accidentally committed more crimes-against-grep.
Apologies in advance, and let me know if you prefer if I split this out in to 3 new issues vs dogpiling into the comments like a coward.

```sh
git grep -nEIoi "\b([a-z]+:)?(ltr|rtl):[a-z0-9:-]+" . | grep -v "/123done/" | grep -v "\.md:"
```

- [ ] `mobileLandscape:ltr:ml-6` vs `mobileLandscape:rtl:ml-6`:
     https://github.com/mozilla/fxa/blob/cb6d0b6c28e890ff3f11f8bb2c041e1c4319a122/packages/fxa-settings/src/components/ConnectedServices/index.tsx#L189
- [ ] `mobileLandscape:ltr:ml-6` vs `mobileLandscape:rtl:ml-6`:
    https://github.com/mozilla/fxa/blob/cb6d0b6c28e890ff3f11f8bb2c041e1c4319a122/packages/fxa-settings/src/components/DataCollection/index.tsx#L57 
- [ ] `mobileLandscape:ltr:ml-6` vs `mobileLandscape:rtl:ml-6`:
    https://github.com/mozilla/fxa/blob/cb6d0b6c28e890ff3f11f8bb2c041e1c4319a122/packages/fxa-settings/src/components/Profile/index.tsx#L13
- [ ] `mobileLandscape:ltr:ml-6` vs `mobileLandscape:rtl:ml-6`:
    https://github.com/mozilla/fxa/blob/cb6d0b6c28e890ff3f11f8bb2c041e1c4319a122/packages/fxa-settings/src/components/Security/index.tsx#L35

**Comment by pdehaan** [comment]
One possible additional hiccup:

```sh
git grep -En "\bfont-header\b" | grep -E "h2 className=" | grep -E "\.tsx:[0-9]+:"

fxa-settings/src/components/ConnectedServices/index.tsx:189:  <h2 className="font-header font-bold mobileLandscape:ltr:ml-6 mobileLandscape:rtl:ml-6 ltr:ml-4 rtl:mr-4 mb-4 relative">
fxa-settings/src/components/DataCollection/index.tsx:57:      <h2 className="font-header font-bold mobileLandscape:ltr:ml-6 mobileLandscape:rtl:ml-6 ltr:ml-4 rtl:mr-4 mb-4 relative">
fxa-settings/src/components/LinkedAccounts/index.tsx:18:      <h2 className="font-header font-bold ltr:ml-4 rtl:mr-4 mb-4 relative">
fxa-settings/src/components/Profile/index.tsx:13:             <h2 className="font-header font-bold mobileLandscape:ltr:ml-6 mobileLandscape:rtl:ml-6 ltr:ml-4 rtl:mr-4 mb-4 relative">
fxa-settings/src/components/Security/index.tsx:35:            <h2 className="font-header font-bold mobileLandscape:ltr:ml-6 mobileLandscape:rtl:ml-6 ltr:ml-4 rtl:mr-4 mb-4 relative">
```

Note that `fxa-settings/src/components/LinkedAccounts/index.tsx:18` doesn't seem to include the `mobileLandscape:*` breakpoint stylings:
https://github.com/mozilla/fxa/blob/52b05b1b84749cb559fecf6f8fc7fc5e438b7c24/packages/fxa-settings/src/components/LinkedAccounts/index.tsx#L18-L21

Not sure if we want to extract that into some reusable component since we repeat this pattern in 5 (well, _4&frac12;_) places.
```diff
-<h2 className="font-header font-bold mobileLandscape:ltr:ml-6 mobileLandscape:rtl:ml-6 ltr:ml-4 rtl:mr-4 mb-4 relative">
+<h2 className="font-header font-bold ltr:ml-4 rtl:mr-4 mb-4 relative">
```

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
