### ISSUE TITLE
A message could be displayed on mobile informing the user that the Firefox browser is already installed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13664]
**Build:**

Stage [Train 236.3]

**Affected platforms:**

Android 12

iOS 15.5

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user is logged in to Sync on desktop.

The “Download Firefox Mobile“ page is opened on desktop.

Firefox browser is installed on mobile.

**Steps to reproduce:**

1. Launch Firefox on a mobile device.
1. Tap on Hamburger menu/ 3 dots menu -> Settings and then tap on Sign in to sync (iOS)/ Turn on Sync (Android).
1. Tap on Ready to scan option and point the phone’s camera to the QR code on desktop to scan the code.

**Actual result:**

After the code is scanned, on Android the user is redirected to Enter your email production page.

On iOS a blank page is displayed.

**Expected result:**

I think it would be good if a message is displayed informing the user that the browser is already installed.

**Notes:**

N/A

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5561)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26532">Android enter email prod pg.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26576">download FF mobile.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26531">iOS blank.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Bianca Oltean would you tell us the URL (and screenshot?) of the “Download Firefox Mobile” page?  Thanks

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Wil Clouser Sure, this is the URL: https://accounts.stage.mozaws.net/pair?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&service=sync&uid=a178de2ce0d84ed39c80175834c1a78e&email=boltean%2Bna%40mozilla.com ( https://accounts.stage.mozaws.net/pair?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&service=sync&uid=a178de2ce0d84ed39c80175834c1a78e&email=boltean%2Bna%40mozilla.com ) and screenshot below:

!download FF mobile.PNG|width=376,height=421!

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Vesta Zare can you take a look to see what we should do here?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
