### ISSUE TITLE
WError: Email account hard bounced

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13668]
Sentry Issue: [FXA-AUTH-95](https://sentry.io/organizations/mozilla/issues/3434322027/?referrer=jira_integration)

FxA has a bunch of bounced emails but we don't alert on them.  Something else must be going on here.  Judging by the breadcrumbs this is Sub Plat related?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5566)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

We should ignore similarly to how we ignore stripe webhooks.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
