### ISSUE TITLE
Auth server emits non-conforming clientIDs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13669]
Sentry Issue: [FXA-EVENT-BROKER-11](https://sentry.io/organizations/mozilla/issues/3430264396/?referrer=jira_integration)

```
ValidationError: "clientId" with value "syn" fails to match the required pattern: /[a-z0-9]{16}/
```

We're wondering why auth-server would emit this event at all.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5567)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
