### ISSUE TITLE
[subplat][tailwind] Component - PlanDetails - Responsivness Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13677]
**Requirements**

1. Replace all CSS/SCSS with Tailwind utility classes
1. Remove .css and .scss files

Additional Notes

* Breaking this story up into 2.
  * Replace all existing classes
  * Rework responsive logic

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5571)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
