### ISSUE TITLE
Support link when not logged in redirects to Settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13679]
When a user visits the support link and is not logged into FxA, they are not taken back to the Support page after logging in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5573)

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Wil Clouser This could likely be a content-server bug that is not honoring the redirect after login.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
