### ISSUE TITLE
[subplat][tailwind] Page - Checkout - Class Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13678]
**Requirements**

1. Replace all CSS/SCSS with Tailwind utility classes
1. Remove .css and .scss files
1. Rework Storybook files as discussed in [https://mozilla-hub.atlassian.net/browse/FXA-5080](https://mozilla-hub.atlassian.net/browse/FXA-5080|smart-link)
1. Add `step-header` to `payments-server/src/styles/tailwind.css` and update `PaymentMethodHeader` component to use the shared style

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5572)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
