### ISSUE TITLE
Import tailwind.css from fxa-react

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13673]
**Background**

Instead of each package having their own `tailwind.css`, have a shared `tailwind.css` in `fxa-react` which also includes other shared style sheets.

**Requirement**

* Import `tailwind.css` from `fxa-react`, for the following packages.
  * `fxa-admin-panel`
  * `fxa-content-server`
  * `fxa-settings`
* Add the `--postcss` parameter to the `build-css` scripts for each package.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5568)

**Comment by LZoog** [comment]
I'm likely going to need to do this in #13492 in all remaining packages except for admin-panel so this should be super fast.

**Comment by LZoog** [comment]
Closing this, it was done in #13492. We could still add it to admin-panel but we don't need any shared styles yet and we can add it when we need it.
