### ISSUE TITLE
Add a more universal "update your browser" page

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1368]
@craigcook noticed that we don't support either IE10 or IE11, and he's right. We officially [support Edge, but neither of the older browsers](https://github.com/mozilla/fxa/blob/master/docs/supported-browsers.md). We require a baseline of ES5 support, and IE's 10 and 11 do not support all the methods we use such as Function.prototype.bind and Array.prototype.filter. There are probably others I'm forgetting too. We have an ["Upgrade Firefox" page](https://github.com/mozilla/fxa/blob/672b1c9c07e376374daf4c489b91281f9b60b6e8/packages/fxa-content-server/server/templates/pages/src/update_firefox.html#L30), what would be very useful is a generic "Upgrade your browser" page that points to the latest Firefox release.

Note, we used to have one of these. I don't remember what happened to it, but I no longer see it in the tree.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-114)
┆Issue Number: FXA-114

**Comment by ryanfeeley** [comment]
@shane-tomlinson I think we have this still, no? I thought I saw it recently.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson I think we have this still, no? I thought I saw it recently.

We only gate on the `context` query parameter, we don't do any UA sniffing.

**Comment by shane-tomlinson** [comment]
For current browser support: https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-dev-process#browser-support

**Comment by hoosteeno** [comment]
The issue mentioned above (https://github.com/mozilla/bedrock/issues/7270) talks about treating this as a bug at the top of a single funnel for a single segment attempting to register an FxA account. I think that's the wrong framing, and this issue is more correct: If FxA can't handle certain user agents, it needs UI to communicate that to those user agents. 

I'll close the issue on Bedrock in favor of this one, and hope we can give legacy browser users a better experience soon.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~mwalkington@mozilla.com] what do you think of changing this from "Firefox Accounts makes use of features that are not supported in your version of Firefox. Please download and install the latest version of Firefox to continue." to "Firefox Accounts makes use of features that are not supported in your browser. Please download and install the latest version of Firefox to continue."  (bold part is the change)
