### ISSUE TITLE
Please coordinate with the Push Server Team on adding information to the VAPID header for Send Tab and FxA command requests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13680]
In order to better understand potential points of data loss in the Push System, it would be useful to have an identifier that can be set as meta information for the request. This identifier can be associated with metrics and errors to allow us to identify potential message loss points within Push. 

We need to make sure that this identifier stays within the Mozilla system, so it is only useful for Mozilla internal systems diagnostics. The push server does not have the concept of meta information other than the VAPID header. A value can be added to the VAPID header (to be determined later) which can be stored and appended to various internal metrics and error logs and can help identify push transactions of interest. 

These can be catalogued in metrics and error report dashboards for review and analysis later as well as potentially identify problematic paths. (See [https://docs.google.com/document/d/178XOZI4LUvWEoav9MDS6wnO_dkGUGJ4rg3Sc6LVwc_w/edit#heading=h.c9u56y2b5vhw](https://docs.google.com/document/d/178XOZI4LUvWEoav9MDS6wnO_dkGUGJ4rg3Sc6LVwc_w/edit#heading=h.c9u56y2b5vhw|smart-link)  for meeting notes)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5575)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
