### ISSUE TITLE
[subplat] Run Stripe to Firestore conversion script - Production

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13689]
**Background**

Work with SREs to run the Stripe metadata to Firestore document conversion script.

**Requirement**

* Run the script with parameter `-t firestore`
* Run the script with parameter `-t local`
  * Upload the JSON files to the appropriate folder in [this private repo](https://github.com/mozilla/fxa-payment-config-manage)

**Additional Note**

To run the script, work with SRE, and ask them to run the following script and parameters.

`node .dist/fxa-auth-server/scripts/stripe-products-and-plans-to-firestore-documents.js -n false -t 'firestore'`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5579)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
