### ISSUE TITLE
A few minor differences between fxa-content-server "sign_in_token_code.mustache" and "confirm_signup_code.mustache" resend snippets

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13691]
## Description

Found while _accidentally_ reviewing https://github.com/mozilla/fxa/pull/13642 (post merge).

### Steps to reproduce

https://github.com/mozilla/fxa/blob/6290adb3a772b57c41fb246300042851747ab00b/packages/fxa-content-server/app/scripts/templates/confirm_signup_code.mustache#L27

https://github.com/mozilla/fxa/blob/6290adb3a772b57c41fb246300042851747ab00b/packages/fxa-content-server/app/scripts/templates/sign_in_token_code.mustache#L29

Hard to see exactly from the snippets (assuming you're browsing in GitHub's luxurious UI), but here's a TLDR:
1. "confirm_signup_code.mustache" separates the `<span>` and `<a>` tags with an `&nbsp;`, but "sign_in_token_code.mustache" doesn't.
2. "sign_in_token_code.mustache" has a `left` class in the `<a>` tag, but "confirm_signup_code.mustache" doesn't.
3. "confirm_signup_code.mustache" has a trailing period in `{{#t}}Email new code.{{/t}}`, but "sign_in_token_code.mustache" doesn't.

### Expected result

🤷 The snippets should probably be more consistent. If it was React I'd probably say make it a reusable component, but we in .mustache land.

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5581)

**Comment by millsoper** [comment]
I'll knock this one out! @pdehaan do you know which version is preferable? I feel like the `nbsp` is a good idea, but no opinion the `left` class or trailing period

**Comment by pdehaan** [comment]
This should be fixed in @LZoog's pending #13739 Tailwindification PR
