### ISSUE TITLE
Support email verification from IE

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1370]
Related to #1368. We do not officially [support IE, only Edge](https://github.com/mozilla/fxa/blob/master/docs/supported-browsers.md). We know signup is broken on IE, I'm not sure whether verification is as well. Yesterday ~1k people tried to verify in IE. Assuming none of those users were able to verify (not likely, but hey), that's north of 300k users/year that are signing up but not verifying.

Of course, we wouldn't have this particular problem if [verification did not involve clicking a link but instead the user had to type a code](https://github.com/mozilla/fxa/pull/1296). 

cc @vladikoff

**Comment by clouserw** [comment]
Thanks for filing.  Your link to using the code instead of a URL is the right path forward here -- let's do that.
