### ISSUE TITLE
RP flows asking me for my password even when I'm signed in to other services and the browser

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1371]
Normally when I am already signed in to the browser and visit one of our services, it recognized me and I just need to click one button to sign in.

This doesn't seem to be happening anymore. I first thought it was a problem with the new flow on /whatsnew which promotes Monitor when you're signed in to the browser:
https://www.mozilla.org/en-US/firefox/67.0.1/whatsnew/

After further investigation, Send and AMO also asked me for my password. So I signed into them to see if it would help the Monitor flow. It did not seem to help improve the flow of those services. They all still ask for my password, one by one.

**Comment by jrgm** [comment]
At the time this was filed, you may have been getting mixed versions of 138/137. I don't know if the UX is sensitive to that, but maybe?

**Comment by davismtl** [comment]
I tested it again this morning. Same problem.

**Comment by shane-tomlinson** [comment]
> I tested it again this morning. Same problem.

It's always going to be the same problem on that machine from here on out unless you sign out of Sync, clear localStorage/cookies, and sign into Sync again.

**Comment by shane-tomlinson** [comment]
There is [this note in the content server code](https://github.com/mozilla/fxa/blob/db6772e07f92a214184c2426358c86dacc2ef2cd/packages/fxa-content-server/app/scripts/views/mixins/cached-credentials-mixin.js#L45) about why we ask for passwords for all sessions except "Sync" sessions:

> We need to ask the user again for their password unless the credentials came from Sync.
> Otherwise they aren't able to "fully" log out. Only Sync has a clear path to disconnect/log out
> your account that invalidates your sessionToken.

This is very much one reason [why it's taken us so long to implement prompt=none](https://github.com/mozilla/fxa-content-server/issues/5916#issuecomment-369777880) - there is potential for confusion around logging out of an RP - some users may expect that their FxA session is destroyed as well.

#1979 has been opened to [support OIDC RP initiated logout](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout), which could give us a path forward here too.

**Comment by davismtl** [comment]
This makes sense. My only worry is that it'll be super challenging to make it clear to users that the sign out from Monitor's website will also disconnect Sync, Lockwise and all the others. If we proceed with that standard, we better be VERY clear on the OP page where the option is global signout is offered.

If I compare to Facebook and Facebook Messenger which has a login that resembles ours (more than Google in some sense since there's is more of an SSO), a sign out of Messenger.com doesn't sign-out Facebook.com. I'm unsure if this is good or bad. I have mixed feelings about it. It's actually what I expected but then the sign-in is very easy since I still have a session with the OP which might be questionable from a security standpoint. 

This is what I saw after sign out of Messenger.com (for reference):

![image](https://user-images.githubusercontent.com/19537086/62063451-b12f4800-b1df-11e9-8fe9-45c540d5c7cc.png)

**Comment by shane-tomlinson** [comment]
> This makes sense. My only worry is that it'll be super challenging to make it clear to users that the sign out from Monitor's website will also disconnect Sync, Lockwise and all the others. If we proceed with that standard, we better be VERY clear on the OP page where the option is global signout is offered.

@davismtl WELCOME BACK!

That's the exact same concern (re signing out of Sync) I noted at the very bottom of https://github.com/mozilla/fxa/issues/1979.

**Comment by rfk** [comment]
> make it clear to users that the sign out from Monitor's website will also disconnect Sync

This is also why we don't currently show a "sign out" button on https://accounts.firefox.com/settings if the user is signed in to sync.

My gut feeling is that this behaviour would be simply too surprising and we'll have to find a way to make it not happen...

> This is what I saw after sign out of Messenger.com (for reference):

This is more-or-less the experience you get right now when you're signed in to Sync (and haven't done anything to disturb that state, such as using a different account to sign in to FxA RPs on the web). I believe it's what Shane is heading towards with his commit above.

> If I compare to Facebook and Facebook Messenger which has a login that resembles ours
> (more than Google in some sense since there's is more of an SSO)

FWIW I get the impression that we want to head towards *more* of an explicit SSO type setup over time...

**Comment by davismtl** [comment]
> FWIW I get the impression that we want to head towards more of an explicit SSO type setup over time...

I'm OK with this so long as we're not opting users into services they didn't know we had. As a result of a best practice like that, the flows should be quite similar.

For example, if you 

- visit Monitor and sign in by clicking "Continue as Ryan".
vs 
- Visit Monitor where you're already signed in but click to turn on the service

The UX is pretty similar in either case. Same number of clicks.

I suppose it would have a slightly bigger difference with Send though where sign in would be automatic vs an extra click.

Returning to this with further thought within the context of SSO:
>  My only worry is that it'll be super challenging to make it clear to users that the sign out from Monitor's website will also disconnect Sync, Lockwise and all the others. If we proceed with that standard, we better be VERY clear on the OP page where the option is global signout is offered.

I feel like all web properties could be signed out together but we should not sign out clients (like the browser) from a web-based RP. Thinking of Google's SSO, if you sign out of Google Accounts, you're signed out everywhere but it won't disconnect Chrome.

**Comment by rfk** [comment]
> if you sign out of Google Accounts, you're signed out everywhere but it won't disconnect Chrome.

I just tried this out of curiosity:

* Visit google.com, sign in with a test account
    * It signs me in on the web, and also in Chrome UI, but doesn't enable sync
* Enable sync in Chrome
* Visit gmail.com, and sign out on the web interface
   * It transitions my Chrome UI to a "paused" state and gives me a screen like this:

![Capture](https://user-images.githubusercontent.com/34695/62091665-70096780-b2b5-11e9-9d0a-c43afcd599e3.PNG)

I guess it didn't completely sign me out of Chrome because the account identity is tied closely to Chrome's local per-user profile management, so it had to remember the identity. But I definitely did disconnect from sync.

**Comment by davismtl** [comment]
Huh, this is new. I stand corrected. Very very interesting.

It's interesting that it still remembers your account though (re: paused). That's a nice touch.

Thanks for going through that flow.

**Comment by rfk** [comment]
I was surprised too, I assume this is relatively new and a result of the infamous "sign you in to the browser automatically when you sign in on the web" thing they went through recently.
