### ISSUE TITLE
Admin Panel: Add link to stripe even for users with canceled subscriptions if a stripe profile exists

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13725]
As a customer support agent, we sometimes need to investigate previous invoices from cancelled or inactive subscriptions. Currently the Admin Panel does not display past invoices or cancelled subscriptions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5594)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
