### ISSUE TITLE
Return `active:false` plans from the /plans endpoint

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13738]
As Barry pointed out in [https://mozilla-hub.atlassian.net/browse/FXA-5577](https://mozilla-hub.atlassian.net/browse/FXA-5577|smart-link) , we should store archived products/plans in Firestore and maintain configuration files for them in our new repo, as we use this endpoint for more than checkout (e.g. subscription management).

This may require an additional check for our checkout logic to filter out `active: false` plans to ensure users can’t subscribe (though it should be blocked downstream by Stripe).

~~It may be that no RP has archived any plans with active subscriptions to this point, but we shouldn’t wait for that to happen before we fix this.~~

As confirmed by Tony, we do indeed have an archived plan, so clewis has updated the severity accordingly.

The main consequence I can see is: a user is subscribed to an archived plan. Since the /plans endpoint doesn’t return the plan, they can’t access the subscription management page unless they are subscribed to another active plan. [~accountid:60482ee0b2ea1201159d2194] are there other bugs that can occur from this?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5599)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

We should add a query string parameter to allow filtering on the endpoint and will need to add the active status to each plan in the response.

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

If a RP archives a plan with active subscribers before this is resolved, affected users will not be able to access the manage subscription page, and this issue will increase in severity to S2

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I think it’s also possible that the subscribed product won’t show on the drop-down of the Support Form.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

There is an archived plan today from VPN - specifically the 4.99 monthly plan - which has current users on it. I’ve raised this to an S2 according to our prior ticket.

Ivo Plamenac Considering the priority of this ticket and expected real impacts to users today vs. https://mozilla-hub.atlassian.net/browse/FXA-5587?atlOrigin=eyJpIjoiYjU1ZDM0ZjRjOTViNGQ0OTk0M2QyM2I1YjZhNDUyYjYiLCJwIjoiaiJ9 ( https://mozilla-hub.atlassian.net/browse/FXA-5587?atlOrigin=eyJpIjoiYjU1ZDM0ZjRjOTViNGQ0OTk0M2QyM2I1YjZhNDUyYjYiLCJwIjoiaiJ9|smart-link )  - in which we cannot reproduce with other accounts, and that it is a test account configured differently than other accounts, I would suggest perhaps we kick that issue out as not able to repro and pick this up on your triage duty instead. Thoughts?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Chelsea Lewis Can you link to the plan in the Stripe dashboard? I don’t see any archived plans for VPN in prod other than “FPN Trial”, https://dashboard.stripe.com/prices/price_1H2k21JNcmPzuWtRvvC4VW7M ( https://dashboard.stripe.com/prices/price_1H2k21JNcmPzuWtRvvC4VW7M ), which has 0 active subscriptions.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Upon further investigation, this is again being reduced to an S3 priority as it is not impacting users. https://dashboard.stripe.com/prices/plan_FvnxS1j9oFUZ7Y ( https://dashboard.stripe.com/prices/plan_FvnxS1j9oFUZ7Y ) is the plan that was noted as archived by Product but not in fact in Stripe. Once this ticket is completed, let’s inform Tony Cinotto so that he can follow-through and Archive in Stripe.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
