### ISSUE TITLE
In settings, letters like “g”, “q” and "y" have the bottom part cut off.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1373]
Originally reported in https://github.com/mozilla/blurts-server/issues/954 by @obotisan.

<img src="https://user-images.githubusercontent.com/42799381/57934969-6b91fd00-78c9-11e9-94fc-31b48d1e1dd5.png" />

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-116)
┆Issue Number: FXA-116

**Comment by Shubhamchinda** [comment]
Hey can I take this issue?

**Comment by shane-tomlinson** [comment]
@Shubhamchinda - you sure can!

**Comment by clouserw** [comment]
@Shubhamchinda are you still working on this?

**Comment by jodyheavener** [comment]
I'm curious if this is still an issue. I can't replicate it in any browser on macOS.

**Comment by vasilicatamas** [comment]
This issue was fixed and verified in #4173. Closing this bug as duplicate.
