### ISSUE TITLE
[customs-server] Add joi validation to routes for Swagger

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13740]
The routes in customs-server do not include any validation. 

There was an attempt to add validation when trying to implement Swagger, in order to include definitions/descriptions (e.g., `.description(DESCRIPTION.email)`). However, this caused invalid requests from gql-api.

The current fix to include definitions/descriptions is to add the text into the `notes` or `response` section in the Swagger API docs. However, do we want to add joi validation (and descriptions) to fxa-customs-server as we have in other routes in fxa-auth-server, or are we fine with not having joi validation for these routes and keeping definitions in the Swagger doc?

* Example of route in fxa-customs-server

```
  api.route({
    method: 'POST',
    path: '/check',
    handler: async (req, h) => {
      ...
    },
  });
```

* Example of route in fxa-auth-server

```
{
      method: 'POST',
      path: '/account/destroy',
      options: {
        ...ACCOUNT_DOCS.ACCOUNT_DESTROY_POST,
        auth: {
          mode: 'optional',
          strategy: 'sessionToken',
        },
        validate: {
          payload: isA.object({
            email: validators.email().required().description(DESCRIPTION.email),
            authPW: validators.authPW.description(DESCRIPTION.authPW),
          }),
        },
      },
      handler: (request: AuthRequest) => accountHandler.destroy(request),
    },
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5600)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
