### ISSUE TITLE
[subplat][product-config] Add script to load Product Config from private repo into local Firestore

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13743]
**Background**

Soon the [Payment Config management repo](https://github.com/mozilla/fxa-payment-config-manage) will be used to maintain the Product and Plan configuration data stored in Firestore. 

Currently during local development we don’t have an easy way to load the data into our local Firestore, except to pull it from Stripe Metadata, using the existing conversion script.

**Requirements**

Create a script to load JSON data from the [Payment Config management repo](https://github.com/mozilla/fxa-payment-config-manage) into local firestore.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5601)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
