### ISSUE TITLE
Review the Playwright migration tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13747]
For the FxA Engg team - This is the draft sheet I created for all the functional tests we currently have and are running on CircleCi [https://docs.google.com/spreadsheets/d/11Wq-Y-ipeNFXqLHbr3GJCh_f_qEAG-CUuqBt5Dcnh5k/edit#gid=0](https://docs.google.com/spreadsheets/d/11Wq-Y-ipeNFXqLHbr3GJCh_f_qEAG-CUuqBt5Dcnh5k/edit#gid=0|smart-link) . There are 3 sections - Keep, remove and Not sure. Please kindly review the sheet to make sure if you agree with the tests to keep and remove and also to decide what should we do with the Not sure tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5602)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Ankita Shrivastava where do you want the engineers to leave feedback?  If in the Google sheet, can you ensure the engineers have edit access on it?

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

Barry Chen My apologies, I gave the edit access to everyone now on the sheet. Yes, you can create a separate column on the sheet for your feedback. Thank you!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
