### ISSUE TITLE
[subplat][tailwind] Component - DialogMessage - Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13754]
`DialogMessage` and `Modal` can become the same component.

(Initially a part of [https://mozilla-hub.atlassian.net/browse/FXA-2463](https://mozilla-hub.atlassian.net/browse/FXA-2463|smart-link), however it is its own task)

**Requirements**

* Replace all CSS/SCSS with Tailwind utility classes
* Remove .css and .scss files
* Rework Storybook files as discussed in [https://mozilla-hub.atlassian.net/browse/FXA-5080](https://mozilla-hub.atlassian.net/browse/FXA-5080|smart-link)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5604)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
