### ISSUE TITLE
[subplat] [intermittently] “Error confirming subscription..” page displayed instead of Subscription Confirmation page after reconnecting to the internet

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13757]
**Affected FxA versions:**

* 1.237.3;

**Prerequisites:**

* Be in a country where Mozilla VPN is available;

* Be on the new Set up your subscription page;

**Steps to reproduce:**

1. Fill in all the mandatory fields with valid credentials;
1. Click on the “Subscribe Now” button and quickly disconnect from the internet;
1. Click on the “Try again” button;
1. Reconnect to the internet;
1. Click on the “Subscribe Now” button;
1. Observe the behavior;

**Expected result:**

* The user is redirected to the Subscription Confirmation page. 

**Actual result:**

* The user is redirected to the “Error confirming subscription..” page. 

**Notes:**

* The Welcome email and Payment confirmation email are being received;

* This reproducing intermittently and the behavior is not the same every time when disconnecting from the internet;

* Reproducible for the old flow as well (intermittently); 

* See the attached video;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5606)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26828">Screen Recording 2022-07-26 at 16.03.31.mov</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
