### ISSUE TITLE
Duplicate subscription with refresh

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13755]
It is possible to create a duplicate subscription during sign-up. We don't know exactly how this happened, but its not clear to the user this has happened until they get billed twice.

We use an imdepotency key on the front-end, but this is somehow being lost or not fulfilling its purpose.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2574)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26826">bandicam 2022-07-26 13-36-35-689.mp4</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26825">Screen Shot 2022-07-26 at 15.38.55.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@ValentinaPC This looks pretty important but we haven't reproduced it.  Are you able to explore this area a bit and see if you can get some STR? Thank you

/cc @rbillings @jackiemunroe @chenba

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

bq. We use an imdepotency key on the front-end, but this is somehow being lost or not fulfilling its purpose.

The nonce / idempotency key is generated on every page load. It's also re-generated on subscription retry after errors. It's meant to prevent duplicate submissions from the current immediate interaction - e.g. issue 4386 double clicks on the submit button ( https://github.com/mozilla/fxa/issues/4386 ). We don't store it in localstorage or retain it on refresh in any way, because it wasn't meant for use beyond a single API call.

I'm not sure the idempotency key would help prevent this, though.

Maybe what we need to do is retain _the invoice ID_ generated on initial payment submission attempt ( https://github.com/mozilla/fxa/blob/80ae4c1536aa2b97497059cf0f3957ca5b0262e9/packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx#L300-L301 ). We keep that in memory through retries ( https://github.com/mozilla/fxa/blob/80ae4c1536aa2b97497059cf0f3957ca5b0262e9/packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx#L319 ), but not in localstorage between refreshes. So, if someone tried to pay, saw an error, then refreshed and tried again - they would open a new invoice.

A few wrinkles though: If we kept the invoice around, we'd need to locally key it on product ID & plan. That way if they tried to pay for a different product, they wouldn't end up hitting a previous product they may have abandoned. Maybe an edge case, but I could see it happening if someone started to pay for bundle A but then reconsidered and went for an upgraded bundle B.

**Comment by data-sync-user** [comment]
➤ ValentinaPC commented:

> 
> 
> @ValentinaPC This looks pretty important but we haven't reproduced it. Are you able to explore this area a bit and see if you can get some STR? Thank you
> 

I will try to reproduce it.

**Comment by data-sync-user** [comment]
➤ ValentinaPC commented:

@clouserw 
I've tried different things like: re-loading the subscription page after a payment, disconnecting the internet while trying to make a subscription and reconnecting it back, clicking multiple times on the "Pay now" button, etc. None of these scenarios took me to the duplicate payment phase. Will throw an extra eye on this side, if you did not figure it out already, what was the problem.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for looking.  Based on Les's comment above it sounds like there is some surface area where this could happen, but it sounds like it's small.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

The one scenario where I think this might happen is:

  * Try to pay for a subscription with a card that causes an error
  * Get a message to try again
  * Refresh the page
  * Try again with a card that works

I haven't been able to reproduce a problem trying this myself though.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Can't reproduce.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Barry Chen , I am able to reproduce the duplicate subscription on Train 1.237.3 - Stage, while performing the next scenario:

Prerequisites: 

  * Have a FXA account without subscription;
  * Be logged in on FXA page ( https://accounts.stage.mozaws.net/settings );
  * Be on Old set up your Subscription page;

Steps:

  1. Fill in all the mandatory fields with valid credentials;
  2. Click on the “Pay now” button and quickly disconnect from the internet;
  3. Click on the “Try again” button;
  4. Reconnect to the internet;
  5. Click on the “Pay now” button;

Actual result: 

  * The user is billed twice and 2 payment confirmed / 2 welcome emails are being received for the same account; 
  * The Stripe dashboard displays the subscription 2 times;
  * The subscription is duplicated on the Subscription management page;

Used account: bhidecuti+du4@mozilla.com ( mailto:bhidecuti+du4@mozilla.com ) 

Barry Chen , I am reopening this issue. If I should file a new one, please let me know. Thank you! 

See the attached video and ss. 

!bandicam 2022-07-26 13-36-35-689.mp4|width=1920,height=1080!

!Screen Shot 2022-07-26 at 15.38.55.png|width=1675,height=655!

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Need to check in with data team to see how many users this might be affecting currently.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Further discussions on impacts here are available within slack, ping Chelsea Lewis on slack for further details. this ticket (fxa-2574) should be leveraged to restate the efficacy of the imdepotency key as mentioned in previous comments, or alternate measures if proposed.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
