### ISSUE TITLE
Update illustrations on all emails

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1375]
Trailhead emails are only sent if `style=trailhead` is passed to the backend. Send these emails all the time.

**Comment by shane-tomlinson** [comment]
Do the Trailhead emails work for OAuth RPs?

**Comment by clouserw** [comment]
@ryanfeeley we have an old version of these designs, but vijay wants to confirm they are right before implementing

**Comment by vbudhram** [comment]
> Do the Trailhead emails work for OAuth RPs?

Currently, they only use the new logo. The email text has not been changed.

<img width="369" alt="Screen Shot 2019-06-25 at 4 08 20 PM" src="https://user-images.githubusercontent.com/1295288/60129682-917dad80-9763-11e9-885c-5f41622082ff.png">
