### ISSUE TITLE
Allow billing-and-subscriptions endpoint to work with a reduced scope

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13764]
Firefox Relay needs to impose "monthly" call & sms limits on Relay phone numbers. To do so, it could use the `current_period_start` and `current_period_end` dates of the `/oauth/mozilla-subscriptions/customer/billing-and-subscriptions` API endpoint to determine its "remaining minutes/texts per current period".

But, the `/oauth/mozilla-subscriptions/customer/billing-and-subscriptions` endpoint requires a different scope.

So, can we reduce the scope required to hit the `/oauth/mozilla-subscriptions/customer/billing-and-subscriptions` endpoint to the same scope that Relay already has? Most likely, by removing the `billing_name`, `last4`, and other payment-related fields.

Original message from @bbangert: "I think the best solution would be to allow that endpoint to work with the reduced scope, and remove some of the unrelated info an RP doesn't need. (like billing data)"

_Issue created in Slack from a [message](https://mozilla.slack.com/archives/CG0AJ6E77/p1658864354660279?thread_ts=1658862442.746539&cid=CG0AJ6E77)._

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5607)

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

Luke Crouch do you have timeframe in mind for this?

**Comment by data-sync-user** [comment]
➤ Ivo Plamenac commented:

For the solution, we do something similar here: https://github.com/mozilla/fxa/blob/508e93ecf538dc60516084c38b51f7478afd8829/packages/fxa-auth-server/lib/routes/account.ts#L1097 ( https://github.com/mozilla/fxa/blob/508e93ecf538dc60516084c38b51f7478afd8829/packages/fxa-auth-server/lib/routes/account.ts#L1097|smart-link )

**Comment by data-sync-user** [comment]
➤ Luke Crouch commented:

ASAP as always. 🙂 But seriously, in the next 2-3 weeks if possible. I’ve got 1 more big (1-2 weeks of work) part of Relay phones that I can build before this is the last thing left to build.

**Comment by data-sync-user** [comment]
➤ Luke Crouch commented:

Any update here? I finished my other Relay work sooner than I expected. I’ve definitely got more I can do without this, but I’d like to know an ETA for this so I can plan around it.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
