### ISSUE TITLE
Share sass-lint config between content and payment servers

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1376]
Both fxa-content-server and fxa-payment-server use sass-lint for styles and have nearly identical `.sass-lint.yml` configs. An improvement would be to move to a shared config for both and tweak their respective `package.json` lint commands to specify the files processed in each package

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-117)
┆Issue Number: FXA-117

**Comment by LZoog** [comment]
Closing this - we shouldn't use sass-lint anymore, and per #5933 and #5932, we're moving content-server and payment-server to Tailwind styles.
