### ISSUE TITLE
Tailwindify remaining content-server non-password form inputs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13777]
Figma: [https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=3582%3A64626](https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=3582%3A64626|smart-link) 

We got a large chunk of the content-server converted over to Tailwind classes with [https://github.com/mozilla/fxa/pull/13739](https://github.com/mozilla/fxa/pull/13739|smart-link) . However, our email/other inputs (not password inputs, those’ll be handled in FXA-5615) are tied to a lot of styles, tooltips, and tests.

In that PR, the `input-text` class was created for this purpose but wasn’t used due to needing more adjustments for tooltips and tests.

The goal is to remove all classes that are not TW classes where possible on remaining non-password content-server inputs. Use IDs where needed for tests/JS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5616)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
