### ISSUE TITLE
Tailwindify all content-server password inputs + the PW strength balloon

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13776]
Figma: [https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=3582%3A64626](https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=3582%3A64626|smart-link) 

We got a large chunk of the content-server converted over to Tailwind classes with [https://github.com/mozilla/fxa/pull/13739](https://github.com/mozilla/fxa/pull/13739|smart-link) . However, our password inputs and the PW strength balloon are tied to a lot of styles, tooltips, and tests.

In that PR, the PW strength balloon was adjusted to visually look similar to TW styles since it was quick, but isn’t using them.

We can possibly use the `input-text` class as a base for the password inputs but we may need a new component class altogether (that can probably be removed once we convert content-server to React and create components for these things instead).

The goal is to remove all classes that are not TW classes where possible. Use IDs where needed for tests/JS.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5615)

**Comment by LZoog** [comment]
Also see this comment: https://github.com/mozilla/fxa/pull/13739#discussion_r929336972

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
