### ISSUE TITLE
[fxa-admin-panel] Tailwind: Classnames 'mt-0' could be replaced by the 'my-0' shorthand

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13786]
I was playing around with `eslint-plugin-tailwindcss` locally to try and lint Tailwind and this super minor nit was reported.

> /Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
>  242:13  warning  Classnames 'mt-0' could be replaced by the 'my-0' shorthand!  `tailwindcss/enforces-shorthand`

https://github.com/mozilla/fxa/blob/cb8621a0ba35c2f01fec8cac6f5a57e019ab7fa4/packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx#L242

Not sure I understand what the error message is saying:
> _"Classnames 'mt-0' could be replaced by the 'my-0' shorthand!"_

But I think the issue is that we're setting the following margins:
- `mt-0` (`margin-top: 0;`)
- `my-0` (`margin-top: 0; margin-bottom: 0;`)
- `mb-1` (`margin-bottom: 4px;`)

I think we can remove `my-0` since it sets the top+bottom margin which are explicitly set anyways.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5621)

**Comment by pdehaan** [comment]
Full linting output was:
```sh
yarn lint

/Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/server/lib/html-middleware.ts
  9:1  warning  Unexpected default export of anonymous function  import/no-anonymous-default-export

/Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/server/lib/server.ts
  37:7  warning  'CLIENT_CONFIG' is assigned a value but never used  @typescript-eslint/no-unused-vars

/Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/src/components/AccountSearch/Account/index.tsx
  242:13  warning  Classnames 'mt-0' could be replaced by the 'my-0' shorthand!  tailwindcss/enforces-shorthand

/Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/src/components/AccountSearch/index.tsx
  240:13  warning  Classname 'placeholder-grey-500' should be updated to 'placeholder:text-grey-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  254:18  warning  Classname 'suggestions-list' is not a Tailwind CSS class!                                              tailwindcss/no-custom-classname

/Volumes/Dev/github/mozilla/fxa/packages/fxa-admin-panel/src/components/LinkAbout/index.tsx
  11:5  warning  Classname 'align-self-center' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

✖ 6 problems (0 errors, 6 warnings)
  0 errors and 2 warnings potentially fixable with the `--fix` option.
```

The first couple warnings, `import/no-anonymous-default-export` and `@typescript-eslint/no-unused-vars`, are interesting, but unrelated to Tailwind.
The third warning, [`tailwindcss/enforces-shorthand`](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/enforces-shorthand.md), is the main issue above.
The fourth warning, [`tailwindcss/migration-from-tailwind-2`](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/migration-from-tailwind-2.md) is also interesting since we do seem to be using Tailwind@3:
	https://github.com/mozilla/fxa/blob/cb8621a0ba35c2f01fec8cac6f5a57e019ab7fa4/packages/fxa-admin-panel/package.json#L86
Not convinced about the final two warnings, [`tailwindcss/no-custom-classname`](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/no-custom-classname.md), and whether we should ignore that rule.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
