### ISSUE TITLE
Ensure fxa-payment-server is included in monorepo install & update scripts

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1378]
We added fxa-payment-server to the pm2 configs for local dev, but I don't think it's included in the install & update scripts. Or, rather, I noticed update didn't cover it - but I haven't actually tried a from-scratch install of the repo in awhile, so I assume it's missing payment server. We should make sure this is all covered.

**Comment by clouserw** [comment]
We think this is actually working, but we should verify that it works.

**Comment by chenba** [comment]
fxa-payment-server is in the install script.  However, it seems to need a build step in the pm2 config, otherwise it'd error out after `pm2 start`.  (`pm2 status` immediately after and it will have an "errored" status.)  I'll add that step to the pm2 config.
