### ISSUE TITLE
[subplat][tailwind] Mixin - checkout-title() - Class Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13782]
Once `PaymentConfirmation` , `PaymentErrorView` , and `PaymentProcessing` have all been converted:

* Replace all CSS/SCSS with Tailwind utility classes
* Remove .css and .scss files

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5619)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
