### ISSUE TITLE
[subplat][tailwind] Mixin - checkout-view() - Class Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13784]
Once `PaymentConfirmation` , `PaymentErrorView` , and `PaymentProcessing` have all been converted:

* Replace all CSS/SCSS with Tailwind utility classes
* Remove .css and .scss files

Note: 

In `PaymentProcessing`, 

* `wrapper` was updated to `flex flex-col text-center`
* `footer` was updated to `border-0 flex flex-col justify-center mt-auto pt-16`

In `PaymentConfirmation`,

* Remove margin-top in `header` in `PaymentConfirmation` component
* In `checkout-view()`, update from `padding: 0 48px 48px` to `px-12 pb-12`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5620)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
