### ISSUE TITLE
"Reset password" link doesn’t expire after 1 hour

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13794]
**Build:**

Production [Train 237.5]

**Affected platforms:**

Windows 10 64-bit

macOS 12.4

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

* Have a FxA account previously created and logged in at least once;

**Steps to reproduce:**

1. Go to [https://addons.mozilla.org/en-US/firefox](https://addons.mozilla.org/en-US/firefox|smart-link) ;
1. Click on Log In  in the upper right corner;
1. Click on Forgot Password on the newly opened page;
1. Open emails and verify if password reset email has been received;
1. Wait for over an hour and click on reset password button from the email received;

**Expected result:**

* “Reset password link expired” error message is displayed;

**Actual result:**

* “Reset password” link is not expired and allows for the process to continue;

**Notes:**

* Have made 3 attempts after 1h7m, 1h8m, 1h24m from requesting and receiving the email to actually pressing the button, with the same result;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5622)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27080">Screenshot 2022-08-03 at 11.00.14.png</a>

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Found an older task ( https://mozilla-hub.atlassian.net/browse/FXA-3812 ) that might be related to this, but it is in To Do, so no clear resolution there.

Thank you.

CC: Bianca Oltean

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Bianca Oltean Can you see if the link expires the next day?

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Barry Chen As per your request I've started the password reset process yesterday and have only just clicked the password reset link today, roughly 24h later. Password link has indeed expired but requesting and accessing the new one leads to an error - bug filed here ( https://mozilla-hub.atlassian.net/browse/FXA-791 ) but cancelled.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Thank you, Bianca.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
