### ISSUE TITLE
Verify untranslated alt, placeholder, and title attributes

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13807]
## Description

Spotted an untranslated attribute in an unrelated PR so I did some poking around a Perl regexp to try and find potentially untranslated `alt=""`, `placeholder=""`, and `title=""` attributes.

### Steps to reproduce

```sh
git grep -PEon '\b(alt|placeholder|title)="(.*?)"' -- ':!**/test/**' ':!123done/**' ':!*.ftl' ':!*.md' ':!*.stories.tsx' ':!*.test.tsx' ':!**/.storybook/**' | grep -v 'alt=""'  | grep -v "{{#t}}"
```

**NOTE:** I reckon we can ignore things in the packages/fxa-admin-panel/** folder.

| FILE | STRING
|:----|:----
fxa-admin-panel/src/components/AccountSearch/index.tsx:238|`placeholder="Email or UID"`
fxa-admin-panel/src/components/AccountSearch/index.tsx:244|`title="search"`
fxa-admin-panel/src/components/AccountSearch/index.tsx:250|`alt="search icon"`
fxa-admin-panel/src/components/LinkAbout/index.tsx:18|`alt="external icon"`
fxa-admin-panel/src/components/Nav/index.tsx:34|`alt="account icon"`
fxa-admin-panel/src/components/Nav/index.tsx:49|`alt="key icon"`
fxa-admin-panel/src/components/Nav/index.tsx:63|`alt="logs icon"`
fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:36|`alt="Firefox logo"`
fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:37|`title="Firefox logo"`
fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:43|`alt="Sync devices"`
fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:44|`title="Sync devices"`
fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:42|`alt="Firefox logo"`
fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:43|`title="Firefox"`
fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:115|`alt="Mozilla logo"`
fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:116|`title="Mozilla"`
fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml:20|`alt="Download <%- locals.productName %> on the App Store"`
fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml:32|`alt="Download <%- locals.productName %> on Google Play"`
fxa-auth-server/lib/senders/emails/partials/icon/index.mjml:9|`alt="<%- productNameOld %>"`<br/>`title="<%- productNameOld %>"`
fxa-auth-server/lib/senders/emails/partials/icon/index.mjml:13|`alt="<%- productName %>"`<br/>`title="<%- productName %>"`
fxa-auth-server/lib/senders/emails/partials/icon/index.mjml:19|`alt="<%- productName %>"`<br/>`title="<%- productName %>"`
fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.mjml:11|`alt="Devices"`
fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.mjml:10|`alt="Devices"`
fxa-auth-server/lib/senders/emails/templates/postVerify/index.mjml:13|`alt="Devices"`
fxa-content-server/app/crash.html:19|`alt="Server Error - We apologize for the inconvenience"`
fxa-content-server/app/scripts/templates/inline_totp_setup.mustache:52|`alt="{{ qrImageAltText }}"`
fxa-content-server/app/scripts/templates/test_template.mustache:48|`placeholder="Old password"`
fxa-content-server/app/scripts/templates/test_template.mustache:49|`placeholder="New password"`
fxa-content-server/app/scripts/templates/test_template.mustache:59|`placeholder="placeholder text"`
fxa-content-server/tests/functional/lib/selectors.js:58|`title="Incorrect password"`
fxa-payments-server/src/components/CouponForm/index.tsx:223|`placeholder="Enter code"`
fxa-payments-server/src/components/Header/index.tsx:27|`title="firefox"`
fxa-payments-server/src/components/NewUserEmailForm/index.tsx:162|`alt="shield"`
fxa-payments-server/src/components/PaymentConfirmation/index.tsx:87|`alt="circled checkbox"`
fxa-payments-server/src/components/PaymentConfirmation/index.tsx:101|`alt="checkmark icon"`
fxa-payments-server/src/components/PaymentConfirmation/index.tsx:105|`alt="email sent icon"`
fxa-payments-server/src/components/PaymentErrorView/index.tsx:92|`alt="error icon"`
fxa-payments-server/src/components/PaymentForm/index.tsx:217|`placeholder="Full Name"`
fxa-payments-server/src/components/PlanErrorDialog/index.tsx:26|`title="Problem loading plans"`
fxa-payments-server/src/routes/Product/AcceptedCards/index.tsx:13|`alt="visa"`
fxa-payments-server/src/routes/Product/AcceptedCards/index.tsx:14|`alt="mastercard"`
fxa-payments-server/src/routes/Product/AcceptedCards/index.tsx:15|`alt="discover"`
fxa-payments-server/src/routes/Product/AcceptedCards/index.tsx:16|`alt="american express"`
fxa-payments-server/src/routes/Product/index.tsx:199|`title="Problem loading profile"`
fxa-payments-server/src/routes/Product/index.tsx:216|`title="Problem loading customer"`
fxa-payments-server/src/routes/Subscriptions/PaymentUpdateForm.tsx:249|`alt="error icon"`
fxa-payments-server/src/routes/Subscriptions/index.tsx:163|`title="Problem loading profile"`
fxa-payments-server/src/routes/Subscriptions/index.tsx:176|`title="Problem loading plans"`
fxa-payments-server/src/routes/Subscriptions/index.tsx:193|`title="Problem loading customer"`
fxa-payments-server/src/routes/Subscriptions/index.tsx:206|`title="Problem loading invoices"`
fxa-react/components/LogoLockup/index.tsx:19|`alt="Firefox logo"`
fxa-settings/src/components/Avatar/index.tsx:24|`alt="Your avatar"`
fxa-settings/src/components/Avatar/index.tsx:40|`alt="Default avatar"`
fxa-settings/src/components/BentoMenu/index.tsx:60|`title="Close"`
fxa-settings/src/components/ConnectAnotherDevicePromo/index.tsx:71|`title="Download Firefox on Google Play"`
fxa-settings/src/components/ConnectAnotherDevicePromo/index.tsx:86|`title="Download Firefox on the App Store"`
fxa-settings/src/components/ConnectedServices/index.tsx:200|`title="Refresh connected services"`
fxa-settings/src/components/GetDataTrio/index.tsx:54|`title="Download"`
fxa-settings/src/components/GetDataTrio/index.tsx:75|`title="Copy"`
fxa-settings/src/components/GetDataTrio/index.tsx:98|`title="Print"`
fxa-settings/src/components/HeaderLockup/index.tsx:43|`title="Back to top"`
fxa-settings/src/components/PageAvatar/buttons.tsx:55|`title="Remove photo"`
fxa-settings/src/components/PageAvatar/buttons.tsx:79|`title="Take photo"`
fxa-settings/src/components/PageAvatar/buttons.tsx:122|`title="Add photo"`
fxa-settings/src/components/PageAvatar/buttons.tsx:175|`title="Zoom Out"`
fxa-settings/src/components/PageAvatar/buttons.tsx:189|`title="Zoom In"`
fxa-settings/src/components/PageAvatar/buttons.tsx:203|`title="Rotate"`
fxa-settings/src/components/PageAvatar/index.tsx:307|`alt="new avatar"`
fxa-settings/src/components/PageAvatar/index.tsx:316|`title="Profile picture"`
fxa-settings/src/components/PageChangePassword/index.tsx:104|`title="Change password"`
fxa-settings/src/components/PageCreatePassword/index.tsx:74|`title="Create password"`
fxa-settings/src/components/PageDeleteAccount/index.tsx:113|`title="Delete account"`
fxa-settings/src/components/PageDisplayName/index.tsx:69|`title="Display name"`
fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx:118|`title="Recovery key"`
fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx:72|`title="Secondary email"`
fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx:93|`title="Secondary email"`
fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx:184|`title="Remove email"`
fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx:195|`title="Refresh email"`
fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx:267|`title="Remove email"`
fxa-settings/src/components/UnitRowSecondaryEmail/index.tsx:279|`title="Refresh email"`
fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx:89|`title="Refresh two-step authentication"`
fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx:105|`title="Refresh two-step authentication"`

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5635)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Sometimes the alt text should be an empty string.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

A lot of those grep results are false positives, when Fluent is used.
