### ISSUE TITLE
Account Blocked on Bounced Email Error Page Erroneously Displayed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13806]
I don’t know the exact steps to reproduce.  The account I used has 2FA enabled (and it’s an @mozilla.com email).  I was doing some testing to verify whether signing into an OAuth RP would also sign the user into FxA.  Even though I received the error page (img attached) my account was not blocked and I did not see any email bounces for the account in the admin panel.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5634)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26980">image (2).png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Assuming we’re talking about your work email with no “+” extensions in it, I see 4 successful deliveries last week, all for new devices logging in, one on the 26th and three on the 29th.

I don’t see any bounces in the logs.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Thanks for checking.  Yes, it was my work email without any “+” labels.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
