### ISSUE TITLE
New email: account deletion notice

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13808]
We will soon begin [deleting accounts](https://mozilla-hub.atlassian.net/browse/FXA-5312) that are not verified after 16 days to cut down on unused or fraudulent accounts. As a result, we need to inform the user that their account will be deleted 1 day prior to the deletion. 

【 highlighted #ff5630 】Email name:【 end highlighted 】 **fxa / verificationReminderFinal**

【 highlighted #ff5630 】Condition:【 end highlighted 】 Final reminder sent to users that have not verified their account, sent 15 days after initial attempt. 

【 highlighted #ff5630 】Subject:【 end highlighted 】 Final reminder to confirm your account

HTML Body:

A couple of weeks ago you created a Firefox account, but never confirmed it. For your security, we will delete the account if not verified in the next 24 hours.

Button:

[+Confirm account+](http://localhost:3030/verify_email)

<Footer Component>

TXT Body:

A couple of weeks ago you created a Firefox account, but never confirmed it. For your security, we will delete the account if not verified in the next 24 hours. 

Confirm account: [+http://localhost:3030/verify_email+](http://localhost:3030/verify_email)

<Footer Component>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5636)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
