### ISSUE TITLE
Send.firefox.com: when attempting to log in - System unavailable, try again soon error 

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/fxa#1381]
State: 
* Firefox Account exists, and is verified
* Firefox Account password is saved in Firefox 

Steps: 
1. Go to https://send.firefox.com/
2. Select "Sign In" from the upper right corner of the page
3. Type first letter of my account email address, then choose suggested email
4. Select "Sign in", page loads with my email address present and the password autofilled
5. Select "Sign in" again

*Expected outcome*: Sign in happens, and goes back to the page where I can upload files
*Actual outcome*: Red error message appears "System unavailable, try again soon" 
*Workaround*: Try signing in a second time, and error goes away.

*Reproducing error*: Sign out of Send *and restart browser*, then try signing into Send again. 

<img width="508" alt="Error message on sign in screen on Send" src="https://user-images.githubusercontent.com/911251/58890325-43fbac80-869f-11e9-8d27-b8a3d91d3096.png">

<img width="1440" alt="Console error details" src="https://user-images.githubusercontent.com/911251/58890340-4bbb5100-869f-11e9-9cd7-d212404c5cc9.png">

<img width="1440" alt="Requests tab of console showing mostly 200 OKs and one red line with System unavailable, try again later" src="https://user-images.githubusercontent.com/911251/58890355-5249c880-869f-11e9-9aff-a9074b771b39.png">

**Comment by jenniferdavidson** [comment]
I don't know if this is helpful at all but another thing to note is that I signed into Monitor with no issue before signing into Send

**Comment by devinreams** [comment]
I believe similar was encountered when signing in via Lockwise:
https://github.com/mozilla-lockwise/lockwise-ios/pull/1043#issuecomment-498655312

**Comment by vladikoff** [comment]
This was fixed 👍

**Comment by vladikoff** [comment]
@jbuck does the timing for https://github.com/mozilla-lockwise/lockwise-ios/pull/1043#issuecomment-498655312 align with the fix we discussed?

**Comment by jbuck** [comment]
Yeah, the occurs were occurring on 2019-06-04 from 11:15AM UTC to 3:35PM UTC. 3-6% of all requests were failing
