### ISSUE TITLE
[subplat][tailwind] Element - CTAs - Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13811]
Update CTAs (links and buttons) to match recent updates to fxa-settings as per [https://mozilla-hub.atlassian.net/browse/FXA-5454](https://mozilla-hub.atlassian.net/browse/FXA-5454|smart-link).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5637)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
