### ISSUE TITLE
[subplat][tailwind] Element - fields - Conversion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13812]
Update form elements and input fields to match recent updates to fxa-settings as per [https://mozilla-hub.atlassian.net/browse/FXA-5454](https://mozilla-hub.atlassian.net/browse/FXA-5454|smart-link).

Note: Component with styles for `fields`

* NewUserEmailForm

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5638)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
