### ISSUE TITLE
Make sure IAP route has the correct scope for access token from account/stub

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13815]
The RP mobile client will obtain an access token from the account/stub endpoint for subsequent API calls. Unlike the new user (aka “passwordless”) flow on the payments server, the client will then be hitting our IAP registration endpoints once an IAP user subscribes via Google or Apple IAP.

We should make sure that the IAP route to which these endpoints belong has the correct scope for this access token.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5640)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
