### ISSUE TITLE
ValidationError: "clientId" with value "guardian-vpn" fails to match the required pattern: /[a-z0-9]{16}/

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13819]
Sentry Issue: [FXA-EVENT-BROKER-19](https://sentry.io/organizations/mozilla/issues/3467882684/?referrer=jira_integration)

```
ValidationError: "clientId" with value "guardian-vpn" fails to match the required pattern: /[a-z0-9]{16}/
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5643)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
