### ISSUE TITLE
[subplat] bump @storybook/html from 6.4.13 to 6.5.9 breaks Payments Storybook

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13814]
**Background**

The pull request mentioned below seems to break Storybook for `fxa-payments-server`.

**Requirements**

Investigate why this bump causes an issue only in `fxa-payments-server`. It can be reproduced locally. (Note that Storybook builds correctly, and the error is shown in the browser console)

[https://github.com/mozilla/fxa/pull/13751](https://github.com/mozilla/fxa/pull/13751|smart-link)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5639)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
