### ISSUE TITLE
FxA rejecting with error UNVERFIED_ACCOUNT

### ISSUE THREAD

**Issue by Joel-Muller** [mozilla/fxa#13822]
## Description

1659381723065	FirefoxAccounts	ERROR	FxA rejecting with error UNVERIFIED_ACCOUNT, details: undefined
1659381723065	FirefoxAccounts	ERROR	Background refresh of initial profile failed: Error: UNVERIFIED_ACCOUNT(resource://gre/modules/FxAccounts.jsm:1536:18) JS Stack trace: _error@FxAccounts.jsm:1536:18

### Steps to reproduce

Install firefox-syncstorage from AUR on ArchLinux 5.18.15 Kernel

### Expected result

No Error!

### Actual result

1659381723065	FirefoxAccounts	ERROR	FxA rejecting with error UNVERIFIED_ACCOUNT, details: undefined
1659381723065	FirefoxAccounts	ERROR	Background refresh of initial profile failed: Error: UNVERIFIED_ACCOUNT(resource://gre/modules/FxAccounts.jsm:1536:18) JS Stack trace: _error@FxAccounts.jsm:1536:18

### Environment

Firefox 103.0.1 (64-Bit)
ArchLinux Kernel 5.13.15
firefox-syncstorage form aur.archlinux.org
[error-sync-1659381747807.txt](https://github.com/mozilla/fxa/files/9236869/error-sync-1659381747807.txt)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5646)

**Comment by clouserw** [comment]
Hi @Joel-Muller.  Thanks for filing this, unfortunately we didn't create and we don't maintain any firefox-syncstorage packages (or any packages on AUR) so I'm going to wontfix this.  Reaching out to the maintainer of the package may help.
