### ISSUE TITLE
[documentation] Allow API docs to be publicly reachable

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13824]
When we deploy, push API doc files to a publicly reachable area (e.g, the CDN):

* schema.gql file to URL in order for GQL to auto-generate documentation
* Customs Server API Swagger JSON file (localhost:7000/swagger.json)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5648)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing this.  In https://mozilla-hub.atlassian.net/browse/FXA-4627 ( https://mozilla-hub.atlassian.net/browse/FXA-4627|smart-link ) Ben describes how the GQL schema is generated:

{quote}When the fxa-graphql-api application is started and generates its dist/, a schema.gql is created there with the graphql schema.{quote}

As part of our build process, I’d like to copy that gql file to somewhere publicly accessible so we can use it in our ecosystem documentation.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
