### ISSUE TITLE
[swagger] Customs Server API doc: Follow-up items

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13834]
Once the Customs Server API Swagger JSON file is publicly reachable:

* In Ecosystem Platform
  * Add Customs Server API Swagger JSON file to `docusaurus.config.js` and `sidebars.js`
  * Update link to Customs Server API doc from fxa repo to link in Ecosystem Platform in `additional-docs.md` 
* In FxA
  * Remove Customs Server’s `api.md` 
  * Redirect link to Customs Server API doc in `README.md`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5652)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
