### ISSUE TITLE
[subplat] Prettify json files in fxa-payment-config-manage 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13842]
**Background**

Ensure that all files added to fxa-payment-config-manage are prettified so that it’s easier to see differences, and maintain files.

**Requirements**

When a pull request is opened or changed, prettify the `JSON` files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5655)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
