### ISSUE TITLE
[subplat] Re-run conversion script for Local and STAGE

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13843]
**Requirements**

* Rerun the conversion script for Local and STAGE and upload the files

**Additional Notes**

* This effort does not require SRE involvement
* Instructions on how to run the Script can be found in the [Payment Config Manage repo README](https://github.com/mozilla/fxa-payment-config-manage)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5656)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
