### ISSUE TITLE
The “You have switched to” email is received instead of the “You have upgraded to” email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13852]
**FxA version:**

* 1.237.5;

**Prerequisites:**

* Be localized in US;
* Have an upgrade made from a low monthly bundle plan to a high monthly bundle plan OR from a low monthly bundle plan to a yearly bundle plan;

**Steps to reproduce:**

1. Access the email client;
1. Open the “You have switched to VPN+Relay Security Bundle” email;
1. Observe the email subject;

**Expected result:**

* The received email subject reflects the action made: upgrade;

**Actual result:**

* The received email says that you have switched instead of upgraded;

**Notes:**

* See the attached screenshot;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5659)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27088">Screenshot 2022-08-03 155458.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I’m marking this subscription platform because it sounds like the emails all exist correctly but the wrong one is being sent.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
