### ISSUE TITLE
[Subplat] Write tests for expired coupons

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13856]
As part of the epic linked to increase subplat automation coverage, write tests for expired coupons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5662)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
