### ISSUE TITLE
Device is showing as active 2/3 years ago, when the account is signed in and syncing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13853]
(This bug was originally filed in Bugzilla: [https://bugzilla.mozilla.org/show_bug.cgi?id=1782476](https://bugzilla.mozilla.org/show_bug.cgi?id=1782476|smart-link).) 

flod reported that

{quote}Testing a local build, I've signed in into my Firefox account, which is already used on a mobile browser (Firefox Nightly).

In Firefox View I have the list of tabs in "Tab Pickup", but below I still have the `Grab tabs from your phone or tablet` promo. Not sure if that's because I'm using nightly and not release.

… the problem is that Firefox Accounts thought my phone was last active 2 years ago, when the account was connected and synced only 5 minutes before.

Disconnecting Nightly and reconnecting refreshed the list, and the banner was correctly dismissed.

The other interesting thing is that before I had 2 entries (Firefox Nightly, Nightly). After disconnecting and reconnecting I only have one (Firefox Nightly).{quote}

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5660)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
