### ISSUE TITLE
Rewrite settings display name tests and change email tests in playwright

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13855]
As part of the playwright test migration, I am taking chunks of tests and rewriting them. So I will be taking on the display name and change email tests first.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5661)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
