### ISSUE TITLE
Update `link-grey` hover/focus states + `link-blue` focus state

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13865]
Figma: [https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=7688%3A154030](https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=7688%3A154030|smart-link) 

`link-grey` does not currently have hover or active states, and its focus state turns blue. On top of this, we have a huge jump in color from `grey-500` to `grey-600`. We should replace all instances using `grey-600` across the codebase to `grey-900`, modify the shared Tailwind config file, and add the two new grey hex colors as `grey-600` and `grey-700` (or whatever values make sense depending on the shade). We can then create all 3 of these states for `link-grey` across the codebase. You might let Subplat know (specifically Reino, Lisa, and Meghan) when this is done since they’ve been restyling all of their components with Tailwind and we don’t want any surprises on that shade update.

`link-blue` needs a `:focus` and/or `:focus-visible`) state matching Figma too. If you check content-server you’ll see these links visually have a nice looking focus state similar to Figma, but that’s because they’re pulling styles from the old SCSS (`main.css`) and should instead be pulling from our CSS/Tailwind classes. You can see this more pronounced in Settings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5668)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
