### ISSUE TITLE
Update `cta-primary` focus state and content-server border-radius, .card box-shadow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13866]
Figma for .card and button border-radius: [https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=7688%3A154030](https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=7688%3A154030|smart-link)

Figma focus states: [https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=7688%3A154030](https://www.figma.com/file/SE4xHgOW84yLiv7vFugm9R/Firefox-View-Stepping-Stone?node-id=7688%3A154030|smart-link) 

`:focus` (and/or `:focus-visible`) what’s seen when tabbing to our buttons (cta-primary, cta-neutral, cta-primary), currently uses the system color outline. We should update this to match what’s in Figma and ensure it looks good in content-server and Settings. (the other ticket addresses focus state for links)

Also, the border-radius for content-server buttons needs to be updated from `rounded` to `rounded-md` (6px). You should be able to add `rounded-md` to `.cta-xl`. 

Then, we need to update the box-shadow on `.card`. The easiest way is to just replace what’s already set in `flows.css` (Design updated the box-shadow recently and forgot to mention it), however, please check for the Tailwind defaults for box-shadows. If one of them looks very similar, we should ask Jihwan K. if it’s acceptable to use that TW default class instead, but he mentioned this was used somewhere in Firefox’s design system so he’ll probably prefer the custom one. One thing I was torn on here was if we should add a custom box-shadow to content-server’s Tailwind configuration file instead so we can do something like `@apply mobileLandscape:ff-shadow-xl` or some similar name to `.card` - it's more Tailwindy to edit the config file, but if we'll never use this anywhere else, then eh. I'll leave this up to the engineer working on it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5669)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
