### ISSUE TITLE
Account creation screen - Add "Addresses" as sync option

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13862]
1- Initiate “sign in” from the desktop toolbar menu

2- Choose “use a different account” and enter a new email alias

3- On the account/password creation page, “Addresses” is not listed as a sync option. 

**On the account creation screen, let’s add “Addresses” as a Sync option. This is already the case in the Sync settings.**

!image-20220803-192510.png|width=696,height=275!

!image-20220803-183726.png|width=936,height=224!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5665)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27118">image-20220803-183726.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27122">image-20220803-192510.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
