### ISSUE TITLE
Update StripeHelper subscription create functions for automatic_tax

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13868]
Both the `createSubscriptionWithPMI` and `createSubscriptionWithPaypal` helper functions need updates to allow them to set the subscription to have `automatic_tax` set to enabled if a new parameter `automaticTax` is set to `true`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5671)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
