### ISSUE TITLE
[subplat] Contact support form has display and layout issues

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13873]
**Affected FxA versions:**

* 1.238.0;

**Prerequisites:**

* Have a FXA account with an active subscription for Mozilla VPN;

* Be on [+Subscription Management Page+](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions);

**Steps to reproduce:**

1. Click on the “Contact Support” button;
1. Observe the Contact support form;
1. Fill in all the mandatory fields and click on the “Send” button;
1. Observe the behavior and the confirmation pop-up displayed on the screen;

**Expected result:**

* _For step 2_: There are no layout or format issues;

* _For step 4_: After clicking on the “Send” button, there are no layout issues. Same for the confirmation pop-up;

**Actual result:**

* _For step 2_: There are a few layout issues: 
  * The Firefox logo and title have a smaller dimension than usual;
  * The options from the breadcrumb menu are displayed in black instead of blue (same for ToS and PN );
  * The Firefox logo is displayed on top of the Contact support form;
  * “Contact us” title is centered, instead of being left aligned / “What are you contacting us about?” / What do you need help with?” / “Subject (optional)” / “Description of issue” titles are centered, instead of being left aligned. The placeholders for the first 2 fields and the options from the drop-down menu are centered, instead of being left aligned;
  * “Cancel” and “Sent” do not have the layout of buttons and user cannot see if/when active;

* _For step 4_: The “Send” button disappears for a second. Inside the popup - there is no space between the title and the first line of the informational text. “Back to Subscriptions” button is left aligned, and does not have a button layout.    

**Notes:**

* The Subscription Management page also displays the Firefox Account title and user email address in larger and bold font. The “Subscriptions” string is also larger than usual - not sure if this is an issue or not;

* See the attached ss;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5673)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27138">Screen Shot 2022-08-04 at 12.59.30.png</a>

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Bianca Hidecuti was this present in production with 237? I’m trying to identify if this is a regression or not.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Chelsea Lewis Hello, this was not present in Production train 237. At the time this was logged, we used prod environment to compare.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Thank you for that, Valentina Virlics - I’ve added the regression label accordingly.

Reino Muhl , I believe these may be related to the fxa-5080 effort, does that seem right to you? I know we made an explicit decision that some minor UI changes would be expected/appropriate to ensure the effort can push forward. Would you assess these with that in mind and let me know your thoughts?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
