### ISSUE TITLE
UI issue on the "Create new password" page - the title has a small font size and space is missing between text and the fields

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13874]
**Build:**

Stage [Train 238]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user is logged in to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net).

The user has Recovery key enabled.

**Steps to reproduce:**

1. Go to Password section and click “Change“.
1. Click “Forgot password?“ link.
1. Enter your email and then click the “Begin reset“ button.
1. Go to your inbox and open the “Reset your password” email.
1. Click the “Create new password“ button from email.
1. Enter the recovery key and click “Confirm recovery key“.
1. Observe the “Create new password” page.

**Actual result:**

The title has a small font size and there’s no space between text and the fields below.

**Expected result:**

The title’s font size is bigger and there’s space between text and the fields below.

**Notes:** 

Same font size issue occurs when user changes the pwd without Recovery key enabled.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5674)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27146">Create new pwd screen UI issue.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27147">create new pwd screen UI issue 2.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
