### ISSUE TITLE
Sync options name difference on Sync settings page and 'Set your password' page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13876]
**Build:**

Stage [Train 238]

**Affected platforms:**

Windows 10 64-bit

**Browsers tested on:**

Firefox, latest release

**Preconditions:**

The user doesn’t have a Fx account.

**Steps to reproduce:**

1. Launch Firefox with a new browser profile.
1. Click the Hamburger menu in the upper right hand corner.
1. Click Sign in.
1. Enter an email address that doesn’t have associated a Fx account and click ‘Sign up or sign in’.
1. Observe the sync options on ‘Set your password’ page.
1. Go to about:preferences#sync and observe the sync options here.

**Actual result:**

On ‘Set your password’ page we have ‘Preferences’ as option while on Sync settings page we have 'Settings' as option.

**Expected result:**

Same name option is used in both places.

**Notes:**

Maybe the order of the sync options could be changed to be similar in both places?!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5675)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27149">sync options small diff.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
