### ISSUE TITLE
Include Stripe Tax on subcription emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13877]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5676)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Quoting myself from Slack:

{quote}subscriptionFirstInvoice and subscriptionSubsequentInvoice

Looks like there are also discount versions of each of those emails as well{quote}

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
