### ISSUE TITLE
[subplat][tailwind] Footer/Legal - Update classes/styles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13883]
Update footer styles to match (font styles and spacing) and add to tailwind.css.

Affected components:

* PaymentConfirmation
* PaymentErrorView
* Payment Processing

Affected routes (all):

* Product
* Checkout
* Subscriptions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5678)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
