### ISSUE TITLE
[subplat] Breadcrumb menu option are no longer a link after browser resize

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13895]
**Affected versions:**

* FxA Stage   

**Tested Platforms:**

* Windows 10/11 using Firefox release;

**Prerequisites:**

* Have a subscription for a premium product i.e. Mozilla VPN;
* Be in Contact Support page;

**Steps to reproduce:**

1. Resize the browser (i.e 1024px width);
1. Hover over Subscriptions breadcrumb menu option;

**Expected result:**

* The “Subscriptions” options is linked;

**Actual result:**

* The “Subscriptions” option is not entirely linked.

**Notes:**

* Going to smaller browser dimensions we end up having no option linked;
* Not reproducing on mobile;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5681)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27199">resize-link.gif</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
