### ISSUE TITLE
The “Would you mind telling us why you’re leaving?”  form can be submitted without checking an option

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13894]
**FxA version:**

* 1.238.0;

**Prerequisites:**

* Be localized in US;
* Have an fxa account;

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net](https://accounts.stage.mozaws.net) and login using an existing account;
1. Click on the "Email communications" option displayed in the navigation menu;
1. Click on "Sign in" button;
1. Check the "Remove me from all the subscriptions on this page:" checkbox displayed at the bottom of the page and click the Save Preferences button;
1. Do not check the checkbox which describe your unsubscribing reason and click "Submit" button;

**Expected result:**

* The Submit button is not available or is disabled;

**Actual result:**

* The submit button can be clicked without any issue;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5680)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
