### ISSUE TITLE
fxa-js-client failure building sjcl w/ node 10

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1389]
Maybe this is has to do with something on my computer, but I can only install/build fxa-js-client using node 6. Specifically, running `grunt sjcl` fails w/

```
Running "sjcl" task
Enabled components:
  aes
  bitArray
  codecString
  codecHex
  codecBase64
  sha256
  hmac
  pbkdf2

Compression: closure
>> make: * No rule to make target `core/sjcl.js', needed by `core.js'.  Stop.
Fatal error: ENOENT: no such file or directory, open 'core_closure.js'
```

### node 10

<img width="968" alt="Screenshot 2019-06-05 at 06 32 59" src="https://user-images.githubusercontent.com/848085/58932602-47a13900-875c-11e9-8bb8-28a4aeb93861.png">

Using `npm install` rather than `npm ci` results in the same problem.

### node 8

<img width="973" alt="Screenshot 2019-06-05 at 06 33 40" src="https://user-images.githubusercontent.com/848085/58932613-51c33780-875c-11e9-9942-0799f2c1492d.png">

### node 6 (success)

<img width="979" alt="Screenshot 2019-06-05 at 06 36 27" src="https://user-images.githubusercontent.com/848085/58932623-5c7dcc80-875c-11e9-89fd-8e304d114cc8.png">

Oddly, if I `npm install` w/ node 6 then do a `grunt sjcl` w/ node 10, no problem.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-119)
┆Issue Number: FXA-119

**Comment by vladikoff** [comment]
Works fine here with `v10.16.0`

**Comment by vbudhram** [comment]
Node 12 is now the minimum and it seems to build with no issues, closing
