### ISSUE TITLE
Font sizes are different (12px vs 14px) for various connected services

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13899]
## Description

I signed into my account on prod this morning and noticed that the font size for linked connected services is 14px, whereas the font size for non-linked services is 12px. 👀 

### Steps to reproduce

Sign into prod. Have several connected services (although some of them need to be linked text; oddly none of mine in staging were linked, so I couldn't confirm there).

Looks like a difference of `text-sm` vs `text-xs`. I could argue that using `xs` is odd/wrong here since the timestamps are using 14px (text-sm) as well, so the unconnected connected service labels are the only thing using the smaller `xs` sizing.

```html
<p class="text-xs break-word" data-testid="service-name">Mozilla VPN</p>
<a data-testid="service-name" target="_blank" rel="noopener noreferrer" class="link-blue text-sm" href="https://monitor.firefox.com/">Firefox Monitor<span class="sr-only">Opens in new window</span></a>
```

### Expected result

What should happen?

### Actual result

![Screen Shot 2022-08-08 at 11 03 47 AM](https://user-images.githubusercontent.com/557895/183485155-cd118630-b42b-4761-96e7-dab1b44c207a.png)

Unrelated to the above bug, but I was also surprised that "Mozilla VPN" wasn't linked to something like https://vpn.mozilla.org/. (presumably this is our desktop VPN client)

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5686)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
