### ISSUE TITLE
Standardize Error Handling for sentry events

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13901]
We currently have a few different routines for ‘capturing’ errors and reporting them to sentry. Some errors need a bit of extra help in order to get them into a nice state for sentry. For example, validation errors require extra processing, so that the actual error messages shows up in the error title in sentry. 

Each project currently has its own way of capturing sentry errors. We shoudl try to consolidate this to a single routine in fxa-shared that handles all the various scenarios and can be put under test.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5688)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
