### ISSUE TITLE
Auth server script errors with OpenSSL 3.0

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13903]
**Background**

When setting up the fxa stack on Ubuntu 22.04, `fxa-auth-server` fails on script `scripts/gen_keys.js`. 

**Additional info**

* Seems dependency `pem-jwk` doesn’t support output format PKCS#8, the default for `openssl genrsa...` for OpenSSL version 3.0+.
  * Adding the `-traditional` option, ie `openssl genrsa -traditional 2048`, serves as a temp work around, since this script only really needs to run this code once.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5690)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
