### ISSUE TITLE
Evaluate need for `localeQuirks.js`; modify or remove

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13908]
In `fxa-auth-server/scripts/e2e-email/localeQuirks.js`, we’ve got a comment at the top of the file:

```
// Not all non-english locales have tranlated some things yet.
// So there are these unfortunate bits of custom mappings that
// will need to change over time.
```

However, this was 7 years ago and has seemingly random strings in it mapping to certain locales.

Do we still need this file? Investigate and either modify it accordingly or remove it.

There’s not much more info in this comment but this was discovered when this file was modified [here](https://github.com/mozilla/fxa/pull/13823/files#r940322251).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5691)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
