### ISSUE TITLE
[subplat] Stage plan only loads after removing invalid metadata from Plan

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13902]
**Background**

The Hubs plan on stage would not load, and instead the “Plan not found” modal is shown. (Screenshot below). Only after removing an invalid metadata item from the Plan, `"ignore": "testo"`, did the plan load correctly.

**Additional observations**

* Originally the plan did not show up in the URL [https://api-accounts.stage.mozaws.net/v1/oauth/subscriptions/plans](https://api-accounts.stage.mozaws.net/v1/oauth/subscriptions/plans)

**Screenshot**

!image-20220808-182407.png|width=832,height=702!

!image-20220808-182941.png|width=371,height=302!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5689)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27238">image-20220808-182407.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/27239">image-20220808-182941.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
