### ISSUE TITLE
Standardize Routine used for scrubbing PII in sentry events.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13900]
We currently have a few different routines used for scrubbing PII from Sentry errors/events. Ideally we’d just have one routine that handles all cases. The goal here is having all services using the same PII filtering routine. In FXA-5103 code was added to fxa-shared that scrubbed PII from sentry errors in a standardized and configurable way. We should try to apply this routine across all services.

I*mportant!* The new PII filters in fxa-shared should be fairly efficient, but when compared to the  approach of filtering out the entire body, which currently exists in some services, there is more overhead. When applying the new way of filtering PII to high throughput endpoints, we should let SRE know, so they can monitor for any adverse side effects.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5687)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
