### ISSUE TITLE
Move stage-123done into mozilla's corporate account

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13915]
Please move stage-123done and any other heroku apps into mozilla’s corporate account.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5692)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
