### ISSUE TITLE
Check for dynamic classnames without variables

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#13918]
_Originally posted by @pdehaan in https://github.com/mozilla/fxa/pull/13882#discussion_r941694337_

We might have a few dynamic `className`s without any variables that can be converted to a static list of classes.

```sh
git grep -PEn 'className=\{`' | grep -v "\\\$"

packages/fxa-settings/.storybook/design-guide/pages/Breakpoints.tsx:109:        className={`shadow-md mb-4 rounded border border-black/25 p-3 w-full text-white bg-yellow-700 mobileLandscape:bg-green-800 tablet:bg-violet-600 desktop:bg-blue-800 desktopXl:bg-red-700 overflow-scroll whitespace-nowrap`}
packages/fxa-settings/src/components/BentoMenu/index.tsx:54:          className={`w-full h-full fixed top-0 ltr:left-0 rtl:right-0 bg-white z-10
packages/fxa-settings/src/components/FlowContainer/index.tsx:30:      className={`max-w-lg mx-auto mt-6 p-6 pb-7 tablet:my-10 flex flex-col items-start bg-white shadow tablet:rounded-xl`}
packages/fxa-settings/src/components/InputText/index.tsx:84:      className={`flex items-center rounded transition-all duration-100 ease-in-out border relative
```

```sh
git grep -PEn "className=\{['\\\"]" | cat

packages/fxa-payments-server/src/components/ErrorMessage/index.tsx:17:          className={'error-message-container'}
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/SubscriptionIapItem.tsx:62:        <div className={'with-settings-button'}>
packages/fxa-payments-server/src/routes/Subscriptions/SubscriptionIapItem/SubscriptionIapItem.tsx:122:        <div className={'with-settings-button'}>
packages/fxa-settings/src/components/PageAvatar/index.tsx:246:            className={'w-100'}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5695)

**Comment by pdehaan** [comment]
Looks like `InputText` one is misleading since it's multiline, and _does_ have variables:

https://github.com/mozilla/fxa/blob/d84af5eee500ca68d1f39dbf150216826046d9be/packages/fxa-settings/src/components/InputText/index.tsx#L83-L90

But the multiline BentoMenu/index.tsx doesn't have variables:

https://github.com/mozilla/fxa/blob/d84af5eee500ca68d1f39dbf150216826046d9be/packages/fxa-settings/src/components/BentoMenu/index.tsx#L51-L57

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
