### ISSUE TITLE
[subplat][tailwind] Storybook cleanup - change storyWithContext to storyWithProps

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13917]
After SB for components and routes in Payments has been updated to use CSF, go through and revise ones that call `storyWithContext` but don't use Context with `story` or `storyWithProps`.

As per Lauren’s slack message:

{quote}We probably shouldn’t call the main story function `storyWithContext` if that story doesn’t use Context. You could just call it `story` (or something like `storyWithProps` if it’s got properties being passed in). Also, if we can create a helper function, that’d be great, to avoid redefining that in every single component. You can pass in the `Subject` as a child of it so you can do whatever you need, e.g. we’d have a `storyWithContext` shared component that wrapped `{children`} in the needed Context provider, then just `story` which does the same thing but without the context provider.{quote}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5694)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
