### ISSUE TITLE
DBError: accessDenied

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13929]
Sentry Issue: [FXA-ADMIN-PANEL-P](https://sentry.io/organizations/mozilla/issues/3493847860/?referrer=jira_integration)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5715)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
