### ISSUE TITLE
Update Terraform resource IDs from "google_play_iap" to "iap" or similar

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13922]
In [https://mozilla-hub.atlassian.net/browse/FXA-5034](https://mozilla-hub.atlassian.net/browse/FXA-5034|smart-link) (specifically, [https://github.com/mozilla-services/cloudops-infra/pull/4258](https://github.com/mozilla-services/cloudops-infra/pull/4258|smart-link) ) some IAP config file names were changed from "google_play_iap_transformed.json" to "iap_transformed.json" to reflect the fact that the data is now for more than Google IAP subscriptions (currently, the data is for both Google and Apple IAP subscriptions thanks to [https://mozilla-hub.atlassian.net/browse/FXA-3806](https://mozilla-hub.atlassian.net/browse/FXA-3806|smart-link)).

It was noted by [~accountid:61b123139615eb006fa413c1] that related Terraform resource files from the PR also reference Google Play (i.e. “google_play_iap.tf”). Ideally to avoid confusion, these resource IDs should also be updated to have a more general name like “iap”.

Per [~accountid:6047cbd9ad0d2e0068412955] in this [PR comment](https://github.com/mozilla-services/cloudops-infra/pull/4258#issuecomment-1210002262):

{quote}Sean is correct, changing resource IDs requires a few more steps but is possible. Definitely need to do it in a separate PR.{quote}

Jbuck: Is this something you or dlactin would handle?

I should note this change is not urgent and does not block any Apple IAP integration work/testing that is underway.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5696)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
