### ISSUE TITLE
Reuse images from content server in payments server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1393]
In PR #1387, we started reusing styles from the content server on the payment server. But, it looks like the out-of-box settings in create-react-app [disallow the usage of images outside of the payment server `src/` directory](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/ModuleScopePlugin.js#L67) unless they come from node modules. So, I copied a few over and included them in the PR for expediency's sake.

This means we'd need to keep them manually updated. What would be better is to either:
* Use an npm script to copy the images over automatically
* Link to fxa-content-server in node_modules for fxa-payment-server, since Sass can use assets from a node module in NODE_PATH

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-120)
┆Issue Number: FXA-120

**Comment by lmorchard** [comment]
Mainly a note to myself, unless someone else takes this up...

Took a quick naive crack at this with a simple `npm link ../fxa-content-server` in a `postinstall` script (mostly stolen from #1392). This worked fine for local dev, and I could refer to images from scss like so:
```scss
background-image: url('~fxa-content-server/app/images/firefox-logo.svg');
```

The problem comes in with Docker builds for test and deployment. Those are restricted to the `fxa-payments-server` package directory - they can't link or copy from anything in the parent directory. So, I need to figure out another way to `fxa-content-server` into `node_modules` or at least copy the images over.

**Comment by philbooth** [comment]
Ref: #941

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Would it make more sense to just hoist all the fxa images into that top level images/assets folder?

**Comment by lmorchard** [comment]
> Would it make more sense to just hoist all the fxa images into that top level images/assets folder?

Not really. The top-level assets directory is *just* for images that are directly uploaded as-is to the CDN - like icons.

Images in content-server are more like source code. The build processes image dependencies, doing things like adding a version hash to filenames for cache busting. I think we might also do some image optimization in that pipeline too.

Maybe we could move those images to a different top-level shared image source directory, but we still run into Docker path issues.
