### ISSUE TITLE
In the device list and notifications, Fenix calls the device ‘Firefox Sync’, it should be ‘Firefox for [Preview/Android/Fenix]’

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#1397]
STEPS TO REPRODUCE
1. Sign into Firefox for iOS or Firefox Desktop
2. Sign into Fenix as second device for Sync
3. Check device list and notification 

EXPECTED RESULTS
* Device List to show Firefox Preview/Android
* Notification to show Firefox Sync has connected to "Firefox Preview/Android," similar to the iOS notification (shown below).

ACTUAL RESULTS

![Screen Shot 2019-06-05 at 4 40 36 PM](https://user-images.githubusercontent.com/28498717/58988907-ac867e80-87b0-11e9-870b-b578c7be6c96.png)

![IMG_0073](https://user-images.githubusercontent.com/28498717/58985357-26b30500-87a9-11e9-8b91-df806ee7ee24.jpg)

**Comment by shane-tomlinson** [comment]
Closing as "by design", see https://github.com/mozilla/fxa/issues/913

**Comment by shane-tomlinson** [comment]
Oh, I see... Firefox Sync has connected to Firefox Sync. @ryanfeeley that's ugly.

**Comment by rfk** [comment]
I'm going to close this in favour of https://github.com/mozilla/fxa/issues/1531 which is the same underlying issue and has more discussion about how to fix it.
