### ISSUE TITLE
In Fenix settings, device name field should prepopulate with existing name/placeholder

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#1398]
STEPS TO REPRODUCE
1. Open Firefox browser on Fenix
2. Navigate to Settings 
3. Click on User Name 
4. View "device name"

EXPECTED RESULTS
* Default device name should be an unique placeholder (i.e. Ryan's Samsung Galaxy S4)
* If edited, the field should be changed and sync across device list
* If left blank after user modification, placeholder value should re-populate

ACTUAL RESULTS
* Current placeholder name "Fenix Preview"
* On first edit, name field is blank (should be pre-populated)

![Screenshot_20190605-152354](https://user-images.githubusercontent.com/28498717/58985574-a4771080-87a9-11e9-8398-ddc53eda999f.jpg)
![Screenshot_20190605-152442](https://user-images.githubusercontent.com/28498717/58985576-a5a83d80-87a9-11e9-8fa3-a7122bab8102.jpg)

**Comment by rfk** [comment]
Thanks for the report! This one will have to be done client-side in Fenix, would you mind re-filing it over in https://github.com/mozilla-mobile/fenix ?

**Comment by dianehuang11** [comment]
Moved to: https://github.com/mozilla-mobile/fenix/issues/3317
