### ISSUE TITLE
In CWTS, make success message permanent

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#1399]
**STEPS TO REPRODUCE**
1. Create Firefox Account on Desktop
2. Enter email address and password 
3. "{Email} Registered" green bar will appear on choose what to sync page
4. Check or uncheck any boxes

**EXPECTED RESULTS**
* Sticky success message. No action on the page should hide or remove the green bar.

**ACTUAL RESULTS**
* Success message disappears once a box is unchecked.
![Screen Shot 2019-06-05 at 4 53 19 PM](https://user-images.githubusercontent.com/28498717/58989959-ea84a200-87b2-11e9-950a-7a1bae35255a.png)
![Screen Shot 2019-06-05 at 4 53 26 PM](https://user-images.githubusercontent.com/28498717/58989961-ea84a200-87b2-11e9-876b-4e858dca9494.png)

**Comment by shane-tomlinson** [comment]
Dup of #660
