### ISSUE TITLE
Create a template for feature documents

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa#140]
I love feature documents! 

In my conversation with @ryanfeeley today, I felt that a (simple) template would help make them better. E.g., a template could:

* Make it clear what sections in a feature document are mandatory
* Make them more consistent with each other
* Make it easier for people not as used to doing product work to participate and propose ideas

I'll leave it to you to decide on the actual template and format, but my strawman would likely include (not necessarily in this order):

# Outcomes

What are the outcomes you want to achieve?

# Assumptions

This is where you talk about what you assume to be true. This could include assumptions around what users are doing, errors, gaps, etc., based on anecdotes, opinions, testing, or data. 

# Problem Statement

Talk about current goals of the system and how they aren't being met. What outcomes are we not delivering? This can also include an explicit request for improvement that doesn't dictate a specific or concrete solution.

# Hypothesis

A high level hypothesis of how the feature you're going propose is going help us achieve the outcomes listed above. I recommend this be a sentence of the form:

We believe that
`<doing this/building this/creating this experience>`
for `<these people>`
will achieve `<this outcome>`.
We will know this is true when we see this
`<qualitative feedback>/<quantitative feedback>/<KPI change>`.

# Describe the Feature

This is where you get into the details of your feature and/or A/B test.

# Sub-hypotheses

Your hypothesis above may too big or high level to test and measure directly. In section, you can break down your hypothesis into sub-hypotheses that hopefully predict the higher level one. These might be rolled into your feature description. One consequence of the above structure of hypotheses is that they contain all the measures you need to prove or disprove them.

Thoughts?

**Comment by vbudhram** [comment]
Looks good! One note, should we have a section on the success criteria of a feature or what statistics/graphs might be generated from it?

**Comment by vladikoff** [comment]
@vbudhram I think that is called "Outcomes" in this one.

**Comment by ckarlof** [comment]
@vbudhram I feel it's useful to separate the desired outcome from the measure we use to know whether the proposed feature helped us make progress towards the outcome. Also, the outcome should be expressed in a way that doesn't dictate a specific solution.

For example, a statement incorporating the hypothesis, outcome, measure, and expected result might be something like:

"We believe that building feature X for FxA OAuth users will make it easier for these users to successfully log in to relying Web sites. We will know this is true when we see that the completion rate for OAuth logins increases from the base rate of Y% for users of feature X." 

Outcome: "make it easier for users to log in to relying Mozilla web properties"
Measure: "completion rate for OAuth Logins"
Expected Result: "increase in completion rate for users of feature X"

**Comment by shane-tomlinson** [comment]
I'm not sure whether it belongs in a template, but I also like to explicitly call out open/unresolved questions and risks.

**Comment by seanmonstar** [comment]
I really enjoy how the Rust team handles this in their [RFCs](https://github.com/rust-lang/rfcs#what-the-process-is) repo:

- There is an existing [template](https://github.com/rust-lang/rfcs/blob/master/0000-template.md) at the root of the repo, with sections defined and instruction test inside each section.
- A new RFC (in our case, feature) is filed by cloning the repo, copying the template file into an appropriate feature name, and filling out the sections.

We could have a template like so:

```md
- Feature Name: (fill me in)
- Start Date: (fill me in with today's date, YYYY-MM-DD)
- Feature PR: (leave this empty)
- Feature Milestone: (leave this empty)

# Summary
[summary]: #summary

One para explanation of the feature.

# Motivation
[motivation]: #motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

# Detailed design
[design]: #detailed-design

This is the bulk of the Feature. This should get into specifics and corner-cases, and include examples of how the feature is used.

# Success Criteria
[success]: #success

How will we measure the success when this feature is implemented?

# Drawbacks
[drawbacks]: #drawbacks

Why should we *not* do this?

# Alternatives
[alternatives]: #alternatives

What other designs have been considered? What is the impact of not doing this?

# Unresolved questions
[unresolved]: #unresolved-questions

What parts of the design are still TBD?
```
