### ISSUE TITLE
Firefox Sync doesn't give the opportunity to change the international prefix number while connecting a smartphone to sync devices [bz1468338]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1403]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1468338

Created attachment 8984996
Schermata del 2018-06-08 10-54-28.png

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20180517113603

Steps to reproduce:

1) Create a Firefox Sync account
2) Try to connect a second device
3) Change the international prefix number (+XX) with another one.
4) insert the rest of the phone number
5) Click on "send" button.

Actual results:

The form becomes red and the description of the error is: "Invalid phone number"

Expected results:

It should accept phone numbers from countries different from the one identified by the IP address.
It should send a message to the phone number inserted.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-123)
┆Issue Number: FXA-123

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bz
