### ISSUE TITLE
[foxfooding] 'Password Requirements' popup hides fields when using while creating Firefox Account when using Firefox Nightly inhalf of the screen in Windows 10

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#14033]
**Firefox Version:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
**Window Size (inner width and height):** 958x954
**GitHub Username:** @mMARUF
## Steps to Reproduce
Browser: Firefox Nightly (Build id: 20220827173411 User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0)
OS: Windows 10 654 Bit

1) Open Firefox Nightly 106.0a1
Open https://accounts.firefox.com/?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync
2) While having focus on Firefox, press Windows + left arrow -> to Snap Firefox to left half of screen
3) Enter Email Account 
4) Press on - " Sign Up or Sign In" button
5) Now in the Password Input modal, press on "Password" Field
6) We see "Password Requirements" pop-up opens
7) We see that the  "Password Requirements" pop-up blocks the fields below
8) Event we press on the blank space in the webpage, we are unable to see the below fields

## Expected Behavior
When using Firefox Nightly in left half of  the screen, the 'Password Requirements' popup should not block the view of the of the fields 

## Actual Behavior
When using Firefox Nightly in left half of  the screen, the 'Password Requirements' popup blocks the view of the of the fields 

## Attachment
![Attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/e2f748be-89ae-425c-8b7a-33077d8ff808.gif)
[Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/e2f748be-89ae-425c-8b7a-33077d8ff808.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5838)

**Comment by clouserw** [comment]
This is filed in several places now.  Easiest place to dupe this one is https://bugzilla.mozilla.org/show_bug.cgi?id=1877479
