### ISSUE TITLE
Consider re-auth when adding/removing two-step auth and primary email changes on an FxA account [bz1466843]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1404]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1466843

I was poking around the two-step auth capability in FxA and I was thinking it might be an added benefit to re-auth (either with password and/or TOTP) as a mechanism to prevent an attacker from taking over a logged in FxA session and then permanently taking it over without knowing the users password or demonstrating they have control over the users TOTP device.

Reproduction:

1.) Login to FxA settings panel
2.) Enabled 2-step auth (notice additional credentials did not need to be proven)
3.) Disable 2-step auth (noticed additional credentials did not need to be proven)

I believe the threat scenario could be:

- I leave my computer unlocked, someone goes to accounts.firefox.com and either enables 2-step auth and logs me out (effectively locking me out of my FxA account) or disables 2-step auth and logs me out (effectively making my 2nd factor null and void)

If we compare this to a service like GitHub, they require a second factor verification step if the user is making changes to critical aspects of the account, such as password change, 2FA change, GPG registration, etc.  To me, doing so adds a little bit of user friction, but I think it adds more of a barrier to prevent an account from being orphaned or degraded security just by visiting a URL for a logged in user.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-124)
┆Issue Number: FXA-124

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bz
