### ISSUE TITLE
Fxa implement WebAuthn U2F / 2FA [feature request] [bz1464888]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1405]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1464888

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Build ID: 20100101

Steps to reproduce:

Open Nightly >> Preferences >> Firefox Account

Actual results:

Following implmentation of "two-step authentication" https://blog.mozilla.org/services/2018/05/22/two-step-authentication-in-firefox-accounts/ This works, but is missing the newly Fx Core implementation of WebAuthn.

Expected results:

Now WebAuthn is integrated in Fx 60, and just this week Google finally allowing the use of this for their accounts, the time feels right to roadmap its implementation into the new version of Firefox Accounts.

Doing so would remove our reliance on 3rd parties and enable the use of user's preferred authentication tool for greater personalization.

I've checked with:
https://docs.google.com/spreadsheets/d/1U1IxTOlsaBcRsnJv0XAaVqQLU4otB6h2lG0NDcvWG-E/edit

https://discourse.mozilla.org/c/participationsystems

https://wiki.mozilla.org/SecurityEngineering

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-125)
┆Issue Number: FXA-125

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
