### ISSUE TITLE
Include webextension storage endpoints in fxa-client-configuration [bz1463316]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1407]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1463316

Via bug 1462615, if a user configures Firefox to use the non-prod FxA end-points, most of Sync and FxA are auto-configured correctly although the webextension-storage endpoints are not. If fxa-client-configuration returned these end-points, Firefox should then be able to be made to work as expected.

It seems that for accounts.stage.mozaws.net, the relevant endpoint is  https://webextensions-settings.stage.mozaws.net/v1 - however, I'm not sure what the matching endpoint for dev is.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-127)
┆Issue Number: FXA-127

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bz
