### ISSUE TITLE
Firefox Accounts: Flawed padding validation for RSA signatures [bz1447008]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1408]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1447008

Firefox Accounts uses RSA to sign assertions (see https://api.accounts.firefox.com/.well-known/browserid for the public RSA key), a fake signature would allow getting OAuth tokens for other people's accounts for example. The code validating RSA signatures can be seen under https://github.com/mozilla/browserid-crypto/blob/a372a53cffe27a84eebb85fc32d75edcb17a57f9/libs/external/rsa-sign.js#L134. As far as I can tell, there are three flaws here:

1. The 0001fffff... prefix is not validated. It is removed if present but its existence and validity isn't actually enforced. It is my understanding that this weakens the protection provided by the padding considerably.

2. This verification algorithm will accept SHA-1 signatures even though all signatures are generated using SHA-256 now. Assuming that SHA-1 was used here before and that somebody still has a SHA-1 signed assertion, generating a collision might be possible.

3. There are known attacks against fixed-pattern padding in RSA, with the result of PKCS#1 v1.5 paddings (the kind being used here) being discouraged. Mind you, my research seems to indicate that this currently isn't relevant for signing but only encryption. Still, not an ideal situation.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-128)
┆Issue Number: FXA-128

**Comment by rfk** [comment]
We're in the process of deprecating BrowserID (ref https://github.com/mozilla/fxa/issues/6940) so I think this is a `WONTFIX`.
