### ISSUE TITLE
Add option to remotely clear all browser data(on disconnecting device)when disconnecting a divice(other than current) using firefoxsync(accounts.firefox.com/settings) [bz1431634]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1409]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1431634

If one's device is stolen or password is leaked
It is hard and time consuming to change password for all sites
If the victim is late they can be damaged

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-129)
┆Issue Number: FXA-129

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bz
