### ISSUE TITLE
How to access/rectify/erase/port stored FxA/Sync data, as per GDPR [bz1437589]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1411]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1437589

We received these questions in IRC and I'm not sure how to answer them:

13:25:25 <da> Hi. How do I see what data is stored in my Firefox Account? How do I rectify or erase it? How do I export it? (I’m asking about the guaranteed rights granted by GDPR Section 2 and 3.)
13:26:40 <da> Right of access by the data subject, Right to rectification, Right to erasure, Right to data portability

What are the official answers and do we have work to do to comply with GDPR?

(I've cc'd the asker on this bug)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-130)
┆Issue Number: FXA-130

**Comment by clouserw** [comment]
We'll address this in bugzilla. Closing here.
