### ISSUE TITLE
Newly created account becomes disconnected after being verified [bz1380190]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1416]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1380190

STEPS TO REPRODUCE
1. On the latest Fennec (iOS) create an account
2. Open the verification link for the new account in desktop (Nightly)
3. When Fennec advances to Account Verified screen, click Cancel
3. Sign in to Sync on (desktop) Nightly
4. Go to any web page and right-click to send page to device

EXPECTED RESULTS
- Firefox desktop shows Fennec and can send it links

ACTUAL RESULTS
- Fennec does not show up
- Fennec is in unverified state

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1380190#a65448235_481559
