### ISSUE TITLE
Invalid error displayed when Display name is to long in Manage Account section [bz1546899]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1418]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1546899

Created attachment 9060643
invalid error.JPG

**Affected versions**
* 67.0b15
* 68.0a1 (2019-04-24)

**Affected platforms**
* Windows 10x64
* Ubuntu 16.04x64
* macOS 10.14

**Steps to reproduce**
1. Launch FF.
2. Log in Sync with valid credentials.
3. Go to FxA account icon.
4. Go to Manage Account...
5. Go to Display name and Click "Change..."
6. Input a very long name

**Expected result**
* Upon inputting a very long name, the message `Name is too long, maximum number of characters is xx` is displayed.

**Actual result**
* The following error is displayed instead : `Invalid parameter in request body: %(param)s`

**Regression range**
* Not a regression.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-132)
┆Issue Number: FXA-132

**Comment by byrw** [comment]
can I work on this?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bz
