### ISSUE TITLE
UX review of "account lockout" feature

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#142]
Back in https://github.com/mozilla/fxa-auth-server/issues/801 we added an "account lockout" security feature that would put your account in a locked-down state if we detected too many failed login attempts.  It's designed to prevent attackers for brute-forcing the password on a particular account -  once your account is in this state, you need to re-confirm your email address before you can perform any logins.

I just tried it out on my account in stage, and it worked, but there were some rough edges.  Here's how the flow looked from my perspective as a user.

First, I used three different devices with three different IPs to make a bunch of failed login attempts against my account, simulating someone trying to brute-force guess my password.  Using different IPs is necessary because we have a separate security feature that imposes a per-IP limit on password guessing attempts.

After enough failed attempts I was told that my account had been locked, as expected:
![screen shot 2016-04-01 at 14 55 16](https://cloud.githubusercontent.com/assets/34695/14197574/89c8a4ea-f81b-11e5-9f6a-e13f37ab8d7f.png)

I clicked the "send unlock email" link and it took me to this screen (ignore the change in email address, the screenshots are pieced together from a couple of different test runs):
![screen shot 2016-04-01 at 14 48 44](https://cloud.githubusercontent.com/assets/34695/14197582/9c2870de-f81b-11e5-8356-1440f094980d.png)

And I received the following email with subject line "Re-verify your Firefox Account":
![screen shot 2016-04-01 at 14 49 17](https://cloud.githubusercontent.com/assets/34695/14197591/bb3b608a-f81b-11e5-8795-1d4673df4117.png)

When I clicked on the "re-verify your account" link I was taken to this page in a new tab:
![screen shot 2016-04-01 at 14 56 29](https://cloud.githubusercontent.com/assets/34695/14197600/d6467892-f81b-11e5-86c2-dad4ca9dc5b2.png)

This screen was a dead-end, so I went back to my original tab.  It had been sitting there polling to see if the account got unlocked, and when it detected this, it *also* transitioned to the same dead-end "your account is ready!" screen.

To actually log in, I had to use the browser back button to get back to the signin form.  I was able to successfully sign in after the account had been unlocked.

To further test things, I signed out and then made another *failed* login attempt.  The account was immediately put back on lockdown and I had to go through the whole cycle again.

So, I feel like we still have some work to do to polish this feature:

1. @ryanfeeley how do you feel about the flow here?  I don't like that there's a dead-end on the final screen, and feel we should at least have a "sign in" link on there to move the user forward.  Better yet, when the original tab detects that the account has been unlocked, perhaps it could proceed with the original login attempt.

2. @ryanfeeley how do you feel about the copy here?  The "Account activity notice" title in the email seemed a bit weird to me, since thats not actually what I'm being notified about.

3. When you successfully unlock your account, we should clear the failed-login-attempts counter so that you don't immediately go back into this state if you typo your password.

Any other thoughts based on the flow described above?

**Comment by rfk** [comment]
I'm going to assign this to @ryanfeeley for initial comment, but I hope others will also weigh in - it can be tricky to decide how to prioritize the details of a flow like that that we hope very few users will ever see.

**Comment by shane-tomlinson** [comment]
@rfk - The flows *should* work as outlined in https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA. If the user was trying to sign into a relier/Sync when their account was locked, if that tab is still open when the user verifies their email, they should be redirected back to the relier or signed up for Sync. There are a number of functional tests for the oauth sign in case, Sync is noticeably lacks test parity.

```
➜  functional git:(master) grep "locked" *
change_password.js:    'locked account, verify same browser': function () {
change_password.js:        // account is unlocked, re-try the password change
change_password.js:    'locked account, verify same browser with original tab closed': function () {
change_password.js:    'locked account, verify same browser by replacing original tab': function () {
change_password.js:    'locked account, verify different browser - from original tab\'s P.O.V.': function () {
change_password.js:        // account is unlocked, re-try the password change
change_password.js:    'locked account, verify different browser - from new browser\'s P.O.V.': function () {
delete_account.js:    'locked account, verify same browser': function () {
delete_account.js:        // account is unlocked, re-try the delete account
delete_account.js:    'locked account, verify same browser with original tab closed': function () {
delete_account.js:    'locked account, verify same browser by replacing original tab': function () {
delete_account.js:    'locked account, verify different browser - from original tab\'s P.O.V.': function () {
delete_account.js:        // account is unlocked, re-try the delete account
delete_account.js:    'locked account, verify different browser - from new browser\'s P.O.V.': function () {
grep: lib: Is a directory
oauth_sign_in.js:    'locked account, verify same browser': function () {
oauth_sign_in.js:    'locked account, verify same browser with original tab closed': function () {
oauth_sign_in.js:    'locked account, verify same browser by replacing original tab': function () {
oauth_sign_in.js:    'locked account, verify different browser - from original tab\'s P.O.V.': function () {
oauth_sign_in.js:    'locked account, verify different browser - from new browser\'s P.O.V.': function () {
```

When you were trying to cause the account to be locked, were you doing so by browsing directly to accounts.firefox.com? If so, asking the user to sign in when complete doesn't really provide a lot of value other than giving the user a session.

**Comment by ryanfeeley** [comment]
@rfk In this case, you probably (unlike most users) went to accounts.firefox.com where no service was specified. Maybe we should get rid of **Your account is ready!** and instead say **You are no ready to use _Account Settings_.** where **_Account Settings_** is a link to settings for that user.

Or we put a big blue button in that says **Account Settings**.

Time to update this design?
<img width="1251" alt="ready" src="https://cloud.githubusercontent.com/assets/68213/14217320/49f8e71c-f81b-11e5-98b7-e47d998b1c17.png">

**Comment by rfk** [comment]
> When you were trying to cause the account to be locked, were you doing so
> by browsing directly to accounts.firefox.com? 

I did in indeed do this; I had a quick look in the code for the different brokers and somehow convinced myself that it wouldn't make a difference.  I'll try running through it again with `service=sync` to see what the difference is.

**Comment by philbooth** [comment]
from meeting: @rfk to triage if active is the wrong column

**Comment by rfk** [comment]
Assigning to @shane-tomlinson since he said he's going to look at it this week

**Comment by shane-tomlinson** [comment]
Here is what @ryanfeeley and I found: https://public.etherpad-mozilla.org/p/fxa-account-unlock-ux-review

This feature is in a sad state. 😭

**Comment by rfk** [comment]
Next step here is to turn this review into a feature definition, for what it means to actually get this feature out to production.

**Comment by shane-tomlinson** [comment]
> Next step here is to turn this review into a feature definition, for what it means to actually get this feature out to production.

ISTM we decided to remove this feature in favor of more targeted approaches to keeping bad folks at bay. I'm happy to close this issue as WONTFIX.

**Comment by rfk** [comment]
WONTFIX
