### ISSUE TITLE
Sync 'Manage Account' page shows each device last synced except device used to view page [bz1546941]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1420]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1546941

Created attachment 9060687
zz sync Capture.JPG

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

Expected results:

The 'last time synced' data should include the device accessing the page
to show that the sync was done. I would suggest there also be a 'flag'
to show if there are problems with any sync account.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-133)
┆Issue Number: FXA-133

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bz
