### ISSUE TITLE
Privacy Notice not properly highlighted when selected via keyboard [bz1543666]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1421]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1543666

Created attachment 9057493
Privacy Notice not properly highlighted.JPG

**Affected versions**
* 67.0b9
* 68.0a1(2019-04-10)
* 66.0.3

**Affected platforms**
* Windows 10x64 
* macOS 10.14
* Ubuntu 16.04 

**Steps to reproduce**
1. Launch FF.
2. Go to the Firefox Account icon near the burger menu.
3. Click on Turn on Sync...
4. Using Tab, reach the Privacy Notice option.

**Expected result**
* The Privacy Notice option is properly highlighted.

**Actual result**
* The privacy Notice option is only partially highlighted.

**Regression range**
*Will return with regression range ASAP.

**Comment by clouserw** [comment]
moved to Firefox component in bugzilla
