### ISSUE TITLE
The email in firefox account isn't right [bz1535274]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1423]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1535274

Created attachment 9050929
Screen-Shot-2019-03-14-at-18.20.40.jpg

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0

Steps to reproduce:

1. Sign Up with an email address, such as first@firefox.com
2. Add a secondary email in that account, suach as second@firefox.com
3. Set second@firefox.com as primary email address
4. Delete the old one, here is first@firefox, only keep second@firefox.com
5. You will find that all emails from firefox or mozilla were sent to first@firefox.com, not second@firefox.com.

Actual results:

All emails from firefox or mozilla were sent to first@firefox.com which is not in the account, and the primary email address in that account never gets any email.

Expected results:

The old email address should not get the emails, and the primary email should get the emails.

**Comment by clouserw** [comment]
This was moved out of the FxA component in bugzilla.  Closing
