### ISSUE TITLE
text overlap in security section with German language

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/fxa#14268]
### Description

In the security section of accounts.firefox.com there is a overlap of the text of two columns.

### Steps to reproduce

1. Make sure your content language is German (maybe other languages are affected as well)
2. open https://accounts.firefox.com/settings
3. scroll to the security section

### Expected result

No readability issues.

### Actual result

<img width="1078" alt="Bildschirmfoto 2022-10-16 um 22 14 07" src="https://user-images.githubusercontent.com/1100614/196056107-4fd7de49-9a5e-41da-9049-0348a79426a6.png">

### Environment

macOS 12.6, Firefox 105

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6089)

**Comment by vpomerleau** [comment]
There is a fix in progress for this issue: https://github.com/mozilla/fxa/pull/14352
