### ISSUE TITLE
[meta] Firefox Account cannot be recovered if all 2FA methods are lost [bz1517660]

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1435]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1517660

If a user loses all their 2FA mechanisms (TOTP device, recovery codes) then there's no way for them to recover their Firefox Account.  This is currently on purpose, because we don't have a sufficiently secure way establish account ownership.  But we should aspire to do better eventually.

In the meantime, here's a meta-bug where we can collect instances of users who are currently locked out of their account.  I've added some I know of recently but I'm sure there are more.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-138)
┆Issue Number: FXA-138

**Comment by carlos-mta** [comment]
Completed? How is this completed?

I have also lost access to my account, I changed my phone and computer the same day and forgot to transfer my recovery codes.

Now I have lost access to one of my addons and my users will no longer receive updates. Sure, I can re-upload it from another account but it will destroy my SEO and my credibility.

In fact that's what I did, and ask all my users to report the old addon in hopes to avoid confusion.

This problem only responds to the laziness, paranoia and little respect of the team behind this project for the business of others.
