### ISSUE TITLE
Close out milestone FxA-54: push on status change

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#144]
Including metrics, outcomes, follow-up work etc.

**Comment by vladikoff** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1260080

**Comment by vladikoff** [comment]
To unblock the above we are gonna use https://bugzilla.mozilla.org/show_bug.cgi?id=1276697

**Comment by vladikoff** [comment]
from mtg: add a new event to account endpoint with push `op` to build the graph

**Comment by vladikoff** [comment]
We added the extra metrics, now waiting for train-63 deploy

**Comment by vladikoff** [comment]
train-64 deployed but our custom op to log push stuff is not logging to kibana 🚒 

```
[19:50:50]  <jrgm>	anyways, we don't have that log stream in kibana, the one that handles the email status stuff. 
```
not sure what to do about this
