### ISSUE TITLE
Confirmation view 'Back' button does nothing on iOS [bz1356261]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1442]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1356261

Created attachment 8857978
IMG_0075.PNG

See screenshot

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-143)
┆Issue Number: FXA-143

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/issues/670

**Comment by shane-tomlinson** [comment]
We are standardizing on email-first, and [removing "Back" from CWTS](https://github.com/mozilla/fxa/issues/1258), it seems to make sense to remove it from here too.
