### ISSUE TITLE
Don't show Google play to install Firefox while you are in Firefox [bz1349547]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1444]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1349547

Created attachment 8850009
Screenshot

Pixel (Android 7.1.1)
Fennec 53.0b5 

Steps:
1. Create a new account and confirm it through the link in the mail received
2. In the page with "This device is connected" tap on the Google Play

Expected results:
- As I am in a Fennec/Firefox synced versions I should not received the google play button
- I would expect us to identify the UA and to show the button only in Chrome or other browser different than Fennec's versions

Actual Results:
- I am seeing both App Store and Google Play Buttons

Note:
- see attachment 
- reproducible on other devices and all Fennec versions 
- also not sure how relevant are both of this buttons on Mobile ( GPlay only would be beneficial when we confirm a sync in Chrome

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-145)
┆Issue Number: FXA-145

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1349547#c6
