### ISSUE TITLE
Changes to base font size in the browser is overruled by fonts size set in px

### ISSUE THREAD

**Issue by vpomerleau** [mozilla/fxa#14470]
## Description

Font sizes are currently defined in absolute units (px). These settings override font size preferences set by users - if a user changes their browser's default font size, text across fxa products does not adapt to respect the user's preference. Font sizes should be defined in rem (a relative unit) instead of our current default of px (an absolute unit) to be more responsive to user preferences.

### Challenges

Changing font sizes from px to rem might cause other responsiveness issues if the other parts of the layout are styled in absolute units (e.g., screen sizes). 

### Steps to reproduce

1. Visit Firefox Account Settings (localhost:3030) - have a look at font size.
2. Open Firefox settings (Hamburger menu --> Settings)
3. Go to General > Language and Appearance > Fonts
4. Change font size from the default setting (16px) to a noticeably larger size (e.g., 28px)
5. Reload Firefox Account Settings (localhost:3030) and look at font size.

### Expected result

Layout is responsive to changes is user-defined font size preference. Font size increases (or decreases) based on user-defined font size preferences and the layout is coherent and usable at larger font sizes.

Layout should be consistent between zoomed page and increased root font size. For example, changing the root font size from 16px to 32 px should result in a similar layout to zooming to 200%.

Visit [firefox.com](firefox.com) for an example of a page that responds to changes in user-defined font size preferences.

E.g.,

Base font size:

![image](https://user-images.githubusercontent.com/22231637/202011266-fb23cc42-6254-4dc0-b02f-8f88b2e27309.png)

Increased font size (30px)

![image](https://user-images.githubusercontent.com/22231637/202011072-7c1e17fb-0763-472e-8c1b-10b5e158d38f.png)

### Actual result

No change in font size, but other parts of the layout are resized or displaced.

Base size 16px:

![image](https://user-images.githubusercontent.com/22231637/202012041-befcff4b-a490-4a6b-a9a3-8b3907440cef.png)

Base size 30px:

![image](https://user-images.githubusercontent.com/22231637/202012227-63dd9c65-4228-4894-86a7-c6f090219ca0.png)

### Environment

Firefox 106.0.5, Mac OS 12.6

### Useful resources

[px to rem convertor](https://codebeautify.org/rem-to-px-converter)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6295)

**Comment by vpomerleau** [comment]
Payments server might be most impacted by changing tailwind's custom font size configuration to rem (without other UI changes). As shown in the  screenshot below, changing the tailwind font sizes to rem results in some (but not all) of the text resizing, the header overlapping the main content, and inconsistent spacing.

Screenshot of payments-server's checkout route at 100px zoom and base font set to 32px.
![image](https://user-images.githubusercontent.com/22231637/202020206-afc37b4e-0d21-4f2a-8fc0-04c1e14c17a8.png)

**Comment by clouserw** [comment]
This is in Jira.  No need to have it open here too.
