### ISSUE TITLE
No success message is displayed when the user signs out, UI is confusing. [bz1556506]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1454]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1556506

In Firefox 67, when attempting to disconnect a device from Firefox Accounts, FxA won't disconnect the device and instead re-connects the device.

Here's a video showing the experience

https://youtu.be/goRhLXGCOWk

This is reproducible 100% of the time.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-151)
┆Issue Number: FXA-151

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bz
