### ISSUE TITLE
Audit potentially hardcoded alt/title/aria-label strings

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#14559]
## Description

Found a few hardcoded `alt=`, `title=`, and `aria-label=` strings in the codebase while reviewing a different PR, so started doing a bit more digging+grepping.

### Steps to reproduce

```sh
git grep -EIn "\s(alt|title|aria-label)=" -- packages ':(exclude)*.test.tsx' ':(exclude)**/.storybook/**' ':(exclude)*.stories.tsx' ':(exclude)**/123done/**' ':(exclude)*.md' | grep -v "={" | grep -Ev "=\"[{<]"
```

```sh
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:36:            alt="Firefox logo"
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:37:            title="Firefox logo">
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:43:            alt="Sync devices"
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:44:            title="Sync devices">
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:42:          alt="Firefox logo"
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:115:          alt="Mozilla logo"
packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml:20:          alt="Download <%- locals.productName %> on the App Store"
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.mjml:11:    <mj-image width="240px" css-class="graphic-devices" alt="Devices" src="https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png"></mj-image>
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.mjml:10:    <mj-image width="240px" css-class="graphic-devices" alt="Devices" src="https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png"></mj-image>
packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.mjml:13:    <mj-image width="240px" css-class="sync-logo" alt="Devices" src="https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png"></mj-image>

packages/fxa-content-server/app/crash.html:19:      alt="Server Error - We apologize for the inconvenience"

packages/fxa-payments-server/src/components/AppLayout/index.tsx:56:    <nav aria-label="breadcrumbs" data-testid="breadcrumbs" className="w-full">
packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx:91:                alt="circled checkbox"
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6394)

**Comment by millsoper** [comment]
@pdehaan A silly question but just to make sure I understand -- what's missing is that these should all (or mostly) be localized, right?

**Comment by pdehaan** [comment]
Original report


## fxa-admin-panel
| FILE | CODE
|----|----
packages/fxa-admin-panel/src/components/LinkAbout/index.tsx:18: |     `alt="external icon"`
packages/fxa-admin-panel/src/components/Nav/index.tsx:34: |               `alt="account icon"`
packages/fxa-admin-panel/src/components/Nav/index.tsx:49:  |              `alt="key icon"`
packages/fxa-admin-panel/src/components/Nav/index.tsx:63:     |         `alt="logs icon"`
packages/fxa-admin-panel/src/components/PageAccountSearch/index.tsx:265:     |       `title="search"`
packages/fxa-admin-panel/src/components/PageAccountSearch/index.tsx:271:      |        `alt="search icon"`

## fxa-auth-server
| FILE | CODE
|----|----
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/en.ftl:7: | `fxa-header-sync-devices-image = <img data-l10n-name="sync-devices-image" alt="Sync devices">`
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/en.ftl:8: | `body-devices-image = <img data-l10n-name="devices-image" alt="Devices">`
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:36:     |       `alt="Firefox logo"`
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:37:   |         `title="Firefox logo">`
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:43:      |      `alt="Sync devices"`
packages/fxa-auth-server/lib/senders/emails/layouts/fxa/index.mjml:44:      |      `title="Sync devices">`
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:42:      |    `alt="Firefox logo"`
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:43:     |     `title="Firefox">`
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:115:    |      `alt="Mozilla logo"`
packages/fxa-auth-server/lib/senders/emails/layouts/subscription/index.mjml:116:     |     `title="Mozilla">`
packages/fxa-auth-server/lib/senders/emails/partials/appBadges/en.ftl:3: |`body-android-badge = <img data-l10n-name="google-play-badge" alt="Download { $productName } on { -google-play }">`
packages/fxa-auth-server/lib/senders/emails/partials/appBadges/en.ftl:6: |`body-ios-badge = <img data-l10n-name="apple-app-badge" alt="Download { $productName } on the { -app-store }">`
packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml:20:     |     `alt="Download <%- locals.productName %> on the App Store"`
packages/fxa-auth-server/lib/senders/emails/partials/appBadges/index.mjml:32:    |      `alt="Download <%- locals.productName %> on Google Play"`
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderFirst/index.mjml:11: |   `<mj-image width="240px" css-class="graphic-devices" alt="Devices" src="https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png"></mj-image>`
packages/fxa-auth-server/lib/senders/emails/templates/cadReminderSecond/index.mjml:10:  |  `<mj-image width="240px" css-class="graphic-devices" alt="Devices" src="https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png"></mj-image>`
packages/fxa-auth-server/lib/senders/emails/templates/postVerify/index.mjml:13:  |  `<mj-image width="240px" css-class="sync-logo" alt="Devices" src="https://accounts-static.cdn.mozilla.net/other/graphic-laptop-mobile.png"></mj-image>`

## fxa-content-server
| FILE | CODE
|----|----
packages/fxa-content-server/app/crash.html:19:  |   `alt="Server Error - We apologize for the inconvenience"`

## fxa-payments-server
| FILE | CODE
|----|----
packages/fxa-payments-server/src/components/AlertBar/index.tsx:71:          |    `alt=""`
packages/fxa-payments-server/src/components/AlertBar/index.tsx:90:        |      `aria-label="Close modal"`
packages/fxa-payments-server/src/components/AppLayout/index.tsx:56: |   `<nav aria-label="breadcrumbs" data-testid="breadcrumbs" className="w-full">`
packages/fxa-payments-server/src/components/DialogMessage/index.tsx:53:         |       `aria-label="Close modal"`
packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx:91:   |             `alt="circled checkbox"`
packages/fxa-payments-server/src/components/PaymentForm/index.tsx:297:        |        `alt=""`
packages/fxa-payments-server/src/components/PlanErrorDialog/index.tsx:26:     |     `title="Problem loading plans"`
packages/fxa-payments-server/src/routes/Product/index.tsx:222:       |   `title="Problem loading profile"`
packages/fxa-payments-server/src/routes/Product/index.tsx:239:       |   `title="Problem loading customer"`
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx:163:      |    `title="Problem loading profile"`
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx:176:     |     `title="Problem loading plans"`
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx:193:     |     `title="Problem loading customer"`
packages/fxa-payments-server/src/routes/Subscriptions/index.tsx:206:    |      `title="Problem loading invoices"`

## fxa-react
| FILE | CODE
|----|----
packages/fxa-react/components/LogoLockup/index.tsx:22:      |    `alt="Firefox logo"`

## fxa-settings
| FILE | CODE
|----|----
packages/fxa-settings/src/components/Settings/Avatar/index.tsx:24:     |     `alt="Your avatar"`
packages/fxa-settings/src/components/Settings/Avatar/index.tsx:40:   |     `alt="Default avatar"`
packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx:71:        |      `title="Download Firefox on Google Play"`
packages/fxa-settings/src/components/Settings/ConnectAnotherDevicePromo/index.tsx:86:       |       `title="Download Firefox on the App Store"`
packages/fxa-settings/src/components/Settings/ConnectedServices/index.tsx:203:         |     `title="Refresh connected services"`
packages/fxa-settings/src/components/Settings/GetDataTrio/index.tsx:78:      |    `title="Download"`
packages/fxa-settings/src/components/Settings/GetDataTrio/index.tsx:99:      |    `title="Copy"`
packages/fxa-settings/src/components/Settings/GetDataTrio/index.tsx:122:      |    `title="Print"`
packages/fxa-settings/src/components/Settings/HeaderLockup/index.tsx:43:     |     `title="Back to top"`
packages/fxa-settings/src/components/Settings/LinkedAccounts/LinkedAccount.tsx:39:    |        `{providerId === 1 && <GoogleIcon role="img" aria-label="Google" />}`
packages/fxa-settings/src/components/Settings/LinkedAccounts/LinkedAccount.tsx:40:      |      `{providerId === 2 && <AppleIcon role="img" aria-label="Apple" />}`
packages/fxa-settings/src/components/Settings/PageAvatar/buttons.tsx:55:    |      `title="Remove photo"`
packages/fxa-settings/src/components/Settings/PageAvatar/buttons.tsx:79:     |     `title="Take photo"`
packages/fxa-settings/src/components/Settings/PageAvatar/buttons.tsx:122:  |        `title="Add photo"`
packages/fxa-settings/src/components/Settings/PageAvatar/buttons.tsx:175:    |    `title="Zoom Out"`
packages/fxa-settings/src/components/Settings/PageAvatar/buttons.tsx:189:    |    `title="Zoom In"`
packages/fxa-settings/src/components/Settings/PageAvatar/buttons.tsx:203:     |   `title="Rotate"`
packages/fxa-settings/src/components/Settings/PageAvatar/index.tsx:247:     |       `aria-label="zoom-slider"`
packages/fxa-settings/src/components/Settings/PageAvatar/index.tsx:307:    |    `alt="new avatar"`
packages/fxa-settings/src/components/Settings/PageAvatar/index.tsx:316:   |   `<FlowContainer title="Profile picture">`
packages/fxa-settings/src/components/Settings/PageChangePassword/index.tsx:104:  |    `<FlowContainer title="Change password">`
packages/fxa-settings/src/components/Settings/PageCreatePassword/index.tsx:74:   |   `<FlowContainer title="Create password">`
packages/fxa-settings/src/components/Settings/PageDisplayName/index.tsx:69:   |  `<FlowContainer title="Display name">`
packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx:177:     |                 `title="Remove email"`
packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx:188:       |                 `title="Refresh email"`
packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx:260:       |           `title="Remove email"`
packages/fxa-settings/src/components/Settings/UnitRowSecondaryEmail/index.tsx:272:       |             `title="Refresh email"`
packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx:89:      |      `title="Refresh two-step authentication"`
packages/fxa-settings/src/components/Settings/UnitRowTwoStepAuth/index.tsx:105:        |    `title="Refresh two-step authentication"`

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?
