### ISSUE TITLE
Create a new context for Thunderbird desktop

### ISSUE THREAD

**Issue by darktrojan** [mozilla/fxa#14552]
Currently Thunderbird is piggy-backing off the `fx_desktop_v3` context, but this requires us to include `Firefox/109.0` (or whatever version) in the user-agent string, and we get Firefox content such as the offer to "get your tabs, bookmarks, and passwords on another device", which isn't really useful for Thunderbird.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6389)

**Comment by millsoper** [comment]
@darktrojan Can you give us more details on what you would want to see (other than omitting the Firefox specific content?)

**Comment by clouserw** [comment]
Once https://mozilla-hub.atlassian.net/browse/FXA-7336 goes live, you'd be able to redirect to whatever page you wanted to.  I think that would fulfill this issue?

**Comment by darktrojan** [comment]
I don't have access to that page, so can't say.

**Comment by darktrojan** [comment]
I've seen the content Jira page now, and yes I believe that would solve one of the problems. The others remain though. 

Sync for Thunderbird is currently on the back burner (from a front-end development POV at least) so this isn't a great priority.

**Comment by clouserw** [comment]
I'm not sure how this relates to other Thunderbird work we're doing, but as it's pretty outdated please ping me if there is more work to do here.  Thanks.
