### ISSUE TITLE
Move Settings pages from src/components/ to src/pages/

### ISSUE THREAD

**Issue by vpomerleau** [mozilla/fxa#14650]
## Description

With the content-server to fxa-settings refactor, we will be bringing in a lot of new components to fxa-settings and the `src/components` folder is becoming very crowded. We'd like to move the components marked as `Page` to a new `src/pages` folder.

Moving these Folders will involve checking all import filepaths within the moved files, and checking any filepaths that refer to the pages.

### Expected result

Settings pages are moved to `/src/pages/Settings/` and subfolder name does not include Page.

E.g., `fxa-settings/src/pages/Settings/CreatePassword`

### Current situation

Settings pages are in `/src/components/Settings/` with folder names starting with Page.

E.g., `fxa-settings/src/components/Settings/PageCreatePassword`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6465)

**Comment by clouserw** [comment]
This is in Jira.  No need to have it open here too.
