### ISSUE TITLE
testAllL10n function errors when the ftl string includes an embedded element (e.g., span)

### ISSUE THREAD

**Issue by vpomerleau** [mozilla/fxa#14655]
## Description

Running `testAllL10n` on components where FtlMsg includes an embedded element (span) errors:

```
Fallback text does not match Fluent message.
    Fallback text: Reset password to continue to account settings
    Fluent message: Reset password <span>to continue to account settings</span>
```

Both the fallback text and fluent message included <span> tags, but these are removed from the fallback before testing because the string is checked on textContent after rendering.

Tags in the source code and in the FTL message might not match even if directly compared, because FTL strings are not required to include the attributes from the source code.

E.g., 

(Simplified) Source code might be:
```
<FtlMsg id="some-ftl-id">
  <h1>
    Reset password 
    <span className="card-subheader">
      to continue to account settings
    </span>
  </h1>
</FtlMsg>
```

and FTL string:

```
some-ftl-id = Reset password <span>to continue to account settings</span>
```

### Steps to reproduce

- uncomment `testAllL10n` test line (and related imports) in `fxa-settings/src/pages/ResetPassword/index.test.tsx` (https://github.com/mozilla/fxa/pull/14599)
- `cd packages/fxa-settings`
- run `yarn test ResetPassword`

### Expected result

Yay, the fallback text and string text match!

### Actual result

```
Fallback text does not match Fluent message.
    Fallback text: Reset password to continue to account settings
    Fluent message: Reset password <span>to continue to account settings</span>
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6461)

**Comment by vpomerleau** [comment]
Needed for l10n test in Settings' ResetPassword page (FXA-6338)

**Comment by clouserw** [comment]
This is in Jira.  No need to have it open here too.
