### ISSUE TITLE
focused and focussed instances in packages/fxa-settings/src/components/Settings/Checkbox/index.tsx

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#14667]
Ref: PR #14599 (and issue #14636)

I think we still have one instance of "focussed" in packages/fxa-settings/src/components/Settings/Checkbox/index.tsx, `setFocussed`.

TLDR: `const [focused, setFocussed] = ...` (focused and focussed)

```sh
git grep -in focussed packages | cat

packages/fxa-settings/src/components/Settings/Checkbox/index.tsx:23:  const [focused, setFocussed] = useState<boolean>(false);
packages/fxa-settings/src/components/Settings/Checkbox/index.tsx:28:    setFocussed(true);
packages/fxa-settings/src/components/Settings/Checkbox/index.tsx:29:  }, [setFocussed]);
packages/fxa-settings/src/components/Settings/Checkbox/index.tsx:32:    setFocussed(false);
packages/fxa-settings/src/components/Settings/Checkbox/index.tsx:33:  }, [setFocussed]);
```

_Originally posted by @pdehaan in https://github.com/mozilla/fxa/issues/14636#issuecomment-1358635807_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6475)

**Comment by vpomerleau** [comment]
Thanks for reporting this! PR is up: https://github.com/mozilla/fxa/pull/14740
