### ISSUE TITLE
Not getting a confirmation code.

### ISSUE THREAD

**Issue by masterben42** [mozilla/fxa#14697]
## Description

I'm trying to get excess to my old account. I don't have the two step authentication anymore, so I'm trying the confirmation code sent to my email option. I've added the email as a contact and its been a few days. Ive resent the email multiple times each day and check the main inbox and spam and still nothing.

### Steps to reproduce

Try to get the confirmation code via email. 

### Expected result

Get an email with the confirmation code.

### Actual result

Not getting an email. 

### Environment

Firefox/Email apps
![Screenshot_20221228_021456](https://user-images.githubusercontent.com/113479784/209865652-64b38ca5-f13a-4c45-bc07-e570ad4e0a17.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6544)

**Comment by clouserw** [comment]
Hi.  Sorry you're running into this.  There is a knowledgebase and support forum at https://support.mozilla.org which can help with this.

**Comment by masterben42** [comment]
Thanks for the link, but I tried that and it still doesn't work.

**Comment by rockofclay** [comment]
I'm having the same issue.
