### ISSUE TITLE
Brand placeable missing from ftl string

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fxa#14753]
I missed this during the review for #14729, but this issue before merging into Pontoon: 
File: `packages/fxa-settings/src/pages/SigninBounced/en.ftl` 
String: `signin-bounced-message` 
This string uses `Firefox` instead of the brand placeable `{ -brand-firefox }`. 

```
signin-bounced-message = The confirmation email we sent to { $email } was returned and we’ve locked your account to protect your Firefox data.
```

This string should be updated with the brand term:
```
signin-bounced-message = The confirmation email we sent to { $email } was returned and we’ve locked your account to protect your { -brand-firefox } data.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6602)

**Comment by bcolsson** [comment]
@millsoper - Could you take a look at this?

**Comment by millsoper** [comment]
@bcolsson Definitely -- thanks for catching this, I super appreciate it!
