### ISSUE TITLE
Cannot start fxa: failed with exit code 1

### ISSUE THREAD

**Issue by giovi321** [mozilla/fxa#14775]
## Description

I tried to install fxa on Debian 11 but I get the following very generic error: "The script called "start.default" which runs "_dev/pm2/[start.sh](http://start.sh/) && _scripts/[pm2-all.sh](http://pm2-all.sh/) start && pm2 restart sync && echo "Use 'yarn stop' to stop all the servers"" failed with exit code 1 https://github.com/sezna/nps/blob/master/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code". Any advice on how to debug?

![image](https://user-images.githubusercontent.com/6443515/213543997-104418f7-9511-45ff-9a40-33acbb746784.png)

### Steps to reproduce

I followed this guide step by step. https://mozilla.github.io/ecosystem-platform/tutorials/development-setup

### Expected result

Start of fxa.

### Actual result

Start failed

### Environment

Debian 11

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6675)

**Comment by Ryandotdot** [comment]
As for me(macOs intel), accoding to my error msg, i successfully run the command `yarn start` by trying flowing steps:
1. change node version to 16.12.0;
2. check if port is binded by other services;
3. fix error by https://github.com/dannycoates/pem-jwk/issues/15#issuecomment-1281503859;

**Comment by clouserw** [comment]
Sorry you're having trouble with this but we can't offer setup support at this point in time.
