### ISSUE TITLE
Should Intl.DateTimeFormat('en-US', ...) be localized in fxa-settings ConnectedServices component?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#14804]
## Description

fxa-settings's components/Settings/PageRecentActivity/SecurityEvent component date is localized to en-US. But _should it be_? [ominous sound]

### Steps to reproduce

Should this `en-US` be localized?

https://github.com/mozilla/fxa/blob/de0e3ee7e830372be9b257f92dec0360d9568a49/packages/fxa-settings/src/components/Settings/PageRecentActivity/SecurityEvent.tsx#L72-L78

### Expected result

Dates localized to user's locale.

### Actual result

en-US for err'body!

### Environment

What browser and operating system are you using?

---

_Originally posted by @pdehaan in https://github.com/mozilla/fxa/pull/14774#discussion_r1081820384_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6702)

**Comment by clouserw** [comment]
this is marked done in jira so closing here
