### ISSUE TITLE
QR Code for 2FA authentication enablement is off-center

### ISSUE THREAD

**Issue by heaversm** [mozilla/fxa#14840]
## Description

See attached screenshot with annotations.

<img width="621" alt="Screenshot 2023-02-06 at 9 00 55 AM" src="https://user-images.githubusercontent.com/520541/217039711-dead4ee8-1724-4689-86b9-9ef9c074376c.png">

### Steps to reproduce

Try and log in to firefox accounts with a non-2fa account
Receive the prompt to enable 2fa
On the [2FA QR code page](https://accounts.firefox.com/inline_totp_setup), the QR code is off-center 

### Expected result

QR Code can be centered with:

`margin: 0 auto` on the `.qr-image` element, or 

```
display: flex;
justify-content: center;
```

on the `.qr-image-container` element.

### Environment

FF 109.0.1 (64-bit) on MacOS Ventura 13.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6765)

**Comment by arimallick** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by NigamDevansh** [comment]
If this issue is still there then i would like to work on it.
@heaversm

**Comment by clouserw** [comment]
we're not going to work on this right now
