### ISSUE TITLE
Scopes document does not include subscription scope, may be missing others

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/fxa#14916]
The [Scopes document](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/oauth/scopes.md#url-scopes) says:

> The following URL scope values are currently recognized by FxA:
> 
>  * https://identity.mozilla.com/apps/oldsync: access to data in Firefox Sync.
>  * https://identity.mozilla.com/apps/notes: access to data in Firefox Notes.

The documentation for [/oauth/subscriptions/clients](https://mozilla.github.io/ecosystem-platform/api#tag/Subscriptions/operation/getOauthSubscriptionsClients) has a link [Authenticated with OAuth bearer token](https://github.com/mozilla/fxa/blob/95cded6e96e2b20f7593153a428d158001bb8d3b/packages/fxa-shared/oauth/constants.ts#L5) to this code:

https://github.com/mozilla/fxa/blob/95cded6e96e2b20f7593153a428d158001bb8d3b/packages/fxa-shared/oauth/constants.ts#L5-L6

The scopes document should list this and any other URL scopes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-6864)

**Comment by vbudhram** [comment]
Thanks @jwhitlock, we will pull this documentation into our ecosystem docs since that is updated more frequently.

**Comment by clouserw** [comment]
thanks. added to https://mozilla.github.io/ecosystem-platform/reference/oauth-details#url-scopes
