### ISSUE TITLE
Increase PBKDF2 iterations

### ISSUE THREAD

**Issue by 1fexd** [mozilla/fxa#15194]
## Description

Currently, [the fxa-auth-client appears to only run 1000 PBKDF2 iterations on the user's password, which is laughably small](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-client/lib/crypto.ts#L30) ([OWASP recommends at least 600000 iterations](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html))

A bug ticket has been opened for this issue on the [mozilla bugtracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1320222) 7(!) years ago, and I don't quite understand why it hasn't been addressed yet, as this poses a great risk to user data (Wladimir Palant has written a great article about this [on his blog](https://palant.info/2018/03/13/can-chrome-sync-or-firefox-sync-be-trusted-with-sensitive-data/#firefox-sync) 5(!) years ago)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-7302)

**Comment by clouserw** [comment]
Hi, thanks for filing.  As you noted, this issue is already open in bugzilla.  I'm going to close this here as a duplicate.
