### ISSUE TITLE
Cannot yarn start

### ISSUE THREAD

**Issue by taxvui** [mozilla/fxa#15296]
## Description

[https://ibb.co/NC5yzx2](url)

What browser and operating system are you using?
Firefox 112.0.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-7457)

**Comment by chenba** [comment]
@taxvui can you include whatever's at that ibb.co link in this issue?  you can include images in Github issue description and comments.  Thanks.
