### ISSUE TITLE
firefox.com and accounts.firefox.com not forced to HTTPS [bz1557468]

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1532]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1557468

Created attachment 9070367
Screen Shot 2019-06-06 at 12.53.22 PM.png

In latest nightly if I type `accounts.firefox.com/pair` or `firefox.com/pair` into the location bar, they navigate to non-HTTPS versions of the website. Screenshot attached.

Something something HSTS busted?

**Comment by clouserw** [comment]
@jrgm to look into the HTTP redirect

**Comment by jrgm** [comment]
I can't see the referenced regression bug, but still present in nightly. Yet, the actual http response is 301 despite what nightly is showing.

**Comment by rfk** [comment]
This is a Firefox issue that we can't really do much about, I'm told the regressing bug is being backed out. It seems to work properly for me in today's nightly.

**Comment by clouserw** [comment]
The concern about it in our triage was that http would show any FxA content at all.  We were thinking that http should only be a redirect, in nginx, to https.

**Comment by jrgm** [comment]
> The concern about it in our triage was that http would show any FxA content at all. We were thinking that http should only be a redirect, in nginx, to https.

It is a redirect from http to https by nginx. The actual content can only come from https://. 

I can't explain exactly what Fx was doing, but I'd guess it was fetching content over https but setting the UI to show that it came from http://. 

However, in a Fx nightly updated to very latest, this bug is no longer showing.

**Comment by rfk** [comment]
> I can't explain exactly what Fx was doing, but I'd guess it was fetching content over https but
> setting the UI to show that it came from http://.

Basically this, the http page was being handled in one content process and the https page in another, and it was having trouble correctly handling the redirect between the two processes.

**Comment by clouserw** [comment]
Got it.  Thanks!
