### ISSUE TITLE
 Reset password view password meter css is broken

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1533]
![image](https://user-images.githubusercontent.com/128755/59069322-c1ccdd00-8884-11e9-8b8b-38c4156d8a16.png)

**Comment by vladikoff** [comment]
also in settings: 
![image](https://user-images.githubusercontent.com/128755/59069599-b3cb8c00-8885-11e9-970d-9d6ad3a23422.png)

this happens on first load of the feature , I think

**Comment by shane-tomlinson** [comment]
From the looks of it, you are in "tablet" mode. Too small for the full desktop layout but too big for the full mobile layout.

**Comment by dannycoates** [comment]
Which browser @vladikoff? Looks fine for me in Nightly

<img width="579" alt="Screen Shot 2019-06-25 at 12 11 06 PM" src="https://user-images.githubusercontent.com/87619/60126286-7f3f4780-9742-11e9-9fce-cb0f11f52e0d.png">

**Comment by vladikoff** [comment]
> Nightly

it was in Nightly, you might have to find the Tablet mode dimensions and then refresh

**Comment by dannycoates** [comment]
> you might have to find the Tablet mode dimensions and then refresh

still fine

**Comment by vladikoff** [comment]
Cannot reproduce this anymore! Thanks for checking this @dannycoates !!
