### ISSUE TITLE
Reset password gets an overlap of "View Saved Logins"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1534]
cc @ryanfeeley 
![image](https://user-images.githubusercontent.com/128755/59069401-00629780-8885-11e9-8281-8281cc8a2154.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-173)
┆Issue Number: FXA-173

**Comment by ryanfeeley** [comment]
@mnoorenberghe should this be appearing if there aren't any saved credentials?

**Comment by mnoorenberghe** [comment]
No, not on focus but I noticed that it will if you type something and then backspace (or hit the down arrow, which is expected). Is it showing on focus? https://bugzilla.mozilla.org/show_bug.cgi?id=1556064 may fix this but we should also fix it in Fx.

What is the URL of this page so I can try repro?

**Comment by clouserw** [comment]
Just going to https://accounts.firefox.com/signup (and being signed out) should show that UI

**Comment by mnoorenberghe** [comment]
It doesn't pop up for me (with only the footer) on https://accounts.firefox.com/signup when I have no accounts saved so it seems to work as expected. If you have an account saved then it is supposed to pop up. If you're seeing something different then let me know.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

As mentioned, this is working as designed.
