### ISSUE TITLE
Desktop was never notified about a password reset from Fenix

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1535]
Desktop was never notified about a password reset that was initiated from Fenix and completed on desktop (and re-entered into Fenix)

STR:

* open Fenix login flow, 
* choose "Forget Password?"
* start reset

After the reset desktop will still sync, it was not notified during the sync fest

cc @ryanfeeley

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-174)
┆Issue Number: FXA-174

**Comment by clouserw** [comment]
We're triaging this and we're not super sure what the issue is.  Are you saying the push notification to desktop didn't appear?  Can you be more specific with the STR -- did you complete the password reset?

**Comment by vladikoff** [comment]
It was:

* Login to Sync in desktop
* Open Fenix, do a "forgot password" flow
* By the end of the reset flow, Firefox Desktop should be notified that password has been reset
