### ISSUE TITLE
Auth server/OAuth server /authorization discrepancy.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1541]
The /authorization endpoint on the OAuth server only requires a `state` parameter if the response_type is `code`, for [`token` it is optional](https://github.com/mozilla/fxa/blob/cf0435e4b20012e48f89234c0d99bdca3efef755/packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorization.js#L64). The auth-server [requires a state token](https://github.com/mozilla/fxa/blob/cf0435e4b20012e48f89234c0d99bdca3efef755/packages/fxa-auth-server/lib/oauthdb/create-authorization-code.js#L23) in all cases.

The /authorization endpoint was being used for the "direct grant" flow which was used by the content server to get an access token to fetch the user's profile information. In the "direct grant" flow, no state token is generated. With #795 we no longer use the /authorization endpoint for direct grants, instead we go straight to the /token endpoint which does not require a state token.

Even though the [OAuth spec says 'state' is RECOMMENDED](https://tools.ietf.org/html/rfc6749#section-4.1.1), I think since we no longer use the direct grant functionality via the /authorization endpoint and both the auth and content servers force RPs to specify a state parameter, we should push that requirement further down into the OAuth server and make `state` REQUIRED in all calls to /authorization.

cc @rfk

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-176)
┆Issue Number: FXA-176

**Comment by rfk** [comment]
> for token it is optional

On reflection, this seems very strange to - what possible use could a client have for using a state parameter in this direct-token-grant flow?  I wonder if it's a nod to compatibility some some third-party OAuth client software.

>  we should push that requirement further down into the OAuth server and make state
> REQUIRED in all calls to /authorization.

+1; if you're not sending a `state` parameter as part of this flow then you're almost certainly doing something wrong.  Technically I don't think there's any reason why we need to send that state to the backend, but it's a good opportunity for us to help RPs do the right thing.

**Comment by clouserw** [comment]
When we file an issue to merge the auth/oauth servers, this will probably get wrapped up in that.
