### ISSUE TITLE
Discuss: Standardize backend Node frameworks

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1544]
All of our backend services use Hapi except for the content server, payments server, and customs server.

Content and payments use Express and Customs uses Restify. 

Standardizing on a single backend framework would reduce the cognitive burden of working across the various repos, come up with consistent styles and paradigms, as well as allow us to more easily share code for things like the heartbeat route (@bbangert's great idea).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-177)
┆Issue Number: FXA-177

**Comment by rfk** [comment]
> All of our backend services use Hapi except for the content server, payments server, and customs server.

Also auth-db-mysql.

**Comment by LZoog** [comment]
Forgive my newbieness, but I imagine we need to greatly consider the level of effort it would take to refactor - why do we have some servers that _don't_ use Hapi?

If _not_ using Hapi really is an option, it may be worth looking into Fastify which was inspired by Hapi, Restify and Express. Benchmarks I've found online consistently show it to be highly performant:
- https://www.fastify.io/benchmarks/ and https://www.nearform.com/blog/reaching-ludicrous-speed-with-fastify/
- https://medium.com/@onufrienkos/express-vs-fastify-performance-4dd5d73e08e2

Of course keep in mind the first two links are benchmarks from the author and I can't find that many others online so I'm sure we'd want to perform our own tests, and the LoE would be even higher to refactor all servers. I have also briefly used Koa which consistently scores high in benchmarks and enjoyed the async/await syntax, but it sounds like we've already got a lot of options in the mix.

**Comment by bbangert** [comment]
> why do we have some servers that don't use Hapi?

Mainly historical, the individual services were written by different folks that made some different choices. The majority (and largest) are in Hapi.

> If not using Hapi really is an option

I'm not sure that's a feasible option as the effort involved would be drastically larger, though at least if its an order of magnitude faster there's additional benefits. I'm not sure we'd see any of those perf improvements though as most of our time is spent in network calls to other services or crypto operations.

The only realistic outcome of agreeing to standardize might be, "How bout we at least stop introducing more frameworks and any new things should be hapi". That way we could at least make some hapi plugins for things like our ops heartbeat route and avoid some repetition (and we have a hapi fxa auth plugin as well).

**Comment by 6a68** [comment]
We discussed this in the cleanup day meeting today.

Vijay's suggestion: start by eliminating restify from auth-db-server.

The customs-server is also using restify, but seems scary to modify, and might soon be obsoleted by the fraud detection pipeline.

**Comment by shane-tomlinson** [comment]
> might soon be obsoleted by the fraud detection pipeline.

In the last meeting with @jvehent, it sounded like customs is unlikely to ever be fully replaced by the fraud detection pipeline. From that P.O.V., probably worthwhile to update.

**Comment by jvehent** [comment]
We could talk about it again and see exactly how much of it can be handled by the fraud pipeline. I want to be careful about some of the realtime counters that customs currently maintains, because moving to an event-driven pipeline won't have the same latency guarantees.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is done. https://github.com/mozilla/fxa/blob/main/docs/adr/0020-application-architecture.md
