### ISSUE TITLE
Pocket ToS and PN links point to English version

### ISSUE THREAD

**Issue by flodolo** [mozilla/fxa#15490]
Commented in the original PR, but making sure this stays on the radar
https://github.com/mozilla/fxa/pull/15456#pullrequestreview-1502546581

We landed strings with hardcoded language (e.g. https://getpocket.com/en/tos/ instead of https://getpocket.com/tos/), we should let the website to language negotiation.

A couple of locales fixed it in their translation, which in turns causes [errors](https://github.com/mozilla/fxa-content-server-l10n/actions/runs/5419932410) in linters.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-7920)

**Comment by pdehaan** [comment]
```sh
git grep -Pno "https://getpocket.com/en/\w+/" | cat

packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache:53:https://getpocket.com/en/tos/
packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache:53:https://getpocket.com/en/privacy/
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache:79:https://getpocket.com/en/tos/
packages/fxa-content-server/app/scripts/templates/sign_up_password.mustache:79:https://getpocket.com/en/privacy/
```
