### ISSUE TITLE
Link to Pocket TOS and Privacy policy uses hardcoded English URL for all languages

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fxa#15513]
Issue: The string below currently uses the English URLs for Pockets terms of service and privacy policy. E.g. `https://getpocket.com/en/tos/`, so even if a user is viewing this string in German, if they click the link they will only see the English version, despite German versions existing.

https://github.com/mozilla/fxa/blob/c54f2736ebcc598b568df280a30aaec96d40d006/packages/fxa-content-server/app/scripts/templates/sign_in_password.mustache#L53

Solution: 
Replace the current URLs with the following, which will redirect to the appropriate language version based on the user's browser preferences.

https://getpocket.com/tos/
https://getpocket.com/privacy/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-7946)

**Comment by bcolsson** [comment]
It looks like there's already a fix underway 😵‍💫 :
https://github.com/mozilla/fxa/pull/15509#pullrequestreview-1522673705

**Comment by LZoog** [comment]
@bcolsson Thanks for review, this has been merged!
