### ISSUE TITLE
Non-SSL version of FxA should redirect automatically

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1554]
STEPS TO REPRODUCE
1. Enter http://accounts.firefox.com/signup

EXPECTED RESULTS
* Auto-directs to HTTPS version

ACTUAL RESULTS
<img width="798" alt="Screen Shot 2019-06-10 at 9 31 43 AM" src="https://user-images.githubusercontent.com/68213/59198950-dd750380-8b62-11e9-9b4d-2315b9158a1f.png">

**Comment by shane-tomlinson** [comment]
Dup of #1532, caused by a bug in Firefox Nightly, not us.
