### ISSUE TITLE
(l10n) Strings with duplicate IDs: 

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fxa#15558]
## Description

#15539 introduced two strings with duplicate IDs:
`recent-activity-account-recovery-key-added`

Looks like this [string](https://github.com/mozilla/fxa/blob/01d14f095b8d34decee082bd09c842e44bed30f6/packages/fxa-settings/src/components/Settings/PageRecentActivity/en.ftl#L28) would need an updated ID.

**Comment by vpomerleau** [comment]
Thanks @bcolsson! PR is up:
https://github.com/mozilla/fxa/pull/15559
