### ISSUE TITLE
[Epic] FxA Toolbar Menu

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1558]
Release date: October 22nd

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-178)
┆Issue Number: FXA-178

**Comment by davismtl** [comment]
Landed in Nightly. Making some changes to the icons. Under review and should land update in the next 2 days.

We should start seeing data coming in already.

**Comment by davismtl** [comment]
@irrationalagent to look into how we can better measure the success of the UX change.
Let's have a plan for next week.

CC @vbudhram

**Comment by davismtl** [comment]
Normally the services should be picking up the utm parameters that we are passing them but at first glance, we are not successfully measuring authentications to Monitor and Send.

See:
https://analytics.amplitude.com/mozilla-corp/chart/vts0xk9

**Comment by davismtl** [comment]
@irrationalagent and Alex to follow up with Monitor and do more testing.

@dannycoates and @johngruen are investigating on the Send side.

**Comment by davismtl** [comment]
The above chart was a funnel which makes no sense. Here is the proper chart:
https://analytics.amplitude.com/mozilla-corp/chart/ed7ave5

We are seeing authentications to both services.

**Comment by irrationalagent** [comment]
being able to track the monitor piece of this depends on https://github.com/mozilla/blurts-server/issues/844

**Comment by davismtl** [comment]
@irrationalagent we need to come to a conclusion quickly about if we think this will have a positive/negative impact on our numbers,.

**Comment by irrationalagent** [comment]
I'll wrap something up in the next day or so. Since there is some holes in the data it will be an estimate, and it could be a close call. We will definitely be trading some sync authentications for monitor/send.

**Comment by davismtl** [comment]
Tracking on Monitor site should be resolved now:
https://github.com/mozilla/blurts-server/issues/844#event-2682103084

**Comment by irrationalagent** [comment]
> Tracking on Monitor site should be resolved now:
> [mozilla/blurts-server#844 (comment)](https://github.com/mozilla/blurts-server/issues/844#event-2682103084)
> 
> Let's give it a couple of days to let metrics come in and see if all is good.

We are starting to see monitor authentications from this now. https://analytics.amplitude.com/mozilla-corp/chart/65e1y5z cc @sandysage

**Comment by davismtl** [comment]
Numbers look promising.
Monitor numbers are higher than what Leif expected so outcome is good.

**Comment by davismtl** [comment]
This shipped last week.

**Comment by davismtl** [comment]
The notification icon has also been fixed so that it appeared on the toolbar menu first for new installs. (in Nightly, the whatsnew badge was being displayed, but no longer)

There was no feature doc so we can close this.
