### ISSUE TITLE
Cannot sign in if localStorage is disabled

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1560]
The user from [this SUMO report](https://support.mozilla.org/en-US/questions/1261091) is unable to sign in to FxA because of some sort of cookie/DOM storage problem.

Maybe they are in permanent private browsing mode, maybe they have cookies disabled, maybe they have DOM storage disabled, maybe an addon is interfering with them. We aren't sure.

The thing is, we don't *need* localStorage, we use it to smooth out the experience by storing the last signed in user and making email verification a bit smoother. In Firefox Desktop we query the browser for its view of the world and use it if it's available. 

If localStorage is disabled, we could just rely upon the in-memory store and the browser query. Sure the user would have to enter their email every time they want to sign in, but at least they'd be *able* to sign in.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-180)
┆Issue Number: FXA-180

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
