### ISSUE TITLE
In list of client use the Send icon for Send for Android

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1562]
See last item (slightly cropped)
![image](https://user-images.githubusercontent.com/68213/59285268-b76f6200-8c3b-11e9-826e-1bf3df1f6ab8.png)

Should use this icon: https://accounts-static.cdn.mozilla.net/images/16bc96ee.icon-service-send.svg

**Comment by LZoog** [comment]
Hey @ryanfeeley, newbie here, I need a bit more context. What page/interface shows this list?

**Comment by vladikoff** [comment]
@LZoog https://github.com/mozilla/fxa/blob/bb6b75637e4a074a5cff2323970e1991bd9de23b/packages/fxa-content-server/app/styles/modules/_settings.scss#L556

it's visible at https://accounts.firefox.com/settings/clients
