### ISSUE TITLE
fxa-content-server no data

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#1565]
The fxa-content-server does not currently provide any data. The window remains empty when you click on Manage Devices or Manage Account. Just freshly checked out.

Thanks Holger...

**Comment by misterhsp** [comment]
I just updated my local repo and rebuilt the servers, but the content server always doesn't give me anything, empty window. Did you change something I didn't notice?

Thanks...

**Comment by misterhsp** [comment]
Nobody has any idea why this doesn't work with the latest content server anymore?

**Comment by misterhsp** [comment]
I just rebuilt everything with the last commits. But the content-server doesn't show me anything anymore, there is no login mask and there is also no way to manage devices. Everything worked fine here, some commit broke it. If I take the content server from an older backup it works fine. I don't know what to do.

**Comment by philbooth** [comment]
I just pulled and rebuilt everything locally and it works fine for me here fwiw, so you'll need to give us some more information to be able to help.

Have you looked at the logs for your content server process? Are there any errors displayed there? Or what about client-side errors in the dev tools console? If nothing is rendered, you should be able to find an error somewhere.

**Comment by misterhsp** [comment]
I suspect the commit here.
https://github.com/mozilla/fxa/commit/3f28675130b65c90b7af7fd3b4f1ef06e11a3349

I am not at home at the moment. logs I can only deliver next week.  As already mentioned the content-server from an older backup is working fine.





https://github.com/mozilla/fxa/commit/3f28675130b65c90b7af7fd3b4f1ef06e11a3349

**Comment by philbooth** [comment]
> I suspect the commit here.
https://github.com/mozilla/fxa/commit/3f28675130b65c90b7af7fd3b4f1ef06e11a3349

I'd be surprised if that was causing it, it doesn't appear to touch any production code, only tests.

> As already mentioned the content-server from an older backup is working fine.

:+1:

**Comment by misterhsp** [comment]
That's just a guess, I'm not sure about that. Sure, it's after some commit that occurred to me. What another assumption is that it has something to do with oauth and therefore nothing comes from the content-server any more.

**Comment by misterhsp** [comment]
Which logs would be interesting for you?
Maybe I can do that somehow in between.

**Comment by philbooth** [comment]
> Which logs would be interesting for you?

Any that contain an error message. From your description of the problem, I *assume* that's going to be either the content server backend, or maybe from the client side code in the browser console. But if there's nothing in those then worth checking the auth server too maybe. Something somewhere should be failing.

**Comment by misterhsp** [comment]
I once fetched the logs from the content server via ssh from home. I found this here.

https://pastebin.com/bD0CTEYP

With the other servers no error is to be found.

**Comment by philbooth** [comment]
That's interesting, I'll need to dig in a bit more to see if it's causing your issue. Have you got a Redis instance set up in your stack? It should be possible to run without one, but maybe that's changed with some recent changes or something.

**Comment by philbooth** [comment]
(or if you *do* have a Redis box in there, it might worth restarting the instance just to make sure that a problem in there is not causing FxA stuff to fail, especially since you mentioned that "Manade devices" is empty upthread, that stuff tries to read from Redis too)

**Comment by misterhsp** [comment]
Redis connection is fine.
--env "FEATURE_FLAGS_REDIS_HOST=172.17.0.1" \
Manage devices and Account is empty.

**Comment by misterhsp** [comment]
I found this in the oauth-server.

fxa-oauth-server.summary.INFO: summary {"code":400,"errno":109,"method":"post","path":"/v1/token","t":11,"client_id":"98e6508e88680e1a","auth":null,"payload":["grant_type","client_id","scope","ttl","access_type","assertion"],"remoteAddressChain":["172.17.0.10"]}

**Comment by shane-tomlinson** [comment]
Hi @misterhsp, is your auth-server the latest version? Or, could you have updated the content & auth servers w/o updating the oauth server? The log there doesn't say which parameter it considers invalid and it's hard to know which it is complaining about.

If you load up the content server and load Firefox's dev tools to the Network console, can you see which request is failing?

**Comment by misterhsp** [comment]
you mean Web-Konsole?

**Comment by shane-tomlinson** [comment]
> you mean Web-Konsole?

Yup, that's the one. Once that is open, click "Network" and reload the page to your instance of Firefox accounts.

**Comment by misterhsp** [comment]
I took a picture once.

https://imgur.com/a/WGNaQsH

older content-servers work without errors, the newest one not anymore

**Comment by shane-tomlinson** [comment]
Thanks @misterhsp - The problem here isn't with the content server, rather it looks like the config for your OAuth server is out of date. We recently [simplified the way OAuth tokens are generated](https://github.com/mozilla/fxa/pull/795), and it may be that your OAuth server's config does not recognize the content server as a "public client". I'm not sure whether you are using dev.json for your config, if so, adding [this line](https://github.com/mozilla/fxa/pull/795/files#diff-bca803ff6b323df3b3407f94d63c23e7R90) might be all that is necessary. If you are using a database backed server, you'll need to load up the oauth database in MySQL and run:

> update clients set publicClient = 1 where id = 0xEA3CA969F8C6BB0D;

ref https://bugzilla.mozilla.org/show_bug.cgi?id=1557691#c1

**Comment by misterhsp** [comment]
I don't understand exactly what you mean.
So I start the oauth-server:

https://pastebin.com/nfCMTeRH

**Comment by misterhsp** [comment]
I can do what I want here. with the new content-server nothing works anymore. Old backup of the docker image and everything works again.

**Comment by misterhsp** [comment]
I found the mistake. The oauth-database must have contained an error. I kicked it and rebuilt the database. Now everything works again.

Thanks for the help until here :)
