### ISSUE TITLE
My Gravatar avatar is not syncing

### ISSUE THREAD

**Issue by osuperjames** [mozilla/fxa#15665]
## Description

Hi, a year ago I needed to change my e-mail registered on my Firefox and on my Gravatar. I changed, everything worked fine, except for the Gravatar pic that is not syncing since then.

I tried everything, even opened a question on Mozilla Support (https://support.mozilla.org/en-US/questions/1389555), no one could help me. Yes, I also tried to change some settings on my Gravatar looking for a solution, but the issue remained intact: Firefox is the only app/website that does not sync my Gravatar pic. Now I'm considering the possibility that Firefox has lost the functionality of linking with Gravatar while (months) I was searching for a solution.

### Steps to reproduce

Try to change the e-mail on your Firefox and Gravatar accounts, maybe the issue will happen too. Observation: I tried to create a new Firefox account from zero and this new account does not sync with the Gravatar's e-mail.

### Expected result

Sync the Gravatar pic.

### Actual result

Does not sync, is showing just a big "J" instead (first letter of my name).

### Environment

Firefox version 116.0 64-bit, Windows 11 21H2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-8139)

**Comment by clouserw** [comment]
Hi @osuperjames .  We no longer integrate with gravatar.  If you want to update your avatar please click your image on accounts.firefox.com and update from there.  Thanks!

**Comment by osuperjames** [comment]
> Hi @osuperjames . We no longer integrate with gravatar. If you want to update your avatar please click your image on accounts.firefox.com and update from there. Thanks!

Hi, @clouserw. Thanks for answer me. I have three more questions now, please answer if you can, friend.

1. Do you remember when the Gravatar integration was removed? I talk about month and year, but quarters of year helps too.

2. If I use an old version of the browser, will the integration return?

3. Is there any possibility of change in the future? I mean of Gravatar's integration back to work on Mozilla Firefox.


Thank you, friend. Your browser is the best!

**Comment by osuperjames** [comment]
> 1. Looks like it was removed in April 2017
> 
>     2. No, this is on the web not in the browser so using an old version wouldn't change anything.
> 
>     3. No, it's not on any roadmaps and I would be surprised to see it.
> 
> 
> Cheers

Thanks, all my questions was answered and I have no more doubts.

Cheers.
