### ISSUE TITLE
Firefox for iOS: "Missing parameter: client_id" error message is displayed when user tries to access account management page 

### ISSUE THREAD

**Issue by alinamoldovan84** [mozilla/fxa#15696]
## Description

"Missing parameter: client_id" error message is displayed when user tries to log into account Management page.
### Steps to reproduce

1. Fresh install the FF app
2. Log into the FF with a valid account
3. Navigate to settings and open the account management page
4. Enter the FxA password and sign in.

### Expected result

User is correctly signed into the account management page

### Actual result

"Missing parameter: client_id" error message is displayed. Login works correctly if user navigates back and retries to access the account management page.

### Environment
Device: iPhone 14+ (16.0.3), iPad Air 3rd Gen (16.3.1)
Build version: v117 (33562)
First seen version: V115 (31516)

https://github.com/mozilla/fxa/assets/124251579/5fdad461-ed60-45ce-8a26-cd033ba681d8

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-8186)

**Comment by clouserw** [comment]
Thanks for letting us know.  We landed a patch and have resolved this.
