### ISSUE TITLE
Ensure rust nightly is being used rather than rust release

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1572]
Possible cause of #1569, I have seen several people ask why the email service will not install for them, turns out they all used the release version of rust rather than nightly. Can we add a check that nightly is being used instead of release?

cc @philbooth

**Comment by philbooth** [comment]
> Can we add a check that nightly is being used instead of release?

The `rust-toolchain` file is supposed to force `cargo` to use the right version fwiw (it's a specific, very old version of nightly that we're pinned to). Maybe we need better docs around the setup phase?

**Comment by philbooth** [comment]
> (it's a specific, very old version of nightly that we're pinned to)

And there's a bugzilla bug about updating that which I should link to at this point, but I'm not on my work machine.

**Comment by clouserw** [comment]
We already do this
