### ISSUE TITLE
[iOS] Device & apps button container is too small on iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla/fxa#1573]
Device: iPad Air 2
iOS: 11.4

Steps to reproduce:
1. Go to Setting -> Firefox Account -> Manage Account & Devices -> Device & apps
2. Tap "Show" button near the Device & apps section

Actual results:
- The button container is too small on iOS. On Android and desktop this looks good. 

Screenshot: 
![IMG_9D5B7C788BDC-1](https://user-images.githubusercontent.com/32130829/59355000-e9adbc00-8d2e-11e9-9a88-e07c962a1f48.jpeg)

**Comment by shane-tomlinson** [comment]
Dup of #1254, closing.
