### ISSUE TITLE
English string "Or download" displayed in Danish Firefox Accounts

### ISSUE THREAD

**Issue by Joergen** [mozilla/fxa#15780]
## Description

English string "Or download" displayed in Danish Firefox Accounts.

### Steps to reproduce

Click the Firefox menu button.
Click "Account name".
Click "Connect another device"/"Opret forbindelse til en ny enhed".

### Expected result

The dialog should have displayed the Danish string "eller hent".

### Actual result  
The dialog "Connect Firefox on another device"./"Forbind Firefox på en anden enhed" contains the English string "Or download". 

![or_download](https://github.com/mozilla/fxa/assets/3466269/36deccfc-fd4b-47cf-94a9-9b92d294bdad)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-8300)

**Comment by bcolsson** [comment]
Thanks @Joergen for reporting this, I've confirmed the same for other locales. It appears the string has not been marked for localization. I've created a PR to fix this.
