### ISSUE TITLE
Update enabled locales list to include Friulian (fur)

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fxa#15809]
Friulian (fur) locale recently achieved 100% completion rate. 

Could you please update the list of enabled locales to include Friulian?
[(Link to most recent ticket with locale updates)](https://mozilla-hub.atlassian.net/browse/FXA-7305)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-8356)

**Comment by pdehaan** [comment]
Ref: #15811
