### ISSUE TITLE
Amplitude events from the OAuth server do not contain UA, OS info

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1582]
When the auth-server sends events to amplitude, [it includes info about the user's OS, UA, and location](https://github.com/mozilla/fxa/blob/bb6b75637e4a074a5cff2323970e1991bd9de23b/packages/fxa-auth-server/lib/metrics/amplitude.js#L151), the OAuth server [sends none of these](https://github.com/mozilla/fxa/blob/bb6b75637e4a074a5cff2323970e1991bd9de23b/packages/fxa-auth-server/fxa-oauth-server/lib/metrics/amplitude.js#L36) which makes these events less useful than they could be. 

For example, it'd sure be nice to differentiate between Fenix versions to help determine whether the token creation problem has been fixed.

cc @jdragojevic, @rfk, @clouserw

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-181)
┆Issue Number: FXA-181

**Comment by shane-tomlinson** [comment]
cc @davismtl and @irrationalagent too.

**Comment by rfk** [comment]
Just a quick note that this could require some coordination on the client side to ensure the right details are sent in e.g. the user-agent string; current UA strings are a mix of two different values listed [here](https://docs.google.com/document/d/1doYLD7p6DnxAPLb-KYWSKUsi85M4JWbhJgnG6HOIstU/edit#heading=h.iyydstq02om).

**Comment by 6a68** [comment]
Swapping this out of the metrics P1s epic in favor of another, higher priority bug

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

some of this is fixed, but we're not doing new amplitude bugs at this time
