### ISSUE TITLE
[fxa-event-broker] Add .well-known routes for public keys

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1583]
Fxa Auth Server uses `.well-known` paths such as the [openid-configuration](https://accounts.firefox.com/.well-known/openid-configuration) for other parties to retrieve public JWT keys. The event broker must provide this as well.

**Comment by rfk** [comment]
I think we have a quick bit of high-level design work to do here. In my opinion the fact that fxa-auth-server hosts its own [`.well-known`](https://api.accounts.firefox.com/.well-known/public-keys) files on the `api.accounts.firefox.com` domain is a bit of a historical wart that leaks internal details of our microservice architecture to RPs, and I like the way that the OIDC ones are discoverable from our public-facing issuer domain on `accounts.firefox.com`.

@shane-tomlinson what's your take on how RPs should discover the JWK used to sign SETs published by the event-broker?

**Comment by bbangert** [comment]
After chatting with @rfk on Slack, we'll use a single JWT key, and stick with the existing openid-configuration endpoint rather than adding more JWK's and complicating discovery of them. This will require ops to deploy the event-broker with the same JWK private key we use elsewhere in FxA.
