### ISSUE TITLE
Merge #1577 to master, with some followups

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1585]
https://github.com/mozilla/fxa/pull/1577 is for a point-release and will need to be merged to master. We can also apply the following cleanups when it's not on a point-release:

* Land a new string for the "disabled client id" error, for translation.
* Move the oauth-devices feature flag out of the scheme handler and into the routes.

**Comment by clouserw** [comment]
Let's make sure this is in train 140 before the release

**Comment by shane-tomlinson** [comment]
Done before release, closing.
