### ISSUE TITLE
Different FxA email account creation flow after delete account [bz1555860]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1587]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1555860

Preconditions
To be able to see the about:welcome page on a version where this is not implemented please go to about:config and set:
identity.fxaccounts.autoconfig.uri to https://accounts.stage.mozaws.net
browser.newtabpage.activity-stream.fxaccounts.endpoint to https://accounts.stage.mozaws.net

Restart the browser.

Affected versions
Tested on Release 67.0.1 (64-bit)

Affected platforms
Tested on MacOS 10.14.5

Steps to reproduce

Go to about:welcome page
Enter new email address.
Click "Continue".
Complete the fields.
Click "Create account"
Click on "Continue"
Open the email.
Click on verification email button.
Click on signed in user icon in the toolbar
Click on Manage Account
Click Delete Account
Enter password
Click Delete account [user is signed out and taken to create account page]
Enter a new email address/pw/age
Click "Create account"

Expected result:
Receive email titled "Finish Creating Your Account" with a "Confirm email" link, after clicking it user gets new Signed in messaging.

Actual result:
Creating first new account generates correct email, link and welcome. Creating account after account deletion sends "Verify Your Firefox Account" email with "Activate now" link, and clicking it takes the signed in user to the Manage Account page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-182)
┆Issue Number: FXA-182

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bz
