### ISSUE TITLE
[fxa-payments-server] Implement more specific & localizable error messages for payment pages

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1589]
In this commit, we added error dialog messages on payment failure: https://github.com/mozilla/fxa/commit/93eddbaac81250ca6f778dfaae139e7452d35155

The messages are somewhat generic and/or display en-US text messages conveyed from Stripe. This may present problems for l10n down the road.

We have this spreadsheet of error message copy (which I believe is approved by legal):

https://docs.google.com/spreadsheets/d/1Kl2v8hJTntQvtGUTJcvWpSZQLIVvoYgnRboT2Lziu_w/edit?disco=AAAADAewemI&usp_dm=false&ts=5cdc2bc0#gid=0

We can implement some of these, based on the error code type relayed via subhub. There may need to be additional work to ensure that error type is carried through from subhub calls.

Some may not be feasible to implement without more detailed info asked for in this subhub issue: https://github.com/mozilla/subhub/issues/98

However, as noted in that issue, the more detailed information might be a security concern

**Comment by 6a68** [comment]
This might be relevant: https://github.com/ekosz/stripe-i18n

**Comment by clouserw** [comment]
@johngruen will follow up to confirm that those are the right error messages to show to end users.
