### ISSUE TITLE
Create metrics dashboard for signin confirmation feature

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#159]
We're planning to ship the signin-confirmation feature preffed on for a small number of users in train-64.  Let's make sure we have a metrics dashboard ready to monitor for any problems (or successes!) during the rollout.

Do we have enough data in datadog to measure whether the feature is working as intended, or do we need to add additional metrics logging?

**Comment by shane-tomlinson** [comment]
We can pretty easily create a DataDog dashboard, but only when we actually deploy. The new events we need to measure are not yet reported to DataDog, so we can't yet easily create the graphs, though I suppose we could try editing the DD JSON directly.

The number we want is signin confirmation completion rate. This should be:

total number of users that confirm / total number of users that must confirm 

This translates to:
complete-signin.verification.success / screen.confirm-signin

**Comment by shane-tomlinson** [comment]
I just tried editing the DD JSON directly, it didn't like it. Maybe we can try again when train-64 goes to stage and some StatsD stats are sent over to DD.

**Comment by rfk** [comment]
Train-64 is live now so we should have the necessary event data for this graph.

**Comment by rfk** [comment]
I've added a "signin confirmation success rate" graph to the logins dashboard in datadog:

  https://app.datadoghq.com/dash/54226/fxa-content-server---login

**Comment by rfk** [comment]
But to be honest, I'm surprised how little data is current in there given we've had this running and being tested in production for a week...result of data sampling maybe?

**Comment by shane-tomlinson** [comment]
> But to be honest, I'm surprised how little data is current in there given we've had this running and being tested in production for a week...result of data sampling maybe?

Those metrics are sampled at 10%, and since we only opened the test to `@mozilla.com` addresses, it's entirely possible we 1) didn't have many folks try, and 2) many of those that did try weren't members of the 10% sample group. It's also possible that we aren't reporting the metrics correctly. All three seem plausible.

**Comment by rfk** [comment]
The dashboard seems to be working well, closing this out
