### ISSUE TITLE
Add subscription capabilities to JWT access token

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1595]
Depends on #935 

RPs can query a user's subscription capabilities in the profile server / userinfo endpoint. However, it would also be useful for some RPs for this information to appear as a claim in a JWT format access token. That way, it's supplied on login without the need for an API request.

As a hint for how capabilities are derived, [here is where it gets done in the `/account/profile` route on  fxa-auth-server](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/account.js#L867).

The algorithm for generating the list is extracted into [a `determineClientVisibleSubscriptionCapabilities` utility function](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/utils/subscriptions.js#L14).

**Comment by lmorchard** [comment]
@shane-tomlinson - hopefully this is what you were asking about?

**Comment by clouserw** [comment]
I'm moving this out of the MVP and marking it as a P1 for Train 144.  This will allow us to get a jumpstart on the `prompt=none` issues.

**Comment by rfk** [comment]
I'm trying to get my head around how the RP and service integration will look in a payments world, particularly for security-review purposes. Do we have a concrete schema in mind for how these will show up in the JWT access token, and what steps the receiving service will need to take to interpret them?

Naively, this seems to be exactly what the `scope` claim from [JWT Profile for OAuth Access Tokens](https://datatracker.ietf.org/doc/draft-ietf-oauth-access-token-jwt/) is designed for - communicating to the Resource Server about what level of access the user is or is not permitted on that service.

Or, do we intend to invent our own field for the JWT (`subscriptions` maybe?) in which to communicate this data?

**Comment by shane-tomlinson** [comment]
> Naively, this seems to be exactly what the scope claim from JWT Profile for OAuth Access Tokens is designed for - communicating to the Resource Server about what level of access the user is or is not permitted on that service.

I too was hoping to place these on the scopes. The idea I had was to add the [applicable subscription capabilities for the client (as defined by client_id)](https://github.com/mozilla/fxa/blob/6f64b72608db4095cc903026198e93a40549ea84/packages/fxa-auth-server/lib/routes/account.js#L995) to the list of scopes to stay as true to the spec as possible.

**Comment by clouserw** [comment]
Is this blocking payments launch or is the expectation to just make a separate API request right now?

**Comment by shane-tomlinson** [comment]
Cloudflare wants to know the user paid by inspecting the JWT - the access tokens they receive do not have the requisite scope to fetch the user's profile info since we don't want them to be able to see PII about the user.
