### ISSUE TITLE
Include display_name in subhub create subscription payload

### ISSUE THREAD

**Issue by marty331** [mozilla/fxa#1597]
It has been determined that subsystems need a user's name to process data creation correctly.  This issue is to request that the profile display_name is included in the body of the  POST /customer/{uid}/subscriptions request.  There is currently an pending PR to accept this value in Subhub .

**Comment by 6a68** [comment]
@ianb Stealing this at Wil's suggestion. Give a shout if you've got a PR in progress and want to hang onto it
