### ISSUE TITLE
Cannot unsubscribe from Firefox Account Tips

### ISSUE THREAD

**Issue by OIRNOIR** [mozilla/fxa#15980]
## Description

I have attempted to unsubscribe from marketing email communication several times since i created my account, but I still receive daily emails.

### Steps to reproduce

- Create a new Firefox account
- When your first "Firefox Account Tips" email arrives, head to https://www.mozilla.org/en-US/newsletter/recovery/ and turn everything off

### Expected result

No more Firefox Account Tips emails

### Actual result

I received multiple emails for several days

### Environment

Safari, MacOS 14.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-8563)

**Comment by krattliff11** [comment]
Hello,

We are happy to investigate this.
Is it ok if we send an email to the address that's listed on your GitHub profile?

Regards,
Mozilla Team

**Comment by OIRNOIR** [comment]
> Hello,
> 
> We are happy to investigate this. Is it ok if we send an email to the address that's listed on your GitHub profile?
> 
> Regards, The Mozilla Team

Sure, as long as it isn't going to be put on a mailing list as well. Note that that isn't the email associated with the account.

**Comment by krattliff11** [comment]
Thank you! A representative from the Mozilla support team will contact you shortly. When communicating with our support team, you will not be not opted in to receiving any email messages apart from helping you with this particular issue.

Regards, the Mozilla Team

**Comment by OIRNOIR** [comment]
> Thank you! A representative from the Mozilla support team will contact you shortly. When communicating with our support team, you will not be not opted in to receiving any email messages apart from helping you with this particular issue.
> 
> Regards, the Mozilla Team

Thank you. It appears the emails have stopped. I received a total of 5. I probably unsubscribed after the second. The latest email was on 10/28.
