### ISSUE TITLE
Readme and documentation needs to use updated "Mozilla accounts" branding

### ISSUE THREAD

**Issue by dholbert** [mozilla/fxa#16011]
## Description

https://github.com/mozilla/fxa/#readme still has several mentions of "Firefox Accounts". So does https://mozilla.github.io/ecosystem-platform/ . Presumably those want to use the updated Mozilla Accounts branding?

### Steps to reproduce
Load https://github.com/mozilla/fxa/#readme
and https://mozilla.github.io/ecosystem-platform/

### Expected result

Should use "Mozilla accounts" terminology.

### Actual result

Still uses "Firefox accounts" terminology.

### Environment

N/A, this is just about the content/docs itself. (But I'm using Firefox Nightly on Linux.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-8596)

**Comment by Sarita-Singh** [comment]
Hey @dholbert should I go ahead and work on this?

**Comment by dholbert** [comment]
I don't know; I'm just the reporter. I'm not in a position to assign tickets here or point you at where this particular lives.

Having said that, I think this is a branding/wording thing, rather than a code fix in-search-of-a-contributor.  So, probably best for someone on the Firefox Accounts and/or branding team to pick up.

**Comment by Sarita-Singh** [comment]
Okay!

**Comment by clouserw** [comment]
The front pages of the README and ecosystem docs are updated and have a note about the former name.
