### ISSUE TITLE
[content server] directly import auth server error definitions

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1603]
Depends on #941.

When we're able to safely import source modules across package boundaries, we should import the auth server's error definitions into the the content server directly, instead of duplicating them in `app/scripts/lib/auth-errors/js`.

**Comment by shane-tomlinson** [comment]
A dup of #885, except proposing a specific method of sharing?

**Comment by philbooth** [comment]
Ah yeah, I'll close this.
