### ISSUE TITLE
Auto-bouncing invalid emails no longer working

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#162]
Not a real domain name, but didn't bounce back to registration screen at all (waited several minutes).
<img width="504" alt="screenshot 2016-06-28 17 10 51" src="https://cloud.githubusercontent.com/assets/68213/16432512/50aab00e-3d53-11e6-9b5c-f5a2e4f81c6d.png">

**Comment by vladikoff** [comment]
From meeting notes:

```
works for resolved domains with no email.
does not work for unresolved domains.
1018 error dropped off
```

**Comment by vladikoff** [comment]
from mtg: not sure what to do here yet!

**Comment by ryanfeeley** [comment]
@vladikoff Did you try that email?

**Comment by vladikoff** [comment]
@ryanfeeley yeah we concluded that:

```
works for resolved domains with no email.
does not work for unresolved domains.
```

I'm not sure what to do for unresolved domains.

**Comment by ryanfeeley** [comment]
@vladikoff Do we need a new bounce feature?

**Comment by vladikoff** [comment]
> @vladikoff Do we need a new bounce feature?

I was thinking that mx record feature we talked about a while ago should fix this, but i am not sure.

**Comment by rfk** [comment]
this one: https://github.com/mozilla/fxa/tree/master/features/proposed/FxA-112-check-domain-mx

**Comment by ryanfeeley** [comment]
@rfk Good. I was hoping this one included it, but realize that some domains just don't have an MX record, but are hosted.

**Comment by vladikoff** [comment]
@jrgm thoughts on this?

**Comment by vladikoff** [comment]
@jrgm says "the auth server knows about unresolved domains, (there is an error returned), but auth server already tells the user that it already the mail"

@jrgm can you find that bug that you mentioned in the meeting?

from mtg: "not sure if SES bounces right away during unresolved domains"

**Comment by ryanfeeley** [comment]
I know @davismtl has worked on an email bounce feature in a previous project. Can he share?

**Comment by rfk** [comment]
> "the auth server knows about unresolved domains, (there is an error returned),
> but auth server already tells the user that it already the mail"

IIRC that's the issue this old PR was trying to resolve:

  https://github.com/mozilla/fxa-auth-server/pull/1329

Or is there more to it?

**Comment by davismtl** [comment]
> I know @davismtl has worked on an email bounce feature in a previous project. Can he share?

- Checking for an MX record could be pretty efficient for detecting if it's a fake domain however I mostly used it to flag likely typos in emails or to detect if it was a Yahoo/Gmail/Outlook email with a whitelabelled domain.
- Bounces tend to be pretty instant so perhaps we can catch that and re-ask for the email.

**Comment by vladikoff** [comment]
This should be fixed!

**Comment by ryanfeeley** [comment]
@vladikoff I agree, but it does not appear to be. I tested it.
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/68213/30561291-85980d80-9c88-11e7-88a3-1cd853fda9e4.png">

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-content-server/issues/5629
