### ISSUE TITLE
[email service] Migrate to lettre_email

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1625]
Previously, the `emailmessage` crate was fine with our unicode email address tests, but as of version `2.2` it rejects them. To get up and running quickly I'm using a forked version in #1624 instead, but we should migrate to something else in due course.

We already have a dependency on `lettre_email` and I think that does everything we need, so maybe we should use that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-183)
┆Issue Number: FXA-183

**Comment by vladikoff** [comment]
@brizental do you remember the story here? I remember lettre was pretty good!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
