### ISSUE TITLE
[email service] Turn off Rocket logging

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1626]
Rockets logs aren't mozlog-friendly and we already have everything covered, so let's just turn off Rocket's logs.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-184)
┆Issue Number: FXA-184

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
