### ISSUE TITLE
[email service] Remove all the `extern crate` directives

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1627]
These are a hangover from Rust 2015, we don't need them (except maybe one or two that still need `macro_use`). Let's get rid.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-185)
┆Issue Number: FXA-185

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
