### ISSUE TITLE
[email service] Make max request body size configurable

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1628]
In #1624, I hard-coded this to be the same as Rocket's default value. But we should get it from config instead and update the value used in `src/api/send/mod.rs` accordingly and also Rocket's internal value too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-186)
┆Issue Number: FXA-186

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
