### ISSUE TITLE
Research @nx/playwright

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#16398]
Splitting this out from my offtopic Q in #16390 PR, plus I'm lazy and this _should_ auto-create a Jira ticket for me.
Lowest of low priorities, but nice to track (considering I'll likely punt to @trinaa because I'm super classy).

---

Same comment as the other PR (which is still probably out of scope here) but I find mentions of [`@nx/cypress`](https://nx.dev/nx-api/cypress) suspicious and we might be able to ✂️ .

Although now I almost definitely feel like we're out of scope and we should file a Jira and cite https://nx.dev/nx-api/playwright (plus, like, figure out what that plugin does that we may not get with our current Playwright setup).

_Originally posted by @pdehaan in https://github.com/mozilla/fxa/pull/16390#discussion_r1484997368_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9141)

**Comment by clouserw** [comment]
This is in Jira.  No need to have it open here too.
