### ISSUE TITLE
White background for Sign In button while waiting spinning wheel is displayed

### ISSUE THREAD

**Issue by vcarciu** [mozilla/fxa#164]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Steps to reproduce:
1.Go to AMO-Stage and Sign in with a known user
2.After entering password and pressing Enter, observe the background of Sign In button while waiting for user to be signed in

Expected results:
Background of Sign In button is Grey and waiting spinning wheel is visible

Actual results:
Background of Sign In button is white and the spinning wheel is almost invisible

NOTES: NOT reproducible on -dev

Please see video for this issue: 
![throbber](https://cloud.githubusercontent.com/assets/1583842/16489540/bd8711e0-3ede-11e6-9f56-72f38f52af37.gif)

**Comment by vladikoff** [comment]
Thanks for the report ! 

cc @ryanfeeley 

dup of https://github.com/mozilla/fxa-content-server/issues/3882

**Comment by ryanfeeley** [comment]
@vladikoff Also an issue inside settings too :(
![avatar-delete](https://cloud.githubusercontent.com/assets/68213/16492967/c95b761e-3eb1-11e6-922b-8840d7ca0a2e.gif)

**Comment by vladikoff** [comment]
>  Also an issue inside settings too :( 

yeah same styles there
