### ISSUE TITLE
(l10n) productPaymentCycleNew and productPaymentCycleOld are hard-coded to English

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fxa#16505]
## Description

The following two Fluent strings call variables `$productPaymentCycleNew` and `$productPaymentCycleOld`. While the rest of the string and variables are localized, these variables are [hard coded](https://github.com/mozilla/fxa/blob/db640c06c3dff9a64cb92108aa8ecba0b3c55d15/packages/fxa-auth-server/lib/payments/stripe.ts#L2886) in English.

Affected strings:
subscriptionDowngrade-content-charge-info
subscriptionUpgrade-content-charge-info-different-cycle

### Steps to reproduce

1) Visit storyboard with your preferred webpage display language set to a different language (e.g. Japanese):
https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-auth-server/index.html?path=/story/subplat-emails-templates-subscriptiondowngrade--subscription-downgrade

### Expected result

The interval should be localized to match the rest of the string.

### Actual result

Both "year" and "month" appear in English while the rest of the string is localized.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9227)

**Comment by clouserw** [comment]
closing as this is tracked in jira https://mozilla-hub.atlassian.net/browse/FXA-9227
