### ISSUE TITLE
[auth-server] Blank sign-in code sent for lockwise

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#1650]
This was reported in slack:

The user was prompted to enter sign-in code. They received the correct email that *should* have had the code, but instead it was blank. From https://github.com/mozilla/fxa/issues/914, I suspected the code might be passed as undefined. Unfortunately I can not reproduce this locally.

Ref: https://github.com/mozilla-lockwise/lockwise-ios/issues/1075

**Comment by rfk** [comment]
Possibly related, this user reports receiving an email with an empty confirmation *link* rather than code: https://support.mozilla.org/en-US/questions/1263631

**Comment by shane-tomlinson** [comment]
Is this related to https://github.com/mozilla/fxa/issues/914?

**Comment by vbudhram** [comment]
Dug into this a little more and I was able to find consistent steps to reproduce.

STR:

1. Disable sign-in confirmation and skipForNewAcconts in auth-server, https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/config/index.js#L766
2. Create an account, log out
3. Create new browser profile and load `127.0.0.1:8080` aka 123Done
4. Append `&forceExperiment=tokenCode&forceExperimentGroup=treatment-code` to url and reload page
5. Login, at enter authorization code page, hit back, then login again

Results:

The browser will attempt to use the `/session/reauth` endpoint, which does not have access to the sign-in code, ref https://github.com/mozilla/fxa/blob/80654240c7482d645eeb450728c15fceac1d08c7/packages/fxa-auth-db-mysql/lib/db/schema/patch-094-095.sql#L57. If we did return the sign-in code, it is hashed so we wouldn't be able to resend it to the user.

I think a possible solution to this problem is to use a TOTP based sign-in code, where the secret is the `tokenVerificationId`, and a 20min-ish expiration time (same as current sign-in code expiration).

**Comment by rfk** [comment]
> I think a possible solution to this problem is to use a TOTP based sign-in code, where the secret
> is the tokenVerificationId, and a 20min-ish expiration time (same as current sign-in code expiration).

👍 to addressing this using boomerang technology :-)
