### ISSUE TITLE
[fxa-content-server] Canceled pairing from the mobile device should update automatically on the desktop side

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1657]
Ref: https://github.com/mozilla-mobile/fenix/issues/3520

## Steps to reproduce

1. Scan pairing code from a desktop Firefox.
1. On the mobile device, tap cancel on the approval screen.
1. Check the desktop approval screen.

## Expected behavior

The desktop page should show a "Pairing not successful" message automatically.

## Actual behavior

The screen doesn't update automatically, only after a refresh.

## Device information

* Android device: Galaxy Note 8 (Android 9)
* Fenix version: 1.0.0 RC 1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-187)
┆Issue Number: FXA-187

**Comment by Diana-Rus** [comment]
Hi, the issue is reproducible on Firefox Preview Beta 4.1.0-beta.2 with Samsung Galaxy S8+ (Android 8)

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on the latest Beta build 5.2.0-beta.1, and on 6/9 Nightly, with Samsung Galaxy Tab S6 (Android 9).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.

**Comment by lobontiumira** [comment]
This is still reproducible!
I canceled the pairing on the Android's approval screen, but the desktop approval screen did not update.
Devices: Lenovo tab M10 (Android 10), Windows 10
Firefox for Android: Beta 93.0.0-beta.1, Nightly 94.0a1 (build 2015832747), and RC 92.1.1

**Comment by lobontiumira** [comment]
This is still reproducible.
Devices: Lenovo tab M10 (Android 10), Windows 10
Firefox for Android: Beta 97.0.0-beta.1

**Comment by delia-pop** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1850707

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
