### ISSUE TITLE
Entering invalid email for FxA registration redirects to sign-in page

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#1672]
**STEPS TO REPRODUCE**

1. Create New FxA Account 
1. Register with ~~invalid~~ email **that is sure to bounce**
1. Enter password 
1. On the next page, invalid email will be detected and webpage redirects to sign-in page 
1. Click "Sign in" button

**EXPECTED RESULTS**

Redirect users to beginning of registration flow where they can re-enter new email. 

**ACTUAL RESULTS**

Redirected webpage is a sign-in form, auto filled with the invalid email and password. When you click on the "Sign in" button, the banner of "Unknown account" pops up.

-----

![image (1)](https://user-images.githubusercontent.com/28498717/60685956-0d6aaa80-9e74-11e9-9b53-2a482231d735.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-188)
┆Issue Number: FXA-188

**Comment by dianehuang11** [comment]
cc @ryanfeeley

**Comment by rfk** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1561103 where this was a contributing factor in a confusing user experience with spurious bounces.
