### ISSUE TITLE
Is prettier configured correctly for the payments server?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1673]
I made some fairly innocuous changes to add Sentry to the payments server client-side, but when the prettier hook kicked in it also replaced a bunch of single-quotes with double-quotes, which I wasn't expecting:

https://github.com/mozilla/fxa/compare/pb/1299-payments-client-sentry?expand=1

Everywhere else still seems to use single quotes.

Do we need to do something to configure prettier properly for the `fxa-payments-server` package? /cc @dannycoates

**Comment by philbooth** [comment]
> Do we need to do something to configure prettier properly for the `fxa-payments-server` package? /cc @dannycoates

Never mind, fixed in #1676.

**Comment by philbooth** [comment]
Gah, I was wrong! I just rebased my other branch and ran the hook again, it's still flipping the quotes. Re-opening this, sorry.

**Comment by dannycoates** [comment]
I avoided making prettier PRs to the subscription packages because I didn't know how much work in progress it would disrupt. I'm happy to make a formatting PR.

**Comment by philbooth** [comment]
Oh, fair point about the work in progress I guess. I've got into the habit of using `--no-verify` in that directory now, so I'm fine if we close this.

**Comment by bbangert** [comment]
@dannycoates event-broker and payments-server should already be using prettier so there shouldn't be any changes (in theory).

**Comment by LZoog** [comment]
I came across this while working on #2053.

It seems to me like this should be reopened?

**Comment by 6a68** [comment]
Reopening to discuss in triage. (@LZoog feel free to reopen bugs :+1:)

**Comment by LZoog** [comment]
@6a68 thanks! I had this issue open to bring up at the end of triage, I'll just reopen from now on and we can close otherwise. :)

**Comment by lmorchard** [comment]
Actually, looks like we never configured prettier for payments-server. 

Brace for incoming enormous PR...
