### ISSUE TITLE
Discuss the best way to display timestamps in login notification email

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#168]
In the initial design for login notification emails [1] we include a timestamp that is displayed as follows:

* It's presented in the timezone of the location that the login occurred, or in UTC if the location could not be determined accurate.
* It's localized according to the user's preferred locale as stored by FxA, and as used to localize the rest of the email.

For example, if a user whose FxA locale is French logged in from Australia right now, the time would be displayed as 4pm on the 7th of July, Australian Eastern Standard Time.  But it would be localized according to the time display rules of the French locale, and the content of the email would be in French.

IIUC, there was some discussion in IRC between @TDA @shane-tomlinson and @ryanfeeley about whether this was the best was to display it.  Could you please either continue that discussion in this bug, or explicitly confirm that you're OK with the above?

[1] https://github.com/mozilla/fxa/commit/dbff4776a1b49d2c0020534d9989dc0b8ac15f51#diff-c35de1f41bd70a742948172e008c4910R62

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by vladikoff** [comment]
@rfk to triage

**Comment by rfk** [comment]
@TDA to triage - if there is no open question left here, can you please ensure the feature doc is up-to-date and then close this out?

**Comment by vladikoff** [comment]
Use the existing locale from the rest of the email.

**Comment by vladikoff** [comment]
@TDA please close this if all questions have been answered

**Comment by TDA** [comment]
Closed with update to Feature doc.
