### ISSUE TITLE
Inconsistent casing of subject lines in emails

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1684]
Most of the FxA emails have the subject line in sentence-casing. But while reviewing #1675, I noticed that "Finish Creating Your Account", "Reminder: Finish Creating Your Account" and "Your Firefox Account is Confirmed" have title-casing.

It looks like it's how they were specified in the designs for #1073 / #1087, but that seems weirdly inconsistent to me. Is it a bug or a feature?

**Comment by shane-tomlinson** [comment]
cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@philbooth Is there an easy way to extract all the email subject lines and post them here? I'll have the content team make the call on all of them.

**Comment by philbooth** [comment]
@ryanfeeley, here you go old bean:

```
Account recovery key generated
Account recovery key removed
Confirm new sign-in to Firefox
Final reminder: Confirm your email to activate your Firefox Account
Finish Creating Your Account
Firefox Account authorization code
Firefox Account new primary email
Firefox Account password changed
Firefox Account password reset required
Firefox Account password reset with recovery key
Low recovery codes remaining
New recovery codes generated
New sign-in to Firefox
Recovery code consumed
Reminder: Finish Creating Your Account
Reset your Firefox Account password
Secondary Firefox Account email added
Secondary Firefox Account email removed
Sign-in code for Firefox
Two-step authentication disabled
Two-step authentication enabled
Verify primary email
Verify secondary email
Your Firefox Account is Confirmed
Your Firefox Account password has been changed
```

**Comment by ryanfeeley** [comment]
So appreciated!

**Comment by ryanfeeley** [comment]
When we look at a screenshot of our current emails, it's apparent that mentioning Firefox Accounts is somewhat redundant. We can improve our emails significantly by simply trimming them down (and including codes in subject line where possible). I also ran them all through a [title case tool](https://titlecase.com/).
<img width="585" alt="image" src="https://user-images.githubusercontent.com/68213/61830112-6193f980-ae38-11e9-9690-f50445c2e00b.png">

Here is where I landed. Any concerns? I'll check with Jeff as well.

Current | Proposed
------------ | -------------
Account recovery key generated | Account Recovery Key Generated
Account recovery key removed | Account Recovery Key Removed
Confirm new sign-in to Firefox | Confirm New Sign-in
Final reminder: Confirm your email to activate your Firefox Account | Final Reminder: Activate Your Account
Finish Creating Your Account | Finish Creating Your Account
Firefox Account authorization code | Authorization Code: RXZ3DSJA
Firefox Account new primary email | New Primary Email
Firefox Account password changed | Password Changed
Firefox Account password reset required | Password Reset Required
Firefox Account password reset with recovery key | Password Reset with Recovery Key
Low recovery codes remaining | Low Recovery Codes Remaining
New recovery codes generated | New Recovery Codes Generated
New sign-in to Firefox | New Sign-in to Firefox
Recovery code consumed | Recovery Code Consumed
Reminder: Finish Creating Your Account | Reminder: Complete Registration
Reset your Firefox Account password | Reset Your Password
Secondary Firefox Account email added | Secondary Email Added
Secondary Firefox Account email removed | Secondary Email Removed
Sign-in code for Firefox | Sign-in Code: RHYZJWTD
Two-step authentication disabled | Two-step Authentication Disabled
Two-step authentication enabled | Two-step Authentication Enabled
Verify primary email | Verify Primary Email
Verify secondary email | Verify Secondary Email
Your Firefox Account is Confirmed | Your Account Is Confirmed
Your Firefox Account password has been changed | Password Changed

**Comment by philbooth** [comment]
Subjects are being updated here:

https://docs.google.com/document/d/1LRf1SiFg3zxJbDVFbilCUVDKjKcRt4_cnT_epzKm684/edit?usp=sharing

**Comment by philbooth** [comment]
Hey @ryanfeeley, I just started to make these changes and I realised there were some subjects I missed when I listed them before. Sorry, there's conditional code and not all the subjects get generated by the test I ran.

These are the ones I missed:

```
Verify your Firefox Account
Confirm your email and start to sync!
```

(alternative subjects for the `Finish Creating Your Account` one)

And:

```
Firefox Account verified
```

(alternative subject for the `Your Firefox Account is Confirmed` one)

**Comment by philbooth** [comment]
WIP PR is at #2017. I'll get that reviewed as soon as decisions/strings are final here.

**Comment by shane-tomlinson** [comment]
New guidance - re-sentence case the titles - info here: https://docs.google.com/document/d/1LRf1SiFg3zxJbDVFbilCUVDKjKcRt4_cnT_epzKm684/edit

**Comment by jpfaller** [comment]
Update per: @shane-tomlinson 

We would keep the strings as is in code, so no change for the l10n team.
In our English translation file, add the new strings as translations for the old string.
Display the new string to English users
Once skyline is done, make the updates in code so the updates are sent to everyone.

https://docs.google.com/document/d/1LRf1SiFg3zxJbDVFbilCUVDKjKcRt4_cnT_epzKm684/edit?usp=sharing

**Comment by clouserw** [comment]
@ryanfeeley Do we want to do anything else in this issue or should we close it?

**Comment by ryanfeeley** [comment]
@clouserw Is it done?
