### ISSUE TITLE
communication on Firefox sync security level

### ISSUE THREAD

**Issue by vitamins** [mozilla/fxa#16855]
There is code on GitHub that suggests a version two of the "password to encryption key derivation scheme" exists, which uses 650000 iterations rather than the previous 1000 in the older version.

https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-client/lib/crypto.ts

Dan Schomburg, you authored the commit, can you please comment on what are the prerequisites for using the more secure version two? 
@dschom 

Mozilla's communication on this issue is non-existent and terrible.

Please update the bug on bugzilla 
https://bugzilla.mozilla.org/show_bug.cgi?id=1320222

as well as the Mozilla website
https://hacks.mozilla.org/2018/11/firefox-sync-privacy/

with up-to-date information on the security level of Firefox sync.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9606)

**Comment by clouserw** [comment]
No need for duplicate issues.  I replied in https://bugzilla.mozilla.org/show_bug.cgi?id=1320222
