### ISSUE TITLE
Make jwks cache control expiry configurable, longer than 10 seconds

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1686]
Over in https://github.com/mozilla/fxa/pull/1667, @rfk set an explicit expiry of 10 seconds on /.well-known/jwks of the oauth server. Let's make this value configurable, and possibly longer than 10 seconds.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-189)
┆Issue Number: FXA-189

**Comment by rfk** [comment]
Just noting, the auth-server has a similar had-coded value which should also be made configurable at the same time.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
