### ISSUE TITLE
Handle payment server token expiration more gracefully

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1694]
Follow-up to #881

Payment server gets a token with a short expiration. That means the user could more likely be in the middle of something when it expires. 

Currently, we sometimes bounce back to the settings page on the content server when this happens. Other times, we just report errors. This should be smoothed out into something with better UX - automatic token refreshes? something else?

**Comment by lmorchard** [comment]
This might be blocked by #1696 if we want a resolution here to be that the payment app silently requests to refresh its short-lived token and retries the operation. (i.e. The user attempts to submit payment to subscribe, but they took longer than the token lifetime and so the request fails unless we get another token)

In fact, we might want some product / UX thinking on this one, too...

**Comment by lmorchard** [comment]
Adding needs:product and needs:ux labels. Here's a rephrasing of the problem: 

When the user arrives at either a product payment page or the subscription management page, they're sent in with an access token. That access token allows the payment pages to make API calls. The API calls accomplish whatever the user's there to do - e.g. pay for a new subscription, update their current card, cancel subscriptions, etc.

For security reasons, that access token has a short life time. After that life time expires, it's no longer usable to make API calls. In terms of UX & product, that means if the user takes longer than the access token life time to complete a task, that task will fail with an error.

So, what can we do about this in terms of UX & product? Depending on how #1696 works out, maybe we can just request a new access token? Otherwise, we might need some UX finesse to walk the user through starting over with their task, which seems less than happymaking

**Comment by lmorchard** [comment]
Got a positive answer on refreshing the token in #1696 - so I think this de-escalates from needing any product or UX decisions. I think we can just push refreshing the token into the invisible background and not have to surface it as a concern to the user.

**Comment by lmorchard** [comment]
I think the main takeaway from triage today was to bump access token expiration time up to 20-30 minutes until we have moved over to being a proper OAuth RP with refresh token?

Would it make any sense at all to set up a `setTimeout` to periodically ping `/v1/verify` on auth-server to detect when the token has expired, then display an error message and redirect back to FxA settings? This might be an abrupt end to a payment flow, though.

**Comment by 6a68** [comment]
Thanks for clarifying.
