### ISSUE TITLE
Rework payment server as a full OAuth RP

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1695]
For issue #881, we implemented auth token generation in content server to enable API calls in payment server pages. This works, but is not ideal for many reasons.

A better situation would be if the payment server web app was a full proper OAuth RP with [OIDC `?prompt=none`](https://github.com/mozilla/fxa/issues/640) for smooth UX transition between content and payment server apps without asking the user to enter a password to access payment pages.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-190)
┆Issue Number: FXA-190

**Comment by clouserw** [comment]
This has a draft PR (missing tests).  Let's have a discussion about the right path forward here (or if we should move forward).

**Comment by clouserw** [comment]
@bbangert - I think you are working on this now?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Seems like this should be an epic?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Yeah, I think this was filed in pre-Jira days and before we worked harder to break down issues. Would do better being re-thought as an epic and re-visiting the solution in the time since it was filed

**Comment by clouserw** [comment]
I converted this to an epic in jira so it will no longer sync with github.  closing this.
