### ISSUE TITLE
Improve security on payment server access token generation using intermediate codes

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1696]
For issue #881, we implemented auth token generation in content server to enable API calls in payment server pages. This works, but is not ideal for many reasons.

An incremental improvement to the security situation would be to supply the payment server web app with a code it can use to fetch an access token. That way, we can enforce various constraints on the transition from content server to payment server - e.g. same IP, etc.

/cc @shane-tomlinson for more erudite details on this.

**Comment by 6a68** [comment]
@shane-tomlinson Let's find a time to chat about the right way to implement this. Could this be a spot to use a JWT?

**Comment by shane-tomlinson** [comment]
> Could this be a spot to use a JWT?

I don't think so, JWTs are currently only used for access tokens. Here I'd love to use the full [prompt=none flow](https://github.com/mozilla/fxa/issues/640), but that's not ready. An intermediate step that's a bit better than what we have now is to redirect to the payments page with an authorization code instead of an access token. At least authorization codes are single use.

**Comment by shane-tomlinson** [comment]
> Could this be a spot to use a JWT?

Though, there is [this IETF spec for using JWTs as authorization grants](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-jwt-bearer#section-2.1).

**Comment by lmorchard** [comment]
A question that occurred to me over in #1694: Short of skipping straight to a full OAuth RP implementation (#1695), is there a way we can implement this issue such that the payment pages can refresh the token?

**Comment by shane-tomlinson** [comment]
> A question that occurred to me over in #1694: Short of skipping straight to a full OAuth RP implementation (#1695), is there a way we can implement this issue such that the payment pages can refresh the token?

When generating the authorization code, request "access_type=offline". When trading the code for an access token at `/token`, a refresh token will also be returned. See https://github.com/mozilla/fxa/blob/9e76653ab3bc62e35ebb2487b925ebb9b4cf01cf/packages/fxa-auth-server/lib/oauthdb/grant-tokens-from-authorization-code.js#L21. The refresh token can then be used to get new access tokens: https://github.com/mozilla/fxa/blob/9e76653ab3bc62e35ebb2487b925ebb9b4cf01cf/packages/fxa-auth-server/lib/oauthdb/grant-tokens-from-refresh-token.js#L16

**Comment by lmorchard** [comment]
Ah, okay - I was thinking we wouldn't be using something bespoke and not a more normal authorization code. That probably makes a lot of things more sane.

**Comment by 6a68** [comment]
Shane and I chatted about this today, and the way forward isn't totally clear, but it seems like we're leaning towards a cookie shared between payments and content servers, as a secure, least-effort hack until Skyline ships. Shane has a branch (as always :-). I'm not working on this right now, but may pick it up next week.

**Comment by 6a68** [comment]
Based on today's meeting, my understanding is that we're going to push the token duration from 15 to 30 minutes for the initial MVP release in this issue, then convert payments server to a proper RP soon thereafter in a separate issue. Does this seem correct, @shane-tomlinson @lmorchard?

**Comment by 6a68** [comment]
Thanks for clarifying

**Comment by 6a68** [comment]
@shane-tomlinson Hey, it seems like the #1772 PR is the right fix for Skyline, then #1695 after that. Can I just close this issue out?

**Comment by shane-tomlinson** [comment]
@6a68 - let's keep this open until those PRs land.

**Comment by clouserw** [comment]
Closing this in favor of #1695

**Comment by lmorchard** [comment]
FWIW, since I had to dig for this, I think this was a branch-in-progress for this issue:

https://github.com/shane-tomlinson/fxa/commits/i881-payments-using-oauth-code-using-cookie
