### ISSUE TITLE
Cannot set snsTopicArn to disabled in fxa-graphql-api

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#17007]
## Description

It is said https://github.com/mozilla/fxa/blob/a50fcffbc31eeed01188b38ce6a9b0245cd966ca/packages/fxa-graphql-api/src/config.ts#L284

But actually:
https://github.com/mozilla/fxa/blob/a50fcffbc31eeed01188b38ce6a9b0245cd966ca/libs/shared/notifier/src/lib/notifier.sns.provider.ts#L15-L22

I think this is copied from https://github.com/mozilla/fxa/blob/a50fcffbc31eeed01188b38ce6a9b0245cd966ca/packages/fxa-auth-server/config/index.ts#L639

but it's implementation has consider the disabled condition.

https://github.com/mozilla/fxa/blob/a50fcffbc31eeed01188b38ce6a9b0245cd966ca/packages/fxa-auth-server/lib/notifier.js#L22-L31

------------------

**Also** when snsTopicArn  is disabled,  error shouldn't be raised when snsTopicEndpoint is undefined 

https://github.com/mozilla/fxa/blob/a50fcffbc31eeed01188b38ce6a9b0245cd966ca/libs/shared/notifier/src/lib/notifier.service.ts#L36-L38

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9716)

**Comment by vpomerleau** [comment]
Thank you for the report! We discussed this issue during triage and have moved it into our Jira backlog. PRs for this are welcome, but it's not currently on our short-term roadmap.
