### ISSUE TITLE
`/v1/certificate/sign` no longer works (This endpoint is no longer supported)

### ISSUE THREAD

**Issue by Mikescher** [mozilla/fxa#17126]
Hello,

I am the maintainer of [ffsclient](https://github.com/Mikescher/firefox-sync-client), a fxa cli client to query bookmarks/tabs/etc.

Since 2024-05-15 my normal [session-auth workflow](https://github.com/Mikescher/firefox-sync-client/blob/master/_data/readme-data/api-flow.svg) no longer works (the `/v1/certificate/sign` returns "This endpoint is no longer supported").

Is there (preferably) an easy way to update my code and make it work again? or can you give me a few hints where I should look.

What I have already done:
 - Looked at https://mozilla.github.io/ecosystem-platform/api#section/Response-format - but the EP ist still present there
 - Looked at https://wiki.mozilla.org/Identity/AttachedServices/KeyServerProtocol - but the wiki hasn't been updated since 2014
 - Tried to understand the code of https://github.com/mozilla/fxa/tree/main/packages/fxa-auth-client - but honestly that would be a lot of work just to find out what my auth flow is doning differently (at least I found out that the certificateSign() method is actually unused in this project)

&nbsp;

Kind Regards
 ~ Mike

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9860)

**Comment by dschom** [comment]
Thanks for reporting this. The `v1/certificate/sign` endpoint was there to support browserid which is phased out. Patterning your API usage after how our auth-client works is the correct approach going forward. 


We realize documentation for this is not sufficient at the moment, and we want to improve this. We will be updating our docs in the near future, and this should provide you with further support. If there are specific questions you have, feel free to respond, and we will try to make sure they are addressed.


By the way, the right hand side of your  [session auth work flow](https://github.com/Mikescher/firefox-sync-client/blob/master/_data/readme-data/api-flow.svg) diagram looks correct, and if you follow that flow you should be able to get the key needed to access your sync data (ie tabs, bookmarks, etc).

**Comment by Mikescher** [comment]
@dschom 
Thanks I managed to implement OAuth, looks like everything works again :D

If anyone else stumbles across this issue:  
The [codejam.info blogposts](https://www.codejam.info/2021/08/scripting-firefox-sync-lockwise-hybrid-oauth.html) were actually pretty useful to get everything working..
