### ISSUE TITLE
Third-Party Login Failure An error occurred while attempting to login via your third-party account.

### ISSUE THREAD

**Issue by pendurkar96akshay** [mozilla/fxa#17172]
## Description

Third-Party Login Failure
An error occurred while attempting to login via your third-party account.

The above error appears when google oauth is used for login.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-9982)

**Comment by LZoog** [comment]
Hi @pendurkar96akshay, thanks for filing an issue!

From testing, this seems to work as expected for me. If you close out of any tabs/windows where you're seeing this and try again, does it keep failing? If it does, is there anything in the Network tab for this request (like the response error) that might help us debug or find an associated error in our Sentry issues? (Please don't share any sensitive data here like your email address, if you need to share your email or anything else this might be better as a [Bugzilla ticket](https://bugzilla.mozilla.org/) where we can mark it as confidential.) Thanks!

**Comment by vbudhram** [comment]
If you are still having issues, please reopen.
