### ISSUE TITLE
Current FxA button bug

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#1720]
![IMG_4D3AB300B31C-1 2](https://user-images.githubusercontent.com/26334275/60924738-c5260080-a256-11e9-94ea-35175c7e6c6e.jpeg)

This disconnect button "..."

**Comment by shane-tomlinson** [comment]
@juliastarkov - is this a duplicate of https://github.com/mozilla/fxa/issues/1009?

**Comment by juliastarkov** [comment]
@shane-tomlinson Slightly different but I'll post to that thread so it's recorded and delete this bug.
