### ISSUE TITLE
There is no limit of characters on the display name option from Account Management section

### ISSUE THREAD

**Issue by abodea** [mozilla/fxa#1727]
## Steps to reproduce
1. Launch FF.
2. Login with valid credentials.
3. Open the Account Management page.
4. Tap on "Add" a "Display Name"

### Expected behavior
When adding a name to the account there should be a character limit. 
### Actual behavior
There is no character limit when adding/changing the account name in **`Account Management page`.**
### Device information

* Device: **`iPhone X(11.4.1), Google Pixel XL(Android Q Beta 4)`**
* Firefox version: **`v18.1 #15719 and latest Fennec RC build`**
### Notes
After adding more than 438 characters, when tapping change the following error is displayed: **`Invalid parameter in request body: %(param)s`**
![IMG_0011](https://user-images.githubusercontent.com/42831109/60958625-548eea80-a30f-11e9-9578-cbdc1700ce0f.PNG)

**Comment by shane-tomlinson** [comment]
Thanks for the report @abodea - this is a dup of #1418.
