### ISSUE TITLE
[payments] Close button for "Plan Not Found" cannot repair error

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1730]
In this code for the case when you link to a plan that doesn't exist, the close button on the error message simply reloads the page:

https://github.com/mozilla/fxa/blob/ee4f03a8e763423b33c8529b5273a9989deaec02/packages/fxa-payments-server/src/routes/Product/index.tsx#L156-L161

A not found is very likely a permanent error, and so reloading the page will only result in the same issue.

I'm not sure what it should do, though maybe the close button should simply be removed.

Other error messages in that file may be intermittent, and so reloading isn't unreasonable.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-191)
┆Priority: Medium
┆Issue Number: FXA-191

**Comment by lmorchard** [comment]
Yeah, I think I threw this message in there as a guard against bad API data. There isn't really a reasonable place for the close button to go, since this is basically a 404 Not Found
