### ISSUE TITLE
issue logging onto firefox on macbook

### ISSUE THREAD

**Issue by BFG-94** [mozilla/fxa#17321]
## Description
-when trying to log on to my profile in the application no matter if I am putting in an email, or password (gotten to by logging on the mozilla site and following a link once logged in)
Describe the issue that you're seeing.
-once putting in either parts of my credentials the page/application is stuck in the loading page while show absolutely no error messages
### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

What should happen?
-log in
### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-10254)

**Comment by clouserw** [comment]
Hi @BFG-94 .  Sorry you're having trouble.  Would you be more specific about the steps to reproduce this problem?  What URL are you trying to log in to?  Can you give us a screenshot of what the loading page looks like?  Thanks

**Comment by BFG-94** [comment]
Wil,
so this is when I have been trying to log on to the application.  I click
the profile icon on the app toolbar in the top right, and then the "sign in
to sync" from the about:preferences#sync page.  The application has pulled
my login username/email from when I have logged on to the mozilla website.
  When I enter my password and press "sign in" nothing happens except for
the sign in button becomes grayed out, and I'm not able to re-press it and
does not give any indication of loading.  I've attached 2 screenshots of
the app that show what I've been experiencing.

Ben

**Comment by clouserw** [comment]
Hi Ben.  I don't think attachments come through to issues so I can't see your screenshots.  It sounds like you're having trouble signing in to Firefox though.  I wonder what version of Firefox you're using and if you have any add-ons installed.

Regardless, you're in a place where you're talking to the engineering team (me) and I think the support team would have better tools to assist you.  You can get in touch with them at https://support.mozilla.org/en-US/questions/new/mozilla-account/form and they'll get back to you via email.

**Comment by BFG-94** [comment]
is this a good channel.  I have gotten absolutely no help from anyone with
this issue.  I would like to use this browser, but considering it is
failing a simple action, I'm pretty much being forced to switch back to
chrome.

**Comment by plwt** [comment]
Hi @BFG-94 .  I recommend that raise this as a support issue at https://support.mozilla.org/en-US/questions/new/mozilla-account/form.  The contributors in our Support Forum should be able to help you.
