### ISSUE TITLE
[Firefox For Fire TV] Focus moves to "Terms of Service" after entering email

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla/fxa#1735]
Part of https://github.com/mozilla/fxa/issues/1734

### Steps to reproduce
- From FFTV home screen
- Select button in the top right corner labled "CC"
-> Browser will navigate to sign in
- Hit enter to begin text input
-> Soft keyboard will slide up
- Enter email
- Select submit

### Expected
- Browser should navigate to password entry

### Actual
- "Terms of Service" link is focused

### FFTV build information
- Build from master at https://github.com/mozilla-mobile/firefox-tv
  - Use debug flavor (should be default)
  - Fxa is currently behind a feature flag. To enable:
    - Install application
    - Stop application (`adb shell am force-stop org.mozilla.tv.firefox.debug`)
    - Start application with Fxa flag enabled (`adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B`)
      - We have documentation on flagged code [here](https://github.com/mozilla-mobile/firefox-tv/wiki/QA)
- Should be run on a Fire TV device
  - The app mostly works on emulators, but some of these edge cases behave differently between Android and Amazon WebViews
- Please reach out to the FFTV team at #firefox-for-fire-tv on Slack for any help building the project

### Video
![tos_focused](https://user-images.githubusercontent.com/13170306/61011194-6338ca00-a32e-11e9-9749-853c71946632.gif)

**Comment by dannycoates** [comment]
reopening. i fixed the sign in page, also need to do the email first flow

**Comment by shane-tomlinson** [comment]
> reopening. i fixed the sign in page, also need to do the email first flow

You know, if we just did away with the legacy signin/signup pages and used email-first everywhere, this wouldn't have been a problem. &lt;More reasons to get that done, sigh...&gt; ref #639
