### ISSUE TITLE
[Firefox For Fire TV] Password keyboard - focus moves to next after entering character

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla/fxa#1736]
Part of #1734

### Steps to reproduce
- Enter email & continue [(see steps here)](https://github.com/mozilla/fxa/issues/1735)
- Enter password

### Expected
- Password is entered as expected

### Actual
- After the first character of the password is entered, focus moves to the "Next" button

### Notes
- This is the default Fire TV soft keyboard, we have made no changes to it
  - We have not seen this behavior on other sites
- This only happens the first time after navigating to the page
  - Even if the password is cleared, soft keyboard closed, and keyboard reopened, this will not be reproducible
- Sometimes (around half the time?) the cursor will move to be in front of the entered character

### Guesses
- Focus being programmatically moved to the input field is probably what is causing the keyboard to open after the button is clicked
- The button on the bottom right of the soft keyboard says "Next."  There should be a way to change this to "Submit", and submit the form whenever it is pressed

### FFTV build information
- Build from master at https://github.com/mozilla-mobile/firefox-tv
  - Use debug flavor (should be default)
  - Fxa is currently behind a feature flag. To enable:
    - Install application
    - Stop application (`adb shell am force-stop org.mozilla.tv.firefox.debug`)
    - Start application with Fxa flag enabled (`adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B`)
      - We have documentation on flagged code [here](https://github.com/mozilla-mobile/firefox-tv/wiki/QA)
- Should be run on a Fire TV device
  - The app mostly works on emulators, but some of these edge cases behave differently between Android and Amazon WebViews
- Please reach out to the FFTV team at #firefox-for-fire-tv on Slack for any help building the project

### Video
![next_button_focused](https://user-images.githubusercontent.com/13170306/61011188-5a47f880-a32e-11e9-9fd0-82cb5ef0e7ae.gif)

**Comment by johngruen** [comment]
@Baron-Severin do you happen know what events are emitted by the soft keyboard when characters are typed?

**Comment by Baron-Severin** [comment]
For characters, event.key is `Unidentified`, and event.code is a blank string.  For the "Next" button, event.key is `Tab`, and event.code is a blank string.  Not super helpful.

I also just noticed that the bottom right button in the soft keyboard is labled "Submit" until the first character is entered, at which point it changes to "Next".
