### ISSUE TITLE
[Firefox For Fire TV] Password validation is not visible until clicking "Sign In"

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla/fxa#1737]
Part of #1734

### Steps to reproduce
- Enter email & continue [(see steps here)](https://github.com/mozilla/fxa/issues/1735)
- Enter invalid password
- Press next
EXPECT -> password validation error is shown
ACTUAL -> nothing is shown
- Click the "Sign In" button
EXPECT -> password validation error is shown
ACTUAL -> error is briefly shown, before soft keyboard opens (hiding the error)

### Guesses
- Focus being programmatically moved to the input field is probably what is causing the keyboard to open after the button is clicked

### FFTV build information
- Build from master at https://github.com/mozilla-mobile/firefox-tv
  - Use debug flavor (should be default)
  - Fxa is currently behind a feature flag. To enable:
    - Install application
    - Stop application (`adb shell am force-stop org.mozilla.tv.firefox.debug`)
    - Start application with Fxa flag enabled (`adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B`)
      - We have documentation on flagged code [here](https://github.com/mozilla-mobile/firefox-tv/wiki/QA)
- Should be run on a Fire TV device
  - The app mostly works on emulators, but some of these edge cases behave differently between Android and Amazon WebViews
- Please reach out to the FFTV team at #firefox-for-fire-tv on Slack for any help building the project

### Video
![password_validation](https://user-images.githubusercontent.com/13170306/61011179-50be9080-a32e-11e9-9b14-8ddb4c64efdb.gif)

**Comment by dannycoates** [comment]
oof. latest doesn't even load the ui, just the spinner 🙈

**Comment by dannycoates** [comment]
I'm not going to change the validation behavior on "next" because that's a ux decision that changes / affects multiple platforms. I will fix the second issue of the on screen keyboard covering the validation message

**Comment by Baron-Severin** [comment]
I think that should be fine, I'm pinging our PM to double check.
