### ISSUE TITLE
Require Confirmation to Remove a Device

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#174]
We should require a confirmation (2 step) to disconnect a device from the device view.

A simple email could be the easiest way to do this.

When a user disconnects a device, send them an email to confirm the action to make sure it was intentional and that it was not done by someone else for malicious reasons.

**Comment by vladikoff** [comment]
@rfk @davismtl not sure if this should be in `fxa-features` instead to discuss it?

**Comment by davismtl** [comment]
You're right.
