### ISSUE TITLE
Only show password policy when password fields have focus

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1744]
Certainly on mobile, it's not great that we persist the password strength field when there is no focus on the password field. It could be affecting our registration success, though I have not explored it. Let's see if removing this panel when users blur the field improves success.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/68213/61059060-667f9480-a3c6-11e9-8517-b00401ae4159.png">

**Comment by LZoog** [comment]
This should not be an issue now. In fact, we have an [issue open](https://github.com/mozilla/fxa/issues/2705) for the field _not_ focusing on desktop when it should.
