### ISSUE TITLE
[Train 141]An 'unexpected error' is presented when you try to delete your account

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1745]
### Environment: ###
Builds: Stage [Train 141];
Devices: 
- Nokia 6 (Android 7.1.1);
- iOS 12.1.4;
- Sony Xperia Z2 (Android 6.0.1);
- Windows 10 - x64;

### Prerequisites ###
The user should be signed in with a valid account.

### Steps to reproduce: ###
1. Go to https://accounts.firefox.com/settings;
2. Click Delete button from the Delete account area;
3. Type the correct password then click Delete account;

### Expected results: ###
The account is successfully deleted.

### Actual results: ###
An 'unexpected error' is presented.

Notes:
- Not reproducible on production;
- a video with the issue: https://drive.google.com/file/d/0B-OVCGyglYi_X2VybWpubjBKeFlieWN1ZG5qQWR6cGtHMUI4/view?usp=sharing
- a logcat with the issue:
[unexpected_error.txt](https://github.com/mozilla/fxa/files/3382543/unexpected_error.txt)

**Comment by philbooth** [comment]
This is the same problem as #1740, will be fixed when 141.3 is deployed.
