### ISSUE TITLE
Payment page — increase vertical space

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#1749]
Payment page needs vertical space after each of top two lines:

![9C06D2E2-6532-414E-8E62-995B4A76453B](https://user-images.githubusercontent.com/6219141/61072998-773e0380-a3e2-11e9-9bad-1e4dfda9c798.jpeg)

**Comment by lmorchard** [comment]
Is there a measurement for this or a mockup with a measurement for exactly how much space to use here?

**Comment by janiceahn** [comment]
you're right, this reflects the spec.

but i think it does need some vertical space — @pwalm would you be able to take a look and give direction here?

**Comment by clouserw** [comment]
We took this section out.  CLosing
