### ISSUE TITLE
modal grammar pattern

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#1750]
The other modals do not have a period in the title. This screen has it. Is that intentional? This is more a question for Jeff Pfaller, whom I don't see on github.
![Screen Shot 2019-07-11 at 2 02 32 PM](https://user-images.githubusercontent.com/6219141/61074029-bd946200-a3e4-11e9-8631-99aa1f98e42b.png)

**Comment by janiceahn** [comment]
@jpfaller

**Comment by jpfaller** [comment]
@janiceahn periods shouldn't be in headlines, so remove it here.

**Comment by clouserw** [comment]
We should fix this before we extract strings

**Comment by janiceahn** [comment]
@clouserw when are we extracting strings?

I caught more capitalization inconsistencies in invision, and @juliastarkov has been trying nail down correct copy to update Zeplin specs.

@jpfaller is responsible for the corrections, and coordinating w/ julia.

**Comment by lmorchard** [comment]
> We should fix this before we extract strings

This is in payments-server, where we don't support l10n yet, so no string extraction here.

**Comment by lmorchard** [comment]
> I caught more capitalization inconsistencies in invision, and @juliastarkov has been trying nail down correct copy to update Zeplin specs.

At this point, can we have issues (or even just *an* issue) filed instead of / along with Zeplin changes? Especially if there are a lot of little copy changes - can't really tell what's different in Zeplin unless it's big design changes.

**Comment by janiceahn** [comment]
@lmorchard Yes, thanks for the direction.
