### ISSUE TITLE
date formatting inconsistent

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#1751]
other screens show July 09, 2020 format
this screen shows 07/09/2020 format

which is the correct format for FxA/Mozilla?

![Screen Shot 2019-07-11 at 2 05 26 PM](https://user-images.githubusercontent.com/6219141/61074185-1a901800-a3e5-11e9-91c7-c8e78703a653.png)

**Comment by janiceahn** [comment]
@jpfaller

**Comment by jpfaller** [comment]
Let's spell it out in all cases to avoid confusion with localizations that do it DD/MM/YY

**Comment by clouserw** [comment]
Let's do this before we extract strings
