### ISSUE TITLE
Fix devices & apps responsive view

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1752]
1. Unwrap prematurely wrapped text
1. Add horizontal padding to button (min 1em)

![Untitled-1](https://user-images.githubusercontent.com/68213/61075688-832cc400-a3e8-11e9-9461-f590e555d4ba.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - is this a dup of #1254?

**Comment by rbrishabh** [comment]
Can I take this up?

**Comment by ryanfeeley** [comment]
@shane-tomlinson It is a dupe! Closing.
