### ISSUE TITLE
Enable getActiveSubscriptions for content server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1753]
In [thinking through](https://github.com/mozilla/fxa/issues/1071#issuecomment-510610046) how to fetch a list of active subscriptions for issue #1071, it looks like I discovered some work needs doing to thread this resource through to the content server:

- [x] PR #1757 Add `sessionToken` to the [auth strategies for `GET /oauth/subscriptions/active`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/subscriptions.js#L88) in auth server - not unlike [what I removed](https://github.com/mozilla/fxa/commit/ab925f5df88adc789f33d17a4b326216d76acb46#diff-eedc9e44d94c523680530e9c145c9496R56) from my initial PR. This should probably get a test, too.

- [x] PR #1761 Tweak `fxa-js-client` to also use `sessionToken` rather than just an OAuth bearer token [in `getActiveSubscriptions()`](https://github.com/mozilla/fxa/blob/master/packages/fxa-js-client/client/FxAccountClient.js#L2538).

- [ ] Ship a new release of fxa-js-client to npm?

- [ ] Add `getActiveSubscriptions()` to [`fxa-client` proxies in `fxa-content-server`](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/lib/fxa-client.js#L1138).

- [ ] Add `getActiveSubscriptions()` to [the `account` model](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/models/account.js#L1283) for use in backbone views.

I *think* this is the whole list of things that needs doing to make the subscriptions list available to the account deletion view?

**Comment by lmorchard** [comment]
I was thinking a short-cut here might be to just implement a `sessionToken` supporting version of `getActiveSubscriptions` in the content server's `fxa-client` wrapper, and skip changing `fxa-js-client` for now. But that might be too much cheating.

**Comment by chenba** [comment]
This is relevant to my interest for #797 and #1078.

I actually have the last two items in my branch for #797, but using very shortlived bearer tokens.  If we switch to using `sessionToken` for active subscriptions, then there is no need for `fxa-js-client`'s `getActiveSubscriptions()` to use an OAuth bearer token.  At least not from the content server.

However, that `fxa-js-client` change is already published to npm.  :grimacing:

**Comment by lmorchard** [comment]
> If we switch to using sessionToken for active subscriptions, then there is no need for fxa-js-client's getActiveSubscriptions() to use an OAuth bearer token. At least not from the content server.

Well, we're not *switching* away from bearer tokens. We're going to need to *also* use sessionToken from *within* content server.

**Comment by chenba** [comment]
I understand.  I was not saying to switch away from bearer tokens _in the auth server_ for the subscription management endpoints.

I was suggesting that perhaps `getActiveSubscriptions()` in `fxa-js-client` does not need to support both kinds of tokens.  I added `getActiveSubscriptions()` to `fxa-js-client` because the content server will need to know about active subscriptions.  I don't know what other apps are doing or that they will use `fxa-js-client` for subscriptions management (hence "At least not from the content server").

**Comment by lmorchard** [comment]
Oh, huh... I thought all the support stuff got hosted on a different domain & app from content server. The payment pages don't use fxa-js-client (so far, at least). So, yeah, if only content-server stuff is using this stuff then only sessionToken needs to be supported right now.

**Comment by lmorchard** [comment]
Well, I went ahead with dual-token support in the client because I had it mostly working anyway 🤷‍♂  We can rework it as needed before merge if we don't want it there

**Comment by shane-tomlinson** [comment]
How come a sessionToken is needed/wanted here? The content server's /settings page already fetches itself [access tokens to get profile info](https://github.com/mozilla/fxa/blob/50fa1e2e189a0e4f6c63f39e350fe45f4414cf57/packages/fxa-content-server/app/scripts/models/account.js#L169), we could either add on to the scopes or mint a 2nd access token to get subscription info.

**Comment by lmorchard** [comment]
> How come a sessionToken is needed/wanted here? The content server's /settings page already fetches itself access tokens to get profile info

I hadn't seen that token creation before. Looks like most other auth-server calls from content-server use a sessionToken, so I figured that'd be the thing to do here too.

> we could either add on to the scopes or mint a 2nd access token to get subscription info.

Might be better to create a second token if we go that route? This would be going to auth-server, not profile-server

**Comment by lmorchard** [comment]
Looking through auth-server calls from content-server again. It looks like they all mostly use sessionToken. FWIW, this call isn't for the subscriptions capabilities info we include in the profile for RPs. This is the direct list of the user's subscribed products that we don't share with third-party RPs.

**Comment by chenba** [comment]
> Oh, huh... I thought all the support stuff got hosted on a different domain & app from content server.

Yeah... 🙁 I started to add the support form on payments server, but @bbangert pointed out that the token for accessing the form could expire before the user submit it.  (Similar to how the subscription management page redirects back to `/settings` on teh content server after the token expired.)

The (WIP) support form currently lives on the content server and uses very short-lived access tokens to get a list of active subscriptions and to submit the support form.

**Comment by lmorchard** [comment]
I believe this is basically resolved via PR #1773, using a short-lived OAuth token rather than wiring things up for a sessionTOken
