### ISSUE TITLE
[Epic] UX Standardization of Authentication Flows

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#1755]
All issues related to standardization of account flows in support of Skyline should be attached to this epic.

Feature doc:
https://docs.google.com/document/d/1HvcZvVHjrs1_gowfj72OmSWEjRIpbTiqkdMP7EJDSdY/edit#heading=h.9qtbe4mxitxr

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-195)
┆Issue Number: FXA-195

**Comment by davismtl** [comment]
CC'd @pwalm since he's working on UX. Can't seem to assign him too. (prob not on repo)

**Comment by pwalm** [comment]
👋

**Comment by davismtl** [comment]
- no change to about:welcome 
- need to follow up with @pwalm and update jennifer so we can do usability testing
- understand changes to newsletter subscription rates:
https://analytics.amplitude.com/mozilla-corp/chart/tzmumag

Meeting notes to the UX discussions we had:
https://docs.google.com/document/d/10Po5SNDqtH0hx381rLMnsaEls-qZARm3qkJrUpR1joQ/edit#

**Comment by davismtl** [comment]
Changes to be made:

- Deploy 1-ups from screens with password field to all touchpoints and flows
- Revert subhead Continue to Firefox to Continue to Firefox Sync
- Animate illustrations @LZoog started work on this
- Remove progress indicator
- Update password strength meter to latest and slimmest (see https://github.com/mozilla/fxa/issues/607#issuecomment-413675245) See also: https://mozilla.invisionapp.com/share/5UM3J3TXWMR#/screens/316338169_Artboard
- Remove style=trailhead and make these changes standardized everywhere

We discussed removing the 1ups but we will keep them until there are changes made to the about:welcome page.

A helpful reference is the table in this document:
https://docs.google.com/document/d/10Po5SNDqtH0hx381rLMnsaEls-qZARm3qkJrUpR1joQ/edit#

**Comment by pwalm** [comment]
A couple of questions: 
> Deploy 1-ups from screens with password field to all touchpoints and flows
Can we get more clarity on this? Does this mean 1-ups go on every single screen in the flow? Or just on the password screen of all versions of the flow?

> Revert subhead Continue to Firefox to Continue to Firefox Sync
What screen does this sit on? Can't seem to find it.

UX is good to go on everything else, don't think we need to provide guidance.

**Comment by davismtl** [comment]
I updated my post so that it is more clear but here are the answers.

> Can we get more clarity on this? Does this mean 1-ups go on every single screen in the flow? Or just on the password screen of all versions of the flow?

We added the 1ups to the password capture screen at trailhead for `style=trailhead`. We'll display the 1ups on the password capture screen even if `style=trailhead` is not specified.

> Revert subhead Continue to Firefox to Continue to Firefox Sync

Password capture screen. Rather than being specific about what the user was registering to, we were told to just say "Continue to Firefox" so that it was broader than just sync. We are undoing this work to revert back to being specific and transparent to users about what service they are registering to.

**Comment by davismtl** [comment]
going out in train 146

@davismtl sent QA documentation
@dannycoates mentioned to QA in Slack that it's going out in 146.

We need to track login and registration across the board after this goes out.

**Comment by davismtl** [comment]
@irrationalagent let's stand up a dashboard and track this now that it has shipped

**Comment by davismtl** [comment]
When we look at the part of the registration funnel that would have been impacted by this, there does seem to be a drop:
https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/q1qteof

The strange thing is that this seems to also impact about:welcome which already had a similar design and flow:
https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/lchry53

Could anything else have impacted these numbers? Does the fact that it also impacted about:welcome give us any additional clues about the cause of the drop?

**Comment by davismtl** [comment]
From Leif: there doesn't seem to be any impact to the login flow.

**Comment by davismtl** [comment]
Following discussions and analysis, we identified a few things that might have had an impact on the registration form submit.

As an outcome, I've filed:
- https://github.com/mozilla/fxa/issues/3056
- https://github.com/mozilla/fxa/issues/3055

Potentially related to this work, I also filed in regard to the drop in users connecting another device. Although, it's still not 100% clear if it's also related to our registration codes:
- https://github.com/mozilla/fxa/issues/3059

**Comment by davismtl** [comment]
*Next steps*
Alex to prepare Feature Doc to run quick progress bar experiment:
https://github.com/mozilla/fxa/issues/3056

**Comment by irrationalagent** [comment]
I logged a few results in the feature doc about the probable impact of the standardization on conversion to mobile after registration, but there is more to log here.

**Comment by davismtl** [comment]
Leif and I wrapped up this feature document. Communicate results at next product meeting.
