### ISSUE TITLE
[Epic] Smoother Authentication Flow

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#1756]
All issues pertaining to the smoother authentication flow for Skyline should be attached to this epic for tracking purposes.

**Comment by davismtl** [comment]
Seems to me that we're missing a feature document for this. @shane-tomlinson I'll schedule something.

**Comment by shane-tomlinson** [comment]
The one pager is https://docs.google.com/document/d/1ln8G1ieFnGnXTFVknDbgKTjLnouiUWJ7qUHCiqJtc5Y/edit. The committed deliverable is https://github.com/mozilla/fxa/issues/1371. Does that require a feature doc?

**Comment by shane-tomlinson** [comment]
Here is an ADR for the behavior: https://github.com/mozilla/fxa/blob/master/docs/adr/0005-minimize-password-entry.md

**Comment by davismtl** [comment]
- Do we know how we will measure success?
- Improved documentation for QA?
- So far, we have not written a feature document but we should assess if this is needed.

**Comment by davismtl** [comment]
Some noticeable changes to our login success rate:
https://analytics.amplitude.com/mozilla-corp/chart/hpw19iu

Unclear what proportion of users see a password prompt vs not, and the success rate of each cohort.

**Comment by davismtl** [comment]
It's unclear if we want to make this issue a blocker to closing this epic but it will be required to fully understand the impact of the more seamless login.

https://github.com/mozilla/fxa/issues/2438
