### ISSUE TITLE
[Epic] SubPlat Support for Secure Proxy

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#1759]
All work pertaining to the integration of Secure Proxy with the SubPlat should be opened under this epic for tracking purposes.

**Comment by davismtl** [comment]
All of the work has been done with the exception of a bug or two.

**Comment by lmorchard** [comment]
FWIW, assuming this is a second product - we may have to address multiple product support too (or at least parts of it) https://github.com/mozilla/fxa/issues/2078

**Comment by clouserw** [comment]
All tasks are finished here.  Closing.
