### ISSUE TITLE
event-broker: make the SQS region a config option and use it when constructing `new SQS()`

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1763]
Still bootstrapping, and I have a workaround, but probably should be considered for fix.

Starting up in stage I get errors for `notificationProcessor.consumerError` due to `"err":"SQSError: SQS receive message failed: Missing region in config"`.

Sorry, my typescript isn't great, but we pass in a `new SQS()`, ya? 

In https://github.com/bbc/sqs-consumer/blob/master/src/consumer.ts#L120-L122, the Consumer takes the injected object;  otherwise, it would create a default SQS, but make sure to set a region.

A simple workaround is to set `AWS_REGION="us-east-1"` in the container environment. But, perhaps, `region` should be a config parameter of the event-broker so that it's more explicit in the code (as opposed to a magic environment variable when deployed).

**Comment by shane-tomlinson** [comment]
cc @bbangert
