### ISSUE TITLE
Running auth server tests locally is a challenge

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1768]
Seems to test the auth server, running `npm run test`, you have to have none of the auth-server nor oauth-server servers running, but memcached and redis both need to be running.

To get the tests running locally, I have to do a `./pm2 start server.json`, then a `./pm2 stop 0`, `./pm2 stop 1`, `./pm2 stop 2`, `./pm2 stop 4`.

An alternative is to have no servers running and then start local memcached and redis instances. From the fxa directory:

```bash
> sh ./_scripts/redis.sh
```
And in another window
```
> sh ./_scripts/memcached.sh
```

I don't have a remedy at mind to make this better.

Ref #1064

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-197)
┆Issue Number: FXA-197

**Comment by vbudhram** [comment]
> An alternative is to have no servers running and then start local memcached and redis instances.

This is what I currently do. Although, I have memcache is redis running outside pm2.

We could update our scripts to start the services from `npm start` on a different port so it doesn't conflict with pm2 services.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
