### ISSUE TITLE
[fxa-event-broker] Finish productizing

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1774]
A few things that cropped up during deployment we should resolve:
- [x] Create a `__lbheartbeat__` route.
- [x] Implement `process.on` handlers as in `fxa-auth-server` and elsewhere for graceful restarts, logging of unhandled rejections ,etc.
- [x] Make a `simulate_webhook_call` script for use by ops to verify a RP has setup their webhookUrl handler correctly.
- [x] Handle 404's less noisily at debug level.
- [x] Log any malformed messages and ack to avoid clogging the queue.

**Comment by jrgm** [comment]
I'll add another item to this list:

- Handle 404 requests less noisily at debug level: Right now, a request for an unknown route produces a stack trace. (The internet has all kinds of random traffic (mostly looking for `..\..\..\..\system32.exe` and such ;-) ) and a single 404 log line is sufficient). [Yes, I have debug level on right now; that will change before going live, but thought it might be useful while getting this all up].
```
Debug: handler, error
Error: Not Found
at internals.notFound (/app/node_modules/@hapi/hapi/lib/core.js:623:16)
at module.exports.internals.Manager.execute (/app/node_modules/@hapi/hapi/lib/toolkit.js:41:33)
at Object.internals.handler (/app/node_modules/@hapi/hapi/lib/handler.js:46:48)
at exports.execute (/app/node_modules/@hapi/hapi/lib/handler.js:31:36)
at Request._lifecycle (/app/node_modules/@hapi/hapi/lib/request.js:312:68)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jrgm** [comment]
And another one. 

If there something malformed in the queue that can never be processed that message is not removed from the queue, and is handled again and again (until, I presume, the queue retention ages it out of the queue).

Sorry, I lost the stack for what was malformed, but it was something where I manually inserted into the queue a message like `{"event":"login"}` and it didn't like that it was missing required parameters.

**Comment by jrgm** [comment]
> Create a __heartbeat__ route.

And a `/__lbheartbeat__` route, which returns 200.
