### ISSUE TITLE
oauth-server errors: Couldn\'t find AWS credentials in environment, credentials file, or IAM role.

### ISSUE THREAD

**Issue by wavepack3t** [mozilla/fxa#1775]
When I run `pm2 start mysql_servers.json` (using a modified `mysql_servers.json` file which has creds for an account on my local mysql instance), initially all servers have status `online`, but 2 seconds later, when I check status with `pm2 status`, I see that `oauth-server PORT 9010` has errored.

When I check `pm2 logs` I see the following error:

```
17|pushbox | Jul 10 14:25:46.634 WARN SQS Rec'v Error: Credentials(CredentialsError { message: "Couldn\'t find AWS credentials in environment, credentials file, or IAM role." })
17|pushbox | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadConnection("Unknown MySQL server host \'mydb\' (-2)")', src/libcore/result.rs:999:5
17|pushbox | note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I have looked around this repo for some sort of AWS config file but I have not found it.
Is there some environment variable I am neglecting to set?

After a few more seconds, if I do `pm2 status` again it will show that two more services have errored out: `event-broker` and `profile-server`.

```
...
│ event-broker                        │ 20 │ 0.33.3  │ fork │ 0     │ errored │ 0       │ 0      │ 0%   │ 0 B        │ wvp │ disabled │
│ google-firestore-emulator PORT 8006 │ 22 │ 2.0.0   │ fork │ 27917 │ online  │ 0       │ 30m    │ 0%   │ 2.2 MB     │ wvp │ disabled │
│ google-pubsub-emulator PORT 8005    │ 21 │ 2.0.0   │ fork │ 27904 │ online  │ 0       │ 30m    │ 0%   │ 2.3 MB     │ wvp │ disabled │
│ memcached PORT 11211                │ 14 │ 2.0.0   │ fork │ 27831 │ online  │ 0       │ 30m    │ 0%   │ 2.3 MB     │ wvp │ disabled │
│ oauth-server PORT 9010              │ 5  │ 2.0.0   │ fork │ 0     │ errored │ 0       │ 0      │ 0%   │ 0 B        │ wvp │ disabled │
│ payments server PORT 3031           │ 18 │ 0.33.3  │ fork │ 27866 │ online  │ 0       │ 30m    │ 0.5% │ 33.8 MB    │ wvp │ disabled │
│ profile-server PORT 1111            │ 6  │ 2.0.0   │ fork │ 0     │ errored │ 0       │ 0      │ 0%   │ 0 B        │ wvp │ disabled │
...
```

It might be a separate issue but I can't seem to get Firefox Sync working with an existing profile of mine. If all servers are up and running and I have configured my `identity.fxaccounts.autoconfig.uri` key to point to `http://127.0.0.1:3030`, should I expect to be able to log in to Firefox Sync? When I click the Sign In button, nothing happens.

Verified this is still happening with current `master` for `mozilla/fxa`.

**Comment by shane-tomlinson** [comment]
@wavepack3t Which version of node, npm, and docker are you using, and on what OS? Are there any errors in any other logs. You shouldn't need pushbox really, the important errors are for the event broker, the oauth server, and the profile server.

**Comment by wavepack3t** [comment]
Closing this issue -- at the time I filed this, I hadn't correctly configured my mysql credentials in fxa.
