### ISSUE TITLE
Confirming backup authentication code impossible.

### ISSUE THREAD

**Issue by kaaraa** [mozilla/fxa#17799]
I am trying to add two factor authentication to my mozilla account as certain features on my account get locked behind it.

https://accounts.firefox.com/inline_recovery_setup?showReactApp=true
When I  get to Confirming backup auth codes part, I get the error message: 

There was a problem confirming your backup authentication code

I have tried 5 different codes and each one gives me the same error.
and I when I put in a different random set of characters it gives me a different error code:

Incorrect backup authentication code

Which leads me to believe mozilla does know the code which I put in are correct but something else is wrong.

I am currently on the Floorp browser on a machine running Debian 12.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-10530)

**Comment by LZoog** [comment]
Hi @kaaraa, thank you for filing an issue, we will take a look when we triage it.

In the meantime, does setting up 2FA inside of account settings work for you? https://accounts.firefox.com/settings/two_step_authentication

**Comment by kaaraa** [comment]
after going through the two factor authentication setup another time and having generated another set of one time authentication codes, I have gotten it to work!
