### ISSUE TITLE
Document Data Available in Re:Dash

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#178]
It would be super useful to document what we are making available in Re:Dash.

Here is an example of how the Android team documented their data: 
https://wiki.mozilla.org/Mobile/Metrics/Redash

**Comment by davismtl** [comment]
@shane-tomlinson as we discussed.

**Comment by vladikoff** [comment]
from mtg: waiting for flowEvents to appear

put it in FxA repo  like the Android wiki page

**Comment by vladikoff** [comment]
from mtg: some of it is done, some recent stuff is missing , needs info

**Comment by shane-tomlinson** [comment]
@philbooth says this is done.
