### ISSUE TITLE
Fix Lockwise icon in devices-and-apps view

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1782]
Now that https://github.com/mozilla/fxa/pull/1262 is out the door, my devices-and-apps view looks like this:

![Capture](https://user-images.githubusercontent.com/34695/61247654-d4e0a000-a794-11e9-9dee-ed61c9b6adda.PNG)

It's an improvement overall, but regressed the appearance of Firefox Lockwise:

* Lockwise connects to sync, so it gets a placeholder device record
* We default OAuth sync clients to deviceType=mobile
* So Lockwise now shows the default mobile device icon rather than the Lockwise icon

I think it would be reasonable, for OAuth clients with a device record, to show the OAuth client icon rather than the generic device icons.  This would also produce a better experience for Firefox Preview (which is currently showing up as a *desktop* device due to https://github.com/mozilla/application-services/pull/1314).

**Comment by rfk** [comment]
So I had a quick poke around at [how the icons are determined](https://github.com/mozilla/fxa/blob/91c94c7464190cab341dfed27f00b93018571788/packages/fxa-content-server/app/styles/modules/_settings.scss#L503), and I want to propose a bit of a refactor to how that's done to work better with oauth clients that are also devices.

Currently we determine the icon by client name, using rules like:

```
.client-oAuthApp[data-name='Android Components Reference Browser'] {
    background-image: url('/images/icon-device-phone-android.svg');
}
```

This seems fragile, because we might change the name on the backend and forget to update the rules on the frontend. It also won't play well with oauth device records, which can customize their display name.

What if instead, we selected the icon by client id, and applied it to all attached clients rather specifically to those of type `oAuthApp`? We could set a new data property `data-client-id` on the HTML element, and use a rule like this:

```
.client[data-client-id='3c49430b43dfba77'] {
    background-image: url('/images/icon-device-phone-android.svg');
}
```

This would require us to be a little more explicit about the list of clients (we "cheat" in a few places by pattern-matching on names like "Firefox Send") but TBH I feel like explicit is probably good here.

@shane-tomlinson what do you think, is it worth exploring something like this?

**Comment by shane-tomlinson** [comment]
I've always wanted to use the client_id. The only downside is that client ids can change from dev servers to stable to stage/prod, so we might have a proliferation of client ids in the CSS. That, or we keep the same client id for all environments.

**Comment by vladikoff** [comment]
Quick note, the 98adfa37698f255b client works fine for me in Prod:  
![image](https://user-images.githubusercontent.com/128755/61296914-167b4600-a7a9-11e9-8c79-493f0301250e.png)

**Comment by LZoog** [comment]
We could be explicit where we find necessary and pattern-match otherwise - `&[data-name^='Firefox Send'] {` seems like a pretty stable name/selector to me, and also makes it easy for someone starting out to figure out what it's for, but of course I respect you guys have been on the project for much longer. If we do go the ID route I think it'd make more sense for us to be consistent across environments than have superfluous CSS selectors in prod.
