### ISSUE TITLE
Map oauth-server errno 122 to an auth-server error

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1784]
Ref https://sentry.prod.mozaws.net/operations/auth-prod/issues/6052963/events/31641096/

The auth-server's new `oauthdb.revokeAuthorizedClient` method calls `/v1/authorized-clients/destroy` on the oauth-server, which can return an errno 122 `Unknown Token` if you try to destroy a refresh token that doesn't exist.  We need to map that back to an auth-server error code as part of the oauthdb wrapper.

**Comment by shane-tomlinson** [comment]
I did this in a PR last week and now can't find it.

**Comment by rfk** [comment]
Done in #1785
