### ISSUE TITLE
Change password tooltips are obscured by Firefox password manager dropdown

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1790]
<img width="738" alt="Screenshot 2019-07-16 at 13 12 50" src="https://user-images.githubusercontent.com/848085/61293402-839fd300-a7cb-11e9-8771-69b542a66264.png">

cc @ryanfeeley

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-200)
┆Issue Number: FXA-200

**Comment by ryanfeeley** [comment]
@shane-tomlinson Ouch… I suppose pinning the error to the top would fix this. We do this elsewhere I think, no?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is fixed with the new settings page.
