### ISSUE TITLE
2FA is broken, utterly, completely, and totally broken.

### ISSUE THREAD

**Issue by BartAgterbosch** [mozilla/fxa#17959]
As the title says, we're being forced to continue with 2fa if we want to log into our dev accounts, which for some reason we need in order to get our api keys, which for some reason we need to sign our code EVEN if that code is going to be run locally.
However, where on desktop the 2fa setup is broken on step 1, where it won't accept the 2fa code you put in, on mobile, where you can only get past that step using a non-firefox browser like brave (so double shame on you), you get stuck on the last step, where you have to fill in one of the backup codes as a verification, the only problem is that those backup codes contain both numbers AND letters, and the keyboard that is being forcefully pulled up is NUMERIC.
Not only that, even if you go back and try to copy paste one of the backup codes into the input box as some sort of last resort, that won't work either, because there's an unknown error that pops up when you try that.

Steps I've taken to "fix" the issue (I'm using "fix" very loosely here as it's the excuse some rando used to close this same issue 4 years ago):
Time syncing, didn't work.
Using different types of authenticators, didn't work.
Using different browsers, didn't work.
Using different platforms, didn't work.
Entering the secret manually, didn't work.
Clearing cookies, didn't work.
Disabling all possible adblockers, didn't work
Smashing the screen, didn't work.
Cursing all the Mozilla devs til the afterlife, didn't work.
Throwing the pc out of the window in a fit of blood boiling rage, didn't work.
Cursing all of the Mozilla executive's ancestors, didn't work.

Platforms and browsers it occurs on:
Windows 10 22H2 (not that it matters).
Ubuntu.
Debian.
Android 12.
Firefox desktop.
Chromium desktop.
Brave desktop.
Brave mobile.
Firefox mobile.
Chrome mobile.
Probably MacOS and IOS also because I don't see why they would be excluded from your serverside macaronicode, though I haven't confirmed that yet.

Now the egregious thing about this is, that this was an issue over 4 years ago, and that it never got fixed, however I see people complaining about this on reddit for months now, and it's still not fixed, yet you all wonder why people prefer to stick to chromium based browsers, it's because developing something for chromium based browsers doesn't force you to fight your way through dev hell in order to get just 1 simple tiny thing done.

Fyi if you close this for a bogus reason again like you did for years and years I will open 500 more

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-10684)

**Comment by Pseudonymity** [comment]
I tried for 2 hours to add 2FA to my account with no success... No wonder why... To see that this is already a old issue which is being ignored? Hmm.. Is there a reason to keep using Firefox?

**Comment by Pseudonymity** [comment]
I can confirm issue occurs also on MacOS 14.2.1 (23C71)

**Comment by BartAgterbosch** [comment]
Yea, though I've read a comment elsewhere that they're trying to patch the second issue, which is the one where it pulls up a numeric keyboard for the backup phrase, except what they're trying to patch is that it won't accept any of the phrases, unfortunately that is only 1 factor in this maze of broken features.
The 2fa itself being broken is something that has been a main subject of complaints for the past 4 years, maybe even before that who knows.. But I've seen it mentioned many times on reddit, on dev forums, on community forums, even in the issues raised here, they are all either brushed off by claiming it's a time syncronization issue (it's not, and if it is, it's on the serverside), or they're being ignored completely.
Unfortunately without access to the mozilla dev tools section of the mozilla account it's impossible to even do any beta testing, since any form of local testing that's not temporary requires you to sign it, which is now barred by a mandatory yet broken security system.
I'll give it this though, it's is indeed very secure, because nobody can get in, even if they own the account

**Comment by dkmar** [comment]
+1 Having trouble setting up a dev account because it can't confirm the backup auth codes. 
> There was a problem confirming your backup authentication code

MacOS 15.1 on Firefox and Safari

**Comment by chenba** [comment]
https://github.com/mozilla/fxa/pull/17958 should fix this issue.

**Comment by BartAgterbosch** [comment]
@chenba I hope so, does this not just refer to the backup code check though on mobile? Because it's currently broken on not only mobile but also on desktop, and on various stages too, not just that one, also the inital 2fa setup stage, for both the qr scan and the manual phrase

**Comment by BartAgterbosch** [comment]
@data-sync-user if this turns out to not get fixed, I will henceforth open 500 more issues, I was very serious about that, you are closing it as fixed before it is fixed, and forgive me for being sceptical but you have failed to fix it for 4 years straight while knowing it was broken.
If it turns out to not be fixed (again), I will keep opening exponentially more issues until it gets fixed

**Comment by chenba** [comment]
@BartAgterbosch Thank you for filing the bug; we appreciate it.  We are aiming to deploy the fix to production today (Nov. 4, North American timezones).  I'll comment again in this issue when the deploy's done.

**Comment by chenba** [comment]
Production deploy is done.

@BartAgterbosch Please reopen the bug if you can still reproduce.  Thanks!

**Comment by BartAgterbosch** [comment]
Yes it is actually fixed, I can hardly believe it, but it is indeed fixed, all stages of the setup, bravo

**Comment by chenba** [comment]
> when doing it for developer page

@cgrice can you explain what you mean by that or give us steps to try to reproduce the error?  Thanks!
