### ISSUE TITLE
Add card type icon in billing forms

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#1798]
Can we add the card icon into the CC form field once a valid CC is added? It is possible via Stripe. It makes the form feel more secure. 

From mockups:
<img width="277" alt="Screen Shot 2019-07-16 at 9 00 41 AM" src="https://user-images.githubusercontent.com/26334275/61313629-ad4b0100-a7af-11e9-8a50-c965ef05bf3b.png">

Currently in Storybook:
<img width="339" alt="Screen Shot 2019-07-16 at 8 56 53 AM" src="https://user-images.githubusercontent.com/26334275/61313567-8bea1500-a7af-11e9-9af0-4b689c79dcf9.png">

**Comment by lmorchard** [comment]
FWIW, it is possible through Stripe via their all-in-one credit card widget that combines all the fields (i.e. cc number, exp date, cvc, zip). It is DIY in the case where we're breaking up the fields here.

**Comment by juliastarkov** [comment]
@lmorchard how can I add this issue to V2 (or post-MVP) issues?

**Comment by lmorchard** [comment]
I just added this to the phase 2 release - we're using the [ZenHub](https://www.zenhub.com/) add-on, which adds things to the GitHub UI. But you don't see those UI elements (like epics & releases) without the add-on :/

**Comment by juliastarkov** [comment]
@lmorchard I just downloaded it, thanks :)

**Comment by clouserw** [comment]
We're not going to do this for now.
