### ISSUE TITLE
Add openAPI validation tests to the subhub spec

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#1799]
We can use the `x-amples` openAPI extension to let us specify subhub API tests as request/response pairs inside the API spec itself (see [example](https://github.com/wikimedia/operations-software-service-checker#basic-example)). These tests can be run against our subhub mock using the [`swagger-test`](https://github.com/earldouglas/swagger-test) npm library, and they can also be run against the python subhub API using the python [`service-checker`](https://github.com/wikimedia/operations-software-service-checker) library.

One unclear bit is how to use fixtures to simulate stateful behavior. The stripe API uses the `x-resourceId` extension for this, but need to see if the tooling supports it. If not, we can just use these tests for input validation.

Goals here:
- move a few basic validation cases into the openAPI spec 
- get spec-based tests passing in this repo, along with our existing tests
- open a PR into subhub to add the `x-amples` to the official spec in their repo

As a next step, we can enhance type definitions in the openAPI spec and add corresponding test cases to the spec.

Related to #1082.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-205)
┆Issue Number: FXA-205

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

no more subhub
