### ISSUE TITLE
FEATURE: "Choose what to sync" on the web

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#18]
![image](https://cloud.githubusercontent.com/assets/128755/8689013/8642ed90-2a57-11e5-989a-bc963ee82d46.png)

Notes:
- [ ] Desktop Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1183917
- [ ] Figure out support in clients (Desktop, Android, iOS): Desktop only for now
- [ ] Events:
  - choose-what-to-sync started, cancelled choose-what-to-sync 
- [ ] ~~Tell Firefox iOS team to use it instead of spending time on the native view iOS is shipping without the signup options~~
- [ ] Content Server pull request: https://github.com/mozilla/fxa-content-server/pull/2757
- [ ] Content server bug: https://github.com/mozilla/fxa-content-server/issues/2303
- [ ] Experiments PR: https://github.com/mozilla/fxa-content-experiments/pull/22/files

Flow: https://www.lucidchart.com/documents/view/92d0ec74-a2af-40b8-b714-6db99149e39c

**Comment by ckarlof** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1183917

**Comment by vladikoff** [comment]
note: client should send a list of engines it supports. i.e if i am on Nightly and there is a new feature, nightly would send that feature in the engines list, so I can choose to sync it.

**Comment by rfk** [comment]
> client should send a list of engines it supports

This could make for some interesting localization hoops to jump through.

**Comment by zaach** [comment]
> This could make for some interesting localization hoops to jump through.

Yep– this is conceptually similar to reliers passing in scopes, which we'll need to localize as well.

**Comment by edmoz** [comment]
in speaking with Vlad - we're targeting fx43 (Aug-21) to land all client dependencies and to ship publicly by Dec 10

**Comment by vladikoff** [comment]
@ryanfeeley could you please upload a PNG version of this choose-what-to-sync graphic somewhere:
![image](https://cloud.githubusercontent.com/assets/128755/8944948/7f7c2ed6-3551-11e5-9b02-799a35731a09.png)

**Comment by ryanfeeley** [comment]
@vladikoff 

![sync](https://cloud.githubusercontent.com/assets/68213/8960990/aa18ddd0-35e0-11e5-8b9d-98161006c362.png)

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-33

**Comment by rfk** [comment]
@vladikoff I didn't close this one because I didn't want to lose any of the above context.  What do you want to do with it?  One option is to migrate the key points above into Aha and close it out here, the open concrete implementation bugs when it comes off the backlog.

**Comment by rfk** [comment]
(I created a milestone for it as well, in case there's other bugs you want to tag into it for context.  If there aren't any, let's also delete the milestone)

**Comment by ryanfeeley** [comment]
@rfk I'd really like to see this feature happen. Helps us improve onboarding in a few ways.

**Comment by rfk** [comment]
> I'd really like to see this feature happen

Fear not, it still lives!  But let's coordinate prioritization and scheduling in aha at https://mozilla.aha.io/features/FXA-33

**Comment by rfk** [comment]
In the product meeting, we scheduled this for work in the Fx44 timeframe, so it should surface again in a couple of iterations time.  I'm gong to leave this bug open, but remove the associated milestone for now to keep things clean, we can bring it back when we gear up to work on it some more.

**Comment by ryanfeeley** [comment]
Something just occurred to me speaking with Joe Cheng from the FFOS TV team

We have account holders that are not sync users.

When they sign in to sync for the first time, currently they don't get to choose what to sync. Everything is on by default.

We should perhaps set a flag at the account level so that if an existing account holder is signing into sync for the first time, they see the choose what to sync screen.

Thoughts @rfk @vladikoff @billmaggs?

**Comment by billmaggs** [comment]
Yup. That is true. We should talk to the FxOS guys to find out what their
expectations are. They have prototyped a Sync experience (with most if not
all data types) and are now supposed to be productizing  it. So it is
relevant just for FxOS users.

Bill

**Comment by rfk** [comment]
> We should perhaps set a flag at the account level so that if an existing account holder is signing
> into sync for the first time, they see the choose what to sync screen.

This seems like a good idea.  The appropriate flag might be "this is the first time you're connected a device" rather than something tied specifically to sync.

TBH I'm not thrilled with the amount of sync-specific logic that's showing up in FxA, continuing to blur the technological line between "FxA" and "Sync".  I don't have a good sense of that the right abstraction is, but I do know that we haven't found it yet.

**Comment by ryanfeeley** [comment]
@rfk It's even a bit awkward in Chrome. The Chrome setup page is a real odd duck of their sign-in page.

I would only ask users to choose what to sync when they are signing up for sync. Otherwise would seem odd (e.g. a web-based relier).

**Comment by ckarlof** [comment]
This is not just a FxOS issue. The user could have signed up for Pocket or Hello, and then signs in to Sync. 

Others might say we need some "service discovery" service to solve this problem. I would say that after the user signs in, we contact Sync and figure out if the user has set up Sync yet. 

In terms of the abstractions, you could imagine treating Sync as just another Web relier. After FxA finishes the log in, we redirect the page to Sync and let it figure out what the most appropriate thing to do is. This requires Sync to grow some new stuff, but I feel it could keep the boundaries cleaner.

**Comment by rfk** [comment]
> This requires Sync to grow some new stuff

Yeah, I feel like this part is inevitable, and we'll end up morphing `token.services.mozilla.com` into a more elaborate sync meta-data API, possibly with some web content for viewing status, completing setup, etc.

**Comment by vladikoff** [comment]
Better assets for the sync image: 

https://www.dropbox.com/s/obqros0kcgrlp42/SYNC_IMAGE-1920.psd?dl=0

**Comment by vladikoff** [comment]
![](https://photos-2.dropbox.com/t/2/AAA--7Ul1RtpU7TL8XZ8m1kLAd9i9n9ZEtaQy1Gxuo0jKA/12/5265484/png/32x32/1/1444075200/0/2/SYNC_IMAGE-1920.psd/CMywwQIgASACIAMgBiAHKAEoAigDKAc/jHXMcMylkXAl0vaOuI5MpmaAvSh87CnbpVaskbOXN3Y%2CvRpS5D_1VA1fUEEEaJyoTOP-uw5iaaQWFRLgnJsucO4%2Cc_0mKzsvu1jQweau5wTbcPUfBPb_EnZXQBgJWJ2D4hg%2CbfX19c0eBPrByDWxudG-na3mwU4hyjrTFBbOfheLSJE%2CS61aakRqbdaZaJ64Wkn89UyyeGWJZQR5DbV75QT6IrY%2Co_UQz2vTTEn4V5LnTPr6JL86okqgzaz-JWYHxwKhOcc%2CuXND-LzFF3pspK5nTesAbXNVRlmaTSclpGT01dtuuMM%2CyKs5oW0dErPxTSX1USRDxs05_yvH4m6quX7fjdYPoDY%2CbrPJezOd4gF1sYZ9HNCX0F-VtdY2rKzF_cncZvu8Ag0%2CUzvKFGEaGvrQr1iZBmwBdvL1fPuPZGZMzxox2tVPtdU%2CjoYaanfcLIvtUnmwWvYDIHgbeS6WofNl4-XEKGTT8OQ%2ChqkVr8RGa6gTXSigavxf_xgFfxTwdQm0QeBVqHvuCMo?size=1024x768&size_mode=2)

**Comment by vladikoff** [comment]
this is tracked in Aha and in https://github.com/mozilla/fxa-content-server/issues/3080 for Fennec
