### ISSUE TITLE
[Epic] Metrics for Subscription Platform

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1800]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-206)
┆Issue Number: FXA-206

**Comment by davismtl** [comment]
- Goal is to add these events and properties before Skyline.
- Should help measure revenue, cancellations, support, CC management, etc.
- Revenue will be in Stripe for MVP. Might track initial purchase. Will have to follow up with recurring payments.
