### ISSUE TITLE
Each signin to Monitor produces a new refresh_token, and appears separately in the devices-and-apps list

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1802]
Every time you sign in to https://monitor.firefox.com, it generates a new OAuth `refresh_token` attached to your account. If you sign in on multiple devices (or sign out and back in multiple times on the same device) then your devices-and-apps list will end up containing lots of duplicate instances of Monitor, like this:

![Capture](https://user-images.githubusercontent.com/34695/61342332-38e68f80-a88d-11e9-88c4-8a21c5479509.PNG)

As far as I can tell, the Monitor backend only stores a single refresh token in its DB, and each new login to the service will [overwrite the previous token with the new one](https://github.com/mozilla/blurts-server/blob/004079f5fc7b98f23e262242c7ca7e1ec0877f93/db/DB.js#L255).  So only one of the "Monitor" entries in my devices-and-apps list is valid, and the others are orphaned tokens.

How can we improve this situation?  Some possibilities:

1. We could just collapse all the tokens for Monitor into a single entry in the devices-and-apps list, essentially giving Monitor back the behaviour it had before #1262.
2. Monitor could destroy its current `refresh_token` when overwriting it with a new one. It already [checks for an existing user record](https://github.com/mozilla/blurts-server/blob/004079f5fc7b98f23e262242c7ca7e1ec0877f93/controllers/oauth.js#L74) when processing a signin, so this wouldn't require any more database lookups. 
3. We could have FxA silently re-use the existing `refresh_token` for non-public clients, rather than issuing a new one each time the user connects. I believe some other OAuth implementations do this already.
4. We could implement [incremental OAuth](https://tools.ietf.org/html/draft-ietf-oauth-incremental-authz-02), allowing Monitor to explicitly tell us to re-use an existing `refresh_token` if it has one.

My personal opinion is that we should do (2) in the short-term and (4) in the longer term, but it's weakly held.

/cc @groovecoder

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-207)
┆Priority: Medium
┆Issue Number: FXA-207

**Comment by shane-tomlinson** [comment]
> My personal opinion is that we should do (2) in the short-term and (4) in the longer term, but it's weakly held.

This is exactly what I was thinking when we discussed this in our 1:1.

**Comment by rfk** [comment]
> Monitor could destroy its current refresh_token when overwriting it with a new one

Filed as https://github.com/mozilla/blurts-server/issues/1131

**Comment by rfk** [comment]
This has been closed on the Monitor side, so closing here. Please re-open if this still causes problems.
