### ISSUE TITLE
Question: Should we move the fxa-oauth-console back to its own repo?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1807]
the fxa-oauth-console isn't really needed for day to day life of a developer, isn't set up on stage or prod, and isn't really well maintained like our other services. It has a bunch of [outdated deps that cause security warnings](#677), and updating them has proven more painful than I'd like.

Should we move it back to its own repo?

**Comment by vladikoff** [comment]
I can also give another look at updating the deps of this as well

**Comment by vladikoff** [comment]
> Should we move it back to its own repo?

👍 I am for this
