### ISSUE TITLE
[content server] Reduce the number of auth server hits from the settings screen

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1808]
When you load the settings screen it hits the auth server a whole heap of times, mostly requesting the same resource over and over. We could make a huge reduction in auth server traffic and improve client side performance a bit if we optimised that.

Most of the calls are to `GET /recovery_email/status`, but there's also 2 to `GET /totp/exists` and 1 to `GET /recovery_emails`. Chatting to @shane-tomlinson just now, he said it's probably because each of the settings child views makes it's own independent requests to the auth server.

Instead, we should have one gestalt-status endpoint that returns all of the necessary data for every child view, and request that once only from the parent view. It can then pass data into whichever child views want it and everything should work the same, except now we've helped avert climate change and everyone has extra bandwidth. Peace breaks out in the middle east.

<img width="865" alt="Screenshot of the FxA settings screen repeatedly hitting the auth server for the same resource" src="https://user-images.githubusercontent.com/64367/61378345-ba8deb80-a894-11e9-8f74-08c2ab2178f9.png" />

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-209)
┆Issue Number: FXA-209

**Comment by philbooth** [comment]
> but there's also 2 to `GET /totp/exists`

Actually no, there's 1 to `GET /totp/exists` and 2 to `POST /totp/exists`. The posts seem especially weird because I don't have totp set up on this account and the request data is an empty object. Presumably they can just disappear completely.

**Comment by philbooth** [comment]
I'm thinking of making the new gestalt endpoint just plain `GET /account`. That differentiates it better from the various `/status` endpoint we have, as something that is not meant for polling. And hopefully hints a bit that other properties may be added to it readily whenever needs arise, it's not limited to whatever set we start with.

**Comment by vbudhram** [comment]
@philbooth The bulk of those calls are caused by panel gating, https://github.com/mozilla/fxa/blob/8701348cdd79dbdc9879b2b4a55a23a135a32bc1/packages/fxa-content-server/app/scripts/views/mixins/upgrade-session-mixin.js#L129. Currently, the email, account recovery and 2FA panels will show an `Upgrade session via email` screen before you can actually use those features.

Ideally, we should cache the result in the user or account model and have that panel check that value.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Done with new settings
