### ISSUE TITLE
"Mozilla email preferences" shows in the devices and apps list

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1810]
The "Mozilla email preferences" are implemented as an OAuth RP, causing an entry to appear in the Devices and Apps list:

<img width="674" alt="Screenshot 2019-07-17 at 14 33 57" src="https://user-images.githubusercontent.com/848085/61379940-62f57d00-a8a0-11e9-8dd2-ebba812957a8.png">

While this isn't the end of the world, it's slightly weird. Should these access tokens have a super short ttl, just long enough for Basket to get the user's profile info and then we can just let the token automatically expire, minimizing the amount of time they are displayed in the list?

cc @pmac

**Comment by pmac** [comment]
That sounds good to me 👍

**Comment by clouserw** [comment]
@pmac would you make this change?

**Comment by pmac** [comment]
I'm not really up to speed on doing dev work on FxA itself. I think someone on the FxA dev team would be much faster and better at this request. I can do it if there's no one else but it'll have to be very low on my priority list behind all of my team's priorities.

**Comment by shane-tomlinson** [comment]
> I'm not really up to speed on doing dev work on FxA itself. I think someone on the FxA dev team would be much faster and better at this request. I can do it if there's no one else but it'll have to be very low on my priority list behind all of my team's priorities.

@pmac - when you trade the authorization code for the access token, [set a short `ttl`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/docs/api.md#post-v1token). Since all you are doing is getting the user's email address, even a ttl of 60 (1 minute) *should* be sufficient, you might want to go with 300 (5 minutes) to handle any clock skew though.

**Comment by shane-tomlinson** [comment]
> @pmac - when you trade the authorization code for the access token, set a short ttl. Since all you are doing is getting the user's email address, even a ttl of 60 (1 minute) should be sufficient, you might want to go with 300 (5 minutes) to handle any clock skew though.

All this means to say is that requesting a short lived access token would be something on the basket end rather than FxA.

**Comment by pmac** [comment]
Ah! Great! Thanks for the clarification. I'll file a basket issue for this and get it in ASAP.

**Comment by vbudhram** [comment]
from mtg:

This is has been fixed on basket side of things. Closing.
