### ISSUE TITLE
Allow the secure proxy to use a short scope name

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1813]
The secure proxy uses a scope name of `https://identity.mozilla.com/apps/secure-proxy`, and this helps bloat the resulting JWT access token. We could shave a few bytes by allowing a scope name of `secure-proxy` or even `proxy`.

cc @bakulf

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-213)
┆Issue Number: FXA-213

**Comment by rfk** [comment]
Using `mpn` would be even shorter, but maybe a little too obtuse...

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This isn't on the roadmap.
