### ISSUE TITLE
Improve Fenix device name

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1816]
Would love to see our default device names behave the same away across all platforms. I think only Fenix is out of compliance currently.
![fenix-device](https://user-images.githubusercontent.com/68213/61388311-b0182580-a885-11e9-975f-58465dfbdaf3.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-215)
┆Issue Number: FXA-215

**Comment by shane-tomlinson** [comment]
Does this overlap with https://github.com/mozilla/fxa/issues/1531?

**Comment by ryanfeeley** [comment]
Definitely related.

**Comment by rfk** [comment]
I think we need to split this up:

> Would love to see our default device names behave the same away across all platforms [...]
> * Prepend device owner name
> * Prepend browser name

The client will almost immediately overwrite any default name that we construct on the FxA side, so these changes really need to come from the client.

We should file this as a Fenix (or maybe a-c?) bug. @grigoryk which is the correct location?

> Use Android compound icon

This one we can fix here in FxA, perhaps as part of #1782.

**Comment by ryanfeeley** [comment]
@rfk I showed the above image to @vladikoff first and he suggested I file it here, although yeah, it does seem more like a Fenix bug.

**Comment by rfk** [comment]
It's a combo bug really, a bit we can do on both sides.

**Comment by ryanfeeley** [comment]
https://github.com/mozilla-mobile/fenix/issues/3886

**Comment by mheubusch** [comment]
@ryanfeeley Firefox for Android doesn't pull in device user's name either AFAICT.

**Comment by clouserw** [comment]
This is fixed now
