### ISSUE TITLE
Create a password reset dashboard showing number of devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#182]
We know that single-device users who reset their passwords are erasing their Sync backup.

What is the breakdown of resets by device?

In order to address this problem, it's good to have a sense of scale.

From today’s standup @rfk @vladikoff

**Comment by rfk** [comment]
We can probably do this in re:dash, where we have a useful notion of how many devices the user has, and we have the `account.reset` activity event.

Some questions I think would be worth answering:

* What percentage of password resets are done by single-device users?
* What percentage of users who do a password reset, succeed in getting a device re-connected to sync?
* What percentage of users who do a password reset, don't succeed in re-connecting all their devices?

**Comment by ryanfeeley** [comment]
@rfk 👍

**Comment by rfk** [comment]
@ryanfeeley is this similar enough to https://github.com/mozilla/fxa-auth-server/issues/1444 that we should close one in favour of the other?

**Comment by ryanfeeley** [comment]
@rfk Yes, your chart was enough of a wake up call.
