### ISSUE TITLE
[fxa-content-server] force_auth oauth flow goes back to signin instead of force_auth

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1825]
* Start a force_auth flow: [flow url example](https://accounts.firefox.com/oauth/force_auth?action=email&response_type=code&email=vlad2%40restmail.net&client_id=a2270f727f45f648&redirect_uri=https%3A%2F%2Faccounts.firefox.com%2Foauth%2Fsuccess%2Fa2270f727f45f648&scope=profile%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync&state=rzFQEEzTUIvVevdh_w9SfA&code_challenge_method=S256&code_challenge=WpM-XFy2qZi5mwCA9j5gpsI3ArYBBD6WC3D02MNYJZ4&access_type=offline&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6InNmQjRDLWtwalN1aXUyeUFYU21zejl1TEYyRXlRa3VBMlZlLXNVYXhtSGciLCJ5IjoiOEV2OU8yZWwyTk9DOXBkRzRDbkJMaGxBczJERXRuQlZMcEtkU3pydlVEUSJ9)
* Click "Forgot password"
* Click "Remember password"

## Expected 

* Goes back to force_auth

## Actual

* Redirected to Sign in

![force_auth_oauth](https://user-images.githubusercontent.com/128755/61404844-655ad580-a8a6-11e9-917a-7eaa3e4edb63.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-217)
┆Issue Number: FXA-217

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
