### ISSUE TITLE
Convert subhub joi validators to openAPI spec constraints

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#1829]
It would be good to have a single source of truth for route validation on both fxa and subhub sides.

We have a lot of implicit constraints in our joi validators that the subhub team can't see.

These could either be manually converted, or we could use a tool like [joi-to-swagger](https://www.npmjs.com/package/joi-to-swagger) to automatically convert the constraints for us.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-219)
┆Issue Number: FXA-219

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

no subhub
