### ISSUE TITLE
Cancelling a subscription when the auth is expired doesn't do anything

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1834]
I reproduced this on accident by hanging out on the subscriptions management page for longer than the temporary token is good for. Then clicking the 'Cancel subscription' button gets a 401, and nothing at all happens on the screen. No error, no redirect, no message pop-up, etc.

This triggered a Sentry error as well:
https://sentry.prod.mozaws.net/operations/fxa-payments-dev/issues/6062255/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-220)
┆Issue Number: FXA-220

**Comment by lmorchard** [comment]
Hmm, that should at least display an error dialog. But also, we should fix it with a token refresh in issue #1694

**Comment by clouserw** [comment]
This may become obsolete once payments is a full RP

**Comment by lmorchard** [comment]
Just for cross-reference: issue #1695

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks Les.  Closing this as it will be fixed with the issue you linked.
