### ISSUE TITLE
Enable "bn" locale, remove "bn_BD" and "bn_IN"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1840]
Follow on from https://github.com/mozilla/fxa-content-server-l10n/issues/358 where "bn_BD" and "bn_IN" are merged into "bn"

**Comment by clouserw** [comment]
+cc @flodolo

**Comment by clouserw** [comment]
Is this a good first issue?

**Comment by flodolo** [comment]
@peiying2 is in charge of localization for that product (also initiated the request). She can answer on the timing or other questions ;-)

**Comment by peiying2** [comment]
@clouserw we are unifying two Bengali flavors into one to best leverage community resources. We are moving or consolidating them to a single `bn` for all products/projects. We got the buy-in from the communities before moving with this plan. In Pontoon, `bn` is the only locale they can contribute to for this product.

**Comment by clouserw** [comment]
Cool, no problem.  This was just an FYI ping since it had to do with L10n.  Sounds like we're all coordinated already. :)
