### ISSUE TITLE
Add credit card icon to card number element in payment form

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#1842]
Originally a part of #1666 

This was deprioritized for the [train 142 milestone](https://github.com/mozilla/fxa/milestone/104)

Context for what all this entails can be found in https://github.com/mozilla/fxa/issues/1666#issuecomment-511540724

**Comment by LZoog** [comment]
Note:
If this icon will be pulled from Stripe, it's likely going to be blocked by CSP when https://github.com/mozilla/fxa/pull/2053 is merged. This may require one or more directive additions found under "Checkout": https://stripe.com/docs/security#content-security-policy

**Comment by clouserw** [comment]
We can close this for now.
