### ISSUE TITLE
Advertize introspection endpoint in authorization server metadata

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1844]
We currently advertise some endpoints via https://accounts.firefox.com/.well-known/openid-configuration, but not all.  Over in https://github.com/mozilla/application-services/pull/1429 we're adding some code that uses the "token introspection" endpoint, so it would be useful to advertise at least that one.

There's a spec for doing so in https://tools.ietf.org/html/rfc8414.

**Comment by clouserw** [comment]
I think this is a good first issue..
