### ISSUE TITLE
[auth server] Either reinstate the api docs script, or delete the api docs

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1845]
In https://github.com/mozilla/fxa/pull/1824#discussion_r304956725, it was pointed out that I forgot to document a new endpoint. Because I'm lazy, I decided to fix it by sneakily bringing back the [docs script](https://github.com/mozilla/fxa-auth-server/pull/2988) just to generate them for that one new endpoint.

The resulting diff highlighted other cases where the docs have not been updated recently, or had gone stale for other reasons; for new endpoints, new validation schemata, new properties in response bodies, new error codes, changes to error codes, assorted refactorings etc and so on.

Of course, as ever, there were also some things that the script got wrong, which was the reason we deleted it in the first place. But the exercise has raised a couple of questions for me:

* Which is worse; documentation that is up to date but has some omissions where an automated script didn't behave correctly, or documentation that hasn't been updated at all and is just plain wrong in some cases?

* If nobody notices the docs are wrong for 3 months, is there any point in having docs? Why are we spending dev time maintaining (or pretending to maintain) something that nobody uses?

Fwiw I'm in favour of deleting the API docs completely, and dropping the pretence that they're somehow accurate or that we actively maintain them. I don't think anybody refers to them, ever, and they're a total waste of time. By definition, they'll always be less accurate than just reading the source code, which is what I think most people do anyway.

In case anyone's interested in the diff, it's here:

https://github.com/mozilla/fxa/compare/pb/get-account-docs?expand=1#diff-b73c5082111d34ac941c5abd568d519f

End of rant! :smile:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-223)
┆Issue Number: FXA-223

**Comment by shane-tomlinson** [comment]
> If nobody notices the docs are wrong for 3 months, is there any point in having docs? Why are we spending dev time maintaining (or pretending to maintain) something that nobody uses?

> Fwiw I'm in favour of deleting the API docs completely, and dropping the pretence that they're somehow accurate or that we actively maintain them. I don't think anybody refers to them, ever, and they're a total waste of time. By definition, they'll always be less accurate than just reading the source code, which is what I think most people do anyway.

I disagree. I use them often, and I also regularly point people at the OAuth server docs so they know how to request access tokens using refresh tokens, or call the /authorization endpoint.

**Comment by philbooth** [comment]
> I use them often

Ok. They're wrong btw, so be careful how you use them.

> I also regularly point people at the OAuth server docs

I'm not talking about those ones fwiw.

**Comment by philbooth** [comment]
In https://github.com/mozilla/fxa/pull/1919#issuecomment-514663455, it was suggested we use swagger instead:

https://github.com/glennjones/hapi-swagger

**Comment by bbangert** [comment]
I had the same thing happen when using the fxa-auth-db-mysql docs. The docs said a totp endpoint field was `enable`, it was actually `enabled`.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We'd like to have auto-documenting docs.  We're going to file a separate issue to make sure we can auto-generate docs, but that isn't this issue.
