### ISSUE TITLE
"$0.5 per month" when setting up a subscription

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#1847]
When setting up your subscription, the checkbox at the bottom of the page says "I authorize Mozilla, maker of Firefox products, to charge my payment method $0.5 per month [...]"

There is some wrong formatting, or math, or something there.

**Comment by clouserw** [comment]
Changing this milestone to be 142 in case this is a string change

**Comment by lmorchard** [comment]
I think the price is 50 cents in subhub, but we divide by 100. Should be formatted as currency here, though.
