### ISSUE TITLE
Support linking to subscription management page

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1850]
The user can currently get to the subscription management page by clicking a "Manage" button from FxA settings. However, emails like in issue #927 want to *link* to that page.

We supported linking to product payment pages in #926 - that's a content-server URL which generates an access token and then redirects to the payment page. We could follow that pattern to also support token-and-redirect to the subscription management page.

**Comment by shane-tomlinson** [comment]
Linking directly to the content server and redirecting to payments with an access token w/o doing the initial OAuth setup suffers all the same security problems as the [link with the access token from the settings page](https://github.com/mozilla/fxa/issues/1696).

A more secure and OAuth compliant implementation would be to make the payments page a full OAuth RP and finish support for [prompt=none](#640). Link directly to the payments page, have the payments page set up the OAuth state parameters, and redirect to the content server to get an authorization code.

**Comment by shane-tomlinson** [comment]
> Linking directly to the content server and redirecting to payments with an access token w/o doing the initial OAuth setup suffers all the same security problems as the link with the access token from the settings page.

Of course, one approach would be to link to the content server, bounce to the payments server to set up the OAuth flow, then bounce back to the content server.

**Comment by lmorchard** [comment]
> A more secure and OAuth compliant implementation would be to make the payments page a full OAuth RP and finish support for prompt=none.

Yeah, this is not the ideal way to implement these links. Can we have issues #640 and #1695 done in the next week? Otherwise, I think that misses the initial MVP date.

**Comment by shane-tomlinson** [comment]
> Yeah, this is not the ideal way to implement these links. Can we have issues #640 and #1695 done in the next week? Otherwise, I think that misses the initial MVP date.

https://github.com/mozilla/fxa/pull/1150 implements a basic prompt=none, I could build on that to try to do #1695.

**Comment by clouserw** [comment]
You're right, we need URLs for the update payments page and the cancel subscription page (which I think are both the same, and both blocked by this bug) for the emails.

**Comment by chenba** [comment]
With #1078, the "Manage" button will only appear when the account has active subs.  Should this do the same check?

**Comment by lmorchard** [comment]
> With #1078, the "Manage" button will only appear when the account has active subs. Should this do the same check?

If we do the check here, I'm not sure what the UX should be - redirect back to FxA settings? Worst case is that the user would land on a subscription management page that reports no subscriptions. That would probably result from a link in an old email maybe?

**Comment by clouserw** [comment]
@juliastarkov do you have a recommendation for that case? ^

**Comment by chenba** [comment]
We don't display the "Manage" button on the Settings page if the account doesn't have any active subscriptions, but if we allow the user to get to the subscription management page without any subscriptions, then at the very least we should hide the Contact Support button.

**Comment by clouserw** [comment]
@lmorchard can you tell me what the final URL will be to link to the subscription management page directly?

**Comment by lmorchard** [comment]
> can you tell me what the final URL will be to link to the subscription management page directly?

Sure - in production it should be this: `https://accounts.firefox.com/subscriptions`

Basically just `/subscriptions` on any content-server base URL.

**Comment by juliastarkov** [comment]
@lmorchard Is it possible to just redirect a user to the fxa settings page with an error message (saying something like "Sorry, you do not have an active subscription")?
