### ISSUE TITLE
Capitalization patterns inconsistent

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#1851]
Capitalization patterns across several visual screens are inconsistent.

@jpfaller @juliastarkov please list the exact corrected copy here, along with screenshots, in order for the devs to make corrections. Les has directed us to file issues rather than to update zeplin specs as the way to bring this and any forthcoming changes to the devs' attn.

**Comment by juliastarkov** [comment]
<img width="754" alt="Screen Shot 2019-07-19 at 12 31 42 PM" src="https://user-images.githubusercontent.com/26334275/61561987-24d59600-aa25-11e9-9191-82ff8fafa25b.png">
<img width="721" alt="Screen Shot 2019-07-19 at 12 30 01 PM" src="https://user-images.githubusercontent.com/26334275/61561999-2a32e080-aa25-11e9-9968-f66ed39e0ebd.png">
<img width="690" alt="Screen Shot 2019-07-19 at 12 30 11 PM" src="https://user-images.githubusercontent.com/26334275/61562003-2bfca400-aa25-11e9-9834-5b20d72269fc.png">
<img width="263" alt="Screen Shot 2019-07-19 at 12 31 14 PM" src="https://user-images.githubusercontent.com/26334275/61562006-2dc66780-aa25-11e9-8389-3671428a612c.png">

**Comment by meandavejustice** [comment]
Snatching this quick fix while I'm waiting on a review
