### ISSUE TITLE
Add VR/TV device types

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa#1856]
See https://github.com/mozilla-mobile/fenix/issues/4037.

We need VR and TV icons for the Send Tab/Synced Tabs menus to add to the existing ones.

**Comment by vladikoff** [comment]
@eoger are you adding this into FXA or do you want someone else do add them?

**Comment by eoger** [comment]
> @eoger are you adding this into FXA or do you want someone else do add them?

I'll add them, however I need someone to create the actual icons. Is it @ryanfeeley ?

From Ryan:

> We should also update the FxA docs to list the supported types, e.g. https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/device_registration.md

**Comment by vladikoff** [comment]
@eoger @ryanfeeley 
![image](https://user-images.githubusercontent.com/128755/61555239-e8a63380-aa2c-11e9-95e4-b408e3b054a7.png)

**Comment by ryanfeeley** [comment]
Related https://github.com/FirefoxUX/photon-icons/issues/54
