### ISSUE TITLE
[fxa-js-client] convert js-client unit tests to mocha

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1857]
We should probably convert the current AMD Intern unit tests to mocha to match the rest of the repos. 

(and later on even move the js-client directly into fxa-content-server, because it's not used anywhere else)

**Comment by shane-tomlinson** [comment]
> We should probably convert the current AMD Intern unit tests to mocha to match the rest of the repos.

👍 Love it.

**Comment by shane-tomlinson** [comment]
intern-geezer is now causing security alerts because of old dependencies. :(
