### ISSUE TITLE
How to represent unconfirmed logins in the devices view?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#186]
@philbooth brought up this concern in https://github.com/mozilla/fxa/pull/181.  Scenario:

I sign in to a new Firefox instance using my existing FxA account.  I do _not_ click through the sign-in confirmation email.  So the browser says I'm logged in but unverified, and it's not able to sync.

How should such a browser show up in the devices list?  Does it need special decoration of some kind to indicate that it's not properly syncing?

We could consider hiding it but that feels like a bit of a cheat.  It is, after all, still a device that's connected to your account.  If you don't intend to confirm the signin you should disconnect it.

@davismtl @ryanfeeley thoughts?

**Comment by davismtl** [comment]
Good catch guys. So many edge cases with this device view!

I think a decoration would be good, like an exclamation. How feasible would it be to add a link that says something like a _resend email confirmation to connect device_ ? (ideally in less words)

If it's too complicated, let's just put an exclamation that when moused over says: _You have not completed sign-in on this device. Open this device to complete sign-in_.

**Comment by ryanfeeley** [comment]
@rfk @davismtl For current device we say "Current device" in green. Perhaps for unconfirmed device we should say "Unconfirmed device" in our red.

**Comment by rfk** [comment]
We can try it out; it's not obvious whether users will really understand what "unconfirmed device" means, or indeed whether they will have any mental model of the system that includes devices in this not-quite-connected-yet-despite-having-entered-your-password state.

**Comment by davismtl** [comment]
I hate to nit pick but... Red seems like something is really bad, yellow feels like it flags that the device is in a bad state or an action is required. Maybe it's just me.

Rather than "unconfirmed device", perhaps "login not finished, check your email." Maybe that's too long but if we can include a semi CTA, it might help the user. 

Alternatively, if a user mouses over "unconfirmed device", it could say, "Recognize device? If so, check your email to confirm login. If not, disconnect it."

**Comment by ryanfeeley** [comment]
@rfk I guess the question is, is it possible to be actionable from that point? Can a user click a link from the device manager and send a new link?

**Comment by rfk** [comment]
We'd have to add a new API on the backend to support it, but yes, it would be doable to re-send the link.  I think we should be wary of complexity here though, and try to do the simplest thing first and revisit it based on metrics.

**Comment by vladikoff** [comment]
from mtg: closing for now until we needed....
