### ISSUE TITLE
[support-panel] valid user without totp enabled shows as `Unable to fetch user`

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1862]
This is because `/totp/<uid>` returns 404 is no totp token is available and https://github.com/mozilla/fxa/blob/master/packages/fxa-support-panel/lib/api.ts#L95-L98 treats that as an error and bails out of any other response.

So, expect 404 where the API is returning normal response (most users do not have totp tokens).

**Comment by philbooth** [comment]
My bad @bbangert, I should have spotted both this and #1861 in code review, sorry!

**Comment by bbangert** [comment]
Closed by #1873.
