### ISSUE TITLE
[support-panel] Log errors as log level `error`

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1863]
This line https://github.com/mozilla/fxa/blob/master/packages/fxa-support-panel/lib/api.ts#L96 should really be `this.logger.erro(...)`.

Although given https://github.com/mozilla/fxa/issues/1862 this would get noisy if we're treating lack of totp tokens as fatal errors.

**Comment by bbangert** [comment]
This line was removed as we no longer error on a totp request returning a 404. However the new code throws the error in its entirety, while it should do the same as the block above.
