### ISSUE TITLE
OIDC id_tokens are not returned when using a refresh token to get access tokens

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1868]
If a refresh_token is used to request an access token, and the request contains `scope: openid`, no id_token is returned.

The OIDC spec allows [ID tokens to be returned when using refresh tokens](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens):

```
12.2.  Successful Refresh Response
Upon successful validation of the Refresh Token, the response body is the Token Response of Section 3.1.3.3 except that it might not contain an id_token.
If an ID Token is returned as a result of a token refresh request, the following requirements apply:
    its iss Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
    its sub Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
    its iat Claim MUST represent the time that the new ID Token is issued,
    its aud Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
    if the ID Token contains an auth_time Claim, its value MUST represent the time of the original authentication - not the time that the new ID token is issued,
    its azp Claim Value MUST be the same as in the ID Token issued when the original authentication occurred; if no azp Claim was present in the original ID Token, one MUST NOT be present in the new ID Token, and
    otherwise, the same rules apply as apply when issuing an ID Token at the time of the original authentication.
```

Found with https://github.com/mozilla/fxa/issues/1867 while working on https://github.com/mozilla/fxa/pull/1841

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-224)
┆Issue Number: FXA-224

**Comment by rfk** [comment]
Do we have a concrete use-case where we *want* one to be returned? The spec seems to allow us the option of returning one, or not, at our convenience.

**Comment by shane-tomlinson** [comment]
> Do we have a concrete use-case where we want one to be returned? The spec seems to allow us the option of returning one, or not, at our convenience.

I can imagine it being used for the so called "poke box", though that's not imminent.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We haven't had any requests from RPs for this.  Closing until it's needed.
