### ISSUE TITLE
Support panel `dist` directory shows up as not checked in

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1869]
After I did a full repo update and did a `git status`, I saw this:

> Untracked files:
  (use "git add <file>..." to include in what will be committed)
>
>	packages/fxa-support-panel/dist/

<img width="520" alt="Screenshot 2019-07-22 at 12 24 46" src="https://user-images.githubusercontent.com/848085/61629079-d5d56e00-ac7b-11e9-8f45-3efeb2ca7fce.png">

**Comment by bbangert** [comment]
Ah, good point, that should be ignored.
