### ISSUE TITLE
Display appropriate payment form banner based on new account activation

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1874]
Spinning this off from #1364: Product payment page displays "account activated" banner for new signup vs just their profile for existing signin. 

The two banners are implemented in the UI - we need the back-end plumbing to decide which to display based on whether the user had an existing account or arrived on the payment page immediately after email verification.

New account ([in storybook](http://localhost:6006/?path=/story/routes-product--subscribing-with-new-account)):

![Screenshot_2019-07-22 Storybook(1)](https://user-images.githubusercontent.com/21687/61646543-27bbcb00-ac5f-11e9-99b8-b86a5385af07.png)

Existing account ([in storybook](http://localhost:6006/?path=/story/routes-product--subscribing-with-existing-account)):

![Screenshot_2019-07-22 Storybook](https://user-images.githubusercontent.com/21687/61646523-15da2800-ac5f-11e9-8b0a-97bffb4c7298.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-227)
┆Issue Number: FXA-227

**Comment by lmorchard** [comment]
I think this is practically blocked by #1723

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

I am going to close this as deprecated based on on the proposed enhancements to the UX for mobile

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

We are not gonna do this
