### ISSUE TITLE
Replace all illustrations with Trailhead style illustrations

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1878]
If you see any of the old blue and white illustrations in our repo for FxA, please replace with the coloured ones. None are animated currently, but we'll do that in an upcoming sprint.
[fxa-new-illustrations.zip](https://github.com/mozilla/fxa/files/3418537/fxa-new-illustrations.zip)

**Comment by clouserw** [comment]
Thanks @ryanfeeley for this link.  The images for content server are stored at https://github.com/mozilla/fxa/tree/master/packages/fxa-content-server/app/images

> These illustrations should all have been replaced with their trailhead equivalents which is inside the trailhead folder (which should also be deleted).
