### ISSUE TITLE
KPIs: Create Queries, Charts and Dashboards in Re:Dash

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#188]
Data will be landing in Re:Dash any day now. Last step is to visualize it.

**Comment by rfk** [comment]
To be clear, this is referring to the graphs defined in https://github.com/mozilla/fxa/blob/feature-kpi-dashboard/features/proposed/FxA-70-kpi-dashboards/README.md

**Comment by rfk** [comment]
I believe @philbooth is on the case, assigning accordingly

**Comment by philbooth** [comment]
Fwiw there is a dashboard here:

https://sql.telemetry.mozilla.org/dashboard/fxa-kpis

However, I won't push this into the review column until we've got the historical data and have updated the queries to operate over 28 day periods (right now they're set at 14 days).

**Comment by philbooth** [comment]
This can go into review as soon as mozilla/fxa-activity-metrics#7 and mozilla/fxa-activity-metrics#11 are resolved.

**Comment by vladikoff** [comment]
from mtg: needs the device connection graph, password reset graph

**Comment by philbooth** [comment]
This is done now.
