### ISSUE TITLE
Sync devices does not show Firefox Preview [bz1564599]

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1889]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1564599

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

Steps to reproduce:

I created a Firefox Sync account on my laptop using Firefox 67.0.4, then installed Firefox Preview on my phone. I did not have Firefox installed on my phone before this. I connected Firefox preview to my Sync account by scanning a pairing code. History and bookmarks were properly synced.

Actual results:

Several minutes later, I got an email that I have yet to connect another device. My laptop does not show any devices I can send tabs to. https://accounts.firefox.com/settings/clients shows two devices: The one corresponding to my laptop and one called "Firefox Sync" which was last active 10 hours ago. I successfully synced several times in the last hour from my phone.

Expected results:

I expect my phone to show up correctly in the list of devices at the URL mentioned above and I expect to be able to send tabs to it from Firefox running on my laptop. I find it a little worrying that devices can sync with my account without showing up. I expect any device that has recently synced to show up.

**Comment by rfk** [comment]
This has been resolved
