### ISSUE TITLE
Firefox Accounts - add option to disconnect multiple devices/sessions at once [bz1566767]

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1891]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1566767

Created attachment 9078636
disconnectMultiple_Sessions.png

**Affected versions**
* 68.0, 69.0b5, 70.a1;

**Affected platforms**
* all;

**Steps to reproduce**
1.  Launch Firefox and sign in to sync with an existing acconut;
2. Click on the Hambourger menu -> Manage account;
3. Click on the Show button for the **Devices & apps** section.

**Enhancement suggestion**
* add an option to select multiple sessions to be disconnected at once;
* the process for just one takes a few seconds, having to do it for more becomes unpleasant;

**Actual result**
* Each connected device is listed;

**Regression range**
* not a regression;

**Additional notes**
* attached screenshot to better illustrate my point, cleared location with the pretty rectangles;
* pretty much an edge case scenario since in all fairness no regular user would have this many sessions sync'd.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-229)
┆Issue Number: FXA-229

**Comment by clouserw** [comment]
discussion happening in the bug

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closed in bugzilla
