### ISSUE TITLE
Servers intermittently failing locally

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#1895]
running `./pm2 start server.json` or `./pm2 start all` leaves some servers failing and needing to be restarted on my local machine. There was some discussion in slack about this with other devs, lets track those issues here.

**Comment by clouserw** [comment]
We talked about this in triage today.  Suggestion: delete the docker cache and try again?  There are several other people on the team running windows and not having problems, so we could ping them if that doesn't fix the problem.

Lauren also mentioned that one of the processes didn't die easily and was hanging on to a port that prevented docker from spinning up a new container.

**Comment by meandavejustice** [comment]
I haven't seen this in a long time, closing
