### ISSUE TITLE
Integrate key-rotation scrips with SOPS, for production use

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#1897]
In https://github.com/mozilla/fxa/pull/1668 we added some scripts to automate rotation of our OIDC signing keys, but they can't be used directly in production because our production secrets are managed via [SOPS](https://github.com/mozilla/sops).

Let's create a pair of additional scripts, "import-keys-from-sops" and "export-keys-to-sops", which can act as a wrapper to bridge these scripts to production. The procedure would look like:

* Run `import-keys-from-sops` to get the production values into some appropriately-secured local scratch space.
* Run whatever key-management script you need, e.g. `prepare-new-signing-key`.
* Run `export-keys-to-sops` to push the updated values back into the production keystore.

We may be able to get more clever than this over time, but the above will be a dramatic improvement over the status quo.

/cc @jrgm @jbuck

**Comment by jvehent** [comment]
Someone made a sops decoder in javascript: https://www.npmjs.com/package/sops-decoder
I have not tested or audited it, but it would allow you to decrypt files without shelling out to the sops binary.

**Comment by rfk** [comment]
Thanks! I guess the real trick then will be writing them back.

**Comment by rfk** [comment]
An initial attempt at this here: https://github.com/mozilla/fxa/pull/1962

(The shelling-out didn't seem too bad in practice...)

**Comment by vbudhram** [comment]
@rfk Is this closable?

**Comment by rfk** [comment]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1365826#c11, sounds like this scripting is working as intended, so we can close this out.

**Comment by clouserw** [comment]
Closing per above comment.  Thanks
