### ISSUE TITLE
[metrics] Send Pairing events to amplitude

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1910]
We should get pairing login events into amplitude

Currently we just have this chart https://sql.telemetry.mozilla.org/queries/63433/source#162424 

@irrationalagent , do you have any thoughts on this?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-232)
┆Issue Number: FXA-232

**Comment by clouserw** [comment]
@irrationalagent ping on this

**Comment by irrationalagent** [comment]
sorry, I'm really behind because the workweek, this is on top of my list to do ASAP

**Comment by irrationalagent** [comment]
sigh, just have not got to this. maybe we can setup a time to over what's possible and what isn't. i know there are some client-side pieces here that would be harder to pipe into amplitude.

**Comment by davismtl** [comment]
See also: https://github.com/mozilla/application-services/issues/1822

**Comment by vbudhram** [comment]
Closing as dup of https://github.com/mozilla/fxa/issues/5990
