### ISSUE TITLE
Delete account text refers to 'Screenshots'

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#1915]
1) Go here: https://accounts.firefox.com/settings/delete_account
2) The text talks about Screenshots.  We should remove that.  @johngruen do you want us to replace that text with another service name?

![image](https://user-images.githubusercontent.com/80098/61746115-d3dcdf00-ad4f-11e9-9f26-e206b5c48fcf.png)

**Comment by philbooth** [comment]
This will be fixed by #1801, right?

**Comment by LZoog** [comment]
Yeah, this will be resolved when my PR is merged. We can go ahead and close.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/13018240/61803782-6afd7180-adf8-11e9-9295-4df12d1c2190.png">

**Comment by clouserw** [comment]
Nice, thanks.
