### ISSUE TITLE
[ci]: cleanup package builds for efficient building

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#1917]
CircleCI remote container, used in `.circleci/config.yml` with the `setup_remote_docker` keyword uses a rather slow dual-core Xeon, regardless of what `resource_class` is used in the primary container. Per the [docs on building docker images](https://circleci.com/docs/2.0/building-docker-images/), the building and testing should be done in the primary container *before* `setup_remote_docker` is called.

I updated the `fxa-email-service` in #1855 to do this which dropped the build time from 27m to ~ 5m. The remainder of the packages should be updated as needed for similar build-time efficiency.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-233)
┆Issue Number: FXA-233

**Comment by dannycoates** [comment]
#785 would take care of this for us. building the image would be a final job after all tests have passed

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This was done in https://github.com/mozilla/fxa/issues/785 and adjacent issues
