### ISSUE TITLE
Add ellipses to Settings expand

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#192]
According to our style guide team, because these actions are revocable, we should append an ellipsis to each "expand" button.

![ellipsis-proposed](https://cloud.githubusercontent.com/assets/68213/18637339/1024ca86-7e5a-11e6-9c48-b5934ecd7a8f.png)

@vladikoff This will also apply to Disconnect button in devices

**Comment by vladikoff** [comment]
bug filed in wrong repo

https://github.com/mozilla/fxa-content-server/issues/4195
