### ISSUE TITLE
Eliminate fxa-oauth-server

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#1922]
The transition to merge oauth-server into auth-server will progress over 3 trains.

## Phase 1: Eliminate auth -> oauth requests

Instead of making http requests from auth to oauth import the oauth-server/lib/db directly and add required config options to the auth-server. No oauth-server code should need to be modified, deleted, or copied in this phase. This will double the number of DB connections to the Oauth database until phase 3.

## Phase 2: Add oauth routes to auth server

Duplicate the oauth routes in auth-server. Minimal if any code should be copied from oauth-server into auth-server, instead imported directly. Deployment should change config to point `oauth.accounts.firefox.com` etc to the auth-server. Oauth-server will serve remaining requests until DNS propagates.

## Phase 3: Move oauth code into auth server

Move necessary oauth code into auth-server and delete fxa-oauth-server and remove oauth-server from build and deployment. The merge is now complete.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-234)
┆Priority: Medium
┆Issue Number: FXA-234

**Comment by shane-tomlinson** [comment]
This just may be the most exciting issue I've seen filed in the past year.

**Comment by vladikoff** [comment]
I'm trying to find a branch I had where I combined the 2 processes together, but no luck yet... 

one milestone was to match up bluebird versions and I think we've done that

**Comment by davismtl** [comment]
Code maintenance. Work done in the background.

**Comment by davismtl** [comment]
Behind on phases but still possible to complete this quarter.

**Comment by davismtl** [comment]
PR in for this now.

Should go out in 147.

**Comment by davismtl** [comment]
Phase 1 pushed to tain 148.
Phase 2 PR will be done this week.

**Comment by davismtl** [comment]
Phase 1 already out.
Phase 2 is in master and will go out with train 150.

**Comment by dannycoates** [comment]
done "forever" ago
