### ISSUE TITLE
Create FxA Toolbar landing page for Firefox Monitor [bz1567405]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1932]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1567405

In Bug 1562006, we will be adding a item to the Firefox Account Toolbar menu to help users discover Firefox Monitor.  The full UI spec is in Invision [here](https://mozilla.invisionapp.com/share/V6ST9IFJMXP#/screens/372045396_Skyline_FxA_Toolbar), but the relevant parts for integrating with Monitor are:

* If the user is not signed in to Firefox, they will see a little description of the Monitor Send service and a button saying "Launch Monitor".
* If the user is signed in to Firefox, they will see a little description of the Monitor service and a button saying "Continue as user@example.com".

These buttons will open the Firefox Monitor site in a new tab, and this bug is about figuring out the details of exactly how it will be opened. We need to:

1. Agree on the precise URL that will be opened by the "Launch Send" button, including any metrics or other tracking parameters.
2. Agree on the precise URL that will be opened by the "Continue as user@example.com" button, including how to pass in the intended identity, and any metrics or other tracking parameters.
3. Optionally, design and build a customize experience to help users through this flow more smoothly.

We should probably make sure the things we do here, are consistent with the "Sign up for Firefox Monitor" branding that's being added to the protection report in Bug 1559422 and friends, so adding :mtigley for context.

**Comment by juliemccracken** [comment]
Working with Luke on the URL for this.
