### ISSUE TITLE
Cleanup the the FxA app menu [bz1568561]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1934]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1568561

From the engineering review of the FxA toolbar menu [1], it was noticed that we could do several things to help reduce some of the complexity of the menu.

- Remove the nested `toolbaritem` ie `appMen-fxa-status`
- Remove duplicate `<image id="appMenu-fxa-avatar"/>`
- Remove the duplicate `fxastatus` attribute

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-235)
┆Issue Number: FXA-235

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bugzilla
