### ISSUE TITLE
[123done] if todo list stringified > 1MB then nginx resets connection on POST

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1961]
Noticed this. If the todo list does the thing where it gives you 1000's of blank entries, when in tries to save that, the nginx in front of the 123done app rejects the POST if it is greater than 1MB (nginx config setting).

I **could** change the nginx, but really, if the todo list is that large, something in the client logic has gone very wrong.

(Note: These massive growths of todo lists have been in 123done "forever").

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-236)
┆Issue Number: FXA-236

**Comment by vladikoff** [comment]
The TODOs actually work? how did we even get to a 1000 of them , heh

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closing
