### ISSUE TITLE
Idea: Check better node/npm version checking

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1964]
#1599 is just one example of several where contributors have a difficult time running the FxA stack because of incompatible node/npm versions. Our [package.json](https://github.com/mozilla/fxa/blob/master/package.json#L41:L44) defines support as node >= 10 even though we *only* support node 10, and users of node 8 seem to either not be warned or ignore the warning. Can we do something in [postinstall.sh](https://github.com/mozilla/fxa/blob/master/_scripts/postinstall.sh) to ensure the correct node/npm versions?

**Comment by Shubhamchinda** [comment]
Hey, I'd love to work on it.

**Comment by shane-tomlinson** [comment]
@Shubhamchinda you can if you'd like!
