### ISSUE TITLE
Only return client_id in `aud` if no `resource` is specified.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1965]
JWT access tokens always send the client id of the RP in the `aud` claim, even though there is a separate `client_id` claim. This is a bit wasteful, and could possibly lead to some confusion by RPs when implementing verification logic. Instead of always sending the client_id in aud, we should only send it if [`resource`](https://github.com/mozilla/fxa/pull/1841) is not specified when requesting the access token.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-237)
┆Issue Number: FXA-237

**Comment by kunalmohan** [comment]
Hi! I would like to work on this issue. Can you guide a bit about where to start?

**Comment by LZoog** [comment]
@kunalmohan are you still interested in working on this issue? There's a PR linked (#1841) that might help give you some context!

**Comment by flozender** [comment]
@LZoog I'd like to take this up!

**Comment by clouserw** [comment]
Hi @flozender .  Thanks for volunteering for this issue.  I'm sorry, but it was mistakenly marked as a `good first bug` and it's more complex than it looks.  I removed the label.  Please check out our other good first bugs!  Thanks

**Comment by flozender** [comment]
Hi @clouserw, thanks for clearing that up. I can still give it a try it you'd like, I already claimed one `good first issue` so I'd like to do something a little more complex now, if that's ok!

**Comment by LZoog** [comment]
Hey @flozender, I sent you a message in IRC and wanted to make sure you saw it since I'm not sure if you check there frequently. Thanks!

**Comment by flozender** [comment]
Hi @LZoog by IRC could you mean the Matrix server? I don't seem to have received any message there. My ID is `@flozender:matrix.org` and I also just dropped you a message there as well.

**Comment by LZoog** [comment]
@flozender great, thanks for clarifying, I pinged ya back!
