### ISSUE TITLE
Support OIDC RP Initiated Logout

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1979]
Ref #640 and https://github.com/mozilla/fxa-content-server/issues/5916#issuecomment-369777880. 

With #1150 we are going to start supporting `prompt=none`. As noted by @rfk in [this content-server issue](https://github.com/mozilla/fxa-content-server/issues/5916#issuecomment-369777880):

> The difficulty is that there's potentially confusing behaviour around logging out of an FxA relier. If I use FxA to sign in to AMO, and then I sign out in AMO, I could reasonably expect to have to enter my password again if I want to sign back in. But we don't have a way for AMO to signal back to FxA that the user signed out.

A "RP Initiated Logout" flow is defined in the [OpenID Connect Spec](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout) that could mitigate this:

> 5.  RP-Initiated Logout
>
> An RP can notify the OP that the End-User has logged out of the site and might want to log out of the OP as well. In this case, the RP, after having logged the End-User out of the RP, redirects the End-User's User Agent to the OP's logout endpoint URL. This URL is normally obtained via the end_session_endpoint element of the OP's Discovery response or may be learned via other mechanisms.
>
> This specification also defines the following parameters that are passed as query parameters in the logout request:
>
>  *  id_token_hint
>     - RECOMMENDED. Previously issued ID Token passed to the logout endpoint as a hint about the End-User's current authenticated session with the Client. This is used as an indication of the identity of the End-User that the RP is requesting be logged out by the OP. The OP need not be listed as an audience of the ID Token when it is used as an id_token_hint value. 
>  * post_logout_redirect_uri
>     - OPTIONAL. URL to which the RP is requesting that the End-User's User Agent be redirected after a logout has been performed. The value MUST have been previously registered with the OP, either using the post_logout_redirect_uris Registration parameter or via another mechanism. If supplied, the OP SHOULD honor this request following the logout. 
>  * state
>    - OPTIONAL. Opaque value used by the RP to maintain state between the logout request and the callback to the endpoint specified by the post_logout_redirect_uri query parameter. If included in the logout request, the OP passes this value back to the RP using the state query parameter when redirecting the User Agent back to the RP. 
>
> At the logout endpoint, the OP SHOULD ask the End-User whether he wants to log out of the OP as well. If the End-User says "yes", then the OP MUST log out the End-User. 

For users that click "Yes", we would destroy their sessionToken, which would cause users to need to enter their password again. 

One possible wrinkle here is that if the sessionToken was used to sign into Sync, then the user's Sync session would be killed too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-238)
┆Issue Number: FXA-238

**Comment by shane-tomlinson** [comment]
Note, there are other OIDC logout flows mentioned in [this article](https://medium.com/@robert.broeckelmann/openid-connect-logout-eccc73df758f):

* [OpenID Connect Session Management v1.0 Spec](https://openid.net/specs/openid-connect-session-1_0.html)
* [OpenID Connect Front-Channel Logout v1.0 Spec](https://openid.net/specs/openid-connect-frontchannel-1_0.html)
* [OpenID Connect Back-Channel Logout v1.0 Spec](https://openid.net/specs/openid-connect-backchannel-1_0.html)

**Comment by rfk** [comment]
> One possible wrinkle here is that if the sessionToken was used to sign into Sync, then
> the user's Sync session would be killed too.

I wonder if instead, we could detect that the `sessionToken` is owned by the browser and:
  * Set some flag in `localStorage` to mark it as being invalidated for web logins, without destroying the token
  * Explain to the user that they're signed in to their browser and can disconnect through sync preferences (maybe even with a button to open sync preferences).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
