### ISSUE TITLE
Discuss use of color icons in the FxA toolbar menu [bz1569620]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#1981]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1569620

Hey all,

Just wanted to capture the discussion and outcomes from the product demo last week. Outstanding questions were:

* Should we use color icons for the new Firefox Account services?
* Should we have a subview panel for these services?
  * Only subview for no signed in user?

**Comment by clouserw** [comment]
Ryan is going to present a couple of options

**Comment by vbudhram** [comment]
We have the updated designs here https://mozilla.invisionapp.com/share/V6ST9IFJMXP#/screens/372045396_Skyline_FxA_Toolbar. This has been approved by UX.
