### ISSUE TITLE
Tests fail with `NoSuchDriver` very often on CircleCI

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1982]
See https://circleci.com/gh/mozilla/fxa/53040#tests/containers/1.

@6a68 has been digging into this and it appears that Firefox is crashing. I'm wondering if it's an OOM error, which we used to see on TeamCity and fixed by [clearing Firefox's memory](https://github.com/mozilla/fxa/blob/c59b7a92b6955d5ca1ffb232326b02d97404cd00/packages/fxa-content-server/tests/functional/lib/helpers.js#L2211).

**Comment by 6a68** [comment]
Thanks for filing this. It looks like the [OOM issue](https://github.com/theintern/intern/issues/967) logged an explicit out of memory error in the CI logs.

With this one, it just looks like the driver disappears in the middle of a run. I SSH'd into a Circle-CI box, and it just looks like a content process crash in the middle of running the tests, see [this gist](https://gist.github.com/6a68/eadb87dad6f9a56e0ea1b30062cc9c2c).

**Comment by clouserw** [comment]
Let's try upgrading to a newer version of Firefox

**Comment by 6a68** [comment]
Looks like Shane opened a PR that upgrades Firefox, but doesn't fix this.

I think we can use `mozprocess` to dump content process info, this might be an option. Docs: https://firefox-source-docs.mozilla.org/mozbase/mozprocess.html#collecting-process-output

Slightly easier thing I might try next: run Firefox with e10s (multiple processes) disabled, see if we get any kind of useful debugging info out of it. `mozprofile` seems like one way to proceed here: https://firefox-source-docs.mozilla.org/mozbase/mozprofile.html

**Comment by 6a68** [comment]
It looks like Les's PR #1996 fixed this 🎉
