### ISSUE TITLE
Animate Trailhead style illustrations

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1994]
Some of our original style (blue and white) illustrations are animated, but none of the new Trailhead style (multi-colored) are animated. Thrilled to learn that these skills are now a part of our team! Take a look, and contact me on how to proceed with engineering.

## Choose What to Sync
* **Original (animated):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/choose_what_to_sync_devices.svg
* **Trailhead (needs animation):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/trailhead/choose_what_to_sync_devices.svg

## Check Your Mail
* **Original (animated):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/graphic_mail.svg
* **Trailhead (needs animation):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/trailhead/graphic_mail.svg

## Connect Another Device
* **Original (animated):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/account-verified-hearts.svg
* **Trailhead (needs animation):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/trailhead/account-verified-hearts.svg
* **Trailhead (needs animation):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/trailhead/account-verified.svg

## Account Verified
* **Original (animated):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/account-verified.svg
* **Trailhead (needs animation):** https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/trailhead/account-verified-hearts.svg

**Comment by LZoog** [comment]
These honestly look like they'll be _a lot_ of fun to take on! 😄 If we don't have time to go through these in a UX/dev meeting, I'll probably need to schedule a 1:1 with you and anyone else that wants to join to go over what you're picturing, although some of them more clearly translate than others so we can cross that bridge soon. I don't think I'm going to get to these this week, so perhaps early next week!

Likely, I'll be creating Codepens for you to review. Those will let you see a preview of what the outcome looks like, and you'll see the code as well. I can point out where you can make any tweaks as far as timing and other small things go that will be easy for you to edit (or we can have a 1:1 for final tweaks when we get there). I'm excited to work on these for the team!

Also, a general accessibility comment - generally, ADA compliancy recommends that animations should be kept at or under 5 seconds, AKA no infinite loops. If we want to make the animations infinite anyway, I should at least account for [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion), which is opt-in for folks that prefer not to see animations.
