### ISSUE TITLE
Include `action` in `fxaccounts:login` LoginData webchannel message

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa#1998]
We need a reliable way to distinguish between sign-ups and logins on the client side. Currently, `fxaccounts:login` (used in Fennec) only allows a somewhat hacky approach: look for presence of `offeredSyncEngines` as an indicator of a sign-up.

We will need similar capabilities in Fenix as well.

**Comment by vladikoff** [comment]
I'll be adding more code to https://github.com/mozilla/fxa/pull/1913 as part of an OAuth WebChannel auth broker, we can add keep track of the action param there. 

For Fennec though, this seems to be rushed for Skyline. the Fennec V1 broker may be adjusted to send the `action` param, but i am not sure if it is valuable to rush that to land ASAP. Others can comment to confirm..

**Comment by rfk** [comment]
For some quick historical context, on OAuth signins we include an `action=signup|signin` param in the final OAuth redirect, to tell the relier whether this was a new or an existing account.  I did a little bit of archaeology and this is currently special-cased in the `oauth-redirect` auth broker here:

  * https://github.com/mozilla/fxa/blob/ed54f4996644262c2ba0c4c00998d54952bcf9f3/packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js#L314-L324

**Comment by grigoryk** [comment]
> For Fennec though, this seems to be rushed for Skyline. the Fennec V1 broker may be adjusted to send the action param, but i am not sure if it is valuable to rush that to land ASAP. Others can comment to confirm..

Yeah, I don't think we need to rush this for Fennec - it can use the `offeredSyncEngines` work-around for the time being. See https://bugzilla.mozilla.org/show_bug.cgi?id=1568605#c2

**Comment by clouserw** [comment]
Fenix is wanting this in Q3 so they can integrate leanplum.  /cc @liuche @vesta0

**Comment by grigoryk** [comment]
In addition to `signin` & `signup`, in Fennec (https://bugzilla.mozilla.org/show_bug.cgi?id=1568605) we're also differentiating a `reconnect` action. This happens when user is re-entering a password for an account they already have connected (due to a remote password change, or a device disconnect).

**Comment by vbudhram** [comment]
@vladikoff assigning you this!

**Comment by vladikoff** [comment]
this was done
