### ISSUE TITLE
Investigate Download by SMS Widget Moz Org team made

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#200]
The moz org team has created an sms widget for mozilla pages that allows to easily download the mobile app. 

Investigate how easy it is to integrate and if we can send dynamic SMS messages to include parameters/token/etc.

**Comment by vladikoff** [comment]
from mtg: need to talk to @jpetto about this. we might be able to use this after connecting to Sync.

cc @ryanfeeley

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/20007226/a53a76c6-a271-11e6-8bf7-af9e7f189577.png)

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/20007234/b0f711fe-a271-11e6-864b-e4dafabaffa1.png)

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-content-server/issues/4373

**Comment by vladikoff** [comment]
Closing in favour of the feature definition....
