### ISSUE TITLE
Failing functional test: 'support form without active subscriptions - go to support form with an active subscription, successfully submits the form'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2003]
See https://circleci.com/gh/mozilla/fxa/54567#tests/containers/3

> × firefox on mac 18.7.0 - support form without active subscriptions - go to support form with an active subscription, successfully submits the form (21.221s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/6dbc32d4-0687-a948-a996-1e6d99bc50f7/element / {"using":"css selector","value":"div.product-payment"}] Unable to locate element: div.product-payment
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '192.168.1.229', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Command.<anonymous>  <tests/functional/lib/helpers.js:191:22>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:75:18>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:69:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1333:8>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:1335:8>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:69:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:2358:6>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:61:10>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:69:10>
      at Test.go to support form with an active subscription, successfully submits the form [as test]  <tests/functional/support.js:51:10>
      at <src/lib/Test.ts:263:51>

This fails locally for me too.

**Comment by shane-tomlinson** [comment]
Oddly, the test passes if I run the whole suite, indicating a cross-test dependency. The test calls [subscribeToTestProduct](https://github.com/mozilla/fxa/blob/341420d1d87673a9b98ec065b64365e3826a156a/packages/fxa-content-server/tests/functional/support.js#L51) which seems to require a signed in user. IIUC, the signed in user comes from the previous test. We generally shy away from cross-test dependencies like this because it makes running the tests in isolation impossible. Should the two tests be combined into one?

**Comment by shane-tomlinson** [comment]
On Circle, a different stack trace is displayed:

> firefox on linux 4.15.0-1035-aws - support form without active subscriptions - go to support form with an active subscription, successfully submits the form (23.857s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/9bdb504b-e8d2-4ba0-b501-3e3c427e5e79/element / {"using":"css selector","value":".subscription-ready"}] Unable to locate element: .subscription-ready
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: '8b67ad60fbef', ip: '172.23.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '11.0.4'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:191:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:2375:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.go to support form with an active subscription, successfully submits the form [as test] @ tests/functional/support.js:51:10
      @ src/lib/Test.ts:263:51

**Comment by chenba** [comment]
> Should the two tests be combined into one?

I'm creating another user for that second test.  Either way is fine though.
