### ISSUE TITLE
Remove signin-from-signup when email first is fully rolled out

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#201]
So it's not the first time I've seen a sentiment like this in review comments:

> However, even that won't be correct because of the hateful,
> hateful sign-in-from-the-sign-up-view feature.

Although perhaps never expressed quite so elegantly before ;-)

This "signin-from-signup" business is an expensive feature - it adds a lot of complexity and it complicates a lot of metrics analysis.  We should take a look at the metrics and re-assure ourselves whether we're justified in keeping it and continuing to pay these costs.

**Comment by shane-tomlinson** [comment]
I have a proposal that I pitched to @ryanfeeley the other day. My feelings are not quite as strong as @philbooth's, but I think we can do a lot better. I am going to experiment tomorrow with doing like Persona (and now Google) does.

1. If a user lands at `/`, show *just an email address*
2. User types in an email, we check whether the email is registered:
  1. If email is registered, go through the signin flow.
  2. If the email is not registered, go through the signup flow.

**Comment by shane-tomlinson** [comment]
Maybe with email-first, we can kill this.

**Comment by vladikoff** [comment]
from mtg: the number of signins for signup should now go down...

**Comment by rfk** [comment]
Feels like we may be almost ready for this one... :-)

**Comment by shane-tomlinson** [comment]
This is largely a dup of https://github.com/mozilla/fxa-content-server/issues/6125, where the original signin and signup pages will be entirely removed w/ email-first. There are still some blockers, such as [this bug that prevents IAM from using email-first](https://github.com/mozilla/fxa-content-server/issues/6082).

**Comment by rfk** [comment]
Should we just close this out then?

**Comment by shane-tomlinson** [comment]
> Should we just close this out then?

Closing as dup of https://github.com/mozilla/fxa-content-server/issues/6125
