### ISSUE TITLE
Standardize on means for alerting escalation from Secops analysis pipelines to FxA

### ISSUE THREAD

**Issue by ameihm0912** [mozilla/fxa#2012]
We are hoping to come up with a standardized message format and delivery method that could be used to convey findings from the Secops analysis pipelines to the FxA application in a generalized way.

Some work has been done in this area with respect to Pub/sub integration between the pipelines and the FxA customs server. The intent here would be to expand on this, and instead of replicating customs related functionality the idea would be to define a message format that contains enough information for FxA to take action (e.g., block IP address, flag user account, etc).

Creating this as an issue here to discuss and provide updates.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-239)
┆Issue Number: FXA-239

**Comment by vbudhram** [comment]
from mtg:

Kick off meeting planned for Thursday to get clarification on details.

**Comment by ameihm0912** [comment]
Documentation and development of this alert format was completed

For details see https://github.com/mozilla-services/foxsec-pipeline/blob/master/src/main/java/com/mozilla/secops/customs/CustomsAlert.java
