### ISSUE TITLE
Can't sign up on FFTV due to focus issue

### ISSUE THREAD

**Issue by athomasmoz** [mozilla/fxa#2013]
### Steps to Reproduce

1. Open FFTV pointed at https://latest.dev.lcip.org/ (here's an APK https://drive.google.com/file/d/1IIdMoVjbNtWKmE1H76XKjRRAMfZu5EsL/view?usp=sharing )
2. Click "Receive Tabs" in toolbar or go to https://www.mozilla.org/en-CA/firefox/accounts/
3. Click sign up
4. Enter Email
5. Click Continue

### Expected Behaviour

You are taken to "Create a Firefox Account" page and "Password" field is focused

### Actual Behaviour

You are taken to "Create a Firefox Account" page, but no field is focused. 

Using the remote arrows, you can reach “terms of service”, “create account” or “mistyped email?” You can't reach the "password" field because the focus gets stuck on "how old are you"

![7-30-fxa-flow](https://user-images.githubusercontent.com/43346208/62166953-eb2f4580-b2d6-11e9-9c76-24ccd9b367a6.gif)

**Comment by clouserw** [comment]
@dannycoates this is blocking the FFTV development

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/issues/1470
