### ISSUE TITLE
Duplicate browser sessions appear in devices and apps list when site data is cleared

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#2019]
This may be a the same issue seen in https://github.com/mozilla/fxa/issues/1802, but is at least related.

When I clear site data and sign back in to my account, my new web session appears and my previous persists.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/13018240/62226738-45381580-b380-11e9-8088-8f413c03f88f.png">

This also affects the new `delete_account` view:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/13018240/62226813-63057a80-b380-11e9-904d-5a004b70b1b3.png">

**Comment by rfk** [comment]
It's semi-related; "clear site data" just discards your `sessionToken` locally but doesn't do anything to delete it from the server, so the server has no way of knowing it has become inactive.

**Comment by LZoog** [comment]
Do these inactive server-side session tokens eventually get purged?

**Comment by rfk** [comment]
Yes, I believe web sessions expire after 4 weeks.

**Comment by LZoog** [comment]
👍 So, shortening that wouldn't be the solution. What if we consolidated web session clients with the same name ("Firefox 70" and "Firefox 68" here) and displayed them with the most recent time accessed to kind of filter the list and get rid of the duplication on the client-side? Could that potentially hide anything that should be shown?

**Comment by rfk** [comment]
> Could that potentially hide anything that should be shown?

Depends what you're trying to achieve I guess. Consolidating seems reasonable for the "delete account" view in my opinion, but I'm not well-versed in what that view is trying to achieve. For example, do we really need to show Web Sessions there at all?

**Comment by LZoog** [comment]
Yeah, someone else had commented to me that it was odd, but UX did request the browser be shown. I offered hiding them as a solution for `delete_account` view yesterday but since it seemed to also affect devices & apps, I created this issue. The intent of `delete_account` is to just show an "account summary" of all active Mozilla products, including browsers, apps, and subscriptions.

cc: @johngruen @janiceahn for visibility on this discussion.

**Comment by rfk** [comment]
> UX did request the browser be shown

Having absolutely zero context on these discussions, I wonder if what they want here are browsers in the "browsers connected to sync" sense, moreso than every place where you're signed in on the web.

> all active Mozilla products, including browsers, apps, and subscriptions.

+1 to rolling it up then, I'd experiment with deduping by name and see if that feels like an OK list.  This would de-dupe web sessions, and also OAuth reliers who happen to have created duplicate tokens, down to a much more manageable list.

**Comment by janiceahn** [comment]
The intent is to show users a concise snapshot of the ecosystem as they're
using it. The browsers, if more than one, should show up as just one
instance. Thus the ## is not necessary—it can simple read "Firefox browser"
rather than Firefox 69 or 70.

**Comment by shane-tomlinson** [comment]
> +1 to rolling it up then, I'd experiment with deduping by name and see if that feels like an OK list. This would de-dupe web sessions, and also OAuth reliers who happen to have created duplicate tokens, down to a much more manageable list.

Rolling up the sessionTokens without destroying the de-duplicated sessions seems like a bad idea to me, otherwise there is a possibility that those sessionTokens could be used and the user would have no way to revoke them.

**Comment by rfk** [comment]
To clarify, I meant roll them up specifically for display in the "delete
account" view, not for the "devices and apps" list.

**Comment by vbudhram** [comment]
from mtg:

Solution from @LZoog is good to proceed with 👍🏽

**Comment by LZoog** [comment]
@rfk @johngruen I've got my client-side sort fix in, but it only feels like a partial fix for this so it feels not completely correct to mark this as resolved. Ryan, do you think we should open a separate issue for a server-side solution (and John, would you prefer that) or would that just end up being a "won't fix"?

**Comment by rfk** [comment]
> Ryan, do you think we should open a separate issue for a server-side solution

Opening a new "discuss how to improve this situation" bug sounds worthwhile, since I don't think we have a clear idea of what  server-driven solution here would look like. Having the server reliably differentiate between "the client threw away its sessionToken and is now creating a replacement" and "this is a new client connecting for the first time" seems likely to involve some sort of device fingerprinting, which we've shied away from in the past.

**Comment by LZoog** [comment]
Closing in favor of continuing this conversation in https://github.com/mozilla/fxa/issues/2256.
