### ISSUE TITLE
[FFTV] The "Show password" button cannot be accessed 

### ISSUE THREAD

**Issue by athomasmoz** [mozilla/fxa#2022]
### Summary

"Show password" option does not work on Firefox for Fire TV. Looking to FxA team to prioritize based on usage of the feature

### Steps to reproduce

1. From FFTV home screen
2. Select button in the top right corner labled "CC"
    -> Browser will navigate to sign in
3. Hit enter to begin text input
    -> Soft keyboard will slide up
4. Enter email
5. Select submit
6. Enter a password.
7. Try to select and tap on the "Show password" button.

### Expected behavior

The password is revealed.

### Actual behavior

Button cannot be used with DPAD remote

### FFTV build information

* Build from master at https://github.com/mozilla-mobile/firefox-tv
  * Use debug flavor (should be default)
  * Fxa is currently behind a feature flag. To enable:
    * Install application
    * Stop application (adb shell am force-stop org.mozilla.tv.firefox.debug)
    * Start application with Fxa flag enabled (adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B)
    * We have documentation on flagged code [here](https://github.com/mozilla-mobile/firefox-tv/wiki/QA)
* Should be run on a Fire TV device
  * The app mostly works on emulators, but some of these edge cases behave differently between Android and Amazon WebViews
* Please reach out to the FFTV team at #firefox-for-fire-tv on Slack for any help building the project

**Comment by dannycoates** [comment]
I suggest wontfix because the on-screen keyboard has it's own 'show password' and special casing the ui for tv is undesirable

**Comment by dannycoates** [comment]
even though i said wontfix, i went and fixed it anyway in #2041
