### ISSUE TITLE
[FFTV]Sign in page can't be used after visiting "Terms of Service"

### ISSUE THREAD

**Issue by athomasmoz** [mozilla/fxa#2023]
### Summary

When you return to the sign in page after visiting "Terms of Service," the DPAD focus is lost and you can't use the page. 

### Steps to reproduce

1. From FFTV home screen
2. Select button in the top right corner labled "CC"
    -> Browser will navigate to sign in
3. Access Terms of Service from FxA,
4. Scroll Up and Down a few times.
5. Tap back.
6. Tap on the up button from the remote.

### Expected behavior

The Main Menu of FxA is correctly displayed and every section from it can be accessed(Email, Continue button, Terms of Service, Privacy Notice)

### Actual behavior

There is a yellow margin displayed and nothing can be accessed in FxA main screen.

### FFTV build information

* Build from master at https://github.com/mozilla-mobile/firefox-tv
  * Use debug flavor (should be default)
  * Fxa is currently behind a feature flag. To enable:
    * Install application
    * Stop application (adb shell am force-stop org.mozilla.tv.firefox.debug)
    * Start application with Fxa flag enabled (adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B)
    * We have documentation on flagged code [here](https://github.com/mozilla-mobile/firefox-tv/wiki/QA)
* Should be run on a Fire TV device
  * The app mostly works on emulators, but some of these edge cases behave differently between Android and Amazon WebViews
* Please reach out to the FFTV team at #firefox-for-fire-tv on Slack for any help building the project

**Comment by dannycoates** [comment]
as of #2041 the TOS links aren't reachable on TV with the "form navigation" or whatever it's called without the cursor. I doubt that's what we want either. I suggest we move the TOS section below the submit buttons so it doesn't interrupt normal flow and make them reachable again if you go past the button

**Comment by dannycoates** [comment]
This is working in stage as of train 146. scheduled for prod on monday
