### ISSUE TITLE
Update product download URL for new subscriber email

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2025]
PR #1791 added [a `subscriptionDownloadUrl` config setting and `SUBSCRIPTION_DOWNLOAD_URL` env var](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/config/index.js#L293) with a temporary URL. This should be updated to point at the real download URL for our first product.

**Comment by clouserw** [comment]
This is blocked on getting a URL

**Comment by clouserw** [comment]
Assign to John to determine URL. Thanks!

**Comment by clouserw** [comment]
This is fixed

**Comment by lmorchard** [comment]
This is not done. [We configured with a placeholder URL](https://github.com/mozilla-services/cloudops-deployment/pull/3461#issuecomment-539248039), not the real download URL for the first product

**Comment by clouserw** [comment]
https://github.com/mozilla-services/cloudops-deployment/pull/3472 should fix this
