### ISSUE TITLE
Add new domains to hsts preload list

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2029]
Ref https://github.com/mozilla/fxa/pull/2015, https://github.com/mozilla/fxa/issues/741 and https://github.com/mozilla/fxa/pull/2010...

This is at least https://subscriptions.firefox.com, are there more for the support page?

cc @lmorchard and @chenba

**Comment by chenba** [comment]
@clouserw where is the Support Panel going to live?

**Comment by clouserw** [comment]
fxa-support-panel.prod.mozaws.net

@jrgm is going to check the current list to double check it.

**Comment by jrgm** [comment]
So, I checked the current prelload list, and the "add to preload list" request tool. 

accounts.firefox.com, and any subdomains of that (i.e., {api,oauth,profile}.accounts.firefox.com), are on the preload list. A new subdomain something.accounts.firefox.com would already be covereed. 

Our, stage domains are not on the preload list, which is arguably fine. 

However, the request tool no longer accepts requests for subdomains addresses. So requesting  subscriptions.firefox.com that way is not available. (We added accounts.f.c before there was a tool). So, it's either get all of `firefox.com` on the list (which is an org-level engineering project), or add things under accounts.firefox.com (or go without preloading for first visit).

**Comment by chenba** [comment]
If I'm understanding @jrgm's comment correctly, there isn't anything for us to do here.

**Comment by clouserw** [comment]
I'll CC @jvehent  for visibility and any comments.  Otherwise, it does sound like this is a wontfix.

**Comment by clouserw** [comment]
Closing as wontfix
