### ISSUE TITLE
Should subscription emails get a different SUMO link?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#2030]
In #1791 we added a new email layout for subscription stuff. It incudes a support link that points at the main FxA SUMO article:

https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account

That doesn't seem like the right page to point to in the context of subscriptions. Do we have, or should we ask for a SUMO article specifically about subscriptions?

**Comment by philbooth** [comment]
Oh wait. Was this link actually supposed to point at the support form?

<img width="503" alt="Screenshot of the support link in the subscription download email" src="https://user-images.githubusercontent.com/64367/62281430-49763880-b43d-11e9-96fa-1ec46fc88fc6.png" />

**Comment by bbangert** [comment]
@chenba We have a /support link now that we can include for this, right?

**Comment by chenba** [comment]
If they have a subscription, then CONTENT_SERVER/support should display the support form.

**Comment by bbangert** [comment]
@philbooth What needs to be done to include that link, given that its different for each environment? Do we have per-env email links?

**Comment by philbooth** [comment]
> Do we have per-env email links?

Yep, in config there's a base URI for the content server and then we hang a bunch of stuff off that:

https://github.com/mozilla/fxa/blob/d5c1402bb1f347f1127e4d09f020cfcd3fd2543a/packages/fxa-auth-server/config/index.js#L1141-L1166

**Comment by clouserw** [comment]
Unassigning John since he is out.  Phil -- can you take over?
