### ISSUE TITLE
Failing functional test: `support form with an active subscription - go to support form, submits the form`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2031]
Ref #2003 

> Screenshot saved at: https://screencap.co.uk/images/4fedd263734bf306490ffc32bfefcd520d9b28f4.png
× firefox on linux 4.15.0-1035-aws - support form with an active subscription - go to support form, submits the form (26.023s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/141996fd-a7fd-4981-bed9-19d0d442a8b3/element / {"using":"css selector","value":".subscription-ready"}] Unable to locate element: .subscription-ready
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: '7a4d15c19093', ip: '192.168.112.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '11.0.4'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:191:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:2375:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.go to support form, submits the form [as test] @ tests/functional/support.js:61:10
      @ src/lib/Test.ts:263:51

@chenba this looks like a different problem to #2003. The test redirects back to 123done and fails looking for the `subscription-ready` element.

**Comment by philbooth** [comment]
Rather than block all the open PRs on fixing this, can we just disable the test until it's fixed? Seems counter-productive to stop everything else in its tracks.
