### ISSUE TITLE
Firefox accounts zoomed way out on a pixel 3 XL

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2032]
Reported [on Twitter](https://twitter.com/rathboma/status/1156572750380720129):

> @firefox account sign in page on pixel 3a xl...seems broken :-S

<img src="https://pbs.twimg.com/media/EAz4yWxXoAEZRPk.jpg" />

Not sure if that's something *we* did or if there is a problem in Fennec.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-242)
┆Issue Number: FXA-242

**Comment by vbudhram** [comment]
from mtg:

Is this repeatable in only webview? Maybe due to iframe and not the device. 

@SorinaFlorean Do you happen to have the pixel 3 and test that it only happensn the webview?

**Comment by clouserw** [comment]
If anyone runs into this with Fenix please let us know
