### ISSUE TITLE
Consume subscription information in sumo

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/fxa#2033]
Goal

We need to be able to identify the subscription status of a user in order to provide custom functionality. SUMO already uses Firefox Accounts as the authentication/authorization mechanism so ideally we would like to get this information through the profile information of a user during login. Additionally, we will need a way to identify when there is status change. Finally, SUMO will need to redirect subscribed users to the support form URL.

Specific tasks that were identified in previous conversations
- [x] Subscription information available for SUMO through the profile scope
- [x] Support form URL
- [ ] Subscription update events

**Comment by lmorchard** [comment]
> Subscription information available for SUMO through the profile scope

What exact subscription information? The system is designed to disclose limited information to any particular Relying Party. So, we can easily indicate that a user has subscribed to *something*, but you won't get a literal list of subscribed products.

> Subscription update events

This will be handled via our event broker and webhooks. @bbangert might be able to fill in the blanks on how to hook up to those updates. (I'm personally a little fuzzy on it)

**Comment by lmorchard** [comment]
IIRC, we'd discussed in the past that SUMO wants to see that a user subscribed to *something* and not necessarily what particular thing. Some details on setting that up:

* Any user who's subscribed to a plan for any product also [gains access to a product named `defaultSubscribed`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/utils/subscriptions.js#L36)
* We associate a capability to this product in the auth-server config `SUBSCRIPTIONS_PRODUCT_CAPABILITIES` - e.g. `"defaultSubscribed": [ "isSubscriber" ]`
* We make this capability visible to the SUMO OAuth client in the auth-server config `SUBSCRIPTIONS_CLIENT_CAPABILITIES` - e.g. `"30b11ae57025e70b": [ "isSubscriber" ]`
* Then, if a user has a subscription to anything, `subscriptions: [ "isSubscriber" ]` will appear in their profile data when fetched by the SUMO OAuth client.

**Comment by bbangert** [comment]
I mentioned this to @jrgm in chat, but leaving it here too. Since SUMO needs a product name, the way to configure it is for the product capabilities to have an identical (or as desired) capability string added for each one. Then the SUMO client can be configured to get all of those capability names. This will provide it with a list of each product string a user has subscribed to.

* In `SUBSCRIPTIONS_PRODUCT_CAPABILITIES `, for product `"123DonePro"`, a capability would be added to the list of `123DonePro` or the desired string SUMO wants for the product.
* In `SUBSCRIPTIONS_CLIENT_CAPABILITIES`, for the SUMO client ID, each of the above capability strings (which happen to match the product name) would be assigned.

Does that make sense to everyone?

**Comment by lmorchard** [comment]
> Does that make sense to everyone?

Yeah, we'll need to make these changes every time there's a new product. So, say there are two products - 123 Done Pro and Firefox Fortress. We'd need config that looks something like this:

```
SUBSCRIPTIONS_PRODUCT_CAPABILITIES = {
  "prod_5678123": [ "has123DonePro" ],
  "prod_8679789": [ "hasFirefoxFortress" ],
}
SUBSCRIPTIONS_CLIENT_CAPABILITIES = {
  "30b11ae57025e70b": [ "has123DonePro", "hasFirefoxFortress" ],
}
```

Where the `prod_*` values are whatever product IDs we have in Stripe associated with those products. The `has*` strings are client capabilities invented by us - so they can be just about anything we agree upon.

**Comment by lmorchard** [comment]
But, the other thing: In the meeting we had about this, I asked for exactly what are SUMO's requirements - we could still use some info on that.

As in, does SUMO need other details about this stuff - like product name, plan name, pricing, etc? It is a just a human-readable product name? Using human readable product names as capability strings could be an awkward but sufficient hack here, but I think we need to know what SUMO needs to be sure.

**Comment by bbangert** [comment]
Yup, that's correct. I talked with @akatsoulas on Slack and we agreed the product nick name was sufficient.

**Comment by lmorchard** [comment]
Okay, then we probably need config that looks something more like this:
```
SUBSCRIPTIONS_PRODUCT_CAPABILITIES = {
  "prod_5678123": [ "123 Done Pro" ],
  "prod_8679789": [ "Firefox Fortress" ],
}
SUBSCRIPTIONS_CLIENT_CAPABILITIES = {
  "30b11ae57025e70b": [ "123 Done Pro", "Firefox Fortress" ],
}
```
We might want to consider building out something better for SUMO in the long run, though, so we're not manually duplicating these titles in server config. (i.e. if a Stripe admin renames a plan & product, that won't be reflected here)

**Comment by shane-tomlinson** [comment]
>   "prod_8679789": [ "Firefox Fortress" ],

Will these names need to be localized at some point?

**Comment by bbangert** [comment]
Nope, they're for relying party consumption only. In this case, its just for SUMO to determine the subscription copy to show, they may need to localize that copy of course at some point.

**Comment by clouserw** [comment]
jrgm already made this configuration change it looks like it's working.  @akatsoulas can you confirm this bug should be closed?

**Comment by akatsoulas** [comment]
@clouserw There is a small issue that we are we discussing with @bbangert  but I believe we can close this ticket and open a new one if there is a need it for it.

**Comment by clouserw** [comment]
ok, thank you
