### ISSUE TITLE
Run Survey with Users that Login very Frequently

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#204]
In our IP profiling analysis, we identified that a lot of users are logging in daily or weekly.

While this support that IP profiling could remove friction for users, it raises the question: "why are so many users signing in that frequently?"

A possible way to answer this question could be a survey after login. We would need to detect the last time they logged in and determine if they are eligible for the survey. If we don't wish to use 3rd party survey tools, we could do something basic using GA or telemetry events. (Hoosteeno has experience setting up surveys on mdn using GA for tracking answers)

**Comment by davismtl** [comment]
Just looking into open source tools that might be cool for this: 
http://surveyjs.org/

**Comment by vladikoff** [comment]
from mtg: @davismtl to figure out a plan for this...

**Comment by vladikoff** [comment]
from mtg: no need for now, we made some fixes to the content-server
