### ISSUE TITLE
Crypto unit test failing

### ISSUE THREAD

**Issue by farhan787** [mozilla/fxa#2061]
[should fail to unbundle with incorrect recovery key](https://github.com/mozilla/fxa/blob/712cc86c213e365439d47072bbe620a3981981c1/packages/fxa-content-server/app/tests/spec/lib/crypto/a256gcm.js#L105), assertion error - incorrect error message.

**Comment by vladikoff** [comment]
Are you running the test in Firefox ?

**Comment by farhan787** [comment]
No, I'm running them in Chrome. This test is also failing for [this PR](https://github.com/mozilla/fxa/pull/2035).

**Comment by farhan787** [comment]
It wasn't failing in Circle CI, it was specific to my machine. Closing it !

**Comment by vladikoff** [comment]
this test fails in chrome because the eeror messages are different

**Comment by farhan787** [comment]
> this test fails in chrome because the eeror messages are different

but why are they different ?

**Comment by vladikoff** [comment]
@farhan787 chrome and firefox throw a different type of error (message) on that crypto operation

**Comment by farhan787** [comment]
Ok, I'll first try to run tests in Firefox before Chrome if they fail in future. Thanks for the info @vladikoff .
