### ISSUE TITLE
`np` in fxa-shared directory does not check in version changes in files, but pushes to npm

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2066]
I've noticed this a couple of times now. 

If I run `np` in the fxa-shared directory, the new version is pushed to npm but both `package.json` and `package-lock.json` remain modified on disk. I would expect a new branch to be created with those files checked in and ready to be pushed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-245)
┆Issue Number: FXA-245

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

no longer applicable
