### ISSUE TITLE
[content server] Update Subscription Platform Terms of Service page

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2072]
**2019-09-30 EDIT**: This issue is for updating the ToS and PN footer links on the payment page.  They should link to https://www.mozilla.org/privacy/firefox-private-network and https://www.mozilla.org/about/legal/terms/firefox-private-network

**2019-09-26 EDIT**: This was a follow-up to an issue for adding a ToS page for the Subscription Platform.  However, that is no longer the case.  We just need to add a couple Firefox Private Network specific links.  Since the ToS and Privacy Notice content actually live in https://github.com/mozilla/legal-docs/, there is nothing to do in this repo.

This is a follow-up to #1986, to be completed once we have the copy in https://github.com/mozilla/legal-docs.

Specifically we need to at least
- [ ] update `fxa-content-server/server/lib/legal-templates.js` (look for a `TODO`) to search for the correct template file
- [ ] update grunt tasks to generate the template files

**Comment by clouserw** [comment]
Blocked on legal content

**Comment by clouserw** [comment]
Sorry Barry, there is a change of plans here.  We'll no longer host this ourselves and instead link out to an external URL.  I'll put the external URL here once we have it...

**Comment by clouserw** [comment]
Unassigning myself as we are no longer blocked.  URLs below

PRIVACY_POLICY_URL = "https://www.mozilla.org/privacy/firefox-private-network"
TERMS_AND_CONDITIONS_URL = "https://www.mozilla.org/about/legal/terms/firefox-private-network"

**Comment by chenba** [comment]
Just to confirm: we are keeping the newly created page, but instead of legal copy, we put two links on the page?  Also, the new page itself is not linked from anywhere (at least within the content server).

**Comment by clouserw** [comment]
We should not have the new page.  We should link directly to the URLs.

**Comment by chenba** [comment]
I just noticed that within the Terms of Service and Privacy Notice pages on the content server there are links out to terms and notices for individual products.  And the FPN ToS is already linked from https://accounts.firefox.com/legal/terms.

For this issue, I think we just need add the FPN Privacy Notice to the section in https://github.com/mozilla/legal-docs/blob/master/firefox_privacy_notice/en-US.md#firefox-accounts--join-firefox?  (In addition to reverting PR #1362 in this repo.)

@clouserw does that sound correct?

**Comment by chenba** [comment]
Filed https://github.com/mozilla/legal-docs/issues/1363.

**Comment by clouserw** [comment]
I'm not totally following the above comment.  We want the PN and ToS links at the bottom of the page to link to the URLs above.  Maybe we should update the Firefox notice also (a question for legal) but I don't think that fixes this bug

**Comment by chenba** [comment]
I think this is my source of confusion: the original issue was for a new ToS page for the Subscription Platform.  That'd make it the third link in the footer.  The two new, additional, links are _product (FPN) specific_, which doesn't seem to be consistent with the placement of rest of the product ToS and PN pages if they are linked in the footer.

>  the PN and ToS links at the bottom of the page to link to the URLs above

Unless you meant _replace_ the current footer links, which is not any less confusing because those are FPN specific pages.

If we are replacing the current footer links with external URLs then they should be https://www.mozilla.org/en-US/about/legal/terms/services/ and https://www.mozilla.org/en-US/privacy/firefox/ ?

**Comment by lmorchard** [comment]
> PRIVACY_POLICY_URL = "https://www.mozilla.org/privacy/firefox-private-network"
> TERMS_AND_CONDITIONS_URL = "https://www.mozilla.org/about/legal/terms/firefox-private-network"

Ah, yeah, this is a little confusing. Are these URLs going to be the overall generic privacy policy and TOS for **all products going forward** and not just the specific Firefox Private Network product?

**Comment by chenba** [comment]
@clouserw Actually, need another point of clarification: in today's meeting we talked about the footer links on the payment form.  The Subscriptions Management page is also on the Payments server, should the footers on that page also be updated to the FPN ones?
