### ISSUE TITLE
Cannot log in to FxA dev: 502 Bad Gateway

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa#2074]
Clicking the *Log In* button on https://addons-dev.allizom.org/en-US/firefox/ (the AMO dev site) results in a 502 Bad Gateway at https://oauth-stable.dev.lcip.org/v1/authorization

Could someone take a look? This is blocking AMO development and failing some functional tests.

**Comment by mathjazz** [comment]
Exact same problem on Pontoon dev.

**Comment by jrgm** [comment]
I fixed the problem on the stable fxadev box. Apologies for that.
