### ISSUE TITLE
[fxa-payments-server] Cache plans response

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2075]
Stripe has API limits that it'd be good to stay under. One of the calls that is likely to be hit the most is the SubHub plans API call to get a list of current plans. This call is hit for every single request to see the payment page, which could be quite a bit even if users don't proceed further.

Ideally we'd cache this for a few minutes with memcached (as we cache other things in FxA).

**Comment by clouserw** [comment]
jrgm says: Let's use redis

**Comment by philbooth** [comment]
See `packages/fxa-shared/redis` for our wrapper around Redis. In particular, the error-handling semantics of the node redis lib are pretty flaky, and our abstraction in `fxa-shared` has some battle-hardened logic to deal with that.
