### ISSUE TITLE
Investigate Discrepency in Salesforce 2nd device numbers

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#208]
Salesforce is not detecting that some users have a second device. 

Example: kcambridge+history@mozilla.com

**Comment by rfk** [comment]
I suspect we'll need to put this in a MoCo-confidential bugzilla bug so that we can safely dig into the db state for these accounts on both sides.

**Comment by bniolet1** [comment]
Should I hold off on details until we fire up a bug, then?

**Comment by rfk** [comment]
I'm going to open one right now...

**Comment by rfk** [comment]
Let's dig into this in https://bugzilla.mozilla.org/show_bug.cgi?id=1318459 and I will leave this bug open for tracking purposes in waffle.

**Comment by rfk** [comment]
It looks like this is a timing issue with the way basket record these events, so we can close out the issue on our side.

**Comment by vladikoff** [comment]
from mtg: closing, see comment above...
