### ISSUE TITLE
Store signing keys in PEM format rather than as JWKs

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2081]
Here's our current procedure for generating and using JWT signing keys:

During setup:
* Generate a new key in PEM format
* Decode it from PEM into a JWK to write to disk as part of the server config
    * Store it as a bunch of individually-encrypted JWK fields via SOPS, like the example [here](https://github.com/mozilla/fxa/pull/1962#issue-301389717)

At runtime:
* Load and check the key as a JWK from server config
* Extract the public component as a JWK so we can serve it from `/.well-known/`
* Convert the key to PEM format to pass to JWT signing library

Round-tripping the private key from PEM to JWK back to PEM seems a bit silly, and multiplies the opportunity for things to go wrong. What if instead this looked like:

During setup:
* Generate a new key in PEM format
* Store it to server config as a single encrypted field via SOPS

At runtime:
* Load the PEM from server config
* Extract the public component as a JWK so we can serve it from `/.well-known/`
* Directly use the loaded PEM-format key to pass to JWT signing library

Alternately, we could do the "extract public components" step once, during setup, and store it (unencrypted) as a separate config field.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-250)
┆Issue Number: FXA-250

**Comment by shane-tomlinson** [comment]
I am experimenting with using node-jose to handle keys everywhere, node-jose creates/loads keys as JWKs and skips the PEM format. We'd still need to load existing PEMs, though that seems tractable.
