### ISSUE TITLE
[Support Panel] Make uid and requestTicket query param validation stricter

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2082]
* Make uid and requestTicket query param validation stricter (currently validated as required strings)
  - e.g. add max and min lengths, restrict set of allowed chars
  - to prevent reflected and DOM XSS and limit data sent to the fxa-auth-db (DoS, exfil) in the event of a support person being phished

_Originally posted by @jvehent in https://github.com/mozilla/fxa/issues/741#issuecomment-518375308_

**Comment by shane-tomlinson** [comment]
UIDs are 32 character hex strings, let's go as strict as possible with that.
