### ISSUE TITLE
The firefox.com/pair page is confusing with 2FA enabled

### ISSUE THREAD

**Issue by moztcampbell** [mozilla/fxa#2089]
When adding Firefox Preview to an existing account with 2FA, the app directs users to firefox.com/pair. The mobile app asks to confirm pairing, and the browser asks for a pin code. It is unclear that this pin code is *not* from the pairing, but rather the 2FA pin which is in an entirely non-Mozilla app of their choice.

Clearer messages that this pin code is due to the user having previously set-up 2FA and that they should check their authenticator app (with some hints about what that may mean) would go a long way. I ran into this confusing because I tried to add a new device to an account I set up in the past.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-252)
┆Issue Number: FXA-252

**Comment by shane-tomlinson** [comment]
cc @vladikoff - I thought pairing was disabled if the account has 2FA enabled?

**Comment by vladikoff** [comment]
> I thought pairing was disabled if the account has 2FA enabled?

We enabled pairing for 2FA a while ago :)

**Comment by vladikoff** [comment]
this is for @ryanfeeley probably
