### ISSUE TITLE
Email confirmation email flagged as Spam in Outlook.com

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#209]
User reported on Twitter that FxA was flagged in Outlook.com as spam: https://twitter.com/ltCatscratch/status/798958950813204481

@shane-tomlinson  also confirmed the same thing with his account: https://irccloud.mozilla.com/file/goLbWeUy/Screen%20Shot%202016-11-17%20at%2017.45.48.png

I tested with my dummy Outlook account but was not flagged as spam.

Things to check:
- sender score in our email on acid account
- check Return Path's sender score: https://www.senderscore.org/

**Comment by davismtl** [comment]
Running email on acid test with Ryan

**Comment by davismtl** [comment]
Suspicion confirmed: 
![image](https://cloud.githubusercontent.com/assets/19537086/20411832/1d133870-acd8-11e6-88bb-ad31eecd4e39.png)

The test is still running but for now, nothing else has been flagged.

**Comment by davismtl** [comment]
We failed 1 out of 71 blacklists:

![image](https://cloud.githubusercontent.com/assets/19537086/20412138/be7dd804-acd9-11e6-828a-1bfbf11c0f07.png)

**Comment by rfk** [comment]
Humph, if you use a popular web search engine to search for "amazon ses sorbs" you will find several threads about their sending IPs ending up in that particular blocklist.

**Comment by davismtl** [comment]
rfk confirmed it via another tool. We seem to be on two blacklists:

![image](https://cloud.githubusercontent.com/assets/19537086/20412770/957806ce-acdd-11e6-831d-8e4b04827b93.png)

**Comment by rfk** [comment]
Ops bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1318513

**Comment by vladikoff** [comment]
cc @jrgm @jbuck see bugzilla bug above ^

**Comment by rfk** [comment]
No concrete updates here, but we can dive into it in earnest now that the new year is under way:

* When train-77 ships we should get flow events for bounces, which will let us understand get a better handle on our deliverability dynamics
* We need get cracking on https://github.com/mozilla/fxa/pull/211 and the associated auth-server issue https://github.com/mozilla/fxa-auth-server/issues/1565

If that doesn't have an impact, we'll have to look at getting standalone sending IPs and enrolling in programs such as those identified in https://bugzilla.mozilla.org/show_bug.cgi?id=1318513#c19

**Comment by davismtl** [comment]
From what I understood, we didn't need our own IP for enrolling in the program.

Seems like once we are removing bounced emails, we should sign-up to that program since we should be abiding by almost every best practice and then if we still have no luck, we can look into our own IPs.

**Comment by vladikoff** [comment]
from mtg: discussion should migrate to feature doc / feature card.

**Comment by rfk** [comment]
@rfk to migrate this to features infra rather than keeping this meta-issue alive

**Comment by vladikoff** [comment]
from mtg: some of the info from here will need to be added to the feature doc...

**Comment by vladikoff** [comment]
Tracked in fxa-56 https://github.com/mozilla/fxa/pull/211
