### ISSUE TITLE
Better integrate 2FA QR with authenticator apps

### ISSUE THREAD

**Issue by moztcampbell** [mozilla/fxa#2090]
When adding two-factor to an app like DUO, it is displayed with as the account email address, "3rd party", and no info relating it to firefox. In contrast, when I add a two-factor for github, the entry appears as "github" with an icon and the username.

1) Is it possible to improve the metadata so that users have a better experience in authentication apps?
2) Can we work with DUO and other apps to have the firefox product family logo shown?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-253)
┆Issue Number: FXA-253

**Comment by shane-tomlinson** [comment]
cc @vbudhram - any idea on how we can add images in Duo?

@moztcampbell - On Google Authenticator and Authy both show "Firefox". Does Duo do things differently?

**Comment by moztcampbell** [comment]
In that case, it may just be DUO lumping everything it doesn't recognize under the name "3RD PARTY".

**Comment by davismtl** [comment]
I have the same problem in Authy. It does not display the service name. See screenshot in: 
https://github.com/mozilla/fxa/issues/2702

**Comment by shane-tomlinson** [comment]
> I have the same problem in Authy.

Very interesting, in Authy mine says `FxA:stomlinson@mozilla.com` and at the bottom where you can select a different item it says "Firefox stomlinson.com".

The list mode does say "FxA:stomlinson@mozilla.com" too, we could probably do better there.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
