### ISSUE TITLE
Blank page when managing account from AMO-dev (400 API response)

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa#2092]
On the https://addons-dev.allizom.org/ site (the dev site for AMO), log in, edit profile, and click *Manage Firefox Accounts*. This results in a blank page. Complete STR: https://github.com/mozilla/addons-frontend/issues/8446

The FxA flow begins by loading:

```
curl 'https://stable.dev.lcip.org/settings?uid=...&email=...&entrypoint=addons' -H 'Referer: https://addons-dev.allizom.org/en-US/firefox/users/edit'
```

This response is a 200. It looks like the JS starts up but one of the XHR requests results in a 400:

```
curl 'https://stable.dev.lcip.org/auth/v1/oauth/token' -H 'authorization: Hawk id="...", ...' \
  --data '{"grant_type":"fxa-credentials","client_id":"ea3ca969f8c6bb0d","scope":"profile profile:write clients:write","ttl":300}'
```

Response body:

```
{
  "code":400,
  "errno":107,
  "error":"Bad Request",
  "message":"Invalid parameter in request body",
  "info":"https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format",
  "validation":"client_secret"
}
```

This is only happening in our dev environment so maybe it was caused by a recent change?

**Comment by kumar303** [comment]
@shane-tomlinson wrote on Slack:

> This looks like the FxA client_id is not marked as a public client.

Did the config change? I don't think we've touched the config for this.

**Comment by shane-tomlinson** [comment]
@kumar303 there is a configuration problem on stable with the FxA settings page. Trying to get it resolved now.

**Comment by jrgm** [comment]
I set publicClient: true for this client,  but it seems there's an issue in https://github.com/mozilla/fxa/issues/2094

**Comment by shane-tomlinson** [comment]
I just tried the STRs @kumar303 mentioned in the description and FxA's settings page now displays as expected. Closing this as resolved. Thanks for filing #2094 and updating the config @jrgm! And thanks @kumar303 for filing the issue and pointing out the problem.

**Comment by kumar303** [comment]
I appreciate the quick fixes -- thanks
