### ISSUE TITLE
[oauth] fix autoupdating of oauth clients to handle publicClient (and others?)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2094]
jrgm oh. I see.
stomlinson  what's going on?
jrgm  https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js#L396-L422

packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js:396-422
  updateClient: function updateClient(client) {
    if (!client.id) {
      return P.reject(new Error('Update client needs an id'));
    }
    var secret = client.hashedSecret;
 Show more
mozilla/fxa | Added by GitHub
https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js#L159-L167

packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js:159-167
const QUERY_CLIENT_UPDATE =
  'UPDATE clients SET ' +
  'name=COALESCE(?, name), imageUri=COALESCE(?, imageUri), ' +
  'hashedSecret=COALESCE(?, hashedSecret), ' +
  'hashedSecretPrevious=COALESCE(?, hashedSecretPrevious), ' +
 Show more
mozilla/fxa | Added by GitHub

“what’s a publicClient?” per that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-254)
┆Issue Number: FXA-254

**Comment by clouserw** [comment]
Summary:  There is a failure to update a particular column (and possibly other columns).  The column exists but it's not being updated on startup.   This issue is to investigate.
