### ISSUE TITLE
Zip code error jumping the gun

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#2096]
Every time I click into the zip code on the billing form and add a number it immediately gives me an error. Can we remove this and have the error only show up if the user clicks outside of the form element?

<img width="635" alt="Screen Shot 2019-08-06 at 11 21 40 AM" src="https://user-images.githubusercontent.com/26334275/62565905-a9555080-b83c-11e9-8b25-697146333c13.png">

**Comment by clouserw** [comment]
Lets do this onblur

**Comment by juliastarkov** [comment]
@meandavejustice Stephen mentioned this is still happening to him. I don't think this issue is ready to be closed.

**Comment by lmorchard** [comment]
>  Stephen mentioned this is still happening to him

Happening when & where? This is code that we just merged, so our dev site is the only place where it will appear fixed. The fix hasn't been deployed anywhere else yet

**Comment by juliastarkov** [comment]
@lmorchard The guardian sign up testing flow

**Comment by lmorchard** [comment]
I think that's using our staging server, which won't have gotten the fix for this issue from PR #2541 deployed yet.

**Comment by juliastarkov** [comment]
@lmorchard Oh ok, I wasn't aware it takes so long. Thanks for clarifying.
