### ISSUE TITLE
Name form element incorrect font

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#2097]
The font weight is different than the rest of the form elements. Please set it to the same weight. 

<img width="426" alt="Screen Shot 2019-08-06 at 11 27 00 AM" src="https://user-images.githubusercontent.com/26334275/62566163-2e406a00-b83d-11e9-9a6d-0bd97475272c.png">

**Comment by meandavejustice** [comment]
Appears to have been fixed with other form changes this sprint, closing

![firefox_7lhyWooAsi](https://user-images.githubusercontent.com/1844554/65069566-edb62f00-d958-11e9-8b84-4bb19629d9f9.png)
