### ISSUE TITLE
Put Synced Tabs sidebar toggle into toolbar

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2101]
The synced tabs sidebar should appear inside the Synced Tabs option now that it's been removed from the top level.

**CURRENT**
![Screen Shot 2019-08-06 at 3 29 24 PM](https://user-images.githubusercontent.com/68213/62578961-7b89ff00-b870-11e9-9b5e-878c9e16d255.png)

**PROPOSED**
![Screen Shot 2019-08-06 at 3 28 56 PM](https://user-images.githubusercontent.com/68213/62579375-95781180-b871-11e9-933e-931985601547.png)

**Comment by shane-tomlinson** [comment]
Are browser issues tracked here, or is this better in Bugzilla?

**Comment by vbudhram** [comment]
Yea it is better to track this in bugzilla since we need an issue to submit a patch. Recreated this issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1572212

Closing here.
