### ISSUE TITLE
Simplify stored procedures for support queries

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2104]
For the Support Panel we used existing stored procedures because they existed, but they pull a bunch of data we don't need.  Let's make some new stored procedures that only pull what is needed for the Support Panel.

Once this code is written, we will need to coordinate with @jrgm to change permissions that are set.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-255)
┆Issue Number: FXA-255

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
