### ISSUE TITLE
Clear recovery keys when resetting the account

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2106]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1569356#c30:

It looks like we delete recovery keys on the server if they are successfully consumed, but we leave them on the account if you reset your password *without* using a recovery key. That means a scenario like this is possible:

1.  Create account, with initial encryption key `k1`. Set up recovery key `rk1`.
2.  Start syncing, causing tokenserver to record `x-c-s-history=[hash(k1)]`.
3.  Reset your password without using the recovery key. Get a new encryption key `k2`.
4.  Sync again, causing tokenserver to record `x-c-s-history=[hash(k2), hash(k1)]`.
5.  Reset your password again, this time using recovery key `rk1` to revert your encryption key to its previous value `k1`.
6. Try to sync, sending `x-c-s=hash(k1)` to tokenserver.
7. Tokenserver sees that you are using an old key and refuses to process the request, on the assumption that you need to refresh your login state and get the most recent keys.  (This is a safety measure to prevent clients writing data with the wrong encryption key).

This scenario violates an assumption made by downstream consumers, that your encryption key should never revert to a previous value.  I don't think we've documented that guarantee explicitly anywhere, but we should, because it's an important part of helping consumers implement robust handling of encrypted data.

I think the right thing to do here is to `DELETE FROM recoveryKeys WHERE uid = uidArg` as part of the `resetAccount` stored procedure.

**Comment by vbudhram** [comment]
@rfk Nice find! I agree with the fix you mentioned, it is the most straightforward thing to do.
