### ISSUE TITLE
Discuss: Show password by default on mobile

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2107]
Amazon shows passwords by default when signing in on a mobile device. Does it make sense for us to do the same?

![amazon-signin-mobile](https://user-images.githubusercontent.com/848085/62613598-af613500-b901-11e9-9b52-18eff6a6a9db.png)

cc @ryanfeeley

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-256)
┆Issue Number: FXA-256

**Comment by clouserw** [comment]
@ryanfeeley for comment/decision

**Comment by ryanfeeley** [comment]
@clouserw I can't find the issue, but currently we show the password only on press. I believe that it is now safe to show this on press. I would prefer this opt-in experience, which would benefit both desktop and mobile users.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We'll keep this the way it is for now
