### ISSUE TITLE
[meta][skyline] Update FxA toolbar menu for Skyline - QA bug tracking [bz1572097]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2108]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1572097

This is a meta bug used by QA to keep track of all the new bugs found for the FxA Toolbar Menu Changes feature during testing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-257)
┆Issue Number: FXA-257

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bugzilla
