### ISSUE TITLE
Return service name to email first forms

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2111]
In some contexts we do not show the subheading **To continue to {Relying Service}** on the email first form, but we should show them consistently everywhere.

Currently looks like:
![Screen Shot 2019-07-22 at 4 43 06 PM](https://user-images.githubusercontent.com/68213/62653816-6377b580-b92c-11e9-984b-75dbd7669849.png)

**Comment by rfk** [comment]
+:100:

It's not just the email-first forms, we have a variety of flows that hide the service name.  For example try opening [this link](https://monitor.firefox.com/oauth/init?style=trailhead) in a new tab (without peeking at the URL!) and see if you can tell where you'll end up after signing in. There is no UI indication whatsoever of where it's going to take you.

If we allowed third-party RPs this would be a security issue; see e.g. [Bug 1320213](https://bugzilla.mozilla.org/show_bug.cgi?id=1320213) for a similar issue that was filed during an [external security audit of FxA](https://blog.mozilla.org/security/2017/07/18/web-service-audits-firefox-accounts/). We should set a good example here and always give users a clear indication of what they're about to do with their account.

**Comment by shane-tomlinson** [comment]
Was this taken out as part of Trailhead?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - the service name is only hidden if `style=trailhead` query parameter is explicitly added, which luckily is only Sync from about:welcome.

## Default Monitor experience
<img width="776" alt="Screenshot 2019-08-08 at 10 18 43" src="https://user-images.githubusercontent.com/848085/62691268-4099df80-b9c6-11e9-9fa7-25694cb9ca38.png">

## Default Sync experience
<img width="621" alt="Screenshot 2019-08-08 at 10 19 14" src="https://user-images.githubusercontent.com/848085/62691288-498ab100-b9c6-11e9-91e9-b410a9d95fff.png">

## about:welcome Sync experience (style=trailhead)
<img width="572" alt="Screenshot 2019-08-08 at 10 20 04" src="https://user-images.githubusercontent.com/848085/62691302-4e4f6500-b9c6-11e9-8dcf-b8a11f8b50d6.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson As we'll be removing style=trailhead, we're getting a list together about what changes are needed.

Broadly:
1. Return service to every possible screen
2. Remove "Get more from these features" from that page that asks the user to enter or create a password
3. Keep "Get more from these features" on the email first page
4. Create new copy for the password reset experience that indicates service (not written yet)

**Comment by dannycoates** [comment]
@ryanfeeley what's the timing supposed to be for doing these? Are we targeting a date or can they land on whatever train?

**Comment by davismtl** [comment]
this was done in train 146
