### ISSUE TITLE
Including :service-fxa Android dependency increases APK size by ~15.3 MB

### ISSUE THREAD

**Issue by mcomella** [mozilla/fxa#2115]
The FFTV APK size increased from 5.43 MB to 21.1 MB between our v4.0 app release and v4.1-LAT1 beta release. We investigated [in this issue](https://github.com/mozilla-mobile/firefox-tv/issues/2647) and discovered there are four copies of `lib/*/libfxaclient_ffi.so` included across four architectures, each one ~3.5+ MB in size:

![Screen Shot 2019-08-07 at 17 09 11](https://user-images.githubusercontent.com/759372/62666062-b0f92000-b936-11e9-971d-5f80285bb7c2.png)

Thus, we suspect this to be the root cause of size increase. This is a non-trivial increase in our app size that we'd prefer to avoid. Thoughts:
- afaik, Fire TV only works on one architecture: can we ship only one copy of this library?
- ~3.5 MB seems like a lot for the FxA libraries: why is it so large? Is there any way to trim that down?

Note: I haven't created a minimal test case to verify that just adding the `:service-fxa` dependency increases our app size to that magnitude – I'm inferring from what we discovered.

**Comment by rfk** [comment]
Thanks @mcomella, I'm going to re-open this over in https://github.com/mozilla/application-services/issues/1559 since this is more about the client libs than the FxA service.
