### ISSUE TITLE
[customs] Handle new action events from Dataflow fraud detection pipeline

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#2116]
Related to #2012.

Secops are going to start publishing actionable events for the customs server to consume, e.g. to block a given IP address. We should handle them but we should also put that handling behind config on a per-event basis, so we can turn things off if there are any teething problems.

**Comment by shane-tomlinson** [comment]
@philbooth the events are from the DataFlow fraud detection pipeline. We are already consuming most of the events and checking whether we expect them or not, but we do not act on them, i.e., we don't add any additional blocks when DataFlow says we should.

The code is here: https://github.com/mozilla/fxa/blob/0ec1e3fc2e53092bb00a4a82da9239c9628376fa/packages/fxa-customs-server/lib/dataflow.js#L54

Where we [check for expected blocks](https://github.com/mozilla/fxa/blob/0ec1e3fc2e53092bb00a4a82da9239c9628376fa/packages/fxa-customs-server/lib/dataflow.js#L118), we should instead be adding blocks.

**Comment by shane-tomlinson** [comment]
cc @ameihm0912

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-customs-server/issues/311 and https://github.com/mozilla/fxa-customs-server/pull/317
