### ISSUE TITLE
[payments-server] Alert Bar Spans the Entire Width of the Page and Not Dismissable

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2119]
![image](https://user-images.githubusercontent.com/198055/62719465-af2e6b80-b9cd-11e9-9e18-f16fec7c0220.png)

**Comment by chenba** [comment]
It should look like this: https://app.zeplin.io/project/5d13e5c151e1e056b3f68fa7/screen/5cf176f616309e0a5cb7406f

**Comment by chenba** [comment]
cc @juliastarkov @janiceahn

**Comment by juliastarkov** [comment]
Also, please set the font to the weight specified in Zeplin (not bold).

**Comment by chenba** [comment]
The alert bar has changed.  This issue is outdated now.  Closing.
