### ISSUE TITLE
[Train 143]The 'Logins and Passwords' from new account flow synchronization is not splitted correctly

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#2130]
Environment:
Builds: Stage [Train 143];
Devices: Android, iOS;

## Steps to reproduce:

1. Start an account creation flow using valid credentials;
2. Tap on 'Create account' button;
3. Observ the 'Choose what to synchronize' list;

## Expected results:
The list doesn't have any visual defect;

## Actual results:
The 'Logins and Password' option is not splitted correctly.

## Notes:
- Not reproducible on Windows;
- Not reproducible on production;
- photo: 
![Screenshot_20190809-102510](https://user-images.githubusercontent.com/40264165/62762789-9d62cc00-ba92-11e9-86c5-3ef9736b7d43.png)

**Comment by clouserw** [comment]
@ryanfeeley what should we do here?  An ellipsis seems....squished.

**Comment by ryanfeeley** [comment]
@clouserw Looks like a regression from: https://github.com/mozilla/fxa/issues/1201#issuecomment-499593007

**Comment by ryanfeeley** [comment]
Specifically: 
![image](https://user-images.githubusercontent.com/68213/62885970-233b7d00-bd08-11e9-9e9e-4d17f98686d1.png)

**Comment by ebalazs-sv** [comment]
Hi! This is reproducible in production, RC 68.0.2 build 1 with Xiaomi MiPad 2 (Android 5.1; tablet) - x86, in landscape mode.

**Comment by shane-tomlinson** [comment]
Hi @ebalazs-sv - this was only reported last week on stage which shipped to prod yesterday, it's likely going to be 2 more weeks until a fix is shipped.

**Comment by ebalazs-sv** [comment]
Hi @shane-tomlinson - Got it, thanks for the reply.
