### ISSUE TITLE
(fxa-payments-server): Consider using CSS modules

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#2139]
CSS modules keep styles locally scoped per-component. This would allow for greater scaling of our CSS while avoiding conventions like BEM, would help keep CSS selector declarations more organized and clear as it would be per-component, and since we can still use SCSS, we wouldn't lose any power of preprocessors. They're also fully supported by `create-react-app` so the configuration would be easy to setup.

It'd look something like this:
```
// index.module.scss
.some-class {
  background: hotpink;
}
```

```
// index.tsx
import styles from './index.module.scss';
...
<div className={styles[some-class]} />
...
```

**Comment by lmorchard** [comment]
FWIW, since most of the CSS for payments-server is inherited from content-server, I think we'd have to consider CSS modules over there too. 

Personally, I'm not a big fan of CSS scoped per component. But, I'd defer to whoever has more time to work on the frontend :)

**Comment by johngruen** [comment]
I am too, though as Les said that's not the model being used on the content server...i think there's a fair amount of tight-ish coupling of classes to test logic over there, so refactoring of that code would be non-trivial...

out of curiosity, I've never really understood how css in js deals with responsive layouts, do you know of any good docs about this?

**Comment by LZoog** [comment]
Definitely down for discussion on this, as I'm not _completely_ sold we need it on this project - it may actually not be worth it, in my opinion, if the scope of what our CSS covers remains relatively non-extensive. The React way is very component-based and each component already has its own style sheet, but... while CSS modules have additional benefits, it could also possibly cause some work-arounds (or extra mixins) for static views (like the 404 page getting some classes). Do we have foresight on how much more front-end work this project will have?

I do think we could benefit from some CSS convention love, though. I wasn't sure what patterns we were using when I first started. If the scope of CSS work is not going to grow a whole lot, I'd be satisfied with some refactor without scoped modules, but also open it up to others working on the front-end. :)

@johngruen this is actually different than CSS-in-JS, as we would still keep all styles and media queries in an SCSS file. FWIW, personally I'm not a fan of CSS-in-JS because I find the syntax clunky, reuse harder, and the lost power of SCSS (or workarounds to get things working) doesn't make me happy, but I have also only used it on one small project to try it out. I used Fela, which look like this for responsiveness: https://fela.js.org/docs/recipes/ResponsiveComponents.html

**Comment by LZoog** [comment]
I'm leaning towards closing this for a couple of reasons:

1. Some folks have expressed they don't like component-scoped CSS
2. CSS module makes reuse more difficult, and as far as styling goes, FxA is a relatively small project

As stated in my previous comment, I do believe we should have better CSS naming conventions, and better reuse (mixins, variables). Since we're going to redesign the settings page, I think  improving conventions would be great to couple with that work.

**Comment by LZoog** [comment]
Closing this for issue for reasons listed above, if someone in the future would like to push for CSS modules feel free to reopen for discussion.
