### ISSUE TITLE
[fxa-event-broker] Notify SPs whenever an accessToken is destroyed.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2140]
The fxa-event-broker only notifies service providers [whenever a user signs in or updates their subscriptions](https://github.com/mozilla/fxa/blob/0ec1e3fc2e53092bb00a4a82da9239c9628376fa/packages/fxa-event-broker/lib/notificationProcessor.ts#L16:L17).

Service providers that make use of relatively long lived JWT access tokens that they verify locally do not find out that a user has revoked accessToken since they do not call either the OAuth server's /introspect or /verify endpoints. To help SPs immediately revoke service for accessTokens the user revokes, we should notify the appropriate SP whenever an accessToken is destroyed. 

Note, we could do the same with refreshTokens, but with refresh tokens the SP and RP could be distinct and only the RP should have access to the refreshTokens.

Ref https://github.com/mozilla/secure-proxy/issues/356 for a concrete use case.
Ref https://github.com/mozilla/fxa/issues/1249 to destroy accessTokens associated with a refreshToken.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-263)
┆Issue Number: FXA-263

**Comment by clouserw** [comment]
Scenario: A person clicks 'disconnect' from the devices page on FxA but it takes 6 hours for Secure Proxy to disconnect.  This would make it [more] immediate.

**Comment by rfk** [comment]
(I edited the title to change "RP" to "SP" for consistency with the issue body)

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Moving this aside for now as there's no SQS events to drive this at the moment. Will mark this as a part of a proper Epic to support this.
