### ISSUE TITLE
[support-panel] needs x-frame-options: allow-from <some config> to work within zd domain

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2142]
So, I updated the stage support panel to latest, which pulled in HSTS, a couple of logic fixes handling db response, and stronger query validation.

Now when Marty loads the panel, it's blank. Console says: `The resource at "<URL>" was blocked because content blocking is enabled`.

In adding HSTS, a set of default security related headers was also enabled, and I think `x-frame-options` needs to do an `allow-from` for a configurable domain name (or names).

**Comment by jrgm** [comment]
Or, maybe it's more correct to disable the `x-frame-options`, and eventually use CSP to control framing.

**Comment by jrgm** [comment]
So the typescript hapi types do not allow setting `security.xframe` to `false` to disable XFO, which is arguably a bug in the types (since the hapijs security code is set up to disable this with `false`. Anyways... I deployed a change to stage that reverts the change that added the XFO, so HSTS is back to off on stage as well, but this unbreaks the use of this panel in stage pending figuring out how to proceed with this issue.

**Comment by chenba** [comment]
I'll add a config for a `frame-ancestors` CSP directive.  That _should_ be enough.  (https://www.w3.org/TR/CSP2/#frame-ancestors-and-frame-options)  So we'll see.
