### ISSUE TITLE
The "primary account email required for sign-in" error is hard to correct in the email-first flow

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2147]
STR:

* Create a Firefox account, then change its primary email address
* Go to https://accounts.firefox.com/signin?action=email and enter the *old* primary email address
* Enter account password when prompted

You end up with a screen like this:

![Capture](https://user-images.githubusercontent.com/34695/62844536-5af4f580-bd05-11e9-8ec8-72b042312f39.PNG)

In order to correct the error, the user has to select "use a different account" in order to change the email address, but I don't think it's very obvious to the user that this is what they need to do (it's the same account, just a different email address).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-265)
┆Issue Number: FXA-265

**Comment by ryanfeeley** [comment]
@rfk  In this instance I suppose it makes more sense for the error to appear on top of the email first screen (bouncing you out of this screen).

**Comment by shane-tomlinson** [comment]
> @rfk In this instance I suppose it makes more sense for the error to appear on top of the email first screen (bouncing you out of this screen).

If the RP specifies the email via the `email` query parameter, then the first opportunity to show it is here. As an "easy" fix, could the wording be made more clear? Something like "Primary email address for account required" Reading "Primary account email" makes me wonder "is it the email for the primary account?"

**Comment by ryanfeeley** [comment]
OK, let's not fuss too much about this as very few will see it. Copy changes are fine.

**Current**
* Primary account email required for sign-in
* Use a different account

**Proposed**
* Please sign in using your account’s primary email address
* Use a different email (safe for all contexts I think)

**Comment by poo0054** [comment]
I am currently facing this situation. What should I do? I can't remember what my main account is.
