### ISSUE TITLE
Create New Email Variations

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#215]
Marketing is relaunching email reminders to help users complete their setup of FxA and Sync across 2 devices.

The current email they will be using looks something like this: 
https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#heading=h.i9is5gq8ixl4

We would however like to test more email designs and copy. They will likely propose some but I think we should propose some ideas too since we are more familiar with the flow. There is no limit on the amount of templates we can test via SalesForce.

**Comment by davismtl** [comment]
I'm thinking that the image used in this screen is probably worth testing out too. It has worked wonders after email confirmation.

![screen shot 2017-01-30 at 3 25 34 pm](https://cloud.githubusercontent.com/assets/19537086/22446263/94d01484-e700-11e6-9c21-77636eea421d.png)

**Comment by shane-tomlinson** [comment]
cc @ryanfeeley

**Comment by vladikoff** [comment]
@ryanfeeley do we still need this or close it?

**Comment by vbudhram** [comment]
from mtg: closing for now
