### ISSUE TITLE
Add SVG icon for secure proxy

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2151]
Currently, Firefox Private Network is missing the icon in the device manager.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/68213/62868633-1442d380-bce4-11e9-89af-1a86ad20edf4.png">

A 32 × 32 SVG icon is attached.
[vpn.svg.zip](https://github.com/mozilla/fxa/files/3492667/vpn.svg.zip)

**Comment by shane-tomlinson** [comment]
fixed by #2157, closing.
