### ISSUE TITLE
Compare post-verification email success

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2152]
We currently send two emails after the users verify their email. One is from accounts@firefox.com and the other is from Mozilla@e.mozilla.org.

<img width="300" alt="Screen Shot 2019-08-12 at 9 36 28 AM" src="https://user-images.githubusercontent.com/68213/62869008-f32eb280-bce4-11e9-93c5-aacd4508005c.png"><img width="300" alt="Screen Shot 2019-08-12 at 9 36 15 AM" src="https://user-images.githubusercontent.com/68213/62869010-f3c74900-bce4-11e9-9bd7-bda61a1f0135.png">

The primary call-to-action in the accounts email goes to:
https://accounts.firefox.com/connect_another_device/?utm_medium=email&utm_campaign=fx-account-verified&utm_content=fx-connect-device

And the primary call-to-action in the mozilla.org email goes to:
https://accounts.firefox.com/sms?service=sync?utm_source=email&utm_medium=email&utm_campaign=desktop&entrypoint=fxaemail&form_type=email&utm_content=wlc_1_en_t2

Which one results in greater engagement? We should probably choose one instead of sending two.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-267)
┆Issue Number: FXA-267

**Comment by ryanfeeley** [comment]
Rough chart, does this look right @irrationalagent? https://analytics.amplitude.com/mozilla-corp/chart/tl7cc76

**Comment by irrationalagent** [comment]
@ryanfeeley do you know the email template of the second email? We need to divide the numbers in your chart by the number of emails sent to get a sense of the engagement rate.

**Comment by ryanfeeley** [comment]
@irrationalagent I don't, and am not sure it gets sent as often. See Lauren Niolet for details as her team sends the second mail.

**Comment by shane-tomlinson** [comment]
> And the primary call-to-action in the mozilla.org email goes to:
https://accounts.firefox.com/sms?service=sync?utm_source=email&utm_medium=email&utm_campaign=desktop&entrypoint=fxaemail&form_type=email&utm_content=wlc_1_en_t2

Do they only send those to people in the US? If they send that email to everyone with English as a primary language, they are going to run into problems in unsupported countries, e.g., in South Africa. None of those people are going to be able to send an sms.

Users should instead be sent to /connect_another_device, we'll decide which form to send users to based on their location + their browser.

cc @laurenniolet

**Comment by LaurenNiolet** [comment]
Hi friends. I have updated the CTA for the marketing email to: 

https://accounts.firefox.com/connect_another_device/?utm_medium=email&utm_campaign=fx-account-verified&utm_content=fx-connect-device&utm_source=email&utm_medium=email&utm_campaign=desktop&entrypoint=fxaemail&form_type=email&utm_content=wlc_1_en_t2

The email in question is on its way out. It goes to accounts that are not created through a Trailhead form. It sends at least 80 minutes after the account was created and only gets sent to users who have not yet connected a second device (the 80+ minute wait is to ensure we don't send it to someone who already did the thing).

The email sent 197k times in the last 30 days (give or take). The email in the last 30 days had a 35% open rate, which is right at or above our benchmarks for a first email and it had a 9% click rate, higher than most anything else we send. (8.2% net ctr on CTA; 0.5% net CTR on opt out link)

Few more details in the PDF. Happy to provide whatever else is helpful. 
[Overview.pdf](https://github.com/mozilla/fxa/files/3507000/Overview.pdf)

**Comment by ryanfeeley** [comment]
@LaurenNiolet I do think this is an email better sent by marketing, as it's the beginning of a journey more than a purely transactional email. Maybe when @irrationalagent has time he can tell which of the two results in more devices being connected.

**Comment by davismtl** [comment]
@ryanfeeley should we close this? Lauren made changes to the destination email and we're making changes to our email template to focus on secondary email and recovery keys instead.

https://docs.google.com/document/d/1Wz0itS76pNS24zeNS5MEqqjQdwxHuNyfq3PTj8C688s/edit#
