### ISSUE TITLE
Provide a way to bypass verification and sign-in confirmation for tests

### ISSUE THREAD

**Issue by kitcambridge** [mozilla/fxa#216]
Hi!

For context, Sync has a test suite called TPS for integration tests. It uses the production Sync and FxA servers, though I think we can also point it to stage, and runs scenarios with multiple Firefox profiles.

Because it uses a real Firefox Account, it's also subject to verification when the account is first created, and sign-in confirmation for the first test run. I usually use a restmail address for this. Opening up restmail.net, finding the email with the `X-Link` header, and opening that link isn't too tedious, but it is a stumbling block, especially for running the tests frequently. ("Why is this stalled? Oh, right, I guess I need to check the mailbox").

It also adds several extra steps to creating a fresh account, which some of the tests assume. Otherwise, they might download stale data from the Sync server, reconcile, and become confused when they see extra records from previous runs.

I'm wondering if we can provide a set of test accounts that can bypass sign-in confirmation...or, better yet, a way to create accounts exempt from both verification and confirmation. (Maybe all restmail accounts?) If that's not possible, we can change the tests to hit restmail and extract the link. Tricky and specific to restmail, but an alternative to consider.

Thanks!

+@mhammond @thomcc

**Comment by thomcc** [comment]
This used to work for restmail accounts until some time in the past two months, AFAICT.

**Comment by rfk** [comment]
I know we use some rules like this for our own tests, both for deterministically skipping sign-in confirmation and for deterministically ensuring that it will be triggered.  @shane-tomlinson is probably the right person to comment on the details there and whether we can tweak the rules to accommodate your needs here as well.

**Comment by rfk** [comment]
> exempt from both verification

FWIW I recall the stage servers accepting a `{ preVerified: true }` request body parameter in order to bypass the verification email, if you're running against stage you might be able to use that.

**Comment by shane-tomlinson** [comment]
I'm deferring to @jrgm on how he tests against prod.

> FWIW I recall the stage servers accepting a { preVerified: true } request body parameter in order to bypass the verification email

Since stage and prod are identical images with different URLs, this behavior should be disabled on stage.

**Comment by thomcc** [comment]
FWIW while we wouldn't test against prod frequently, last I checked the plan was (once we get TPS running automatically...) to run a single fairly small TPS test against prod daily, and the full suite against stage daily.

So ideally this would work against either (and it used to, as well).

**Comment by rfk** [comment]
>  we can change the tests to hit restmail and extract the link.
> Tricky and specific to restmail, but an alternative to consider.

I'd like to explore this option a little more.  Can we update restmail to make this kind of automation easier?  That's more-or-less why restmail exists, and automating it through restmail would:

* Avoid depending on configuration differences between stage and production
* Avoid us having to punch careful restmail-shaped holes in our security boundary, with the attendant risk of getting it wrong.

For example, in the PyFxA tests we use this little helper class for completing email loops with restmail:

  https://github.com/mozilla/PyFxA/blob/master/fxa/tests/utils.py#L45

**Comment by thomcc** [comment]
That could be doable but seems tricky. I'll look into it tomorrow though, might not be that bad in practice.

**Comment by mhammond** [comment]
Given TPS is already broken and isn't being run automatically anyway, I support the efforts to unbreak it, but don't think it should be a higher priority than the repair work - if it turns out some of that work (or other stuff) breaks TPS even more, we can fix them at a later time (ISTM most such breakage is far more likely to be around the test-runner part of TPS than real breakage in sync)

**Comment by shane-tomlinson** [comment]
>>  we can change the tests to hit restmail and extract the link.
>> Tricky and specific to restmail, but an alternative to consider.
>
> I'd like to explore this option a little more. Can we update restmail to make this kind of automation easier? 

I'm not convinced restmail needs to be updated, the verification links are already [available in the email headers to facilitate testing](https://github.com/mozilla/fxa-auth-mailer/blob/master/mailer.js#L289). We use this extensively on the content server for our functional tests. Or, if they'd rather call the auth-server directly with the verification code, they [can get that from a header too](https://github.com/mozilla/fxa-auth-mailer/blob/master/mailer.js#L292).

**Comment by thomcc** [comment]
I don't expect we'd have to change restmail, just TPS.

It also might not be *that* involved of a change. I mean, AIUI we'd just need create an account at the start of the run, pass the credentials in, and check for confirmation at the start of each phase where it's the first phase for the profile, which is something that IIRC should be easy to find out from TPS.

**Comment by vladikoff** [comment]
from meeting: 

DevOps are suggesting to use the stable ( https://stable.dev.lcip.org/ ) environment. If there is anything missing or not configured properly on `stable` we can fix that up. We probably won't tweak prod to support this... 

However we can discuss this further and maybe also tweak `stable` to allow us to skip confirmation.

cc @jrgm

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this?

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this? (we are using passive aggressive triage techniques now)

**Comment by rfk** [comment]
@thomcc @mhammond @kitcambridge - IIUC from the related email thread, the resolution here was to try using restmail to complete the confirmation loop, and revisit things if that proves unwieldy.  I'm going to close out the bug here but please don't hesitate to re-open and/or continue discussion on the list if that's not an acceptable solution.

**Comment by kitcambridge** [comment]
Sounds good, thanks! It is a little unfortunate that we'll need to hardcode restmail handling into the TPS harness, but, since we're really the only consumer that needs this now, it's not fair to foist that maintenance burden on you. Let's see how this goes, and we can revisit as needed.
