### ISSUE TITLE
1.5 Teach users to use Send Tab after login when they are connected to 2 or more devices.

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2165]
This is in regards to eliminating dead-ends in our flows. 

Feature doc: https://docs.google.com/document/d/1ppfBNDpALb1ndOJvIlOzakToBAmYuHzN4abxzbCdtCE/edit#

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-269)
┆Issue Number: FXA-269

**Comment by davismtl** [comment]
To measure the success of this work, we need to understand why we stopped tracking Send Tab events back in May.

https://analytics.amplitude.com/mozilla-corp/chart/new/pjsr04g

**Comment by davismtl** [comment]
CC @dianehuang11

**Comment by dianehuang11** [comment]
Feature Doc: https://docs.google.com/document/d/1ppfBNDpALb1ndOJvIlOzakToBAmYuHzN4abxzbCdtCE/edit#

Design is in progress. Variation A drafts are included in doc.

**Comment by ryanfeeley** [comment]
Nearing completion: https://mozilla.invisionapp.com/share/GQT88RLWXAD#/376556183_Send_Tab_Wow_Moment

**Comment by davismtl** [comment]
- animations are done
- creatives are good to go

To do:
- @davismtl to update feature doc
- we still have a bug open for fixing the send tab metric https://github.com/mozilla/fxa/issues/2167

Moving to ready for engineering.

**Comment by davismtl** [comment]
@chelsea-lewis can you help @6a68 setup a kick-off for this?

**Comment by chelsea-lewis** [comment]
> @chelsea-lewis can you help @6a68 setup a kick-off for this?
> 
> Jennifer Davidson would like to see if we can user test this once it's in staging.

The meeting is set on Wednesday 2 October at 1pm PT.

**Comment by 6a68** [comment]
Please note, per recent comments in #2167, that the new send tab implementation in Firefox doesn't submit telemetry, meaning, a fix will have to ride the trains.

We may not have trend data to compare this feature against, so it might be worth thinking through an A/B test to evaluate what impact this feature will have vs. the current 'Connect a Device' screen.

**Comment by davismtl** [comment]
According to @ryanfeeley this may start soon but we may also have new illustrations to work with.

**Comment by davismtl** [comment]
From mtg:
- This will likely go out in train-153 which is in mid-January.

**Comment by ryanfeeley** [comment]
@davismtl I wouldn't hold your breath for the new illustrations. We should ship this feature as soon as it is measurable.

**Comment by davismtl** [comment]
We have decided to punt this to the new year. It is unclear if this is will be in Q1 OKRs but it would be a shame if it wasn't since we've invested so much time already.

**Comment by davismtl** [comment]
@davismtl to see if where this fits in Q1. It is not currently in our Q1 OKR draft.

**Comment by clouserw** [comment]
epics are tracked in jira
