### ISSUE TITLE
Support the Firefox Notes encryption use case.

### ISSUE THREAD

**Issue by Natim** [mozilla/fxa#217]
We are planning to do a Test Pilot experiment with the [Hoverpad project](https://github.com/mozilla-services/hoverpad)

Hoverpad is an extension that display a text field that can contain sensible data.
The goal is to have the content of this pad to be available on multiple places (desktop app/web app/mobile app/webextensions).

The discussion about what exactly is going on there: https://github.com/mozilla-services/hoverpad/issues/15

In order to implement that we would need to be able to grab a key linked to a FxA account.
A bit like kB is used for Firefox Sync and for the chrome.storage.sync web-extension API.

After discussing a bit about that with @rfk and @shane-tomlinson it seems that a similar feature was [present and used by Firefox Hello](https://github.com/mozilla/fxa-content-server/pull/4295) and has been removed lately.

However the suggestion is not to put it back like it was but more to implement a way for FxA bearer token to get keys related to their scopes.

We could have a service responsible for grabbing keys linked to a Firefox Account.

For instance a Bearer token with the following scopes : `['profile', 'sync[addons]']`
 
Could return the following keys:

```
{
  "keys": {
    "profile": {
      "kA": "IDYgJ594ilFriYYBRswskw",
      "kB": "M2SAKF1y1oLePBovEbI3WA"
    },
    "sync[addons]": {
      "kA": "hnMf9yd-YiqaYD5LTlVADg",
      "kB": "kfyWAdJ-_O51mZjOcTm0NQ"
    }
  }
}
```

Depending on the use case this could allow the application to use one of the kA or kB for a scope or to derive multi scope key from the key scopes.

For the specific case of the Hoverpad application we would just need to get a kB for the hoverpad scope.

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this?

**Comment by rfk** [comment]
-> backlog is the most appropriate triage spot for now, but I'm glad to have a place to continue this conversation in public.

>  implement a way for FxA bearer token to get keys related to their scopes.

I like this conceptually, but it's tricky - it can't be a simple web service that takes a token and returns some keys, because that service would by definition have to have access to the raw encryption keys, and we want to avoid that where possible.  I will have to do a bit of thinking here.

The *browser* could offer this API to webextensions, because the browser holds the raw encryption keys.  But that would limit it to working only in webextensions.

> sync[addons]

An aside, but is this the actual scope being used for addons storage sync?

**Comment by Natim** [comment]
> An aside, but is this the actual scope being used for addons storage sync?

No I took this one as an example but the one used by chrome.storage.sync API is `sync:addon_storage`

**Comment by rfk** [comment]
From discussion with @juliemccracken and @davismtl, I'm going to close out this meta-issue and open more specific implementation issue to correspond to the above PRs, so we can get a better visual sense of the scope of work remaining.

**Comment by rfk** [comment]
I broke this down into the following smaller issues:

* https://github.com/mozilla/fxa-content-server/issues/5494
* https://github.com/mozilla/fxa-oauth-server/issues/483
* https://github.com/mozilla/fxa-oauth-server/issues/484
* https://github.com/mozilla/fxa/issues/269

And I also filed a separate one for "help with the crypto review" here:

* https://github.com/mozilla/fxa/issues/270
