### ISSUE TITLE
Failing require interpolatiing `$LIB_DIR/lib/db`

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2170]
One issue for a refactor that touched `bin/subhub_messaging.js`.

https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/bin/subhub_messaging.js#L32

That becomes `../lib/lib/db`, which can't be required, and that process fails at startup.

Gifting to @philbooth to fix, and I suppose check that there aren't any similar. (I didn't see any though).

**Comment by jrgm** [comment]
Kinda need a v1.143.3 to ship this tomorrow.

**Comment by philbooth** [comment]
> Kinda need a v1.143.3 to ship this tomorrow.

Done, sorry about that!
