### ISSUE TITLE
add payments and support panel to fxa-dev

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2174]
We have new servers, we should run them on fxa-dev too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-271)
┆Issue Number: FXA-271

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
