### ISSUE TITLE
Metrics for one-click signins / signins w/ cached credentials

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#2186]
Related to https://github.com/mozilla/fxa/issues/2009

Ideally we would

1. emit an amplitude `fxa_login - complete` event in these cases.
2. add a property that distinguishes these logins from cases that require a password. For example a boolean like `password_required` and make that an amplitude *event* property. 
3. (edit) ensure that the service the user is logging into is attached to these events.

cc @shane-tomlinson @davismtl

**Comment by davismtl** [comment]
Could we also add password_required to the `fxa_login - form_view`?

**Comment by shane-tomlinson** [comment]
Re-opening, still need to add the `password_required` property to view/login events.

**Comment by shane-tomlinson** [comment]
@vbudhram while I was away you worked on #2354 which is "Emit cached.signin.success metric when using cached creds". Does that fix this issue?

**Comment by vbudhram** [comment]
@shane-tomlinson Hrm, I would say that it doesnt fix this? We didn't add the user property, but we do emit a new event for the cached case.

@irrationalagent Do you think we still need the user property? Or is having the unique events good enough?

**Comment by davismtl** [comment]
The properties would allow us to know what proportion of logins are 1-click vs require a password.

Over time, we want to see the proportion shift to 1-click.

**Comment by irrationalagent** [comment]
related to 
https://github.com/mozilla/fxa/issues/2186

So @davismtl is suggesting a password_required property (true/false) and in #2186 i am suggesting a more comprehensive change where we have a `login_type` property that indicates the login flow. My suggestion there is to have property values `confirm` (when email confirmation is required) `password` when only the password is required (no email confirm) and `click` where no pw is required (only a button click)

**Comment by clouserw** [comment]
closing in favor of #2186
