### ISSUE TITLE
Name validation is not working properly.

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2195]
#### Affected versions:
- All Firefox 

#### Affected Platforms:
- All Windows

#### Steps to reproduce
1. Go to [123done](https://123done-stage.dev.lcip.org/).
2. Sign in/up with an account.
3. Click on "Subscribe to Pro".
4. In the "Name as it appears on your card" field enter the following name: 73s7 N@m3

#### Expected result:
An invalid name error should be displayed

#### Actual result:
No error is displayed.

#### Notes:
The name field should only allow letters, spaces, dashes, and apostrophes. Currently you can create a subscription entering anything as a name.

**Comment by clouserw** [comment]
If we make a regex for this we need to make sure we allow diacritics (like ā) and letters in other languages (like 濁点 or تنوين).  

CCing @peiying2 and @flodolo -- do you have recommendations for what validation should happen on a name?

**Comment by lmorchard** [comment]
I feel like this is one of those things we shouldn't restrict / allow Stripe to throw an error if necessary. [So many things can go wrong.](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)

**Comment by peiying2** [comment]
> If we make a regex for this we need to make sure we allow diacritics (like ā) and letters in other languages (like 濁点 or تنوين).
> 
> CCing @peiying2 and @flodolo -- do you have recommendations for what validation should happen on a name?

Flod is offline now, I am pinging our tech lead to see if he is online still to comment. I am not much of help on this topic.

**Comment by flodolo** [comment]
More context would help. I assume that's a credit card name, who provides the constraints on the name (`The name field should only allow letters, spaces, dashes, and apostrophes`)? I think that should be your starting point.

Magnetic cards can't even contain diacritics, let alone a different alphabet, as far as I know.

Or [this](http://english.cmbchina.com/CreditCard/DetailInfo.aspx?guid=81e25fb6-ebff-49ce-8ef8-f9081d9cc2cd)

> We recommend using the English name written on your passport, which is generally the Chinese name in pinyin.

**Comment by clouserw** [comment]
I thought about this over the weekend and I think it's the same answer as #2196.  The validation requirements for this field are on the payment processor and we don't want to have to update our code when they decide to modify what they'll accept (to say nothing of different cards having different rules).

@johngruen for visibility: please reopen if you disagree.
