### ISSUE TITLE
Credit card expiration year validation is not working properly

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2196]
#### Affected versions:
- All Firefox 

#### Affected Platforms:
- All Windows

#### Steps to reproduce
1. Go to [123done](https://123done-stage.dev.lcip.org/).
2. Sign in/up with an account.
3. Click on "Subscribe to Pro".
4. Enter any valid card number.
5. In the "Exp. date" field enter a date that is more than 4 years past the current date. (eg. 08/24)

#### Expected result:
An error is displayed informing the user that the expiration year is invalid.

#### Actual result:
No error is displayed.

#### Notes:
As most cards have a valid period of 4 years any date that is past that should return an error.
Currently, the error is displayed only when entering a very distant year in the future eg. xx/70

![image](https://user-images.githubusercontent.com/17178945/63010163-8a833980-be8e-11e9-907f-0e3ec33df0ef.png)

**Comment by clouserw** [comment]
The payment provider should be determining the validity of a credit card number.  As you mention, "most cards have a valid period of 4 years" -- if a card issuer decides to change their system we shouldn't need to make a change in our front-end code.

I recommend wontfix.  @johngruen ?

**Comment by johngruen** [comment]
Agree with @clouserw
