### ISSUE TITLE
Migrate from Alpine-based docker images to Debian-based docker images

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#2199]
We currently have two issues open to update from node 8 to node 10 (#374) or node 12 (#2179). Another change I'd like to see is migrating us from the Alpine-based variants to the Debian-based variants. That would require removing the -alpine prefix, fixing the OS package installs, user creation, and any other random breakage that may occur.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-274)
┆Issue Number: FXA-274

**Comment by clouserw** [comment]
@jrgm will put an example in here

**Comment by jrgm** [comment]
From triage meeting request, here's an example of moving from alpine to docker (which also changed the working directory to /app, which is the standard).
