### ISSUE TITLE
Propose event taxonomy for sending to Amplitude

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#222]
@davismtl something for the two of us to collaborate on over the next couple of days.

**Comment by davismtl** [comment]
Work in progress here: 
https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055

**Comment by vladikoff** [comment]
I sent an email with demo creds for Amplitude. We can also use the `amp` branch to experiment with taxonomy events if needed.

**Comment by vladikoff** [comment]
Closing, follow up issues will be filed if needed
