### ISSUE TITLE
Password input text is prefilled with the last password when trying to create a new account

### ISSUE THREAD

**Issue by abodea** [mozilla/fxa#2220]
## Steps to reproduce
1. Launch FF.
2. Access the `Send Tab` menu.
3. Enter any valid FF email and a wrong password.
4. Tap "Use a different account"
5. Enter a new email address to be redirected to the "Create Firefox Account"
### Expected behavior
The "Password", "Repeat password" & "How old are you?" input text fields should be blank.
### Actual behavior
The "Password" input text field is populated with the wrong password used in step 3.
### Device information
* Fire TV device: Fire Stick 4k.
* Latest affected Firefox version: **`Firefox TV v4.3 LAT1`**
* Earliest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Turbo Mode: On/Off

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-276)
┆Issue Number: FXA-276

**Comment by sv-sdeiac** [comment]
Hello, I was encounter this problem also with the FxA testing for Train 146. 
Additionally, I found different steps to reproduce the same issue.

1. Go to: https://accounts.stage.mozaws.net/?action=email&service=sync;
2. Enter an existing email and tap continue;
3. After the sign-in page with the password pre-filled, tap on 'Use a different account';
4. Change the email with another existent one;
5. Tap on 'Continue' button.

Actual results:
The Password field is populated with the pre-filled password from step 3.

Expected results:
The password field is blanked after changing the email.

Notes:
- I think that those steps are leading us to the same issue from the server and the pre-fill password setting.

**Comment by byrw** [comment]
May I work on it? 

Just a `cleanInput()` before navigating seems enough to fix it.
