### ISSUE TITLE
[FFTV] The back button from Terms of Service doesn't have any functionality and cannot be selected

### ISSUE THREAD

**Issue by abodea** [mozilla/fxa#2221]
## Steps to reproduce
1. Launch FF.
2. Access the `Sign In` screen.
3. Access `Terms of Service` and scroll until the bottom of the page.
4. Try to select the `Back` button.
### Expected behavior
The back button can be selected and the previous menu should be reached by tapping it.
### Actual behavior
The back button cannot be selected from `Terms of Service` page.
### Device information
* Fire TV device: **`Fire TV Stick 4k and 2nd Gen Stick`**
* Latest affected Firefox version: **`Firefox TV v4.3 LAT1`**
* Earliest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Turbo Mode: **`On And Off`**
![20190802_161023](https://user-images.githubusercontent.com/42831109/62372676-c0e0c080-b540-11e9-9978-49da93bb4a5b.jpg)

**Comment by dannycoates** [comment]
this is working in stage as of train 146. scheduled for prod on monday
