### ISSUE TITLE
Discuss: Titles within emails should (usually) match subject

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2222]
In #2017 the subject of many emails were updated, but the titles within the emails were not. Should the titles within the emails have been updated too? 

There are some exceptions that existed previous to #2017 and I imagine those will remain, e.g., where the title is "Almost done!" but the title is "Finish creating your account"

cc @ryanfeeley

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-277)
┆Issue Number: FXA-277

**Comment by shane-tomlinson** [comment]
@ryanfeeley can you request that you are added to the `fxa-ux` group: https://github.com/orgs/mozilla/teams/fxa-ux/members, you'll have to have @jpfaller request the same.

**Comment by ryanfeeley** [comment]
@shane-tomlinson My request is pending and i'll ask Jeff to do the same.

**Comment by jpfaller** [comment]
@shane-tomlinson for some reason I'm getting a 404 at that link

**Comment by shane-tomlinson** [comment]
@jpfaller - Are you part of the Mozilla org?

**Comment by jpfaller** [comment]
I think I am! I'm a contractor, but I have access to the fenix group.

**Comment by shane-tomlinson** [comment]
> I think I am! I'm a contractor, but I have access to the fenix group.

I don't see you in the list here: https://github.com/orgs/mozilla/people?utf8=%E2%9C%93&query=jpfaller. Let's ask @clouserw if he can add you.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closing this as inactive
