### ISSUE TITLE
Question: Should `prompt=none` trigger a `fxa_login - complete` event?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2225]
`prompt=none` landed, according to OIDC it's purpose is to check whether the user's credentials for an OAuth RP are still valid. Our purpose is slightly more lenient, to be able to sign into services w/o the need for user interaction. 

Right now `prompt=none` does not log a `fxa_login - complete` event. Should it?

cc @davismtl, @irrationalagent 

Ref https://github.com/mozilla/fxa/issues/2186

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-278)
┆Issue Number: FXA-278

**Comment by irrationalagent** [comment]
Are the cases here mostly that a user had previously signed in and are returning? Or might it also sometimes be that the user had signed into another service and we are using that to log them in automatically?

In either case though I think it probably should log the event, along with the `password_required = false` property. @davismtl can disagree

**Comment by davismtl** [comment]
Update:
@irrationalagent and I just discussed how we might want to take a step back to assess how we will want to distinguish these types of logins and how they measure our overall success rate:

- login w/ pwd
- just pwd
- pair with QR (or eventually a code)
- just click
- automatic login w/ prompt=none

They're in order of ease and as we shift users from one bucket to the next, we should expect our login success rate to improve.

*Short answer*, `password_required = false` is likely insufficient when we consider bigger picture.

**Comment by davismtl** [comment]
Just circling back:
> Are the cases here mostly that a user had previously signed in and are returning? Or might it also sometimes be that the user had signed into another service and we are using that to log them in to another service for the first time automatically?

These are two great questions I'd like to have more clarity on too.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Since I'm in the OIDC corner of FxA already, maybe now is a good time to reconsider these product questions about measuring prompt=none usage accurately. [~adavis@mozilla.com], any interest in making changes to how we measure various flavors of login?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Thanks for reviving this Jared.
Looping in [~loines@mozilla.com]. He recently documented a lot around device pairing metrics but now that he did that, I'd be curious how the rest of this fits in.

My early opinion is that these should prob be `fxa_login - *` events with a `fxa_login - complete` with a property to tell them apart:

  * login w/ pwd
  * just pwd
  * just click

At the very least, QR pairing should trigger `fxa_login - complete` and should likely also have a property to differentiate it but we're discussing the taxonomy/nomenclature of the events prior to that one. (we're really close to having the full picture here)

For automatic logins, I'm again tempted to track `fxa_login - complete` but again I would also use the same property to track a unique value to tell it apart from the other flows.

I could see us making charts in the future where we group `fxa_login - complete` by the type of auth flow users went through. 

Ultimately, all of these flows aim at authenticating a user. They just have different degrees of ease. Prior to auto-login, we would have asked for a password. We don't have fewer authentications now, we just made them easier and the metric should reflect that.

Leif, thoughts?

**Comment by data-sync-user** [comment]
➤ Leif Oines commented:

I broadly agree, though one issue is that IIUC for these sorts of logins we will not also be tracking a "top of funnel" event for purposes of calculating the login rate. We will be adding one to the numerator without adding one to the denominator. Put another way, we would be logging a completion event without a corresponding attempt event, and all of our success rates are of the form (number of completions) / (number of attempts). Ideally we would log them both, to keep the metric "balanced". Imagine a hypothetical where on one day millions of users were logged in with prompt = none. We could in theory then have a success rate of over 100%.

If we do have a event property to tell different flavors logins apart, as suggested by alex, then we could exclude prompt=none logins from the rate calculation. But, its not clear that we want to exclude them completely, as alex implied we should probably get "credit" for them. 

A long while back, I suggested some changes in this issue https://github.com/mozilla/fxa/issues/2438 ( https://github.com/mozilla/fxa/issues/2438 ) maybe that's not the perfect solution, but it does account for the above issue by proposing a more generic `fxa - flow_begin` starting event that would allow auto-logins of this type to be counted properly to the login rate. Maybe we need to circle back on whether we want to do that. Its a somewhat bigger change than just adding the event property.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

What are the next steps on this issue and who is the owner?  Thanks

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

[~wclouser@mozilla.com]
I think that this needs to be addressed within the context of FXA-333 and DS-101 (which I don't think we've made an equivalent FxA issue for yet... I'm checking with [~loines@mozilla.com]). The work in DS-101 resulted in this fine document: https://docs.google.com/document/d/1mYtPTswtzawcn-fwVIbJr1N2J-eiLYd6o1ymlB2DnKM/edit#

This issue combined with the 2 others aims to better measure our newest types of login flows (auto-login, QR, 1-click). Tackling the 3 together would ensure we have consistency in our solution.

We might want to make an Epic for the 3 of these.
