### ISSUE TITLE
Remove `marketingOptIn` param from services

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#2227]
While working on https://github.com/mozilla/fxa/pull/2208#discussion_r314670366, I wasn't sure if the `newsletter` property replaces the need for the `marketingOptIn` property. The newsletter property was introduced as part of trailhead changes and allows a user to register for multiple newsletters. 

Are there any reasons why we couldn't remove `marketingOptIn` in favor of newsletters?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-279)
┆Issue Number: FXA-279

**Comment by philbooth** [comment]
> Are there any reasons why we couldn't remove `marketingOptIn` in favor of newsletters?

Currently they're both included in the amplitude event schema (`marketingOptIn` gets serialised as `newsletter_state`). Might be worth checking with @irrationalagent and @davismtl before removing it, if we do want to remove it.

**Comment by davismtl** [comment]
I made this chart to show that they could potentially replace each other.

https://analytics.amplitude.com/mozilla-corp/chart/new/5u8moq2

We also seem to have stopped collecting the older one.

**Comment by vbudhram** [comment]
I found this https://github.com/mozilla/fxa/blob/b2b98f37658d15ea7e6db9d1ea64f6531a995208/packages/fxa-content-server/app/scripts/models/account.js#L715, while working on boomerang.

Updating this to remove `marketingOptIn`.

**Comment by krishnanunnir** [comment]
Hi, can I work on this issue? I think I could contribute.

**Comment by vladikoff** [comment]
@krishnanunnir Sure!

**Comment by krishnanunnir** [comment]
Hi, I am not sure where to ask for help, I tried the FXA IRC chat, but didn't get any response over there. Is it okay if I ask doubts over here?

**Comment by vbudhram** [comment]
@krishnanunnir We are currently migrating away from IRC, but feel free to ask any questions you have here.
