### ISSUE TITLE
Reconnect to Sync highlight doesn't have correct padding [bz1572922]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2233]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1572922

Created attachment 9084482
Screenshot from 2019-08-10 02-06-06.png

On an Ubuntu Eoan machine using Adwaita theme.

Using the default Firefox theme.

Was disconnected from Sync and received a prompt to reconnect.

The highlight in the menu panel showing my email address doesn't have enough bottom padding, so the highlight looks off.

See screenshot.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-280)
┆Issue Number: FXA-280

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

fixed in bz
