### ISSUE TITLE
[Boomerang] Reconsider including verification codes in email subject

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#2235]
Per[ user testing results ](
https://docs.google.com/spreadsheets/d/1ZThjOz-JE-oDbpEfMOYPkZ3cGZcYP63dZHR5mE7QEtE/edit?usp=sharing) of sign-up codes, we saw 2/7 participants not open their emails to verify. Both participants verified after immediately seeing the 6-digit code in the subject line. 

Codes in email subject made it convenient, however users are less motivated to open the email. Some considerations:
- Tracking email metrics cannot rely on open/click rate
- Security flaw to the login flow, since existing accounts have synced information. Including codes in the subject may provide unauthorized access for people who can view the notification.
 
Full user test report: https://docs.google.com/presentation/d/1DEsOfdkbbGRuk906DwrrTON6_dYGmp6L8El2fwPJC2c/edit?usp=sharing

**Comment by shane-tomlinson** [comment]
cc @jvehent - do you have any reference material that explains why including the codes in the email title is bad practice? I can imagine one possible reason is that the codes may show up in a lock screen notification on a user's mobile phone.

**Comment by jvehent** [comment]
Yep, showing up in notifications is the main reason.

**Comment by davismtl** [comment]
@jvehent and @shane-tomlinson 

Can we at least display them on registration emails? The account won't have any data in it.

**Comment by jvehent** [comment]
Yeah that seems reasonable to me

**Comment by clouserw** [comment]
This is already on registration emails and we won't do it on logins.
