### ISSUE TITLE
[Boomerang] Modify copy to clarify verification being a required step

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#2237]
Per[ user testing ](
https://docs.google.com/spreadsheets/d/1ZThjOz-JE-oDbpEfMOYPkZ3cGZcYP63dZHR5mE7QEtE/edit?usp=sharing) of sign-up codes, it was not 100% made clear that entering verification code is necessary to complete the account set-up. 1 participant stayed on the below page, believing he already finished account set-up.

<img width="400" alt="Screen Shot 2019-08-16 at 2 22 29 PM" src="https://user-images.githubusercontent.com/28498717/63189180-601db180-c031-11e9-9c99-37c91b401061.png">

Proposed copy could include words that emphasize the urgency and necessity of the codes:
“Enter code **now** to **complete** account creation...” 
“**Last** step…”
"You're almost there..."

Full user test report: https://docs.google.com/presentation/d/1DEsOfdkbbGRuk906DwrrTON6_dYGmp6L8El2fwPJC2c/edit?usp=sharing

**Comment by clouserw** [comment]
@ryanfeeley ^

**Comment by ryanfeeley** [comment]
Returning the service subheading to this screen (e.g. "to continue to Firefox Monitor") should achive the desired effect. I believe this has already been filed.

**Comment by clouserw** [comment]
@davismtl

**Comment by davismtl** [comment]
> Returning the service subheading to this screen (e.g. "to continue to Firefox Monitor") should achive the desired effect. I believe this has already been filed.

Is this done @ryanfeeley ?

**Comment by ryanfeeley** [comment]
Yes… live screenshot from today 
![image](https://user-images.githubusercontent.com/68213/67232286-0a89ca80-f40f-11e9-8b10-59afe9cccc66.png)

**Comment by davismtl** [comment]
In that case, this works for me. Closing.
