### ISSUE TITLE
[Boomerang] Reduce code expiration from 20 to 5 minutes

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#2238]
Per[ user testing results ](
https://docs.google.com/spreadsheets/d/1ZThjOz-JE-oDbpEfMOYPkZ3cGZcYP63dZHR5mE7QEtE/edit?usp=sharing) of sign-up codes, we saw 6/7 participants verify successfully within a minute of the code being sent. 7/7 participants stated that they have experience using verification codes for other services. 

**General feedback from participants was that the 20 minutes expiration was too lengthy to induce urgency.** One participant specifically mentioned that reducing expiration to 5 minutes would prompt her to verify immediately. 

Examples:

_PayPal login codes expire in 5 minutes_
<img width="200" src="https://user-images.githubusercontent.com/28498717/63190130-8e9c8c00-c033-11e9-9c8e-e3e1bd6879ce.PNG">

_Telegram login codes expire in 2 minutes, where upon expiry they call to verify_
<img width="200" src="https://user-images.githubusercontent.com/28498717/63190105-7af12580-c033-11e9-9136-6f26c3762465.png">

Since we are sending codes via email, the delivery time may vary. We could even modify copy to say 5 minutes, even if the code itself works for 20 mins. 

Full user testing report: https://docs.google.com/presentation/d/1DEsOfdkbbGRuk906DwrrTON6_dYGmp6L8El2fwPJC2c/edit?usp=sharing

**Comment by dianehuang11** [comment]
cc @davismtl @vbudhram @ryanfeeley for any thoughts to add.

**Comment by ryanfeeley** [comment]
Is this a good opportunity for A/B? If not, let's do 5 minutes.

**Comment by davismtl** [comment]
I don't think we need to A/B test.

The code can probably still last 20 minutes but we shouldn't say so. We should give them about 5 mins. I'm worried to go shorter because email is not always instant and we don't want urgency to turn into panic.
