### ISSUE TITLE
No account image is displayed in the subscription management page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2248]
#### Affected versions:
- Firefox 68.0.2

#### Affected Platforms:
- Windows 10 (64-bit)

#### Steps to reproduce
1. Go to [Firefox Account](https://accounts.stage.mozaws.net/settings).
2. Sign in/up with an account.
3. Click on the "Manage" button from the "Subscriptions" section.
4. Observe the page layout.

#### Expected result:
The default account image should be displayed.

#### Actual result:
No account image is displayed.

#### Notes:
The account image is not displayed even if uploading a custom image or in any of the other subscription window variants (active subscription or canceled subscription)

![image](https://user-images.githubusercontent.com/17178945/63265175-a1160000-c295-11e9-8e8b-64ebc644a9c8.png)

**Comment by lmorchard** [comment]
Since we recently made changes in this area, I'm guessing this might be a CSP issue? Might help to see if there are any messages in Web Console related to CSP while loading the profile image. We *might* need a server config tweak to make sure the right profile image server is allowed through for staging.

/cc @LZoog

**Comment by clouserw** [comment]
Yes, this is CSP.  Getting this in the console:

> Content Security Policy: The page’s settings blocked the loading of a resource at https://mozillausercontent.com/00000000000000000000000000000000 (“img-src”). react-dom.production.min.js:978
> Content Security Policy: The page’s settings blocked the loading of a resource at https://mozillausercontent.com/00000000000000000000000000000000 (“img-src”). react-dom.production.min.js:4080

**Comment by bsurd** [comment]
Verified today and the issue is no longer reproducible. The default account image is displayed and updated properly when selecting a new image. Closing the issue.
