### ISSUE TITLE
"Terms of Service" and "Privacy Policy" links are not displayed on FxA payment page

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#2250]
#### Affected versions:
 All Firefox

#### Affected Platforms:
Windows 10 (64-bit)

#### Steps to reproduce
1. Go to [123done](https://123done-stage.dev.lcip.org/).
2. Sign in/up with an account.
3. Click on "Subscribe to Pro".
4. Observe the page layout.

#### Expected result:
"Terms of Service" and "Privacy Policy" hyperlinks are displayed on the bottom right of the page.

#### Actual result:
"Terms of Service" and "Privacy Policy" hyperlinks are not displayed.

#### Notes:
We have the expected result from the wireframes.

![screencapture-mozilla-invisionapp-share-CXSAXZU2HZE-2019-08-19-16_02_38 (2)](https://user-images.githubusercontent.com/48829350/63268396-bfcbc500-c29c-11e9-8fcf-9ff5d2b05912.jpg)
![Screenshot_2019-08-19 Firefox Accounts Payments Server](https://user-images.githubusercontent.com/48829350/63268405-c2c6b580-c29c-11e9-88a3-e4327e478cc9.png)

**Comment by rfk** [comment]
> These should open in a new window

Do we expect that the payments page will always be accessed via a full web browser, or will it sometimes be possible for the user to be doing this inline in a signin flow that can't open a open window or tab?

I recall us having to turn these into something-other-than-normal-links on the FxA signin page due to some flows not being able to navigate to them property (e.g. iOS signin flow).

**Comment by chenba** [comment]
I noticed that the subscription management page has those links.  However, they have incorrect URLs.  The links are going to the payments server; those pages are on the content server.

I'll fix those links as part of this issue.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [Guardian VPN stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/). Using Firefox Release 73.0. Tested on MacOS 10.14.6.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [Guardian VPN stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/). Using Firefox Release 73.0. Tested on MacOS 10.14.6.
