### ISSUE TITLE
Subscription section is not displayed for newly created accounts

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2251]
#### Affected versions:
- Firefox 68.0.2

#### Affected Platforms:
- Windows 10 (64-bit)

#### Steps to reproduce
1. Go to [Firefox Account](https://accounts.stage.mozaws.net/settings).
2. Sign in with a newly created account.
3. Observe the page layout.

#### Expected result:
The "Subscription" section is displayed.

#### Actual result:
The "Subscription" section is not displayed.

#### Notes:
If subscribing to a product the section is displayed even after the subscription has expired.

![image](https://user-images.githubusercontent.com/17178945/63268536-0f11f580-c29d-11e9-948a-1e52c56c9d38.png)

**Comment by lmorchard** [comment]
I think this is the expected behavior for a new account. [The subscription management button should only appear if the user has at least one active subscription](https://github.com/mozilla/fxa/issues/1078), including if it's been cancelled but remains active until end of current term.

**Comment by clouserw** [comment]
Yes, this is by design.  Thanks
