### ISSUE TITLE
Authenticator tokens out of sync with Sync [bz1573895]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2270]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1573895

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0
Firefox for Android

Steps to reproduce:

Created Sync account. Enabled 2F auth. Used it happily for a few years, with 2-3 Android phones and 2-3 computers.

Bought new phone. Enabled sync on phone. Linked account to Google Authenticator.

Got a new computer.

Logged in to browser.

Got standard 2F auth request to enter token. (" Ouvrez l’application d’authentification et saisissez le code de sécurité fourni. )

Opened Authenticator on phone. Got token. 

Entered token in browser Sync login.

Token not recognized.

Try again. Not recognized again. ("Code de validation en deux étapes incorrect").

Actual results:

Enabled two factor auth with Google Authenticator.

Then the tokens from Authenticator stopped being accepted in desktop browser sessions.

My hypothesis is that there is corruption in the stored token causing the handshake with Authenticator to fail.

Expected results:

Successful login on entering a token from Authenticator.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-286)
┆Issue Number: FXA-286

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

fixed in bz
