### ISSUE TITLE
Add dropdown to Support form

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#2279]
Please add a dropdown to the top of the support form. It will only have two options ("Secure Proxy" and "Other"). Set the default to Secure Proxy. 

_Purpose: (1) We will need this drop down when we have more than one subscription, so this will scale faster, and (2) viewers of the support demo noted the current UI doesn't mention Secure Proxy, this solves for that issue without adding unnecessary copy._ 

![Support Form (Filled out)](https://user-images.githubusercontent.com/26334275/63388531-9f177400-c35d-11e9-901f-c04e01e9d54a.png)

**Comment by chenba** [comment]
For this issue we can hard code whatever the final product name is for Secure Proxy and "Other", with the default selection being Secure Proxy.  But I do have questions for when we have multiple product offerings.

1. Should the dropdown include the user's current subscribed products + "Other", or _all_ current products + "Other"?
2. What should be the default selection when there are multiple products in the dropdown?

@juliastarkov

**Comment by juliastarkov** [comment]
@chenba 
For post-MVP:
1. Subscribed products + "Other" (there _might_ be a case for adding "All products" as well but I'll chat with Rina about that). 
2. Once we have more than one product, if the user is coming from FxA the dropdown will show "Please select one" as it does with the other dropdown. If they are coming from SUMO, we will pre-populate to show whatever product page they're coming from.

**Comment by chenba** [comment]
I added the actual subscribed plans for the options of the new drop down since it wasn't too much work.

For example, in local dev environment:

![image](https://user-images.githubusercontent.com/198055/63898333-2d26d680-c9be-11e9-8680-12a526a4dda8.png)

**Comment by juliastarkov** [comment]
@chenba Updated mockups: https://mozilla.invisionapp.com/share/5BS1I7KANWP#/381321757_Support_Form
And Zeplin screens: https://zpl.io/2pMEYRN
