### ISSUE TITLE
Will a user logging into firefox preview/Fenix using their fennec session emit a login complete metrics event?

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#2287]
related to https://github.com/mozilla/fxa/issues/2009

@davismtl and I can't seem to discern in the data whether a user who is logged into fenix automatically via their fennec session will trigger any metrics around login. 

My hunch is that if this is done similar to https://github.com/mozilla/fxa/issues/2009 then there will be no event emitted. If there are no metrics, what could we do to ensure this is logged?

Also related to https://github.com/mozilla/fxa/issues/2225

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-288)
┆Issue Number: FXA-288

**Comment by davismtl** [comment]
I'm not convinced it is done similarly to #2009 

But @rfk might be able to shed some light on this since he has a good understanding of the component and FxA side.

**Comment by rfk** [comment]
Going to defer to @vladikoff on this one

**Comment by vladikoff** [comment]
After chatting with @rfk, we won't emit a complete event. We could add it, however we don't have a flow id in that native flow at that point. might have to wire that it

**Comment by davismtl** [comment]
If you guys can coordinate on that, it would be awesome. :)

**Comment by clouserw** [comment]
Would you break down the next steps here?  I think based on above comments Fenix needs to add some code?

**Comment by rfk** [comment]
I'm trying to get my head around the landscape here.

Over in https://github.com/mozilla/fxa/pull/2224 we added code to emit the "login complete" event directly from the front-end when it uses a sessionToken to generate an OAuth code. The equivalent for the Fenix migration flow would be to have *Fenix* submit a metrics event to amplitude when it completes the migration, which sounds like a violation of division of responsibilities.

Instead, we should have Fenix hit the `/metrics-flow` endpoint to obtain flowid etc, and then annotate its various requests to the backend servers so they can emit the appropriate events.

@davismtl @irrationalagent do you see this being a full "funnel" with both flow-begin and flow-complete events? What other events occur in this funnel, if any?

Here's what the sequence of operations would look like from Fenix's perspective:

* Show some UX prompting the user to sign in as the user that's already signed in over in Fennec.
* When the user clicks OK, hit the FxA `/metrics-flow` endpoint to begin the flow.
* Obtain sessionToken from Fennec and call `/session/duplicate` to make a copy of its own use. Should we have the server emit flow-complete here? At this point Fenix technically has everything it needs to complete the flow, but I don't think it actually saves that data to disk until the next step.
* Use the sessionToken to grant itself an OAuth refresh token with sync scope. We could have the server emit flow-complete here.

So...I think we would have to add a bit of code to Fenix to use `/metrics-flow`, and a bit of code in the auth-server to log completion events in some new places. The details of where to add both of those depend on precisely how you want to measure this funnel.

**Comment by irrationalagent** [comment]
I think we need both a flow begin and flow complete event, similar to what is proposed in #2438 because we want to add to both the numerator and denominator when calculating login completion rates. 

I agree we want to avoid Fenix sending events to amplitude directly, so using the metrics endpoint seems OK here. 

As for the two possibilities on when to log flow_complete, i tend to err on putting that event as late in the process as possible, but from my understanding of the earlier option (emit the event on `/session/duplicate`) there doesn't seem to be a particularly high likelihood of something "going wrong" before the final sessionToken -> refresh token step? if true then i would be ok with emitting the event there, if there are independent technical reasons to so.

**Comment by rfk** [comment]
> there doesn't seem to be a particularly high likelihood of something "going wrong" before 
> the final sessionToken -> refresh token step? 

Good question for @vladikoff and/or @grigoryk I think.

During the migration flow, once Fenix has obtained a sessionToken from Fennec, under what circumstances (if any) might the migration fail? Unverified sessionToken maybe? Network errors that we don't recover from gracefully?

**Comment by davismtl** [comment]
See also: https://github.com/mozilla/application-services/issues/1822
