### ISSUE TITLE
[content] running functional tests - ` ReferenceError: URL is not defined`

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2291]
Happened to notice this:
```
 via product page and redirect after confirm (1m:32s)
  ReferenceError: URL is not defined
    at Test.signup via product page and redirect after confirm [as test] @ tests/functional/sign_up.js:490:30
    @ src/lib/Test.ts:263:51
    @ anonymous
```

Which is here https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/tests/functional/sign_up.js#L490, and I don't see a  `require('url')` in scope there.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-291)
┆Issue Number: FXA-291

**Comment by shane-tomlinson** [comment]
@jrgm - which version of node are you using? According to the [node 10 URL history docs](https://nodejs.org/docs/latest-v10.x/api/url.html#url_class_url):

> v10.0.0 | The class is now available on the global object.

**Comment by jrgm** [comment]
Yeah, so in the teamcity containers, the version is nodejs@8

**Comment by vbudhram** [comment]
RIP teamcity...
