### ISSUE TITLE
Upgrade Sentry library

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2299]
At the bottom of all the logged issues it says "This event was reported with an old version of the javascript SDK."  -- we should upgrade that?

eg. https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6148239/?query=is:unresolved

@6a68 I know you're working on library upgrades, but I'm not sure this would show up in the regular tools so filing this

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-294)
┆Priority: Medium
┆Issue Number: FXA-294

**Comment by clouserw** [comment]
+ @jrgm @jbuck for visibility

**Comment by chenba** [comment]
This was resolved as part of #2345.  The content server front end is using `@sentry/browser` now.  (There's #3726 for the back end upgrade.)
