### ISSUE TITLE
The name "Firefox Accounts" missing from accounts@firefox.com emails

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#230]
The name "Firefox Accounts" was discovered to be missing from accounts@firefox.com emails in the March 7th SyncFest session.

<img width="617" alt="screen shot 2017-03-10 at 5 14 51 pm" src="https://cloud.githubusercontent.com/assets/17153650/23818963/4cbf7350-05b5-11e7-829d-1ce3ae0e2592.png">

**Comment by vladikoff** [comment]
@jrgm I think we fixed this but didn't uplift this to `master` https://github.com/mozilla/fxa-auth-mailer/pull/263
