### ISSUE TITLE
Implement commit message conventions to limit test suites run in CI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2303]
In CircleCI, [one can skip a build altogether with `[skip ci]`](https://circleci.com/docs/2.0/skip-build/) in the commit message.

It might be nice if we could maybe specify test suites to run in a similar way with our own commit message conventions. Maybe select packages? Select specific suites within packages?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-295)
┆Issue Number: FXA-295

**Comment by chenba** [comment]
Maybe it's something we can piggyback on `--grep`?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm marking this as won't do because it's not on our roadmap and it's not a high priority.  If the priority changes let's talk.
