### ISSUE TITLE
Implement branch name conventions to control test suites run in CI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2304]
Might be nice to skip CI runs for work-in-progress branches?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-296)
┆Issue Number: FXA-296

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm marking this as won't do because it's not on our roadmap and it's not a high priority. If the priority changes let's talk.
