### ISSUE TITLE
CWTS: need to have full control of selectable engines for Fenix

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2317]
We need to be able to provide a list of syncable engines in Choose what to Sync.

Currently we only allow `creditcards` and `addresses` to be customizable. Other engine types are hardcoded.

**Comment by clouserw** [comment]
Is this fixed by https://github.com/mozilla/fxa/pull/2320 ?

**Comment by vladikoff** [comment]
yes!!
