### ISSUE TITLE
FxA and Sync devices list are not in Sync (names not the same)

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#232]

**Comment by vladikoff** [comment]
@eoger is this fixed in FF clients?

**Comment by eoger** [comment]
I would need repro steps to confirm or not. I haven't stumbled upon this bug.

**Comment by vladikoff** [comment]
@eoger but we try to merge the client list with FxA on all clients these days, right?

**Comment by eoger** [comment]
Yup to my knowledge we do our best.

**Comment by vladikoff** [comment]
@eoger 👍 thanks!!

**Comment by rfk** [comment]
Awesome.  I think we can close this, and open smaller bugs with specific STR if we find cases where the lists are still mis-matched.
