### ISSUE TITLE
FxA Settings Redesign Phase 1

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2325]
The Settings of FxA were designed about 5 years ago when we only had about 4 sections. We currently have 9 sections and plan to have more in the future with foreseeable things like payment and billing details, U2F, Phone number, etc.

Let's make sure our Settings design is scalable and that users can easily navigate to find the things that they would like to change/manage.

Edit:
Here is the PRD 
https://docs.google.com/document/d/1oAfDMwHz7Ot1Hrxk6xYf2gtIVvjb_5jEqMv5mPIHp7s/edit

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-299)
┆Priority: Medium
┆Issue Number: FXA-299

**Comment by davismtl** [comment]
- Protocole out for feedback.
- Holly will post links here.
- Identified cards for card sort.
- Jeff is writing the cards.
- Getting feedback for tasks list. What are the top tasks that account users currently try to complete in Settings?

**Comment by hollycollier** [comment]
Here's the protocol for the IA Research: https://docs.google.com/document/d/1sR-ih1aGLUOyftZ-KWHGsZ2sxp_wP-3wqgynwx-6XfQ/edit#

And the spreadsheet of card content for the open card sort & proposed tasks for the tree test: https://docs.google.com/spreadsheets/d/1Q7m020_gxc00us_xGZNcxnuSZ9yLyEPbgQslB4oV07E/edit#gid=0

Feedback is due by 9/11. Let me know if you have any questions & thanks!

**Comment by davismtl** [comment]
- Launched the test today (open card sort). The test went well. 
- Stuff is on track.
- Check-in on Friday.
- Closed card sort next week.

In this document we go over tentative milestones:
https://docs.google.com/document/d/1ENHnw6inCOKuWQ1W8qj9pU-XBEXF-25Yv9XxnbVVAlE/edit#heading=h.voh6hkc7vxaz

**Comment by davismtl** [comment]
Update:
- Doing the analysis of closed card sort.
- On track to share findings this week
- Preparing tree test

AI: 
- Finalize the tasks that we want to ask users to do to test the taxonomy and tree test. Ideas:
   - change email
   - change password
   - add avatar
   - manage newsletter subscriptions
   - disconnect a device from your accounts
   - prevent yourself from being locked out

Holy will put a link to the spreadsheet.

**Comment by hollycollier** [comment]
Hi all -
Here's the spreadsheet tab containing tasks for the tree test of the proposed FxA Settings taxonomy:
https://docs.google.com/spreadsheets/d/1Q7m020_gxc00us_xGZNcxnuSZ9yLyEPbgQslB4oV07E/edit#gid=269971627

Please review and contribute tasks! These are the tasks we'll ask users to complete to make sure that they can find information within our proposed IA (for example:"You lost your old phone and you want to disconnect it from your Firefox Account. Where would you go to do that?"

We need you to:
• Review the list & add important/common/painful tasks to the list if they are missing (task + phrasing if you can—take a stab, I can help get the final phrasing right)
• Vote for the top tasks for testing (we can test up to 8; we should include a variety of categories and represent the tasks that we want to improve).
**Tasks are DUE Thursday 9/26 by your EOD** (the test pilot goes out on Tue 10/1)
Thank you,
Holly

**Comment by davismtl** [comment]
Janice kicked off a PRD (WIP)
https://docs.google.com/document/d/1oAfDMwHz7Ot1Hrxk6xYf2gtIVvjb_5jEqMv5mPIHp7s/edit

Closed card sorting is done. Users, for the most part, put things where we thought they would (though a couple of exception)

Pilot of tree sorting kicked off this morning. Holly will look into launching it to a broader audience today.

**Comment by hollycollier** [comment]
Hi - 
Here's last week's Closed Card Sort findings presentation & deck for those that are interested:
[Recording of the presentation](https://mozilla.zoom.us/recording/play/TdjvrY4go_ApcR5gOvm7EBDEx27Q28DIhzVyE1KvaRmKTDFMbr1JgGAw-e5CDS0n?continueMode=true)
[Presentation deck (includes findings, an explanation of tree testing as a method & the taxonomy we'll be testing)](https://docs.google.com/presentation/d/10vSlTcGeCJd8RD75K5sGkfPtEotrmWqDdInoKM4rPLs/edit#slide=id.g603b5e2e54_0_55)
[Meeting Notes](https://docs.google.com/document/d/1Hdtgfh5vb-3Fd1A-Q9vOZQkP0p3yvVk2lwO0Tg5BLf8/edit)

**Next up:**
-   10/1-3: Tree test & Analysis 
-     After that: If needed: Repeat Tree Test with alternate tree structure or labels
-     10/11: Tree Test Findings Presentation

**Comment by clouserw** [comment]
@davismtl - Can you confirm that there is **not** engineering work to do here in Q4?

**Comment by davismtl** [comment]
We have dependencies on UX that lead us up to early December. It's for this reason we removed engineering from the Q4 OKRs.

I plan for us to work on this first thing in Q1 so if someone has spare time at the end of Q4 then we can put time on it to get a head start but I'm not under any illusion that it will necessarily be possible. 

I think a nice goal might be to aim for to ship an MVP by/in Berlin. (whatever an MVP may look like) But we'll review that timeline as we get closer to the end of the year.

**Comment by janiceahn** [comment]
I want to reiterate that our goal is to ship an MVP by Berlin if possible.

I've asked Chelsea to include you and Lauren as optional to the weekly
check-in where we'll be sharing designs starting tmw. we can also schedule
separate reviews if preferred.

**Comment by davismtl** [comment]
Alex to watch recording of last call to provide feedback about wireframes.

Let's dig in on scope of work for MVP for Berlin.

**Comment by davismtl** [comment]
Wireframes and designs have begun.

@janiceahn if you have links you'd like to add here, please do. :)

**Comment by davismtl** [comment]
Janice is getting a lot of UX feedback this week and we'll get a clearer update for next week.

Working on individual pieces that can be worked on by engineering.

**Comment by davismtl** [comment]
from mtg:
Janice and Philip are doing a usability test from the wireframes after Thanksgiving.

Chelsea is working on a timeline for this Q1.

**Comment by davismtl** [comment]
Usability plan is getting reviewed right now. Test driven analysis will start on UT. Jennifer is redesigning.

Tie this work into all the other parallel efforts around global and local navigation (and settings). Making sure we have alignment everywhere.

**Comment by davismtl** [comment]
I will close this since it was Q4 specific.
