### ISSUE TITLE
[fxa-payment-server] Update subscription management page for multiple plans

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2335]
Per #2078 mock-ups, the subscription management page needs UI updates to match the mock-ups for multiple product handling.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-301)
┆Issue Number: FXA-301

**Comment by lmorchard** [comment]
FWIW, [this is blocked](https://github.com/mozilla/fxa/issues/2078#issuecomment-525981960) and I'm not actively working on it at the moment

**Comment by lmorchard** [comment]
Tweaked title with `s/product/plan/` since we're aiming at managing plans

**Comment by bbangert** [comment]
@lmorchard is this still blocked?

**Comment by lmorchard** [comment]
> is this still blocked?

Yes, this is blocked until we have updated subhub APIs for multiple plans to implement against

**Comment by johngruen** [comment]
UX for this exists in Zeplin...We can take out a few parts for the first REV

1. Since we do not get card type from SubHub, let's whack that from this issue
2. Since adding a payment method is not free either, let's whack that from this issue

**Comment by bbangert** [comment]
@lmorchard given that we're now doing tiers instead of multiple products, should we table this entirely?

**Comment by lmorchard** [comment]
Yeah, I think so... the UX for tiers will likely be entirely different than what we've talked about for this issue so far

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~lorchard@mozilla.com][~bbangert@mozilla.com] - Les had mentioned this previously as a blocker for Multiple Products Support. Is that still the case?

Further, is this still blocked? My thoughts are that, now that we have Arch 2.0, we would not have SubHub blockers here. Correct me if I'm wrong? If it's still a blocker for multi products, I can help link the issues to each other for better tracking. If the github issue above # 2078 is still a blocker, too, then I can link that accordingly.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

This isn't blocked by subhub now, but we should file issues to break down the server-side work that now falls to FxA. Looks like 2078 isn't a standalone issue but an epic, so we probably need to do some fresh work breakdown from whatever the latest plan is for multiple plans

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

We need to know if billing period alignment is a requirement first, as that will drastically alter our server-side work.

**Comment by lmorchard** [comment]
I think in other meetings we've talked about coming up with a new design for this page that's closer to the new subscription create page.

But, if only for historic interest and because I had to look the mockups again, this is what "Per #2078 mock-ups" meant:

<img width="331" alt="Capture" src="https://user-images.githubusercontent.com/21687/86060101-ed36e280-ba18-11ea-887a-9df4066dfe32.PNG">

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

This work will be completed with the newly created story that covers the subscription management updates.
