### ISSUE TITLE
[fxa-payment-server] Update credit card prompt for existing card usage

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2336]
With #2078, new mock-ups exist for how to present the credit card choice if the user already has a subscription and wants to use the existing card on file or replace it with one they enter.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-302)
┆Issue Number: FXA-302

**Comment by lmorchard** [comment]
FWIW, [this is blocked](https://github.com/mozilla/fxa/issues/2078#issuecomment-525981960) and I'm not actively progressing on it at the moment

**Comment by johngruen** [comment]
UX for this exists in [Zeplin](https://zpl.io/Vxr3ErX)...We can take out a few parts for the first REV

1. Since we do not get card type from SubHub, let's whack that from this issue
2. Since adding a payment method is not free either, let's whack that from this issue

**Comment by lmorchard** [comment]
> let's whack that from this issue

Well, there's also 3) We don't have access to an existing card for a new subscription with Subhub either. What parts of this issue are left?

**Comment by bbangert** [comment]
I think we can table this for now, but leave it open for when we revisit multiple products *after* we do tiers. At which point the UX might change.

**Comment by lmorchard** [comment]
We will need *some* sort of use-existing-card UX for the tiers support - but, yeah, it will also probably look a bit different than what was lined up for this issue

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

This will be completed in full by the new story that covers the update card flow in its entirety.
