### ISSUE TITLE
[fxa-payment-server] Change displayed product from plan_nickname

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2337]
Right now the subscription checkout flow pages show the plan id selected. Stripe indicates this name should be an internal nickname, not displayed to users. The name we display should likely be a combination of the product + the billing interval. For example, for product `Firefox Awesome`, on a monthly plan, would be `Firefox Awesome - Monthly' or so.

SubHub already supplies the billing interval and product name when looking up the plans, so no API changes are needed.

This change in FxA should be applied anywhere the subscription is displayed (during payment, emails, and subscription management), and a corresponding ticket for SubHub and other IT services that may result in emails.

@johngruen, @stlhood what should the product name be?

@marty331 did you want to file a corresponding issue in the appropriate locations to ensure the new subscription name is carried through?

**Comment by bbangert** [comment]
I discussed this with @jackiemunroe, and it would be simplest to replace the `plan_nickname` with the correct display name for the plan. That would avoid any code changes in FxA, and centralize the naming scheme to SubHub for use in all materials.

**Comment by clouserw** [comment]
There is no work for FxA here so closing this.
