### ISSUE TITLE
Create point release for signup codes experiment in Train 145

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#2338]
From slack, the boomerang signup codes experiment will run on 40% of sync registrations. 20% for control group (uses links) and 20% for treatment group (uses codes). This will be a point release on train 145 so we can rollback if necessary.

cc @irrationalagent

**Comment by clouserw** [comment]
@vbudhram what's the status of this?

**Comment by vbudhram** [comment]
This has landed, closing!
