### ISSUE TITLE
Load balancer IPs are showing up in Sentry

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2341]
Most sentry errors we're looking at have what we think are load balancer IPs in the reports.  Things like 100k events with only 3 users.  Is it possible to get end user IPs in there so we can see how many users are affected?  @jrgm @jbuck

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-303)
┆Issue Number: FXA-303

**Comment by bbangert** [comment]
We can also have a custom scrub operation for it that could turn the IP into a hash:
https://docs.sentry.io/data-management/sensitive-data/#custom-event-processing-in-the-sdk

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closing
