### ISSUE TITLE
TypeError: null is not an object (evaluating 'a.title')

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2342]
This is only showing up on IOS Firefox 18.2, and it just started 2 days ago.  

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6177300/

```
TypeError: null is not an object (evaluating 'a.title')
  at r (/bundle-0e0b608a229f062397f52e26c9ab18413e0111c4/appDependencies.bundle.js:107:11816)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-304)
┆Issue Number: FXA-304

**Comment by shane-tomlinson** [comment]
> and it just started 2 days ago.

This has been going on for ages, just under a different bug. Lots of old bugs are being reported as new since we no longer fetch source.

**Comment by shane-tomlinson** [comment]
Sentry issue: [FXA-CONTENT-PRODUCT-EQF](https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/3204691/)

**Comment by meandavejustice** [comment]
Not sure how I'm going to repro this, open for suggestions.

Following files from the `/complete_signin` endpoint leads me to [a document.title call in baseView](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/base.js#L24) which seems unlikely 🤔

**Comment by meandavejustice** [comment]
@vbudhram Shane said you have don't some of the development on ios fxa, any tips for reproducing this bug?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is out of date
