### ISSUE TITLE
WebChannel error: No Such Channel

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2344]
This is one of the top reported events in Sentry, and searching for that error message on Google shows that the top hits are from people failing to sync and asking for help.  We should investigate what is going on here.

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/377150/

```
WebChannel error: No Such Channel
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-305)
┆Issue Number: FXA-305

**Comment by meandavejustice** [comment]
Seeing this on every page load on `http://127.0.0.1:3030/settings` and `http://127.0.0.1:3030/signup`

Looks like the channel is `account_updates`
```
Error: Unexpected error errors.js:125
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:21258
channel id: account_updates raven.js:51
WebChannel error: No Such Channel raven.js:51
ON ERROR RECEIVED: 
Object { message: "No Such Channel", stack: null }
 
Object { errno: 2, error: {…} }
raven.js:51
```

​

**Comment by clouserw** [comment]
Looks like Shane fixed a very similar issue in https://github.com/mozilla/fxa-content-server/commit/d4c0343c7494c6ee64470d8e01b8941c70d28d74
