### ISSUE TITLE
TypeError: e.onSubmitComplete is not a function

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2346]
This was first seen August 13th.  It's affecting a moderate amount of people.

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6148056/

```
TypeError: e.onSubmitComplete is not a function
  at submit/< (/bundle-0e0b608a229f062397f52e26c9ab18413e0111c4/app.bundle.en.js:9:211523)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-306)
┆Issue Number: FXA-306

**Comment by clouserw** [comment]
Sentry issue: [FXA-CONTENT-PRODUCT-1A0M](https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6188232/)

**Comment by meandavejustice** [comment]
https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js#L101

**Comment by vladikoff** [comment]
This can happen if the view is somehow rendered without an `onSubmitComplete` passed to it: https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js#L29

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is out of date. CWTS is on the sign up page now
