### ISSUE TITLE
Extract 2FA QR code screen into a mixin

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2348]
One step along the way to enabling 2FA as part of the login flow. Refs #2024

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-308)
┆Issue Number: FXA-308

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

This work is done but not landed. Feels weird to mark done, feels weird to mark cancelled. Going with cancelled. See https://jira.mozilla.com/browse/FXA-1750 for remaining work.
