### ISSUE TITLE
Use iPad icon for iPad

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2352]
**STEPS TO REPRODUCE**
* Sync an iPad
* Visit **Devices & apps**

**EXPECTED RESULTS**
* Icon used is icon-device-tablet-ipad.svg

**ACTUAL RESULTS**
* iPhone icon is used
<img width="333" alt="image" src="https://user-images.githubusercontent.com/68213/63886675-0e6a1500-c9a9-11e9-93c3-b7eb5e4513a3.png">

**Comment by philbooth** [comment]
Hey @ryanfeeley, can you paste the user agent header that's reported by that device? I don't have an iPad to test with and these icons are driven by the user-agent strings, so we can make sure the parsing code is behaving correctly if we have that.

**Comment by shane-tomlinson** [comment]
@philbooth - http://enterpriseios.com/wiki/Complete_List_of_iOS_User_Agent_Strings

**Comment by philbooth** [comment]
> @philbooth - http://enterpriseios.com/wiki/Complete_List_of_iOS_User_Agent_Strings

Thanks, although that doesn't really answer the question.

There are lots of those user agent string lists on the internet, they all claim to be "complete" but none of them are and none of them have up to date strings. The most recent string in the list you found is from 2015.

I already spent a lot of time going through such lists to find failing cases before. The last occasion was in mozilla/fxa-auth-server#2051, but there are other times I've played whack-a-mole too, e.g. mozilla/fxa-auth-server#1982 and mozilla/fxa-auth-server#1787.

Nonetheless, I will go through and manually check every one of the strings from your "complete" list to see if there are failing cases. But I already suspect none of them will reproduce this problem because the iPad strings there all include the text `iPad`, and our code for this is really quite simple:

https://github.com/mozilla/fxa/blob/0650d4eb504f2b77dcb3612eddd1f0bee9120518/packages/fxa-auth-server/lib/userAgent/index.js#L120-L122

So, help appreciated, but I'd still like @ryanfeeley to provide the user-agent string from the failing device in this particular case. Without it I don't have any way of knowing whether I've resolved his particular issue.

**Comment by ryanfeeley** [comment]
On my iPad this Firefox gets from: https://www.whatismybrowser.com

`Mozilla/5.0 (iPad; CPU OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.2b15817 Mobile/15E148 Safari/605.1.15`

**Comment by philbooth** [comment]
Interestingly, the user-agent parsing in the auth server appears to be behaving correctly here using the user-agent string given. With the following diff applied, the additional test case passes:

```diff
diff --git a/packages/fxa-auth-server/test/local/user_agent.js b/packages/fxa-auth-server/test/local/user_agent.js
index 852b46544..32b35cb71 100644
--- a/packages/fxa-auth-server/test/local/user_agent.js
+++ b/packages/fxa-auth-server/test/local/user_agent.js
@@ -538,5 +538,13 @@ describe('userAgent, real dependency', () => {
       deviceType: null,
       formFactor: undefined,
     });
+    assert.deepEqual(userAgent('Mozilla/5.0 (iPad; CPU OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.2b15817 Mobile/15E148 Safari/605.1.15'), {
+      browser: 'Firefox iOS',
+      browserVersion: '18.2',
+      os: 'iOS',
+      osVersion: '12.4',
+      deviceType: 'tablet',
+      formFactor: 'iPad',
+    });
   });
 });
```

So not sure where the cause of the problem is yet, still looking at it.

**Comment by ryanfeeley** [comment]
Desktop's got it, though I have no idea whether or not they have more to work with.
<img width="336" alt="image" src="https://user-images.githubusercontent.com/68213/64653367-45521900-d3f4-11e9-9c69-94fea56adf92.png">

**Comment by LZoog** [comment]
Hey @ryanfeeley, I'm wondering if you checked that while using Chrome or Safari. Will you check one more time for me por favor? 😇 I have an iPad Air 2 to test with and I see a similar user agent in Chrome (it at least states "iPad"), but in Firefox, I see:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/20.2 Safari/605.1.15
```

It seems that somewhere around iOS 12/13, Apple started sending a desktop header for tablets in some cases. I want to make sure my fix will cover your problem as well, Ryan - as Phil shows above, we're already checking for the words `iPad` and `tablet` so you should have never come across this if what you pasted is an accurate user agent for your iPad.

**Comment by ryanfeeley** [comment]
> Hey @ryanfeeley, I'm wondering if you checked that while using Chrome or Safari. 

I likely checked in Nightly at the time, and just checked again.

I even disconnected my iPad from `/settings` and re-authenticated, but still see the iPhone (i.e. Apple Phone) icon.

![Screen Shot 2019-12-09 at 4 15 47 PM](https://user-images.githubusercontent.com/68213/70473599-5ec03b00-1a9f-11ea-87c2-f2525ac47d09.png)

And when I check in desktop Chrome I see the same icon.

![image](https://user-images.githubusercontent.com/68213/70473724-9c24c880-1a9f-11ea-92fe-a3c5b7448fa4.png)

Is that what you mean?

**Comment by LZoog** [comment]
@ryanfeeley sorry, I meant will you check again what your user agent is reported from https://www.whatismybrowser.com/ ?

I'm seeing this issue on my personal iPad as well, but the solution I've got going would only fix the issue for you if the user agent is similar to what _my_ iPad reflects: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/20.2 Safari/605.1.15
`

I'm hoping your user agent is similar to the above and not what you posted originally. If it contains the word "iPad" as you reported before, I'm going to be left scratching my head.

**Comment by ryanfeeley** [comment]
@LZoog got it:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0`

**Comment by LZoog** [comment]
_Sweet_, I'll move forward with my fix then, thanks for checking again!

**Comment by garvankeeley** [comment]
Note that the user agent used for FxA and sync is not the same as UA shown in the webview: https://github.com/mozilla-mobile/firefox-ios/blob/master/Shared/UserAgent.swift#L18
