### ISSUE TITLE
Use Android smartphone icon for Firefox Preview

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2353]
**STEPS TO REPRODUCE**
* Sync a Firefox Preview
* Visit **Devices & apps**

**EXPECTED RESULTS**
* Icon used is `icon-device-phone-android.svg`

**ACTUAL RESULTS**
* Generic smartphone icon is used
<img width="341" alt="image" src="https://user-images.githubusercontent.com/68213/63886949-a10ab400-c9a9-11e9-86e8-0f6c6d32e4be.png">

**Comment by philbooth** [comment]
Hey @ryanfeeley,  can you paste the user agent header that's reported by this device? These icons are driven by the user-agent strings, so we can make sure the parsing code is behaving correctly if we have that.

**Comment by shane-tomlinson** [comment]
On my device it's:

`Mozilla/5.0 (Android 9; Mobile; rv:70.0) Gecko/70.0 Firefox/70.0`

**Comment by philbooth** [comment]
Similar to https://github.com/mozilla/fxa/issues/2352#issuecomment-527863569, note that user-agent parsing in the auth server seems to behave okay here:

```diff
diff --git a/packages/fxa-auth-server/test/local/user_agent.js b/packages/fxa-auth-server/test/local/user_agent.js
index 852b46544..fb3e0e929 100644
--- a/packages/fxa-auth-server/test/local/user_agent.js
+++ b/packages/fxa-auth-server/test/local/user_agent.js
@@ -538,5 +538,13 @@ describe('userAgent, real dependency', () => {
       deviceType: null,
       formFactor: undefined,
     });
+    assert.deepEqual(userAgent('Mozilla/5.0 (Android 9; Mobile; rv:70.0) Gecko/70.0 Firefox/70.0'), {
+      browser: 'Firefox Mobile',
+      browserVersion: '70.0',
+      os: 'Android',
+      osVersion: '9',
+      deviceType: 'mobile',
+      formFactor: undefined,
+    });
   });
 });
```

**Comment by rfk** [comment]
The difficulty here may be due to the special way Fenix registers its device record (via the oauth refresh token rather than sessionToken)

**Comment by clouserw** [comment]
@ryanfeeley: please put a priority label on this. thanks

**Comment by LZoog** [comment]
Patch: #3551
