### ISSUE TITLE
[content server] `fxa_login - complete` amplitude events are emitted if cached signin fails

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#2358]
Ref: https://github.com/mozilla/fxa/pull/2354/files#r318890570

In #2354, we added a new `cached.signin.success` event on the front end, as a trigger for the `fxa_login - complete` amplitude event. However, we're emitting it regardless of whether the call to `this.signIn` actually succeeds or fails, which means we're still over-counting the events in Amplitude.

As per the comment inside the `catch` handler, `this.signIn` is expected to fail if the session has expired. ~~So we need to emit `cached.signin.success` inside a `.then` handler before that `.catch` instead.~~

/cc @vbudhram, @irrationalagent.

**Comment by vbudhram** [comment]
This fix has been merged!
