### ISSUE TITLE
If a user changes their password, do they lose their subscription?

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2366]
This came up in a meeting and I just want to confirm resetting a password won't affect a subscription:

> If a user forgets their firefox accounts password, our supports page says “Any data you have on the server will be erased when you reset your password. Your other devices will stop synchronizing unless you update them with the new password.” I’m assuming that applies just to sync and won’t impact a users subscription but want to confirm: https://support.mozilla.org/en-US/kb/ive-lost-my-firefox-sync-account-information

**Comment by lmorchard** [comment]
I don't think a password change affects subscriptions. An account reset is performed after password change, but as far as I can tell [that doesn't include anything about subscriptions](https://github.com/mozilla/fxa/blob/627380f39ceda34c77cd9c5f65c1ab6f6051581f/packages/fxa-auth-db-mysql/lib/db/schema/patch-021-022.sql).

**Comment by clouserw** [comment]
Ben says no
