### ISSUE TITLE
Update support form handling to include product id

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2367]
Due to consolidating our Zendesk installs, we need to include additional information on the tickets we create. Specifically we need to include the product id as a custom field. The Zendesk custom field id is `360022027772` that should be used for the product name.

**Comment by clouserw** [comment]
We should use the product ID instead of the product name here

**Comment by chenba** [comment]
I see that @bbangert changed the title from 'product id' to 'product name', but then @clouserw's comment asks for product id.  😕

**Comment by chenba** [comment]
We allow users to select "Other" on the subscription drop down of the support form.  What should be the value for this new custom field when "Other" is selected?

**Comment by bbangert** [comment]
This should be product id, not name. Sorry bout the confusion.

**Comment by chenba** [comment]
Bumped the estimate up because the product id isn't part of the subscriptions data from the account model.
