### ISSUE TITLE
Not Tracking the OS User Property Properly in Amplitude for Form Views

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2368]
When looking at this chart:
https://analytics.amplitude.com/mozilla-corp/chart/new/2if5meo

We observe that there are nearly the same number of views and registration on iOS.

Prior to July, we had more `registration - complete` than `registration - form_view`.

@left47 and I believe it is preventing us from efficiently tracking changes in login and registration success rates.

CC @irrationalagent

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-311)
┆Issue Number: FXA-311

**Comment by irrationalagent** [comment]
@davismtl could this be due to our discovery last week that many reg - complete events for mobile were actually started on desktop?

**Comment by davismtl** [comment]
Oh yes, this is likely related! How do we work around this?
Should the reg complete always have the OS of the starting device? And the email confirmed event can have the OS of the other OS?

**Comment by davismtl** [comment]
Moving this to P3. It might be indirectly resolved as a result of deploying login and registration codes.

**Comment by vbudhram** [comment]
This looks fixed https://analytics.amplitude.com/mozilla-corp/chart/new/q5jec32
