### ISSUE TITLE
Ability to deploy docker images from private repos

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#237]
cc @shane-tomlinson @jrgm @jbuck

**Comment by vladikoff** [comment]
* update to the pipeline to support CircleCI API 
 *need to pay for DockerHub

**Comment by rfk** [comment]
Next step: prioritize getting dockerhub private

**Comment by jbuck** [comment]
We have 5 dockerhub private repos now, and I've added the credentials for each to the Circle CI private repo. If someone would like to verify that the CircleCI builds are working for these privates repos, go for it! If not I'll take a look at it next week

**Comment by vladikoff** [comment]
@jbuck yeap Push works and CI works, example here: https://circleci.com/gh/mozilla/fxa-auth-server-private/13

Do we need anything else for this?

**Comment by jbuck** [comment]
We're almost there! I've finished all of the code for private repositories, it just needs to be landed and deployed with Jenkins. That'll happen sometime this week, hopefully tomorrow

Then we can deploy from private repos

**Comment by vladikoff** [comment]
Sweet! 🍰

**Comment by vladikoff** [comment]
All done!!!
