### ISSUE TITLE
Integrate and deploy security event logs to our new FxA settings.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2370]
@farhan787 cooked up a [dashboard](https://drive.google.com/file/d/15FCCqNPJnEfMUwU9aNVR04iso50VZ799/view) over the summer.  We should expand it and add some polish.  What events should be surfaced here?  How should the dashboard be accessed?  

/cc @johngruen @juliastarkov @davismtl @ryanfeeley

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-312)
┆Issue Number: FXA-312

**Comment by chenba** [comment]
Currently the page is a minimally styled table of the latest 100 events in reverse chronological order.  
Screenshot: 
![image](https://user-images.githubusercontent.com/198055/67334417-b7377b00-f4e7-11e9-9e77-f3579df61f58.png)

That delete button deletes all the events on the page, that is, up to 100 of the latest events.

I'd like some general direction on what to do here so I can get started.

**Comment by farhan787** [comment]
@chenba a new table is also ready to add here, my [PR](https://github.com/mozilla/fxa/pull/2312) will be merged in few days if @vbudhram approve it.

**Comment by johngruen** [comment]
Sorry i missed this mention over the summer! this is really cool...Wonder if we could think about how to integrate this into the fxa settings redesign currently under waay

**Comment by davismtl** [comment]
> Wonder if we could think about how to integrate this into the fxa settings redesign currently under waay

@johngruen it's already part of the scope and in some of the early wireframes that I saw.

**Comment by davismtl** [comment]
@chenba I suspect we need to kick-off a feature document to determine scope.

**Comment by chenba** [comment]
@davismtl Do we have a timeline for this?  I know it's part of the Q4 OKRs.  Soon™️?

**Comment by davismtl** [comment]
Per our discussions this morning, we may post-pone this work until Q1 because:
- we're going to focus on some low hanging fruit to grow relationships before the end of the year
- the timing of this work isn't great given we're redesigning Account Settings. This way, we can avoid integrating it and then changing the design again in just a 1-2 months.

**Comment by clouserw** [comment]
We are dropping this KR from Q4 goals.

**Comment by clouserw** [comment]
epics are tracked in jira
