### ISSUE TITLE
[payments server] Subscription Management Page Should Redirect to Settings If the User Doesn't Have Any Subscriptions

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2372]
While the Settings page does not display the button for the subscription management page when a user does not have any subscriptions, if the user know the URL for the subscription management page, they can still land there.

**Comment by mbStavola** [comment]
I'd like to take this if possible.

**Comment by chenba** [comment]
@mbStavola Yes, please.  Thanks!

**Comment by viorelaioia** [comment]
@chenba , is the fix for this issue deployed in staging yet? I can still reproduce it.

**Comment by chenba** [comment]
@viorelaioia No, it's not deployed to stage yet.  Train 150 won't be tagged for almost another two weeks, so it'll be a while.
