### ISSUE TITLE
1.3 Ensure that 100% of users enabling TOTP download their recovery codes.

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2373]
Too many users are getting locked out.

Let's have users paste in a form one of their saved recovery codes to confirm that they've successfully saved them before we turn on TOTP.

Feature doc is being worked on here (WIP):
https://docs.google.com/document/d/16OMxNfbkJeXdLCrD3XJ0PfD2ia2kzeIHcYlS4mMSKgA/edit#heading=h.9qtbe4mxitxr

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-313)
┆Issue Number: FXA-313

**Comment by davismtl** [comment]
Starting feature document here:
https://docs.google.com/document/d/16OMxNfbkJeXdLCrD3XJ0PfD2ia2kzeIHcYlS4mMSKgA/edit#heading=h.9qtbe4mxitxr

**Comment by davismtl** [comment]
I'm aiming to finish feature doc today so we can do a kick-off with Ryan and Danny.

**Comment by davismtl** [comment]
The feature doc is pretty up-to-date but we need designs from @ryanfeeley for it to be ready for engineering.

**Comment by davismtl** [comment]
The work being done for AMO is a good design foundation to this work. See 2FA AMO design here:
https://mozilla.invisionapp.com/share/7PUGYZX2TJW#/screens/389634598_Two-Step_Authentication_Wall

**Comment by chelsea-lewis** [comment]
- Per @ryanfeeley, Design will complete revisions from Product and Content feedback week of November 4.
- Confirmed with @dannycoates that Engineering will begin in Sprint 151.

**Comment by davismtl** [comment]
Danny is starting this week.
@ryanfeeley has designs. 
@davismtl  needs to add it to the feature documents.

**Comment by dannycoates** [comment]
Likely landing in train-152

**Comment by davismtl** [comment]
From prd meeting:
@dannycoates is this still on track?

**Comment by dannycoates** [comment]
Behind schedule :(

The order of the flow requires some unanticipated changes to the backend. Targeting 153

**Comment by dannycoates** [comment]
Still targeting 153

**Comment by dannycoates** [comment]
Finally landed ☠️

**Comment by davismtl** [comment]
@irrationalagent @davismtl double check that we will successfully be measuring that this when it lands in release.
