### ISSUE TITLE
(Phase 3) Recovery Keys and Secondary Email at Login

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2374]
We have a KR written like this:
Increase by 100% the weekly number of users that setup an account recovery key and secondary email.

We've identified that we would like to do an account audit after X number of logins or Y amount of time after a successful login. 

We will ask users to verify that their email is still accurate, to check on their secondary and to download a recovery key.

Feature document: [add me]

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-314)
┆Issue Number: FXA-314

**Comment by clouserw** [comment]
epics are tracked in jira
