### ISSUE TITLE
Sentry error: Cannot read property 'closingEls' of undefined

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2376]
See https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/331142/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-316)
┆Issue Number: FXA-316

**Comment by clouserw** [comment]
Sentry issue: [FXA-CONTENT-PRODUCT-K3](https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/331142/)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

sentry links don't work anymore
