### ISSUE TITLE
flash of no password before requiring password

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2388]
Found while testing https://github.com/mozilla/secure-proxy/issues/393.

Use these STRs:

1. In browser A, sign into Sync, close any FxA windows.
2. In browser B, disconnect browser A from Sync.
3. In browser A, go to https://getpocket.com/login?s=homepage
4. In browser A, click "Log In with Firefox" - The user needs to enter their password, but they can still sign in.

Notice the flash of "no password" and then swapping to require the password:

![flash-of-no-password](https://user-images.githubusercontent.com/848085/64187601-d2cbc100-ce68-11e9-8136-da339ca10d03.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-319)
┆Issue Number: FXA-319

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this is out of date
