### ISSUE TITLE
Let users opt-out of sync when signing in to Firefox

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2396]
This issue is for the FxA-side details of [Bug 1577690](https://bugzilla.mozilla.org/show_bug.cgi?id=1577690).

As we expand the suite of products and services powered by FxA, we want users to be able to "Join Firefox" by signing in from about:welcome without forcing them to enable Sync. In conversation with @ryanfeeley we designed an approach that gives users this choice as part of the choose-what-to-sync screen.

### Current Experience

In the current approach, the user loads https://accounts.firefox.com/?service=sync&context=fx_desktop_v3 to sign in to Sync and they get the following after entering their credentials:

New user | Existing user 
--- | ---
<img src="https://user-images.githubusercontent.com/34695/64221852-9acc8880-cf11-11e9-91e4-b0d2588e9a07.PNG" height=250 /> | (no CWTS screen)

Notably:

* New users *have* to make sync datatype selections in order to continue the flow. If they close the tab or choose "back" then they won't be signed in to Firefox.
* Existing users don't see anything at this step, they get signed in and start syncing as soon as their credentials are accepted.

We should keep this experience for browser touchpoints where the user is deliberately signing in to sync, such as the sync preferences page. (We should also [show choose-what-to-sync for all new sync users](https://bugzilla.mozilla.org/show_bug.cgi?id=1572344) rather than only for new FxA users, but that's an orthogonal issue).

### New Experience

I propose making the `service=sync` part of that URL optional, and having about:welcome omit it, because the user is signing in to Firefox but not intending to use any particular service.

In this case we'll offer the user to set up sync but give them the option to decline.  So they would load https://accounts.firefox.com/?context=fx_desktop_v3  and after entering credentials we would instead show the following:

New user | Existing user 
--- | ---
<img src="https://user-images.githubusercontent.com/34695/64222274-e03d8580-cf12-11e9-850f-664b388e6d65.PNG" height=250 /> | <img src="https://user-images.githubusercontent.com/34695/64222293-f5b2af80-cf12-11e9-919f-ff9c28f42ef6.PNG" height=250 />

Notable changes:

* Existing users now see a kind of "choose whether to sync" screen.
* All users now have a "Don't sync this device" option which, if clicked, will continue the signin flow without enabling sync.
* There is no "back" option from this screen. I need to confirm with @ryanfeeley but I take this to mean that the user is successfully signed in to the browser at this point, and closing the tab or otherwise abandoning the flow is equivalent to choosing "don't sync this device".

**Comment by rfk** [comment]
To make this work, we'll need to make some changes to the [`fxaccounts:login`](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/docs/relier-communication-protocols/fx-webchannel.md#fxaccountslogin) webchannel message.

In the simplest case I think we could add a `service=sync` field to the message and include/omit sync-related fields as appropriate. So we would get the following cases:

* with **`service=sync` query param:**
  * **new user:** webchannel message includes `service=sync`, `offeredSyncEngines` and `declinedSyncEngines`
  * **existing user:** webchannel message includes `service=sync`, but not `offeredSyncEngines` or `declinedSyncEngines`
* **no `service` query param:**
  * **new user:**
    * **enabled sync:** webchannel message includes `service=sync`, `offeredSyncEngines` and `declinedSyncEngines`
    * **declined sync:** webchannel message does not include `service=sync`, `offeredSyncEngines` or `declinedSyncEngines`
  * **existing user:**
    * **enabled sync:** webchannel message includes `service=sync`, but not `offeredSyncEngines` and `declinedSyncEngines`
    * **declined sync:** webchannel message does not include `service=sync`, `offeredSyncEngines` or `declinedSyncEngines`

That looks complicated, but I think it would be OK from the browser's perspective:

* If the user opted in to sync (either when launching the flow, or on the CWTS screen) then the login message contains `service=sync`; if it does not then Sync should not be enabled.
* If the user made some sync data choices then the login message contains `offeredSyncEngines` and `declinedSyncEngines`; if it does not then the browser should use data from the sync server or appropriate defaults.

One thing that this approach doesn't solve is users who abandon the flow on the CWTS screen. This abandonment would result in no login message being sent to the browser and a failure to successfully sign in.  I think ideally we'd treat abandonment on this screen the same as clicking "Don't sync this device", but I fear that we may have to move the sync data selections out of `fxaccounts:login` and into a new separate webchannel message in order to do that reliably.

@shane-tomlinson, before I get any further down this path, what do you think about the direction this is heading?

**Comment by mhammond** [comment]
> To make this work, we'll need to make some changes to the [`fxaccounts:login`](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/docs/relier-communication-protocols/fx-webchannel.md#fxaccountslogin) webchannel message.

There are possibly a few changes I could suggest to future-proof the `:login` message (eg, instead of `service=string` do something like `services={sync: {offered: ..., declined: ...}}` etc, but I can't see a great reason to do that now.

>  I think ideally we'd treat abandonment on this screen the same as clicking "Don't sync this device", but I fear that we may have to move the sync data selections out of `fxaccounts:login` and into a new separate webchannel message in order to do that reliably.

Yes, I don't see any alternative if we did go that route. However, there seems to be some risk in confusing the user (and the browser!) in that case - the message that logs the user in would be sent *while* the user is on the CWTS screen, leading to:

* The browser changing state before the flow has finished might not be clear to the user and lead to a greater abandonment rate than if we just did it all at the end.
* The browser would then be in a "connected to an account but not connected to sync" state - and allow enabling sync from about:preferences#sync. You could imagine bizarre edge cases, triggered by the user experimenting after noticing the state change, whereby the user enables sync in about:prefs#sync and *later* completes the CWTS flow in the web content. To put this another way, what exactly should the browser do if it receives a message telling it about CWTS *after* it's already syncing?

So all in all, I'd probably advocate for an all-or-nothing approach here.

**Comment by rfk** [comment]
> To put this another way, what exactly should the browser do if it receives a message
> telling it about CWTS after it's already syncing?

😱 

I think "ignore it" is the only sensible option, or possibly "return an error so that web content can transition to an error page". But you're right this could lead to very confusing user behaviour!

**Comment by rfk** [comment]
> There is no "back" option from this screen.

From slack conversation, it seems that there is no "back" button in the latest version of the current UI either, so I'm fine with not trying to disentangle the CWTS stuff into a separate message.

**Comment by shane-tomlinson** [comment]
I am in agreement with @mhammond - while I was reading through your chart and before I got to his suggestion, I was thinking to myself that I wanted almost exactly what Mark outlined. Relying on the presence of `service` seems brittle and like it's going to cause us some problems. I'd go directly to the array/object of services and avoid all of that. Of course, we'd need to ensure we are backwards compatible with existing browsers, I suppose new browsers could advertise support for a "v2" login message in its response to `fxaccounts:fxa_status`.

There is a lot written about handling users that abandon on CWTS - that's a problem now that we have lived with for many years, knowing it's a problem. If the user closes the tab we could fire off a WebChannel message in a onbeforeunload handler, hoping it arrives on time though that relies upon a hope and a prayer.

> the message that logs the user in would be sent while the user is on the CWTS screen

We have this problem with emails already, the email is sent while the user is on CWTS. Many users feel their phone vibrate, open the email, and verify while they are on CWTS. We poll in the background on the CWTS screen to detect verifications and send the `fxaccounts:login` message if so.

**Comment by rfk** [comment]
> We poll in the background on the CWTS screen to detect verifications and send
> the fxaccounts:login message if so.

Remind me, does this mean that the user just gets whatever CWTS choices happened to be selected on the screen at the time they clicked the verification?

I guess this might also change with the switch from links to codes for initial verification.

**Comment by shane-tomlinson** [comment]
> Remind me, does this mean that the user just gets whatever CWTS choices happened to be selected on the screen at the time they clicked the verification?

That's exactly what happens. If the user has made no changes, then they get all sync engines. If they deselected one, then all engines minus that one.

> I guess this might also change with the switch from links to codes for initial verification.

@ryanfeeley - was CWTS considered with the signup codes? Will we want to delay sending the email until after CWTS, because a user that sees "here's the code you need" and doesn't know they need to enter a code because they are on CWTS might be mighty confused. Of course this leads to a situation where we fail to capture users who never complete the CWTS screen.

**Comment by rfk** [comment]
> Relying on the presence of service seems brittle and like it's going to cause us some problems.
> I'd go directly to the array/object of services and avoid all of that.

FWIW, I suspect that WAGNI, but have no particular objection to doing it this way.

One wrinkle here will be that we currently use `service=sync` on the backend in a few places to control e.g. which email to send. We may need to replace this with some other value in the sync-optional case.

**Comment by rfk** [comment]
> One wrinkle here will be that we currently use service=sync on the backend in a few places
> to control e.g. which email to send. 

In fact, which emails *will* we send in this case?

If the user needs to verify their account or their signin, we will send the email *before* giving them the the choice of whether or not they want sync. So I don't think we can send the "Ready, set, sync" email, and will instead use the more generic ones.

**Comment by rfk** [comment]
> So I don't think we can send the "Ready, set, sync" email, and will instead use the more generic ones.

From mtg: yes, we'll use the more generic ones, and @ryanfeeley is going to work on updating them a little.

**Comment by rfk** [comment]
> One wrinkle here will be that we currently use service=sync on the backend in a few places

This is the list of places where we currently check `service=sync` in the backend, as discovered by `rg "service.*sync" ./lib`:

1) In `./lib/log.js`, to special-case the way we populate `clientId` and `service` fields for [service notifications](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/service_notifications.md). I believe these values are consumed by Basket etc for metrics purposes.
2) In `./lib/routes/account.js`, during account creation, to determine what event should be the flow-completion signal.
3) In `./lib/routes/sign.js`, to determine whether to synthesize a placeholder device record for legacy sync clients.
4) In `./lib/routes/totp.js`, to determine whether to send a "new device" notification email when the user verifies a session via TOTP.
5) In `./lib/senders/email.js`, to customize the subject line of the `verifyEmail` email.
6) In `./lib/routes/utils/signup.js`, to determine whether or not to send a post-verification email when users verify their account.
7) In `./lib/routes/utils/signin.js`, to set the flow-completion event in the same manner as (2) above.

We'll have to figure out what to do instead for each of these cases. Strawman proposal:

1) We could arrange for Firefox to provide its OAuth client_id, and include that in the notification in the existing `clientId` field. This is probably most inline with how we handle logins for other services.
2) We'll need to apply the same logic regardless of what service the browser is requesting. Perhaps we should pass `context=fx_desktop_v3` in as an argument here and check for that instead?
3) No change, this is called by the browser and it will specify `service=sync` if appropriate, and we want to make a device record even if we sign in to the browser for some other reason.
4) I'm not sure what to do about this, but the current setup seems like a bit of a hack anyway. May need to refactor the way this is done more broadly. I'll spin out a separate issue for this. The solution will need to be similar to (6) below.
5) I think the current behaviour will be fine, we send a sync-specific email iff service=sync.
6) We need to know whether this was any kind of signin to Firefox, because that signin will give the browser the ability to enable sync at a later time even if it didn't enable it right now. So we should use whatever signal we use for (1) above.
7) As per (2) above.

**Comment by rfk** [comment]
> In ./lib/log.js, to special-case the way we populate clientId and service fields for service notifications.
> I believe these values are consumed by Basket etc for metrics purposes.

See also https://github.com/mozilla/fxa/issues/2485 for an idea about improving the coverage of these Basket notifications.
