### ISSUE TITLE
[iOS] [Train 145] "Repeat password" field is highlighted

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2399]
Environment:
iOS, stage - Train 145

Steps to reproduce:
1. Go to "Sign in to Sync".
2. Enter the email and tap on "Continue"

Expected result:
"Password" field is highlighted.

Actual result: 
"Repeat password" field is highlighted.

Video: https://drive.google.com/file/d/1nQvs-KYURiRYd7D6MN9qezQX5AZGkewe/view?usp=sharing

Note: not reproducible on Android/Win10.

**Comment by LZoog** [comment]
@SorinaFlorean will you confirm this is still an issue?

This view was changed in #2404 - according to Danny in there referenced PR, we don't want autofocus at all in mobile, and I can't reproduce focusing on "repeat password" with the latest code in XCode iOS simulation.

**Comment by SorinaFlorean** [comment]
@LZoog sorry for the late reply here, indeed on stage server - train 147 the issue is not reproducible. The behavior is changed, now when I tap on "Continue" none of the fields are selected, and I have to do this manually.

**Comment by LZoog** [comment]
I confirmed with UX that this is behaving as expected in mobile. We have another issue (#2705) open for desktop-only first PW field focus.
