### ISSUE TITLE
Account recovery is disabled if the password is changed without using the key

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2400]
Environment:
Stage server - Train 145

Prerequisites: User is logged in and Account recovery is enabled in "Manage account".

Steps to reproduce:
1. Tap on "Forget password" from Manage account.
2. Enter the email from prerequisites.
3. Tap on "create new password" from email.
4. Tap on "Don't have a recovery key" and change the password.
5. Go to Manage account page.

Expected result:
Account recovery is enabled.

Actual result:
Account recovery is disabled.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-322)
┆Issue Number: FXA-322

**Comment by rfk** [comment]
Unfortunately there are some subtle technical details that force us into this behaviour. If you reset your password without using a recovery key, we have to wipe your recovery key or risk the system getting into a bad state. Details in https://github.com/mozilla/fxa/issues/2106.

Perhaps there's something we can do in the UX to make this more obvious to the user though?
