### ISSUE TITLE
TypeError: Object doesn't support property or method 'toBlob'

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2401]
It looks like no version of Edge supports `toBlob`.  Someone wrote a polyfill at 
https://github.com/Mawi137/ngx-image-cropper/issues/74#issuecomment-428304953 which we could use if it's important.

It looks like if someone on Edge tries to crop their avatar right now it fails.  @davismtl is there a list of browsers we support?

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6189230/

```
TypeError: Object doesn't support property or method 'toBlob'
  at i.prototype.toBlob (/bundle-0a053c22ba4173eed724fbebfd3f8d1996e5054c/app.bundle.en.js:9:164173)
  at Anonymous function (/bundle-0a053c22ba4173eed724fbebfd3f8d1996e5054c/app.bundle.en.js:9:165513)
  at toBlob (/bundle-0a053c22ba4173eed724fbebfd3f8d1996e5054c/app.bundle.en.js:9:165482)
  at submit (/bundle-0a053c22ba4173eed724fbebfd3f8d1996e5054c/app.bundle.en.js:9:165649)
  at Anonymous function (/bundle-0a053c22ba4173eed724fbebfd3f8d1996e5054c/app.bundle.en.js:1:22721)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-323)
┆Issue Number: FXA-323

**Comment by davismtl** [comment]
There is not a list of browsers that we support yet. This may become necessary as Send and Monitor grow.

When looking at breakdown by user agent, less than 1% of our settings traffic is on Edge.
https://analytics.amplitude.com/mozilla-corp/chart/new/ui8145i

**Comment by shane-tomlinson** [comment]
Crikey, I *just* removed the toBlob polyfill in https://github.com/mozilla/fxa/pull/2215

**Comment by shane-tomlinson** [comment]
> There is not a list of browsers that we support yet. 

Sure there is: https://github.com/mozilla/fxa/blob/7228646ae64fb7ddce9071e567c94b1041382bcd/docs/supported-browsers.md

**Comment by davismtl** [comment]
> Sure there is: https://github.com/mozilla/fxa/blob/7228646ae64fb7ddce9071e567c94b1041382bcd/docs/supported-browsers.md

TIL :)

**Comment by clouserw** [comment]
Well, according to that we support the latest version of Edge, so, I guess we should restore that polyfill unless @davismtl says differently.  -> putting in the backlog

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this was replaced with new settings work
