### ISSUE TITLE
Stripe privacy policy link should open in new window on billing page

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#2402]
This would match the behavior of tos and privacy notice links in footer

![new-window-stripe-privacy-link](https://user-images.githubusercontent.com/1844554/64273223-ddd92c80-cf0e-11e9-9f44-769b87a0433e.png)

**Comment by shane-tomlinson** [comment]
I'm not sure whether it's applicable here, but within the content server if a user is signing into Sync or viewing settings on Firefox for iOS, we have to convert external links to visible text because we are unable to open external links in new tabs w/o breaking the signin/settings flow.

**Comment by shane-tomlinson** [comment]
See https://github.com/mozilla/fxa/blob/7228646ae64fb7ddce9071e567c94b1041382bcd/packages/fxa-content-server/app/scripts/views/mixins/external-links-mixin.js#L8
