### ISSUE TITLE
Return original scopes by default in refresh_token grant

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2408]
According to https://tools.ietf.org/html/rfc6749#section-6 when a client uses `grant_type=refresh_token` and does not provide the `scope` parameter, we should grant the same set of scopes as was originally requested:

```
   scope
         OPTIONAL.  The scope of the access request as described by
         Section 3.3.  The requested scope MUST NOT include any scope
         not originally granted by the resource owner, and if omitted is
         treated as equal to the scope originally granted by the
         resource owner.
```

We currently appear treat a missing scope as equivalent to the empty scope, which is not correct in this case.

**Comment by rfk** [comment]
(This came up during development on a moco-confidential project that I won't refer to explicitly by name here)

**Comment by shane-tomlinson** [comment]
Dup of #1867
