### ISSUE TITLE
[Boomerang] Different messages for invalid and expired codes

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2412]
Prerequisites: Perform all steps to create a new account until you reach the 'Enter verification code' page.

Steps to reproduce;
1. Enter an invalid code.
2. Enter an expired code.

Expected results: 
For 1. "Invalid registration code" message is displayed.
For 2. "Expired registration code" message is displayed.

Actual result: "Invalid or expired OTP code" message is shown to users. 

Reason: 
- users might get confused if the code is expired or not and using the same code again will end up to see the same message.

**Comment by clouserw** [comment]
This is by design
