### ISSUE TITLE
[Boomerang] New registration code per every email sent

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2416]
Prerequisites: Perform all steps to create a new account until you reach the 'Enter verification code' page.

Steps to reproduce;
1. Wait 5-10 minutes and tap on ("Not in inbox or spam folder? Resend") (make sure to be the same code as in prerequisites).
2. Wait for 20 min until the code from prerequisites expires.
3. Tap on the last email (from step 1).

Expected results:
Codes are different for every email sent for registration. 

Actual result:
The code is invalid since is the same code and 20 minutes have passed since the first email.

Reason:
- due to the fact that users might delete the first email by accident, and will be confused because the code was used in 20 min timeline.

**Comment by vbudhram** [comment]
from mtg: I don't believe this is a bug. The codes are time based, so a user could potentially get the same code if it is calculated in the same code window.

**Comment by vbudhram** [comment]
from mtg: Also note, that the minimum the code will last for 10mins and max 20mins. Closing unless I have mistaken the question.
