### ISSUE TITLE
Define metrics for 2FA screens in login flow

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2417]
When we add 2FA screens to the login flow (see #2024), we should be sure to add metrics. Most of the code will be extracted and reused from the 2FA screens in the settings page, so hopefully we can just vary the page info, and otherwise keep the same interaction metrics.

(description edited to clarify that this is connected to 2FA AMO work)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-327)
┆Issue Number: FXA-327

**Comment by vbudhram** [comment]
from mtg: Do you mean the 2FA setup screens while in the login flow, example what AMO is trying to do?

**Comment by irrationalagent** [comment]
I'm pretty sure this isn't what jared is referring to but we do currently track totp view/engage/submit/success events in amplitude for login w/totp.

**Comment by 6a68** [comment]
I updated the description to reflect that this is intended to mean, "when we add 2FA to the login flow in #2024, we should make sure there are metrics in the new screens."

I noticed this has been lumped into epic 1.3, ensure users download their recovery codes. If the recovery codes screen isn't instrumented, that might be a good separate issue.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Since this is the same flow from the settings page, I'm thinking the best approach here will be to just stick with the existing flow metrics for those screens. Closing in favor of FXA-308.
