### ISSUE TITLE
Deploy "nightly.dev.lcip.org" using Dockerflow

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#242]
cc @jrgm @jbuck , part of the Q2 OKR Backlog

**Comment by jbuck** [comment]
We're getting closer! Currently we have deployed:

- https://nightly.dev.lcip.org
- https://nightly-auth.dev.lcip.org
- https://nightly-oauth.dev.lcip.org
- https://nightly-profile.dev.lcip.org
- https://nightly-static.dev.lcip.org
- https://nightly-usercontent.dev.lcip.org

We're currently finding bugs and fixing them as we go.

**Comment by vladikoff** [comment]
This is working!

**Comment by vladikoff** [comment]
Out first P1 bug closed!
