### ISSUE TITLE
[fxa-payments-server] Create metrics reporting capability in payments 

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2425]
The payments-server has no metrics reporting infrastructure in it. Before any of the metrics issues can be done that add new events in the payment-server, some infrastructure to actually log the metrics must be built.

In content-server, the events are emitted to the `post-metrics` end-point, which logs them out for the log collector to submit to amplitude. Porting the code into the payment-server from content-server is likely to be more trouble than its worth, so the payments-server should have some similar setup with an end-point that the client-side can emit to, that logs out the event for collection.

**Comment by 6a68** [comment]
Wil pointed out that payments eventually wants to be just another RP, so I'm going to explore integrating as a relier before I continue work on #2734.

**Comment by 6a68** [comment]
Updating this issue with the current plan: I'm going to finish adding the metrics endpoint to payments for the current train (#2734).
