### ISSUE TITLE
Deprecate routes to tokenCode verification

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#2427]
Since https://github.com/mozilla/fxa/pull/2398, will update the type of code that is generated on sign-in confirmations when using a code. We no longer need the manually generated code but can use the otp based one. Specifically, we should do the following

- [x] Depreciate https://github.com/mozilla/fxa/blob/9a265905fd292178999f6b32b422401d1234f9bb/packages/fxa-auth-server/lib/routes/token-codes.js#L5
- [x] Remove https://github.com/mozilla/fxa/blob/5d709f96d371d51c781d40567cead4f15a70688c/packages/fxa-auth-db-mysql/db-server/index.js#L179
- [ ] Add migration to remove columns `unverifiedToken`.`tokenVerificationCodeHashArg` and `unverifiedTokens`.`tokenVerificationCodeExpiresAt`
- [x] Remove js-client endpoints
- [x] Remove associated tests

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-328)
┆Issue Number: FXA-328

**Comment by vbudhram** [comment]
from mtg: vbudhram to work this since the new stuff will land. This can be worked in train 147+ since the new sign-in codes need to run for at least a train.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is done except for removing columns which we don't need to do.
