### ISSUE TITLE
Breakdown oauth / profile db opsec bugs

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#243]
Need to further discuss with @rfk @jrgm and @jbuck to figure out what we need to do to improve opsec in oauth and profile servers

**Comment by rfk** [comment]
@jrgm @jbuck @vladikoff let's discuss this in the next devops catchup

**Comment by vladikoff** [comment]
👍

**Comment by vladikoff** [comment]
@rfk This was a Q2 thing, not sure what we want to do about this in Q3. Close it for now?

**Comment by rfk** [comment]
Good call, closing
