### ISSUE TITLE
Add a event or user property for the Firefox Channel

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2432]
Doing an analysis of our client-side changes is challenging because we don't track channel in FxA telemetry.

I understand that this is apparently pretty hard to do but as we do more client-side work to improve the discoverability of the various values of an account, it would be valuable to be able to do impact analysis on Nightly or Beta.

I propose we add an event or user property alongside the ua_* properties.

CC @irrationalagent

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-329)
┆Issue Number: FXA-329

**Comment by irrationalagent** [comment]
I agree we should do this if possible, but I don't think that the user agent reports release channel. maybe there is some other way?

**Comment by rfk** [comment]
I guess we could have the browser return its current channel in the `fxa_status` message. It wouldn't be foolproof but it would probably work for the majority of users. We might need to check with data stewards for completeness in case there are privacy concerns, but I can't really think of any.

**Comment by vbudhram** [comment]
from mtg: It is possible to do this, we would have to make some desktop changes and have it ride trains. Moving this to backlog, please move if you want earlier.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
