### ISSUE TITLE
Inconsistent casing of emails may cause Invalid Authorization Code error

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2434]
Originally from https://bugzilla.mozilla.org/show_bug.cgi?id=1512515

STR:

* Attempted to sign in as "rYaN-ThReE@kfr" with password "testtesttest" (which is not my real password, obviously)
* Re-submited the signin attempt several times, until I got rate-limited for password guesses and triggered the "Authorize this sign-in" screen.
* Retrieved the authorization code from my email and submitted it.
* Got an "invalid authorization code" error.

In the web console, I saw two requests to /account/login.  The first failed with "incorrect email case" error:
```
  POST /account/login
  {
   email: "rYaN-ThReE@kfr",
   authPW: "...",
   unblockCode: "CEKN5V1T"
  }
  --
  {
    "code":400,
    "errno":120,
    "message":"Incorrect email case",
    "email":"ryan-three@kfr"
  }

This error causes us to retry to login attempt with correct email case, but this fails because the unblock code has already been consumed:

  POST /account/login
  {
   email: "ryan-three@kfr",
   originalLoginEmail: "rYaN-ThReE@kfr",
   authPW: "...",
   unblockCode: "CEKN5V1T"
  }
  --
  {
    "code":400,
    "errno":127,
    "message":"Invalid unblock code"
  }
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-330)
┆Issue Number: FXA-330

**Comment by vbudhram** [comment]
from mtg: This might have to do with the unblock logic or the way we are caching them.

**Comment by rfk** [comment]
Bumping this issue, because we use the same "invalid email case" error code to drive the login flow for users who have changed their primary email address. So I think anyone who has changed their primary email address would hit this issue an be unable to use the unblock codes. This is my leading theory for the behaviour reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1664806.
