### ISSUE TITLE
Retire fxa-basket-proxy, let basket handle everything itself [bz1417298]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2439]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1417298

As of the deploy of train-100 and the latest update of basket, we should have everything we need in order to retire fxa-basket-proxy and let basket handle all that functionality natively.  Basket has grown an SQS event handler, and its API now accepts FxA OAuth token directly.

This bug is for figuring out and executing on a plan to make that tha transition a reality.

IIUC, we will need to:

* Update fxa-content-server config, so that it talks directly to basket's API via OAuth, rather than to our basket proxy.  In theory this involved just changing some URLs.
* Pick a cutover date for fxa-basket-proxy to stop handling SQS events, and for basket to start.  The config on our side is in [1] but this'll require some careful QA to ensure that we don't get e.g. any weird timezone effects.
* Get the above deployed to production, wait for the cutover date to pass, and assure ourselves that things are working properly.
* Tear down fxa-basket-proxy, remove its SQS queues, archive the repo, celebrate :-)

Shane, can you think of any other things we would need to do here on the FxA side?

Let's try this all our in stage once FxA train-100 is out the door.

[1] https://github.com/mozilla/fxa-basket-proxy/pull/48

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-334)
┆Issue Number: FXA-334

**Comment by vbudhram** [comment]
from mtg: @jrgm to investigate what is left for this.

**Comment by dannycoates** [comment]
done?

**Comment by shane-tomlinson** [comment]
@jrgm or @jbuck - has the basket proxy been removed from prod too? If so, we can close this.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~wclouser@mozilla.com] it looks like [~jbuckley@mozilla.com] did this work (as is noted in the bugzilla comments here: https://bugzilla.mozilla.org/show_bug.cgi?id=1417298) ( https://bugzilla.mozilla.org/show_bug.cgi?id=1417298) ) and on Github the 'code quality' component has been removed. Should we remove that component here as well?

If this should be counted toward the closed codequality backlog KR for this quarter, we would need to retro-add story points.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It's not clear any work happened in Q12020.  I think it should be left as is.
