### ISSUE TITLE
Provide IP Addresses for prod-test

### ISSUE THREAD

**Issue by marty331** [mozilla/fxa#2440]
A new environment will be created called "prod-test" and for this we expect FxA to have a set of unique IP Addresses.  Could those please be created and shared with SubHub?  @clouserw @jrgm

**Comment by clouserw** [comment]
@marty331 this is "prod-test" right?

@jrgm @jbuck this would be the IPs of fxa -dev and -stage environments

**Comment by marty331** [comment]
> @marty331 this is "prod-test" right?
> 
> @jrgm @jbuck this would be the IPs of fxa -dev and -stage environments

Yes, updated.

**Comment by jrgm** [comment]
fxa stage auth-server will connect with one of these three IP addresses - 3.217.6.148, 3.214.25.122, 3.94.151.18

For fxa-dev, we have “latest.dev.lcip.org” (updated continuously) and “stable.dev.lcip.org”. You’re probably interested in “stable”, but here is the egress IP for both: “stable” - 54.187.164.119, “latest” - 54.245.163.164

**Comment by marty331** [comment]
IP addresses received, closing.
