### ISSUE TITLE
Update docs to remove npm-shrinkwrap references

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2441]
Just noticed that the main README includes a link to https://mozilla.github.io/application-services/docs/accounts/local-development.html#updating-npm-shrinkwrap.

I've removed npm-shrinkwrap and npmshrink as of #2234, but these docs need to be brought up to date. (They also refer to fxa-dev, which I'm not sure is actively used anymore.)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-335)
┆Issue Number: FXA-335

**Comment by vbudhram** [comment]
from mtg: @6a68 Moving to backlog.

**Comment by smishra2903** [comment]
If this issue still open, can I work on this? 
Also. i am a beginner so I will be grateful if someone can help me know how to begin with.

**Comment by aayushi221** [comment]
Hey!
I'd like to work on this issue if it's still open. 
I'd also like to request a bit of guidance as to how to start this.

**Comment by Cronus1007** [comment]
@vbudhram @6a68 I don't think that the main Readme of the main branch contains the references to the npm-shrinkwrap  and npmshrink. So it would be better to close this issue
