### ISSUE TITLE
[Smoother feat] Email autofill not working for Lockwise and Send app

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2446]
Environment
- Production server
- Android, iOS

Steps to reproduce:
1. Sign in to Sync on the browser.
2. Install Lockwise app.
3. Tap on Get started.

Expected result: The email address used for Sync is auto-filled or a message asking if the same account should be used.

Actual result: The email is not auto-filled.

**Comment by shane-tomlinson** [comment]
> Sign in to Sync on the browser.
> Install Lockwise app.
> Tap on Get started.

These are totally different apps so will not work and not something we can control from the FxA side. If you sign into Sync and sign into Monitor in the same browser, then the email should be remembered.

**Comment by rfk** [comment]
I agree there's nothing FxA can do here. We do have some code for sharing signin state from Fennec to Fenix, and may be able to add similar code to have it share signing state to the Monitor and Send apps. I'll take a task to migrate this issue to feature requests on the relevant repos.

**Comment by rfk** [comment]
For Lockwise on Android, this has been implemented here: https://github.com/mozilla-lockwise/lockwise-android/pull/879

I've filed a corresponding feature-request for Send here: https://github.com/mozilla/send/issues/1393

I'm going to close this issue because it's not actionable on the FxA side.
