### ISSUE TITLE
[Sentry] AppError: An internal server error occurred

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2448]
https://sentry.prod.mozaws.net/operations/auth-prod/issues/6242694/

```
AppError: An internal server error occurred
  File "/app/node_modules/hapi/lib/toolkit.js", line 52, in module.exports.internals.Manager.execute
    response = Boom.badImplementation(`${method.name} method did not return a value, a promise, or throw an error`);

AppError: An internal server error occurred
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-336)
┆Issue Number: FXA-336

**Comment by shane-tomlinson** [comment]
Sentry issue: [AUTH-PROD-3B](https://sentry.prod.mozaws.net/operations/auth-prod/issues/6248167/)

**Comment by vladikoff** [comment]
In this case `deviceType: None, ` probably caused the error

**Comment by vbudhram** [comment]
from mtg: Moving to backlog, please move out if you think it is big enough.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

sentry links are out of date
