### ISSUE TITLE
Discuss: allow subdomain matching in /metrics-flow allow-list

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2451]
The call to /metrics-flow for FPN was blocked because the site, even though it's a firefox.com subdomain, is not on the list of allowed sites in https://github.com/mozilla-services/cloudops-deployment/blob/0f99d96c0883ef136904905502ac205414611288/projects/fxa/puppet/yaml/type/fxa.content_server.prod.yaml#L8.

Could we allow subdomain matching on firefox.com to avoid needing to explicitly allow new subdomains to be added?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-338)
┆Issue Number: FXA-338

**Comment by clouserw** [comment]
"Sure, but it's a low priority"
