### ISSUE TITLE
Improve text wrapping of sync selections

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2456]
Not sure if this was fixed before but still happens on mobile on *Choose What to Sync* screen.
![choose-wrap](https://user-images.githubusercontent.com/68213/64639530-01501b80-d3d6-11e9-8661-84855e6ee793.png)

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa/issues/2130?

**Comment by ryanfeeley** [comment]
@vladikoff yes, thanks!
