### ISSUE TITLE
Create API route to force cache clear in profile-server and use it from auth-server

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2463]
## Background

The profile-server uses an SQS queue event stream to determine when to clear the cache for a user. This makes the RP login system prone to race timing issues in that its not possible to gauge with accuracy whether the cache is cleared before an RP makes a request for the users `/profile`. It's possible there's also latent cache timing issues like #498.

For our use in the subscription platform, we want to ensure that when an RP makes a `/profile` request, the data reflects the recently purchased subscription. To do this we need a guaranteed method of clearing the cache from the auth-server after the subscription is created but *before we redirect the user*.

## Solution

- [x] API route in profile-server to clear the cache for a user
- [ ] Configuration for profile-server API route to require server-to-server shared secret
- [x] Code in auth-server after subscription has been created in the database to call the profile-server cache clear route
- [ ] Configuration for auth-server server-to-server shared secret to use in the API call to profile-server

**Comment by rfk** [comment]
> bearer token

As in, a server-to-server shared secret, not an OAuth bearer token?

**Comment by bbangert** [comment]
Updated the description to reflect @rfk's comment.

**Comment by shane-tomlinson** [comment]
Do we have any idea *why* the existing cache invalidation logic is not working as expected? I worry that if we create a new route as a workaround, we are going to leave other instances of the cache being invalid.

**Comment by lmorchard** [comment]
> Do we have any idea why the existing cache invalidation logic is not working as expected?

Best guess so far is that it's still a race condition. I'm wondering if #498 actually fixed the issue, or if we left something out. Adding a synchronous method to invalidate the cache would solve the issue of relying on an async queue.

But, I'm also confused as to why the `profileChangedAt` mechanism doesn't seem to do the trick. Doing a little more poking, and I see that [profile-server expects a `profile_changed_at` property on the OAuth creds used](https://github.com/mozilla/fxa/blob/master/packages/fxa-profile-server/lib/routes/profile.js#L87) as a means of determining the freshness of the cache. [Maybe I broke it by renaming this from `profileChangedAt`?](https://github.com/mozilla/fxa/commit/7c27ef765e003fb83024998efce2e37338019963) 

Still, when I drop in some log statements, I don't actually see either `profileChangedAt` or `profile_changed_at` appearing at all in the `creds` object. I'm in unfamiliar territory, but I'm trying to dig through the layers to figure out if/where the OAuth creds (i.e. the token?) received by profile-server is meant to have picked up the profile change timestamp in the first place.

**Comment by lmorchard** [comment]
So, I *may* have worked out why existing cache invalidation isn't working:

https://github.com/mozilla/fxa/pull/2482

However, we may still want to implement this issue because I *think* the user would have to logout and back in again to pick up profile changes?

**Comment by rfk** [comment]
> I think the user would have to logout and back in again to pick up profile changes?

Yeah, possibly. The use of profileChangedAt here should ensure that RPs see profile info that is at least as fresh as the user's signin to the RP. But it won't help in a situation like:

* User signs in to RP, generating access token with "profile" scope.
* User visits acconts.firefox.com and updates their subscription info
* User returns to RP and triggers it to check their subscription info somehow
* RP refreshes user profile data using existing access token

If you're going to have flows like that, this synchronous clearing API will probably still be valuable.
