### ISSUE TITLE
Update email copy/templates for desktop decouple work

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2466]
In today's Desktop Decouple meeting, @ryanfeeley mentioned that he wanted to do a round of updates on our emails to check for (and remove) sync-specific messaging. This is a tracking issue so we don't forget to do follow up on that.

**Comment by ryanfeeley** [comment]
Adding @jpfaller as well.

**Comment by jdragojevic** [comment]
@ryanfeeley and @anamedinac  - is this something you still want ahead of Fx71 release?

**Comment by AnaMedinac** [comment]
@jdragojevic We can close this, I confirmed with Vlad that they are in Nightly.

**Comment by jdragojevic** [comment]
@vladikoff can you close this out, I don't have permissions.
