### ISSUE TITLE
[customs] Implement tooling to revoke long-term/permanent bans

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#2471]
Related to #2012.

In #2445, handling is added for the new action events from the dataflow pipeline. One of the actions, `disable`, is a long term ban that has obvious repercussions for users if it ever goes off in error.

To mitigate that, we should write some tooling to make it easy to revoke those bans in the (admittedly unlikely) event we need to back one out.

Not an immediate priority because the code is landing in report-only mode first anyway.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-343)
┆Issue Number: FXA-343

**Comment by vbudhram** [comment]
from mtg:

Do you intend to work on this in the current train?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
