### ISSUE TITLE
[fxa-auth-server] Drop the device `name` column? (it's now nameUtf8)

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2477]
![image](https://user-images.githubusercontent.com/128755/64742395-13ab8180-d4ca-11e9-8fd7-11f853ff825f.png)

Should we bother dropping the old `name` column for `devices`? 
@jrgm @rfk ?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-344)
┆Issue Number: FXA-344

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
