### ISSUE TITLE
[fxa-oauth-server] We should be stricter with OAuth scopes

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2478]
Improvement can be made to make the scope list stricter. We should cache allowed the scope list and validate against it.
See : https://github.com/mozilla/fxa/pull/2442#discussion_r323148483

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-345)
┆Issue Number: FXA-345

**Comment by shane-tomlinson** [comment]
Adding the context from the original comment:

> If an RP with allowedScopes defined requests a short scope that isn't in the allowedScopes list, then that scope will be allowed. Likewise, if a requested long scope name is not in the DB, and not in allowedScopes, we still allow it. It seems to me that we should be strict and only allow scopes that are in the list whether those scopes are in the DB or not. Which leads to the question of why do we do it this way?
