### ISSUE TITLE
[fxa-auth-server] attach refreshTokenId to tokens

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2480]
![image](https://user-images.githubusercontent.com/128755/64743024-54a49580-d4cc-11e9-9707-defa4e13d5be.png)

Ref: https://github.com/mozilla/fxa/pull/2442#pullrequestreview-286659709

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-347)
┆Issue Number: FXA-347

**Comment by clouserw** [comment]
Right now access tokens don't know what refresh token they came from so if a person deletes a refresh token it doesn't delete the access token (we just have to wait for it to expire).

**Comment by rfk** [comment]
This change would be in service of https://github.com/mozilla/fxa/issues/1249, where we want to delete all the access tokens when deleting a refresh token.
