### ISSUE TITLE
Notify Basket/SFMC of every service authorization

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2485]
We currently send SQS messages to Basket to notify about new account verifications and new logins, so that it can maintain a very coarse profile of what services a user has accessed via their Firefox Account. I believe there are a few cases where this scheme misses important user actions, and our work to [decouple signing in to firefox from setting up sync](https://github.com/mozilla/fxa/issues/2396) will make it worse. So I'd like to figure out how to make it better.

IIRC, Basket currently gets information about what services a user has accessed from the following events:

* [`account.verified`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/service_notifications.md#account-verification-event), which we fire when a user verifies their email address and their account becomes active.
* [`account.login`](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/service_notifications.md#account-login-event), which we fire whenever a new sessionToken is created.

As discussed in https://github.com/mozilla/fxa/issues/2009, https://github.com/mozilla/fxa/issues/2186 this doesn't actually give a complete picture of what services a user has accessed, because they can use a single cached sessionToken to access multiple different OAuth RPs without generating new `account.login` events.

It's also complicated to accurately count sync users in this setup, because some clients access sync via BrowserID (generating `account.login` events tagged with `service=sync`) while other clients access sync via OAuth) (generating `account.login` events tagged with the OAuth client id of the application, e.g. Lockwise or Fenix).

I propose that we add a new event, `account.authorized`, which fires whenever the user authorizes a new OAuth grant. The event metadata would include both the client_id of the RP which was authorized, and the set of scopes that were granted.  This event would be useful for tracking flow completions with cached credentials as discussed in https://github.com/mozilla/fxa/issues/2186, and would also let Basket maintain a more complete picture of user activity.

**Comment by clouserw** [comment]
@rfk is this for CDP?  Is there a timeline for this?

**Comment by rfk** [comment]
No, not specifically for CDP; it's part of ensuring we don't cause gaps in our metrics with the Desktop decouple work.

**Comment by rfk** [comment]
So, I jumped straight to a solution here, but it may not be the best one. I'm going to close this in favour of a higher-level "don't break SFMC" bug in Bugzilla, where we can make sure we understand requirements and agree on the appropriate way to meet them. Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1581707
