### ISSUE TITLE
[Sentry] TypeError: Cannot modify non-writable property 'entries'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2486]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/5841892/

```
TypeError: Cannot modify non-writable property 'entries'
  at startApp (./app.js:14:12)
  at startApp (./app.js:14:12)
  at Anonymous function (./app.js:14:12)
...
(2 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-348)
┆Issue Number: FXA-348

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

sentry links are out of date
