### ISSUE TITLE
Create Data Flow Diagram: FxA data to Amplitude

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#250]
In service of https://docs.google.com/document/d/13trLnLuoNtFk2vpb90KLLJQgfm2DlIw1DsNY48K_MHI/edit?ts=59139b93

**Comment by shane-tomlinson** [comment]
@rfk - I put this in active because you are already assigned, feel free to re-triage.

**Comment by rfk** [comment]
We did this, it's at https://www.lucidchart.com/documents/edit/a031bec6-a927-4420-850a-96c50307c993
