### ISSUE TITLE
Use Lockwise icon for all Lockwise clients

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2506]
Lockwise for iOS should use the Lockwise icon for now:
https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/icon-service-lockwise.svg

CURRENT:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/68213/64874904-f259ab00-d619-11e9-87a9-0589217d2c1a.png">

**Comment by rfk** [comment]
Possible dupe of https://github.com/mozilla/fxa/issues/1782, which has some more technical details on *why* this behaviour is happening.

**Comment by LZoog** [comment]
Patch: #3551
