### ISSUE TITLE
[EPIC] Improve technical documentation

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2508]
This Epic is specifically for improving our technical documentation.  I'm going to file issues for some areas so that we can assign them and budget time for them.

Documentation should live in https://github.com/mozilla/ecosystem-platform and we'll get that auto-deploying.

PRD: https://docs.google.com/document/d/1Fx0_iYtjEeV1L8uH4YlHNSqzW6uRPIag3Ve2ick9Hyg/edit?ts=5db86d15

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-352)
┆Issue Number: FXA-352

**Comment by clouserw** [comment]
I have a super rough draft outline of how this could mesh together: https://docs.google.com/document/d/14P94X3RnVb1SyatOp2H_NOPlj2jIvxrTDsusSOxK2zQ/edit

**Comment by davismtl** [comment]
Added PRD to epic description.

**Comment by davismtl** [comment]
Relying party docs have landed.

We're about half way there but here is a great demo of the progress that has been made:

https://drive.google.com/file/d/1j_8GXuu7Svo7eqwxF6Rfwj_iRhf_4Aw3/view

Will carryover into Q1.

**Comment by davismtl** [comment]
Wil will look through these. We need to see if we want to revise in this meeting moving forward.
