### ISSUE TITLE
Document how metrics work in FxA

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2509]
Just brain storming:

* How do numbers get in to Amplitude?
* How do numbers get in to Redshift?  How does that show up in Redash?
* Link to top level dashboards we use regularly
* Link to new stackdriver trace dashboard
* In addition to "how it works" include a "how to add a new event" section
* Front-end vs Back-end metrics

**Comment by philbooth** [comment]
Brain dump started here:

https://docs.google.com/document/d/1m0rtfFOS0EEhzt60_VyPA55hdZu5fzBOyyAt4e0Z6Pw/edit#

I'll need to rework it a bit so it answer the questions listed though, I only just saw those sorry.

**Comment by philbooth** [comment]
I've added some more to that doc. I don't think there's any more brain to dump now, I'm empty. What do I need to do to close out this issue @clouserw?

**Comment by philbooth** [comment]
Tentatively closing this out because of the above doc, but re-open if there's more to do.

**Comment by clouserw** [comment]
https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-metrics
