### ISSUE TITLE
Document how emails are sent

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2511]
Some emails are sent from FxA...

* How did we choose which emails are sent from FxA and which are sent from another service?
* Which services do we route the emails through?
* What happens when they bounce?
* How are the templates localized?  How do we know which locale to send to people?

**Comment by philbooth** [comment]
Have a document outline for this but realise it's going to be a lot easier to fill out after #1779 is done, because that gets rid of a load of stuff I won't have to waste time explaining. So I might try and make time to do that this week.

**Comment by philbooth** [comment]
🧠💩:

https://docs.google.com/document/d/1SHu64k27fA1SdxSPcLQ3-b9i5hHvJZRXlb5XIf7RCIA/edit

**Comment by philbooth** [comment]
Tentatively closing this based on the above linked doc, but re-open if there's more to do.

**Comment by clouserw** [comment]
http://localhost:3000/ecosystem-platform/docs/fxa-engineering/fxa-email
