### ISSUE TITLE
Document dev/stage/prod architecture

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2515]
I'm flagging @jrgm on this because he mentioned he was working on something (or had a plan to).

**Comment by jrgm** [comment]
https://mana.mozilla.org/wiki/display/SVCOPS/FxA+Auth+Server+Logical+Diagram
https://mana.mozilla.org/wiki/display/SVCOPS/FxA+Content+Server+Logical+Diagram
https://mana.mozilla.org/wiki/display/SVCOPS/FxA+Profile+Server+Logical+Diagram

**Comment by clouserw** [comment]
Thanks, closed in https://github.com/mozilla/ecosystem-platform/pull/41
