### ISSUE TITLE
Document how relying parties integrate with FxA & SP

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2518]
This should have some kind of checklist, including:
* (for rfeeley): Don't forget that new RPs need an icon!

**Comment by shane-tomlinson** [comment]
> This should have some kind of checklist, including:

Do you mean [something like this](https://docs.google.com/document/d/18l-EKwDyKwnUYUsvtud7j6AwfOe_ZA93YEkrBIjJe1Y/edit#)?
