### ISSUE TITLE
Determine why CAD events aren't being seen in DataDog

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#252]

**Comment by rfk** [comment]
IIUC this is a follow-up from a front-end coordination meeting; we're gonna need some more context here @shane-tomlinson @pb :-)

**Comment by shane-tomlinson** [comment]
Probably because the `connectAnotherDevice` experiment as such was removed from the content server when we enabled the feature for 100% of users. The follow on test started, called `sendSms`.
