### ISSUE TITLE
The 'j' and 'g' character from the email are cut on the Manage Account

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#2522]
Environment:
Builds: production;
Devices: Windows 10 ;

Prerequisites:
You are logged on a valid account and the email contains 'j' or 'g' letters.

Steps to reproduce:

1. Go to Manage account;
2. Watch the email;

Expected results:
The email is entirely visible without any visual problem.

Actual results:
The 'j' or 'g' characters from the email are cut on the Manage Account.

Notes:
- Not reproducible on Android;
- screenshot
![Screenshot_10](https://user-images.githubusercontent.com/40264165/64965677-1d582f00-d8a6-11e9-8468-7931aa17e72b.png)

**Comment by shane-tomlinson** [comment]
Dup of #1373, closing.
