### ISSUE TITLE
4.2.1 Decrease typical CI build time by 5 minutes (~25%) while maintaining adequate test coverage

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2525]
Starting an epic to organize efforts around shortening the duration of FxA CI runs.

**Comment by clouserw** [comment]
The OKR is to decrease build time by 5 minutes.  What is the time we are starting at so we can see what the target is for end of the quarter?

**Comment by lmorchard** [comment]
> The OKR is to decrease build time by 5 minutes. What is the time we are starting at so we can see what the target is for end of the quarter?

We could get some more accurate numbers by building some quick & dirty queries against CircleCI API. Short of that, I eyeballed a few older pages of CI runs - e.g. https://circleci.com/gh/mozilla/workflows/fxa/tree/master?page=5

I'm seeing runs from 32 to 39 minutes. Since four weeks ago, we've started landing some changes to speed things up, so better calculations should probably start at at least a month back if we want them

**Comment by dannycoates** [comment]
Let's round down to 30 minutes as our starting point**. That put's 25% at 7.5min or 22:30 target time.




** since I know we've already passed the goal ;)

**Comment by davismtl** [comment]
According to Wil, this is done. Wil will review them after this call.

**Comment by dannycoates** [comment]
done 🎉
