### ISSUE TITLE
Finish audit of FxA CI runs to find performance improvement opportunities

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2527]
Along with starting to read through tests, I started these notes on attempts to find opportunities to improve CI test performance:

https://docs.google.com/document/d/1Z47ImHnCL3TqOcqbeEbUXlMJz5Ltpq53FN_NDIdeowM/edit?usp=sharing

It's not much, but I'm hoping to massage it into a more interesting audit doc and/or a set of issues filed in github.

**Comment by clouserw** [comment]
Closing in favor of parent epic
