### ISSUE TITLE
Speed up CI step install-content-server with caching?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2528]
Looks like the CI step `install-content-server` does a few things over the course of 5 minutes or so:

* `sudo apt-get install -y graphicsmagick`
* `npm ci` in fxa-shared
* `_scripts/install_packages.sh` - which runs `npm install` or `npm ci` in every package directory
* Installing a Rust toolchain
* Compiling fxa-email-service

I wonder if some of these things could be cached?

* `browserid-verifier` takes ~90 sec for `npm ci` - part of this looks like building libs (e.g. `bignum`) from source
* Most PRs don't change fxa-email-service - could we use a cached build of that?
  * Also we *already* build fxa-email-service for its own test stage - so we're building this from scratch twice on every test run. Filed issue #2529 for this in particular
* Installing graphicsmagick is probably fast, but could we use a docker base image that already has that installed?

**Comment by lmorchard** [comment]
Of course, something to watch here is whether caching certain things ends up being worse performance because we store so much data that restoring the cache takes longer than a fresh build./

**Comment by lmorchard** [comment]
Skimming over this Medium post about using sccache with Rust & CircleCI - might be an option for fxa-email-service?

https://medium.com/@edouard.oger/rust-caching-on-circleci-using-sccache-c996344f0115

**Comment by dannycoates** [comment]
fxa-circleci docker image exists now
