### ISSUE TITLE
De-duplicate fxa-email-service builds in CI?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2529]
Looks like we build fxa-email-service from scratch twice with every CI run - once for the `fxa-email-service` test stage and again for `install-content-server` before `test-content-server` functional tests.

Could we de-dupe these builds? Maybe just use the artifact from fxa-email-service stage for install-content-server?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-355)
┆Issue Number: FXA-355

**Comment by lmorchard** [comment]
Maybe also relevant here: skimming over this Medium post about using sccache with Rust & CircleCI - might be an option for fxa-email-service?

https://medium.com/@edouard.oger/rust-caching-on-circleci-using-sccache-c996344f0115

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we don't build email service every CI anymore
