### ISSUE TITLE
Add ability for non-verified session to become verified

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#253]
Certain security features of FxA require that you be in a verified session aka the user has confirm the sign-in through their email, before they can be used. Currently, a verified session can only be accomplished when accessing FxA through Sync.

FxA needs the ability for a user to upgrade their session. This could possibly be through some confirmation loop (email, 2FA?) . Once they do this, the user should be able to use the feature.

One idea that has been considered are the following
* Display the panel for the feature, but when panel is open, prompt user to confirm the sign-in before they can use the feature.

**Comment by vladikoff** [comment]
@davismtl @ryanfeeley do we need a feature card for this?

**Comment by davismtl** [comment]
If feels big enough that we might want to turn it into a feature.

It would be interesting in the meantime to see if we can measure how many people visit security settings in an unverified state. It might help prioritize this.

**Comment by davismtl** [comment]
https://projects.growthhackers.com/s2/ZNFuxVTsKQOLtY--VyEEBg

**Comment by rfk** [comment]
> It would be interesting in the meantime to see if we can
> measure how many people visit security settings in an unverified state. It might help prioritize this.

@vbudhram just mentioned making a feature-specific dashboard and I think this would be a great addition to it: the number of users for whom we *would* have shown the add-email section if they'd been in a verified session.  (perhaps as a percentage of the folks who did actually see the section?)

**Comment by vbudhram** [comment]
from uno: this is done!
