### ISSUE TITLE
Drop in oauth server amplitude metrics Sat 9/4 ~ 5am PDT

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#2533]
https://analytics.amplitude.com/mozilla-corp/chart/ofslvrx

fixed link ^

this has caused the DAU of our non-sync services to drop substantially. almost certainly a problem on our end. 

cc @jbuck @davismtl @ckarlof

**Comment by vladikoff** [comment]
from slack : 

> pipeline isn’t processing events fast enough,

so this is not a problem with code changes

**Comment by rfk** [comment]
Too many `token.created` events to churn through?

**Comment by clouserw** [comment]
@irrationalagent is this fixed now that the queue has caught up?  I looked at metrics for the 4th and don't see anything out of place

**Comment by irrationalagent** [comment]
things looking good to me, I'm going to close this.
