### ISSUE TITLE
[Boomerang]Verification link is presented when you want to verify by resending from Sync

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#2537]
Prerequisites:
- Perform all steps to create a new account until you reach the 'Enter verification code' page.

Steps to reproduce:
- Tap on the hamburger menu;
- Click on the 'Verify Your Email' button;
- Click on the 'resend verification' button;
- Open the email and check the content;

Expected result:
A new link with the registration code is presented in order to confirm the account.

Actual result:
" Verify Your Account" email is displayed with the verification link instead of verification code.

**Comment by vbudhram** [comment]
@sv-sdeiac This is known and the intended behavior at this time. The browser will always fallback to verification links since it won't know if you are at an input field or navigated away.

**Comment by rfk** [comment]
> Click on the 'resend verification' button;

Something for us to consider here, is that the "resend verification" button in Firefox could open a new tab to a verification page in FxA rather than triggering the email resend itself. This would let us show a form or provide other context for different verification methods.
