### ISSUE TITLE
Support visiting the settings page with `context=oauth_webchannel_v1`

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2539]
The "manage account" menu item in Fenix will link to the settings page like so:

  https://latest.dev.lcip.org/settings?email=foo@bar.net&service=sync&context=oauth_webchannel_v1

Visiting this URL *should* use an `fxa_status` webchannel message to sync login state with the browser, and then display the user's settings page.

When @grigoryk tried this out just now, the `fxa_status` message went through OK, but it then directed him to the signin page.  Let's make sure we're treating the new `context=oauth_webchannel_v1` the same as `context=fxa_desktop_v1` in this case and letting it load the settings page.

**Comment by rfk** [comment]
From slack, the webchannel response that Fenix is sending back looks like:

```
{"id":"account_updates","message":{"messageId":"15688357952961","command":"fxaccounts:fxa_status","data":{"capabilities":{"engines":["history","bookmarks"]},"signedInUser":{"email":"gri3@restmail.net","uid":"6ead313a7cee415e9ab7f42d242522ae","sessionToken":"someFancyToken,"verified":true}}}}
```

But with a properly-formed sessionToken hex string.

**Comment by vladikoff** [comment]
fixed in https://github.com/mozilla/fxa/pull/2547
