### ISSUE TITLE
Add a /oauth/destroy route

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa#2540]
This would allow us to remove the OAuth-server [client code](https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccountsOAuthGrantClient.jsm) entirely from Firefox.

**Comment by rfk** [comment]
+1; this might also be a good opportunity to ensure compatibility with the [token revocation spec](https://tools.ietf.org/html/rfc7009) without breaking b/w compat with older clients.

**Comment by shane-tomlinson** [comment]
Is this the auth server's equivalent of the [/v1/destroy route on the OAuth server](https://github.com/mozilla/fxa/blob/a142c2528ea83dfd2852e0e5fa9cd79e74193904/packages/fxa-auth-server/fxa-oauth-server/lib/routes/destroy.js)?

**Comment by eoger** [comment]
> Is this the auth server's equivalent of the [/v1/destroy route on the OAuth server](https://github.com/mozilla/fxa/blob/a142c2528ea83dfd2852e0e5fa9cd79e74193904/packages/fxa-auth-server/fxa-oauth-server/lib/routes/destroy.js)?

Yup!
