### ISSUE TITLE
Can we safely assume that all `/certificate/sign` requests are coming from sync?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#2542]
Now that it's possible to directly grant OAuth tokens using a sessionToken, I believe that the only clients calling our `/certificate/sign` endpoint in the wild will be browsers connected to sync.  Is that true?

According to [this amplitude chart](https://analytics.amplitude.com/mozilla-corp/chart/t6a0g50), the vast majority of `cert_signed` events come through with no `service` property.  I take these to be certificate-sign requests from Desktop which does not send an explicit `service=sync`.  There is a much smaller volume of `cert_signed` events that have `service=sync` set explicitly.  And there is an extremely low volume (single-digit occurrences per day) of `cert_signed` events where `service` is some OAuth client.

I'm not sure how to explain the background rate of non-sync certificate signings. Are they maybe users who are somehow still using an older version of the content-server code that uses older OAuth endpoint?  I wonder if we should error out in these cases because we really don't expect that to be happening anymore.

If it is in fact true that the only users of this endpoint are for sync, I'd like to update the [`account.signed` event](https://github.com/mozilla/fxa/blob/098fe0780059c44faa09f7b5f868624b36130a09/packages/fxa-auth-server/lib/routes/sign.js#L178) to include an explicit `service=sync` in all cases. This will help us with distinguishing users who have disabled sync in their browser after [the great decoupling](https://bugzilla.mozilla.org/show_bug.cgi?id=1570565).

**Comment by shane-tomlinson** [comment]
>  I believe that the only clients calling our /certificate/sign endpoint in the wild will be browsers connected to sync. Is that true?

Kind of sort of. Firefox for iOS still uses assertions to [fetch OAuth tokens](https://github.com/mozilla-mobile/firefox-ios/blob/a7a1a2a9803b13c83e23a1b0ad28ecde6d1bec14/Account/FxAClient10.swift#L608), it looks like sometimes to get at kSync, sometimes [to get profile information](https://github.com/mozilla-mobile/firefox-ios/blob/a7a1a2a9803b13c83e23a1b0ad28ecde6d1bec14/Account/FxAClient10.swift#L636).
