### ISSUE TITLE
Deduplicate services in account deletion section

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2544]
I noticed that Notes appears twice in my Delete Account selection, as I have it installed both at home and work. Possible to deduplicate these services before presenting them?
![image](https://user-images.githubusercontent.com/68213/65269064-6dbdcf80-dae6-11e9-8c48-ae8ef1f5b031.png)

**Comment by shane-tomlinson** [comment]
Deduplicating this issue as a dup of #2450.
