### ISSUE TITLE
[iOS] Link exposed on synced devices page

### ISSUE THREAD

**Issue by athomasmoz** [mozilla/fxa#2545]
Steps to reproduce:
1. Open Firefox on iOS
2. Login to FxA
3. Hit the hamburger menu in the bottom right and click on your username
4. Click "Manage Account & Devices"
5. Click "Show" next to "Devices & apps"

Expected Behaviour

Underneath the devices, there's a named link to the SUMO article

Actual Behaviour

Underneath the devices, there's a URL in brackets that points to the SUMO article. It is not clickable & exposes UTM params

![image](https://user-images.githubusercontent.com/43346208/65269081-4f97a580-dacd-11e9-9b7c-f4ba9c87488d.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-356)
┆Issue Number: FXA-356

**Comment by shane-tomlinson** [comment]
This is intentional because the way settings is embedded within Firefox for iOS makes it impossible to open a link in a new tab, and redirects within the same tab provide no way to go back to the fxa settings page.

**Comment by shane-tomlinson** [comment]
For historical context, see https://github.com/mozilla/fxa-content-server/issues/3164 and https://bugzilla.mozilla.org/show_bug.cgi?id=1213210.

**Comment by clouserw** [comment]
@ryanfeeley is there work to do here?  Sounds like this was intentional?

**Comment by clouserw** [comment]
@garvankeeley it sounds like there is some history here about how this view is displayed on iOS.  Are there any plans on the iOS side that would let us make this a link?

**Comment by garvankeeley** [comment]
Yeah, I can put up a PR that does this: https://github.com/mozilla/fxa/issues/1369#issuecomment-500032558 , that is, opens a new tab for links.
