### ISSUE TITLE
Sending tabs does not work on Fenix/Fire TV with Desktop nightly

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/fxa#2546]
### STR
1. Try to send a tab from desktop to Fenix.
2. Observe.
3. Open Fenix and press Sync Now.
4. Observe.

### Expected
At 2 and 4, tabs should be sync'd

### Actual
Nada

Fenix:

> Nightly 190918 18:01 (Build #12611806)
> 📦: 13.0.0, 3cb2ac19c
> 🦎: 71.0a1-20190916093313

Desktop: 71.0a1 (2019-09-19)

**Comment by vladikoff** [comment]
works in stable, not nightly Firefox Desktop 

![image](https://user-images.githubusercontent.com/128755/65271593-7a90f200-daeb-11e9-8e44-23a708e69e1c.png)

very strange

**Comment by eoger** [comment]
These are 1582542 and 1582537 on Bugzilla.
