### ISSUE TITLE
Server installation using Nginx for noobs

### ISSUE THREAD

**Issue by OhDaeto** [mozilla/fxa#2550]
Hello! I meet for the first time with projects based on Node.js

I went through the simplest steps from the README file and now I want to make the registration web page public.

After setting "public_url" (the service was installed at https://fxa.r208.org/ ) in packages/fxa-content-server/server/config/local.json the registration process is work but canceled by an unknown error

![Снимок экрана_2019-09-20_02-56-13](https://user-images.githubusercontent.com/14937307/65289150-3e44ac80-db52-11e9-9bee-7391a0947e6c.png)

Where and what additional services should I forward with Nginx? Thank you!

**Comment by clouserw** [comment]
There isn't much I can say about an Unexpected Error -- maybe look in the logs?  I'm going to close this as there isn't much more we can do here.

Honestly, this is a complicated project with many sub-projects and other pieces (in other languages entirely).  It's not going to be simple to turn on and maintain.

**Comment by OhDaeto** [comment]
@clouserw I'm sorry, here's a partial log:  https://gist.github.com/OhDaeto/203850253038089b66d377dcc08e8788

**Comment by OhDaeto** [comment]
@clouserw i packed all logs in 1 archive: https://cloud.r208.org/s/k52Mowz6oWx3sY5
