### ISSUE TITLE
"Reconnect to Sync" takes too many clicks to reconnect [bz1582595]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2551]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1582595

Start Firefox when it is in a "please reconnect" state. Notice the hamburger menu indicates the "please reconnect" state.

* Click the hamburger menu - it opens.
* Click "Reconnect to Sync" - the "account panel" opens.
* Click "Reconnect to Sync" on this account panel - about:preferences#sync opens.
* Click "Sign in" - finally accounts.firefox.com is opened and I can enter my new password.

That seemed a very long journey. Ryan, do you think this can/should be streamlined?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-357)
┆Issue Number: FXA-357

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bz
