### ISSUE TITLE
Remove unused images in `fxa-content-server/app/images`

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#2554]
We have at least several images in `fxa-content-server/app/images` that are not used anywhere in the codebase anymore and should be deleted, including but not limited to `graphic_mail.png`, `graphic_mail@2x.png`, `account-verified.png`, and images starting with `ddarrow`.

Most of these seem to be cases where we replaced the use of a PNG with an SVG and did not remove the PNG.

**Comment by krtb** [comment]
Hi, could I give this issue a try?

**Comment by shane-tomlinson** [comment]
@LZoog have you already done this? Did I imagine that?

**Comment by LZoog** [comment]
I have not done this, but it may have a small overlap with #1878, just something to be aware of @dannycoates (tagging you since that issue is assigned to you).

@krtb sounds good to me, thanks! Let us know if you have any questions. :)

**Comment by krtb** [comment]
Thanks @LZoog! As an update on this

I've removed the images mentioned:
* `graphic_mail.png`
* `graphic_mail@2x.png`
* `account-verified.png`
*  all `ddarrow` files

The only remaining duplicate PNGs that also have a corresponding SVG file are:
* `spinnerlight.png`
* `spinnerlight@2x.png`

I ran a search on these and don't see them being used in the code base, all other remaining png's have a corresponding SASS file where they're referenced. 

Should the above `spinnerlight PNGs` need to be deleted as well?

**Comment by LZoog** [comment]
It seems we're still using `spinnerlight.png`, the mixin `hidpi-background-image` is called with the filename and looks like it spits out the file extension `.png` along with a `@2x` version. Thanks for checking out the rest of those! 😄

When you're ready to put in a PR, check out our guidelines here if this is your first contribution (forgive me if not, I checked for your username on previous PRs and didn't see ya): https://github.com/mozilla/fxa/blob/master/CONTRIBUTING.md
I'd probably consider this fix a type of 'chore'.

**Comment by krtb** [comment]
Oh no worries @LZoog, it was actually my first time! 😊 

Please let me know if there are any additional edits needed to my pull request or the changes that I made.

The PR can be found here: [#2635](https://github.com/mozilla/fxa/pull/2635)

**Comment by shane-tomlinson** [comment]
fixed by #2862, closing.
