### ISSUE TITLE
[Android&Win]Password tooltip not displayed when creating account

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2557]
Environment:
Android Q, stage server, Train 146

Steps to reproduce:
1. Go to Menu -> Settings -> Sign in.
2. Tap on "Create an account".
3. Enter a valid email.
4. Start typing the password.

Expected results: Password tooltip is displayed.

Actual results:  Password tooltip (bubble) is not displayed.

**Comment by clouserw** [comment]
@dannycoates is this the stuff you're working on?

**Comment by dannycoates** [comment]
I assume, because I don't have an Android, that this isn't using the email-first flow. There's no changes to that flow in 146, and we just had a discussion this morning about eliminating it.

**Comment by vasilicatamas** [comment]
This issue also reproduces on stage while using Firefox 69.0.1 under Windows 10 64-bit.

![password tooltip](https://user-images.githubusercontent.com/18114210/65420311-7f1a1b00-de09-11e9-807b-da5ca8d59bf8.gif)

**Comment by clouserw** [comment]
The tooltip is only for the email-first flow so this specific bug should be closed.  We're talking about migrating everything to email-first soon.  "soon"
