### ISSUE TITLE
upgrade "redis" library to "ioredis"?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#2559]
In converting fxa-shared to typescript we wondered if using [ioredis](https://github.com/luin/ioredis) would let us use less custom code. I don't know the history of our customizations so I can't make the best assessment. @philbooth what's your take?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-358)
┆Issue Number: FXA-358

**Comment by philbooth** [comment]
I'm in favour! We had particular reservations about reliable error-handling semantics with the old `redis` dependency, and that accounts for a fair chunk of our wrapping code IIRC. The rest was just to use bluebird disposers with the pooling, so it was impossible for callers to forget to release connections.
