### ISSUE TITLE
Investigate slow `total time` on performance graphs

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2561]
On this page https://sql.telemetry.mozilla.org/dashboard/fxa-performance we show percentiles for loading some pages.  It looks like the 90th percentile to load the log in page is taking 80 some seconds?  That seems really bad...  let's look into that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-360)
┆Issue Number: FXA-360

**Comment by shane-tomlinson** [comment]
ref #862, #662

**Comment by clouserw** [comment]
@philbooth do you have ideas on this?

**Comment by philbooth** [comment]
> do you have ideas on this?

Not yet, but I'll give it some thought tomorrow. It's possible we might get more data that helps figure it out after #2574 ships.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we have new perf graphs now and this has changed with the new page timings API
