### ISSUE TITLE
Access denied on “Federal Trade Commission” page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2572]
**Steps to reproduce:**
1. Go to https://accounts.stage.mozaws.net/signup?service=sync&context=fx_desktop_v3&entrypoint=menupanel
2. Insert a valid email address and a valid password.
3. At age field type a number <13
4. Click on “Create account” button
5. Click on “Lear more” link from “Cannot create account” message.

**Expected results:**
Federal Trade Commission page successfully displays the content.

 **Actual Results:**
“Access denied.You are not authorized to access this page.” message is displayed on Federal Trade Commission page

![Screenshot_2019-09-23 Federal Trade Commission](https://user-images.githubusercontent.com/18114210/65419480-67da2e00-de07-11e9-8606-c21e21aaf7cf.png)

**Comment by clouserw** [comment]
The URL we are using is http://www.ftc.gov/news-events/media-resources/protecting-consumer-privacy/kids-privacy-coppa .

Maybe https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy is the replacement?  I'll ask legal.  Good catch @vasilicatamas

**Comment by clouserw** [comment]
@mafeld

**Comment by clouserw** [comment]
Confirmed:  Let's use https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA stage server 148 under Firefox 69.0.3. Federal Trade Commission page is successfully displayed.

![ftc](https://user-images.githubusercontent.com/18114210/66745388-74422b80-ee87-11e9-888b-5f01f3848205.png)
