### ISSUE TITLE
The error message about recreating the account doesn't appears on Android or Windows 10

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#2575]
### Build: 
 Stage [Train 146], production;
### Devices:
- Google Pixel (Android Q);
- Nexus 6 (Android 6.0);
- Windows 10 - x64.

### Steps to reproduce:
- Connect on a valid account with multiple OS's;
- Go to 'Manage Account' from Windows;
- Tap on 'Delete' from the 'Delete account' section;
- Delete your account;
- On the other devices, go to Manage Account;

### Expected results:
A creation account flow is presented with the email pre-filled and an error: 'Account no longer exists. Recreate it?'.

### Actual results:
- The Creation flow is presented but the error message is not presented.

### Notes:
- Not reproducible on iOS;
- It seems that if you tap on the back button from your device (or PC), the same page is reloaded and the issue disappears.
- Screenshots:
- iOS 
![Image-1 (1)](https://user-images.githubusercontent.com/40264165/65422840-43368400-de10-11e9-99bb-94f6ee7ba716.jpg)
- Android
![Android](https://user-images.githubusercontent.com/40264165/65423059-cbb52480-de10-11e9-87c9-05b590361204.png)
- Windows 10 x64
![Screenshot_32](https://user-images.githubusercontent.com/40264165/65423088-e1c2e500-de10-11e9-8685-ee71902b9603.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-364)
┆Issue Number: FXA-364

**Comment by clouserw** [comment]
Maybe this is a media query thing?  We're unsure why this would be related to OS

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
