### ISSUE TITLE
Inconsistency between verification and authorization code field hint

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2576]
**Steps to reproduce:**
1. On Browser A, perform all steps to create a new account until you reach the 'Verification code' page.
2. On Browser B, perform all steps to login into sync until you reach the 'Authorize this sign-in' page.
3. Pay attention to the code field.

**Expected results:** for both situations, the field hint is the same.

**Actual results:** "Enter code" and "Enter 6-digit code" hints are displayed.

![Screenshot_44](https://user-images.githubusercontent.com/24588037/65432676-4c315080-de24-11e9-87d1-6db625344d6f.jpg)

**Comment by clouserw** [comment]
@ryanfeeley can you confirm the change above?

**Comment by ryanfeeley** [comment]
Great find @SorinaFlorean! And I would love these screens to be as similar as possible. I will discuss with @jpfaller.

@clouserw Can you confirm that both fields share the same six-digit syntax?

**Comment by jpfaller** [comment]
If both fields are 6 digits, we should use the "Enter 6-digit code" string

**Comment by clouserw** [comment]
@vbudhram can confirm ^
