### ISSUE TITLE
Ordering / Duplication of Send to Device menu

### ISSUE THREAD

**Issue by Left47** [mozilla/fxa#2584]
I've seen some incremental option creep in the Send to Device menu options that could use some UX love. See the screenshot and notes below.

• The first option is a macbook air that I haven't used in 8 months (and don't own anymore). Could we prioritize recently active devices? Or move that down / indicate it's inactive?
• I think the `DESKTOP-*` and the `jthomas-*` devices are the same laptop. Only the 4th option actually results in a tab being shared where I expected, even though it's the same as the 6th options.

![Image from iOS](https://user-images.githubusercontent.com/8242332/65458421-6c501800-de02-11e9-81d2-6b76215f5d69.png)

**Comment by rfk** [comment]
@Left47 if you're happy to, could you also please post a screenshot of your device list from https://accounts.firefox.com/settings/clients for comparison?

**Comment by davismtl** [comment]
Normally duplicates are the result of signing out and back in on the same device but over Slack, @Left47 was mentioning that he hasn't done that. (or not that he knows of)

**Comment by Left47** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/8242332/65459375-9dc9e300-de04-11e9-8285-53e117192fe8.png">

**Comment by davismtl** [comment]
Speaking to Jim, we noticed that the dates go back to roughly trailhead si this is likely the result of testing and creating new profiles.

Unrelated, there is a dup Pocket in this list and there is a bug tracking that here:
https://github.com/mozilla/fxa/issues/1802
