### ISSUE TITLE
Don't reset "sync_active_devices_XX" value after password reset

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2587]
When a user completes a password reset, we seem to reset the user property that indicates how many Sync devices they had in the last day, week or month.

This is making it particularly difficult to determine what proportion of users may be losing their data following a successful password reset since they seem to all be set to 0 which makes no sense because, at the very least, the value should be at least 1 since they successfully reset that sync device.

Proposal: do not reset this value with password resets. 
To discuss: If the reset is successful, increment it by 1 thanks to the successful password reset.

See: https://analytics.amplitude.com/mozilla-corp/chart/new/p0npanz 

CC @irrationalagent 

We apparently did a Re:Dash analysis but the charts are no longer good:
https://github.com/mozilla/fxa-auth-server/issues/1444

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-368)
┆Issue Number: FXA-368

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closing amplitude issues
