### ISSUE TITLE
(Phase 1) Recovery Keys and Secondary Email During Registration

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2595]
We’ve always had a steady volume of users complaining or reaching out to us via Bugzilla, SUMO, Twitter and Reddit due to being locked out of their accounts.

There are three reasons for this:
- They don’t have access to their email anymore;
- They forgot their password;
- They lost their device for TOTP.

This feature proposes to tackle the first two. The impact of the first reason is that users can’t get into their accounts. The impact of the second reason is that users risk losing their Sync data if they do not have more than 1 device actively Syncing.

As a first phase, we will send users an email immediately after registration to encourage them to setup a recovery key and a secondary email. This email will link to the settings. As a phase 2, we will link people to a screen that can be used from various places like our login flow and account toolbar menu in the browser.

Feature Doc: https://docs.google.com/document/d/1Wz0itS76pNS24zeNS5MEqqjQdwxHuNyfq3PTj8C688s/edit#

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-370)
┆Issue Number: FXA-370

**Comment by davismtl** [comment]
The feature doc is now ready for design.

**Comment by davismtl** [comment]
Ryan added proposed email templated to the feature. Jeff will help with copy.

We've realized that there may be two ways of doing this:
- 1 email with 2 calls to action
- 2 emails with 1 call to action

Let's see what amount of scope that would add?

**Comment by davismtl** [comment]
from mtg:
Work has started. Email templates have been created. Should land in 150.
Updating experiment logic so that auth server can use it.

**Comment by davismtl** [comment]
R+
It's a point release for train 151.
The experiment is setup and there will be 3 treatments with different email variations.

**Comment by davismtl** [comment]
Just working on enabling it and measuring it.

Config change for it to go out. No deployment needed.

**Comment by irrationalagent** [comment]
Rolled out on 2019-12-16 at about 7:50 PM PDT

[Started a dashboard](https://analytics.amplitude.com/mozilla-corp/dashboard/wwsbahr)

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Need to log a conclusion. [~adavis@mozilla.com]
