### ISSUE TITLE
Upgrade stale fxa-customs-server dependencies

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#2600]
We have to add an .nsprc exception to the customs server, due to stale versions of restify, csv-parse.

Once #2599 is resolved, and we have trustworthy tests, it'll be easier to upgrade those packages and know we haven't broken any functionality.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-372)
┆Issue Number: FXA-372

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

dependabot on github does this now
