### ISSUE TITLE
Update server to Hapi 18

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2601]
Currently adding .nsprc exceptions to fxa-auth-server and fxa-profile-server to work around a vulnerability in `subtext`, which is fixed, but in the re-namespaced package, `@hapi/subtext`. Picking up the fix requires us to upgrade to hapi 18, which introduced the naming changes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-373)
┆Issue Number: FXA-373

**Comment by shane-tomlinson** [comment]
cc @vladikoff didn't you put some effort into converting both of these to hapi 18?

**Comment by chenba** [comment]
Hapi 19 is out now.  We also need to switch to @hapi/hawk.
