### ISSUE TITLE
Different page/flow for mobile devices after tapping on Menu -> "Sign In"

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2603]
**Environment:**
- **Phone:**  
- Nexus 5 (Android 6.0.1)
- Google Pixel (Android Q)
- Samsung Note 8 (Android 9)
- **Tablet:** Samsung Galaxy Tab S3 (Android 8.0)
- **iOS:** iPhone SE (12.1.4)
Note: all devices have stage configs. 

**Steps to reproduce:** 
1. On phones - Android devices -> Go to Menu -> Sign In.

**Expected results:** The same flow is displayed on all devices.

**iOS Results:**
- "Enter your email to continue to Firefox Sync" page is displayed. 
- "Get more of these features" section under the "Continue" button. 
- Tapping on "Continue button" doesn't display again the "Get more of these features" section. 

**Android - Phone Results:**
- Sign in page is displayed.
- Tapping on "Create an account" doesn't bring up **"Get more of these features"** section. But the Skyline UI is visible. 

**Android - Tablet Results:**
- "Enter your email to continue to Firefox Sync" page is displayed. 
- "Get more of these features" section under the "Continue" button. 
- "Get more of these features" section. displayed also if the "Continue" button is tapped. 

**iOS**
![Image-1](https://user-images.githubusercontent.com/24588037/65598937-4151f980-dfa5-11e9-9a43-5b54808a5364.jpg)

**Android - Phone**
![Screenshot_20190925-144808](https://user-images.githubusercontent.com/24588037/65599363-58451b80-dfa6-11e9-8d5e-7e14ff3be559.png)
![Screenshot_20190925-150954](https://user-images.githubusercontent.com/24588037/65599525-b7a32b80-dfa6-11e9-94a0-88a984d00cc8.png)

**Android - Tablet**
![Screenshot_20190925-143750_Firefox Beta](https://user-images.githubusercontent.com/24588037/65599315-42cff180-dfa6-11e9-97fb-5b8264eac251.jpg)

**Comment by davismtl** [comment]
This is related to where we discuss making email-first the default flow everywhere: 
https://github.com/mozilla/fxa/issues/639

**Comment by clouserw** [comment]
As @davismtl mentions, this will be fixed when the email first flow is required across all relying parties.
