### ISSUE TITLE
[Standardize all flows] Setting the device to an RTL language doesn't display the new UI

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2607]
Environment:
- Google Pixel (Android Q)
- Nexus 5 (Android 6.0.1)
- Stage server 

Prerequisites:
- Android language is set to ar, fa, he (RTL). 

**Steps to reproduce:**
1. Go to Menu -> Sign In -> Create a new account.

 **Expected result:**
The text is translated into the RTL language and the new UI is displayed.

**Actual result:**
The new UI is not displayed. 

![Screenshot_20190925-161828](https://user-images.githubusercontent.com/24588037/65604523-4b2d2a00-dfb0-11e9-85bf-6e7e9bdfc624.png)

**Comment by davismtl** [comment]
This is also related to where we discuss making email-first the default flow everywhere:
#639

**Comment by clouserw** [comment]
The UI shown is due to the action=signin parameter in the URL.  If the relying party changes to action=email it will show the newer UI.  The standardizing flows Epic was about eliminating the trailhead-specific designs.  Migrating all relying parties to the email flow is a different issue.
