### ISSUE TITLE
verification error loading chunk 23 failed [bz1582748]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2609]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1582748

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

Steps to reproduce:

created sign in on firefox monitor, which sent verification email.

Actual results:

Clicking on link in verification email returned error : 
Loading chunk 23 failed. (missing: https://accounts-static.cdn.mozilla.net/bundle-04f47a3c381ca922dec07498e92c29bb5b5eba13/vendors~fxaClient.bundle.js)

Expected results:

verification should have happened.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-375)
┆Issue Number: FXA-375

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
