### ISSUE TITLE
Unable to load Manage subscriptions on old version of FF

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#2611]
This was filed over in the guardian website repo by @rbillings. I'm pretty sure Firefox 43 isn't officially supported but she makes a good point about having messaging around it.

> Testing on FF 43.0.1 on Windows Vista I was able to sign into FxA and can manage my account - however the manage subscriptions page never loads.
> 
>  If there is a limitation on which versions of Firefox we support there should be messaging.
> 
> URL of page that won't load:
> https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions#accessToken=XXX
> 
> <img width="734" alt="Screen Shot 2019-09-24 at 1 23 03 PM" src="https://user-images.githubusercontent.com/737878/65547554-88b98680-dece-11e9-8a05-f87dcbbbca89.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-376)
┆Issue Number: FXA-376

**Comment by clouserw** [comment]
Are there any errors in the console?

From triage:  It would be nice to have a better experience than this, but this is going to be a low priority.

**Comment by rbillings** [comment]
Strict-Transport-Security: The site specified a header that could not
be parsed successfully.[Learn More] subscriptions
Strict-Transport-Security: The site specified a header that could not
be parsed successfully.[Learn More] runtime~main.a6f6bf86.js
Strict-Transport-Security: The site specified a header that could not
be parsed successfully.[Learn More] main.deb2a8e6.chunk.js
Strict-Transport-Security: The site specified a header that could not
be parsed successfully.[Learn More] main.341dc825.chunk.css
mutating the [[Prototype]] of an object will cause your code to run
very slowly; instead create the object with the correct initial
[[Prototype]] value using Object.create v3:1:1053
Strict-Transport-Security: The site specified a header that could not
be parsed successfully.[Learn More] 2.22f3c2b0.chunk.js
init error TypeError: Object.entries is not a function
Stack trace:
e@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:20062
s@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:20041
u@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:19819
e/<@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:24743
c@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:73119
l/i._invoke</<@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:72909
E/</e[t]@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:73538
r@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:3879
u@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:4085
o/</<@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:4144
o/<@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/2.22f3c2b0.chunk.js:1:4026
T@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:24624
[93]/<@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:26895
[93]@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:26877
i@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/runtime~main.a6f6bf86.js:1:564
[70]@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:20251
i@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/runtime~main.a6f6bf86.js:1:564
r@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/runtime~main.a6f6bf86.js:1:430
t@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/runtime~main.a6f6bf86.js:1:293
@https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/static/js/main.deb2a8e6.chunk.js:1:2
 main.deb2a8e6.chunk.js:1:26994
Strict-Transport-Security: The site specified a header that could not
be parsed successfully.[Learn More] mozilla.c86df1d3.svg
calling a builtin ArrayBuffer constructor without new is deprecated
and will be forbidden in ES6

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Browser support is defined at https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-dev-process#browser-support and, as suspected, 4 3 is way too old.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

x
