### ISSUE TITLE
FxA Accounts page has no ability to return to the website

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#2612]
This was filed over in the guardian website repo by @rbillings. Is there anything we can do to smoothen out this experience? If we send users over to FxA/settings, it's basically a dead end.

> After logging in to FxA on the Guardian website, if a user goes to the Manage Account or Manage Subscription page there is no way to return to the website - and clicking the back button refreshes FxA but does not return to the website.

> Correction, I was able to get back to the site using the back button. It would still be nice to have a direct link or way to return to the website.

**Comment by lmorchard** [comment]
Not really sure how we would address this... FxA has multiple RPs, so it's hard to tell what site to go back to depending on how you got to the account management page.

**Comment by clouserw** [comment]
The expectation would be that going to the FxA/Settings page would open in a new tab, so going back would be closing the tab.
