### ISSUE TITLE
'unlink' support missing from redis library

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#2623]
The `redis` library is old enough that the redis background delete command, UNLINK, is not supported. We'll need this command to remove clients without blocking for O(N) time, where N is the number of client tokens.

Related to #2559?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-377)
┆Issue Number: FXA-377

**Comment by dannycoates** [comment]
> UNLINK, is not supported

is that the case or just undocumented? last time i looked (years ago) the commands were dynamically generated. the readme also suggests we could diy it with [send_command](https://github.com/NodeRedis/node_redis#clientsend_commandcommand_name-args-callback) _or  maybe_ `add_command`

fwiw I'm trying out ioredis right now, but maybe mixing lib update with a big app change isn't the best idea 😬

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we don't need this
