### ISSUE TITLE
OAuth authorization codes for 123done expire immediately when using MySQL backend

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2626]
STR

1. Start the servers using `./pm2 start mysql_server.json`
2. Go to `http://127.0.0.1:8080`, sign in.
3. When returning to 123done, an error is displayed: 

> name	"JWTVerificationError"
> message	"malformed"

**Comment by dannycoates** [comment]
WFM. I can't reproduce

**Comment by shane-tomlinson** [comment]
This still reproduces for me, re-opening until I figure out the problem.

**Comment by shane-tomlinson** [comment]
I cleared all of the databases in MySQL, went to master, tried @dannycoates new PR. All with the same result. Perhaps I need to re-install dependencies, I'll try that now.

**Comment by shane-tomlinson** [comment]
If I look in the logs, I keep getting an "Expired code" error when trading the code for a token:

<img width="973" alt="Screenshot 2019-10-01 at 11 25 55" src="https://user-images.githubusercontent.com/848085/65954728-798e8780-e43e-11e9-9e66-d464decb880c.png">

Updating the title to reflect that.

**Comment by shane-tomlinson** [comment]
Applying this patch:

```diff
diff --git a/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js b/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js
index ac0de3ea7..9f71f3f7f 100644
--- a/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js
+++ b/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js
@@ -250,8 +250,17 @@ async function validateAuthorizationCodeGrant(client, params) {
   // Has it expired?
   // The + is because loldatemath; without it, it does string concat.
   const expiresAt = +codeObj.createdAt + config.get('expiration.code');
+  const expiresAtDate = new Date();
+  expiresAtDate.setTime(expiresAt);
+  const nowDate = new Date();
   if (Date.now() > expiresAt) {
-    logger.debug('code.expired', { code: code });
+    logger.debug('code.expired', {
+      code: code,
+      createdAt: codeObj.createdAt,
+      expiresAt: expiresAtDate.toISOString(),
+      nowDate: nowDate.toISOString(),
+      ttl: config.get('expiration.code')
+    });
     throw AppError.expiredCode(code, expiresAt);
   }
   // If it used PKCE...
```

I get a little more information:

<img width="971" alt="Screenshot 2019-10-01 at 11 36 15" src="https://user-images.githubusercontent.com/848085/65955288-b6a74980-e43f-11e9-82d9-cc6289caf8fd.png">


```json
{
  "code":"6a971a044a73140a7c4a618a4dc2f8f9e91118780a88eef862e909f55992ed8c",
  "createdAt":"2019-10-01T09:34:40.000Z",
  "expiresAt":"2019-10-01T09:49:40.000Z",
  "nowDate":"2019-10-01T10:34:40.681Z",
  "ttl":900000
}
```

The `createdAt` date is an hour in the past, and since OAuth codes are only valid for 15 minutes the code is considered expired.

**Comment by shane-tomlinson** [comment]
To make matters more confusing, the mydb docker image knows the correct date:

<img width="577" alt="Screenshot 2019-10-01 at 11 41 51" src="https://user-images.githubusercontent.com/848085/65955647-88763980-e440-11e9-901b-da3647fc25b7.png">

**Comment by shane-tomlinson** [comment]
When codes are created, the timestamp is [generated by the database](https://github.com/mozilla/fxa/blob/7a14b1f65a7511d001ef33f4b74f47b9f11435a6/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/patches/patch-001-002.sql#L28):

> createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

When I query MySQL for it's current timestamp, it's right too:

<img width="392" alt="Screenshot 2019-10-01 at 11 46 57" src="https://user-images.githubusercontent.com/848085/65956006-4dc0d100-e441-11e9-9eed-2f4e3c33322f.png">

**Comment by shane-tomlinson** [comment]
I figured out the problem looking at the internals of the `mysql` dependency to see how it creates dates.

If I add some logging to where the [mysql dep](https://github.com/mysqljs/mysql/blob/e16c52da980e46012a391232be884b797b8af070/lib/protocol/packets/RowDataPacket.js#L82) converts strings to dates, I see this:

```
originalString 2019-10-01 13:29:13
dateString 2019-10-01 13:29:13
converted 2019-10-01T12:29:13.000Z
```

No timezone is passed in as config, so the [default is local time](https://github.com/mysqljs/mysql/blob/e16c52da980e46012a391232be884b797b8af070/lib/protocol/packets/RowDataPacket.js#L78).

Since I am one hour ahead of UTC right now, `2019-10-01 13:29:13` does equal `2019-10-01T12:29:13.000Z`. 

This is wrong though, `2019-10-01 13:29:13` is already in UTC time. A [MySQL CURRENT_TIMESTAMP (alias for now()](https://dev.mysql.com/doc/refman/5.6/en/date-and-time-functions.html#function_now) is expressed in the "session time zone", I assume meaning the local time as seen on the server that hosts MySQL. The MySQL docker container is in UTC, so the time being written to the DB is in UTC.

The OAuth server code get's the time that is already in UTC and assumes it's in local time, local time on my box is BST, UTC + 1. The mysql dep believes the time is a "UTC + 1" and converts the time to an hour in the past.

This can be fixed though, the mysql connection accepts a [timezone option](https://github.com/mysqljs/mysql#connection-options), which is listed as:

> timezone: The timezone configured on the MySQL server. This is used to type cast server date/time values to JavaScript Date object and vice versa. This can be 'local', 'Z', or an offset in the form +HH:MM or -HH:MM. (Default: 'local')

If I create a new config option that sets the timezone of the MySQL connection, all is well with the world:

```diff
diff --git a/packages/fxa-auth-server/fxa-oauth-server/lib/config.js b/packages/fxa-auth-server/fxa-oauth-server/lib/config.js
index 45fcbf55b..41ed9566a 100644
--- a/packages/fxa-auth-server/fxa-oauth-server/lib/config.js
+++ b/packages/fxa-auth-server/fxa-oauth-server/lib/config.js
@@ -239,6 +239,11 @@ const conf = convict({
       default: 10,
       env: 'MYSQL_CONNECTION_LIMIT',
     },
+    timezone: {
+      doc: 'The timezone configured on the MySQL server. This is used to type cast server date/time values to JavaScript `Date` object and vice versa.',
+      default: 'Z',
+      env: 'MYSQL_TIMEZONE'
+    }
   },
   openid: {
     // See ../docs/signing-key-management.md to read more about what these different keys are for.
```

**Comment by shane-tomlinson** [comment]
@jrgm and @jbuck - are the system clocks on the production servers set to UTC or some other timezone?
