### ISSUE TITLE
Document how to use feature flags

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2628]
I found this super old note that Phil was going to write some docs about the feature flags.  Do you have a link to those?  I'll pull them into our ecosystem docs.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-378)
┆Issue Number: FXA-378

**Comment by philbooth** [comment]
@clouserw, are these sufficient?

https://github.com/mozilla/fxa/blob/master/packages/fxa-shared/feature-flags/README.md

Let me know if you think they're missing anything and I'll add...

**Comment by vbudhram** [comment]
We have more docs on this at https://github.com/mozilla/ecosystem-platform/blob/master/docs/fxa-engineering/fxa-content-server-ab-testing.md
