### ISSUE TITLE
Export amplitude events from Sync telemetry into S3

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#263]
As part of our amplitude integration, we want to correlate sync-related events (such as sent tabs and successful syncs) with future activity as an FxA user. To do this we'll need to synthesize the events named "sync - *" from this event taxonomy spreadsheet:

https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055

Rough plan is to:

* Write some sort of sync telemetry job that finds these events and exports them into a bucket in S3
* Have our own periodic job that picks up these dumps, reformats them into the format expected by amplitude, does ID anonymization etc, and puts them in a separate location in S3.
* Pick up the formatted files from S3 and publish them to amplitude via HTTP API.

**Comment by rfk** [comment]
(We'll almost certainly need someone from the sync team to help us with the telemetry events).

**Comment by philbooth** [comment]
There was no work for in this issue, it already existed. Closing.
