### ISSUE TITLE
Investigate Swagger for our API docs

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2630]
This came out of old retrospective notes.  We were supposed to investigate adding this, and if we liked it, to add it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4589)

**Comment by meandavejustice** [comment]
- [ ] 123done (express)
- [ ] browserid-verifier (express)
- [ ] fortress (express)
- [ ] fxa-auth-db-mysql (restify)
- [ ] fxa-auth-server (hapi)
- [ ] fxa-content-server (express)
- [ ] fxa-customs-server (restify)
- [ ] fxa-event-broker (hapi)
- [ ] fxa-payments-server (express)
- [ ] fxa-profile-server (hapi)
- [ ] fxa-support-panel (hapi)

https://github.com/glennjones/hapi-swagger
https://github.com/fliptoo/swagger-express

**Comment by meandavejustice** [comment]
Update from Cleanup meeting discussion:

We think swagger could be useful for onboarding team members and contributors, also could be helpful for larger refactors we may run into in the future.

For now I'm going to implement a route or two on the auth-server and demo it at the next cleanup meeting (October 31st)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

At this point we should aim for GQL and nestjs auto-documentation

**Comment by clouserw** [comment]
Re-opening now that we have public APIs

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
