### ISSUE TITLE
Make architecture diagrams

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2633]
We'd like to make some new architecture diagrams since things are evolving (eg. redis).  When we do, let's ensure that the packages link to the appropriate diagrams/documentation in their READMEs.

**Comment by clouserw** [comment]
https://gitlab.com/shane-tomlinson/mermaid-charts/tree/master/charts

**Comment by shane-tomlinson** [comment]
> https://gitlab.com/shane-tomlinson/mermaid-charts/tree/master/charts

We should move these into mozilla owned repos or docs.

**Comment by clouserw** [comment]
I was just linking them there so I could close the tab. :)  

This is kind of blocked by https://github.com/mozilla/ecosystem-platform/issues/10 -- we could do it without, but it wouldn't be as smooth.
