### ISSUE TITLE
Publish events from daily S3 dumps to the amplitude HTTP API

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#264]
Once #262 and #263 land, we'll need something that periodically picks up new event log dumps from S3, and publishes them to amplitude via its HTTP API.  We'll have to talk to ops about what this infrastructure should look like in practice, e.g. maybe it makes sense to use some fancy new AWS pipeline tooling, or maybe we just do this as a cronjob on an admin box somewhere.

**Comment by vladikoff** [comment]
from mtg: waiting on events

**Comment by vladikoff** [comment]
@philbooth to maybe close this, meta bug!
