### ISSUE TITLE
oauth server should back off if the DB is gone

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#2640]
When trying to recover from recent DB outage, ops ran into issues where the oauth server had queued up a lot of traffic. Would be good if the server would detect DB slowness and gracefully shed traffic in such cases, and not continue hammering the DB at full force.

@jbuck feel free to correct this description if I've misunderstood what was happening

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-381)
┆Issue Number: FXA-381

**Comment by jbuck** [comment]
@6a68 that's correct. We'd specifically see lots of messages emitted by https://github.com/mozilla/fxa/blob/28cc9035ded8c6deaa9c9cea0affac3b60503623/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/index.js#L44

Looking at the docs, the easiest fix here might be setting the `queueLimit` to something non-zero: https://www.npmjs.com/package/mysql#pool-options

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is this still an issue since we are using redis now?

**Comment by jbuck** [comment]
We're using redis to store access tokens but the oauth server still uses MySQL for some other tokens. I'd like to add the queueLimit (and any other options that'd help) to prevent a unbounded build-up of queries
