### ISSUE TITLE
Deploy boomerang signup codes to 100% sync users

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#2642]
From mtg: Lets deploy this to 100%. This is aimed as a point release for train-146

**Comment by sv-sdeiac** [comment]
Hello, I tested the train-147 and I found that the boomerang sign-up codes are not displayed on Desktop (Windows 10 x64) and Android (Google Pixel with Android Q and Google Pixel with Android 9) sometimes. Is the boomerang feature deployed 100% or there should be those differences? 
Notes:
- On iPhone SE (12.1.4) I can't reproduce this problem, the verification code page is displayed all times when I create a new account.

**Comment by SorinaFlorean** [comment]
@vbudhram we still encounter issues while we create a new account on production and don't get verification codes.

**Comment by vbudhram** [comment]
@SorinaFlorean Is this with Sync users?
