### ISSUE TITLE
Expose endpoint for getting hashed_fxa_uid [bz1584356]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#2644]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1584356

This is used to hash certain things in telemetry, such as device IDs.

Right now this is provided by the token server, however after the sync/fxa decouple, non-sync users won't have this.

We could still get a token for them just to get this value, but doing so seems dodgy. rfkelly suggested at one point that a good way to do this would be an endpoint that returned it from FxA.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-382)
┆Issue Number: FXA-382

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bz
