### ISSUE TITLE
"Contact support" button missing from "Subscriptions" page on smaller screen resolution

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#2646]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Prerequisites:
- The user is successfully subscribed.
- The display is set to a resolution of 1280x720 pixels or lower.

#### Steps to reproduce
1. Go to [Subscriptions](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions) page.
2. Observe the page.

#### Expected result:
The "Subscriptions settings" is displayed in the middle of the page and the "Contact Support" button is available.

#### Actual result:
 - The "Subscriptions settings" is displayed on the left side of the page in a compacted format without the "Subscriptions" section and the "Contact Support" button.

#### Notes:
-The same result is with higher resolution but with a reduced window size.

![Screenshot 2019-09-27 at 14 29 22](https://user-images.githubusercontent.com/48829350/65766595-21047500-e134-11e9-9169-6462eb95cf36.png)

![1](https://user-images.githubusercontent.com/48829350/65766601-2792ec80-e134-11e9-9436-94e358e9de95.gif)

**Comment by LZoog** [comment]
@SoftVision-LorandJanos I cannot reproduce this locally or on stage. This page also looks a tad different currently than what you've got on your screenshot.

There's a piece of code [here](https://github.com/mozilla/fxa/commit/4ed4d39e3f7008b75fed1a7eaa2113d11ac32a1c#diff-a1e9d2d465bb9143570649cc6efa55b2L4) that would have had hidden this section in mobile, but that was merged in #2322, fixing #1832. I copied and pasted some of that CSS back locally and can reproduce.

I know you just created this issue 3 days ago, but will you confirm this is still an issue on the current stage? Here's what I did...
1) Registered a new account on https://payments-stage.fxa.nonprod.cloudops.mozgcp.net
2) Subscribed via https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_FUUNYnlDso7FeB
3) Visited https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions and shrank the screen

Tested on Firefox Nightly 71.0a1 and Firefox Release 69.0.1 on MacOS 10.14.6

Stage screenshot: 
![image](https://user-images.githubusercontent.com/13018240/65903353-eb54cb80-e381-11e9-821f-095652e520f2.png)

**Comment by SoftVision-LorandJanos** [comment]
@LZoog I've rechecked it today, and yes, it seems to be fixed. I will close this issue.
