### ISSUE TITLE
Add small feature doc for disabledButtonState experiment

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#265]

**Comment by shane-tomlinson** [comment]
@vladikoff - can you triage this appropriately?

**Comment by vladikoff** [comment]
@davismtl has a google doc with this 👍

**Comment by davismtl** [comment]
Here: https://docs.google.com/document/d/1-40YKqjl91OFSUpNVeeCVQzB_SZovr6h6J__FZUNSYE/edit#heading=h.qrbb2drvq5dg

**Comment by vladikoff** [comment]
Thanks @davismtl !!
