### ISSUE TITLE
Connect to SubHub prod environment

### ISSUE THREAD

**Issue by marty331** [mozilla/fxa#2651]
SubHub prod has been deployed to allow for connections to be complete.  @jrgm has been sent URL and creds.

**Comment by jrgm** [comment]
Commited credentials to sops.

Url is unchanged from previous config. Does that sound correct?

**Comment by marty331** [comment]
URL is unique for prod as it is with other environments. Slack message sent.

**Comment by clouserw** [comment]
This is done
