### ISSUE TITLE
Add small feature doc for confirm password experiment

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#266]
from morning notes: Add small feature doc for confirm password experiment

cc @seanmonstar

**Comment by seanmonstar** [comment]
I probably won't get this to this soon, cramming on push 2FA.

**Comment by rfk** [comment]
from product meeting, @davismtl is going to pick up this to start.

**Comment by davismtl** [comment]
I'm making it here: https://docs.google.com/document/d/1NfpKU4CjHshL463qrDyLlgiZn_ChbWz2cPptIe4H_1Y/edit#

@seanmonstar I left a comment for you to just add a screenshot to the document of the treatment.

Closing this issue.
