### ISSUE TITLE
Set up an instance of FxA that points to subhub-QA

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2661]
Please configure an instance of FxA that points to subhub-QA.  This is a proactive environment for the situation where we would need to test changes in subhub from fxa development code under time constraints.

It seems like this might be a good case to use https://github.com/mozilla/fxa-dev/ but I don't know enough about it to say for sure.

/cc @jrgm

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-385)
┆Issue Number: FXA-385

**Comment by marty331** [comment]
SubHub needs an instance to be able to validate end to end testing in our QA environment to test features/enhancements/bug fixes prior to rolling out to prod or prod-test.  Our current state leaves us to doing the final test in prod or prod-test before we can do full end to end testing.

**Comment by habib** [comment]
How often will this QA environment be used? When it is in use, what would be the duration of the QA tests?

**Comment by marty331** [comment]
Since we have not launched yet I don't have an accurate response.  I would expect traffic to be light.

**Comment by clouserw** [comment]
Long term:  SubHub will focus on versioning their API 

Short term:  We'll connect fxa-stable to subhub-qa
