### ISSUE TITLE
Deploy Telegraf to Collect FxA StatsD Metrics

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2665]
The event broker and the auth server has started using `hot-shots` to send StatsD metrics.  However, we need telegraf instance(s?) to collect said metrics.

Part of #997

**Comment by chenba** [comment]
@jbuck and/or @jrgm Is this something in your domain?

**Comment by chenba** [comment]
This is specifically for the auth server.

**Comment by jrgm** [comment]
Statsd metrics are available for stage now at https://hillvalley-b40313e5.influxcloud.net, svcops.autogen for event-broker, and svcops_aws.autogen for auth. Please have a look and let me know if something doesn't seem right. (An issue and PR has been filed for event-broker prefix).

**Comment by chenba** [comment]
@jrgm Thanks!  I do see some data.  Given that it's on a testing env and it's sampled at a 10% rate, it looks about right.

**Comment by chenba** [comment]
@jrgm Query for the same data in Grafana (https://earthangel-b40313e5.influxcloud.net/) doesn't return anything.  But I'm not sure if I'm doing something wrong.  Could you verify?

**Comment by jrgm** [comment]
@chenba - I just made this graph of customs check counts - https://earthangel-b40313e5.influxcloud.net/d/HqOQKXoZk/fxa-auth-prod-elb?orgId=1&refresh=5s&from=now-24h&to=now&fullscreen&panelId=12

Maybe you had the datasource as svcops instead of svcops_aws?

**Comment by jrgm** [comment]
I also started tests, so you'll notice the custom check counts have gone from sporadic to a regular, and scaled up to 3 auth servers to get a little more variety in the data.

**Comment by chenba** [comment]
👍 Excellent.  I was in svcops_aws, querying on one of the sqs stats, but I think my query was probably wrong.  Thanks!

**Comment by clouserw** [comment]
Sounds like this is done.  Thanks everyone!
