### ISSUE TITLE
How to setup NGINX?

### ISSUE THREAD

**Issue by OhDaeto** [mozilla/fxa#2669]
Hello. I want to make the registration web page public.

After setting "public_url" (the service was installed at https://fxa.r208.org/ ) in packages/fxa-content-server/server/config/local.json the registration process is work but canceled by an unknown error

All logs in 1 archive: https://cloud.r208.org/s/k52Mowz6oWx3sY5

Nginx conf:
```
server {
    listen 80;
    listen [::]:80;
    server_name fxa.r208.org;
    # enforce https
    return 301 https://$server_name:443$request_uri;
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name fxa.r208.org;
    ssl_certificate /etc/letsencrypt/live/cloud.r208.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cloud.r208.org/privkey.pem; # managed by Certbot


    location / {
        proxy_pass http://localhost:3030;
    }

}
```

**Comment by clouserw** [comment]
Hi @OhDaeto .  Thanks for filing the bug.  Our code is open source and we try to keep docs relevant, however, we're unable to chase after unknown errors on other systems.  Sorry we can't be more helpful.

**Comment by OhDaeto** [comment]
Thank you for this honest answer
