### ISSUE TITLE
Links and check-boxes remain selected after clicking on them

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2671]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Precondition
Have the payment screen opened.

#### Steps to reproduce
1. Click on any of the following:
      - Check-box
      - Terms of Service
      - Privacy Notice
      - Stripe privacy policy

#### Expected result:
- There is no selection border present after clicking on any of the items/links.

#### Actual result:
- A persistent selection border is present after clicking on any of the items/links.

![picturemessage_s43hleoi ld0](https://user-images.githubusercontent.com/17178945/65963639-dcdee080-e463-11e9-95b7-358f66d8566c.png)

**Comment by meandavejustice** [comment]
This is our focus style being activated. I think this is intentional. cc/ @johngruen
