### ISSUE TITLE
Open stripe privacy policy in new tab

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2672]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Precondition
Have the payment screen opened.

#### Steps to reproduce
1. Fill in all of your billing information.
2. Click on the "Stripe privacy policy" link.
3. Go back to the payment page.

#### Expected result:
2. The [stripe privacy policy](https://stripe.com/privacy) is opened in a new tab.
3. All of the billing information is still available.

#### Actual result:
2. The [stripe privacy policy](https://stripe.com/privacy) is opened in the same tab.
3. All of the filled-in billing information is lost.

#### Notes:
As to avoid having the user fill in all of his details again we could either keep track of what was filled in the fields or open the privacy policy in a new tab avoiding having to make the user fill in all of his billing information again.

![2](https://user-images.githubusercontent.com/17178945/65962523-8e304700-e461-11e9-8b66-553900462bdd.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-387)
┆Issue Number: FXA-387

**Comment by LZoog** [comment]
It looks like this has been fixed for at least 3 months. See `target="_blank"` on the Stripe link here: https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/components/PaymentLegalBlurb/index.tsx#L17

I verified this link opens in a new window in dev & in stage.
