### ISSUE TITLE
Subscription mails are received with big delays or not received at all 

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#2673]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Steps to reproduce
1. Make a Guardian VPN subscription.

#### Expected result:
- A subscription confirmation mail is sent.

#### Actual result:
- A subscription confirmation mail is not sent or is received at times with huge delays.

#### Notes:
- The same issue is valid for any type of mail when managing a subscription.
- Maybe related to #2657?

**Comment by clouserw** [comment]
Thanks for filing @bsurd .  Can you be specific about what email you're talking about here?  A screenshot would be great.

If it looks like https://github.com/mozilla/fxa/issues/927#issuecomment-512991375 we should look at it.  If it's a salesforce email we should move this to subhub.

**Comment by bsurd** [comment]
I'm not sure of the exact mail but I've used my mozilla email address while testing so anything from bsurd+test5@mozilla.com to bsurd+test12@mozilla.com. 

Altho testing today everything seems to work out as expected so closing this as it no longer seems to be reproducible.

If we encounter any new issues related to this we will file a new bug for those.
