### ISSUE TITLE
[Support] Track support form request originating region

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2675]
For use by support agents, we should send in a field to Zendesk that contains the users originating IP. This can be used later depending on the support request to verify the user is accessing our service from the same location they typically do.

This may require our Support team to setup a new field to store this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-388)
┆Priority: Medium
┆Issue Number: FXA-388

**Comment by chenba** [comment]
@jackiemunroe You said you can add a new field on Zendesk?  Can you add a `location`?

**Comment by jackiemunroe** [comment]
@bbangert would we want this data added to the user object or the ticket object in Zendesk?

**Comment by bbangert** [comment]
The ticket object. Can we do a nested field? There's a few location fields, and I'm not sure if its going to look good to smush it together in a single field vs. using a few fields for Country/State/etc.

**Comment by chenba** [comment]
> Can we do a nested field?

Isn't the `requester` field a nested field?

> There's a few location fields, and I'm not sure if its going to look good to smush it together in a single field vs. using a few fields for Country/State/etc.

Could format it into a "City, State, Country" if that's preferable.

**Comment by jackiemunroe** [comment]
> > Can we do a nested field?
> 
> Isn't the `requester` field a nested field?
No. The `requester`data that is being sent actually creates a mapping to a User object in Zendesk.
@bbangert To answer your question: Zendesk does not have a concept of nested attributes - but we can organize them in the Agent's view such that they appear next to one another.

> > There's a few location fields, and I'm not sure if its going to look good to smush it together in a single field vs. using a few fields for Country/State/etc.
> 
> Could format it into a "City, State, Country" if that's preferable.
It is simple enough to create a new Text form field for each of these and add them to the Form object.

Just let me know what Text fields we want, and I can get them configured :)

**Comment by chenba** [comment]
> It is simple enough to create a new Text form field for each of these and add them to the Form object.
>
> Just let me know what Text fields we want, and I can get them configured :)

@jackiemunroe Sorry, I'm not familiar with Zendesk, so I want to confirm that I'm parsing correctly.  If we send a support request with a `location` in it that's shaped `{city: string, state: string: country: string}`, you can map those three properties into three "Text form fields" in the "Form object"?  The form object is what's displayed to support agents?  What would happen if the `location` object has additional properties on them (say, "countryCode" or "stateCode")?

If there's reference you can link to, please do that instead typing out answers. :)

**Comment by jackiemunroe** [comment]
I sent @chenba internal documentation for reference on Zendesk usage.

The new fields have been created in Zendesk and mapped to the appropriate form. Since these are custom fields, to populate the value we will need to use the field id.

Field Name | Field ID
------------ | -------------
City | 360026463311
State | 360026463491
Country | 360026463511

Example:
```...,
"custom_fields": [
  {
    "id": 360026463311,
    "value": "Los Angeles"
  },
  {
    "id": 360026463491,
    "value": "California"
  },
  {
    "id": 360026463511,
    "value": "United States"
  }
]
