### ISSUE TITLE
[Support] Display IP/Geo-region of prior service access for a user

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2677]
For verification by support agents, our support-panel should display the services a user has accessed, and their IP/geo-region of access based on the oauth tokens issued.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-389)
┆Issue Number: FXA-389

**Comment by bbangert** [comment]
@shane-tomlinson I assume we store the IP already for issued tokens, I'm not sure support will find IP comparisons very useful though, do we have a geo-service in FxA we use so we can display a region as well?

**Comment by shane-tomlinson** [comment]
> I assume we store the IP already for issued tokens

We do not store this info for OAuth tokens, only for Session tokens.

> do we have a geo-service in FxA we use so we can display a region as well?

Yes, we use https://www.maxmind.com/en/geolite2-developer-package

**Comment by bbangert** [comment]
Note that we actually store geo information in Redis for session tokens, which is likely where this information will need to come from:
https://github.com/mozilla/fxa/blob/d91e1beb07da902a1c6797188cee0b88f5a22afe/packages/fxa-auth-server/lib/db.js#L613-L658

**Comment by chenba** [comment]
Since the location data is stored in Redis, that puts us in a pickle.  The most direct and simple thing to do here is for support-panel to get read access to Redis.

@jbuck @jrgm can the support panel have read access to Redis?  Any risks?

**Comment by jbuck** [comment]
> @jbuck @jrgm can the support panel have read access to Redis? Any risks?

The support panel currently has read-only access to specific tables on the mysql database. If we grant network access to the Redis instance, there is no access control to make it read-only, it's read/write everything. I'm not sure what the consequences of allowing write access to the Redis instance are, could someone create sessionTokens or are they looked up in the database too?

Let's loop in secops before we do this

/cc @jvehent

**Comment by chenba** [comment]
The Redis token data is merged into those from MySQL when there's a token id match: https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/db.js#L332

**Comment by rfk** [comment]
> I'm not sure what the consequences of allowing write access to the Redis instance are

Even if there aren't any bad consequences right now, I can imagine us adding more consequences in future without necessarily remembering that the support panel has this access. I worry it would be a future security footgun.

**Comment by chenba** [comment]
> Even if there aren't any bad consequences right now, I can imagine us adding more consequences in future ...

Very true.  There's already talk of moving oauth tokens into Redis.

**Comment by jbuck** [comment]
In production we have two Redis instances (one primary, one replica) for higher availability and failover. According to [the docs](https://redis.io/topics/replication),  replica-read-only means that you can only read from the replica and writes are rejected. I will test this out.

**Comment by jbuck** [comment]
So, the good news is that if you try to modify the replica, you get denied:

```
> set foo bar
(error) READONLY You can't write against a read only slave.
```

The bad news is that the primary and replica share the same security group, so if:

1) Someone gained access to the support panel
2) Gained access to the config, to view the replica URL
3) Connect to the primary based on the replica URL

They could muck with the redis info.

Anyways, lets chat with secops before we merge this patch, but I think it's okay to continue developing it.

**Comment by chenba** [comment]
The session token metadata in Redis are only for session tokens that Sync clients used to access https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#post-certificatesign.  That's not particularly helpful for this issue.  I think storing metadata for more session tokens in Redis warrants additional discussion, especially if we are going to do it _only_ for this issue.

**Comment by chenba** [comment]
@bbangert to answer your question regarding connecting another device: yes, that does create a meta data entry in Redis since that is part of Sync.

If a user only sign in through RPs, then they won't have any session token meta data.  I can imagine someone who'd opt into Monitor and a subscription but not Sync.

**Comment by chenba** [comment]
I'll continue with this as originally planned.  Nothing blocks us from reading from Redis at this point.  (Unless secops think it's a bad idea of course.)  I'll file two follow-ups:

1. Add/update meta data in Redis for session tokens used to get oauth tokens.
1. Remove the JS Redis meta data packing/unpacking code once they are in Lua.

**Comment by jbuck** [comment]
@jvehent Could someone from secops weigh in on the proposed change for allowing the support panel to access Redis?

**Comment by clouserw** [comment]
@arroway are you able to give input here?

**Comment by arroway** [comment]
Granting read access to the whole database, as well as the possibility of an attacker gaining write access is worrying. Especially if OAuth tokens are going to be stored in that database in a foreseeable future.

Basically, we should avoid to expose session tokens and OAuth tokens as much as possible.
We have a few mechanisms to protect against token replay and token theft, however I wouldn't recommend we expand our attack surface on that matter. 

1) [the obvious question that I'm going to ask anyway] Is this the only way to get IP/geo information for the support panel?
2) Could we store the session token metadata / geo information in a separate read-only replica Redis instance, with a different security group? What would be the cost?

**Comment by chenba** [comment]
> [the obvious question that I'm going to ask anyway] Is this the only way to get IP/geo information for the support panel?

Yes, they are (only) in Redis because MySQL won't be able to handle that volume of writes.

> Could we store the session token metadata / geo information in a separate read-only replica Redis instance, with a different security group? What would be the cost?

@jbuck might be the best to answer that.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

New plan: we could ask auth server to do the query for us since we're already going to be talking to auth server.
