### ISSUE TITLE
Enable locale cak (kaqchikel)

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa#268]
Hello

Our community contributors informed me that they have completed Firefox Accounts and would like to have their language enabled.  

Locale: cak (kaqchikel).

What is the ETA to get this completed?

**Comment by vladikoff** [comment]
@peiying2 I added it to our locale list, it should be around 2 to 3 weeks to get it into production

**Comment by vladikoff** [comment]
@peiying2 it looks like this is not a valid Firefox language (not present in Prefs), how do they manage that?

**Comment by flodolo** [comment]
cak is shipping as an official build for Firefox
https://www.mozilla.org/en-US/firefox/all/?q=Kaqchikel

It's not in languageNames.properties ([this is the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1263437)), but I'm not sure how that affects FxA?

**Comment by vladikoff** [comment]
@flodolo I was trying to test it but couldn't even set the locale. I will try via about:config. Thanks for the response!

**Comment by flodolo** [comment]
Ah, that makes more sense. Setting `intl.accept_languages` to `cak, kaq, es, en-us, en` in about:config would be enough.
