### ISSUE TITLE
Bug while enabling 2FA

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2698]
While enabling 2FA, I tried to take a screenshot of the QR code (but cancelled) which somehow lead the menu collapsing. When I tried to re-open the Two-step authentication menu, this happened:

![image](https://user-images.githubusercontent.com/19537086/66007402-2977eb00-e467-11e9-9e5b-87f6120549a1.png)

When I re-click on enable, I just get a spinner:
![image](https://user-images.githubusercontent.com/19537086/66007412-3b598e00-e467-11e9-8914-729bb8cf24a2.png)

The menu never opens.

Once I refreshed the page, it seems to have worked.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-397)
┆Issue Number: FXA-397

**Comment by davismtl** [comment]
I was able to replicate it over and over again. See this video:
https://drive.google.com/open?id=1dw8NoG8ft3fA2PmVOy9bYJXDp6BTz5Dp

If I try to replicate it with another menu section, it doesn't work. Just happens with 2FA section.

**Comment by davismtl** [comment]
Lastly, I can replicate it without taking a screenshot. All I need to do is hit ESC when the menu is open. It will close the menu and then it bugs outs and I can't re-open it.

**Comment by 6a68** [comment]
This is relevant to my interests

**Comment by 6a68** [comment]
Aha, STR:

1. Click on the 'Enable' 2FA button
2. Hit ESC
3. Click 'Enable' on 2FA button again
4. Button turns into a forever-spinner and an error is logged to the console: `Error: A TOTP token already exists for this account`
5. Reload the page, and the 2FA section of settings is shown in this awkward state:

<img width="692" alt="Screen Shot 2019-10-24 at 1 00 44 PM" src="https://user-images.githubusercontent.com/96396/67520758-51b9ca80-f65e-11e9-932e-397c6f0a73a8.png">

6. After the reload, hit ESC, and the 2FA screen is dismissed, and the button works normally (restarting the setup process)

-----

Also, I can confirm that if I cancel out of 2FA by clicking the 'Cancel' button, the bug isn't triggered.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this is old settings
