### ISSUE TITLE
Regenerating 2FA Recovery Codes Keep Green bar at the top

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2699]
After enabling 2FA, we currently display the recovery codes with a green bar at the top that says "Two-step authentication enabled". Within this context, it makes sense.

However, if you return to it later, that green bar is still displayed. This doesn't make sense anymore since it's out of context.

![image](https://user-images.githubusercontent.com/19537086/66007888-09492b80-e469-11e9-9f7c-aad273c2b2de.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-398)
┆Issue Number: FXA-398

**Comment by ryanfeeley** [comment]
@clouserw Alex is correct. Why would this be assigned to me? Just to check. I'm becoming a bottleneck here.

**Comment by clouserw** [comment]
Maybe to prioritize?  I don't know -- we probably did it in a triage and I didn't write down why.  I'll remove.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this is old settings
