### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#27]
This has been making the rounds on The Internet, but it would probably be a good thing to explicitly add to this repo, and maybe add pointers to the global document from the project repos:

http://todogroup.org/blog/open-code-of-conduct/
http://todogroup.org/opencodeofconduct/

Not sure if we want to copy/pasta the code of conduct and host it in GitHub, or simply add pointers to the todogroup.org site's version (with our name/contact embedded)

[http://todogroup.org/opencodeofconduct/#FirefoxAccounts/conduct@firefox.com](http://todogroup.org/opencodeofconduct/#FirefoxAccounts/conduct@firefox.com)

**Comment by rfk** [comment]
:+1:

We should ensure this aligns with existing Mozilla docs and process though, which may mean importing some Mozilla policy from the wiki rather than adopting a third-party thing wholesale.

**Comment by rfk** [comment]
For example, we should link to this in any such discussion: https://www.mozilla.org/en-US/about/governance/policies/participation/

I'm no expert on these things, are there details we want to add beyond what's covered in the gernal Mozilla policies?  I wouldnt be surprised to hear that there are.

**Comment by shane-tomlinson** [comment]
@shane-tomlinson to ask @gerv if there is a Mozilla-wide policy.

**Comment by gerv** [comment]
https://www.mozilla.org/en-US/about/governance/policies/participation/ is the Mozilla-wide "code of conduct" (although we don't use that name for it); Mozilla-run projects should use that one, which was created after much community discussion, and not adopt any other one.

**Comment by shane-tomlinson** [comment]
Thanks for the super quick response @gerv!
