### ISSUE TITLE
Make connect another device direct-link friendly

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2700]
Most people visit the Connect Another Device screen through authentication, but some will arrive there by a direct link in Sync UI. We should make it more direct-link friendly by removing the auth-specific language, and increasing the size of the illustration (height 128px)

![connect](https://user-images.githubusercontent.com/68213/66008251-8f726b80-e483-11e9-8c31-60c53e274d72.png)

For non SMS region, simply increase the height of the illustration to 128px (too small as shown in current screenshot)
![image](https://user-images.githubusercontent.com/68213/66008387-27705500-e484-11e9-9612-35cebff95ee9.png)

**Comment by clouserw** [comment]
@vladikoff did you volunteer for this or is this a surprise? :)

**Comment by clouserw** [comment]
@vladikoff are you working on this?

**Comment by vladikoff** [comment]
> @vladikoff are you working on this?

sorry, missed this in the fury of notifications. I don't have this in my TODO.

**Comment by vladikoff** [comment]
I can probably take care of it, gonna send a PR...

**Comment by vladikoff** [comment]
PR: https://github.com/mozilla/fxa/pull/3189

**Comment by mirunacurtean** [comment]
Verified under Windows Pro 10 64-bit and macOS Catalina 10.15 on Stage [Train 1.150.2]. 
The Connect to another device screen shows up after the account creation or account sign in and can be directly accessed through the "Connect another Device" option from the Settings toolbar or the FxA panel (after account is signed in)
![Desktop Sign in sms service](https://user-images.githubusercontent.com/53306802/68848278-b5249e80-06d8-11ea-9aa1-3ca5dc36806c.PNG)
While on desktop the phone number field is present, on Android 8.0.0 this is not necessary. 
![Android](https://user-images.githubusercontent.com/53306802/68848440-ffa61b00-06d8-11ea-95bc-8db7f6ec96d7.jpg)
