### ISSUE TITLE
Service name not displayed in Authenticator App when setting up TOTP

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2702]
When I enable TOTP by adding it to an App like Authy, the account name is my email, rather than Firefox. This makes it really easy save it but then have no idea what account or service this is setup for.

If possible, **let's add Firefox before or after the email in the account name so that users are able to quickly find their 2FA codes for FxA.**

![IMG_5050](https://user-images.githubusercontent.com/19537086/66008476-76f65700-e46b-11e9-9330-11e1d0b7938c.jpg)

This might explain why 5% of people surveyed around 2FA lockout said that they accidentally deleted Firefox from their Authenticator app.

![image](https://user-images.githubusercontent.com/19537086/66008558-dd7b7500-e46b-11e9-947c-ad98a0d75a46.png)

**Comment by shane-tomlinson** [comment]
This is a dup of #2090 and only happens in Duo, both Google Authenticator and Authy show the service name.

Closing as a dup.

**Comment by davismtl** [comment]
@shane-tomlinson that was in Authy, not in Duo.
