### ISSUE TITLE
FxA Login and Registration Flows for Decoupling

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2703]
We need to make changes FxA flows for the Sync decoupling.

Let's track that here.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-399)
┆Priority: Medium
┆Issue Number: FXA-399

**Comment by irrationalagent** [comment]
There's some numbers on the sync opt-out step [in this comment](https://github.com/mozilla/fxa/issues/2682#issuecomment-567985514).

**Comment by davismtl** [comment]
This has shipped and we are tracking results in another issue.
