### ISSUE TITLE
email-first: Password field not focused in desktop in signup flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2705]
![no-focus-on-signup-password-screen](https://user-images.githubusercontent.com/848085/66020766-1e14d600-e4e0-11e9-86c8-3ece5f824505.gif)

My understanding is the password field *should* be focused on desktop, and *not* focused on mobile. At least that's how @ryanfeeley and I discussed the behavior in the past.

**Comment by irrationalagent** [comment]
@vbudhram suggests that this may be a cause of a drop in our registration rate as of train 146. I tend to agree - it lines up in time, and we would only expect it to affect desktop, which seems to be the case: https://analytics.amplitude.com/mozilla-corp/chart/jozv8fk

**Comment by shane-tomlinson** [comment]
fixed by #3025, closing.
