### ISSUE TITLE
Automatically update auth-server's schema document

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2706]
The auth-server's schema.md file is horribly out of date: https://github.com/mozilla/fxa/blob/5d709f96d371d51c781d40567cead4f15a70688c/packages/fxa-auth-server/docs/schema.md

What would we want in a schema doc to be useful?

cc @bbangert

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-400)
┆Issue Number: FXA-400

**Comment by shane-tomlinson** [comment]
I personally find the OAuth server's schema.sql more useful: https://github.com/mozilla/fxa/blob/5d709f96d371d51c781d40567cead4f15a70688c/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/schema.sql

**Comment by shane-tomlinson** [comment]
Here's an easy way to create an equivalent to the OAuth server's schema.sql file:

```bash
docker exec -it mydb mysqldump --tables -d fxa| sed 's/\/\*.*//'|sed 's/\-\-.*//' | sed 's/DROP TABLE.*//' | grep -v "^$"
```

**Comment by bbangert** [comment]
I think having a schema.sql like the oauth server would be quite useful.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
