### ISSUE TITLE
Automatically update the oauth server's schema document

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2707]
https://github.com/mozilla/fxa/blob/5d709f96d371d51c781d40567cead4f15a70688c/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/schema.sql is useful to me, but is out of date. Is there a way to ensure this is automatically kept up to date, perhaps via auto-generation?

Goes along with #2706 for the auth-server.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-401)
┆Issue Number: FXA-401

**Comment by shane-tomlinson** [comment]
Here's an easy way to create schema.sql files for the OAuth server:

```bash
docker exec -it mydb mysqldump --tables -d fxa_oauth| sed 's/\/\*.*//'|sed 's/\-\-.*//' | sed 's/DROP TABLE.*//' | grep -v "^$"
```

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is nice to have but isn't on our roadmap
