### ISSUE TITLE
"Last sync over" strings

### ISSUE THREAD

**Issue by sn-o-w** [mozilla/fxa#2708]
> **This issue is related to Romanian localization (perhaps other locales affected)**

Regarding these strings: https://pontoon.mozilla.org/ro/firefox-accounts/LC_MESSAGES/client.po/?search=Last+sync+over

**"Last sync over bla-bla"**

Is it possible to add a replace function + regex rule for the placeholder %(translatedTimeAgo)s?

Something like the following, perhaps?
**`Ultima sincronizare acum peste %(translatedTimeAgo)s.replace(/^acum /g, '')`**

We have to add "**peste**" after "**acum**" for English strings like ".**.. over 3 years ago ...**"

For instance:
> **"last sync [3 years ago]" => "ultima sincronizare [acum 3 ani]"**
> **"last sync over [3 years ago]" => "ultima sincronizare [acum peste 3 ani]"**

Notice the square brackets, text inside those would be an example of placeholder's displayed texts and how they should look (for Romanian, bcuz for English is fine).

We can't change strings for **%(translatedTimeAgo)s** and to remove "**acum**", we would ruin other simple strings like "**last sync 3 years ago**" => "**ultima sincronizare acum 3 ani**". We are forced to some kind of hack, if is it possible, for the cases having "**over**" in it.

The idea behind the above hack is that we insert "acum peste" before the placeholder and even if the placeholder has Romanian string starting with "acum", to remove it. This way we don't have two "**acum**" words in sentence. In English you can put "over" before the placeholder. Unfortunately we kinda need "over" in the middle of the text showed by that placeholder. :(

This is more likely "what we gonna do if there're languages that need word/words inside a placeholder, but everything's fine for English?"

Other way would be to introduce a new placeholder like **%(translatedOverTimeAgo)s** + new strings for this case (like "Last sync %(translatedOverTimeAgo)s").

Hope there will be a way to deal with these problems and sorry of my bad English, quite late in my country.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-402)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16013/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-402

**Comment by shane-tomlinson** [comment]
cc @vladikoff

**Comment by flodolo** [comment]
Drop the "over" part, and put the actual time "20 years ago", instead of "over 10 years ago"? The current sentence seems to kind of "abuse" the value returned by moment.js (I think that's the library used).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We no longer prefix these strings with "Last sync over".  Instead it's just the time value.

!screenshot-1.png|thumbnail!
