### ISSUE TITLE
stable.dev.lcip.org hasn't been updated since April

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#271]
Andrew Williamson reported in IRC that secondary emails are not enabled in stable.dev.lcip.org. After some digging, we saw that stable hasn't been update since April and is still running train-84 code.
I ssh'd into the box and the auth-server hasn't been update since April 12th.

I'm manually running the cron job now to force an update, hoping it doesn't blow up the box.

@jrgm, @jbuck - should this box be migrated to docker?

**Comment by shane-tomlinson** [comment]
Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1393588

**Comment by jrgm** [comment]
fixed sufficiently for now

**Comment by vladikoff** [comment]
Thanks @jrgm !!
