### ISSUE TITLE
Provide stable endpoints that allow test credit cards

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2714]
Similar to how subhub provides prod-test, we should provide a stable endpoint for clients to test their changes that allows test credit cards.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-403)
┆Issue Number: FXA-403

**Comment by lmorchard** [comment]
There isn't an isolated "endpoint" we can provide, per se. I think this calls for a full FxA deployment that points at prod-test and uses a test mode [1] publishable API key from Stripe in the payments-server. Needs test-mode plumbed fully from the frontend UI back through subhub server backend.

[1] https://stripe.com/docs/keys#test-live-modes

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We'll focus on a strategy to use real credit cards
