### ISSUE TITLE
Update Redash Performance Charts

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2716]
https://github.com/mozilla/fxa/pull/2574 removed the 'auth' and 'other' performance metric groups.  We'll need to update the Redash queries and charts accordingly.  Timeline: a couple weeks after 147 prod deploy?

**Comment by clouserw** [comment]
@irrationalagent please review

**Comment by chenba** [comment]
I think we could just copy the existing queries and change the `type` column for each of the view names.

**Comment by chenba** [comment]
I can take this as it is related to #996 anyway.

**Comment by irrationalagent** [comment]
thanks for doing that @chenba if you need some guidance let me know

**Comment by chenba** [comment]
I've updated the dashboard.  I'll create another issue for adding more charts once we have performance metrics in payments server.
