### ISSUE TITLE
Setting section success messages border color should match the background color

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#272]
Setting section success messages border color should match the background color
.settings-success

- border-color is now #12bc00
- but should be #058b00
<img width="598" alt="display name updated" src="https://user-images.githubusercontent.com/17153650/30650072-d6bfdb94-9dd6-11e7-96b2-7ca3396db35c.png">

**Comment by tanya-vedi** [comment]
I would like to work on this issue.

**Comment by vladikoff** [comment]
ok!

**Comment by vladikoff** [comment]
@shikhar-scs @himanish-star @anweshknayak Hey, this is should be an easy bug to fix 😄

**Comment by anweshknayak** [comment]
Will fix this

**Comment by anweshknayak** [comment]
@vladikoff just to be sure it is https://github.com/mozilla/fxa-content-server right?

**Comment by vladikoff** [comment]
@anweshknayak  yeap
