### ISSUE TITLE
Turn session tokens brain dump into an ADR

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#2723]
@pbooth has kindly dumped some history and context around our use of session tokens: https://docs.google.com/document/d/1NOxpl0OBwQjqUrm5aZSqz3BbKUZfF39PSQ9F6BrxmK8/edit#

There's nothing particularly sensitive about this info, and it's critical to developing an understanding of how FxA works, so it seems like it should be cleaned up a bit and moved into an architectural decision record (ADR) in the repo docs.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-404)
┆Issue Number: FXA-404

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Done @ https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-session-tokens
