### ISSUE TITLE
4.2.5 Eliminate 3 current dependencies that can be replaced by other existing dependencies. Ex. restify → hapi

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2725]

**Comment by meandavejustice** [comment]
@shane-tomlinson @dannycoates @6a68 @lmorchard @LZoog @chenba I think this warrants some discussion. There are a couple of lower hanging dependencies which can be consolidated, but we should discuss if we want to switch restify/express servers to hapi. We should create a list in this issue of PROS/CONS of switching, and maybe setup a meeting. Thoughts?

**Comment by davismtl** [comment]
from mtg:
@meandavejustice any updates you might want to share? Should we move this epic to "in progress"?

**Comment by meandavejustice** [comment]
#3290 fulfilled this issue

* `eslint-config-prettier` moved to `eslint-plugin-fxa` package
* `grunt`, `grunt-copyright`, `grunt-eslint` and `load-grunt-tasks` removed from `fxa-auth-db-mysql`
* `eslint-plugin-sorting` removed
* `grunt`, `grunt-eslint`, and `load-grunt-tasks` removed from `fxa-geodb`
* `eslint-plugin-react` removed
