### ISSUE TITLE
4.2.2 Establish TypeScript coverage reporting and increase coverage by 2x overall

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2726]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-405)
┆Priority: Medium
┆Issue Number: FXA-405

**Comment by davismtl** [comment]
The last issue on this list is for train 153.

**Comment by dannycoates** [comment]
This needs to be revised because my assumption on coverage tooling turned out to be false. We still want to grow TypeScript, but the measurement method needs to change. Since 19Q4 is over I think we should close this and re-evaluate our TS strategy.
