### ISSUE TITLE
4.1 Complete P1s and P2s from UX backlog.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2727]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-406)
┆Priority: Medium
┆Issue Number: FXA-406

**Comment by davismtl** [comment]
Going well. Lauren has a few questions for Ryan. They will sync up this week.

**Comment by davismtl** [comment]
It's on track for train 152 but not 151.

**Comment by davismtl** [comment]
No update. Still on track for 152

**Comment by davismtl** [comment]
Looking for feedback on https://github.com/mozilla/fxa/issues/3261

**Comment by LZoog** [comment]
Update: this backlog is my priority for this train. I'm hoping to get most/all of the issues in for 152 but it's possible there will be a couple of stragglers for 153 if I run into unknowns and folks are out for the holidays.

**Comment by davismtl** [comment]
Almost done the last two issues this week. Should be done the epic this week.

**Comment by LZoog** [comment]
@davismtl skipping today's product meeting in favor of working on this.

I have a PR open for one of the remaining issues pending an r+, and am going to do my best to finish up the last one today. We're still on track for this train.

**Comment by LZoog** [comment]
All issues have been completed. :partyparrot:
