### ISSUE TITLE
4.3 Close all P1 FxA metric issues in our backlog.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2728]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-407)
┆Priority: Medium
┆Issue Number: FXA-407

**Comment by davismtl** [comment]
- Engagement metrics for Monitor should go out in a dot release soon. Should be out the 18th which will give QA some time.
- Will reach out to Monitor team so they do the rest on their end.
- Send Tab fix will be next.
- @6a68 will re-do estimates for this for schedule.
- Will unlikely finish the entire epic before EOQ.

**Comment by davismtl** [comment]
@irrationalagent we should see if there is something we can remove in order to also fix this:
https://github.com/mozilla/fxa/issues/3261

We may remove the 2fa issue and move it to the AMO epic since it supports that feature.

**Comment by davismtl** [comment]
We extended the timeline to complete this until the end of the year.

**Comment by davismtl** [comment]
Making progress. Should be around until the end of the year.

**Comment by davismtl** [comment]
We will close this epic.

Jared is working on a preposal to make something more reliable and easier to maintain within the context of the upcoming ecosystem telemetry.

There are 2 categories of issues. 1- Quality, 2- Add more events.

Let's review our Q1 OKRs to see how this impacts it. Next steps are to sync up with Katie and Matt Miller so we have alignment for the quarter for moving our data to their pipeline to potentially address quality and how this roll-up to the AET.
