### ISSUE TITLE
Support the team building and integrating the new Bento menu.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2729]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-408)
┆Priority: Medium
┆Issue Number: FXA-408

**Comment by davismtl** [comment]
This is already shipped to Monitor.

We will check how easy it is for us to integrate so that we can determine if we should add to Settings now, prior to our Settings redesign.

**Comment by clouserw** [comment]
We are dropping this KR from Q4 goals.
