### ISSUE TITLE
Backfill synthetic "fxa_reg - created" events for amplitude

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#273]
Amplitude has a built-in notion of "new user" that basically boils down to "the first time we saw an amplitude event from that user".  This means that when we start sending live metrics events to amplitude, all of our existing users are going to look like "new" users from amplitude's perspective.

Their recommendation for dealing with this is to backfill synthetic user-creation events for existing users.  If we put a timestamp in the past, then it'll look like those events happened in the past, and amplitude will update its notion of when the user was "new".  So let's give it a shot.

We'll need to:

* Export a list of all users who created an account before the 11th of September, which is when we started capturing amplitude events in production; something like `select hex(uid), createdAt FROM accounts WHERE createdAt < 1505088000000;`
* Convert this list into a set of synthetic "fxa_reg - created" JSON event blobs, just like the ones that auth-server might spit out, using the `createdAt` timestamp as the event time.
* Send the events to amplitude in the normal way.

@jbuck @philbooth make sense?  I believe it's fine to wait until we've got the live event stream up and running before tackling this, but wanted to make sure we have it on file.

**Comment by jbuck** [comment]
Yeah, this makes sense, I'll note in this bug what the epoch for synthetic events should be when I deploy to prod.

**Comment by vladikoff** [comment]
from mtg: throw some json objects at it. cc @jbuck

**Comment by vladikoff** [comment]
from mtg: waiting on Sync UIDs

**Comment by vladikoff** [comment]
from mtg: waiting on Sync UIDs

**Comment by vladikoff** [comment]
from mtg: waiting for sync events in Q1

**Comment by vladikoff** [comment]
from mtg: still waiting for sync events in Q1

**Comment by vladikoff** [comment]
from mtg: blocked on token server change

**Comment by vladikoff** [comment]
from mtg: next meeting ask @jbuck to either close this or do next train

**Comment by vladikoff** [comment]
🗡 closing this for now
