### ISSUE TITLE
Integrate an account audit process via account toolbar menu to ensure account set up is complete and up to date.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2732]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-410)
┆Issue Number: FXA-410

**Comment by davismtl** [comment]
@vbudhram we may punt this to next quarter to try to get some low hanging fruit in to grow relationships more by the end of the year.

The good news is that a lot of the foundational work will have been done and it will give us some time to measure and see how the other tactics are going.

**Comment by clouserw** [comment]
We are dropping this KR from Q4 goals.

**Comment by clouserw** [comment]
epics are tracked in jira
