### ISSUE TITLE
Remove/update yuidoc for js-client

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#2738]
Currently we are not building our js-client docs because we removed [grun-contrib-yuidoc](https://github.com/gruntjs/grunt-contrib-yuidoc). It was removed because of nsp warnings. I think we should update our js-client docs to match what our other services are using or find a updated plugin. Quick googling didn't turn up anything.

Ref: https://app.circleci.com/jobs/github/mozilla/fxa/86231

If no objections, I can remove yuidoc for now so that builds don't fail for it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-411)
┆Issue Number: FXA-411

**Comment by philbooth** [comment]
> Currently we are not building our js-client docs

Fwiw they are built here:

https://github.com/mozilla/fxa/blob/b02c87d9b352c958dabc4b0e977e6d68a30426b6/_scripts/gh-pages.sh#L16

And are deployed here:

https://mozilla.github.io/fxa-js-client/

**Comment by philbooth** [comment]
> Fwiw they are built here.

Nvm, looks like I misunderstood the issue.
