### ISSUE TITLE
Move away from the use of `new Buffer()` api (or `Buffer()`)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#274]
With nodejs 8.x, `new Buffer()` is deprecated, and may be removed in a future major version (not sure if that means in 10.x, or if it will be later). This issue is just to remind that porting to the new apis would be good.

```
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for 
use due to security and usability concerns. Please use the new Buffer.alloc(), 
Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
```

**Comment by rfk** [comment]
I recall doing some work on this already, and indeed adding an eslint rule to try to catch leftover instances of this:

  https://github.com/mozilla/eslint-plugin-fxa/blob/master/lib/rules/no-new-buffer.js

But it looks like it doesn't necessarily catch the `Buffer()` constructions, only `new Buffer()`.  A good first step here would be to extend that to catch `Buffer()` and then ensure the rule is being applied in all our repos.

**Comment by vladikoff** [comment]
backlog due to "deprecated", not removed

**Comment by vladikoff** [comment]
Opened 3 issues above that should take care of the remaining repos

**Comment by pdehaan** [comment]
Filed https://github.com/mozilla/fxa-auth-server/issues/2343 since it looked like there were a few deprecated `Buffer()` instances (since v6), as well as a couple deprecated `util._extend()` (since v6), and `punycode` (since v7) references.
