### ISSUE TITLE
[email service] Localise the sender field

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#2740]
The email sender field is set in config and not currently localised. We should probably localise it.

https://github.com/mozilla/fxa/blob/b02c87d9b352c958dabc4b0e977e6d68a30426b6/packages/fxa-email-service/src/settings/mod.rs#L194-L205

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-412)
┆Issue Number: FXA-412

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing but this isn't on our roadmap so I'm going to close it.
