### ISSUE TITLE
Apps & Devices icon needed for Firefox Lite

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2749]
Goes with https://bugzilla.mozilla.org/show_bug.cgi?id=1586029

cc @ryanfeeley

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-414)
┆Issue Number: FXA-414

**Comment by ryanfeeley** [comment]
I suspect that this icon will work: https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/icon-device-phone-android.svg

If the Lite team wants a specific icon, perhaps @youwenliang can help?

Just had to match the style of the icon-* SVGs in this folder: 
https://github.com/mozilla/fxa/tree/master/packages/fxa-content-server/app/images

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This whole section changed with the settings redesign.
