### ISSUE TITLE
Experiment: Show Sync login form on Firefox Update

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#275]
@davismtl thoughts? Have we done this before?

Would it be possible to show this form if user updated Firefox, but is not signed into sync?

URL: https://www.mozilla.org/en-US/firefox/56.0.2/whatsnew/?oldversion=56.0

![image](https://user-images.githubusercontent.com/128755/32518688-53abf58a-c3d8-11e7-80e6-6e922352c593.png)

**Comment by davismtl** [comment]
So, we hope to replace marketing's sms/email box with ours in the near future since we cover more geographies and can personalize the experience more than they can.

I think that if you are logged in and already have 2 devices, we could show you a different message (e.g. add secondary email)

**Comment by shane-tomlinson** [comment]
@davismtl - I'm backlogging this for now, can you triage it into next when appropriate?

**Comment by davismtl** [comment]
Yeah, I'm tempted to change this to a feature. Needs scoping and measuring.

**Comment by vladikoff** [comment]
@davismtl @shane-tomlinson this was just an experiment idea, if it is no good feel free to also close it 🗡

**Comment by davismtl** [comment]
I think it is a great idea. I left it open to log it in our product board. Just haven't had time to move it over. Feel free to drop it in there. Or else, I'll jump to it later today.

**Comment by davismtl** [comment]
I added it to our product backlog here: https://projects.growthhackers.com/cards/firefox-update-page-detect-fxa/-ON3G8AsuJjdGUVnYqjCPQ
