### ISSUE TITLE
[fxa-event-broker] unhandled promised rejection after issue 2754 exception

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2756]
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejectio\
ns are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shane-tomlinson** [comment]
@jrgm - which service is this coming from?

**Comment by bbangert** [comment]
It's referring to #2754, so I'm guessing its a event-broker bug. @jrgm can you include any more detail about what unhandled promise this might be? Did it leave a record in Sentry?

**Comment by jrgm** [comment]
More context:

{"Timestamp":1570241852210000000,"Logger":"subhub-messaging","Type":"handleSubHubUpdated","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"uid":"10c7546c97f641dc8b3e07cd6f723173","action":"notify"}}
{"Timestamp":1570241852236000000,"Logger":"subhub-messaging","Type":"handleSubHubUpdated","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"uid":"10c7546c97f641dc8b3e07cd6f723173","action":"error","err":"Error: Record already exists","stack":"Error: Record already exists\n    at handleResponse (/app/lib/pool.js:71:21)\n    at RequestSet.callback (/app/node_modules/poolee/lib/pool.js:151:4)\n    at RequestSet.handleResponse (/app/node_modules/poolee/lib/request_set.js:66:8)\n    at Endpoint.complete (/app/node_modules/poolee/lib/endpoint.js:162:11)\n    at Endpoint.succeeded (/app/node_modules/poolee/lib/endpoint.js:168:8)\n    at IncomingMessage.gotEnd (/app/node_modules/poolee/lib/endpoint.js:326:8)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}}
(node:1) UnhandledPromiseRejectionWarning: Error: Record already exists
at handleResponse (/app/lib/pool.js:71:21)
at RequestSet.callback (/app/node_modules/poolee/lib/pool.js:151:4)
at RequestSet.handleResponse (/app/node_modules/poolee/lib/request_set.js:66:8)
at Endpoint.complete (/app/node_modules/poolee/lib/endpoint.js:162:11)
at Endpoint.succeeded (/app/node_modules/poolee/lib/endpoint.js:168:8)
at IncomingMessage.gotEnd (/app/node_modules/poolee/lib/endpoint.js:326:8)
at IncomingMessage.emit (events.js:203:15)
at IncomingMessage.EventEmitter.emit (domain.js:448:20)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"Timestamp":1570241861413000000,"Logger":"subhub-messaging","Type":"handleSubHubUpdated","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"uid":"10c7546c97f641dc8b3e07cd6f723173","action":"notify"}}
