### ISSUE TITLE
sms budget check starts in subhub sqs processor process?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2760]
I'm pretty sure this has nothing to do with subhub_messaging.js code; just that it's probably pulling in a library that starts this routine on load. Possibly harmless, but a puzzle.

Oct 04 23:50:30 ip-172-31-74-37.ec2.internal docker-fxa-auth-subhub-queue[28513]: {"Timestamp":1570233030963000000,"Logger":"subhub-messaging","Typ\
e":"sms.budget.ok","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"isBudgetOk":true,"current":0.48834,"limit":10,"threshold":1}}

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-416)
┆Issue Number: FXA-416

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we disabled the check
