### ISSUE TITLE
Recovery code flow: Add a link to a SUMO article for users who are locked out

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2764]
From https://docs.google.com/document/d/16OMxNfbkJeXdLCrD3XJ0PfD2ia2kzeIHcYlS4mMSKgA

The goal of this link is twofold:

* Provide users with information on how to get back into their account
* Track the number of users that are locked out of their account due to TOTP and not having recovery codes.

We could point to: https://support.mozilla.org/kb/what-if-im-locked-out-two-step-authentication

cc @davismtl, @irrationalagent, @vbudhram

**Comment by shane-tomlinson** [comment]
@ryanfeeley what should the text for this link be, and where should it be, on both of these screens?

<img width="639" alt="Screenshot 2019-10-07 at 10 54 42" src="https://user-images.githubusercontent.com/848085/66302490-ee573b00-e8f0-11e9-8bbf-ff5c938f75cb.png">


<img width="552" alt="Screenshot 2019-10-07 at 10 47 43" src="https://user-images.githubusercontent.com/848085/66302420-d089d600-e8f0-11e9-85e0-7939f68f6943.png">

**Comment by ryanfeeley** [comment]
@shane-tomlinson I think a few small changes can make this work, let me know your thoughts. My assumption is that users will always see the TOTP code before the recovery code string. The original copy was neutral, and the recovery code would even be linked directly. We aren't linking to it directly from anywhere, are we? If not, I think we can go with the proposed changes:

![security-code](https://user-images.githubusercontent.com/68213/66320505-f1502c80-e8ec-11e9-87cd-ceceb85afcfe.png)
![recovery-code](https://user-images.githubusercontent.com/68213/66320504-f1502c80-e8ec-11e9-9c54-07232ad48272.png)

WIll also take this opportunity to:
1. Add the "continue to service" that we could be including as a subhead everywhere possible.
1. Left and right align the links.

**Comment by vasilicatamas** [comment]
- Verified this issue on Stage [Train 1.149.3] under Windows 10 64-bit and Android 8.0.0 using a Google Pixel. 
- SUMO article is successfully accessed by clicking on "Are you locked out" link from "Enter recovery code" page. 
- During this testing 3 new issues were encountered and tracked separately: #3184, #3185, #3186.
- Based on this I will mark this issue as Verified.
![2fa](https://user-images.githubusercontent.com/18114210/67936034-b1baee80-fbd3-11e9-9f1c-c5c1e85f4097.gif)
