### ISSUE TITLE
fxa-payments-stage and -prod are missing from sentry

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2771]
on https://sentry.prod.mozaws.net/operations/ I see fxa-payments-dev but not -stage or -prod.

**Comment by jrgm** [comment]
Created separate stage/prod projects fxa-payments-stage and fxa-payments-prod and configured secrets for the fxa project. 

But do the payments code expect new form of DSN, or the old form.

**Comment by jrgm** [comment]
Closing. -stage and -prod projects are on Sentry.
