### ISSUE TITLE
Incorrect Client ID on Prod

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2772]
## Description

Incorrect client id on Prod

### Steps to reproduce

1. Sign into pro FxA
1. Go to on https://accounts.firefox.com/support

### Expected result

Be redirected to settings page.

### Actual result

Page stuck in a spinner state.

The cause is 400 with an "unknown client_id" error when {"grant_type":"fxa-credentials","client_id":"59cceb6f8c32317c","scope":"profile https://identity.mozilla.com/account/subscriptions","ttl":1800} is POSTed to https://api.accounts.firefox.com/v1/oauth/token

### Environment

Windows 10 and Nightly 71.0a1

**Comment by shane-tomlinson** [comment]
@chenba - the client_id `59cceb6f8c32317c` isn't registered on prod: https://oauth.accounts.firefox.com/v1/client/59cceb6f8c32317c

It is however a client_id on stage: https://oauth.stage.mozaws.net/v1/client/59cceb6f8c32317c

**Comment by jbuck** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1586854

**Comment by jrgm** [comment]
Added the production entry, with the question about adding profile to allowedScopes in stage and prod TBD. 

Now, I need to make a content server config change to point content server to subscriptions.firefox.com

**Comment by jrgm** [comment]
Waiting for clarification `profile` in `allowedScopes`, but the client is in production now. - https://bugzilla.mozilla.org/show_bug.cgi?id=1586854

**Comment by jrgm** [comment]
I closed https://bugzilla.mozilla.org/show_bug.cgi?id=1586854 with note: "It will be clearer, if the allowedScopes needs to include profile, to file a new bug to change it." So, closing this one too.

The client is in prod:
$ curl -s https://oauth.accounts.firefox.com/v1/client/59cceb6f8c32317c | python -mjson.tool
{
    "id": "59cceb6f8c32317c",
    "image_uri": "",
    "name": "Mozilla subscriptions management",
    "redirect_uri": "",
    "trusted": true
}
