### ISSUE TITLE
404 on privacy policy

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2777]
https://firefox-source-docs.mozilla.org/mobile/android/fennec/adjust.html is 404’ing from https://accounts.firefox.com/legal/privacy 

There are some other broken links too

**Comment by clouserw** [comment]
Three dead links found:


Status | URL | Source link text
-- | -- | --
404 Not Found | https://firefox-source-docs.mozilla.org/mobile/android/fennec/adjust.html | documentation
404 Not Found | https://firefox-source-docs.mozilla.org/mobile/android/fennec/mma.html | Android
404 Not Found | https://support.mozilla.org/en-US/kb/extension-recommendationss | Awesome Bar recommendations [302 from https://support.mozilla.org/kb/extension-recommendationss]

**Comment by vbudhram** [comment]
@clouserw @shane-tomlinson Objects to disabling these tests while we wait for legal?

**Comment by shane-tomlinson** [comment]
> @clouserw @shane-tomlinson Objections to disabling these tests while we wait for legal?

Already done! I disabled those tests in ae85faf29d32bf5d74690fe1825056223a67285b.

**Comment by Left47** [comment]
The third link seems to have an extra trailing "s". This works: https://support.mozilla.org/en-US/kb/extension-recommendations

**Comment by mafeld** [comment]
Agreed with @Left47. @clouserw - can we fix the typo in the one @Left47 mentioned?

**Comment by clouserw** [comment]
The first two links have been repaired and are working.

The third, as pointed out, is a typo and will need a patch.

**Comment by clouserw** [comment]
Ok, patch has landed.  If I'm reading our docs correctly, the HEAD of legal-docs gets pulled in when the docker container gets built, so, this should be fixed next time we push.

Marking QA+ -- please verify that there are no broken links on https://accounts.firefox.com/legal/privacy

**Comment by vasilicatamas** [comment]
This issue was verified on Stage [Train 1.150.2] under Windows 10 64-bit and encountered 3 links that return 404. Marking this bug as verified since the broken links are tracked in a follow-up bug #3368.
