### ISSUE TITLE
Issues with Onboarding Billing Form Visual Design

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#2785]
![Screenshot (5)](https://user-images.githubusercontent.com/26334275/66349276-59af0600-e90d-11e9-929d-7c23736b99bf.png)

Issues:
1) The icon at the top is too big and there needs to be more padding with the email line underneath. 
2) Name and ZIP code field text (both placeholder and filled in) is smaller than the rest of the text in the form fields. 
3) No check mark icon in check box.

Optimization questions:
1) Is it possible to add more character spacing to visually "fill up" the fields? (This also is a design best practice for heightening a sense of security in the form). Right now, it looks weird that the number fields all have a lot of white space to the right. 
2) The font doesn't seem to be SF UI Display as specified on Zeplin. Is this because we change the font for Windows..? All the font on the screen looks weird (might be because of the size differences and weird distribution of numbers, though).

**Comment by clouserw** [comment]
@johngruen fixed a couple of these already, but there is still some work to do

**Comment by johngruen** [comment]
@juliastarkov I believe i already fixed a lot of these

![image](https://user-images.githubusercontent.com/3323249/66774244-7032ff80-eec1-11e9-9313-0c09969387f7.png)

These should be in our staging environment today. Gonna close this, but plz file any other issues
