### ISSUE TITLE
Audit servers for Logging2.0 compatibility

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#279]
We need to populate the "logging 2.0" milestone with a concrete list of actions to bring us into full compliance.  @jrgm @jbuck can you please help lead the effort to identify remaining work here, and tag it into the appropriate milestone?

**Comment by jbuck** [comment]
The most important one is fxa-content-server

**Comment by jbuck** [comment]
Which helpfully has been filled into the correct milestone already: https://github.com/mozilla/fxa-content-server/issues/5523

**Comment by vladikoff** [comment]
cc @philbooth @jbuck

**Comment by philbooth** [comment]
In the cold light of day I think we can close this.

Related issues:

* https://github.com/mozilla/fxa-activity-metrics/issues/99
* https://github.com/mozilla/fxa-content-server/issues/5523

Milestone view:

* https://waffle.io/mozilla/fxa?milestone=FxA-144:%20logging%202.0
