### ISSUE TITLE
Document how we use JWTs

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2796]
I don't know how much overlap there would be with #2518 -- this might just be a section on that page.  I know Shane is working on a doc though, so I'm filing this so we don't lose track of it.

**Comment by shane-tomlinson** [comment]
The doc I wrote already merged! https://github.com/mozilla/fxa/pull/2770

Specifically, here it is: https://github.com/mozilla/fxa/pull/2770/files?short_path=2a143b6#diff-2a143b6de50e356c1d1d679b7226ea6b

There are other uses of JWTs that could be documented, primarily server->server communication.
