### ISSUE TITLE
Intermittent failing test:   1) selectEmailServices with real redis: returned the correct results:

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2805]
See https://app.circleci.com/jobs/github/mozilla/fxa/89063

>  1) selectEmailServices with real redis:
       returned the correct results:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/local/senders/select_email_services.js)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-420)
┆Issue Number: FXA-420

**Comment by vbudhram** [comment]
This still happens, https://app.circleci.com/jobs/github/mozilla/fxa/145396

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

I haven't seen this failure in a really really long time, think its safe to close.
