### ISSUE TITLE
[fxa-auth-server] The account email is not in the email message

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2810]
Imagine you have several Firefox Accounts. Right now it's very hard to determine the account the email is related to when getting Verification emails, Reset or other emails. The only way to tell is to look at the TO header in the email app.

**Comment by clouserw** [comment]
@ryanfeeley @davismtl

**Comment by davismtl** [comment]
This only seems like a problem for users who have multiple aliases or for users creating ad-hoc email aliases (e.g. alex+1@, alex+2@ and alex+3@ ).

I think this will only concern employees and power users. I am not concerned about this at this time.
