### ISSUE TITLE
Eliminate the use of ResumeTokens

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2814]
ResumeTokens are a way for us to pass information from a signup/signin flow to a verification flow without having to store data in the database. A resume token is a JSON bundle that's been btoa'd and contains a [whole bunch of fields](https://github.com/mozilla/fxa/blob/c759ba95c659d0bc527a2bff34a2ffcf9f83c1cb/packages/fxa-content-server/app/scripts/models/resume-token.js#L14) we need to propagate whenever a user clicks on a link from a verification email. They are a useful abstraction that adds a lot of complexity to the code base. I'd like to rip them out.

If we fully migrate to signup and signin codes, link based verification will only be used for verification reminders and password resets. Verification reminders don't use resume tokens, however password reset emails do. :sigh:

Now, if we could verify password resets with codes as well, then only verification reminders would contain a link, and again, those don't use ResumeTokens.

Needed to do this:

* [ ] Fully migrate signup to verification codes instead of links
* [ ] Fully migrate signin to verification codes instead of links
* [ ] Fully migrate password reset to verification codes instead of links
* [ ] Fully migrate add secondary email flow to verification codes instead of links

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-421)
┆Issue Number: FXA-421

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
