### ISSUE TITLE
Update redirect URI for Lockbox iOS client

### ISSUE THREAD

**Issue by linuxwolf** [mozilla/fxa#282]
The redirect URI for `lockbox-ios` (client_id "1b024772203a0849") should be the following:

* https://mozilla-lockbox.github.io/fxa/ios-redirect.html

**Comment by vladikoff** [comment]
Thanks @linuxwolf !

**Comment by linuxwolf** [comment]
(CC @sashei @ssage)

Thank _you_ @vladikoff (-;

**Comment by rfk** [comment]
> 1b024772203a0849

@linuxwolf are you sure this is the iOS client and not the webextension?  I get that client-id when I try logging in with the latest webextension release.

**Comment by linuxwolf** [comment]
OK, I see the problem now.

We registered an iOS client for a specific development environment (client_id 98adfa37698f255b), but I can't find the request to register an iOS client in _production_.

**Comment by linuxwolf** [comment]
Filed a new provisioning request (https://bugzilla.mozilla.org/show_bug.cgi?id=1436814).  I think this GH issue can be closed on your end.

**Comment by rfk** [comment]
I've linked this to the above bugzilla bug for fxa-bugzilla-mirror's benefit, will leave it open here so we can include it in the "lockbox beta" milestone for tracking purposes.

**Comment by linuxwolf** [comment]
mozilla-lockbox/lockbox-ios#113 (Update FxA client credentials in iOS)

**Comment by vladikoff** [comment]
We allow listed the ios redirect uri in the content server. OAuth server should get the new client when 105 gets deployed today or tomorrow. Via https://bugzilla.mozilla.org/show_bug.cgi?id=1436814
