### ISSUE TITLE
Setup docker creds and env vars for fxa-circleci

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#2825]
We need `DOCKER_USER_fxa_circleci` and `DOCKER_PASS_fxa_circleci` for #2803 

@jrgm

**Comment by jrgm** [comment]
These credentials have been added, and environment variables DOCKER_USER_fxa_circleci and DOCKER_PASS_fxa_circleci added to https://circleci.com/gh/mozilla/fxa/edit#env-vars with the user and pass values.
