### ISSUE TITLE
[Intermittent] Validation code turns in invalid after inserting for the first time an incorrect code

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2829]
### Build:
Prod [Train 1.147.3]

### Affected platforms:
Windows 10 x64

### Steps to reproduce
1. Launch Firefox and create Firefox account.
2. At “Enter verification code” step enter the 6-digit code received via email and add one empty space at the beginning and another one at the end of the code
3. Click “Verify” button
4. Erase the empty spaces
5. Click again “Verify” button

### Expected result
The correct 6-digit code is valid and the account is confirmed.

### Actual result
- The correct 6-digit code is seen as “Expired or invalid code” and the account is not validated.
- No new "Verification code" is received.
- The validation time was not exceeded (as you can see in the attached video the email was received 3 minutes ago)

### Additional details
- This is an intermittent issue.
- I am attaching a video.

![code-error](https://user-images.githubusercontent.com/18114210/66555295-16e06e80-eb57-11e9-955c-695343d6136c.gif)

**Comment by vbudhram** [comment]
@vasilicatamas Thanks for report, currently that input field only validates for digits, all other characters are considered invalid. I have a PR in https://github.com/mozilla/fxa/issues/2829 that strips away space characters so that this shouldn't be an issue.
