### ISSUE TITLE
Need icon and copy for Mozilla IAM login

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#283]
Test url: https://social-ldap-pwless.testrp.security.allizom.org/
To fit the design: 
![image](https://user-images.githubusercontent.com/128755/36236817-35caca6e-11c6-11e8-9b4f-407d016e61fc.png)

Example:

![foxy](https://user-images.githubusercontent.com/128755/36236919-e3367d24-11c6-11e8-9e68-20f5d1baf575.gif)

**Comment by vladikoff** [comment]
Old version from:  https://getpocket.com/login

![image](https://user-images.githubusercontent.com/128755/36236993-40fa7f32-11c7-11e8-84bf-3875e3688143.png)

**Comment by ryanfeeley** [comment]
@vladikoff We have a glyph to use, yay! https://design.firefox.com/photon/visuals/product-identity-assets.html#icon-as-glyph

**Comment by vladikoff** [comment]
from mtg:
- Use the glyph
- "leave it as `Log in with Firefox Accounts`

**Comment by vladikoff** [comment]
@gdestuynder could you please use 

this icon:

* http://design.firefox.com/product-identity/firefox-glyph/firefox-logo-glyph.svg
* http://design.firefox.com/product-identity/firefox-glyph/firefox-logo-glyph.png

and this copy:

`Log in with Firefox Accounts`

**Comment by vladikoff** [comment]
Done!

**Comment by gdestuynder** [comment]
![image](https://user-images.githubusercontent.com/956866/38100326-f4d1ad7e-3331-11e8-8a36-fc49a5bf0648.png)

The logo is not very well contrasted on the login page, so I'm wondering if there is another version we could use, or if the FxA branding team would like to change it in some way

This can also be seen on https://social-ldap-pwless.testrp.security.allizom.org/ (if you don't have auto login)

**Comment by ryanfeeley** [comment]
I have permission for us to use the full colour icon. Available here! https://design.firefox.com/photon/visuals/product-identity-assets.html

**Comment by m-branson** [comment]
Fantastic, thanks @ryanfeeley 👏

**Comment by m-branson** [comment]
Looks great @gdestuynder, thanks for quick turn! Side note is the Google icon being cut off at the top? (can take this to a different thread, tho wanted to flag while it was in front of me)

**Comment by gdestuynder** [comment]
indeed, i never noticed that - let's take it to => https://github.com/mozilla-iam/auth0-custom-lock/issues/95
