### ISSUE TITLE
Allow confidential OAuth clients to call the /introspect endpoint

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2832]
@rlr is trying to make use of the /introspect endpoint to check refresh tokens for FPN. However, since FPN is a confidential client (rather than a public client), [it's now allowed to](https://github.com/mozilla/fxa/blob/1e09c67db8ed25a3d4126b808c08674c993dd58f/packages/fxa-auth-server/fxa-oauth-server/lib/routes/introspect.js#L64).

We should fix this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-424)
┆Issue Number: FXA-424

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm not sure why confidential clients would need to provide a secret here, but I assume we're requiring it for a good reason. 😀

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

not on the roadmap
