### ISSUE TITLE
[fxa-auth-server] session_token_id is received as None, fails validation

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2834]
See https://sentry.prod.mozaws.net/operations/auth-prod/issues/6443091/?referrer=slack

![image](https://user-images.githubusercontent.com/128755/66584604-72a8f880-eb53-11e9-9488-8dddf4cf3dca.png)

We need to patch this somewhere to make sure it's not sent over the wire or validated differently

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-425)
┆Issue Number: FXA-425

**Comment by vladikoff** [comment]
Confirmed that it's returned as `null`.

>  \“session_token_id\” fails because [\“session_token_id\” must be a string]“,

We should fix this up

**Comment by clouserw** [comment]
Any updates here?

**Comment by vladikoff** [comment]
Closing for now unless it appears again
