### ISSUE TITLE
Why did this PR run 'all' in circleci?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#2837]
https://circleci.com/workflow-run/b4bca8fe-eb9d-411c-b73c-38d5adfa6f83

**Comment by lmorchard** [comment]
Just thinking out loud, but seems like there are 4 cases where "all" is run by [`.circleci/modules-to-test.js`](https://github.com/mozilla/fxa/blob/master/.circleci/modules-to-test.js). One of those is an exception handler. Might help to print out the reason for picking which of the 4 "all" cases?

**Comment by dannycoates** [comment]
The `CIRCLE_PULL_REQUEST` env var wasn't set on this build.

From the "Spin up environment" step:
```
BASH_ENV=/tmp/.bash_env-5d9f723b10d6bd406dfb3dd4-0-build
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=rm-trailhead-images
  CIRCLE_BUILD_NUM=90720
  CIRCLE_BUILD_URL=https://circleci.com/gh/mozilla/fxa/90720
  CIRCLE_COMPARE_URL=
  CIRCLE_JOB=install
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_PREVIOUS_BUILD_NUM=
  CIRCLE_PROJECT_REPONAME=fxa
  CIRCLE_PROJECT_USERNAME=mozilla
  CIRCLE_REPOSITORY_URL=git@github.com:mozilla/fxa.git
  CIRCLE_SHA1=0256dfaac94ea758bfcb67431805b11bc18bc165
  CIRCLE_SHELL_ENV=/tmp/.bash_env-5d9f723b10d6bd406dfb3dd4-0-build
  CIRCLE_STAGE=install
  CIRCLE_USERNAME=dannycoates
  CIRCLE_WORKFLOW_ID=b4bca8fe-eb9d-411c-b73c-38d5adfa6f83
  CIRCLE_WORKFLOW_JOB_ID=b88232e9-bb2b-4e84-a696-55fae5a01232
  CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS=
  CIRCLE_WORKFLOW_WORKSPACE_ID=b4bca8fe-eb9d-411c-b73c-38d5adfa6f83
  CIRCLE_WORKING_DIRECTORY=~/project
```

Seems like this has happened periodically for a long time: 
- https://discuss.circleci.com/t/circle-pull-request-not-being-set/14409/21
- https://discuss.circleci.com/t/circle-pull-requests-environment-variable-not-being-set/29883/10

**Comment by dannycoates** [comment]
IDK what to do about it... `all` seems like the best failure case i guess. 🤷‍♂️
