### ISSUE TITLE
30% of users who create an account, don't verify their email

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#284]
30% of users who create an account, don't verify their email. The email click event seems broken (I think there's already a bug filed for that) so it doesn't help with the diagnostic.

We should probably dig into on Re:Dash to see what the clickrate is on the emails we sent. Perhaps also look into deliverability, bounce, etc...

https://analytics.amplitude.com/org/31251/chart/new/nfie0f6

Ultimately, why are we losing so many users?

At a glance, it doesn't seem to be related to firstrun users. The rate is pretty similar for non-firstrun users.

**Comment by davismtl** [comment]
CC @irrationalagent

**Comment by vladikoff** [comment]
We have a server verification feature which needs a bit of fixing. That feature can help decrease the number of unverified account signups. 

Ref: https://github.com/mozilla/fxa-content-server/issues/4966
Ref: https://github.com/mozilla/fxa-auth-server/pull/2023

**Comment by vladikoff** [comment]
@juliemccracken can we add this to the Q2 doc to prioritize?

**Comment by vladikoff** [comment]
@davismtl can this be boomerang closed?

**Comment by davismtl** [comment]
I think there is still a problem with this rate overall but I will close it because it is too vague.
