### ISSUE TITLE
Add service to subscription sign in

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#2841]
Similar to what we do if you sign into any relier...

If you sign into or sign up for the subscription platform, we should indicate the service to which you are subscribing on the sign in page. For normal reliers we use the string `to continue to ${service}`...for sign ins to the subscription platform, we should use `to subscribe to ${service}`

![image](https://user-images.githubusercontent.com/3323249/66598512-cec94800-eb66-11e9-9339-0aeca126ea1a.png)

![image](https://user-images.githubusercontent.com/3323249/66598566-e86a8f80-eb66-11e9-888b-078a1b302833.png)

**Comment by meandavejustice** [comment]
This is looking a bit more complicated than I initially thought, waiting to get Shane's opinion.

[slack discussion thread](https://mozilla.slack.com/archives/GLV3KMZ8B/p1571161657218600)

**Comment by johngruen** [comment]
@johngruen will review different permutations

**Comment by meandavejustice** [comment]
Steps:
1. Sign out of fxa
2. navigate to fortress or 123done
3. click `Subcribe for pro`

![one-click-install](https://user-images.githubusercontent.com/1844554/67239798-02855700-f41e-11e9-9ec1-4ee666031759.gif)

**Comment by lmorchard** [comment]
> click Subcribe for pro

Yeah, the wrinkle here is that you're not signing into 123done (i.e. the subscription RP). You're signing into FxA to be redirected to the payment-server (i.e. a different RP).

I think the ask in this issue is that we'd like to add a special case for this payment-server-specific login flow to indicate that you're on your way to pay for 123done.

**Comment by meandavejustice** [comment]
Just verified with @johngruen that we won't be running into this case with the upcoming RP, closing.
