### ISSUE TITLE
The user is able to download the vpn after he cancels his subscription and his active time has expired

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#2849]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Precondition
User is logged in in the Guardian VPN homepage, he has canceled his subscription and his active time has expired

#### Steps to reproduce
1. Open the Guardian website and access the download page

#### Expected result:
- The user can't access the download page he is not able to download the product

#### Actual result:
- Download page is accessible, the user is able to download the product
![downlaodAvailableAfterCancelingSub](https://user-images.githubusercontent.com/15685441/66636598-2f658d00-ec1a-11e9-86b9-719f9648cd0d.gif)

**Comment by shane-tomlinson** [comment]
Moving this to the guardian website, we don't control access for the download.

**Comment by shane-tomlinson** [comment]
Moved to https://github.com/mozilla-services/guardian-website/issues/320, closing.

**Comment by lmorchard** [comment]
Also FWIW: I think we've said all along that *downloading* products is okay and should be accessible whether or not a subscription is cancelled. The product itself should verify subscription capabilities when it runs. I don't think we've planned to prevent access to downloads.
