### ISSUE TITLE
Cancelled subscription is still available under the subscriptions endpoint

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/fxa#2851]
## Description
The subscription endpoint returns a subscription even though it's already cancelled and it's not available in the UI. The userinfo endpoint though does not return any subscriptions.

### Steps to reproduce

* Cancel the guardian subscription in the FxA staging environment.
* Verify that there are not any subscriptions through the FxA account management.
* curl -v -H "Authorization: Bearer access_token" https://profile.stage.mozaws.net/v1/profile
   returns no subscriptions
* curl -v -H "Authorization: Bearer access_token" https://profile.stage.mozaws.net/v1/subscriptions
  returns `{"subscriptions": ["subscription_capability"]}`

### Expected result

The /subscriptions endpoint should not return any subscriptions

### Actual result

A subscription capability is returned.

**Comment by clouserw** [comment]
When a subscription is cancelled it's still valid until the end of the billing period (month).  I think this is by design.  @johngruen @stlhood @bbangert to confirm

**Comment by stlhood** [comment]
Correct, subscription is still valid until the end of the current billing period.

**Comment by clouserw** [comment]
Thanks.

**Comment by lmorchard** [comment]
> it's not available in the UI.
> Verify that there are not any subscriptions through the FxA account management.

Screenshot might be helpful here. When the user cancels a subscription, it should remain active and available to be reactivated until the end of the current billing cycle. Are you saying that the subscription disappears entirely from the management UI when you cancel it? (That would be a bug.)

> curl -v -H "Authorization: Bearer access_token" https://profile.stage.mozaws.net/v1/profile
returns no subscriptions
> curl -v -H "Authorization: Bearer access_token" https://profile.stage.mozaws.net/v1/subscriptions
returns {"subscriptions": ["subscription_capability"]}

This looks like trouble - both of these endpoints should report the same information about subscriptions in any case.

**Comment by lmorchard** [comment]
Reopening - this sounds like there's still a problem

**Comment by lmorchard** [comment]
Trying to reproduce. I went through the guardian subscription flow - create new account, pay for a subscription, then cancel the subscription. I still see the subscription pending cancellation in the management UI, ready to be reactivated. Did you see something different than this, @akatsoulas?

<img width="330" alt="Capture" src="https://user-images.githubusercontent.com/21687/66671049-12c45780-ec10-11e9-8594-45133f6f6a47.PNG">

**Comment by lmorchard** [comment]
Having trouble figuring out how to attempt repro against profile-server - I don't have id / secret for any oauth clients there. But, it looks like 123done and guardian are both getting the expected subscription capabilities.

Will poke some more later, but would be interested to know if the subscription is getting immediately cancelled rather than deferred until end of term for anyone else.

**Comment by akatsoulas** [comment]
@lmorchard We are using the staging server for testing which has an invalidation period of one day.
We tested after the subscription was cancelled and the one day had already passed so there were no subscriptions.  This was the result in the UI.
https://user-images.githubusercontent.com/5293100/66641504-963b7400-ec23-11e9-855a-64dc18906c1b.png

**Comment by johngruen** [comment]
I think i reproduced this by being able to access a guardian subscription on their staging site this morning that I'd cancelled on Friday on the sub plat staging environment. 

Ricky says they check the `guardian_vpn` string in `profile.subscriptions`, so the fact that i can access my sub suggests there is an error here.

**Comment by johngruen** [comment]
@rlr is going to push to the guardian staging environment with a patch that exposes the profile scope so we can verify/debug this a bit more easily

**Comment by johngruen** [comment]
Okay, i can reliably reproduce this issue:

1. Go to the Guardian staging environment and subscribe
2. Go to fxa staging and view your guardian subscription
3. Go to the Stripe staging environment and cancel your subscription.
4. Go back to the Subscription Management Page on FxA Staging and refresh, you will see the subscription is correctly cancelled.
5. Go back to the main FXA settings page, you will see the Manage Subscriptions section incorrectly displayed.
6. Open the Network panel and refresh. In the `profile` response body, you can see the incorrect `guardian_vpn` subscription string.

**Comment by marty331** [comment]
@bbangert I think the problem is on the subhub side, we are not sending the notification when the for the `customer.subscription.deleted` event is received.  We will get a PR out to fix this tonight (Tues).  The payload should be the same as we've discuss already, is that right?  
"uid",
 "active",
"subscriptionId",
"productId",
"eventId",
"eventCreatedAt",
"messageCreatedAt"

**Comment by marty331** [comment]
@bbangert PR created in subhub to process `customer.subscription.deleted` events and send to SNS - https://github.com/mozilla/subhub/pull/317

**Comment by akatsoulas** [comment]
The inconsistency between the `profile` and `subscriptions` endpoint is still present. The former still returns an active subscription although it was cancelled yesterday.

**Comment by lmorchard** [comment]
I don't think the fix cited in closing this issue has been deployed yet. Probably need to check again in a day or so?

**Comment by akatsoulas** [comment]
Sounds good. Thanks @lmorchard

**Comment by bbangert** [comment]
@akatsoulas Yes, the fix isn't out yet. Hopefully once the fix is out today we can see if its fully resolved.

**Comment by viorelaioia** [comment]
@bbangert , any updates here? Is the fix deployed?

**Comment by viorelaioia** [comment]
Just confirmed with @akatsoulas  that this issue is fixed.
