### ISSUE TITLE
Create ~Chronograf~ Grafana Charts Based on Statsd Metrics

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2854]
Once https://github.com/mozilla/fxa/issues/2665 is done.  Get access to InfluxDB and create some colorful charts?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-431)
┆Priority: Medium
┆Issue Number: FXA-431

**Comment by clouserw** [comment]
Let's investigate grafana also

**Comment by chenba** [comment]
https://github.com/mozilla/fxa/pull/3581 will change the name of the stats once deployed.

**Comment by chenba** [comment]
Adding this into a milestone since we have some data in influxdb now.

**Comment by chenba** [comment]
The auth server currently emits the following timing stats.

### SMS with AWS SNS

`fxa-auth-server.sms.send.success `
`fxa-auth-server.sms.send.error `


### AWS SQS

The stat names have the following format: `fxa-auth-server.sqs.${QUEUE_NAME}.(delete|receive)`.

A `receive` is a timing stat for a call to SQS to get up to 10 messages, with a wait time up to 20 seconds.

A `delete` is a timing stat for a delete call to SQS to remove a message from the queue after the auth server processed it.

#### Email Notifications

These are notification messages from SES on email statuses.

`fxa-auth-server.sqs.fxa-email-*`

#### Profile Update Notifications 

`fxa-auth-server.sqs.fxa-profile-*`

#### SubHub Update Notifications 

`fxa-auth-server.sqs.fxa-subhub-*`


### HTTP API Calls

These are timing stats to external services.  Prior to https://github.com/mozilla/fxa/pull/3581 (Train 152), they have names in the format of `fxa-auth-server.${SERVICE_NAME}.${FUNCTION_NAME}`, which is a timing stat for a successful call.  PR #3581 added stats for failed calls, and the names have changed to the format of `fxa-auth-server.${SERVICE_NAME}.${FUNCTION_NAME}.(success|failure)`.  The lists below use the new names.

#### Customs Server

`fxa-auth-server.customs.check.failure `
`fxa-auth-server.customs.check.success `
`fxa-auth-server.customs.checkAuthenticated.failure`
`fxa-auth-server.customs.checkAuthenticated.success `
`fxa-auth-server.customs.checkIpOnly.failure`
`fxa-auth-server.customs.checkIpOnly.success `
`fxa-auth-server.customs.failedLoginAttempt.failure`
`fxa-auth-server.customs.failedLoginAttempt.success `
`fxa-auth-server.customs.passwordReset.failure`
`fxa-auth-server.customs.passwordReset.success `

#### Pushbox 

`fxa-auth-server.pushbox.retrieve.failure`
`fxa-auth-server.pushbox.retrieve.success`
`fxa-auth-server.pushbox.store.failure`
`fxa-auth-server.pushbox.store.success`

#### SubHub

`fxa-auth-server.subhub.cancelSubscription.failure`
`fxa-auth-server.subhub.cancelSubscription.success`
`fxa-auth-server.subhub.createSubscription.failure`
`fxa-auth-server.subhub.createSubscription.success `
`fxa-auth-server.subhub.deleteCache.failure`
`fxa-auth-server.subhub.deleteCache.success`
`fxa-auth-server.subhub.deleteCustomer.failure `
`fxa-auth-server.subhub.deleteCustomer.success `
`fxa-auth-server.subhub.getCustomer.failure `
`fxa-auth-server.subhub.getCustomer.success`
`fxa-auth-server.subhub.listPlans.failure`
`fxa-auth-server.subhub.listPlans.success`
`fxa-auth-server.subhub.listSubscriptions.failure`
`fxa-auth-server.subhub.listSubscriptions.success`
`fxa-auth-server.subhub.reactivateSubscription.failure`
`fxa-auth-server.subhub.reactivateSubscription.success`
`fxa-auth-server.subhub.updateCustomer.failure`
`fxa-auth-server.subhub.updateCustomer.success`

**Comment by clouserw** [comment]
There is the start of a dashboard at https://earthangel-b40313e5.influxcloud.net/d/J81nRFfWz/auth-server?orgId=1&refresh=5s&var-environment=prod

We're going to kick this to 153 since the stat names changed in 152 and we don't want to make the dashboard twice.

**Comment by clouserw** [comment]
Ok, everything is graphed at https://earthangel-b40313e5.influxcloud.net/d/J81nRFfWz/auth-server?orgId=1&refresh=5s .  I didn't include subhub because the Architecture 2.0 change should be happening in January and would make the graphs obsolete.

**Comment by clouserw** [comment]
Eh, I added the subhub graphs to the same report
