### ISSUE TITLE
Firefox iOS: "Authorize this sign-in" viewport broken

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#2859]
## Description and  STR
Try to sign into FxA with an unverified account.
 When you get to the "Authorize this sign-in" dialog, background then foreground the app.
Result: The dialog appears zoomed in upon foregrounding and can't be zoomed out.
Happens on iPhone and iPad.

https://user-images.githubusercontent.com/1866605/66643043-9ee17980-ec26-11e9-83be-1eb21dce158f.png

### Environment

iOS 13, Firefox iOS Beta. Not sure if it happens in non beta.

**Comment by vladikoff** [comment]
@vbudhram this happens once the app is backgrounded (to check the email for the sign in code) and then foregrounded. I saw this in the iOS 13 simulator

**Comment by garvankeeley** [comment]
The  viewport for this page looks ok: ```
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=2,user-scalable=yes">
```
I tried manually adjusting the viewport using JS injected to the page, and was not able to improve the result at all.
