### ISSUE TITLE
Move Firefox Accounts docs off of MDN

### ISSUE THREAD

**Issue by andymckay** [mozilla/fxa#286]
To allow MDN to focus on Web docs, let's move our docs off of MDN and onto somewhere like read the docs. Assuming that http://fxa.readthedocs.io/en/latest/ is the best location.

Currently on MDN we've got: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts

/cc @wbamberg because I couldn't find Chris Mills on github.

**Comment by vladikoff** [comment]
@chrisdavidmills :)

**Comment by chrisdavidmills** [comment]
Hi there,

Thanks for helping out with the effort. I don't think this'll be a big migration job — I've done some digging, and it looks like there are only 6 child pages sitting below the main Firefox Accounts page.

Let me know what help you need.

**Comment by vladikoff** [comment]
from mtg: for Q2 or Q3

**Comment by vladikoff** [comment]
Some of this has been done, we are gonna reformat the large doc on the new portal in the next couple of weeks
