### ISSUE TITLE
Document how to do a point release

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2860]
docs @ https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-432)
┆Priority: Medium
┆Issue Number: FXA-432

**Comment by clouserw** [comment]
This should also include how to deal with `fxa-private` if needed

**Comment by vbudhram** [comment]
A draft of this document was created [here](https://docs.google.com/document/d/1E0svSUV_bYxLCoea_GE2UGUtwoOdcwAWlYnuOy2yWSc/edit?usp=sharing) for feedback.
