### ISSUE TITLE
Firefox iOS: FxA account page missing heading

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#2864]
## Description

https://user-images.githubusercontent.com/1866605/66652418-5df55f00-ec3e-11e9-9679-7318aaa8098f.png

### Steps to reproduce

Open FxA settings on Firefox OR 
on Firefox desktop, go to Manage Account, then shrink the window to 300 px wide, the bug happens there too.

### Expected result

Should have Firefox Account title

### Actual result

The title disappears as the viewport is shrunk.

---
x-posted from https://github.com/mozilla-mobile/firefox-ios/issues/5596

**Comment by johngruen** [comment]
This is as intended, in some views of Firefox accounts there is a shoulder sign out button. At mobile breakpoints these two things collide.
