### ISSUE TITLE
Sub Plat — subscription price on payment page incorrect

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#2868]
I believe the FPN price is $4.99 and this is reflected in the FPN website screens.

The payment page lists $5 as the price. This should be changed to $4.99.

**Comment by johngruen** [comment]
@janiceahn are you sure you're looking at the FPN subscription price and not the 123done price here. I am unable to reproduce this.

**Comment by janiceahn** [comment]
I was on the payment page in 123done.
