### ISSUE TITLE
Sub Plat — Typo in cancellation modal

### ISSUE THREAD

**Issue by stlhood** [mozilla/fxa#2873]
## Description

There is a typo in the confirmation modal that appears after the user cancels a subscription.

### Steps to reproduce

Cancel a subscription.

### Expected result

The text in the confirmation modal should read: "You will still have access to [service name] until [date]."

### Actual result

There is an extra "until" in the sentence. The text reads: ""You will still have until access to [service name] until [date]."

**Comment by stlhood** [comment]
![image](https://user-images.githubusercontent.com/42821/66706987-f814e000-ecee-11e9-895d-a23a6f32fe69.png)

**Comment by johngruen** [comment]
Gross
