### ISSUE TITLE
Fix tests running against latest

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2877]
In the full functional tests run against e.g., `latest.dev.lcip.org`, there's a pretty consistent 15-20 failures. It should be green most of the time.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-436)
┆Issue Number: FXA-436

**Comment by shane-tomlinson** [comment]
https://tc-test.dev.lcip.org is where to see these test runs.

**Comment by clouserw** [comment]
Let's also document:
* What teamcity is, how those tests are run, and where they report their status.

**Comment by clouserw** [comment]
Let's also clarify:  The relationship of these tests to the ones on CircleCI.

**Comment by juliemccracken** [comment]
Might choose to work on only a subset.

**Comment by clouserw** [comment]
team city is gone.  Closing this.  /cc @ashrivastava-qa
