### ISSUE TITLE
Clicking “Go Back” button from “Terms of Service” page doesn’t return the user to registration form

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2881]
**Build:**
Stage [Train 1.148.0]

**Affected platforms:**
Windows 10 x64 (Intermittent)

**Steps to reproduce:**
1. Launch Firefox and click on the Firefox Account from tollbar.
2. Click o “Turn on Sync...”
3. Insert an email address which does not have an associated  Firefox account
4. At registration page click on “Terms of Service” link from the bottom of the page.
5. Click “Back” button.
 
**Expected Results:**
The user is redirected to registration page “Create a Firefox Account”.

**Actual Results:**
The user is redirected to “Enter your email” page.

**Additional Notes:**
- This issue also reproduce for “Privacy Notice” link
- I am attaching a video.

![back issue](https://user-images.githubusercontent.com/18114210/66755203-36053600-eea0-11e9-85d1-34d0c0265e7d.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-437)
┆Issue Number: FXA-437

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
