### ISSUE TITLE
Subscription Platform Download Email References Incorrect Product

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#2882]
## Description

Seen on Stage

![image](https://user-images.githubusercontent.com/3323249/66761521-7e265780-eea4-11e9-96ad-e791c4fde3c6.png)

And the link points to `https://accounts.stage.mozaws.net/subscriptions/download`

The product name is Firefox Private Network, and that link is incorrect (see slack)

**Comment by lmorchard** [comment]
Looking into this a bit. [Looks like we refactored at some point to ignore the `SUBSCRIPTION_DOWNLOAD_URL` env var](https://github.com/mozilla/fxa/commit/330a4926dae26fbe0c845b40a36329290d334fbe). I'm not sure why. Still digging.
