### ISSUE TITLE
Invalid Payment URL with two `?` when passing in `?plan=<>`

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#2883]
## Description

Describe the issue that you're seeing.

On stage, we are sending users to `https://accounts.stage.mozaws.net/subscriptions/products/prod_FiJ42WCzZNRSbS?plan=plan_FiJ55YK6UYftPa` for subscribing to guardian. From there the user is redirected to a URL like the one below which is invalid with two `?` in it.

`https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_FiJ42WCzZNRSbS?plan=plan_FiJ55YK6UYftPa?device_id=<>&flow_begin_time=<>&flow_id=<>`

It looks like url parsing is fine with this though. at least `new URL()` doesn't blow up.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

Go to https://accounts.stage.mozaws.net/subscriptions/products/prod_FiJ42WCzZNRSbS?plan=plan_FiJ55YK6UYftPa and look a the url you end up at.

### Expected result

What should happen?

The URL should not have two `?`s.

### Actual result

What happened.

The URL has two `?`s.

### Environment

What browser and operating system are you using?

**Comment by lmorchard** [comment]
Starting to scratch my head at this. We just landed this PR to start supporting metrics, which seems like a lead: https://github.com/mozilla/fxa/pull/2844/files
