### ISSUE TITLE
Expand the message shown before deleting an account

### ISSUE THREAD

**Issue by andymckay** [mozilla/fxa#289]
In order to get closer to GDPR compliance, we'll have to ensure data is deleted across multiple reliers once a user deletes their account. For example: data will be deleted out of AMO, notes will be removed, lockbox data (when its implemented) will go.

At this point the deletion screen looks like this:

![f0083ba7-f427-4a3c-9178-4d0fd46ee34b](https://user-images.githubusercontent.com/74699/37542438-6b979ae8-291b-11e8-9890-820d46ff71d6.png)

Firefox accounts knows what apps I'm using (if I go to the "clients" page). Perhaps we could show a message that includes those apps, for example: "... and your data on the Firefox Add-ons site".

/cc @ryanfeeley @davismtl

**Comment by davismtl** [comment]
Ryan Feeley has worked on a great flow at registration to talk about lost data with reliers if you reset your password. I think much of the copy and logic he proposes there should be used here to inform users of what data they will lose when they delete their accounts. (i.e. it might not be obvious that they will lose their data in sync, notes, lockbox, etc)

**Comment by vladikoff** [comment]
Q2!

**Comment by vladikoff** [comment]
from mtg: @ryanfeeley do you have bandwidth for this in the next 2 weeks?

**Comment by ryanfeeley** [comment]
@vladikoff I'm not sure we need to list every possible service, and if we did, it could get messy. What about something like this? Password field is disabled until checked.
<img width="587" alt="screen shot 2018-04-06 at 1 46 47 pm" src="https://user-images.githubusercontent.com/68213/38436759-81ad2ba2-39a3-11e8-81cc-ff0f3927d560.png">

**Comment by rfk** [comment]
> I'm not sure we need to list every possible service, and if we did, it could get messy. 

We need to be guided by legal here, /cc @juliemccracken for recommendations.

**Comment by juliemccracken** [comment]
Here's a quick summary of the MVP legal told us we have done by May 25th:  When a user goes to delete their account, we should put up a caution to warn the user that they need to visit the reliers and opt-out of using their FxA account/delete their own personal data prior to deleting their Firefox account.

**Comment by shane-tomlinson** [comment]
>  we should put up a caution to warn the user that they need to visit the reliers and opt-out of using their FxA account/delete their own personal data prior to deleting their Firefox account.

@juliemccracken - Legal quite often wants specific wording, did they make any suggestions as to what we would say?

**Comment by juliemccracken** [comment]
We didn't get any specific wording from legal. Here are the [notes I took during my conversation with Mika](https://docs.google.com/document/d/10btzDY6MwMZuAaZBK67Yob4xwIHXgGjE4G3sCKQwloo/edit) to perhaps provide a little more context. I'll request from help from Michelle Heubusch. Perhaps she can help us with this.

**Comment by juliemccracken** [comment]
Michelle Heubusch proposed the following content for the delete account warning: 
"This will delete your account from Firefox browsers.  It will not delete the account or any saved personal information from Mozilla apps and services like Screenshots, Notes, AMO, and Lockbox. "  She asked for feedback. It was reviewed with the team on April 30th, and the feedback Julie will share with Michelle is that we should tell the users they should first visit any applicable relier apps to delete their account data there first prior to deleting their Firefox account.

**Comment by ryanfeeley** [comment]
This sounds very different than was is described in this issue originally. For compliance, we HAVE to delete their data. I don't think we can just tell them to make the rounds and delete it first themselves, can we?

**Comment by rfk** [comment]
>  I don't think we can just tell them to make the rounds and delete it first themselves, can we?

Advice from legal was that as an MVP, we could in fact tell the user to make the rounds and delete it first themselves.

**Comment by rfk** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/pull/6178
