### ISSUE TITLE
User with a previously cancelled and currently expired subscription cannot subscribe again to Guardian

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/fxa#2897]
## Description
Trying to subscribe to guardian with an account that previously cancelled a subscription and reached the inactivity period doesn't work. 

### Preconditions:
1. Have an account that had an active subscription
2. Cancel the existing subscription (subscription is still valid until the next day)
3. Wait for the subscription to expire 
3. Login to fxa the next day, when the period of inactivity was reached and the subscription is expired 

### Steps to reproduce
1. Login to fxa with the account from precondition
2. Verify that there is no "Subscriptions" option in your user menu
3. Navigate to Guardian Staging Environment
4. Click "Subscribe Now" button
5. Enter fxa credentials used in step 1 to login 

### Expected result
Billing Information form page is returned

### Actual result
FPN Download page is returned. If I click "Manage subscriptions" button, I'm redirected to the Subscriptions page on my fxa account, where I have no subscription enabled. 
![image](https://user-images.githubusercontent.com/5293100/66814268-fe999680-ef3e-11e9-926c-40ab96e5e893.png)

### Environment
Ubuntu 16.04, Firefox 69.0.3

**Comment by johngruen** [comment]
I wonder if this is related to #2851...seems like a case of bad state being passed around, such as a user still having the wrong stuff in their profile scope

**Comment by clouserw** [comment]
We think a PR ben merged last night will fix this.  I'm going to close to get QA verification

**Comment by viorelaioia** [comment]
@clouserw , is the fix deployed yet? I can still reproduce this issue

**Comment by clouserw** [comment]
It is as of about an hour ago

**Comment by viorelaioia** [comment]
@clouserw , the PR doesn't seem to fix this issues, as I can still reproduce it. 
I used email address iam_test+4@mozilla.com, which shows in stripe as cancelled and expired in Oct 15. After clicking Subscribe now and entering my fxa credentials, I was redirected to download page, instead of billing info page.
Can you take another look?

**Comment by bbangert** [comment]
@viorelaioia I believe our fix went out in the afternoon on the 16th, while the subscription expiration happened in the morning before our fix was deployed. This resulted in our database continuing to have a record thinking you are already subscribed. I'm working with ops to have this incorrect record removed from stage db, but in the meantime the existence of this bug can be verified by using a new account to sign-up and watch for expiration.

**Comment by bbangert** [comment]
@viorelaioia we reprocessed the stripe event, and it looks like it was deleted now. Can you try resubscribing now?

**Comment by lmorchard** [comment]
FWIW, I have a draft PR open with a possible further improvement for this situation:

https://github.com/mozilla/fxa/pull/2925

Still in draft because it could use some overall scrutiny, and I want to drop the update calls into more places, but might be worth a look in relation to this issue

**Comment by viorelaioia** [comment]
@bbangert , I tried to re-subscribe with the iam_test+4@mozilla.com email address and it worked as expected (payment window was returned). Though, I tried with a different email address that was in the same state as  iam_test+4@mozilla.com, but I got the old behavior. Probably because you reprocessed the stripe event for the specific email. 
I would verify this bug with a new email, by cancelling now and verifying when the subscription expires. But I noticed there is only monthly subscriptions available. Is there any way I can trigger a daily subscription?

**Comment by viorelaioia** [comment]
I verified this using an fxa account with daily subscription that I cancelled yesterday, so it expired today. I consider it half fixed, as it doesn't work as expected first time after the subscription expired.
Instead of getting: Subscribe button > login > payment, I'm getting Subscribe button > login > Subscribe button > payment.
To be more explicit:
First time I clicked  "Subscribed now" from homepage, after subscription was expired, 
I was redirected to Homepage (logged-in mode), where I had the "Subscribe now" button available again. After clicking it, I received the payment screen, as expected. 
Logging out and clicking "Subscribe now" again, I got the payment window. 

@bbangert, @johngruen, any thoughts on this?

**Comment by johngruen** [comment]
@viorelaioia I filed an issue on the guardian side since i think it's their bug at this point.

**Comment by johngruen** [comment]
This issue is not in FxA and it looks like Ricky has resolved the Guardian end

**Comment by viorelaioia** [comment]
This issue is fixed.
