### ISSUE TITLE
Audit logs to ensure that no emails appear in the logs

### ISSUE THREAD

**Issue by andymckay** [mozilla/fxa#290]
To help with GDPR compliance we should check that no emails end up in the log files. Otherwise when a user deletes their account, we'd still be holding onto that peice of information. This could be expanded to cover any other PII data that might going into the logs.

**Comment by shane-tomlinson** [comment]
Just found this, cc @jrgm and @jbuck

**Comment by vladikoff** [comment]
Reopen this if any leftovers remain for this
