### ISSUE TITLE
[Android] Access denied on “Federal Trade Commission” page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2902]
**Build:**
Prod [Train 1.148.1]

**Affected platforms:**
Android 9

**Steps to reproduce:**
1. Go to menu -> settings -> SIGN IN
2. Insert a valid email address and a valid password.
3. At age field type a number <13
4. Tap on “Create account” button
5. Tap on “Lear more” link from “Cannot create account” message.

**Expected results:**
Federal Trade Commission page successfully displays the content.

 **Actual Results:**
“Access denied.You are not authorized to access this page.” message is displayed on Federal Trade Commission page.

![73096717_1510852335741135_8868307803459026944_n](https://user-images.githubusercontent.com/18114210/66829565-50044e80-ef5c-11e9-900e-6a503cf4c150.jpg)

**Comment by vasilicatamas** [comment]
See also #2572

**Comment by clouserw** [comment]
> Build:
> Prod [Train 1.148.1]

This is fixed in Train 148 which is on Stage but not on Prod yet.  Was this tested in Stage or Prod?

**Comment by vasilicatamas** [comment]
> This is fixed in Train 148 which is on Stage but not on Prod yet. Was this tested in Stage or Prod?

Sorry for the typo, this issue was encountered on stage. But checked again on stage train 1.148.3 and the Children's Privacy page seems to be successfully displayed on Android.

![72921774_713016762551074_3011789633852801024_n](https://user-images.githubusercontent.com/18114210/66901586-a24e7980-f007-11e9-98bd-ef1d5d654398.jpg)

Base on this I am closing this issue as it is no longer reproducible.
