### ISSUE TITLE
Link from FPN marketing footer page should redirect to different page in sumo

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/fxa#2909]
"Private Network Help" link from FPN marketing footer page currently redirects to https://support.mozilla.org/en-US/products/firefox-private-network.
It should be updated to redirect to https://support.mozilla.org/1/vpn/%VERSION%/%OS%/%LOCALE%/vpn

**Comment by johngruen** [comment]
Hi @viorelaioia this is filed in the wrong repo...I believe you are invited to the correct one. Closing this for now, LMK if you have questions.

**Comment by rbillings** [comment]
Filed in the guardian-website repo:  https://github.com/mozilla-services/guardian-website/issues/365
