### ISSUE TITLE
Setup Application Services portal

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#291]
- [ ] Setup a new Repo
- [ ] Create 2 pages 
- [ ] Create outbound links to other App Services stuff
- [ ] Copy MDN Content
- [ ] Deploy it somewhere

Ref: https://docs.google.com/document/d/1lVXIxYpjxwTKll0A7Kaz_b3M0e1rtFcyJMTHzNULmoU/edit
Ref:  https://docs.google.com/document/d/1pqioHeU2b4bdfMh4-dzrSNrLwf1NEL2LUORS4TYhZCs/edit?ts=5aaf8ca8#

**Comment by rfk** [comment]
This is ongoing over at https://github.com/mozilla/application-services and https://mozilla.github.io/application-services/ so I think we can close it here; thanks @vladikoff!
