### ISSUE TITLE
Support tickets are filed from Anonymous User

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2912]
Support tickets in Zendesk are showing up as from Anonymous User.  Email is populating correctly, but name is not.  

https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/support.js#L79

**Comment by stlhood** [comment]
Note that this "Anonymous User" placeholder text is also ending up in emails sent to the customer, so this is a user-visible issue.

**Comment by bbangert** [comment]
We're going to replace this with the user's email address since we do not store the users name used for Stripe, and many users have not entered a username string.
