### ISSUE TITLE
Enable amplitude processing for payments server in stage

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2913]
Once https://github.com/mozilla/fxa/pull/2734 lands, we'll want to start ingesting amplitude metrics events from the payments server, as is currently done for content server.

**Comment by 6a68** [comment]
@jbuck @jrgm is this issue needed here, or should I file it against the fxa-amplitude-send repo?

**Comment by jbuck** [comment]
Yeah, I'll add links to PRs where I enable this

**Comment by johngruen** [comment]
@jbuck so we can close this, ya?

**Comment by jbuck** [comment]
I'd like to keep this open until #3053 is on stage and confirmed working

**Comment by jbuck** [comment]
#3053 didn't fix this, continuing to track in #3050

**Comment by clouserw** [comment]
It looks like #3050 is closed.  Should this be closed to?  Should this be kicked to the next milestone?  Thanks

**Comment by 6a68** [comment]
Hopefully payments metrics will be working on stage today, and then we can close this :+1:

**Comment by clouserw** [comment]
We checked amplitude stage and saw some numbers in there so it looks like this works.  Thanks!

**Comment by 6a68** [comment]
@jbuck Hey, is this bug good to close?
