### ISSUE TITLE
refresh fxa dev pipeline

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#2916]
There is a dev pipeline in the dev iam that matches the stage/prod pipeline. We should dust that off and get that running correctly again.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-439)
┆Issue Number: FXA-439

**Comment by clouserw** [comment]
Depending on the outcome of this bug, I will add ecosystem docs about fxa-dev, or not.  Commenting here so I get CC'd on stuff. :)

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Refreshing the dev pipeline in AWS doesn't make sense
