### ISSUE TITLE
Automatically request SMS budget increases

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#292]
We could write a Lambda script that polls the current SMS spend and automatically files a support ticket when it's projected to exceed the limit. Maybe using some fancy stats wizardry from @irrationalagent to make that projection accurate.

**Comment by irrationalagent** [comment]
hmm. I'll give it some thought, maybe we don't need anything too fancy here. if we are serious about this, could we pull some sample data for me to play around with?

**Comment by irrationalagent** [comment]
Hacked something together to forecast SMS spending, based on the data emailed to me by pb/jrgm: https://github.com/irrationalagent/forecast_sms 

still definite WIP but right now it:
* predicts hour-by hour. So if you specify 24 hours, it will give predictions for each hour of the next 24 hours
* is not super accurate atm, but I'm confident I can make it much better, this was just a first try. if you pick a random day in the middle of the month and forecast 24 hours out, and compare the 24 hrs of predictions to the actual 24 hrs of data, the prediction at the end of the day ends up being off by about $40. obviously the further out you try to predict the worse it will be, and the closer to the beginning of the dataset you try to predict from the worse it will be (happy to clarify this; tldr more leading data is better)

some questions for @philbooth @jrgm : 
1. it has some python library dependencies (see repo), would this a problem for usage in the real world?
2. what is the most helpful timescale for prediction here? would it help to be able specify days or hours?
3. right now it just spits data to the console, assuming you would use something like this to trigger some kind of alert etc, what format would the inputs/outputs need to be? should it be wrapped in a bash script or something...

**Comment by irrationalagent** [comment]
👍 @jbuck or @jrgm when you get a chance could you pull a few months more of data, maybe starting jan of this year, and send it my way? a few complete months of data might help make predictions a bit better

**Comment by jbuck** [comment]
@irrationalagent I've sent you Jan -> April SMS spend via email

**Comment by philbooth** [comment]
Just including some notes for my own benefit.

https://docs.aws.amazon.com/awssupport/latest/APIReference/API_CreateCase.html

16:32:16 <jbuck> pb: when you're creating them, you need to set the subject line so it's ignored properly
16:32:24 <jbuck> Warning
16:32:24 <jbuck> The AWS Support endpoint creates cases in the production database. Include a subject line such as "TEST CASE--Please ignore" when you call CreateCase for testing, and close the test cases you create by calling ResolveCase.
16:32:35 <jbuck> from https://docs.aws.amazon.com/awssupport/latest/user/Welcome.html#endpoint

**Comment by davismtl** [comment]
@phibooth Doing triage with shane, is this going out in this train or do we move it over?

**Comment by philbooth** [comment]
> Doing triage with shane, is this going out in this train or do we move it over?

I'm literally working on it at the moment, so hopefully this train. (but no promises)

**Comment by philbooth** [comment]
@jbuck is it possible link me to an old ticket where a budget increase was requested? Or if not, can you suggest a standard format / some copy for the script to use when opening tickets?

**Comment by jbuck** [comment]
Yep, feel free to lift from this support ticket:

```
Limit increase request 1 Service: SNS Text Messaging
Resource Type: General Limits
Limit name: Account Spend Threshold Increase for SMS
New limit value: 20000
------------
Use case description: After review of our current usage we will exceed our current limit for this month in a few days. Please see case #4859506511 for implementation details of how we're using SMS - nothing has changed except more users are signing in to Firefox Accounts and ask for the install link for Firefox Mobile.
Link to site or app which will be sending SMS: https://accounts.firefox.com
Type of messages: Promotional
Targeted Countries: AT, AU, BE, CA, DE, DK, ES, FR, GB, IT, LU, NL, PT, RO, US 
```

**Comment by philbooth** [comment]
I've done some work to try and port @irrationalagent's script so that it runs in AWS and creates the support ticket for us. You can see those changes [here](https://github.com/irrationalagent/forecast_sms/compare/master...philbooth:aws-integration?expand=1).

I've had problems actually running those changes in AWS though. I've started a separate discussion in irrationalagent/forecast_sms#2 for those, so that this issue doesn't get bogged down by technical wiff-waffery.

Calling it out here for visibility.

/cc @irrationalagent @jbuck.

**Comment by philbooth** [comment]
Notes from chat with @jbuck just now, so I don't forget over the weekend.

1. It's easy to ensure there are datapoints in dev by sending SMS directly from the AWS console:

   `SNS dashboard > Publish text message (SMS)`

2. The logic for opening a ticket doesn't take into account whether a ticket already exists. Two easy ways round this:

   1. Don't open the ticket, just send email to `fxa-core` instead and let a human open the ticket. Send the email via boto3/SES of course.

   2. Do open the ticket, but include some special text in the subject (e.g. append `(SMS budget automation)` to the subject). Then we can query the open tickets before opening a new one. But this approach is not foolproof and I am a fool, so `i` seems like a preferable option.

**Comment by philbooth** [comment]
Ref: https://github.com/mozilla/fxa-sms-forecast

**Comment by philbooth** [comment]
This is done!

**Comment by shane-tomlinson** [comment]
> This is done!

Hooray!
