### ISSUE TITLE
Investigate the slowest queries

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2934]
These three queries were, by far, the slowest queries leading up to the downtime.  Let's make sure we're not missing any indexes or anything else obvious:

* Call `sessionWithDevice_18`
* Call `accountDevices_16`
* Insert into `tokens`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-443)
┆Issue Number: FXA-443

**Comment by rfk** [comment]
> Call sessionWithDevice_18

This one is called on basically every request from the Browser to FxA, and may be a good candidate for some caching even if the query is already as fast as it can be.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I wonder if these are still the slowest queries
