### ISSUE TITLE
Inconsistent line-height within subscriptions screens vs modals

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#2936]
We should make sure the `line-height` is consistent. We should either increase it where it is lower or decrease it where it is set higher.

Low line-height:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13018240/66870830-e722d380-ef67-11e9-884c-71378ee9a7da.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/13018240/66870845-f0ac3b80-ef67-11e9-9a38-158c14b99fd2.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/13018240/66871223-d161de00-ef68-11e9-95f1-d40d97105913.png">

Modal with higher appearing line-height:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13018240/66870931-23eeca80-ef68-11e9-90cb-06358fbe911d.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13018240/66871447-4cc38f80-ef69-11e9-9373-80978e044bd6.png">

We seem to have `line-height: 185%` (the same as `1.85em`) set on modals. I just checked a Zeplin board and that does seem accurate for those. @ UX, would you like the non-modal copy also set to `1.85` or what would you prefer? We tend to use `1.5` in settings copy.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-445)
┆Issue Number: FXA-445

**Comment by johngruen** [comment]
I’m not in love with the line heights in the modals...maybe we can do 1.5 everywhere?

**Comment by johngruen** [comment]
@johngruen i think i can close this, will confirm
