### ISSUE TITLE
Clean up payments-server Dockerfile

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#2937]
The payments-server Dockerfile changes in https://github.com/mozilla/fxa/pull/2734 involve copying some files over from fxa-shared manually, which may not be the most maintainable long-term solution. Need to clean that file up (and maybe clean up other Dockerfiles, too).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-446)
┆Issue Number: FXA-446

**Comment by dannycoates** [comment]
ref #758
