### ISSUE TITLE
[payments-server] Queue, then Flush Amplitude Metric Events

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2939]
Kinda low priority until there are more events in Payments?

Currently the payments server frontend send one request per Amplitude event.  The shape of the payload already allows for multiple events per request, and there are events that are fired close to each other, e.g. a fetch that resolves quickly would trigger multiple events in quick succession.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-447)
┆Issue Number: FXA-447

**Comment by chenba** [comment]
Since PR #3578, the flush time is used as the event time for Amplitude events.  This issue directly affects that.  We'll need to calculate the event time of each Amplitude event as part of this change.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

don't need this anymore
