### ISSUE TITLE
[payments-server] Listen to Less and/or More Actions for Amplitude Events

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2942]
I've updated the "Subscription Services Metrics Funnels Draft" spreadsheet to note the _current state_ of Amplitude events in payments server.  It's in the "Amplitude Event Notes/Details" sheet.

The current state is less than ideal of course, since we tried to get Amplitude metrics into Train 148 in a very short time.  It serves as starting point to discuss any updates.

cc @johngruen @irrationalagent

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-448)
┆Issue Number: FXA-448

**Comment by clouserw** [comment]
There are some notes on the second sheet: https://docs.google.com/spreadsheets/d/1ttgV60YeurrMhmdlCZ5WNBJXa-PcnRmrGgOEow71E1U/edit#gid=2075361713

@johngruen @irrationalagent is there any work to do here?
