### ISSUE TITLE
“Got it” button from “Why sync multiple devices” dialog does nothing when is opened in a new tab

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2950]
**Build:**
Stage [Train 1.148.3]

**Affected platforms:**
Windows 10 x64

**Steps to reproduce:**
1. Launch Firefox and log in using a Firefox account
2. Navigate to “https://accounts.stage.mozaws.net/sms?service=sync”
3. Right-click on "Why sign in on another device?" link and select “Open Link In New Tab”.
4. Navigate to the new tab and click on “Got it” button.

**Expected results:**
“Why sync multiple devices?” dialog is successfully closed.

 **Actual Results:**
- Nothing happens when clicking on “Got it” button. 
- Modal dialog closes when clicking outside of it.
- "Why sign in on another device?" link from the second tab does nothing on click.

**Additional notes:**
This issue also reproduces when opening the link in new window.

![gotit button](https://user-images.githubusercontent.com/18114210/66909167-f6ac2600-f014-11e9-8761-a92e09d7e1aa.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-450)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15306/issue82.gif">issue82.gif</a>
┆Issue Number: FXA-450

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is still reproducible in "Connect another device" screen which appears after logging using an account that with 2FA enabled. "Why sync multiple devices?" cannot be closed if opened in a new tab by clicking on "Why is more than one device required?"

!issue82.gif!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
