### ISSUE TITLE
Email preferences cannot be saved

### ISSUE THREAD

**Issue by vcarciu** [mozilla/fxa#2952]
Steps to reproduce:
1.Login to FXA with a valid account
2.From Manage Account page, click the Email Preferences blue link
3.Sign in again when asked
4.On Manage your Email Preferences page, Subscribe to some sections(check the Yes checkboxes from all sections)
5.Click Save Preferences button
6.Perform a Sync and then check again the Email Preferences

Expected results:
Email preferences are correctly saved

Actual results:
Email preferences cannot be saved

Please see a video for this issue :
![FXAPreferences](https://user-images.githubusercontent.com/1583842/66921229-69c19680-f02d-11e9-891a-f8338334d49f.gif)

### Environment

FF69, FF71 with Win10x64.

NOTES:
Issue is reproducible in production

**Comment by shane-tomlinson** [comment]
Email preferences are not handled by FxA, rather those are handled by @pmac's team using Basket: https://github.com/mozmeao/basket

**Comment by shane-tomlinson** [comment]
Moved to https://github.com/mozmeao/basket/issues/358
