### ISSUE TITLE
500 Error page after blocking the account which have Two-Factor activated

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2954]
**Build:**
Stage [Train 1.148.3]

**Affected platforms:**
Windows 10 x64
Mac OS X 10.14.6

**Steps to reproduce:**
1.Launch Firefox and log in using a Firefox account
2.Enable Two-Factor Authentication from manage accounts
4.Open multiple fxa related tabs (manage accounts, connect another device option) 
4.Select “Connect another device option”.
5.Enter a phone number and send the message for 6 times to the same number.

**Expected results:**
The user is disconnected from all fxa tabs.

 **Actual Results:**
The others fxa-related tabs return 500 error.
<img width="594" alt="500 error" src="https://user-images.githubusercontent.com/18114210/66933009-1d805180-f041-11e9-8104-8d513f612f71.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-451)
┆Issue Number: FXA-451

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closing as we don't do sms anymore
