### ISSUE TITLE
Navigation issues on "Reset email sent" page

### ISSUE THREAD

**Issue by athomasmoz** [mozilla/fxa#2974]
https://github.com/mozilla-mobile/firefox-tv/issues/2770

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-454)
┆Issue Number: FXA-454

**Comment by clouserw** [comment]
@dannycoates was working on these pages

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
