### ISSUE TITLE
Document how testing works

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2977]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-455)
┆Issue Number: FXA-455

**Comment by clouserw** [comment]
Between https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-tests-circleci and https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/functional-testing I think this is fulfilled.  Did you have more you want to do here @lmorchard ?

**Comment by lmorchard** [comment]
There's a big TBD at the bottom of the "Testing in CircleCI" deep dive:

https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-tests-circleci#circleci-test-content-serversh

I think the "Functional/Selenium Tests" covers some of that, but other parts are pending doco
