### ISSUE TITLE
Update redirect URL for AMO -dev

### ISSUE THREAD

**Issue by willdurand** [mozilla/fxa#298]
Hi,

I work in the AMO team and we would like to update the redirect/confirmation URL sent to a newly created user to point to the edit profile page instead of the homepage (see https://github.com/mozilla/addons-frontend/issues/4376).

How are we supposed to do that? Can you do it for us? I believe no one in our team has access to the OAuth application settings.

Regards,
Will

**Comment by willdurand** [comment]
It turns out that this is actually handled by addons-server, sorry for the noise.

That would be still useful to know how we can update information on our different OAuth apps, because we do not know how to do that anymore...

**Comment by rfk** [comment]
> That would be still useful to know how we can update information on our different OAuth apps

We don't have any self-service UI for doing this on the production db; filing a bug either here or in [our  bugzilla component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Server:%20Firefox%20Accounts) is the right way to go for now.
