### ISSUE TITLE
Sentry error in payments metrics: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2981]
https://sentry.prod.mozaws.net/operations/fxa-payments-dev/issues/6476380/

```
TypeError: Cannot read property 'forEach' of undefined
  File "/app/server/lib/routes/post-metrics.js", line 59, in handler
    events.forEach(event => amplitude(event, request, data));
  File "/app/server/lib/html-middleware.js", line 29, in null.<anonymous>
    next();
...
(5 additional frame(s) were not displayed)
```

**Comment by shane-tomlinson** [comment]
Copying the curl command from the request, the content-type is text/plain. Maybe the preProcess handler isn't being called correctly?

**Comment by shane-tomlinson** [comment]
Hmm, that doesn't make sense, I just tried that in the console and it works as expected.

**Comment by vladikoff** [comment]
@shane-tomlinson the UA is `Firefox/40.0 FxATester/1.0` is it our functional tests?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson the UA is Firefox/40.0 FxATester/1.0 is it our functional tests?

Definitely is, though when I run those locally no problem. They seem to have died off, and were on "-dev", so I'm going to kill this. Maybe this happened on a dev box (mine even?) before we had proper validation.
