### ISSUE TITLE
Fix Subscription Modal Close

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#2982]
Subscription modal dismiss button is 

* too small, should be 24 x 24
* should use an x icon (provided) rather than the letter x
```
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path fill="rgba(12, 12, 13, .8)" d="M9.414 8l5.293-5.293a1 1 0 00-1.414-1.414L8 6.586 2.707 1.293a1 1 0 00-1.414 1.414L6.586 8l-5.293 5.293a1 1 0 101.414 1.414L8 9.414l5.293 5.293a1 1 0 001.414-1.414z"/></svg>
```

**Comment by clouserw** [comment]
Which page does this show up on?

**Comment by johngruen** [comment]
This shows up on support and both payment and subscription settings

**Comment by chenba** [comment]
> too small, should be 24 x 24

but then 

> width="16" height="16"

in the given svg.  ಠ_ಠ 😄

**Comment by LZoog** [comment]
@chenba you can try adding a `viewBox` too:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24px 24px" width="24" height="24">
```

**Comment by chenba** [comment]
@LZoog sorry I don't think I understand what that's supposed to help.

FWIW I'm inlining the svg as a react component so it can be styled through css (or some props).  Changing the size of the svg doesn't scale up the `path`.  Either way, 24x24 looked way too big for the modals.  So I'm just leaving the dimensions as they are for now.

**Comment by chenba** [comment]
Ah, good to know.  I hope I'll remember that if I run into that problem!

**Comment by chenba** [comment]
![image](https://user-images.githubusercontent.com/198055/67891934-998a9700-fb21-11e9-9615-79545dc2aa66.png)

@johngruen that's what it looks like without changing the svg.  The size of the 'X' relative to other elements look reasonable to me.  Let me know if you want bigger.
