### ISSUE TITLE
Email addresses w/ trailing period in local part cause Sentry error

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#2989]
See [#21](https://github.com/mozilla/fxa-private/issues/21)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-458)
┆Issue Number: FXA-458

**Comment by clouserw** [comment]
Link should go to https://github.com/mozilla/fxa-private/issues/21

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

resolved -> expired
