### ISSUE TITLE
Document commit-message format in CONTRIBUTING.md?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#3]
Not sure the best place/file for it.
I like CONTRIBUTING.md since I think GitHub adds a nice yellow banner on the page when you submit a PR saying to read the contribution guidelines.

---

Re: "Document commit-message format in CONTRIBUTING.md",

> @rfk: _"Let's put this in the top-level fxa repo, and link to it from CONTRIBUTING.md"_
> &mdash; via https://github.com/mozilla/fxa-oauth-server/issues/272

**Comment by vladikoff** [comment]
also see https://github.com/mozilla/fxa-content-server/issues/3000

**Comment by vladikoff** [comment]
Added https://github.com/mozilla/fxa/blob/master/CONTRIBUTING.md
