### ISSUE TITLE
Device Controller Basic Information - Sync on FF Devices

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#30]
As a FF user when using Firefox,

I want to know the devices and services I am connected to via my Firefox Account, and important information about my the status of my services. 1a. For devices, this includes last time synced, record counts of different data types, and optionally data storage size (perhaps an option for self-hosters or others?)

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-16
