### ISSUE TITLE
Consider a new page-level loading icon for the content and payment servers

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3003]
Because of the number of redirects we sometimes do, the spinner can wind up looking a bit  janky as it restarts its animation. I wonder if using a static master brand icon would have the same effect as a loading spinner.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-461)
┆Issue Number: FXA-461

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
