### ISSUE TITLE
Add background color to HTML as an embedded style in payment server templates

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3005]
With Payment redirects, there is a white flash on the screen before the background color of the app comes in with the react app...we can fix this by adding

```
    <style>
      body {
        background: hsl(240, 60%, 99%);
      }
    </style>
```
to the index template. @shane-tomlinson i believe you gave the okay for adding embedded styles here?

**Comment by shane-tomlinson** [comment]
>  @shane-tomlinson i believe you gave the okay for adding embedded styles here?

Ya, should be good to go on the payments server.
