### ISSUE TITLE
test failures on latest: support form with an active suscription - *

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3009]
STR: 

1. Go to content server package.
2. `npm run test-latest -- --grep="support form with an active subscription"`

Screenshot saved at: https://screencap.co.uk/images/c9adb4682c90deb948c361a0e53612153aebaf03.png
> × firefox on mac 18.7.0 - support form with an active subscription - go to support form, submits the form (27.821s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/4ec9ed17-ebfa-4f4f-8c39-bf35e69058c6/element / {"using":"css selector","value":"div.product-payment"}] Unable to locate element: div.product-payment
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '10.239.30.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:191:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.parent.get.setFindTimeout.then.then @ tests/functional/lib/helpers.js:1377:30
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1375:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1381:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:2385:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.go to support form, submits the form [as test] @ tests/functional/support.js:71:10
      @ src/lib/Test.ts:263:51

Screenshot saved at: https://screencap.co.uk/images/65524f4f6e47ec6c6d98cd8b2c351ffca7cd50a8.png
> × firefox on mac 18.7.0 - support form with an active subscription - go to support form, cancel, redirects to subscription management (26.794s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/4ec9ed17-ebfa-4f4f-8c39-bf35e69058c6/element / {"using":"css selector","value":"input[type=email]"}] Unable to locate element: input[type=email]
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '10.239.30.176', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:205:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:210:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:308:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1520:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.go to support form, cancel, redirects to subscription management [as test] @ tests/functional/support.js:98:10
      @ src/lib/Test.ts:263:51

blocks #2877 

cc @lmorchard, @bbangert

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-462)
┆Issue Number: FXA-462

**Comment by chenba** [comment]
Looks like subhub for that env isn't working?  https://latest.dev.lcip.org/auth/v1/oauth/subscriptions/plans and https://latest.dev.lcip.org/auth/v1/oauth/subscriptions/customer are returning 500s.

**Comment by johngruen** [comment]
Let's discuss this in tomorrow's x-functional

**Comment by shane-tomlinson** [comment]
I see this on Circle today too:



    Screenshot saved at: https://screencap.co.uk/images/077a1ae07983deac32f5a17cae54dad8075484e4.png
    × firefox on linux 4.15.0-1052-aws - support form with an active subscription - go to support form, submits the form (28.028s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/f96b4743-3740-45bb-9597-0e385c0bb7dd/element / {"using":"css selector","value":"#splash header h1"}] Unable to locate element: #splash header h1
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: '9b4e2edac972', ip: '172.27.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1052-aws', java.version: '11.0.5'
    Driver info: driver.version: unknown
    at Command. @ tests/functional/lib/helpers.js:2044:6
    at Command. @ tests/functional/lib/helpers.js:61:10
    at Command. @ tests/functional/lib/helpers.js:75:18
    at Command. @ tests/functional/lib/helpers.js:69:10
    at Command. @ tests/functional/lib/helpers.js:2463:6
    at Command. @ tests/functional/lib/helpers.js:61:10
    at Command. @ tests/functional/lib/helpers.js:69:10
    at Test.go to support form, submits the form [as test] @ tests/functional/support.js:65:10
    @ src/lib/Test.ts:263:51

    Screenshot saved at: https://screencap.co.uk/images/077a1ae07983deac32f5a17cae54dad8075484e4.png
    × firefox on linux 4.15.0-1052-aws - support form with an active subscription - go to support form, cancel, redirects to subscription management (26.866s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/f96b4743-3740-45bb-9597-0e385c0bb7dd/element / {"using":"css selector","value":"#splash header h1"}] Unable to locate element: #splash header h1
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: '9b4e2edac972', ip: '172.27.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1052-aws', java.version: '11.0.5'
    Driver info: driver.version: unknown
    at Command. @ tests/functional/lib/helpers.js:2044:6
    at Command. @ tests/functional/lib/helpers.js:61:10
    at Command. @ tests/functional/lib/helpers.js:75:18
    at Command. @ tests/functional/lib/helpers.js:69:10
    at Command. @ tests/functional/lib/helpers.js:2463:6
    at Command. @ tests/functional/lib/helpers.js:61:10
    at Command. @ tests/functional/lib/helpers.js:69:10
    at Test.go to support form, cancel, redirects to subscription management [as test] @ tests/functional/support.js:94:10
    @ src/lib/Test.ts:263:51


It's redirecting to what looks like the mozilla.org home page.

@lmorchard - any ideas?

**Comment by chenba** [comment]
> It's redirecting to what looks like the mozilla.org home page.

It should be redirecting to 123Done Pro after a successful subscription.  Not sure why it's landing on mozilla.org.

**Comment by lmorchard** [comment]
Hmm, this might be related to changes we just merged that moved the download redirect URL into Stripe product metadata. Will take a look

**Comment by lmorchard** [comment]
>I see this on Circle today too:

@shane-tomlinson It looks like the screencaps from the issue description are 404s now - is this all the same issue that's been failing in same way since October? Or is this something new?

**Comment by chenba** [comment]
> is this all the same issue that's been failing in same way since October? Or is this something new?

This issue is for a different failure, where the tests cannot even subscribe to a product. 

https://github.com/mozilla/fxa/issues/3009#issuecomment-559079705 are tests that errored out waiting for the 123Done Pro redirect after successful subscriptions.

**Comment by chenba** [comment]
Filed https://github.com/mozilla/fxa/issues/3502 to fix successful sub verification in those tests.

**Comment by lmorchard** [comment]
Is this still an issue?

**Comment by chenba** [comment]
Sure looks like it.

@jrgm Is `latest` suppose to have a working instance SubHub?

**Comment by clouserw** [comment]
The architecture 2.0 plan may affect this.

We should stub our calls to external APIs (both subhub and stripe).

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

No longer an issue.
