### ISSUE TITLE
Open email provider button from confirmation page looks like the wrong color

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3014]
I noticed this today while working on email-first everywhere changes:

<img width="609" alt="Screenshot 2019-10-18 at 14 22 45" src="https://user-images.githubusercontent.com/848085/67098333-e54d5000-f1b3-11e9-8d1e-eb1ecb33bf9c.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-463)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16014/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-463

**Comment by clouserw** [comment]
Should the gray button be blue? @ryanfeeley

**Comment by vbudhram** [comment]
from mtg: Should this match our other buttons? I think so, @ryanfeeley thoughts?

**Comment by ryanfeeley** [comment]
@vbudhram Not sure why this became grey. Should be the default white on Photon blue.

**Comment by shane-tomlinson** [comment]
With the move to codes, is this going to be moot? I suppose we'll still show the button on /confirm_reset_password and /confirm_secondary_email.

**Comment by ryanfeeley** [comment]
@shane-tomlinson You bring two good points:
1. We should start using codes for reset too. Are there other opportunities to replace links?
2. We should probably return the link to open the email provider. How about something like this:
![image](https://user-images.githubusercontent.com/68213/69810358-b2867680-11b9-11ea-95ec-a2aeaa6216cc.png)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This button is gone now.

!screenshot-1.png|thumbnail!
