### ISSUE TITLE
Circle builds should run `npm ls --production` in a container of the production image

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#302]
Ref: https://github.com/mozilla/fxa-customs-server-private/issues/49#issuecomment-400872826

It passed the tests and was pushed to docker hub, but couldn't actually start.

Proposed: all fxa circle.yml run the command:

  `docker run --rm -it productionimagename npm ls --production`

and fail the circle run if $? is non-zero

**Comment by jrgm** [comment]
Interestingly, the rebuild of v1.115.1 was also missing this module due to stale shrinkwap. So, this could save a lot of churn.

**Comment by jrgm** [comment]
for mozilla/fxa-content-server, that installs `webpack`, which has an optional dependency on fsevents, which is an osx only modules so it doesn't install on docker linux. However, `npm ls --production` considers this missing optional dependency, and all its child dependencies, as error and will exit 1. Which snookers the idea of using `npm ls --production` to check from real missing module dependencies.

**Comment by vladikoff** [comment]
This was done with new Circle 2 updates
