### ISSUE TITLE
instrument a metric event for when a user clicks "start browsing"

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#3022]
There is now a "start browsing" link on the bottom of the "connect another device" screen that a user can click to open a new tab. we should instrument an engage or submit event when a user clicks this. this will help us know how many additional mobile users we may be foregoing. 

i do not see any pre-existing event that would count this https://sql.telemetry.mozilla.org/queries/65451/source we have events for connect a device engage/submit but those are too general

cc @davismtl @ksiegler1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-465)
┆Issue Number: FXA-465

**Comment by shane-tomlinson** [comment]
@irrationalagent - Is this counted by the [link.mozilla.org event](https://github.com/mozilla/fxa/blob/74f6f333c5d687a4b740238f53c8b119553f0037/packages/fxa-content-server/app/scripts/templates/sms_sent.mustache#L27)?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~loines@mozilla.com] is this still something you need?
