### ISSUE TITLE
(payments) Store and display card type from `/customer` endpoint

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3037]
It does not look like our `/customer` endpoint stores card type (Visa, MasterCard etc.).

This may need a follow up issue if we separate front-end from back-end here, but we need this in place to 1) display the card type (text) in the resubscribe confirmation modal (in `SubscriptionItem.tsx`) and 2) an image for the card type when the user is updating their payment method (in `PaymentUpdateForm.tsx`). Both of these have a related “TO DO” comment above them.

![image](https://user-images.githubusercontent.com/13018240/67218188-8d992980-f3eb-11e9-94ec-a83d21b433be.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-466)
┆Issue Number: FXA-466

**Comment by lmorchard** [comment]
Yeah, this needs to get plumbed all the way back to the subhub API layer - the card type isn't available for us to include in the auth-server API on our side.

**Comment by LZoog** [comment]
👍 Does that mean we'll need to transfer this to subhub, then create a separate issue for front-end implementation here + make a separate API call just to display this?

**Comment by lmorchard** [comment]
This has come up again as a need in the tiered subscription UX (#3241) that wants to display a card image. However, [it looks like subhub has added `brand` to the customer data](https://github.com/mozilla/subhub/search?q=brand&unscoped_q=brand), so we should take a look at adding the plumbing on our end.

**Comment by lmorchard** [comment]
[Filed a related issue over on subhub](https://github.com/mozilla/subhub/issues/377).

**Comment by lmorchard** [comment]
We might also have to dig around a bit for an acceptable set of icons - [doesn't seem like Stripe offers something like a convenient ZIP file of icons](https://support.stripe.com/questions/where-to-find-logos-for-accepted-credit-card-types).

Looks like [the expected values for `brand` are](https://stripe.com/docs/api/cards/object#card_object-brand) `American Express`, `Diners Club`, `Discover`, `JCB`, `MasterCard`, `UnionPay`, `Visa`, or `Unknown`.

**Comment by LZoog** [comment]
One approach when we get the icons could be parsing `brand` by lowercasing and substituting spaces with dashes and add it as a `className` like ```<span className={`brand-${brandClass}`} aria-label={brand}></span>``` and adding the icon as a background-image in CSS.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

we're gonna refile w/ arch 2.0
