### ISSUE TITLE
Firefox iOS: Enable SUMO/help links

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#3047]
#  Description

On Firefox iOS, we now open a secondary webview to enable showing help links: https://github.com/mozilla-mobile/firefox-ios/pull/5639

If the class`visible-url` is removed from help links, they will open in an overlay webview as they already have `target=_blank`. The target attribute must not be removed of course, we need them to open in a new window. 

### Steps to reproduce

Currently, help links are displayed in full and are not tappable.

### Expected result

Tapping help links triggers target=_blank behaviour and opens them in an overlay webview. Pressing back on the overlay webview closes it and returns the user to the FxA webview.

**Comment by vladikoff** [comment]
patch in https://github.com/mozilla/fxa/pull/3048
