### ISSUE TITLE
Payments metrics missing `time` key

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3050]
Payments data on stage is not showing up in amplitude because of a missing `time` key.

This field is required because amplitude uses it to construct its time series.

**Comment by 6a68** [comment]
Looks like the server should handle this field: https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/flow-event.js#L84 (thx @chenba for digging this up)

**Comment by 6a68** [comment]
For reference, the validation happens in the fxa-amplitude-send code ([source](https://github.com/mozilla/fxa-amplitude-send/blob/master/pubsub/index.js#L244-L250)):
```js
function isEventOk (event) {
  return (
    is.nonEmptyString(event.device_id) ||
    is.nonEmptyString(event.user_id)
  ) &&
    is.nonEmptyString(event.event_type) &&
    is.positive(event.time)
}
```

**Comment by chenba** [comment]
Reopening because the bug was not fixed with #3053.  https://github.com/mozilla/fxa/pull/3053/files/6c3fe91c4b44815a671ccdf1fd01374fca6a0861#r339762628 is likely the problem.

**Comment by jbuck** [comment]
#3217 did not fix this unfortunately:

```
{
   app_version: "149.4"    
   device_id: "35722378809846dc95c64b568f58a179"    
   event_properties: "{}"    
   event_type: "fxa_subscribe_manage - view"    
   op: "amplitudeEvent"    
   os_name: "Mac OS X"    
   os_version: "10.14.6"    
   session_id: "1572906129533"    
   user_properties: "{"flow_id":"e4b9476a5b9e39e9f332f0351c2232718b252e78bde3fcdf288feca8edc1e071","ua_browser":"Chrome","ua_version":"78.0.3904"}"    
  }
```

**Comment by 6a68** [comment]
Looks like the amplitude post-metrics endpoint assumes the performance data points are available to calculate the offset, but on the payments server, that data's not currently included in the request. Working on a fix.
