### ISSUE TITLE
Registration: prevent repeating password if first entry is invalid?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3051]
Should we prevent users from repeating their password in the second field if what they entered in the first password field is invalid? I'm tempted to say yes, we should prevent input in the second field until conditions are met in the first field.

@ryanfeeley thoughts?

![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/70a5a333-d23e-47c2-82c7-ae4e173dca5b)

(somewhat related to: https://github.com/mozilla/fxa/issues/631)

**Comment by LZoog** [comment]
Per #607, @ryanfeeley appears to like this option too.

@shane-tomlinson probably already has an idea of how this would work, but I think a potential awkwardness could be if someone tries to tab from the first field and ends up in the "age" field. Is it going to be obvious it's disabled, or can the user click into it and they just can't type? Is there a tooltip that would show up if it's focused or will it just not be focusable?

**Comment by davismtl** [comment]
Shane and Lauren are working on this together. Lauren will take it over.

I am behind on feature document, I'll try to catch up today or tomorrow.

**Comment by davismtl** [comment]
from discussions with @ryanfeeley @LZoog and @vbudhram 

If the password in the first password field is invalid (does not meet criteria), refocus on that first password field. Avoid users from repeating their password in the second field.

This will keep the behavior consistent with the work @vbudhram is doing with inline password validation. In his case, if the passwords don't match, he refocuses on the repeat password field.

**Comment by davismtl** [comment]
Removing epic from this since I don't think we need an feature document for auto-focusing a field if it's contents our invalid.

**Comment by davismtl** [comment]
Per our discussions here: https://github.com/mozilla/fxa/issues/631#issuecomment-555591960

We will not work on this because we can't find a UX experience that seems ideal. There are already a few problems being highlighted caused by refocusing fields..
