### ISSUE TITLE
Improve string: "Get more from these features"

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3054]
We currently refer to Firefox, Lockwise, Monitor and Send as *features* when most of them are actually standalone products.

See:
![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/7385d7f2-2b36-4aa9-a489-e3ac01684903)

Can we just change "Get more from these features" to "Get more from:" ??

I'd want to improve some of the other copy but this would be an awesome start.
CC @ryanfeeley @jpfaller

**Comment by jpfaller** [comment]
What about:

Get more with an account:

or

Sign up to get more features:
(if we went this route, I'd want to change the copy under each item)

Firefox Browser
Sync your bookmarks, passwords, and more on every device.

Firefox Lockwise
Securely access passwords saved in Firefox anywhere — even outside of the browser.

Firefox Send
Send larger files securely and privately.

**Comment by davismtl** [comment]
I love these! The value proposition is very clear.
