### ISSUE TITLE
Run a/b to test putting the progress meter back at the top of registration forms

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3056]
Last week, @ryanfeeley , @dannycoates , @irrationalagent and I met to review the impact of the train 146 release on our registration form submissions.

The drop in form submit rates can be observed here (Sept 30th):
https://analytics.amplitude.com/mozilla-corp/chart/npkmd4u

We identified various things that might have contributed to the drop.

One of those things was the removal of the progress bar at the top of the registration form that showed that it was just 3 steps to register. In past experiments I've run for other companies, progress bars improved conversion rates so I believe the removal likely contributed to the drop in registrations.

We removed this because we needed the vertical room to restore "to continue to [service_name]".

Let's run a test where we restore the progress bar. If we are concerned about the vertical height, we could put "change email" to the right of the email and rename it to just "edit" or "change".

I'll make this an epic so that I make a small feature doc to track this little experiment (and so we track this in the product board).

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-471)
┆Issue Number: FXA-471

**Comment by chenba** [comment]
@davismtl is this ready?  Still `need:ux`?  And "progress bar" here is referring to the one removed in https://github.com/mozilla/fxa/commit/2e060aa ?

**Comment by chenba** [comment]
Hmm with email-first, we don't know if it's sign-up or sign-in on the first step.  How should we handle that?

**Comment by davismtl** [comment]
Let's pause on this one. Ryan Feeley and I haven't decided the right path forward here.

**Comment by clouserw** [comment]
epics are tracked in jira
