### ISSUE TITLE
Run A/A Test to Ensure we are properly bucketing our experiments

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3057]
Lately, when we deployed a winning A/B test, it didn't quite perform as expected in release. The experiment was run on all locales and had statistical significance so there's not much reason for there to be a difference.

During a retrospective around the feature release, @irrationalagent proposed running an A/A test to make sure our treatment bucketing and controls are working properly.

CC @vbudhram 

(I'll make this an epic so we can track in the product board)

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-472)
┆Issue Number: FXA-472

**Comment by clouserw** [comment]
epics are tracked in jira
