### ISSUE TITLE
Investigate Connect Another Device Performance Changes with Train 146

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3059]
The release of Train 146 saw a drastic drop in the number of users connecting another device. [1] We were convinced this was due to the codes. However, I am now almost certain it is because of our flow standardization work that shipped at the same time.

There was not as much of a noticeable drop on about:welcome. In fact, about:welcome dropped more predictably to align more with what we saw during our A/B test relating to codes. [2] That is, the rate went down but the volume remained constant.

We, however, observed the drop on about:welcome when we shipped trailhead. [3] This confirms my suspicion that the flow standardization had a negative impact on this step.

Let's identify what changed on this screen and determine what should be reverted back.

[1] https://analytics.amplitude.com/mozilla-corp/chart/m5ocsgt
[2] https://analytics.amplitude.com/mozilla-corp/chart/m5ocsgt/edit/x377ulf
[3] https://analytics.amplitude.com/mozilla-corp/chart/m5ocsgt/edit/dce78h5

CC @irrationalagent @dannycoates @vbudhram @ryanfeeley

**Comment by davismtl** [comment]
This chart shows that the connect another device page (specifically) drastically dropped with that release:
https://analytics.amplitude.com/mozilla-corp/chart/new/abj7glo

Note that we also added a "start browsing" button. This also likely contributed to the drop.

**Comment by davismtl** [comment]
Small clarification: we also observed the drop for users on about:welcome
https://analytics.amplitude.com/mozilla-corp/chart/new/0c5un5w

If this is correct then the above analysis might be missing something.

According to this document, these are the changes between pre-trailhead, trailhead and skyline:
https://mozilla.invisionapp.com/share/K3T84L9XRM6#/screens

For CAD, here is skyline vs trailhead:
![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/44eae501-5cd8-42e1-adae-a4cd82742e2f)

**Comment by davismtl** [comment]
The login flows of about:welcome also observed a big drop in the use of the CAD page:
https://analytics.amplitude.com/mozilla-corp/chart/new/5ozt6v8

Since codes were not released to logins, it leads to something else breaking.

**Comment by davismtl** [comment]
> We, however, observed the drop on about:welcome when we shipped trailhead. [3] This confirms my suspicion that the flow standardization had a negative impact on this step.

> https://analytics.amplitude.com/mozilla-corp/chart/m5ocsgt/edit/dce78h5

This chart shows just the CAD form submit also dropping with trailhead on about:welcome:
https://analytics.amplitude.com/mozilla-corp/chart/new/eqd2fud

Though little has changed, in that same chart, we see it drop again train 146.

**Comment by davismtl** [comment]
It might be that less people are seeing the connect another device page altogether now:
https://analytics.amplitude.com/mozilla-corp/chart/new/av34kwk

Not visible in the Invision doc is that we also added "Enable Sync" rather than continue.

![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/d1bf0198-2ec0-4eb6-9883-e52ffbbe9cfb)


We now have half the number of users seeing the CAD page.

**Comment by davismtl** [comment]
@irrationalagent is helping me investigate. There might be a metrics bug involved here:

See the drop in rate:
https://analytics.amplitude.com/mozilla-corp/chart/new/reilpq4

Observe that there is little change in volume:
https://analytics.amplitude.com/mozilla-corp/chart/new/s4fh1b0

Something's probably broken.

**Comment by irrationalagent** [comment]
So @davismtl the weird thing about the comparison between those two charts ^ is that there are more CAD views than registrations (because you get CAD on login and you can also see it on its own now via the toolbar menu), so the funnel chart really shows that the number of CAD views AFTER REGISTRATION has gone down, even though number of views overall has held relatively steady. So, there's not necessarily an inconsistency there and would be consistent with the number of views after registration actually going down.

Will dig in more...

**Comment by irrationalagent** [comment]
[This chart](https://analytics.amplitude.com/mozilla-corp/chart/new/l6memzl) is somewhat revealing.

It shows that the entrypoints in the browser (menupanel and preferences) that are still hard-coded to hit the /signin endpoint (see screenshot) have not seen a drop in the number of views of the CAD screen after registration

<img width="773" alt="image" src="https://user-images.githubusercontent.com/5625313/67340168-0c748c00-f4ea-11e9-9d9c-37e3325ac930.png">

This tilts toward the hypothesis that the cause is the new flow, not the codes (still TBD if its a metrics thing or if its actually not being displayed) @davismtl

**Comment by irrationalagent** [comment]
Couple more things... 
1. Are we doing anything weird/different in the new flow for tier 1 locations? they seem to be hit harder than others https://analytics.amplitude.com/mozilla-corp/chart/hkqshb4
2. [This is me signing in with a test account](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D118309607380) it doesn't show the CAD view event even though i DID see it when i signed in. n = 1 in favor of metrics bug.

**Comment by davismtl** [comment]
> Are we doing anything weird/different in the new flow for tier 1 locations? they seem to be hit harder than others https://analytics.amplitude.com/mozilla-corp/chart/hkqshb4

Not that I know of.

@dannycoates @vbudhram have any ideas to help me and Leif?

**Comment by vbudhram** [comment]
> Are we doing anything weird/different in the new flow for tier 1 locations?

I am not aware of anything either. Most (if not all) tier 1 locations have SMS enabled so should be shown the screen.

> This is me signing in with a test account it doesn't show the CAD view event

Hmm from https://github.com/mozilla/fxa/pull/3075#issue-331133693, I didn't see any view metrics being sent for CAD. I can dig into this a little more to see what might have changed it.

```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email_first - view","time":1571768122592,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment"]}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email_first - engage","time":1571768132157,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment"]}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email_first - submit","time":1571768134428,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment"]}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - view","time":1571768134557,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment"]}}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - engage","time":1571768141002,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - submit","time":1571768145314,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - cwts_view","time":1571768145914,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - cwts_submit","time":1571768147381,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - signup_code_view","time":1571768147388,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - signup_code_engage","time":1571768155257,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - signup_code_submit","time":1571768156574,"device_id":"62b46fd8d375478e839764fb8bc8bcc0","session_id":1571768121760,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"b7a0a173cdf78bc871a45eb73da92852dda94c636d2d282e188371c2bc2fa042","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","signup_code_treatment","token_code_treatment_code"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
```

**Comment by vbudhram** [comment]
> I can dig into this a little more to see what might have changed it.

I can confirm that verifying an account via link logs the connect device metric

```
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email_first - view","time":1571943858507,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code"]}}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email_first - engage","time":1571943861256,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code"]}}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email_first - submit","time":1571943870584,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code"]}}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - view","time":1571943872129,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code","signup_code_control"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - engage","time":1571943874460,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code","signup_code_control"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - submit","time":1571943878768,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code","signup_code_control"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - cwts_view","time":1571943879419,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code","signup_code_control"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - cwts_submit","time":1571943880979,"device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","$append":{"fxa_services_used":"sync","experiments":["email_first_treatment","token_code_treatment_code","signup_code_control"]},"sync_engines":["bookmarks","history","passwords","addons","tabs","prefs"]}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_email - click","time":1571943897056,"user_id":"b14fee79079b41d0a1a771a839153cac","device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync","email_type":"registration","email_provider":"other"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
11|content-server PORT 3030  | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_connect_device - view","time":1571943897357,"user_id":"b14fee79079b41d0a1a771a839153cac","device_id":"d47e431df62a4e32a1a746c2b55c1982","session_id":1571943853631,"app_version":"148","language":"en","os_name":"Mac OS X","os_version":"10.14","event_properties":{"service":"sync","connect_device_flow":"sms"},"user_properties":{"entrypoint":"fxa_discoverability_native","flow_id":"2805e57ef3b5ab23a16bb38c9b474a4926c7ee8e4af5606e25873b611bae5ad6","ua_browser":"Firefox","ua_version":"70.0","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","$append":{"fxa_services_used":"sync"}}}
```

**Comment by davismtl** [comment]
Thanks @vbudhram for catching that. This answers part of the problem we're observing. 

Unfortunately, it still doesn't explain why we'd see desktop registrations > mobile login drop so drastically since the CAD is not in this funnel:

https://analytics.amplitude.com/mozilla-corp/chart/m5ocsgt

**Comment by shane-tomlinson** [comment]
@irrationalagent, @vbudhram and @shane-tomlinson - we are tagged to figure out what could be causing this drop.

**Comment by irrationalagent** [comment]
Putting some notes in here, no definite causes yet:

1. For users that register then login to mobile within a day, we appear to be missing some content server events during the mobile login flow. many users look [like this](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D115139389123) and in [this chart](https://analytics.amplitude.com/mozilla-corp/chart/new/am6v1x6) we can see that there are actually more login complete events than login form views, which should not be possible. Note that this is [not true generally](https://analytics.amplitude.com/mozilla-corp/chart/new/h8dvh2z), it only seems to be true of users who registered the same day that they kick off the login flow. 

2. [this shows my attempt to reproduce #1](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D118772178701). i do have the content server events, but they were "added late" if you look at the timestamp for the login view event:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/5625313/67597246-eccaa700-f727-11e9-95a2-497c168089e4.png">

and compare the timestamps for the login complete event:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/5625313/67597287-0c61cf80-f728-11e9-857c-672173aee8f4.png">

so it seems that the content server is slower to funnel the events to amplitude than the auth server is. this isn't necessarily a problem in and of itself, since amplitude uses the client time to order the events, but I want to be sure that this slowness would not lead to content server events going missing in some cases

**Comment by irrationalagent** [comment]
We have had a [small decline](https://analytics.amplitude.com/mozilla-corp/chart/new/7qmcvlz) in the number of SMS sent after registration since train 146. (21.3% down from 24.1%). I calculated that this would explain 20% of the difference between the pre-train 146 and post-train 146 mobile login rates after registration.

So, the styling changes to the SMS form may have had an actual, real effect on the mobile login rate, but so far I don't think it explains the entire drop [in this chart](https://analytics.amplitude.com/mozilla-corp/chart/m5ocsgt)

**Comment by davismtl** [comment]
> so it seems that the content server is slower to funnel the events to amplitude than the auth server is. this isn't necessarily a problem in and of itself, since amplitude uses the client time to order the events, but I want to be sure that this slowness would not lead to content server events going missing in some cases.

So long as the time stamps are accurate, there is no problem. If the delay is causing innacurate timestamps, then there is a problem.

**Comment by irrationalagent** [comment]
I returned to the hypothesis the that links were driving some mobile logins, due to the fact that confirming registration on the phone would show you the CAD screen. We then might be losing some logins because we lost that path entirely.

[This chart](https://analytics.amplitude.com/mozilla-corp/chart/ldwmqhp) shows the following step s, **among users whose registration was attributed to desktop**

1. reg - created on desktop (successful pw & email submit)
2. email confirmed on mobile
3. CAD view on mobile
4. Login on mobile

We had about 20k logins to mobile due to this path in sept, up until the point it was removed entirely. Next step is to understand how much of the overall reg on desktop -> login on mobile drop this can explain. But, I feel confident that this is decent chunk of it.

**Comment by davismtl** [comment]
Interesting 🤔

> This chart shows the following steps, among users whose registration was attributed to desktop

That's a good chart. Good context.

> But, I feel confident that this is a decent chunk of it.

If we lost 100% of those users (as in none of them would use the CAD flow on desktop instead, which would be very unlikely) then it would represent 2/3 of the loss we're seeing.

In other words, that would account for *at most* 2/3 of the loss of desktop to mobile. In practice, it may be closer to 1/2 since I'm sure we're forcing some through the desktop CAD flow instead.

**Comment by davismtl** [comment]
> In other words, that would account for at most 2/3 of the loss of desktop to mobile. In practice, it may be closer to 1/2 since I'm sure we're forcing some through the desktop CAD flow instead.

@irrationalagent Can you reverify how that compares to the initial A/B test?

**Comment by irrationalagent** [comment]
> > In other words, that would account for at most 2/3 of the loss of desktop to mobile. In practice, it may be closer to 1/2 since I'm sure we're forcing some through the desktop CAD flow instead.
> 
> @irrationalagent Can you reverify how that compares to the initial A/B test?

[I'd say its roughly consistent with the drop there](https://analytics.amplitude.com/mozilla-corp/chart/new/izv8t0f) which was a little less than half of the drop that we ultimately observed in production. So the evidence so far is that drop we observed in the A/B test was due to the loss of CAD on mobile after confirmation on mobile. We've also see an 2.6% (absolute) drop in the number of users sending an SMS after registration. Given that ~18.5% of users who send an sms login on mobile, this would explain an additional 0.4% (absolute) of the drop in production. Combined with the above that still only explains about 1.6%-1.8% out of the total 2.87% absolute drop (depending on how much credit you give to the loss of CAD on mobile).

**Comment by davismtl** [comment]
@irrationalagent perhaps this provides clues to the missing pieces. CAD after login seemed to have drop after train 146. There was however no codes for login with that release:
https://analytics.amplitude.com/mozilla-corp/chart/3p8eyj5

While the decrease is much smaller on about:welcome, it is still noticeable there too.
https://analytics.amplitude.com/mozilla-corp/chart/3p8eyj5/edit/nmqbzfn

**Comment by irrationalagent** [comment]
@ksiegler1 & I are compiling analysis in [this doc](https://docs.google.com/document/d/15LyHLE3e4BnQxspTKEtRw7olQPRHSgdAe3s_z9W_uvc/edit#)
