### ISSUE TITLE
replace uses of node-ass coverage tool with modern tools, if/where they still exist.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#306]
In reference to https://github.com/jrgm/ass/pull/1, that was my fork of lloyd's tool for code coverage. Better ways to do that these days, and porting the binary dependencies in that repo adds no value.

Most places it is/was used, you can set NO_COVERAGE=1 to skip these tests.

So a meta bug to remove this dependency from wherever else it is still used.

**Comment by vladikoff** [comment]
None of the FxA repos have it AFAIK

**Comment by pdehaan** [comment]
I did a quick scan of the following repos and didn't see it used in the following repos:

- mozilla/fxa
- mozilla/fxa-amplitude-send
- mozilla/fxa-auth-db-mysql
- mozilla/fxa-auth-server
- mozilla/fxa-basket-proxy
- mozilla/fxa-brickftp-copy
- mozilla/fxa-bugzilla-mirror
- mozilla/fxa-checkbox
- mozilla/fxa-common-password-list
- mozilla/fxa-content-server
- mozilla/fxa-crypto-relier
- mozilla/fxa-customs-server
- mozilla/fxa-easter-egg
- mozilla/fxa-geodb
- mozilla/fxa-js-client
- mozilla/fxa-jwtool
- mozilla/fxa-oauth-client
- mozilla/fxa-oauth-console
- mozilla/fxa-oauth-server
- mozilla/fxa-profile-server
- mozilla/fxa-reconcile-with-salesforce
- mozilla/fxa-relier-client
- mozilla/fxa-sendgrid-event-proxy
- mozilla/fxa-shared
- mozilla/fxa-webpagetest-driver
- mozilla/fxa-webrtc-idp
- mozilla/hapi-fxa-oauth

<details>
<summary>In fact, here's my garbage scanner...</summary>

```js
const got = require("got");
const meow = require("meow");

const cli = meow(`Usage: $ node index [package.name]`);

const FXA_REPOS = [
  "fxa",
  "fxa-amplitude-send",
  "fxa-auth-db-mysql",
  "fxa-auth-server",
  "fxa-basket-proxy",
  "fxa-brickftp-copy",
  "fxa-bugzilla-mirror",
  "fxa-checkbox",
  "fxa-common-password-list",
  "fxa-content-server",
  "fxa-crypto-relier",
  "fxa-customs-server",
  "fxa-easter-egg",
  "fxa-geodb",
  "fxa-js-client",
  "fxa-jwtool",
  "fxa-oauth-client",
  "fxa-oauth-console",
  "fxa-oauth-server",
  "fxa-profile-server",
  "fxa-reconcile-with-salesforce",
  "fxa-relier-client",
  "fxa-sendgrid-event-proxy",
  "fxa-shared",
  "fxa-webpagetest-driver",
  "fxa-webrtc-idp",
  "hapi-fxa-oauth"
];

async function fetchPackage(name) {
  try {
    const {body} = await got(`https://rawgit.com/mozilla/${name}/master/package.json`, {json:true});
    return body;
  } catch (err) {
    console.error(`${name}: ${err.message}`);
    process.exitCode = 1;
    return {};
  }
}

async function getDeps(name) {
  const {dependencies, devDependencies} = await fetchPackage(name);
  return Object.keys({...dependencies, ...devDependencies}).sort();
}

async function main(names) {
  if (names.length === 0) {
    cli.showHelp();
  }
  for (const repo of FXA_REPOS) {
    const dependencies = await getDeps(repo);
    for (const name of names) {
      if (dependencies.includes(name)) {
        console.log(`${repo} uses "${name}"`);
      }
    }
  }
}

main(cli.input);
```
</details>
