### ISSUE TITLE
Subscription is created even though UI claims it failed

### ISSUE THREAD

**Issue by stlhood** [mozilla/fxa#3061]
## Description

When attempting to create a subscription in production, in certain scenarios an unfriendly error modal will be displayed indicating that the subscription failed. However, the subscription *is* created in Stripe.

### Steps to reproduce

In production, attempt to create a new subscription using a credit card that is already associated with another subscription.

### Expected result

- Card reuse is not permitted (due to fraud concerns), so the customer should see a user-friendly error.
- A subscription should not be created.
 
### Actual result

- A user-hostile error is shown indicating that the subscription failed.
- A subscription is created in Stripe, anyway.

![image](https://user-images.githubusercontent.com/42821/67259594-8efa3e80-f44b-11e9-8d50-6b3d9b7cb0ad.png)

Example user to investigate: slangtonhood+vpn4@mozilla.com

**Comment by johngruen** [comment]
This error comes from the fxa-auth-server

**Comment by lmorchard** [comment]
> This error comes from the fxa-auth-server

It does, but it could be auth-server relaying an error from subhub - do we have any error messages from any server logs?

**Comment by lmorchard** [comment]
@marty331 We probably need more information for this, but any chance we can find an error related to this issue from subhub prod logs?

**Comment by johngruen** [comment]
Maybe related to #3106...

Note @davismtl reports a canadian  Zip hack where you append 2 zeros to the canadian post code...looking at Stripe logs, this seems to work...the `address_zip_check` on Alex' XXX00 zip code passed.

In the meantime @stlhood added radar so international CCs should be rejected

**Comment by marty331** [comment]
@lmorchard the call did not result in an error on the SubHub side, we are currently getting a PR together to log successful responses to help support these issues.

**Comment by snowmanco** [comment]
this issue occurred to for me this morning: 

I started at fpn.firefox.com/vpn and clicked subscribe, and created a new FXA account (boneill+paidvpnprod@mozilla.com), I went to the payment page and filled in my cc info and clicked next.  I was given an error message that read “backend service request failed" error.   I closed the window and went back to fpn.firefox.com and it said “you are now subscribed, click here to download”.  i checked and my card was charged.  so, i paid, was told an error occurred and then billed, then i had to re-open the window.

**Comment by johngruen** [comment]
Maybe related here but in Stripe, @snowmanco has a "postal_code" not a "zip_code" which is what i am seeing on other issued cards.

**Comment by davismtl** [comment]
> a canadian Zip hack where you append 2 zeros to the canadian post code...

Clarification, you take only the numbers from your postal code (three of them) and then add two zeros to get five numbers.

If postal code is A1B 2C3, it would look like 12300.

**Comment by bbangert** [comment]
This appears to be caused by an exception from SubHub. We are adding more logging details but will have to wait until @marty331 can locate an exception/issue in SubHub.

**Comment by bbangert** [comment]
Card re-use is allowed, @stlhood will bring this up in our next meeting to discuss timelines for restricting card re-use.

This bug will track the error that a user hostile error is shown to users indicating that the subscription failed to create, but was actually created. I have located logs in our system of subhub create customer calls that are returning 'Internal Server Error'.

@snowmanco I located this record which likely matches up to your error:
```
  {
    "timestamp": "2019-10-23 15:16:40.721314 UTC",
    "type": "subhub.createSubscription.1",
    "err": "Error: Internal server error",
    "params": "{\"uid\":\"USERID\"}",
    "payload": "{\"pmt_token\":\"tok_SOMETOKEN\",\"plan_id\":\"plan_FvnxS1j9oFUZ7Y\",\"display_name\":\"Brian O'Neill\",\"email\":\"boneill+vpnpaidprod@mozilla.com\",\"origin_system\":\"fxa\"}"
  }
```

**Comment by bbangert** [comment]
I believe this was due to a timeout in SubHub, the request was taking longer than 5 seconds so AWS Lambda killed the process. Wed evening this timeout was upped to 10seconds and I have seen no further errors from SubHub in our logs since.

@stlhood, @snowmanco, @johngruen Can you confirm if this still exists and re-open if needed, as I haven't seen any new errors in our logs that I can match with the existing reports?
