### ISSUE TITLE
Add autofocus of password field on Android

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3066]
We recently accidentally enabled the autofocus of the password field on iOS. We were under the impression that it would be a bad user experience since it opens up the keyboard automatically.

To our surprise, we observed the opposite and it seems to have been quite beneficial. See:
https://github.com/mozilla/fxa/issues/3040#issuecomment-544722110

Let's learn from this accidental win and turn on the autofocus on Android too now.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-473)
┆Issue Number: FXA-473

**Comment by LZoog** [comment]
On my actual iPhone, it doesn't appear to pull up the keyboard automatically, just the focus and a prompt that covers the rest of the form. 🤔

<img src="https://user-images.githubusercontent.com/13018240/67299708-a1f42980-f4b2-11e9-8cf0-650c7947c425.jpg" width="300px">

**Comment by davismtl** [comment]
Need to dive back in to data because it doesn't seem like iOS is auto-focusing properly which makes me question why the rates improved on iOS.
