### ISSUE TITLE
button label/text in html email not localized (in English) when user signs into from new browser profile/IP address, e.g. 'Confirm sign-in', 'Manage account' [bz1590436]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3068]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1590436

Signed into Firefox Accounts with a 72.0a1 Nightly in German (de) on Windows 8.1 (Options > Sync) - browser and OS shouldn't matter.

That browser profile didn't know about the Sync account yet and sent an email to confirm it.

The email is in German except the 'Confirm sign-in' button which is in English. The plaintext part of the message contains the German text ("Anmeldung bestätigen"), only the HTML part has the English label.

Related to https://github.com/mozilla/fxa/commit/03b72dfb854a764ced8eb2ef960045b48a67c2a9#diff-ad28990900043fd71d26e323cb2eb9f4 ?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-475)
┆Issue Number: FXA-475

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in bz
