### ISSUE TITLE
[payments-server] Add `fxa-activity-metrics` payments log pipeline

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3072]
Once #3071 is merged, payments-server will start logging flow perf events to stdout.  (This is different from content-server, which writes to stderr.)  These events need to be piped through https://github.com/mozilla/fxa-activity-metrics so they can be queried on Redshift like those from content-server.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-476)
┆Issue Number: FXA-476

**Comment by chenba** [comment]
@jbuck Here's another metrics related thing for ya!  😬

**Comment by shane-tomlinson** [comment]
cc @jbuck - the payments server will be ready to emit metrics with train-149, flagging this to bump it in your queue.

**Comment by jbuck** [comment]
I will summarize a bunch of Slack messages here for context, but tl;dr is that I think we should backlog this issue.

The current fxa-activity-metrics (which includes the perf events) are processed with the following pipeline: logs on stderr -> heka logging agent -> heka server -> rolls logs up to 1 day -> deliver to S3 -> fxa-activity-metrics ETL job running on fxa-admin -> Redshift database -> can be queried from STMO

We'd like to stop using heka, so we'd need to integrate stackdriver logging into this pipeline somehow. There’s another, potentially parallel effort to migrate off Redshift to Big Query
and it’s trivial to export from Stackdriver Logging to Big Query.

@irrationalagent currently uses the activity metrics, so we can't stop sending them. He can live with not having the payment-related events though.

**Comment by chenba** [comment]
More background: this is all originated from https://github.com/mozilla/fxa/issues/996.  Because the perf metrics is piggybacked off of flow activity metrics [0], we ended up here.  So to be perfectly clear:

 * This has nothing to do with Amplitude.
 * Payments does _not_ emit activity metrics at the moment.
 * Payments is emitting flow perf metrics.

[0] I'm guessing.  I don't know the actual history of these metrics. :D

**Comment by clouserw** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1594137

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Payments now uses statsd and influxdb: #FXA-43
