### ISSUE TITLE
Wrong Image on Email Confirmation Step

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3079]
![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/12e0e4ba-9ee7-47cf-a1a4-147f34da2095)

This is the image we use when we send a link. I'm pretty sure we have an image for when we send codes too. If we don't, we should update this image because it makes less sense.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-477)
┆Issue Number: FXA-477

**Comment by ryanfeeley** [comment]
Indeed we do: https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/graphic_mail_code.svg

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The image ryan linked to no longer exists.  If one exists and this should be done please link to it. thanks.
