### ISSUE TITLE
Should Confirming Email with Codes Come Before CWTS?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3080]
If you drop out of the funnel on the CWTS page, you cannot confirm your email. ~Roughly 15% of user drop off at CWTS~ so they will not be able to confirm their emails.

Edit: when adding a chart, I noticed that I could not replicate this value in charts.

Edit 2: Feature doc link:
https://docs.google.com/document/d/1vl9qtckQvepWvS_l1I82etozrUq27q5Fmn7EHjbbeEw/edit#

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-478)
┆Issue Number: FXA-478

**Comment by davismtl** [comment]
@shane-tomlinson @ryanfeeley 

This bug as described is not quite accurate and may be misleading. I think I mixed up some metrics when initially filing it.

The dropoff rate is of submitting CWTS is closer 7-8%, not 15%. 
https://analytics.amplitude.com/mozilla-corp/chart/new/89n0tou

I am wondering if somehow the 15% mentioned in this bug was confused with the fact that 15% of users registering to Sync never see a CWTS screen.
https://analytics.amplitude.com/mozilla-corp/chart/new/grxl1k1

With the bulk being iOS users (and it likely being a metric bug) which I will file.
https://analytics.amplitude.com/mozilla-corp/chart/new/szb712a 

Ultimately, there is a large drop-off around CWTS. It's just that it's not as big as intially thought.

Let's still investigate the effort here but lets be mindful that the impact is smaller than thought.

**Comment by davismtl** [comment]
@shane-tomlinson I've started a feature document here that will reflect your proposed user flow:
https://docs.google.com/document/d/1vl9qtckQvepWvS_l1I82etozrUq27q5Fmn7EHjbbeEw/edit#

**Comment by davismtl** [comment]
@shane-tomlinson , @ryanfeeley has signed off on your design.

**Comment by davismtl** [comment]
- Going to stage this week.
- A/B test logic in place
- Need to investigate if all the changes are going to impact each other
   - Need to make sure that changes that are going out get applied to both A/B branches.

**Comment by vasilicatamas** [comment]
Verified this issue on Stage [Train 1.150.2] under Windows 10 64-bit, Mac Os X 10.14.6, Android 8 and iOS 13.1.2 and noticed the following: 
- subscription newsletter is replaced by CWTS section in registration form while attempting to create a Firefox account from toolbar, hamburger menu and about:preferences#sync (tested on Firefox 71.0b9)
- In addition to the above mentioned arias, on Firefox 70.0.1, this replacement also is visible when creating an account from about:welcome page
- The email confirmation page is displayed right after the form submit

I am also attaching 3 screenshots from windows, android and iOS
Based on the above mentioned, I am marking this bug as Verified.

![Screenshot_6](https://user-images.githubusercontent.com/18114210/68876824-bcb26a80-070d-11ea-9704-f5c5e846f1ac.png)
![1573744754266](https://user-images.githubusercontent.com/18114210/68876830-bfad5b00-070d-11ea-93be-766f0e3ae094.JPEG)
![IMG_0114](https://user-images.githubusercontent.com/18114210/68876844-c50aa580-070d-11ea-81d5-01ad0dd58e9a.PNG)

**Comment by davismtl** [comment]
I'm going to re-open this so that it's in our product board to track measuring and log results.

See here: 
https://analytics.amplitude.com/mozilla-corp/chart/bs4sg9z

**Comment by davismtl** [comment]
Seems to be positive for iOS:
https://analytics.amplitude.com/mozilla-corp/chart/bs4sg9z/edit/bfu0v78

And desktop:
https://analytics.amplitude.com/mozilla-corp/chart/bs4sg9z/edit/45nd11y

But Android is unclear. I see metrics bugs (see https://github.com/mozilla/fxa/issues/3446)
https://analytics.amplitude.com/mozilla-corp/chart/bs4sg9z/edit/eqxsle6

**Comment by davismtl** [comment]
THis is shipped and at 100%. We will be doing follow up experiments.
