### ISSUE TITLE
Update payment method cancel and subscription cancel buttons are confusing

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3087]
From internal testing... @janiceahn and Rina both had this concern...

> When the user clicks to Change payment method, the window expands to reveal the form.   The Cancel subscription button below it is confusing/distracting. There are two Cancel buttons with two different actions. If user clicks the Cancel for cancel subscription thinking he/she is canceling the credit card change, then user goes down the wrong flow.  My suggestion is to hide the Cancel subscription when the form is shown.

![image](https://user-images.githubusercontent.com/3323249/67385990-734e7f80-f594-11e9-932a-18477e8dda78.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-480)
┆Issue Number: FXA-480

**Comment by johngruen** [comment]
I would be fine to punt on this pending FXA settings redesign

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

punting for new settings design
