### ISSUE TITLE
teamcity test flakiness: oauth force_auth

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3092]
All of these tests are being ignored:

* verified, blocked
* with a registered email
* with an unregistered email

blocks #2877

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-482)
┆Issue Number: FXA-482

**Comment by clouserw** [comment]
team city is gone.  Closing this.  /cc @ashrivastava-qa
