### ISSUE TITLE
teamcity test flakiness: Firefox desktop user info handshake - OAuth flows

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3093]
The following are being ignored on teamcity:

* OAuth signin page - user signed into browser, no user signed in locally
* OAuth signin page - user signed into browser, user signed in locally

blocks #2877

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-483)
┆Issue Number: FXA-483

**Comment by clouserw** [comment]
team city is gone.  Closing this.  /cc @ashrivastava-qa
