### ISSUE TITLE
teamcity test flakiness: oauth choose redirect

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3095]
The following are being ignored on teamcity:

* oauth endpoint redirects to signin with a registered email
* oauth endpoint redirects to signup with an unregistered email

blocks #2877

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-485)
┆Issue Number: FXA-485

**Comment by clouserw** [comment]
team city is gone.  Closing this.  /cc @ashrivastava-qa
