### ISSUE TITLE
teamcity test flakiness: oauth permissions for trusted reliers

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3096]
These are being ignored on teamcity:

* force_auth with `pro
* force_auth without `
* signin with `prompt= 
* signin without `prom 
* signup with `prompt=
* signup without `prom

blocks #2877

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-486)
┆Issue Number: FXA-486

**Comment by clouserw** [comment]
team city is gone.  Closing this.  /cc @ashrivastava-qa
