### ISSUE TITLE
Autofocus Name field on Payments Page

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3098]
Fewer clicks = Faster typing = faster paying

**Comment by johngruen** [comment]
boy setting autofocus in react seems painful

**Comment by lmorchard** [comment]
Can probably do it [something like this](https://github.com/kensnyder/react-hook-use-autofocus/blob/master/src/hooks/useAutofocus.js#L9) with hooks:

```javascript
const ref = useRef();
useEffect(
  () => ref.current.focus(),
  [ref],
);
return <input ref={ref} />
```
Or better yet, add a new reusable hook to [`hooks.tsx`](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/lib/hooks.tsx) based on [that example](https://github.com/kensnyder/react-hook-use-autofocus/blob/master/src/hooks/useAutofocus.js#L9) and use that.

**Comment by lmorchard** [comment]
Although, it looks like we [already use a `ref` in input fields for positioning tooltips](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/components/fields.tsx#L174), so we might need to share that with an auto-focus effect rather than pass one into the field component.
