### ISSUE TITLE
Device Controller Basic Information - Services attached to FxA

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#31]
As a FF user when using Firefox,

I want to know the devices and services I am connected to via my Firefox Account, and important information about my the status of my services. 1b. For services, this includes when I am connected to those services via FF (a FF device) as well as through other other browsers (a non-FF device) 1

**Comment by rfk** [comment]
> when I am connected to those services via FF (a FF device) as well as through other other browsers
> (a non-FF device)

I think being "connected to those services via FF" is pretty straightforward, but being "connected through other browsers" is pretty murky.  What does it mean to be connected to a service through another browser?  @billmaggs can you give a concrete example of this from a user's point of view?

**Comment by billmaggs** [comment]
How about "as well as logged into the service via FxA using other
browsers?"

Bill

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-17
