### ISSUE TITLE
[fxa-auth-server] avoid hitting subhub in settings page unless active in local sub table

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3109]
Right now we hit subhub for every single user regardless of if they have a subscription in our local subscription table:
https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/account.js#L1505

To lower the calls to subhub, we should only query subhub on the actual subscriptions management page, and use our local table to determine if we show the Subscription management button.

**Comment by lmorchard** [comment]
I think I remember where the plumbing is for this, so I can take a crack at it.

**Comment by lmorchard** [comment]
> use our local table to determine if we show the Subscription management button

I submitted a PR that skips making the call to subhub if the local DB has no subscriptions.

But, FWIW, we also proactively fetch subhub subscriptions for the delete account view in settings. We might want to consider a followup to lazy-load that, only hitting subhub when the delete account view is first rendered.
