### ISSUE TITLE
Firefox account toolbar button looks small [bz1538642]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3112]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1538642

Created attachment 9053209
image.png

The button for the Firefox Account menu looks small-ish in comparison to the other icons in the toolbar.
Also it seems slightly off-brand (since we have strong borders everywhere). Maybe adding a 2px border around it (to expand its current size) would solve both issues (_not sure at all_)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-487)
┆Issue Number: FXA-487

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

no longer valid
