### ISSUE TITLE
teamcity test runner is crashing or OOM

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3123]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=60099&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests, click on "oauth query parameter va"

> ======= Failed test run #71 ==========
> NoSuchDriver: [POST http://localhost:4444/wd/hub/session/a1a9c5cd-aa38-4f09-bb62-8fb41a5b7b98/url / {"url":"https://latest.dev.lcip.org/"}] Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '4ccfe51f7550', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: unknown
  @ src/lib/ProxiedSession.ts:63:22
  at Test.test @ tests/functional/pages.js:87:8
  @ src/lib/Test.ts:263:51
  at runMicrotasks @ anonymous
NoSuchDriver: [POST http://localhost:4444/wd/hub/session/a1a9c5cd-aa38-4f09-bb62-8fb41a5b7b98/url / {"url":"https://latest.dev.lcip.org//"}] Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '4ccfe51f7550', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: unknown
  @ src/lib/ProxiedSession.ts:63:22
  at Test.test @ tests/functional/pages.js:87:8
  @ src/lib/Test.ts:263:51
  at runMicrotasks @ anonymous
NoSuchDriver: [POST http://localhost:4444/wd/hub/session/a1a9c5cd-aa38-4f09-bb62-8fb41a5b7b98/url / {"url":"https://latest.dev.lcip.org/authorization"}] Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '4ccfe51f7550', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: unknown
  @ src/lib/ProxiedSession.ts:63:22
  at Test.test @ tests/functional/pages.js:87:8
  @ src/lib/Test.ts:263:51
  at runMicrotasks @ anonymous
NoSuchDriver: [POST http://localhost:4444/wd/hub/session/a1a9c5cd-aa38-4f09-bb62-8fb41a5b7b98/url / {"url":"https://latest.dev.lcip.org/authorization/"}] Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '4ccfe51f7550', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: unknown
  @ src/lib/ProxiedSession.ts:63:22
  at Test.test @ tests/functional/pages.js:87:8
  @ src/lib/Test.ts:263:51
  at runMicrotasks @ anonymous
NoSuchDriver: [POST http://localhost:4444/wd/hub/session/a1a9c5cd-aa38-4f09-bb62-8fb41a5b7b98/url / {"url":"https://latest.dev.lcip.org/boom"}] Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '4ccfe51f7550', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.41-36.55.amzn1.x86_64', java.version: '1.8.0_144'
Driver info: driver.version: unknown
  @ src/lib/ProxiedSession.ts:63:22
  at Test.test @ tests/functional/pages.js:87:8
  @ src/lib/Test.ts:263:51
  at runMicrotasks @ anonymous

blocks #2877

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-490)
┆Issue Number: FXA-490

**Comment by clouserw** [comment]
team city is gone.  Closing this.  /cc @ashrivastava-qa
