### ISSUE TITLE
Card validation errors should use existing fxa pattern, not modal

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3135]
Right now, card validation errors show up in a modal. This is unhelpful as it obscures the CC form and makes it hard for users to spot the error in their input while seeing the instructional text of the error. 

We should ditch the error modal and use the `.error` pattern utilized by other parts of FxA.

This pattern should apply in subscription settings as well

![image](https://user-images.githubusercontent.com/3323249/67584907-e865b480-f74e-11e9-8628-f3cb6267ed74.png)

**Comment by johngruen** [comment]
This implies that we ditch headers for error messages as well

**Comment by LZoog** [comment]
Patch: #3266
