### ISSUE TITLE
[fxa-auth-server] Chain errors to avoid losing stack information

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3138]
In fxa-auth-server (and possibly other packages), we catch and rethrow errors, typically as AppError for use in the request cycle control-flow. These are used to exit with specific request information such as a status code and message set, but when reported by Sentry have lost the original stack trace.

Using a package like [verror](https://www.npmjs.com/package/verror), we could re-plumb these error re-throws to include the `cause` each time an error is thrown and retain the full error stack. This would help us know the call stack that resulted in the error and more easily annotate it with useful debug information.

**Comment by vbudhram** [comment]
from mtg: Not a small task, decent amount of repluming.

**Comment by 6a68** [comment]
I'd definitely be in favor of improving our error reporting. Is this work parallelizable? Want to make it a cleanup day topic?

**Comment by bbangert** [comment]
Bringing in the scope of this as I added chaining capability in #3179 while addressing lost support error information. The PR that will close this shortly adds the original error to the `backendService.js` which was one of the most common errors that lost its stack trace that I've seen. Retaining stack traces for other parts can now be done fairly easily in fxa-auth-server.
