### ISSUE TITLE
[fxa-auth-server] filter possibly unrelated breadcrumbs

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3139]
Due to Node's concurrent model and integrations, when http requests occur they are recorded as Sentry breadcrumbs. When the exception is recorded, all breadcrumbs from the global scope are sent, which can vary based on in-flight requests. These may or may not be relevant to the request though, and we should probably avoid including them.

How Scopes and Hubs work:
https://docs.sentry.io/enriching-error-data/scopes/?platform=browser

Using a Client directly to avoid global breadcrumbs/context:
https://docs.sentry.io/platforms/javascript/advance-settings/#using-a-client-directly

Related issue:
https://github.com/getsentry/sentry-javascript/issues/2023

A simple fix might be to turn off default integrations entirely.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-492)
┆Issue Number: FXA-492

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
