### ISSUE TITLE
Replace avatar spinner with our best version

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#3148]
We previously had a [fantastic spinner](https://github.com/mozilla/fxa-content-server/pull/3323) made by a contributor that we should use everywhere the profile image is loading. In the recent spinner fix, the small spinner was scaled up, and looks a bit silly.

Please apply to everywhere the avatar has a loading state (avatar modal, sign-in screens, etc.)

CURRENT
<img width="478" alt="Screen Shot 2019-10-28 at 12 21 28 PM" src="https://user-images.githubusercontent.com/68213/67697653-4547b180-f97f-11e9-8ab5-4c9543162a6e.png">

PROPOSED
![64e246fe-a2b2-11e5-99ed-aef7a36d6d8a](https://user-images.githubusercontent.com/68213/67697705-5b557200-f97f-11e9-9e04-e56a55dc9fdb.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-496)
┆Issue Number: FXA-496

**Comment by ryanfeeley** [comment]
Actually, it wasn't working when I tested it first, but it does appear to still be on the sign-in page.
<img width="228" alt="image" src="https://user-images.githubusercontent.com/68213/67699565-b8065c00-f982-11e9-9e2e-8394765f81c2.png">
Essentially, this bug is about taking that spinniner/fade style and applying it to the change avatar screen (and other places that the avatar loading appears).

**Comment by vbudhram** [comment]
from mtg: This might have only been applied to sign-in...maybe. Might be very involved and require javascript because spinner goes around avatar and fades at the right time.

**Comment by LZoog** [comment]
I spent a few minutes looking into this and we should be able to swap out the spinner, and when the avatar has finished loading, we can fade out `#loading-avatar-spinner` and fade in `#image-holder` inside of `avatar-mixin.js`. We need to do some `position` property tweaking as well.

I'm going to go ahead and assign myself, but I won't get this in this train.

**Comment by smishra2903** [comment]
If this issue is still open, can I work on this? 
Also I am a beginner, so can I get some help on how to begin with it?

**Comment by vladikoff** [comment]
@smishra2903 this issue is taken. sorry!
