### ISSUE TITLE
Create Firefox account “Stay safe” password tooltip is not displayed when using some entry points [bz1591997]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3153]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1591997

Created attachment 9104669
Create account password tooltip.PNG

Affected versions:
70.0 (20191016161957)
71.0b3 (20191021164841)
72.0a1 (20191027212548)

[Affected platforms:]
Windows Pro 10 x64
Ubuntu 18.04.3 LTS

[Steps to reproduce]:
1. Launch Firefox and go to Create account page starting from either of these locations: AMO (addons.allizom.org), Firefox Pocket (bookmarks toolbar>  view pocket list) or Ff Sync Settings. 
2. In the Create account password field input some passwords that have under 8 characters.
3. Erase that the input from the password fields and try using your email as a password instead.
4. Erase that the input from the password fields and use one of the most common used passwords - “password1234”.
5. Fill in other required fields and click on “Create Account” button.

[Expected results]:
When starting with a new profile and the Welcome to Firefox page is displayed, and the user reaches the Create a Firefox Account page through that entry point, the “Stay safe — don't reuse passwords.” password tooltip is displayed until the user fills in the password fields according to the requirements. (see the Create account password tooltip.png)
The password tooltip with the warning message (see screenshot) with which the user is warned that the password must be at least 8 characters, must not be the email address or one of the commonly used passwords from the linked list. 

[Actual results]:
The “Stay safe” password tooltip does not in the create account flow when the entry point is AMO, firefox pocket or the Sync Settings.

**Comment by shane-tomlinson** [comment]
Closing as dup of https://github.com/mozilla/fxa/issues/2557
