### ISSUE TITLE
Failing locally auth-server tests

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#3157]
I'm not really sure what changed in my local setup but the first test of my auth-server remote tests **always** fails. It appears to be some timing incident since it test server doesn't seem to get created in time?

<img width="781" alt="Screen Shot 2019-10-28 at 5 32 43 PM" src="https://user-images.githubusercontent.com/1295288/67719879-147c7200-f9a9-11e9-818f-08390792a448.png">

I'm not sure if it is failing on CI since circle is down. If anyone gets a moment and wants to try it, run auth-server tests.

**Comment by jrgm** [comment]
Is your customs server started? - https://github.com/mozilla/fxa/issues/3158

**Comment by shane-tomlinson** [comment]
You might have to go into the auth-server, and do an `node ./scripts/oauth_gen_keys.js`

**Comment by shane-tomlinson** [comment]
> Is your customs server started? - #3158

Customs isn't normally run locally.

**Comment by shane-tomlinson** [comment]
@dannycoates - There are rumors that you might have already fixed this. If so, can you close this down?

**Comment by dannycoates** [comment]
fixed in #3191
