### ISSUE TITLE
(customs): The customs-server in v1.149.0 does not start. 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#3158]
The customs-server in v1.149.0 does not start. It logs only the below lines on the way out (last okay line, then `"op":"customs.bin.error","err":{"cause":{}` thank you very much, and docker recording that the container has exited.
`
Oct 28 23:26:01 ip-172-31-81-183.ec2.internal docker-fxa-customs[14825]: {"name":"customs-server","hostname":"ip-172-31-81-183.ec2.internal","pid":1,"level":30,"op":"requestChecks.validate.changed","key":"flowIdRequiredOnLogin","currentFlowIdRequiredOnLogin":true,"futureFlowIdRequiredOnLogin":false,"msg":"","time":"2019-10-28T23:26:01.378Z","v":0}
Oct 28 23:26:01 ip-172-31-81-183.ec2.internal docker-fxa-customs[14825]: {"name":"customs-server","hostname":"ip-172-31-81-183.ec2.internal","pid":1,"level":50,"op":"customs.bin.error","err":{"cause":{},"isOperational":true},"msg":"","time":"2019-10-28T23:26:01.383Z","v":0}
Oct 28 23:26:01 ip-172-31-81-183.ec2.internal systemd[1]: docker-fxa-customs.service: main process exited, code=exited, status=1/FAILURE
`
This in turn prevents the fxa-auth-server from working.

The only "change" since v1.148.8 is an upgrade of `csv-parse` from "1.0.4" to "4.4.6" (which it uses to read IP block lists from disk).

In a remarkable coincidence, if I do `npm test` locally, it fails a number of csv tests. 

But under circle-ci it doesn't appear to run any tests, presumably since no code change (except code did change with the dependency upgrade of course).

**Comment by shane-tomlinson** [comment]
Fixed by #3167, closing.
