### ISSUE TITLE
Restore logging of oauth activity events to BigQuery

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#3160]
#2996 had the desired effect of avoiding sending an overwhelming deluge of oauth activity event into amplitude, but it had the side-effect of making those events unavailable for analysis in other tools such as BigQuery. In particular, they're no longer available for [export to CDP](https://bugzilla.mozilla.org/show_bug.cgi?id=1573359).

Let's restore them.

I put up a trial PR for this in #3129, but @jbuck said it may not be necessary, we perhaps we can instead revert #2996 and move the amplitude filtering into infrastructure.

**Comment by rfk** [comment]
Ideally we would like to have this available before Firefox 71 hits release, otherwise we risk having only partial visibility into metrics around whether or not users are signed in to the browser but disabling sync.

**Comment by rfk** [comment]
Unassigning myself from this because IIUC it's currently on @jbuck for some infra changes; please comment here if that's not correct.

**Comment by jbuck** [comment]
PR to fix this in #3314 . It should go out with stage this week in train-150 so that this fix can be verified before the launch of Firefox 71

**Comment by jdragojevic** [comment]
@clouserw ^^ ok to update the train milestone?

**Comment by clouserw** [comment]
@meandavejustice this is back in train 150

**Comment by clouserw** [comment]
This has been uplifted
