### ISSUE TITLE
Over eager invalid handling on zip code input

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3168]
Focus the zip code and start typing, when a single character is entered, the box is marked `invalid`. The box should only look to see if it's invalid on blur

**Comment by lmorchard** [comment]
What is the exact behavior you're seeing? We do mark fields as invalid while typing, we just don't display error messages until blur. We have to update the invalid status in order to accurately find validity for the whole form and enable / disable the submit button.
