### ISSUE TITLE
Land device pairing phase 1 Firefox Desktop patch

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#317]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1490671

TODO:
- [x] add "fxaccounts:pair_heartbeat" message handling
- [x] use channelID as base64url bytes.
- [x] On decryption error -> display an error to the user

**Comment by shane-tomlinson** [comment]
cc @eoger

**Comment by eoger** [comment]
Yes

**Comment by shane-tomlinson** [comment]
@eoger has the security review been completed?

**Comment by rfk** [comment]
Yes, we have on more outstanding security reviews on the docket.

**Comment by vladikoff** [comment]
This is done
