### ISSUE TITLE
Add rust-fmt to fxa-email-service

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3172]
We are using eslint / prettier for all of our js files, it would be nice to use rust-fmt for fxa-email-service.

https://circleci.com/gh/mozilla/fxa/104453

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-499)
┆Issue Number: FXA-499

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
