### ISSUE TITLE
Error flash while canceling Billing Information change

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#3182]
<img width="707" alt="Screen Shot 2019-10-29 at 4 28 29 PM" src="https://user-images.githubusercontent.com/26334275/67817054-4ead4880-fa69-11e9-95aa-ab327518a4fa.png">

### Steps to reproduce

On the subscription management page, pressing cancel on this billing form quickly flashes an error on the last form field that is empty, causing a red flash (unfortunately moves too quickly to properly screenshot). 

### Expected result

There should be no error message here, even for a split second. Cancellation should just close the form. 

### Environment

I noticed this in Safari and Firefox Release.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-500)
┆Issue Number: FXA-500

**Comment by lmorchard** [comment]
Hmm, this one might be tricky: We validate fields & display errors when form fields lose focus. Clicking cancel causes the name field to lose focus - and so the error tooltip is displayed. We might maybe skip displaying an error tooltip on an empty field?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

resolved -> expired
