### ISSUE TITLE
”to continue to {Service}” string misses after opening “Enter recovery code” page in a new tab

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3184]
**Build:**
Stage [Train 1.149.3]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Launch Firefox and attempt to log in with an account that has 2FA enabled.
2. Insert a valid email address and a valid password.
3. Click on "Sign in" button.
4. Right-Click on “Trouble entering code” link from “Enter security code” page and select to open it in a new tab

**Expected results:**
“Enter recovery code to continue to {Service}” title is successfully displayed.
 
 **Actual Results:**
- “to continue to {Service}” string is not displayed in “Enter recovery code” page.
- “to continue to {Service}” string also misses from “Enter security code” page after clicking “Back” link from the affected “Enter recovery code” page.

**Additional notes:**
- This issue also reproduces while opening “Enter recovery code” page in a new window
- This is a follow-up issue for #2764

![to continue to {Service}](https://user-images.githubusercontent.com/18114210/67858329-9ee7e180-fb21-11e9-9525-89db386417a5.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-501)
┆Issue Number: FXA-501

**Comment by vladikoff** [comment]
@vbudhram related https://github.com/mozilla/fxa/issues/624
