### ISSUE TITLE
2FA remains enabled after using all the recovery codes

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3186]
**Build:**
Stage [Train 1.149.3]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Launch Firefox and attempt to log in with an account that has 2FA enabled.
2. Insert a valid email address and a valid password.
3. Click on “Sign in” button.
4. Click on “Trouble entering code” link from “Enter security code” 
5. Enter a valid recovery key.
6. Repeat this step until remains one valid recovery key.
7. After logging with the last 2 valid recovery key the user is redirected to manage account and  prompted to generate new recovery codes.
8. Click “Done” button from recovery codes dialog without generating new ones.

**Expected results:**
- “Done” button should be disabled until new recovery codes are generated.
**Or**
- 2FA should be disabled after using all the recovery codes.
 
 **Actual Results:**
- “Recovery Codes” dialog can be closed without generating new recovery codes.
- The users might forget that they already used all the keys and after sign out they will probably be locked out.
 
**Additional notes:**
This is a follow-up issue for #2764

![recoverycodes](https://user-images.githubusercontent.com/18114210/67863596-de67fb00-fb2c-11e9-9e40-f6ad37d882f4.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-503)
┆Issue Number: FXA-503

**Comment by vbudhram** [comment]
> 2FA remains enabled after using all the recovery codes

I believe this is the intended behavior. The would have gotten a few emails telling them that they have a low amount of codes and that they should generate new ones.

However, disabling the `Done` button would be nice. @ryanfeeley thoughts? Or maybe a different way to ensure users do this?

**Comment by ryanfeeley** [comment]
@vbudhram You are right "Done" is a little dismissive.

What if we did something like:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/68213/68157456-accfa500-ff1b-11e9-8ef2-b54ae2c1c5bc.png">

**Comment by ryanfeeley** [comment]
(or, to follow established patterns, put *Disable recovery* as a link beneath.)

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We're ok to do nothing here, and leave 2FA enabled if we run out of recovery codes.
