### ISSUE TITLE
[payments server] Successful Billing Info Update Alert Bar Self-Dismiss Quickly

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3187]
#### STR

1. Subscribe to a product
1. Go to subscriptions management page
1. Update payment info for the product

#### Expected

Alert bar for successful payment info update stays on page until dismissed by clicking 'X'.

#### Actual

Alert bar is displayed for a very short period of time.

**Comment by shane-tomlinson** [comment]
@chenba - are you working on this right now as part of #2982?

**Comment by chenba** [comment]
Oh, no, I was simply removing the close icon from the alert bar in #2982.  But I can extend the delay for this.  I'll do that in the current milestone.

**Comment by lmorchard** [comment]
> Ah, ok. I'll just remove the AlertBar's close icon

I think we want it manually close-able too. It's just that if the user doesn't get to it, it should also self-dismiss

**Comment by chenba** [comment]
That make sense.  I'll add it back and extend the delay a bit.  (Partly because I don't want to have PR #3193 go through CI again.)
