### ISSUE TITLE
Update production database to latest mysql 5.6

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#319]
Ops bug tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1504902

**Comment by vladikoff** [comment]
@rfk "not authorized " on that bug

**Comment by vladikoff** [comment]
from mtg: bumping to next week, due to Thanksgiving. been running in stage for a few weeks

**Comment by vladikoff** [comment]
from mtg: after holidays

**Comment by vladikoff** [comment]
cc @jrgm @jbuck any updates?

**Comment by jrgm** [comment]
Doing today

**Comment by shane-tomlinson** [comment]
DONE!
