### ISSUE TITLE
Cannot sign in to firefox account after windows/firefox fresh install [bz1592722]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3190]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1592722

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

1. Click on the hamburger menu button in the top right of a firefox window.
2. Click on the "Sign in to Firefox" option at the top of the resulting window.
3. Click on the "Sign in to Firefox" button in the resulting window to turn on sync.
4. Enter email address at resulting page.
5. Click Continue.

Actual results:

Get unexpected error above email address
Observe the following in web console:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.accounts.firefox.com/v1/account/status. (Reason: CORS request did not succeed). 

2 Unexpected error logger.js:69:29 error logger.js:69 captureError error-utils.js:63 logError base.js:769 o base.js:80 Underscore 2 R n _submitForm form.js:240

Expected results:

I expected to have to enter my firefox account password in a subsequent field and have successfully logged in to my firefox account in order to utilise Sync.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-504)
┆Issue Number: FXA-504

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Assuming this user got their account sorted in the year since this was last touched
