### ISSUE TITLE
Define schema for amplitude outgoing pings

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3194]
It would be good to define exactly what we send to amplitude, whether that's expressed in JSON Schema, Joi, or OpenAPI/Swagger.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-505)
┆Issue Number: FXA-505

**Comment by shane-tomlinson** [comment]
Taxonomy doc: https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055

**Comment by 6a68** [comment]
Based on conversations with Data Engineering, JSON Schema might be a better choice than Joi, since they are using it, ajv is more performant than Joi, and it's a language-agnostic schema, so we can share schemas (or even tests generated from JSON Schemas).

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We are moving away from Amplitude. Closing.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We are moving away from Amplitude. Closing.
