### ISSUE TITLE
Do an MX Lookup on Domain of Email Used for Registration

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3196]
At my past job, we did MX lookups on the domain of the email address being used for registration to make sure people didn't have typos and to make sure we wouldn't send emails that would bounce. This improved our registrations because it highlighted some types of potential typos that are less visible to a regex.

Obviously if the domain is Google, Yahoo, msn, hotmail, gmx, outlook, etc... we don't need to do a lookup.

How would we surface there's a problem? We may not have time to do a lookup before the user hits submit on an email first flow. If we can do it there, great but we could potentially surface it at the next step (registration form). We have a link to change the email for registration.

Our metrics show that the majority of emails that are bouncing are sent to a domain that is not one of the above. This is where the MX lookup would help.

See chart:
https://analytics.amplitude.com/mozilla-corp/chart/new/osniv8u

The volume in the above chart shows that nearly 5% of our registration submits will result in a bounced email sent to a domain with potentially no MX record. (I don't think we distinguish soft from hard bounces in our metrics)

Edit:
[Feature document here](https://docs.google.com/document/d/1qKy8NFOasmCvwniqhso8ndFjMecI595Z7dW6tccUjI4/edit#)

**Comment by rfk** [comment]
Some previous discussion about this here: https://github.com/mozilla/fxa/pull/123

**Comment by jrgm** [comment]
Technical Note: the domain in an email address must have **either** an MX **or** an A record.

**Comment by davismtl** [comment]
Starting feature document here: 
https://docs.google.com/document/d/1qKy8NFOasmCvwniqhso8ndFjMecI595Z7dW6tccUjI4/edit#

> Technical Note: the domain in an email address must have either an MX or an A record.

Per @jrgm comment, if no MX record is found, email servers fallback to the A record. Some more details here:
https://tools.ietf.org/html/rfc5321#section-5

**Comment by davismtl** [comment]
@chenba I've made progress on the feature document and discussed flows with @ryanfeeley .

He's going to work on the UX. 

There may be some investigative engineering work that can start based on what's already in the feature document. There seems to have already been a lot of progress in https://github.com/mozilla/fxa/pull/123. Not sure why that work stopped when there was a pull request and a merge.

**Comment by chenba** [comment]
> There seems to have already been a lot of progress in #123. Not sure why that work stopped when there was a pull request and a merge.

The merged PR for #123 was a written doc describing how to synchronously catch an error from Postfix when it fails to deliver mail due to an unknown recipient domain.  This issue is about validating the domain _before_ sending any emails.  (Moreover, we also use SES, Sendgrid, and SocketLabs now, so catching Postfix erorrs wouldn't work?)

**Comment by chenba** [comment]
When the user submits the email address, we check to see if it belongs to an existing account.  And if it is an email for a _deleted_ account, we display an error message.  (Probably a very rare use case?)  So there is already a spot for an error message upon rendering of the registration form, and it looks like this:

![image](https://user-images.githubusercontent.com/198055/68313402-27163b80-007a-11ea-92cf-5fd1ca8baaa7.png)

**Comment by chelsea-lewis** [comment]
@davismtl @ryanfeeley If we want this to be worked in Sprint 151, we ideally need to get UX complete this week, by 8 Nov, so that this is ready for engineering by Sprint Planning on 11 Nov. Are we on track for that?

**Comment by ryanfeeley** [comment]
For emails that are **definitely** wrong, we should redirect to the email first screen and present this message:
<img width="563" alt="mx-record-possibly-wrong" src="https://user-images.githubusercontent.com/68213/68336208-f5b66380-00ab-11ea-97c4-84f1d5bf052d.png">


For emails that are **possibly** wrong, we should redirect to the email first screen and present this dimissable message:
<img width="563" alt="mx-record-possibly-wrong" src="https://user-images.githubusercontent.com/68213/68336241-049d1600-00ac-11ea-9e51-03dccd2d9088.png">

**Comment by davismtl** [comment]
@ryanfeeley 
> we should redirect to the email first screen and present this message

Most users will start on this screen. (exception being about:welcome). When you say to redirect to it, are you saying to submit the form and refresh the page with that error if the email is invalid?

**Comment by ryanfeeley** [comment]
Yes, the page will reload (or redirect if from a relier that uses action=email)

**Comment by chelsea-lewis** [comment]
@ryanfeeley Hey Ryan, we have engineering slotted for this sprint for this work. As this is still marked In Design/Needs UX, can you let us know when you expect to complete Design?

**Comment by davismtl** [comment]
We are UX complete according to Ryan and it's in the feature doc.

**Comment by davismtl** [comment]
Shane did a review but hasn't seen any changes since yesterday.

@irrationalagent @chenba should we be tracking how many form submits are blocked from the mx lookup? I'm tempted to say yes given that Lauren is landing work on the same touchpoint within a similar timeframe.

**Comment by chenba** [comment]
> tracking how many form submits are blocked from the mx lookup

Only straight up blocks when there's no MX or A records?  Having a A record but no MX record block the first submission but not the subsequent submission (if no correction was made).

 > Lauren is landing work on the same touchpoint

Slightly off-topic: Shane recently landed a patch that use Mailcheck to make domain typo correction suggestions.  If the auto-complete feature uses more or less the same domains for suggestions, should we keep both features?  If the user ignore the auto-complete suggestion, they likely ignore that same suggestion from Mailcheck?

**Comment by davismtl** [comment]
> Only straight up blocks when there's no MX or A records? Having a A record but no MX record block the first submission but not the subsequent submission (if no correction was made).

I think we should distinguish the two. It'll be helpful to tell if our soft blocks are having a negative impact.

> Shane recently landed a patch that use Mailcheck to make domain typo correction suggestions. If the auto-complete feature uses more or less the same domains for suggestions, should we keep both features? If the user ignore the auto-complete suggestion, they likely ignore that same suggestion from Mailcheck?

I don't have many details about the work Shane did. But we should certainly avoid the duplicate effort.

**Comment by chenba** [comment]
> I don't have many details about the work Shane did.

It's in prod now.  To see it in action, go to https://accounts.firefox.com/?action=email and enter "test@yaboo.com", press Enter.  The typo correction suggestions are based on this list: https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/lib/mailcheck.js#L14-L38

**Comment by chenba** [comment]
@davismtl @irrationalagent I've added the Amplitude events below in the PR, let me know what you think and I'll update accordingly.

 - `fxa_reg - domain_validation_engage`: when a user submits an email address that's not in FxA
 - `fxa_reg - domain_validation_skip`: the domain is in the list of top domains
 - `fxa_reg - domain_validation_success`: the domain has a MX record
 - `fxa_reg - domain_validation_block`: the domain does not have a MX record or an A record
 - `fxa_reg - domain_validation_warn`: the damain does not have a MX record but has an A record
 - `fxa_reg - domain_validation_ignore`: the user ignores the tooltip and submits an adddress with a domain that does not have a MX record but has an A record

**Comment by davismtl** [comment]
> It's in prod now. To see it in action, go to https://accounts.firefox.com/?action=email and enter "test@yaboo.com", press Enter. The typo correction suggestions are based on this list: https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/lib/mailcheck.js#L14-L38

So, I don't think the UX will conflict. It may be a bit redundant with @LZoog work but in practice, her work will avoid typos before users even hit submit and @shane-tomlinson will catch typos if they still happened once they hit "enter".

I think we should certainly test them together just to be sure they are not colliding with each other,.

Similarly, @chenba is there risk that the MX messages bubbles collide with Shane's domain messages?

**Comment by chenba** [comment]
> Similarly, @chenba is there risk that the MX messages bubbles collide with Shane's domain messages?

No, by the time MX validation is performed, the email address has passed mailcheck and existing account email check.

**Comment by irrationalagent** [comment]
replying @chenba re: amplitude

to limit event volume, maybe we could simplify these to four events, one of which has an event property. I'm thinking something along these lines:

`fxa_reg - domain_validation_triggered` - similar to @chenba 's first event above, but I feel like "triggered" is semantically a bit more transparent, because iiuc this will always happen when the email is not in the top list?

`fxa_reg - domain_validation_skipped` - similar @chenba suggestion, no change here. but just to double check - each reg flow must have EITHER a triggered or skipped event (mutually exclusive), correct?

`fxa_reg - domain_validation_ignored` - similar @chenba suggestion

here's the bigger change:

`fxa_reg - domain_validation_result` with event property `validation_result` one of the following: `block`, `warn`, `success`.

@chenba @davismtl does this seem reasonable to you? it would allow us to economize a bit on adding new events.

**Comment by chenba** [comment]
> `fxa_reg - domain_validation_triggered` - similar to @chenba 's first event above, but I feel like "triggered" is semantically a bit more transparent, because iiuc this will always happen when the email is not in the top list?

This will always happen when the submitted email address is not in FxA, regardless if it's in the top domain list.  I can change it though.

> `fxa_reg - domain_validation_skipped` - similar @chenba suggestion, no change here. but just to double check - each reg flow must have EITHER a triggered or skipped event (mutually exclusive), correct?

No, because, see previous answer.  But that make sense.  I'll make the change so it's either skipped because the domain is in the top list or the MX validation is triggered.

Thanks!

**Comment by chenba** [comment]
One thing to note is that we could see different results from FxA's sign-up form vs. some external form (e.g. about:welcome).  FxA's sign-up process has domain auto-complete and domain typo correction suggestions, both obviate DNS lookup validation when users use either.

**Comment by shane-tomlinson** [comment]
> One thing to note is that we could see different results from FxA's sign-up form vs. some external form (e.g. about:welcome). FxA's sign-up process has domain auto-complete and domain typo correction suggestions, both obviate DNS lookup validation when users use either.

External entries into FxA are forced into the email-first flow, any emails passed in via the `?email` query param should be checked [here](https://github.com/mozilla/fxa/blob/58d0f9f8d8cb89991bf3cac25cfe96967a68fd67/packages/fxa-content-server/app/scripts/views/index.js#L111). It should be easy to set up a functional test for this though, you can add [to the sync_v3_email_first](https://github.com/mozilla/fxa/blob/58d0f9f8d8cb89991bf3cac25cfe96967a68fd67/packages/fxa-content-server/tests/functional/sync_v3_email_first.js#L47) functional tests, maybe one [similar to this test](https://github.com/mozilla/fxa/blob/58d0f9f8d8cb89991bf3cac25cfe96967a68fd67/packages/fxa-content-server/tests/functional/sync_v3_email_first.js#L362) with an invalid domain.

**Comment by chenba** [comment]
Ah yes, the mailcheck step does work.  👍

**Comment by sv-sdeiac** [comment]
Hello, I tried to verify this ticket and from my investigations, I found two issues related to the autocomplete domain during the registration flow.
#3518 and #3519 are the new tickets for those issues.

**Comment by sv-sdeiac** [comment]
Hello, due to the @davismtl comment from #3197, I'll close this ticket as verified, thanks.
