### ISSUE TITLE
Autocomplete Domain of Email During Registration

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3197]
80% of registrations are with an email from one of the following providers (I shorten the list):
- gmail
- outlook
- hotmail
- yahoo
- qq
- web.de
- aol.com
- mail.ru
- icloud
- gmx.de

Let's make registration easier for users (especially on mobile) and propose to auto-complete the email domain.

The LinkedIn mobile app does this pretty well however when I tried to replicate it for a screenshot, it seemed to have a UX bug. Ultimately, using my locale, it proposed in the drop-down the most likely domains for my email. We may not need to localize but we could propose to auto-complete as people type of provide options in a drop-down.

![Screenshot 2019-10-30 at 17 57 05](https://user-images.githubusercontent.com/19537086/67910187-f6487a80-fb3e-11e9-91ed-bc63e847b2fb.png)

Note: Given we don't track emails in our metrics (and just most common domains... because privacy of course), I can only identify 80% of domains users.

src: https://analytics.amplitude.com/mozilla-corp/chart/new/70x6ky6

**Comment by ryanfeeley** [comment]
I totally support this, and thought it was actually filed. I found some other examples that show how it responds to character input.
<img width="223" alt="Screen Shot 2019-03-23 at 8 51 30 AM" src="https://user-images.githubusercontent.com/68213/68145264-6a9a6980-ff03-11e9-92c8-a5ad81dd722e.png">
<img width="220" alt="Screen Shot 2019-03-23 at 8 51 14 AM" src="https://user-images.githubusercontent.com/68213/68145265-6a9a6980-ff03-11e9-951c-50a0ada513c5.png">

Perhaps @LZoog has some suggestions on how to gracefully handle this on mobile where we don't want to show 8 domains at once

**Comment by juliemccracken** [comment]
Alex is working on a feature doc for this and would like to prioritize it for growth.

**Comment by LZoog** [comment]
Also keep in mind that in mobile, users often have autocomplete or suggested words built-in to the keyboard. When I type "@" in an e-mail field, the top suggestion is always correct for me despite me having an uncommon domain since it's the one I use for everything.

**Comment by ryanfeeley** [comment]
I'm not sure how to override the client suggestions, but on the web it could work something like this (exact row height TDB). On mobile, as long as the menu does not exceed viewport, and the list is scrollable by touch, we should be fine.
![email-suggest](https://user-images.githubusercontent.com/68213/68416207-075a4280-0162-11ea-90fa-c2f58e43fb74.gif)

**Comment by ryanfeeley** [comment]
@LZoog For measurements, we'll go with a 20px vertical grid. Each row is 40x high, line-height for each item is 40px. Highlight colour is [photon 50](https://design.firefox.com/photon/visuals/color.html). Font colour is normal, or current placeholder colour.
![image](https://user-images.githubusercontent.com/68213/68430375-f8818900-017d-11ea-9b22-03562044b197.png)

**Comment by davismtl** [comment]
This is very nice. Thanks for sharing @ryanfeeley

**Comment by davismtl** [comment]
@LZoog grabbed this today.

- We need to figure out how many email domains we want to suggest as the user types.
- What do we do on mobile? Should we hide the following field with the drop down? It should be fine since we have email-first rolled out everywhere now.
- Feature document to follow.

**Comment by LZoog** [comment]
@davismtl & @ryanfeeley

I was looking into the best way to implement this and mentioned possibly using the HTML `datalist` option earlier in our call but we definitely need some logic to check for waiting on `@` to autocomplete so I started searching for examples of how others have done it.

[Check out this CodePen on Chrome](https://codepen.io/antoniamab/pen/eeLYGw) (the one on the left does not work in FF). Ryan, it looks like you're wanting this to look like the option on the left-side but limited to 3 domains, BUT I actually think the one on the right is much nicer. While it only offers one domain suggestion at a time, it's less invasive, users can select the option onblur/tab or with a right arrow press, and on mobile you select with onblur or on tap. Bonus points for it working on FF already.

It uses a jQuery plugin that I can go into and copy some logic from as I'd like to get us away from jQ / unnecessary package dependencies. Do you like this option as much as I do?

**Comment by davismtl** [comment]
It is certainly clean. And it doesn't particularly bother me that there is just one suggestion. I think it will likely still reduce typos.

My only hesitation is that I'm not sure that on mobile I would have known that I could tap.

> Check out this CodePen on Chrome (the one on the left does not work in FF)

Can you clarify? I'm not sure what it's supposed to look like but it seems to work for me in Firefox. It's interesting because it starts with Firefox form suggestions but once I add the `@*` it hijacks Firefox's suggestions with domains.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/19537086/68817157-a76a0d00-0635-11ea-93bf-30a6fe17e07c.png">

**Comment by LZoog** [comment]
Good point on not knowing you can tap. I do like it otherwise.

Per our Slack convos... For some reason, the drop down does not want to work for me in FF (or Nightly), but works for you (but doesn't look great in Chrome). The dropdown also autopopulates the keyboard suggestions since it uses `datalist`. Hmm. 🤔

**Comment by chenba** [comment]
I think the suggestions should be based on the list in https://github.com/mozilla/fxa/pull/3287/files#diff-16bcf5624446195f98e13d97a897a4f0R15-R84.  That way there's consistency among this feature, mailcheck, and the MX record validation feature.

**Comment by LZoog** [comment]
(earlier comments were resolved in Slack, I'm working on a cross-browser solution with `datalist`)

Thanks @chenba!

@davismtl @ryanfeeley what do you think about that list? See "default domains" here: https://github.com/mailcheck/mailcheck/wiki/List-of-Popular-Domains

**Comment by ryanfeeley** [comment]
@LZoog I thought we had our own list, but if not, this looks fine. May not matter but it sorted by popularity?

**Comment by chenba** [comment]
I'll share our list with y'all.

**Comment by chenba** [comment]
The link I shared to the PR above is based on our list.  More importantly, it doesn't include domains such as gmil.com and gmai.com, which are valid and in our list but shouldn't be suggested.

**Comment by LZoog** [comment]
Yeah, I'm looking through it and see the `SECOND_LEVEL_DOMAINS` array but not sure about domain extensions from? That's when I found the link in my previous comment but that list is pretty short.

Just got your e-mail, I am not sure just how many suggestions we want this to show. One problem is that on Chrome in particular, I was having trouble limiting the number of drop-down options shown since it's native functionality to display them all, but FF and Safari start a scrollable list after it reaches 4 or 5. Alex and Ryan are OK with the suggestions showing one character after the "@" sign (such as "something@g"), but including the top 100 could change my approach.

@ryanfeeley  / @davismtl this issue was made listing the top 10. Do we want to show the top 20, 30, 100?

**Comment by ryanfeeley** [comment]
@LZoog I believe Alex had mentioned a number around 20 as the sweet spot, as it cover the most number of users without introducing long menus. Sometimes it's good to try a demo and see how it feels.

**Comment by davismtl** [comment]
Context is mostly from my metrics. I see only 20 domains in my metrics due and they represent 70-80% of emails we send. (other 20-30% goes under "other")

The volume of emails sent to hotmail.co.uk which is the 20th most popular is pretty low so in order to cover the last 20-30%, we would need to support a lot of domains and that might make for bad UX for the majority.

https://analytics.amplitude.com/mozilla-corp/chart/new/uif7xok

**Comment by davismtl** [comment]
@LZoog did an awesome demo in the product meeting. Started with 10 domains and will try 20 to see if Chrome bug makes the drop-down list.

**Comment by davismtl** [comment]
@LZoog @irrationalagent what might we want to track beyond the email-first form submit rate.

Should we track whether people used the auto-complete functionality? Can we?

**Comment by davismtl** [comment]
@davismtl FEATURE DOC!!!?

**Comment by sv-sdeiac** [comment]
Hello, I tried to verify this ticket and from my investigations, I found two issues related to the autocomplete domain during the registration flow.
#3518 and #3519 are the new tickets for those issues.

**Comment by davismtl** [comment]
Hi @sv-sdeiac, I reviewed those 2 issues and have closed them.

Those are two behaviors that are intentional and are as designed but that were not well documented since discussions happened in Slack.

Good catch and thanks for reporting them. Apologies for not better documenting those decisions.

**Comment by sv-sdeiac** [comment]
Due to the @davismtl comment, I'll close this ticket as verified, thanks.
