### ISSUE TITLE
Device Naming and Editing 

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#32]
I want my FF devices to be logically named so I recognize them and also have the ability to rename them.

**Comment by billmaggs** [comment]
Guys, we need to break this work down sooner rather than later so we can move it into next and now columns as work for 43. Who should be involved in this discussion? Unless I hear something here I will assume Rfeeley, Rkelly, Zach?

**Comment by rfk** [comment]
See #1009

**Comment by rfk** [comment]
> I want my FF devices to be logically named

Sync already has some logic for choosing a default device name.  Do we need additional work on top of that, or simply need to lift that information up into FxA?

@billmaggs also should this have "Firefox 43" milestone set here, or does that only happen when it gets into a certain state in aha?

**Comment by rfk** [comment]
> should this have "Firefox 43" milestone set here, or does that only happen when it gets
> into a certain state in aha?

Actually, I see a bunch of the metrics-related issues have "Firefox 43" milestone here in github, but are scheduled under "Firefox 42" in aha.  Is that managed by aha or something that we've layered on top of it?

**Comment by billmaggs** [comment]
That logic does not yet map across, AFAIK. Will check.

**Comment by rfk** [comment]
Thinking about it, I realize I'm making a lot of implicit assumptions about the scope of this bug.

Sync already has a notion of device names, with non-terrible defaults and the ability to edit them in the sync-preferences panel.  So I'm assuming this bug is mostly about lifting that ability up into core FxA rather than doing it down in sync, and e.g. allowing you to edit the description directly in some web-based devices view.  Do we need to clarify the user experience a little more here before we can break it down into units of work?

**Comment by billmaggs** [comment]
I am thinking that the Ux discussion is part of the breakdown work. From my
point of view and some others in our discussions  the device names we
mostly lift are the bare minimum and we should see if we can do more, and
yes it should become a core part of understanding (and eventually managing)
services across all your FF devices.

**Comment by rfk** [comment]
SGTM, I think the right path forward then is for me to continue working bottom-up on infra and APIs in mozilla/fxa-auth-server#1009, and concurrently kick off UX and design work with @ryanfeeley.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-18
