### ISSUE TITLE
Update production database to mysql 5.7

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#320]
Ops bug tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1504903

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-506)
┆Issue Number: FXA-506

**Comment by rfk** [comment]
First step: try this out on fxa-dev boxes

**Comment by vladikoff** [comment]
> First step: try this out on fxa-dev boxes


@rfk deployed at https://mysql57.dev.lcip.org

docker container: `910512ac894d        mysql:5.7.24 `

**Comment by rfk** [comment]
@jrgm do we have any poking that we'd like to do on a MySQL5.7 dev box besides just checking that it seems to work?

**Comment by jbuck** [comment]
I've migrated to mysql 5.7 in stage, QA is currently testing train 199 with it. Assuming that QA is green, we'll target the production migration sometime during the next two weeks

**Comment by jbuck** [comment]
Upgrade complete!
