### ISSUE TITLE
Remove email-first experiment code

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3205]
Once all of the brokers are converted to only support email first, we can safely remove the email-first experiment code.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-507)
┆Issue Number: FXA-507

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~vbudhram@mozilla.com] is this ready to be closed?
