### ISSUE TITLE
Audit production impact of gh-ost migration bug

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#321]
Ops bug tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1504905

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-510)
┆Issue Number: FXA-510

**Comment by vladikoff** [comment]
Ref https://github.com/github/gh-ost/issues/654

**Comment by vladikoff** [comment]
from mtg: @jrgm to add notes

**Comment by vladikoff** [comment]
cc @jbuck @jrgm any updates?

**Comment by clouserw** [comment]
Bugzilla bug is closed; closing this bug too
