### ISSUE TITLE
50% of Firefox iOS Registrations don't see CWTS.

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3213]
According to this chart, 50% of Firefox for iOS users don't see CWTS when registering to Sync:
https://analytics.amplitude.com/mozilla-corp/chart/new/prwip9u

This is substantially lower than all other OS that average about 15% drop off. (which is also alarming but less so)

When looking at registration rates, Firefox for iOS is not doing bad so this isn't preventing people from completing their registration. (good news)
https://analytics.amplitude.com/mozilla-corp/chart/new/at6k5ew

This leads me to believe there are two things potentially causing this anomoly:
- Users aren't seeing CWTS in some Firefox for iOS registration flows (I'm testing but haven't identified any yet)
- We are somehow not tracking the views.

In either case, we have a bug somewhere.

**Comment by davismtl** [comment]
It does not seem to be a specific entrypoint:
https://analytics.amplitude.com/mozilla-corp/chart/new/24s5ggz

**Comment by shane-tomlinson** [comment]
I wonder if we are sending the `login` notification to the browser before the metrics are fully flushed.

**Comment by juliemccracken** [comment]
Alex: Let's think about how we might improve reliability of our metrics for the next year! There might be an Epic that we should open up for work like this.
