### ISSUE TITLE
Organize payments React components into their own directories

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3218]
The `components` directory in `fxa-payments-server/src` is looking a little cluttered.

Unless someone has an opposing opinion, let's follow the convention we used in the `PaymentForm` directory for the rest of the components.

![image](https://user-images.githubusercontent.com/13018240/67965756-a5816200-fbd0-11e9-8927-2fbc39abf598.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-511)
┆Priority: Medium
┆Issue Number: FXA-511

**Comment by lmorchard** [comment]
Hmm, yeah... I've been on the fence about this: 

* On one hand, ugh, this *is* getting cluttered, now that the number of assets per component has grown. 
* On the other hand, if every component has a folder like PaymentForm - every component will have a filename of `index.jsx`

I disliked the similar filename problem on a previous project. But, I was using vim at the time. VSCode handles displaying the file path more sensibly in editor tabs. Maybe we should just bite the bullet and start moving them into folders? maybe vim users can look for a plugin to improve the situation there?

**Comment by LZoog** [comment]
@lmorchard Another option I've seen is something like `PaymentForm/PaymentForm.tsx`, but then the import is redundant (`PaymentForm/PaymentForm`), yet it could be a happy medium. That was the pattern in a popular React Udemy course I took a while back.

I do think they should go in their own directories whether we go this way or the `index` way - I'm making a new component now and adding 4 files for it makes `components` feel even worse. 😅

**Comment by lmorchard** [comment]
FWIW, after some more sleeping on it, I'd just go ahead and go with the `index.tsx` pattern - it makes imports simpler and we can probably finesse it in editors

**Comment by meandavejustice** [comment]
This is complete except for `fields` which is in a pr with a test failing, should be able to get test passing today, then I can close this issue
