### ISSUE TITLE
Investigate cause of unexpectedly bad query performance of `accountRecord_4`

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#322]
Ops bug tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1504907

**Comment by rfk** [comment]
Some investigations here: https://bugzilla.mozilla.org/show_bug.cgi?id=1504907#c5

TL;DR: definitely a unicode issue, which we can fix by doing this awful explicit cast to utf8:

```
CREATE PROCEDURE `accountRecord_N` (
   IN `inEmail` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin
)
```

It'd be nice to find a more thorough fix, but based on our previous adventure migrating the device-name column from utf8 to utf8mb4, I'm not sure hopeful...

**Comment by vladikoff** [comment]
@rfk could you try the same in mysql 5.7? would that be different , or possibly fixed?

**Comment by rfk** [comment]
> could you try the same in mysql 5.7? would that be different , or possibly fixed?

Unfortunately I get similar behaviour in MySQL 5.7.

**Comment by vladikoff** [comment]
@rfk for train-127?

**Comment by rfk** [comment]
I don't have any more "investigating" to do, I think we understand the issue well enough.  Perhaps we can close this in favour of https://github.com/mozilla/fxa-auth-db-mysql/issues/440 which is about adding the linter checks to prevent the issue in future?

**Comment by vbudhram** [comment]
This was fixed in https://github.com/mozilla/fxa-auth-db-mysql/issues/440 and https://github.com/mozilla/fxa-auth-db-mysql/pull/441.
