### ISSUE TITLE
Old Logo Displayed on iOS Sign In Page

### ISSUE THREAD

**Issue by athomasmoz** [mozilla/fxa#3222]
## Description

The old logo is displayed on the sign in page on iOS
![image](https://user-images.githubusercontent.com/43346208/67989047-eee0aa00-fbee-11e9-92bd-28ff8f10a246.png)

### Steps to reproduce

1. Open Firefox for iOS
2. Click the hamburger menu at the bottom right
3. Click "Sign in to Sync" (if your email is already shown and its asking for a password, click "Use a different account"

### Expected result

The Firefox Browser logo should be the new logo

### Actual result

The Firefox Browser logo is the old logo

### Environment

Firefox for iOS on v20
iOS device

**Comment by shane-tomlinson** [comment]
@ryanfeeley - hey, we brought this up while developing for Trailhead too. Should we get an updated logo for this, or should we just kill the one ups?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Updated logos. Can you access? https://drive.google.com/drive/folders/1yryPGL0dwyPrtqGL1oZxctXiEsjtOICq
