### ISSUE TITLE
(payments) Stripe test cards that should decline are accepted in local dev

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3223]
See: https://stripe.com/docs/testing#cards

`4000000000000002` should fail with a `card_declined` message. It correctly fails on stage, but is accepted locally.

FWIW, it looks like anything goes through if it passes client-side validation? I typed `2478912374289374` randomly and this was also accepted.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-512)
┆Issue Number: FXA-512

**Comment by LZoog** [comment]
@lmorchard do you have any insight on this?

**Comment by lmorchard** [comment]
This is because local dev is hooked up to [an internal stub API](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/subhub/stubAPI.js) that doesn't talk to subhub or stripe. 

We talk to Stripe for the `createToken` call, which I think does some basic validation. But, our `createSubscription` call doesn't actually hit the payment backend.

We have issue #1082 to include a subhub docker container in local dev. But, we haven't circled back to it because a) getting a working Docker container happened fairly recently and b) you need a private  Stripe API key for it to work.

**Comment by 6a68** [comment]
Maybe we could make the local dev mock a little more intelligent, and return error messages for the known bad testing card numbers?

**Comment by lmorchard** [comment]
> Maybe we could make the local dev mock a little more intelligent, and return error messages for the known bad testing card numbers?

Depends on why we'd want that? If you want to see the error messages rendered, that's what Storybook should be for. If you want to see how the whole system works, we should get Subhub included in the dev stack. I'd be worried that something in-between would be enough like the real thing to mask real issues or a slippery slope toward implementing most of subhub + stripe.

It would be nice if [stripe-mock](https://github.com/stripe/stripe-mock#future-plans) were a stateful pretend-Stripe, which might solve a lot of things

**Comment by LZoog** [comment]
> Depends on why we'd want that? If you want to see the error messages rendered, that's what Storybook should be for. If you want to see how the whole system works, we should get Subhub included in the dev stack.

Hmm yeah, I suppose my use case is a little bit of both; this came up for me while working on #3135. I'm creating a new component for this new type of error message, and while I can see the error in the flow by causing a network failure while updating a payment, I want to also see the error message when `createToken` fails when purchasing a new subscription to verify it looks correct there.

> In the end, I think the practical thing is that if you're going to work a lot on the payments side of FxA, you probably want to sign up for Stripe and get subhub running locally. 😞

Do we have any docs for this? Doesn't _sound_ particularly difficult? 😅

**Comment by lmorchard** [comment]
>  I want to also see the error message when createToken fails when purchasing a new subscription to verify it looks correct there.

For what it's worth, [I commented a bit on `createToken` vs `createSubscription` and where payments are processed over here](https://github.com/mozilla/fxa/issues/3151#issuecomment-548868278).

> Do we have any docs for this? Doesn't sound particularly difficult?

We don't have an explicit how-to doc on the setup overall. [subhub has some docs](https://github.com/mozilla/subhub#subhub) on prereqs to install and how to start up Docker. Beyond that, it's reading Stripe docs and getting an API secret key, along with fxa-auth-server tweaks.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

SubHub is no longer a thing so this no longer applies.
