### ISSUE TITLE
import open issues/pulls from fxa-amplitude-send repo

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3225]
The fxa-amplitude-send repo has been pulled into the monorepo, but there are some open issues and a few PRs that haven't been imported

**Comment by clouserw** [comment]
fxa-activity-metrics

**Comment by clouserw** [comment]
1 issue and 2 PRs left: https://github.com/mozilla/fxa-amplitude-send

**Comment by clouserw** [comment]
Turns out this isn't in the monorepo!  Closing this

**Comment by 6a68** [comment]
> Turns out this isn't in the monorepo! Closing this

Minor correction: it's in the monorepo, but doesn't currently build on Mac (because of node-parquet). There's some work to do before ops can migrate to using the monorepo version. We should talk about this at another time :+1:
