### ISSUE TITLE
Add aria-label to Modal/Alert Bar Close Buttons

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3227]

**Comment by jackiemunroe** [comment]
It looks like an aria-label was added to the modal with https://github.com/mozilla/fxa/commit/d9445ea5a85a9114a1d7242849d5d8a3e2fe18d2 . Are there other places that this ticket refers to?

**Comment by LZoog** [comment]
Closing - yep, looks like this was fixed in #3249. Thanks @jackiemunroe for poking around and finding that!
