### ISSUE TITLE
Support multiple 2FA devices [bz1593382]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3229]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1593382

Currently Firefox only support setting up a single 2FA, which is unfortunate because people may lost their 2FA device. Although there is a backup code, it is sometimes easier to have a dedicate backup 2FA device than trying to hide the backup code somewhere.

As an example, Yubikey can be used with Yubico Authenticator to store TOTP keys inside the hardware key, which makes it easy to have a second key to serve as backup when the primary one is lost. It is more secure and convenient than using backup code.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-513)
┆Issue Number: FXA-513

**Comment by clouserw** [comment]
The code is structured to support this, but it'll still be work to do.  Needs definition/priority.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We have recovery codes to help with the case where a user loses their 2FA device.

Maybe we can address this when we implement webauthn, closing for now.
