### ISSUE TITLE
 Prune the fxa_oauth.tokens table

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#323]
Ops bug tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1504908

**Comment by vbudhram** [comment]
Not authorized to view.

**Comment by rfk** [comment]
> switch to the different pruning query

What's the "different pruning query"?

**Comment by vladikoff** [comment]
@rfk , @jrgm mentioned something about that

**Comment by jrgm** [comment]
Pruned up to 2018-11-08 right now. Should complete this evening.

**Comment by jrgm** [comment]
> What's the "different pruning query"?

I was just wondering aloud if the original strategy `'DELETE FROM tokens WHERE clientId NOT IN (?) AND expiresAt < NOW() LIMIT ?'` would be better at maintaining the table, now that the table is smaller, than the strategy used of keeping track of `last-purge-time` and deleting a specific small list of expired tokens.

**Comment by jrgm** [comment]
This is done. Closing.

A systemd unit /etc/systemd/system/purge-expired-oauth-tokens.service on the prod fxa-admin box is now keeping this running (runs to delete all expired tokens every five seconds basically). I'm using the `last-purge-time` strategy which is doing fine, so sticking with it.

@jbuck to stop, in needed, `sudo systemctl stop purge-expired-oauth-tokens`. Logs in `journalctl`.

This cleanup task is showing no significant extra load on db. (With token pruning done, our Read I/O is relatively none, which is great.)

**Comment by jbuck** [comment]
Is this PRed yet? I don't want to lose it when the box inevitably dies
