### ISSUE TITLE
Address inconsistencies with crypto.randomBytes method

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3234]
discussion: https://app.slack.com/client/T027LFU12/GLV3KMZ8B/thread/GLV3KMZ8B-1572899039.169400?cdn_fallback=2

We have a custom rule in our `eslint-plugin-fxa` package that asks for a callback to be passed to `crypto.randomBytes`. In some places we have a promisified version which mistaken as an error with our current rule, and some instances where we silence the error. We should address these inconsistencies after the async epic work is complete.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-515)
┆Issue Number: FXA-515

**Comment by dannycoates** [comment]
I don't think we use randomBytes for any large buffer sizes. we can use sync randomBytes everywhere

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Wontfixing, but if we notice this next time we're in the crypto code, we can clean it up.
