### ISSUE TITLE
Security advisory in fxa-payments-server breaking CI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3238]
Looks like [a security advisory](https://www.npmjs.com/advisories/1300) is [breaking tests](https://circleci.com/gh/mozilla/fxa/107976?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link).

Seems like it's a sub-sub-dependency of `nyc`, the utility we use for test coverage reports on payments-server:
```
➜  fxa-payments-server git:(3098-autofocus-payment-name) ✗ npm ls handlebars
fxa-payments-server@1.148.8 /home/lmorchard/devel/fxa/packages/fxa-payments-server
└─┬ nyc@14.1.1
  └─┬ istanbul-reports@2.2.6
    └── handlebars@4.3.0 
```
This is [the latest version of nyc](https://www.npmjs.com/package/nyc), though. And we mainly use nyc in development. So, we might get away [with filtering](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/.nsprc) this advisory for now?

**Comment by clouserw** [comment]
We'll leave this open until nyc does a release

**Comment by lmorchard** [comment]
Another advisory around this just came up: https://www.npmjs.com/advisories/1316

Going to try forcing a handlebars update in our own dependencies, which might be a better mitigation for now.
