### ISSUE TITLE
Consolidate docs on https://mozilla.github.io/application-services/

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#324]
We have received feedback that it's often difficult to find various bits of documentation, either developer or relier. Right now "developer facing" documentation is on https://fxa.readthedocs.io/en/latest/, whereas "relier" documentation is on https://mozilla.github.io/application-services/. 

It would be easier if we could point *everyone* to one site. If we don't completely migrate the readthedocs.io docs to github.io, we could at least link out.

A quick kudos to @vladikoff who has single-handedly put together nearly all of our docs over the years.

ref #286

**Comment by rfk** [comment]
We also have "in repo" docs such as [1], and I wonder if that's a good place for developer-facing documentation if it feels out of place in a consumer-facing docs portal (i.e. keeping the docs close to the code that they're related to).

[1] https://github.com/mozilla/fxa-auth-server/tree/master/docs
