### ISSUE TITLE
Implement Upgrade Payments Page

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3241]
In order to allow for upgrading subscription we need to implement a new payments view for users going from lower tier to higher tier subs. @juliastarkov is working on final visual design here, but this view will have the following requirements:

- [ ] If the user is eligible for an upgrade, it should allow a user to upgrade by following a link to the higher tier product’s payment route
- [ ] If the user is eligible for an upgrade, it should show a payments UI with the following
  - [ ] A visual indication of the current product and the product being upgraded to
  - [ ] The user’s payment method
  - [ ] Indication that the user will be billed a new amount on N date
  - [ ] Indication that the user’s first payment will be a prorated charge (Note: @betsymikel is working on final content for this, we may need to include the prorated amount in this view but that is still TBD)
  - [ ] This just needs to be text, we don’t have to actually state the prorated payment
  - [ ] A checkbox/label for the user to verify the upgrade amount
  - [ ] A submit button that is disabled until the user verifies the checkbox
  - [ ] A verification redirect screen that shows the new product

A provisional design is here
![Group 3](https://user-images.githubusercontent.com/3323249/68225482-c858af80-fff0-11e9-8c77-120e5e80052f.png)

**Comment by johngruen** [comment]
Visual spec is here: zpl.io/V058dmm

**Comment by lmorchard** [comment]
Thinking out loud after the planning meeting today:

* I think we can implement this as just an alternate view for the existing product subscription page - i.e. a page like https://accounts.stage.mozaws.net/subscriptions/products/prod_FiJ42WCzZNRSbS?plan=plan_FiJ55YK6UYftPa

* If the user doesn't already have a subscription in the product set for the product & plan selected in the query string, we just show the current product subscription page.

* If the user *does* have a subscription in that product set, we show the upgrade view instead.

* So, the URL for both a from-scratch subscription and an upgrade is the same.

**Comment by lmorchard** [comment]
Slapping a high-ish estimate on this because the hidden work lurks in the backend API integration following on from subhub changes.
