### ISSUE TITLE
Implement Upgrade Prompt In FxA Subscription Settings

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3242]
![image](https://user-images.githubusercontent.com/3323249/68225560-e7574180-fff0-11e9-9a19-85cc1a451bed.png)

Products with an upgrade can provide a link to an upgrade page that they host as well as a string advertising the upgrade.

- [ ] It should show the provided string and link on subscription management page if available

**Comment by lmorchard** [comment]
Quick thing clarified from meeting today: No upgrade/downgrade logic here - it's just a piece of content to display. The upgrade CTA string is content tied to the *current* product - it links to a product lead page that describes and links to possible upgrades from there.

Possible ways to implement, off the top of my head:

1. We add this as a bit of Plan or Product metadata in Stripe, get it passed through Subhub, and we display it on payments-server.
2. We build a module in payments-server with a product_id-to-upgrade-string map and we display it.

Main difference is the former can be changed in Stripe admin without an FxA deployment, while the latter requires FxA code changes and a deployment.

**Comment by lmorchard** [comment]
Closed as part of #3241
