### ISSUE TITLE
Elevated level of content errors reported to sentry with train-149

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#3245]
https://sentry.prod.mozaws.net/operations/fxa-content-product/?query=is%3Aunresolved++level%3Aerror

e.g.,
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6148056/?query=is:unresolved%20level:error
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6323785/?query=is:unresolved%20level:error
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6148056/?query=is:unresolved%20level:error
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6602599/?query=is:unresolved%20level:error

**Comment by dannycoates** [comment]
On first review none of these look critical enough to roll the release back

**Comment by shane-tomlinson** [comment]
> On first review none of these look critical enough to roll the release back

Agreed, and when I merge common errors that have the same titles (e.g., e.onSubmitComplete is not a function), the relative rates stay constant across releases.

**Comment by habib** [comment]
That's great to hear! Can these be cleaned up/fixed so we reduce noise?
