### ISSUE TITLE
Check for "resovled": "http://" in npm-shrinkwrap.json

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#325]
@philbooth added `tls-shrink.sh` to almost all of our repos, the script converts all `http://` resolutions to `https:`, but only if we run `npm run shrink`. If we do an `npm install` and commit npm-shrinkwrap.json w/o re-wrapping, we often end up with `http://` resolutions. 

We could avoid this, possibly by running tls-shrink.sh as a post-commit hook, or banning "http://" from npm-shrinkwrap.json and checking for it in the lint scripts.

**Comment by pdehaan** [comment]
Personal curiosity, but if you're running latest Node 8/npm 6, why not just use the generated [package-lock.json](https://docs.npmjs.com/files/package-lock.json) instead of npm-shrinkwrap.json?

**Comment by shane-tomlinson** [comment]
> Personal curiosity, but if you're running latest Node 8/npm 6, why not just use the generated package-lock.json instead of npm-shrinkwrap.json?

We've discussed it loads, and there was some discomfort over the semantics of the two and when each is safe to use. @rfk explored when npm-shrinkwrap.json should be used vs package-lock.json and was going to report his findings. I think the summary is package-lock.json can be used for things like the content server that are top level installs, but not for things like fxa-js-client which is a dependency of other packages.

cc @vladikoff, @philbooth, @vbudhram - should we reconsider using package-lock.json?

**Comment by vladikoff** [comment]
@pdehaan because from what we read it is the same file anyway:

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json, which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages.

Whatever this loaded sentence means, it seems okay to just stay with shrinkwrap. We have existing Dockerfiles and other stuff that relies on those files being there. Also moving to package-lock doesn't help with the `http://` problem.

**Comment by vladikoff** [comment]
done in the PRs linked above ^
