### ISSUE TITLE
TypeError: t.print is not a function

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3255]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6453782/

```
TypeError: t.print is not a function
  at print (./views/settings/recovery_codes.js:116:35)
  at apply (./views/settings/recovery_codes.js:22:13)
  at apply (./views/base.js:199:11)
...
(1 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-519)
┆Issue Number: FXA-519

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

This is a bug in old-settings. Closing
