### ISSUE TITLE
Login is not working on AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/fxa#326]
STR:
1. Load AMO dev and try to login. 

Actual results:
502 Bad Gateway is displayed after clicking the button.

Expected results:
The User and password fields are displayed. The user can login. 

Notes:
Issue is reproducible from Dev Hub too.
Reproducible on AMO dev with FF63 (Win10).  Not reproducible on AMO stage.

![502 bad gateway](https://user-images.githubusercontent.com/33448286/48337209-ff5ce500-e66a-11e8-83f1-4cb07860db9e.gif)

**Comment by shane-tomlinson** [comment]
I kicked the tires, it's working again.

**Comment by shane-tomlinson** [comment]
@ioanarusiczki and sorry it went down and we didn't restart it sooner!

**Comment by ioanarusiczki** [comment]
@shane-tomlinson The login works again. Thanks for fixing it! Verified on AMO dev - FF63 (Win10)

![amo dev login1](https://user-images.githubusercontent.com/33448286/48352938-ce92a500-e696-11e8-8f2c-7d20f78d52b0.gif)

**Comment by ioanarusiczki** [comment]
@shane-tomlinson Hello, I'm afraid this issue is reproducible again today on AMO dev - FF63 (Win10)

![login not working today](https://user-images.githubusercontent.com/33448286/48471212-0c5d0e00-e7fc-11e8-859c-5f92af9b1a95.gif)

**Comment by rfk** [comment]
I restarted it again, but we need to figure out why it keeps crashing out...

**Comment by rfk** [comment]
Looks like we've got a pending fix that needs to be pushed out to this box; /cc @jrgm @vladikoff

**Comment by rfk** [comment]
If this goes down again prior to that fix getting pushed out, it can be restarted it via:

```
ssh ec2-user@meta-stable.dev.lcip.org docker restart oauth
```
