### ISSUE TITLE
Losing entrypoint on fxa_reg - complete

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3261]
I am observing a large spike in registrations on Fennec mobile where `entrypoint=none`

See: https://analytics.amplitude.com/mozilla-corp/chart/04iwt2n

When I investigate the event streams of the users with no `entrypoint`, we observe that the user had an `entrypoint` on `fxa_reg - view` and ``fxa_reg - submit`. Somehow we are dropping it for `fxa_reg - complete`.

[Example 1](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D118532944130?sessionHandle=W381g0E_W3812Zb_BuZHTEC_rg3_983639df1d884c939537f47890d2c461&eventId=9067bb74-f637-11e9-a810-0ab5c86372ce)
[Example 2](https://analytics.amplitude.com/mozilla-corp/project/178231/search/amplitude_id%3D118530479362?sessionHandle=W38vSrL_W38vThG_BuY95UC_rg3_f0f678d17963473c93ae3d0fa990146f&eventId=1760ff14-f633-11e9-bd91-06cfb6897594)

Those are the first two users I looked at that had `entrypoint=none`. What we observe is that they are also coming in from different entrypoints which means it is not caused by one specifically. (one is from firstrun and the other from the awesome-tab)

Per the above chart, this seems to have increased with train-148. (but it certainly increased further with the last Fennec release)

This bug is preventing the Fennec team from accurately measuring impact of changes to their recent onboarding changes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-521)
┆Issue Number: FXA-521

**Comment by davismtl** [comment]
If we look at registrations based on where the form was viewed rather than where the registration was completed, we get a pretty big difference in metrics.

https://analytics.amplitude.com/mozilla-corp/chart/04iwt2n/edit/liuu4mq

**Comment by clouserw** [comment]
@davismtl could you add a priority label to this (and future metrics issues)?  Thanks!

**Comment by davismtl** [comment]
This is high priority because it is not only preventing us from accurately measuring but preventing other teams like mobile from accurately measuring the impact of their product changes to improve account authentications.

**Comment by 6a68** [comment]
Looking at all fxa_reg complete events, where service is sync, and where entrypoint is none, and grouping by OS, this bug only seems to affect Android. Not iOS or Desktop. https://analytics.amplitude.com/mozilla-corp/chart/04iwt2n/edit/6p5q66w

**Comment by davismtl** [comment]
@6a68 that is correct. It's worst and Android. And Android got worst with fxa train-148.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Fennec is gone, and Amplitude is on the way out. Closing. Let's reopen if it's still occurring.
