### ISSUE TITLE
[RTL] Wrong padding for the account deletion section on FxA settings [bz1594549]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3262]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1594549

Created attachment 9107039
Screenshot

See attached.

Paddings to fix for RTL:
`.delete-account-product-list`
`.delete-account-checkbox-list`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-522)
┆Issue Number: FXA-522

**Comment by SaumyaSinghal** [comment]
I'm fairly new to this but I'd love trying to fix it. Can I take this up?

**Comment by Mayur500** [comment]
can I work on this issue? I am new to this so
Can you give a description of what to be done?
Thanks
