### ISSUE TITLE
Add a config to disable flow/activity metrics in the auth-server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3264]
Folks that self-host don't really need to emit flow and activity events, and in fact all those things do is clutter up their logs and cause confusion. We should add a configuration option that allows those events to be disabled.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-523)
┆Issue Number: FXA-523

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thanks for filing. Self-hosters can route the logs to /dev/null if that's what they'd like to do. Closing.
