### ISSUE TITLE
Backfill Country to SalesForce

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#327]
Lauren asked me about the feasibility of backfilling country to SalesForce records.

What would the effort of this be? IIUC, she would ideally need it for next week.

Story: As a marketer, Lauren would like to promote an event with only newsletter subscribers in the US.

**Comment by rfk** [comment]
Do you mean IP geolocation country data, or something else?

**Comment by davismtl** [comment]
Yes, IP geolocation country.
We currently pass language but not all EN-US are in the US.

**Comment by LaurenNiolet** [comment]
^What he said. 

I'm standing by to answer any questions you probably now have.

**Comment by rfk** [comment]
I don't believe we persist this information anywhere on our side, so I can't think of a good data source for the backfill here.

**Comment by rfk** [comment]
> I can't think of a good data source for the backfill here.

Alex points out that we don't store this data for the *account*, but we do track location information for each active login session on the account and we might be able to get it from there.  Non-trivial but I'll take a quick look at what might be possible...

**Comment by rfk** [comment]
In theory, we can obtain the geolocation info for a user's most recent syncs from redis, but it's non-trivial to get out.  We could in theory write a script to [scan](https://redis.io/commands/scan) through all the keys in redis to iterate over all users, pull out each user's session location data, try to sensibly resolve it into single country in the case where they have multiple active sessions, and spit out a list of (uid, country) pairs that could be imported into salesforce.

This seems fragile, I don't know what the load impact would be on the production db, and I don't have a good estimate for how long it would take such a script to run.  It doesn't feel like a good time+risk tradeoff to me to try to get that qa'd and running on a short timeframe.

**Comment by davismtl** [comment]
Thanks Ryan for investigating. I don’t feel comfortable with the risk here. 

I’ll speak with @LaurenNiolet about this.
