### ISSUE TITLE
Implement new subscription upgrade APIs in auth-server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3273]
Subhub will make API changes to support subscription upgrades. We need to update auth-server to expose those APIs to payments-server. This includes tests and whatever local API mocking we need in lieu of a solution for #1082

**Comment by bbangert** [comment]
This involves adding information to the `all plans` API call so that it includes the product set and product order, and one new call to upgrade the subscription plan.

**Comment by bbangert** [comment]
The upgrade API call must notify the auth server that the old product id is turned off, and the new product id is turned on. It must also clear the profile server's cache for this user so they are given the new product on request.

**Comment by lmorchard** [comment]
Something that just occurred to me as possibly a good idea: In the subhub response for plans, [we're going to include all plan & product metadata](https://github.com/mozilla/subhub/pull/364/files#diff-f403345a8c45bd2be07538e1d127fe97R140).

That will include [`capabilities:{clientID}` values](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=COPS&title=SP+Tiered+Product+Support#SPTieredProductSupport-MetadataAgreements). Those will be handy for calculating what capabilities to include in a user's profile based on RP client ID & subscribed products.

But [in the auth-server API that payments-server uses to fetch plans](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/subscriptions.js#L79), we might want to filter these metadata values out of the response. We don't need them for payments-server and we probably want to keep them somewhat secret.
