### ISSUE TITLE
Track amplitude metrics for subscription upgrades

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3274]
We will likely need to include some tracking for amplitude of product upgrades.

@irrationalagent Any input on what data we might want to include or how to represent a product/plan upgrade?

**Comment by johngruen** [comment]
Let's do these: 
* `fxa_pay_upgrade - view` on page view
* `fxa_pay_upgrade - engage` on engage with upgrade form
* `fxa_pay_upgrade - submit` on form submit
* `fxa_pay_upgrade - success` on form success
* `fxa_pay_upgrade - fail` on submit fail

Additionally, each of these should include all the event and user properties attached the similarly named `fxa_pay_setup` events
