### ISSUE TITLE
Authorization code expired about 30 seconds after being sent

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa#3277]
Just hit this in Firefox 70. I'm certain it's been less than a minute between when the code was sent and when I've tried using it.

![image](https://user-images.githubusercontent.com/465422/68439400-4d240480-017c-11ea-9257-20a417486a7a.png)

**Comment by grigoryk** [comment]
I've clicked "resend", got a new code in an email, tried it within less than 30 seconds of pressing "resend", and it worked fine.

**Comment by vbudhram** [comment]
@grigoryk hm interesting. That code should be valid for at least 10mins

https://github.com/mozilla/fxa/blob/b5f7df167f2808ea6263ca2de439192380d8d48e/packages/fxa-auth-server/config/index.js#L1535

I'll take a peek and try to replicate this locally.

**Comment by shane-tomlinson** [comment]
> I'll take a peek and try to replicate this locally.

FWIW, I've had this happen too when testing against prod, except maybe 5 mins. Definitely not 10.

**Comment by clouserw** [comment]
If anyone else can reproduce this, please add a comment here with your scenario.  We're having some trouble reproducing this.

**Comment by davismtl** [comment]
I just experienced this again in a live demo with marketing.

During a live demo, Celest didn’t receive her code so she tried to resend it but got a token error.

I proceeded to share my screen to replicate. I received my first code, hit resend (but I got no error) and the second email I got had the same code as the first one. When I hit verify, I got the invalid message seen in @grigoryk 's screenshot.

No more than 10 seconds passed between receiving the email and entering it.

**Comment by shane-tomlinson** [comment]
I saw this several times yesterday too, on prod. Maybe 1 minute instead of 10 seconds. I'm wondering if there is clock skew between the servers or whether somehow, the totp lib configuration used to generate codes is different to the totp lib configuration used to verify codes.

**Comment by vasilicatamas** [comment]
I just reproduced this issue on Stage [1.151.0] using Firefox 70.0.1 under Windows 10 64-bit. Created a new account and clicked on “Need another code? Resend” link in order to check if 2 emails with the same verification code are sent. There were 2 mails in the inbox but the code was expired. Clicked again on “Need another code? Resend” link and a new code was generated. 

![Screenshot_4](https://user-images.githubusercontent.com/18114210/69639438-2f540c00-1065-11ea-970b-d17702844310.png)

**Comment by vbudhram** [comment]
Thanks @vasilicatamas, your screenshot helped me debug this :)

I think I've got the right fix in https://github.com/mozilla/fxa/pull/3492 which hopefully get landed in train-151.
