### ISSUE TITLE
Define initial metadata vocabulary for Products & Plans in Stripe

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3286]
Filing this as an issue, if only to have a place for discussion. This may also be a duplicate / parallel effort along with https://jira.mozilla.com/browse/COPS-867

Dumping some things off the top of my head here, we can review / revise / rework as needed:

## Product
Key | Value
-- | --
iconURL | Image URL for product
productSet | An arbitrary string used to group products in a set of upgrades & downgrades
productSetOrder | A number used for sorting products in a set
capabilities:{clientID} | Comma-separated list of capabilities enabled by this product for the Relying Party identified by {clientID} - e.g. `capabilities:dcdb5ae7add825d2 = 123donePro, 321donePro` 
upgradeCTA | HTML content string describing available upgrades from this plan. By convention, should include a link back to a product lead page. That lead page links back to FxA's plan subscription pages

**Comment by lmorchard** [comment]
An eventual concern here will be localization - especially considering `upgradeCTA`, but maybe also icons? We *could* conceivably do something with a naming convention - e.g. `upgradeCTA-{locale}` - but maybe we can do something smarter?

**Comment by lmorchard** [comment]
I'm also wondering if `productSet` should live in Plans?

**Comment by jackiemunroe** [comment]
Other Plan metadata:
Key | Value
------------ | -------------
upgrades | List of plan_ids that are eligible upgrades
downgrades | List of plan_ids that are eligible downgrades

These will be used to validate upgrade/downgrade requests

**Comment by lmorchard** [comment]
> These will be used to validate upgrade/downgrade requests

So, I *think* @bbangert was tossing around a notion of replacing `upgrades` / `downgrades` with `productSet` / `productOrder`.

That is, by using a common product set name, we can assemble a group of related products. And then product order can tell us the upgrade / downgrade relation, Might be a simpler thing to manage than a list in each product

**Comment by bbangert** [comment]
Yes, that was my thinking. It could be a bit more error-prone to have to change metadata per plan, than a single sort order on the product. Especially as I won't be surprised when they decide to add annual plans to each product.

**Comment by lmorchard** [comment]
FWIW, I just added `capabilities` to the proposed metadata in the issue comment. Kind of a nice to have for which we haven't yet filed any issues to support.

**Comment by lmorchard** [comment]
Going to close this as an issue, since we met about it on Friday and I think that's basically what I opened the bug for

**Comment by lmorchard** [comment]
Just to follow up, I think the resolution of this issue can be considered the creation of this section of a mana page:

https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=COPS&title=SP+Tiered+Product+Support#SPTieredProductSupport-MetadataAgreements
