### ISSUE TITLE
Integrate pairing with the reference browser

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#329]
ref: https://github.com/mozilla-mobile/reference-browser/issues/162

**Comment by vladikoff** [comment]
from mtg: after review from a-c, we need to write some Kotlin in a-c and 'copy pasta' the QR library

**Comment by shane-tomlinson** [comment]
@vladikoff did I imagine that this was done already?

**Comment by vladikoff** [comment]
Keep it open for now, need to think about what/where to track this

**Comment by vladikoff** [comment]
This is tracked elsewhere now
