### ISSUE TITLE
Device Contoller--Integration with Tabs From My Other Devices 

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#33]
I want views that make use of device names such as Tabs from My Other Devices to carry the same device naming and last synced information as the device/service dashboard

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-19
