### ISSUE TITLE
Subscription Email PN link is incorrect

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3301]
It should point to
https://www.mozilla.org/en-US/privacy/firefox-private-network/

**Comment by clouserw** [comment]
This is a link in the email

**Comment by clouserw** [comment]
This might be a server config

**Comment by lmorchard** [comment]
I just saw that this issue was closed, but: In what email from what environment was this link incorrect? PR #3448 may not have solved it for prod or stage
