### ISSUE TITLE
Resubscribe button padding is off

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3302]
![image](https://user-images.githubusercontent.com/3323249/68593494-df3a4e80-0495-11ea-8467-1d086dcac03c.png)

**Comment by LZoog** [comment]
@johngruen Is this happening on a particular device or OS? On my Mac in FF, shrunk down and in desktop, this looks good:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/13018240/68617873-bf9f2800-048d-11ea-9d07-735a101edb94.png">

**Comment by johngruen** [comment]
Very littte context here in this report, but try this...add some extra chars to the two strings to the left of the button and see what happens?

**Comment by LZoog** [comment]
Huh, thought I closed this yesterday. Patch here: #3335
