### ISSUE TITLE
Remove __version__ endpoint fallback values

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3305]
Suggestion from @jrgm in slack: "One thing in general which would simplify version.ts/version.js a lot is to remove the fallbacks and pre-bake everything in the docker build’s version.json file. And if you’re not a docker image, the /__version__ route just says unknown."

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-526)
┆Issue Number: FXA-526

**Comment by jrgm** [comment]
One thing I thought of now. Our deployment libraries for dockerflow/jenkins expect the current structure and name of /app/version.json. Some of it is configurable, but perhaps simplest to leave that `version.json` as is, and create a `version2.json` (or some name) with the new all baked-in values.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

This is working OK, wontfixing.
