### ISSUE TITLE
notify user if release.sh fails because of access rights to fxa-private

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3308]
right now it fails silently

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-527)
┆Issue Number: FXA-527

**Comment by 6a68** [comment]
Wil says: everyone on the team should have access now, and release.sh should get replaced once we figure out our new release strategy, so this shouldn't bite us until we hire again. Hence, backlogging for now.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

fxa-private is not referenced by the script any longer, closing
