### ISSUE TITLE
Cannot delete my account [bz1595520]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3318]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1595520

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

Steps to reproduce:

I started registration on https://accounts.firefox.com/ but entered incorrect email by mistake.
Now I am getting reminders about email confirmation to this email. I do not want to use this account because I already have an account linked to another my email.
The reminders I receive do not have a link that I should click to stop this notifications and remove unconfirmed account. Please add this link and let me know how can I remove this account with unconfirmed email.

Actual results:

I cannot delete my account that I've created by mistake.

Expected results:

Email confirmation email has a link "I did not register". Link should go to the page with button "I did not created this account. Delete it completely." that should remove all account related data and email from account.firefox.org and other related services i.e. ff sync and etc.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-528)
┆Issue Number: FXA-528

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Underlying BMO bug is fixed. Closing
