### ISSUE TITLE
(payments) Hoisted avatar off-center from FF logo

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3325]
This is regression from #3268 I did not see we needed to account for.

This is kind of done in a hacky way but we can refactor during redesign next quarter, for now I'm going to grab this and just adjust the `margin-top` that's already set.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/13018240/68694046-08aeb500-053e-11ea-85fb-0896db932d14.png">

**Comment by lmorchard** [comment]
Yeah, this was not my best work. I think I did it this way to try to reuse as much of the CSS from content-server as possible and just layer over it. But it's a terrible hack
