### ISSUE TITLE
Unpublish fxa-shared from npm

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3327]
We've been using `fxa-shared` via relative paths in the monorepo instead of via the npm package for a while now (see https://github.com/mozilla/fxa/pull/2126).

Is there any reason `fxa-shared` should still be up on npm? If not, let's take it down.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-362)
┆Issue Number: FXA-362

**Comment by dannycoates** [comment]
The work here is in updating any of our packages here to use the local fxa-shared and any dockerfile changes required.

**Comment by meandavejustice** [comment]
once #3614 is merged and makes it through trains we can unpublish

**Comment by meandavejustice** [comment]
package was marked `deprecated`
