### ISSUE TITLE
Document payments metrics

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3328]
Reminder bug: we should be sure to add payments metrics docs to the payments docs/ folder and the ecosystem docs repo.

**Comment by 6a68** [comment]
I *think* #3363 has the complete list of docs to update

**Comment by chenba** [comment]
Closed by https://github.com/mozilla/ecosystem-platform/pull/33 and https://github.com/mozilla/ecosystem-platform/pull/44
