### ISSUE TITLE
Clean up margin/padding/positions around FF logo and avatar from payments

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3336]
See #3329 - there is some weirdness/inconsistency around how we're displaying the FF logo (with a `::before` pseudo-element) with a lot of padding in place for `#main-content`, and the avatar shown in payments (a DOM element, visually displayed the same).

We probably don't need a negative `margin-top` on the FF logo, we can just use `top`.

In payments, we're having to set a very large negative `margin-top` on the avatar to account for the `#main-content` `padding-top`, and it's especially awkward in mobile. Let's see what we can do to clean this up.

Note: this probably goes well with the settings redesign next quarter.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-534)
┆Issue Number: FXA-534

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~lzugai@mozilla.com]Do you know if we've addressed this?
