### ISSUE TITLE
Unit / integration tests for fxa-amplitude-send

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3337]
AFAICT, there are no tests for the code that imports data into amplitude.

GCP PubSub provides an emulator that can be used to mock it out locally: https://cloud.google.com/pubsub/docs/emulator

I'm not sure what other pieces need to be mocked out; suggestions welcome :+1:

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-535)
┆Issue Number: FXA-535

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We're sunsetting amplitude, don't need the tests. Closing
