### ISSUE TITLE
switch to amplitude http api v2

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3338]
Looks like v1 http api is deprecated:

https://help.amplitude.com/hc/en-us/articles/204771828-HTTP-API

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-536)
┆Issue Number: FXA-536

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

No longer needed. Closing
