### ISSUE TITLE
Unable to create a Firefox account using an email previously used as secondary on another account [bz1595852]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3340]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1595852

Created attachment 9108175
firefox-new-account.jpg

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

Create an account and set a secondary email. Delete this secondary email and try to create a new account using it.

Actual results:

After entered the email and a new password, when I click on 'Create' the response is 'Primary account email required for signin'.

Expected results:

A new account should be created.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-538)
┆Issue Number: FXA-538

**Comment by ddbeck** [comment]
I was searching for help with this problem and found this issue. I didn't reproduce this from the steps in the original bug, but I did discover the same steps independently.

For background, my use case is to stop using my work email as the secondary email for my personal account (which I seem to have succeeded at—it's no longer listed in secondary email) and then create a separate account for that work email.

Please @-me if I can provide any additional details which might help fix this problem.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~vbudhram@mozilla.com]
