### ISSUE TITLE
Firefox logo is displayed behind the account image in the payment page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#3348]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- macOS 10.14.6

#### Steps to reproduce
1. Go to the [Full-Device VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page.
2. Click on the "Subscribe Now" button and make an account.
3. Observe the UI in the payment page.

#### Expected result:
- Only the Firefox logo is displayed in the top section.

#### Actual result:
- The Firefox logo is displayed behind the account image.

![image](https://user-images.githubusercontent.com/17178945/68748365-fcd9f600-0604-11ea-8b23-9be7d8af701a.png)

**Comment by LZoog** [comment]
Dupe of #3325 / fixed by #3329
