### ISSUE TITLE
Stage Avatar thingy is broken

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3356]
![image](https://user-images.githubusercontent.com/3323249/68788425-a5a74600-0643-11ea-804b-ef05d388c5f6.png)

Oh no

**Comment by LZoog** [comment]
Dupe of #3325 + #3348 / fixed by #3329

**Comment by johngruen** [comment]
lol, thanks!

**Comment by LZoog** [comment]
😛 I noticed it yesterday and took care of it because it's a little horrendous.
