### ISSUE TITLE
Optimize the email first login form for Firefox Reality

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#3358]
![image](https://user-images.githubusercontent.com/128755/68792605-a32ff680-0619-11ea-95e2-3bf8b9271a3a.png)

Reported by the FxR team, they would prefer to have something that fits the VR Tab

cc @ryanfeeley @johngruen

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-544)
┆Issue Number: FXA-544

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

No longer needed, closing.
