### ISSUE TITLE
content-server fails to find chosen-js

### ISSUE THREAD

**Issue by johnsey** [mozilla/fxa#3384]
## Description

content-server fails to resolve chosen-js as reported by _pm2 log_ despite it being installed.

### Steps to reproduce

Check out fxa on branch master and perform installation steps according the Readme.md.

### Expected result

content-server should start without error and be usable.

### Actual result

Connecting to the content-server on port 3030 just displays a loading animation which loops forever.
The following error is shown in the log files:

>11|content-server PORT 3030            | ERROR in multi lib/jquery backbone chosen-js cocktail-lib duration es6-promise jquery mailcheck js-md5 modal raven speed-trap ua-parser-js uuid vat styles/main.scss
11|content-server PORT 3030            | Module not found: Error: Can't resolve 'chosen-js' in '/home/fxa/fxa/packages/fxa-content-server/app/scripts'
11|content-server PORT 3030            |  @ multi lib/jquery backbone chosen-js cocktail-lib duration es6-promise jquery mailcheck js-md5 modal raven speed-trap ua-parser-js uuid vat styles/main.scss appDependencies[2]
11|content-server PORT 3030            | ERROR in ../app/scripts/views/support.js
11|content-server PORT 3030            | Module not found: Error: Can't resolve 'chosen-js' in '/home/fxa/fxa/packages/fxa-content-server/app/scripts/views'
11|content-server PORT 3030            |  @ ../app/scripts/views/support.js 12:0-19
11|content-server PORT 3030            |  @ ../app/tests/spec/views/support.js
11|content-server PORT 3030            |  @ ../app/tests/test_start.js
11|content-server PORT 3030            |  @ ../app/tests/webpack.js
11|content-server PORT 3030            | ℹ ｢wdm｣: Failed to compile.

chosen-js is installed though:

> $ npm view chosen-js
chosen-js@1.8.7 | MIT | deps: none | versions: 12
Chosen is a JavaScript plugin that makes select boxes user-friendly. It is currently available in both jQuery and Prototype flavors.
https://harvesthq.github.io/chosen/

### Environment

xubuntu 19.10
npm@latest
chosen-js@1.8.7

**Comment by shane-tomlinson** [comment]
> xubuntu 19.10
> npm@latest
> chosen-js@1.8.7

Are you using node 12 or 10? Unfortunately we are still on node 10.
