### ISSUE TITLE
fxa-payments-server-1: https://npmjs.com/advisories/1316

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#3391]
see https://circleci.com/gh/mozilla/fxa/115109?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by vladikoff** [comment]
Same with the support panel: https://circleci.com/gh/mozilla/fxa/115101?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by lmorchard** [comment]
Advisory 1316 in payments-server should have been fixed with PR #3377. Might need a rebase?

Not sure about support panel, though

**Comment by bbangert** [comment]
I just checked fxa-payments-server, fxa-event-broker, and fxa-support-panel. npm audit is showing no issues now. A prior commit must've fixed this.
