### ISSUE TITLE
Make sure choose what to sync metrics are emitted from the login flow

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#3394]
Apparently, after desktop decoupling, users will be electing what to sync during the process of logging into an additional device. Currently, they only have to make this election during registration. We have these events:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/5625313/69077071-07740100-09f2-11ea-8eed-647b5b84bf9b.png">

to the extent that these events will also now exist in the login flow, we should start emitting analogous events to above that start with prefix `fxa_login` rather than `fxa_reg`.

**Comment by rfk** [comment]
> after desktop decoupling, users will be electing what to sync during the process of logging
> into an additional device

I don't believe that's accurate, yet - although we'd like to get to that point eventually, right now CWTS is only shown during signup.  Signin gets a different "Choose *Not* To Sync" screen that doesn't offer data choices.

When we do implement such a thing, we should make sure to line up the metrics to match what's done on signup.

**Comment by irrationalagent** [comment]
cc @davismtl ^^ so I think for the near term [vlad's PR](https://github.com/mozilla/fxa/pull/3389) should cover us here. i suppose we can close this for now and re-open when it becomes relevant again.
