### ISSUE TITLE
Device Controller- User View 

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#34]
I want a place to go when I think that something might be wrong with Sync to be able to see when a sync last occurred.

**Comment by rfk** [comment]
@billmaggs I don't understand the difference between this story and the story in #30.  Can you please clarify, or if they're very similar, maybe merge them into  single story?

**Comment by billmaggs** [comment]
They are different uses cases that could be solved by the same user experience (or not). #30 is a home base for a user to see data about their connected experience for any reason. Could be because they have added a new device, or look at what they are connected to, or how Sync is working, even how much space it is taking up if they are hosting it. 

#34 is specifically to provide them a place to go when they think something is wrong, 

#34 here is specifically a place to go when someting goes wrong.

**Comment by rfk** [comment]
OK, that makes sense, thanks @billmaggs

**Comment by billmaggs** [comment]
This is here: https://mozilla.aha.io/requirements/FXA-16-1

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-16-1
