### ISSUE TITLE
Subscription management page shows incorrect cancellation date

### ISSUE THREAD

**Issue by stlhood** [mozilla/fxa#3400]
## Description

When the user cancels their subscription and then visits the Subscriptions page for their FxA account, there are two dates shown: (a) the date that the user cancelled their service, and (b) the date that their service will end. (b) is correct but (a) is very wrong. 

SubHub is not actually sending a date for (a), only for (b). FxA PM and design should determine if showing date (a) is critical. If so, we'll need to add it in SubHub and then FxA will need to make updates to use the new value. If not, FxA should remove this line of text from the page.

### Steps to reproduce

- Create a new FxA user in production
- Subscribe to a plan
- Cancel that subscription
- Visit the user's FxA subscriptions page

### Expected result

The page should say: "You cancelled your subscription on [today's date, since you cancelled the user's subscription just now]".

### Actual result

The page instead says: "You cancelled your subscription on December 31, 1969."

![image](https://user-images.githubusercontent.com/42821/69103172-87fa2800-0a19-11ea-8d13-10752f5579ad.png)

### Environment

Seen in production.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-551)
┆Issue Number: FXA-551

**Comment by lmorchard** [comment]
> SubHub is not actually sending a date for (a), only for (b). FxA PM and design should determine if showing date (a) is critical.

Hmm, I'll check into this today: IIRC, we should be recording a date in the FxA database when the user hits the cancel button. So, subhub doesn't send the date, but I *thought* we had our own record over here.

Though, it occurs to me that if cancellation happens *not* via the user clicking "cancel" on FxA, this date might not get set in our database. I wonder if that's what happened here? If so, then that would be a case where we'd need that info from subhub

**Comment by stlhood** [comment]
Ah ha, that's exactly what happened. This user's subscription was cancelled directly via the Stripe dashboard, as a simulation of a support agent cancelling a subscription on the customer's behalf. 

Sounds like in the short term, where there is no date stored in the FxA database, no date should be shown at all. Longer-term we could pass this via the SubHub payload, as you said.

**Comment by johngruen** [comment]
Can we just hide the string if we don't have access to the date?

**Comment by johngruen** [comment]
Easiest thing would just be to hide that first string altogether until we iron out how we want to store the cancellation date piece. Either way, given that this issue derives from stripe-based cancellation, i don't think it's a blocker.

**Comment by lmorchard** [comment]
Closing this - we never moved to record the cancellation date anywhere and so this message is just not displayed anymore (let alone incorrectly). 

We should open a new issue if we want to revisit displaying the date when a user cancelled. (i.e. as opposed to when they're going to lose access, which we *do* display)
