### ISSUE TITLE
Secondary email account not also deleted when firefox account is deleted [bz1596754]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3401]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1596754

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0

Steps to reproduce:

Created firefox account previously. 
Added contact@mattwaler.com as secondary email. 
Deleted account. 
When creating a new account, I am unable to use the secondary email address as a primary or secondary email address. It claims to still be in use by a valid account, despite not being the case.

Actual results:

I am unable to use the email address, it claims the address is already in use by a valid account.

Expected results:

I should be able to use the email address with a new account since that account was deleted.

**Comment by rfk** [comment]
I tried but was unable to reproduce this.

**Comment by vasilicatamas** [comment]
I was also unable to reproduce this issue on FxA Prod 1.150.9 using Firefox 72.0a1 (2019-11-24), Firefox 71.0.b12 and Firefox 70.0.1 under Windows 10 64-bit and Mac OS X 10.14.6. After the FxA account is deleted, both Primary and Secondary emails are available for new accounts creation.

![secondaryemail](https://user-images.githubusercontent.com/18114210/69547286-f6049900-0f9d-11ea-8062-052a913598ec.gif)
