### ISSUE TITLE
[content server] Update the Second Level Domain List in Mailcheck

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3403]
Once the experiment for email domain MX record validation (#3196) is over, we should update the list of second level domains in mailcheck based on our list of top domains.

See https://github.com/mozilla/fxa/pull/3287/commits/6e5714881980035daa086bdd2dddd9674f67654b#diff-16bcf5624446195f98e13d97a897a4f0R38-R84

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-552)
┆Issue Number: FXA-552

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~bchen@mozilla.com]Do we still want to do this? Is this experiment still running?

**Comment by chenba** [comment]
The experiment is not running anymore.  I'll close this because the number of blocked sign-ups has been pretty low, and we didn't save the blocked domain names anywhere afaict.
