### ISSUE TITLE
Buttons on payments-server subscription management view are too wide

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3404]
Looks like the change / cancel buttons on payments-server subscription management have gotten too wide.

`git bisect` tells me that this is where the change happened: 3ca66354fad19cecce33a3a8cd3d3a2eec2a61f4

Storybook example: http://mozilla.github.io/fxa/fxa-payments-server/?path=/story/routes-subscriptions--subscribed

Expected:
<img width="329" alt="Capture" src="https://user-images.githubusercontent.com/21687/69166809-b3782380-0aa8-11ea-920a-54b28ea8b0dc.PNG">

Actual:
<img width="334" alt="Capture2" src="https://user-images.githubusercontent.com/21687/69166813-b6731400-0aa8-11ea-9aa1-378431c029c0.PNG">

**Comment by lmorchard** [comment]
@LZoog I might look at this later today. But, if you have a chance to peek, you will probably fix this faster than me

**Comment by LZoog** [comment]
Ewwwwww yeah I can grab this and get it fixed today.
