### ISSUE TITLE
Update Fortress to support two tiers

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3407]
Pro and Pro Plus

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-553)
┆Issue Number: FXA-553

**Comment by lmorchard** [comment]
Some notes on where we've ended up with defining tiers [with metadata](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=COPS&title=SP+Tiered+Product+Support#SPTieredProductSupport-MetadataAgreements):

* Add `productSet = 123done` metadata to each Product in the set of tiers
* Add `productOrder` metadata to each Product in the set of tiers, where the value is a number that will be used to sort them in order of upgrade / downgrade. (e.g. so the lower tier could be `productOrder = 0` and higher tier is `productOrder = 1`
* Add `upgradeCTA = some HTML string` to the lower tier(s) with call-to-action content to inform user about upgrades from that tier

**Comment by lmorchard** [comment]
Also, this same metadata can be added at the Plan level, and it will override the Product metadata - e.g. if you use two Plans within the same Product, you can specify different `upgradeCTA` for each Plan

**Comment by lmorchard** [comment]
FWIW, to test things out, I used this metadata in my personal Stripe account on a product and things seemed to work okay:

<img width="397" alt="Capture" src="https://user-images.githubusercontent.com/21687/69442594-b3269500-0d01-11ea-9e24-09a5bbd104e8.PNG">

Something like this should work for products in the Stripe account for stage / prod

**Comment by johngruen** [comment]
@rbillings @bsurd this is now testable on stage with the following prod and plan names
```
base
prod: prod_FfiuDs9u11ESbD
plan: plan_FfiupsKXZ3mMZ6
upgrade
prod: prod_GVNS86uMUO3VRM
plan: plan_GVNTBblhnCobNa
```

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

If this is testable, should we close it as done so it can follow the regular QA flow?

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

We're gonna do this on fortress instead b/c it's less fragile and not connected to fxa tests

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Docs on Stripe metadata FWIW:

https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#configuration
