### ISSUE TITLE
Preserve utm_* params thru oauth redirects

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa#3412]
## Description

Preserve `utm_*` params thru oauth redirects.

### Steps to reproduce

1. Go to https://monitor.firefox.com/oauth/init?utm_source=TBD&utm_campaign=TBD&form_type=email&flowId=XXXX&flowBeginTime=YYYY&entrypoint=mozilla.org-whatsnew67
2. Click "Sign in"

### Expected result

Redirect to https://monitor.firefox.com/user/dashboard?utm_source=TBD&utm_campaign=TBD

### Actual result

Redirect to https://monitor.firefox.com/user/dashboard

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-554)
┆Issue Number: FXA-554

**Comment by vladikoff** [comment]
> Redirect to https://monitor.firefox.com/user/dashboard

hm in the actual result do you get a ```https://monitor.firefox.com/user/dashboard?code=..&state=..?```

**Comment by rfk** [comment]
One option here may be for Monitor to preserve these itself as part of the `state` parameter.

**Comment by vladikoff** [comment]
but anyway, I believe we preserve some params, UTM might not one of them yet...

**Comment by shane-tomlinson** [comment]
> but anyway, I believe we preserve some params, UTM might not one of them yet...

We don't, but we could here:
https://github.com/mozilla/fxa/blob/43dea31e4f45d2821e7c0f45dc055a49aa15c327/packages/fxa-content-server/app/scripts/models/auth_brokers/oauth-redirect.js#L120

**Comment by clouserw** [comment]
@davismtl what priority would you set here?
