### ISSUE TITLE
Work out / document where to host images for subscription products

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3416]
TL;DR: nail down the where & how for hosting images with predictable URLs that we can copy/paste into a Stripe product `webIconURL` metadata field.

For #2026 & #3244, we need a place to host subscription product images.

This might be as simple as deploying images along with general FxA deployments on our train schedule.

We could also consider a CDN or image host that's managed separately and is independent from FxA pushes.

**Comment by lmorchard** [comment]
@johngruen btw, this is the issue I promised to file from this morning

**Comment by lmorchard** [comment]
Filed issue #3452 as I just realized we need to make sure payments-server CSP headers are copacetic with wherever these images are hosted.

**Comment by clouserw** [comment]
@johngruen will talk to @jbuck and @jrgm about this today

**Comment by lmorchard** [comment]
Interesting fact that I just realized about the FPN icon we're using on payments-server: It's an inline `data:image/svg+xml;base64` URL.

But, alas, we can't stuff data-encoded images into [Stripe metadata](https://stripe.com/docs/api/metadata) if they're over 500 characters:

> You can specify up to 50 keys, with key names up to 40 characters long and values up to 500 characters long.

**Comment by jbuck** [comment]
We can upload files to the content server CDN, https://accounts-static.cdn.mozilla.net and refer to them from there

**Comment by lmorchard** [comment]
> https://accounts-static.cdn.mozilla.net

Cool, if we can do that, then adding that host to CSP will resolve #3452 

Main thing for this issue would be making sure we have the CDN upload process documented somewhere (i.e. I don't know how to do that)

**Comment by jbuck** [comment]
> Main thing for this issue would be making sure we have the CDN upload process documented somewhere (i.e. I don't know how to do that)

@jrgm and I can upload files - do you think there will be enough churn to create accounts for you/others to upload files?

**Comment by lmorchard** [comment]
Alright, how about this:

- We create a directory in the fxa repo - i.e. `assets/product-icons`.
- Any product icons get checked in there.
- We add an `upload.sh` script in that directory which can semi-automate pushing the icons to the CDN, assuming the user has the correct credentials / env vars whatever
- Whenever icons need deploying, we ask @jbuck or @jrgm to run the `upload.sh` script.
- Icons show up at `https://accounts-static.cdn.mozilla.net/`
  - One question: Is there a subdirectory we should use here? i.e. https://accounts-static.cdn.mozilla.net/product-icons/

**Comment by lmorchard** [comment]
I'm actually going to call this closed. We have a process, we can try it out once we have icons.
