### ISSUE TITLE
Use /app/scripts/lib/sentry.js throughout content-server client side

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3419]
There are instances where we were using raven directly for reporting certain errors in webchannel. When replacing with `@sentry/browser` in #3388, I decided to separate this issue out in order to get sourcemaps working asap. In addition to this change we should update `app/tests/spec/lib/channels/receivers/web-channel.js ` to spy on our sentry wrapper.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-556)
┆Issue Number: FXA-556

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~djustice@mozilla.com]Do you think this is still worth keeping open?

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

We can go ahead and close this, since we will be replacing content-server in the future, and most of the functionality has been moved to settings

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

No longer necessary, after settings work
