### ISSUE TITLE
WError: Unspecified error; add more logging here

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3424]
https://sentry.prod.mozaws.net/operations/auth-prod/issues/6701656/

```
WError: Unspecified error
  File "/app/lib/error.js", line 1303, in Function.AppError.unexpectedError.request [as unexpectedError]
    const error = new AppError({});
  File "/app/lib/senders/email_service.js", line 65, in marshallError
    return error.unexpectedError();
  File "/app/lib/senders/email_service.js", line 49, in Request.request [as _callback]
    err = marshallError(res.statusCode, body);
...
(10 additional frame(s) were not displayed)
```

We probably can't solve this sentry report in this issue, but we can pass through more data to this unspecified error and hopefully fix the reports in the future.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-558)
┆Issue Number: FXA-558

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We've lost the sentry data associated with this bug.
