### ISSUE TITLE
Can't log in after changing primary email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#3427]
## Description

Though Sync UI updated with the new primary email, when I installed the Firefox Notes extension, and tried syncing Notes, I was unable to log in at all.

### Steps to reproduce

1. Sign in to Firefox/Sync in desktop
1. Add secondary email
1. Make secondary email the primary email
1. Confirm new email address in Firefox/Sync UI (toolbar, prefs, etc)
1. Install Firefox Notes and select **Sign in to Sync**

### Expected result
* New primary email is shown so user doesn't have to retype email, password accepted

### Actual result
* Can't log in
![not-alright-alright-alright](https://user-images.githubusercontent.com/68213/69268186-a9375180-0b9c-11ea-987b-670850da761e.png)

### Environment

Nightly Mac

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-559)
┆Issue Number: FXA-559

**Comment by vladikoff** [comment]
We should clear the locally cached email after emails have been switched

**Comment by davismtl** [comment]
Based on Slack conversation, this is happening with most services.
This is pretty major if it's the case.

**Comment by vbudhram** [comment]
> Can't log in

@ryanfeeley If you click `Use a different account` you are still not able to login? Does the new attempt use the old email?

**Comment by ryanfeeley** [comment]
@vbudhram You are right, clicking use a different account does work, but the bug is pretty severe because no one would think to do that (as the right account is being shown above).

Luckily, if my change modications are correct, retention is still a lot higher for those that change their primary email than those that don’t. They are also different user types too probably.

https://analytics.amplitude.com/mozilla-corp/chart/7y22vf0

**Comment by davismtl** [comment]
For context, here is the volume of users per month adding a secondary email:
https://analytics.amplitude.com/mozilla-corp/chart/new/tk2unio

I suspect this volume will go up with the work @vbudhram is doing this quarter.

**Comment by clouserw** [comment]
Being able to log in with the secondary email is a better user experience, but we're unsure if there are security concerns.  @jvehent are there any concerns with this change?

**Comment by davismtl** [comment]
Talked w/ @vbudhram 
Another simple solution would be to include a link in the error message to the email-first form.
We also suspect that his solution to login with secondary email would be convenient but would not resolve the entire problem so he'll file another bug for what we would want to do longer term. We expect this problem to surface more often as we push users to add a secondary email and to audit their primary emails.

**Comment by arroway** [comment]
@clouserw Answering for Julien:
I can't think of any red flag right now which would discourage allowing login with secondary email.

However this is conditioned by the fact that we currently lack knowledge of all states and possibilities related to having a secondary email. There was a review done 2 years ago which outcome was basically: "we need to document all possible scenarios and associated states".

Given the intent to push users to add a secondary email, now might be a good time to have that discussion and perform a threat model so we have a clear view to inform these kind of decisions.
I'll reach out on Slack to figure out if and when.

**Comment by ryanfeeley** [comment]
@clouserw Is using secondary email as login related to the encryption key? Or is only the password used?

**Comment by rfk** [comment]
> Being able to log in with the secondary email is a better user experience,
> but we're unsure if there are security concerns.

Just wanted to link [my specific privacy concern](https://github.com/mozilla/fxa/pull/3460#discussion_r349963064) here for full context. TL;DR: because of how the onepw protocol currently works, you need to know the primary email address on the account so you can use it as a salt in a hashing procedure with the password. If a user attempts to sign in with their secondary email, and the server sends back an "unable to check your password, re-hash it using this different email address and try again" error to the client, we are revealing the user's primary email address to an unauthenticated caller.

**Comment by jvehent** [comment]
Can this be fixed by not returning the email address in the body of the error? (we shouldn't reveal informations in errors, generally speaking)

**Comment by rfk** [comment]
> Can this be fixed by not returning the email address in the body of the error?

We need to either communicate the primary email address to the client somehow, or need to change our login protocol to store an extra validator on the server side that uses the secondary email address as a salt for the hash. There is currently no way for the client to produce a correct `authPW` hash without knowing the primary email address.

**Comment by rfk** [comment]
(Actually, I remembered that we already have a version of this kind of leak for users who *change* their primary email address.  In that case, when you attempt to sign in with the new primary email address, the server sends back a similar error that reveals what the old primary email address was, so that the client code can re-hash the user's password and try again.)

**Comment by vbudhram** [comment]
This was fixed in https://github.com/mozilla/fxa/pull/4576, closin.
