### ISSUE TITLE
[Epic] 2FA reset process for subscribers

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3428]
## Overview

Overall process to reset a 2FA account (this will result in loss of stored data like a password change):
1. User reads Support KB article that contains an email address allowing them to contact support informing them of lost 2FA
2. Support agent requests Last 4 of cc and expiration date as first confirmation.
3. Support agent triggers FXA panel 2FA recovery button which sends an email to the FXa holders email to have them confirm they own the email
  a. “Someone is attempting to remove 2FA on your account. Please confirm this is you.” - From FXA transactional emails
4. Support agent sends 2 transactions between 0-99 and asks the user to confirm the amounts.
5. If support verifies the identity of the user and confirmed the user did not halt the 2FA reset process, they file a confidential bugzilla ticket tagging FxAccount ops & support lead that user has been verified. There is a 3 day delay before the FXa engineer takes action.
  a. Support lead confirms data and gives approval to reset in bug.
  b. FXA engineer removes the 2FA from the user’s account and sends a password reset to the FXA user
  c. When resetting we still delete Sync data

## Technical Requirements

The Support Panel shown for Zendesk requires the Zendesk ticket to have a user with a FxA uid attached (authenticated request). This change would allow for a panel to appear for users that do no have this, as submitting a ticket in the manner described is done when a user does not have access to their account (unauthenticated request).

### Support Panel Changes

For unauthenticated requests, the support panel displays either the first 2 of these, or the last one:
* `Send 2FA Recovery Email` button, or appends 'Again' if the email was already sent but the user has not clicked it. Clicking this will send an e-mail that:
  * Is sent to all the email addresses on record for the user.
  * Indicates a 2FA recovery has been requested and gives the user a link to halt the process.
  * Tracks whether we have sent a recovery email before.
  * Includes a time limited encrypted token that contains the users e-mail address.
  * Takes one to a FxA page that does not require authentication, which asks the user to confirm they did not request the 2FA recovery and records if they want to halt it.
* `Charge verification amounts to card` to trigger 2 charges of $0.01-$0.99 to the users credit card on file. The total amount will be credited to the account. This can only be clicked once and will be dimmed out after the first time its triggered. This button will only be usable after the `Send 2FA Recovery Email` button has been pushed.
* `User has requested this 2FA recovery be halted` if the user has clicked the link in the email to halt the process.

### Questions to Resolve

* Where do we store these temporary bits of state? Redis?
* How do we safely give the support panel access to those temporary bits of state?
* What token tech do we use for the TTL encrypted token? Something like Fernet? What token capabilities do we have already?

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-560)
┆Issue Number: FXA-560

**Comment by rfk** [comment]
> b. FXA engineer removes the 2FA from the user’s account and sends a password reset to the FXA user

FYI, I believe we have some existing technical mechanism to put  a users account into a "must reset" state, where we wipe their `kB` and don't let them log in until they complete a full password reset.  See the `must-reset.js` script in fxa-auth-server.

**Comment by shane-tomlinson** [comment]
Overall this seems reasonable, why 2 charges to the user's account?

**Comment by bbangert** [comment]
@shane-tomlinson I think our session yesterday morning cleared that up? To have a record of it here, 2 transactions are used to verify access to the credit card statement.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson I think our session yesterday morning cleared that up? To have a record of it here, 2 transactions are used to verify access to the credit card statement.

Yeah, for the record, 2 transactions provides more entropy rather than a single transaction.

**Comment by johngruen** [comment]
Do we refund the charges?

**Comment by bbangert** [comment]
`The total amount will be credited to the account.`

That's the planned way to handle it. We will take the Stripe charge.

**Comment by clouserw** [comment]
This is blocked on the Architecture 2.0 plan

**Comment by clouserw** [comment]
epics are tracked in jira
