### ISSUE TITLE
Convert l10n to Fluent

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3431]
Maybe should be paired with #3430

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-562)
┆Issue Number: FXA-562

**Comment by dannycoates** [comment]
ref https://bedrock.readthedocs.io/en/latest/fluent-conversion.html

**Comment by clouserw** [comment]
Also https://discourse.mozilla.org/t/handlebars-helper-for-i18n-of-templates-using-fluent/44980/5

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This will be handled with https://jira.mozilla.com/browse/FXA-999
