### ISSUE TITLE
Replace sjcl and node-jose with WebCrypto

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3434]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-565)
┆Issue Number: FXA-565

**Comment by shane-tomlinson** [comment]
> Replace sjcl and node-jose with WebCrypto

Emphatic +1! We have to make sure the required primitives are available in embedded/app environments like Lockwise and Send.
