### ISSUE TITLE
Update code to use "stable" Rust

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3435]
or "what to do with email-service?"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-566)
┆Issue Number: FXA-566

**Comment by vladikoff** [comment]
👍  

do you mean "stable" rust?

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We probably won't touch this code until it breaks :shrug: so we're just going to close this placeholder
