### ISSUE TITLE
There is no option to add PGP key for notifications from Mozilla. [bz1598228]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3439]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1598228

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

I checked the settings and preferences.

Actual results:

I could not find any place to add my public PGP keys so that the emails whether the notifications or any other services from Mozilla/Firefox should be encrypted.

Expected results:

There should be option to add PGP keys so that the emails from mozilla to user can be encrypted.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-567)
┆Issue Number: FXA-567

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Parent BMO bug wontfixed.
