### ISSUE TITLE
Sync options selected in registration form are not saved

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3440]
**Build:**
Prod [Train 1.150.5]

**Affected platforms:**
Windows 10 64-bit
Ubuntu 18.04.3 64-bit

**Steps to reproduce:**
1. Launch Firefox with a new profile and click on the FxA toolbar menu button.
2. Click on "Sign in to Firefox (Turn on Sync)" option.
3. Enter a Mozilla email address and click on "Continue" button.
4. Fill with a valid password and select a few sync options.
5. Finish the account creation flow.
6. Go to about:preferences#sync and check the sync options.

**Expected results:**
Only the sync options selected during the account creation flow are checked in about:preferences#sync.

**Actual Results:**
All sync preferences appears as checked in about:preferences#sync.

**Notes:**
This issue is a follow-up bug for #3080

![syncpreferences](https://user-images.githubusercontent.com/18114210/69347877-ef181680-0c7d-11ea-88eb-a8bd66c07b25.gif)

**Comment by shane-tomlinson** [comment]
ref #3080

**Comment by shane-tomlinson** [comment]
This looks like a problem with Nightly only, on release Firefox it seems fine. @vasilicatamas can you confirm this only happens in Nightly for you?

**Comment by shane-tomlinson** [comment]
Right, after about 5 goes locally using Nightly, "declinedSyncEngines" is empty even though I deselected everything. Need to dig in further to find solid STRs.

**Comment by shane-tomlinson** [comment]
Even on nightly against prod, this is intermittent. If I open the developer console and add the following event listener while at the "enter your email" screen, as long as "declineSyncEngines" shows up in the message, the browser detects which buckets I've deselected:

```
addEventListener('WebChannelMessageToChrome', evt => console.log('webchannel message', evt.detail), false)
```

> webchannel message {"id":"account_updates","message":{"command":"fxaccounts:login","data":{"email":"stomlinson+20191121@mozilla.com","keyFetchToken":"XXX","sessionToken":"XXX","uid":"XXX","unwrapBKey":"XXX","verified":false,"services":{"sync":{"offeredEngines":["bookmarks","history","passwords","addons","tabs","prefs","addresses"],"declinedEngines":["history","passwords","addons","tabs","prefs","addresses"]}},"verifiedCanLinkAccount":true},"messageId":null}}

**Comment by vladikoff** [comment]
It works for me, new account and i declined some engines:

![image](https://user-images.githubusercontent.com/128755/69366417-57f29500-0c64-11ea-8f9c-49b853fb2b35.png)

**Comment by shane-tomlinson** [comment]
One thing I have seen  when "declinedSyncEngines" is empty is the an extra sync bucket shows up, I forget if it's addresses or credit cards.

**Comment by shane-tomlinson** [comment]
Here's another WebChannel message:

{"id":"account_updates","message":{"command":"fxaccounts:login","data":{"email":"stomlinson+20191121@mozilla.com","keyFetchToken":"XXX","sessionToken":"XXX","uid":"XXX","unwrapBKey":"XXX","verified":false,"services":{"sync":{}},"verifiedCanLinkAccount":true},"messageId":null}}

What is strange there is the "services: { sync: {} }"

That means [this line is being hit](https://github.com/mozilla/fxa/blob/b43a5b7b05fe410ac1aa5be50791866863bbb005/packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-channel.js#L304) and [this line below to set offered/declinedEngines](https://github.com/mozilla/fxa/blob/b43a5b7b05fe410ac1aa5be50791866863bbb005/packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync-channel.js#L307) is *not* even though I *was* offered engines and deselected all but "bookmarks".

**Comment by shane-tomlinson** [comment]
@vasilicatamas - a fix for this has been shipped to prod, could you have a look to see if the issue is resolved?

**Comment by vasilicatamas** [comment]
> @vasilicatamas - a fix for this has been shipped to prod, could you have a look to see if the issue is resolved?

This issue is no longer reproducible on FxA Prod 1.150.6. Only the sync options selected in registration form are checked in about:preferences#sync. 
Tested on Firefox 72.0a1 (2019-11-21), Firefox 71.0b11 and Firefox 70.0,1 under Windows 10 64-bit and Ubuntu 18.14.3 64-bit.

![syncprefs](https://user-images.githubusercontent.com/18114210/69420676-cea49680-0d27-11ea-99fe-d89912f1b118.gif)

Based on the above mentioned I will mark this bug as Verified.
