### ISSUE TITLE
[content server] Support Form Amplitude Events Plan Id and Product Id Inconsistency

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3445]
#### Preamble 

The content server flushes metrics (that is, send them to the server) based on inactivity and on page unloading.

https://github.com/mozilla/fxa/issues/994 is the original issue for adding metrics to the support form.  (PR https://github.com/mozilla/fxa/pull/2481)

#### Current Behavior

The support form reports a plan id and a product id of the selected subscribed plan with its Amplitude events.  However, they are in a list of properties that is _per request_, not per event.  If the user has multiple subscriptions and updates the selected plan on the form, the reported plan id and product id are dependent of the metrics flush timing.

This mainly affects the "view" and "engage" events; a metrics flush is triggered by the page unload after a successful form submission, ensuring "submit", "success", and "complete" will have the correct ids.  The "fail" event is also susceptible, but less likely in normal usage (where people would type the message after selecting the plan).

#### Example

1. A user who is subscribed to A and B goes to the support form.
1. The user selects A, then switches context to something else, idling the support form.
1. The front end flushes its metrics from inactivity; "view" and "engage" are reported with the plan id and product id of A.
1. The user changes their selection to B.  Fill out the rest of the form, and successfully submits.
1. The "submit", "success", and "complete" events are reported with the plan id and product id of B.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-568)
┆Issue Number: FXA-568

**Comment by chenba** [comment]
@davismtl or @johngruen and @irrationalagent FYI.

**Comment by clouserw** [comment]
It's not clear if this is a bug or not.  Need input from y'all if there is anything to change here or not.  Marking `needs:product` for lack of a better label.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

No longer needed, phasing out amplitude
