### ISSUE TITLE
`start-android.js` script is broken from `servers.json` removal

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3457]
I came across this earlier today when trying to test with the GenyMotion emulator. Our docs say to run `npm run start-android` but the file still tries to load `servers.json`.

I was able to get it working temporarily for my purposes by changing this:
```
function createConfig () {
  var servers = require('../servers.json');

  function findConfig(name) {
    return servers.apps.findIndex(servers.apps, function(obj) {
      return obj.name === name;
    });
  }

  function setConf(idx, name, value) {
    servers.apps[idx].env[name] = value;
  }
```

to this:
```
function createConfig () {
  var servers = require('../mysql_servers.json');

  function findConfig(name) {
    return servers.apps.findIndex(function(obj) {
      return obj.name === name;
    });
  }

  function setConf(idx, name, value) {
    if (idx > -1) {
      servers.apps[idx].env[name] = value;
    }
  }
```

... but as I only needed to see the signup page, I did not update my FF config and run through any flows to verify everything works or optimize the script any further.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-573)
┆Issue Number: FXA-573

**Comment by vladikoff** [comment]
I think we can get rid of the Android script. OR it can do what the docs say:

https://github.com/mozilla/fxa#android-debugging

for example run the following:

```
adb reverse tcp:3030 tcp:3030 # Content server
adb reverse tcp:9000 tcp:9000 # Auth server
adb reverse tcp:9010 tcp:9010 # OAuth server
adb reverse tcp:1111 tcp:1111 # Profile server
adb reverse tcp:5000 tcp:5000 # Sync server
``` 
Plus start the servers.

**Comment by vladikoff** [comment]
> Plus start the servers.

and no changes to the running servers will be required I think

**Comment by dannycoates** [comment]
removed in #4533
