### ISSUE TITLE
Signing in with an unverified account uses links instead of codes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3459]
STR

1. Sign up with a new email address. Do not verify.
2. Sign in with the email from step 1.
3. A link is sent instead of a signup code.

**Comment by clouserw** [comment]
Expected result:  codes are used

**Comment by clouserw** [comment]
If we want to migrate all of the functional tests to codes, we'll need to fix this.

Also, we have stats of people getting sent links and were wondering how they were getting those...probably this!

**Comment by davismtl** [comment]
Here is the volume I'm observing in our metrics:
https://analytics.amplitude.com/mozilla-corp/chart/c5azi7v

**Comment by vasilicatamas** [comment]
Verification code is successfully sent when trying to sign in with an unverified account on:
- Firefox 71.0 under Windows 10 64-bit
- Fennec 68.4.0 under Android 8
- Firefox for iOS 21.0 under iOS 13.1.2
![Screenshot_5](https://user-images.githubusercontent.com/18114210/71902870-9dfbad80-316b-11ea-9751-6916b5102fd4.png)
