### ISSUE TITLE
Unable to verify account if the "verify" form is closed.

### ISSUE THREAD

**Issue by tublitzed** [mozilla/fxa#3476]
Against nightly, I just ran into a problem trying to signup as a new user:

Here's a [video recording](https://recordit.co/nb23TR4e5R) of the issue.

STR:

1. Sign up for a new account.
2. Instead of verifying using the verification code that is received via email (which I _did_ receive), close the form.
3. Now...try to verify your account. You'll find you have no way to get back to that form. Nothing in FxA settings, nothing when signing in and out again. Ie, when I try to login again, all I see is an "Open Gmail" link, which doesn't help since there was no link emailed to me.

This effectively blocks new users from verifying their accounts, so I'd consider it significant.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-577)
┆Issue Number: FXA-577

**Comment by vbudhram** [comment]
@tublitzed I followed your steps, but received a second email containing the verification link.

<img width="913" alt="Screen Shot 2019-11-25 at 10 35 34 AM" src="https://user-images.githubusercontent.com/1295288/69554182-6647f600-0f6f-11ea-90d8-0c0b98da99b9.png">

Does the second email never arrive?

**Comment by tublitzed** [comment]
@vbudhram - Ah, yes - confirmed that it did arrive; thanks for taking a look! That makes this much less of a significant issue then  IMO  - at least there is a way to get back to the form (verified that clicking "confirm email" got me there).

... I do think there's a way to improve the UX a bit here though:

@davismtl or @ryanfeeley - What do you think about adding a link like "Already have a verification code? Enter it here" to this form? 

![Screen Shot 2019-11-25 at 10 19 05 AM](https://user-images.githubusercontent.com/1756056/69555224-d5721a00-0f70-11ea-8930-b774ac2d17ad.png)

^ Ie, the problem with this flow as it stands now is that I click that "Open Gmail" link above, I then open the email with the verification link and have no idea what to do next. It's not obvious at all that I need to now look for another email.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

The new settings page has a link to resend a verification email, which takes you to the verification input form. Feels fair to wontfix this bug.
