### ISSUE TITLE
Release process: document what to do with train PRs into fxa-private 

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3480]
The release process creates a PR into fxa-private for each train, just in case we need to do a security fix into the private repo.

What should happen to these PRs after the next train is cut? For instance, train-148 PR seems unnecessary once train-149 is tagged. Do we close or merge these PRs? This should be added to the docs.

**Comment by clouserw** [comment]
It should be merged back in.  The diagram shows it.  If it should be clearer, please make a PR. :)

Here's a proposed new flow: https://docs.google.com/presentation/d/1UY0WVssIjo7AywgO76RtiQ--h8DIheaJwQagoH-6v5g/edit#slide=id.p
