### ISSUE TITLE
Public status page

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3483]
From #357, I discovered that FxA does have a status page (https://firefoxoperations.statuspage.io/), but it's only visible to employees.

A public status page makes sense for any consumer product, but especially one with paying customers.

Maybe we can get this started with a public fork / subset of the private status page material?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-579)
┆Priority: Medium
┆Issue Number: FXA-579

**Comment by clouserw** [comment]
@jbuck @jrgm is there a place where we can dupe this bug to?

**Comment by habib** [comment]
A publicly visible status page comes with an extra set of duties. This is being thought through on the ops side to be a solution for all services that are public, not just FxA.

**Comment by clouserw** [comment]
Ok, I'm happy to close this then.  Is there a place we can refer to for status updates?  (another bug?)

**Comment by clouserw** [comment]
@habib - is there a place where I can point people to so we can close this issue?  Thanks
