### ISSUE TITLE
Delay in processing Amplitude events 2019-11-25

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#3484]
Since 2019-11-25T02:00:00.000Z Amplitude event processing has been significantly slowed down, causing a build-up of almost 40M events now. This is due to a combination of adding a new Amplitude event type `fxa_rp - view` / `fxa_rp - engage` and a large data breach landing in Firefox Monitor that uses this new event. These new events trigger rate-limiting in the Amplitude identify api because they often happen close in time to one another, and if they appear in the same payload they'll always be rate-limited.

I have a PR up at https://github.com/mozilla/fxa-amplitude-send/pull/102/files that attempts to do some pruning of the identify api events before sending them, and waits for retries rather than nack()-ing the messages which doesn't seem to help unfortunately.

I can roll this out in production and I think it'll be able to process the backlog, but I think I should get some other eyes on it first...

/cc @mozilla/fxa-core

**Comment by irrationalagent** [comment]
FYI minor correction, the monitor ping is generating the `fxa_rp - engage` event. There is no `fxa_rp - view` event, there *is*  `fxa_rp_button - view` but that (should not be) triggered by the monitor ping - it is an older event that is triggered in different contexts.

**Comment by 6a68** [comment]
We discussed this in the fxa ops meeting today. Some notes: https://docs.google.com/document/d/1W7LwHimPhs11KphYdSaz6SiN31o796SQ0vb8FpU1WTQ/edit

Summarizing, the amplitude Identify API fails a batch with a retry error if the same `user_id` or `device_id` occurs more than once in the batch. The fxa-amplitude-send code processes queued events in groups of 10 without doing this deduping, and on failure, calls `message.nack()` to throw them back into the queue, where they may simply be put back on the head of the queue?

The current plan is to talk to amplitude about disabling this check temporarily to help us get through our backlog; in parallel, I'm writing a patch to reduce the batch size to 1 and increase worker concurrency to more than 1 to get caught up.

**Comment by clouserw** [comment]
This is resolved now.  All previous data is entered.  No data loss as far as we know.
