### ISSUE TITLE
Please reset my Firefox account [bz1599457]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3487]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1599457

Actually, I have been contributing in Mozilla since 9 years. 
https://mozillians.org/en-US/u/biraj/

This my email address brnet00@gmail.com

Recently, due to some virus problem, I need to reset my phone and computer. That time I forget to keep the keys of Firefox account. From then, till now I could not open my mozillian profile and reps profile and pontoon profile etc. It has really affected my contribution. I tried a many ways but I failed in all.

It would be great if you can please reset my account so that i can use it again for contribution purpose. 

Here I am cc-in Jeff, who gave me this link.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-580)
┆Issue Number: FXA-580

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

The underlying BMO bug was wontfix'd last year.
