### ISSUE TITLE
(sign-up) Repeat password balloon no longer shows

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3489]
I believe this is regression from https://github.com/mozilla/fxa/pull/3406. The balloon shows in commit 4a2420f21 before this was merged but no longer in e098929f4.

@ryanfeeley @davismtl do we want to rethink this now that we have the inline validation? When does it disappear?

With no inline validation but with balloon (sorry for cutoff):
![pw-balloon](https://user-images.githubusercontent.com/13018240/69651286-762a0d80-1035-11ea-8108-97c14676a20a.gif)

With inline validation and no balloon:
![pw-balloon-noshow](https://user-images.githubusercontent.com/13018240/69651298-7cb88500-1035-11ea-94b3-91667ead7a18.gif)

**Comment by vbudhram** [comment]
Oof yea this seems like it should at least show the password notes about encryption before the user starts typing.

**Comment by LZoog** [comment]
Yeah, I noticed this when starting on #607. We seem to want the "repeat password" field to also come up in mobile and behave the same as desktop.

**Comment by vasilicatamas** [comment]
This issue was verified as fixed on Stage[1.152.0] using Firefox 71.0 under Windows 10 64-bit. 

![Screenshot_1](https://user-images.githubusercontent.com/18114210/70696624-c3141200-1ccc-11ea-8d78-552b840ffbbf.png)
