### ISSUE TITLE
Create an OAuth relying party integration checklist

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#349]
OAuth relying parties need to be aware that integration with FxA carries some responsibilities, unfortunately those responsibilities aren't really documented anywhere. Let's create a checklist and supporting documentation on how to meet the checklist.

Ref https://docs.google.com/document/d/18l-EKwDyKwnUYUsvtud7j6AwfOe_ZA93YEkrBIjJe1Y/edit

**Comment by vladikoff** [comment]
might move to train-133

**Comment by shane-tomlinson** [comment]
cc @clouserw

**Comment by clouserw** [comment]
Thanks.  This is https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa
