### ISSUE TITLE
Can't create a new subscriptions in the stage env

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#3499]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- macOS 10.14.6

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button

#### Expected result:
- Payment page displayed

#### Actual result:
- The page is not loaded, error displayed:
![image](https://user-images.githubusercontent.com/15685441/69719934-36892180-111a-11ea-9cc5-40e059115901.png)

#### Notes:
- This issue is only reproducing in Stage
- It only started reproducing today
- Other flows that do not work: Accessing the Manage account page from the user drop down menu, accessing the subscriptions page  from the same menu

**Comment by lmorchard** [comment]
We'd need to get a look at server logs to diagnose this - might be a subhub issue? Alternatively, I think we did just deploy changes on FxA for #3243 upgradable subscriptions - they *shouldn't* affect things here, but a change is a change.

Also noticed some subhub issues mentioning deployments needing fixing? Not sure if that could be related.

https://github.com/mozilla/subhub/pull/408
https://github.com/mozilla/subhub/pull/407

**Comment by marty331** [comment]
@lmorchard @madalincm I reported the outage of SubHub prod-test (the environment this is connected to) last night in the Subscription-Platform channel.  The outage has been resolved and everything is fully functional again.  I believe this issue should be closed.

**Comment by johngruen** [comment]
Thanks @marty311...i is suspect this is down to the prod-test outage earlier?

**Comment by marty331** [comment]
> Thanks @marty311...i is suspect this is down to the prod-test outage earlier?

Yes that is correct.  Everything is up and running as of this morning. (11-27-2019 approx 7 am CST).

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [FPN-stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release (70.0.1).
Verified on Windows 10 x64.
