### ISSUE TITLE
Push in FxA- Performance Improvements 

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#35]
I want FF and my core browsing data to feel speedy and to the point both in general usage and when I am specifically interacting with synced data.
1a. When I am looking at another device's history, tabs, passwords, or other data types synced across my devices, I want FF to feel like it is propagating that information across my devices in a timely fashion.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-30-1
