### ISSUE TITLE
Readthedocs integration no longer working

### ISSUE THREAD

**Issue by gene1wood** [mozilla/fxa#350]
With [GitHub services being turned off yesterday](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) the Readthedocs integration has stopped working and changes to documentation will no longer result in updated to the readthedocs site for this project. Please create [a Readthedocs GitHub webhook](https://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation) to re-enable this functionality.

**Comment by vladikoff** [comment]
We moved off readthedocs to https://mozilla.github.io/application-services/ !
