### ISSUE TITLE
Support panel amplitude events are missing time

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3503]
Need to investigate, but jbuck mentioned some malformed events are winding up on the amplitude queue.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-582)
┆Issue Number: FXA-582

**Comment by clouserw** [comment]
These are malformed events (missing the `time` key) and are being discarded rather than processed.  This might be the support Form instead of the support Panel.

**Comment by chenba** [comment]
I do see data in Amplitude though (for support form)

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
