### ISSUE TITLE
Password Verification Tooltip Incorrectly Displayed

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3504]
There's a timing(?) issue somewhere that's causing the not matching password tooltip to be displayed, even when the passwords are matching.

![image](https://user-images.githubusercontent.com/198055/69743604-501f6e80-1104-11ea-9cdc-f1ce1ab031de.png)

**Comment by chenba** [comment]
The user can still successfully sign up.  It doesn't block form submission.

**Comment by vasilicatamas** [comment]
I’m suspecting that this is a dupe of #3486

**Comment by clouserw** [comment]
This is currently listening to the keyUp event.  We probably need to add support for the paste event (or whichever event gets triggered for pasting in a password)
