### ISSUE TITLE
Ensure we have sufficient metrics headroom

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3505]
We should make sure we have a plan to handle 2-10x spikes due to successful marketing campaigns or new products coming online (or RP code that's a bit buggy and submits dupes). This might just mean having a plan to contact amplitude and room in the budget.

**Comment by irrationalagent** [comment]
related https://bugzilla.mozilla.org/show_bug.cgi?id=1592123

**Comment by clouserw** [comment]
Regarding engineering - we have plenty of headroom now with the new code.

Regarding planning - we could do some.  Looking at every link in the chain would be good.  Once we have an architecture diagram that could help highlight any weak areas.  That's #2515
