### ISSUE TITLE
Add metrics usage estimates to PRD doc process

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3507]
When a new RP is planning to ship in a given quarter, we should be sure they document their best estimate of the total metrics volume they will generate, based on estimated number of users times the number of events generated per user.

Not sure if this is explicitly done already or not, but it will help with planning.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-583)
┆Issue Number: FXA-583

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
