### ISSUE TITLE
Move off of screencap.co.uk

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3513]
From slack:

lorchard: Also, we should maybe look into a different host for screencaps in our CI someday :slightly_smiling_face:  (iirc, that's shane's personal server and it might be polite to stop leaning on it)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-584)
┆Issue Number: FXA-584

**Comment by dannycoates** [comment]
maybe just save to circleci artifacts?

**Comment by vladikoff** [comment]
>maybe just save to circleci artifacts?

could be a lot of artifacts (is there a limit?) but might work!

**Comment by lmorchard** [comment]
The nice thing about the current screencap scheme is that we get links output along with the tests. Not sure if / how we can easily refer to & link to screenshots in artifacts? Beyond that, it would make a lot of sense if the screenshots were artifacts associated with the run.

**Comment by shane-tomlinson** [comment]
> (iirc, that's shane's personal server and it might be polite to stop leaning on it)

It is my personal server, I haven't thought too much about shutting it down yet, but I could use the server cost to buy another bag of coffee every month. :D
