### ISSUE TITLE
Sentry related buld-and-deploy-content-server failures on CircleCI

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3517]
I'm seeing this across PRs (including merge to master):

https://circleci.com/gh/mozilla/fxa/122286?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

> Running "webpack" task
> (node:23) UnhandledPromiseRejectionWarning: Error: Command failed: /app/node_modules/@sentry/cli/sentry-cli releases propose-version
error: Could not automatically determine release name
>
> Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:23) UnhandledPromiseRejectionWarning: Error: Command failed: /app/node_modules/@sentry/cli/sentry-cli releases propose-version
error: Could not automatically determine release name
>
> Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by shane-tomlinson** [comment]
This also happens locally whenever running:

```
> docker build -f fxa-content-server/Dockerfile-build -t fxa-content-server:build .
```

cc @meandavejustice

**Comment by shane-tomlinson** [comment]
If I run `/fxa-content-server/node_modules/@sentry/cli/sentry-cli releases propose-version` locally from `fxa/packages`, then the current git sha is returned. I wonder if the command is being run outside of a git repo.

**Comment by shane-tomlinson** [comment]
ref #3509

**Comment by meandavejustice** [comment]
These warnings stopped breaking builds in version `1.9.3` of sentrywebpackplugin https://github.com/getsentry/sentry-webpack-plugin/issues/148
