### ISSUE TITLE
The domain list is triggered only after typing the first character of a valid domain

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#3518]
### Steps to reproduce
1. Tap on the Hamburger menu;
2. Tap on the Sign-in to Firefox button;
3. Start to write an email on the email field(ex. qwerty@);

### Expected result
A domain list is triggered under the email field.

### Actual result
The list is triggered only if you type the first character of a valid domain name.

### Notes
- The list can be triggered if I click on the email field

### Environment
- Windows 10 - x64bit;
- Reproducible on Train 151 and production;
- Browser: FF 70.0.1(64-bit) and Chrome 71.0.3578.98 (64-bit);

**Comment by davismtl** [comment]
> The list is triggered only if you type the first character of a valid domain name.

This is the intended behavior. We do this to avoid recommending a very long list of irrelevant emails.

Here's a demo of @LZoog walking through the feature:
https://drive.google.com/file/d/1LBLAQiI593DBKQEr9On4UL5QqpHiE9gK/view
