### ISSUE TITLE
[Android]The domain list is triggered only after erasing a domain

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#3519]
### Steps to reproduce
1. Go to the settings and tap on Sign-in button;
2. Start to write an email on the email field(ex. qwerty@);

### Expected result
A domain list is triggered under the email field.

### Actual result
The domain list is triggered only if I write a complete domain and erase it.

### Environment
- Devices: Samsung Galaxy Note 8(Android 9);
- Browser: Firefox 68.3.0;

### Notes
- On iOS, an arrow is presented for the list and tapping on it, the keyboard is changed with a list.
![IMG_0003](https://user-images.githubusercontent.com/40264165/69793148-8f1af600-11d0-11ea-8b4d-1ab65479cb7a.PNG)

**Comment by davismtl** [comment]
This is as expected per this demo:
https://drive.google.com/file/d/1LBLAQiI593DBKQEr9On4UL5QqpHiE9gK/view

**Comment by davismtl** [comment]
CC @LZoog
