### ISSUE TITLE
Former primary email instead of new primary email is displayed as signed in in new browser profile

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/fxa#3522]
## Build
Stage [Train 1.151.0]
Firefox Beta 71 Stage. 
This issue does not occur in Production. 

### Steps to reproduce
1. Create on Profile A a new account (ex:primaryemail01@yopmail.com) and verify that email. 
2. Navigate through about:preferences and click on Manage account link. 
3. On the Manage account page add a new secondary email and verify it. (ex: secondaryemail02@yopmail.com)
4. Make secondary email primary and refresh browser after which check that the account logged into the browser has been updated to reflect the change of primary email. 
5. From about:profile a new profile can be created. In that new profile, Profile B,  sign in through any of the sign in entries (toolbar, hamburger menu,etc) with the new primary email (ex: secondaryemail02@yopmail.com) .
6. Check manage account page and the browser toolbar, hamburger menu and about:preferences#sync pages.

### Expected result
In profile B, the account that should be logged in the browser toolbar/ hamburger menu/the about:preferences page/ the Manage account page should be the same, the account that has been made Primary in profile A.

### Actual result
On the Profile B, in the browser toolbar/hamburger menu and the about:preferences page the account that looks to be logged in is the former primary account from profile A. 
Only in the manage account page is the switch between primary and secondary email correctly displayed. 

### Environment
Windows 10 64-bit with FF Beta 71
Android 8.0.0 with Beta 68

![Sign in with former secondary email on clean profile](https://user-images.githubusercontent.com/53306802/69813661-4a588480-11fb-11ea-92cc-ac9b05f693a4.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-586)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15928/gif13.gif">gif13.gif</a>
┆Issue Number: FXA-586

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~vtamas@mozilla.com]Could you see if this issue is still reproducible?

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible on Stage [Train 1.203.5] and Prod [Train 1.203.4] using Firefox 87.0 and Firefox 88.0b7 under Windows 10 64-bit. Closing.
