### ISSUE TITLE
[Android] Account deleted on Desktop is not displayed as sign out of Android

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/fxa#3524]
## Build
Stage [Train 1.151.0]
Firefox Beta 71 Stage.

### Steps to reproduce
1. Sign in Firefox Desktop and navigate to Account settings> Manage Account. 
2. Sign in on Firefox on Android and navigate to Settings> Firefox Account.
3. On Firefox desktop in manage account page go to the account Delete panel and check all the required boxes and input the valid password in the pwd field. Delete account and refresh page. The account is signed out. 
4. On Android navigate to the Settings page and refresh. Click on the Firefox Account and sync. 

### Expected result
On android the Firefox Account should no longer be signed in. 

### Actual result
The account looks like it's still sign in when reaching Settings. When clicking on the Account and reaching the Sync page the "Cannot connect.Tap to sign in" error is shown. Clicking further on the account will direct the user to a create account form.

### Environment

Android 8.0.0

![Screenshot_20191128-171309_Firefox%20Beta](https://user-images.githubusercontent.com/53306802/69817716-e5edf300-1203-11ea-9ed4-5959c7550fcf.jpg)
![Screenshot_20191128-171314_Firefox%20Beta](https://user-images.githubusercontent.com/53306802/69817717-e5edf300-1203-11ea-9acd-434e2a9013ee.jpg)
![Screenshot_20191128-171951_Firefox%20Beta](https://user-images.githubusercontent.com/53306802/69817715-e5edf300-1203-11ea-9c33-e9ce90a031c5.jpg)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-588)
┆Issue Number: FXA-588

**Comment by johngruen** [comment]
@mirunacurtean is this on Fennec of Fenix?

**Comment by johngruen** [comment]
We think it takes a few hours for the device to undertand the acct was deleted

**Comment by mirunacurtean** [comment]
Hello @johngruen. 
The initial tests and this one was performed between Beta 71 stage server on Desktop and firefox Beta (currently 68.4b1) on Android 8.0.0. I believe that this version of of Firefox for android is Fennec. 
On the matter of device sync/ sign out, after more than 3 hours after the account was deleted from Desktop, it still displayed the account as signed in in Firefox Settings and on the Sync page the "Cannot connect. Tap to sign in" error is shown. 
Tapping on it redirects the user to the "Create a Firefox account" registration form where the "Account no longer exists. Recreate it?" notification is visible. 
I will keep an eye on the device to see if the account is signed out from Firefox settings and update the ticket accordingly.
Please let me know if there is anything else I can help with.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

No longer fixing fennec bugs
