### ISSUE TITLE
Use signin token codes everywhere

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3529]
Creating an epic to track all the work needed to use signin codes everywhere.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-592)
┆Issue Number: FXA-592

**Comment by shane-tomlinson** [comment]
Ref #3531, #2814 for converting secondary email and password reset flow to codes instead of links

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

[~vbudhram@mozilla.com] This is an epic we moved over. Are there still places we need to remove links?

Reminder emails are the only place I believe we still use links but I don't think we can migrate to codes.

(just checking to see if we can close this epic)

**Comment by rfk** [comment]
> Reminder emails are the only place I believe we still use links but I don't think we can migrate to codes.

I recall the "resend confirmation email" button in Desktop Firefox being another place that uses links.

**Comment by clouserw** [comment]
epics are tracked in jira
