### ISSUE TITLE
Convert the secondary email verification flow from link to code based verification

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3531]
Similar to #2815, this is to convert the add a secondary email flow from link to code based verification.

blocks #2814

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-593)
┆Issue Number: FXA-593

**Comment by vbudhram** [comment]
Assigning myself since this is needed for https://github.com/mozilla/fxa/issues/2653

**Comment by vbudhram** [comment]
All the parts for this standalone view have landed, closing.
