### ISSUE TITLE
Stuck with the back button usage on v151.1

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#3539]
With https://accounts.stage.mozaws.net/ver.json

```
 "commit": "036a2b71ede429a7743230b0182f67c0c3eb8318",
  "version": "1.151.1",
```

### STR

* Open a new profile, not logged in.
* Click this link: https://accounts.firefox.com/settings
* Try to go back with the back button the browser

### Expected

* can come back to this github issue

### Actual

* stuck redirecting from `/` to `/signin` page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-594)
┆Issue Number: FXA-594

**Comment by johngruen** [comment]
@vladikoff clicking that link opens a new tab so it's hard to repro ur bug. Can you provide an alternate STR?

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
