### ISSUE TITLE
Measure Caps Lock to see if it impacts success

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#3546]
Currently we do not warn users if their caps lock is on when they are authenticating an account. So we can determine is a warning is needed, where we measure form submission success, we should also measure caps lock usage.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-67)
┆Issue Number: FXA-67

**Comment by lmorchard** [comment]
I might be out of date with my know-how, but - can we actually detect caps lock in JS? I seem to remember this being a challenge in the past

**Comment by ryanfeeley** [comment]
Looks like it… https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
