### ISSUE TITLE
Test external links in the TOS/PP pages to ensure they are valid

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3547]
Over in https://github.com/mozilla/fxa/commit/ae85faf29d32bf5d74690fe1825056223a67285b we had to disable external link checks in the TOS/PP pages because the links were invalid. With train 151 going out, those links should again be valid, and we should be able to bring back the test.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-66)
┆Issue Number: FXA-66

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I don't think we should be hitting external servers in our unit tests.  Closing.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

wontfix
