### ISSUE TITLE
Firefox accounts two step authentication controls are broken

### ISSUE THREAD

**Issue by durack1** [mozilla/fxa#355]
The "Disable" button and "replace recovery codes" link on the "two-step authentication" section of my Firefox Accounts page (https://accounts.firefox.com/settings/two_step_authentication) just don't do anything.

I am unable to reset my two-factor authentication or reconfigure an authenticator app for use

**Comment by rfk** [comment]
If you open the web console [1] does it show any errors or other messaging?

[1] https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console

**Comment by durack1** [comment]
@rfk this is what I get
![190325_FFAccountFail](https://user-images.githubusercontent.com/3229632/54933651-4c36af00-4eda-11e9-8a4e-2048231b1de0.png)

**Comment by rfk** [comment]
Thanks @durack1, looks like this is the same issue as https://github.com/mozilla/fxa-content-server/issues/6767.  As a workaround, if you sign out and sign back in (using your existing 2FA device) then you should be able to reconfigure the 2FA setup.

**Comment by durack1** [comment]
@rfk ok I'll try.. And see if I can find those recovery keys just in case, that also doesn't work so if I get locked out, oh dear..

**Comment by shane-tomlinson** [comment]
Closing as a dup of mozilla/fxa-contnet-server#6767, thanks for the taking the time to open this report @durack1 and answering our questions along the way. This feedback is valuable in helping us prioritize fixing this.
