### ISSUE TITLE
Do not use the sync-optional flow with Fenix

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#3553]
Ref https://github.com/mozilla/application-services/issues/2283, but filing it here for tracking because the fix will need to be in FxA.

Users who sign in to Fenix currently get the "sync optional" flow. They shouldn't, because Fenix doesn't support it, and IIUC clicking the "do not sync this device" button will not have any effect in Fenix.

The sync-optional flow should only be offered to `context=fx_desktop_v3` clients, and only if they report `multiService: true` in their FxA webchannel handshake

**Comment by shane-tomlinson** [comment]
This should be a pretty easy fix, we should be able to add a capability to the respective auth-brokers that says whether the sync-optional flow is supported.

**Comment by johngruen** [comment]
Let's cherry pick this in for next week since 152 is the last train of 2019

**Comment by shane-tomlinson** [comment]
@vladikoff, @rfk - does this also apply to sign in where users can get the `would_you_like_to_sync` screen?

**Comment by vladikoff** [comment]
Yeah, we do NOT want to offer that choice for now, this might change with FPN on Fenix.

**Comment by sv-sdeiac** [comment]
Hello, 
I can confirm that the issue is verified on the latest version of Firefox Preview (2.3.0 #13031728) using Nokia 6 (Android 7.1.1) and Samsung Galaxy Note 8 (Android 9).
