### ISSUE TITLE
Push `verificationMethod` for signup to /account/create auth-server route

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3561]
As noted by [@vbudhram in this comment](https://github.com/mozilla/fxa/pull/3477/files#r352640014), with #3477 the only verificationMethod available in /account/create is `email-otp`. We should [stop sending this from the front-end](https://github.com/mozilla/fxa/blob/c59445f537b0a2cceeac00cfb928aff7bee515ea/packages/fxa-content-server/app/scripts/views/mixins/signup-mixin.js#L34) and have the route use this value by default, removing any legacy support code for other verificationMethods.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-60)
┆Issue Number: FXA-60

**Comment by vbudhram** [comment]
I think this would be fixed when we move our login flows to React. Closing.
