### ISSUE TITLE
Consolidate sentry utility wrapper in fxa-shared

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3563]
We are using the sentry utility wrapper in payments server and content server. We should pull it out into `fxa-shared`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-59)
┆Issue Number: FXA-59

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This is part of the NextJS shared libraries now.
