### ISSUE TITLE
[services] Style client icons with `data-client-id` instead of `data-name`s?

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3566]
Edit: See first comment.

---
I was able to close #1782 with a CSS fix, but didn't want the following suggestion to be lost.

- - -
_Originally posted by @rfk in https://github.com/mozilla/fxa/issues/1782#issuecomment-511614223_

So I had a quick poke around at [how the icons are determined](https://github.com/mozilla/fxa/blob/91c94c7464190cab341dfed27f00b93018571788/packages/fxa-content-server/app/styles/modules/_settings.scss#L503), and I want to propose a bit of a refactor to how that's done to work better with oauth clients that are also devices.

Currently we determine the icon by client name, using rules like:

```
.client-oAuthApp[data-name='Android Components Reference Browser'] {
    background-image: url('/images/icon-device-phone-android.svg');
}
```

This seems fragile, because we might change the name on the backend and forget to update the rules on the frontend. It also won't play well with oauth device records, which can customize their display name.

What if instead, we selected the icon by client id, and applied it to all attached clients rather specifically to those of type `oAuthApp`? We could set a new data property `data-client-id` on the HTML element, and use a rule like this:

```
.client[data-client-id='3c49430b43dfba77'] {
    background-image: url('/images/icon-device-phone-android.svg');
}
```

This would require us to be a little more explicit about the list of clients (we "cheat" in a few places by pattern-matching on names like "Firefox Send") but TBH I feel like explicit is probably good here.

@shane-tomlinson what do you think, is it worth exploring something like this?

- - -
_Originally posted by @shane~~tomlinson in https://github.com/mozilla/fxa/issues/1782#issuecomment~~511757385_

I've always wanted to use the client_id. The only downside is that client ids can change from dev servers to stable to stage/prod, so we might have a proliferation of client ids in the CSS. That, or we keep the same client id for all environments.

- - -
Personally, I prefer a selector like `&[data-name^='Firefox Send']` because it's more human readable and we don't have to either make IDs consistent across environments or have a bunch of extra CSS, and I don't foresee us tampering with product names in the back-end, but I may not understand the full implications of what this means: 

> It also won't play well with oauth device records, which can customize their display name.

Also, in response to this:

> What if instead, we selected the icon by client id, and applied it to all attached clients rather specifically to those of type `oAuthApp`?

As of #3551, we only have a couple of selectors still living under `.oAuthApp`. We may actually be able to move what's in this selector into `.client`, I am not sure if we need the differentiation.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-58)
┆Issue Number: FXA-58

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

With this being added to the Settings Redesign epic, I've got more food for thought here.

We're now inlining all of our SVGs in Settings so far, and I've recently fiddled with dynamic inlined SVG imports. See this code sandbox ( https://codesandbox.io/s/react-dynamic-svg-import-ts-kzx7n?fontsize=14&hidenavigation=1&theme=dark ) (not mine, but I used this as a base for my needs).

If we had a file mapping names or IDs to the SVG file name, I wonder if we could just dynamically import them. If we can do that, that'd solve this issue plus FXA-1758.
