### ISSUE TITLE
Define a formal SLA

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#357]
We have been running FxA for over 5 years now. We have a good idea of our uptime, our average response time, and our escalation plan. 

We've never codified these into a document that can be shared or used as a reference to hold ourselves accountable. With new services increasingly depending on us, we should be able to point at the doc and say "these are the guarantees we make to you."

cc @bbangert

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-595)
┆Issue Number: FXA-595

**Comment by clouserw** [comment]
@jbuck is there an SLA from cloud services?  I thought I had seen a page on mana about that, but I don't find it now.

**Comment by jbuck** [comment]
I don't know if we have that written down anywhere, but we do have https://firefoxoperations.statuspage.io/ for tracking uptime

**Comment by clouserw** [comment]
In addition to availability, we should consider adding a section around loss of data due to password resets or 2fa or such

**Comment by shane-tomlinson** [comment]
@clouserw - should this be assigned to you to figure out next steps?

**Comment by clouserw** [comment]
update from @jrgm: @habib is setting up some time to make a draft

**Comment by gdestuynder** [comment]
do you have a draft for this? there is an outstanding item on the SubHub RRA that's related to this ticket

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
