### ISSUE TITLE
[auth-server] Backend Service API statsD Does Not Collect Error Timings

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3571]
If an error is thrown from `sendRequest` in auth-server's `lib/backendService.js`, `statsd` is not called.

_Originally posted by @l-hedgehog in https://github.com/mozilla/fxa/pull/2594/files/fda7d1f5b6d8f79537824caee4cfc5f8efd99324_

**Comment by l-hedgehog** [comment]
Thanks for fixing this so quickly!
