### ISSUE TITLE
[content-server] Group Email Domain DNS Record Validation Server Errors by Error Code

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3572]
There are 22 potential types of errors in the email domain validation route that would throw a 500 and get logged by Sentry.  We should catch and re-throw these errors so that they are grouped by their error codes.  We know at least one of these errors, `SERVFAIL`, includes the queried domain in its message.  This unncessarily creates many unique errors in Sentry.

The list of errors are list on [Node's docs for `dns`](https://nodejs.org/docs/latest-v10.x/api/dns.html#dns_error_codes).  The `validate-email-domain` route is currently handling `dns.NODATA` and `dns.NOTFOUND`.  The error code is simply the `code` property in the error object.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-55)
┆Issue Number: FXA-55

**Comment by shane-tomlinson** [comment]
@chenba - Might be helpful to enumerate or point to a reference to the various types of errors so contributors or other team members know what needs to be handled.

**Comment by chenba** [comment]
@shane-tomlinson Good point.  I was hoping to get to this quickly but I'm not sure that's going to be the case.

I'll update the issue description.  Thanks!
