### ISSUE TITLE
Why is email confirmation so bad in some countries/languages?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3573]
I first observed that email confirmation rates were really low in some languages like Persian, Hindi and Arabic. (all RTL)
https://analytics.amplitude.com/mozilla-corp/chart/q16ecw3/edit/fi7wnfg

As a start, they seem to have the highest bounce rate but that doesn't seem to account for the huge discrepency.
https://analytics.amplitude.com/mozilla-corp/chart/q16ecw3/edit/2pu0j7k

Could l10n be part of the problem/solution?

This is an investigative bug that will likely need collaboration between UX, PM, QA and l10N to identify the cause.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-54)
┆Issue Number: FXA-54

**Comment by vbudhram** [comment]
Closing since we wont get to work on this for a while, please reopen if needed.
