### ISSUE TITLE
Improve edge cases for inline password validation

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#3575]
From https://github.com/mozilla/fxa/pull/3548, there are a couple edge cases where the tooltip is not correctly displayed.

Ref

<img width="444" alt="Screen Shot 2019-12-04 at 1 33 07 PM" src="https://user-images.githubusercontent.com/1295288/70170419-a52a2a00-169a-11ea-9568-a5093d148a54.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-53)
┆Issue Number: FXA-53

**Comment by LZoog** [comment]
Note: first edgecase is fixed by #3795

**Comment by byrw** [comment]
May I work on the second edge case?

The solution that best worked for me, is just verifying if the `#new_password` input is valid before verifying whether passwords do match. This solution is implemented in the same way as the function `showValidationErrors()`, in the file change_passwords.jsx.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.187.2] under Windows 10 64-bit. "Passwords do not match" error is no longer displayed if there is a validation error. 

![Screenshot_48](https://user-images.githubusercontent.com/18114210/93070154-2f220d00-f687-11ea-918e-fb6fa9a2221f.png)
