### ISSUE TITLE
Payments server Amplitude events do not have the correct time

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#3576]
@johngruen noticed on https://analytics.amplitude.com/mozilla-corp/chart/uoz0ypk/edit/8jxp0as that payment events that happened today are recorded as happening on Monday December 2nd

I looked at the BigQuery logs for the payment events and found that the `time` field is set to a time on Monday December 2nd instead of approximately when the user paid for their subscription.

**Comment by jbuck** [comment]
On a WAG, given that we deployed on Monday, I wonder if it's calculating offsets based on process start time rather than flow id start time? I restarted all the payments containers, so we can test this theory with the next payments

**Comment by jbuck** [comment]
To temporarily patch this, we could modify fxa-amplitude-send to replace the `jsonPayload.fields.time` field with `timestamp` if the difference between the two is larger than some margin of error, or maybe just always replace it for all payment server events

**Comment by jbuck** [comment]
https://github.com/mozilla/fxa/blob/316df61a1c3c5d965e155839d2d00acb619e9565/packages/fxa-payments-server/server/lib/routes/post-metrics.js#L67-L71

`data.perfStartTime` is the server start time, which is why all amplitude events cluster around the same time. I can reset the payments containers every few hours so that the metrics are kinda accurate on a daily basis, but that's just a hack

**Comment by chenba** [comment]
> data.perfStartTime is the server start time

That was not the intention; it was meant to be a timestamp of the moment when the server starts responding.  But in stage/prod the value does not change due some static content caching.

That value is not necessary for the `time` property on an Amplitude event.  The front end currently sends a request for every event emitted, so the flush time can be used as the event time, which is what PR #3578 is doing.
