### ISSUE TITLE
Intermittent content-server test failure: mozinstall error after all tests pass

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3584]
Sometimes all the content-server tests pass, then CI fails the run with a mozinstall error:

"mozinstall.mozinstall.InstallError: Failed to install "/7f10c7614e9fa46-target.tar.bz2 ([Errno 26] Text file busy: '/home/circleci/project/packages/fxa-content-server/firefox/firefox-bin')"

Here's a screenshot of [this recent CI run](https://circleci.com/gh/mozilla/fxa/124819#tests/containers/5) that was affected:

![image](https://user-images.githubusercontent.com/96396/70259453-11f8ff00-1743-11ea-8fe5-e9b88b6b94aa.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-49)
┆Issue Number: FXA-49

**Comment by dannycoates** [comment]
That's in the setup for the pairing tests https://github.com/mozilla/fxa/blob/master/.circleci/test-content-server.sh#L53

**Comment by dannycoates** [comment]
whose tar file comes from https://github.com/mozilla/fxa/blob/master/packages/fxa-circleci/Dockerfile#L21

**Comment by dannycoates** [comment]
@vladikoff is that special firefox still required to test pairing? I know nothing about it
