### ISSUE TITLE
Attribute users who register through sync-optional flow to sync (if they don't disable it)

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#3586]
With decoupling, users who go through the sync-optional flow during registration will now be attributed to oauth_client_id `5882386c6d801776` which maps to `service` = `firefox-dekstop`. 

This is intended behavior insofar as it captures both users who keep sync enabled during registration and users who turn it off. However, it would be good if we could *also* attribute registrations that keep sync turned on to `sync` as well as `firefox-desktop`.

Note that @rfk 's patch made it so sync users still request certificates if they are using sync, so those users will still be associated with the sync service (e.g. when segmenting MAU by services used) since the `fxa_activity - cert_signed` event will still be associated with `service` = `sync`. So this issue is restricted only to attributing new registrations to sync at the point of registration.

Another option is that we only attribute users to `firefox-desktop` if they disable sync at the point of registration, and attribute them to `sync` otherwise. I'm less keen on this option but from a technical perspective it might be easier.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-47)
┆Issue Number: FXA-47

**Comment by rfk** [comment]
What does this mean in terms of the events that get sent - should e.g. the `fxa_reg - complete` event have `service=sync` if the user opted-in to sync during this flow?

**Comment by irrationalagent** [comment]
> What does this mean in terms of the events that get sent - should e.g. the `fxa_reg - complete` event have `service=sync` if the user opted-in to sync during this flow?

right, i should have been more specific here. i see (non-exhaustive) options here being, for `fxa_reg - complete`:

**Option 1**
`service=[firefox_desktop,sync]` (users who leave sync turned on during reg)
`service=[firefox_desktop]` (users who turn sync off during reg)

**Option 2**
`service=sync` (users who leave sync turned on during reg)
`service=firefox_desktop` (users who turn sync off during reg)

Alex points out that with option 2 we lose one easy way of determining which users came through sync-optional flows and which didn't (for users that kept sync turned on).

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~loines@mozilla.com] [~adavis@mozilla.com] is this still something we should work on?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

TBH, I'm not sure what the state of affairs is and what the current behavior is...

A quick look at our metrics leads me to believe that we have option 1 in place using our `fxa - activity` event.

`cert_signed` doesn't exist anymore.

We can probably close this.
