### ISSUE TITLE
Use new amplitude identify api features to avoid duplicate entries in user properties

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#3590]
Our contact at amplitude has let me know that they have added a few things to the identify API that will help us to avoid really long arrays of user properties (for example we currently append another value to the `fxa_services_used` user property with every event, meaning sync users will have arrays 1000s of entries long like [sync, sync, sync ...])

everything below is copy/paste from email (note the link to the new api docs):

>The new [Identify API](https://help.amplitude.com/hc/en-us/articles/205406617-Identify-API-Modify-User-Properties) is ready! As soon as possible, we'd advise switching over so that this issue does not happen again and Mozilla's query speed stays functional. The 3 new functionalities highlighted below:

    $preInsert: this functionality will add the specified values to the beginning of the list of properties for the user property if the values do not already exist in the list. Can give a single value or an array of values. If a list is sent, the order of the list will be maintained.
    $postInsert: this functionality will add the specified values to the beginning of the list of properties for the user property if the values do not already exist in the list. Can give a single value or an array of values. If a list is sent, the order of the list will be maintained.
    $remove: this functionality will remove all instances of the value or values specified. Can give a single value or an array of values.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-46)
┆Issue Number: FXA-46

**Comment by irrationalagent** [comment]
My understanding of what's going on here is kind of incomplete but AFAICT this would at least mean adding the new verbs here

https://github.com/mozilla/fxa/blob/f54ac4a22e731cffd19202ee00e7f6bb07af660a/packages/fxa-amplitude-send/pubsub/index.js#L77

and making the relevant changes e.g. here

https://github.com/mozilla/fxa/blob/f54ac4a22e731cffd19202ee00e7f6bb07af660a/packages/fxa-shared/metrics/amplitude.js#L312-L319

and potentially any other place that uses `$append`. there may also be other changes needed to e.g. tests or other things

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
