### ISSUE TITLE
[Epic] Improve FxA performance/use metrics

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3591]
## Background

Currently FxA has Amplitude metrics for user driven engagement and some user-experience related metrics around how fast pages load. In the past New Relic was used for application metrics to gauge slow pages/db queries/requests/etc. Use of New Relic ceased due to cost constraints, and no replacement system is in widespread use.

There are some metrics that are available via AWS/GCP that augment FxA integrated metrics.

## Goals

Metrics should be added to FxA to address any gaps in knowledge regarding: 
* Does a new release improve or degrade performance?
* What are the most utilized aspects of each FxA service? (Which URL, API method, etc)
* What are the the slowest aspects of each FxA service? (Which db query, API call, etc)
* Are we seeing unusual SQS/API/web traffic?
* Are we using more/less servers than usual? More/less CPU/Memory?

## Process

For each FxA service/script/process, a ticket should be filed under this epic summarizing the type of service, its typical operation, and what metrics are needed to answer the above goals that cannot be derived from existing system metrics that operations collects. Another dependent ticket should also be filed to create a grafana dashboard that contains these metrics.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-45)
┆Issue Number: FXA-45

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

I don't think this is a subscription related epic. Removing the component.
