### ISSUE TITLE
Collect Page Performance Metrics with StatsD on Payments Server

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3596]
Content server uses flow events to collect performance metrics (https://sql.telemetry.mozilla.org/dashboard/fxa-performance).  But we ran into some [speed hump](https://github.com/mozilla/fxa/issues/3072)s when trying to replicate that in Payments.

We should consider using StatsD instead.  Let's try it with Payments first, then move Content over as well if we like the result.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-43)
┆Issue Number: FXA-43

**Comment by chenba** [comment]
@jbuck Before I end up with a different version of https://github.com/mozilla/fxa/issues/3072, I'd like  you confirm that using statsd on the Payments server shouldn't be a problem.  😀

**Comment by jbuck** [comment]
It shouldn't be a problem
