### ISSUE TITLE
We removed "start browsing" on CAD page

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3597]
This issue was filed because the user thought that CAD was required:
https://github.com/mozilla/fxa/issues/3594

I was surprised because we have a start browsing button on that page. We even have an issue open to measure usage of the "start browsing" link:
https://github.com/mozilla/fxa/issues/3022

I just went through the flow and it seems like we've removed the link:
![image](https://user-images.githubusercontent.com/19537086/70340245-4af9a800-1805-11ea-8eb4-5f476abd2024.png)

Let's restore the "Start browsing" link. 

Note: Martin Lapatka also brought this to my attention this week. He reported that he knew folks who thought that this was required.

CC @ryanfeeley

**Comment by kvark** [comment]
Just faced it myself on a new machine. This is very unfortunate, feels like Firefox forces you to enroll into something unwanted.

**Comment by ryanfeeley** [comment]
@davismtl I'm not sure why the Start browsing was removed, though I do think this was related to making the page compatible with Connect Another Device (e.g. fxa toolbar) entrypoints.

We could make this page look less mandatory by using the string variant that starts with "Still adding devices?". That way it looks less mandatory, and is even more compatible with the Connect Another Device entrypoints.

Other option is making two different pages, but I always err on the side of keeping it simple.

**Comment by davismtl** [comment]
@ryanfeeley 
I think there's a lot of improvements we can make to this page to clarify why people should do this but I don't think "Still adding devices?" does that. For example, a clear CTA like "Sync this browser with your mobile device" would provide a lot of context and eliminate confusion about people thinking the phone number was just required for registration.

If you're worried about compatibility with CAD in the toolbar menu, instead of "Start browsing", we could put "Not now" or "Remind me later".

**Comment by davismtl** [comment]
We perhaps broke it here
https://github.com/mozilla/fxa/pull/3189

**Comment by vasilicatamas** [comment]
2 issues were encountered on Windows 10 and Android 8 while verifying this bug. “Not now” button seems to be correctly displayed on Mac OS 10.14.6.
<img width="494" alt="Screenshot 2020-01-07 at 15 13 09" src="https://user-images.githubusercontent.com/18114210/71898105-1f9a0e00-3161-11ea-8815-4740ceca12e4.png">

Since the other issues are tracked separately I will mark this bug as Verified
