### ISSUE TITLE
Push in FxA - Timely Services Info

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#36]
As a FF user when using Firefox,

I want FF and my core browsing data to feel speedy and to the point both in general usage and when I am specifically interacting with synced data.
    
1b. When I log into a service with my FxA, I want to be able to see it in my FxA dashboard, complete with last time logged in.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-30-2
