### ISSUE TITLE
[Sentry] All the logs for fxa-content-product are going to content-express-server-prod

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3600]
In the 1.151.4 Train the logging got swapped around and all the Sentry logs that should be going in to fxa-content-product are going in to the content-express-server-prod project.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-42)
┆Priority: Medium
┆Issue Number: FXA-42

**Comment by chenba** [comment]
I think https://github.com/mozilla/fxa/pull/3388/files#diff-da283abf354df26a8bebd2d236b18f39R66 (might be to scroll up a bit after you click) is the change that caused this.

**Comment by clouserw** [comment]
@meandavejustice ^
