### ISSUE TITLE
Firefox Accounts sign-in assumes mistyped domain [bz1602224]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3605]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1602224

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

Steps to reproduce:

Boot an Xubuntu 19.10 live USB image.
Initiate a Sync sign-in process by clicking the icon in the Firefox toolbar.
Type in my email address which is on the "zao.se" domain.
Hit enter to attempt to go to the next step of the sign-in process to enter password.

Actual results:

The form shows a red error-like balloon asking "did you mean aol.se".

Expected results:

I expected to be on the next page of the sign-in process as I had intentionally typed an e-mail address which has a Sync account since forever.

If there must be such suggestions, please have them out-of-line and don't make them interfere with the task at hand. I'm no UX person, but error-red might not be appropriate for an unprompted suggestion by the UI, especially as the information typed is legitimate.

The suggestion is especially amusing as approximately no-one uses AOL here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-40)
┆Issue Number: FXA-40

**Comment by vladikoff** [comment]
cc @ryanfeeley

**Comment by davismtl** [comment]
Likely related to this:
https://github.com/mozilla/fxa/pull/3233

I have 2 thoughts. 
- We should only be making that recommendation if we don't recognize the email (registration) like we do for the MX lookups.
- This experience might be redundant with the work that @LZoog did and TBH, her UX is a bit more solid.

**Comment by clouserw** [comment]
This is being removed in https://github.com/mozilla/fxa/issues/3897 (and PR at https://github.com/mozilla/fxa/pull/4097 )
