### ISSUE TITLE
Show correct Fenix device name in Firefox notifications [bz1602006]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3606]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1602006

Created attachment 9114180
Screen Shot 2019-12-06 at 11.07.39 AM.png

STEPS TO REPRODUCE
1. Have an iOS or desktop device signed in to Firefox/Sync
2. Connect a Fenix device

EXPECTED RESULTS
* The correct Fenix device name (e.g. Firefox Preview on samsung SM-G900W8) appears in the notifications 

ACTUAL RESULTS
* Fenix is called Firefox Sync (which is particularly problematic now that users can sign in to Firefox without enabling Sync)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-39)
┆Issue Number: FXA-39

**Comment by clouserw** [comment]
Marking this as `needs:ux` because we need to make the decision about what to show @ https://bugzilla.mozilla.org/show_bug.cgi?id=1602006#c1
