### ISSUE TITLE
Firefox Sync is blocking the login, even after I insert the confirmation code which I have received by email [bz1602402]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3608]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1602402

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Firefox for Android

Steps to reproduce:

tried to login in Firefox Sync on a new pc, misspelt several times the password

Actual results:

The page asking me to insert the code sent by email came up. I received the email and after I inserted the code, the page saying that I inserted the wrong password came up. This happened multiple times (on two different PC, actually).

Expected results:

I expected to be able to access my Firefox Sync account

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-38)
┆Issue Number: FXA-38

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Closed in bugzilla too
