### ISSUE TITLE
Add fluent dependency to payments server

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3610]
Let's start getting L10n going

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-37)
┆Priority: Medium
┆Issue Number: FXA-37

**Comment by clouserw** [comment]
@meandavejustice please break this up into appropriate bugs and add estimates.  Thanks!

**Comment by meandavejustice** [comment]
I'm going to use this issue to track the effort for setting up boilerplate for l10n. I've filed #3704 for the remaining work
