### ISSUE TITLE
Not Tracking Service for form views of Sync decouple flows

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3611]
See login form views on about:welcome: 
https://analytics.amplitude.com/mozilla-corp/chart/r7iiqzt

See registration form views on about:welcome: 
https://analytics.amplitude.com/mozilla-corp/chart/ln7e496 

We are not tracking a service property value for the Sync decouple flow form views. (reg and login)

CC @irrationalagent

**Comment by rfk** [comment]
Is the expected behavior for these events, that they have "service=firefox-desktop"?

**Comment by rfk** [comment]
I expect we'll need to pass some fallback value in for `service` when creating the metrics-gathering object here:

https://github.com/mozilla/fxa/blob/fa177e97e27a829bfbf990c59eda0200efdbf4f2/packages/fxa-content-server/app/scripts/lib/app-start.js#L196

We currently only set a fallback service *name*, not a fallback value for the `service` param itself, ref:

https://github.com/mozilla/fxa/blob/fa177e97e27a829bfbf990c59eda0200efdbf4f2/packages/fxa-content-server/app/scripts/models/reliers/browser.js#L60-L65

**Comment by davismtl** [comment]
> Is the expected behavior for these events, that they have "service=firefox-desktop"?

Given that's what we track when the flow completes, I would say yes. That's what I would expect.

**Comment by rfk** [comment]
> We currently only set a fallback service name, not a fallback value for the service param itself, ref:

Actually it looks like we do set `relier["service"] = "firefox-desktop" in the sync-optional flow, based on the results of the fxa-status handshake here:

https://github.com/mozilla/fxa/blob/fa177e97e27a829bfbf990c59eda0200efdbf4f2/packages/fxa-content-server/app/scripts/models/auth_brokers/fx-sync.js#L69

It's just that we do this *after* we've initialized the global `Metrics` object, so the updated value doesn't get propagated through to any metrics. PR incoming.

**Comment by rfk** [comment]
@davismtl is this impactful enough that we should consider an uplift of #3634 to the current train? /cc @LZoog who IIUC is the train-wrangler for this cycle.

**Comment by davismtl** [comment]
I don't want to prescribe uplifts before Christmas. 

The bug does make some analysis hard though and does limit some of the visibility we have into 2 of our biggest entrypoints.

I'll let engineering assess risks and effort.
