### ISSUE TITLE
Display `serviceName` in "ready" view if user is authenticated

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3623]
Follow-up to #3569 

@shane-tomlinson I'm going to spell this out to make sure I've got this right.

`ready.mustache` needs some more finessing. UX would prefer "You are now ready to use Account Settings" to display instead of "Your account is ready!," but we need a condition to check if the user is signed in. Otherwise, a user can hit this screen because of an email verification reminder, and "You are now ready to use Account Settings" doesn't make sense because they're not signed in.

It looks like we want to change this:
```
{{^isFromRelyingParty}}
  {{#emailVerified}}
    <p class="account-ready-service">{{{escapedEmailReadyText}}}</p>
  {{/emailVerified}}
  {{^emailVerified}}
     <p class="account-ready-generic">{{#t}}Your account is ready!{{/t}}</p>
  {{/emailVerified}}
{{/isFromRelyingParty}}
```

(`escapedEmailReadyText` should display "'You are now ready to make changes to your Firefox Account.")

to:
```
{{^isFromRelyingParty}}
  {{#emailVerified}}
    <p class="account-ready-service">{{{escapedEmailReadyText}}}</p>
  {{/emailVerified}}
  {{^emailVerified}}
    {{#isAuthenticated}}
         <p class="account-ready-service">{{#t}}You are now ready to use %(serviceName)s{{/t}}</p>
    {{/isAuthenticated}}
    {{^isAuthenticated}}
      <p class="account-ready-generic">{{#t}}Your account is ready!{{/t}}</p>
    {{/isAuthenticated}}
  {{/emailVerified}}
{{/isFromRelyingParty}}
```

This screen is getting a little convoluted. The `escapedEmailReadyText` differentiation seems strange to me - I don't think I'd know as a user what the difference is between "You are now ready to make changes to your Firefox Account" and "Your account is ready!".

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-34)
┆Priority: Medium
┆Issue Number: FXA-34

**Comment by shane-tomlinson** [comment]
Overall, your summary looks spot on. 

>  I don't think I'd know as a user what the difference is between "You are now ready to make changes to your Firefox Account" and "Your account is ready!".

In the former case we could add a link to settings so the user can make changes.
