### ISSUE TITLE
Should payments-server update meta tags in index.html for each request?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3625]
Took me awhile, but I finally grasped what happened with the stale `fxa-perf-start-time` meta header.

We [update the meta headers of the static `index.html` and store the result in a variable `renderedStaticHtml`](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/server/lib/server.js#L208-L212):
```javascript
    const renderedStaticHtml = injectHtmlConfig(
      STATIC_INDEX_HTML,
      CLIENT_CONFIG,
      {}
    );
```

Then, we just [serve up the contents of `renderedStaticHtml` for various `INDEX_ROUTES`](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/server/lib/server.js#L213-L218):
```javascript
    INDEX_ROUTES.forEach(route => {
      // FIXME: should set ETag, Not-Modified:
      app.get(route, (req, res) => {
        res.send(renderedStaticHtml);
      });
    });
```

This means that the meta headers will only ever be updated on server start. That's okay for env vars that only change on server restart, but not okay for anything tied to a per-request basis. 

But, will we want more per-request things in the future? Feature flags come to mind, if we change the flags in Redis and don't restart the server. (issue #1281)

Maybe we should rework this code to inject updated meta tags every request like so:
```javascript
    INDEX_ROUTES.forEach(route => {
      // FIXME: should set ETag, Not-Modified:
      app.get(route, (req, res) => {
        res.send(injectHtmlConfig(
          STATIC_INDEX_HTML,
          CLIENT_CONFIG,
          {}
        ));
      });
    });
```

I realize this issue is longer than the actual PR to do the above would be. But I wanted to think out loud and maybe see if there are potential issues to think through here. Performance change seems like it would be negligible. `max-age` is a thing to consider in client-side caching. Anything else?

**Comment by lmorchard** [comment]
@chenba Since this thing bit you, maybe you have thoughts?

**Comment by lmorchard** [comment]
I went ahead and opened a PR, but we can still discuss here or on the PR

**Comment by chenba** [comment]
Thanks! 👍
