### ISSUE TITLE
Move payments server to AWS

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3633]
Moving the payments server to AWS would keep all* our services in once place, and we could leverage the same tools we use for FxA servers on the payments server.  

* The one thing that would be left out of AWS still would be the event broker 

/cc @jrgm @jbuck @habib

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-31)
┆Issue Number: FXA-31

**Comment by clouserw** [comment]
From triage: This sounds like a good idea, no specific timeline for it.  Let's do it in January.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~wclouser@mozilla.com] [~jbuckley@mozilla.com]  is this something we should still do?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

wontfix

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

wontfix
