### ISSUE TITLE
New OAuth errors do not have entries in content server's errors.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3635]
I noticed this today (and apparently in the past too based on the bugs GitHub found), many auth-server errors that used to be OAuth-server errors do not have entires in the content-server's errors.js file, meaning some error cases may not be handled and that these error messages are not being translated.

Many of these errors were previously translated in the auth->oauth translation layer, I suspect that if these were given new error numbers we are not correctly handling them on the front end because we still expect the old error numbers to be returned.

Example: 

* [insufficientACRValues, errno 170](https://github.com/mozilla/fxa/blob/8407c0c457317e6bd4c121b6aedb54d076f541ff/packages/fxa-auth-server/lib/error.js#L1217)
* The front end expects [errno 160](https://github.com/mozilla/fxa/blob/8407c0c457317e6bd4c121b6aedb54d076f541ff/packages/fxa-content-server/app/scripts/views/mixins/signin-mixin.js#L132) and isn't handling 170.

In addition, the new error value won't be translated unless it's [added to this list](https://github.com/mozilla/fxa/blob/8407c0c457317e6bd4c121b6aedb54d076f541ff/packages/fxa-content-server/app/scripts/lib/auth-errors.js#L246). Only one error in the [range 161 and 176](https://github.com/mozilla/fxa/blob/8407c0c457317e6bd4c121b6aedb54d076f541ff/packages/fxa-auth-server/lib/error.js#L75:L89) have entries on the [content-server](https://github.com/mozilla/fxa/blob/8407c0c457317e6bd4c121b6aedb54d076f541ff/packages/fxa-content-server/app/scripts/lib/auth-errors.js#L242).

ref #885, #530

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-30)
┆Issue Number: FXA-30

**Comment by dannycoates** [comment]
Ok, on first reading I assumed this was a consequence of the oauth->auth server merge. Now I'm pretty sure that it's not and has been an open issue for longer. I don't think this is a simple, "oops, I forgot to translate these error numbers", but a "we need to reconcile the error numbers sent by auth and handled by content" so probably a large(r) task.

**Comment by dannycoates** [comment]
I'm gonna unassign this an kick it to the backlog because I have higher priority tasks this sprint.

**Comment by vbudhram** [comment]
Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
