### ISSUE TITLE
[iOS] “Learn more” link from “Cannot create account” page does nothing

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3637]
**Build:**
Stage [1.152.0]
Prod [1.151.5]

**Affected platforms:**
iOS 13.1.2

**Steps to reproduce:**
1. Go to https://accounts.stage.mozaws.net/cannot_create_account?service=sync&context=fx_desktop_v3&entrypoint=preferences
2. Tap on “Learn more” link.

**Expected results:**
Federal Trade Commission - Children's Privacy page is successfully displayed. ( https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy )

**Actual Results:**
Nothing happens when tapping on “Learn more” link.

**Additional notes:**
- This issue is not reproducible on Android.

![IMG_0006](https://user-images.githubusercontent.com/18114210/70628679-441dcb80-1c31-11ea-81ed-346d4d45cd56.jpg)

**Comment by vladikoff** [comment]
cc @garvankeeley

**Comment by garvankeeley** [comment]
This is correct-ish, the v21 release of Fx iOS (released tomorrow) will handle these links correctly, previous versions will not. If you are able to test on the v21 Beta (currently available), it should work there.

**Comment by clouserw** [comment]
Thanks @garvankeeley.  Calling this fixed
