### ISSUE TITLE
Delete saved Username&Pass without confirmation

### ISSUE THREAD

**Issue by glaseyer** [mozilla/fxa#3646]
Hi,
when i'm on a Loginscreen, saved credentials are shown in the dropdown. wenn i highlight one and press Backspace oder Delete on the KeyBoard, the Entry disapears. I first thought this is only the Webform Cache from the browser. Later i was not able to find this Credentials in Firefox/Lockwise.

it has been deleted directli ans synct (my luck it was a test account witch could be reseted)

I had no warnings and hat no "confirm do delete" button. even worse, i have a MasterPassword active. 

Request
1) add confirm to delete Button
2) Option requires Masterpassword to delete Entries
3) add recycle Bin

regards

**Comment by clouserw** [comment]
Hi

This repository is only for the Firefox Accounts project.  It sounds like this is a request for the Firefox browser.  Please file the issue at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
