### ISSUE TITLE
Convert cached signin with an unverified account from links to codes

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3649]
If a user signs in with a cached unverified account, we send them to the legacy "confirm signup" screen.  We should send them to the "enter a code" screen instead.

Ref #3648

**Comment by vasilicatamas** [comment]
"Enter verification code" screen is successfully displayed when trying to sign in with an unverified account on:
- Firefox 71.0 under Windows 10 64-bit
- Fennec 68.4.0 under Android 8
- Firefox for iOS 21.0 under iOS 13.1.2

![Screenshot_4](https://user-images.githubusercontent.com/18114210/71901609-fe3d2000-3168-11ea-80bb-44616e61fa6f.png)
