### ISSUE TITLE
Gracefully fail on invalid query parameters

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3673]
In #3645 we're showing an error to an end user about an invalid utm parameter.  We should gracefully fail if utm parameters are wrong.  (Although logging would be great)

Maybe we should gracefully fail on non-utm query parameters also?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-20)
┆Issue Number: FXA-20

**Comment by 6a68** [comment]
Gracefully failing here probably means allowing the user to complete their sign in flow, as long as any required query params are present and valid.

**Comment by davismtl** [comment]
@6a68 mentioned in a meeting that we should prob have RP put the utm params at the end of the URL so that any mistakes don't break the URL and so that the form submit can still be successful.

**Comment by clouserw** [comment]
https://github.com/mozilla/fxa/issues/5991 has an example and a screenshot

**Comment by rlr** [comment]
Until this is fixed, we're going to have to stop passing along the utm_* parameters we get to FxA. We have pretty much no control over what utm_* parameters we get from the wild so it's pretty bad UX to show the error to the user and not let them proceed.

**Comment by chrismore** [comment]
Any idea how often this happens? I'm concerned now that we have a paid product using fxa and lots of inbound traffic to subscription pages (with utms) that this error could be leading to lost subscriptions or cancels.

What is the regex or definition of a valid or invalid parameter value?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is a regular expression which we could loosen, and also we should log this silently – not show anything to the user.
