### ISSUE TITLE
Track The First Login to a Service

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3677]
We tend to think about registrations at the moment that someone creates an account.

For most of our relying parties, a registration is the first time a user tries their service. This can happen via login or registration.

I don't have a proposal at this time but we need to track that first access to a service so teams can do better retention analysis and cohort analysis.

user story:
As the PM of Lockwise, I would like to look at the retention of accounts trying Lockwise for the first time.

CC @irrationalagent @sandysage

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-19)
┆Issue Number: FXA-19

**Comment by irrationalagent** [comment]
This is a good idea. FWIW, we have a table in bigquery called `fxa_users_services_first_seen` that contains the first usage dates for each service that each user adds (although we only have this for user-service logins after 2019-03-01).  But, we should probably get this data into amplitude somehow. 

One way would be to add a user property to login complete events that indicates whether its a new service for the users.

**Comment by clouserw** [comment]
Long term:  We want to add a parameter to the amplitude event `fxa-login-complete` that we send that indicates if the user has logged in to the service before.  

@irrationalagent what should the parameter be named?

**Comment by irrationalagent** [comment]
We would add a boolean event property `first_time` to `fxa_login - complete` that is `true` if it was the first time a user was logging into a service.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~adavis@mozilla.com] is this something we still need/or can do with the new Looker metrics?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

I'd argue that we haven't had to do it because of a new feature in Amplitude but we may need to do it for Looker.
