### ISSUE TITLE
browserid-verifier: builderror after switch to node12

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#3683]
The browser-verifier doesn't build correctly with node12 in my selfhosting anymore. With node10 everything is fine.

[...]
./bignum.cc:1127:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(bignum, init)
 ^~~~~~~~~~~
In file included from /home/fxa/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../bignum.cc:8:
/home/fxa/.cache/node-gyp/12.13.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/home/fxa/.cache/node-gyp/12.13.1/include/node/node_object_wrap.h:84:78:   required from here
/home/fxa/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/fxa/.cache/node-gyp/12.13.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:66:61:   required from here
/home/fxa/.cache/node-gyp/12.13.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
In file included from ../bignum.cc:8:
../../nan/nan.h: In instantiation of 'void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]':
../../nan/nan.h:2353:20:   required from 'void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]'
../bignum.cc:1124:62:   required from here
../../nan/nan.h:2337:3: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^~~~
In file included from /home/fxa/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14,
                 from /home/fxa/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /home/fxa/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../bignum.cc:8:
/home/fxa/.cache/node-gyp/12.13.1/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^~~
/home/fxa/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [bignum.target.mk:111: Release/obj.target/bignum/bignum.o] Error 1
make: Leaving directory '/home/fxa/packages/browserid-verifier/node_modules/bignum/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.0-3-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fxa/packages/browserid-verifier/node_modules/bignum
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

**Comment by dannycoates** [comment]
`bignum` is an optional dependency, so it's ok to ignore this error. I filed https://github.com/mozilla/browserid-crypto/issues/120 to follow up
