### ISSUE TITLE
Endless throbber accounts page from email campaign link, works on refresh

### ISSUE THREAD

**Issue by digitarald** [mozilla/fxa#3684]
## Description

Clicking through a campaign link ends on endless-throbber page.

### Steps to reproduce

Clicked on campaign link from `Find out if you have been part of a breach`.

### Expected result

Page loads

### Actual result

<img width="672" alt="image" src="https://user-images.githubusercontent.com/8599/70852904-b540c700-1e5b-11ea-8b2a-16e895a0b7e7.png">

HAR file for opening the link: https://www.dropbox.com/s/rs06y90fx1sfi5r/accounts.firefox.com_Archive%20%5B19-12-14%2010-14-37%5D.har?dl=0

HAR file for refresh: https://www.dropbox.com/s/mw7iq1wucw6lyi0/accounts.firefox.com_Archive%20%5B19-12-14%2010-16-32%5D.har?dl=0

### Environment

Private Browsing mode in Firefox Nightly.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-18)
┆Priority: Medium
┆Issue Number: FXA-18

**Comment by clouserw** [comment]
This might be related to #3645 or #3673

**Comment by clouserw** [comment]
The campaign link was fixed so, I'm optimistically calling this fixed.  Thanks for filing and let us know if it's still broken please.
