### ISSUE TITLE
Add amplitude pings for resubscribe events

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3692]
While refactoring some Amplitude code, I noticed that our calls for `reactivateSubscription` don't have any Amplitude pings associated with them. Should we add them?

/cc @johngruen - not sure who might need to weigh in on this or where our original list of pings is. (We could probably use a docs/metrics.md)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-15)
┆Issue Number: FXA-15

**Comment by 6a68** [comment]
There is an amplitude taxonomy doc that lists all the pings (second tab on the bottom) https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=813106673

**Comment by lmorchard** [comment]
> There is an amplitude taxonomy doc that lists all the pings 

@6a68 Doesn't look like that list includes any of our subscription-related pings. This is what we have implemented so far on payments-server - https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/lib/amplitude.ts

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

We are not prioritizing amplitude bugs at the moment.
