### ISSUE TITLE
Up the StatsD Sampling Rate in Auth Server

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3696]
This is a config change, which can be done by updating teh default value in `config/index.js` or through an env var.

The issue here is mostly a request for comment from Ops.

When StatsD was proposed for the auth-server, Shane expressed concern because of some performance issues from back in the Datadog days.  As a result I conservatively set the default sampling rate to 0.1.

Now that we've been collecting stats for a while and have not experienced any related performance issues, I think we could increase the sampling rate.

@jbuck @jrgm What's your take on this?  How high can we go?

cc @clouserw

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-13)
┆Priority: Medium
┆Issue Number: FXA-13

**Comment by clouserw** [comment]
Thanks @chenba.  I think this is a good idea because right now we get 0 to 5 data points per day on really low traffic points right now (like subscription platform).  eg. https://earthangel-b40313e5.influxcloud.net/d/Bm47VHbWz/fxa-auth-server-subhub?orgId=1

**Comment by jbuck** [comment]
We could set it to 1 and see if InfluxDB blows up :)
