### ISSUE TITLE
Release scripts fails when running patch sometimes

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#3698]
While tagging train-152 with @LZoog we found in certain scenarios the release script returns the latest tag as

```
vijaybudhram-ms:fxa vijaybudhram$ git describe --tags --first-parent
monorepo-merge-1006-g94b11a69d
```

This will cause the tag parsing rules to fail and the script to not continue. This might be related to https://github.com/mozilla/fxa/issues/1270.

As a workaround, we can manually specify the current train tag to cut the release.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-12)
┆Issue Number: FXA-12

**Comment by LZoog** [comment]
👍 The error I saw when running `./release.sh patch` was:

```
expr: not a decimal number: 'monorepo'
```

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is this still an issue?  I haven't seen/heard any other reports

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

I think so? The scenario would be

  1. Train 199 in production
  2. Tag and merge train 200 to master
  3. Need to tag point release on train 199

With our 1 week train, this is probably less of an issue verses doing tags every 2 weeks.

**Comment by 6a68** [comment]
I don't know why this happened for the most recent release, but I ran into this bug today.

**Comment by clouserw** [comment]
`git describe --tags --first-parent --abbrev=0` is the command running and returning `monorepo-merge`.  Searching around the internet shows other projects using that command successfully.  

However, running `git describe --tags --abbrev=0 --match "v*.*.*"` fixes it for me, and maybe would be a good alternative?

**Comment by clouserw** [comment]
https://stackoverflow.com/questions/3867619/how-to-get-last-git-tag-matching-regex-criteria/42131335 has some other ideas including:

`git for-each-ref --sort=-taggerdate --count=1  refs/tags/v*`
and
`git describe --match "v*.*.*" --abbrev=0 --tags $(git rev-list --tags --max-count=1)`

both of which work for me

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This doesn't happen often enough to worry about it.
