### ISSUE TITLE
Service Management - Mozilla-branded Services 

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#37]
As a FF user when using Firefox,

1. I want to manage the devices and services attached to my FxA from one place.  
 1a. For Mozilla-branded services like Sync and Hello, I want to be able to revoke the service and turn off data types synced between devices. This can include Sync data types as well as other Mozilla information services like Hello. My expectations about how those data types coexist on my FF devices should be consistent.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-14
