### ISSUE TITLE
Remove /subscribe_sms endpoint

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#370]
Over in https://github.com/mozilla/fxa-basket-proxy/issues/21 we added an endpoint `/subscribe_sms`, which forwards to a `/subscribe_sms` endpoint on basket.  But from the linked discussion, it doesn't look like we ever ended up landing code to use it.  Is it safe to remove?

@jbuck of @jrgm, can we tell from fxa-basket-proxy server logs with /subscribe_sms is ever called in production?

**Comment by shane-tomlinson** [comment]
I'm going to close this, we are in the process of getting rid of the basket proxy.
