### ISSUE TITLE
convert each component and route in payment server to use fluent l10n

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3704]
from `src/components`:
- [x] AlertBar
- [x] DialogMessage
- [x] FetchErrorDialogMessage
- [x] LoadingSpinner
- [x] Tooltip
- [x] LoadingOverlay
- [x] PaymentForm
- [x] PaymentLegalBlurb
- [x] Portal
- [ ] fields
- [x] AppLayout
- [x] ErrorMessage
- [x] CloseIcon

from `/src/routes/Product`:
- [x] PlanDetails
- [x] SubscriptionCreate
- [ ] SubscriptionUpgrade
- [x] index
- [x] ProfileBanner
- [x] SubscriptionRedirect

from `/src/routes/Subscriptions`:
- [x] PaymentUpdateForm
- [x] Reactivate
- [x] SubscriptionItem
- [x] index

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-11)
┆Issue Number: FXA-11

**Comment by LZoog** [comment]
Hey @meandavejustice, I know we closed this 3 days ago, but I think we're still lacking translations in/for at least:
- `PaymentUpdateForm`
- `SubscriptionItem`
- `routes/Subscriptions/index`
- `AccountActivatedBanner`
- `Product/SubscriptionCreate/index`
- 3x `aria-label`s (in `components/DialogMessage`, `routes/Product/SubscriptionUpgrade`, and `routes/Subscriptions`

**Comment by LZoog** [comment]
Also, I wonder if work completed for this mean we can also close #1089 or are the date formats and "edgecases" (per Les and Wil's comments) keeping that one open?

**Comment by meandavejustice** [comment]
@LZoog Thank you, reopening to check these out
