### ISSUE TITLE
Upload product-icons to FxA CDN

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3706]
We're got some new icons checked into the repo:

* https://github.com/mozilla/fxa/tree/master/assets/product-icons/

Ideally, we'd like to make these available hereabouts:

* https://accounts-static.cdn.mozilla.net/product-icons/

Pinging @jbuck & @jrgm for CDN upload help.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-10)
┆Priority: Medium
┆Issue Number: FXA-10

**Comment by jbuck** [comment]
* https://accounts-static.cdn.mozilla.net/product-icons/123-done-pro.svg
* https://accounts-static.cdn.mozilla.net/product-icons/123-done-pro-plus.svg
* https://accounts-static.cdn.mozilla.net/product-icons/fpn.svg
