### ISSUE TITLE
evaluate redis eviction policy for auth-server

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3707]
It may be possible to safely evict old records depending on how they're used... @dannycoates to add more detail.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-9)
┆Issue Number: FXA-9

**Comment by clouserw** [comment]
This is for session token metadata

**Comment by vbudhram** [comment]
Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
