### ISSUE TITLE
deprecate 'disabled' config options in favor of 'enabled'

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3708]
@jackiemunroe brought this up in slack.

We should standardize on `enabled` as the preferred convention for config variables. To do this we should:

1. add the new config var and env name
2. map _both_ the old and new env to the new var
3. release (before updating ops config)
4. update ops config
5. release
6. remove old env name from code

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-8)
┆Issue Number: FXA-8

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This will be done in the Global config service feature
