### ISSUE TITLE
Add support for versioning

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#372]
Noticed that this repo wasn't setup to use any versioning scripts. We could add it using our normal scripts or add [np](https://github.com/sindresorhus/np) like we did in the fxa-shared repo. I think it makes sense to use np since this gets published.

**Comment by philbooth** [comment]
I'm going to close this one because the monorepo will have [it's own release script](https://gist.github.com/philbooth/94a1f5ec37d9983a17adae1a38e13acd).
