### ISSUE TITLE
Email marketing events not in Amplitude

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#3725]
It was reported that the email marketing events are not being sent to Amplitude anymore, starting around April 10th. I checked BrickFTP ( /etl/deg-exacttarget ) for the files, and the latest file I'm seeing is `FXA_Email_Events_20190409.zip`, and `FXA_Email_Events_Sent20190308.zip`. We should figure out why SFMC stopped sending files to BrickFTP

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-596)
┆Issue Number: FXA-596

**Comment by jbuck** [comment]
Amplitude chart for the interested: https://analytics.amplitude.com/mozilla-corp/chart/new/wi1rpzj

**Comment by LaurenNiolet** [comment]
I can shed some light on this. In April, the automation that produced the export file began failing. This was an ETL process that relied on SFMC's terribly under-equipped SQL infrastructure. 

Efforts to troubleshoot failed and we moved on to focus on FxA MAU work. The good news is that this week, the IT team is finishing up moving FxAs from SFMC to SFDC (CRM). The result: all the data we need to resume this export will be housed in the same place, vastly simplifying the process of sending it over. 

I'd like to try having the faucet turned back on in January.

**Comment by clouserw** [comment]
Is there any FxA Engineering work to do in this issue?

**Comment by 6a68** [comment]
@LaurenNiolet We're doing some metrics pipeline redesign work, and we're investigating feasibility of moving our sources from batch to streaming processing. Is there an SFMC API that we could pull from, instead of relying on batch exports to FTP?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This will be handled in this tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1617710
