### ISSUE TITLE
[Epic] Metrics pipeline improvements

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3738]
Some of the existing metrics issues will be fixed as part of a broader redesign of the metrics pipeline. Collecting those here, so they aren't lost in the backlog.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-838)
┆Issue Number: FXA-838

**Comment by clouserw** [comment]
epics are tracked in jira
