### ISSUE TITLE
Rewrite release.sh script in JS

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#3739]
The release.sh script is pretty painful to deal with if anything goes wrong. If we rewrote it in JS, we could have a much shorter script to maintain, since there's a git / github package on npm, and JS actually supports unit tests, so we could trust the code a bit more.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-839)
┆Issue Number: FXA-839

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This isn't on our near term roadmap.
