### ISSUE TITLE
[Epic] FxA Settings Redesign

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3740]
Related: #2325 is a redesign epic created to keep track of 2019 Q4 UX and design progress. This epic should hold phase 1 engineering issues.

See FXA-840 on Jira which is our single source of truth for this epic. Updates in the description are no longer synced to this issue since epics aren't created as Jira tickets.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-840)
┆Issue Number: FXA-840

**Comment by davismtl** [comment]
PRD WIP for phase 1: https://docs.google.com/document/d/18zu7JCYIsUp8tUMJqb2uErNlzL9f6CQvefLy9HFZ4UY/edit#

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Alex made updates to stories, documented user flows and provided more context in the PRD.

Janice, Philip and Marydel met to read over the stories and look at the flows.
