### ISSUE TITLE
[ADR needed] Redesign kickoff infrastructure: React app?

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3741]
There's been some discussion around whether or not the settings redesign could make sense to propel us into Reactland, which has been on everyone's minds for a while. This strongly relates to #3430, migrating the `fxa-content-server` to React. It's possible an ADR could be shared amongst these issues.

The outcome of this decision could also be impacted by Phase 1 / Phase 2 scope & priorities which is TBD at the time of writing, but I'd like to capture some thoughts from folks before the holidays. As the wires ([desktop](https://mozilla.invisionapp.com/share/PTUIT2C4N8Z#/screens/398004229) / [mobile](https://mozilla.invisionapp.com/share/7FUIT2QWQRE#/screens)) stand today, it seems likely that "Plans and Billing" will not be included in Phase 1 unless we want a link-out to the application.

I wonder if this could be the ideal solution:
* Discuss and determine LoE to integrate payments into settings, considering
  * per @bbangert, at least "Update your Credit Card" requires a separate domain, but also potentially billing history - how can this be integrated nicely?
  * other engineering priorities and timelines - could this infrastructure work be done in Phase 1?
  * We probably need to identify underlying security concerns. We have an [ADR written for the payments server separation](https://github.com/mozilla/fxa/blob/master/docs/adr/0001-isolating-payment-content-with-third-party-widgets-from-general-account-management.md) that would be good to review. How's this affect CSP, as in payments we currently allow inline CSS styles due to iframes?
* Move forward with the settings updates, excluding payments (and other issues/features determined to be beyond Phase 1) in a React app

While the payments -> settings integration is a separate issue, it probably makes _less_ sense to move settings to a React app with this redesign if payments remains its own separate application.

@dannycoates has also suggested a "phase 0" that would restyle and rearrange our views to reflect something similar to the wires but keep things functionally identical. (Maybe the drawers could be all "open".) I will bring this up in consideration of conversations next week as well.

---

This list is no where complete but can get us started. Whatever we choose, shuffling around views = our tests are not going to be fun to get passing.

Pros:
- Gives us a better opportunity to better organize our queries hitting the settings page, which I think we have several issues open for
- A separate application could make rolling out to some users easier (A/B testing)
- We won't have to create or retrofit the new header and navigation in both Backbone + React, we can just write it in React
- Allows users to have a much more seamless, cohesive Accounts experience
- Propels us into a modern framework
- Storybook?

Cons:
- Time for initial setup & rollout
- Setup for payments restructuring

Approaches (which will need greater detail & planning):
- Create a new React app in `packages/fxa-content-server/fxa-settings` (I think `fxa` is pretty superfluous here, but🤷‍♀️), duplicate files as-needed, and begin [embedding React into the Backbone Views](https://reactjs.org/docs/integrating-with-other-libraries.html)
- There are likely additional approaches TBD as discussion ensues and I spend more time thinking about this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-841)
┆Issue Number: FXA-841

**Comment by dannycoates** [comment]
I broadly agree. I think it's debatable whether the "new" way would take longer to rollout than a major refactor of the existing code. They're both a lot of work but in different ways

**Comment by lmorchard** [comment]
My basic $0.02:

If the changes are limited to CSS & HTML tweaks without new functionality - refactoring the existing Backbone settings app makes sense to me.

If changes introduce new functionality and the CSS & HTML are basically a ground-up remake - then starting a fresh React app makes more sense to me. (i.e. *not* embedded in Backbone)

And beyond React vs Backbone, this could also be an opportunity to extract model & API code from the existing settings app into shared modules reusable by both old & new apps.

IMO, it could be good to have an incremental view-by-view build up in a new React app. Deploy smaller changes to a new domain as soon as they're ready. Have QA (and maybe alpha/beta users?) try them out along the way? We could possibly set it up as a new OAuth RP with a special scope to access settings-related auth-server APIs.

It would mean we have a "new settings experience" that's in an incomplete state for awhile. But, it could mean it's been solidly beaten on by the time it's ready for us to call it done.

**Comment by davismtl** [comment]
Per our discussion todays, the first phase will mostly aim for feature parity (which would maybe be an argument against React) but the overall goal of his new project is to give us more flexibility to expand settings and add more functionality (which might be a pro for React). There are already quite a few new features we will want to add after.

In terms of timeline, while we hoped to get an MVP/phase 1 out in Q1, if the ideal engineering path forward requires a bit more time and doesn't fit within those dates, I think we can be accomadating to have the best path forward.
