### ISSUE TITLE
[Epic] Subscription Architecture 2.0

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3742]
## Overview

Subscription Platform 2.0 is a change to how Stripe integration is handled in FxA. The core of these changes is that communication with SubHub is skipped, and FxA interacts with Stripe via API calls and Stripe webhooks.

## Work Overview

- Implement Stripe API calls instead of SubHub API calls (Preliminary work exists)
- Tests for Stripe API calls
- Implement Stripe webhook handling & tests
- Use Stripe to determine if a user has a subscription
- Remove SubscriptionAccount table and usage
- Update support panel to show subscription information
- Documentation updates as needed

## Links

Technical specification: https://docs.google.com/document/d/1H_FWUtuz1qURfc7R5G2dzvSWqNVnYflKrlYYP9fKcR8/edit?ts=5dcc62e0#

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-842)
┆Issue Number: FXA-842

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We had a sync up meeting on Tuesday to align priorities and schedules.  Everything is still on track.
