### ISSUE TITLE
Privacy Notice link wraps

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#3743]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1543666, the FxA Privacy notice link wraps to the next line, which causes the link to look funny?

![Screen Shot 2019-12-20 at 3 02 54 PM](https://user-images.githubusercontent.com/1295288/71288918-d876e500-2339-11ea-8955-af85436b13da.png)

@ryanfeeley Thoughts? We could rename the link, or even close this bug if working as intended.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-843)
┆Priority: Medium
┆Issue Number: FXA-843

**Comment by ryanfeeley** [comment]
Other option, that I am not averse to, is to put a unicode non-breaking space `like this` (if that works) between `Privacy` and `Notice`.

**Comment by ryanfeeley** [comment]
Back in a day, there were Wordpress plug-ins that would do this to posts automatically to prevent typographic orphans.

**Comment by clouserw** [comment]
Let's use a non-breaking class in the link

**Comment by LZoog** [comment]
To elaborate on Wil's suggestion, we'll probably be able to add a class on the link (or use an existing class) and add `white-space: nowrap` in the CSS. If there's any issue with that we can wrap the link in a `span` and add the class there.

**Comment by vasilicatamas** [comment]
Privacy links are successfully displayed in sign-in pages on: 
- Firefox 71.0 under Windows 10 64-bit, Mac OS X 10.14.6
- Fennec 68.4.0 under Android 8
- Firefox for iOS 21.0 under iOS 13.1.2
![Screenshot_3](https://user-images.githubusercontent.com/18114210/71900838-478c7000-3167-11ea-9d6f-2f19915dfaa9.png)
