### ISSUE TITLE
If user types password in sign-up and quickly tabs away when matching criteria, strength balloon persists

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3750]
I believe this is an edge-case I didn't catch in #3724.

If a user types their password quickly enough and tabs before all 3 checks are shown, the password strength balloon doesn't disappear.

![pw](https://user-images.githubusercontent.com/13018240/71366022-60d9cd80-2566-11ea-84c0-947cc3aada9c.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-845)
┆Priority: Medium
┆Issue Number: FXA-845

**Comment by mirunacurtean** [comment]
The password strength tool-tip is now displayed for only a couple more seconds after switching to the next row by using the TAB key (on windows/mac) or the Next key (on Android).

Fix has been verified on:
Firefox 71.0 on Windows Pro 10 64-bit
Firefox 71.0 on macOS Catalina 10.15
Fennec 68.4 on Android 8.0

![Type password and hit TAB](https://user-images.githubusercontent.com/53306802/71908522-dd7bc700-3176-11ea-9178-1b7067904ea0.gif)
