### ISSUE TITLE
use pseudolocalization to test translations on payments server

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3756]
need to get myself up to date with https://github.com/projectfluent/fluent.js/issues/83

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-848)
┆Issue Number: FXA-848

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

If we do this it should be across all of FxA.  Closing this narrowly scoped issue.
