### ISSUE TITLE
move AppLocalizationProvider into separate file and use TS types over proptypes

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3762]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-849)
┆Issue Number: FXA-849

**Comment by LZoog** [comment]
I just realized our console is complaining now too. We can probably take care of this with a fix for this issue.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/13018240/71524020-356e2000-2891-11ea-9df6-a736741dfd42.png">
