### ISSUE TITLE
Login is not working on AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/fxa#3764]
STR:
1. Load https://addons-dev.allizom.org/en-US/firefox/
2. Try to login/register 

Expected result: 
The user can log in AMO dev 

Actual result:
Login/registration is not working. 

Notes:
This issue is not reproducible on AMO stage or AMO prod. 
The issue is also reproducible from dev hub https://addons-dev.allizom.org/en-US/developers/ or code manger https://code.addons-dev.allizom.org/en-US/ on the dev server. 

![logindev](https://user-images.githubusercontent.com/33448286/71514273-905e4200-28a6-11ea-86b6-0693b7ff6ca1.gif)

I'm tagging @shane-tomlinson @rfk from https://github.com/mozilla/fxa/issues/326

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-850)
┆Priority: Medium
┆Issue Number: FXA-850

**Comment by dannycoates** [comment]
This should be fixed as of now. ref #3766

**Comment by ioanarusiczki** [comment]
Works for me now - with FF71(Win10).
