### ISSUE TITLE
Stable dev is down

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#3766]
Currently, the `stable` dev environment seems fairly busted:

502 error from Profile server (https://stable.dev.lcip.org/profile/v1/profile)
502 error from 123done (https://123done-stable.dev.lcip.org/)
404 error from auth API endpoint (https://stable.dev.lcip.org/auth/v1)
404 error from oauth API endpoint (https://oauth-stable.dev.lcip.org/v1)

Content server is up, but profile 502s during login, so the settings page is just a blank screen.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-851)
┆Priority: Medium
┆Issue Number: FXA-851

**Comment by dannycoates** [comment]
stable ought to be fixed now. down because the profile-server docker image was broken #3767 and #3755
