### ISSUE TITLE
Auth-server tests failing because of fxa-geodb

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#3773]
From https://app.circleci.com/jobs/github/mozilla/fxa/133100, we get

```
  1) geodb
       returns location data when enabled:
     Error: ENOENT: no such file or directory, open '/fxa-geodb/db/cities-db.mmdb'
```

That code hasn't changed in a while, so might be maxmind geodb related.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-854)
┆Priority: Medium
┆Issue Number: FXA-854

**Comment by vbudhram** [comment]
Per https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

`Starting December 30, 2019, we will be requiring users of our GeoLite2 databases to register for a MaxMind account and obtain a license key in order to download GeoLite2 databases.`

**Comment by clouserw** [comment]
In production we have a full license, but we need something in dev.

**Comment by immanuelfodor** [comment]
Not only in dev, there is also a geodb error in Firefox Send which uses this project as a dependency, and a self-hosted Send won't start without removing it: https://github.com/mozilla/send/issues/1430
