### ISSUE TITLE
Device Management- Third party FxA-relying services

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#38]
As a FF user when using Firefox,

1. I want to manage the devices and services attached to my FxA from one place.  
 1b. For third party FxA-relaying services, I want to be able to disconnect them from FxA.

**Comment by ryanfeeley** [comment]
Why just one place? Why at all? Let's flesh out this story to include why.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-15
