### ISSUE TITLE
Show totp secret in a modal

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3804]
Follow up to #3748 

The “Can’t scan code?” link should open a modal instead of showing the secret inline.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-862)
┆Priority: Medium
┆Issue Number: FXA-862

**Comment by vasilicatamas** [comment]
I can confirm that the secret key is successfully displayed in a modal on Stage 1.155,0 under Windows 10 64-bit, Android 9 and iOS 13.1.2.

![Screenshot_23](https://user-images.githubusercontent.com/18114210/73665257-7a178300-46a9-11ea-971e-711150652855.png)
