### ISSUE TITLE
Survey not found

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#3807]
#### Affected versions:
- Firefox Release 71.0

#### Affected Platforms:
- Windows 10 (64-bit)

#### Prerequisites:
Have an active subscription.

#### Steps to reproduce
1. Go to [Manage subscriptions](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions?device_id=e67c73c571ec4a8d981c9bb28de3347a&flow_begin_time=1578323831817&flow_id=d167bb9ab4e2fe87e869f1d11af2638e98efe5f413e7c33f701e429c603f7720) and Cancel your subscription.
2. Go to the "Subscription cancellation" email and click on the "short survey" link.

#### Expected result:
The [survey page](https://www.surveygizmo.com/s3/5111573/d9c6a6dceb0c) is displayed correctly.

#### Actual result:
The survey page is not found.

![Screenshot (33)](https://user-images.githubusercontent.com/48829350/71829183-b8228680-30ac-11ea-8ba4-315f14a9fcfa.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-864)
┆Priority: Medium
┆Issue Number: FXA-864

**Comment by clouserw** [comment]
This looks like it's on stage and it's an email coming from marketing cloud.  @stlhood can you help us here?

**Comment by stlhood** [comment]
Confirmed this is only happening in staged. The issue has now been fixed.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible, using the latest Firefox Release (72.0.1).
Verified on Windows 10 x64.
The [Survey page](https://qsurvey.mozilla.com/s3/fpn-cancellation) works as expected.
