### ISSUE TITLE
Use cached Stripe customer data as source of subscription status

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3808]
We currently use a local DB table in auth-server that tracks subscriptions per user. This information is redundant when considering the user's customer record in Stripe as the source of truth. So, let's use that customer record directly instead - and remove the local DB table altogether.

Also, let's cache the data locally to reduce hits to the Stripe API. This data is used by every RP that fetches a user's profile to check subscriptions, so that will be a hot spot for access.

Cache lifetime & invalidation policy is a concern. Stale cache means that a recently purchased or expired subscription is not reflected in the system. So, we should explicitly expire a cached customer record whenever we know the data has changed - i.e. when a user subscribes or cancels, or when Stripe sends a webhook event that changes a subscription.

Another handy point to invalidate the cache could be when the user authenticates to use the subscription management pages. That would help ensure that the data is fresh as the user begins to engage in subscription changes.

It might also help to have an explicit cache invalidation tool or button for a support agent to force-refresh a user's customer record in the cache.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-865)
┆Issue Number: FXA-865

**Comment by bbangert** [comment]
@lmorchard notes that we will store the entire Stripe customer object with nested fields for subscriptions in Redis.
