### ISSUE TITLE
Set amplitude property when user enables MFA

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#381]
from mtg: To help get a better understanding of the feature we should log this property.

```
vbudhram: yep, you'll just need to add it to `mapUserProperties` in metrics/amplitude.js in fxa-shared, then make sure you pass in the appropriate data from the auth server to set it
2:33 PM (i'm assuming it can only be set in the auth server because that has the info, but set it from the content server if it's available there as those events occur earlier which means the user property will be available on more events in the amplitude ui)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-599)
┆Priority: Medium
┆Issue Number: FXA-599

**Comment by clouserw** [comment]
Maybe @vbudhram already did this!

**Comment by vbudhram** [comment]
We currently emit metrics for when users enable two step authentication from settings page

Ref: https://analytics.amplitude.com/mozilla-corp/chart/xrqs8j3

**Comment by vbudhram** [comment]
Marking this as closed ^
