### ISSUE TITLE
Stripe webhook handler

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3812]
We need to handle several Stripe events to know when a subscription state for a user has changed. If a subscription should be regarded as inactive even though its in our list of active states we need to know that as well.

[Events ](https://stripe.com/docs/api/events/types)we need to listen for:
- customer.updated
- customer.subscription.created
- customer.subscription.updated
- customer.subscription.deleted

When any of these events come in we must invalidate the customer object cached and re-fetch.

@jackiemunroe notes that we can also listen for product/plan events to invalidate our plan/product caching and update them out of band from a user-driven request.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-870)
┆Issue Number: FXA-870

**Comment by chenba** [comment]
> invalidate the customer object cached and re-fetch

@bbangert Where is this cache?  Are you referring to something in subplat 2.0 that's not currently in the code?

**Comment by chenba** [comment]
Per discussion elsewhere, we'll invalidate the customer on "customer.updated" only.  It is not necessary to handle the "customer.subscription.*" events since they also trigger a "customer.updated".
