### ISSUE TITLE
“Not now” button not displayed on Android

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3821]
**Note:**
This is a follow-up issue for #3597

**Build:**
Stage [Train 1.154.0]

**Affected platforms:**
Android 8

**Steps to reproduce:**
1. Launch Firefox app and login using a Firefox account.
2. Observe the CAD page.

**Expected results:**
“Not now” button is successfully displayed under “Why is more than one device required” string.

**Actual Results:**
“Not now” button is not displayed.

![Screenshot_20200107-134722](https://user-images.githubusercontent.com/18114210/71895298-5f5cf780-3159-11ea-8f67-0a646c9100d7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-875)
┆Issue Number: FXA-875

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Should the link appear here or not?  It sounds like we don't include it on purpose right now.  /cc [~rfeeley@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible on the current Fenix release (it was as Fennec specific bug) as the CAD page is not displayed because the user is automatically redirected to the settings Fenix menu.
