### ISSUE TITLE
1.3 Reduce cost per install of SMS by at least 25%.

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3824]
Our monthly bills are big. Let's revisit our supported countries and the overall flow. Lets optimize the whole thing to reduce costs and to make sure that users clearly understand why they are sending and SMS and that they are getting the most out of it.

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-878)
┆Issue Number: FXA-878

**Comment by jrgm** [comment]
Drive by note: consider that some countries are >10x other countries.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

While Leif is doing cost analysis,  ( https://docs.google.com/document/d/1j7STjUZW0zhR92ABBVRpt8r3DtbmQKkMHkBtMpPoT7k/edit# )
[~rfeeley@mozilla.com] is looking into updating copy in the flow to reduce confusion.
