### ISSUE TITLE
[payments] eliminate SENTRY_URL config; derive from SENTRY_DSN instead

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#3829]
I said this in slack:

>  So, I see a possible issue with payments and sentry. Payments has config for SENTRY_DSN (default: ‘’) and SENTRY_URL (default 'https://sentry.prod.mozaws.net/444').  The former is set in the environment for dev/stage/prod k8s; the latter is not. However, the URL can be derived from the DSN in whatever form one wants, so it seems to me the fix is to do that in the payments code, and not a redundant config option.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-883)
┆Issue Number: FXA-883

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
