### ISSUE TITLE
Not seeing bounce events in Amplitude

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#383]
I created an Amplitude dashboard for the Yahoo! experiment. SocketLabs bounce events are not showing up in it:

https://analytics.amplitude.com/mozilla-corp/dashboard/fsuk88d

I wonder if we got something wrong in the outgoing event structure from this repo, which is causing the auth server not to fully parse them or something? Or maybe one of the properties crucial for Amplitude import to work is not set.

I'll dig into it tomorrow.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-600)
┆Issue Number: FXA-600

**Comment by clouserw** [comment]
The two issues mentioned above are now https://github.com/mozilla/fxa/issues/434 and https://github.com/mozilla/fxa/issues/479
