### ISSUE TITLE
Account management page does not meet UI specs

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#3836]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.6
- Linux Ubuntu 16.04 (64-bit)

#### Steps to reproduce
1. Make a subscription on 123done.
2. Go to your [FxA account](https://accounts.stage.mozaws.net/) page.
3. Click on the **Manage..** button in the subscription section.
4. Observe the UI.

#### Expected result:
- There are no UI issues.

#### Actual result:
- The text reads **You are billed** instead of **You'll be billed**.
- The **Hey, you should really think about upgrading!** should not be displayed.
- The card icon is missing.

![image](https://user-images.githubusercontent.com/17178945/71976979-63078180-3220-11ea-91eb-d57e9cdfa260.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-890)
┆Issue Number: FXA-890

**Comment by bbangert** [comment]
@johngruen the 'Hey' line is coming out of Stripe per our specs. Did you want to change that, or should we consider this the intended output for testing at this point?

**Comment by johngruen** [comment]
Based on this and #3837, it looks like maybe two different specs were being referenced? I am actually inclined to not have either thing in settings at this point

**Comment by lmorchard** [comment]
> I am actually inclined to not have either thing in settings at this point

Well, the "Hey" line is relatively easy to remove: Just delete the CTA from Stripe metadata.

Adding an upgrade link for #3837 is harder: we'd need to figure out what the logic is to decide when the link appears and to what exactly it links.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This was redesigned
