### ISSUE TITLE
Tiered upgrade is not available in the subscription management page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#3837]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.6
- Linux Ubuntu 16.04 (64-bit)

#### Steps to reproduce
1. Make a subscription on 123done.
2. Go to your [FxA account](https://accounts.stage.mozaws.net/) page.
3. Click on the **Manage..** button in the subscription section.
4. Observe the UI.

#### Expected result:
- The **Upgrade Subscription** option is available to the right of the product name in the top.

#### Actual result:
- The **Upgrade Subscription** option is not available.

![image](https://user-images.githubusercontent.com/17178945/71976680-95fd4580-321f-11ea-9ccf-155433d6eda0.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-889)
┆Issue Number: FXA-889

**Comment by bbangert** [comment]
@johngruen can you confirm that this is intended behavior? I don't recall this in the PRD.

**Comment by johngruen** [comment]
@bsurd can you send a link to the spec you are looking at?

**Comment by bsurd** [comment]
Hey @johngruen, [this](https://mozilla.invisionapp.com/share/A3UT5FV6W8Q#/screens/393124327) is the link which we were working with.

Based on that and additional documents received, we've made a set of test cases [here](https://testrail.stage.mozaws.net/index.php?/suites/view/6383&group_by=cases:section_id&group_order=asc&group_id=62429) that we've sent in for review to everyone to confirm that everything is correct.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

feel like this is a little gross and is probably the job of the RP anyway
