### ISSUE TITLE
header 'Content-Type' could be 'content-type'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#384]
Yeah, yeah, minor nit, but I happened to notice this line: https://github.com/mozilla/fxa-email-event-proxy/blob/master/index.js#L68

Headers are case-insensitive. In practice though, 'Content-Type' is matching. Whether to do anything, or how comprehensive to cover this is up to you. (I suppose one could try the JSON.parse, and if that throws, try the qs.parse).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-601)
┆Issue Number: FXA-601

**Comment by clouserw** [comment]
As far as I know, `Content-Type` is correct.  Closing this assuming it got fixed at some point or I'm misunderstanding the bug...
