### ISSUE TITLE
Unverified state section fixes

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#3848]
When testing two-step authentication changes on a staging server, I noticed that our rarely-seen unverified state has a few issues:

1. Section names should not be in title case
2. `Primary email` is missing its line break

![image](https://user-images.githubusercontent.com/68213/72021093-357c0180-323b-11ea-8700-1ab77d804159.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-899)
┆Issue Number: FXA-899

**Comment by apsychogirl** [comment]
Hi, Can I take this up?

**Comment by LZoog** [comment]
Hi @apsychogirl, if you're still interested in taking this issue on yes, feel free to work on it!

**Comment by LZoog** [comment]
Closing this issue as we have a new settings page that makes this issue obsolete.
