### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#385]
Instead of giving a ZIP from Circle CI. 

Let's try to create github tag then a  release with attachments. For now we can just manually attach it, but we could automate it in the future.!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-602)
┆Issue Number: FXA-602

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

Won't fix.
