### ISSUE TITLE
Notes cannot login in Firefox Nightly, halts at Profile Server request

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#3857]
The extension halts at the OPTIONS profile server `/profile` request 
![image](https://user-images.githubusercontent.com/128755/72083510-f2b83900-32cf-11ea-9aa5-473cc02b7794.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-904)
┆Issue Number: FXA-904

**Comment by vladikoff** [comment]
This works fine in Firefox Release, @rfk I think we had an issue tracking this that was fixed?

**Comment by vladikoff** [comment]
Related https://github.com/mozilla/fxa/issues/2411

**Comment by rfk** [comment]
The `Origin: null` thing is from [Bug 1405971](https://bugzilla.mozilla.org/show_bug.cgi?id=1405971). It looks like there's some related bustage in [Bug 1607154](https://bugzilla.mozilla.org/show_bug.cgi?id=1607154) which sounds similar to what we're doing here (cross-origin request with Authorization header).

From the debug view, profile-server is correctly echoing back `access-control-allow-origin: null` in the response headers. But the webextension's origin is not actually "null", so [the browser rejects its attempt to send credentials with the request](https://bugzilla.mozilla.org/show_bug.cgi?id=1607154#c6).

We *should* be able to fix this by setting `{cors: "ignore"}` on the profile-server, but that requires us to [update to the latest hapi](https://github.com/mozilla/fxa/issues/2411#issuecomment-554824718).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is there a timeline when you need this?  Updating HAPI might be a can of worms

**Comment by chenba** [comment]
#2601 is the latest "update Hapi" issue.

**Comment by rfk** [comment]
IIUC the change in Nightly was backed out and Notes login should be working again. I've mentioned Notes as a good testcase for manual QA in the bug since it seems to exercise all the right bits of Firefox that come together to cause problems like this.

So, assuming things have indeed starting working again, I don't think there's a pressing time constraint here.

**Comment by vladikoff** [comment]
> We should be able to fix this by setting {cors: "ignore"} on the profile-server, but that requires us to update to the latest hapi.

We upgraded hapi and can flip the switch if needed in the future. I checked latest Nightly and Notes login works for now 👍
