### ISSUE TITLE
[TOTP] "Confirm recovery code" modal is not displayed when generating new codes (replace)

### ISSUE THREAD

**Issue by sflorean** [mozilla/fxa#3858]
Prerequisites:
- 2FA is enabled

### Steps to reproduce
1. From 2FA section tap on "Generate recovery codes". 
2. Save the codes and tap on "Continue".

### Expected result
"Confirm recovery code" modal is displayed.

### Actual result
The modal is dismissed. 2FA section is displayed and 2FA is enabled. 

### Environment
- Mobile, Desktop
- Train 154 - stage server

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-905)
┆Issue Number: FXA-905

**Comment by sflorean** [comment]
ref #2373

**Comment by sflorean** [comment]
@clouserw this is reproducible when 2FA is enabled and we want to generate new recovery codes due to the fact that we consumed the existing ones. 
Sorry for the confusion here:  **change for step 1**: "From 2FA section tap on "Replace recovery codes". 
I will update the summary as well.

**Comment by dannycoates** [comment]
This isn't ready for implementation until the ux for when the last recovery code is used has been specified. Currently, the generate new codes flow doesn't account for when you've run out of codes. If we require new code confirmation do we block users from logging in until they do? Do we disable TOTP if they skip? idk

**Comment by dannycoates** [comment]
This will also require backend changes. The frontend code from #3748 can be reused, but the codes are replaced on the server at the same time they are shown to the user. Requiring confirmation will make this a two request process.

I think most of the value in requiring confirmation comes from the initial setup so we might want to prioritize this lower than other issues.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~rfeeley@mozilla.com] for UX guidance

**Comment by data-sync-user** [comment]
➤ Ryan Feeley commented:

We should because that “replace recovery codes” link is pretty easy to click. Does the existing confirm screen suffice?

**Comment by vasilicatamas** [comment]
@clouserw  Due to the fact that this issue is still unresolved, it is reproducible also on the New Settings page. The Recovery code confirmation screen should be also displayed when changing the codes just to be sure that they were successfully saved.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I think the existing screen will suffice.  Thanks.
