### ISSUE TITLE
revisit "Communications" category label

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#3865]
In recent UR, some participants click on Communications vs Get Help to contact Support.

How might we rework the copy here to address this confusion?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-910)
┆Issue Number: FXA-910

**Comment by MeridelW** [comment]
In reviewing possible options (Communications, Notifications, Email Preferences, Email Newsletters, Subscriptions), I think **Newsletters** is the clearest and most concise option. The user is indeed just managing email newsletters, and not general account/security notifications, from the page so "Newsletters" is accurate. It also creates clearer distinction from managing your email address in general (which is under Profile) and getting help.

**Comment by janiceahn** [comment]
Thank you for reviewing options. I'll make the change to Newsletters in the wires.
