### ISSUE TITLE
No success message is displayed if the recovery codes are downloaded/printed/copied

### ISSUE THREAD

**Issue by sflorean** [mozilla/fxa#3877]
Prerequisites:
- Login with an Fx Account.

### Steps to reproduce
1. From 2FA section tap on "Enable". 
2. Scan the QRcode and enter the security code it provides in the field.
2. Tap on Ready.
3. Copy, download, print the codes (only download on iOS).
4. Pay attention to the success messages. 

### Expected result
Green success messages are displayed for the following actions:
- download
- copy 
- print

### Actual result
Nothing is displayed. And leads to confusion if the codes were downloaded or not (example). 

### Environment
- Mobile, Desktop
- Train 154 - stage server

![20200110_171849](https://user-images.githubusercontent.com/58466444/72164043-a7845000-33cd-11ea-9732-1d6e88d5271f.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-919)
┆Issue Number: FXA-919

**Comment by sflorean** [comment]
ref #2373

**Comment by clouserw** [comment]
We think this is working as designed.  @ryanfeeley are there any adjustments you want to make to this?

**Comment by ryanfeeley** [comment]
Good eye, yes, we should show one as we do for recovery key (except Print which is confirmed when the paper comes out).
<img width="449" alt="image" src="https://user-images.githubusercontent.com/68213/72281487-b0149a80-3608-11ea-868d-c4f2d7922889.png">
