### ISSUE TITLE
Incorrect error message for empty “Recovery code” field

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3878]
**Build:**
Stage [Train 1.154.0]

**Affected platforms:**
Windows 10
Mac Os X 10.14.6
Android Q
iOS 13.1.2

**Affected versions:**
Firefox 72.0.1
Fennec 68.4.0
Firefox for iOS 21.0

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox Account.
2. Navigate to Manage account page.
3. Click on "Enable" button from 2FA section.
4. Enter the code received after the QR code was scanned and tap on "Ready".
5. At “Save recovery codes” click on "Confirm" button without entering any code.

**Expected results:**
An error message is displayed saying "Recovery code required".

 **Actual Results:**
"Invalid recovery code" error message is displayed.

![Screenshot_4](https://user-images.githubusercontent.com/18114210/72161569-098e8680-33c9-11ea-935d-25927b89046c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-920)
┆Issue Number: FXA-920

**Comment by clouserw** [comment]
We think this is working as designed.  @ryanfeeley are there changes you want to make here?

**Comment by ryanfeeley** [comment]
This comment is correct. Wrong is different than empty.
>  An error message is displayed saying "Recovery code required".

**Comment by vasilicatamas** [comment]
Confirm that "Recovery code required" message is successfully displayed for an empty "Recovery Code" field. Tested on Stage [Train 1.156.0] under Windows 10 64-bit.

![Screenshot_6](https://user-images.githubusercontent.com/18114210/73938174-65c4c780-48ef-11ea-8073-164debcff2b2.png)
