### ISSUE TITLE
"Sign in with PKCE" button does not redirect to FxA

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#388]
When I click the "Sign in with PKCE" button, I am not redirected to FxA.

Opening the browser console, a network request is made to the content-server's /authorization endpoint. The /authorization endpoint does not have CORS and the request fails.

If enabling CORS on that route, the request then fails because /authorization only returns HTML where this call expects a JSON response.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-604)
┆Issue Number: FXA-604

**Comment by clouserw** [comment]
We suspect this is a bug in 123done

**Comment by rfk** [comment]
The PKCE signin flow tries to fetch a JSON bundle of login information here:

  https://github.com/mozilla/fxa/blob/2c85d557255de034226e530c34b0c041c366d0ec/packages/123done/static/js/pkce.js#L17

But that endpoint doesn't return a JSON blob, it redirects to the FxA authentication page. So we end up trying to do a CORS read fo the FxA login page, which is not allowed.

I suspect that this endpoint *used to* function that way, but got refactored in a way that broke the PKCE button.

To repair this, I think we'll want to add a new server endpoint in `oauth.js`, (perhaps called `/api/config` or similar?) that calls the existing `setupOAuthFlow` function and just returns the resulting JSON blog of params.  We can then updat the client code linked above to call this endpoint in the place where it currently incorrectly calls `/api/login`.
