### ISSUE TITLE
possible l10n key showing up on name error tool tip

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#3881]
Note: I saw this while in storybook, but didn't see it on staging 1.154.0

!image-2020-01-10-16-28-32-765.png!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-922)
┆Issue Number: FXA-922
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/12414/image-2020-01-10-16-28-32-765.png">image-2020-01-10-16-28-32-765.png</a>

**Comment by meandavejustice** [comment]
![name-error](https://user-images.githubusercontent.com/1844554/73012545-92072100-3de4-11ea-97a6-11edf93ba2ff.png)

Not seeing this locally, it's possible its only in storybook

**Comment by lmorchard** [comment]
I haven't gotten around to looking into it further, but this might be related to #3819 - fluent seems unconfigured / broken in Storybook. We'll need to fix that in the nearish future, since we'll rely on Storybook as we develop new features and need to demo / get UX approval

**Comment by lmorchard** [comment]
I think this was fixed along with #3819
