### ISSUE TITLE
Consider indexing the root FxA page for search engines

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3884]
In https://github.com/mozilla/fxa-content-server/pull/3604, we added a `noindex,nofollow` tag to all of our pages, the reason being:

"Our page URLs might contain sensitive info like verification tokens. We want to avoid them showing up in search engine indexes, even if a user accidentally posts e.g. their account verification link into a public support website and it gets found by the googlebot."

One side effect of this is that since not even `accounts.firefox.com` is indexed, users will never be able to find us through a search engine search.

- Is it preferred that users should only get to FxA through internal links?
- Do users ever actually hit the root `accounts.firefox.com` with sensitive information, or could `noindex` be potentially removed from this page without security concerns?
- Do we want to consider any other pages/links, such as `change_password`, or **is this just opening a can of worms we want to leave closed**? While some of our URLs don't contain sensitive info and there are options to block parameters ([see first answer](https://webmasters.stackexchange.com/questions/101851/why-is-google-indexing-pages-with-utm-campaign-query-string)) from search engines, this feels... not as airtight.

FWIW, we are considering adding a "home" page to `accounts.firefox.com` at a later date.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-926)
┆Issue Number: FXA-926

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I remember running into some complications with this on screenshots.firefox.com and we ended up having to just noindex the whole thing in a hurry.  Whatever we do, let's be careful.

**Comment by rfk** [comment]
> Do users ever actually hit the root accounts.firefox.com with sensitive information
> or could noindex be potentially removed from this page without security concerns?

To which I'll add: even if they do not do so right now, are we able to ensure they won't do so in future?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
