### ISSUE TITLE
add minimum-scale=1.0 and initial-scale=1.0 to the FxA signup page [bz1599582]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3887]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1599582

Created attachment 9111737
Screenshot_20191126-091227_Firefox.jpg

Steps to reproduce: 
Install Firefox, sign out of FxA (if signed in), clear cache.
Open the following deeplink URL with Firefox set as your default browser: firefox://fxa-signin?entrypoint=fx-push-notification%26utm_source=leanplum-push-notification-test%26utm_campaign=android-push-notification-test

Expected behavior: FxA signup page resolves normally.
Actual behavior: FxA signup page resolves but is very small (screenshot attached).

Tested using: 
Device: Galaxy Note 10+
Android OS Version: 9

Note that the deeplink schema was tested and validated in this ticket:
https://bugzilla.mozilla.org/show_bug.cgi?id=1522704

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-927)
┆Issue Number: FXA-927

**Comment by vasilicatamas** [comment]
The Sign-in page is correctly opened on Fennec 68.5.0 using:
 - Google Pixel with (Android Q)
 - Samsung Galaxy Note 8 with (Android 9)
 - Moto G6 with (Android 9)

Based on the above mentioned I am marking this bug as Verified.

![Screenshot_20200218-171249](https://user-images.githubusercontent.com/18114210/74749616-17121880-5273-11ea-85ef-abb7f3374947.png)
