### ISSUE TITLE
Change the OAuth client name for Firefox Preview to be "Firefox Preview"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#3890]
The OAuth client name for Fenix is currently "Firefox Sync". This was a quick hack to make the Fenix login page say "Continue to Firefox Sync", but it has been causing confusing UX in other places such as #1531.

With the landing of #3770, the login page will now say "Continue to Firefox Sync" for any client connecting to Sync, so we can safely change that OAuth client name back to something more meaningful, such as "Firefox Preview".  This change should be made as part of whatever deployment includes #3770.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-928)
┆Issue Number: FXA-928

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

#3770 is in train 155

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm moving this to Sprint 156 because 155 is closing, but this work needs to be done when the deploy is done – it doesn't land early or ride the train.  I've put the note in the deploy doc.

**Comment by data-sync-user** [comment]
➤ John Morrison commented:

This was changed in production once v1.157.0 was live:

```

MySQL [fxa_oauth]> select hex(id), name, redirectUri from clients where id = 0xA2270F727F45F648;

+------------------+--------------+-------------------------------------------------------------+
 hex(id)  name  redirectUri +------------------+--------------+-------------------------------------------------------------+
 A2270F727F45F648  Firefox Sync  https://accounts.firefox.com/oauth/success/a2270f727f45f648 +------------------+--------------+-------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [fxa_oauth]> update clients set name = 'Firefox Preview' where id = 0xA2270F727F45F648;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1 Changed: 1 Warnings: 0

MySQL [fxa_oauth]> select hex(id), name, redirectUri from clients where id = 0xA2270F727F45F648;

+------------------+-----------------+-------------------------------------------------------------+
 hex(id)  name  redirectUri +------------------+-----------------+-------------------------------------------------------------+
 A2270F727F45F648  Firefox Preview  https://accounts.firefox.com/oauth/success/a2270f727f45f648 +------------------+-----------------+-------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [fxa_oauth]>

```
