### ISSUE TITLE
The password entry page for firefox/mozilla accounts does not allow copying on mobile, preventing password managers from working. [bz1608709]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3893]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1608709

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

Steps to reproduce:

Attempt to sign into a firefox/mozilla account on firefox mobile (android). 

Actual results:

Unlike the email sign in, you cannot hold on the entry box to paste and the keyboard is set to a no-paste mode too. This prevents password managers working.

Expected results:

I can press and hold to paste in the password.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-930)
┆Issue Number: FXA-930

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this is tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1608709
