### ISSUE TITLE
Let administrative user remove all of its previously synced devices remotely. (AKA logout & purge everything from previously synced devices) [bz1608749]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3894]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1608749

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

Steps to reproduce:

This is so lame idea, even to ask as simple as this. This is a big disappointment that Firefox lacking this extreme privacy emergency option.

But Google, Microsoft doesn't let this happen. 

Here is the full story.

I had to sync the Firefox browser into my friend's laptop in order to see a particular website that I have bookmarked in the Firefox browser. The synced everything as expected. But stupidly I forgot to clean/logout/purge everything after I repaired his laptop.

When I returned back home. I wanted to remove all that synced devices remotely like how Google allows protecting user's privacy. This option will automatically log out from recent devices which a user has logged in before.

But sadly, this option doesn't exist on Firefox.

Expected results:

Let "administrative user" (aka the real boss) who has complete authority over toward his Firefox account completely remove, delete and purge every single synced data that is on another device.

This is NOT A DRILL. 

Its a really cool, very important option to have. It can save from millions of accounts from getting hacked/stolen/seen/leaked.  

Please DO something about.

Let administrative users remove clean wipe everything remotely when he wants.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-931)
┆Issue Number: FXA-931

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1608749
