### ISSUE TITLE
Remove hover and down state for disabled buttons

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#3895]
I noticed that our disabled button style offers a hover and down state. As they don't do anything, we should stop doing this.

Instead we can change the cursor on hover to 🚫 with `cursor: not-allowed;`

![secondary-hover](https://user-images.githubusercontent.com/68213/72292485-7ac77700-361f-11ea-9b25-a801b907a6ad.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-932)
┆Issue Number: FXA-932

**Comment by farhan787** [comment]
@ryanfeeley may I fix this ?

**Comment by LZoog** [comment]
@farhan787 go ahead! :)

**Comment by farhan787** [comment]
Thanks @LZoog

**Comment by LZoog** [comment]
Hey @farhan787, we just merged your PR but it's only a partial fix. There's still a hover state on the disabled button in "secondary email" when you add another email, it darkens the background a tad. We'll need `not(.disabled)` on our hover CSS or something similar. Would you like to take a stab at that? 🙂

![disabled-hover](https://user-images.githubusercontent.com/13018240/72844906-19c52200-3c63-11ea-9541-90c53f212a4a.gif)

**Comment by farhan787** [comment]
@LZoog sure, fixing it.

**Comment by LZoog** [comment]
Patches: #3949, #3946

**Comment by farhan787** [comment]
@clouserw is there still anything needed to fix this issue ?

**Comment by LZoog** [comment]
@farhan787 There's no work remaining, it looks like you weren't assigned before your PRs were merged and we tend to leave ourselves assigned when an issue is closed so I think you were just assigned late. Feel to remove yourself if you prefer. :)

**Comment by farhan787** [comment]
> Feel to remove yourself if you prefer. :)

No, it's ok to get the assigned tag

**Comment by clouserw** [comment]
Thanks @farhan787 !
