### ISSUE TITLE
Uploading avatar console error: 'fontello' downloadable font rejected by sanitizer

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#3902]
Upon uploading an avatar, the following error message appears in the console.

```
downloadable font: rejected by sanitizer (font-family: "fontello" style:normal weight:400 stretch:100 src index:0) source: https://accounts-static.cdn.mozilla.net/fonts/icons/b9640f1b.fontello.eot?33237408
```

We only have this font-family set on `::before` psuedo-elements on elements with a class containing `icon-`, such as the `-` and `+` magnifying glasses after uploading an image. The font loads properly, else the icons would look like this:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13018240/72373570-29c28c00-36ce-11ea-8bed-88f92a961c4a.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-937)
┆Issue Number: FXA-937

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Looks like this is fixed in the new design
