### ISSUE TITLE
Cannot Reconnect to Firefox Account on Desktop after using 2FA recovery code [bz1606234]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3909]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1606234

Created attachment 9117978
error-sync-1577585667048.txt

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

Steps to reproduce:

Installed Firefox on my new Iphone XR and had to reset password because existing password did not work.  Verify security asked for authenticator, but no longer had old phone, luckily had saved recovery codes and used one to successfully login to my Firefox account on iPhone XR.

Went back to Win 10 Desktop and clicked on yellow icon on menu to reconnect account, and was prompted on webpage to "Sign in to continue to Firefox Sync" with a password prompt.  I entered new password, but got message about "incorrect password" in RED color on screen.  Attached Sync Log file.

Expected results:

Firefox Sync Login should work on Desktop Firefox, just as it does on iPhone XR and Firefox app.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-940)
┆Issue Number: FXA-940

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

I've tried to replicate this a few times and was not able to. My only other explanation at this time is that the user might have typed password incorrectly.

I'm going to pull out of sprint but keep open to see if others might experience this issue.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

tracked in bugzilla
