### ISSUE TITLE
Allow OAuth flows for Firefox iOS client ID [bz1609455]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3912]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1609455

+++ This bug was initially created as a clone of Bug #1528355 +++

We are trying to hook up Firefox iOS to our FxA rust client which uses OAuth flows.
They currently have the client id `1b1a3e44c54fbb58` but this one doesn't come with a `redirect_uri` (and I suppose some flags might have to be switched also).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-943)
┆Issue Number: FXA-943

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

doing this in bugzilla
