### ISSUE TITLE
l10n for upgradeCTA in payments server

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3923]
`upgradeCTA` is set in auth-server config, then fetched and displayed in payment server. We need to restructure this so it can be translated

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-950)
┆Issue Number: FXA-950

**Comment by lmorchard** [comment]
This should come out of Stripe metadata rather than server config. That, in turn, raises a whole issue of how should we localize stuff coming from Stripe - for which I don't think we have a particular issue

**Comment by meandavejustice** [comment]
@lmorchard we may be able to localize this the same as how we are doing errors, with a mapping between error code and our copy version of the error message

**Comment by lmorchard** [comment]
This isn't going to be a code, though - it's a per-product marketing message with HTML markup customized within Stripe by product owners

**Comment by clouserw** [comment]
It's possible we may need to use some kind of codes here and coordinate with Product/Marketing.

**Comment by lmorchard** [comment]
FWIW, I think this points at broader l10n concerns - this isn't this only field that will need localization. We'll probably want something like a full set of strings per product (e.g. name, upgrade CTA, whatever else) and localize that as a set keyed on product ID. That, or maybe we end up with different products per locale depending on pricing, etc

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

nah
