### ISSUE TITLE
firefox account was locked,and received no login email [bz1609831]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3926]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1609831

Created attachment 9121442
my account was locked

User Agent: Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
Firefox for Android

Steps to reproduce:

i've reseted my windows10, then i rebooted my computer and login my firefox account

Actual results:

sorry,we've locked your account

Expected results:

sometext llike "we've already sent you login email"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-952)
┆Issue Number: FXA-952

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

handing this in bugzilla
