### ISSUE TITLE
Implement updated subscription Confirmation UI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#3929]
Implement Subscription Page Confirmation UI improvements

See screens 8-10 [here](https://www.figma.com/file/KowVfoI16p90mURxLhh4D6/FXa-%26-Mobile-Checkout)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-956)
┆Issue Number: FXA-956

**Comment by meandavejustice** [comment]
Estimated 5, here is the breakdown:

2: need to verify that the new data is coming down (invoice number)
2: making the visual updates
1: updating tests

**Comment by meandavejustice** [comment]
Still need confirmation on the redirect from @johngruen. @LZoog had some accessibility concerns with the redirect.

**Comment by meandavejustice** [comment]
Also correct link appears to be https://www.figma.com/file/KowVfoI16p90mURxLhh4D6/Subscription-Platform?node-id=181%3A0

**Comment by meandavejustice** [comment]
### CURRENT DESIGN:
![sub-confirm-current](https://user-images.githubusercontent.com/1844554/74466797-f5292800-4e65-11ea-8e74-4fa080a7a191.png)

### FULL SIZE REDESIGN
![sub-confirm-full](https://user-images.githubusercontent.com/1844554/74466798-f5292800-4e65-11ea-8564-6bb3ea763e4e.png)

### MID SIZE REDESIGN
![sub-confirm-midsize](https://user-images.githubusercontent.com/1844554/74466800-f5292800-4e65-11ea-9c02-0f81623e739a.png)

### SMALL REDESIGN
![sub-confirm-small](https://user-images.githubusercontent.com/1844554/74466801-f5c1be80-4e65-11ea-809f-e39ff42cae41.png)

**Comment by meandavejustice** [comment]
* create confirmation info view
* update header
* add details view

breaking these out into separate issues

**Comment by data-sync-user** [comment]
➤ David Justice commented:

This is only blocked by PlanDetails pr being merged tomorrow morning and  Task FXA-1100. Should be able to start on this tomorrow afternoon. Possibly wednesday morning at the latest

**Comment by data-sync-user** [comment]
➤ David Justice commented:

This is mostly complete, Trying to fix up some remaining tests and addressing some small pr review comments. https://github.com/mozilla/fxa/pull/4423
