### ISSUE TITLE
Replace sjcl w/ node-jose

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#393]
We use node-jose within the content-server, using it here would provide a couple of advantages:

1. node-jose delegates to a browser's native WebCrypto functionality if available whereas sjcl does everything in JS. Operations done in natively by WebCrypto are ~ 2x as fast as operations done in JS.
2. We could use 1 shared copy of an underlying crypto library resulting in a smaller download.

The underlying push is we are considering [increasing the number of rounds of PBKDF2](https://bugzilla.mozilla.org/show_bug.cgi?id=1320222) run on the user's pw before sending the hash to the backend. On older mobile devices 100k rounds of PBKDF2 can take a long time using sjcl, ~8 seconds on a Moto G4 Play. Cutting that in half would make the experience a lot more acceptable.

I think all of the functionality we use in sjcl has an equivalent in node-jose:

* [sjcl.codec.hex.fromBits(bits)](https://github.com/mozilla/fxa-js-client/blob/6b7c4ca065b704763e824a1beb1cd15e85270249/client/FxAccountClient.js#L709) - I believe we could use `Buffer.from(bits).toString('hex')`
* [sjcl.codec.utf8String.toBits(string)](https://github.com/mozilla/fxa-js-client/blob/6b7c4ca065b704763e824a1beb1cd15e85270249/client/lib/credentials.js#L24) - `Buffer.from(string, 'utf8')`
* [sjcl.misc.hmac(keys.hmacKey, sjcl.hash.sha256)](https://github.com/mozilla/fxa-js-client/blob/6b7c4ca065b704763e824a1beb1cd15e85270249/client/lib/credentials.js#L115) - [jose.JWA.sign('HS256', key, msg)](https://github.com/cisco/node-jose/blob/master/test/algorithms/hmac-test.js#L42)
* [hkdf could be done by node-jose](https://github.com/cisco/node-jose/blob/master/test/algorithms/hkdf-test.js#L16)
* [sjcl.misc.pbkdf2](https://github.com/mozilla/fxa-js-client/blob/6b7c4ca065b704763e824a1beb1cd15e85270249/client/lib/pbkdf2.js#L19) by [jose.JWA.derive('PBKDF2-SHA-256', key, props)](https://github.com/cisco/node-jose/blob/master/test/algorithms/pbes2-test.js#L17)

There are a few other low level bit operations (bitSlice, xor, concat) that seem like we should be able to take care of ourselves.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-606)
┆Issue Number: FXA-606

**Comment by meandavejustice** [comment]
I'd like to prioritize this to get it out of `fxa-js-client`, it fails often in ci, I think because we are pulling from a specific commit
