### ISSUE TITLE
Implement updated subscription UI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#3930]
Implement Subscription Page UI improvements

See screens 4-7 [here](https://www.figma.com/file/KowVfoI16p90mURxLhh4D6/FXa-and-Mobile-Checkout?node-id=148%3A776) - note: need invite 

This prototype shows a [complete flow](https://cloud.protopie.io/p/134c8b0560) including the VPN and FxA components which are out of scope for this Epic.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-955)
┆Issue Number: FXA-955

**Comment by meandavejustice** [comment]
After reviewing again today in figma, looks like the main updates are just adding details section and changing header. Updates to the form and messaging beneath the form are minor. My estimate reflects this

**Comment by data-sync-user** [comment]
➤ David Justice commented:

I feel like this issue can be closed out, as we have issues for each of the things listed in the description here

**Comment by data-sync-user** [comment]
➤ David Justice commented:

all items listed are duplicates of individual issues, and we already have an epic
