### ISSUE TITLE
Migrate docs for accounts/sync protocol and token use to doc ecosystem

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#3935]
This rather important doc that describe the FxA account/sync protocol and how our session tokens work exists only in the FxA wiki and should probably be moved into the ecosystem docs:
https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-958)
┆Issue Number: FXA-958

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

done at https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-onepw-protocol
