### ISSUE TITLE
Show password "eye" in the recovery key password input field

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#3938]
From https://github.com/mozilla/fxa/pull/3903, the recovery key password field should show the "eye" toggle button that show the password in plaintext.

Ref:
![image](https://user-images.githubusercontent.com/1295288/72837927-5857de00-3c5d-11ea-9dc9-981cd0d578b6.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-960)
┆Issue Number: FXA-960

**Comment by farhan787** [comment]
@vbudhram may I implement it ?

**Comment by vbudhram** [comment]
@farhan787 Sure!

**Comment by LZoog** [comment]
Hey @farhan787, just so you know I have a PR open at the time of writing (#4100) that modifies the show PW toggle. It might be a good idea to wait until that's merged (hopefully in a day or so) so you can reference the latest. :)

**Comment by farhan787** [comment]
> It might be a good idea to wait until that's merged (hopefully in a day or so) so you can reference the latest. :)

@LZoog  sure thanks for informing me about that.

**Comment by farhan787** [comment]
@vbudhram as @LZoog mentioned about the PR in her last comment, that has fixed this issue, I think that we can now close this issue.

**Comment by LZoog** [comment]
@farhan787 I just double checked and I'm still seeing this as an issue. Here's how to see it, you likely already know how but just in case:
- `npm start`, sign up for an account, run `./pm2 logs` and scroll up to see `Signin code [######]`, use the code to verify the account
- Go to http://127.0.0.1:3030/post_verify/account_recovery/add_recovery_key, start typing, see that there is no password eye

It looks like `confirm_password.mustache` isn't using the `password-mixin`.

**Comment by farhan787** [comment]
> @farhan787 I just double checked and I'm still seeing this as an issue. Here's how to see it, you likely already know how but just in case:

I might have seen my local branch where I was fixing this, my mistake, let me take a look and then I'll fix this.

**Comment by LZoog** [comment]
Patch: #4189
