### ISSUE TITLE
Remove AMD wrappers to be more compatible with Webpack 4

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#394]
Dynamic loads with Webpack 4 for requires us to dereference [`<module_name>.default`](https://github.com/mozilla/fxa-content-server/pull/6376/files#diff-341971be75d35dbd724949cda527a0efR152) to get the actual constructor. If we ditched the AMD wrappers, we wouldn't have to do this.

Blocked by #280

**Comment by vladikoff** [comment]
@shane-tomlinson did we do this already? I converted it from AMD, not sure if we have anything remaining

**Comment by shane-tomlinson** [comment]
This can be closed!
