### ISSUE TITLE
Error: Your email was just returned. Mistyped email?

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3952]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/7071057/

This just started happening in Train 154 and is happening a few hundred times a day.

```
Error: Your email was just returned. Mistyped email?
  at string (./lib/errors.js:122:43)
  at Ne/t[n]</< (./models/auth_brokers/oauth-redirect.js:27:14)
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-970)
┆Issue Number: FXA-970

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Sentry links no longer active
