### ISSUE TITLE
Error: Error: Invalid token

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3953]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/7071043/

This started happening in Train 154 and is occuring a few hundred times a day.  The token might be invalid, but I'm not sure why we're reporting that to sentry.

```
Error: Error: Invalid token
  at fetch/< (./views/mixins/modal-panel-mixin.js:106:11)
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-969)
┆Issue Number: FXA-969

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Sentry links no longer active
