### ISSUE TITLE
GPG Key (Temporary Query)

### ISSUE THREAD

**Issue by farhan787** [mozilla/fxa#3958]
As the public IRC channel is inactive for last few months, I'm asking this query here.

My  GPG key has expired and I've added a new GPG key and all of my older commits in this fxa repo have the unverified tag now, is that a problem to consider or is it fine ? Though I've added a new GPG key to sign commits but older ones have unverified tag. @vbudhram could you please answer this ?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-972)
┆Issue Number: FXA-972

**Comment by clouserw** [comment]
Hey @farhan787 .  This is ok, as is, but I think most folks would expect you to renew the GPG key you had (set the expiration date further into the future and re-upload) which *I think* wouldn't affect this like it has.  I haven't run into this though, so, that's just a guess.  Either way, you're ok.  I'll close this and thanks for your contributions!
