### ISSUE TITLE
Filter out amplitude events from Fenix client_id

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#3968]
In our metrics processing pipeline, we currently filter out OAuth events from Desktop and Fennec before submitting the data to amplitude, because the sheer volume of events generated by those two clients would quickly exceed our data budget with amplitude. (ref e.g. [Bug 1592123](https://bugzilla.mozilla.org/show_bug.cgi?id=1592123) for more details).

When we [switch Fennec users over to Fenix](https://docs.google.com/document/d/1mh8DihcA7w0wjwSPxYAZcWVET0TGHJlYUa9esZyxh9s/) later this year, those high-volume OAuth events and going to start being associated with the Fenix client_id rather than the Fennec client_id. The volume of events will also increase, as Fenix generates *more* OAuth traffic than Fennec does.

Sometime before that migration gets under way in earnest, we should adjust the amplitude event-filtering logic to exclude events from the Fenix client_id.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-973)
┆Issue Number: FXA-973

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I should add for completeness: this will affect analysis of Fenix traffic in amplitude, particularly with respect to DAU, since oauth events will be the primary signal of ongoing user activity in Fenix. But I'm not sure there's a good way around it in the short term. We might want to prioritize something like https://bugzilla.mozilla.org/show_bug.cgi?id=1592123, ( https://bugzilla.mozilla.org/show_bug.cgi?id=1592123, ) and/or try to do some calculations and see whether we can accept some subset of events from Fenix. I'm happy to try to work through that it more detail with someone from the team.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

/cc [~loines@mozilla.com] [~adavis@mozilla.com] for visibility

**Comment by rfk** [comment]
> this will affect analysis of Fenix traffic in amplitude, particularly with respect to DAU, since oauth
> events will be the primary signal of ongoing user activity in Fenix

I'm wondering if we can keep the "oauth token created" events from Fenix and use them to measure DAU, but exclude the "oauth token verified" events which are much higher volume. The token-created events are more-or-less equivalent to the "certificate signed" events that are currently generated by Fennec, and which we'll lose as part of the migration.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~jbuckley@mozilla.com] Can you provide an estimated completion date for this effort?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

This is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1592123 I think

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Thanks jbuck, added the 'is blocked by' link to Jira to the DS bug: https://jira.mozilla.com/browse/DS-187

**Comment by data-sync-user** [comment]
➤ Leif Oines commented:

I update the bugzilla with some more info. If sampling is too hairy to figure out before fenix launch, I think Ryan's solution of selectively filtering out `fxa_activity - access_token_checked` could be a faster solution. There are still about 3 of `fxa_activity - access_token_created` events per user per day, but that shouldn't be so much as to overwhelm us.

**Comment by rfk** [comment]
I believe this has been resolved by the "daily activity summary" work in https://bugzilla.mozilla.org/show_bug.cgi?id=1632635
