### ISSUE TITLE
Log using mozlog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#397]
This repo writes directly to stderr w/o using mozlog 2.0, which is different than other fxa servers. This can cause confusion with questions like "why does this server write an object with an op whereas other repos call the log method with the op as the first argument and then an object?" Or at least, that's what I asked.

Maybe shared server side logging should be part of fxa-shared so we can reduce confusion.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-607)
┆Issue Number: FXA-607

**Comment by clouserw** [comment]
wontfix
