### ISSUE TITLE
Finalize account state before sending "account verified" push notification

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#3970]
This is a fun one, and a little hard to believe, but it's the best explanation I have for what we're seeing in [Bug 1609166](https://bugzilla.mozilla.org/show_bug.cgi?id=1609166).

When verifying a new account via email codes, we call the `/session/verify_code` endpoint, which does the following in a non-transactional manner:

1. Check that the submitted code is valid.
2. Update the db to mark the account as verified.
3. Send a push notification to tell the browser the account is verified.
4. Update the db to mark the session as verified.

If the server is slow enough and the user's network is fast enough, it's possible that their browser will receive the push notification and poll for the status of the account after step 3, but before step 4. If this happens then the browser will see an incorrect transient account state with `emailVerified=true` but `sessionVerified=false`.

Due to a related client bug, the browser will stop polling for account status updates when it receives the push notification from step 3, so it will never discover the correct account state after step 4 finishes.

We're going to fix the client behaviour to keep polling in this case, but I'd argue this is actually a server bug, and it shouldn't be telling the client any transient account states.

The classically-correct fix here would be to ensure that all db changes for a single request occur within the scope of a single transaction, but that's very difficult in our current architecture. Perhaps instead we could arrange for the push notification to only go out after all db updates have been finalized, to reduce the chance of clients reading partial states in practice.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-974)
┆Issue Number: FXA-974

**Comment by vbudhram** [comment]
@rfk Thanks for the excellent detective work! I've put together a PR in https://github.com/mozilla/fxa/pull/3972 with your recommendations since it seem pretty straight forward enough.
