### ISSUE TITLE
[auth server] [request for comments] Store More Geo Location Data in Session Token Meta Data?

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#3973]
This is kind of a follow-up to https://github.com/mozilla/fxa/issues/2677, in which we displayed the geo location data from session token meta data in Redis in the support panel.  However, that meta data is only from browser/sync sign-ins.

Should we store more geo data in our session token meta data?  How?  Simply add an entry during log in session token creation?  How much of a load increase is this for Redis?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-975)
┆Issue Number: FXA-975

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
