### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of caionavarro.n@hotmail.com [bz1611691]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#3976]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1611691

User: 
Support Case link

The user has tried the following:
*

I verified with the user that their email is indeed working but the account seems to be blocked. 

Can we investigate on our side what might be happening or to see if we can unlock the account by attached identity verification.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-976)
┆Issue Number: FXA-976

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We'll handle this in bugzilla
