### ISSUE TITLE
[Bug] 2FA security code page is not displayed after Disconnect -> log in again

### ISSUE THREAD

**Issue by sflorean** [mozilla/fxa#3977]
## Prerequisites
- Install Fenix Nightly and sign in with an account with **2FA enabled**.

## Steps to reproduce
1. Go to Settings -> Sign Out.
2. Disconnect the account.
3. Tap on "Turn on Sync" -> Use email instead.
4. Type valid credentials and tap the "Sign in" button.

### Expected behavior
"Enter security code" page is displayed and security code from the authentication app is required. 

### Actual behavior
The user is signed in.

### Note: 
"Enter security code" page is displayed when we first log in. 

### Device information
* Android device: Google Pixel (Android Q), Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.
* Fenix version: Nightly build 01/16.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-977)
┆Issue Number: FXA-977

**Comment by rfk** [comment]
> Disconnect the account.

This step is *supposed* to destroy the underlying `sessionToken`, but I bet it somehow is not. So when the user goes to sign in again, they have to re-enter their password (in order to get the sync encryption keys) but it uses the existing `sessionToken` and hence bypasses 2FA.

**Comment by rfk** [comment]
I tried this just now but wasn't able to reproduce, I get the "Enter security code" screen as expected. @sflorean does it still reproduce for you on latest Fenix Nightly?

**Comment by sflorean** [comment]
@rfk yes, this is still reproducible on the latest Nightly, sorry for the late reply here. Make sure that you are logged with the account - save credentials - disconnect - log in again -> 2fa screen is not displayed.

**Comment by vasilicatamas** [comment]
I managed to reproduce this issue on FxA Train [Stage 1.164.0] using Fenix Nightly (#20900607).

![2faissue](https://user-images.githubusercontent.com/18114210/77927182-b03f4080-72af-11ea-9ce1-a2e5b0c000e4.gif)
