### ISSUE TITLE
Better balance functional tests for content-server between parallel instances in CircleCI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3997]
Currently, we split content-server functional tests across 6 parallel VMs. This is done in a simple round-robin fashion with no regard to the performance / execution time of any given test. Might be useful to better balance their distribution between VMs with respect to those metrics

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-991)
┆Issue Number: FXA-991

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
