### ISSUE TITLE
Audit tests for duplication

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3998]
Do we still have duplicate tests anywhere? We should find them and de-dupe them. Or if we're already de-duped, just close this issue

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-998)
┆Issue Number: FXA-998

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We do have some dupes, but we don't need an issue for this.  We delete the dupes as we come across them.
