### ISSUE TITLE
Ensure sass-lint can successfully run for content-server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#4000]
We want sass-lint to run and check styles for content-server. We think that's not happening because the CSS needs to be cleaned up. 

We should make sure a) that the CSS is cleaned up so that b) sass-lint can successfully run on content-server

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-996)
┆Issue Number: FXA-996

**Comment by LZoog** [comment]
Dupe of #2088, blocked by #2239.
