### ISSUE TITLE
Loading chunk vendors failed

### ISSUE THREAD

**Issue by MrHappy** [mozilla/fxa#4005]
## Description

Loading chunk vendors~fxaClient failed. (error: http://127.0.0.1:3030/bundle/vendors~fxaClient.bundle.js)

### Steps to reproduce

Follow the documentation.

### Expected result

Register an emailaccount

### Actual result

Error - see description

### Environment

Ubuntu 18.04

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1003)
┆Issue Number: FXA-1003

**Comment by MrHappy** [comment]
The logging of the content-server gives this logging rule:
`fxa-content-server.server.routes.ERROR: validation.failed {"err":{"joi":{"isJoi":true,"name":"ValidationError","details":[{"message":"\"type\" with value \"error.enter-email.unknown namespace.ChunkLoadError: Loading chunk vendors&#x7e;fxaClient failed.&#x0a;&#x28;error: http:&#x2f;&#x2f;127.0.0.1:3030&#x2f;bundle&#x2f;vendors&#x7e;fxaClient.bundle.js&#x29;\" fails to match the required pattern: /^[\\w\\s.:-]+$/","path":["events",6,"type"],"type":"string.regex.base","context":{"pattern":{},"value":"error.enter-email.unknown namespace.ChunkLoadError: Loading chunk vendors~fxaClient failed.\n(error: http://127.0.0.1:3030/bundle/vendors~fxaClient.bundle.js)","key":"type","label":"type"}}],"_object":{"broker":"web","context":"web","deviceId":"d9580070c9654ee795bd4eedf4c72acd","duration":8159,"emailDomain":"other","entrypoint":"none","entrypoint_experiment":"none","entrypoint_variation":"none","events":[{"type":"enter-email.sync-suggest.visible","offset":931},{"type":"loaded","offset":931},{"type":"flow.enter-email.engage","offset":2300},{"type":"flow.enter-email.submit","offset":6157},{"type":"mailcheck.triggered","offset":6157},{"type":"enter-email.submit","offset":6158},{"type":"error.enter-email.unknown namespace.ChunkLoadError: Loading chunk vendors~fxaClient failed.\n(error: http://127.0.0.1:3030/bundle/vendors~fxaClient.bundle.js)","offset":6169}],"experiments":[],"flowBeginTime":1581090872446,"flowId":"348aa32b6383f77ae2fcdcf46edb406d534ee8522fbc70c108835ec8197b5e70","flushTime":1581090880483,"initialView":"enter-email","isSampledUser":true,"lang":"nl","marketing":[],"migration":"none","navigationTiming":{"navigationStart":0,"unloadEventStart":94,"unloadEventEnd":104,"redirectStart":null,"redirectEnd":null,"fetchStart":2,"domainLookupStart":2,"domainLookupEnd":2,"connectStart":2,"connectEnd":2,"secureConnectionStart":null,"requestStart":51,"responseStart":79,"responseEnd":79,"domLoading":94,"domInteractive":650,"domContentLoadedEventStart":651,"domContentLoadedEventEnd":658,"domComplete":658,"loadEventStart":658,"loadEventEnd":679},"referrer":"none","screen":{"clientHeight":938,"clientWidth":1920,"devicePixelRatio":1,"height":1080,"width":1920},"service":"none","syncEngines":[],"startTime":1581090872324,"timers":{},"uid":"none","uniqueUserId":"dd4b1c4d-845c-4299-83ee-d0754a25710e","userPreferences":{},"utm_campaign":"none","utm_content":"none","utm_medium":"none","utm_source":"none","utm_term":"none"}},"meta":{"source":"body"}},"method":"POST","path":"/metrics"}
`

**Comment by jayarc** [comment]
Same here although I think what I'm in search of may be up-to-date branches for deploying fxa in a production mode (no 127.0.0.1 references that break CSP). I see scripts in the repo for swapping the accounts.firefox.whatever/v1 maybe some comment docs in there would be helpful to future folks. I'm going ton keep working on understanding what's going on with all this, will post more here if I have useful info. So far my next steps are checking out the NODE_ENV #882 I think and how to set production mode in all the container or find a config for doing so and trying to replace select 127.0.0.1 and localhost references through trial and error. Anybody with useful information will be appreciated by myself as well. Love that this code is open.

**Comment by jayarc** [comment]
More potential clues for others trying to tweak the fxa repo to run in production may lie here in older methods:
* https://blog.mirabellette.eu/index.php?article33/i-failed-to-install-firefox-accounts-server
* https://github.com/michielbdejong/fxa-self-hosting

I'm attempting to self-host behind my own nginx-proxy-manager on a dynamic public ip.

**Comment by MrHappy** [comment]
A functional how-to would be greatly appreciated...
I've tried to get it to work for several days, but I seem to be missing some (a lot?) of configuration items to change...
And as it runs on Ubuntu without desktop I cannot install a browser on it and see what it does locally, shouldn't be necessary either...

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Made irrelevant due to Settings refresh.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Needs verification to ensure this isn't fixed with Settings refresh.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
