### ISSUE TITLE
Download button from the download email is not redirecting the user to the /download page

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4008]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button and complete the subscription process
3. Open the download email and click on the download button

#### Expected result:
- The user is redirected to the guardian /download page.

#### Actual result:
- The user is prompted to download a txt file
![image](https://user-images.githubusercontent.com/15685441/73532395-46c4c200-4425-11ea-9df5-bc1cfd85811b.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1007)
┆Issue Number: FXA-1007

**Comment by lmorchard** [comment]
This should have been fixed along with #4007 in 5b257b1996960937ce4862999d667fb66d96be30

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Th button is not redirecting the user to the download page, the anchor tag is missing the href tribute
![image](https://user-images.githubusercontent.com/15685441/73640042-3fe0be00-4676-11ea-91e4-6035278efcb2.png)

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Issue is no longer reproducing.
