### ISSUE TITLE
The ZIP code field accepts any kind of character

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4012]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button and enter a valid name, card number exp date and cvc number
3. In the ZIP code field enter 5 random characters (QWERT or !@#$%) 
4. Complete the subscription process

#### Expected result:
- An warning should be displayed that the zip code field accepts only numbers and the subscription should not be completed

#### Actual result:
- No warning is displayed, the subscription process is completed
![zipCodeValidation](https://user-images.githubusercontent.com/15685441/73540424-919c0500-4438-11ea-8b60-b05b9839fbd0.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1009)
┆Issue Number: FXA-1009

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~rfeeley@mozilla.com] – should this have an error message?  If so, what should it say?

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Issue is no longer reproducing.
