### ISSUE TITLE
The product name is not displayed correctly in the contact support form

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4024]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Open the [subscription management page](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions)
2. Click on Contact Support button
3. Click on the "What are you contacting us about?" drop down menu

#### Expected result:
- The listed products are displayed in a user friendly format i.e. Firefox Guardian

#### Actual result:
- The displayed product is "guardian_monthly"
![image](https://user-images.githubusercontent.com/15685441/73641510-cbf3e500-4678-11ea-8d57-a0db6ed1ca12.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1016)
┆Issue Number: FXA-1016

**Comment by bsurd** [comment]
This issue is also encountered when submitting a support ticket.

![image](https://user-images.githubusercontent.com/17178945/73651374-fa7bbb00-468c-11ea-95cc-b168b9ecaabc.png)

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Issue is no longer reproducing.

![image](https://user-images.githubusercontent.com/15685441/74040198-e658f600-49cb-11ea-9982-5cccb5c39d63.png)
![image](https://user-images.githubusercontent.com/15685441/74040218-f07af480-49cb-11ea-854b-b3c5e326d4c0.png)
