### ISSUE TITLE
The type of currency is not mentioned in the payment page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4025]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Ubuntu 19.04 (x64)
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscriptions

#### Steps to reproduce
1. Open the [VPN page](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button, sign in and observe the UI of the payment page.

#### Expected result:
- The subscription page is displayed without any issues.

#### Actual result:
- In the payment section, it says "Firefox Guardian for 9.99 per month" but it does not state in what currency the payment will be made. To avoid any kind of confusion the type of currency should be stated as well, either by using the appropriate currency symbol or in plain text.

#### Notes:
- The same should be applied for the confirmation message next to the right of the checkbox.

![Screenshot from 2020-02-03 11-29-09](https://user-images.githubusercontent.com/17178945/73641423-a8c93580-4678-11ea-82b6-44c480d1fb09.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1018)
┆Issue Number: FXA-1018

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We're thinking this might be a regression with the L10n patches Dave was working on

**Comment by bsurd** [comment]
This issue is no longer reproducible, the currency is now displayed.
