### ISSUE TITLE
Product name not correctly formatted in the resubscribe window

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4026]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Open the [subscription management page](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions) and cancel the subscription
2. Click the Resubscribe button

#### Expected result:
- The resubscribe pop-up is displayed having no format or display issues.

#### Actual result:
The pop-up is displayed having the following title:  "Want to keep using ⁨{$productName}⁩?"
![image](https://user-images.githubusercontent.com/15685441/73643043-7240ea00-467b-11ea-9fc8-732c0e0b57bc.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1019)
┆Issue Number: FXA-1019

**Comment by madalincm** [comment]
We have re-verified the issue in stage and is still reproducing. 
![image](https://user-images.githubusercontent.com/15685441/74047634-5de15200-49d9-11ea-8ce9-136f278bc454.png)

We have tried to test the issue in -dev but we are hitting an error that is blocking us from logging in(https://github.com/mozilla/fxa/issues/4080).
After discussing with Wil via email we have decided to reopen this bug.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for reopening this – sorry for the confusion.  Looks like the Payments server is not updated yet according to https://bugzilla.mozilla.org/show_bug.cgi?id=1613837#c1 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1613837#c1 ) .  I'm going to reclose this.

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Issue is no longer reproducing.
![image](https://user-images.githubusercontent.com/15685441/74150669-13e3b080-4c13-11ea-8538-28e66888cf23.png)
