### ISSUE TITLE
Confirmation link is sent instead of code when adding a Secondary Email from Manage account page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4027]
**Note:**
This is a follow-up issue for: #3531

**Build:**
Prod [Train 1.155.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Launch Firefox and login using a FxA.
2. Go to https://accounts.stage.mozaws.net/settings -> Secondary Email section.
3. Add a secondary email.
4. Go to the email inbox belonging to the secondary email and check for the confirmation email.

**Expected results:**
“Confirm secondary email” contains verification code.

 **Actual Results:**
“Confirm secondary email” contains verification link.
![Screenshot_22](https://user-images.githubusercontent.com/18114210/73645166-74a54300-467f-11ea-91df-5d78be77011e.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1020)
┆Issue Number: FXA-1020

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

No longer an issue due to Settings refresh.
