### ISSUE TITLE
Legal docs are out of date again

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4031]
[https://accounts.firefox.com/__version__](https://accounts.firefox.com/__version__) says the legal docs are `c99707983486f30fb4d1cbe10ea9d221fed28da1` which is a commit from last October.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1023)
┆Issue Number: FXA-1023

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The CircleCI logs might have some hints about why this isn't pulling a newer version.

**Comment by jrgm** [comment]
I had a look at circle logs, but it didn't show me a problem. But I pulled the image, and poked around. 

I think the issue may be this:
- package.json wants master - https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/package.json#L95
- but package-lock.json pins to #c99707... - https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/package-lock.json#L8319-L8322

Also, from within the container of mozilla/fxa-content-server:latest, I get: 
```
~ $ npm ls --depth 0 2>&1 | grep legal
+-- UNMET DEPENDENCY legal-docs@git://github.com/mozilla/legal-docs.git#c99707983486f30fb4d1cbe10ea9d221fed28da1
npm ERR! missing: legal-docs@git://github.com/mozilla/legal-docs.git#master, required by fxa-content-server@1.155.0
~ $ 
```
The module though does exist in the container under /app/node_modules.

**Comment by data-sync-user** [comment]
➤ John Morrison commented:

I did the bump to get it back to master of this content repo in https://github.com/mozilla/fxa/pull/4034 ( https://github.com/mozilla/fxa/pull/4034 )

But needs a way to keep that version being bumped regularly to really fix this.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for John for fixing this in the short term, I'm kicking it out of the sprint.  The legal docs don't change very often and his explanation makes sense.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This was resolved in a recent PR.
