### ISSUE TITLE
Get packages/fxa-auth-server/scripts/delete-account.js working again

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#4032]
Ops needs to use this script to delete user accounts every so often. While using it today I ran into the following problem:

```
$ node delete-account.js jbuckley@mozilla.com
{"Timestamp":1580764691800000000,"Logger":"fxa-auth-server","Type":"uncaughtException","Severity":0,"Pid":41,"EnvVersion":"2.0","Fields":{"error":"TypeError: require(...) is not a function","stack":"\n    at Object.<anonymous> (/app/scripts/delete-account.js:28:47)\n    at Module._compile (internal/modules/cjs/loader.js:959:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n    at Module.load (internal/modules/cjs/loader.js:815:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)\n    at internal/main/run_main_module.js:17:11"}}
```

I was able to fix this by changing line 28 to: `const subhub = require('../lib/subhub/client').client(log, config, {timing: () => {}, close: () => {}});`

However, once I ran this this script it only deleted some of the users account: `ERROR: Cannot read property 'removeUser' of undefined`

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1024)
┆Issue Number: FXA-1024

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

https://github.com/mozilla/fxa/pull/4198
