### ISSUE TITLE
Security code error is not displayed

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4038]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- MacOS 10.14.6
- Ubuntu 19.04 (x64)
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using the following Card number: 4000-0000-0000-0101.
3. Click on the Subscribe button.

#### Expected result:
- An error message is displayed with "Subscription failed" as title with "Your card's security code is incorrect" message under the title.
- No payment is made.

#### Actual result:
- No error message is displayed.
- The card number is accepted.

#### Notes:
https://stripe.com/docs/testing

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1026)
┆Issue Number: FXA-1026
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/12452/Capture.PNG">Capture.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/12454/Capture-2.PNG">Capture-2.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/12455/Capture-3.PNG">Capture-3.PNG</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We're unsure if this is in the front-end error showing code, or the stripe error messages.  Les is going to investigate.  Thanks Les.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Doesn't look like a front-end issue. The test card ( https://stripe.com/docs/testing ) in the issue should intentionally trigger a CVC rejection - but, no error comes back from the server (i.e. the POST to `subscriptions/active`):

!Capture.PNG!

If I use the card `4000 0000 0000 0002` to trigger a card_declined error, I do see an error message in the front-end. It's an internal server error, which is also not quite right, but the front-end is at least displaying that error:

!Capture.PNG!

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think I fixed the internal server error in this PR - https://github.com/mozilla/fxa/pull/4047 ( https://github.com/mozilla/fxa/pull/4047 )

But, I can't reproduce the lack of error while using the invalid CVC test card. That is, on my local machine, I do get the expected error while using my personal Stripe account. And, I think we changed the display of this error from a full-screen dialog down to a red message at the top of the form. But you can see the invalid CVC error message, as well as how it appears in the web console:

!Capture-3.PNG!

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

So, tl;dr:

  * I found what looks like a bug in reporting card errors, filed a PR.
  * But, on my personal dev machine, I am seeing the expected error.
  * On stage, we're not seeing the CVC error happen at all on the backend.

Not sure if there's a difference in processing rules between the Stripe accounts?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

From slack convo, looks like CVC verification rule was not enabled. We did that, so I'll call this issue done.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Our stage was missing a radar rule to check these, I've brought all radar rules into alignment with prod now. This should be fixed.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [Guardian-stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release (72.0.2). Verified on Windows 10 x64.
