### ISSUE TITLE
The UI is not properly displayed in the tier upgrade page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4049]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Ubuntu 19.04 (x64)
- Windows 10 (x64)

#### Preconditions
- Have a FxA account with a tier 1 subscription made on 123done.

#### Steps to reproduce
1. Open the [123done](https://123done-stage.dev.lcip.org/) page and sign into your account.
2. Upgrade to a tier 2 subscription.
3. Observe the UI.

#### Expected result:
- There are no issues displayed.

#### Actual result:
- The upgrade arrow is not aligned properly.
- There should be a space between the **Card Ending 4242** and **Expires** text.
- There is a comma (,) displayed in the year. 
- The checkbox and text are not properly aligned.

![image](https://user-images.githubusercontent.com/17178945/73831102-6df90600-480e-11ea-9e12-59d9d7e920e4.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1032)
┆Issue Number: FXA-1032

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We're going to close this in favor of the work in FXA-914
