### ISSUE TITLE
Avatar display does not work

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#405]
With my fxa-setup via docker the display of the avatar does not work. The image is uploaded but not displayed. Everything else works fine. Does anyone have a tip for me where it's stuck?

The whole thing is based on https://github.com/michielbdejong/fxa-self-hosting.

My Docker start script:
https://pastebin.com/J8m7KgCM

My nginx.conf:
https://pastebin.com/HWv6zEix

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-611)
┆Issue Number: FXA-611

**Comment by misterhsp** [comment]
No one has an idea?

...

**Comment by shane-tomlinson** [comment]
Unfortunately not.
