### ISSUE TITLE
Intermittent: Diners Club cards are accepted/declined at random

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4050]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- MacOS 10.14.6
- Ubuntu 19.04 (x64)
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using the following Card number: 3056-930902-5904 or 3852-000002-3237.
3. Click on the Subscribe button.

#### Expected result:
- An error message is displayed telling the user that the card type cannot be used.
- No payment is made.

#### Actual result:
- Sometimes the card numbers are accepted.

#### Notes:
- This happens while making a new subscription or updating the payment for an existing one.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1033)
┆Issue Number: FXA-1033

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We were unable to reproduce this from the US.  Are there any additional steps you can add to narrow this down? 

[~rbillings@mozilla.com] - can you try to reproduce this?

To be clear:  We accept Diners Club cards and they should not be declined.

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

I was able to successfully sign up for a subscription on stage using two different Diners club test numbers: 

36227206271667 & 3056930009020004

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

I was not able to use the card numbers mentioned above- I got mine from https://stripe.com/docs/testing ( https://stripe.com/docs/testing )

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release. Tested on iOS 13.3.1 (iPhone 6S).
