### ISSUE TITLE
Error: A usable image was not found

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#4053]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/7071378/

```
Error: A usable image was not found
  at _normalizeError (./views/base.js:821:17)
  at displayError (./views/base.js:78:14)
  at displayStatusMessages (./views/base.js:448:12)
  at showChildView/< (./views/reset_password.js:56:40)
...
(1 additional frame(s) were not displayed)
```

This is happening about 30 times per day, but it's just someone uploading a broken image, we think.  There is no reason to report this to sentry -- lets stop.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1038)
┆Issue Number: FXA-1038

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

No longer an issue due to Settings refresh.
