### ISSUE TITLE
Error: submit already in progress

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#4054]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/7071056/

```
Error: submit already in progress
  at t.default/</< (./views/decorators/allow_only_one_submit.js:18:19)
```

This doesn't seem like something we need to report to Sentry.  Let's not report this error.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1037)
┆Issue Number: FXA-1037

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

No longer an issue due to Settings refresh.
