### ISSUE TITLE
Error: You've tried too many times. Try again later.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#4055]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/7071074/

```
Error: You've tried too many times. Try again later.
  at toError (./lib/errors.js:122:43)
  at Ne/t[n]</< (./models/reliers/oauth.js:28:15)
```

At first glance, this doesn't seem like something we need to pay much attention to, but it's weird that it only started showing up in Train 154.  Did we change a limit there?  It's happening ~20 times per day ever since we did that push.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1036)
┆Issue Number: FXA-1036

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We actually got quite a few of these "odd" errors showing up after Train 154.  Maybe we enabled some reporting for uncaught errors or something?  If that's the case, we can probably just close this.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closing this for now
