### ISSUE TITLE
Firefox account locked when I went to sign in to sync [bz1613567]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4061]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1613567

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0

Steps to reproduce:

I went to sign in to sync my account on my desktop computer Win 10 , but after entering my username/password, it said it sent an email to my email address & it was returned so it locked my Firefox account.  I clicked the link below that said if I need help but it just takes me to a support page, no contact link, contact us link just takes me around in circles, doesn't ever give me an email address or anyone to contact.  Keeps me going around in circles.  So I have no way to get my Firefox account unlocked now.  Please help & unlock my account!!!

Actual results:

 I can't get into my Firefox account to sync since its now locked.  I signed in as usual but it said it sent an email & it was returned so it locked my account.  I have the same email address & has been working fine.  So I don't know why it was returned & now my account is locked.  & have no clue how to get a hold of someone/email address, etc. to get it unlocked.

Expected results:

I should have been able to log into my FireFox account so I could sync.  I guess it sends an email to me to click on so it knows I'm trying to log in.  But for some reason the email was blocked or returned or something, so it locked my Firefox account.  & the links that are there to help you just keep taking you around in circles, it doesn't give you an email address or anyone to contact for help.  So I've been locked out of my Firefox account for over a week or more.  & have no way to know who to get a hold of for help to get it unlocked.  Getting really frustrated with Firefox & not getting any help & going around in circles when something happens.  Plz help & unlock my Firefox account.  Thanks!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1042)
┆Issue Number: FXA-1042

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

handling this on bugzilla
