### ISSUE TITLE
Discuss: Provide a way to return secondary emails when request profile information

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#407]
This was requested by Monitor. A request for profile information only returns the user's primary email. Monitor would like to get access to all of the user's emails at once.

Since secondary emails are pitched as an address to send security notices, they might not expect that info to be provided to reliers. If we do provide a way to surface this info, maybe it should require a separate scope.

ref https://github.com/mozilla/fxa-content-server/issues/6748

cc @groovecoder

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-613)
┆Issue Number: FXA-613

**Comment by groovecoder** [comment]
For what it's worth, our request is lower priority now. We are currently building multiple email address support on the Monitor side.
