### ISSUE TITLE
Profile server should only return active subscriptions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4072]
The profile server uses a function from auth-server to retrieve all subscriptions. The direct stripe implementation does not implement any filtering for only active subscriptions though, and it should.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1045)
┆Issue Number: FXA-1045

**Comment by bbangert** [comment]
Closed by #4070
