### ISSUE TITLE
Download button does not have a href attribute in the daily product download email

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4075]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account

#### Steps to reproduce
1. Go to 123done  and create a daily subscription (using prod_FUUNYnlDso7FeB)
2. Go to the download email and try to use the download button.

#### Expected result:
- The user is redirected to a download page.

#### Actual result:
- The button is not redirecting the user to the download page, the anchor tag is missing the href attribute.

#### Notes
This is only reproducing for the daily product.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1047)
┆Issue Number: FXA-1047

**Comment by lmorchard** [comment]
If this is only happening for one product, we might be missing the link in Stripe metadata.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Yes, that's what happened in https://jira.mozilla.com/browse/FXA-858 .  [~bbangert@mozilla.com] - please check/sync the stripe metadata

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I've updated the metadata in Stripe to match production. It may take up to 5 minutes for the change to appear.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks.  Closing this for verification.

**Comment by madalincm** [comment]
The download button now triggers a download:
![image](https://user-images.githubusercontent.com/15685441/74152040-227f9700-4c16-11ea-911d-5ec0cc15b505.png)

The "No thanks, just take me to my product" link from the survey at the end of the subscription process is linking to https://mozilla.org/

Should we have the same link in the download mail?

**Comment by clouserw** [comment]
@johngruen to comment on any email changes
