### ISSUE TITLE
Incorrect card error message

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4077]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using the following Card number: 4000-0000-0000-0002.
3. Click on the Subscribe button.

#### Expected result:
- An error message is displayed with "Card declined" as title with "Your card was declined." message under the title.
- No payment is made.

#### Actual result:
- An "Something went wrong. Please try again later." message appears.

#### Notes:
- It's the same result with the following card numbers: 
4000-0000-0000-0127
4000-0000-0000-9979
4000-0000-0000-9987
4000-0000-0000-9995
4000-0000-0000-0101

![Screenshot (98)](https://user-images.githubusercontent.com/48829350/74032771-7774a080-49bd-11ea-9b0a-a4c8ca034588.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1049)
┆Issue Number: FXA-1049

**Comment by lmorchard** [comment]
I went through all the cards mentioned in the issue, and I think *this* is the correct message:

> Your transaction could not be processed. Please verify your credit card information and try again.

Found a small bug preventing this message, so I should have a PR to fix soon.

**Comment by SoftVision-LorandJanos** [comment]
I still get the "Something went wrong. Please try again later." error message using those card numbers.

**Comment by lmorchard** [comment]
The fix for this issue isn't a part of a deployed release yet. I think it goes out next week

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [FPN-stage(https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release (73.0). Verified on Windows 10 x64
![Screenshot_2020-02-17 Firefox Accounts](https://user-images.githubusercontent.com/48829350/74637380-92d86c00-5172-11ea-8157-5a8babd932d3.png)
.
