### ISSUE TITLE
Unexpected error displayed when trying to log in to fxa dev

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4080]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Steps to reproduce
1. Access FxA -dev:  https://latest.dev.lcip.org/
2. Enter a valid email address in the email field and click the Continue button

#### Expected result:
Log in/Sign up process starts

#### Actual result:
"Unexpected error" message is displayed
![image](https://user-images.githubusercontent.com/15685441/74047482-15c22f80-49d9-11ea-886e-f1fa1f68bfc9.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1050)
┆Issue Number: FXA-1050

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~mcotetiu@mozilla.com] I just tried this in our triage this morning and I couldn't reproduce it.  Could you try again?  -dev picked up new builds 2 days ago so it might have fixed itself.

**Comment by madalincm** [comment]
I was able to complete both a sign in and a sign up flow on dev. 
I am closing this issue and marking it as verified fixed.
