### ISSUE TITLE
Typo in download email of the monthly product

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4085]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Crete a monthly guradian subscription
2. Open the download email

#### Expected result:
- There is no underscore in the product name

#### Actual result:
The product name is displayed as "Guardian_Monthly (Monthly)"

![image](https://user-images.githubusercontent.com/15685441/74150961-c61b7800-4c13-11ea-9b1e-21a3f9e09a13.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1058)
┆Issue Number: FXA-1058

**Comment by stlhood** [comment]
This is specific to the testing environment and does not need to be fixed. In the future we are going to migrate our email to a new implementation where test and production are always in sync.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I think this is meta data?  /cc [~bbangert@mozilla.com] since you can see it

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for the clarification.  Closing this
