### ISSUE TITLE
Creating account with a mailbox "in validation" lock the account and no way to unlock it later. [bz1613401]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4094]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1613401

Created attachment 9124504
IMG_20200205_121426.jpg

User Agent: Mozilla/5.0 (Android 7.1.2; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

Steps to reproduce:

Create an email account (tutanota - 48h validating new account)
Before 48h validating : create account Firefox via synch without am having access of the mailbox at the time.

david.mabileau@tutanota.com

Actual results:

Email verification throw back from tutanota servers
Firefox account locked for security reason
More than 48h later : can't get a new email verification
Can't unlock account

Expected results:

Being able to send a new email verification after 48h + checking "not a robot" or something like that ?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1064)
┆Issue Number: FXA-1064

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll address in bugzilla
