### ISSUE TITLE
Coordinate update of Fenix link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#4101]
Currently **Get app** links to: https://play.google.com/store/apps/details?id=org.mozilla.fenix

When Fenix swaps with Fennec it should link to: https://play.google.com/store/apps/details?id=org.mozilla.firefox

I have no idea how to coordinate the timing of this with our trains.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/68213/74256360-3a602500-4cc1-11ea-92a7-fb09336ad85a.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1067)
┆Issue Number: FXA-1067

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's target April 6th launch for this.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Putting this in the backlog until we know more about a release date.

**Comment by rfk** [comment]
Unrelated to the change in release dates, there's also some talk of "rebranding" that may happen as part of the beta rollout, which will probably relate to this issue.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Already fixed.
