### ISSUE TITLE
Getting error on setting up project

### ISSUE THREAD

**Issue by aryamanpuri** [mozilla/fxa#4102]
I followed the steps to get started in building the project
On npm start :
`script not found : /home/aryaman/fxa/packages/fxa-content-server/node_modules/.bin/grunt`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1068)
┆Issue Number: FXA-1068

**Comment by aryamanpuri** [comment]
@vbudhram

**Comment by LZoog** [comment]
Hi @aryamanpuri,

As a sanity check, will you run `node --version` to make sure you're not on an old Node version (we're using 12), and try re-running `npm i` at the root-level of the projecft? I checked my local `node_modules` directory in `fxa-content-server` and see the file it's asking for so I think successfully running `npm i` should fix this problem.

**Comment by aryamanpuri** [comment]
Hi @LZoog  
My current node version : `v12.13.1`

Done with this too 
> try re-running `npm i` at the root-level of the project?

**Comment by LZoog** [comment]
@aryamanpuri ah sorry, I actually checked `grunt/bin` instead of `./bin/grunt`. The file it's asking for here is related to [grunt-cli](https://github.com/gruntjs/grunt-cli) which we've got listed under [dependencies](https://github.com/mozilla/fxa#dependencies). Do you have that installed (`npm i -g grunt-cli`)?

**Comment by aryamanpuri** [comment]
Actually it is installed 
`grunt-cli v1.3.2
`

**Comment by aryamanpuri** [comment]
I have done `npm install` in fxa and fxa-content-server as directed by @LZoog and @vbudhram , but it is not opening the server.
![Screenshot from 2020-02-18 14-20-38](https://user-images.githubusercontent.com/43513114/74719353-dce84d00-5259-11ea-8cf4-2a5b1d134d1d.png)

**Comment by LZoog** [comment]
Hey @aryamanpuri, thanks for circling back. Are you still seeing the `script not found` error? Do you have Docker desktop running? There's a few different things we can check...

For a quicker response and easier back-and-forth, you can try popping into our IRC: https://chat.mozilla.org/#/room/#fxa:mozilla.org

**Comment by vladikoff** [comment]
> but it is not opening the server.

@aryamanpuri Are you trying to open http://127.0.0.1:3030/signin in your web browser?

**Comment by aryamanpuri** [comment]
Yes

**Comment by jodyheavener** [comment]
Thanks for filing this issue. As it's been more than a year without an update I'm going to close. If this continues to be an issue please re-open. You can reach us in Matrix under [#fxa](https://chat.mozilla.org/#/room/#fxa:mozilla.org)
