### ISSUE TITLE
Add a `pairing` option for the `connect_device_flow` amplitude user property

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#4103]
Right now when a user visits firefox.com/pair they see this view:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/5625313/74267332-1d2c5600-4cc3-11ea-9dba-1120ac0f750c.png">

Which triggers the amplitude event `fxa_connect_device - view` with event property `connect_device_flow` = `sms`. The event property value is incorrect, we should implement a new value `pairing` so that (1) we can know how many users visit the pairing page and (2) we stop mixing the pairing metrics with the SMS CAD metrics. 

CC @davismtl this is now preventing us from measuring pairing properly.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1069)
┆Issue Number: FXA-1069

**Comment by davismtl** [comment]
Thanks Leif. Good catch.

We should certainly fix this so we can understand usage of device pairing as we roll out Fenix.

**Comment by chenba** [comment]
@irrationalagent @davismtl I cannot reproduce this.  When I visit `/pair`, no amplitude event is logged.  I do see the event reported when I go to `/sms`.

It appears to me that there is no misreporting, but rather an event is completely missing.

**Comment by chenba** [comment]
My patch will add `fxa_connect_device - view` on page view and `fxa_connect_device - submit` on "Show code" button click, with the event property "connect_device_flow" set to "pairing".

@irrationalagent Let me know if you want it differently.

**Comment by data-sync-user** [comment]
➤ Leif Oines commented:

That works for me. There may be more metrics work to do on the pairing flow (e.g. adding a success event as mentioned in the PR) but i will file the required bugs for that separately.
