### ISSUE TITLE
Login Firefox Sync / Loading chunk 26 failed [bz1614784]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4104]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1614784

I am trying to log in to Firefox Sync.
As soon as I enter and confirm my email address, I receive the following message:

Loading chunk 26 failed. (missing: https://accounts-static.cdn.mozilla.net/bundle-6dde71a150fecb9c660f03a0db33014378442bab/vendors~fxaClient.bundle.js)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1070)
┆Issue Number: FXA-1070

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Possibly related to FXA-1003

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Closing as this was closed in Bugzilla.
