### ISSUE TITLE
[release] Remove "Marked QA+" Section from Output

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#4106]
The release script generates some content for the deploy bug in Bugzilla.  It has a section for links to QA+ issues.  However, since we do not use milestones in Github anymore, these links are useless.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1071)
┆Issue Number: FXA-1071

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's start using `needs:qa`.  I'll update the script.

**Comment by clouserw** [comment]
Closed in #4389
