### ISSUE TITLE
[release] Remove Two Email Addresses from New Deploy Bug Link

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#4107]
The release script creates a URL for creating a deploy bug.  We should remove two email addresses from it.

```edit:  <removing email addresses>```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1072)
┆Issue Number: FXA-1072

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closed in https://github.com/mozilla/fxa-private/pull/101
