### ISSUE TITLE
The Subscribe Now button is not replaced with a Download Now button after making a subscription

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4109]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Steps to reproduce
1. Go to the [Full-Device VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page.
2. Click on **Subscribe Now** button and sign in with or create an account.
3. Fill in all of your billing information and click on **Submit**.
4. In the next screen don't click on the **No thanks, just take me to my product.** hyperlink.
5. Go back on the [Full-Device VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page and observe the UI.

#### Expected result:
The **Subscribe Now** button is replaced with a **Download Now** button.

#### Actual result:
The **Subscribe Now** button is still displayed.

#### Notes:
The subscription appears in your FxA account page and the payment and download emails are sent.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1073)
┆Issue Number: FXA-1073

**Comment by johngruen** [comment]
I can't transfer the issue via GH b/c the repo is in a different org, but i recreated this issue here:
https://github.com/mozilla-services/guardian-website/issues/662
