### ISSUE TITLE
Terms and cancellation policy link from the download email redirects to a page that does not exist

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4110]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account

#### Steps to reproduce
1. Create a subscription
2. Open the download email and click the "Terms and cancellation policy"

#### Expected result:
User is redirected to an existing page

#### Actual result:
The link redirects to https://accounts.stage.mozaws.net/legal/subscription_terms which throws a 404
![image](https://user-images.githubusercontent.com/15685441/74347571-f56be980-4db9-11ea-8a6b-831db4b16064.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1074)
┆Issue Number: FXA-1074

**Comment by rlr** [comment]
Should that link to https://www.mozilla.org/about/legal/terms/firefox-private-network/ instead?

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

As far as I can tell the default config value for this URL is correct...not sure why the weird URL is showing up in staging?

For reference, the correct value can be found here: https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/config/index.js#L286

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Yes, Per Ricky's comment, that's the correct URL, it's also the one we have in our config.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

[~wclouser@mozilla.com]setting this to high priority b/c legal links really should be working correctly.

**Comment by jrgm** [comment]
Should that be the URL for both prod and stage. (Going to assume yes, and make that change).

**Comment by jrgm** [comment]
Or, hmm. The `about/legal/terms/firefox-private-network/` link is product specific. Anyways, I'll put up a PR to use that and we can go from there.

**Comment by jrgm** [comment]
PR ready - https://github.com/mozilla-services/cloudops-deployment/pull/3659 - if that's the right URL to use.

**Comment by madalincm** [comment]
Issue no longer reproducing in stage. Marking as verified fixed.
