### ISSUE TITLE
adding containers to sync causes sign-out, weird fxa sign-in behavior

### ISSUE THREAD

**Issue by djmitche** [mozilla/fxa#4111]
## Description

I just clicked the button to add containers to sync, and it seems to have created a new fx account and signed me out of everything.  "New" in the sense that once I entered my (existing) password and MFA code, it invited me to set up my account on another device, yet I already have a bunch of devices in my account.  And I seem to be logged out of Mozilla SSO and Heroku at least (neither of which I use a container for)

### Steps to reproduce

Unclear

### Expected result

* "Sign in" should acknowledge that I already have an account, not send me through the "great, welcome to your new account" flow
* Signing in should not sign me out of other services

### Environment

Firefox 72 on Linux

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1075)
┆Issue Number: FXA-1075

**Comment by clouserw** [comment]
Can you be specific about which button you clicked to add containers to sync?  I'm on linux with some containers, I'm willing to click it and try to reproduce.

**Comment by djmitche** [comment]
There was a "gift" icon over the containers button on the toolbar, and I clicked that and got a doorhanger inviting me to sign in to sync so my containers would sync between devices.  So I clicked that.

**Comment by rfk** [comment]
@djmitche is this specifically with the multi-account containers addon? https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by djmitche** [comment]
yes

**Comment by rfk** [comment]
Thanks. Could you also confirm whether or not you were already signed in to Sync in this browser? (You mention already having an account, but was it specifically signed in already at this time?)

I had a quick chat about this in #containers on slack, and what I think is happening here is:

* The new M-A-C addon includes a call-to-action to sign in to sync. The addon cannot tell whether you're already signed in to Sync or not, so it unconditionally directs users to the FxA login page.
* The FxA login page will always prompt the user to log in, even if they're already signed in to the browser. There may be an old bug on file for this, but IIRC the logic is essentially "well if the browser didn't want the user to sign in again, why did it load the login page?".
* After signing in to Firefox, FxA will always show the "connect another device" screen, regardless of how many devices you already have. This is related to e.g. (Bug 1604293)[https://bugzilla.mozilla.org/show_bug.cgi?id=1604293] and its friends about confusion in this flow.

>  And I seem to be logged out of Mozilla SSO and Heroku at least (neither of which I use a container for)

This, I can't explain, I don't have any theory about why an FxA signin flow could cause that even hypothetically. I wonder if this is either an unrelated bug in the containers code somewhere, or an unlucky coincidence with session timeouts.

**Comment by djmitche** [comment]
I'm not sure if I was signed in.  I hadn't specifically signed out, and I just added something to pocket yesterday -- which usually prompts me to sign in if I'm not already signed in.

The logouts may have been unrelated.  I feel like my job title should be "MFA code typist' sometimes, and there are "peak" and "quiet" days for that.  Today was a peak day, but perhaps not because of this issue.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Based on Ryan's comment above I don't think there is work for the FxA team here.  [~rkelly@mozilla.com] - should we file this elsewhere for the containers team (or is there a duplicate already filed)?  Thanks

**Comment by rfk** [comment]
> I don't think there is work for the FxA team here.  

That sounds right to me. If there's work here, it's on the sync-and-accounts-client-integrations team to provide richer APIs for WebExtensions so that they can better manage the sync sign-in call-to-action.

**Comment by rfk** [comment]
I've filed https://github.com/mozilla/multi-account-containers/issues/1649 specifically about the behaviour of the addon in this case.

Mark pointed out that we also have a related FxA issue in https://github.com/mozilla/fxa/issues/3906, which is about trying to do something more sensible if the user does find themselves signing back in to sync on a device where they're already connected.

I'm going to go ahead and close this issue in favour of those.
