### ISSUE TITLE
CAD SMS messages not being delivered to Telus subsidiaries

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#4113]
@mhoye reported that his phone (on Public Mobile, a Telus subsidiary) wasn't receiving the CAD SMS from https://accounts.firefox.com/sms/ . I tested using my phone number (on Koodo, another Telus subsidiary) and I also did not receive the CAD SMS. Becca G in the office was able to receive the CAD SMS (on Rogers)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1077)
┆Issue Number: FXA-1077

**Comment by jbuck** [comment]
@vladikoff was able to have it work with his Freedom Mobile phone

**Comment by davismtl** [comment]
I had no trouble with Fido, which is Rogers.

**Comment by jbuck** [comment]
This is working with my Koodo phone number now ¯\\_(ツ)_/¯
