### ISSUE TITLE
Requesting Analytics for Multi Account Containers Sync Campaign [bz1615094]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4133]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1615094

We added utm data to our "sign in to sync" links:

Blog post: https://accounts.firefox.com/?service=sync&utm_source=blog.mozilla.org&utm_medium=referral&utm_campaign=container-sync

Addon: https://accounts.firefox.com/?service=sync&action=email&context=fx_desktop_v3&entrypoint=multi-account-containers&utm_source=addon&utm_medium=panel&utm_campaign=container-sync

Please let me know what this looks like when you've got some data. Thanks

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1096)
┆Issue Number: FXA-1096

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll do this in bugzilla
