### ISSUE TITLE
What value should be used in the verified event for account creation time?

### ISSUE THREAD

**Issue by pmac** [mozilla/fxa#4138]
In https://github.com/mozmeao/basket/issues/76 we added support for a timestamp value in the `createDate` field of the verified event data. We use this to populate data on our end for when the account was created. It does not appear to be sent any longer. So my question is whether there is another field in the data that we should use for account creation date, or whether `createDate` could be added back to the event?

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1098)
┆Issue Number: FXA-1098

**Comment by clouserw** [comment]
@pmac - we're not sure how to prioritize this.  Can you expand about what not having the field means for an end user?

/cc @irrationalagent

**Comment by pmac** [comment]
I believe marketing would like to use the account creation date in their queries. Is it worth it to add this value back in to the message, or do you think it's good enough to just record the date that I receive the `verified` event to be creation date?

cc @andrewmozilla @mozbrandon

**Comment by pmac** [comment]
I have data coming in from your staging instance that looks like this:

```python
{
  'country': 'United States', 
  'countryCode': 'US', 
  'email': 'sync0.3486440592016071@restmail.net', 
  'event': 'verified',
  'iss': 'api-accounts.stage.mozaws.net', 
  'lang': 'en', 
  'locale': 'en', 
  'metricsContext': {
    'flow_time': None, 
    'time': '** ** ** **'
  }, 
  'timestamp': '** ** ** **', 
  'ts': 1582252410.066, 
  'uid': 'dac5bf77929745668ca44ea392e35a4c', 
  'userAgent': 'node-XMLHttpRequest'
}
```

So I guess my question is whether the `metricsContext['time']` value or the `timestamp` or `ts` values are good for me to use to approximate the create time for the account.

(the `********` values are what Sentry showed me ¯\\\_(ツ)\_/¯)

**Comment by pmac** [comment]
Based on my reading of the code, I think the `ts` value will be most useful for us. It's not the account creation date, but it is the date in seconds since unix epoc when the verify event was sent. That seems close enough.

https://github.com/mozilla/fxa/blob/9c39cc49172c2cb1eb92bd1d232ef3e3cc957dc8/packages/fxa-auth-server/lib/log.js#L139

Thoughts?

**Comment by clouserw** [comment]
If you're happy with it, I'm happy with it

**Comment by pmac** [comment]
@clouserw am I right about my assessment of that value? It's the datetime at which the notification was generated? And do you consider that to be very close to the time at which the user account was verified? If it's guaranteed to be close (within a minute or two I'd say) then I think it's fine. Otherwise it would be nice to get the actual account creation (or verification) datetime thrown in there.

**Comment by rfk** [comment]
> It's the datetime at which the notification was generated?
> And do you consider that to be very close to the time at which the user account was verified?

Yes, and yes 👍

**Comment by pmac** [comment]
> Yes, and yes 👍

Awesome. Thank you!
