### ISSUE TITLE
Mitigate db write load of maintaining refresh_token "last used at"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#4146]
The OAuth refresh_tokens database table contains a "last used at" column giving the timestamp at which the token was last used to generate on access token. We use this information as part of the user's "devices and apps" list to let them know which connected clients have been recently active.

There's currently [some logic](https://github.com/mozilla/fxa/blob/e6f111cbf8cb41f25103eb34503ab83468465088/packages/fxa-auth-server/lib/oauth/routes/token.js#L333) to guard against writing that column to the db too frequently, because writes can be expensive at scale. But that'll only get us so far, and the broader we make the definition of "too frequently" the less useful this information becomes to the user.

We've already been through this once in the past, with sessionTokens. For sessionTokens we wound up [storing the frequently-changing metadata in redis](https://github.com/mozilla/fxa/blob/e6f111cbf8cb41f25103eb34503ab83468465088/packages/fxa-auth-server/lib/db.js#L290) rather than writing it through to the db, on the logic that it's better to have information that's usually accurate but with a small risk of disappearing entirely, than to have information that's never particularly accurate.

I propose that we do the same for refresh tokens, storing last-used-at in redis in the same way that we currently do for sessionTokens, to mitigate potential scaling issues for when we get a big influx of new refresh-token-using OAuth clients with the Fennec->Fenix migration.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1104)
┆Issue Number: FXA-1104

**Comment by rfk** [comment]
I spent a bit of time today to re-acquaint myself with how all the pieces work here, here's my summary for future reference:

* We write sessionToken metadata into redis under a key that's just the user's `uid`.
* Its contents is a JSON object where the keys are session token ids, and the values are an object containing last-access time, UA and geolocation data.
* There are lua scripts `getSessionTokens_1` and `touchSessionToken_1` for manipulating this value on the redis server, as well as a `pruneSessionTokens_1` script for background cleanup of expired tokens.
* The code in `./lib/db.js` calls the redis lua function when it's working with sessionTokens, in order to merge the data in redis with the data in MySQL.

If we wanted to take a similar approach with refresh tokens, it would look like this:

* Store refresh_token metadata in the same redis under a different key, say `refresh-tokens-${uid}`, or perhaps `rt-${uid}` if we want to keep the length short.
    * The contents of this key would be a JSON object with the refresh token metadata.
    * The keys would be refresh token ids, and the values would be JSON objects with a single `lastAccessTime` field (so that we can expand the stored metadata in future).
* Create `getRefreshTokens_1` and `touchRefreshToken_1` lua scripts, and more-or-less direct copies of the sessionToken scripts. Duplication here doesn't seem too bad as the scripts are pretty short and simple.
* Update `./lib/oauth/db/index.js` to integrate with redis:
    * It can read redis config from the existing config key and make its own redis connection. Or, should we try to refactor to share a single redis client between the two bits of database code?
    * Update the following methods to read the metadata from redis and merge it with the data in the db: `getRefreshTokensByUid`, `getRefreshToken`, 
    * Update the following methods to delete from redis when deleting from the db: `deleteRefreshTokens`, `deleteClientRefreshToken`, `removeRefreshToken`, `removePublicAndCanGrantTokens`
      * Some of these will need to first delete the data in MySQL, then return the list of deleted ids so they can be purged from redis.
    * Update the following methods to update metadata in redis: `usedRefreshToken`.
      * Should this only ever write to redis, or occasionally write through to MySQL as well? Unlike session tokens, this is the only reason we ever write to an existing refresh token in MySQL, so there's no opportunity to flush the data to MySQL opportunistically.
* Update `./lib/oauth/routes/token.js` to remove the logic that only calls `db.usedRefreshToken` if the timestamp is sufficiently new, and instead just calls it on any use of the token.
* We do not expire refresh tokens, so we don't need an equivalent of the `purgeSessionTokens_1` lua script.
* Add new tests as necessary, but hopefully not have to adjust any existing tests because the change should be transparent to calling code above the db layer.

In the future, we could hook in to `db.usedRefreshToken` to write additional metadata into redis, such as the geolocation data that we currently track for sessiontokens.

@dannycoates does this seem like a reasonable approach?

**Comment by dannycoates** [comment]
> does this seem like a reasonable approach?

indeed 👍 

>     * as more-or-less direct copies of the sessionToken scripts

_or less_ ;) I'd prefer to not do the [un]packing part and either use full json strings or msgpack if size is an issue



>     * should we try to refactor to share a single redis client between the two bits of database code?

It'd be nice to use one connection but a separate instance is ok for now

**Comment by rfk** [comment]
> I'd prefer to not do the [un]packing part and either use full json strings or msgpack if size is an issue

Oh my, yes, I had forgotten how...uh..."involved" the serialization of that sessionToken data had gotten over time.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Just wanted to note for planning purposes, I'm not likely to have a PR up for this until later in the week, and it's no problem if it's not reviewed before the train cutting on Thursday. I'm still planning to work on it this week.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I need to move this back into our sprint as Jira won't let me start our new sprint with this hanging out in yours.  🙁
