### ISSUE TITLE
The payment confirmation email is sent with a delay

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4151]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button and complete the subscription process.
3. Observe the received emails.

#### Expected result:
- The payment confirmation email is sent.

#### Actual result:
- The payment confirmation email is not sent.

#### Notes
- fxa account used to reproduce this issue today: mcotetiu+sub500@mozilla.com
- This also reproduces for the daily product
- This did not reproduce yesterday.  For two subscription created yesterday the confirmation emails were sent. fxa accounst used is tests yesterday:  mcotetiu+sub400@mozilla.com, mcotetiu+sub401@mozilla.com

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1107)
┆Issue Number: FXA-1107

**Comment by madalincm** [comment]
After further investigation it appears the email is sent but with some delays. I am lowering the severity

**Comment by clouserw** [comment]
Based on conversation, it sounds like this is within the 15m threshold and should be closed.  Please let me know if that's not the case.
