### ISSUE TITLE
The show password icon is not displayed in the FxA delete account section

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4152]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Create a FxA account.
2. Go to https://accounts.stage.mozaws.net/settings/delete_account
3. Write anything in the password field. 

#### Expected result:
- There are no issues.

#### Actual result:
- There is a **Show password** text instead of an eye icon displayed.

#### Notes:
- This issue is also reproducible for all other fields where you need to login/register and have the show password option.

![image](https://user-images.githubusercontent.com/17178945/74531523-8915f500-4f35-11ea-8e57-4e50a91adaf4.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1108)
┆Issue Number: FXA-1108

**Comment by vasilicatamas** [comment]
@LZoog This issue seems to be regressed by #3991

**Comment by LZoog** [comment]
Shoot, I definitely checked this view. I'll take a look at this today.

**Comment by bsurd** [comment]
Verified in the latest stage env, the **Show password** text is no longer displayed and has been replaced with the correct icon. Marking as verified.
