### ISSUE TITLE
Incorrect update card error message

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4153]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- MacOS 10.14.6
- Linux Ubuntu 19.04
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using a valid card number. (Ex. 4242-4242-4242-4242)
3. Click on the Subscribe button.
4. Go to "Manage Subscription" > "Change"
5. Complete the subscription update process using the following card number: 4000-0000-0000-0002.
6. Click on the Update button.

#### Expected result:
- The following error message is displayed: Your transaction could not be processed. Please verify your credit card information and try again.
- No payment is made.

#### Actual result:
"An internal server error occurred" message appears.

#### Notes:
It's the same result with the following card numbers: 
4000-0000-0000-0069
4000-0000-0000-0127
4000-0000-0000-0119
4000-0000-0000-9979
4000-0000-0000-9995
4000-0000-0000-0101

![Screenshot 2020-02-14 at 3 26 11 PM](https://user-images.githubusercontent.com/48829350/74535963-be274500-4f3f-11ea-9c8d-2708485541f6.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1109)
┆Issue Number: FXA-1109

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think this was fixed as part of https://github.com/mozilla/fxa/commit/849ee53edb90ead6f37af008b422f1c57d1119d5#diff-eedc9e44d94c523680530e9c145c9496

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [FPN-stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/) site, using the latest Firefox Release (73.0.1).
Verified on Windows 10 x64.
