### ISSUE TITLE
No email is received on mailinator.com

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4154]
**Build:**
Stage [Train 1.158.0]

**Affected platforms:**
Windows 10 x64

**Steps to reproduce:**
1. Launch Firefox 
2. Follow the account creation flow using a mailinator.com account

**Expected results:**
Firefox emails are successfully sent on mailinator.com

**Actual Results:**
Firefox emails are not received on mailinator.com. 

**Note:**
- This issue is not reproducible on production Train 1.157.0
- QA team uses mailinator.com for creating temporary testing users.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1110)
┆Issue Number: FXA-1110

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage:  We don't think any code has changed recently.

[~jbuckley@mozilla.com] [~jmorrison@mozilla.com] - is this something that changed on your end?  

[~vtamas@mozilla.com] - maybe this was just temporary?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Nothing has changed on our end - this should work just fine

**Comment by vasilicatamas** [comment]
This issue is no longer reproducible on FxA stage Train 159. Closing.
