### ISSUE TITLE
Remove scrypt-hash dependency

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#416]
`scrypt-hash` is still an optional dependency, but we're now running the tests and building the Docker image using node 10's built-in scrypt implementation. As soon as everyone has updated to running node 10 locally too, we should remember to remove the dependency on `scrypt-hash`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-618)
┆Issue Number: FXA-618

**Comment by clouserw** [comment]
We're well past node 10 now.  We should be able to replace this with built-ins.
