### ISSUE TITLE
Unable to login to Sync because forgotten password email was returned [bz1615817]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4171]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1615817

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

1. Sign in to Firefox
2. A new screen appears asking for email address (I proceed)
3. Another screen appears asking for Firefox password
4. I key in the password I wrote somewhere to remember
5. Firefox says Invalid password
6. I click on Forgot password?
7. A new screen appears asking for my email to proceed
8. As soon as I provide my email, a RED message appears saying
    Your email was just returned

Actual results:

Firefox has created a no win scenario for me. It won't accept my password and it doesn't or can't send a recovery email.

Expected results:

My email should not have been returned. There's absolutely nothing in my email address to prevent emails coming in from anybody.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1117)
┆Issue Number: FXA-1117

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll handle this in bugzilla
