### ISSUE TITLE
[FxA] Low hanging characters like "g" and "q" appear cut off in Firefox account display name [bz1615596]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4173]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1615596

Created attachment 9126720
character display issue.PNG

[Affected versions]:
Firefox 73.0 (20200207195153)
Firefox 74.0b2 (20200211200559)
Firefox 75.0a1 (20200213035745)

[Affected platforms]:
Windows 10 64-bit

[Steps to reproduce]:
1.Launch Firefox and login using a Firefox Account.
2.Navigate to https://accounts.firefox.com/settings/display_name and edit the Display Name adding low hanging characters like "g", "q" or "p". 
3. Save the change and view the display name as it shows in manage account page. 

[Expected results]:
Extra padding so that the characters are no longer cut off. This is not happening on MacOS or on Android so consistency across platforms would be appreciated. 

[Actual results]:
Low hanging characters are cut off. 

[Additional notes]:
Issue does not occur on about:preferences#sync, only on Manage account page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1118)
┆Issue Number: FXA-1118

**Comment by LZoog** [comment]
I can confirm this is not an issue on Mac OS on dev, stage, or prod. Also not seeing it on prod iOS.

Must be Windows only.

**Comment by mirunacurtean** [comment]
Verified fixed on dev on Windows pro 10 64-bit. Display name Letter dangles are no longer cropped. 

![image](https://user-images.githubusercontent.com/53306802/75431434-86fc5f00-5955-11ea-8432-6ba85f233483.png)
