### ISSUE TITLE
Standardize how errors are displayed on the subscription page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4174]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All Platforms

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the **Subscribe Now** button and log in/sign up with an account.
3. Fill all of the fields with valid data, use 4000-0000-0000-9979 for the card number and click on the **Submit** button.
4. Observe the UI.
5. Change the card number to  4000-0000-0000-0069 and click on the **Submit** button.
6. Observe the UI.

#### Expected result:
- The errors are being handled in the same way.

#### Actual result:
- The errors are handled in different ways, one is displayed in a container while the other is being handled by a modal.

![image](https://user-images.githubusercontent.com/17178945/74655080-6e8d8700-5194-11ea-917d-75e2e05d169d.png)

![image](https://user-images.githubusercontent.com/17178945/74655095-777e5880-5194-11ea-95d4-7c45b0a22351.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1119)
┆Issue Number: FXA-1119

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage:  John says all errors should be in the first style (red box at the top, not a modal).

**Comment by bsurd** [comment]
Verified in the latest stage environment, all errors are properly displayed using the red box style. Closing and marking as verified.
