### ISSUE TITLE
Unable to send password reset [bz1616021]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4175]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1616021

Created attachment 9127055
44a8a90878bd1e83e67094a54c4b91be(1).png

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0

Steps to reproduce:

We are attempting to regain access to an extension (jid1-np4qQKys1098lQ@jetpack) by sending a password reset to the owner (christopher.lloyd@theguardian.com) who has now left the company.

We were referred to opening a bug here after emailing amo-admins@mozilla.com. We also be happy to explore any other ways of restoring our access if possible?

Actual results:

Unfortunately the reset fails with "Your email was just returned. Mistyped email?".

We think this is because we originally tried to send a reset mail before restoring the address in our GSuite, however we still got the error after restoring the account.

NB: we have taken the account down again for security reasons. Let me know if you need us to restore it.

Expected results:

The reset email is sent.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1120)
┆Issue Number: FXA-1120

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll handle this in bugzilla
