### ISSUE TITLE
Subscriptions button is not shown on account/settings page

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#4182]
## Description

Describe the issue that you're seeing.
In prod, the button to go to the subscriptions page ian’t shown.

### Steps to reproduce

Go to https://accounts.firefox.com/settings

### Expected result
 

There should be a button that takes me to my subscriptions page

### Actual result

No button.

![7C3A2075-9E8A-4771-83A8-0D3F3B9F8E08](https://user-images.githubusercontent.com/36629/74781820-3fe4de80-5270-11ea-8971-0110e7332cce.png)

Also, going to the support url redirects to the settings page after bouncing on some subscription URLs.

### Environment

Prod

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1125)
┆Issue Number: FXA-1125

**Comment by johngruen** [comment]
I can reproduce this...the net result is that user cannot access support or cancel their subscriptions

**Comment by chrismore** [comment]
I am experiencing the same issue with my fxa email address linked to my paying FPN VPN subscription.

**Comment by rlr** [comment]
This was fixed at some point last night. I think the arch 2.0 deploy and some migration scripts did the trick, if I read correctly in slack.
