### ISSUE TITLE
Let's merge this repo into fxa-auth-server

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#419]
On two occasions in the last week or so, auth server CI got broke because of stuff being reverted here. It's much easier to fix those breakages when you are notified straight away than it is to do so days after the breakage actually occurred and you're not sure specifically which change caused it.

If it's okay to merge the oauth repo into auth, I don't see why this one shouldn't be merged too (actually I think the argument is even stronger in this case). I plan to make a big song and dance about this in the next retro to see if there are arguments against.

**Comment by shane-tomlinson** [comment]
We *just did this*. 🕺
