### ISSUE TITLE
Fxa no longer sending events to syslog-proxy1.dmz.mdc1.mozilla.com [bz1610693]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4190]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1610693

Looks like we stopped receiving events from fxa to syslog-proxy1.dmz.mdc1.mozilla.com

The number of received events dropped considerably on the 16th, and by the 17th of January at 2PM PACIFIC they stopped coming in completely.

Was there a change on your end to the shipper that was sending to syslog-proxy1.dmz.mdc1.mozilla.com?

Please advise,

Alicia Smith

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1129)
┆Issue Number: FXA-1129

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll do this in bugzilla
