### ISSUE TITLE
[admin panel A1.0] Create rough wires for the UI

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4197]
We want to include all of the currently desired features from the user stories.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1135)
┆Issue Number: FXA-1135

**Comment by LZoog** [comment]
This isn't exactly a "rough wire" but I ended up using the settings redesign header + navigation placement. My hope is that we can get a head start on settings with the admin panel and share some of this code.

The header BG is from Firefox branding, and all of the icons (besides FPN) are from the FF Photon Icons page.

To also get a head start on the "basic UI styles" ticket (#4204), I went ahead and spun up a codepen and wrote some rough HTML/SCSS to get us going for the main content. I started experimenting with some CSS variables so this will likely remain WIP, but I thought it was prudent to not spend time getting the design pixel-perfect in Photoshop only to have to code it out in PS, so the content is a screenshot. The SVGs are at the bottom.

Codepen: https://codepen.io/LZoog/pen/yLNVoqY
Wire:
<img width="962" alt="admin-panel-email" src="https://user-images.githubusercontent.com/13018240/75192998-fdf9e380-571a-11ea-8b74-252c76d54683.png">

I'll update the admin panel Google doc correspondingly.
