### ISSUE TITLE
[admin panel A1.0] Setup single user / DB connection with restricted permissions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4199]
This is an ops task.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1137)
┆Issue Number: FXA-1137

**Comment by jrgm** [comment]
which logical databases will the admin panel need to query (both initially, and possibly later on). The fxa (auth) db, fxa_oauth and/or fxa_profile; I’m thinking the answer is {fxa,fxa_oauth}

**Comment by LZoog** [comment]
Auth + OAuth sounds correct to me, don't think we need profile. We've got 4 planned features now - clearing blocked emails (auth), viewing non-secret RP info (oauth), viewing feature flags in redis (auth), and viewing Stripe product/plan metadata which will probably need some keys set but I don't think that needs a db connection.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

These are deployment tasks and therefore should go with the sprint when we're ready to deploy Admin Panel. Completion sprint TBD; will move into backlog.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

This was already done.
