### ISSUE TITLE
[SUMO User Issue]  Specific email not receiving emails Investigation of michael@domain.tld [bz1617079]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4238]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1617079

I am unable to register an account with either bugzilla.mozilla.org or accounts.firefox.com. In both cases, I am told to expect a confirmation number, but they never show up.

I attempted two gmail accounts (including michael@domain.tld), two work accounts, and a newly-created account at mail.com (this account). I was only successful with the last account mentioned.

If at all possible, please CC that address so that I am less likely to miss a response.

(domain.tld -> lustfield.net)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1184)
┆Issue Number: FXA-1184

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll do this on bugzilla
