### ISSUE TITLE
Even when I am logged in, going to firefox sync login page shows me sign in page for the same account. [bz1617346]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4255]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1617346

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

From new tab page, I clicked "Sign in to sync". Entered authentication details

Actual results:

I successfully logged in to the account. After this, if I go to the "Sign in to sync" button, it goes to login page, and asks me to enter password for the same account into which I am logged in. It does not seem to log out automatically.

Expected results:

As I am logged in, it should not ask for the password. Instead, show me as logged in.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1191)
┆Issue Number: FXA-1191

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Closed in Bugzilla.
