### ISSUE TITLE
Play with rayon for the queues process

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#426]
I just read about [rayon](https://github.com/rayon-rs/rayon):

> Rayon is a data-parallelism library for Rust. It is extremely lightweight and makes it easy to convert a sequential computation into a parallel one.

Seems like it might be a good fit for the queues process, which sequentially processes batches of events from the bounce, complaint and delivery queues.

**Comment by clouserw** [comment]
-> wontfix
