### ISSUE TITLE
"Enter auth code" page on Android shows alpha keyboard

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa#4281]
When connecting an acct on Fenix, if you bring up the on-screen keyboard on the "enter auth code we just sent you" page, a full alpha keyboard is shown. It should be possible for the HTML to arrange for a numeric-only keyboard to be shown instead.

(I admit that I haven't looked into this very much - it's certainly possible this is actually a bug in Fenix, or I may have missed something else - apologies in advance if that's true)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1202)
┆Issue Number: FXA-1202

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This may be more tricky than it seems as we do some processing for dashes and spaces

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I've verified that on Android Firefox and Firefox Preview the input does pull up the full alpha keyboard.  However, in Chrome, the numeric keyboard is displayed.  This is because Firefox doesn't handle the `inputmode="numeric"` on the input correctly.  Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1205133 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1205133 )

WONTFIX?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~mhammond@mozilla.com] (in case @someone in Jira actually works)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I also don't see the harm of using input type="number".  I'll just make that change.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

number inputs do not support the `pattern` attribution, which breaks validation.  I'm leaning towards WONTFIX.

**Comment by mhammond** [comment]
> number inputs do not support the pattern attribution, which breaks validation.  I'm leaning towards WONTFIX.

I believe that this would be a massive improvement for users who actually enter the code via the (virtual) keypad on their phone. IMHO, the fact that it requires extra work to handle codes copy/pasted in isn't a good enough justification for ignoring those who enter it.

**Comment by chenba** [comment]
> this would be a massive improvement for users who actually enter the code via the (virtual) keypad on their phone

I do agree.  Let me fiddle around with the validation code and see what I can do.

**Comment by chenba** [comment]
@mhammond thanks for nudge.  The validation issue was not what I thought it was.  New PR created.

**Comment by chenba** [comment]
Danny linked to https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/ in the PR, which in turn linked to some related screenreader bugs (some have been fixed).

https://a11ysupport.io/tests/tech__html__input__input-number shows partial screen reader support level.  😦

**Comment by chenba** [comment]
Since moving to input type=number represents a downgrade in accessibility, I think we ought to WONTFIX this.

(https://bugzilla.mozilla.org/show_bug.cgi?id=1205133 has been active in the last few days so hopefully a real fix is coming soon.)

**Comment by mhammond** [comment]
I can't argue with that.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

WONTFIX.  See above comments regarding accessibility of the type=number approach.
