### ISSUE TITLE
[doc] s/irc/matrix/ on CONTRIBUTING.md

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#4282]
what: https://wiki.mozilla.org/Matrix
where: https://chat.mozilla.org/#/room/#fxa:mozilla.org

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1203)
┆Issue Number: FXA-1203

**Comment by jackiemunroe** [comment]
Closed with https://github.com/mozilla/fxa/pull/4340
