### ISSUE TITLE
FPN/Guardian isn't receiving any Subscription State Change events from fxa-event-broker

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#4298]
I already slacked about this with @bbangert a little. Filing ticket for tracking....

Searching our logs for both stage and prod, I see plenty of `delete-user`, `profile-change` and `password-change` events coming in through our webhook. But there is not a single `subscription-state-change` event in our logs even though subscriptions are cancelled almost every day and many more are created. Something is not working right here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1214)
┆Issue Number: FXA-1214

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

dupe
