### ISSUE TITLE
FxA Mobile Users Metric

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#43]
As a Firefox product group member I want to know how many FxA users are using a mobile device, and how many are mobile only.

**Comment by shane-tomlinson** [comment]
> how many are mobile only.

Does this depend on #42 (FxA Multiple Device Metrics)?

**Comment by rfk** [comment]
There's no explicit dependency, but most of the work we do to enable a "has multiple devices" metric will also enable the "has only one device and it's a mobile" metric.

**Comment by shane-tomlinson** [comment]
> There's no explicit dependency, but most of the work we do to enable a "has multiple devices" metric will also enable the "has only one device and it's a mobile" metric.

That's what I was getting at. It sounds like the foundation work required for #42 at least partially overlaps with the foundation work required for this. That's good.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-22
