### ISSUE TITLE
The request was blocked for security reasons [bz1618476]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4305]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1618476

Created attachment 9129426
Screenshot_2020-02-27_14-15-31.png

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

Went to https://accounts.firefox.com/ , and entered my email address. Same outcome on mobile and laptop.

Actual results:

On pressing continue button, i got "The request was blocked for security reasons"

Expected results:

Should have proceeded to ask for password.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1217)
┆Issue Number: FXA-1217

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll do this in bugzilla
