### ISSUE TITLE
Integrate anonymizing key into JS bundle or fetch from endpoint

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4323]
Get the key from data engineering / ops and integrate into client-side JS bundle for generating ecosystem_anon_id.

Note that we already have this public key, it's exposed for Sync clients via GET /.well-known/fxa-client-configuration. We need to decide if we want to fetch the key from that endpoint, or bundle it into the client-side JS.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1228)
┆Issue Number: FXA-1228

**Comment by LZoog** [comment]
Didn't realize we closed this with #5996 -party parrot-
