### ISSUE TITLE
Local services

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#4343]
Problem: New contributors who might have redis, memcached, and/or mysql running in the background won't be able to successfully start the monorepo, but also won't get a clear error message when they `npm start`.

Simple fix: we could address this by mentioning it in the docs.

Fancier fix: we could add some cross-platform checks to ensure those services aren't running, and log a helpful error if they are.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1243)
┆Issue Number: FXA-1243

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's hardcode some ports in the startup script
