### ISSUE TITLE
No icon is displayed in “Confirm recovery key” modal

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4367]
**Note:**
This is a follow-up up for #2653

**Build:**
Stage [Train 1.160.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Create and confirm a new Firefox account.
2. Go to the email inbox and open the "Get a recovery key" email.
3. Click on the “Get a recovery key” button from the email.
4. Click on “Get a recovery key” button from “protect your data with a recovery key” page.
5. Enter your password and click the “Continue” button.
6. Copy the recovery key and click the “Done” button.

**Expected results:**
There are no UI issues in “Confirm recovery key“ modal.

**Actual Results:**
The icon misses from “Confirm recovery key“.

![Screenshot_13](https://user-images.githubusercontent.com/18114210/75672703-f641be00-5c89-11ea-92c0-96de4f6c7c0b.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1262)
┆Issue Number: FXA-1262

**Comment by davismtl** [comment]
> The icon misses from “Confirm recovery key“.

Are you referring to the Firefox Brand logo?

**Comment by vasilicatamas** [comment]
> Are you referring to the Firefox Brand logo?

I'm referring to the following blue icon:

![Screenshot_15](https://user-images.githubusercontent.com/18114210/75973168-65632080-5edd-11ea-82d5-e9e04dca2866.png)

See mock-ups: https://mozilla.invisionapp.com/share/Q3UK63V4PKA#/screens/390543494_Recovery_Key_Recommendation

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [1.162.0] under Windows 10 64-bit and Android 9. Recovery key graphic is successfully displayed in Confirm recovery key screen.

![Screenshot_26](https://user-images.githubusercontent.com/18114210/76633957-3a687480-654e-11ea-803d-98f3645489e3.png)
