### ISSUE TITLE
”Back” button misses from “Save recovery key” modal

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4368]
**Note:**
This is a follow-up up for #2653

**Build:**
Stage [Train 1.160.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Create and confirm a new Firefox account.
2. Go to the email inbox and open the "Get a recovery key" email.
3. Click on the “Get a recovery key” button from the email.
4. Click on “Get a recovery key” button from “protect your data with a recovery key” page.
5. Enter your password and click the “Continue” button.

**Expected results:**
“Back” button is successfully displayed in “Save recovery key” modal under “Done” button based on https://mozilla.invisionapp.com/share/Q3UK63V4PKA#/screens/390543494_Recovery_Key_Recommendation

**Actual Results:**
There is no “Back” button displayed in “Save recovery key” modal.

![Screenshot_14](https://user-images.githubusercontent.com/18114210/75673075-c3e49080-5c8a-11ea-985a-5970eedc4861.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1264)
┆Issue Number: FXA-1264

**Comment by davismtl** [comment]
This is a good catch but I don't believe the back button provides any benefit at this step so I am OK with it missing.
