### ISSUE TITLE
Subscription status not being properly returned in /v1/profile or /v1/subscriptions

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#4370]
## Description

Subscription status isn't being returned correctly for users with active subscriptions.

### Steps to reproduce

1. Go to https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn
2. Click Subscribe Now
3. Go through payments flow
4. Verify subscription is active on https://accounts.stage.mozaws.net/settings

The subscription status isn't seen by the fpn/guardian client. This is what's being returned by the API:

At the profile endpoint (`/v1/profile`):
```
{"email":"ricky@mozilla.com","locale":"en-US,en;q=0.5","amrValues":["pwd","email"],"twoFactorAuthentication":false,"uid":"1ecccb60e389446a896f7d927ddeb767","avatar":"https://mozillausercontent.com/bc8784649e1f5bfe93dd1c113ec7984c","avatarDefault":false,"displayName":"Ricky R.","subscriptions":[]}
```

At the subscriptions endpoing (`/v1/subscriptions`):
```
{"subscriptions":[]}
```

### Expected result

There should be a vpn subscription returned in the array.

### Actual result

Empty subscriptions array.

### Environment

Stage
What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1266)
┆Issue Number: FXA-1266

**Comment by lmorchard** [comment]
I can also reproduce this issue on staging using the 123done demo product, so it's not limited to FPN. In a Slack thread, we verified that the expected metadata is set in Stripe. So, next step is to look into the subscription capabilities changes from a663d7b8ab8436a2c2152ff17f10a860d6c99e16

**Comment by bsurd** [comment]
I was looking into this today, but if the user has a subscription for guardian and another one for 123done only one of them seems to be displayed in the request. Shouldn't both of them be returned?

```
{"email":"bsurd+tst1@mozilla.com","locale":"en-US,en;q=0.9","amrValues":["pwd","email"],"twoFactorAuthentication":false,"subscriptions":["123donePro"],"uid":"c2e95bddc255476d9796f2e6ef6433e8","avatar":"https://mozillausercontent.com/00000000000000000000000000000000","avatarDefault":true}
```

![image](https://user-images.githubusercontent.com/17178945/75969115-1f0ac300-5ed7-11ea-82ac-ed14766e282d.png)

![image](https://user-images.githubusercontent.com/17178945/75969141-2a5dee80-5ed7-11ea-8b87-f7b0e44f99c6.png)

**Comment by bsurd** [comment]
Marking this as verified as there is only one product the user can currently subscribe to.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

bq. @lmorchard Shouldn't both of them be returned?

No, subscription capabilities are filtered for the Relying Party requesting the profile. 

So, if the 123done client ID is used in a request for the profile, it should only see 123done-related capabilities. Vice versa for Guardian - it should only see Guardian-related capabilities and not those scoped for 123done. We do this in order to selectively reveal information to RPs - we don't want every RP to see all subscriptions for a user.
