### ISSUE TITLE
Only build docker images on master/tags

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4372]
Our usage of circleCI grew out of how we used to have split projects.  We build docker images in CircleCI, but only end up pushing them a small percentage of the time.  Let's not build them unless we're going to use them.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1270)
┆Issue Number: FXA-1270

**Comment by dannycoates** [comment]
done
