### ISSUE TITLE
[RTL] Fix padding on the Firefox services section on the signup page

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/fxa#4383]
This is a follow-up to #4334, see the discussion there.

CSS file:
https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/styles/modules/_marketing.scss

Code to remove:
https://github.com/mozilla/fxa/blob/736b623c93ad5c572a8d9004620be31a4378b0e8/packages/fxa-content-server/app/styles/modules/_marketing.scss#L47

Code to add in the `.firefox-service` rule:
```css
html[dir='rtl'] & {
  padding: 0 0 10px 10px;
}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1273)
┆Issue Number: FXA-1273

**Comment by chenba** [comment]
@ItielMaN Thanks!
