### ISSUE TITLE
Limit email header size to less than 998 characters

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#4390]
When sending a password reset email, we embed a lot of contextual information into the password-reset link, and we include that full URL of the link in the `X-Link` email header as an aid for debugging/testing.  This URL can be arbitrarily long, e.g. if you try resetting your password from [this signin page](https://accounts.firefox.com/reset_password?utm_campaign=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&entrypoint=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&utm_medium=utm_campaign=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&entrypoint_variantion=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&utm_source=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&utm_term=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) it will generate a password-reset link that's well over 1000 characters long.

That's a problem for the `X-Link` header. [RFC5322 says that](https://tools.ietf.org/html/rfc5322#section-2.1.1):

```
   There are two limits that this specification places on the number of
   characters in a line.  Each line of characters MUST be no more than
   998 characters, and SHOULD be no more than 78 characters, excluding
   the CRLF.

   The 998 character limit is due to limitations in many implementations
   that send, receive, or store IMF messages which simply cannot handle
   more than 998 characters on a line.  Receiving implementations would
   do well to handle an arbitrarily large number of characters in a line
   for robustness sake.  However, there are so many implementations that
   (in compliance with the transport requirements of [RFC5321]) do not
   accept messages containing more than 1000 characters including the CR
   and LF per line, it is important for implementations not to create
   such messages.
```

It is possible for emails to contain long header values by [folding them on whitespace](https://tools.ietf.org/html/rfc5322#section-2.2.3) to get around the line-length limit, but in our case, the header does not contain any whitespace at which to fold.

Many email servers can handle lines longer than 1000 characters just fine (I was able to test this with my fastmail address and it had no problems with the gigantic header) but there are almost certainly some that can't. I suspect this is the cause of deliverability problems in e.g. Bug 1618831.

I don't know what the rate of delivery problems due to this issue might be. But given that the `X-Link` header is mostly for dev purposes, any risk of deliverability problems seems like a bad tradeoff. Can we either remove this header, or find some way to limit its length without compromising its usefulness for testing?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1276)
┆Issue Number: FXA-1276

**Comment by rfk** [comment]
The major contributor to the size of this link, FWIW, is the "resume token" which even in the simplest case of accessing FxA with no query params, includes a base64-ified JSON representation of an object like this:

```
{
  "deviceId":"5be18b3991d748d38ad2effe1cb75250",
  "email":"me@example.com",
  "entrypoint":null,
  "entrypointExperiment":null,
  "entrypointVariation":null,
  "flowBegin":1583201249847,
  "flowId":"b29128fc9a9fb6bbb12bf968613742b27a5833f4daae18181c602ed8ab4b95a2",
  "planId":null,
  "productId":null,
  "resetPasswordConfirm":true,
  "style":null,
  "uniqueUserId":"0f47f0b3-5af5-4531-8f5a-ec1a262a3b0a",
  "utmCampaign":null,
  "utmContent":null,
  "utmMedium":null,
  "utmSource":null,
  "utmTerm":null
}
```

**Comment by rfk** [comment]
> I suspect this is the cause of deliverability problems in e.g. Bug 1618831.

We were indeed able to resolve the issue in this bug by [generating a shorter X-Link header](https://bugzilla.mozilla.org/show_bug.cgi?id=1618831#c8) so I'm pretty confident this was the cause of the issue.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's truncate the header at 998

**Comment by rfk** [comment]
> Let's truncate the header at 998

OK; just keep an eye out for external test suites that expect to be able to fish the `X-Link` header out of the email and open it (e.g. [this one](https://phabricator.services.mozilla.com/D53789)). Hopefully they don't generate such long links, but if they start randomly failing then this might be why.
