### ISSUE TITLE
Fennec device is not displayed in “Send tab to device” list when sync is off

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4391]
**Build:**
Stage [Train 1.160.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Login using a Firefox account on 2 devices:
 - Desktop - Sync should be turned OFF
 - Android Fennec - Sync should be turned ON
2. On first device, open a random page.
3. Right click on the recently opened tab and select “Send tab to device” option.

**Expected results:**
Android (Fennec) device is successfully displayed in “Send tab to device” list.

**Actual Results:**
Android (Fennec) device does not appear in “Send tab to device” list as long as the Sync is turned off.

**Additional notes:**
- Android (Fennec) device is successfully displayed  in “Send tab to device” list when Sync is turned ON.
- This issue is not reproducible using Fenix.

![sendtab](https://user-images.githubusercontent.com/18114210/75763028-48471a00-5d44-11ea-8039-15998f4d11af.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1277)
┆Issue Number: FXA-1277

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Do you need to have sync on to send tabs?  We (in triage) thought you did.

**Comment by rfk** [comment]
This is confusing, but unfortunately, is behaving as expected.

Fennec only supports the "old" send-tab system, which transfers data by storing it in sync.

When sync is enabled in Desktop, it is able to send tabs to Fennec via the old send-tab system. When sync is not enabled in Desktop, it can only use "new" send-tab and hence is unable to send to Fennec.

This situation will become much less confusing once we finish migrating Fennec to the new Fenix codebase, which supports new send-tab.

I think this is a WONTFIX given that we will not do any additional work in Fennec.
