### ISSUE TITLE
Create Amplitude Versions of Recovery Key Flow Metrics

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#4402]
We currently log some recovery key metrics as flow events, but they would be easier to use if they were also logged to amplitude. I propose we create the following mapping of flow events to amplitude events:

|flow event|amplitude event| 
|-- | --|
|  flow.account-recovery-confirm-key.view|  fxa_pref - account_recovery_confirm_view   |
|  flow.account-recovery-confirm-key.engage|  fxa_pref - account_recovery_confirm_enage   |
|  flow.account-recovery-confirm-key.submit|  fxa_pref - account_recovery_confirm_submit   |
|  flow.account-recovery-confirm-key.success|  fxa_pref - account_recovery_confirm_success   |
| flow.account-recovery-reset-password.view | fxa_login - forgot_password_recovery_key_view| 
| flow.account-recovery-reset-password.engage | fxa_login - forgot_password_recovery_key_engage|
|flow.account-recovery-reset-password.submit | fxa_login - forgot_password_recovery_key_submit|
| flow.account-recovery-reset-password.recovery-key-consume.success | fxa_login - forgot_password_recovery_key_success|

CC @davismtl @vbudhram

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1284)
┆Issue Number: FXA-1284

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Pulling into this train since it is metrics related.
