### ISSUE TITLE
SMS Clarity: Don't show CAD or SMS on mobile login/registration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4432]
These screens should not be shown after login or registration for mobile devices.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1302)
┆Issue Number: FXA-1302
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/12653/Screen+Shot+2020-03-06+at+4.22.23+PM.png">Screen Shot 2020-03-06 at 4.22.23 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Q for [~adavis@mozilla.com]: should they be redirected to the "ready" screen or maybe "verified"?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Q for [~adavis@mozilla.com]: should they be redirected to the "ready" screen or maybe "verified"?

Do you have a screenshot of the ready or verified screens? I want to be sure we're talking about the same ones?

Our recent discussions have highlighted that we don't always have alignment on names (e.g. connect another device vs SMS).

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Context: we marked this as low priority for now because mobile teams have been working around this "bug". They redirect users away quickly before we have time to ask them to connect a mobile device (when they are already on mobile).

Resolving this fixes a long-time outstanding bug though should not have a tremendously noticeable impact.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

I'm taking a stab at this as we're about to wrap up a few of the other issues in this epic.

[~adavis@mozilla.com] can you elaborate on where users should be redirected to? You mentioned "They redirect users away quickly before we have time to ask them to connect a mobile device", where's that? Also, since a user can land on this screen in a variety of ways (post registration, post Sync, post-verify secondary email decline), should we have a few places they could be redirect to?

I'll note that if you hit the `/connect_another_device` path on a mobile device that is ineligible to receive SMS you are shown the "complete set-up" screen (see attached). If you click "Not now" on the SMS screen you are taken [here](https://www.mozilla.org/en-CA/firefox/accounts/ ( https://www.mozilla.org/en-CA/firefox/accounts/ )). The latter seems like a good contender?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

!Screen Shot 2020-03-06 at 4.22.23 PM.png!

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

On Fennec (Firefox for Android), I think they are not doing option 2 from this comment:
https://bugzilla.mozilla.org/show_bug.cgi?id=1548331#c21 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1548331#c21 )

Summary is that they are listening for the registration success event and redirecting users to a new tab.

I will test Firefox for iOS right and charge up my Android phone see if Fenix is also doing the same thing. (which I suspect)

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

So... I'm wondering if we may already have solved this because on Firefox for iOS, it did not show a mobile app download button as I suspected (as also described by that open bug).

Instead, for <1 second, FxA displayed a start browsing button which was quickly closed by the browser and it redirected me to a new tab.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Oops, I missed this question:

> Also, since a user can land on this screen in a variety of ways (post registration, post Sync, post-verify secondary email decline), should we have a few places they could be redirect to?

If they chose to not connect another device or we decide to not ask them, we should just get them to start browsing and I think we already have a destination for that per what you linked. It's not the best destination but it's at least somewhat relevant.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Hi. I've been doing some investigation, as well as following your comments, and I think there might not be any action required here. The main logic occurs [right here](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js#L162) (and it notes our exact situation); any time someone hits `/connect_another_device` they are redirected appropriately (to the app installation success I noted above).

I have tested this:

  * iOS (physical device), fresh app install and re-sign-in
  * Android (physical device), fresh app install and re-sign-in
  * FF browser with iOS simulation, signing up for an account, and enabling sync
  * Declining secondary email add ("Maybe later")

In no case was I able to be redirected to the SMS screen.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~adavis@mozilla.com] ahh, I was chatting with Lauren, and it sounds like you might not want to show the "Sign in to Firefox for [Device] to complete set-up" page or the SMS page if you're signing up via mobile. This is do-able, but Connect Another Device on mobile serves to prompt the user to download the Firefox app. There’s a chance the user if performing their registration in Chrome or Safari, so this page might be doing some good. Can you confirm this is what you'd like (to disable both)?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

> In no case was I able to be redirected to the SMS screen.

Well, we might have already addressed this in the past. I know it was a big topic in June of 2019. Mobile did workarounds since we didn't fix it fast enough. Maybe we eventually got to it. We still had open items saying we needed to address this but if you can't reproduce it, it might be a good sign.

> There’s a chance the user if performing their registration in Chrome or Safari, so this page might be doing some good. Can you confirm this is what you'd like (to disable both)?

So, we only show the SMS / CAD flow to download the mobile app when the user is specifically signing up for Sync. You can't sign up for Sync in Safari or Chrome.

Again, if you didn't experience during testing, we might have already resolved this in 2019.

**Comment by LZoog** [comment]
Closing this as a `wontfix` but is more accurately an "already done" or dupe. Per a Zoom chat with Alex & Jody and additional testing, it looks like users that sign up through the Sync flow on mobile aren't shown this screen as-is.
