### ISSUE TITLE
Secondary email verification code does not expire after 5 minutes

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4451]
**Note:**
This is a follow-up up for #2653

**Build:**
Stage [Train 1.161.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Create and confirm a new Firefox account.
2. Go to the email inbox and open the "Set up recovery email" email.
3. Click on the “Add a secondary email” button.
4. Add a valid email address in the secondary email field and tap on "Continue".
5. Wait more than 5 minute and paste in “Enter 6-digit code” field the verification code received on the secondary email. 

**Expected results:**
Verification code becomes expired after 5 minutes.

**Actual Results:**
Confirm secondary email verification code is still valid after more than 5 minutes.

![verificationcode](https://user-images.githubusercontent.com/18114210/76072884-69f10d00-5fa1-11ea-8eb1-21f960d7bbde.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1311)
┆Issue Number: FXA-1311

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The email says '5 minutes' but the actual wait is longer.  15 maybe?  It might be longer.  Can you test it with a code from yesterday to make sure it expires?  If so, I think this should be closed.

**Comment by vasilicatamas** [comment]
> ➤ Wil Clouser commented:
> 
> The email says '5 minutes' but the actual wait is longer.  15 maybe?  It might be longer.  Can you test it with a code from yesterday to make sure it expires?  If so, I think this should be closed.

I confirm that the verification code expired after 14 min. I am closing this bug considering that this is an intended behavior.
