### ISSUE TITLE
`npm start` failing on syntax error in check_ports.sh

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4458]
```

$ npm start

> fxa@2.0.0 start /home/chenba/code/fxa
 > sh _scripts/check_ports.sh && pm2 start mysql_servers.json && echo "Use 'npm stop' to stop all the servers"

_scripts/check_ports.sh: 3: _scripts/check_ports.sh: Syntax error: "(" unexpected

```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1314)
┆Issue Number: FXA-1314

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Not that this is not an issue on macOS.

**Comment by imskr** [comment]
I would like to fix this!

**Comment by chenba** [comment]
@imskr sorry, I accidentally pushed fix for this while working on something else.  Thanks a lot for volunteering though!
