### ISSUE TITLE
Add warning for AMO Developers during FxA deletion

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4467]
We are currently working with other teams to ensure that they are listening to FxA deletion events to ensure that account deletions propagate to our relying parties.

AMO requests that we display a message to inform developers that their published add-ons will be deleted.

Attached is a screenshot if what our deletion screen looks like for context.

My proposal is that we add another checkbox that says something like:

* "Any extensions that you published to addons.mozilla.org will be deleted"

In the short-medium term, I don't believe we need to detect if they are a developer. We can display this message to 100% of users even though it will not concern most.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1321)
┆Issue Number: FXA-1321
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/12757/image+%282%29.png">image (2).png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

AMO extensions can have more than one author, as well as disabled states.  [~scolville@mozilla.com] do you have a recommendation for wording here for what will happen on the AMO side?

**Comment by data-sync-user** [comment]
➤ Stuart Colville commented:

[~wclouser@mozilla.com], Jorge would be the best person to answer that.

**Comment by data-sync-user** [comment]
➤ Jorge Villalobos commented:

I would adjust the wording to

  * Any extensions and themes that you published to addons.mozilla.org will be deleted

There's a detailed description of what we expect to happen in this PRD ( https://docs.google.com/document/d/1hjlWVzzrSrGzMYKmxqK76MzOVQbV7sbc7padtj8xclA/edit?ts=5e669697 ), but the gist of it is that if you're the sole owner of any add-on, regardless of state, it will be deleted. We could link to documentation fleshing out the specific scenarios, for developers who have add-ons with multiple owners or contributors.

**Comment by data-sync-user** [comment]
➤ Stuart Colville commented:

Just pointing this out here in case it's not obvious. We're not currently listening to the deletion events on AMO. So it's important that the wording doesn't change to something that's not going to happen until we have done that work. Can the wording updates be behind a flag?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~scolville@mozilla.com] [~jvillalobos@mozilla.com] I have a PR open ( https://github.com/mozilla/fxa/pull/4532 ) for this change that could probably just wait to merge until I get a green light here.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~scolville@mozilla.com] [~jvillalobos@mozilla.com] What's the latest here?

**Comment by data-sync-user** [comment]
➤ Stuart Colville commented:

We've got an item for AMO planned for Q2. If it was possible to put this change behind a flag until we have got ready the ability to handle listening to deletion messages, that would make co-ordinating the roll-out once easier once both sides are in-place.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The patch is done.  We won't land it and put this in our backlog.  Please let us know when you've got a date set for us to land it.  Thanks.

**Comment by clouserw** [comment]
AMO isn't ready to land this yet and has some work ahead of them before it can be done.  Please reopen this when it's time.  Thank you.

**Comment by jodyheavener** [comment]
https://github.com/mozilla/fxa/pull/5767
