### ISSUE TITLE
Beware the accuracy of complained recipients

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#447]
Related to mozilla/fxa-auth-server#2450, [the SES docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#complained-recipients) make an important point about complained recipients:

> **Important**
>
> Most ISPs remove the email address of the recipient who submitted the complaint from their complaint notification. For this reason, this list contains information about recipients who might have sent the complaint, based on the recipients of the original message and the ISP from which we received the complaint. Amazon SES performs a lookup against the original message to determine this recipient list.

In the current bounce-handling logic, this means we may have false positives for complaints. That's a low-risk issue for our current usage but may become more problematic in the future.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-640)
┆Issue Number: FXA-640

**Comment by clouserw** [comment]
Closing this as non-actionable
