### ISSUE TITLE
Sync will not accept my phone number (says invalid), probably because area code 689 is fairly new. [bz1619105]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4474]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1619105

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

I tried to input my cell phone number into the https://accounts.firefox.com/sms?service web page to add synced Firefox to my phone.

Actual results:

I keep getting message "invalid phone number."

Expected results:

It should have accepted my phone number and I am guessing because 689 is a relatively new area code that it will not recognize it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1329)
┆Issue Number: FXA-1329

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

duplicates FXA-1307
