### ISSUE TITLE
Firefox account requests two factor authentication or recovery  key even if they have been disabled or revoked [bz1621175]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4478]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1621175

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

Steps to reproduce:

I disabled the two factors authentication and revoked the recovery key the last time I signed according to the following information:
https://support.mozilla.org/en-US/kb/changing-your-two-step-authentication-device-firefox-account
https://support.mozilla.org/en-US/kb/reset-your-firefox-account-password-recovery-keys

Actual results:

Firefox sync account requests two factor authentication or recovery key even if they have been removed.

I cannot access to my account because I deleted also the two factor authentication and recovery key. I only can change the password.

Expected results:

Firefox sync account let me sign without two step authentication and recovery key or let me delete the account and create a new with the same email that previously I used.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1331)
┆Issue Number: FXA-1331

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Issue above was closed as WONTFIX, see https://bugzilla.mozilla.org/show_bug.cgi?id=1621175#c5.
