### ISSUE TITLE
The localization of the string "You've tried too many times. Try again in 14 minutes." cannot be displayed correctly

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla/fxa#4480]
### Description

The localization of the string "You've tried too many times. Try again in 14 minutes." cannot be displayed correctly

### Steps to reproduce
1. Goto  https://accounts.firefox.com
2. Input wrong pwd for several times
3. Input wrong authorization code for several times

### Actual result
There is a tip saying "You've tried too many times. Try again in xx minutes."
This string has been localized in Pontoon, but cannot be displayed correctly on the page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1332)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15605/Screenshot_22.png">Screenshot_22.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15606/Screenshot_25.png">Screenshot_25.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15607/Screenshot_26.png">Screenshot_26.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15608/Screenshot_27.png">Screenshot_27.png</a>
┆Issue Number: FXA-1332

**Comment by clouserw** [comment]
Hi @bli-mozbj .  Thanks for filing this issue.  What are you seeing and what are you expecting to see?  What language are you using Firefox Accounts in?  Thanks.

**Comment by bli-mozbj** [comment]
I'm using Simplified Chinese.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

No longer an issue due to Settings refresh.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is not only about the Settings page, it also includes the Sign in page where appears the "You've tried too many times. Try again in 15 minutes." message and it looks like is not translated at all in the Chinese (zh-cn) language, or partially translated in es, fr, de.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Apologies, thanks for re-opening!
