### ISSUE TITLE
Store service, redirectTo with verification reminders

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#450]
Verification reminders are not service-aware, so the email contains generic content and the user is taken to the FxA settings view after verifying. It might be nice if we could tailor the experience to particular services.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-642)
┆Issue Number: FXA-642

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
