### ISSUE TITLE
Not receiving verification email

### ISSUE THREAD

**Issue by PhantomGamers** [mozilla/fxa#4500]
## Description

When adding my Firefox account to my android device, it asks me to verify my account with an email that has been sent to my account, however no email ever arrives.

I suspect maybe this is related to my email being a g-suite email with a custom domain?

EDIT: I should say it's been over 24 hours and I've checked my spam folder, there's definitely no email. I've seen the support page here - https://support.mozilla.org/en-US/kb/im-having-problems-confirming-my-firefox-account

### Expected result

An email should arrive with a verification link.

### Actual result

No emails arrive.

### Environment

Android 10, One UI 2.1 (Samsung Galaxy S20+ 5G US Unlocked)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1339)
┆Issue Number: FXA-1339

**Comment by clouserw** [comment]
Hi.  Sorry you're having this problem.  The SUMO article you'll need is https://support.mozilla.org/en-US/kb/forum-response-firefox-sync-verification-email-faq specifically, the "this link" link at the bottom to create a bug on bugzilla.mozilla.org.  We can't help from github (among other reasons, we don't know your email :).   Thanks.
