### ISSUE TITLE
authentication error [bz1621537]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4503]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1621537

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

when i log in to firefox account my  authentication app is active and no matter what code i put in it still doesn't unlock my account i used my original recovery key still wont accept and there isnt away for me to even view 2 step verification its not even on my options list plz help 

Actual results:

im locked out of my sync account yet i can still access all my saved passwords and access lock-wise but cant sync tabs 

Expected results:

log in should accept my authentication like it always has access to my dang account

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1340)
┆Issue Number: FXA-1340

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

we'll do this in bugzilla
