### ISSUE TITLE
Add cloudops deploy bot to #fxa

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4507]
From planning:

|----|
|Make bot show deploy started|
|Make bot show deploy failed (w/ message)|
|Make bot show deploy finished|

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1345)
┆Issue Number: FXA-1345

**Comment by imskr** [comment]
I would like to add this feature.

**Comment by chenba** [comment]
(manually updated assignee because data-sync couldn't)
