### ISSUE TITLE
Add CodeCov Support

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#4508]
## Description
Add codecov for coverage report on every PR
Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1348)
┆Issue Number: FXA-1348

**Comment by imskr** [comment]
@rfk Can I add codecov support to Fxa repo?

**Comment by clouserw** [comment]
We already have coveralls support in FxA so probably not, but I'll ping @vbudhram to see how that issue is going.  Thanks

**Comment by imskr** [comment]
Okay thanks @clouserw

**Comment by vbudhram** [comment]
Hey @imskr I'm going to close this because we started adding coveralls support in https://github.com/mozilla/fxa/pull/4016.

**Comment by imskr** [comment]
@vbudhram I think it will be nice to see coverage report on every pull request and codecov can do that. codecov.io
