### ISSUE TITLE
Check to ensure relying parties only request OAuth scopes they are allowed to

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#452]
Follow on from [discussion in #2969](https://github.com/mozilla/fxa-auth-server/pull/2969/files#r269182194). Untrusted relying parties are only allowed to request scopes from a [fixed set of possibilities](https://github.com/mozilla/fxa-auth-server/blob/40b65eeb05a11437ae32cbf4b2ed06e30d71f261/fxa-oauth-server/lib/routes/authorization.js#L278). Trusted RPs may request any scope, whether known or not, with the caveat that [unexpected key bearing scopes cause an invalidScope error](https://github.com/mozilla/fxa-auth-server/pull/2969/files#diff-73b4c94cdb4b0d54e7778a35a862ad12R76).

A more robust set of checks would require all relying parties, trusted or not, to only request scopes from a fixed set. We could go so far as to require relying parties to register up front which scopes they may possibly request and ensure the requested scopes are a subset of that list, similar to the Google flow when setting up a new OAuth integration.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-643)
┆Issue Number: FXA-643

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We already require RPs to tell us what scopes they will access when they register.  We should enforce that list.

Additionally, we should clarify trusted vs untrusted RPs – there may no longer be a distinction.
