### ISSUE TITLE
Incorrect devices location

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4523]
**Build:**
Prod [Train 1.161.0]

**Affected platforms:**
Windows 10 x64
Mac OS X 10.14.6

**Steps to reproduce:**
1. Sign in with a Firefox account on multiple devices. 
2. Sync all devices.
3. Go to account settings and check the list of Devices.
4. Verify the location of each device.

**Expected results:**
The devices location is correctly displayed.

**Actual Results:**
The location of some of the devices is wrongly reported.

![Screenshot_18](https://user-images.githubusercontent.com/18114210/76528234-2737a500-6479-11ea-8d8f-15a6390f3e06.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1352)
┆Issue Number: FXA-1352

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

What would you expect to see?  Is the City wrong?

**Comment by vasilicatamas** [comment]
> ➤ Wil Clouser commented:
> 
> What would you expect to see?  Is the City wrong?

Yes, The city was wrong but noticed that this issue is no longer reproducing on FxA Prod [1.162.1].
Based on this I am closing the bug.
![Screenshot_2](https://user-images.githubusercontent.com/18114210/76942934-34d0ad00-6907-11ea-8956-6220afd1e6cf.png)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Ok. Sounds good.  For the record, being close-ish is about as good as we can do here (close-ish being, maybe, 200km?).  So, a neighboring city wouldn't be unheard of, but it depends on how the infrastructure around the area is organized.
