### ISSUE TITLE
[train-162] create v1.162.1 tag with fix for event-broker uuid dependency

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4542]
i.e., cherry-pick https://github.com/mozilla/fxa/commit/0d989878c513991a2f39b5eac4971be10b071853 to train-162 (or whatever the right procedure is).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1371)
┆Issue Number: FXA-1371

**Comment by dannycoates** [comment]
done #4550

**Comment by jrgm** [comment]
This was done.
