### ISSUE TITLE
[RTL] Fix padding for the account deletion section

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/fxa#4559]
See [bug 1594549](https://bugzilla.mozilla.org/show_bug.cgi?id=1594549).

Relevant code:
https://github.com/mozilla/fxa/blob/168ae14fa01dfa6f12a278dc69dda2c531259433/packages/fxa-content-server/app/styles/modules/_settings.scss#L417-L426

Both `padding-left`s should be extracted to a `html[dir='ltr']`, and another 2 `html[dir='rtl']` should be added with the respective `padding-right`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1377)
┆Issue Number: FXA-1377

**Comment by ItielMaN** [comment]
cc @chenba, who might be interested in fixing this.

**Comment by imskr** [comment]
Is this assigned??

**Comment by vladikoff** [comment]
@imskr yeap 
![image](https://user-images.githubusercontent.com/128755/76921602-d541b580-68a4-11ea-9ae2-fb0a878b650f.png)

**Comment by chenba** [comment]
@ItielMaN Fix has been merged.  Thanks!
