### ISSUE TITLE
Add Gmail Actions to Confirmation Emails

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#456]
Let's increase our email confirmation clickrates and login confirmation clickrates by using email actions.

https://developers.google.com/gmail/markup/actions/actions-overview

**Comment by philbooth** [comment]
It was on me to check whether these are working in prod, and they are.

Next step was to check through our templates to audit which emails have them set up. This is what I found:

Template|Action|Format|CTA in body
--------|------|------|-----------
`lowRecoveryCodesEmail`|-|-|Generate codes
`newDeviceLoginEmail`|-|-|Manage account
`passwordChangedEmail`|-|-|-
`passwordResetEmail`|-|-|-
`passwordResetAccountRecoveryEmail`|-|-|Create new recovery key
`passwordResetRequiredEmail`|-|-|First, change your Firefox Account password.
`postAddAccountRecoveryEmail`|-|-|Manage account
`postAddTwoStepAuthenticationEmail`|-|-|Manage account
`postChangePrimaryEmail`|-|-|Manage account
`postConsumeRecoveryCodeEmail`|-|-|Manage account
`postNewRecoveryCodesEmail`|-|-|Manage account
`postRemoveAccountRecoveryEmail`|-|-|Manage account
`postRemoveSecondaryEmail`|-|-|Manage account
`postRemoveTwoStepAuthenticationEmail`|-|-|Manage account
`postVerifyEmail`|-|-|Connect another device
`postVerifySecondaryEmail`|-|-|Manage account
`recoveryEmail`|-|-|Create new password
`unblockCodeEmail`|-|-|-
`verificationReminderFirstEmail`|Confirm email|ldjson|Confirm email
`verificationReminderSecondEmail`|Confirm email|ldjson|Confirm email
`verifyEmail`|Verify Email|microdata|Activate now
`verifyLoginEmail`|-|-|Confirm sign-in
`verifyLoginCodeEmail`|-|-|-
`verifyPrimaryEmail`|-|-|Verify email
`verifySecondaryEmail`|-|-|Verify email
`verifySyncEmail`|Verify Email|microdata|Verify email

I can add them to the emails that don't have them. I'll also change the existing microdata ones to ldjson.

**Comment by davismtl** [comment]
@philbooth It occurred to me that the login and registration code work that @shane-tomlinson is doing may make this work useless. 🤦🏼‍♂️

Let me know if I'm missing something...

@shane-tomlinson will you be rolling out codes to all login and registration emails?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson will you be rolling out codes to all login and registration emails?

Woah, Nelly! Doing all confirmation types is huge undertaking, I'm going for registration emails right now.

**Comment by davismtl** [comment]
> Doing all confirmation types is huge undertaking,
There's no doubt.

Do we think it'll be some time before we start on login emails?

@shane-tomlinson , do we think @philbooth should add email actions if they may become obsolete in x amount of time?

**Comment by shane-tomlinson** [comment]
> Do we think it'll be some time before we start on login emails?

I thought login emails could already have code behavior, it's just that it's enabled on an RP by RP basis.

**Comment by shane-tomlinson** [comment]
> I thought login emails could already have code behavior, it's just that it's enabled on an RP by RP basis.

@vbudhram - can you confirm or deny this statement?

**Comment by philbooth** [comment]
Note that, since #2535 landed, all emails get this automatically as long as they set the properties `oneClickLink` and `action` in the template data. Right now that is all our emails that have a CTA button, so I think there's nothing more to do here.

Closing, the changes will be visible in prod in train 146.
