### ISSUE TITLE
Secondary email address is not updated without stats refresh when it is set as primary on another browser

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/fxa#4561]
**Platforms:**
Windows pro 10 64-bit 
Android 8.0.0

**Build:** 
Firefox 74.0  (stage configuration)   -Browser A
Firefox Nightly 76.0a1 (stage configuration)  - Browser B 
Fennec 68.5.0  (stage configuration)  - Browser C
Firefox 74.0 (production)

### Steps to reproduce
1. Log in on multiple browsers (A with primary email X. 
2. Navigate to Manage Account page and add secondary email and refresh all manage account pages browser pages on the browsers the account is now logged in. 
3. After the secondary email is verified on all browsers, leave Manage account section open an all browsers. 
4. On browser A open Secondary email section and set secondary email as primary. Observe that secondary email address is updated. 
5. view account primary and secondary email address on browser B and C. 

### Expected result

Primary and secondary email are refreshed and updated after automatic sync. 

### Actual result
Only primary email address is updated, while secondary email address requires a status refresh or page refresh in order to be updated. 

![secondary email is not updated without status refresh](https://user-images.githubusercontent.com/53306802/76772814-2f118500-67aa-11ea-8f75-ec1e882cd59d.gif)

**Notes:**
1. This is reproduced on both stage and production environments. 
2. tested and reproduced windows to windows browser and windows to android.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1378)
┆Issue Number: FXA-1378

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing.  This will probably be fixed (and/or change) with the settings refresh happening soon.  However, this isn't something we're going to spend time on right now.  Thanks

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closing
