### ISSUE TITLE
Possible Breakage in FxA App (Hamburger) Menu Telemetry in Version 73 [bz1617285]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4566]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1617285

[This chart](https://sql.telemetry.mozilla.org/queries/68484/source#172975) shows that the volume of events related to the FxA hamburger menu menu seem to be in a freefall from around the time 73 went to release. 

A similar thing has NOT happened to the toolbar menu telemetry.

edit, talking about [these](https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/Events.yaml#711) events, they have not expired.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1379)
┆Issue Number: FXA-1379

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This was fixed in the latest FF release, https://bugzilla.mozilla.org/show_bug.cgi?id=1617285#c2.
