### ISSUE TITLE
Track list of services the user has signed in to

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#459]
Right now we only know which services the user has a current access or refresh token for, once those tokens expire and are purged, we lose that knowledge.

This means:
* We have no way of notifying the user which services may hold data about them.
* We have to notify *all* services when a user deletes their account (or makes other account information updates).

cc @bbangert 

blocks #472

**Comment by bbangert** [comment]
@shane-tomlinson Which issue is this blocking?

Also per previous discussion:

- When we track this information we should know what scopes were shared with the RP as well.
- Should we broadcast token rejections to RPs?

**Comment by shane-tomlinson** [comment]
Dup of https://github.com/mozilla/fxa/issues/711, closing.
