### ISSUE TITLE
Secondary email “Refresh status” button is gray instead of blue

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4602]
**Build:**
Stage [Train 1.163.0]

**Affected platforms:**
Windows 10 x64
Android 9

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox Account.
2. Navigate to Manage account page.
3. Click on the “Add...” button from the “Secondary email” section.
4. Insert a valid email address in “secondary email” field and click on “Add” button.

**Expected results:**
”Refresh status” button is blue. (eg "Refresh status" buttons from Account recovery and Devices @ apps sections)

**Actual Results:**
”Refresh status” button is gray. 

![Screenshot_8](https://user-images.githubusercontent.com/18114210/77180215-4619e500-6ad2-11ea-91b7-7cc285e00ac8.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1392)
┆Issue Number: FXA-1392

**Comment by imskr** [comment]
I would like to work on this @vasilicatamas

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [1.164.0] under Windows 10 64-bit, iOS 13.1.2 and Android 9. ”Refresh status” button from Secondary email section is blue.

![Screenshot_14](https://user-images.githubusercontent.com/18114210/77770349-c8b02080-704d-11ea-9e96-34bde5f23d57.png)
