### ISSUE TITLE
fxa-content-server mocked Statsd is undefined.

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#4608]
fxa-content-server mocked Statsd is undefined.

https://github.com/mozilla/fxa/blob/00e4ecd27059a80f07d90d8ad4535209e1bf6557/packages/fxa-content-server/server/lib/statsd.js#L11-L17

and will cause error in
https://github.com/mozilla/fxa/blob/00e4ecd27059a80f07d90d8ad4535209e1bf6557/packages/fxa-content-server/server/lib/flow-event.js#L215

It should be
```javascript
 const noopStatsd = () => { 
   const mock = {}; 
   Object.keys(StatsD.prototype).forEach(x => { 
     if (typeof StatsD.prototype[x] === 'function') { 
       mock[x] = NOOP; 
     } 
    return mock;
   }); 
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1394)
┆Issue Number: FXA-1394

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

This was fixed and release as part of v1.163.1.  Thanks!
