### ISSUE TITLE
[email-service] improve error logging on sending to SES failure

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4635]
We've experienced some intervals where email sending by the email-service reports sporadic failures for while and then this goes away. A logging message for a failure looks like this:
```
=> Outcome: Success                                                                                                                                 
{"Logger":"fxa_email_service-1.163.0","Type":"fxa_email_service:log","Pid":1,\                                                                      
 "Severity":3,"Timestamp":1585064578350505995,"Fields":{                     \                                                                      
   "msg":"Request errored","code":500,"error":"Internal Server Error",       \                                                                      
   "errno":100,"message":"","additional_fields":"{}"}}                                                                                              
=> Response succeeded. 
```
Is it possible to include more contextual information in that error message (e.g., the email address involved, meta-data for the message being sent (template), details from SES response (or making it clear that it wasn't SES related if it didn't get that far), other context that might be available. The above message doesn't give us much to go on, or to pursue with AWS support. Thanks in advance.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1402)
┆Issue Number: FXA-1402

**Comment by jrgm** [comment]
Ops could use this in a sooner-than-later train.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm nervous about including the email address, but the other data seems good.  Is this going into a PII friendly place?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Update:  If this goes in to bigquery, we can include the email.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

These errors are logged with more detail to Sentry, which indicates these are AWS throwing an internal error. Since we can't fix AWS (but we can let them know via the Sentry error AWS request-id), we are not going to add more detail to the error message at this time.
