### ISSUE TITLE
Update profile server to Hapi 19

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#4650]
After https://github.com/mozilla/fxa/pull/4607 lands we should make the necessary changes for Hapi 19.
See https://www.npmjs.com/package/@hapi/hapi

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1408)
┆Issue Number: FXA-1408

**Comment by imskr** [comment]
I would like to fix this @vladikoff
