### ISSUE TITLE
[fxa-admin-panel] implement __lbheartbeat__ and __version__ routes

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4659]
As noted here - https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-StandardEndpoints

I'll workaround the missing lbheartbeat route, but we'll need both these routes to use normally in production.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1415)
┆Issue Number: FXA-1415

**Comment by jrgm** [comment]
Note: The version route should read from the version.json file contained in the docker image.

**Comment by LZoog** [comment]
@jrgm this is a dupe of #4410 which @jodyheavener almost has finished (and with CSP!), closing.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

marking dup
