### ISSUE TITLE
Add a route specifically for generating the "devices and apps" list on the settings page

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#466]
The "devices and apps" list on the settings page currently pulls in data from two different sources:

* The auth-server's `/sessions` endpoint, which includes all device records that have a `sessionToken`.
* The oauth-server's `/client-tokens` endpoint, which lists each connected OAuth client, but which doesn't distinguish between multiple instances of the same client (ref https://github.com/mozilla/fxa-auth-server/issues/2928)

And it does a bit of a complex sort-and-merge to produce the final list of all the things connected to the user's account.

As we work to [allow OAuth clients to access the devices API](https://github.com/mozilla/fxa-auth-server/issues/2547), managing that view is only going to get more complex.  I suggest we simplify it by creating an auth-server endpoint specifically for this purpose.

Strawman: add a new route `GET /v1/account/connected_clients`, authenticated with a `sessionToken`, that lists all of the things connected to the user's account.  Each entry returned by this endpoint would correspond precisely to an entry in the "devices and apps" list:
    * One entry for each device record (Firefox, Fenix, Reference Browser)
    * One entry for each OAuth refresh token that isn't owned by a device record (Monitor, Send, Lockbox)
    * One entry for each OAuth client_id that has live access tokens that don't tie back to a refresh token (Pocket, I'm looking at you...)
    * One entry for each sessionToken that isn't owned by a device record (web sessions)

We *could* synthesize an equivalent list on the client side by requesting the individual lists and merging them, but it seems like it would be both more responsive and more reliable to do this work on the server.  

The new route would aim to **replace** the current `/sessions` and `/client-tokens` routes, which IIUC are only called from web content for the purposes of rendering the "devices and apps" list.  Hopefully this would address earlier concerns about proliferating new routes and new maintenance burdens as we do the oauth-devices work.

@shane-tomlinson @vladikoff thoughts?

**Comment by vladikoff** [comment]
new cases to handle: 

There is a notes webextension and an android app:

![image](https://user-images.githubusercontent.com/128755/56833751-5fbc9900-683d-11e9-9d53-3d34f87ae2c5.png)

Fenix is now gonna be called "Firefox Sync" in the list. So that needs to be reorganized
