### ISSUE TITLE
Payment flow - Localization Updates (result of l10n/Fluent review)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4668]
After discussions with the l10n and Fluent teams, we need to make the following updates for our payment flow translations:

1. Update `fluent` packages in payments
2. Update our currency formatting to use Fluent, which will take into account the currency and the locale for display
3. Update our date display to use Fluent

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1419)
┆Issue Number: FXA-1419

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

PR: https://github.com/mozilla/fxa/pull/4687

**Comment by jackiemunroe** [comment]
Closed with https://github.com/mozilla/fxa/pull/4935
