### ISSUE TITLE
[v1.164.0][stage] &amp shown in Subscriptions &amp; Payments

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4670]
![image](https://user-images.githubusercontent.com/758162/77701070-af867180-6f72-11ea-9e8b-b4176b77f5ad.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1425)
┆Issue Number: FXA-1425

**Comment by jrgm** [comment]
https://accounts.stage.mozaws.net/settings

**Comment by lmorchard** [comment]
Looks like this was also reported by QA (#4675) and fixed (PR #4676)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

marking dup
