### ISSUE TITLE
Subscriptions & Payments incorrectly displayed in FxA settings page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4675]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- macOS 10.14.6

#### Steps to reproduce
1. Go to the [Full-Device VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page.
2. Create a subscription.
3. Go to the [Firefox Accounts](https://accounts.stage.mozaws.net/settings) settings page.
4. Look at the **Subscriptions & Payments** section.

#### Expected result:
- **Subscriptions & Payments** is displayed.

#### Actual result:
- `Subscriptions &amp; Payments` is displayed.

![image](https://user-images.githubusercontent.com/17178945/77745811-9fc76580-7024-11ea-825b-85776b89f583.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1428)
┆Issue Number: FXA-1428

**Comment by bsurd** [comment]
Checked in stage and the issue is still reproducible. Will this land with train 164 or train 165?

**Comment by lmorchard** [comment]
Looks like 165 - train 164 was tagged on Thursday, this was merged on Friday, so this will not make it to stage until next week.

**Comment by LZoog** [comment]
Hey @bsurd, we actually ended up including this in a point release for train 164. It should be on stage soon.

**Comment by bsurd** [comment]
Verified in the latest stage environment, the issue is no longer reproducible. Marking as verified.
