### ISSUE TITLE
Local Installation Error

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#4688]
## Description
`npm install` shows error
### Steps to reproduce
After clone
- run `npm install

### Expected result

Install all dependencies successfully

### Actual result

lerna info Installing external dependencies
lerna ERR! npm install --no-save exited 1 in 'browserid-verifier'
lerna ERR! npm install --no-save stderr:
npm WARN tarball tarball data for underscore@1.9.1 (sha512-5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for foreachasync@3.0.0 (sha1-VQKYfchxS+M5IJfzLgBxyd7gfPY=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for express@4.16.4 (sha512-j12Uuyb4FMrd/qQAm6uCHAkPtO8FDTRJZBDd5D2KOL2eLaz1yUNdUB/NOIyq0iU4q4cFarsUCrnFDPBcnksuOg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for underscore@1.9.1 (sha512-5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open '/home/shubham/Github/fxa/packages/browserid-verifier/node_modules/.staging/express-e34cf377/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/shubham/Github/fxa/packages/browserid-verifier/node_modules/.staging/express-e34cf377/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/shubham/Github/fxa/packages/browserid-verifier/node_modules/.staging/express-e34cf377/Readme.md'
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting underscore@1.9.1:
npm ERR! Verification failed while extracting underscore@1.9.1:
npm ERR! sha512-5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg== integrity checksum failed when using sha512: wanted sha512-5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg== but got sha512-r+hJPOswzdrrHahfLSAHaf5LiR0rAqu81Fi9KD1/cZv5FwslYLorStFWPjBplx5rOeimjosudoRdUY8QCzcyow==. (34137 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shubham/.npm/_logs/2020-03-29T14_32_47_249Z-debug.log

lerna ERR! npm install --no-save exited 1 in 'browserid-verifier'
lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa@2.0.0 postinstall: `_scripts/install_all.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Environment
- `ubuntu 19.10`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1439)
┆Issue Number: FXA-1439

**Comment by vladikoff** [comment]
```
npm WARN tarball tarball data for underscore@1.9.1 (sha512-5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for foreachasync@3.0.0 (sha1-VQKYfchxS+M5IJfzLgBxyd7gfPY=) seems to be corrupted. Trying one more time.
```

seems like an npm install issue
