### ISSUE TITLE
[iOS] Paste option does not appear on long tap on an empty field

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4690]
**Build:**
Stage [Train 1.164.0]

**Affected platforms:**
iOS 13.1.2

**Steps to reproduce:**
1. Launch Firefox app.
2. Go to menu -> Sign in to Sync
3. Long tap on Email/Password field. 

**Expected results:**
Paste option is successfully displayed on long tap on an empty field. 

**Actual Results:**
“Select all” option is displayed on long press on an empty field.

![Screenshot_19](https://user-images.githubusercontent.com/18114210/77925637-c5b36b00-72ad-11ea-9de5-7fcae57aa78a.png)
![Screenshot_17](https://user-images.githubusercontent.com/18114210/77925528-a0bef800-72ad-11ea-8623-89fc690647ee.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1440)
┆Issue Number: FXA-1440

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Hmm, I can't seem to replicate. Is this new in stage, or are you experiencing it in production as well? Can you confirm that the text you are trying to paste is paste-able in another app to verify that it is indeed in your clipboard?

**Comment by vasilicatamas** [comment]
I did not manage to reproduce this issue anymore, probably I failed to copy the code to clipboard. Thanks Jody for looking into this! 

![Screenshot_24](https://user-images.githubusercontent.com/18114210/78157329-80777080-7448-11ea-9d03-aece0dbb77e2.png)
