### ISSUE TITLE
Avatar Selection and Adjustments

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#47]
I want to be able to choose, upoload, and adjust (move, rotate, zoom, etc) my Avatar for Firefox Accounts.

**Comment by edmoz** [comment]
test

**Comment by edmoz** [comment]
test 2

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-26
