### ISSUE TITLE
Discuss: Continue to consider fully verified sessions fully verified after enabling 2FA

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#470]
More users than I would have expected complain they have lost their 2FA device and are [unable to disable 2FA](https://github.com/mozilla/fxa-content-server/issues/6767) from a [device that has been connected to Sync for a long time](https://github.com/mozilla/fxa-bugzilla-mirror/issues/533).

On an account with 2FA enabled, we only consider a session fully verified if the session was verified with 2FA as well, even if that session was created before enabling 2FA.

I understand the rationale for this policy, but it feels like a roadblock that is causing a lot of user frustration, for perhaps minimal gain.

What if we relax this restriction to say that sessions that are considered fully verified when 2FA is enabled remain fully verified? This change would enable devices that have been connected since before 2FA was enabled to continue to perform account operations w/o asking for a 2FA code.

To mitigate risks associated with the change of policy, we could show a "audit your sessions and devices" view after a user enables 2FA.

**Comment by vbudhram** [comment]
This fix has been landed and will be released in train 137.
