### ISSUE TITLE
“Rotate” button highlighter overlaps the “Change” and “Cancel” buttons

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4712]
**Build:**
Prod [Train 1.164.0]

**Affected platforms:**
Windows 10
Android 9

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox account.
2. Navigate to Account Settings page.
3. Click "Add" button from the Account picture area.
4. Upload a picture.
5. Click on “Rotate” button.

**Expected results:**
”Rotate” button is correctly displayed.

**Actual Results:**
Rotate highlighter is displayed over “Change” and “Cancel” buttons

Android 9 
![Screenshot_21](https://user-images.githubusercontent.com/18114210/78141517-44d2ab80-7434-11ea-9c8a-60bbceea1a47.png)

Windows 10
![Screenshot_20](https://user-images.githubusercontent.com/18114210/78141522-469c6f00-7434-11ea-94a1-f69ec7964cf7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1456)
┆Issue Number: FXA-1456

**Comment by jodyheavener** [comment]
@vasilicatamas Just to clarify, do you mean specifically that the focus border overlaps the buttons and that there should be more space between?

**Comment by vasilicatamas** [comment]
> @vasilicatamas Just to clarify, do you mean specifically that the focus border overlaps the buttons and that there should be more space between?

Yes, this is what I wanted to say.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.167.1] under Windows 10 64 bit, Android 9 and iOS 13.1.2. Focus border of the "Rotate" button does no longer overlap the "Change" and "Cancel" buttons,
![Screenshot_3](https://user-images.githubusercontent.com/18114210/79852894-f92a7680-83cf-11ea-88fe-419d5e2a78a1.png)

![Screenshot_4](https://user-images.githubusercontent.com/18114210/79853024-2bd46f00-83d0-11ea-8975-706936c9babb.png)
