### ISSUE TITLE
Product details in Set up your subscription page are not accurate

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4713]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit), Android 9

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button
3. Click on Show details

#### Expected result:
- The info displayed is accurate

#### Actual result:
- The last detail displayed mentions the product is available on windows, ios and android
![image](https://user-images.githubusercontent.com/15685441/78148061-0db4c800-743d-11ea-85b5-d6d0cebab4ff.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1457)
┆Issue Number: FXA-1457

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

These details will be correct when this feature launches

**Comment by madalincm** [comment]
We will postpone verifying the issue after the launch. Thanks John for the comment.
