### ISSUE TITLE
Incorrect text billing information section

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4715]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit), Android 9

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button
3. Observe the text displayed in the billing information section next to the checkbox

#### Expected result:
- The info displayed is as in mockups

#### Actual result:
- The text displayed is "I authorize Mozilla, maker of Firefox" (In mockups is displayed as "I authorize Mozilla, the maker of Firefox")
![image](https://user-images.githubusercontent.com/15685441/78150816-781b3780-7440-11ea-8124-2fbbccd305d1.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1458)
┆Issue Number: FXA-1458

**Comment by madalincm** [comment]
Also there is another inconsistency in the text under the pay now button:
![image](https://user-images.githubusercontent.com/15685441/78152591-b154a700-7442-11ea-9462-ec15871dac25.png)

**Comment by data-sync-user** [comment]
➤ David Justice commented:

This was updated in [~jmunroe@mozilla.com] recent changes. Her copy may be more up to date than the designs. cc/ [~jmunroe@mozilla.com]

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

the mockup is incorrect here

**Comment by madalincm** [comment]
@johngruen  Thanks for clarification. Marking this bug as invalid.
