### ISSUE TITLE
The redirect notification to the product download page is not displayed in the payment confirmation page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4716]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- Samsung Galaxy S7 (Android 7)
- Google Pixel 2 XL (Android 8)

#### Preconditions:
- Have a FxA account without an active subscription.

#### Steps to reproduce
1. Go to the FPN [vpn](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page and sign in.
2. Make a subscription.
3. Observe the layout on the payment confirmation page.

#### Expected result:
- A green redirect notification is displayed in the top of the page.

#### Actual result:
- No notification is displayed.

![image](https://user-images.githubusercontent.com/17178945/78150793-705b9300-7440-11ea-84ca-5a3b2c42d48a.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1460)
┆Issue Number: FXA-1460

**Comment by lmorchard** [comment]
I think this is an FPN / Guardian issue and not an FxA issue? (Unless an FxA backend issue is causing it over on FPN)

**Comment by data-sync-user** [comment]
➤ David Justice commented:

This notification was cancelled by product, the design was just never updated. Assigning [~jgruen@mozilla.com] for verification.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Yes, this is as expected for improved A11y

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

We're cancelling this work due to A11y concerns about the redirect
