### ISSUE TITLE
Taping zip code field is opening an alphanumeric keyboard

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4717]
#### Affected versions:
- All Firefox, chrome

#### Affected Platforms:
Android 9

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button
3. Tap inside the zip code field

#### Expected result:
-  A numeric only keyboard id displayed.  (all the rest of the fields that accept only numeric values open a numeric keyboard)

#### Actual result:
- An alphanumeric keyboard is diplayed. 
![image](https://user-images.githubusercontent.com/15685441/78153725-0fce5500-7444-11ea-85c1-ff8279d04dea.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1461)
┆Issue Number: FXA-1461

**Comment by vladikoff** [comment]
> A numeric only keyboard id displayed. (all the rest of the fields that accept only numeric values open a numeric keyboard)

For example postal zip code is i.e: "M9A 3J9", so I need an alphanumeric keyboard to type that in

**Comment by lmorchard** [comment]
This seems similar to an issue we had with the keyboard used for verification codes on content-server. I think there were some accessibility concerns there that led us to WONTFIX? Might not be the same issues

https://github.com/mozilla/fxa/issues/4281

**Comment by jodyheavener** [comment]
Worth noting that the input currently does not allow you to input alphabetic characters anyway. In the future we will need to remove that limitation to support non-US ZIP codes. Barring accessibility issues I'd prefer a numeric keyboard.

**Comment by jodyheavener** [comment]
Given the accessibility concerns and the eventual expansion to postal zip codes I'm going to call this wontfix for now

**Comment by madalincm** [comment]
@jodyheavener  thanks for the clarifications. I am marking this bug as wontfix.
