### ISSUE TITLE
Support notifying reliers of account deletions via HTTP requests

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#472]
Right now whenever a user deletes their account we notify reliers via SNS/SQS. This places a requirement on reliers to connect to one of these services, which isn't awesome for several reasons:

1. As a company we are largely migrating to GCP.
2. Each relier has to enable and pay for SQS.

We could simplify this by having OAuth reliers register an endpoint to call whenever the user deletes their account.

To avoid notifying reliers the user never signed in to, we'd need to keep a list of reliers the user has ever signed in to and only notify those.

Ref https://github.com/mozilla/blurts-server/issues/710

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-653)
┆Issue Number: FXA-653

**Comment by clouserw** [comment]
let's use the event broker: https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events
