### ISSUE TITLE
Firefox logo and user icon from the set up subscription and payment confirmation pages are not working

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4724]
#### Affected versions:
- All Firefox, chrome

#### Affected Platforms:
Android 9

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Tap the Subscribe now button.
3. Tap the Firefox logo from the header.
or
4. Tap the user icon.

#### Expected result:
Step 3: The Firefox page is opened in a new tab.
Step 4: The dropdown menu is opened.

#### Actual result:
For both Step 3 & Step 4 nothing happens.

#### Notes
The issue is also reproducing in the payment confirmation page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1469)
┆Issue Number: FXA-1469

**Comment by data-sync-user** [comment]
➤ David Justice commented:

Product decided that the avatar will not be a dropdown menu in this flow. Though Firefox logo should probably still be a link.

cc/ [~jgruen@mozilla.com]

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Not sure to what...i don't think we need to give users the opportunity to accidently exit the flow here. Let's WONTFIX this.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

See comments on the issue

**Comment by madalincm** [comment]
@johngruen  It makes sense to not let the user exit the payment flow but the issue is also reproducing in the payment confirmation page:
![image](https://user-images.githubusercontent.com/15685441/78751646-4a237f00-797b-11ea-9243-927b59cbb3cf.png)

Taping the firefox logo and the user icon in this page has no results. Do we want to change the behaviour in this page and mark the bug as wontfix?
