### ISSUE TITLE
The subscription fields display the placeholder values in Manage subscription

### ISSUE THREAD

**Issue by heres-maria** [mozilla/fxa#4726]
**[Affected Versions]:**
- Firefox 68.6.0
- Firefox for iOS 24
- Firefox Release 74.0 (Build ID  20200309095159)

**[Affected Platforms]:**
- Android 10
- iOS 12.4.5
- iOS 13.3.1
- Windows 10 (x64)

**[Prerequisites]:**
- You are signed into the site using the sign-in option from the [Full-Device VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page.
- You have subscribed to Firefox Guardian.

**[Steps to reproduce]:**
1. Click the “Manage subscription” option from the account icon menu (click the “Sign In” button if necessary)
2. Click the “Change” button.
3. Observe the data displayed in the fields.

**[Expected results]:**
- The data entered when creating the subscription are displayed.

**[Actual results]:**
- The placeholder values of the fields are displayed.

**[Notes]:**
- Attached is a screenshot of the issue.
![placeholder](https://user-images.githubusercontent.com/53752296/78236930-5757ee00-74e3-11ea-83c8-eafd3f716009.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1471)
┆Issue Number: FXA-1471

**Comment by jodyheavener** [comment]
I almost think this needs an additional section that shows you the current card's brand, expiry, and last 4 digits (we do not have access to nor would we want to display the full CC number in the input), in addition to the update fields.

**Comment by lmorchard** [comment]
> The data entered when creating the subscription are displayed.

Yeah, as far as I'm aware, this is not exactly possible. For privacy / security reasons, the billing update is write-only. We do not have access to fetch the existing details to fill in these fields.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

This is part of the same issue
