### ISSUE TITLE
Tier upgrade page is displayed with old UI

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4727]
#### Affected versions:
- All Firefox
- Chrome

#### Affected Platforms:
- Windows 10 (64-bit)
- Samsung Galaxy S7 (Android 7)
- Google Pixel 2 XL (Android 8)

#### Preconditions
- Have a FxA account with a tier 1 subscription

#### Steps to reproduce
1. Go to [123done](https://123done-stage.dev.lcip.org/) and sign in.
2. Upgrade to a tier 2 plan.
3. Observe the page layout.

#### Expected result:
-  The new tier upgrade page is displayed.

#### Actual result:
- The old tier upgrade page with broken UI is displayed.

![image](https://user-images.githubusercontent.com/17178945/78242082-157e7600-74ea-11ea-8db7-3709347187fc.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1472)
┆Issue Number: FXA-1472

**Comment by data-sync-user** [comment]
➤ David Justice commented:

Upgrades are not a part of these updates. They should not be a blocker for this release

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Upgrade flows are not covered in this epic...closing this as a dupe
