### ISSUE TITLE
What can we do to give Sentry more useful information for 500 errors?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#473]
Consider the following Sentry error:

https://sentry.prod.mozaws.net/operations/auth-prod/issues/5148811/?environment=prod

I can't identify a single useful piece of information about what went wrong, anywhere on that page. Nothing in the stack trace helps us, none of the error data, the tags. It's completely opaque.

Is there more information we could try to include at runtime that would help us debug these?

**Comment by clouserw** [comment]
Hopefully this gets addressed with #2345
