### ISSUE TITLE
Breakdown updated CWTS work in Q2

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#4739]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1478)
┆Issue Number: FXA-1478

**Comment by rfk** [comment]
Reference doc: https://docs.google.com/document/d/1EDzyi4SPf2Ou5Hkt2Ws8kOOIHmcVBCvPA9cNge6UBKk/

**Comment by vbudhram** [comment]
This is done
