### ISSUE TITLE
Fix error report AUTH-PROD-27

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#474]
Per Slack report. See https://sentry.prod.mozaws.net/operations/auth-prod/issues/5144403/?referrer=slack for details

**Comment by shane-tomlinson** [comment]
I wonder if we can find the equivalent report on the oauth server, the linked to error looks like the auth server's oauth translation layer.

**Comment by clouserw** [comment]
This link doesn't exist anymore.  closing...
