### ISSUE TITLE
Make product details configurable

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4741]
Need to determine if we want to store these in stripe or in our ftl files.

They are currently in ftl files. If we stick with this method we need to pass in the product name to the plan details to display the correct details in the list.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1484)
┆Issue Number: FXA-1484

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Do we have more details on this? Is it part of an epic?

**Comment by lmorchard** [comment]
While working on #3931, I notice that [this "Full-device VPN" string in PlanDetails is hardcoded and not localized](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/components/PlanDetails/index.tsx#L69).

Going to need a source for this string, as it will appear twice for upgrades too.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

[~lorchard@mozilla.com] this was the issue i wanted to file for upgrades (de-hardcoding these strings). Can you clarify what you mean by needing a source?

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

moving this to the upgradable subs epic

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

bq. Can you clarify what you mean by needing a source?

Source as in where does this subtitle string describing each product come from? Who writes them, where are they stored? It's not in Stripe metadata (yet?) and it's not in any L10n strings. I've only seen these in mockups. 

bq. moving this to the upgradable subs epic

It's not directly related to upgrades, though. This also includes the hardcoded product feature bullet points left over from the mobile UX changes

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Thanks that makes sense. I am happy to work with marketing to provide appropriate strings for each new product. I pulled this into upgradable subs b/c once we go live with this feature there will be two discrete products with two different sets of details, so we should resolve this now.

...maybe the way to do this would be to store these strings in ftl with a key that's based off of the product name we get from stripe? IE firefox-private-network-desc-1 (or whatever)..FWIW we are still only selling products in the US for the time being, so i think the issue of being able to add per-product descriptions is the immediate concern.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Putting together recent discussions, this task seems to be about making all product details configurable and localizable. From what I can tell, this issue includes these strings:

  * Product name
  * Product subtitle
  * Variable-length list of product benefits bullet points

Are there any others?
{quote}maybe the way to do this would be to store these strings in ftl with a key that's based off of the product name we get from stripe?
{quote}
Scratching my head on this, I think these strings belong in Stripe metadata properties rather than FxA FTL files:

  * Subscription product changes shouldn't require FxA deployments.
    * We maintain configurable product details as Stripe metadata ( https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#product-metadata ).
    * Stripe metadata can be changed independent of FxA deployment cycles.
    * FTL changes require deployments, which would tie product changes back to FxA trains.

  * Subscription product teams may want specific copy & localizations at certain time points (e.g. for marketing)
    * These aren't FxA localizations - they're localizations for other teams' products with their own content & plans.
    * We don't control the content or timing of Pontoon localizations, which complicates things for other teams.

  * Not every product will be available in every locale
    * A string added to FTL requests localization from all 94+ locale teams ( https://pontoon.mozilla.org/projects/firefox-accounts/ ).
    * For example, that seems like a waste for a product only available in en-US

  * We may need to share these localized strings with other Mozilla services
    * Other Mozilla services may need to use these localized product details - i.e. Fluent on FxA is not the only potential consumer
    * Stripe metadata is a central source of truth for all Mozilla systems dealing with subscription products (e.g. including subhub)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

As far as I can tell, Stripe doesn't have a ready-made solution for this. So we can invent a scheme. Let's say something like this for en-US as a base:

  * product:name = "Firefox Private Network"
  * product:subtitle = "Full-device VPN"
  * product:details:1 = "Device-level encryption"
  * product:details:2 = "Servers in 30+ countries"
  * product:details:3 = "Connects 5 devices with one subscription"
  * product:details:4 = "Available for Windows, iOS and Android"

Then, when we have localizations for these strings, we can tack a locale onto the metadata keys:

  * product:name:xx-pirate = "Firefox Private Network"
  * product:subtitle:xx-pirate = "VPN fer yer full-device"
  * product:details:1:xx-pirate = "Device-level encryption arr"
  * product:details:2:xx-pirate = "Servers is 30+ countries matey"
  * product:details:3:xx-pirate = "Connects 5 devices wit' one subscription"
  * product:details:4:xx-pirate = "Available fer Windows, iOS an' Android"

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Brief mention in the product meeting that l10n here is the lesser priority because products will be more common in ENclish. If that's the case, then I think sticking this stuff in Stripe metadata is even more important, since we'd really be wasting localizer effort throwing this info into FTL.

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

I would be hesitant to localize a Product name at all. The number one reason being is that it could cause confusion when a user looks at their billing statement from their credit card company.
