### ISSUE TITLE
Generic errors are displayed for invalid cvc, stolen card, lost card, insufficient funds situations

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#4747]
#### Affected versions:
- All Firefox, chrome

#### Affected Platforms:
Android 9, Win10

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn)
2. Click on the Subscribe now button
3. Follow the following scenarios:
a. Enter a test credit card number which should return a invalid cvc number
or
b. Enter a test credit card number which should return a stolen card error (card declined)
or
c. Enter a test credit card number which should return a lost card error (card declined)
or
d. Enter a test credit card number which should return an insufficient funds error

#### Expected result:
-  The error displayed are specific for the given situation:
a.  "Your card's security code is incorrect."
b. "Your card was declined"
c. "Your card was declined"
d. "Your card has insufficient funds."

#### Actual result:
- A generic error is displayed "Your transaction could not be processed. Please verify your credit card information and try again."

![image](https://user-images.githubusercontent.com/15685441/78342300-baa85580-75a1-11ea-94e7-ab5876dfb2f2.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1485)
┆Issue Number: FXA-1485

**Comment by lmorchard** [comment]
I think this is intentional: For security reasons, we don't want to reveal exact reasons like stolen card, lost card, etc. So we intentionally squash these into a prompt to verify the card details

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is intentional and has been discussed before.  We should update the test cases.  I saw https://github.com/mozilla/fxa/issues/2812 ( https://github.com/mozilla/fxa/issues/2812 ) which has some discussion and some links.

**Comment by madalincm** [comment]
@clouserw  thanks for clarifications. We will update the test cases. 
One of the reasons I have logged this issue is because the error messages are generic in create new sub flow but specific in update billing info (I considered we should had a consistency across all the flows)
For example for incorect cvc code we show a specific error in the update flow:
![image](https://user-images.githubusercontent.com/15685441/78752272-77bcf800-797c-11ea-9346-24a01b1bbcd1.png)

Should we mark this bug as invalid and open a new bug for the update flow to have generic message in there too?

**Comment by madalincm** [comment]
@lmorchard The generic error is shown also for insufficient funds. This might be confusing for the user  as we are warning him to verify credit card info when the user does not have enough funds.
![image](https://user-images.githubusercontent.com/15685441/78756772-02edbc00-7984-11ea-94c8-1b60b59824b8.png)

Do we want to use a generic error in this case?

**Comment by clouserw** [comment]
Let's ask @pwalm and @davismtl for final guidance that we can refer to in the future.
