### ISSUE TITLE
[question] is it possible to login to firefox account programmatically?

### ISSUE THREAD

**Issue by DictumMortuum** [mozilla/fxa#4762]
Hello,

I'm computer-savvy, but my family is not at all. So I try to make it easy for them. Is there any way to login to firefox account programmatically? My goal is that they have their bookmarks and passwords in their account, regardless of what laptop they use in our household.

Is this possible via the official accounts or do I need to selfhost?
If I need to selfhost, is there the possibility of using ldap as a backend?

Thank you in advance,
Dimitris

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1492)
┆Issue Number: FXA-1492

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Hi Dimitris, Thanks for filing this issue.  We don't offer this feature right now and it's not on our roadmap.
