### ISSUE TITLE
Testing for the survey component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4769]
Unit tests / coverage

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1495)
┆Issue Number: FXA-1495

**Comment by meandavejustice** [comment]
Survey component tests are completed in #5081. Will need to add testing for "survey is complete and removed" in the parent component once surveys are integrated.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~djustice@mozilla.com] What's the status of this?  What's the "parent component" in the description?
