### ISSUE TITLE
Firefox iOS: Long email or display name breaks layout on FxA management page

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#4775]
x-ref to https://github.com/mozilla-mobile/firefox-ios/issues/6353

## Description

Long email or display name breaks layout on FxA management page.

### Steps to reproduce

Create an account using a long email or add a long display name to an existing one.
Check the FxA management page.
Result: The page expands outside the viewport and can't be zoomed out. Also the left side of the page becomes truncated.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/5495083/78692751-56023900-78c8-11ea-9efa-4fc5c229dfc4.png">

### Expected result

Email/display name should not break layout of other elements on the page

### Actual result

All rows are cut off 

### Environment

Firefox iOS, master, iPhone 11

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1498)
┆Issue Number: FXA-1498

**Comment by vasilicatamas** [comment]
During this testing on Stage [Train 1.167.1] under Windows 10 64 bit, Android 9 and iOS 13.1.2 I found a new issue which is tracked separately in #5041. Considering that the FxA management page is correctly displayed and the email or display name are successfully interrupted by ellipses I am marking this bug as Verified. 

![Screenshot_6](https://user-images.githubusercontent.com/18114210/79862460-c9369f80-83de-11ea-9d73-6c5273cfb9b6.png)
