### ISSUE TITLE
Webpack content embeds 127.0.0.1

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4776]
From our ops meeting:

> Should have filed this as a bug, but the webpack content embeds http://127.0.0.1:3030 in the content. Could I have that with just relative URL?

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1499)
┆Issue Number: FXA-1499

**Comment by LZoog** [comment]
I believe this will be fixed when my branch `issues/4208` is merged.
