### ISSUE TITLE
Combine gen_keys.js from oauth into the auth gen_keys.js

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#478]
Combine gen_keys.js from oauth into the auth gen_keys.js

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-657)
┆Issue Number: FXA-657

**Comment by vbudhram** [comment]
@dannycoates Do you think we still need to do this? It seems like it might be useful to keep these separate since you might only need to generate one key?

**Comment by dannycoates** [comment]
> Do you think we still need to do this?

IDK. we prob don't need an issue for it
