### ISSUE TITLE
Web Login Flow Support for Fennec

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#48]
As a developer of services running on Firefox Mobile I want to be able to use a web login flow for Firefox Accounts to manage the experience and integration with other services (ie Hello).

**Comment by rfk** [comment]
Corresponding android client bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1161223

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-27
