### ISSUE TITLE
The contents of the subscription card fields are bolded

### ISSUE THREAD

**Issue by heres-maria** [mozilla/fxa#4805]
**[Affected Versions]:**
- All versions

**[Affected Platforms]:**
- All platforms

**[Prerequisites]:**
- You are on the [stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/) website.

**[Steps to reproduce]:**
1. Tap the “Subscribe Now” button.
2. Create an account and validate it.
3. Observe the “Card number”/”Expiration”/”CVC” fields’ placeholders.
4. Enter data in the fields and observe them.

**[Expected results]:**
- The contents of the three fields are not bolded.

**[Actual results]:**
- The contents of the three fields are bolded.

**[Notes]:**
- This issue is reproducible in “Manage Subscription” > “Change” (Billing Information) as well.
- While the issue is not visually observable on Firefox Release 75.0 (Build ID  20200403170909) (but observable on Chrome), inspecting the fonts reveals they have seemingly different weights.

![Untitled](https://user-images.githubusercontent.com/53752296/78880791-94c9f780-7a5e-11ea-9e78-13be6195b6ed.png)
![1586423958282](https://user-images.githubusercontent.com/53752296/78880868-b2975c80-7a5e-11ea-9f3c-820aba0336b2.JPEG)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1524)
┆Issue Number: FXA-1524

**Comment by data-sync-user** [comment]
➤ David Justice commented:

It appears that this bug is comparing placeholder text VS actual input values. These should have different color values and styles. assigned [~jgruen@mozilla.com] to confirm, feel free to assign back to me if the request is valid.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

let me verify when we walk through the funnel tomorrow in our product call...might be that this actually looks good
