### ISSUE TITLE
Show/Hide section when making a subscription changes its size when selected/deselected

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4806]
#### Affected Versions:
- All versions

#### Affected Platforms:
- Any mobile devices

#### Prerequisites:
- You are signed in on the [FPN VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site with an account with no active subscription.

#### Steps to reproduce:
1. Tap the **Subscribe Now** button.
2. In the **Set up your subscription** section tap on **Show details**.
3. While observing the section tap anywhere in the page to deselect **Show details**.

#### Expected results:
- The container remains the same.

#### Actual results:
- The container changes its size.

![20200409_143241](https://user-images.githubusercontent.com/17178945/78891281-ef1f8400-7a6f-11ea-87e3-2cd488fe3c9c.gif)

![image](https://user-images.githubusercontent.com/17178945/78891250-dc0cb400-7a6f-11ea-80f4-3fb78ae20ddf.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1525)
┆Issue Number: FXA-1525

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release. Tested on iOS 13.3.1 (iPhone 6S).
