### ISSUE TITLE
Explore creating a per-service metrics event for users currently signed in

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#481]
@rfk tells us that users signed into e.g. pocket via fxa don't communicate with our servers on a daily basis, so this may not be practical to do. But in theory it would be useful for us to have some kind of measurement of how often people are using fxa-relying services. Filing this issue so that maybe some time in the future it becomes do-able. 

In the meantime, we should work on https://github.com/mozilla/fxa-auth-server/issues/2552 so we at least know this for sync.

cc @davismtl

**Comment by philbooth** [comment]
Just noting there is some overlap here with #465.

**Comment by davismtl** [comment]
@loines do we close this? We sort of have this now.

**Comment by irrationalagent** [comment]
closing this, we have the oauth events now.
