### ISSUE TITLE
Update FPN Icon on content server

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#4837]
https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/images/icon-service-private-network.svg

once we get the new icon

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1552)
┆Issue Number: FXA-1552

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

[~jgruen@mozilla.com] Can I get a link to the new svg to replace with here?

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

[~jgruen@mozilla.com] Can I get a link to the new svg to replace with here?
