### ISSUE TITLE
Disable phase 2 recovery keys experiment?

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#4846]
We recently completed phase 2 of recovery key experiment and logged conclusions at 
https://docs.google.com/document/d/1fJA_wfrgVF4cuQVzoWqQh22kiejDHbXJrkzTNuVldII/edit#heading=h.49t9dg60lw6o. We determined that the feature would not have as big of an impact as originally thought.

@davismtl @irrationalagent Should we remove this experiment and default back to the `Connect another device` post verify email?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1555)
┆Issue Number: FXA-1555

**Comment by davismtl** [comment]
I hope to confirm this to you later today or this week. I think that we will need to make a choice in order to start executing on OKR 1.1. I'm discussing with @pwalm in a couple of minutes.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Let's disable this experiment. For the time being, we can revert back to connect another device post verify email.

Note that we may have an experiment where we disable `connect another device post verify` email again in the next month or so.
