### ISSUE TITLE
[E2E] Decide on E2E testing library

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4849]
Unit tests will, of course, be written in tandem with the creation of new components for this project. However, we're going to want some sort of E2E testing setup with Selenium like we do now in the `fxa-content-server`.

This might be a good opportunity to reflect on pain points using our current functional testing stack. Does theintern/leadfoot offer enough support or should we also explore conveniences NightmareJS, Playwright, Puppeteer, WebDriverIO, or another library offers? (FWIW, theintern/leadfoot has been deprecated in favor of just theintern/intern.)

At the very least, let's ensure we're using async/await syntax with these tests.

This `needs:discussion`. If we decide to use another framework, we'll want an ADR written to document why this decision was made. If we go with what we currently have, this issue can be closed.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1557)
┆Issue Number: FXA-1557

**Comment by LZoog** [comment]
@rbillings @ashrivastava-qa Tagging you here for insight, discussion, and/or comments.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Notes from a 4/16 meeting involving [~vbudhram@mozilla.com], [~jheavener@mozilla.com], [~rbillings@mozilla.com], [~ashrivastava@mozilla.com], and myself:

At the very least, we'll want to copy current tests, adjust them as needed, remove outdated tests, and use async/await. However, it does sound like it's worth identifying the painpoints of the current framework and outlining pros & cons of using another framework.

Pros of keeping theintern:

  * Current framework is straightforward by having helper functions and examples readily available
  * Might be more copy-and-pastable in new Settings E2E testing than starting from scratch (but would still need refactoring)

Cons:

  * Still requires a learning curve to understand how things work and are structured.
  * It's kind of clunky, would be a lot of effort to go refactor all tests to async/await and could be better to just rewrite them with another library
  * It's an older framework, a newer framework may offer greater support and features
  * Our tests are a little flaky, can another framework help mitigate false failures from CI?

Things to look into:

  * What are the learning curves on newer frameworks?
  * What features will we gain? I (Lauren) have had one issue with getting theintern to "tab" to something and verify focus changed.

Other notes

  * Playwright’s big claim to fame is testing in a variety of browsers. Is this a priority of FxA's?
  * Per Ankita, WebDriverIO should be much less flaky compared to theintern. WebDriverIO is also used by other teams at Mozilla and they have experience with it, can offer support, and like it.
  * Failures should take a screenshot.
  * Probably not Puppeteer - Firefox has experimental support?
  * Is Nightmare only headless? Not ideal.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~vbudhram@mozilla.com] if I recall correctly this will be something you pick up - but maybe that changes as we have moved onto the new swarming team setup. Does this need to be done before we pick Settings back up, or any particular sprint?

**Comment by LZoog** [comment]
I think this should be done in the first 1-2 sprints we're back on Settings in case an ADR needs to be written, given our plans for QA to help out with writing functional tests while we work on issues in tandem (after certain flows have passed manual testing).
