### ISSUE TITLE
Contacting support returns an error

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4889]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All platforms

#### Preconditions
- Have an active subscription.

#### Steps to reproduce
1. Go to the "Manage subscription" page.
2. Click on the "Contact support" button and complete the fields with valid data.
3. Click on the Send button.

#### Expected result:
- A message is displayed, telling the user that the ticket was sent to the support page.

#### Actual result:
- The "Hmm, we're having trouble with our system. We're working on fixing it for you and apologize for the inconvenience. Please try again later." error message is displayed.

![image](https://user-images.githubusercontent.com/48829350/79108806-c6ed9900-7d7f-11ea-886d-d29908f8953d.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1596)
┆Issue Number: FXA-1596

**Comment by chenba** [comment]
The plan name was removed in #4693 but the support ticket still requires a plan (https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/support.js#L48).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

https://github.com/mozilla/fxa/pull/4904 ( https://github.com/mozilla/fxa/pull/4904 ) should fix this

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release. Tested on iOS 13.3.1 (iPhone 6S).
