### ISSUE TITLE
Require contact info when provisioning OAuth credentials

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#489]
Migrated from https://github.com/mozilla/fxa-oauth-server/issues/557

During the audit of outstanding OAuth relier credentials, it was very difficult to collectively remember which teams requested which creds. It seems this could be solved by requiring contact and or bugzilla bug info for each set of credentials so that the next time we do an audit, we know who to contact.

**Comment by clouserw** [comment]
Contact info is a part of our new relying party checklist @ https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa
