### ISSUE TITLE
[Fenix] “Confirm a recovery code” modal disappears when the keyboard is enabled

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4890]
**Build:**
FxA Stage [Train 1.166.0]

**Affected platforms:**
Android 9

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox Account.
2. Navigate to Manage account page and expand the 2FA section.
3. Tap on "Enable" and then on “Can’t scan code?” link.
4. Copy the secret key and add it into Google Authenticator with the email address.
5. Click on "Ready" button.
6. Copy the code and paste it into form fill from "Two-step authentication" option and tap on "Confirm".
7. Tap on "Continue" and focus de Recovery codes field.

**Expected results:**
The code is successfully typed in the “Recovery code” field.

**Actual Results:**
“Confirm a recovery code” modal disappears and the screen becomes white when the keyboard is enabled.

![confirm recovery code](https://user-images.githubusercontent.com/18114210/79112055-62820800-7d86-11ea-973e-a458d6cf42a5.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1597)
┆Issue Number: FXA-1597

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is this reproducible in production right now? (Which is on Train 165) 

Thanks

**Comment by vasilicatamas** [comment]
> ➤ Wil Clouser commented:
> Is this reproducible in production right now? (Which is on Train 165) 

I confirm that this issue is also reproducible in Production - FxA Train 165, using Firefox Preview Nightly build (20990609) under Motorola G6 device.

**Comment by vbudhram** [comment]
Hey @vasilicatamas I've tried to replicate this with your configuration (Android 9 + Firefox Preview) but was not able to. Some notes

* Your screenshot does not have the keyboard below for Firefox Preview. I installed my version directly from the Play Store today (4/20/2020). Is it possible that we are running different versions of Firefox?

![Screen Shot 2020-04-20 at 2 32 00 PM](https://user-images.githubusercontent.com/1295288/79786619-bf943580-8313-11ea-9814-7c3545c4e842.png)

* In the video of me [testing](https://drive.google.com/open?id=1cuIbK9qojAZrgWHNDMokdJ58la2K-Tw-),  at 0:05, I click the url toolbar and the entire page goes blank for 2-3 seconds, then the url bar is loaded. Is it possible you are seeing this screen?

* I've tested this on Android 8 with regular Firefox and Firefox Preview on a physical device (Nexus 6p) on both Stage/Production and it worked as expected. Is there another Android device you can test this with to verify it is not related to the Motorola G6?

**Comment by vasilicatamas** [comment]
> Hey @vasilicatamas I've tried to replicate this with your configuration (Android 9 + Firefox Preview) but was not able to. Some notes
> 
Thanks @vbudhram for looking at this issue. Seems that it is no longer reproducible on Fenix build 21110611 and I tend to think that this was a Fenix related issue.

> * Your screenshot does not have the keyboard below for Firefox Preview. I installed my version directly from the Play Store today (4/20/2020). Is it possible that we are running different versions of Firefox?

I can confirm that on the actual build the urls bar is displayed on “Confirm a recovery code” screen.

> * In the video of me [testing](https://drive.google.com/open?id=1cuIbK9qojAZrgWHNDMokdJ58la2K-Tw-),  at 0:05, I click the url toolbar and the entire page goes blank for 2-3 seconds, then the url bar is loaded. Is it possible you are seeing this screen?

No. On my devices the blank senescence is not even noticeable.  

> * I've tested this on Android 8 with regular Firefox and Firefox Preview on a physical device (Nexus 6p) on both Stage/Production and it worked as expected. Is there another Android device you can test this with to verify it is not related to the Motorola G6?

Retested on Moto g6 (Android 9) and Samsung Galaxy S7 (Android 8).

 I am closing this bug due to the fact that this issue is no longer reproducible on the latest Fenix build.

![confirm recovery code1](https://user-images.githubusercontent.com/18114210/79866439-77454800-83e5-11ea-92d3-ac0489091900.gif)
