### ISSUE TITLE
The checkmark is not deselected when the user clicks on stay subscribed in the subscription management page

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4891]
#### Affected Versions:
- All versions

#### Affected Platforms:
- All platforms

#### Prerequisites:
- You have an account with an active subscription.

#### Steps to reproduce:
1. Open the [FxA](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions) subscription management page.
2. Click on the **Cancel** button from the *Cancel Subscription* section.
3. Click on the checkmark and then on the **Stay Subscribed** button.
4. Click on the **Cancel** button from the section again and observe the checkmark.

#### Expected results:
- There is no checkmark displayed.

#### Actual results:
- The checkmark remains selected.

![1](https://user-images.githubusercontent.com/17178945/79118176-c52ed000-7d95-11ea-83cb-5dd9f9fa1b3d.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1598)
┆Issue Number: FXA-1598

**Comment by data-sync-user** [comment]
➤ David Justice commented:

This is outside of the scope of this epic

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release. Tested on iOS 13.3.1 (iPhone 6S).
