### ISSUE TITLE
Subscribing on 1, 2, 3 done gives you access to the VPN

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4892]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All Platforms

#### Steps to reproduce
1. Create a subscription on 1, 2, 3 done.
2. With the same account login and open the download page on the FPN site.

#### Expected result:
- You don't have access to the VPN as you're not subscribed to it.

#### Actual result:
- You have access to the VPN.

![image](https://user-images.githubusercontent.com/17178945/79119387-e8a74a00-7d98-11ea-9e5a-a1a20b8479f5.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1599)
┆Issue Number: FXA-1599

**Comment by lmorchard** [comment]
By "access to the VPN" do you mean that you can download the VPN product and use it? Or is this just appearing as logged into the FPN website?

**Comment by bsurd** [comment]
@lmorchard You can download and install the VPN, we do not know how to set up the VPN so that it points to stage in order to verify if it can or can't be used.

**Comment by lmorchard** [comment]
I don't think download & install are restricted by a subscription - i.e. anyone can get a hold of the software, it should be the servers that decide whether or not to enable actual VPN access when the software is running. That might be independent from what the product website displays 

I think we'll need some debugging from the FPN side on this one, at least to see what they're seeing in terms of subscription capabilities reported for them from the FxA API

**Comment by chrismore** [comment]
> I don't think download & install are restricted by a subscription - i.e. anyone can get a hold of the software, it should be the servers that decide whether or not to enable actual VPN access when the software is running. That might be independent from what the product website displays
> 
> I think we'll need some debugging from the FPN side on this one, at least to see what they're seeing in terms of subscription capabilities reported for them from the FxA API

The VPN user acquisition funnel are these main steps:

1. Visit FPN VPN website
2. Join VPN waitlist
3. Get invite code via email
4. Subscribe and pay
5. Download and install the VPN

To be able to do steps #4 and #5 above, you need to:

- Have a Firefox Account
- Be in the United States
- Have a US credit card
- Have a valid VPN subscription

So, if you are able to get to the VPN download page and not have an active FPN VPN subscription, that is a problem.

@rlr can you verify the above?

**Comment by rlr** [comment]
I'm unable to reproduce this on stage using https://123done-stage.dev.lcip.org/ and https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn. @bsurd can you provide the URLs and any other details?

Access to the downloads page is limited to users that have `guardian_vpn` subscription capability in their FxA profile.

**Comment by rlr** [comment]
Here is an account I set up with 1,2,3 done subscription. On FPN, it tells them to Subscribe Now on the landing page. And the download URL just bounces the user back to the landing page.

@bsurd I did notice you have an extra subscription for Firefox Fortress. I have no idea what that but it sounds like it might be providing the VPN subscription capability?

<img width="1641" alt="Screen Shot 2020-04-20 at 2 01 07 PM" src="https://user-images.githubusercontent.com/36629/79784040-a38e9500-830f-11ea-9e02-3fbe1209751e.png">

**Comment by lmorchard** [comment]
> So, if you are able to get to the VPN download page and not have an active FPN VPN subscription, that is a problem.

@chrismore Just to clarify: Are you saying that we *do* gate download on active subscription? We've had an assumption for a long while now that downloads themselves are not controlled like that - only the actual usage of the product once installed. (i.e. if you did manage to download it without a subscription, it wouldn't matter because the product wouldn't function)

**Comment by chrismore** [comment]
> > So, if you are able to get to the VPN download page and not have an active FPN VPN subscription, that is a problem.
> 
> @chrismore Just to clarify: Are you saying that we _do_ gate download on active subscription? We've had an assumption for a long while now that downloads themselves are not controlled like that - only the actual usage of the product once installed. (i.e. if you did manage to download it without a subscription, it wouldn't matter because the product wouldn't function)

@lmorchard yes, that is correct. The legal guidance we received at the start of the project stated that we have to restrict the distribution of the software binaries themselves using an appropriate level of gates, which assumes it it not possible to restrict them in 100% of use-cases (e.g. linking to the MSI). Even though the software is useless without a subscription, we kept the distribution strict. This is due to the sensitive nature of VPN software and encryption technology. Initially it was in the due to US export laws of encryption/routing technology (now complete), but it also applies to the countries where VPNs are not legal (China, Iran, Iraq, etc.).

If you try to go to the ./download page and you don't have an active subscription, you will get bounced back to the waitlist form.

@rlr ^^ all correct?

**Comment by rlr** [comment]
> If you try to go to the ./download page and you don't have an active subscription, you will get bounced back to the waitlist form.
> 
> @rlr ^^ all correct?

@chrismore correct. The download page is currently only accessible to subscribed users. But technically, we could change that in the future to be a public page if there is a good reason to. The binary URL would remain geo-restricted.

**Comment by rlr** [comment]
I confirmed with @bbangert that the Firefox Fortress subscription enables the `guardian_vpn`.... So, working as intended!

**Comment by bsurd** [comment]
Based on https://github.com/mozilla/fxa/issues/4892#issuecomment-616755084 closing the issue and we'll keep this in mind for future testing.
