### ISSUE TITLE
Diners Club cards are accepted

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4893]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All platforms

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using the following Card numbers: 3056930009020004 or 36227206271667.
3. Click on the Subscribe button.

#### Expected result:
- An error message is displayed telling the user that the card type cannot be used.
- No payment is made.

#### Actual result:
- The card numbers are accepted.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1600)
┆Issue Number: FXA-1600

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~ljanos@mozilla.com] Where are you seeing that they should be declined?  In https://jira.mozilla.com/browse/FXA-1033 we said they should be accepted

**Comment by SoftVision-LorandJanos** [comment]
My mistake, sorry about it, this issue is invalid.
