### ISSUE TITLE
[RTL] Wrong padding for the account deletion section on FxA settings [bz1594549]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4895]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1594549

Created attachment 9107039
Screenshot

See attached.

Paddings to fix for RTL:
`.delete-account-product-list`
`.delete-account-checkbox-list`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1602)
┆Issue Number: FXA-1602

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Followed up in the Bugzilla report, but I don't think this is an issue anymore.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

fixed in https://github.com/mozilla/fxa/issues/4559
