### ISSUE TITLE
Explicitly track the key-rotation timestamp for kB

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#490]
When dealing with scoped keys [1] we want to be able to form a timestamped key identifier that looks like this:

   `"<timestamp when the key changed>-<hash derived from the key material>"`

Unfortunately we don't currently track the timestamp at which a user's `kB` changed.  We track a `veriferSetAt` timestamp and echo it out to reliers as the `fxa-generation` number.  But this timestamp can increase both on both password change (which preserves kB) and password reset (which might changes kB, or might not if a recovery key is used).

Let's track a  separate `keysChangedAt` timestamp that is only incremented when the user's kB actually changes, so we can use that to build key ids in the future.  We'll need to:

* [ ] make a db migration to store an additional column on the `accounts` table
* [ ] add logic for updating this column when `kB` changes, and preserving it when it doesnt
* [ ] add a `"fxa-keysChangedAt"` timestamp to the metadata in our identity assertions, alongside `"fxa-generation"`.
* [ ] update fxa-oauth-server to use the new `"fxa-keysChangedAt"` field when it informs fxa-content-server of the key rotation timestamp, falling back to `"fxa-generation"` if it's not present.

[1] https://docs.google.com/document/d/1IvQJFEBFz0PnL4uVlIvt8fBS_IPwSK-avK0BRIHucxQ/edit#

**Comment by shane-tomlinson** [comment]
@rfk isn't all the code for this already in place and running?

**Comment by rfk** [comment]
> isn't all the code for this already in place and running?

On the DB server it is, but I haven't gotten around to the corresponding auth-server changes yet :-(

**Comment by rfk** [comment]
A brief status update, since most of the status info is currently buried in the draft PR at https://github.com/mozilla/fxa/pull/2570:

* We've deployed a good chunk of the logic for reporting the key-rotation timestamp out to RPs.
* We're waiting on a new tokenserver deploy to be stable in prod before we can deploy the rest of the changes on the FxA side (ref Bug 1589565)[https://bugzilla.mozilla.org/show_bug.cgi?id=1589565].
  * If we deploy further FxA changes without having that in prod, we risk locking out OAuth sync clients such as Lockwise and Fenix.
* Once that's ready, the PR in https://github.com/mozilla/fxa/pull/2570 can merge and head out to prod, which completes the work for this issues.

It would be useful to concurrently review https://github.com/mozilla/fxa/pull/2570 while waiting for the tokenserver deploy; I'll comment as such in the PR for completeness.
