### ISSUE TITLE
[train-166] burst of ValidationError as train-166 went live

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4906]
When train-166 went live on auth-server, for about 5 to 7 minutes there were a number of 500 errors like below that ultimately went away. 
```
Apr 13 19:30:30 ip-172-31-8-48.us-west-2.compute.internal docker-fxa-auth[4005]: 
{"Timestamp":1586806230024000000,
"Logger":"fxa-auth-server","Type":"metricsContext.get","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":
{"err":"Error: Invalid token","hasToken":true,"hasId":false,"hasUid":false}}

Apr 13 19:30:30 ip-172-31-8-48.us-west-2.compute.internal docker-fxa-auth[4005]:
{"Timestamp":1586806230024000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":
{"status":500,"errno":999,"path":"/v1/oauth/subscriptions/plans","lang":"en-us",
"agent":"Mozilla/5.0 (iPhone; CPU OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/24.1  Mobile/15E148 Safari/605.1.15",
"remoteAddressChain":"\"68.36.56.235\",\"172.31.1.96\",\"127.0.0.1\"]",
"t":11,"uid":"00","keys":false,"method":"get","email":"someone@gmail.com"}}
```
Mostly filing this for the record, but if anyone has any insight on what triggered this, that would be great.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1611)
┆Issue Number: FXA-1611

**Comment by jrgm** [comment]
Actually, the 'invalid token' is a red herring; https://sentry.prod.mozaws.net/operations/auth-prod/issues/7843129/?query=is:unresolved is more the issue, which is probably due to timing of how the stacks went live, and what callers/callees expected.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Will the timing be a problem for every push or just a one off?

**Comment by jrgm** [comment]
This timing window has/will always exist on both aws and gcp.

For a brief period of time, **both** the previous and the new versions are live.

But, with respect to ValidationError's, I recall that Sean Macarthur in the standalone oauth server had code to disable validation of responses when running with NODE_ENV=prod. In other words, fail in dev/stage to find the bugs, but just whine about it in production. That doesn't solve this case of validation on the request, and doesn't solve the general api expectation mismatch problem. But food for thought.
