### ISSUE TITLE
[main] Settings > primary email not verified state: primary email section

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4908]
Display "unverified" label and add "Verification needed. Send verification email" copy. 
Allow the "Send verification email" to function as expected. If FXA-1633 is complete, which allows for an account verification message to be displayed, in the new settings page, display a success message.

See: https://mozilla.invisionapp.com/share/PTUIT2C4N8Z#/screens/412929909

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1612)
┆Issue Number: FXA-1612

**Comment by LZoog** [comment]
I'm closing this issue because users can't view the settings page without first verifying their primary email. There is an unverified session state that will be accounted for but it doesn't affect the primary email section.
