### ISSUE TITLE
Ensure actions/routes are guarded in unverified session state

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4909]
A user can’t do the following in an unverified session, as determined by an `Unverified session` error from the auth-server:

* Delete their account (not applicable for this task)
* All actions around secondary emails
* All actions around TOTP
* All actions around the recovery key

These actions by the user should be guarded by a `ModalVerifySession` (`VerifiedSessionGuard`) and a modal should be displayed when interacted with, copy TBD by @MeridelW.

**By the time this issue is worked on, most if not all of these actions should already be guarded if done when those actions were implemented.** 1) Ensure this is the case across these interactions **and** their corresponding pages/flows and 2) work with Meridel to ensure the copy is correct if it was not already determined beforehand.

As of 9/09, this is what the `ModalVerifySession` looks like: [https://mozilla-fxa.github.io/storybooks/commits/5f2ad51fadd80ea3afef726ea7d66b2eecdc8987/fxa-settings/index.html?path=/story/components-modalverifysession--valid-code-1234-invalid-code-4444](https://mozilla-fxa.github.io/storybooks/commits/5f2ad51fadd80ea3afef726ea7d66b2eecdc8987/fxa-settings/index.html?path=/story/components-modalverifysession--valid-code-1234-invalid-code-4444)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1613)
┆Issue Number: FXA-1613

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

It looks like we have VerifiedSessionGuard coverage around all of the totp, recovery keys, and 2fa work. Here are links:

  * [2fa unitRow][https://github.com/mozilla/fxa/blob/c98be7cceb32d2d88a2c300e431b00f73e7faf7a/packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx#L120 ( https://github.com/mozilla/fxa/blob/c98be7cceb32d2d88a2c300e431b00f73e7faf7a/packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx#L120 )|https://github.com/mozilla/fxa/blob/c98be7cceb32d2d88a2c300e431b00f73e7faf7a/packages/fxa-settings/src/components/UnitRowTwoStepAuth/index.tsx#L120)]
  * [recovery key unitRow][https://github.com/mozilla/fxa/blob/3a0e04d8b6fe227a49954e355421c09d561d11a3/packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx#L102 ( https://github.com/mozilla/fxa/blob/3a0e04d8b6fe227a49954e355421c09d561d11a3/packages/fxa-settings/src/components/UnitRowRecoveryKey/index.tsx#L102 )]
  * [pageSecondaryEmailAdd][https://github.com/mozilla/fxa/blob/46f0e0d1de32c8e15157c42c845b7e824fb0639c/packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx ( https://github.com/mozilla/fxa/blob/46f0e0d1de32c8e15157c42c845b7e824fb0639c/packages/fxa-settings/src/components/PageSecondaryEmailAdd/index.tsx )]
  * [pageSecondaryEmailVerify][https://github.com/mozilla/fxa/blob/46f0e0d1de32c8e15157c42c845b7e824fb0639c/packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx ( https://github.com/mozilla/fxa/blob/46f0e0d1de32c8e15157c42c845b7e824fb0639c/packages/fxa-settings/src/components/PageSecondaryEmailVerify/index.tsx )]
  * [page2faReplaceRecoveryCodes][https://github.com/mozilla/fxa/blob/b380660a2359aa1287a6d2694e16ac1615c1f40f/packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx ( https://github.com/mozilla/fxa/blob/b380660a2359aa1287a6d2694e16ac1615c1f40f/packages/fxa-settings/src/components/Page2faReplaceRecoveryCodes/index.tsx )]
  * [pageRecoveryKeyAdd][https://github.com/mozilla/fxa/blob/3a0e04d8b6fe227a49954e355421c09d561d11a3/packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx ( https://github.com/mozilla/fxa/blob/3a0e04d8b6fe227a49954e355421c09d561d11a3/packages/fxa-settings/src/components/PageRecoveryKeyAdd/index.tsx )]
  * [connectedServices/service.tsx signout modal][https://github.com/mozilla/fxa/blob/4fc142704d257d78b6a010f9ead2336ca6b37ef5/packages/fxa-settings/src/components/ConnectedServices/Service.tsx ( https://github.com/mozilla/fxa/blob/4fc142704d257d78b6a010f9ead2336ca6b37ef5/packages/fxa-settings/src/components/ConnectedServices/Service.tsx )]

The only issue open in https://jira.mozilla.com/browse/FXA-1658 is the "download, copy, print" issue. Which just needs a little formatting tweak of the codes so it no longer blocks this issue.

Looks like we can close this one out since "Delete their account (not applicable for this task)"

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~rbillings@mozilla.com] [~vtamas@mozilla.com] [~ashrivastava@mozilla.com] this is ready for QA.

**Comment by vasilicatamas** [comment]
This task was verified on Stage [Train 1.193.0] under Windows 10 64-bit, Android 9 and iOS 13.6 - [2](https://github.com/mozilla/fxa/issues?q=6916+6917) new issues were found.

![Screenshot_56](https://user-images.githubusercontent.com/18114210/98942066-24082380-24f6-11eb-9f2a-162a2f4e5bef.png)
![Screenshot_57](https://user-images.githubusercontent.com/18114210/98942068-24a0ba00-24f6-11eb-8349-2f04c1fcced2.png)
![Screenshot_58](https://user-images.githubusercontent.com/18114210/98942070-25395080-24f6-11eb-8615-58e2afae9db2.png)
