### ISSUE TITLE
favicon for content server was remove in train-166

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4912]
Was this intentional?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1617)
┆Issue Number: FXA-1617

**Comment by vladikoff** [comment]
@jrgm it's back in https://github.com/mozilla/fxa/pull/4845

**Comment by vbudhram** [comment]
@jrgm I think this is safe to close, it is on a point release for 166.1, ref https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/CHANGELOG.md#bug-fixes.

**Comment by jrgm** [comment]
Closing. Somehow didn't see 166.1 on the ticket.
