### ISSUE TITLE
fxa-auth-db-mysql test case failing

### ISSUE THREAD

**Issue by farhan787** [mozilla/fxa#4921]
## Description

`_showVariables returns a plausible set of values` test case is failing. Here is the [test case](https://github.com/mozilla/fxa/blob/e54b278fa8a2f80e86e142d835b9c6984167a027/packages/fxa-auth-db-mysql/test/local/mysql_tests.js#L321).

![Screenshot 2020-04-14 at 9 46 57 PM](https://user-images.githubusercontent.com/38656082/79249099-62732c80-7e9a-11ea-96d1-46d1b2cdb311.png)

### Steps to reproduce

Run `npm run test-mysql` in fxa-auth-db-mysql package

### Possible reasons
1. `Error: ER_NO_SUCH_TABLE: Table 'performance_schema.session_variables' doesn't exist`
2. At `fxa/packages/fxa-auth-db-mysql/node_modules/istanbul-reports/lib/lcovonly/index.js:52`, getting this type error `TypeError: Cannot read property 'loc' of undefined`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1625)
┆Issue Number: FXA-1625

**Comment by vladikoff** [comment]
Seems like a broken mysql server install. You should have the default `performance_schema` database with your MySQL installation. This is not FxA related, we don't create this database

See https://dev.mysql.com/doc/refman/5.7/en/performance-schema.html

**Comment by farhan787** [comment]
@vladikoff thanks for making me aware of it that it's not related to `fxa`, I'll check if I've something broken in mysql db.
