### ISSUE TITLE
Pass service with cert_signed amplitude event

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#493]
MOVED FROM mozilla/fxa-amplitude-send#66:

> When looking at DAU using cert_signed (our primary indicator), we can't group or filter on service. Service rare seems defined.:
>
> https://analytics.amplitude.com/mozilla-corp/chart/yswb4kd/edit/rksvzu1
>
> Given that we are signing certificates for Lockbox and Notes, we should probably be able to tell the difference.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-668)
┆Issue Number: FXA-668

**Comment by davismtl** [comment]
Per comments in bug #1356 , we should look into resolving this.

**Comment by davismtl** [comment]
@irrationalagent do we still need to do this or is this covered by something else now?

**Comment by irrationalagent** [comment]
So I seem to recall that we tried just assigning `sync` to all cert signed events (per phil's comment above) and it went wrong so we had to revert. Though I can't seem to find that pr/issue now. I'll keep looking. 

It would be nice to have this though. I don't think its covered by another other work. Putting it as a p2 for now, feel free to change it.
