### ISSUE TITLE
The invoice is not sent for all subscription types/durations

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#4940]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All Platforms

#### Steps to reproduce
1. Create a subscription for the weekly, 6 weeks or yearly product.
2. Check the inbox for the invoice mail.

#### Expected result:
- The invoice for the payment is received.

#### Actual result:
- The invoice for the payment is not received.

Notes:
The "Welcome to Firefox Variety Product" is received for every subscription but the invoice is only sent for the daily, 15 days, monthly and 6 months subscriptions.

![image](https://user-images.githubusercontent.com/17178945/79341861-188b5480-7f35-11ea-82e4-804b93df72a6.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1636)
┆Issue Number: FXA-1636

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~wclouser@mozilla.com] [~jmunroe@mozilla.com]  tagging you both for awareness of this major issue found in QA.
