### ISSUE TITLE
[secondary email] Create `/emails` page with dummy form and cancel link

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4957]
The `/emails` route should be hooked up from the settings page in FXA-1609.

Add the text and the form for this page and style it accordingly.

Also allow for the "Cancel" link to take the user back to the settings page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1647)
┆Issue Number: FXA-1647

**Comment by LZoog** [comment]
The work here was completed in this PR: https://github.com/mozilla/fxa/pull/6276
