### ISSUE TITLE
Consider loosening `prompt=none` restrictions

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#4963]
We originally restricted `prompt=none` usage, because we only supported passing an email as the hint. In this version of the flow, a well-intentioned RP might confuse a user by silently logging them in.

Now that we've added support for the `id_token_hint`, in which the RP passes in an ID Token specific to that RP and created during the regular, user interaction required oauth flow, we could relax our restriction on which RPs can use `prompt=none`, provided they use an `id_token_hint`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1652)
┆Issue Number: FXA-1652

**Comment by clouserw** [comment]
@6a68 - is there a specific use case you're wanting to enable by changing this?

@rfk @arroway - do you have opinions on this?

**Comment by rfk** [comment]
I have no objection to it, and I think it's inline with how we want the `prompt=none` flow to operate. If we come to add `prompt=none` for another RP then we could consider doing this work instead of adding them to the special config allowlist.

**Comment by 6a68** [comment]
Yup, this is just to get our usage of prompt=none more in line with the
OIDC spec.

See the prompt=none doc for more details:
https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/oauth/prompt-none.md#future-directions

**Comment by arroway** [comment]
Sounds good to me too.
