### ISSUE TITLE
[recovery] Generate key, display success message on "Done" button

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4967]
On hitting the "step 2 of 2" page, generate the account recovery code and display it on this page.

This needs to `useAuth` in order to fetch keys to generate the recovery key/bundle. Reference `fxa-content-server...crypto/recovery-keys.js`

Wait until the user clicks on "Done," and then 1) take the user back to the main settings page 2) with a success message.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1657)
┆Issue Number: FXA-1657

**Comment by dannycoates** [comment]
crossed wires. this hasn't been done yet
