### ISSUE TITLE
Make sure utm_* params in our emails are correct

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#497]
In #2505, we stopped setting `utm_source=email` on links in our outgoing emails because it clobbered the existing `utm_source` for the flow and polluted our metrics.

`utm_medium` is still set in exactly the same way though and probably suffers from a similar problem:

https://github.com/mozilla/fxa-auth-server/blob/e47b7102e680fd2361b14100a059025046acd178/lib/senders/email.js#L1095

There is also conditional logic for setting `utm_content` and `utm_campaign`, which may or may not be fine.

Let's audit these to make sure they're not messing up any metrics.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-672)
┆Issue Number: FXA-672

**Comment by clouserw** [comment]
@irrationalagent @davismtl are there clear next steps for this issue?  Otherwise I think we should close it and open smaller/specific issues for any changes.
