### ISSUE TITLE
[content] lib/auth/hawk test failing in Chrome

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#4989]
I think it's just a different way of handling errors in Blink crypto?

"DataError: The optional HMAC key length must be shorter than the key data, and by no more than 7 bits."

Running http://127.0.0.1:3030/tests/index.html

![image](https://user-images.githubusercontent.com/128755/79508892-73da4700-8008-11ea-885d-b38d93cbcd59.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1680)
┆Issue Number: FXA-1680

**Comment by dannycoates** [comment]
Fortunately none of the keys we use outside of test cases are less than 256 bits. Unfortunately these test vectors copied from the reference hawk implementation are.

https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/tests/spec/lib/auth/hawk.js#L10

This doesn't seem to be as critical as I initially thought but we should generate some new test vectors from using reference implementation.
