### ISSUE TITLE
Emit login SQS event anytime a user 'signs in' to a relying party

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4994]
Currently we only emit login SQS events if a user needs to enter their login/password on FxA. The event-broker was built with the assumption that logging into a RP will always trigger this event, which does not occur if they are already logged into FxA.

We should emit a login SQS event on RP login, even if the user is already logged into FxA.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1682)
┆Issue Number: FXA-1682

**Comment by rfk** [comment]
(In concrete terms I think this means "at the point where we create the OAuth authorization code")
