### ISSUE TITLE
Changing Email address to regain access to FxA

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#50]
As an FxA user when I lose control of the email account  that is my username in Firefox Accounts I want to be able to change that FxA email address so that I don't lose access to my data and other FxA-relying services. 

See https://www.lucidchart.com/documents/view/9c9a4647-615f-4b7c-a4db-71ae10afcd04

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-28
