### ISSUE TITLE
[metrics] Setup Sentry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5017]
Sentry errors bubble up to `AppErrorBoundary`. We should be able to reference the payments-server setup for this.

Can this become a shared component within `fxa-components`?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1693)
┆Issue Number: FXA-1693

**Comment by jodyheavener** [comment]
Reference https://github.com/mozilla/fxa/pull/5129 for earlier AppErrorBoundary and Sentry entrypoint setup.
