### ISSUE TITLE
"Primary email required" error message can be confusing

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#502]
I'm spinning this out from [Bug 1467649](https://bugzilla.mozilla.org/show_bug.cgi?id=1467649) where a user encountered the "primary account email required" error message and it led to a great deal of confusion.

For users who don't have a clear mental model of "primary email" and "secondary email", the error message "Primary account email required for sign-in" provides almost no actionable info.  This particular user interpreted it as meaning something was wrong with their password, attempted a password reset, and got blocked on a similar confusing error "Primary account email required for reset".

Note that it's possible for a user to encounter this error without ever having set up a secondary email address themselves, for example if they're the new owner of an email address that was previously added as a secondary on someone else's account.

I don't have a good suggestion for rewording this error to make it clearer, but I wonder if we can either (a) allow logins and password resets to proceed based on secondary email address, or (b) have some sort of "help" or "more info" link in the error messages that helps users get unstuck.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-676)
┆Issue Number: FXA-676

**Comment by Tammychmarney** [comment]
Google gmail primary website email administrator address location services provider Rogers residential location settings chocsantagramma@rogers.com

**Comment by Tammychmarney** [comment]
Location of provider ORANGEVILLE ONTARIO CANADA

**Comment by Tammychmarney** [comment]
Google play store settings browser on my gmail fails to download to my iPhone settings for INTERNET IN CANADA

**Comment by poo0054** [comment]
I am currently facing this situation. What should I do? I can't remember what my main account is.
