### ISSUE TITLE
[change pw] Process form response (REST)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5034]
The button will be enabled/disabled in FXA-1710.

This won't hit the GQL server. See FXA-2001 for details.

A successful response should 1) take the user back to the main settings page 2) with a success message while 3) updating the "last changed" time on the main Settings page.
Any server errors should be displayed on the separate page that "Save" was selected on, in the global alert message.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1711)
┆Issue Number: FXA-1711

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Note: Danny added a rough draft of what this could look like while closing out another issue, see that draft here: https://github.com/mozilla/fxa/pull/6109/files

**Comment by dannycoates** [comment]
closed in #6523
