### ISSUE TITLE
[Fenix] Long pressing on backspace button doesn’t work properly

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5042]
**Build:**
FxA Stage [Train 1.167.1]
Firefox Previe Nightly #21110611

**Affected platforms:**
Android 9

**Steps to reproduce:**
1. Launch Firefox and navigate to https://accounts.firefox.com/signin.
2. Insert an email address. 
3. Place the cursor in the middle of the email address and long press the backspace button.

**Expected results:**
All the characters that are displayed in the left side of the cursor are successfully deleted. 

**Actual Results:**
- Only 1 or 2 characters are deleted.
- If the cursor is placed at the end of the email address, all the characters that represent the email domain + the “@” are deleted and then it stops.

![backspace](https://user-images.githubusercontent.com/18114210/79869510-2421c400-83ea-11ea-86d8-91a0c58645a4.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1714)
┆Issue Number: FXA-1714

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This sounds like it might be an OS behaviour (whether it's a feature or bug I am not sure). Can you confirm that this does not occur on another email-type input on this device/OS?

**Comment by vasilicatamas** [comment]
> ➤ Jody Heavener commented:
> This sounds like it might be an OS behaviour (whether it's a feature or bug I am not sure). Can you confirm that this does not occur on another email-type input on this device/OS?

I confirm that I did not encounter this issue on another email-type field, and it would worth mentioning that it is not reproducible on Fennec 68.7.0 on the same device/OS.
