### ISSUE TITLE
Long Device name causes layout issues in “Disconnect from sync” confirmation panel

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5043]
**Build:**
FxA Stage [Train 1.167.1]

**Affected platforms:**
Windows 10 x64
Android 9 
iOS 13.1.2

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox Account.
2. Navigate to about:preferences#sync and click on “Change Device Name...” button.
3. Type a long name and click on “Save” button.
4. Connect on a different device and navigate to Manage Account page
5. Expand the “Devices & apps” section and click on “Disconnect” button.

**Expected results:**
The Device name is divided on several lines in Confirmation panel. 

**Actual Results:**
The Device name is displayed outside the Confirmation panel.

![Screenshot_9](https://user-images.githubusercontent.com/18114210/79876709-0e190100-83f4-11ea-907c-4b2205305b40.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1715)
┆Issue Number: FXA-1715

**Comment by clouserw** [comment]
This is probably adding a `max-width:100%` to this container.

**Comment by imskr** [comment]
@vasilicatamas Can i work?

**Comment by LZoog** [comment]
@imskr sure thing! I've assigned it to ya.

**Comment by imskr** [comment]
Thanks @LZoog

**Comment by mrunalvilas** [comment]
hello can I work on this issue

**Comment by LZoog** [comment]
@imskr, are you still working on this issue?

@mrunalvilas, if @imskr doesn't get back here in a day or two I'd say go for it, thanks!

**Comment by imskr** [comment]
No @LZoog. @mrunalvilas you can work on this

**Comment by mrunalvilas** [comment]
thank you!!

**Comment by vasilicatamas** [comment]
This issue also reproduces in the new Settings page. @clouserw should we keep track this bug or a separate issue should be filed?

![Screenshot_36](https://user-images.githubusercontent.com/18114210/100219572-d8ef0700-2f1e-11eb-9495-c70d904dc1b5.png)

**Comment by LZoog** [comment]
Thanks @vasilicatamas for verifying it's still a bug in new settings! Let's leave it open, the fix should solve this in new settings.

**Comment by vasilicatamas** [comment]
Sorry for closing it. I was convinced that there is a separate one for the new settings page.

**Comment by Deek9399** [comment]
Hello @LZoog, I am an outreachy applicant. Can I work on this issue?

**Comment by LZoog** [comment]
Hi @Deek9399, yes, I will assign you! Thanks!

**Comment by Deek9399** [comment]
Yes, I am working on my other issue. Hopefully, I will create a PR today.
Thanks @LZoog

**Comment by Jo-bot86** [comment]
Hi @LZoog  and @jodyheavener! I already had a first good issue and was just wondering if all the other outreachey applicants had one. Would love to work on it but if someone hasn't had one yet I would leave it up to others.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

The issue was verified as fixed on Stage [1.208.0] under Windows 10 64-bit, Android 11 and iOS 14.4. I confirm that the text is not displayed outside the Confirmation panel.
