### ISSUE TITLE
Quite a lot of outdated dependencies

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#506]
> npm outdated  
Package                Current  Wanted   Latest  Location
acorn                    5.0.3   5.0.3    5.5.3  fxa-auth-server
ajv                      4.1.7   4.1.7    6.5.0  fxa-auth-server
aws-sdk                 2.77.0  2.77.0  2.242.1  fxa-auth-server
binary-split             0.1.2   0.1.2    1.0.3  fxa-auth-server
bluebird                 3.4.7   3.4.7    3.5.1  fxa-auth-server
cldr-core               31.0.1  31.0.1   33.0.0  fxa-auth-server
cldr-localenames-full   31.0.1  31.0.1   33.0.0  fxa-auth-server
commander                2.9.0   2.9.0   2.15.1  fxa-auth-server
convict                  2.0.0   2.0.0    4.2.0  fxa-auth-server
email-addresses          2.0.2   2.0.2    3.0.1  fxa-auth-server
eslint-plugin-fxa        1.0.0     git      git  fxa-auth-server
fxa-auth-db-mysql      1.112.0     git      git  fxa-auth-server
fxa-jwtool               0.7.1   0.7.1    0.7.2  fxa-auth-server
generic-pool             3.2.0   3.2.0    3.4.2  fxa-auth-server
google-libphonenumber   2.0.10  2.0.10    3.1.5  fxa-auth-server
grunt                    1.0.1   1.0.1    1.0.2  fxa-auth-server
grunt-eslint            19.0.0  19.0.0   20.1.0  fxa-auth-server
grunt-newer              1.2.0   1.2.0    1.3.0  fxa-auth-server
grunt-nunjucks-2-html    0.3.4     git      git  fxa-auth-server
handlebars               4.0.6   4.0.6   4.0.11  fxa-auth-server
hapi                    16.6.3  16.6.3   17.4.0  fxa-auth-server
hapi-auth-hawk           3.0.1   3.0.1    4.0.0  fxa-auth-server
hapi-hpkp                1.0.0     git      git  fxa-auth-server
hawk                     3.1.3   3.1.3    7.0.7  fxa-auth-server
inert                    4.0.2   4.0.2    5.1.0  fxa-auth-server
insist                   1.0.0   1.0.0    1.0.1  fxa-auth-server
jed                      0.5.4   0.5.4    1.1.1  fxa-auth-server
joi                     12.0.0  12.0.0   13.3.0  fxa-auth-server
jws                      3.1.3   3.1.3    3.1.5  fxa-auth-server
leftpad                  0.0.0   0.0.0    0.0.1  fxa-auth-server
load-grunt-tasks         3.5.2   3.5.2    4.0.0  fxa-auth-server
mailparser               0.6.1   0.6.1    2.2.0  fxa-auth-server
mocha                    3.1.2   3.1.2    5.1.1  fxa-auth-server
moment-timezone         0.5.11  0.5.11   0.5.17  fxa-auth-server
mozlog                   2.0.6   2.0.6    2.2.0  fxa-auth-server
newrelic                 4.1.0   4.1.0    4.1.1  fxa-auth-server
nock                     8.0.0   8.0.0    9.2.6  fxa-auth-server
node-uap                 0.0.3     git      git  fxa-auth-server
nodemailer               2.7.2   2.7.2    4.6.4  fxa-auth-server
nyc                      8.4.0   8.4.0   11.8.0  fxa-auth-server
otplib                   8.0.1   8.0.1    9.0.0  fxa-auth-server
proxyquire               1.8.0   1.8.0    2.0.1  fxa-auth-server
raven                    2.1.2   2.1.2    2.6.2  fxa-auth-server
redis                    2.7.1   2.7.1    2.8.0  fxa-auth-server
request                 2.83.0  2.83.0   2.86.0  fxa-auth-server
sinon                   1.17.5  1.17.5    5.0.7  fxa-auth-server
sjcl                     1.0.6   1.0.6    1.0.7  fxa-auth-server
uuid                     1.4.1   1.4.1    3.2.1  fxa-auth-server
web-push                 3.3.0   3.3.0    3.3.1  fxa-auth-server
ws                       1.1.1   1.1.1    5.1.1  fxa-auth-server

ref #2438

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-679)
┆Issue Number: FXA-679

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We're using dependabot on github now
