### ISSUE TITLE
User not told to use primary email address until after entering unblock code.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#509]
Follow on from mozilla/fxa-content-server#6064

Start with @vbudhram's STRs:

> * Start the custom server on default ports
> * Set customsUrl in dev.json to 127.0.0.1:7000. This will enable rate limiting locally.
> * Start servers with ./pm2 start servers.json
> * Create account, verify, add secondary email, change to primary, log out
> * Attempt to login until you are rate limited (should see sign-in unblock view)

Now, attempt to login with the original email address, which is now the secondary. You'll be sent to the "Authorize this sign-in" screen. Enter the unblock code. Only now is the user informed they must sign in with the primary address.

ISTM a better experience here would be to inform the user before they enter the unblock code they need to sign in with the primary email address. I suspect the check whether the primary address is being used is done after the check for whether the account is blocked.

<img width="477" alt="screen shot 2018-04-13 at 12 14 13" src="https://user-images.githubusercontent.com/848085/38731997-0d6e1fc6-3f0c-11e8-8fb6-a397f8c978f1.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-682)
┆Issue Number: FXA-682

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
