### ISSUE TITLE
Investigate * vs - bullet point Prettier MD changes

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#5091]
Most notably with our train tag PRs, Prettier seems to change its mind on `*` vs `-` preference for bullet points in our MD files. Previous release changelogs seem to get changed from one or the other. See https://github.com/mozilla/fxa/pull/5090/files#diff-2d61339859c5b4dde8723cd7ec566eefL10-R50 for an example.

What's causing this... Prettier versioning? Git? Something else? It'd be nice to be consistent.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1751)
┆Issue Number: FXA-1751

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The release script uses asterisks if I'm reading this section right:  https://github.com/mozilla/fxa/blob/master/release.sh#L164

Looking at the last few trains, Barry, Vijay and Les all committed dashes.  I committed asterisks.  You all probably have a prettier pre-commit hook that hits that file?

Sounds like it would be easiest to change the release script to use dashes.

**Comment by jodyheavener** [comment]
Oh apparently I did this 🤷 https://github.com/mozilla/fxa/commit/b93687608b0a9134c9ea6b5aa28ece149944a272
