### ISSUE TITLE
Suggested Changes to FxA Subscriptions Support intake Form

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5093]
Sumo Suggested changes to Subscription Service Ticket form input fields.

1. What are you contacting us about? Change "please select one"  drop down options to include:

* Firefox Account
* Firefox Private Network Android App
* Firefox Private Network Windows App

* Firefox Private Network IOS App
* Firefox Private Network Browser Extension
* Other

2. What do you need help with? Change "Please Select One" drop down options to include:

* Payment & Billing
* Account Issues
* Technical Issues
* Provide feedback / Request features
* Not listed

Within Zendesk update subscription service ticket form routing.

3. Route "What are you contacting us about?" selections to "Support Category" Ticket Field in Zendesk.

[https://mozilladev.zendesk.com/agent/admin/ticket_fields/360028484432](https://mozilladev.zendesk.com/agent/admin/ticket_fields/360028484432)

4. Create Ticket Field "Sub-Category" within the subscription service ticket form in Zendesk.

5. Route "What do you need help with?" selections to "Sub-Category" Ticket Field

Change in Scope as Requested in Code Review:
Update how we are currently handling authorization for the support ticket creation endpoint.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1754)
┆Issue Number: FXA-1754
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13213/Screen+Shot+2020-04-23+at+2.28.39+PM.png">Screen Shot 2020-04-23 at 2.28.39 PM.png</a> | <a href="https://jira.mozilla.com/secure/attachment/13212/Screen+Shot+2020-04-23+at+2.28.44+PM.png">Screen Shot 2020-04-23 at 2.28.44 PM.png</a> | <a href="https://jira.mozilla.com/secure/attachment/13211/Screen+Shot+2020-04-23+at+2.28.53+PM.png">Screen Shot 2020-04-23 at 2.28.53 PM.png</a> | <a href="https://jira.mozilla.com/secure/attachment/13210/Screen+Shot+2020-04-23+at+2.30.57+PM.png">Screen Shot 2020-04-23 at 2.30.57 PM.png</a> | <a href="https://jira.mozilla.com/secure/attachment/13209/Screen+Shot+2020-04-23+at+2.31.05+PM.png">Screen Shot 2020-04-23 at 2.31.05 PM.png</a>

**Comment by jackiemunroe** [comment]
- [ ] Create "Sub-Catagory" Ticket Field within Zendesk and add to Subscription Service Form.
- [ ] Update Support Form
