### ISSUE TITLE
Contacting support returns an error

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#5106]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All platforms

#### Preconditions
- Have an active subscription.

#### Steps to reproduce
1. Go to the "Manage subscription" page.
2. Click on the "Contact support" button and complete the fields with valid data.
3. Click on the Send button.

#### Expected result:
- A message is displayed, telling the user that the ticket was sent to the support page.

#### Actual result:
- The "Hmm, we're having trouble with our system. We're working on fixing it for you and apologize for the inconvenience. Please try again later." error message is displayed.

![image](https://user-images.githubusercontent.com/48829350/80181901-67f51300-860e-11ea-8f02-4d33b6df97da.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1763)
┆Issue Number: FXA-1763

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This was fixed on Friday

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) site, using the latest Firefox Release. Tested on iOS 13.3.1 (iPhone 6S).
