### ISSUE TITLE
"Activate account" reminder emails have incorrect content

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5107]
**Build:**
FxA Stage [Train 1.168.0]

**Affected platforms:**
Windows 10 x64

**Steps to reproduce:**
1. Launch Firefox.
2. Follow the account creation flow.
3. Check the email inbox.
4. Do not confirm the account.

**Expected results:**
The time elapsed since the account was created corresponds to the period specified in the email.

**Actual Results:**
“Reminder: Finish creating your account” and “Final reminder: Activate your account” emails are received after 11 and 15 minutes while in the emails are specified the following periods: “A few days ago” and “Almost a week ago”.

![reminders](https://user-images.githubusercontent.com/18114210/80191734-cde99680-861e-11ea-934b-8b964f846aa5.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1764)
┆Issue Number: FXA-1764

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is done on purpose on stage to help QA.  See https://github.com/mozilla/fxa/issues/1302
