### ISSUE TITLE
Add more automation/documentation around email template creation

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#511]
The steps and process to add a new email template to the auth-server has grown. We should add some automation and documentation for future us. These are a few off top of my head

* Create new template in `/lib/senders`, run `grunt template`
* Create a text version (file with `.txt`) of template
* Add template to [template index](https://github.com/mozilla/fxa-auth-server/blob/master/lib/senders/templates/index.js#L62)
* Add email logic in `/lib/senders/email.js`
* Add template name to [UTM mapping](https://github.com/mozilla/fxa-auth-server/blob/01d37ee77647d923f7310d3e1acc551314f4cf61/lib/senders/email.js#L30)
* Expose mailer function in `/lib/senders/index`, function must have these 3 params, `function (emails, account, opts)`
* Update local email [test cases](https://github.com/mozilla/fxa-auth-server/blob/01d37ee77647d923f7310d3e1acc551314f4cf61/test/local/senders/email.js#L26)
* Add to metric [templates](https://github.com/mozilla/fxa-auth-server/blob/c68105343e38e2c60bf4eb03aba86c48584efc3f/lib/metrics/amplitude.js#L79)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-684)
┆Issue Number: FXA-684

**Comment by Cronus1007** [comment]
@vbudhram  If you are currently  not working on this issue shall I take over this issue?

**Comment by Cronus1007** [comment]
@clouserw Shall I take over this issue.
