### ISSUE TITLE
Recurrent payment email is not sent

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5119]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Create a daily product subscription (https://accounts.stage.mozaws.net/subscriptions/products/prod_H63sY3qFAwW4Rk?plan=plan_H647jpSbC33HHp)
2. Wait one full day since subscription

#### Expected result:
- The email with invoice is sent.

#### Actual result:
- The recurrent payment email is not sent. 

#### Notes
- fxa account used to reproduce this issue today: mcotetiu+mt03@mozilla.com

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1771)
┆Issue Number: FXA-1771

**Comment by lmorchard** [comment]
I haven't seen a recurring payment email yet, but I *think* this issue will be fixed after I made a Stripe configuration change described here:

https://github.com/mozilla/fxa/issues/5108#issuecomment-620107307

**Comment by madalincm** [comment]
Recurrent payments mails have started to arrive, so it looks the issue is no longer reproducing in stage. However we have found two new issues regarding this email. Please have a look at #5133 and #5134.

**Comment by lmorchard** [comment]
If the emails are arriving, let's call this issue closed rather than expanding its scope. We can track problems in the content of the received emails in those separate issues.
