### ISSUE TITLE
The canceled subscription mail should not contain a cancel subscription link

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5120]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Access the /subscriptions page (https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions)
2. Cancel the subscription
3. Open the subscription canceled email

#### Expected result:
- The mail does not contain a cancel subscription link.  It may contain a reactivate subscription link.

#### Actual result:
- The mail contains a link to cancel the subscription which links to the /subscriptions page.

#### Notes
- This is also reproducing in the email that is sent when the user deleted the fxa account and the subscription is auto-canceled.

![image](https://user-images.githubusercontent.com/15685441/80352197-2ff30780-887c-11ea-9c05-cf69cd6fffab.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1770)
┆Issue Number: FXA-1770

**Comment by lmorchard** [comment]
FWIW, the existing cancellation email has this link in the footer and does not have a reactivation link. This will be a change to what we migrated over from Salesforce.

https://docs.google.com/document/d/1zQevMPvapl8QOKkaMwBKBh_mG1pmqnLjBkszlWkDYwI/edit#heading=h.88sbb24g38u8

**Comment by lmorchard** [comment]
Got a PR already, seems like maybe not a big deal. But just want to ping @johngruen on the product change

**Comment by madalincm** [comment]
Verified as fixed in stage in the subscription canceled email.
![image](https://user-images.githubusercontent.com/15685441/80956169-57f8e280-8e09-11ea-8b3d-69f58b403789.png)
