### ISSUE TITLE
Canceled subscription mail is sent after fxa account deletion even when that subscription was already canceled

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5121]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Access the /subscriptions page (https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions)
2. Cancel the subscription
-- the canceled subscription emai is sent --
3. Delete that fxa account

#### Expected result:
- The canceled subscription is not sent as the user already canceled the subscription and the user received already a canceled subscription email.

#### Actual result:
- The canceled subscription is sent.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1769)
┆Issue Number: FXA-1769

**Comment by madalincm** [comment]
Has the fix for this issue landed in stage? The issue is still reproducing today when we re-tested this section in stage.

**Comment by clouserw** [comment]
This is not on stage yet

**Comment by madalincm** [comment]
The issue is still reproducing in stage.  Reopening.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

Will put this into the next train.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Thinking through this a bit: The previous fix ( https://github.com/mozilla/fxa/pull/5125/files ) assumed that a subscription cancelled immediately on account deletion would still have `cancel_at_period_end = true`. Looks like this assumption is incorrect.

When FxA flags a customer for deletion ( https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/payments/stripe.js#L389 ), the Stripe customer update webhook event will trigger subhub to immediately cancel any existing subscriptions ( https://github.com/mozilla/subhub/blob/4dd240c3a3138f5ffc16dd6f1f79e8d2870b3693/src/hub/vendor/customer.py#L81 ). But, it appears that the `cancel_at_period_end` flag is reset.

So, I'm thinking maybe a fix would be for FxA to set a metadata property on the subscription as its own flag to record that a cancellation email was sent. Clear that flag on reactivation.

**Comment by madalincm** [comment]
@lmorchard Is the fix in stage? This issue is still reproducing for me.
