### ISSUE TITLE
Incorrect next billing date displayed in payment confirmation email and recurrent payment email

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5133]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with no subscriptions

#### Steps to reproduce
1. Create a daily product subscription (https://accounts.stage.mozaws.net/subscriptions/products/prod_H63sY3qFAwW4Rk?plan=plan_H647jpSbC33HHp).
2. Check the Payment received email that has been sent.

#### Expected result:
- The next billing date is correctly displayed in the email.

#### Actual result:
- The next billing date is the same as the current billing date.

#### Notes
- This is also reproducing in recurrent payment emails.
- In the /subscriptions fxa page the correct date is displayed, so this look only a issue in the emails.

![image](https://user-images.githubusercontent.com/15685441/80485042-63f42880-8961-11ea-9300-443e68032050.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1773)
┆Issue Number: FXA-1773

**Comment by bsurd** [comment]
This is also reproducible for the resubscription mail, the billing date is displayed the same as the current one.

![image](https://user-images.githubusercontent.com/17178945/80490594-44adc900-896a-11ea-84d5-3ee074b621d5.png)

**Comment by madalincm** [comment]
I have verified this issue in stage. The next billing date is correctly displayed in the payment confirmation email and recurrent payment email but in the resubscribe mail the date is still wrong:
![image](https://user-images.githubusercontent.com/15685441/80956544-1c124d00-8e0a-11ea-9e0c-f4f3b51a61e8.png)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~mcotetiu@mozilla.com] marking this DONE as the emails in the original bug have been resolved. I have created https://github.com/mozilla/fxa/issues/5200 ( https://github.com/mozilla/fxa/issues/5200 ) to track this issue for Resubscribe emails. (Please review details in Description and add any details necessary).

**Comment by madalincm** [comment]
Marking the bug as verified.
