### ISSUE TITLE
Stop logging (or be more selective) on type flow.missingData

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5142]
This is a significant part of our auth server logging cost. Can we reduce these. One source is (I think) requests from kintowe. Removing it entirely may have a security implication.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1779)
┆Issue Number: FXA-1779

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This sounds like something we can do.  CCing some people for visibility.  [~loines@mozilla.com]  [~adavis@mozilla.com] [~stephouillon@mozilla.com] [~kkleemola@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Stéphanie Ouillon commented:

After grepping it, flow.missingData doesn't seem to be used in the fraud pipeline, so it shouldn't have an impact on this side of things.

**Comment by data-sync-user** [comment]
➤ Leif Oines commented:

I have never used this

**Comment by vladikoff** [comment]
Not sure if cheaper but this event could possibly be moved to StatsD

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

Let's stop logging this, since it isn't used anywhere.
