### ISSUE TITLE
Amplitude user properties `sync_active_devices_*` doesn't count Fx iOS anymore and Fenix, and will break when sync moves to oauth

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5143]
We have several amplitude user properties of the form `sync_active_devices_day`, week and month. These are set only when an `fxa_activity - cert_signed` event is logged, and that event is going away. At that point, we will start relying on the `fxa_activity - access_token*` events to track e.g. DAU and MAU. We should be sure that these sync device count user properties are still set when this happens.

[This is where the device counts are set](https://github.com/mozilla/fxa/blob/045ffadb8e4d8007861641aa96d59e4d069e53c9/packages/fxa-shared/metrics/amplitude.js#L404)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1780)
┆Issue Number: FXA-1780

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

There's some urgency.
The FxA Rust component is alread in Firefox for iOS Beta.

**Comment by rfk** [comment]
Fenix doesn't currently generate `cert_signed` events, and iOS will soon stop generating them. I guess in theory right now we could have users who are only signed in on Fenix and thus are not correctly tracking these active-devices metrics.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

[~adavis@mozilla.com] [~loines@mozilla.com] is this something that needs to get onto the next train?

**Comment by data-sync-user** [comment]
➤ Leif Oines commented:

Its probably moderately urgent (Alex can disagree), as the recent switch of iOS to oauth for sync means that we are no longer updating these values accurately for those users. And I guess we have never been doing it for Fenix. This is causing us to undercount multidevice users in some of our amplitude charts.

So, at some point we definitely need to start updating these user properties via `fxa_activity - access_token*` events and not just the cert_signed events. I know properly tracking M-D users is important for the OKRs so I'm guessing we should probably do this if not next train then very shortly after.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

[~loines@mozilla.com] is this something [~fbertsch@mozilla.com] can help with or is this something that our team has to do ourselves?

**Comment by data-sync-user** [comment]
➤ Frank Bertsch commented:

If we have an `active_device` field from oauth events, we can aggregate those like we do the `os_used` fields, and create `active_devices_*`. I'm not seeing anything like that from oauth events, but if we can just get that added then it is doable to aggregate and add the user property on our end.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

I've changed this to relate to CAD via QR codes since it prevents us from measuring our overall multi-device user numbers. It was formally rolling up to the Sync over OAuth epic since that too would continue to break this metric.

Firefox for iOS is already being excluded from this roll-up.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Here's an example of a chart that we monitor closely that is broken now:
https://analytics.amplitude.com/mozilla-corp/chart/n2bn398

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This won't make current sprint, bumping ->

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Summarizing the issue in a bit of detail, because the story is a little convoluted, and not collected in any one place:

Sync is in the process of switching from using browserid assertions to using oauth access tokens for authentication, starting with mobile clients. (See this doc ( https://docs.google.com/document/d/1Qifi2p2YqqqY_A1oKeKHpxWIqhbZsEnNkW_YNaOoJ5k/edit#heading=h.d6wgcnlgkkno ) for more details.) 

Browserid assertions are only valid for 6 hours, and sync clients historically needed the FxA server to sign those assertions in order to authenticate with the sync tokenserver. Hence, Sync usage metrics (like DAU and number of devices used per day per user) could be derived from the browserid assertion signing events recorded by the server.

With the move to oauth, this daily usage data is lost, because our oauth tokens have a longer TTL (currently two days). Note that this TTL is longer than typical for an oauth token for a service with sensitive user data, so it's suboptimal both from a security standpoint and from the standpoint of understanding usage patterns.

The goal here is to restore the lost DAU and daily device usage metrics.

Current plan:

1) reduce the TTL to less than a day, maybe down to 6 hours if we can. There is a bug in our token endpoint validator to be fixed here: it throws an error if a service requests a longer TTL than the max supported value (https://jira.mozilla.com/browse/FXA-2110). I've got a pull request open to fix this bug (https://github.com/mozilla/fxa/pull/5747). ( https://github.com/mozilla/fxa/pull/5747). )

2) Double-check with the secure proxy team that reducing the token TTL won't break anything, since they ran into the above bug.

3) Check in with other FxA relying parties list to ensure nothing will break if the token lifetime is reduced to a day or less.

4) Update the FxA server metrics code to derive the missing sync usage events from the `fxa_activity - access_token_created` event, generated when an oauth token is created, instead of the no longer reliable `fxa_activity - cert_signed` event, which was generated when a browserid assertion was signed.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Thanks [~jhirsch@mozilla.com] for the summary. Do we need to inform ops of any potential increase in load as a result of the shorter TTL?

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

> Do we need to inform ops of any potential increase in load as a result of the shorter TTL?

Happily, no: token storage has been moved from mysql to redis, which should address the main performance bottleneck we've seen with past attempts to reduce the token TTL.

**Comment by 6a68** [comment]
Infrastructure work related to (1) avoiding this new high-volume event destroying our Amplitude budget and (2) adding this new event to the bigquery-ETL rollup is captured in https://bugzilla.mozilla.org/show_bug.cgi?id=1649871

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Note that we've run into a new TTL issue that is preventing us from reducing the token TTL in production:

https://jira.mozilla.com/browse/FXA-2212

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

The TTL issue seems to be specific to relying parties that use PPIDs. I'm working now to understand what limitations exist around lowering the token TTLs used by sync clients.

**Comment by 6a68** [comment]
OK, after some discussion with @rfk (see PR #6368 for details), it seems the FPN problems in #5826 are unique to their use case.

We should be fine to lower the default access token TTLs down to just above six hours, so that we can (1) achieve nearly-identical metrics data resolution as the 6-hour browserid assertions used to give us, but (2) ensuring we stay above the magic six-hour threshold below which tokens are stored in mysql instead of redis. (MySQL couldn't handle the additional traffic, but redis should be able to handle it.)

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Data Sync does not seem to be working right now. Copying over the latest comment manually from github:

OK, after some discussion with @rfk ( https://github.com/rfk ) (see PR #6368 ( https://github.com/mozilla/fxa/pull/6368 ) for details), it seems the FPN problems in #5826 ( https://github.com/mozilla/fxa/issues/5826 ) are unique to their use case.
 We should be fine to lower the default access token TTLs down to just above six hours, so that we can (1) achieve nearly-identical metrics data resolution as the 6-hour browserid assertions used to give us, but (2) ensuring we stay above the magic six-hour threshold below which tokens are not stored in redis, and where the validation behavior is slightly different.

**Comment by 6a68** [comment]
jbuck mentioned in the release issue for train 187 (https://bugzilla.mozilla.org/show_bug.cgi?id=1664244#c1) that his plan is to gradually lower the token lifetime in prod from 48 hours to 24 hours to 12 hours to just over 6 hours.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

[~jhirsch@mozilla.com] I can't be 100% sure but I suspect that the TTL is not the only cause of this metric tanking. With a 48h TTL, we're undercounting our users at worst by 50% (missing 1 out of 2 days). But when we look at the metrics tanking, we've gone from a metric in the X Million ballpark to  X/5 Million ballpark (and still plummeting).

https://analytics.amplitude.com/mozilla-corp/chart/n2bn398

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

The access token TTL is now set to 24 hours in production

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

It doesn't seem to have had any impact on the multi-device metric.
https://analytics.amplitude.com/mozilla-corp/chart/n2bn398/edit/cernmr8

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Reopening, pulling this into the current sprint

**Comment by 6a68** [comment]
It looks to me like we have an off-by-one error here in the counts, rather than data loss:

https://analytics.amplitude.com/mozilla-corp/chart/4o2xg0y

**Comment by 6a68** [comment]
This issue was not fixed by #6987. Reopening.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Reclosing. Leif found a workaround query.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Closing, Leif and Alex found a workaround: a bigquery replacement that works well enough.
