### ISSUE TITLE
Roll out variation B to 100%

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5147]
From the parent Epic, Alex is asking that we:

bq. Let's roll out variation B to 100%: “Would you like to sync your phone?”

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1784)
┆Issue Number: FXA-1784

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for doing this on short notice, [~vbudhram@mozilla.com]

**Comment by vbudhram** [comment]
Fixed in https://github.com/mozilla/fxa/pull/5148
