### ISSUE TITLE
The canceled subscription mail is not send anymore when the user deletes his account

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#5164]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- All Platforms

#### Steps to reproduce
1. Create any subscription.
2. With the same account open the [FxA management page](https://accounts.stage.mozaws.net/settings).
3. Delete your account.
4. Open your inbox and look for the subscription cancellation mail.

#### Expected result:
- A subscription cancellation mail is sent and present in the inbox.

#### Actual result:
- The subscription cancellation mail is not sent.

Notes:
This issue is only reproducible when a user deletes their account.
The cancellation mail is still sent if the user cancels his subscription from the subscription management page.
We believe this was introduced when #5121 landed.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1792)
┆Issue Number: FXA-1792

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

This might be related to similar issue in sprint. It might get closed if unrelated/fixed.

**Comment by chelsea-lewis** [comment]
@bsurd is this still valid? In the more recent QA emails including signoff today we saw no majors remaining, but saw this in triage today.

**Comment by bsurd** [comment]
@chelsea-lewis this issue is no longer reproducing, tho I am leaving it open to see if it still happens after #5121 gets fixed as the last time when it got patched this issue was introduced.

**Comment by clouserw** [comment]
Is this fixed now?

**Comment by chelsea-lewis** [comment]
@ValentinaPC / @madalincm Please re-open if still reproducible. As Bogdan's last update was that this was not reproducing, I am closing this as resolved.
