### ISSUE TITLE
[l10n] Adjust styles to support rtl languages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5169]
Go through the new Settings page and flows and add rtl style overrides where necessary. Can we use https://github.com/RonMelkhior/tailwindcss-dir?

This should probably be done with multiple PRs, scoped to different flows or components.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1797)
┆Issue Number: FXA-1797

**Comment by yehudab** [comment]
Mind if I give it a try?
Already found one adjustment needed for the photo upload:
![photo upload](https://user-images.githubusercontent.com/633345/95076493-9842f080-071a-11eb-8c17-85ae20473026.png)

My fix for the above is ready in this commit: https://github.com/yehudab/fxa/commit/1e907bd18f9b892b82b024fea89c7d3cd6334d8c

**Comment by yehudab** [comment]
I see now that I was looking at the wrong path. Was checking `/settings` instead of `/beta/settings`
Anyway, this fix will probably be usefull for the new settings as well.
Will look now at `tailwindcss-dir`

**Comment by yehudab** [comment]
Started the tailwindcss-dir integeration. Looks pretty straight forward, please more work is needed.
Initial commit available here: https://github.com/yehudab/fxa/commit/d2990ee3f879942b04c324c12e33354529f78394

Some samples:
Before:
![new-settings-rtl-before](https://user-images.githubusercontent.com/633345/95121459-bd098900-0757-11eb-8599-39af2e21eab9.png)

After:
![new-settings-rtl-after](https://user-images.githubusercontent.com/633345/95121256-76b42a00-0757-11eb-994d-127c9dcba1d4.png)

**Comment by yehudab** [comment]
I also updated the project's README file. Should be easier to check the above diffs, after reading the new [RTL section](https://github.com/mozilla/fxa/blob/a623f0852a0e23d1c6de6e0bf691b402d1f8b607/packages/fxa-settings/README.md#rtl-support) in my branch.

**Comment by yehudab** [comment]
After more twicks and fixes for the new settings page, I feel pretty confident with my work. I'll open the 2 PRs now.
