### ISSUE TITLE
Implement the sync_engines_used user property on amplitude events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#517]
Spinning this out from #2076 as a dedicated issue because it requires jiggery-pokery.

The [taxonomy](https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4) defines `sync_engines_used` in `user_properties`. The content server definitely knows the answer to this when the user signs up, but I have no idea what we should do to get this information for existing users.

**Comment by davismtl** [comment]
Judging by this chart, have we already done this work?
https://analytics.amplitude.com/mozilla-corp/chart/new/8slglzb

@philbooth @irrationalagent 

If so, please close this issue.

**Comment by irrationalagent** [comment]
work is done, closing
