### ISSUE TITLE
Mail bounces error back to Stripe

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5193]
When handling a Stripe event, if the email that is being sent to bounces then our handler throws an error which is surfaced to Stripe as a 400. These were caused by `invoice.payment_succeeded` in our stage environment, as the email hard bounced with error:

{{{ "code": 400, "errno": 134, "error": "Bad Request", "message": "Email account hard bounced", "info": "https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format", "bouncedAt": 1588032984660 }}}

`We should return 200's to Stripe unless we want to retry.`

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1814)
┆Issue Number: FXA-1814

**Comment by bbangert** [comment]
Sentry issue: [AUTH-STAGE-16](https://sentry.prod.mozaws.net/operations/auth-stage/issues/8251662/)

I believe this is the Sentry error for this bug.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

bq. We should return 200's to Stripe unless we want to retry.

Do we want to retry?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Looks like test@testo.com was the email address for the customer ( https://dashboard.stripe.com/test/customers/cus_GZ7W7P4xbNI9Xl ) involved in this particular error.

So, the bounce makes sense, since it's a fake email. Quick fix would be to catch & log errors from sending emails from Stripe webhook event handling, but always respond with a 200.

Unless we want to retry, in which case this is arguably working as expected? (i.e. Stripe will retry on errors for up to three days ( https://stripe.com/docs/webhooks/best-practices#retry-logic ).)

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

I think les' suggestion makes sense here...catch and log the error, but respond w/ a 200

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I'm also good with catching and logging this. We might also want to Sentry log them so that we can get alerted on these and manually verify what happened and if action should be taken.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per Slack discussion with John Gruen, Ben Bangert, and Les Orchard, this is not a blocker for Train 169. We will bring this to triage tomorrow for estimation.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Trying to summarize further Slack discussion for future resolution:

  * Error responses to Stripe cause a retry of the event handling, which will retry sending the email.
  * However, we don't want to lean on Stripe's retry mechanism, because it results in false-positive notifications about site breakage.
  * Catching & logging bounces would avoid sending error responses to Stripe.
  * We should handle retrying on email bounce with an in-house queue and not just catch & log & ignore.

So, long term solution for this issue:

  * Trap errors from sending email.
  * Send Stripe a 200 OK response as long as the rest of event processing was successful.
  * Re-queue bounced email send on our own end.
