### ISSUE TITLE
[iOS] 2FA key cannot be copied

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5199]
**Build:**
Stage [Train 1.169.0]

**Affected platforms:**
iOS 13.4.1

**Steps to reproduce:**
1. Sign in with a Firefox account. 
2. Go to Account Settings -> 2FA section 
3. Tap on "Can't scan code?"
4. Copy the secret key.

**Expected results:**
The key is successfully copied to clipboard.

**Actual Results:**
The text cannot be selected and copied.

**Additional details:**
- This issue was reproduced on Firefox for iOS 25.0 (17803)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1820)
┆Issue Number: FXA-1820

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

Seems lower priority, since users can still download and 2FA will not be enabled.

**Comment by vasilicatamas** [comment]
> ➤ Vijay Budhram commented:
> Seems lower priority, since users can still download and 2FA will not be enabled.

I don't think this code can be downloaded in any way. It can only be manually typed in the authentication app, which can discourage the completion of the 2FA enabling process.

![Screenshot_8](https://user-images.githubusercontent.com/18114210/81176683-28370f80-8fae-11ea-8b40-3800590a5be8.png)

**Comment by vasilicatamas** [comment]
This issue is no longer reproducible on Firefox for iOS 28.0 (18809) under iOS 13.5.1 and 13.6. The code can be now successfully copied.

![Screenshot_24](https://user-images.githubusercontent.com/18114210/90374978-fccbc280-e07c-11ea-8967-3674b0e36877.png)
