### ISSUE TITLE
Use SNS bounce notifications to emit SMS deliverability metrics

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#520]

**Comment by clouserw** [comment]
@philbooth Is this still valid?

**Comment by philbooth** [comment]
> Is this still valid?

Possibly not, although I may not the best person to decide. I think it's possible for @jrgm and @jbuck to see the actual deliverability rate of our SMS messages using a chart in AWS somewhere so it's not like we have no visibility at all. But if we wanted to make those metrics more visible in either Amplitude or Redash, then we'd want to do this.

So closing, but anyone feel free to reopen if that's wrong.
