### ISSUE TITLE
Incorrect next billing date displayed in Subscription Resubscribe email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5200]
#### Affected versions:
* All Firefox

#### Affected Platforms:
* Windows 10 (64-bit)

#### Preconditions
* existent FxA account with which has unsubscribed from a subscription.

#### Steps to reproduce
1. Create a subscription
1. Cancel the subscription
1. Reactivate the subscription

#### Expected result:
* The next billing date is correctly displayed in the email.

#### Actual result:
* The next billing date is the same as the current billing date.

#### Notes
* This ticket was cloned from a DONE issue [https://github.com/mozilla/fxa/issues/5133](https://github.com/mozilla/fxa/issues/5133) involving different emails.
* In the /subscriptions fxa page the correct date is displayed, so this look only a issue in the emails.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1821)
┆Issue Number: FXA-1821

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Just to confirm, I think the steps to reproduce are actually:

  1. Create a subscription
  2. Cancel the subscription
  3. Reactivate the subscription

And the email in question is the subscription reactivation, not the initial payment received email

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Assuming those are the steps to reproduce, I can reproduce and I think will have a fix shortly.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Your steps to reproduce are correct from my understanding. Adjusted description accordingly.

**Comment by madalincm** [comment]
Verified as fixed in stage. The next invoice date is correct in the resubscribe email: 
![image](https://user-images.githubusercontent.com/15685441/81054700-f485b800-8ecf-11ea-8794-28af27628905.png)

Marking as verified.
