### ISSUE TITLE
'Unverified session' error on force-2FA flow

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#5206]
Looks like signing in to 123done with the 2fa required flow can sometimes run into an error where, after clicking 'sign in', the inline 2FA flow isn't opened. Instead, an "Unverified session" 500 error is shown.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1822)
┆Issue Number: FXA-1822

**Comment by 6a68** [comment]
Still exploring steps to reproduce this, but it appears this happens when

* account A is logged in to the browser
* account B logs in to 123done with the '2fa required' option
* neither account has 2fa already enabled

**Comment by 6a68** [comment]
I'm struggling to find steps to reproduce this bug.

The only time I've definitely seen this is when I was signed into the browser (production FxA environment), then tried to sign in to staging or stable dev 123done using the "require 2FA" button.

**Comment by diox** [comment]
I can reproduce with my account on https://stable.dev.lcip.org without being logged in to the browser (fresh profile).

**Comment by 6a68** [comment]
Huh. Can you reproduce with a new account, or just that one?

**Comment by diox** [comment]
I tried with a second existing account and got the 500 again. Tried creating a new account and it worked.

**Comment by bsurd** [comment]
Tried the following:
Sign In (Require 2FA) - 2FA not setup - no issues
Sign In - 2FA not setup - no issues
Sign In (Require 2FA) - 2FA setup - no issues
Sign In - 2FA setup - no issues

But all of these were done using a new account, from what @diox mentioned it could be that the issue is reproduced with pre-existing accounts only. So there might be something there. Sadly, can't confirm if this is the case because I don't really have any pre-existing accounts as I tend to delete them after I'm done testing with them.

**Comment by diox** [comment]
FWIW AMO QA team probably has a lot of old FxA accounts laying around on https://stable.dev.lcip.org given that's the server we use for our dev instance where they test patches after they land on AMO. But I'm not sure this would help give us steps to reproduce beyond "use an existing account".

**Comment by vasilicatamas** [comment]
I constantly reproduce this issue running the following steps:
1. Launch Firefox with a clean profile.
2. Navigate to https://stable.dev.lcip.org/ 
3. Create and confirm a new account.
4. Launch Firefox with a new clean profile
5. Navigate to https://123done-stable.dev.lcip.org/
6. Click on “Sign In (Require 2FA)” button.
7. Type the account credentials and click the “Sign in” button.

![500 error](https://user-images.githubusercontent.com/18114210/81083930-dd5dbf00-8efd-11ea-8dab-6cd1f8552844.gif)

**Comment by 6a68** [comment]
Great! Thank you so much, @vasilicatamas!

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

[~jhirsch@mozilla.com] will you be working on this next or current sprint?

**Comment by 6a68** [comment]
ah, current sprint. I'll add it

**Comment by 6a68** [comment]
Hi @vasilicatamas, could you try to reproduce this issue on stage?

I'm not able to reproduce locally or on stage, only on stable-dev. I wonder if this is only a bug in that particular environment.

**Comment by 6a68** [comment]
It appears that what's happening is that the account is verified, but the session is coming back as unverified.

The signin mixin checks that the account is verified before calling into the inline_totp_setup view; if the account is not verified, the confirm_signup_code view would be shown instead. But in this case, the inline_totp_setup view is shown.

The inline_totp_setup view then calls the `GET /totp/exists` endpoint on auth server, which returns a 400 'Unverified session' error if `session.verificationTokenId` is truthy. This is the error that's being displayed as a 500.

I don't think it should ever be the case that a session is marked unverified, while the account is verified.

**Comment by rfk** [comment]
> I don't think it should ever be the case that a session is marked unverified, while the account is verified.

It's very easy to get into a state where `accountVerified=true` and `sessionVerified=false` - create and very an account, then do a separate signin on another device, to a service that doesn't require session verification. IIUC that's essentially what the STR above are doing.

I expect if you try it from two different IP addresses, you'll be able to repro in production. We have some logic to automagically mark sessions as verified if they're created from an IP address that was previously used for another verified session. If that logic is not activated on stable-dev then it might explain the differences you're seeing.

**Comment by rfk** [comment]
> We have some logic to automagically mark sessions as verified ...

That's https://github.com/mozilla/fxa/blob/9a9aaade72a310e4eebc55f6356c5fe060a500e1/packages/fxa-auth-server/lib/routes/account.js#L723 for reference.

**Comment by 6a68** [comment]
@rfk Thanks for the explanation! Is there any way to handle this error more gracefully in the content-server? I can add an error handler [here](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/inline_totp_setup.js#L78), but I'm not sure how to help the user. Do they basically have to sign out and back in to fix the session verified state?

**Comment by rfk** [comment]
The ideal thing for the user would be to let them verify the session inline. Similar to what you describe above for unverified accounts, we could show a `confirm_signin_code` view of some sort before proceeding to the `inline_totp_setup` view. I don't know if we have an existing view for this, though.

In the settings-page version of this, expanding the "Two-step authentication" panel within an unverified session shows this:

![Capture](https://user-images.githubusercontent.com/34695/81127137-9cf35500-8f80-11ea-981b-1e0eff07cb82.PNG)

I expect you'll need an inline version of something similar. @vbudhram is probably the right person to talk to about the possibilities there.

**Comment by vasilicatamas** [comment]
@6a68  I didn't manage to reproduce this issue on stage following the dev environment str. 
> 1. Launch Firefox with a clean profile.
> 2. Navigate to https://stable.dev.lcip.org/
> 3. Create and confirm a new account.
> 4. Launch Firefox with a new clean profile
> 5. Navigate to https://123done-stable.dev.lcip.org/
> 6. Click on “Sign In (Require 2FA)” button.
> 7. Type the account credentials and click the “Sign in” button.

But I encountered this error using old stage accounts (with 2FA disabled) when signing on https://123done-stage.dev.lcip.org/ (Sign In (Require 2FA)) using a clean profile.

**Comment by vbudhram** [comment]
> In the settings-page version of this, expanding the "Two-step authentication" panel within an unverified session shows this:

This logic for this section is [here](https://github.com/mozilla/fxa/blob/8701348cdd79dbdc9879b2b4a55a23a135a32bc1/packages/fxa-content-server/app/scripts/views/mixins/upgrade-session-mixin.js#L129). I imagine you could do something like this in the beforeRender of inline totp page.

```javascript
  beforeRender() {
    // ...
    return account.checkTotpTokenExists().then(result => {
     // ...
    })
    .catch((err) => {
       // if unverified error
      this.relier.set('redirectTo', this.window.location.href);
      return this.replaceCurrentPage('/signin_token_code');
    })
  },
```

This would be nice to have as a mixin because we now have views that require sessions to be verified.

**Comment by 6a68** [comment]
@vbudhram thanks for the hint! Way less complicated than the patch I was working on 🥇

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Just closed this via https://github.com/mozilla/fxa/pull/6246

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~vtamas@mozilla.com] We believe this to be resolved. Could you test again to verify?

**Comment by vasilicatamas** [comment]
> 1. Launch Firefox with a clean profile.
> 2. Navigate to https://stable.dev.lcip.org/
> 3. Create and confirm a new account.
> 4. Launch Firefox with a new clean profile
> 5. Navigate to https://123done-stable.dev.lcip.org/
> 6. Click on “Sign In (Require 2FA)” button.
> 7. Type the account credentials and click the “Sign in” button.

Verified this issue following the above steps on Windows 10 64-bit. The "Unverified session" 500 error is no longer shown and the 2FA flow successfully starts. 

@6a68 Are there any other STR by which this issue should be verified?

![issue10](https://user-images.githubusercontent.com/18114210/91327793-affb9080-e7ce-11ea-9d4e-aa9eb22297d0.gif)

**Comment by 6a68** [comment]
@vasilicatamas Nope, I think we're done here. Thanks very much for verifying it's fixed!

**Comment by vasilicatamas** [comment]
> @vasilicatamas Nope, I think we're done here. Thanks very much for verifying it's fixed!

Glad that I could help. Marking as Verified fixed.

**Comment by diox** [comment]
When testing this on AMO, I got a new error preventing me to log in after this fix. I filed https://github.com/mozilla/fxa/issues/6342
