### ISSUE TITLE
Account panel gets cut off horizontally when a long fxa account name is displayed [bz1624567]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#5228]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1624567

Created attachment 9135376
menu_cut.jpg

See screenshot.
On OSX, 13 inch macbook with Display set to "Larger text" (the left most option).
The right hand side of the popup the icons get cut off.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1835)
┆Issue Number: FXA-1835

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Bumping this to train 173 since my train is full for 172.
