### ISSUE TITLE
Use one domain across our entire emails

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#523]
(moved from https://github.com/mozilla/fxa-auth-mailer/issues/267#issuecomment-294670031)

The phishing message displayed to Outlook users about our emails reminded me to check all the domain names in our emails.

At my past job, we would get flagged as spam if our images loaded from a different domain than the sender. Apparently this is something that is checked for phishing.

It turns out that we make this mistake. Our sender is accounts@firefox.com but our images are loaded from http://image.e.mozilla.org. Our privacy policy in our footer also points to mozilla.org too.

I don't recall if sub domains are also problematical but I know a few people that can answer that for us.

This is somewhat related to #4 from this link (essentially consistency is important).
https://www.campaignmonitor.com/blog/email-marketing/2015/09/9-things-that-are-killing-your-email-deliverability/

Also domain related:
"Use the same domain in the email From field as the actual domain sending the message. Hotmail is especially scrupulous about this and likes to filter the messages as junk mail if the two domains do not match."

http://www.datavalidation.com/blog/How-to-Optimize-Your-Email-Deliverability-and-Maximize-Your-Email-Marketing-Revenues.html

Our smtp is amazonses.com so we also make this mistake. :-/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-692)
┆Issue Number: FXA-692

**Comment by clouserw** [comment]
Next step for this would be to audit our emails since they've changed a few times since this was filed.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm forward-duping this to FXA-3490 as there is some active work there.
