### ISSUE TITLE
Return 304 from /account/devices if device list on the client is current

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa#524]
C/cing the message from [Bugzilla#1351481](https://bugzilla.mozilla.org/show_bug.cgi?id=1351481) for more visibility

---

In [Bug 1351104](https://bugzilla.mozilla.org/show_bug.cgi?id=1351104) we're going to start fetching the list of FxA devices much more frequently on Android clients, and we're planning to expose "refresh devices list" functionality more broadly in the UI. Similar changes are likely to happen on other clients.

It would be great if we could short-circuit this somehow if our cached device list is current. Adding an ETag or timestamp-driven "If-Modified-Since" conditional request support seems like a good way to achieve this.

This would:
- reduce server load
- reduce bandwidth and resource use on clients, especially important for mobile clients
- make for a snappier UX in most uses of "pull-to-refresh" or similar user-facing refresh functionality

**Comment by vladikoff** [comment]
Let's reopen if this becomes an issue on the servers IMHO
