### ISSUE TITLE
Production sourcemaps are pointing at a wrong file in Chrome and Firefox

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#5247]
Open url: 

https://accounts.firefox.com/authorization?action=email&response_type=code&client_id=5882386c6d801776&scope=profile+https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Flockbox&state=nAtuaf5kmoqUauyVFI9TxQ&code_challenge_method=S256&code_challenge=FuqP_hfzat0FRx1TlcswUjKZZd0Bk09bW1oSIoyDKVM&access_type=offline&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IkxOQXBzZHlndUxZQ1FsN2U5MUZLcVNlOC00Z0lVWU16d29QNlM3RHp5WEEiLCJ5IjoiZDFWdDdqUW9OLVFDZWtCek9jd1ZzOEZxU0dxOGNmV3UxVHBFZE5jSnFCQSJ9

## Actual

Chrome sourcemap (production):
![image](https://user-images.githubusercontent.com/128755/81338624-f17afb00-907a-11ea-9db3-40882b069411.png)
Firefox:
![image](https://user-images.githubusercontent.com/128755/81338655-fcce2680-907a-11ea-8540-1fc03dfd6770.png)

**The _validateKeyScopeRequest function is not in fxa-client.js** It is in oauth.js.

## Expected

Chrome (localhost:3030 server dev mode)

![image](https://user-images.githubusercontent.com/128755/81338682-08215200-907b-11ea-8f54-6b02d7968811.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1853)
┆Issue Number: FXA-1853

**Comment by data-sync-user** [comment]
➤ David Justice commented:

Seeing this also, we should take a look at our webpack config for the production builds
