### ISSUE TITLE
Gitignore prevented a `.stylelintrc` from being added

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#5250]
While looking at #5189, I noticed adding a `.stylelintrc` file locally wasn't being picked up by git.

```
git check-ignore -v .stylelintrc
.gitignore:54:.*	.stylelintrc
```

https://github.com/mozilla/fxa/blob/master/.gitignore#L54

Looks like `.*` was the issue, but I don't recall running into this with other dot files. Why do we need this for Linux anyway? 🤔

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1855)
┆Issue Number: FXA-1855

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's remove the `.*` line and reevaluate the allow-list lines below it.
