### ISSUE TITLE
Duplicate field in contact support form

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5265]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Open /subscriptions page: https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Click the Contact Support button
3. Observe the form

#### Expected result:
- No UI issues

#### Actual result:
- The form contains 2 "What are you contacting us about?" fields.

![image](https://user-images.githubusercontent.com/15685441/81552651-88ea9180-938c-11ea-88a8-95523edaecf5.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1859)
┆Issue Number: FXA-1859

**Comment by jackiemunroe** [comment]
@madalincm We have reverted the commit that introduced the new fields. Please verify if this has now been resolved. Thanks :)

**Comment by madalincm** [comment]
Verified as fixed in stage. The issue is no longer reproducing.
![image](https://user-images.githubusercontent.com/15685441/81941710-dae81d00-9601-11ea-840d-fa0c5f10199a.png)
