### ISSUE TITLE
Inactive "Send" button from an empty Contact Support form can be clicked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5266]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Open /subscriptions page: https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Click the Contact Support button
3. Click on "Send" button without filling something in any fields. 

#### Expected result:
- "Send" is inactive and nothing happens at click.

#### Actual result:
- "Send" button can be clicked. After click turns active and a loading spinner is displayed on top of it.
- The following message is also displayed "Hmm, we're having trouble with our system. We're working on fixing it for you and apologize for the inconvenience. Please try again later." error message is displayed."

#### Notes:
- dismissing the popup with the message and filling up all mandatory fields will not stop the loading spinner.

![contact support](https://user-images.githubusercontent.com/15685960/81565628-4f248580-93a2-11ea-9818-fa10c3184d7b.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1860)
┆Issue Number: FXA-1860

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jmunroe@mozilla.com] - assigning to you because we think this may be related to the recent patch to adjust these fields.

**Comment by jackiemunroe** [comment]
@ValentinaPC We have reverted the commit that likely caused this issue. Please verify if this has been resolved. Thanks :)

**Comment by ValentinaPC** [comment]
I have verified this and seems like the revert of the commit did not fix it.
Still reproducing following above STRs.
![image](https://user-images.githubusercontent.com/15685960/81897702-dd298780-95bf-11ea-958f-d01b37140d00.png)

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

Thanks for looking into it 😀

**Comment by ValentinaPC** [comment]
Verified as fixed  in stage, using Fx76 and Windows 10 (64-bit).
Postfix video below.
![sendb](https://user-images.githubusercontent.com/15685960/82640884-0ecfcd80-9c14-11ea-8453-902787567f59.gif)
