### ISSUE TITLE
fxa-content-server-l10n still failing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5268]
Looks like this failed again on Friday.  This is only the cron job that runs on Friday mornings.  Here is a link to the failure: [https://circleci.com/gh/mozilla/fxa-content-server-l10n/6404](https://circleci.com/gh/mozilla/fxa-content-server-l10n/6404)

Looks like something with Sentry in fxa-shared, maybe:

> fxa-shared@1.170.0 postinstall /home/circleci/project/workspace/fxa/packages/fxa-auth-server/node_modules/fxa-shared
> npm run build

> fxa-shared@1.170.0 build /home/circleci/project/workspace/fxa/packages/fxa-shared
> tsc

lib/sentry.ts:5:25 - error TS2307: Cannot find module '@sentry/browser'.

5 import * as Sentry from '@sentry/browser';
                          ~~~~~~~~~~~~~~~~~

test/lib/logger.ts:10:16 - error TS2503: Cannot find namespace 'sinon'.

10 let consoleFn: sinon.SinonSpy;
                  ~~~~~

test/lib/sentry.ts:7:25 - error TS2307: Cannot find module '@sentry/browser'.

7 import * as Sentry from '@sentry/browser';
                          ~~~~~~~~~~~~~~~~~

test/lib/sentry.ts:21:41 - error TS2503: Cannot find namespace 'sinon'.

21     (globalThis.window.console.error as sinon.SinonSpy).restore();
                                           ~~~~~

Found 4 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fxa-shared@1.170.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fxa-shared@1.170.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-05-08T16_01_39_103Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fxa-shared@1.170.0 postinstall: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fxa-shared@1.170.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-05-08T16_01_39_139Z-debug.log
./scripts/extract-and-pull-request.sh: line 10: cd: fxa/packages/fxa-content-server: No such file or directory
./scripts/extract-and-pull-request.sh: line 15: ./scripts/extract_strings.sh: No such file or directoryExited with code exit status 127



┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1861)
┆Issue Number: FXA-1861

**Comment by dannycoates** [comment]
https://app.circleci.com/pipelines/github/mozilla/fxa-content-server-l10n/186/workflows/c815446c-f2b2-4e04-9731-2c2eae0cda24/jobs/6431/steps

but will need updates for yarn
