### ISSUE TITLE
console.log the active feature flags

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#527]
It should be possible for an interested user to discover which experiments/feature-flags they are part of. This could be as simple as printing them to `console.log` after page load.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-694)
┆Issue Number: FXA-694

**Comment by Cronus1007** [comment]
@dannycoates I guess that this issue is now available for work.So shall I proceed with it.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
