### ISSUE TITLE
[train-170] revert sms change to limit sms to 10% in US/CA

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5277]
We put v1.169.3 live, configured as Transactional SMS, us-west-2 in production today. That tag includes the change https://github.com/mozilla/fxa/commit/5f750ee080c0e2e48ac9bc5c822a1beb27bc37ef

SMS are being delivered successfully. We'll let that run for now in that configuration in production.

But for 170, we'll need to partially (or completely) revert[1] that change to send more in US/CA and/or send to other countries. 

[1] - the change packages/fxa-customs-server/lib/config/config.js to reduce maxSms should not be reverted.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1865)
┆Issue Number: FXA-1865

**Comment by vbudhram** [comment]
Fixed in https://github.com/mozilla/fxa/pull/5281
