### ISSUE TITLE
QA Login Flow on Android

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#529]
45% of Android users don't successfully submit their login form.

In other words, they submit the login form but don't successfully login. This is the step preceding the email confirmation. Things that come to mind:
- incorrect passwords
- typos
- forms capitalizing first letters
- spaces getting added to email or password
- etc..

This failure rate is MUCH higher than other OSs. Note that iOS has the highest success rate, even when compared to Desktop so this is not a mobile-specific problem. It's an Android-specific problem.

If we can figure out what is causing the problem, we can have a substantial boost to our overall login success rate. See:
https://docs.google.com/spreadsheets/d/1wDvyOxEMoJ3EUjNlM5xPDNGwjefOAL27H-AEuD0wV6c/edit#gid=0

Note: If we cannot find the problem through QA, we may need to do UR. I'd like us to start here though.

**Comment by davismtl** [comment]
From Sorina:

>Please note that this email stands as a test report for the PI request “Fxa login and registration on >Android” on Firefox Release 66.0.2. 
>
>Our main focus during this testing was to verify that login and registration flow works as expected, >meaning that Firefox does not crash/hangs or becomes unresponsive.
>
>We didn’t find any major differences between iOS and Android, but it all depends on Android >versions. For 4.4.2 the pages were in loading mode more than on Android 7, 8 or 9. Also, on Windows >10 the flow worked as expected; the confirmations emails were sent and received on all platforms.
>
>Testing covered the following:
>
>    Firefox build: Firefox 66.0.2
>
>   Platforms: Win 10 x64, iPhone SE (12.1.4), Android 9, Android 8.1.0, Android 7.1.1, Android 7.0, >Android 6.0, Android 5.1.1, Android 5.0.2, Android 4.4.2
>
>Testing summary:
>[Test plan](https://docs.google.com/document/d/1WHANxJWPTSbxYkNDkGOmSpCzSk6pSKZQZ8QEZXe0LtU/edit)
>[Test report](https://docs.google.com/spreadsheets/d/1_PgvHFWsfcVXI93GCNd12LdVGqtPf5QEsbugUESYZ58/edit#gid=0)
>
>Issues found:
>
> - Sign In button unresponsive but we couldn’t reproduce 100% -  Android 5.0.2
> - Black page when tapping on the “Tap here to check Sync settings” - Android 4.4.2
> - “Invalid parameter” message displayed when a wrong password was used - Android 4.4.2 and 5.1.1
> - Field not focused when we change the password - small display devices
 Loading takes long on Android 4.4.2


From the QA perspective we suggest the following:

    Mail and password fields to be focused.

    Credentials hints (we think that users might try to login with wrong credentials and they end clicking “forgot password”).

    After we tap on create/sign in if the page is loading more than 2 seconds to move all the process in the background (even if we hit “back” button), in order to use the browser and not seeing just a loading screen. 


If more testing is needed, please let us know.

**Comment by shane-tomlinson** [comment]
@shane-tomlinson to open some issues.

**Comment by clouserw** [comment]
These issues are open.  Thanks!
