### ISSUE TITLE
Contact support confirmation popup message is incomplete

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5298]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription

#### Steps to reproduce
1. Open /subscriptions page: https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Click the “Contact Support” button
3. Fill out all fields and click “Send”
4. Observe confirmation popup message 

#### Expected result:
- There are no issues in the confirmation message..

#### Actual result:
The value of the “What are you contacting us about?” field is missing.

#### Notes:
- Reproducing for both (Firefox Guardian/Other) options.

![for](https://user-images.githubusercontent.com/15685960/81788810-c7f32100-950b-11ea-9f4f-8137b19f42f5.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1875)
┆Issue Number: FXA-1875

**Comment by ValentinaPC** [comment]
This is also happening in production.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jmunroe@mozilla.com] you've been working on this, but I think all your changes were backed out?

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

[~wclouser@mozilla.com] yes, those changes were reverted. I will do a sanity check now to verify that all of it was indeed removed.

**Comment by jackiemunroe** [comment]
@clouserw this is an existing issue. it would be a 1 to fix this. 

In packages/fxa-content-server/app/scripts/views/support.js :: line 213
`const escapedSelectedPlan = _.escape(this.supportForm.attributes.plan);`
needs to be changed to:
`const escapedSelectedPlan = _.escape(this.supportForm.attributes.product);`

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx76 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/83489570-47469580-a4b7-11ea-8ee9-9e60588b4cac.png)

@jackiemunroe I suppose that this is intended, but just wanna be sure: while choosing the "Other" option from "What are you contacting us about?", the confirmation message does not mentions "Other". See below screenshot.
![Other-csform](https://user-images.githubusercontent.com/15685960/83489735-8e348b00-a4b7-11ea-915c-da7f5978e864.png)

**Comment by jackiemunroe** [comment]
yes. it is the intent that if "other" is selected, it is not displayed.

**Comment by ValentinaPC** [comment]
Based on the above comments, I'll mark this as verified fixed.
