### ISSUE TITLE
Pricing details listed in subscription form/e-mails do not correspond with the one listed in the Guardian-stage page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5301]
#### Affected versions:
- All Firefox;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account;

#### Steps to reproduce
1. Open Guardian page: https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn
2. Observe VPN pricing/month details listed
3. Log in using your FxA account
4. Make a subscription
5. Observe pricing details from subscription form

#### Expected result:
- Pricing information is the same everywhere.

#### Actual result:
- Guardian page lists 4.99$/month, but subscriptions form and e-mails list 9.99$/month.

![pricedetails](https://user-images.githubusercontent.com/15685960/81779685-e2260280-94fd-11ea-9f14-02e13a35ac78.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1878)
┆Issue Number: FXA-1878

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is just two teams working in their staging environments so they don't line up.  Since it's 4.99 everywhere at this point, let's update our stripe price point to be 4.99 in stage.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

We've fixed this in Stripe, Guardian stage must update their link to use plan: plan_HJyNT4gbuyyZ0G

**Comment by rlr** [comment]
@bbangert When using that new plan, I'm not seeing any subscription come back in the user profile (using client `6089c54fdc970aed`)

**Comment by rlr** [comment]
Profile returned:
```
{"email":"ricky+65@mozilla.com","locale":"en-US,en;q=0.7,de;q=0.3","amrValues":["pwd","email"],"twoFactorAuthentication":false,"uid":"d9e3c35a88de421aa4adb6c829c9ec32","avatar":"https://mozillausercontent.com/00000000000000000000000000000000","avatarDefault":true}
```

Subscription page:
<img width="685" alt="Screen Shot 2020-06-05 at 6 03 22 PM" src="https://user-images.githubusercontent.com/36629/83926086-dae9c180-a756-11ea-9040-d4f3a9fb8d63.png">
