### ISSUE TITLE
[auth-server] lower logging of metricsEvents.emitFlowEvent "missingFlowId":true

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5306]
Thanks for the fix in https://github.com/mozilla/fxa/pull/5223 

I was looking again at our log usage for auth server, and there remains this kind of missingFlowId message:
```
... "Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,
"Pid":1,"EnvVersion":"2.0","Fields":{"event":"route./verify.200","missingFlowId":true}}
```
and usually its for the verify.200 route. It counts for ~12% of the log volume in bytes now (after other reductions https://github.com/mozilla/fxa/pull/5223 and for geodb in https://github.com/mozilla/fxa/pull/5139).

That's from https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/metrics/events.js#L212-L216. If that's not actionable, perhaps that error can be lowered to log.trace level (?).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1880)
┆Issue Number: FXA-1880

**Comment by jrgm** [comment]
And if it is really an error, do we need to do something with this?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's make this log.trace level

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It looks like auth server has all the logging levels except trace enabled... any reason for that?  We could make this debug instead, if so.
