### ISSUE TITLE
Ditch assertions when requestion OAuth authorization codes and access tokens, use a sessionToken instead

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#531]
With @rfk's great work to allow OAuth [authorization codes](https://github.com/mozilla/fxa-auth-server/pull/2932) and [access tokens](https://github.com/mozilla/fxa-auth-server/pull/2983) to be fetched using sessionTokens from the auth server, we can get rid of assertions! Let's do this!

Note, to move over to getting access tokens, we'll have to modify the way we do "implicit grants" to no longer get the access token from the /authorization endpoint, instead we'll need to go straight to the auth-server's /token endpoint with `grant_type=fxa-assertion`.

Blocked by https://github.com/mozilla/fxa-auth-server/pull/2932
Blocked by https://github.com/mozilla/fxa-auth-server/pull/2969
Blocked by https://github.com/mozilla/fxa-auth-server/pull/2983

**Comment by clouserw** [comment]
I'm moving this to backlog based on being blocked on the above bug, which is also in backlog
