### ISSUE TITLE
[profile] possibly switch batch.cached logline to statsd

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5311]
About 40% of the log _lines_ for profile server are like this line:
```
{"Timestamp":1589406163905000000,"Logger":"fxa-profile-server",
"Type":"routes.profile.batch.cached","Severity":6,"Pid":1,"EnvVersion":"2.0",
"Fields":{"storedAt":1589371622438,"ttl":8658533}}
```
Not to over-optimize logging, but perhaps the `ttl` could be better used as a sampled statsd value, with the logging being reduced to trace level. - https://github.com/mozilla/fxa/blob/master/packages/fxa-profile-server/lib/routes/profile.js#L75-L81

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1883)
┆Issue Number: FXA-1883

**Comment by jrgm** [comment]
I suppose that in addition to recording the approximate ttl, we'd want to track the counts of the above and of the batch.cached alternative path to track the cache hit ratio - https://github.com/mozilla/fxa/blob/master/packages/fxa-profile-server/lib/routes/profile.js#L82-L84

**Comment by jrgm** [comment]
In bytes, that is about 28% of volume. Also contributes to cpu to handle logging so possibly can use fewer instances.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's make this a trace level too

**Comment by clouserw** [comment]
closed in https://github.com/mozilla/fxa/pull/5461
