### ISSUE TITLE
“Your new password must be different” error message disappears very quickly

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5312]
**Build**
Prod [Train 1.170.3]

**Affected platforms**
Windows 10 64-bit
Android 9

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to https://accounts.firefox.com/settings
3. Click on "Change" button from Password section.
4. Type the old password in all 3 fields: “Old password”, “New password” and “Re-enter password”.
5. Click “Change” button.

**Expected results**
“Your new password must be different” error message is successfully displayed. 

**Actual Results**
The error message is displayed only for a second. 

![different error](https://user-images.githubusercontent.com/18114210/81922716-2dffa700-95e5-11ea-9153-e995cbe58477.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1884)
┆Issue Number: FXA-1884

**Comment by byrw** [comment]
can I work on this?

**Comment by byrw** [comment]
Probably what is causing this issue is that, when the error appears the first password input is on focus. And because it's on focus, the password_strength_ballon will appear as well. But the one-visible-type-mixin.js does not allow the two of them to appear at the same time.

Considering this, the only working solution that I have found is making the error message appearing on the second password input(vpassword).

**Comment by LZoog** [comment]
@byrw sure thing, thank you!

I'm able to reproduce this and I think you're right, the focus jumps back to the first input so the tooltip is hidden in favor of showing the password balloon. I believe we actually want the input to jump back to make it easier to type a different password - would it be possible to simply not show the password balloon instead in this scenario, like this?

![image](https://user-images.githubusercontent.com/13018240/82374477-ba92d680-99e4-11ea-8c92-adc2f9e14079.png)

**Comment by byrw** [comment]
>would it be possible to simply not show the password balloon instead in this scenario, like this?

Yes, its possible. After some testing, a simple solution for this issue would be to make sure that the password input is on focus before rendering the error message. This way, password_strength_ballon will appear first, and  one-visible-type-mixin.js will remove the password_strength_ballon when the error tooltip appears.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.170.0] under Windows 10 64-bit and Android 9. One new issue was encountered during this testing and it is tracked separately in #5607 

![issue7](https://user-images.githubusercontent.com/18114210/84149391-1216e600-aa69-11ea-9900-92099209a38a.gif)
