### ISSUE TITLE
Convert all modules to ES2015 format

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#532]
## Description

We have a mixture of AMD, simplified AMD using both return and export, CommonJS using both exports and module.exports, ES2015 modules, and finally modules that use ES2015 imports and CommonJS module.exports.

This is ugly. Let's standardize on ES2015 modules for both importing exporting. Doing so will bring consistency to the code base, unblock #535, and enable us to remove the [babel-plugin-syntax-dynamic-import](https://github.com/shane-tomlinson/fxa-content-server/blob/9263051659cfb1c18967faba01bfd8abb1ac732a/webpack.config.js#L168) plugin from the WebPack build.

Note to any intrepid contributor thinking about doing this. I started 4 months ago and made significant progress in a day, but never finished the job. This is a major update that will touch nearly every front end file we have, including unit tests. Many files will need substantial indentation changes.

Because this is such a chore, I'd take a progressive approach, opening multiple PRs to merge early and often:

* [x] Remove the AMD wrapper around any modules
* [x] Convert all `require` expressions to `import`
* [x] Convert all module.exports to `export default`
* [ ] Remove `use strict` since modules by default are strict.

**Comment by farhan787** [comment]
> Note to any intrepid contributor thinking about doing this. 

@shane-tomlinson can I consider myself even 1% of intrepid contributor 😁

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson can I consider myself even 1% of intrepid contributor 😁

You took on a project I've wanted to do for 2 years. That's saying something. We are one step closer to "living in the present". 🤣 Thanks @farhan787!

**Comment by farhan787** [comment]
Your most welcome and thank you too for assigning this issue to me 😄
