### ISSUE TITLE
Enable failed tests insights in CircleCI

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#5320]
There is a page of insights for our CircleCI runs here:  https://circleci.com/build-insights/gh/mozilla/fxa/master

It has sections at the bottom for most failed tests and slowest failed tests that aren't populated because we're not sending the data to CircleCI.  In our meeting last week it sounded like we were already generating these xml files, we just weren't copying them to the right place for CircleCI to pick up.  Let's start sending this data to CircleCI.

CircleCI docs are at https://circleci.com/docs/2.0/collect-test-data/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1887)
┆Issue Number: FXA-1887

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Do we need to connect to the CircleCI API to access these numbers now?
