### ISSUE TITLE
Active Secure Proxy browser extension blocks the user to be able to download the VPN app from Guardian page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5335]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.171.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- have a FxA account with active subscription;
- have the Secure Proxy extension installed and active

#### Steps to reproduce
1. Open Guardian page: https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn .
2. Click on the “Download Now” button.
3. Observe the “Download” button for the 3 devices.

#### Expected result:
- The “Download” button is active and functional. 

#### Actual result:
-  An “You can only download this app from the United States.” info message is displayed.

#### Notes:
- Reproducing for 21 and 22 versions of the secure proxy extension.

![Untitled](https://user-images.githubusercontent.com/15685960/82035985-fb1ee700-96a8-11ea-8597-a177cb00b4b9.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1898)
┆Issue Number: FXA-1898

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

If you go to https://whatismyipaddress.com/ ( https://whatismyipaddress.com/ ) where does it say you are connecting from?  If the proxy endpoint is outside of the US this is working properly.

**Comment by ValentinaPC** [comment]
> 
> 
> ➤ Wil Clouser commented:
> 
> If you go to https://whatismyipaddress.com/ ( https://whatismyipaddress.com/ ) where does it say you are connecting from?  If the proxy endpoint is outside of the US this is working properly.

Sorry for the late reply.
It says that I am connecting from US. See screenshot below.
![image](https://user-images.githubusercontent.com/15685960/82649344-b43d6e00-9c21-11ea-974d-edeb37b25a17.png)

**Comment by clouserw** [comment]
Huh, that's not what I'd expect, but this sounds like a guardian website issue.  Please file at https://github.com/mozilla-services/guardian-website/issues
