### ISSUE TITLE
Existing account holders should not have to retype their email for Sync

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#534]
## Description

After registering and verifying for Monitor, I clicked on **Turn on Sync…* in the new toolbar panel. Instead of seeing the username and avatar, I instead got the blank email first form.

### Steps to reproduce

1. In a fresh Nightly profile go to monitor.fiorefox.com
2. Create an account and verify it
3. Click on **Turn on Sync…** in the new Sync toolbar menu item 

### Expected result

User only need to enter password to turn on Sync

### Actual result

User is presented with a blank email first form.

### Environment

Nightly on macOS.

**Comment by davismtl** [comment]
@shane-tomlinson @ryanfeeley 
If I am not mistaken, this is resolved now thanks to Shane's patches from August. If this is correct, please close this.

**Comment by shane-tomlinson** [comment]
This is fixed:

![sync-email-not-needed](https://user-images.githubusercontent.com/848085/65953685-67abe500-e43c-11e9-8551-ac357f38bc88.gif)
