### ISSUE TITLE
Deleting the card from Stripe generates a 500 error while accessing subscriptions page using the same account

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5345]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.171.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- have a FxA account with active subscription;

#### Steps to reproduce
1. Go to Stripe - https://dashboard.stripe.com/ .
2. Delete the card associated with the account for which you made the subscription for in prerequisites.
3. Go to the subscriptions page for the same account.

#### Expected result:
- A friendly message is displayed informing the user that the card was deleted.

#### Actual result:
-  The page returns a 500 error with the ”Problem loading customer. An internal server error occurred” message.
![500 error](https://user-images.githubusercontent.com/15685960/82188957-56deaf80-98f7-11ea-8a2c-0e304ef03fa6.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1905)
┆Issue Number: FXA-1905

**Comment by lmorchard** [comment]
We should probably fix this error, but I don't think that we've planned for this use case.

A user can cancel a subscription from the payment-server UI. But, I don't remember a case where we'd want to delete a user's card while leaving the subscription active. What's the scenario where we'd want to do that?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm wondering the same thing as Les.  As far as I know, there is no use case for this.  [~jgruen@mozilla.com] for visibility.  I'll ping Patrick and JR also.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We talked this over in triage.  This isn't a situation that should ever occur so I'm going to close this.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

wontfix
