### ISSUE TITLE
Emails from support are not sent to FxA secondary mail

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5347]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.171.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions:
- have a FxA account with active subscription;
- have a secondary e-mail;

#### Steps to reproduce
1. Go to support page - https://accounts.stage.mozaws.net/support 
2. Send a support request.
3. Check your e-mail.

#### Expected result:
- The e-mail is sent to both primary and secondary emails.

#### Actual result
- The e-mail is sent only to the primary email.

#### Notes:
 - Not reproducing while canceling subscriptions or resubscribe.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1907)
┆Issue Number: FXA-1907

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is working as designed – emails should be delivered only to the primary email.

**Comment by ValentinaPC** [comment]
> 
> 
> ➤ Wil Clouser commented:
> 
> This is working as designed – emails should be delivered only to the primary email.

E-mails are sent to both addresses (primary and secondary) for subscription/cancel subscription/re-subscription, this is the case only for support mails.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Interesting, thanks for the info.  [~jgruen@mozilla.com]  - Which way do you want this to work or is it working already?
