### ISSUE TITLE
[content server] Show a user friendly error message when uploaded avatar image is too large

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5348]
This is a follow-up to FXA-1858.  When a user upload an avatar image that's greater than the configured size limit, we should display an error message to inform the user, instead of the current generic and confusing "System unavailable, try again soon."

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1908)
┆Issue Number: FXA-1908

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] Could you give us some text to use for this?

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

"The image is too large to uploaded and needs to be resized."

First pass without Content looking at it, good for now.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

To be clear, we're talking about the file size of the image being uploaded, not the pixel dimensions of the image.  Should we change the wording to specify that?

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

Yes, thank you for clarifying that.

"The image file size is too large to be uploaded."

**Comment by vasilicatamas** [comment]
“The image file size is too large to be uploaded.” error message is successfully displayed on Stage [Train 1.180.0] under Windows 10 64-bit, Android 9 and iOS 13.4.1. But its position doesn't seem to be the right one and a new issues was filed for tracking this bug separately #5975 . Marking this issues as Verified Fixed.

![Screenshot_14](https://user-images.githubusercontent.com/18114210/87806261-4008fa80-c85f-11ea-8509-15fb89c6eb99.png)
