### ISSUE TITLE
Only serve compiled ES5 JS to user agents that need it

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#535]
Right now we serve the same Babel compiled ES5 JS to all user-agents regardless of whether the user-agent supports new JS syntax or not. This has a couple of downsides:

1. The result is a much larger bundle, by ~ 100kb

<img width="830" alt="Screenshot 2019-03-25 at 12 55 21" src="https://user-images.githubusercontent.com/848085/54926534-64bdbe00-4f08-11e9-8958-de8a2f94a735.png">
<img width="839" alt="Screenshot 2019-03-25 at 12 56 44" src="https://user-images.githubusercontent.com/848085/54926535-64bdbe00-4f08-11e9-95fc-4c4c478d3f9a.png">

2. Stepping through code is more tedious because we have to rely on source maps, and sometimes the source maps don't map 1:1 to the actual code.

I could see this panning out like so:

1. Compile 2 JS bundles, one with "modern" syntax, one with ES5. 
  1a. Have to update [webpack.config.js](https://github.com/mozilla/fxa-content-server/blob/da94f530c8b5bb7477e207944ea0c6623af2f710/webpack.config.js) create two bundles, one with [babel-preset-es2015](https://github.com/mozilla/fxa-content-server/blob/da94f530c8b5bb7477e207944ea0c6623af2f710/webpack.config.js#L167) and one without.
2. Use [<script type="module">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) to serve "modern syntax" JS code, and `<script type="javascript" nomodule>` to serve ES5 code.
3. Win.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-696)
┆Issue Number: FXA-696

**Comment by 6a68** [comment]
Note that fxa-content-server issue #7094 has been migrated to https://github.com/mozilla/fxa/issues/532
