### ISSUE TITLE
Hook payments-server up to Pontoon for l10n

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#5353]
We're a fair ways down the road to ensuring payments-server is localized. But, as far as I can tell, we haven't gotten the FTL files in that project hooked up with Pontoon. We should do that -- and tie up whatever loose ends we might have that block doing that. (i.e. both implementation and process concerns)-

Note: Struck out tying up loose ends note as these are addressed by other tickets within this epic.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1910)
┆Issue Number: FXA-1910

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Coincidentally, we will be prioritizing this week per some late breaking updates from the VPN. Product is beginning to detail this out in epic FXA-1900, which I have linked to this ticket for tracking purposes. Thanks for filing this, Les.

cc: [~wclouser@mozilla.com] [~jgruen@mozilla.com] for your awareness.

**Comment by lmorchard** [comment]
Bit of tech context - we have one FTL file for the en-US locale living here, so far:

https://github.com/mozilla/fxa/tree/master/packages/fxa-payments-server/public/locales

Current implementation just deploys that as a static file with the rest of the site and active locales are listed in [locales.json](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/locales.json). (Though I see we list `fr-FR` as a locale, with no corresponding FTL)

These strings are *only* for the payments-server UI, though.

For translations of product-specific details, [we use Stripe metadata with locale overrides](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#product-metadata) that should be supplied by the teams owning the products themselves.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

There is a meeting with the L10n team about this on Wednesday on the internal calendar.  Anyone is welcome.

**Comment by data-sync-user** [comment]
➤ Axel Hecht commented:

Sorry for the lag, got a few wrenches flying by.

I did put up a fork of `fxa-content-server-l10n` on Pontoon stage, and added the `main.ftl` file to `locale/templates/main.ftl`.  That worked like expected.

A couple of things I noticed on the way: The comments in https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl ( https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl )  need a review. In particular the group comments don't end at the right places. I've also filed an issue to on cleaning up the repo.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Do you mean, for example, https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L173 ( https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L173 ) should be a single `#` ?

**Comment by data-sync-user** [comment]
➤ Axel Hecht commented:

That one's OK, but https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L220 ( https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L220 ) should have an empty `##` to unset the group comment from above. That happens a few times in the file.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The comments concerns are split out to https://jira.mozilla.com/browse/FXA-2020

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I made a patch at https://github.com/mozilla/fxa-content-server-l10n/pull/421 ( https://github.com/mozilla/fxa-content-server-l10n/pull/421 ) that I think closes the bulk of this bug, aside from "tie up loose ends"

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~wclouser@mozilla.com] per today's conversation this scope should be completed with your patch #4 21. I have stricken out the mention of the loose ends as those are resolved by other tasks within this epic.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Patch has landed.  We'll see on Friday morning when it runs if it copies the file...

Calling this done.
