### ISSUE TITLE
Add link to mozilla.org on Account Settings Page

### ISSUE THREAD

**Issue by trishla08** [mozilla/fxa#536]
I created an account for Firefox and was redirected to my Accounts Settings Page.

![image](https://user-images.githubusercontent.com/27439626/54829435-66a33980-4cdc-11e9-83fd-ab5f70f10ed5.png)

I strongly feel this page (and the logo) should have a link to [the Firefox page](https://www.mozilla.org/en-US/firefox/) and maybe additionally a download Firefox prompt for those who don't have it installed on the device they're current operating on. There should be a way to be led to the website where the user can explore more of what they can do with Firefox.

The Firefox logo at the top left should definitely be utilised as a link.

I am an Outreachy applicant and would like to work on it if you approve! Thanks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-697)
┆Issue Number: FXA-697

**Comment by Cronus1007** [comment]
@ryanfeeley Are you looking over this issue or shall I take over this issue.
