### ISSUE TITLE
Add statsd metrics around push notifications

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#5367]
The Sync team has recently been investigating the end-to-end quality of Send Tab, and one of the pieces we needed to dig in to was the success rate of sending push notifications to connected devices. See [here](https://docs.google.com/document/d/1XxNHWuotwNpaOSzrdN3KPu0bFPe28SSxZZp4HNWezhM/edit#heading=h.lsh1ooublr1l) for the ad-hoc analysis I was able to do on top of the existing logs in bigquery.

I'd like to make it easier to keep an eye on these metrics in future, and maybe even allow for some alerting if the success-rate of send-tab push delivery falls below a certain level. I believe that statsd is the preferred mechanism for this in FxA these days, so my strawman proposal is to modify the [`incrementPushAction`](https://github.com/mozilla/fxa/blob/b49b01a260ea25164a44341d5c3014f925352e48/packages/fxa-auth-server/lib/push.js#L105) to emit stats metrics such as:

* `statsd.increment("push.send", tags)` when we attempt to send a push
* `statsd.increment("push.send.success", tags)` when that succeeds
* `statsd.increment("push.send.error", tags)` when that fails

We can use tags to provide more fine-grained info, such as:

* `tags["reason"] = "accountVerify"|"commandReceived"|...` for the type of push being sent
* `tags["error"] = "no_callback"|"no_keys"|"reset"|...` for the cause of a failure to send
* `tags["ua_os"] = "ios"|"android"|"windows"|...` for the platform of the target device
* Maybe uaBrowserVersion etc here as well? I'm not sure how thrifty we need to be with possible tags.

This these metrics going to statsd, we could set up a dashboard for easy viewing and easy exploration by the different tags.

@bbangert what do you think, does this sound like a sensible approach?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1917)
┆Issue Number: FXA-1917

**Comment by bbangert** [comment]
This makes sense to me. There are some limitations with total tag cardinality still, I think they affect budget in some aspect. Otherwise I'm 👍

**Comment by sciurus** [comment]
I'm popping in at bbangert's request:

I'd expect uaBrowserVersion to have hundreds of values. This is too high cardinality to be a good fit for our metrics database. Can you rely on recording this in logs and analyzing it via Bigquery when needed instead?

I'm thinking `ua_os` would have just 5 values (ios, android, windows, os x, linux), `reason` would have [seven](https://github.com/mozilla/fxa/blob/bb3880cdc81758775fba69b3c8e7bcea03f123bf/packages/fxa-auth-server/docs/pushpayloads.schema.json#L7-L14), and `error` would have four (based on the linked doc). That all sounds helpful and not worrying for a cardinality perspective.

**Comment by rfk** [comment]
> I'd expect uaBrowserVersion to have hundreds of values. This is too high cardinality to be a good fit
> for our metrics database. Can you rely on recording this in logs and analyzing it via Bigquery when
> needed instead?

Yep, no worries. Thanks both, this is exactly the sort of feedback I was looking for :-)
