### ISSUE TITLE
Small discrepancies between subscriptions upgrade actual page and the one from specs

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5368]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.171.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page and make a subscription.
2. Load this page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM using the same browser session.
3. Observe the page: UI, strings, layout, etc.

#### Expected result:
- The actual upgrade subscription page corresponds with the one from specs.

#### Actual result:
- There are some discrepancies between them, as follows:
    - Some strings from “I authorize...” section are different;
    - There is an “Privacy Notice” footer link;
    - “Monthly” instead of “mo” in the plans section;
    - One section instead of two, in the Billing information section;
![mvsr](https://user-images.githubusercontent.com/15685960/82422529-3f383000-9a8b-11ea-85c7-2faa1870b419.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1918)
┆Issue Number: FXA-1918

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~amurphy@mozilla.com] - please confirm if the specs are correct or the implementation and we'll make the changes.  Thank you.

**Comment by jackiemunroe** [comment]
There were updates made as a part of the Longer Duration Subscriptions work (https://github.com/mozilla/fxa/issues/3987)
It should indeed be monthly.
@clouserw

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks Jackie.  Closing this as working as [re-] designed.
