### ISSUE TITLE
[Mobile] Subscription upgrade page is not rendered as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5369]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.171.0;

#### Affected Platforms:
- Android 10.0;

#### Preconditions:
- Have a mobile device with Firefox app installed and opened;

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page and make a subscription.
2. Load this page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM using the same browser session.
3. Observe the page layout.

#### Expected result:
- The page has a mobile layout.

#### Actual result:
- The page has a desktop layout.

#### Notes:
- There is also the possibility to scroll horizontally the subscription upgrade page while using the device.

![mobile1](https://user-images.githubusercontent.com/15685960/82426083-0fd7f200-9a90-11ea-8731-98e57df02b19.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1919)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16110/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-1919

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

What resolution (and/or device) are you using?  Thanks

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~djustice@mozilla.com] - We're in triage and trying to decipher the screenshot above.  We think the red box is around the part that is in question and in one it's a horizontal layout and in one it's a vertical layout.  Does that differ based on screen size?

**Comment by ValentinaPC** [comment]
> 
> 
> ➤ Wil Clouser commented:
> 
> What resolution (and/or device) are you using?  Thanks

I am using Samsung Galaxy A6 with Android 10.0 and screen size: 360x692.
You're welcome!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~djustice@mozilla.com] - please provide details above.  Thanks

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Looks like it may be a similar issue to FXA-3237.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

May be fixed by changes in https://github.com/mozilla/fxa/pull/8328

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

I could only check this partially, as we cannot the upgrade part, yet.
The page that we display now, has no UI or layout issues.
But we should wait for the upgrade to be possible, to check the rest.
 !screenshot-1.png|thumbnail!

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

[~vvirlics@mozilla.com], when it is time to verify this, can you verify that there is no horizontal scrollbar anymore on mobile?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Sure. [~bdanforth@mozilla.com]
