### ISSUE TITLE
[RTL] The "Generate" button is overlapping the key icon under Account Recovery

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/fxa#537]
## Description

In the Firefox Accounts settings under Account Recovery, the "Generate" button is overlapping the key icon, on RTL locales.

### Steps to reproduce

1. Open RTL version of Firefox Accounts
2. Log in
3. Account Recovery
4. See the key icon

### Expected result

I'm not sure how this is currently looking in LTR, but at least the icon shouldn't be overlapped.
![תמונה](https://user-images.githubusercontent.com/18016656/54773268-e1ebe900-4c11-11e9-87fb-8eacab20a6ca.png)

### Actual result

The "Generate" button is overlapping the key icon.

### Environment

Windows 10 x64, latest Nightly.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-698)
┆Issue Number: FXA-698

**Comment by jodyheavener** [comment]
It looks like this was addressed here: https://github.com/mozilla/fxa/commit/5c6d094a143d7892dca7d8dff0f695555bd4d845#diff-0118be3b5284f51ab0f0b2ade3d15273

My own testing shows it fixed as well.
