### ISSUE TITLE
[Tablet]Black bar presented on Zoom control from avatar

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#538]
Environment:
Devices: Samsung Galaxy Tab S3 (Android 8.0) - Tablet;
Build: [Stage Train 133];

Prerequisites:
Make sure you are logged in a valid account.

Steps to reproduce:
1. Go to https://accounts.firefox.com/settings;
2. Tap the 'Change' button from the Account picture area;
3. Tap on the 'Upload' button;
4. Take a photo ;
5. Pay attention to the space between zoom control buttons.

Expected result:
A line is presented between the zoom controls buttons.

Actual result:
A black bar is presented.

Notes:
-Not reproducible on IOS and Windows;
-Not reproducible on phones;
![Screenshot_20190321-154817_Firefox Beta](https://user-images.githubusercontent.com/40264165/54761954-cd045b00-4bfb-11e9-938e-32c3e62a1360.jpg)

**Comment by shane-tomlinson** [comment]
Closing as dup of #557
