### ISSUE TITLE
Run storybook publishing from CircleCI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#5385]
In #4823 / FXA-1542, I got the scripts together to build & publish static Storybook builds for commits & pull request. I did not get those scripts hooked up to CircleCI to run after tests. We should do that.

Some notes-to-implementor (probably me):

* This *should* run similarly to [`_scripts/gh-pages.sh`](https://github.com/mozilla/fxa/blob/master/_scripts/gh-pages.sh) - do we actually run that any more?
* Rather than use mozilla/fxa, it seems safer & cleaner to create a new repo to which the gh-pages content is pushed - e.g. mozilla-fxa/storybooks
* Probably also safer to create a new user that can only push to that repo and not mozilla/fxa - though, this may be overkill
* For bonus points, also post a comment with a link to the Storybook build for that PR. This part is a [one-line curl command to POST with an API token](https://github.com/mozilla/testpilot/blob/master/bin/deploy-storybook.sh#L71) (or a simple `fetch()` in JS)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1937)
┆Issue Number: FXA-1937

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Added another story point - had to tweak things a bit for yarn and recent shared component module changes. Also added some bits to try skipping build work if storybook-using packages weren't involved in the PR.
