### ISSUE TITLE
Login blocked because 2FA isn't enabled, but 2FA shows as enabled in account settings

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/fxa#540]
Note: I can't reproduce this since @gdestuynder turned off 2FA verification during FxA authentication, but I imagine the bug still exists

Steps:
1. Open voice.mozilla.org
2. Click "Log In / Sign Up"
3. Select "Log in with Firefox"
4. Click "Sign In" on Firefox Accounts page (I'm already logged in to Firefox Accounts)
5. Red banner saying 2FA needs to be enabled is displayed
6. Open https://accounts.firefox.com/settings/two_step_authentication
7. Two-step authentication says "Enabled"

@gdestuynder you might be able to fill more information in here as I'm not sure what's going on behind the scenes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-700)
┆Issue Number: FXA-700

**Comment by shane-tomlinson** [comment]
Ref #589
