### ISSUE TITLE
Discuss appropriate cache-control headers for JWT token keys

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#5411]
In conversation with @fzzzy, we were wondering about the right cache-control settings for the management of JWT signing keys between FxA and Tokenserver. Here's what came out in the reasoning:

Currently, every OAuth request to tokenserver results in one request from tokenserver to FxA, calling `/verify` to verify the token. Previously this would involve a database lookup, but @dannycoates recently landed some logic to verify JWT tokens without hitting the db.

If tokenserver switches to local verification of JWTs, then it needs to do *two* network requests: one to `/.well-known/openid-configuration` to discover the OAuth server metadata, and another to the value of `jwks_uri` contained therein in order to obtain the public keys.

If we do that for every token that needs to be verified, it's a net loss for both services; we've replaced a single request with two!

So obviously we need some caching. I checked the cache-control headers and we currently have:

* https://accounts.firefox.com/.well-known/openid-configuration => `public, max-age=3600`
* https://oauth.accounts.firefox.com/v1/jwks => `max-age=10, must-revalidate, public`

So assuming tokenserver respects these headers, it would fetch the `openid-configuration` once every hour, and the keys once every 10 seconds.

Are we comfortable with these values, or would we like to consider tweaking them?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1951)
┆Issue Number: FXA-1951

**Comment by rfk** [comment]
For comparison, the cache settings for BrowserID key lookup are:

* https://api.accounts.firefox.com/.well-known/browserid => `max-age=10, must-revalidate, public`

That is, they're the same as for the OAuth keys. And I think that's been OK for us in general.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It sounds reasonable to me (and thanks for respecting headers!)

[~dcoates@mozilla.com]?

**Comment by data-sync-user** [comment]
➤ Daniel Coates commented:

sgtm. I wonder if we have nginx cache these on our side as well? If so that'd be even better!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~rkelly@mozilla.com] This sounds fine to us.  Is there more to do in this issue?

[~jmorrison@mozilla.com] Do we cache these routes in nginx?

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I'm happy to close this as "happy with the status quo", thanks for taking a look :thumbsup:

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you!
