### ISSUE TITLE
Have auth-server serve a copy of the openid-configuration file from its domain

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#5412]
The canonical OpenID/OAuth configuration file for FxA lives here:

* https://accounts.firefox.com/.well-known/openid-configuration

However, because we've previously encouraged OAuth clients to use the special "oauth.accounts.firefox.com" domain for OAuth operations, it may not be obvious how they should form the URL from which to fetch this document. They could hack off the "oauth." prefix for the default production domain, but that doesn't scale well to stage or self-hosting setups.

What do y'all think about having this URL work as well, either as a clone or as a simple redirect to the canonical one:

* https://oauth.accounts.firefox.com/.well-known/openid-configuration

The contents of this file contain an "issuer" field that's specifically designed to identify the canonical domain, so I think this would work out OK from a security perspective.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1952)
┆Issue Number: FXA-1952

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This seems fine.

This fix is in content-server.
