### ISSUE TITLE
500 error page at “Continue to download” from subscription confirmation page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5413]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions:
- Have a new, clean Firefox profile.

#### Steps to reproduce
1. Open FPN page:  https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn  
2. Click on the “Subscribe Now” button.
3.  Finalize sign in.
4. Finalize subscription flow.
5. Click “Continue to Download” from the subscription confirmation page.

#### Expected result:
- The download page is loaded.

#### Actual result:
- An unknown page is loaded.

#### Notes:
- Page is dismissed at browser refresh.

![image](https://user-images.githubusercontent.com/15685960/82642623-e2698080-9c16-11ea-8585-13c2ac410cd5.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1953)
┆Issue Number: FXA-1953

**Comment by clouserw** [comment]
This sounds like a guardian website error.  Please file at https://github.com/mozilla-services/guardian-website/issues .  I can't transfer since it's a different org.
