### ISSUE TITLE
500 Error page is displayed instead of registration/signin confirmation page on Fennec

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5415]
**Build**
Stage [Train 1.172.0]

**Affected platforms**
Android 9 

**Steps to reproduce**
1. Install Fennec and launch the app.
2. Tap on Sign in to Sync button.
3. Follow the account creation flow.
4. Observe the confirmation page.

**Expected results**
“Sign in to Firefox on another device to complete set-up” page together with the successfully green message “The Firefox is connected” are successfully displayed.

**Actual Results**
500 Error page is displayed.

**Additional notes**
- This issue is also encountered at the end of the login flow. 
- This issue is a regression because it is not reproducible on FxA Prod [Train 1.171.1] using the same devices.

![Screenshot_20](https://user-images.githubusercontent.com/18114210/82658275-616ab300-9c2f-11ea-847a-c2f9ab20df52.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1955)
┆Issue Number: FXA-1955

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Are you able to give us the full URL that it's trying to load?

/cc [~vfilippov@mozilla.com]

**Comment by jackyzy823** [comment]
I'm using a self hosted fxa and encounter similar problem in fxa v1.172.0.
This same 500 error page displayed in page `content-server_url/connect_another_device` after the page of entering  verification code of registration.

When i switch back version v1.171 . 
It displays a page including content of "This firefox is connected" 
![Screenshot_2020-05-24 Connect another device](https://user-images.githubusercontent.com/2900871/82755892-45226e00-9e09-11ea-9b06-285cea3099c9.png)

In my self config . I disabled `SMS`  in auth-server.  So I think it may related to `sms`  and `CAD` issues .

**Comment by vbudhram** [comment]
@jackyzy823 @vasilicatamas Thanks for the report, this was indeed related to the sms/CAD experiment and was fixed in https://github.com/mozilla/fxa/pull/5477.
