### ISSUE TITLE
payments-server build mystery

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#5428]
So this doesn't get forgotten... Follow-up on this thread https://github.com/mozilla/fxa/pull/5352#discussion_r427632013

It'd be nice to not have to do a full `yarn install` for payments-server tests to pass.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1967)
┆Issue Number: FXA-1967

**Comment by dannycoates** [comment]
This should be reproducible locally with:
```
yarn workspaces focus fxa-payments-server
yarn test
```

**Comment by lmorchard** [comment]
I did just run into an error trying to build storybook for fxa-payments-server and found that fxa-react was missing a dependency on fxa-content-server. Not sure if that's relevant here?

https://github.com/mozilla/fxa/pull/5429/files#diff-49ea761e488940ca87a1522acea455a2R26
