### ISSUE TITLE
[Fenix] Extra highlighter for Settings page buttons

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5435]
**Build**
Stage [Train 1.172.0]

**Affected platforms**
Android 9 

**Steps to reproduce**
1. Launch Fenix and login using a Firefox account.
2. Go to https://accounts.stage.mozaws.net/settings/
3. Observe the highlighter of the account picture buttons: “Add”, “Upload”, “Clear”, “Zoom out”, “Zoom in”, “Rotate”.
4. Observe the highlighter of the secondary email button: “Make primary”
5. Observe the highlighter of the account recovery button: “Generate” 

**Expected results**
There is no extra highlighter displayed.

**Actual Results**
White, black or blue unnecessary highlighter is displayed for Account Settings page buttons.

![Screenshot_21](https://user-images.githubusercontent.com/18114210/82805884-6cbb1a00-9e8d-11ea-88e0-3386df71c7f8.png)
![Screenshot_25](https://user-images.githubusercontent.com/18114210/82805888-6d53b080-9e8d-11ea-8944-1960bc0c5d13.png)
![Screenshot_22](https://user-images.githubusercontent.com/18114210/82805890-6d53b080-9e8d-11ea-9cda-6dcfcb078166.png)
![Screenshot_23](https://user-images.githubusercontent.com/18114210/82805891-6dec4700-9e8d-11ea-9978-61f288c674ba.png)
![Screenshot_24](https://user-images.githubusercontent.com/18114210/82805892-6dec4700-9e8d-11ea-8a02-d2495f855735.png)
![Screenshot_26](https://user-images.githubusercontent.com/18114210/82805895-704ea100-9e8d-11ea-8030-ba026e68e36c.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1970)
┆Issue Number: FXA-1970

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer applicable considering the New Settings page replacement. Closing
