### ISSUE TITLE
Replace Survey imported content-server variables values with literal values

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#5439]
Maybe with the new style guidelines fxa-react will naturally lose this reference to content-server?
https://github.com/mozilla/fxa/blob/master/packages/fxa-react/components/Survey/index.scss#L1

If anything we should invert the fxa-react/fxa-content-server dependency.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1973)
┆Issue Number: FXA-1973

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~lzugai@mozilla.com] [~jheavener@mozilla.com]  do the new style guidelines affect this?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Eventually the content server should also start using Tailwind, and that would result in this reference going away. However I don't think that's in the immediate future, and would likely happen as a followup to the Settings project (or even as we get closer to the end).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Add grey-10, grey-50 and any other variables to the file
