### ISSUE TITLE
Installation issues on windows

### ISSUE THREAD

**Issue by abhinavsagar** [mozilla/fxa#544]
## Description
`After` doing `npm install` , I am getting 

`npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Win 10\Desktop\github\fxa-content-server\node_modules\fsevents\node_modules'

> fxa-content-server@1.132.1 postinstall C:\Users\Win 10\Desktop\github\fxa-content-server
> scripts/download_l10n.sh`

`'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa-content-server@1.132.1 postinstall: `scripts/download_l10n.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fxa-content-server@1.132.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

### Steps to reproduce

`npm install`

### Environment

What browser and operating system are you using?

Browser-Google Chrome
OS-Windows 10 64

**Comment by clouserw** [comment]
A couple people are now developing successfully on windows using WSL.  Closing this.
