### ISSUE TITLE
“Use SMS instead” button from Connect your mobile device page doesn’t work

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5463]
**Build**
Prod [Train 1.172.0]

**Affected platforms**
Windows 10 x64 

**Steps to reproduce**
1. Launch Firefox and log in using a Firefox account.
2. Click on Firefox account icon from toolbar.
3. Select “Connect another device” option. 
4. Click on “Get started”.
5. Click on “Ready to scan”.
6. Click on “Use SMS instead” button from the bottom of the page

**Expected results**
The user is redirected to “Would you like to sync your phone?” page.

**Actual Results**
Nothing happens when clicking on “Use SMS instead” button.

![issue2](https://user-images.githubusercontent.com/18114210/82993429-34d8e180-a009-11ea-8d1d-70382a08245f.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1988)
┆Issue Number: FXA-1988

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

x
