### ISSUE TITLE
“I'll do this later, send me a reminder” button from “Sync Firefox between devices” opens a wrong page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5466]
**Build**
Prod [Train 1.172.1]

**Affected platforms**
Windows 10 

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Click on FxA icon from toolbar.
3. Select “Connect another device” option. 
4. Click on “I’ll do this later, send me a reminder” button.

**Expected results**
The user is redirected to https://www.mozilla.org/en-US/firefox/accounts/?utm_campaign=fx-signup&utm_content=fx-sync-get-started&utm_medium=fx-accounts&utm_source=fx-website

**Actual Results**
The user is redirected to “Would you like to sync your phone?” page.

**Additional notes**
This issue is not reproducible when clicking on “I’ll do this later, send me a reminder” button from “Download Firefox with your camera”.

![issue3](https://user-images.githubusercontent.com/18114210/83021546-d88ab780-a032-11ea-8bcd-48d4db1e34a6.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1991)
┆Issue Number: FXA-1991

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

We closed FxA-2032 as a dupe.

Here were the details about that one:

In the designs, we have a link that says "I'll do this later, send me a reminder". For the first release of the experiment, we agreed that this link would do nothing (to save time).

As a fast follow, we would like to send a reminder 8h and 36h later when the link is clicked AND if they haven't already setup a second device.

You can see when this occurs in the flow outlined in the Miro board (listed as phase 2):
https://miro.com/app/board/o9J_krmXBhw=/

The template for the first email can be found here:
https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#bookmark=id.svmpy2gtxsjy

The template for the second email can be found here:
https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#bookmark=id.fib0mhsh4vrt

This does not need to be performed as an experiment.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Moving this out of sprint since working on password change epic.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Assigned this to an epic so it gets better tracked. It is related to both the QR code epic and the send mobile download link by email epic.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Closed in https://github.com/mozilla/fxa/pull/5729

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This was fixed in https://github.com/mozilla/fxa/pull/5729.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.177.0] under Windows 10 64-bit. The user is successfully redirected to https://www.mozilla.org/en-US/firefox/accounts/?utm_campaign=fx-signup&utm_content=fx-sync-get-started&utm_medium=fx-accounts&utm_source=fx-website after clicking on “I’ll do this later, send me a reminder” button.

![fix1](https://user-images.githubusercontent.com/18114210/85846776-050b2e00-b7af-11ea-8165-46cdfb62cbf5.gif)
