### ISSUE TITLE
SecureProxy issues with token TTL in production

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#5469]
## First issue:

The SecureProxy asks for a TTL of 24 hours, but production has changed its value to be less 24 hours. 

We could possibly update the TTL validation, so it doesn't totally refuse requests with higher TTL but does a `min()` on the TTL value.

## Second issue 

Related to the TTL, it's been reported that when the TTL is SET and is a smaller value than MAX_TTL, FxA profile server responds with `Unauthorized` ( 401: {"code":401,"errno":100,"error":"Bad Request","message":"Unauthorized"} )

When SecureProxy removed the TTL param everything worked okay.
The "Unauthorized" behaviour could be some side effect

Related https://github.com/mozilla/fxa/issues/5465

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1993)
┆Issue Number: FXA-1993

**Comment by vladikoff** [comment]
I think the validation here needs to be adjusted https://github.com/mozilla/fxa/blob/b3b3d2c0ef4185562691b82ef84603b5d0dd9e6b/packages/fxa-auth-server/lib/oauth/routes/token.js#L100

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

marking as duplicate

**Comment by vladikoff** [comment]
> marking as duplicate

What is the duplicate? I think we should still fix the way we do `max(MAX_TTL_S)` logic if we want to minimize the TTL in the future.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Duplicate was https://jira.mozilla.com/browse/FXA-1990 but was just for the symptom.  I'll reopen for your suggestion

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I filed https://jira.mozilla.com/browse/FXA-2110 and will close this to avoid confusion.
