### ISSUE TITLE
[Train 132] [Desktop] Android device displayed as not connected on "Manage Account" page

### ISSUE THREAD

**Issue by miralobontiu** [mozilla/fxa#548]
STR:
1. Log in with the same Firefox account on multiple devices (Android, iOS and Windows 10).
2. Go to Manage Account page on all devices, and desktop.
3. Go to "Devices & apps" and observe the displayed devices.

Expected results:
All devices should be displayed.

Actual results:
On desktop, the Android device is not connected.

Notes: 
On iOS and Android, all three devices are displayed, as expected.
Please see attached screenshot:

![untitled](https://user-images.githubusercontent.com/45595767/53960023-cd75ff80-40ed-11e9-907d-8dcd1b22e96c.png)

**Comment by juliemccracken** [comment]
We think these are two totally separate accounts
