### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#5502]
- Currently, there is only a bug report template.
- Add a PR template.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2008)
┆Issue Number: FXA-2008

**Comment by jodyheavener** [comment]
I think that could be useful. Oftentimes a PR consists of only one commit, and as a result GitHub auto-populates the PR body with the commit message, which we do have a [template](https://github.com/mozilla/fxa/blob/master/CONTRIBUTING.md#body) for, so you might base the template off of that.

**Comment by clouserw** [comment]
This sounds like a good idea.  @imskr do you want to add this?

**Comment by imskr** [comment]
Yes. @clouserw
