### ISSUE TITLE
auth-server does not start correctly

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#5503]
My auth-server does not start properly anymore and I do not know why. Something with mysql is going wrong. Somebody give me a hint what's wrong with mysql. Before that, everything worked fine. A 'docker restart auth' and the auth-server works without the error.

https://pastebin.com/zHV0fxyY

Thanks...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2009)
┆Issue Number: FXA-2009

**Comment by clouserw** [comment]
Try this command:  `yarn workspace fxa-shared run build `


Also cc @jrgm in case you are running into problems too

**Comment by misterhsp** [comment]
Does not help, same error :(

...

**Comment by misterhsp** [comment]
Something is not right, the auth-server always starts properly after a docker restart. The error also appeared suddenly, when exactly it was not so exact anymore. Anyway, everything was fine before that.

...

**Comment by misterhsp** [comment]
I think it's because the computer running the docker images is too slow and the auth-server is not yet compiled internally. On a much faster computer with the same docker images, auth-server will not do this and start normally. I think it has to do with the switch to yarn or ts-node. Everything worked before.

...

**Comment by misterhsp** [comment]
I simply cannot solve the problem on the slower computer. Even if I run this in a VM (Virtualbox) this error occurs. If only I knew what is stuck.

...

**Comment by misterhsp** [comment]
> Try this command: `yarn workspace fxa-shared run build `
> 
You meant that when you built the docker image, or did you mean it differently?

**Comment by misterhsp** [comment]
I think I have found the presumed solution I hope.

https://www.sebastianomontino.com/blog/2016/02/etimedout-nodejs-mysql/

thanks...

**Comment by misterhsp** [comment]
Is there anything that can be done to avoid this problem?

...

**Comment by misterhsp** [comment]
Is there a solution in sight. On slower computers this still occurs.

...

**Comment by clouserw** [comment]
Sorry @misterhsp .  Focusing on this is not on our roadmap

**Comment by misterhsp** [comment]
What did you change, now after a rebuild it suddenly works again on the slower computer?

...

**Comment by clouserw** [comment]
Testing on slow servers is not a part of our testing suite.  It might break or work, but it's not something we monitor.

I'm glad it started working for you again though.

**Comment by misterhsp** [comment]
Can anyone tell me where this timeout is set?

Thank you...
