### ISSUE TITLE
Pairing: Signal that it's a pairing flow to Firefox Desktop in fxa_status

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#552]
> * Provide a signal for Firefox Desktop that fxa_status should be allowed for the pairing context (currently it is only for `service === sync`)

Follow up to https://github.com/mozilla/fxa-content-server/pull/6876

**Comment by clouserw** [comment]
@vladikoff we're kicking this out of the current milestone.  Is this being actively worked on?

**Comment by vladikoff** [comment]
I shall put it on my TODO and triage
