### ISSUE TITLE
Subscription downgrade plan looks like a subscription upgrade plan

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5521]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.173.0;

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with subscription upgraded;

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page again (as you did when you made the upgrade flow)
2. Click the “Subscribe for Pro” option.
7. Observe downgrade flow window.

 #### Expected result:
A subscription downgrade plan is explained. (downgrade suggestive title, button label and related details).

#### Actual result:
Subscription downgrade plan looks like a subscription upgrade plan.

#### Notes:
- If it wouldn’t be for the values that suggest a downgrade, we could not distinguish downgrade from upgrade.

![image](https://user-images.githubusercontent.com/15685960/83497005-87f7dc00-a4c2-11ea-825b-a03a8bd5a59e.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2015)
┆Issue Number: FXA-2015

**Comment by lmorchard** [comment]
Probably need a product decision on this one since I don't recall seeing mocks for a downgrade. (Or I might have missed them?)

FWIW, we do have [a downgrade email template](https://docs.google.com/document/d/1zQevMPvapl8QOKkaMwBKBh_mG1pmqnLjBkszlWkDYwI/edit#heading=h.wfr0e8kxtg28), which has phrasing that calls this a "switch" rather than a downgrade. So I assume there's some thought behind not making it sound negative.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jgruen@mozilla.com] what should this look like?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

We should consider simplifying this to avoid differentiating upgrade versus downgrade.

Ben: Going from VPN to Prospector is not an upgrade; it’s a change in your plan. One’s a bundle and one isn’t. I’d prefer if we didn’t try to differentiate “upgrade” versus “downgrade” -- let’s just say they are making a change. Saying “change” is also good to future-proof ourselves: Right now we have multiple subscriptions on two separate billing cycles; but what people would like is one billing cycle (two prices to same subscription with aligned billing cycles). You would get one invoice for the total amount due. This would be changing your “plan” for the “subscription” (now for multiple products).

[~jecook@mozilla.com], what do you think about this idea? It would simplify logic for us also between the website and our emails.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm a fan.  It will also be simpler for localizers

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

[~bdanforth@mozilla.com] This is the same logic that I was planning to execute on from the UX side so yes this makes sense to me.
