### ISSUE TITLE
Incorrect one-time fee value listed in subscription upgrade mail if a normal subscription is made before

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5536]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.173.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active normal and upgraded subscription;

#### Steps to reproduce
1. Go to subscription upgrade email.
2. Observe the one-time fee value.

#### Expected result:
- One-time fee value is correct.

#### Actual result:
- One-time fee value is replaced with the value of the normal subscription.

![image](https://user-images.githubusercontent.com/15685960/83611558-cf956b00-a589-11ea-86a9-56ac9a082a2b.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2027)
┆Issue Number: FXA-2027

**Comment by lmorchard** [comment]
Digging into this and I think I can see the details in [this customer](https://dashboard.stripe.com/test/customers/cus_HOddhvZxx87YC1) and [this subscription](https://dashboard.stripe.com/test/subscriptions/sub_HOdoC8gMW2Ph9w) on SUB_PLAT_STAGE.

The one-time charge value in the email should be $495 - i.e. 500 + (-5) per the proration adjustments listed in the subscription events.

It looks like the $9.95 price came from the invoice for [a different subscription](https://dashboard.stripe.com/test/subscriptions/sub_HOddZDQCjMZbtD).

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Took a couple of points from this because the fix ended up being easy after some thought

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx77 and Windows 10 (64-bit).
The one time fee value is correctly displayed even if a "normal" subscription is also made before
Postfix screenshot below.
![onetimefee](https://user-images.githubusercontent.com/15685960/84477003-9ea6eb80-ac97-11ea-9101-0b6d1f11b3a1.png)
