### ISSUE TITLE
Follow up changes for post verify emali

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5553]
This missed train 174, but we should update the email template

* Use cdn images
* Fix broken tests
* Add mobile specific language to templates

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2037)
┆Issue Number: FXA-2037

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~lzugai@mozilla.com] [~vbudhram@mozilla.com]  Hey folks, I'm trying to hand this off to QA but I'm severely lacking in detail here. What is there to test? What was done to the templates?

cc: [~adavis@mozilla.com] [~wclouser@mozilla.com]

**Comment by vbudhram** [comment]
@chelsea-lewis 

#### To test Desktop use case:

1. Create and verify a sync account using Firefox Desktop browser
2. Observe the account verified account email

Should look similar (spacing and padding will be different)
![Screen Shot 2020-07-08 at 3 06 01 PM](https://user-images.githubusercontent.com/1295288/86960035-ed2b9680-c12c-11ea-9baa-3f61d529eb4c.png)

The `another desktop device` opens site to download Firefox browser.

#### To test Mobile use case:

1. Create and verify a sync account using Firefox Mobile browser
2. Observe the account verified account email

Should look similar (spacing and padding will be different)
![Screen Shot 2020-07-08 at 3 06 12 PM](https://user-images.githubusercontent.com/1295288/86960272-44ca0200-c12d-11ea-9ffa-56576fa430ec.png)

The `another mobile device` opens site to App/Play App stores.

**Comment by LZoog** [comment]
Lol oops @vbudhram , I knew I should have pinged you, I just posted a similar comment in JIRA with a screenshot that's slow to transfer over here. ;)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

[~clewis@mozilla.com] if a user signs up on a non-mobile device, the bottom part of the post verify email should read "Or, install on another desktop device" and should link-out to: https://firefox.com/?utm_content=registration-confirmation&utm_medium=email&utm_source=fxa

Here's a screenshot:
 !screenshot-1.png|thumbnail! 

Otherwise, if they sign up on a mobile device, it should read "Or, install on another device" and link out to connect another device (unchanged).

They could also verify that the app store/google play store images are coming from a `image.e.mozilla.org` URL and not `accounts.firefox.com` as they were previously.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Thanks you two! [~rbillings@mozilla.com] Do we think this gives us what we need to get a quick test done?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Tagging [~vtamas@mozilla.com] as well. This isn't a large scope of testing but we wanted to flag for QA review. Is this something you'd need a PI request for? This is already in production, so we hope to be able to accomplish some testing soon to be sure we're getting the expected experience. My apologies for the miss.

**Comment by vasilicatamas** [comment]
Hi @chelsea-lewis ! Thanks for notifying me! There is no need for a Pi request as I have already started verifying this ticket.

I can confirm that the post verify email is successfully received on desktop, displaying the "Or, install on another desktop device" link which redirects to https://firefox.com/?utm_content=registration-confirmation&utm_medium=email&utm_source=fxa page. 

But I’m having trouble receiving this email on the mobile side (Fenix and iOS) for which I filed the following issue #5920.
 
“Account verified. Next, sync another device to finish setup” is successfully received while using Fennec but I am a bit confused about which version is the correct one "Or, install on another device" or "Or, install on another *mobile* device"?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~vbudhram@mozilla.com] or [~lzugai@mozilla.com] please advise when you have a moment. 

>“Account verified. Next, sync another device to finish setup” is successfully received while using Fennec but I am a bit confused about which version is the correct one "Or, install on another device" or "Or, install on another mobile device"?
