### ISSUE TITLE
Pass account delete notifications to AMO

### ISSUE THREAD

**Issue by eviljeff** [mozilla/fxa#5557]
We'd like the aws sqs added a few years back (mozilla/addons-server#6451) to feed notifications of email changes to addons.mozilla.org be expanded to include delete notifications too for mozilla/addons-server#13896.

@bbangert mentions webhooks is the new thing in mozilla/addons-server#13896 but for the first step (and to get this actually done this quarter) we want to keep the existing integration method.  Switching both email&delete notifications to webhooks will be the follow-up.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2045)
┆Issue Number: FXA-2045

**Comment by muffinresearch** [comment]
Note: this blocks mozilla/addons-server#13896 which in turn blocks https://github.com/mozilla/fxa/issues/4467

**Comment by clouserw** [comment]
Is the ask for this to be done before June 30th?  If this is an emergency please ping us on Slack so we can figure out if we can kick something out of our schedule to get this in. /cc @chelsea-lewis on potential schedule impact

If it's not an emergency, I'd suggest using the webhooks in the event-broker that Ben mentioned.  There is documentation to connect to it at https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events 

As for the SQS queue: I'm not even sure which that is.  Is it still active?  Does anyone else use it?  @jbuck

**Comment by eviljeff** [comment]
> Is the ask for this to be done before June 30th? If this is an emergency please ping us on Slack so we can figure out if we can kick something out of our schedule to get this in. /cc @chelsea-lewis on potential schedule impact

The original request for us to handle deletions was from your team (#4467) and legal.  Back in March it sounded like it was [good to go](https://github.com/mozilla/fxa/issues/4467#issuecomment-601343690).  We'll defer to whatever priority you place on it.

> If it's not an emergency, I'd suggest using the webhooks in the event-broker that Ben mentioned. 

We already have the existing integration so migrating to a new one would be the follow-up. 

> There is documentation to connect to it at https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events

I replied to Ben's comment in the issue at the time - the documentation is just about verifying JWT keys rather than the actual integration - it's difficult to tell if it fits our use-case.  If it's in use somewhere else I'm happy to look into sample code instead.

> As for the SQS queue: I'm not even sure which that is. Is it still active? Does anyone else use it?

As far as I'm aware no-one let us know it was deprecated, or we'd have put it on our roadmap already to move away from it.  If there's an issue we missed can you link to it?

**Comment by clouserw** [comment]
>     * Are the webhooks already being used in production by other services?
Yes, they are our standard way of communicating events to RPs.

>     * Will supporting AMO migrating to web-hooks actually take less time than getting the deletion messages into SQS, since we're already listening to it for email changes?
I don't know.  Once we have improved documentation let's talk about how much work it would be.  I'd rather migrate everyone to a standard system if we can.

>     * What's the time-frame for deprecating the SQS queue?
No timeline at this point.

**Comment by jbuck** [comment]
I can change the SNS queue to allow delete notifications very quickly - I'd recommend doing that until the web hook support is ready.

@muffinresearch would you like me to enable this for AMO stage before enabling it for AMO prod?

**Comment by muffinresearch** [comment]
> I can change the SNS queue to allow delete notifications very quickly - I'd recommend doing that until the web hook support is ready.
> 
> @muffinresearch would you like me to enable this for AMO stage before enabling it for AMO prod?

Yes, I think that sounds good - thanks, @eviljeff does that work for you?

**Comment by eviljeff** [comment]
> > @muffinresearch would you like me to enable this for AMO stage before enabling it for AMO prod?
> 
> @jbuck Yes, I think that sounds good - thanks, @eviljeff does that work for you?

works for me.  Can we have it enabled for AMO dev too?

**Comment by jbuck** [comment]
> works for me. Can we have it enabled for AMO dev too?

Maybe! What Firefox Accounts environment is AMO dev connected to? If it's connected to stage or prod then I can do it, if it's not, then I'm not sure

**Comment by diox** [comment]
- AMO dev is currently using stable.dev.lcip.org, but looking to move to stage, as per https://bugzilla.mozilla.org/show_bug.cgi?id=1639985
- AMO stage is using FxA prod.
- AMO prod is using FxA prod (obviously).

**Comment by jbuck** [comment]
I've enabled deletion notifications for AMO stage

**Comment by eviljeff** [comment]
> 
> 
> I've enabled deletion notifications for AMO stage

great.  I can see them in our logs (currently just ignoring them because we've left the processing task switched off)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is this ready to be turned on in production?

**Comment by eviljeff** [comment]
@clouserw we'll be ready after the next push to prod (Thursday 25th afternoon PST or after).

**Comment by eviljeff** [comment]
Is there work to do on the FxA side for #4467 though?  We'll want to coordinate that with the `'fxa-account-delete'` waffle flag on addons-server being enabled.

**Comment by clouserw** [comment]
Yeah, we'll have to reopen and land that patch.

**Comment by eviljeff** [comment]
We've found a few blockers so at the earliest it'll be the following week (July 2nd) when we're ready to enable the processing (waffle switch).  We're okay to start receiving the SQS notifications anytime from Thursday this week though (they'll just be ignored and cleared)

**Comment by clouserw** [comment]
It'll have to get back on our roadmap too, so, no hurry.  It'll definitely be after Jul 2

**Comment by jbuck** [comment]
> @clouserw we'll be ready after the next push to prod (Thursday 25th afternoon PST or after).

I've enabled deletion notifications for AMO prod

**Comment by eviljeff** [comment]
> I've enabled deletion notifications for AMO prod

we're getting them, thanks!

From our side we're good to go (after July 2nd) - just let us know and we'll have ops enable the waffle switch on AMO prod.

I see that @jodyheavener created #4532 in March to close #4467 and it was approved. Not sure if there other blockers not specified in the issue/pr though.  Please close the issue if there's nothing else to do here.

I've logged mozilla/addons#14730 for us to look into migrating to webhooks.

**Comment by jodyheavener** [comment]
Just a heads up that new checkbox will be available when Train 178 hits prod.

**Comment by clouserw** [comment]
That's July 6th :)
