### ISSUE TITLE
The survey is not prompted for a different user logged in on the same profile

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5561]
**Build**
Stage [Train 1.174.0]

**Affected platforms**
Windows 10
Android 9
iOS 13.4.1

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to https://accounts.stage.mozaws.net/reset_password
3. Submit the survey.
4. Log out.
5. Log in using a different Firefox account.
6. Go to https://accounts.stage.mozaws.net/reset_password

**Expected results**
The survey is successfully prompted for each different user that changes the password on the same profile.

**Actual Results**
The survey is displayed a single time on a profile, only for the first user that changes the password.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2052)
┆Issue Number: FXA-2052

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

We should probably create a new story about rate limiting.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Canceled and filed related Rate Limiting improvement task with fxa-2116.
