### ISSUE TITLE
The survey is displayed on each profile/device a user resets the password

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5562]
**Build**
Stage [Train 1.174.0]

**Affected platforms**
Windows 10
Android 9
iOS 13.4.1

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to https://accounts.stage.mozaws.net/reset_password
3. Submit the survey.
4. Launch Firefox on a second device and login using the same account used at step 1.
5. Go to https://accounts.stage.mozaws.net/reset_password

**Expected results**
The survey is displayed a single time per user.

**Actual Results**
The survey is displayed each time a user resets the password from a different device.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2053)
┆Issue Number: FXA-2053

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

At this point, surveys are not associated with users.  It's just a flag in local storage.  So, this is expected, but might still not be how [~adavis@mozilla.com]  and [~jgruen@mozilla.com]  want it to work.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Given we plan to do small samples for surveys during login and registration, I don't expect most users to get surveyed twice. However, I could see this being annoying if we run a survey in our new Settings when it goes into beta. It could also skew the opt-in measurement of our survey.

I'd also specify that given some users won't be signed in or registered yet (e.g. password reset step, registration form, etc.), we wouldn't throttle the survey based on the account specifically.

I'm not sure this is a bug at this stage but rather, it should be a planned enhancement and remain a known limitation of our survey tool at this time.

Let's see if John has other thoughts or use cases that would expedite this.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Sure. Works for me.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Canceled as this is a known limitation to the current implementation. Filed FXA-2117 as an enhancement for this in future versions of the survey product.
