### ISSUE TITLE
Running `yarn test` in `fxa-react` makes `fxa-settings` error out

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#5577]
`yarn test` runs `yarn clean && jest`.

`yarn clean` seems to cause some TS compiling issues if `fxa-settings` is running. I have to restart `fxa-settings`, `fxa-react` and also the content server to fix the issue.
<img width="761" alt="image" src="https://user-images.githubusercontent.com/13018240/84047199-a18c9e00-a970-11ea-8b42-a758809b8c75.png">

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2054)
┆Issue Number: FXA-2054

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

How can I repro this? In fxa-settings I ran `yarn test` and then made a change to a tsx file that imports from fxa-react, and things were fine. I assume it's more specific than this?

**Comment by LZoog** [comment]
> How can I repro this?

You shouldn't need to change a tsx file. I had `/beta/settings` pulled up and ran `yarn test` in `fxa-react` and this happens on HMR.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~dcoates@mozilla.com] - do you have an idea for this?
