### ISSUE TITLE
Failing test `force_auth` on latest and stage

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#558]
https://tc-test.dev.lcip.org/viewLog.html?buildId=47956&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_state=326&focus=338

## Description

Failing test `force_auth` on latest and stage

### Steps to reproduce

Run tests on teamcity

### Expected result

Pass

### Actual result

Fail

### Environment

teamcity docker images

### Additional Info

Test log:

https://tc-test.dev.lcip.org/viewLog.html?buildId=47956&buildTypeId=FxaLatest_FunctionalTests&tab=buildLog#_state=326&focus=338

Screencap:

https://screencap.co.uk/images/5a72662ea9610354be3010e041ab1fe7c4122663.png

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-708)
┆Issue Number: FXA-708

**Comment by vladikoff** [comment]
@jrgm is this still happening?
