### ISSUE TITLE
Create util.js for client side lib (client side)

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#5585]
**(Phase-2 - Client): Create util.js**

- To take public key cred and convert it to JSON and export it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2063)
┆Issue Number: FXA-2063

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
