### ISSUE TITLE
Create loginChallenge.js (client side)

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#5587]
**(Phase-2 - Client): Create loginChallenge.js**

- For solving the login challenge

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2061)
┆Issue Number: FXA-2061

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
