### ISSUE TITLE
Create user.js and store pem file for tls (client side)

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#5588]
**(Phase-2 - Client):**

- create user.js for storing user credentials.
- store `.pem` file (Required).
- create index.js for implementing endpoints (using express).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2065)
┆Issue Number: FXA-2065

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

This issue is not applicable anymore
