### ISSUE TITLE
Implement register page for webauthn

### ISSUE THREAD

**Issue by imskr** [mozilla/fxa#5589]
We should create dedicated registration pages for webauthn using the new settings page as a template. We should also be able to follow the existing design patterns to create the pages.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2064)
┆Issue Number: FXA-2064

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
