### ISSUE TITLE
Use Webpack for HTML/CSS minimization, ditch grunt-usemin, grunt-cssmin

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#559]
We use grunt-usemin to minimize our CSS resources, however it's no longer maintained. We are already using Webpack to generate CSS, let's use it to rev dependencies and minimize the output too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-709)
┆Issue Number: FXA-709

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Note: Since we'll use PostCSS with Tailwind styles, we probably just need to update the HTML minifier.
