### ISSUE TITLE
“Connect another device” pictogram is not centered on post verify email

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5613]
**Note**
This is a follow-up bug for #5400

**Build**
Stage [Train 1.174.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Launch Firefox.
2. Create a Firefox account.
3. Confirm it.
4. Check the “Account verified. Next, sync another device to finish setup” email.

**Expected results**
The Email content is correctly displayed.

**Actual Results**
“Connect another device” pictogram is not centered.
![Screenshot_13](https://user-images.githubusercontent.com/18114210/84166024-09300f80-aa7d-11ea-9d94-2d531d9c2f6c.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2079)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15938/Screenshot_44.png">Screenshot_44.png</a>
┆Issue Number: FXA-2079

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

What email client is this?

**Comment by vasilicatamas** [comment]
> What email client is this?

Thunderbird and Yahoo. But I don't think this is a client email specific issue because the template from [#5547](https://github.com/mozilla/fxa/pull/5547) displays the same format.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer applicable because the "Account verified. Next, sync another device to finish setup "email pictogram has changed and the new one is correctly displayed.
