### ISSUE TITLE
Long display name causes confusions in subscription confirmation page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5627]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.174.0;

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with a long display name set;

#### Steps to reproduce
1. Go to https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn  page.
2. Click the “Subscribe Now” button.
3. Fill all mandatory fields and finalize subscription.
4. Observe the “Billed to” section.

 #### Expected result:
- The strings are clear and intuitive. Maybe with a separator between display name and email address.

#### Actual result:
- Account display name and email address are not separated.

![long display name](https://user-images.githubusercontent.com/15685960/84263671-92e8e700-ab28-11ea-8e3b-389e8595607c.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2086)
┆Issue Number: FXA-2086

**Comment by ValentinaPC** [comment]
For display name without spaces, things look very bad, even if, and edge case.
![image](https://user-images.githubusercontent.com/15685960/84360739-40183980-abd3-11ea-99bf-af6725b29050.png)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] - is there anything you want to change here?
