### ISSUE TITLE
Unclear strings for l10n (imperative or not)

### ISSUE THREAD

**Issue by TonnesM** [mozilla/fxa#563]
Recently some new strings were exposed for l10n. Two of them, or at least one, cause(s) confusion as to whether or not the string is imperative (i.e. an instruction to the user), or a user choice. As a rule of thumb says, that confusion could have been eliminated by using a trailing period in case of imperative usage. Seeing different variations of localizations for locales enforces that thought.

- Approve connections <small>to begin syncing</small>     // Probably (?) imperative, could use period if so
- Approve this connection <small>from this device</small>  // Very unclear, and when imperative, also unclear what "from this device" refers to.

Can any clarity be provided, and perhaps change what is, or add periods where needed?

**Comment by clouserw** [comment]
I think the questions are answered here (punctuation was omitted on purpose).  -> closing
