### ISSUE TITLE
"Use SMS instead" is missing a "href"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#5636]
See devtools screenshot below. 

@vbudhram any ideas?

![image](https://user-images.githubusercontent.com/128755/84316727-9fc20680-ab39-11ea-8c3c-58fa47dc4f79.png)

![image](https://user-images.githubusercontent.com/128755/84316761-acdef580-ab39-11ea-82bc-a777818133de.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2091)
┆Issue Number: FXA-2091

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

duplicate
