### ISSUE TITLE
Invalid token message on check your email page

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#564]
I see this error often when creating accounts, and returning later in the day. I can't imagine a scenario where this is a useful message. Is there a way to hide all errors on this page?
<img width="477" alt="image" src="https://user-images.githubusercontent.com/68213/52503464-9f1b0800-2bb3-11e9-8f9e-17e4b7bb18a1.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-713)
┆Issue Number: FXA-713

**Comment by softvision-miralobontiu** [comment]
Hi all!
I encountered this issue on the latest Fenix Beta 79.0.0-beta.6 using Samsung Galaxy Tab S6 (Android 9), with these steps:
1. Go to Settings - Turn on Sync and create a new account.
2. Copy the requested verification code from the email, and paste it.
3. Tap on Verify.

The user gets the "Invalid token" message. 
Tapping on the "Resend code", and using the new code results in the same errors.
Going back to Setting I've noticed that the account was created successfully.
