### ISSUE TITLE
'verifyShortCode' template doesn't send a code inside of a header

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#5649]
I signed up for a new account and the code is only in the subject and contents of the email

![image](https://user-images.githubusercontent.com/128755/84408228-e23b2000-abd9-11ea-8c5a-52a96f2ffb60.png)

Should we include the code inside a header like we do for other emails?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2102)
┆Issue Number: FXA-2102

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Yes, we should.  Marking duplicate of existing bug
