### ISSUE TITLE
“Learn more” link from “Cannot create account” page returns “Page not found” on Fenix and iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5657]
**Build**
Stage [Train 1.175.0]
Prod [Train 1.174.1]

**Affected platforms**
Android 9
iOS 13.4.1 

**Steps to reproduce**
1. Launch Firefox app 
2. Try to create a Firefox account, inserting for age field a number <13.
3. Tap on “Learn more” link from “Cannot create account” page.

**Expected results**
[Federal Trade Commission - Children's Privacy](https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy?action=email&response_type=code&client_id=a2270f727f45f648&scope=profile%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&state=N242JuQLK9ah4be9eoKTTA&code_challenge_method=S256&code_challenge=-RDVh1l1_AcGe3hpiUgUCB8x7V1MQH91bjfJU7TWKhI&access_type=offline&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6Im9NZUV3MjFCZXFTbXhwQ25ZQ0dCVjhyX2l6M0phU3VqRmRqdU02R0VZMEkiLCJ5IjoiNHlkaHd4cl8wbngzTXFYN2Joa01Td2QwakVmZUpsT29qRWFvZTFUc0R4TSJ9&context=oauth_webchannel_v1) page is successfully displayed.

** Actual Results**
- “Page not found” error is displayed. The user is redirected to https://accounts.stage.mozaws.net/https://www.ftc.gov/tips-advice/business-center/privacy-and-security/children%27s-privacy?action=email&response_type=code&client_id=a2270f727f45f648&scope=profile%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&state=N242JuQLK9ah4be9eoKTTA&code_challenge_method=S256&code_challenge=-RDVh1l1_AcGe3hpiUgUCB8x7V1MQH91bjfJU7TWKhI&access_type=offline&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6Im9NZUV3MjFCZXFTbXhwQ25ZQ0dCVjhyX2l6M0phU3VqRmRqdU02R0VZMEkiLCJ5IjoiNHlkaHd4cl8wbngzTXFYN2Joa01Td2QwakVmZUpsT29qRWFvZTFUc0R4TSJ9&context=oauth_webchannel_v1 

- https://accounts.stage.mozaws.net/ should be removed from the above link in order to display the correct page

![issue9](https://user-images.githubusercontent.com/18114210/84480315-09a6f100-ac9d-11ea-97a3-079d9aa67936.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2108)
┆Issue Number: FXA-2108

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because the link didn’t work
**Frequency**: low
**How was this found?**
Test filed in Prod
**What caused it?
Where was the gap which caused this issue**
The link was changed at some point
**Why didn’t we catch it sooner?**
This manual test was removed as it has automation coverage- but that didn't cover page links
**How do we ensure it doesn’t repeat?**
The manual test was added back in
**Is this a symptom of a broader issue**
No

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

duplicate
