### ISSUE TITLE
The red buttons from Manage Account page do not have hover effect

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5658]
**Build**
Stage [Train 1.175.0]

**Affected platforms**
Windows 10

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Navigate to https://accounts.stage.mozaws.net/settings.
3. Add a secondary email and check the “Remove” button.
4. Generate a recovery key and check the “Revoke” button.
5. Enable 2FA and check the “Disable” button.
6. Connect to some devices/services and check the “Disconnect...” button.

**Expected results**
All the red buttons from the Manage account page display a hover feedback effect.

** Actual Results**
Manage account red buttons do not have a hover effect.

![issue9](https://user-images.githubusercontent.com/18114210/84514283-6de4a780-acd3-11ea-9c24-a358c8a94977.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2109)
┆Issue Number: FXA-2109

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] - should these have a hover state?  If so, what?

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

They should, and it should be: # a4000f

And the pressed/clicked stated should be: # 5a0002

**Comment by byrw** [comment]
can I work on it?

**Comment by clouserw** [comment]
@byrw sure, thank you

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [1.182.1] under Windows 10 64-bit, Android 9 and iOS 13.6. All the red buttons from the Manage account page have hover effect.
![issue9](https://user-images.githubusercontent.com/18114210/89211342-58507780-d5ca-11ea-8d5d-540d3ae63e4a.gif)
