### ISSUE TITLE
“Cancel” button highlighter overlaps the “Continue” button from “Step 1 of 2: Re-enter password” modal

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5659]
**Build**
Stage [Train 1.175.0]

**Affected platforms**
Windows 10

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Navigate to Account Settings page.
3. Click on "Enable" button from the Account recovery section.
4. Click on “Generate” button.
5. Click on “Cancel” button.

**Expected results**
”Cancel” button is correctly displayed.

**Actual Results**
“Cancel” button highlighter is displayed over the “Continue” button.

![Screenshot_17](https://user-images.githubusercontent.com/18114210/84516756-e6993300-acd6-11ea-97b8-80087fc87f0e.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2111)
┆Issue Number: FXA-2111

**Comment by byrw** [comment]
can I work on it?

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.180.0] under Windows 10 64-bit. "Cancel" button is correctly displayed.

![Screenshot_18](https://user-images.githubusercontent.com/18114210/87936964-77b0b600-ca9c-11ea-9f06-2b54ae9fd20e.png)
