### ISSUE TITLE
“Copy” option is not center aligned in “Step 2 of 2: Save Recovery key” modal on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5661]
**Build**
Stage [Train 1.175.0]

**Affected platforms**
iOS 13.4.1

**Steps to reproduce**
1. Launch Firefox app and login using a Firefox account.
2. Navigate to Account Settings page.
3. Click on "Enable" button from the Account recovery section.
4. Click on “Generate” button.
5. Type the account password and click on “Continue” button.
6. Observe the “Copy” option.

**Expected results**
“Copy” option is center aligned.

**Actual Results**
“Copy” option is displayed on the left side of the modal.

![Screenshot_19](https://user-images.githubusercontent.com/18114210/84517749-61168280-acd8-11ea-83a7-ccbc81bd98fd.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2112)
┆Issue Number: FXA-2112

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue can be closed because it is no longer applicable, considering the New Settings page replacement.
