### ISSUE TITLE
Disabled “Done” button from Secondary email is highlighted on click

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5672]
**Build**
Stage [Train 1.175.0]

**Affected platforms**
Windows 10 64-bit
Android 9

**Steps to reproduce**
1. Login using a Firefox account and navigate to Manage account page.
2. Expand the Secondary email section by clicking on "Add..." button.
3. Type a valid email address and click on "Add" button.
4. Click on “Done” button.

**Expected results**
“Done” button does not display any visual effect while in disabled state.

**Actual Results**
The disabled “Done” button is focused when clicking on it.

![issue10](https://user-images.githubusercontent.com/18114210/84667367-edb87f00-af2a-11ea-9074-bc08022b8f44.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2123)
┆Issue Number: FXA-2123

**Comment by byrw** [comment]
Adding `:not(.disabled)` seems enough to fix it.

On main.css:
```
  .button:focus,
  .settings-button:focus:not(.disabled),
  button:focus:not(.disabled) {
    box-shadow: 0 0 0 1px #0a84ff inset, 0 0 0 1px #0a84ff, 0 0 0 4px rgba(10, 132, 255, 0.3); }
```

**Comment by Rudresh22** [comment]
Hello, can I work on this issue?

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue can be closed because it is no longer applicable, considering the New Settings page replacement.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue can be closed because it is no longer applicable, considering the New Settings page replacement.
