### ISSUE TITLE
The same sign-in code is sent even if it has already been used

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5677]
**Build**
Prod [Train 1.175.0]

**Affected platforms**
Windows 10 64-bit
Android 9

**Steps to reproduce**
1. Login using a Firefox account.
2. Use the sign-in code received via email.
3. Log out.
4. Login again using the same account.
5. Check the code received via email.
6. Use the code in order to authorize the sign-in.
 
**Expected results**
New code is received once the previous one has been used.

**Actual Results**
- Same code is received even if it has already been used.
- The code is valid and can be used several times.
- A new code is received only 5 minutes later after receiving the first code.

![issue11](https://user-images.githubusercontent.com/18114210/84769777-1306c500-afdf-11ea-85a5-7961e261eced.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2126)
┆Issue Number: FXA-2126

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage: this is a known behavior.  More discussion at https://bugzilla.mozilla.org/show_bug.cgi?id=1646072
