### ISSUE TITLE
Wrong icon and details in Set up subscription page and payment confirmation page

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5685]
#### Affected versions:
- All Firefox;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account;

#### Steps to reproduce
1. Install Secure Proxy v23 and log it with an account that does not have a secure proxy subscription.
2. Start the subscription flow for secure proxy.
3. Observe the UI in the Set up your subscriptions page.

#### Expected result:
- The new FPN Icon is displayed.
- The subtitle is mentioning that the product is only browser level not device level.
- The Product details are the ones for the browser extensions.

#### Actual result:
- The old icon is displayed.
- The subtitle is mentioning Full-device protection.
- The product details are for the full device vpn.

![image](https://user-images.githubusercontent.com/15685441/84877616-69ccd700-b091-11ea-981c-f3bac62aa946.png)

#### Notes
This is reproducing in FxA stage. 
This is also reproducing in the payment confirmation page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2129)
┆Issue Number: FXA-2129

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78 and Windows 10 (64-bit).
Postfix screenshot below.
