### ISSUE TITLE
The support ticket emails are mentioning Firefox Private Network in the footer and not FPN Browser Extension

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#5697]
#### Affected versions:
- All Firefox;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with Secure Proxy subscription

#### Steps to reproduce
1. Open the contact us page: https://accounts.stage.mozaws.net/support
2. Select Firefox Private Network Browser Extension in the What are you contacting us about section.
3. Fill the rest of the form and click the Send button.
4. Open the received mail and observe the footer.

#### Expected result:
The footer mentions that the user recieved the mail because he is subscribed to **Firefox Private Network Browser Extension**

#### Actual result:
The footer contains the following text: You’re receiving this email because you have a Firefox account and you signed up for **Firefox Private Network**.

![image](https://user-images.githubusercontent.com/15685441/85010525-d1a22100-b168-11ea-9d31-a2e2f7d9bf47.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2134)
┆Issue Number: FXA-2134

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jgruen@mozilla.com] should the email text be changed?

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

AFAIK these come from Stripe, i can go ahead and change the staging stripe product to be the VPN

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Hmm, [~mcotetiu@mozilla.com] could you screenshot the entire email, I want to make sure i understand where this email is coming from

**Comment by madalincm** [comment]
Hello here is a full screenshot:
![image](https://user-images.githubusercontent.com/15685441/85371888-ab4dfe00-b539-11ea-8014-e1929729ef6e.png)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~jgruen@mozilla.com] will bring this to Andrew Morales' attention.

**Comment by ValentinaPC** [comment]
@johngruen Additional to the initial issue, is the fact that the "Firefox Private Network" product name no longer exist, and was replaced with "Mozilla VPN".
