### ISSUE TITLE
Update 'master key' terminology throughout

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#5699]
Followup from #5695. We have some references to "master key material" and the "sync master key" that could be updated to use less racist terminology (sadly, TIL "master key" is indeed intended as a metaphorical counterpoint to a "slave key").

Leaning on the suggestions in the [IETF 'Terminology, Power, and Oppressive Languages' internet-draft](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1.1), I think "primary key" would be a suitable substitute. Opening this issue for discussion, and to capture work to update "master key" refs here, and in the sync repos, and probably in some support.mozilla.org pages as well. Let's do it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2136)
┆Issue Number: FXA-2136

**Comment by 6a68** [comment]
Ah, we'll also want to update the [onepw protocol doc](https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol), and perhaps this is a good excuse to finally import that critically important doc into this repo.

**Comment by rfk** [comment]
(Just want to state right at the outset that I am here for this, and not trying to argue to keep the current terminology)

> I think "primary key" would be a suitable substitute. 

I think "primary key" loses some important part of the mental model of this key material, which to me includes the tree-like structure where you have `kB` at the root, and from it you can derive various sub-keys, and perhaps derive further keys from them in turn. None of the duals of "primary key" seem to capture this notion well ("secondary key"? "replica key"? meh...).

Would something like "root key" and "derived keys" work here?

**Comment by 6a68** [comment]
I think "root key" is a great idea for a substitute!
