### ISSUE TITLE
Setting NODE_ENV is confusing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#57]
I happened to stumble onto this, and now cannot unsee.

[**mozilla/fxa-content-server** /server/lib/configuration.js:47](https://github.com/mozilla/fxa-content-server/blob/5d1f469bfdfec6e999eb38d0da7342287c213b92/server/lib/configuration.js#L47) has:

``` js
  env: {
    doc: 'What environment are we running in?  Note: all hosted environments are \'production\'.',
    format: ['production', 'development'],
    default: 'production',
    env: 'NODE_ENV'
  },
```

[**mozilla/fxa-auth-server** /config/index.js:17](https://github.com/mozilla/fxa-auth-server/blob/b966c2e8d5f7e180b1da7079edbec89fb5aa7bb7/config/index.js#L17) and [**mozilla/fxa-oauth-server** /lib/config.js:67](https://github.com/mozilla/fxa-oauth-server/blob/a456847809a86d214b8f778d413ab47c54b0dcdc/lib/config.js#L67) has:

``` js
  env: {
    doc: 'The current node.js environment',
    default: 'prod',
    format: [ 'dev', 'test', 'stage', 'prod' ],
    env: 'NODE_ENV'
  },
```

[**mozilla/fxa-profile-server** /lib/config.js:28](https://github.com/mozilla/fxa-profile-server/blob/0dedad2e504ab97273e140951f9475b0d4e7896c/lib/config.js#L28) has:

``` js
  env: {
    arg: 'node-env',
    doc: 'The current node.js environment',
    env: 'NODE_ENV',
    format: ['dev', 'test', 'stage', 'prod'],
    default: 'dev'
  },
```

So my `NODE_ENV` can be "production" or "prod", or "development" or "dev", and the default on some servers is "dev" in some cases and "prod" (or "production") in others.

**Comment by rfk** [comment]
This came up again when spinning up fxa-basket-proxy repo, raising priority

**Comment by vladikoff** [comment]
We fixed most of these, let's reopen if we hit this problem again..
