### ISSUE TITLE
Can we delete the isSampledUser experiment?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#570]
Also related references to `metrics.isSampledUser`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-718)
┆Issue Number: FXA-718

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~adavis@mozilla.com] [~loines@mozilla.com] are you still using this experiment?
