### ISSUE TITLE
Update use of 'master' branch in l10n/pontoon integration

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#5700]
Followup from #5695. I don’t know if we can change the fxa l10n repo from ‘master’ to ‘main’ without breaking pontoon integration, so I’ve retained references to ‘master’ in several places in the repo. The work here is to figure out if we can update pontoon to point to the 'main' branch instead, and if so, get that updated across this repo, the https://github.com/mozilla/fxa-content-server-l10n repo, and pontoon, and any docs we have for our localizers that aren't in these repos (??).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2137)
┆Issue Number: FXA-2137

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~axel@mozilla.com] - if we change the branch name from `master` to `main` in fxa-content-server-l10n will it break pontoon?

**Comment by data-sync-user** [comment]
➤ Axel Hecht commented:

I think that's possible, but it probably requires coordination.

[~mhorvat@mozilla.com]? Also, CC [~pmo@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Matjaz Horvat commented:

Right, we should coordinate the change and update Pontoon configuration accordingly.
