### ISSUE TITLE
Create new email template for `remind me later` for CAD

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5705]
Template for first reminder https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#bookmark=id.svmpy2gtxsjy

Template for second reminder https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#bookmark=id.svmpy2gtxsjy

We should be able to build one email template and pass in the contents via code. Docs for creating a new email [template](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-email)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2142)
┆Issue Number: FXA-2142

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

There were some open questions about which subject line to use for the reminder email. We discussed and it should be:
Your Friendly Reminder: How-To Complete Your Sync Setup

**Comment by vasilicatamas** [comment]
The "remind me later" emails are successfully received after 8 and 72 hours. 2 new issues (#5798 and #5799) were found and filed separately . Based on this I am marking this bug as verified.
