### ISSUE TITLE
FxA stage returns a 500 error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5708]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.176.0;

#### Affected Platforms:
- Windows 10 (64-bit);

### Steps to reproduce
1. Load https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ page
2. Try to sign in.

#### Expected result:
- Users are redirected to FxA stage authentication page. Users are able to sign in.

#### Actual result:
- An 500 error page is displayed.

![image](https://user-images.githubusercontent.com/15685960/85115943-31f69880-b225-11ea-93f4-99000772db98.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2146)
┆Issue Number: FXA-2146

**Comment by jbuck** [comment]
I've fixed this now, we didn't fully run the db migration so the backend was refusing to connect to the database

**Comment by ValentinaPC** [comment]
Verified as fixed using Fx77 and Windows 10 (64-bit).
The FxA stage is working without any 500 error at sign in.
![image](https://user-images.githubusercontent.com/15685960/85288590-a5570f00-b49e-11ea-8090-77fe4ad6a413.png)
