### ISSUE TITLE
"NZ$" currency and "An internal server error occurred" message at subscription upgrade

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5726]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.176.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with no subscription (US region);

#### Steps to reproduce
1. Go to  https://123done-stage.dev.lcip.org/ page.
2. Click on the “Subscribe for Pro” button.
3. Complete all mandatory fields and finalize subscription.
4. Load the  https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM URL in the same browser session.
5. Click on the "Confirm upgrade" button.

#### Expected result:
- The subscription upgrade is made.

#### Actual result:
- "An internal server error occurred" message is displayed and user is blocked to make the subscription upgrade.

#### Notes:
- In the "Set up your subscription" page the currency is "NZ$" instead of "$"
![nz](https://user-images.githubusercontent.com/15685960/85410369-ac018700-b56f-11ea-993d-1fbbdd1bf20c.png)
![image](https://user-images.githubusercontent.com/15685960/85410377-ad32b400-b56f-11ea-8f41-ea615ef656a6.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2158)
┆Issue Number: FXA-2158

**Comment by johngruen** [comment]
Hmm, this is probably b/c i added a NZ plan and 123done does not provide a plan in the subscription link URL

@ValentinaPC can you try this link: https://accounts.stage.mozaws.net/subscriptions/products/prod_FfiuDs9u11ESbD?plan=plan_FfiupsKXZ3mMZ6

**Comment by johngruen** [comment]
We should update the 123done link to the URL above

**Comment by ValentinaPC** [comment]
> 
> 
> Hmm, this is probably b/c i added a NZ plan and 123done does not provide a plan in the subscription link URL
> 
> @ValentinaPC can you try this link: https://accounts.stage.mozaws.net/subscriptions/products/prod_FfiuDs9u11ESbD?plan=plan_FfiupsKXZ3mMZ6

At this time the NZ currency is no longer displayed for 123done, without using the link you provided, and the subscription works as expected.

Yesterday, we also noticed the "₤" currency for 123done product. This was also removed.
Subscription upgrade finalizes with success.
