### ISSUE TITLE
Subscription for “One, Two, Three Done...PRO” is not working if a VPN subscription was made first

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5727]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.176.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active normal subscription;

#### Steps to reproduce
1. Go to https://123done-stage.dev.lcip.org/ page.
2. Fill all mandatory fields and click the “Pay now” button.

#### Expected result:
- Payment confirmation page is loaded.

#### Actual result:
- “An internal server error” message is displayed.

![image](https://user-images.githubusercontent.com/15685960/85411784-752c7080-b571-11ea-8b3e-f5724de561fe.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2159)
┆Issue Number: FXA-2159

**Comment by johngruen** [comment]
@chenba this looks like the issue you encountered?

**Comment by chenba** [comment]
Sounds like it, although my attempted second subscription was with a different credit card in a different currency.  Not sure if that had any effects.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I was unable to reproduce this after trying these steps:

  * Sign up for a new account at accounts.stage.firefox.com
  * Pay for a Firefox Private Network subscription ( https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_Fnzoovl5zlg0Zd )
  * Visit https://123done-stage.dev.lcip.org/ and click "Subscribe for Pro"
  * Pay for a One, Two, Three Done...PRO subscription ( https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_FfiuDs9u11ESbD )

All of the above worked for me without error. I also tried with existing staging accounts I'd created earlier in the month and saw no errors.

I wonder if there might have been some temporary issues with some edits made to products in the staging Stripe environment that we undid? Maybe that fixed it?

**Comment by ValentinaPC** [comment]
> All of the above worked for me without error. I also tried with existing staging accounts I'd created earlier in the month and saw no errors.
> 
> I wonder if there might have been some temporary issues with some edits made to products in the staging Stripe environment that we undid? Maybe that fixed it?

Yeah, maybe that fixed it. As soon as the currency changed back to normal (form NZ$ or pounds to $), everything started to work again, as expected.
