### ISSUE TITLE
Subscription Issues After Invalid Card

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5731]
**STR**

1. Attempt to subscribe to a product in staging (123done or whatever) with a valid CC that stripe rejects for being blocked (eg, the Stripe demo card for Norway for example, 4000 0057 8000 0007)
1. Your card will be rejected (auth server throws {"code":400,"errno":186,"error":"Bad Request","message":"Payment method failed","info":"https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format"})
1. Try again with a valid test card (4242 4242 4242 4242)
1. This time, the auth server throws a 500: {"code":500,"errno":999,"error":"Internal Server Error","message":"An internal server error occurred","info":"https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format","request":{"acceptLanguage":"en,en-US;q=0.5","locale":"en","userAgent":{"browser":"Firefox","browserVersion":"79.0","os":"Mac OS X","osVersion":"10.15","deviceType":null},"method":"post","path":"/v1/oauth/subscriptions/active","query":{},"payload":{},"headers":{"host":"localhost:9000","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0","accept":"*/*","accept-language":"en,en-US;q=0.5","accept-encoding":"gzip, deflate","referer":"http://localhost:3031/","content-type":"application/json","authorization":"Bearer b7a9a0aa21189191fdefd3446a509d9f1f7de256b26aa09dfd2cfd9426322e2f","origin":"http://localhost:3031","content-length":"198","dnt":"1","connection":"keep-alive","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"cross-site"}}}
1. Clicking the Pay Now button again, you see a "User already subscribed." message and a 409 error from the auth server: {"code":409,"errno":187,"error":"Already subscribed","message":"User already subscribed.","info":"https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format"}
1. Now, navigate to FxA settings, you would expect to see the "payments and subscriptions" section but it is not present, this is verified in the network panel by looking at the profile
1. In Stripe, the customer is shown as an active subscriber

**Expected**

regardless of previously rejected payments, users should be able to subscribe w/o issue given a valid payment method

**Actual**

User is able to create a subscription (ie start paying, subscription is active in stripe) but cannot access their subscription

**Note**

I discovered this trying international cards, but there may be other conditions where a user is rejected, tries to recover and is then put into this bad state. I am marking this as high priority to resolve b/c of this as it creates unknown exposure to chargebacks and fees.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2160)
┆Issue Number: FXA-2160

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

Status update:

This morning, I was unable to reproduce the error, and instead saw the expected result in Staging. [~jgruen@mozilla.com] will re-attempt to verify if the error still exists.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Verified invalid

**Comment by ValentinaPC** [comment]
Verified this in Stage, using FF78 and Windows 10 x64.
@johngruen I can still reproduce the issue. After entering an invalid card, I am blocked in using a valid one and subscription is still not possible.
See bellow video.
![invalidcardfirst](https://user-images.githubusercontent.com/15685960/86449201-82d7b800-bd20-11ea-88c7-9c057d21bb54.gif)

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

Hmm, Valentina, can you provide your STR to get the initial error that I see at the start of your gif? [~vvirlics@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Sure! At least I'll try 😛
1. Enter the "4000002760003184" 3D secure credit card (+ complete all mandatory fields) + "Pay Now" click => "Payment method failed" message displayed; (I think this is expected as the 3D secure validation was not yet implemented)
2. Delete the 3D card, and enter a valid one "6011000990139424" (+ complete all mandatory fields) + "Pay Now" click => "A backend service request failed." message is displayed;

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Cannot reproduce.
