### ISSUE TITLE
Make sure Zip/Postcode field handles different valid lengths correctly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5732]
Right now we reject anything but 5 character, as we move to accept payments in other markets, we need to make sure that we allow the submission of valid codes (4 char, and 7 char in particular for Canada and UK respectively)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2161)
┆Issue Number: FXA-2161

**Comment by jodyheavener** [comment]
#4717 and possibly #4012 might be helpful here.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's remove our validation of this field and let Stripe's Radar to do the validation.  We also have this input as a numeric keyboard.  It should be changed back to standard.

[~jgruen@mozilla.com] will see if we should restrict on min/max characters.

/cc [~vtamas@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jgruen@mozilla.com] are 4 and 7 good restrictions on min/max?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

For now, let's ignore any validation here.  We'll let Stripe do it.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I'll leave the empty string validation in place.  Also, it currently does not show the numeric keyboard; nothing to change there.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

👍
