### ISSUE TITLE
Set Up Plans to test and debug international payments flows on 123done in staging

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5736]
We should add subscription plans for the following regions to 123done pro on staging

* Euros
* Canadian Dollars
* Malaysian Ringgit

These plans should be billed daily to make QA quicker. Plans should be individually accessible via separate buttons on 123done

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2167)
┆Issue Number: FXA-2167

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~clewis@mozilla.com]and [~jgruen@mozilla.com] to discuss and plan PI ticket request.

**Comment by ValentinaPC** [comment]
Verified this in stage, using Fx78.0.2 and Windows 10 (64-bit).
The intended changes are not available.
Please see screenshot below.
![image](https://user-images.githubusercontent.com/15685960/89010317-0502ce80-d317-11ea-9028-ada01398df8c.png)

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx79 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/89395125-927a6000-d715-11ea-8555-1de8c3b9c2cc.png)
