### ISSUE TITLE
Last subscription will change billing details for all previous subscriptions in Manage Subscription page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5749]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.176.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with active subscription for Firefox Guardian

#### Steps to reproduce
1. Go to https://123done-stage.dev.lcip.org/ page and sign up.
2. Click on “Subscribe for Pro”.
3. Fill all mandatory fields (using different billing information : different card, etc.) and click the “Pay now” button.
4. Navigate to Manage Subscription page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions .
5. Observed billing details.

#### Expected result:
- Each subscription has its own billing details.

#### Actual result:
- Billing details for the first subscription (Firefox Guardian) are replaced with the billing details of the second subscription (123done).

#### Notes:
- Billing details from each subscription mail are correct.
![duplicate card](https://user-images.githubusercontent.com/15685960/85533890-947ed880-b619-11ea-8d35-edc2a3f60105.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2173)
┆Issue Number: FXA-2173

**Comment by lmorchard** [comment]
> Each subscription has its own billing details.

This is actually **not** expected or supported. We currently only support one billing source across all subscriptions.

However, the UI for this is incomplete. We have pending tasks to rework these screens to separate the billing out from subscriptions, among other things.

Should probably pull @johngruen in on this for product insight.

**Comment by ValentinaPC** [comment]
@lmorchard still...the e-mails generated at each subscription have different billing details. 
I just expected to have the possibility, that, when buying different products, to be able to use different cards.

**Comment by lmorchard** [comment]
> still...the e-mails generated at each subscription have different billing details.

That might be the real bug

> I just expected, that, if I am able to make subscriptions for different products, using different cards, this would be reflected in the Subscription page.

That is what we don't support. We have plans to remove billing details from the individual subscriptions and have one section for billing that applies to all subscriptions. But, that work hasn't been done yet

**Comment by ValentinaPC** [comment]
Based on the above comments, I've logged a separate issue for this, as suggested.
