### ISSUE TITLE
User gets a 400 while trying to disable 2FA in an unverified session

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#575]
![](http://v14d.com/i/83efbefb4ccc6c5460c4263bc2a688c5d3ed54f1f2463b5cfaeeaf9049afef49.jpg)

From a Slack thread, someone got to settings, the 2FA button showed that it can be disabled.

![image](https://user-images.githubusercontent.com/128755/50290903-0c73ad80-043b-11e9-83d7-616fa2d06740.png)

I suggested workaround to them, create a new profile, login to Sync and try disable via settings that way.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-723)
┆Issue Number: FXA-723

**Comment by vbudhram** [comment]
A partial fix was landed for train 137, moving this to backlog for the UX work.
