### ISSUE TITLE
Take FxHey! off of pbooth's plate

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#5759]
@rfk noticed that https://philbooth.me/fxa is still up and running. This seems like something QA and our various RPs might like to use when waiting on changes to land or ship; maybe we should pull it into the mozilla org and spin up a permanent version on mozilla cloud servers.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2179)
┆Issue Number: FXA-2179

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I think there is a Slack bot that could fulfill this role.  I don't know where it is though.
