### ISSUE TITLE
Metrics: if oauth relier doesn't provide entrypoint, set entrypoint as the client_id

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#576]
if oauth relier doesn't provide entrypoint, set entrypoint as the client_id

@davismtl @irrationalagent what do you think about this idea?

See this chart with entrypoints and client ids: https://analytics.amplitude.com/mozilla-corp/chart/2ngrhz1/edit/nkdi8ub

**Comment by juliemccracken** [comment]
Will change it via policy.
