### ISSUE TITLE
[l10n][payments] Invoice number from “Thank you!” page has display issues while using a Firefox “fr”-locale build

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5775]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.177.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account;
- Firefox Release “fr” locale build installed;

#### Steps to reproduce
1. Go to https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ page using the profile from prerequisites;
2. Click on “Subscribe Now” button;
3. Fill all mandatory fields and click “Pay now” button;
4. Observe invoice number from “Thank you” page;

#### Expected result:
- Invoice number is correctly displayed.

#### Actual result:
- Invoice number is not rendered as expected.

#### Notes:
- not reproducing for “de”/”en-GB”/ locale build;
- invoice number in mails is rendered correctly;

![billingd](https://user-images.githubusercontent.com/15685960/85842289-29174100-b7a8-11ea-9932-c19e77b6eeb2.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2190)
┆Issue Number: FXA-2190

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for the tip [~lorchard@mozilla.com] .  This is being caused because the variable was localized and shouldn't be.

At this link: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/fr/main.ftl#L339 ( https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/fr/main.ftl#L339 ) $factureNumber should be $invoiceNumber

[~pmo@mozilla.com] - does this need to be fixed in Pontoon?  Also, is there some linting we can enable in Pontoon to avoid this? /cc [~axel@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Peiying Mo commented:

I fixed it in Pontoon.

So the usual check and error reporting doesn't include Fluent file format? Usually Pontoon will have a warning for touching variables/placeables. Let me see if a bug is already file regarding this issue.

**Comment by data-sync-user** [comment]
➤ Axel Hecht commented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1525514 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1525514 ) is filed for that, and there a few details that make it a little bit harder than we would hope.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for the fix and the comments.

@ QA - this will be fixed once stage gets updated again (and pulls in new strings)

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/86438549-7bf47980-bd0f-11ea-9354-d7506bf86f02.png)

**Comment by ValentinaPC** [comment]
@clouserw this is happening again while using a Firefox Release 78 "fr" localized build, on Windows 10 x64, while on stage.
See below screenshot.
![image](https://user-images.githubusercontent.com/15685960/86917491-cd48a280-c12d-11ea-946d-b633e69e7575.png)

Do you know why?
Thanks!

**Comment by Pike** [comment]
Per https://github.com/mozilla/fxa-content-server-l10n/blame/acdb6225834c2f77679d26be8cd62f97e22cdfb8/locale/fr/main.ftl#L291, the localization uses the right variable now, and hasn't changed in the past 12 days.

**Comment by ValentinaPC** [comment]
@Pike As you can see in the above screenshot, from 5 days ago, the issue was fixed.

**Comment by data-sync-user** [comment]
➤ Peiying Mo commented:

I just noticed something else in the screenshot for French. The currency is in US$, it should be in Euro. I also have a Danish localizer reporting currency not in Danish Krone.

**Comment by clouserw** [comment]
Train 178 failed to launch and we had to roll back.  I don't know how it would happen, but it's possible that messed up which l10n files we were including.  We've updated to Train 178.1 today.  Are you able to check this again now to see if it is fixed with the new train?

**Comment by ValentinaPC** [comment]
Verified this as fixed on stage (178.1) using Fx78 and Windows 10x64.
Postfix screenshot below.
![frinvoice](https://user-images.githubusercontent.com/15685960/87014033-3551c400-c1d4-11ea-9b31-9a7fd66858ca.png)
