### ISSUE TITLE
“Approval now required” page doesn't disappear if the approval is received while the app is not in focus on Fenix

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5776]
**Build**
Stage [Train 1.177.0]

**Affected platforms**
Android 9

**Steps to reproduce**
1. Login on desktop using a Firefox account.
2. Launch Firefox app and go to Settings.
3. Click on “Turn on Sync” button and select the “Ready to scan” option.
4. Switch to the computer. navigate to https://accounts.stage.mozaws.net/pair/ and click on "Show code" button.
5. Scan the pairing code using the device and tap on "Confirm pairing" button.
6. Switch the focus to another app (e.g GAuthenticator)
7. Complete all the steps on desktop side.
8. Focus the Firefox app.

**Expected results**
The user is redirected to the Settings tab where the Firefox account is appears as connected.

**Actual Results**
“Approval now required” page never disappears even if the user has been already connected.

**Additional notes**
This scenario could often be encountered by the users that have 2FA enabled and they have to switch to the authentication app for the security code.

![Screenshot_3](https://user-images.githubusercontent.com/18114210/85843971-af348700-b7aa-11ea-80ac-2542ff53acc2.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2191)
┆Issue Number: FXA-2191

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Based on comment 0 it sounds like this is working, it just doesn't look like it is, so, I will backlog.
