### ISSUE TITLE
[l10n][payments] Payments details section from “Thank you!” page lists both “US” and “$” currency while using a “fr” locale build

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5777]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.177.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account;
- Firefox Release “fr” locale build installed;

#### Steps to reproduce
1. Go to https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ page using the profile from prerequisites;
2. Click on “Subscribe Now” button;
3. Fill all mandatory fields and click “Pay now” button;
4. Observe Payment details section from “Thank you” page;

#### Expected result:
- Payment details section displays only “$” currency.

#### Actual result:
- Payment details  section lists both “$” and “US” currencies.

#### Notes:
- not reproducing for “de”/”en-GB”/”en-CA” locale build;
- currency is rendered correctly in mails ;

![both](https://user-images.githubusercontent.com/15685960/85844872-13a41600-b7ac-11ea-9bc1-fd24e3ffe6ba.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2192)
┆Issue Number: FXA-2192

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

This is not a bug.  Unicode CLDR call for '$US'.

**Comment by rbillings** [comment]
The FR payment details display differently than DE or any other locale, where it only displays the "$" but not "US". So this doesn't sound like a unicode issue.

**Comment by chenba** [comment]
I didn't mean as a character encoding issue.  fr uses '$US': https://unicode-org.github.io/cldr-staging/charts/37/summary/fr.html#196bd456f629e908
