### ISSUE TITLE
L10n extraction is broken

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5783]
error at [https://app.circleci.com/pipelines/github/mozilla/fxa-content-server-l10n/974/workflows/770d2a47-1441-4dd5-8c73-e90e3b72fc39/jobs/7219/steps](https://app.circleci.com/pipelines/github/mozilla/fxa-content-server-l10n/974/workflows/770d2a47-1441-4dd5-8c73-e90e3b72fc39/jobs/7219/steps)

Danny says he knows what is wrong and can fix it

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2196)
┆Issue Number: FXA-2196

**Comment by dannycoates** [comment]
fixed
