### ISSUE TITLE
Unable to sign in with fxa-js-client

### ISSUE THREAD

**Issue by Barabazs** [mozilla/fxa#5794]
## Description

I'm unable to sign in to my account with the fxa-js-client module. I keep getting error number 125.
I tried this with an existing account and a newly created account.
Even with an unblock code, the error persists.
```
{
  code: 400,
  errno: 125,
  error: 'Request blocked',
  message: 'The request was blocked for security reasons',
  info: 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format',
  verificationMethod: 'email-captcha',
  verificationReason: 'login'
}
```

### Steps to reproduce

I am trying to login by using the code below in the file [packages/fxa-js-client/node/index.js](https://github.com/mozilla/fxa/blob/main/packages/fxa-js-client/node/index.js)
```
const authServerURL = "https://api.accounts.firefox.com/";
let fxAcct = new FxAccountClient(authServerURL);
let userEmail = ********;
let userPwd = *********;
fxAcct
    .signIn(userEmail, userPwd)
    .then((res) => console.log(res))
    .catch((err) => console.log(err));

```

### Expected result
Being able to sign in successfully or confirm identity through email-2fa.

### Actual result

Error no 125 persists.
```
{
  code: 400,
  errno: 125,
  error: 'Request blocked',
  message: 'The request was blocked for security reasons',
  info: 'https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#response-format',
  verificationMethod: 'email-captcha',
  verificationReason: 'login'
}
```

### Environment
node: v12.16.3
OS: Ubuntu 20.04 LTS

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2200)
┆Issue Number: FXA-2200

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Can you give some more details about what you are trying to accomplish?  It sounds like you are trying to auth against our servers but use your own version of fxa-js-client?

**Comment by Barabas-dev** [comment]
Yes, that's pretty much what I'm trying to do.
I have not modified the fxa-js-client, but I'm only trying to use it to interact with my existing account.

I did manage to programmatically sign up with a new account successfully. But signing in with either the orignal or new account remains unsuccessful.

**Comment by Barabas-dev** [comment]
> ➤ Wil Clouser commented:
> 
> It sounds like you are trying to auth against our servers but use your own version of fxa-js-client?
Is that not supported?
