### ISSUE TITLE
Host the list of commonly-used passwords somewhere that's controlled by the FxA team

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#5796]
Ref https://github.com/mozilla/application-services/issues/3292

The application-services repo currently hosts (and publishes via github pages) this [list of commonly-used passwords](https://mozilla.github.io/application-services/docs/accounts/50000-most-common-passwords.html), which is indirectly linked to from the FxA password-strength helper UI. We'd like to be able to decommission the docs site on which it's hosted, and also it's organizationally kind of weird for it to be maintained by team other than FxA, and also it contains a bunch of obscenities and slurs that I don't want to have just hanging out in our repo for what I don't think is any good reason.

Could we please work together to re-home this document somewhere where it's the responsibility of the FxA team? (Or, decide that it's not necessary at all and just delete it?).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2201)
┆Issue Number: FXA-2201

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's remove this page.  I also agree that we should remove all those FxA docs completely in favor of the ecosystem docs.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Passing this back to rfk by duping to https://jira.mozilla.com/browse/SYNC-1448 .  We're ready for that to be removed.
