### ISSUE TITLE
[l10n][payments] Cancel Subscription confirmation mail displays the currency twice

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5797]
- All Firefox;

#### Affected FxA versions:
- 1.177.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions
- existent FxA account with an active subscription;
- Firefox Release “de” locale build installed;

#### Steps to reproduce
1. Go to https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscription page using the profile from prerequisites;
2. Click on “Cancel Subscription” button;
3. Go to email client and check the unsubscribe confirmation mail;

#### Expected result:
- There are no display or layout issues.

#### Actual result:
- The currency value is listed twice before and after the billing value.

#### Notes:
- not reproducing for “fr”/”en-GB”/”en-CA” locale build;

![doi](https://user-images.githubusercontent.com/15685960/85998411-7a773880-ba13-11ea-98f0-b0a121a6ba34.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2202)
┆Issue Number: FXA-2202

**Comment by lmorchard** [comment]
This looks like a typo in the `de` localization: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/de/LC_MESSAGES/server.po#L355
```
"Wir haben Ihr Abonnement für %(productName)s gekündigt. Ihre letzte Zahlung von %(invoiceTotal)s $ wurde 
```

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

That extra '$' is a typo.  However, that '$9.99' is also incorrect; it should be '9,99 $'.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

The formatting bug is caused by the fact that we use Node 12 and Intl.NumberFormat requires Node >=13.  I've filed FXA-2207 for upgrading Node.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Filed https://github.com/mozilla/fxa-content-server-l10n/issues/428 ( https://github.com/mozilla/fxa-content-server-l10n/issues/428 ) for the extra '$' in the translated string.

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/86445561-48b7e780-bd1b-11ea-8d97-381e28ecc64e.png)
