### ISSUE TITLE
The links from “Complete Your Sync Setup” emails received for a stage account point to production

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5798]
**Note**
This is a follow-up bug for #5705

**Build**
Stage [Train 1.177.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Launch Firefox and login using a Mozilla account.
2. Click on “I’ll do this later, send me a reminder” button from “Sync Firefox between devices” page.

**Expected results**
The stage user is redirected to stage links:
1. First email:
[Sync another device](https://accounts.stage.mozaws.net/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-first&utm_content=fx-connect-device) and [another device](https://accounts.stage.mozaws.net/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-first&utm_content=fx-connect-device)
2. Second email:
[Sync another device](https://accounts.stage.mozaws.net/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-second&utm_content=fx-connect-device) and [another device](https://accounts.stage.mozaws.net/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-second&utm_content=fx-connect-device)

**Actual Results**
The stage user is redirected to production links:
1. First reminder:
[Sync another device](https://accounts.firefox.com/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-first&utm_content=fx-connect-device) and [another device](https://accounts.firefox.com/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-first&utm_content=fx-connect-device)
2. Second reminder:
[Sync another device](https://accounts.firefox.com/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-second&utm_content=fx-connect-device) and [another device](https://accounts.firefox.com/connect_another_device/?utm_medium=email&utm_campaign=fx-cad-reminder-second&utm_content=fx-connect-device)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2203)
┆Issue Number: FXA-2203

**Comment by jodyheavener** [comment]
As long as its drawing from the same config value (`smtp.syncUrl`) I think this is fixed in #5779

**Comment by vbudhram** [comment]
> I think this is fixed in #5779

Yea, that should be the fix, which would be live next train.

**Comment by clouserw** [comment]
Thanks all.  Closing via https://github.com/mozilla/fxa/pull/5779
