### ISSUE TITLE
Payment charges not found in subscription payment intent on subscription creation.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#5818]
https://sentry.prod.mozaws.net/operations/auth-stage/issues/8939638/?referrer=github_plugin

```
Payment charges not found in subscription payment intent on subscription creation.
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2208)
┆Issue Number: FXA-2208

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

auth-prod issue: https://sentry.prod.mozaws.net/operations/auth-prod/issues/8957034/

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Closing as WONTFIX because the SCA work affects the subscription/payment flow.
