### ISSUE TITLE
Profile token endpoint errors with PPIDs and shorter TTL

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#5826]
Update: this issue does not block lowering the JWT default TTL down to 6 hours. The problems FPN encountered turned out to be specific to FPN's use case and changes over time (see rfk's comments in #6368 for details). I'll close this when #6368 lands and file followup bugs once I figure out whether there are already bugs for the quirks in FxA's PPID and JWT code.

-----

In the earlier issue https://jira.mozilla.com/browse/FXA-1780, I had planned to fix our daily usage numbers, starting by fixing a validation bug in auth-server that was preventing us from shortening the oauth token durations (also known as lifetime, or time-to-live, abbreviated 'TTL') down to the same six hour duration used in browserid assertions. Sync is migrating from browserid assertions to oauth tokens, so lowering the oauth token lifetimes to a matching six hours would get our daily device numbers back to normal.

Note that clients request these oauth tokens via the profile server, which relays the call through to the auth server. We discovered in production with FPN that, while the bug is fixed in auth server, a bug still exists in profile server: lowering the requested TTL down to 6 hours in profile-server requests throws an error.

So, in order to lower oauth token TTLs down to six hours, we now need to fix this profile-server bug, to restore accurate daily sync device numbers.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2212)
┆Issue Number: FXA-2212

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jhirsch@mozilla.com] We're in triage now and trying to prioritize this.  Would you give us some guidance on priority?  Thanks

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~adavis@mozilla.com] it sounds like counts for active devices are currently wrong due to this issue.  There is some backstory in https://jira.mozilla.com/browse/FXA-1780 .  I'm considering this a lower priority than AET but open to feedback.  I expect to fit it into the schedule after FXA-2029

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

If we can fix this bug after AET, I'd appreciate it. We're plagued with a lot of metric changes and bugs lately so it's hard to tell what's a new trend and what's a bug.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Estimating at 3 points as an initial guess.

**Comment by 6a68** [comment]
This turned out to be a much more involved bug than expected!

We can't have RPs request `profile` scope JWTs when using PPIDs. This only surfaces at shorter TTLs. I'll add a check to the token grant code to enforce this with a readable error message.
