### ISSUE TITLE
Allow a relying web service to display authenticated FxA user profile

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#585]
Relying services like AMO and Firefox Monitor can increase their adoption by offering users a "Continue as" button. We should provide an API (like Facebook does for messenger.com below) that allows relying services to query for the currently authenticated FxA user and display:
1. Email address
1. Display name (if set, or not set)
1. Profile picture (if set, or not set)
This would greatly reduce friction, as users would recognize themselves and not need to re-enter their email address. Depending on the service, further details like password, may be required.

<img width="343" alt="screen shot 2018-11-14 at 4 34 42 pm" src="https://user-images.githubusercontent.com/68213/48563848-388f9200-e8c3-11e8-885f-f0a66f11fb43.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-732)
┆Issue Number: FXA-732

**Comment by shane-tomlinson** [comment]
See https://youtu.be/BxTuCh75xAU
