### ISSUE TITLE
Avatar is no longer displayed.

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#5858]
With my docker-self-hosting the avatar in the upper right corner of the addon bar is no longer displayed on some instances. Also logging out in Firefox and logging in again does not bring any improvement.

Thank you...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2232)
┆Issue Number: FXA-2232

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We haven't changed anything around this code recently so I don't think it's a newly introduced bug on the FxA side.  I'm going to close this as there isn't much we can do from here.

**Comment by jackyzy823** [comment]
Hello @misterhsp 
I've encountered similar issue , probably may help you.

in `fxa-auth-server` edit config about clients and add `"publicClient": true` to `firefox` entry which id is `5882386c6d801776`

see : https://github.com/mozilla/fxa/commit/19ce415#diff-071040d5f028a4dfefcb67b4f6d59144

**Comment by jackyzy823** [comment]
Hello @misterhsp 
I've encountered similar issue , probably may help you.

in `fxa-auth-server` edit config about clients and add `"publicClient": true` to `firefox` entry which id is `5882386c6d801776`

see : https://github.com/mozilla/fxa/commit/19ce415#diff-071040d5f028a4dfefcb67b4f6d59144

**Comment by misterhsp** [comment]
@jackyzy823 
Can you be more specific? I don't understand what you mean.

**Comment by jackyzy823** [comment]
May i know how you docker-self-hosting ? espeically `fxa-auth-server`

**Comment by misterhsp** [comment]
yes, docker-self-hosting. I am currently not at home for a longer time.

**Comment by jackyzy823** [comment]
Well....
Have you check error logs in `about:sync-log` in firefox.
It may provide useful information.

**Comment by misterhsp** [comment]
I'll take care of it when I get back home. So far away now is bad. I'll give you some more feedback then.

**Comment by misterhsp** [comment]
I found the problem. In the profile folder of Firefox in the file signedInUser.json the section "profileCache" is no longer created in which the Avatar-ID and URL from prodile-server stored for download. Disconnecting and logging in again does not change this.

**Comment by misterhsp** [comment]
How do you open them again?

**Comment by misterhsp** [comment]
Is there any way to force this to re-create the section?

...

**Comment by misterhsp** [comment]
@jackyzy823 
No errors can be found in the sync-log.

...
