### ISSUE TITLE
A/B test signin/signup rates for 100k PBKDF2 rounds

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#587]
We'd like to bump the # of rounds of PBKDF2 run on a user's password to 100k which will take several seconds on older mobile devices. We want to find out whether this causes a drop in registration and login rates using an A/B test before we ship the change out to everyone.

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1320222

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-733)
┆Issue Number: FXA-733

**Comment by clouserw** [comment]
When we do this, let's use WebCrypto which should make it more performant.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Next steps here:

  * Use webcrypto as a hard dependency
  * Review how many iterations 1password is doing now and lets do that many
  * Let's implement the extra iterations in an A/B test, but then throw away the results.  The actual login will continue to use the current system, the treatment in the A/B test will just do some extra calculations and then throw away the result
  * [~adavis@mozilla.com] [~loines@mozilla.com] what are the right things to measure here?  Total successful logins?
