### ISSUE TITLE
VPN ToS and PN were not removed from the update payment page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5873]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.178.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have and active FxA account;

#### Steps to reproduce
1. Load the VPN main page https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ while signed in with the account from prerequisites; 
2. Click on the “Subscribe Now” button
3. Complete all mandatory fields and finalize subscription;
4. Go to the subscription page https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions ;
5. Click to change billing details.

#### Expected result:
- There are no ToS and PN on the update form;

#### Actual result:
- There are ToS and PN links on the update form;

#### Notes:
- Same for Subscription Proxy, Firefox Variety and 123done products;
![updatepayment](https://user-images.githubusercontent.com/15685960/86768415-34932380-c056-11ea-968f-9f40805c3b4d.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2241)
┆Issue Number: FXA-2241

**Comment by lmorchard** [comment]
I don't think it's expected that these are removed from the page, as long as there's a plan associated with the billing form like there is here (i.e. Firefox Guardian).

When we eventually have support in the UI for multiple products, they'll probably go away then.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Conclusion: get rid of both of these links when updating payments.  (We still need them for creating new payments)

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78.0.2 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/87759338-d49b3a80-c816-11ea-96e6-3bfccd65fa11.png)
