### ISSUE TITLE
[fxa-profile-server] Uploading images fails with Istio/Envoy

### ISSUE THREAD

**Issue by enote-kane** [mozilla/fxa#5874]
## Description

When setting up the FxA stack inside a Kubernetes cluster and using Istio as a service mesh with Envoy, avatar upload requests that are passed through to the profile server to the actual internal worker service for processing will fail with a HTTP `500`.

### Steps to reproduce

Set up the FxA stack in Kubernetes where Istio and Envoy are properly configured.

### Expected result

Avatar upload succeeds.

### Actual result

Avatar upload fails with HTTP `500` and errno `103`.

### Environment

_not applicable_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2240)
┆Issue Number: FXA-2240

**Comment by enote-kane** [comment]
Although I know that Kubernetes is not a major target for running FxA, I could provide a pull-request, which I've already verified at our side.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Hi Kane.  We don't support Kubernetes so it depends on what the PR is for and what it would do.  If it means more maintenance or testing on our side we probably wouldn't land it.

**Comment by enote-kane** [comment]
OK, it is basically about the fact that the HTTP request to the worker gets all HTTP headers from the original request, including the `Host` header, which is against the spec ([RFC 7230, 5.4. Host](https://tools.ietf.org/html/rfc7230#section-5.4)):
> [...] When a proxy receives a request with an absolute-form of request-target, the proxy MUST ignore the received Host header field (if any) and instead replace it with the host information of the request-target. [...]

The PR I would create adds a configurable array of HTTP headers to ignore/exclude to the profile server. defaulting to `['host']`, but other headers may be needed in other scenarios.

**Comment by clouserw** [comment]
If an empty list makes it do nothing (meaning, the functionality is the same as today) I think it sounds like a good patch.

**Comment by enote-kane** [comment]
Yes, explicitly unconfiguring it with `null` or an empty array (or even some value that doesn't match any header, practically) will result in the current behavior.

However, again, the current behavior is - strictly speaking - violating the spec.

**Comment by enote-kane** [comment]
@clouserw 
I've just added PR #5917 to address this issue in a flexible and non-breaking way. It would be great if someone could havea look at it.
