### ISSUE TITLE
Clicking on Firefox Variety ToS triggers a pdf copy of the Subscription Proxy ToS

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5875]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.178.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have and active FxA account;

#### Steps to reproduce
1. Load the Firefox Variety subscription page while being logged in with the account from prerequisites https://accounts.stage.mozaws.net/subscriptions/products/prod_H63sY3qFAwW4Rk?plan=plan_H647jpSbC33HHp 
2. Click on the ToS link from authorization section or the one below the “Pay now” button;

#### Expected result:
- A page with the Firefox Variety ToS is opened;

#### Actual result:
- A copy of the Subscription Proxy ToS is downloaded.

#### Notes:
- This is happening all over the places where Firefox Variety ToS are listed;
![ToSfromSP](https://user-images.githubusercontent.com/15685960/86768853-d9156580-c056-11ea-8246-75d2df760d6c.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2239)
┆Issue Number: FXA-2239

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Les suggests adding 2 more metadata fields to stripe to differentiate HTML and download which seems like a good path forward.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Thinking that the fix for this is adding 2 more metadata props for PDF vs HTML links, then use the PDF links in email instead of HTML

**Comment by ValentinaPC** [comment]
The initial issue is still reproducing - not sure if this was meant to be like that: the product listed in the Firefox Variety ToS from SubPlat pages is FPN Browser Extension, as you cans see below.

But, I can confirm that ToS from subscriptions emails ("Terms and cancellation policy" link) trigger a .pdf copy of the Mozilla VPN product for all products (suppose this is intended, as Firefox Variety and 123done are not quite "real" product)
