### ISSUE TITLE
Firefox Private Network ToS and PN are displayed for Subscription Proxy/123done and Firefox Variety products

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5876]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.178.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have and active FxA account;

#### Steps to reproduce
1. Load the Subscription Proxy main page https://stage-browser.guardian.nonprod.cloudops.mozgcp.net/ 
2. Click on the “Subscribe for $2.99/Month” button;
2. Click on the ToS and PN links from authorization section and below the “Pay now” button;

#### Expected result:
- A page with the ToS and PN of the Subscription Proxy are opened.

#### Actual result:
- A page with the ToS and PN of the Firefox Private Network is opened.

#### Notes:
- Incorrect ToS and PN are displayed all over the places where available.
![SPtos](https://user-images.githubusercontent.com/15685960/86768987-14b02f80-c057-11ea-9d63-11d52ca4a5b3.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2238)
┆Issue Number: FXA-2238

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

These are the right ToS and PN for this product.  Closing

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78 and Windows 10 (64-bit).
Postfix screenshot below.
![tosPN](https://user-images.githubusercontent.com/15685960/87552555-83763400-c6ba-11ea-9dd0-e17f9cd9acf3.png)
