### ISSUE TITLE
Enrolling Sync Optional users to QR flow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5881]
In the Sync optional flow, users are asked if they want to turn on Sync. If they select no, we send them into the CAD QR code flow.

* If they selected to turn on Sync, this makes sense.
* If they don't turn on Sync, we shouldn't do this.
* In both cases, we should avoid redirecting the SMS CAD at the end.

It's unclear if we forced the SMS flow on people who opted out of Sync so I don't know if this is a QR experiment bug or a broader one.

See https://www.loom.com/share/3a63ddd6deb94750b4c9756e45b17cd1

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2245)
┆Issue Number: FXA-2245

**Comment by vbudhram** [comment]
> It's unclear if we forced the SMS flow on people who opted out of Sync so I don't know if this is a QR experiment bug or a broader one

There was not logic to gate this on the CAD page, so in the Sync optional flow either CAD SMS/QR would have been shown to the user if they were eligible.
