### ISSUE TITLE
FPN ToS/PN have the “FPN Browser Extension (Beta)” title

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5889]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.178.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have and active FxA account;

#### Steps to reproduce
1. Load the FPN main page https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ 
2. Click on the “Subscribe Now” button;
3. Click on the “Terms of Service” link;

#### Expected result:
- User is redirected to the FPN ToS page.

#### Actual result:
- User is redirected to a ToS page that has the “FPN Browser Extension (Beta)” title.

#### Notes:
- The content mentions the FPN product.
- Same title is available in all the ToS pages for the FPN/Firefox Variety products.
![image](https://user-images.githubusercontent.com/15685960/86907531-daf62c00-c11d-11ea-8a7a-d3c5ca8ea62b.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2249)
┆Issue Number: FXA-2249

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I think this is fixed now.  When I follow the steps to reproduce I end up on https://www.mozilla.org/en-US/about/legal/terms/mozilla-vpn/ ( https://www.mozilla.org/en-US/about/legal/terms/mozilla-vpn/ )

If you don't end up there, please be specific about what URLs you are seeing.  Thanks

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78 and Windows 10 (64-bit).
Postfix video below.
![tosandpn](https://user-images.githubusercontent.com/15685960/87519239-fc10cc80-c689-11ea-88a9-e814bd70a5c3.gif)
