### ISSUE TITLE
enhance must-change-password.js to accept a plain text list of email addresses

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5895]
SImilar to https://github.com/mozilla/fxa/issues/5894, enhance this script to take a plain text list of email addresses, resolve those to uid (including lookup of secondary/primary address), and do this action.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2251)
┆Issue Number: FXA-2251

**Comment by mhk19** [comment]
@jrgm @data-sync-user I want to work on this issue, may I?

**Comment by Yashs911** [comment]
Hi, @jrgm I would like to work on this issue.

**Comment by Cronus1007** [comment]
@jrgm Actually I want to work on this issue so shall I take over this issue.

**Comment by Cronus1007** [comment]
@jrgm It would be really helpful for me if you refer the codebase since I am very new to the fxa repo

**Comment by Cronus1007** [comment]
cc @bbangert  @chenba

**Comment by LZoog** [comment]
@Cronus1007 are you still interested in working on this? You can maybe check out the related issue #5894 and corresponding PR, #5981 🙂

**Comment by Cronus1007** [comment]
@LZoog Sure I will. Can you assign this issue to me?
