### ISSUE TITLE
[content server] Apply the MX record validation feature flag to the validate-email-domain endpoint

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5896]
There's a feature flag for the MX record validation feature, but currently it only affects the frontend.  Let's have the endpoint immediately return a 200 response if the feature flag is set to off.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2252)
┆Issue Number: FXA-2252

**Comment by karthikshetty03** [comment]
I would like to work on this issue.
Can I know more about this issue as well as the filename where the code needs to be changed ?

**Comment by chenba** [comment]
@karthikshetty03 The function that process validation request starts at https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/routes/validate-email-domain.js#L69.  And this issue asking that if the configuration https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/configuration.js#L367 is false, that function would then return a 200 response.

Thanks for working on this!

**Comment by chenba** [comment]
@Cronus1007 Good question.  Let return a result of 'skip' along with the 200.  The list of available results are declared at https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/routes/validate-email-domain.js#L16.  And when the frontend get that result, it just resolves the promise.
