### ISSUE TITLE
Post verify email is not received for accounts created on Fenix or iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5920]
**Build**
Prod [Train 1.178.0]
Stage [Train 1.179.0]

**Affected platforms**
iOS 13.4.1
Android 9 

**Steps to reproduce**
1. Create and verify a sync account using Fenix or Firefox for iOS
2. Observe the email received after the account confirmation.

**Expected results**
“Account verified. Next, sync another device to finish setup” email is successfully received.

**Actual Results**
“New sign-in to Firefox Preview” and “New Sign-in to Firefox iOS” emails are received.

**Notes**
This issue is not reproducible while using Fennec.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2272)
┆Issue Number: FXA-2272

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~adavis@mozilla.com] to get clarity per Leads discussion

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Just to be sure I understand, users are getting login notification emails when they register on iOS or Fenix (rather than the new template entitled “Account verified. Next, sync another device to finish setup”)?

If I am not mistaken, “New sign-in to Firefox Preview” and “New Sign-in to Firefox iOS” emails are not what we previously sent either. They would have received an account verified email.

**Comment by vasilicatamas** [comment]
> Just to be sure I understand, users are getting login notification emails when they register on iOS or Fenix (rather than the new template entitled “Account verified. Next, sync another device to finish setup”)?

yes, that's correct!

![Screenshot_11](https://user-images.githubusercontent.com/18114210/87426612-227e2b80-c5e8-11ea-9ada-620e0f5319e5.png)

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [1.182.0] under Android 9 and iOS 13.6. "Account verified. Next, sync another device to finish setup" email is successfully received by Android and iOS users after confirming the account.

![Screenshot_1](https://user-images.githubusercontent.com/18114210/89031064-68eabe80-d33a-11ea-9082-7b187053ad4f.png)
