### ISSUE TITLE
The ToS and Privacy Notice links redirect to a 404 error page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5937]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.179.2;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Steps to reproduce:
1. Go to Mozilla VPN page https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/;
2. Click on the “Try Mozilla VPN” button;
3. Click on the ToS/PN available links;

#### Expected result:
- The ToS/PN links redirect to specific pages.

#### Actual result:
- The ToS/PN links redirect to a 404 page;

#### Notes:
- We assume that this happened while changing the "FPN" name to "Mozilla VPN" new name.

![image](https://user-images.githubusercontent.com/15685960/87403266-5136da80-c5c5-11ea-9dc5-97b351edb136.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2279)
┆Issue Number: FXA-2279

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~vvirlics@mozilla.com]these have been redeployed by Legal and this appears to be resolved. Closing accordingly - please reopen if further issue occurs.

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78 and Windows 10 (64-bit).
Postfix video below.
![tosandpn](https://user-images.githubusercontent.com/15685960/87520356-8443a180-c68b-11ea-865a-852d4878c6bc.gif)
