### ISSUE TITLE
Payments in some locales do not show that they are USD

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5942]
STR

* Set your browser's accept-header to en-nz
* Complete a checkout flow

Expected

* Price is displayed as US$4.99

Actual

* Price is displayed as $4.99

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2280)
┆Issue Number: FXA-2280

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

So I tried just doing ->

return `new ${Intl.NumberFormat("en-US", options).format(decimal)} ${currency}`; 

As a return on the this https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/lib/formats.ts#L43 ( https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/lib/formats.ts#L43 )

I still see the error which suggests that we are not hitting the fallback. My guess is that the global locale fallback to en-US supersedes this?

**Comment by lmorchard** [comment]
Not sure if this is related, but we recently found problems with currency localization between versions of node.

```
Welcome to Node.js v13.7.0.
Type ".help" for more information.
> new Intl.NumberFormat('fr', { style: 'currency', currency: 'USD' }).format(599)
'599,00 $US'
> new Intl.NumberFormat('en-NZ', { style: 'currency', currency: 'USD' }).format(599)
'US$599.00'
> 
```

```
Welcome to Node.js v12.14.1.
Type ".help" for more information.
> new Intl.NumberFormat('fr', { style: 'currency', currency: 'USD' }).format(599)
'$599.00'
> new Intl.NumberFormat('en-NZ', { style: 'currency', currency: 'USD' }).format(599)
'$599.00'
> 
```

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Also for what it's worth, we added a polyfill for the Intl API as part of FXA-2202 to resolve a similar issue in emails. https://github.com/mozilla/fxa/pull/5819

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

So yeah i am seeing the same thing in node, but what's weird is...if run the payments server using v12.18.2

and i add a console log above the fallback return.

console.log(new Intl.NumberFormat('en-NZ', options).format(decimal));
 return new Intl.NumberFormat('en-NZ', options).format(decimal);

the log correctly shows `US$5.99`

Additionally, if I go into a component, say here...https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/components/PlanDetails/index.tsx#L141 ( https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/components/PlanDetails/index.tsx#L141 )

and remove the wrapping `Localized` tag and just having the <p>{productPrice}</p> returns the correct string.

Which is to say, the problem seems to be coming from inside Fluent

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Tagging [~dcoates@mozilla.com] as the assignee as he and [~wclouser@mozilla.com] landed patches to resolve.

  * https://github.com/mozilla/fxa-content-server-l10n/pull/432 ( https://github.com/mozilla/fxa-content-server-l10n/pull/432 )
  * https://github.com/mozilla/fxa/pull/5948 ( https://github.com/mozilla/fxa/pull/5948 )

These landed and were promoted to Production around 5pm PT on 14 July in 179.3. Deployment details in Bugzilla deploy bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1651749 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1651749 )
