### ISSUE TITLE
[l10n] Payments emails list “$” currency instead of “US$”

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5953]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.179.3;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- have a Firefox “en-CA” locale build installed;
- have an FxA account with active subscription;

#### Steps to reproduce:
1. Open a new profile and sign in with the account from prerequisites;
2. Go to your email client 
3. Check the currency in the “Mozilla VPN payment confirmed” email;

#### Expected result:
- The currency listed is “US$”;

#### Actual result:
- The currency listed is “$”;

#### Notes:
- this is happening in all emails that contain the currency string  (tried different products also);
- this is happening for the following locales: en-CA, en-MY and en-SG;
![currency](https://user-images.githubusercontent.com/15685960/87532729-40a56380-c69c-11ea-9557-d9f17685c0bc.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2292)
┆Issue Number: FXA-2292

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This was fixed and pushed to production today

**Comment by ValentinaPC** [comment]
Verified as fixed in Stage 179.4, using Fx 78.0.2 and Windows 10 (64-bit).

Mails display the correct currency: "US$" for the following locales "en-CA", "en-MY" and "en-SG" while subscribing/resubscribing for Mozilla VPN, Subscription Proxy, 123Done Pro and Firefox Variety products.
