### ISSUE TITLE
Update fxa-js-client to update the anon_id

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5954]
These values need to be passed to the auth-server `/account/login` and `/account/create` endpoints.

They should be sent over as an optional param.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2293)
┆Issue Number: FXA-2293

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

>These values need to be passed to the auth-server `/account/login` and `/account/create` endpoints.

I don't have much context on the conversation that lead to this bug, but wanted to flag some potential complexity here. In order to calculate the eco_uid and turn it into an eco_anon_id, you have to have the user's kB, which means that you need to already be authenticated. So, I'm concerned that you won't have access to eco_anon_id at the time you're calling `/account/login` or `/account/create`.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~rkelly@mozilla.com] Thanks for flagging, we I've updated the bug to mention adding js-client functions to only update the id. We should be able to call this function after the user successfully logins and has access to all the required info to generate the id.

**Comment by vbudhram** [comment]
> call this function after the user successfully logins and has access to all the required info to generate the id

I think the plan now is to not deal with rotating on login and only when user changes their password, which simplifies things a good bit.
