### ISSUE TITLE
Add generate anon_id from scoped key and kB

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5956]
Per docs in https://docs.google.com/document/d/1zH3eVVI_28Afg1JXe_McDrW4MTYuWhiJMQR6AQbli8I/edit#heading=h.eo0wl228m5t2 we will need to do the crypto work.

1. Get kB
2. Derive ecosystem_user_id (see doc)
3. Get anonymizing key (Refer to #1228)
  1. Example. We POST metrics to content-server so we should do something similar here.
4. Encrypt ecosystem_user_id => ecosystem_anon_id
5. Return value to be saved

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2294)
┆Issue Number: FXA-2294

**Comment by rfk** [comment]
> Derive ecosystem_user_id (see doc)

Just a quick drive-by to note that the underlying key-derivation code should already be available for your use in `app/scripts/lib/crypto/scoped-keys.js `.
