### ISSUE TITLE
Add AET documentation to ecosystem platform

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5960]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2295)
┆Issue Number: FXA-2295

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

I think this is actually something [~rkelly@mozilla.com] was working on. Let's close this for now and follow up with him in Slack.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

I think rfk is working on this, will ping him about it. Closing.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~lzugai@mozilla.com] Maybe I was too hasty to close this out? Feel free to reopen if you have ideas about FxA-specific AET docs. We can do something now and merge with the other docs later.

**Comment by rfk** [comment]
> I think this is actually something [~rkelly@mozilla.com] was working on.

I do intend to move parts of the [working technical doc](https://docs.google.com/document/d/1rR3uJG8sVtow4plYu6M5Jp5e5zOSrLzdkUx8BdO8kOM) over to a more permanent home, you're welcome to leave this open and assigned to me if it's helpful.
