### ISSUE TITLE
“The image file size is too large to be uploaded.” error is always displayed when setting a picture avatar using camera on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5976]
**Notes**
This is a follow-up issue for #5348

**Build**
Stage [Train 1.180.0]

**Affected platforms**
iOS 13.4.1
iOS 13.5.1

**Steps to reproduce**
1. Login using a Firefox account and navigate to the Manage account page.
2. Click "Add" button from the Account picture area.
3. Click the “Upload” button and choose ”Take Photo” option.
4. Take a photo and click on “Use Photo” button.

**Expected results**
The picture taken with the iOS camera is successfully displayed as avatar. 

**Actual Results**
The following error message is displayed: “The image file size is too large to be uploaded.”

![issue4](https://user-images.githubusercontent.com/18114210/87808484-7431ea80-c862-11ea-987c-6858e916119e.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2305)
┆Issue Number: FXA-2305

**Comment by byrw** [comment]
The same error also happens with android. I think this is related with the limit size value being too low.

**Comment by jodyheavener** [comment]
@vbudhram Tagging you since we talked about file size limits earlier. Presumably the issue here is that the file returned by the device camera exceeds the new client file size validation (1.35mb). My question is, how was this passing server-side validation? I assume there's some compression happening somewhere.

**Comment by jodyheavener** [comment]
I haven't had time to dig into this too much, but I think if we can't sort it shortly we can just remove [the check](https://github.com/mozilla/fxa/pull/5941/files#diff-25a007784ec4c2571519f5ae3c07a819R106) (or revert) and get it in a point release.

**Comment by clouserw** [comment]
Have we talked about why the max file size is 1.35mb?  That seems really small in today's world of cameras.  For the sake of giving us something to talk about, how about we make it 15mb?  /cc @jrgm @jbuck

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage: maybe we are validating before it hits the cropper

**Comment by jodyheavener** [comment]
Yes, I believe this is the case. On testing, an input camera roll image of 2mb comes out of the cropper consistently less than 100kb. I think my recommendation is going to be to revert the frontend validation for now and try to identify the instances where the cropper is producing large outputs that lead to that "system unavailable" message.

**Comment by vasilicatamas** [comment]
Tested this issue across 3 platforms and these are the results:
- iOS: the error does no longer appear and the picture taken with the iOS camera is successfully displayed as avatar
- Fenix:  #5212 is still reproducible but the avatar can be successfully set when using the “Camera” option displayed near the “Upload” button 
- Windows: it seems that #5264 reproduces again and I filed a new ticket for this issue #6039 

Considering that the encountered issues are addressed separately I will mark this bug as Verified fixed.
