### ISSUE TITLE
"This message seems dangerous" warning in gmail from FxA welcome emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5977]
After the VPN launch on July 15th, we had a customer put in a support ticket that gmail warned that the FxA welcome emails that prompts the user to download the VPN clients.

I talked to Michele Warther about it and she said that there are some potential reasons this could be happening. It could also be that we got over 1,000 new customers in 24 hours and maybe a 1,000 FxA welcome emails trigger spam filters on gmail.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2306)
┆Issue Number: FXA-2306
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13528/image.png">image.png</a> | <a href="https://jira.mozilla.com/secure/attachment/13531/Screen+Shot+2020-07-17+at+4.28.32+PM.png">Screen Shot 2020-07-17 at 4.28.32 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Chris More commented:

[~mwarther@mozilla.com] could you help provide some insights here on what could be causing this issue?

**Comment by data-sync-user** [comment]
➤ Michele Warther commented:

Couple of questions/ideas for troubleshooting..

  * Does this domain that have DMARC/DKIM set-up?
  * How many different IP's are available for sending?
  * What is the sender reputation score % for each IP address?
  * Is the VPN email set-up differently then the other FxA emails?
  * Does it have a different priority level?
  * How/where does the download link go - to a Firefox or Mozilla domain?

We can run it through Litmus and/or Return Path for you to flag any other potential concerns.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Nothing special about the VPN emails.  DMARC/DKIM did just change a couple weeks ago.

I'll CC some more folks who might have comments.  [~bbangert@mozilla.com] [~jmunroe@mozilla.com] [~lorchard@mozilla.com] [~jbuckley@mozilla.com] [~jmorrison@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

{quote}How/where does the download link go - to a Firefox or Mozilla domain?{quote}

Someone with Stripe production account access (not me) can look up the download URL from the product metadata field.

For the rest of the questions: While I set up the logic & templates for subscription emails, I'm not all that familiar with the underlying email sending infrastructure. As far as I can tell, we're sending subscription emails through the same configuration as every other FxA email - i.e. no special change in priority or headers or other metadata that I'm aware of.

**Comment by data-sync-user** [comment]
➤ Chris More commented:

Yeah, I'd like to also confirm the URL of the download button too. I want to check to see if it was changed to vpn.mozilla.org or if it points to fpn.firefox.com/vpn, which is a redirect.

**Comment by data-sync-user** [comment]
➤ Jackie Munroe commented:

The download URL for the VPN in production:
https://fpn.firefox.com/vpn/download?utm_medium=email&utm_source=email&utm_campaign=subscription-download

**Comment by data-sync-user** [comment]
➤ Chris More commented:

Yeah, I just found it too in Stripe: https://fpn.firefox.com/vpn/download?utm_medium=email&utm_source=email&utm_campaign=subscription-download ( https://fpn.firefox.com/vpn/download?utm_medium=email&utm_source=email&utm_campaign=subscription-download )

That needs to be updated to:

https://vpn.mozilla.org/vpn/download?utm_medium=email&utm_source=email&utm_campaign=subscription-download ( https://vpn.mozilla.org/vpn/download?utm_medium=email&utm_source=email&utm_campaign=subscription-download )

I can do that now as I am looking at the variable in prod. Shall I update it?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

No objections from me.  +cc [~jgruen@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Chris More commented:

!Screen Shot 2020-07-17 at 4.28.32 PM.png!

**Comment by data-sync-user** [comment]
➤ Chris More commented:

Updated the downloadURL variable to vpn.mozilla.org instead of fpn.firefox.com. I am not sure how that could trigger a dangerous email notification.

I also noticed there are two ToS variables: termsOfServiceURL and product:termsOfServiceURL. The first points to the proxy terms and the second points to the Mozilla VPN terms. Should they both point to the same URL?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm pretty sure `termsOfServiceURL` can be deleted but would definitely want to verify from [~lorchard@mozilla.com] or [~jmunroe@mozilla.com] before it's done.

**Comment by data-sync-user** [comment]
➤ Chris More commented:

Hi everyone. Anyone have an update here? I am checking with support to see if any other customers have complained about this.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

> I'm pretty sure `termsOfServiceURL` can be deleted but would definitely want to verify from Les Orchard or Jackie Munroe before it's done.

`termsOfServiceURL` is incorrect and should be deleted. We've got the currently supported metadata props documented here:

https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#product-metadata

**Comment by ancoron** [comment]
I also got this spam warning, but using my own FxA + Sync servers on my own domains and almost all for the standard account verification, not related to VPN or anything. I initially thought it might have been on my setup (also because I am using another personal Gmail account for sending those mails). So I just re-checked all such mails and the warning is gone.

I personally suspect a broken rules/algorithm change in spam detection at gmail.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

So we have verified this issue with GMX and Gmail. The issue reproduced on both the initial download email and the receipt email for the VPN service.

Next step is to test whether swapping the PDF ToS link with a web-based link resolves.

**Comment by data-sync-user** [comment]
➤ Chris More commented:

Hi. Just looking for a quick update on where this is at so that Michele Warther knows when her team can re-start the marketing channels. Thanks all.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Three issues came out of this:
1) John swapped the PDF link with a regular web link in the emails
2) https://jira.mozilla.com/browse/FXA-2327 - we need to add a ToS link to our confirmation page
3) https://jira.mozilla.com/browse/FXA-2324 - we need to remove an exclamation mark from the email copy

As far as I know, #1 is already done and live.  #2 and #3 are both in the current train, set to go live next Monday (Aug 3).  I think restarting the marketing depends on how critical #3 is.  I got the impression the exclamation point had a minor effect, but we'd need to confirm with Michele.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Closing as this spawned into 3 issues which have since been resolved.
