### ISSUE TITLE
Several buttons highlighters are incorrectly displayed

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5986]
**Build**
Stage [Train 1.180.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Launch Firefox and choose a Firefox user that has already a recovery key enabled.
2. Go to Sign In Page and tap on "Forget password?".
3. Insert the email and click on "Begin reset".
4. Go to email and tap on "Create new password".
5. Click on "Don't have a recovery key?" button.

**Expected results**
”Don't have a recovery key?” button is correctly displayed.

**Actual Results**
“Don't have a recovery key?” button highlighter is displayed over the “Confirm recovery key” button. 

**Additional notes**
Same issue is encountered for: 
 - “Remember password? Sign in” button from “Create new password” page. 
 - “Continue to my account” button from “Your password has been reset” page.
![Screenshot_15](https://user-images.githubusercontent.com/18114210/87936480-8ea2d880-ca9b-11ea-8006-43bcfc9156e9.png)
![Screenshot_16](https://user-images.githubusercontent.com/18114210/87936491-906c9c00-ca9b-11ea-8244-33d3726a5d7a.png)
![Screenshot_17](https://user-images.githubusercontent.com/18114210/87936493-92365f80-ca9b-11ea-8050-5998220596bb.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2309)
┆Issue Number: FXA-2309

**Comment by byrw** [comment]
can I work on this?

**Comment by clouserw** [comment]
Sure.  Thanks

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Windows 10 64-bit. All the account recovery buttons are correctly displayed. 

![Screenshot_22](https://user-images.githubusercontent.com/18114210/88546570-40ef1880-d025-11ea-8073-8c7715955d30.png)
![Screenshot_23](https://user-images.githubusercontent.com/18114210/88546573-42204580-d025-11ea-942b-4afb6fe51feb.png)
![Screenshot_24](https://user-images.githubusercontent.com/18114210/88546576-43517280-d025-11ea-9eed-4220a12f0ea0.png)
