### ISSUE TITLE
Track completed logins via device pairing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5990]
**Context**
We are not tracking successful logins done via device pairing. As a result, when device pairing landed on iOS via the FxA Rust component, we started to measure less logins (though we would expect more).

Fenix also has device pairing capabilities and we have the same inability to measure successful logins.

There are already a few issues open on this topic but they all seem much broader which is why none of them likely moved forward. See:

* FXA-232
* FXA-333
* FXA-525

**Request**
Trigger a `fxa_login - complete` event when someone successfully authenticates via device pairing.

Based on the proposed "Change 2" of FXA-333, we should add the event property `login_type` where the value is `qr`.

Fenix is going to production in 2 weeks and so, as of then, we will not be efficiently tracking all of our mobile logins across both platforms.

**Other resources**
Here is a Fenix dashboard to look at pairing (using Fenix client-side telemetry):
https://analytics.amplitude.com/mozilla-corp/dashboard/doctj72

Here is a Firefox for iOS dashboard to look at pairing (using iOS client-side telemetry):
https://analytics.amplitude.com/mozilla-corp/dashboard/3xlucrd

We have some events leading up to a successful pairing like a view of the call to action to pair:
https://analytics.amplitude.com/mozilla-corp/chart/new/174s8yd

**Warning**
Don't get confused with all of the `fxa_qr_connect_device - ` events already in fxa telemetry. Those are mostly all related to the connect another device experiment.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2311)
┆Issue Number: FXA-2311

**Comment by vbudhram** [comment]
We are correctly tracking the login metric, however it not logging the associated service with it.

Ref: https://analytics.amplitude.com/mozilla-corp/chart/zxg4h0g

**Comment by davismtl** [comment]
@vbudhram things are looking better but there is some uncertainty because we're not 100% sure if the logins we're observing are from QR because per request above, this part was not done:
> add the event property login_type where the value is qr.

Can we add the `login_type`?

**Comment by davismtl** [comment]
@vbudhram did you ever add the login_type?

**Comment by vbudhram** [comment]
> @vbudhram did you ever add the login_type?

No that wasn't added. Lets reopen this issue verses the other one since it has more info.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Closing this because we won't be using amplitude as much.
