### ISSUE TITLE
Submit AET pings to the data pipeline via HTTP

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5998]
In FXA-1885, we planned to submit AET pings to the data pipeline by logging the events, then asking the data team (in bug [https://bugzilla.mozilla.org/show_bug.cgi?id=1653654](https://bugzilla.mozilla.org/show_bug.cgi?id=1653654)) to set up an ETL transform to route the pings into the correct AET bucket.

The data folks would prefer we submit AET pings either through the HTTP ingestion edge, or directly into a PubSub topic they can provision.

This bug captures work to back out the previous metrics ping and add the POST to the ingestion edge.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2321)
┆Issue Number: FXA-2321

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

Work in progress pr here https://github.com/mozilla/fxa/pull/6061

**Comment by 6a68** [comment]
Per continued conversations with ops, particularly https://bugzilla.mozilla.org/show_bug.cgi?id=1653654#c5, it looks like we actually don't want to switch from logging to HTTP. Hence, there's no work to do here. Closing. Thanks for the PR @meandavejustice, sorry for the back-and-forth on this issue.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Per ops feedback in https://bugzilla.mozilla.org/show_bug.cgi?id=1653654#c5, ( https://bugzilla.mozilla.org/show_bug.cgi?id=1653654#c5, ) we are going to stick with the already-completed approach of logging the events, then handling the submission to AET on the backend, rather than switching to logging via HTTP, the work this bug was intended to capture.
