### ISSUE TITLE
Unhandled Stripe event received.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#6003]
https://sentry.prod.mozaws.net/operations/auth-stage/issues/7276374/?referrer=github_plugin

```
Unhandled Stripe event received.
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2326)
┆Issue Number: FXA-2326

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Looks like this is because we don't handle customer.deleted events. The webhook was setup incorrectly, I'm removing this event from the webhook so it won't be sent.
