### ISSUE TITLE
New emailRecord_5 stored procedure is much slower than emailRecord_4

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6006]
When @jrgm deployed Train 180 to production we encountered 100% CPU on the RDS database immediately. After rolling back to Train 179 he had to manually kill some queries that were still running after the instances were terminated. After restoring service, we looked at Performance Insights and found significant waits and 30M rows/second being queried, which smelled like a query doing table scans instead of using an index. When @jrgm and I manually ran `CALL emailRecord('jbuckley@mozilla.com');` we found that it took >5 seconds to return results. When running the query inside the stored procedure it ran fine. So, something about the stored procedure was de-optimizing the query. @bbangert suggested duplicating `emailRecord_5` and adding an `EXPLAIN` to the `SELECT` statement to verify this behaviour and we found that it was indeed doing a table scan instead of using the index:

```
MySQL [fxa]> CALL emailRecord_5_explain('jbuckley@mozilla.com');
+----+-------------+-------+------+---------------+------+---------+------+-----------+-------------+
| id | select_type | table | type | possible_keys | key  | key_len | ref  | rows      | Extra       |
+----+-------------+-------+------+---------------+------+---------+------+-----------+-------------+
|  1 | SIMPLE      | a     | ALL  | NULL          | NULL | NULL    | NULL | 116557655 | Using where |
+----+-------------+-------+------+---------------+------+---------+------+-----------+-------------+
1 row in set (0.01 sec)
```

After some googling, I found [a blog post from 2013](https://lowleveldesign.org/2013/07/19/diagnosing-collation-issue-mysql-stored-procedure/) saying that procedure character sets and table index character sets need to match otherwise it'll be a table scan.

My suggested fix is that we should drop stored procedures like they're hot, and use queries like we do everywhere else.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2329)
┆Issue Number: FXA-2329

**Comment by rfk** [comment]
For completeness, we do have a linting tool that complains about this issue:

```
$> npm run migration-lint

> fxa-auth-db-mysql@1.180.0 migration-lint /Users/rfk/repos/mozilla/fxa/packages/fxa-auth-db-mysql
> node scripts/migration-lint

Warning: expected "utf8 COLLATE utf8_bin" for inNormalizedEmail in createAccount_8!
IN `inNormalizedEmail` VARCHAR(255),

Warning: expected "utf8 COLLATE utf8_bin" for inEmail in createAccount_8!
IN `inEmail` VARCHAR(255),

Warning: expected "utf8 COLLATE utf8_bin" for inEmail in emailRecord_5!
IN `inEmail` VARCHAR(255)
```

But I don't see anything that would run it manually, so it may as well not exist :-(

We might want to checkout `createAccount_8` while we're here as well...

> My suggested fix is that we should drop stored procedures like they're hot, and use queries like we do everywhere else.

💯 they have been nothing but trouble in practice.

**Comment by 6a68** [comment]
I would also like to remove the stored procedures. I'll open a new bug for that

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Fixed by https://github.com/mozilla/fxa/pull/6012
