### ISSUE TITLE
email first flow does not check for common errors in the domain

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#601]
mailcheck is hooked up in the legacy /signup page, but not in email-first

blocks #6125

**Comment by shane-tomlinson** [comment]
On the legacy signup page adding mailcheck was straight forward because the user had to enter their email address and password on the same page. As soon as the user blurred the email address to enter the password, we'd check the domain name. With email-first, where the email address is the only input element, this isn't so straight forward.

I propose we treat it like this:

1. If an email address falls afoul of mailcheck, block submit once.
2. If the email address hasn't changed and the user submits again or dismisses the tooltip, allow the submit.
3. If the email address has changed, go check it again.

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
In other words, show this on form submission if mailcheck is tripped…
<img width="433" alt="image" src="https://user-images.githubusercontent.com/68213/68135535-d1af2280-fef1-11e9-8c85-fb8aa8f768fc.png">

That makes sense.

Longer term we should suggest email providers in a dropdown, though some may find that creepy.

**Comment by shane-tomlinson** [comment]
> Longer term we should suggest email providers in a dropdown, though some may find that creepy.

@davismtl filed #3197 about just that.

**Comment by davismtl** [comment]
> Longer term we should suggest email providers in a dropdown, though some may find that creepy.

I have found it very helpful when I experienced an autocomplete of the domain.
