### ISSUE TITLE
[auth-server][stripe] Remove old Source/Payment Method when setting new default payment method

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6041]
We allow customers to update their payment information, but we should also remove the previous Source (pre-SCA customers) or Payment Method.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2348)
┆Issue Number: FXA-2348

**Comment by 6a68** [comment]
Closed by #6232.
