### ISSUE TITLE
Subscription upgrade cannot be done

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6046]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.181.0

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with an active subscription for 123Done… Pro product;

 #### Steps to reproduce:
1. Load https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM  page in the same browser session as the one from prerequisites;
2. Check the authorization box and click the “Confirm upgrade” button;

#### Expected result:
- Subscription upgrade is finalized with success.

#### Actual result:
- “Plan update failed. An internal server error occurred” message is displayed and subscription upgrade cannot be made.

#### Notes:
- We suspect the issue is because of the different currencies;
![upgrade](https://user-images.githubusercontent.com/15685960/88544449-10f24600-d022-11ea-98dd-c07540a529a0.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2351)
┆Issue Number: FXA-2351

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I can confirm this is due to different currencies. My recommended fix is that we should reflect the error better, to indicate to the user that they cannot pay in two different currencies.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Another option would be to prevent people from choosing to upgrade products offered in two different currencies.  [~jgruen@mozilla.com]  please advise

**Comment by chenba** [comment]
I can see in the screenshot that the upgrade is from USD to MYR; that will not work.  This is a Stripe product configuration issue.

**Comment by ValentinaPC** [comment]
This issue was fixed when we added the multiple currency options for 123Done product.
