### ISSUE TITLE
The user is not automatically connected after changing the password

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6047]
**Build**
Stage [Train 1.181.0]

**Affected platforms**
Windows 10

**Steps to reproduce**
1. Go to Sign In Page and click on "Forget password?".
2. Insert the email and click on "Begin reset".
3. Go to email and click on "Create new password".
4. Create a new password.

**Expected results**
The user is automatically connected.

**Actual Results**
“Reconnect to Firefox Account” yellow message is displayed.

![issue6](https://user-images.githubusercontent.com/18114210/88564408-db5a5680-d03b-11ea-9e10-be2fa209330c.gif)

**Additional notes**
This issue is not reproducible in Prod [Train 1.180.1]

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2352)
┆Issue Number: FXA-2352

**Comment by vbudhram** [comment]
@vasilicatamas Thanks for finding this. It is related to the ecosystemAnonId parts we are adding.

<img width="370" alt="Screen Shot 2020-07-27 at 3 38 08 PM" src="https://user-images.githubusercontent.com/1295288/88584244-5bbe8e80-d01f-11ea-8cd6-8ab14faa0e86.png">

The browser is attempting to fetch keys, however the token to fetch them has already been used and the browser is complaining.

**Comment by clouserw** [comment]
@vbudhram I think we can close this?

**Comment by vasilicatamas** [comment]
This issue was verified as fixed on Prod [Train 1.181.2] under Windows 10 64-bit. But the user seems to not be automatically connected on mobile devices after resetting the password, issue tracked in a separate bug #6072.  Based on this I am setting the Verified label.

![issue8](https://user-images.githubusercontent.com/18114210/88816041-a75e6d00-d1c4-11ea-8d93-1b11bc9be642.gif)
