### ISSUE TITLE
Remove `style` param from /session/verify_code endpoint

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#6058]
This param is a left over from the trailhead experiment. It should be safe to remove in frontend and backend.

https://github.com/mozilla/fxa/blob/9f03c12e9e3ea2abe107f397256a5b390c38854d/packages/fxa-auth-server/lib/routes/session.js#L332

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2357)
┆Issue Number: FXA-2357

**Comment by byrw** [comment]
can I work on it?

**Comment by Yashs911** [comment]
Hi, @vbudhram can I work on this?
