### ISSUE TITLE
Account recovery: doorhanger displayed to update the password when tapping on "Cancel"

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#606]
Environment:
Win10
Stage server - Train 119

Steps to reproduce:
1. Go to Manage account->Account recovery->Enable;
2. Tap on "Generate";
3. On re-enter password modal tap on "Cancel".

Actual results: a door-hanger is displayed to update the password after the modal is dismissed. 

Expected results: no doorhanger is displayed since the password is the same. 

![2018_08_24_10_40_37_firefox_accounts_account_recovery_firefox_nightly](https://user-images.githubusercontent.com/24588037/44571726-48974a00-a78a-11e8-8acc-aa7234b2f3f3.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-742)
┆Issue Number: FXA-742

**Comment by jodyheavener** [comment]
I think this is related to https://github.com/mozilla/fxa/issues/876 and https://github.com/mozilla/fxa/issues/932

**Comment by byrw** [comment]
I have a solution for this issue. Can I create a PR for it?
