### ISSUE TITLE
upgrade node-convict

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#608]
Happened to notice this was at convict@1.5.0, which is <<< 4.3.2, the current version.

blocked by mozilla/node-convict#271

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-744)
┆Issue Number: FXA-744

**Comment by A-312** [comment]
mozilla/node-convict#271 will be fixed in the next update of convict (6.0.0).
