### ISSUE TITLE
Email-first sign in avatar is always the placeholder

### ISSUE THREAD

**Issue by devinreams** [mozilla/fxa#609]
I have been testing with multiple accounts and when going through the email-first flow, the next screen (where it knows its an existing account and should enter password) always has the placeholder avatar, not my actual face or icon that I've uploaded:

Expected (multicolor Apple icon for `dreams+appletest@mozilla.com`):

<img width="528" alt="screen shot 2018-08-02 at 9 39 08 am" src="https://user-images.githubusercontent.com/49511/43594645-fd912df4-9637-11e8-90f8-edcd1b2a0efa.png">

Actual (placeholder default avatar icon):

![img_0014](https://user-images.githubusercontent.com/49511/43594574-cbaf5018-9637-11e8-9147-cc4216d869ee.png)

**Comment by shane-tomlinson** [comment]
Closing this as a wontfix, but we do need to discuss how to make signin easier across multiple services.
