### ISSUE TITLE
“Subscriptions” option from Manage Account page disappears in aprox 10 minutes after a subscription

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6097]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.182.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account;

 #### Steps to reproduce:
1. Load https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn page;
2. Click on the “Try Mozilla VPN” button;
3. Finalize subscription and click “Continue to download” button;
4. Click on the “Manage account” option from page header user menu;
5. Wait around 10 minutes;
6. Access the “Manage Account” page;
7. Observe the “Subscriptions” option;

#### Expected result:
- “Subscriptions” option is listed. User can click it and be redirected to the “Subscriptions” page.

#### Actual result:
- “Subscriptions” option disappears. 

#### Notes:
- Sign in out/in does not fix the problem.
- Making a “cancel subscription” action in the Subscription page (accessed from Mozilla VPN page - user menu - Manage subscriptions) will make the option reappear in manage account page.
![disap](https://user-images.githubusercontent.com/15685960/89031255-d4cd2700-d33a-11ea-9ff9-161e999f7577.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2369)
┆Issue Number: FXA-2369

**Comment by lmorchard** [comment]
Lending a hand here on this one. Can reproduce locally and digging into things.

**Comment by lmorchard** [comment]
Looks like this is a larger issue than just the button disappearing. The appearance of the button relies on the existence of cached Customer data. However, the appearance of subscription capabilities provisioning customer access to paid products **also** relies on the same data. So, problems with this button are tied to problems with accessing paid products.

I *think* I tracked it down to how we're using our new caching library. We set a global cache expiration time, whereas before we only set expiration TTL for plans & products data. Customers are (currently) meant to stay cached indefinitely. Instead, they're getting a redis TTL of 600 seconds.

**Comment by clouserw** [comment]
Thanks for the patch!  We're going to push this to stage today.  @ValentinaPC please double check this on stage and we can push it live tomorrow

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

FWIW, I can no longer reproduce this issue on local dev or stage. Probably want further confirmation on the fix, though, since I wrote the patch. 😅

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx79 and Windows 10 (64-bit).
The Subscription button from Manage Account page does not disappears.

We should mention here that the issue is **still reproducible for old accounts** (from yesterday). Different from the initial scenario, is that for old accounts the "Manage Subscription" option from user menu, also disappears.  Not sure if this was in scope to be fixed or not.
See below screenshots.
![10min](https://user-images.githubusercontent.com/15685960/89407338-4801df00-d727-11ea-9059-92fd77e3ec29.png)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

{quote}We should mention here that the issue is still reproducible for old accounts{quote}

By "still reproducible", do you mean the whole process of steps to reproduce? i.e. when you subscribe to a new subscription with one of those old accounts, the button still disappears in 10 minutes? That would mean that we still have a bug to fix.

Or, do you mean that the old account hasn't had the button reappear? If that's the case, then that's the expected outcome - because we can't automatically undo cache expiration of customer data.

If you tried cancelling & reactivating a subscription with an old account, the button should reappear and stay there past 10 minutes. That change in subscription status restores customer data to the cache.

**Comment by ValentinaPC** [comment]
> Or, do you mean that the old account hasn't had the button reappear? If that's the case, then that's the expected outcome - because we can't automatically undo cache expiration of customer data.

Yes, that was what I mean. :) 

> If you tried cancelling & reactivating a subscription with an old account, the button should reappear and stay there past 10 minutes. That change in subscription status restores customer data to the cache.

Yeah, that was the case, also, when the issue was found, as I noted in the initial comment. And now, after the fix, is working the same.

Marking this issue verified.
