### ISSUE TITLE
Use "protected branches" on all our repos

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#61]

**Comment by rfk** [comment]
@seanmonstar pointed these out in IRC, they sound like a very sensible precaution:

  https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by pdehaan** [comment]
For reference, here's a list of all our repos (via [/scripts/repos.txt](https://github.com/mozilla/fxa/blob/master/scripts/repos.txt)):

- [X] fxa
- [ ] fxa-auth-db-mem
- [ ] fxa-auth-db-mysql
- [ ] fxa-auth-db-server
- [ ] fxa-auth-mailer
- [ ] fxa-auth-server
- [ ] fxa-basket-proxy
- [ ] fxa-content-experiments
- [ ] fxa-content-server
- [ ] fxa-content-server-l10n
- [ ] fxa-customs-server
- [ ] fxa-dev
- [ ] fxa-js-client
- [ ] fxa-js-client-old
- [ ] fxa-jwtool
- [ ] fxa-local-dev
- [ ] fxa-notification-server
- [ ] fxa-oauth-console
- [ ] fxa-oauth-client
- [ ] fxa-oauth-server
- [ ] fxa-profile-server
- [ ] fxa-python-client
- [ ] fxa-relier-client
- [ ] hapi-fxa-oauth
- [ ] PyFxA
- [ ] fxa-easter-egg
- [ ] fxa-password-strength-checker
- [ ] browserid-verifier
- [ ] browserid-local-verify

**Comment by pdehaan** [comment]
OK, I did most of the repos listed above. I'm not sure if you want me to add them the remaining repos, or in cases like browserid-*, I don't have admin access to set the flag.

**Comment by shane-tomlinson** [comment]
@pdehaan - you are awesome. I added [fxa-checkbox](https://github.com/mozilla/fxa-checkbox) to the list.

**Comment by vladikoff** [comment]
@shane-tomlinson @rfk do you have access to modify

 browserid-verifier
 browserid-local-verify

?

cannot change settings for those, otherwise all other repos should have the master branch protected now

**Comment by rfk** [comment]
> do you have access

I do, re-opening and assigning to me to finalize those

**Comment by pdehaan** [comment]
@rfk: not sure if we want to expand admin-access to those repos (as well as [node-convict](https://github.com/mozilla/node-convict)).

**Comment by rfk** [comment]
> re-opening and assigning to me to finalize those

done

> not sure if we want to expand admin-access to those repos (as well as node-convict).

also done
