### ISSUE TITLE
404 page message should be in a `p` tag and has incorrect line-height

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#6102]
"The page you requested is not found..." text should be in a `p` tag instead of a `section` and should have a line-height of `1.5em` to match our other styles.

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/13018240/89052725-c02d6680-d31b-11ea-8659-c3b4ffa17ada.png">

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2371)
┆Issue Number: FXA-2371

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

From mtg: Contributor filed a PR for this, Lauren working on review.
