### ISSUE TITLE
Setup on the README.md

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#6111]
If you set up fxa after the README.md, is it permanent after a reboot/shutdown, or is the data all gone again and has to start from the beginning? My own setup here no longer works as it looks.  If so, is there already something to read to set up permanently?

https://github.com/mozilla/fxa/blob/main/README.md

Thank you...

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2373)
┆Issue Number: FXA-2373

**Comment by vbudhram** [comment]
From mtg: The user information is stored in mysql and should still be there on reboot. Do you mean your sync data?

**Comment by misterhsp** [comment]
I mean the sync data too.

...
