### ISSUE TITLE
Display subscription product name as service during signup / signin for payment flows

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6121]
Currently:

If i enter a subscription flow by going straight to a subscription link i see an fxa flow that tells me to continue to settings....instead we should:

* not suggest the user is looking for sync
* indicate that they are going to the specific product

Before:
!image-2020-08-03-22-19-18-931.png|width=377,height=502!

After:

!image-2020-08-03-22-20-09-318.png|width=358,height=466!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2381)
┆Issue Number: FXA-2381
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13763/image-2020-08-03-22-19-18-931.png">image-2020-08-03-22-19-18-931.png</a> | <a href="https://jira.mozilla.com/secure/attachment/13762/image-2020-08-03-22-20-09-318.png">image-2020-08-03-22-20-09-318.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~vbudhram@mozilla.com] I thought we had a URL parameter that would hint at what we service we should put there.  Am I making that up?

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~wclouser@mozilla.com] correct, the `service` param should provide a hint, or the client id. 

Since this isn't redirecting back to an RP, you will be redirected to the payment service, does it still make sense to show the RP? [~jgruen@mozilla.com]

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

So [~vbudhram@mozilla.com] if today, we add  a service param, we see the right thing? I think that covers my immediate need, but let's keep this open as it's looking increasingly likely we will be shipping bundled services where the subscription will not be for any single RP.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

[~vbudhram@mozilla.com] adding a service does not seem to do the trick here: (eg https://accounts.stage.mozaws.net/?plan=price_1H5DAuKb9q6OnNsLumpJuItR&service=notes ( https://accounts.stage.mozaws.net/?plan=price_1H5DAuKb9q6OnNsLumpJuItR&service=notes )) am i missing something

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

The status quo here is broken, if i authenticate to subscibe i should not see a generic "to continue to Settings" string...using the service makes sense for now since, but ultimately we should probably pull in the "product name" from stripe for these cases

**Comment by lmorchard** [comment]
>  I thought we had a URL parameter that would hint at what we service we should put there. Am I making that up?

I suspect the problem here is that this "service" messaging is tied to which Relying Party you're signing into.

When you're subscribing to a product, you're signing into the **payments-server** RP and not the product RP. So, that's technically the correct "service" for this flow - as currently implemented, anyway.

I think we need to add an exception for the payments-server RP: grab the plan/product from query string, hit the auth-server API for product details, display that when the user authenticates into payments-server.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

[~lorchard@mozilla.com] that's my sense as well!

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Gave this issue a new title that I think better reflects what we want at the end
