### ISSUE TITLE
Update FxA config with prod pipeline AET keys

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#6122]
AET is landing in Nightly soon, and data ops will be working to provision production AET pipeline keys this week.

This is a placeholder/reminder bug to make sure we update the AET config once those keys are available.

I've also added an item to the deploy doc for train 183 to be sure we don't miss this config change.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2382)
┆Issue Number: FXA-2382

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~jmorrison@mozilla.com] would this be done by you in train 183?

**Comment by data-sync-user** [comment]
➤ John Morrison commented:

Yes. There is a PR pending which I don't intend to land until 182 is done, so it doesn't go out with 182. Unless this should go out with 182, although I discussed with Jared already and the thought was to wait.

PR: https://github.com/mozilla-services/cloudops-deployment/pull/3980 ( https://github.com/mozilla-services/cloudops-deployment/pull/3980 )

**Comment by data-sync-user** [comment]
➤ John Morrison commented:

Actually, I checked with rfk and he asked if it could go out with 182. So I've merged my PR above and respun content-server so it will go into production with the next prod update.
