### ISSUE TITLE
Add more robust cta prop functionality to UnitRow component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6127]
from https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/UnitRow/index.tsx#L21
【 highlighted #6a9955 】// TO DO: accept a refresh button prop to use in for secondary email【 end highlighted 】
【 highlighted #6a9955 】// and recovery key, a delete icon next to secondary email, and【 end highlighted 】
【 highlighted #6a9955 】// conditionally display "disable" for two-step auth【 end highlighted 】

【 highlighted #6a9955 】This will need to be added in order to complete the rest of the panels in settings view.【 end highlighted 】

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2384)
┆Issue Number: FXA-2384

**Comment by LZoog** [comment]
Sorry for not being clear, this TODO maybe should have been removed as we have a few issues setup for these already:
* Adding a refresh button to various pieces: https://jira.mozilla.com/browse/FXA-1798
* Delete secondary email icon/functionality: https://jira.mozilla.com/browse/FXA-2372
* Two-step auth with real data: https://jira.mozilla.com/browse/FXA-1616

**Comment by LZoog** [comment]
Going to close this issue as it is a dupe, let me know if that's incorrect.
