### ISSUE TITLE
“Mozilla VPN payment failed” email received while the 3D Secure popup is triggered

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6129]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.182.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account;

 #### Steps to reproduce:
1. Load https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn page;
2. Click on the “Try Mozilla VPN” button;
3. Sign in with the account from prerequisites;
4. Change the URL by adding a “/v2” value after .net/
5. Fill all mandatory fields and click the “Pay Now” button;
6. Open you email client and check inbox;

#### Expected result:
- No email is received while the 3D secure popup is triggered.

#### Actual result:
- A “payment failed” email is received when the popup is triggered.

#### Notes:
- Also, 2 “payment failed” mails are received for each of the following actions: cancel popup and fail authentication. (maybe intended?)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2385)
┆Issue Number: FXA-2385

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Can reproduce this in both local dev and staging.

Haven't dug into code yet, but I wonder if the thing here is that we get an `invoice.payment_failed` webhook event on 3D Secure failure? If so, we should add a check whether there's actually an active subscription associated with the payment method before sending the email.

Probably hereabouts: https://github.com/mozilla/fxa/blob/ae87468aefd8c4cff82634e5f5104ac2fc14e7dc/packages/fxa-auth-server/lib/routes/subscriptions.ts#L1040

**Comment by madalincm** [comment]
After further investigation we have observed that each time the 3D secure pop-us is triggered the **Welcome to Mozilla VPN** is received by the user together with the payment failed mail.
![image](https://user-images.githubusercontent.com/15685441/89787150-a9f68600-db25-11ea-9dbf-0a5dfd85d085.png)

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx79 and Windows 10 (64-bit).
No "Mozilla VPN payment failed" email is received while triggering the 3D secure popup. Correct emails are received when expected.
