### ISSUE TITLE
Subscriptions that require 3D authentication do not support “mixed” ZIP code

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6130]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.182.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account;

 #### Steps to reproduce:
1. Load https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn page;
2. Click on the “Try Mozilla VPN” button;
3. Sign in with the account from prerequisites;
4. Change the URL by adding a “/v2” value after .net/
5. Go to ZIP code field and try to type both chars and digits in it;

#### Expected result:
- Both chars and digits are accepted.

#### Actual result:
- Chars are not accepted.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2386)
┆Issue Number: FXA-2386
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13773/Capture.PNG">Capture.PNG</a>

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

The ZIP code field in this new combined credit card field form is out of our local control - Stripe handles it completely in their iframe component.

Maybe we can this form with different locales where ZIP code formats vary? I think Stripe adapts it to requirements for each locale. May need to change language settings in the browser to make this happen

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Yeah, I can confirm that the Stripe credit card field adapts to the specific credit card number as it's entered. Translated strings are affected by locale setting, but it seems to be the credit card number itself that causes the ZIP code field to change.

For example, I used an international testing card ( https://stripe.com/docs/testing#international-cards ) from Canada - 4000 0012 4000 0000 - and the ZIP code field changed to "Postal Code" and accepted "A1A 1A1" as input 

!Capture.PNG!

**Comment by ValentinaPC** [comment]
> For example, I used an international testing card ( https://stripe.com/docs/testing#international-cards ) from Canada - 4000 0012 4000 0000 - and the ZIP code field changed to "Postal Code" and accepted "A1A 1A1" as input
@lmorchard 
Yeah, you are right. Seems like postal code and card no. are related, at least when it comes to /v2.
Because while using cards form "Basic test card numbers" Stripe section, ZIP code accepts both digits and chars.
Did not find a card that require 3D secure authentication and ZIP code with both digits and chars.
![image](https://user-images.githubusercontent.com/15685960/89393269-3b738b80-d713-11ea-86be-328ad37b9bca.png)

**Comment by lmorchard** [comment]
> Seems like postal code and card no. are related, at least when it comes to /v2.

Yeah, this should be one of the new features of the form for /v2: Stripe controls the whole "Your card" portion of the form and can do more intelligent things with the fields there. 

However, I'm not sure we fully understand everything that entails yet, so there may be further surprises like this. (Hopefully they're all good surprises!)
