### ISSUE TITLE
Subscription flow via SCA does not send out the download email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6138]
I noticed that the new SCA server-side flow for creating a subscription did not send out the download email.

Got ahead of myself and wrote the patch before filing this issue.

https://github.com/mozilla/fxa/pull/6126

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2391)
┆Issue Number: FXA-2391

**Comment by lmorchard** [comment]
https://github.com/mozilla/fxa/commit/9cdc058e5e15389966ad0718bdccdd6516c8d131

**Comment by madalincm** [comment]
I have verified this issue in stage.
The welcome mail is now sent everytime the user triggers the 3d secure pop-up window together with the failed payment mail. 
The welcome mail is still not sent after the user authenticates the payment.
![welcome failedat4dpopup](https://user-images.githubusercontent.com/15685441/89788111-4cfbcf80-db27-11ea-9bed-66615f63c5ab.gif)

This reproducible for both VPN and the Browser Extension producs.
I am reopening this issue.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I also filed FXA-2415 - we're sending the download email both too much and not enough 😅 Needs to be sent on successful payment, whether that's on the first round of the SCA flow or subsequent retries after card failure.

Currently just sending it on subscription creation, which is not quite right because SCA creates subscriptions in advance of getting a successful payment.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This was fixed as part of another issue.

**Comment by madalincm** [comment]
Verified as fixed in stage.
The download mail is successfully sent. Marking bug as verified fixed.
