### ISSUE TITLE
Support 'prompt=select_account'

### ISSUE THREAD

**Issue by hidde** [mozilla/fxa#614]
Trgigering FxA with a `prompt=select_account`parameter stops the login screen from being shown.

Steps to reproduce: 
Trigger FxA with a URL that contains `prompt=select_account` (for example by follow the steps in [auth0-custom-lock#182](https://github.com/mozilla-iam/auth0-custom-lock/issues/182))

Expected result:
FxA login window is displayed.

Actual result: 
FxA displays an error:

<img width="535" alt="Fxa Error page: Bad Request: Invalid OAuth parameter: prompt" src="https://user-images.githubusercontent.com/178782/42023815-0d7a5476-7ac1-11e8-8c93-e9c691a509ea.png">

`select_account` is a valid value for the `prompt` parameter ([spec](https://openid.net/specs/openid-connect-core-1_0.html))

The problem only exists in the staging environment that is connected to Mozilla IAM, it works as expected in production.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-747)
┆Issue Number: FXA-747

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
