### ISSUE TITLE
500 Server Error - After VPN login

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6142]
https://jira.mozilla.com/browse/PGAND-384?focusedCommentId=137514&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-137514

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2392)
┆Issue Number: FXA-2392

**Comment by madalincm** [comment]
QA team can't test this flow while in stage because the current VPN desktop app is not pointing to stage. I think we should address this so the QA team can include testing at least basic functionalities of the VPN app during the weekly train testing.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

Is it possible to get the url of the page while it throws the error? Also who would be able to get a build of VPN pointing to FxA stage. cc [~rrosario@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Ricky Rosario commented:

[~cmore@mozilla.com] [~vchen@mozilla.com] Did we find out who has access and is responsible for adding people to the Android and iOS staging app?

QA already knows how to point the Windows app at stage.

**Comment by data-sync-user** [comment]
➤ Chris More commented:

Android: Ryan VM

iOS: jlorenzo

I filed this issue https://jira.mozilla.com/browse/PGAND-411 for [~vchen@mozilla.com]  to document the QA process.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Marking this cancelled.  It's duplicated by PGAND-384 and that issues says it's not reproducible anymore.
