### ISSUE TITLE
about:welcome register and sign in flows are not sync optional

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6151]
**Build**
Prod [Train 1.182.2]

**Affected platforms**
Windows 10 

**Steps to reproduce**
1. Launch Firefox and navigate to about:welcome.
2. Click on ["Sign in"](https://accounts.firefox.com/?service=sync&action=email&context=fx_desktop_v3&entrypoint=activity-stream-firstrun&style=trailhead&utm_source=activity-stream&utm_campaign=firstrun&utm_medium=referral&utm_term=aboutwelcome-default-screen&device_id=e17f2433dd5a44aead5f8665aaf1445a&flow_id=cfab0b652508b308aa3f8ddee18d645ef0240aee11155387d5fb48f5e9510716&flow_begin_time=1596704334293) displayed in the top right corner.
3. Enter a valid email address which is not associated with a Firefox account and click "Continue".
4. Fill with a valid password and uncheck all the sync options.
5. Finish the account creation flow.
6. Confirm the account.
7. Go to about:preferences#sync and check the sync state.

**Expected results**
Sync is disabled.

**Actual Results**
Sync is enabled.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2396)
┆Issue Number: FXA-2396

**Comment by vladikoff** [comment]
This is happening due to appended `service=sync` parameter. 

We need to patch the logic here to not append `service=sync` param when going through the UITour:

https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccountsConfig.jsm#60

https://searchfox.org/mozilla-central/source/browser/components/uitour/UITour.jsm#528

**Comment by vladikoff** [comment]
bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1657642

**Comment by mhammond** [comment]
I'm reading this bug as "sync engines were correctly offered, but after disabling them all, sync was still activated in the product". It appears @vladikoff thinks the bug is "sync engines should not have been offered at all until the user explicitly chose a 'turn on sync' option during the flow". @vasilicatamas can you please confirm or clarify?

**Comment by vasilicatamas** [comment]
> I'm reading this bug as "sync engines were correctly offered, but after disabling them all, sync was still activated in the product". It appears @vladikoff thinks the bug is "sync engines should not have been offered at all until the user explicitly chose a 'turn on sync' option during the flow". @vasilicatamas can you please confirm or clarify?

The previous behavior started from about:welcome page was as follows:
- Registration: Sync engines were offered in the “Create a Firefox” page, the same as for the account creation flow started from toolbar, hamburger menu or about:sync#preferences, but the difference was that Sync was turned Off if no sync option displayed in “Create A Firefox Account” page was selected.
- Sign in: “Would you like to sync this device to your account” page was displayed offering the option to choose whether to sync or not.

@vladikoff  Can you please confirm that the above described behavior is still valid?

**Comment by mhammond** [comment]
Thanks!

>     * but the difference was that Sync was turned Off

That's my understanding of how some flows worked too and IIUC, that was all controlled by the server (it could be controlled by the client too, but never was in desktop).

>     * Sign in: “Would you like to sync this device to your account” page was displayed offering the option to choose whether to sync or not.

I don't recall how this interacted with signin - but what I *do* know still works is that if the main URL being used for the flow *does not* include the `service=sync` param, then you get this behaviour, including for account creation. This is what Vlad is referring to as the "sync optional flow".

But it sounds like from the above that the main issue is that "Registration" point, and I agree it should work as you describe - enabling sync with no engines doesn't make any sense.
