### ISSUE TITLE
Establish cache expiration TTL for Stripe customer data

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6163]
Once we start using the DB association between FxA users and Stripe customers (FXA-2403), we can start treating Stripe customer data in Redis as disposable and subject to periodic refresh. In Redis, that's best done by setting a TTL for the data.

Maybe it can be a very long TTL - e.g. many hours? a day? a week? Whatever would strike a good balance between availability, rate limits, and staying up to date with account changes. That said, we do also force-refresh this data as part of processing Stripe webhook events around account changes and payment events.

Also seems related to / may close FXA-949 - because we'll have separate cache lifetimes for customers vs plan / product data as a natural consequence

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2404)
┆Issue Number: FXA-2404

**Comment by jackiemunroe** [comment]
For initial purposes, setting to an hour. We can increase if we see any issues with rate-limiting.
