### ISSUE TITLE
500 error received when creating a new account after deleting an existing one on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6164]
**Build**
Stage [Train 1.183.1]
Prod [Train 1.182.2]

**Affected platforms**
Windows 10 

**Steps to reproduce**
1. Login on iOS using a Firefox account.
2. Navigate to Accounts Settings and delete the account.
3. Type a new email address in order to create a new account on the page that is displayed.
4. Click “Continue” button.

**Expected results**
“Create a Firefox Account” form is successfully displayed.

**Actual Results**
500 error is received - [500 error.txt](https://github.com/mozilla/fxa/files/5041575/500.error.txt)

**Additional notes**
- This issue is not reproducible when signing in using an existing account after deleting another one
- This issue is also reproducible in production.

![issue10](https://user-images.githubusercontent.com/18114210/89649595-b67ea280-d8c9-11ea-82db-5ca2d0b3b004.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2406)
┆Issue Number: FXA-2406

**Comment by vladikoff** [comment]
Error text:
```
_getOfferedEngines@https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/app.bundle.en_US.js:9:258315
setInitialContext@https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/app.bundle.en_US.js:9:258054
https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/appDependencies.bundle.js:20:101114
forEach@[native code]
https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/appDependencies.bundle.js:36:10664
https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/appDependencies.bundle.js:36:22473
https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/appDependencies.bundle.js:20:101071
getContext@https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/app.bundle.en_US.js:1:29836
renderTemplate@https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/app.bundle.en_US.js:1:28202
https://accounts-static-2.stage.mozaws.net/bundle-971296410f1612cfd859f8f25534b7bbce7868ea/app.bundle.en_US.js:1:27830
promiseReactionJob@[native code]
```

**Comment by vasilicatamas** [comment]
> @vasilicatamas I think this is fine on the FxA side of things because we are emitting the delete account event for iOS to handle. We could raise a bug for iOS to dismiss the view controller when this happens.

Filed https://github.com/mozilla-mobile/firefox-ios/issues/7227 . Considering that this issue is separately tracked I can mark this bug as Verified fixed.
