### ISSUE TITLE
QR CAD is not displayed for all login flows

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6165]
**Build**
Stage [Train 1.183.1]

**Affected platforms**
Windows 10 

**Steps to reproduce**
1. Login using a Firefox account that has been recently connected (for which the sign-in authorization screen is not displayed) and observe the last screen displayed.
2. Login using a Firefox account that has 2FA enabled and observe the last screen displayed.

**Expected results**
QR CAD screen appears at the end of the all login flows -https://accounts.stage.mozaws.net/post_verify/cad_qr/get_started?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&service=sync

**Actual Results**
1. Pairing screen is displayed - https://accounts.stage.mozaws.net/pair?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&service=sync
2. APP Badges screen is displayed - https://accounts.stage.mozaws.net/connect_another_device?context=fx_desktop_v3&entrypoint=fxa_discoverability_native&action=email&service=sync

**Additional notes**
This issue is not reproducible for accounts that have not been used for a while and need to confirm their sign-in using the code.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2407)
┆Issue Number: FXA-2407

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~vbudhram@mozilla.com] any thoughts on this?
