### ISSUE TITLE
“Cancel” button displayed in first modal from generate recovery key flow should be a link

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6166]
**Note**
This is a follow-up issue for #3951

**Build**
Stage [Train 1.183.1]

**Affected platforms**
Windows 10 

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to Manage Account-> Account Recovery and click on “Enable...” button.
3. Click on “Generate” button.
4. Observe “Cancel” button.

**Expected results**
“Cancel” button should be a link.

**Actual Results**
“Cancel” button is displayed as a button.

![Screenshot_10](https://user-images.githubusercontent.com/18114210/89667986-c906d500-d8e5-11ea-8edd-08017b3c5c07.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2408)
┆Issue Number: FXA-2408

**Comment by LZoog** [comment]
Ah, in the PR for that issue we determined this should actually remain a button. All other instances updated should be links.

**Comment by vasilicatamas** [comment]
Thanks @LZoog ! I probably missed that! Closing this issue based on https://github.com/mozilla/fxa/pull/6021
