### ISSUE TITLE
Ensure consistent error codes for TOTP and recovery codes

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#617]
For TOTP and recovery codes, we surface errors differently for types of errors. We should update this to ensure that auth-server and content-server have consistent errnos for [TOTP](https://github.com/mozilla/fxa-content-server/blob/bf4051159e1a49feb9ca9e77dd380ef93fb4ca0e/app/scripts/lib/auth-errors.js#L460) and [recovery codes](https://github.com/mozilla/fxa-content-server/blob/bf4051159e1a49feb9ca9e77dd380ef93fb4ca0e/app/scripts/lib/auth-errors.js#L468), https://github.com/mozilla/fxa-auth-server/blob/master/lib/error.js#L67.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-750)
┆Issue Number: FXA-750

**Comment by farhan787** [comment]
@vbudhram may I make these TOTP and recovery codes `errnos` consistent ?
