### ISSUE TITLE
Subscription reactivated email does not contain the updated credit card

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#6172]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account with active subscription that uses a specific credit card.

#### Steps to reproduce
1. Open the subscription management page and update billing information (add a different card number).
2. Cancel the subscription.
3. Resubscribe .
4. Open the Subscription reactivated email.

#### Expected result:
- The email should contain the updated credit card info.

#### Actual result:
- The mail contains the old credit card number ending.

![subscriptionReactivatedEmailWrongCC](https://user-images.githubusercontent.com/15685441/73547349-666ce200-4447-11ea-9d09-1b71bad72554.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2413)
┆Issue Number: FXA-2413

**Comment by madalincm** [comment]
This issue is still reproducing. I have transferred the issue in the fxa repo for better visibility.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I can reproduce this in local development, taking a deeper look.

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

This was originally found in stage. We should remove the found in production flag.
