### ISSUE TITLE
Sign in page is still displayed after a valid recovery code is used.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/fxa#6173]
Environment:
FF 79, Win10x64, MacOS 10.15.5
Not reproducible on mobile devices

Steps to reproduce:
1. Create a new FXA user and login to Firefox 
2. From Manage Account, go through Two-step authentication process and enable it, saving the recovery codes
3. Sign out , then sign in again and press on "Trouble entering code" when you are asked for 2FA authentication
4. Enter one of the recovery codes saved at Step 3

Expected results:
User is signed in and "The firefox is connected" page is displayed

Actual results:
User is redirected to sign in page 

Please see video for this issue:
![recoverycode](https://user-images.githubusercontent.com/1583842/89790694-f7292680-db2a-11ea-870a-928702870fb7.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2414)
┆Issue Number: FXA-2414

**Comment by clouserw** [comment]
@vcarciu would you clarify -- if you click 'sign in' on the resulting page, do you successfully log in?

**Comment by vcarciu** [comment]
> 
> 
> @vcarciu would you clarify -- if you click 'sign in' on the resulting page, do you successfully log in?

If you enter the security code from auth app , yes, you are logged in, but this is wrong because we already used a recovery code in order to avoid to enter the security code from authenticator app.

**Comment by vcarciu** [comment]
Verified as fixed using FF 80, Win10x64, MacOS 10.15.5
