### ISSUE TITLE
Only send download email in SCA flow when the subscription is successful

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6175]
In FXA-2391, I found that we weren't sending the product download email at all by the end of the SCA flow.

[The patch I wrote](https://github.com/mozilla/fxa/pull/6126) now sends the download email with every attempt to process payment during the subscription creation process - that includes failed 3D Secure auth flows and invoice retries.

This should be refined to send the email only on successful payment status - and also at the end of successful invoice retry, not just initial subscription creation.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2415)
┆Issue Number: FXA-2415

**Comment by ValentinaPC** [comment]
Verified this in stage, using Fx79 and Windows 10 (64-bit).

The only thing noticed as different, is that for Mozilla VPN product, even if both mails - subscription and download - are received in the same time - the order is: Welcome (download) mail and then payment confirmation mail. The other products: Variety, 123Done have the mail order reversed.
Not sure which is the correct order, @lmorchard ?
Screenshot below.
![mails](https://user-images.githubusercontent.com/15685960/90236107-f940fd00-de2a-11ea-8097-6280b241a5a2.png)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I don't think the order is significant as long as they are both received?

**Comment by ValentinaPC** [comment]
> 
> 
> ➤ Les Orchard commented:
> 
> I don't think the order is significant as long as they are both received?

I was thinking at the fact that a user is announced to download the VPN product, before the payment confirmation mail.
And was a bit confused, because the order is one for 2 products and other for VPN product.
