### ISSUE TITLE
Signin Page touts unavailable service

### ISSUE THREAD

**Issue by RainerBielefeld** [mozilla/fxa#6188]
### Steps to reproduce

1. Visit [accounts.firefox.com/signin](https://accounts.firefox.com/signin) without being logged in
   » several mozilla services are offered including "Firefox Send"
2. After having logged in visit [blog.mozilla.org](https://blog.mozilla.org/blog/2019/03/12/introducing-firefox-send-providing-free-file-transfers-while-keeping-your-personal-information-private/) 
3. Search page for "information is safe with Send"
4. Click link "send"
   » Expected: FF Send
    Actual: Service not available  😥

    "Firefox Send" is (currently?) unavailable

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2418)
┆Issue Number: FXA-2418

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It looks like we are shutting down Send for longer term.  There are 4 things in that group, so just removing Send might look weird.  [~pwalmsley@mozilla.com] - do you have a design that would look good?  /cc [~adavis@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Maybe put in Pocket instead?
