### ISSUE TITLE
“Unverified session” error received when deleting an account logged in via pairing method

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6199]
**Build**
Stage [Train 1.184.0]

**Affected platforms**
Android 9
iOS 13.6

**Steps to reproduce**
1. Login on a desktop using a user which has 2FA enabled and navigate to https://accounts.stage.mozaws.net/pair (firefox.com/pair).
2. Login on a mobile device (Android/iOS) via pairing method.
3. On the mobile device, navigate to Settings page.
4. Delete the account.

**Expected results**
Firefox account is successfully deleted. 

**Actual Results**
“Unverified Session” error is displayed and the account is not deleted. 

**Additional notes**
This issue might be related to #4257

![Screenshot_23](https://user-images.githubusercontent.com/18114210/90255380-e5a68e00-de4c-11ea-9bc6-a25664d4292e.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2423)
┆Issue Number: FXA-2423

**Comment by vbudhram** [comment]
@vasilicatamas I don't think this is a major issue/blocker for the current train. Not a lot of users go through this flow (2FA/pair/delete account) at the moment, so we could prioritize it for next train.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.186.0] under iOS 13.6 and Android 9. The account logged in via pairing method is successfully deleted.

![issue9](https://user-images.githubusercontent.com/18114210/91577386-48ba1980-e951-11ea-8812-8fc731830269.gif)
