### ISSUE TITLE
“Enter security code” screen is displayed only on the first login on mobile devices

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6208]
**Build**
Stage [Train 1.184.0]

**Affected platforms**
Android 9
iOS 13.6

**Steps to reproduce**
1. Launch Firefox app and go to menu -> Settings -> Turn on Sync -> "Use email instead".
2. Type an email address which has 2FA enabled.
3. Enter the password
4. Enter the totp code.
5. Logout.
6. Repeat the above steps using the same Firefox account on the same device.

**Expected results**
“Enter security code” screen is displayed for each login.

**Actual Results**
“Enter security code” is no longer displayed for the next logins (except the first one) and the user is automatically connected after typing the password.

**Additional notes**
This issue is not reproducible on desktop (Windows 10 64-bit).

![issue12](https://user-images.githubusercontent.com/18114210/90384882-efb5d000-e08a-11ea-89fa-51aa37423453.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2427)
┆Issue Number: FXA-2427

**Comment by vbudhram** [comment]
@vasilicatamas Thanks for the report. This is surprising to me, but it might be possible if the session is not being correctly destroyed and the login is used the cached version.

Does this happen in production as well?

**Comment by vasilicatamas** [comment]
> Does this happen in production as well?

@vbudhram I didn’t get to check this issue on the previous production version, but I can confirm that it is reproducible in the actual 1.184.0 prod version.
