### ISSUE TITLE
Clicking the Fail button from the SCA pop-up no longer triggers a Failed payment email

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#6209]
#### Affected versions:
- All Firefox

#### Affected FxA versions:
- 1.184.0

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions:
- Existent FxA account, the user is logged in in FxA stage;

#### Steps to reproduce:
1. Use this [link ](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/v2/products/prod_FiJ42WCzZNRSbS?device_id=de08e3cecdfa4667beb21a8686c4701c&flow_begin_time=1597661722065&flow_id=f94ccaec46c8a10da3c5a54240d4b76179df21f816e006fc49b1a02545475356&plan=plan_FiJ55YK6UYftPa)to start subscription flow using /v2;
2. Fill the form correctly and enter a CC number that requires SCA;
3. Click the **Pay now** button;
4. Click the **Fail** button from the SCA pop-up window;

 #### Expected result:
- The Failed payment mail is triggered;

#### Actual result:
- The Failed payment mail is not sent;

#### Notes:
We are not sure that this is a real issue that will reproduce in production, but our testing flows in stage include testing the failed payment mail by clicking that button in the SCA pop-up window;

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2428)
┆Issue Number: FXA-2428

**Comment by lmorchard** [comment]
I don't think this is meant to send a failure email, at least not during the interaction with the subscription creation page. I think we only want to send that email on an automatic renewal.

Does the payment form show an error when fail ls clicked? If so, that's all that should happen here

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks Les.  Closing this

**Comment by madalincm** [comment]
We do show an error in the form:
![image](https://user-images.githubusercontent.com/15685441/90644362-50850a00-e23d-11ea-9e96-e658dad6340e.png)
