### ISSUE TITLE
Add suggestive error message at subscription upgrade if different currencies are used

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6215]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.184.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account;

 #### Steps to reproduce:
1. Load https://123done-stage.dev.lcip.org ;
2. Select the non-“USD” currency;
3. Fill all mandatory fields and finalize subscription;
4. In the same browser session load https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/products/prod_GVNS86uMUO3VRM 
5. Check the authorization box and “Confirm upgrade”;

#### Expected result:
- A suggestive error message is displayed informing the user about the different currencies.

#### Actual result:
- The “Plan update failed. An internal server error occurred” error message is displayed.

![image](https://user-images.githubusercontent.com/15685960/90514576-0717ba80-e16a-11ea-9df1-50ee674d814c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2430)
┆Issue Number: FXA-2430

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is happening because [~jgruen@mozilla.com]  added a non-USD currency to the staging server.  We should not have that (so CCing him here) but also closing this bug as it won't occur in production.
