### ISSUE TITLE
Add multiple currency option for “123 Done” product while signed in

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6216]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.184.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account;

 #### Steps to reproduce:
1. Load https://123done-stage.dev.lcip.org while signed in;
2. Observe the page header;

#### Expected result:
- Multiple currency options are available. (https://github.com/mozilla/fxa/issues/5736)

#### Actual result:
- Multiple currency options are NOT available.

#### Notes:
- The currency options are available only if the user is signed out.
- Signed in users will be redirected to 123Done subscription flow with MYR currency.
![123](https://user-images.githubusercontent.com/15685960/90518668-c327b400-e16f-11ea-8ceb-1d4f5a157993.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2431)
┆Issue Number: FXA-2431

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The links added in the linked ticket were only added in the logged-out view.  We should copy them so they also exist in the logged-in view.

**Comment by ValentinaPC** [comment]
@lmorchard Seems like this should already be fixed, but is not. Any idea why?
Thanks!
![image](https://user-images.githubusercontent.com/15685960/91527648-d3c5f000-e90e-11ea-92fb-ac90fb58a9c8.png)
