### ISSUE TITLE
Apple Keychain Access stores age (in place of email) when generating a password in the FxA login flow

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#6217]
## Description

When going through the FxA new account flow in Safari, the password manager (Apple Keychain Access) ends up storing the age instead of the email. This causes silent validation errors later when the user tries to sign back in because the hidden email input field on the password form gets changed to have their age instead of email. They end up stuck on the auth page with no visible validation errors (only the console shows errors).

We've had many customers filing Mozilla VPN support tickets due to this issue. We finally were able to figure out what was happening.

### Steps to reproduce

Sign up for a new FxA account in Safari and use the strong password option suggested. Once signed in, clear your recent history so all the FxA cookies are cleared. Then try to sign back in using the stored password.

See video:
https://drive.google.com/file/d/1uz1Ud1OruPmlAESZKW801vbqK_ubsPC0/view?usp=sharing

This is what ends up stored in Keychain Access (note my age instead of username/email in the Account field):
<img width="532" alt="Screen Shot 2020-08-18 at 12 01 42 PM" src="https://user-images.githubusercontent.com/36629/90537890-d1fc6f80-e14b-11ea-95e3-09c8af7620bb.png">

### Expected result

The email address should be stored in the Account field with the generated password.

### Actual result

The age is stored in the Account field with the generated password.

### Environment

Safari 13.1.2 on macOS 10.15.6

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2432)
┆Issue Number: FXA-2432

**Comment by chrismore** [comment]
@jodyheavener This bug is currently impacting growth of the Mozilla VPN as iOS users are running into this issue leading to refunds,  loss of that customers, and low app store reviews. Let me know if we could get an estimate on when this could be resolved. Thanks!

**Comment by jodyheavener** [comment]
@chrismore I have a hunch, so assuming I can get it fixed tomorrow I'll have a point release out by EOD. cc @clouserw

**Comment by chrismore** [comment]
> @chrismore I have a hunch, so assuming I can get it fixed tomorrow I'll have a point release out by EOD. cc @clouserw

Nice! Thanks so much

**Comment by jodyheavener** [comment]
Oops PR closed this. Going to re-open until fix is verified in prod.

**Comment by jodyheavener** [comment]
Working as expected for me on https://latest.dev.lcip.org/ - point release coming up tomorrow 👍

**Comment by jodyheavener** [comment]
@chrismore The point release is out and the fix works as expected on my end.

**Comment by clouserw** [comment]
Thanks @jodyheavener
