### ISSUE TITLE
Allow subscriptions to specify a list of products as support categories

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6220]
Basic idea is that with a bundle of products a user may wish to get support for an individual product within that bundle.

Let's allow metadata to specify a list of produxts that are iterated and displayed as select list on the support page and then the user choice gets added to the support request along with any other info from that form.

I can provide UX if needed here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2434)
┆Issue Number: FXA-2434
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13798/image-2020-08-21-14-40-10-045.png">image-2020-08-21-14-40-10-045.png</a>

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~jgruen@mozilla.com] should this be added to https://jira.mozilla.com/browse/FXA-2333 ?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~jgruen@mozilla.com] I'm thinking `support:app:` for the prefix on the metadata keys, e.g. `support:app:win10` -> "Mozilla VPN Windows 10".  Let me know if you have something else in mind.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Note that the app/service field will be disabled until a product where that type of metadata exists is selected.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

[~bchen@mozilla.com] answering ur comments

  1. That works for me. I would say if that metadata is not included, we can eliminate that "Do you need help with a specific app or service" piece
  2. Yeah i think that should stay, i just cut off the field in the screenshot
  3. Better to hide it i think?

**Comment by ValentinaPC** [comment]
1) The Firefox Account option was removed from "What are you contacting us about?" field.
![image](https://user-images.githubusercontent.com/15685960/93570032-12454c80-f99b-11ea-81a8-3d69866b1de5.png)
2) @chenba  Do we have a test product for which we display the extra field? I've tried: Mozilla VPN, Secure Proxy, Firefox Variety and 123 Done, without success.

**Comment by chenba** [comment]
@ValentinaPC sorry about the oversight there.  I just added three options to Mozilla VPN.  Let me know if you prefer to have them on a different product.

**Comment by ValentinaPC** [comment]
@chenba It is perfect and thanks for adding the options!
As a side note (small suggestion): you can remove the "optional" word from the section, because there is no "empty" value for that field, and an option is ALWAYS selected.

Verified as fixed in stage, using Fx80.0.1 and Windows 10 (64-bit). All options work as expected and without any issues.
Postfix screenshot below.
![extraop](https://user-images.githubusercontent.com/15685960/93741259-c1c92b80-fbf4-11ea-9dee-946c124bf181.png)

**Comment by chenba** [comment]
> As a side note (small suggestion): you can remove the "optional" word from the section, because there is no "empty" value for that field, and an option is ALWAYS selected.

Thanks.  That's actually a bug.  I'll file an issue to add an empty option so that it is optional.
