### ISSUE TITLE
Spinning wheels displayed simultaneously on two “Cancel Subscription” buttons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6234]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.184.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with 3 subscriptions;

 #### Steps to reproduce:
1. Load Subscriptions page (https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions)
2. Click on “Cancel” button for 2 of the products;
3. Check the confirmation box for both;
4. Click “Cancel Subscription” for one of them;
5. Look at both "Cancel Subscription" buttons;

#### Expected result:
- A spinning wheel is displayed on the clicked “Cancel Subscription” button.

#### Actual result:
- A spinning wheel is displayed on both “Cancel Subscription” buttons, suggesting that both subscriptions would be cancelled.

#### Notes:
- Same happening for 3 or more products.
- The subscription is canceled only for the product for which the button was clicked.
![wheel](https://user-images.githubusercontent.com/15685960/90643560-6645ff80-e23c-11ea-9ba9-0c4d664eaa95.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2442)
┆Issue Number: FXA-2442

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Guessing 3 points.

Off the top of my head, the cause is probably that we only have one Redux state here to track an in-flight cancellation API request. Should probably break away from Redux here and switch to API requests local to the component like we did in the new SCA payment flow UI. That would let each subscription item component manage its own independent API request flow.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Dropping to 3 points, since this occurred to me: Supporting multiple simultaneous cancellations is overthinking this. Best to only allow one cancellation at a time and lock out / disable all other cancellations until the first has finished. That should simplify everything.

**Comment by ValentinaPC** [comment]
@lmorchard this fix should already be on Stage, or only with the next train? Thanks!
