### ISSUE TITLE
Different focus borders for “Terms of Service” and “Privacy Notice” links from Settings page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6235]
****Build**
Prod [Train 1.184.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Login using a Firefox account and navigate to https://accounts.firefox.com/settings
2. Open the “Terms of Service” and “Privacy Notice” links in new tabs. 
3. Observe the “Terms of Service” and “Privacy Notice” focus borders. 

**Expected results**
Both links have the same focus border shape.

**Actual Results**
 “Terms of Service” and “Privacy Notice” have different focus borders shapes.

![Screenshot_44](https://user-images.githubusercontent.com/18114210/90646400-d609b980-e23f-11ea-9bed-5a04c3166849.png)
![Screenshot_45](https://user-images.githubusercontent.com/18114210/90646403-d7d37d00-e23f-11ea-90f6-d70bca624248.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2443)
┆Issue Number: FXA-2443

**Comment by byrw** [comment]
Can I work on it?

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.187.0] under Windows 10 64-bit. Both links have the same focus border shape.
![Screenshot_46](https://user-images.githubusercontent.com/18114210/92897643-0bac5780-f426-11ea-8e03-186039a8a068.png)
![Screenshot_47](https://user-images.githubusercontent.com/18114210/92897647-0c44ee00-f426-11ea-9079-de3380d72320.png)
