### ISSUE TITLE
Case where a verified session is required to get attached clients

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6240]
Steps to reproduce:

* start firefox with a new profile
* sign in to sync via the account toolbar
* you should be redirected to `/signin_token_code`
* browse to `/beta/settings`

Note that signing in to a fresh profile via _browsing_ to the signin page does _not_ trigger this behavior

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2446)
┆Issue Number: FXA-2446

**Comment by rfk** [comment]
> sign in to sync via the account toolbar

IIRC, signing in via sync sets a special `mustVerify=true` flag on the resulting session, forcing you to verify it before you can use it for *anything*.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

This is an edge-case and could potentially be kicked out of phase 2 if necessary.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Question for you [~dcoates@mozilla.com] - could this be related to the path (/beta/settings)? If so, perhaps we should kick this into the 'post-beta prep' epic to validate its necessity prior to putting time into it.

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

This is more important than the STR suggests. It's a security issue if the new settings page is reachable when it shouldn't be. The open PR for it linked through the gh issue explains it more.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Bumped to high priority per your note [~dcoates@mozilla.com] , thanks.
