### ISSUE TITLE
TOTP: Ask to verify a recovery code to complete setup

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#625]
Migrated from @davismtl's original report in https://github.com/mozilla/fxa-amplitude-send/issues/63.

-----------------

I went through the TOTP flow for Evernotes and in order to complete setup, users had to prove that they had stored their recovery codes by entering of them (which one remain valid).

I think this is a great idea and avoids any slip ups.

It would probably be useful to do this too when a user generates new codes.

<img width="581" alt="screen shot 2018-05-29 at 16 10 57" src="https://user-images.githubusercontent.com/19537086/40690633-adb7c026-635c-11e8-9618-e9fc1c00796a.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-756)
┆Issue Number: FXA-756

**Comment by davismtl** [comment]
Let's prioritize this after we land want we need to in Fx 68. It seems to be very necessary.
