### ISSUE TITLE
[Newsletter Subscriptions] Sign in page is displayed after clicking on “Subscribe” or “Maybe later”

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6255]
**Build**
Prod [Train 1.184.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Launch Firefox and click the sign-up from FF toolbar menu.
2. Append ‘&forceExperiment=newsletterSync&forceExperimentGroup=new-copy’ or ‘&forceExperiment=newsletterSync&forceExperimentGroup=trailhead-copy’ and refresh the page.
3. Complete the sign-up process. 
4. Click on “Subscribe” or “Maybe later” buttons displayed in the newsletter screen.

**Expected results**
App Badges screen is displayed.

**Actual Results**
The user is redirected to Sign in page, even if the account is already connected. 

![issue13](https://user-images.githubusercontent.com/18114210/90766044-9a302c00-e2f3-11ea-9646-ab02717028b9.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2453)
┆Issue Number: FXA-2453

**Comment by vbudhram** [comment]
Hey @vasilicatamas, I've tried to replicate this locally and in production but was not able to. Can you reproduce this but show the network requests being sent?

In your screen capture, the url changes to `/pair` but then redirects to the sign-in page. The pairing page requires you to be signed in so its possible that the account hasn't been marked verified yet.

**Comment by vasilicatamas** [comment]
I can constantly reproduce this issue. The user is successfully connected and all the FxA related actions are fully functional. The only problem is the "Sign in" screen that is displayed instead of App Badges screen.

![Screenshot_22](https://user-images.githubusercontent.com/18114210/91884634-13823400-ec8f-11ea-9b00-2db8248b598d.png)

**Comment by vasilicatamas** [comment]
Tested on FxA Stage [Train 1.187.0] under Windows 10 64-bit and noticed the following:
- For Control - appears the App badges screen
- For Treatment new copy and Treatment trailhead appears the Pairing screen

![issue7](https://user-images.githubusercontent.com/18114210/92895022-cc7d0700-f423-11ea-9e37-bb41ef6b75f3.gif)

@vbudhram Can you please confirm that this is the expected behavior?
