### ISSUE TITLE
[Newsletter Subscriptions] “Subscribe” and “Maybe later” buttons do nothing on Fenix

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6256]
**Build**
Prod [Train 1.184.0]

**Affected platforms**
Android 9

**Steps to reproduce**
1. Launch Firefox app and go to menu -> Settings -> Turn on Sync -> "Use email instead".
2. Click on 3 dots menu from the bottom right corner and select “Open in Firefox”option.
3. Append ‘&forceExperiment=newsletterSync&forceExperimentGroup=new-copy’ or ‘&forceExperiment=newsletterSync&forceExperimentGroup=trailhead-copy’ and refresh the page.
3. Complete the sign-up process. 
4. Click on “Subscribe” or “Maybe later” buttons displayed on the newsletter screen.

**Expected results**
The user is redirected to the Settings menu.

**Actual Results**
Nothing happens when tapping on “Subscribe” and “Maybe” later buttons.

![issue12](https://user-images.githubusercontent.com/18114210/90767327-af0dbf00-e2f5-11ea-95bd-98430cef3026.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2454)
┆Issue Number: FXA-2454

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This experiment won't be enabled on mobile so closing the mobile bugs.  Thanks for checking.
