### ISSUE TITLE
[Newsletter Subscriptions] “Subscribe” button is enabled even if no option is selected

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6257]
**Build**
Prod [Train 1.184.1]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Launch Firefox and click the sign-up from FF toolbar menu.
2. Append ‘&forceExperiment=newsletterSync&forceExperimentGroup=new-copy’ or ‘&forceExperiment=newsletterSync&forceExperimentGroup=trailhead-copy’ and refresh the page.
3. Complete the sign-up process. 
4. While on the Newsletter screen, leave all the options unselected and click on the “Subscribe” button.

**Expected results**
a) All 3 checkboxes are checked by default (the users can deselect the ones they are not interested in)
b) “Subscribe” button is disabled until at least one option is selected.
c) An error message is displayed when clicking on the “Subscribe” button, stating that no option has been selected.

**Actual Results**
“Subscribe” button is clickable even if there are no options selected.

![issue14](https://user-images.githubusercontent.com/18114210/90778193-05362e80-e305-11ea-8a51-64d39d6d23aa.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2455)
┆Issue Number: FXA-2455

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This experiment won't be enabled on mobile so closing the mobile bugs.  Thanks for checking.

**Comment by vasilicatamas** [comment]
> ➤ Wil Clouser commented:
> This experiment won't be enabled on mobile so closing the mobile bugs.  Thanks for checking.

@clouserw This issue reproduces on Desktop - Windows 10 x64 - this can be seen in the attached video. Sorry for the confusion! updated the Affected Platforms section.

**Comment by vasilicatamas** [comment]
This issue was verified as fixed on FxA Stage [Train 1.187.0] under Windows 10 64-bit. “Subscribe” button is successfully disabled until at least one option is selected.

![issue5](https://user-images.githubusercontent.com/18114210/92892977-efa6b700-f421-11ea-8347-41bc142918b6.gif)
