### ISSUE TITLE
[Newsletter Subscriptions] Subscription options are not displayed on several locales

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6258]
**Build**
Prod [Train 1.184.1]

**Affected platforms**
Windows 10 x64

**Affected locals**
Arabic 
Portuguese 
Italian 
Turkish 

**Steps to reproduce**
1. Launch Firefox and click the sign-up from FF toolbar menu.
2. Append ‘&forceExperiment=newsletterSync&forceExperimentGroup=new-copy’ or ‘&forceExperiment=newsletterSync&forceExperimentGroup=trailhead-copy’ and refresh the page.
3. Complete the sign-up process. 
4. Observe the newsletter screen.

**Expected results**
The Newsletter Subscriptions screen is correctly displayed.

**Actual Results**
Subscription options are not displayed.

![Screenshot_7](https://user-images.githubusercontent.com/18114210/90779538-9fe33d00-e306-11ea-938b-72d439582afd.png)
![Screenshot_8](https://user-images.githubusercontent.com/18114210/90779465-89d57c80-e306-11ea-986b-0acccea583dc.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2456)
┆Issue Number: FXA-2456

**Comment by vasilicatamas** [comment]
Considering that these locals are not eligible to be enrolled in the experiment we can drop the severity to minor.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

As noted in comment 1, this experiment is not available in those locales.
