### ISSUE TITLE
Update payment details of a 3D Secure subscription is not possible using the normal flow

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6280]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.185.1;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with an active “3D Secure” subscription;

 #### Steps to reproduce:
1. Load Subscriptions page  -https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions ;
2. Click on “Change” button;
3. Enter new payment details (without adding a “/v2” value after .net/ in the URL bar) ;
4. Click on “Update” button;

#### Expected result:
- The  payment details are updated.

#### Actual result:
- The payment details appear to be saved, but they are not updated.

#### Notes:
- we should either update payment details or inform the user that it is not possible.
- NOT reproducing if we start with “normal flow” and choose to update using “3D Secure flow”;
![3d-to-normal](https://user-images.githubusercontent.com/15685960/91023112-cd7a0000-e5fe-11ea-9448-0cb2cab02595.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2469)
┆Issue Number: FXA-2469

**Comment by lmorchard** [comment]
I think this is working as expected: Users should be able to go from the v1 legacy flow to the new v2 SCA flow - but we do not have plans to support managing v2 payments from v1 flows. When SCA feature is launched, it will replace the current flow and the v1 flow will no longer be available.
