### ISSUE TITLE
A “normal” subscription is not possible if a “3D Secured” subscription was made before

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6281]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.185.1;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with an active “3D Secure” subscription for Mozilla VPN product;

 #### Steps to reproduce:
1. Load FPN Page  https://stage-browser.guardian.nonprod.cloudops.mozgcp.net/;
2. Click on “Subscribe for $2.99/month” button;
3.Complete all mandatory fields using a normal subscription flow (without adding a “/v2” value after .net/ in the URL bar) ;
4. Click on “Pay now” button;

#### Expected result:
- The  payment is finalized with success.

#### Actual result:
- The “Payment method failed” message is displayed and subscription cannot be finalized.

#### Notes:
- Reproducing while using all products;
- NOT reproducing vice versa:  have a subscription for a product using a normal flow and try another subscription, for different products using a 3D Secure flow.
![normal after 3d](https://user-images.githubusercontent.com/15685960/91026601-a40fa300-e603-11ea-8188-c9308655bff9.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2470)
┆Issue Number: FXA-2470

**Comment by lmorchard** [comment]
I don't think it's expected that this should work. Users should be able to move from using the legacy v1 payment flows to the new SCA v2 payment flows. We do not plan to support going from v2 to v1. We will replace v1 with v2 when SCA is fully launched.
