### ISSUE TITLE
Sentry reports our RavenJS is out of date.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#629]
<img width="572" alt="screen shot 2018-05-22 at 11 02 34" src="https://user-images.githubusercontent.com/848085/40355950-ac931392-5daf-11e8-9545-f29f3760f796.png">

**Comment by clouserw** [comment]
I don't see this since @meandavejustice upgraded our sentry versions

**Comment by vladikoff** [comment]
Yay!
