### ISSUE TITLE
Planning and work breakdown for OpenID Connect

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#63]

**Comment by vladikoff** [comment]
@seanmonstar @rfk @dannycoates to meet to generate bugs...

**Comment by rfk** [comment]
> meet to generate bugs...

We met, ongoing notes in [1].  Rather than generating a bunch of right away, the outcome for this work may be a backend-y version of the "feature requirements" documentation that we've been trying out for the devices work (#64, #66).

[1] https://public.etherpad-mozilla.org/p/fxa-openid-connect
