### ISSUE TITLE
Sentry Error: Unexpected error at getPermissionsWithValues

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#630]
See https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/4344112/events/21564016/

> Error: Unexpected error
  at Error(./lib/errors.js:125:44)
  at getPermissionsWithValues(./models/reliers/oauth.js:298:16)

> url: https://accounts.firefox.com/settings

**Comment by clouserw** [comment]
I'm not seeing this error anymore in Sentry.  Reopen if this is still an issue
