### ISSUE TITLE
Validate password & vpassword inline instead of on form submit

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#631]
Blocks https://github.com/mozilla/fxa-content-server/issues/6083

I suspect this could be handled on #vpassword blur. 

Other changes:
* Highlight both fields
* Attach the tooltip to the first field.

<img width="375" alt="screen shot 2018-05-21 at 14 43 53" src="https://user-images.githubusercontent.com/848085/40310656-685f3c0a-5d05-11e8-8052-ff3ddb64d97e.png">

**Comment by farhan787** [comment]
@shane-tomlinson is this issue still exist ?

**Comment by shane-tomlinson** [comment]
@ryanfeeley what are your thoughts here? Worthwhile? At a minimum, I think we should use a tooltip rather than putting the "invalid password" as an error message at the top of the screen.

**Comment by shane-tomlinson** [comment]
Note, any implementation of this will need to have some smarts so that it doesn't appear too janky, i.e., the password mismatch tooltip should not appear until after the user has been given an opportunity to type the vpassword and they have stopped typing.

**Comment by clouserw** [comment]
Whoever looks at this, please let us know what strings already exist for this code.  We may not have time for more L10n

**Comment by davismtl** [comment]
@vbudhram started this. There are still some updates to come.

**Comment by chenba** [comment]
I just experienced this locally, and it was not ideal.  After confidently typing in an incorrect password, tabbed to the age field, started typing in a number, the validation changed the focus, and I was unknowingly typing in the confirm password field for a moment before realizing what's happened.

Maybe it should not change the focused element?

@vbudhram imma re-open this.

**Comment by vbudhram** [comment]
> Maybe it should not change the focused element?

Heh I thought the experience was a little better when it refocused the element, but that was also because I was going through the flow a lot. I think this might be a new issue and warrant further discussion since we will probably want the same behavior when the user enters the first password and it doesn't meet the requirements.

@davismtl Thoughts?

**Comment by shane-tomlinson** [comment]
> Maybe it should not change the focused element?

I was told by that repeatedly changing focused elements is bad for accessibility since a screen reader user will try to tab into the tooltip to read the error message and focus will be pulled back into the input element, causing the user to be unable to read the tooltip.

**Comment by davismtl** [comment]
Based on feedback from @chenba and @shane-tomlinson, let's not refocus the password field. The inline-validation is already a good start.

This also makes me wonder about our work in https://github.com/mozilla/fxa/issues/3051
where we plan to keep the focus on the first password field until conditions are met. CC @LZoog

**Comment by LZoog** [comment]
@davismtl Yeah, after reading the comments here it kind of reaffirms my thinking that personally, I think it may be a better experience to avoid jumping focus around in #3051. I know that while signing up for something I have entered an invalid password in the first field, tabbed to repeat password and saw the first password didn't meet criteria, corrected the mistake in "repeat password" and then tabbed back to the first field. I'm not sure how common that is, but users may tab to get to "repeat password" and just not realize that they've been redirected back to the first field until they've typed a few more characters, especially if someone doesn't have great vision or looks at the keyboard to type, and I am curious how it affects screenreaders.

**Comment by davismtl** [comment]
Vijay is reviewing to remove the focusing of the field.

**Comment by mirunacurtean** [comment]
Verified this on Desktop on Windows 10 64-bit and on Android 8.0.0 on FF Stage [Train 1.151.0]. 

On Desktop the password fields are highlighted when entering the passwords for the first time however the password tooltip is not displayed above the first field. Also after editing the passwords, even if the passwords do not match, the first password field is no longer highlighted. 
![Desktop Pwd fields](https://user-images.githubusercontent.com/53306802/69819664-120b7300-1208-11ea-8783-7b1436f01da0.gif)


On Android it does not seem like the first field is highlighted at all in the process and again, the toolip is displayed above the second password field. 
![Passwords do no match Android](https://user-images.githubusercontent.com/53306802/69819766-3d8e5d80-1208-11ea-9005-624ee155a13b.jpg)

Based on this not matching the expected results from the first comment screenshot I am reopening this issue.

**Comment by mirunacurtean** [comment]
Taking a look again at this issue it became clearer that the expected result had changed throughout the process and ultimately what should have been verified was that:
1. The Repeat password field is highlighted if the passwords do not match. 
2. This should only occur after the user has stopped typing. 
3. The "Passwords do not match" tooltip location is still located around the Repeat password field. 
4. When the "passwords do not match" detection occurs, if the user has already reached the following field, the focus should not be changed to point to the password field. 
Note that the field validation and tooltip will permanently show until the passwords match when the user clicks on the "Create account" button. 
I have re-tested this issue having those expected results in mind on Windows 10 64-bit and Android 8.0.0 on FF Stage [Train 1.151.0] and closing it again based on that.
