### ISSUE TITLE
Impossible to log in to AMO when 2FA is enforced because of " Authorize this sign-in" page requiring 2FA, which is not set up yet

### ISSUE THREAD

**Issue by diox** [mozilla/fxa#6342]
## Description

When logging in to AMO dev with a FxA account that doesn't have 2FA set up yet, and has 2FA enforcement set on the AMO side, the user is asked to authorize this sign-in before proceeding to the inline 2FA setup (previously it would fail before that with a 500, that was fixed in https://github.com/mozilla/fxa/issues/5206).

However, there is a chicken and egg problem: At this point the user doesn't have 2FA set yet, but when pasting the code received by email in the "Authorize this sign-in" page, the following error is shown: "This request requires two step authentication enabled on your account.".

![fxa_2fa_fail](https://user-images.githubusercontent.com/187006/91713390-fa438f80-eb89-11ea-8a9a-5539bfd5a775.png)

### Steps to reproduce

- Try to log in to AMO dev (https://addons-dev.allizom.org) with a FxA stage account that 1) doesn't have 2FA set up yet and 2) has 2FA enforcement set on AMO (ask an AMO engineer to set it on your account)

### Expected result

- You should log in to FxA as normal, then be presented with the inline flow to set up your second factor before going back to AMO, fully authenticated.

### Actual result

- You see the "Authorize this sign-in" page - which already is confusing, since the user just successfully entered their email and password, but then when pasting the code received by email, the error "This request requires two step authentication enabled on your account." appears and the user is blocked there.

Note: the code entered does appear to be validated properly - entering the wrong code shows "Invalid or expired verification code".

### Environment

What browser and operating system are you using?

Reproduced on Firefox 81.0a1 on Linux.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2498)
┆Issue Number: FXA-2498

**Comment by diox** [comment]
Note: Our QA was unable to reproduce with newer account, so maybe account/session age has something to do with it.

**Comment by diox** [comment]
I just saw this again on stable.dev, and I've noted something : I was already logged in to FxA with a different account, clicked the link to use a different account, entered the email and then password, that worked, then got the session unverified screen which doesn't let me through even with the correct verification code received by email. So maybe this is related to session switching somehow.

**Comment by 6a68** [comment]
@vasilicatamas Hi, could you try to reproduce this bug? Maybe by switching between two accounts?

**Comment by vbudhram** [comment]
@6a68 I think I might have introduced this bug in https://github.com/mozilla/fxa/pull/6295/files#r481289985. That PR created a general mixin to redirect to the verification page if the user got an `Unverified session` error. 

I would say we could reuse that mixin however, it will only work when you user submits the form. In your case, it seems like this should proactively redirect to verification page. The simplest fix is to add back the `redirectTo`.

**Comment by 6a68** [comment]
Great catch @vbudhram! Thanks for taking a look. I'll take a swing at a fix once I get #5826 wrapped up

**Comment by vasilicatamas** [comment]
@6a68 I was able to reproduce the error from description when logging (Sign in (Require 2FA)) on https://123done-stable.dev.lcip.org/ using an old account that hasn't been used for a while and needed to confirm their process using the code in "Authorize this sign-in" screen.

![issue6](https://user-images.githubusercontent.com/18114210/91982607-2d755280-ed33-11ea-9466-d98a6d8cf28e.gif)

**Comment by 6a68** [comment]
Hi @vasilicatamas, could you verify this is fixed once train 187 hits stage?

**Comment by vasilicatamas** [comment]
> Hi @vasilicatamas, could you verify this is fixed once train 187 hits stage?

Sorry for not seeing this request earlier. For next time, I suggest you to add the needs:qa label, so that it will appear in the queries and I will not miss it.

I was still able to reproduce this issue on https://123done-stable.dev.lcip.org/ but it seems that everything worked as expected and no error was encountered while testing on https://123done-stage.dev.lcip.org/ 

![Screenshot_49](https://user-images.githubusercontent.com/18114210/93199214-c99d5180-f756-11ea-92a1-b32dc950e746.png)
![issue11](https://user-images.githubusercontent.com/18114210/93210035-9f07c480-f767-11ea-9770-8e05264fc346.gif)

**Comment by 6a68** [comment]
Thanks for verifying the fix on stage! I'll be sure to use the needs:qa label next time :+1:
