### ISSUE TITLE
auth-server does not emit flow-complete events for Firefox 80

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#6347]
In fxa-auth-server, we have a special mechanism for emitting a server-side `flow.complete` event to signal the successful completion of a login flow. I don't think it's well-documented, but it works something like this:

* When we see the user is signing in, we [look at the details of the signin request](https://github.com/mozilla/fxa/blob/a55097f4004a06a9ffae963e6d23c3c795a28b8c/packages/fxa-auth-server/lib/routes/utils/signin.js#L249) and decide what event will signal its successful completion.  This is called the "flow complete signal".
* This gets [stashed in memcache](https://github.com/mozilla/fxa/blob/a55097f4004a06a9ffae963e6d23c3c795a28b8c/packages/fxa-auth-server/lib/routes/utils/signin.js#L260) for later reference alongside other metrics-related data about the login attempt.
* Later, when we're [emitting a metrics event](https://github.com/mozilla/fxa/blob/6f0a4bd9bc9fb319f448e3be66aab789c268e4a3/packages/fxa-auth-server/lib/metrics/events.js#L91), we check whether that event matches the stashed `flowCompleteSignal` and if it does, we emit an additional [`flow.complete` event](https://github.com/mozilla/fxa/blob/6f0a4bd9bc9fb319f448e3be66aab789c268e4a3/packages/fxa-auth-server/lib/metrics/events.js#L122).

Why this elaborate stashing dance, you ask? We want `flow.complete` to signal that the user successfully did the thing they wanted to do. In particular, if the user is signing in to the browser, we want `flow.complete` to signal that the browser successfully obtained the FxA credentials and is attempting use them to sync. That happens in a separate request to `/account/login`, so we need to remember the metrics context across requests.

That's why, when we see a login flow that we think is coming from a signin to Firefox (such as [here](https://github.com/mozilla/fxa/blob/a55097f4004a06a9ffae963e6d23c3c795a28b8c/packages/fxa-auth-server/lib/routes/utils/signin.js#L250) and [here](https://github.com/mozilla/fxa/blob/e440dae101bbd5d90e26dfcf60bea3edde8f362a/packages/fxa-auth-server/lib/routes/password.js#L437)) we set `flowCompleteSignal = "account.signed"`, the even that indicates that the browser is using its FxA credentials to sign a BrowserID certificate in order to start syncing.

As of Firefox 80, this no longer works as intended.

Firefox 80 switches to using OAuth for sync rather than BrowserID, so it will never generate the `account.signed` event, and will never trigger the auth-server to emit its `flow.complete` event. It instead calls the [`/oauth/authorization` endpoint](https://github.com/mozilla/fxa/blob/19eb3b5fda630ae120a28e8a5f9106ebacd8b494/packages/fxa-auth-server/lib/routes/oauth/index.js#L123) to make OAuth tokens for itself. This endpoint emits an oauth `token.created` event, but those events aren't hooked up to the above machinery and it does not trigger `flow.complete`.

If we want the `flow.complete` events back, we'll need to convince `/oauth/authorization` to trigger the flow-complete signal somehow.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2501)
┆Issue Number: FXA-2501

**Comment by rfk** [comment]
The simplest solution here may be to have the [`/oauth/authorization` endpoint](https://github.com/mozilla/fxa/blob/19eb3b5fda630ae120a28e8a5f9106ebacd8b494/packages/fxa-auth-server/lib/routes/oauth/index.js#L123) emit a fake `account.signed` event; not pretty, but it would get the job done.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

[~adavis@mozilla.com] is this something you want on a point release this week?

**Comment by 6a68** [comment]
@rfk thanks for the context here. As so often happens with metrics-related code in FxA, here I am slightly baffled, and find myself wondering how much of this we really need to be doing.

Rather than store fields in memcached, couldn't we just log the relevant fields with start and end events, for instance, "login started on a desktop firefox with $client_id for user $uid", and "oauth token issued for desktop firefox $client_id and user $uid", and configure a bigquery-ETL job on the backend to count up completed vs abandoned logins?

**Comment by rfk** [comment]
> I am slightly baffled, and find myself wondering how much of this we really need to be doing.

That's fair; it's likely that the world this was designed for is very different to the world that currently exists in terms of how we handle our metrics.

What you describe above sounds worth investigating. There could be some tricky correlation work to get all the events associated to a single "flow". Some of them happen early in the process when all you have is the randomly-generated flowid, others happen post-login when all you have the deviceid. Hopefully there's an event in the middle that can have both identifiers!
