### ISSUE TITLE
In case of card issues multiple emails (for each product) are sent to the subscriber

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6348]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.186.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have a FxA account with 2 subscriptions (products example: Firefox Variety and Subscription Proxy);

#### Steps to reproduce:
1. Go to [Stripe](https://dashboard.stripe.com/test/payments) and delete the attached card to the account used to make the subscriptions mentioned in prerequisites;
2. Wait for 1 day so that the recurrent payment email is triggered;
3. Check the payment failed email using your email client;

#### Expected result:
- User receives one email about the payment failure.

#### Actual result:
- User receives two emails, one for each product.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2502)
┆Issue Number: FXA-2502

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Each product can have their own payment methods and schedules and payment failures are triggered in separate notifications to us – we don't think there is a way to unify these emails.

**Comment by lmorchard** [comment]
FWIW, multiple payment methods are unimplemented and aimed at a future epic. But, we definitely have separate payment schedules at present.
