### ISSUE TITLE
[FxA-Settings] Header elements are not aligned on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6356]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
iOS 13.6 

**Affected devices**
iPhone 11

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Check how the header elements are displayed.

**Expected results**
All the elements are displayed on the same line.

**Actual Results**
Avatar icon is displayed above the rest of the header elements.

![Screenshot_25](https://user-images.githubusercontent.com/18114210/91988494-fe151480-ed37-11ea-9391-3a781df00581.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2504)
┆Issue Number: FXA-2504

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Maybe related to fxa-2507

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

done https://github.com/mozilla/fxa/commit/5d4e2e94d144be7379fb146d5af68d2227ea0a75

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [train 1.192.0] under iOS 13.6. All the elements are displayed on the same line.

![Screenshot_5](https://user-images.githubusercontent.com/18114210/97311052-9cbb7e80-186c-11eb-91a6-3e3daa2c6614.png)
