### ISSUE TITLE
[FxA-Settings] Password creation date is not displayed in 12-hours time on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6369]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
iOS 13.6 

**Affected devices**
iPhone 11

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Check how the password creation date is displayed in the page.

**Expected results**
Password creation date is successfully displayed in 12-hours format.

**Actual Results**
Password creation date is displayed in 24-hours time.

![Screenshot_33](https://user-images.githubusercontent.com/18114210/92120322-90cdb600-ee01-11ea-874c-7752196fd6d3.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2510)
┆Issue Number: FXA-2510

**Comment by jodyheavener** [comment]
I can't seem to replicate this, but I'm curious: is the device where this is happening set to display time in 24 hour clock, or 12 hour clock? Or alternatively, what region/locale is the device set in? I wonder if our code is trying to follow device preference.

To whomever works on this, if we _do_ want to override this I think we can use the [`h12` hour cycle](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat). I might suggest leaving it as is, though.

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

We shouldn't force 12h time since preferred time format is locale specific

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This displays in the format of the date/time format library we are using.  Marking wontfix.
