### ISSUE TITLE
[FxA-Settings] “Make primary” button is displayed in hovered state after tapping on it on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6371]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
iOS 13.6 

**Affected devices**
iPhone 11

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/
2. Login using an user that has already added a secondary email
3. Tap on “Make primary” button.

**Expected results**
The “Make primary” button returns to the enabled state.

**Actual Results**
The “Make primary” button is displayed in the hover state.

![issue5](https://user-images.githubusercontent.com/18114210/92126749-39cbdf00-ee09-11ea-8bce-a3046a03803f.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2512)
┆Issue Number: FXA-2512

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage  [Train 1.200.1] under iOS 13.6. The “Make primary” button successfully returns to the enabled state after taping on it.
