### ISSUE TITLE
[FxA-Settings] “Confirm” blue button displayed instead of “Remove” red button in “Remove recovery key?” modal

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6373]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
Windows 10 x64
iOS 13.6 
Android

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/
2. Login using an existing user that has already set a recovery key.
3. Click on the "Remove" button from "Recovery key" section.
4. Observe the available buttons.

**Expected results**
“Cancel” and “Remove” buttons are successfully displayed as expected per [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1).
![Screenshot_37](https://user-images.githubusercontent.com/18114210/92221553-5407ca80-eea6-11ea-8e74-00b332fe69cd.png)

**Actual Results**
“Confirm” blue button is displayed instead of the “Remove” red button.
![Screenshot_36](https://user-images.githubusercontent.com/18114210/92221559-5702bb00-eea6-11ea-80db-41e95d133387.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2514)
┆Issue Number: FXA-2514

**Comment by jodyheavener** [comment]
Will be fixed with https://github.com/mozilla/fxa/pull/6302

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This was addressed in FXA-1616

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.190.1] under Windows 10 64-bit and Android 9. "Remove" red button is successfully displayed in “Remove recovery key?” modal.

![Screenshot_21](https://user-images.githubusercontent.com/18114210/95485037-dc8ff400-0999-11eb-9d73-2ec527dee9b8.png)
