### ISSUE TITLE
[FxA-Settings] The buttons from “Remove recovery key?” modal are incorrectly displayed

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6374]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
Windows 10 x64
iOS 13.6 
Android

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/
2. Login using an existing user that has already set a recovery key.
3. Click on the "Remove" button from "Recovery key" section.
4. Observe the available buttons.

**Expected results**
The buttons are displayed separately.

**Actual Results**
The buttons are attached to each other.

![Screenshot_38](https://user-images.githubusercontent.com/18114210/92222235-5b7ba380-eea7-11ea-8850-b134a8f66779.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2515)
┆Issue Number: FXA-2515

**Comment by jodyheavener** [comment]
I believe this is fixed in #6350 and should be verifiable in the next train.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.190.1] under Windows 10 64-bit and Android 9. "Remove recover key?" modal buttons are correctly displayed. 
![Screenshot_21](https://user-images.githubusercontent.com/18114210/95484622-5ffd1580-0999-11eb-9997-932ce1c1500d.png)
