### ISSUE TITLE
[FxA-Settings] 2FA section does not reflect the enabled state

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6376]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
Windows 10 x64
iOS 13.6 
Android

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/
2. Login using an existing user that has already enabled the two-step authentication.
3. Check the Two-step authentication section.

**Expected results**
"Enabled" status, "Change" button and "Disable" button are successfully displayed in the "Two-step authentication" section.

**Actual Results**
The "Not set" status and "Add" button are displayed in the "Two-step authentication" section.

![Screenshot_42](https://user-images.githubusercontent.com/18114210/92227893-a8fc0e80-eeaf-11ea-98a3-bfe2d7739198.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2517)
┆Issue Number: FXA-2517

**Comment by jodyheavener** [comment]
Should be fixed in https://github.com/mozilla/fxa/pull/6302

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This was addressed in FXA-1616

**Comment by vasilicatamas** [comment]
Confirm that the 2FA section successfully displays the Enabled state. Tested on FxA Stage [Train 1.190.1] under Windows 10 64-bit, Android 9 and iOS 13.6.

![Screenshot_18](https://user-images.githubusercontent.com/18114210/95480565-b2880300-0994-11eb-87e0-1cad89b267c6.png)
