### ISSUE TITLE
Error: Error: Invalid token

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#6386]
These errors started happening September 1st, we should investigate and see what might have caused this.

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/9507428/?referrer=github_plugin

```
Error: Error: Invalid token
  at None (./views/settings/account_recovery/account_recovery.js:74:12)
  at promiseReactionJob ([native code])
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2518)
┆Issue Number: FXA-2518

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Looks like this was resolved with the push on Sep 14

**Comment by jodyheavener** [comment]
Oh good timing
