### ISSUE TITLE
GQL server connection error on staging

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6399]
Beta settings can't be hit after the point release. See this thread: https://mozilla.slack.com/archives/G0177C5FTCZ/p1599681917064100

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2523)
┆Issue Number: FXA-2523

**Comment by 6a68** [comment]
I can take a look.

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

> is it possible that the graphql server can’t connect to the auth server?

Yes, yes it is. There's no creds in the ASG launch config, and I accidently killed the old instance so all the working creds are done

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Ah, I asked jbuck and he quickly found the error. Reassigning.

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

This is now working on stage again
