### ISSUE TITLE
Support OIDC prompt=none parameter?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#640]
This came up in a recent meeting with @gdestuynder about the IAM integration.

The OpenID Connect spec defines some special behavior when the user loads the oauth flow with `?prompt=none`; from [1]:

```
prompt
    OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the
    Authorization Server prompts the End-User for reauthentication and consent. The defined values are:

        none
            The Authorization Server MUST NOT display any authentication or consent user interface pages.
            An error is returned if an End-User is not already authenticated or the Client does not have
            pre-configured consent for the requested Claims or does not fulfill other conditions for 
            processing the request. The error code will typically be login_required, interaction_required, or
            another code defined in Section 3.1.2.6. This can be used as a method to check for existing
            authentication and/or consent.
```

OIDC clients (such as the Auth0 stack used for IAM integration) use this as a way to check for freshness of a user's login session - they make a background request to the OAuth authorization endpoint with `?prompt=none`, refresh their auth state if it succeeds, and sign the user out if it fails.  It basically allows the relier to ask "if the user did an OAuth flow right now, would they have to log in?"

The IAM integration stack tries to use `prompt=none` in this manner when talking to FxA, but we don't handle it in a spec compliant way; instead we silently ignore it.

One wrinkle: as discussed in https://github.com/mozilla/fxa-content-server/issues/5916, we will *always* require some user interaction when signing in to an OAuth relier, so the correct way for us to handle `prompt=none` would be to immediately redirect back to the relier with an error response.  That might actually make it simpler to implement on our side :-)

@gdestuynder is working on a fix for this in Auth0 config, to prevent it from trying to use this unsupported parameter when talking to FxA.  But that's probably going to be at least a little gross, and it's a feature that's generally useful, so we should consider whether it's worth adding on our side for a better experience.

[1] http://openid.net/specs/openid-connect-core-1_0.html

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/issues/1979 to support RP initiated logout.

**Comment by gdestuynder** [comment]
@shane-tomlinson is this a feature we can/should be using with SSO?

The comment in https://github.com/mozilla/fxa/commit/15d0cbf30764323913ace0b575671feb0a3b4f51 is a little scary :)

Otherwise, i tried to just pass `prompt=none` on staging (https://accounts.stage.mozaws.net/oauth/signin) which did not work, but I'm guessing this is something that would have to be enabled for our SSO RP.

If the feature is not in a state that would be usable for SSO though, I'm fine doing nothing for now :)

**Comment by rfk** [comment]
IMHO we could investigate it, you'd be a good test case! Right now you have to specify both `prompt=none` and `login_hint=user@example.com` in order to get the correct flow, is that something that the IAM gateway is in a position to do?

**Comment by gdestuynder** [comment]
@rfk I'm not sure I'm able to provide the login hint, though I might ask auth0 to support that.

If I hit: `https://oauth.accounts.firefox.com/v1/authorization?prompt=none&login_hint=kang@insecure.ws` manually though, with kang@insecure.ws logged in, it just sends me to `/signin` with these params and a login button like before:

![image](https://user-images.githubusercontent.com/956866/62330591-fbc5f400-b46d-11e9-9e7d-b5cf97baa171.png)

**Comment by rfk** [comment]
It's not deployed yet and you're not on the allowlist so I wouldn't expect it to work just yet. Do you have a dev environment that interacts with http://latest.dev.lcip.org that could be used for testing purposes?

**Comment by gdestuynder** [comment]
i have only 2 envs (prod and "dev"). I can point "dev" to your dev instead of your staging, so yes :-)
I'll need credentials for it though
