### ISSUE TITLE
Don’t redirect endlessly when the GQL server can’t be reached

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6400]
We direct to `get_flow` and back to settings in an endless loop when the "general application error" is shown. The page should instead stay in place at the general application error.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2524)
┆Issue Number: FXA-2524

**Comment by 6a68** [comment]
seems connected to the other one. grabbing

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

this was a bit of a stretch issue, bumping to next sprint to wrap up
