### ISSUE TITLE
(Settings code quality) Don't use negative margin on the back button for positioning

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6402]
Using a negative margin on the "back" arrow on the inner pages is a quick & dirty way to get the arrow visually looking right.

See this Slack thread: [https://mozilla.slack.com/archives/G0177C5FTCZ/p1597691731023300](https://mozilla.slack.com/archives/G0177C5FTCZ/p1597691731023300)

It's cleaner to use flexbox if possible to change the layout in desktop/mobile but if this is impossible a better solution would be to `position: relative` and scoot around what needs to move position-wise. Another less-than-ideal solution would be to hide/show a mobile/desktop arrow depending on breakpoint, but one could argue a negative margin would be preferable over that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2526)
┆Issue Number: FXA-2526

**Comment by jodyheavener** [comment]
I bet this would be fairly trivial using grid
