### ISSUE TITLE
Support OAuth in WebViews without localStorage?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#641]
Migrating from https://github.com/mozilla-iam/auth0-custom-lock/issues/111

Several Mozilla-hosted services (e.g. IRCCloud, Tableaux) have an Android app that loads the Mozilla IAM login flow in a WebView.  Now that IAM supports FxA, that means they can also load our OAuth flow in a WebView.

Unfortunately said WebView may not support localStorage, so if the user opts to sign in with FxA, they'll get our "cookies and local storage are required" error page.  These are third-party apps, so we're not really in a position to update them to support localStorage.

So...could we avoid this requirement in our OAuth flow by using some sort of localStorage mock or shim?  Should we?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-763)
┆Issue Number: FXA-763

**Comment by vladikoff** [comment]
cc @shane-tomlinson

**Comment by laghee** [comment]
Just a note to point out the issue linked above -- with the new matrix modular server, this issue now impacts android access for contributors.

**Comment by vladikoff** [comment]
@clouserw might need to reprioritize this...
