### ISSUE TITLE
Shows App Badges from Sync prefs -> CAD

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#6422]
From slack:

STR:

1. Be signed into the browser
2. Goto `about:preferences#sync`
3. Click `Connect another device`

Expected:

Shown the pairing screen.

Actual:

Shown the app badges screen.

Notes:

We should add the support for showing the pairing page with entrypoint=preferences [here](https://github.com/mozilla/fxa/blob/3f5ea06792c07db3f3ce54964a67d4274e166477/packages/fxa-content-server/app/scripts/views/mixins/connect-another-device-mixin.js#L90).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2528)
┆Issue Number: FXA-2528

**Comment by vasilicatamas** [comment]
Confirm that pairing screen is successfully displayed when clicking on "Connect another device" from about:preferences#sync.

![issue13](https://user-images.githubusercontent.com/18114210/94530558-edc35d00-0243-11eb-85b6-b135cbbf72bc.gif)
