### ISSUE TITLE
TOTP: recovery code used - message

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#644]
STR:
Try to Sign In with a recovery code already used.

Actual results: "recovery code not found" message is displayed.
Expected results: "recovery code used" message to be displayed.

Probably this is applying for codes that are in the last list generated. If I have 3 lists downloaded for the same account and I'm using a code from first list, the message "recovery code not found" has more context.

**Comment by clouserw** [comment]
In triage we agreed saying that the code was not found was an ok message to keep.  Closing this.
