### ISSUE TITLE
chore(deps): bump sass-loader from 8.0.2 to 10.0.2 in /packages/fxa-content-server

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#6444]
PR @ https://github.com/mozilla/fxa/pull/6426 but it won't land cleanly so will require some work

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2534)
┆Issue Number: FXA-2534

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

won't do
