### ISSUE TITLE
chore(deps): bump mozlog from 2.2.0 to 3.0.1 in /packages/fxa-content-server

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#6445]
PR @ https://github.com/mozilla/fxa/pull/6425 but won't land cleanly so will require some work

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2533)
┆Issue Number: FXA-2533

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

closed in https://github.com/mozilla/fxa/pull/6483
