### ISSUE TITLE
[post-beta] Remove beta opt-in link

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6477]
Remove the opt-in link added in FXA-1739.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2547)
┆Issue Number: FXA-2547

**Comment by 6a68** [comment]
Seems related to #6476, grabbing this one too

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue was verified as Fixed on Stage [Train 1.203.2] under Windows 10 and Android 11. The opt-in link (Switch to new design/ Switch to old design) is not available anymore.
