### ISSUE TITLE
“Get on App Store” button from VPN Download page is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6489]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.188.1;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have a FxA account with active subscription for Mozilla VPN;

#### Steps to reproduce:
1. Load https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/ page;
2. Click on “Download Now” button;
3. Click on the “Get on App Store” button;

#### Expected result:
- User is redirected to the VPN Mozilla app from the App Store.

#### Actual result:
- The App Store is “Connecting” continuously.

#### Notes:
- The URL of the page is: “https://apps.apple.com/us/app/firefox-private-network-vpn/id1489407738”;
- The App Store is working if accessed directly on Mac;
- The issue is also reproducing on iOS device;

![image](https://user-images.githubusercontent.com/15685960/93591019-36635680-f9b8-11ea-80d3-66f28e46c899.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2549)
┆Issue Number: FXA-2549

**Comment by ValentinaPC** [comment]
This is also happening in production.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I don't think this is a bug we can fix.  It seems like there is no fallback page being shown from the Apple app store.

In safari the link works correctly.  In Firefox I'm prompted to open the app store.  If I choose 'no' I see the behavior you are describing.  Is it possible you've set it to 'no' and said not to ask you again? 

Either way, this isn't something we can fix so I'm going to close this.

**Comment by ValentinaPC** [comment]
>  Is it possible you've set it to 'no' and said not to ask you again?

Nope. And, I can tell you for sure that the page from App Store containing the Mozilla VPN product, was working few weeks ago, even from Windows, and using FF.

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx81 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/94928732-cf23c700-04cc-11eb-9139-2331104c62be.png)
