### ISSUE TITLE
Implement server-side flow.begin events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#649]
As pointed out in https://github.com/mozilla/fxa-content-server/issues/5553#issuecomment-334571417, we don't emit `flow.begin` events for flows that are aborted before there is a chance to send metrics to the back-end.

If we were to emit `flow.begin` on the server, it would fix that problem. However, we'd need to come up with a plan for handling requests that should not emit a `flow.begin` event, e.g. for signed-in users. If that decision can't be shifted to the back-end, perhaps we could work round it by emitting some kind of `flow.invalidate` event that we can use to sort things out during the redshift import process.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-768)
┆Issue Number: FXA-768

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
