### ISSUE TITLE
[support form] Add empty select option to the product specific app/service field

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6501]
The field is suppose to be optional, but there's no empty option to make that so.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2552)
┆Issue Number: FXA-2552

**Comment by ValentinaPC** [comment]
Verified as fixed in Stage, using Fx81 and Windows 10 (64-bit).
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/94408128-0b79bf00-017d-11eb-8edf-f6d2e265425b.png)
