### ISSUE TITLE
No Longer Tracking Activity for Sync on Desktop

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6503]
On desktop, we normally track 2 types of activity metrics:

1) Are they signed into an account or not? `service=firefox-desktop`
2) Are they signed into Sync specifically? `service=sync`

We are no longer tracking if they are signed into Sync on desktop.

See (ignore chart title): 
https://analytics.amplitude.com/mozilla-corp/chart/alh9e7d/edit/46ajhvp

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2554)
┆Issue Number: FXA-2554

**Comment by rfk** [comment]
Quick drive-by to note, looks like this drop corresponds to the release of Firefox 80 and its switch to using OAuth for Sync access.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Some optional related reading material:

  * https://bugzilla.mozilla.org/show_bug.cgi?id=1632635 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1632635 ) The origin of "fxa_activity - active"
  * https://github.com/mozilla/fxa/pull/6383 ( https://github.com/mozilla/fxa/pull/6383 ) PR for emitting a "fake" 'account.signed' ('fxa_activity - cert_signed') event
  * https://github.com/mozilla/fxa/pull/5820 ( https://github.com/mozilla/fxa/pull/5820 ) The origin of "fxa_activity - oauth_access_token_create"
  * https://bugzilla.mozilla.org/show_bug.cgi?id=1591312 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1591312 ) Restoration 'cert_signed' with 'service=sync'

The event in question here is "cert_signed", which no longer includes the service in its event properties after Sync's switch to OAuth.  Prior to the switch, the event is emitted when Sync sends a request to `/certificate/sign` with the query param 'service=sync'.  After the switch, this event is "faked" within the `/oauth/token` handler.  However, it does not include the service name in the event properties since there isn't one in the request.

What we could do (should do?) on the FxA side is to include `{service: sync}` in the new events emitted from the `/oauth/token` when "oldsync" is in the scopes.

I was made aware of https://github.com/mozilla/fxa/issues/6578 ( https://github.com/mozilla/fxa/issues/6578 ) literally in the middle of writing this comment, so perhaps we should also _only_ emit those events when "oldsync" is in the scope?

I think Sync should include the service name in its requests to FxA.  @rfk will let us know whether that's a good idea.

**Comment by rfk** [comment]
> I think Sync should include the service name in its requests to FxA

TBH, I think I prefer the approach you're taking in #6581 - the client is already telling FxA that it's accessing sync by requesting a token with the `oldsync`, we should use that information rather than asking the client to send it again in some other parameter.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

This was a 5 for me simply for the complete lack of context.
