### ISSUE TITLE
Instrument the `/m/:signinCode` endpoint with flow events.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#651]
@philbooth, Leif and I were trying to create a CAD phase 3 funnel the other day and noticed we have not instrumented the `/m/:signinCode` endpoint, so we have to get numbers for this endpoint from Kibana.

**Comment by davismtl** [comment]
@irrationalagent still relevant?

**Comment by irrationalagent** [comment]
I don't think this is relevant anymore.
