### ISSUE TITLE
Secondary email verification screen should not require cookies

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#652]
Please consult attached screen shot - Secondary email verification screen should not require cookies.
![secondary email verification screen should not require cookies](https://user-images.githubusercontent.com/17153650/30649814-2272e9ba-9dd6-11e7-8559-f6fae0461601.png)
 attached screen shot and

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-769)
┆Issue Number: FXA-769

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
