### ISSUE TITLE
Link in About Section of Repository leads to a 404 page

### ISSUE THREAD

**Issue by KarenEfereyan** [mozilla/fxa#6529]
This [link](https://mozilla.github.io/application-services/docs/accounts/welcome.html) as seen on the about page on this repository leads to a 404 page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2567)
┆Issue Number: FXA-2567

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing this.  I fixed it.
