### ISSUE TITLE
Animate settings sections open like when we disconnect devices

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#655]
When users open sections in Settings, it can be a little jarring. Can we make it smoother like when a device is disconnected? Should match the new [Photon animation curve](https://design.firefox.com/photon/motion/duration-and-easing.html).
![show-devices](https://user-images.githubusercontent.com/68213/30079562-a00dcdc4-924e-11e7-9af2-4fd12930c187.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-772)
┆Issue Number: FXA-772

**Comment by clouserw** [comment]
Settings has a new design.  Closing this.
