### ISSUE TITLE
Duplicate subscription with refresh

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6553]
It is possible to create a duplicate subscription during sign-up. We don't know exactly how this happened, but its not clear to the user this has happened until they get billed twice.

We use an imdepotency key on the front-end, but this is somehow being lost or not fulfilling its purpose.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2574)
┆Issue Number: FXA-2574

**Comment by clouserw** [comment]
@ValentinaPC This looks pretty important but we haven't reproduced it.  Are you able to explore this area a bit and see if you can get some STR? Thank you

/cc @rbillings

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

bq. We use an imdepotency key on the front-end, but this is somehow being lost or not fulfilling its purpose.

The nonce / idempotency key is generated on every page load. It's also re-generated on subscription retry after errors. It's meant to prevent duplicate submissions from the current immediate interaction - e.g. issue 4386 double clicks on the submit button ( https://github.com/mozilla/fxa/issues/4386 ).

We don't store it in localstorage or retain it on refresh in any way, because it wasn't meant for use beyond a single API call. We could retain the key. But we would need to be sure to clear / expire it, or else future attempts to use the payment flow would fail in error.

I'm not sure the idempotency key would help prevent this, though.

Maybe what we need to do is retain the invoice generated on initial payment submission. We keep that in memory through retries, but not in localstorage. So, if someone tried to pay, saw an error, then refreshed and tried again - they would open a new invoice.

**Comment by ValentinaPC** [comment]
> 
> 
> @ValentinaPC This looks pretty important but we haven't reproduced it. Are you able to explore this area a bit and see if you can get some STR? Thank you
> 

I will try to reproduce it.

**Comment by ValentinaPC** [comment]
@clouserw 
I've tried different things like: re-loading the subscription page after a payment, disconnecting the internet while trying to make a subscription and reconnecting it back, clicking multiple times on the "Pay now" button, etc. None of these scenarios took me to the duplicate payment phase. Will throw an extra eye on this side, if you did not figure it out already, what was the problem.

**Comment by clouserw** [comment]
Thanks for looking.  Based on Les's comment above it sounds like there is some surface area where this could happen, but it sounds like it's small.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

The one scenario where I think this might happen is:

  * Try to pay for a subscription with a card that causes an error
  * Get a message to try again
  * Refresh the page
  * Try again with a card that works

I haven't been able to reproduce a problem trying this myself though.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Can't reproduce.
