### ISSUE TITLE
error in the logs from profile-server

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#6555]
I found this in the logs of my profile-server. What is wrong there, or can I ignore it? Or is there something missing in the configuration?

Thanks...

[...]

fxa-profile-server.updates_queue.ERROR: SQSSender.send No SQS region or queueURL provided, SQS features will be disabled

[...]

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2575)
┆Issue Number: FXA-2575

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Based on the error, if you want to use SQS you'll need to tell it where your SQS URL is.  If you don't, then you're good to ignore it.
