### ISSUE TITLE
New fxa accounts can't be created in stage

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#6560]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.189.0;

#### Affected Platforms:
- all platforms

#### Steps to reproduce:
1. Open https://accounts.stage.mozaws.net/
2. Fill all the required forms to create a new fxa account and click the **Create account** button

 #### Expected result:
- The account can be created.

#### Actual result:
- **Failed to send email** error message is displayed and the account can't be created.
![image](https://user-images.githubusercontent.com/15685441/94406164-47f7eb80-017a-11eb-9a93-557ca23d17f9.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2576)
┆Issue Number: FXA-2576

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

I understand that Ops has resolved this due to the email-service config issue discussed in #fxa channel today. Please confirm fix or reopen if required.

**Comment by madalincm** [comment]
I can confirm that this issue is no longer reproducing in stage. I can successfully create a new fxa account. Marking this bug as verified fixed.
