### ISSUE TITLE
FxA login fails with“Unexpected error”

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6561]
**Build**
Stage [Train 1.189.0]

**Affected platforms**
Windows 10 x64
Android 9

**Steps to reproduce**
1. Launch Firefox with a new profile and click on the FxA toolbar menu button.
2. Click on "Sign in to Firefox (Turn on Sync)" option.
3. Type an email address which is associated with a Firefox Account and click "Continue" button
4. Type a valid password and click the "Sign in" button.

**Expected results**
The user is successfully connected.

**Actual Results**
Login fails with the following error: “Unexpected error”.

**Additional details**
This error is also displayed when trying to login on https://accounsts.stage.mozaws.net using the same account for which was previously received the following error "Failed to send email" during the registration process (see #6560 6560)

![Screenshot_1](https://user-images.githubusercontent.com/18114210/94411210-fb63de80-0180-11eb-9713-e3bf9049308e.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2577)
┆Issue Number: FXA-2577

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

I understand that Ops has resolved this due to the email-service config issue discussed in #fxa channel today. Please confirm fix or reopen if required.

**Comment by vasilicatamas** [comment]
Confirm that the error is no longer encountered and the login process is successfully completed.

![issue13](https://user-images.githubusercontent.com/18114210/94539615-21a38000-024e-11eb-8bc9-9aba821e8983.gif)
