### ISSUE TITLE
[FxA-Settings] The account picture is displayed at very small dimensions

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6563]
**Build**
Stage [Train 1.189.0]

**Affected platforms**
Windows 10
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account that has already set an account picture.
2. Open the avatar drop-down.
3. Check how the account picture

**Expected results**
The avatar picture is displayed without issues.

**Actual Results**
The account picture is displayed at very small dimensions.

**Additional details**
This issue is not reproducible when the avatar picture is not set.

![Screenshot_2](https://user-images.githubusercontent.com/18114210/94455353-9f6a7b80-01bb-11eb-96c9-f45b1c70bb91.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2579)
┆Issue Number: FXA-2579

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Jody says look at flexbox to fix this

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage  [Train 1.200.0] under Windows 10 64-bit, Android 9 and iOS 13.6. The avatar picture is displayed using the correct dimension.
