### ISSUE TITLE
Visiting settings with a wrong uid disconnects user from sync

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa#659]
STR:
* create account, verify etc, then visit "settings" - bookmark the page.
* delete account.
* create new account (with same email address, although it's not clear that's necessary), verify etc.
* visit bookmarked page (and note that the uid in the URL is not the current uid)

Actual:
* This device is kicked out of sync.

Expected:
* Not sure, but probably not being completely disconnected.

The content server appears to send a fxaccounts:fxa_status message (which IIUC gives is the current account) followed by a fxaccounts:logout message (that specifies the uid of the current user) and we disconnect.

Even without a bookmark there's a risk that the user will land on this page due to awesomebar completion or by using their history. However, it seems low impact as we expect account deletion to be rare.

(I also wonder if this is what @ryanfeeley saw in one of his recent sync-fests?)

**Comment by clouserw** [comment]
I think this was filed before https://accounts.firefox.com/settings was the settings URL (@mhammond talks about a UID being in the URL).  So, closing this, but please let me know if I'm misunderstanding
