### ISSUE TITLE
CWTS - cannot go "back" after de-selecing a Sync bucket.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#660]
I thought there was a bug on file about this already, but I can't find it.

On CWTS the only way to go back is with the "Mistyped email?" link in the green status bar. If the user unchecks a Sync bucket, the green status bar goes away, leaving the user with no way to correct their email address.

STR

1. Sign up for a new account for Sync.
2. On CWTS, uncheck a bucket.
3. Where'd the green status bar go?

![cwts-status-goes-away](https://user-images.githubusercontent.com/848085/28831047-7c718c5a-76d0-11e7-9683-afb6daac19ef.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-774)
┆Issue Number: FXA-774

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this CWTS page was moved
