### ISSUE TITLE
account/create endpoint broken

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa#6609]
Our application-services integration tests are currently failing, it seems that we cannot create an account. Here are the details of the failing FxA call:

# Request

URL: https://stable.dev.lcip.org/auth/v1/account/create?keys=true
Method: POST
Body:
```json
{
  "authPW": "c6cfaf3cf5346d5a109490e514c54d0d47a6702d25a87d6a89d2d5369438c626",
  "email": "rust-login-sql-test--cxiyU@restmail.net",
  "service": "3c49430b43dfba77",
}
```

# Response

```json
{
  "code": 500,
  "errno": 203,
  "error": "Internal Server Error",
  "info": "https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format",
  "message": "A backend service request failed.",
  "method": "POST",
  "operation": "check",
  "path": {
    "_expectedKeys": {
      "array": [],
      "set": {}
    },
    "_template": "/check"
  },
  "service": "customs"
}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2595)
┆Issue Number: FXA-2595

**Comment by groovecoder** [comment]
👍 for this issue, which I think is also currently breaking local Monitor sign-ins?

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Triaging: [~wclouser@mozilla.com] I think we need to reassess our dev environment process. This is one of those things jrgm used to just magically handle somehow.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~eoger@mozilla.com] could you try this again?  I think [~jbuckley@mozilla.com] fixed stable yesterday.

**Comment by eoger** [comment]
We're getting a nginx error doing a GET on https://stable.dev.lcip.org/.well-known/fxa-client-configuration

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Fixed in https://github.com/mozilla/fxa-dev/pull/516 ( https://github.com/mozilla/fxa-dev/pull/516 ) (I hope)
