### ISSUE TITLE
iOS avatars are 90° CW and squished

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#661]
child of https://github.com/mozilla/fxa-content-server/issues/6261 

STEPS TO REPRODUCE
1. Go to FxA Settings on Firefox for iOS
1. In Account picture select Change
1. Select Upload
1. Select Take Photo
1. Take a vertically oriented photo and select Use Photo

EXPECTED RESULTS
* Photo is straight and centered

ACTUAL RESULTS
* Photo is 90° CW and squished and avatar UI is oversized

![img_3369](https://user-images.githubusercontent.com/68213/28795605-7ded0866-7608-11e7-8d5c-d4bf438fe49d.PNG)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-775)
┆Issue Number: FXA-775

**Comment by LZoog** [comment]
Cannot reproduce in new beta settings, going to go ahead and close this as it's an "epic" #623 that can otherwise be closed (besides one issue that will be kicked to another epic).
