### ISSUE TITLE
Settings: Improved load times by reducing number of XHRs

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa#662]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-776)
┆Issue Number: FXA-776

**Comment by clouserw** [comment]
We should add the settings page to https://sql.telemetry.mozilla.org/dashboard/fxa-performance to get some hard numbers and see how it compares to the rest of the site

**Comment by philbooth** [comment]
> We should add the settings page

So numbers from settings do make it into that dashboard, it's just that we didn't spend time distinguishing them yet. At the time, our main concern was performance of the signin/signup views as they impact our funnels, and those views are labelled as `auth` in the charts.

The categorisation of events from those views happens here:

https://github.com/mozilla/fxa/blob/098fe0780059c44faa09f7b5f868624b36130a09/packages/fxa-content-server/server/lib/flow-event.js#L74

...and then later:

https://github.com/mozilla/fxa/blob/098fe0780059c44faa09f7b5f868624b36130a09/packages/fxa-content-server/server/lib/flow-event.js#L85-L87

We could do something similar to pull settings data out of the `other` bucket. Or maybe it's better to segment all the data by view name, and get rid of that categorisation which was kind of a hack anyway. We can easily combine view names in the queries if we want to categorise `auth`/`other`.

**Comment by shane-tomlinson** [comment]
ref #862, #2561
