### ISSUE TITLE
Ensure AET eco_anon_id updates are logged correctly

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#6625]
Data Eng is not observing AET updates in the pipeline, see https://bugzilla.mozilla.org/show_bug.cgi?id=1656949.

We should figure out what's missing and get those updates flowing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2601)
┆Issue Number: FXA-2601

**Comment by 6a68** [comment]
I'll plan to tackle this in the next sprint or two, depending on whether #6581 fixed sync device metrics (#6578)
