### ISSUE TITLE
Upload test remote content server test results to XML

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6626]
In the test remote content server steps, it would be nice if we could upload the test results in XML so circle ci can display them nicely https://app.circleci.com/pipelines/github/mozilla/fxa/14159/workflows/5d84f45e-1695-4e5d-94c4-78e6cd117264/jobs/198198/tests

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2600)
┆Issue Number: FXA-2600

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Based on https://github.com/mozilla/fxa/commit/eb03d818a338b8af20b1bed512d07b73c8037d35 ( https://github.com/mozilla/fxa/commit/eb03d818a338b8af20b1bed512d07b73c8037d35 ) we should be able to do this for the smoke tests too

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

working now, https://app.circleci.com/pipelines/github/mozilla/fxa/14520/workflows/7d3a6bc0-6438-4629-aa6a-a0e001fdd796/jobs/201200/steps
