### ISSUE TITLE
Add sentry integration for all services to Slack

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6628]
We currently have some Sentry projects send messages of new errors into Slack, we should have them all send messages.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2603)
┆Issue Number: FXA-2603

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

[~ckolos@mozilla.com] has a PR up at https://github.com/mozilla-services/cloudops-deployment/pull/4163

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks [~ckolos@mozilla.com] and [~jbuckley@mozilla.com].  This is closed!
