### ISSUE TITLE
Send Slack message to #fxa when smoke tests fail in Circle CI

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6629]
Add the [Slack örb](https://circleci.com/developer/orbs/orb/circleci/slack) to [our Circle CI config](https://github.com/mozilla/fxa/blob/main/.circleci/config.yml#L247) so we get notified when the smoke tests fail

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2602)
┆Issue Number: FXA-2602

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

https://github.com/mozilla-services/cloudops-deployment/pull/4156
