### ISSUE TITLE
Sign-up/in flow: Account verification links don’t work if you open them in certain configurations of mobile safari; instead they give a "cookies required" error.

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa#663]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-777)
┆Issue Number: FXA-777

**Comment by rfk** [comment]
@shane-tomlinson I noticed that https://github.com/mozilla/fxa/commit/acedb9be05241bf263932831dac7b3ca02c58ac5 closed this issue, but it looks like an unrelated styling change, possible typo somewhere in github's auto-closing logic chain?

**Comment by shane-tomlinson** [comment]
That was meant to close [bugzilla-mirror#663](https://github.com/mozilla/fxa-bugzilla-mirror/issues/663) rather than here. Re-opening.
