### ISSUE TITLE
Jenkins pipeline should trigger smoke tests and fail build if smoke tests fail

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6630]
We need to setup Jenkins to trigger to smoke tests in Circle CI, and then watch them for success/failure to  respond accordingly.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2604)
┆Issue Number: FXA-2604

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

https://github.com/mozilla-services/cloudops-deployment/pull/4156
