### ISSUE TITLE
Sign-up/in flow: Don't ask to connect a mobile device when you started flow on mobile

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa#664]

**Comment by davismtl** [comment]
The mobile team is requesting that we resolve this by July 9th. (mobile trailhead)

https://bugzilla.mozilla.org/show_bug.cgi?id=1548331

**Comment by davismtl** [comment]
Duplicate of https://github.com/mozilla/fxa/issues/615

Will do work there instead since it has more context.
