### ISSUE TITLE
Document restmail behavior

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#6662]
We have some special case code to allow restmail-based testing of certain flows. We should document this somewhere, at least for devs and QA.

ref: https://mozilla.slack.com/archives/CLV3KMZ8B/p1602257563319500

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2612)
┆Issue Number: FXA-2612

**Comment by vbudhram** [comment]
@6a68 This isn't documented as far as I can tell.

> We should document this somewhere, at least for devs and QA.

Agreed, in general we could have a some testing section that tells how you to force certain things locally, 2FA required, sign-in code, unverified sessions etc.
