### ISSUE TITLE
Allow non-Sync users to go back during registration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#670]
Users who are signing up for Sync are seeding the client with their email address, and after they have chosen what to sync are unable to go back and make a correction with additional client development work.

We could easily add this ability for users registering for Add-ons, and other non-Sync related services.

https://irccloud.mozilla.com/file/3DbHyz76/fxa-back-button.png

**Comment by clouserw** [comment]
Now that we have email first, we don't think this is needed anymore.  If we're wrong, please reopen and let us know why. :)
