### ISSUE TITLE
The FxA verification is not complete after entering the verification code if Remote Settings is set to Stage

### ISSUE THREAD

**Issue by heres-maria** [mozilla/fxa#6721]
**[Affected versions]:**
- Firefox Nightly 84.0a1 (Build ID: 20201020145547)
- Firefox Beta 83.0b2 (Build ID: 20201020173725)
- Firefox Release 81.0.2 (Build ID: 20201012085804)

**[Affected Platforms]:**
- Windows 10 
- Windows 7
- macOS 10.15
- Linux Mint 20

**[Prerequisites]:**
- If using Firefox Beta or Release: see [this document](https://docs.google.com/document/d/13yxuvfpIGojY1FSsUJYHKUUQldKkSW0UzrUirdC0kQ0/edit#bookmark=id.3qlajv1ku5v3) for the environment variable needed.
- Have a Firefox desktop browser installed and open.
- Have Remote Settings Devtools installed.
- Have the Environment set to Stage from Remote Settings Devtools.

**[Steps to reproduce]:**
1. Navigate to “about:welcome”.
2. Click "Sign in".
3. Create an account and enter the verification code received on email.
4. Click the hamburger button and observe its menu.

**[Expected result]:**
- There is no option to “Finish Account Setup” as the account has already been verified.

**[Actual result]:**
- There is an option to “Finish Account Setup” for ~25s.

**[Notes]:**
- To finish verifying the account you need to click on “Finish Account Setup” and then click on “Resend Verification”.
- Attached is a recording of the issue.
![fxa stage](https://user-images.githubusercontent.com/53752296/96698032-4f836c80-1395-11eb-974d-bc7a8c3f5f05.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2627)
┆Issue Number: FXA-2627

**Comment by dannycoates** [comment]
I think this is an issue with the remote settings extension, not firefox accounts. There are several profile settings that should be set to use stage fxa ... https://github.com/mozilla/fxa/blob/main/packages/fxa-dev-launcher/profile.js

AFAIK, our team doesn't use remote settings extension. We use [fxa-dev-launcher](https://github.com/mozilla/fxa/blob/main/packages/fxa-dev-launcher/README.md) to test in other environments
