### ISSUE TITLE
Sign in from the VPN prod app does not work if you are already signed in on the VPN website

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6728]
#### Affected versions:
- All Firefox;

 #### Affected VPN versions:
- production version;

#### Affected FxA versions:
- 1.191.1;

#### Affected Platforms:
- Windows 10 x64;

#### Prerequisites:
- Have an FxA account with active subscriptions;
- Have Firefox as your default browser;

 #### Steps to reproduce:
1. Load https://vpn.mozilla.org/ page using Firefox;
2. Click the “Sign in” button;
3. Finalize sign in with success;
4. Go to the VPN app and open it;
5. Click on the “Get started” button;

#### Expected result:
- The user is asked to sign in using its default browser and a success message is displayed after he does it.

#### Actual result:
- En error page is displayed and user cannot sign in;

#### Notes:
- not reproducing if you are not signed in on the VPN website.
- not reproducing while using Chrome as default browser.
![image_2020_10_22T08_31_19_554Z](https://user-images.githubusercontent.com/15685960/96857858-313a7100-1468-11eb-9e29-9667c829b041.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2629)
┆Issue Number: FXA-2629

**Comment by ValentinaPC** [comment]
We moved this here: https://github.com/mozilla-services/guardian-website/issues/966 .
Closing.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

-> cancelled
