### ISSUE TITLE
Unit tests are slow

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#673]
The unit tests now take about 44 seconds to run on my machine, up from around 25 seconds when I started 8 months ago.

My hunch is that the biggest factor is all the XHR requests made by require.js, so it could be interesting to try running them against a browserified/webpacked bundle (just to be clear, I mean for testing purposes only, I'm not suggesting we ditch require.js).

Another possible cause is all the DOM manipulation that happens in the view tests. If we mocked more aggressively it should help.

Please add your thoughts below if you have other suggestions.

**Comment by clouserw** [comment]
If there are specific things we should modify or discuss let's open separate bugs for them.  Leaving this broad bug open won't help -- it's likely the unit tests could always be faster (or at least we'd like them to be).  Thanks.
