### ISSUE TITLE
Avatar crop UI is uncentered on small screens/mobile

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#674]
child of https://github.com/mozilla/fxa-content-server/issues/6261

(Originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1246138 for the specific case of the first-run flow)

STR: 
- As a logged-in user, visit https://accounts.firefox.com/settings, edit your avatar, and upload a new picture in order to access the /settings/avatar/crop screen.
- Make your window really short.

The resulting cropper UI is off-center like so:
![screen shot 2016-02-08 at 13 06 40](https://cloud.githubusercontent.com/assets/34695/12877289/37e5e46a-ce65-11e5-9584-0d9024a58cc7.png)

If you make the window bigger a different set of styles kick in and it looks fine:
![screen shot 2016-02-08 at 13 06 31](https://cloud.githubusercontent.com/assets/34695/12877297/4b489d36-ce65-11e5-98b9-a7749d3bef00.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-782)
┆Issue Number: FXA-782

**Comment by clouserw** [comment]
Dropping needs:ux -- let's just make the image fit by making it smaller.
