### ISSUE TITLE
/settings page blank while the avatar loads

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#675]
To test #3324, I added a 5 second delay to the response of the avatar fetch. I was surprised to see the settings screen is blank while the avatar loads. The code makes it seem like the avatar fetch occurs in [afterVisible](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/views/settings.js#L148), so I'm a bit confused why this is happening.

![blank-settings-during-fetch-master](https://cloud.githubusercontent.com/assets/848085/12261608/0acdf7ac-b91a-11e5-8cd2-20df94f08ade.gif)

**Comment by clouserw** [comment]
We tested this in triage and I think it is fixed.  A full refresh will show the settings page immediately with a blank avatar, and then the avatar is shown (after it downloads, presumably).
