### ISSUE TITLE
[FxA-Settings] Incorrect Firefox logo displayed on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6763]
****Build**
Stage [Train 1.192.0]

**Affected platforms**
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Check the Firefox logo displayed in the header.

**Expected results**
The correct Firefox logo is displayed.

**Actual Results**
Firefox logo displays a green color.

![Screenshot_1](https://user-images.githubusercontent.com/18114210/97301478-7d1e5900-1860-11eb-9205-fdee8260f2bf.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2667)
┆Issue Number: FXA-2667

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

pretty weird because it's the exact same svg as the one on accounts.firefox.com

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [1.193.0] under iOS 13.6. The correct Firefox logo is successfully displayed.
![Screenshot_34](https://user-images.githubusercontent.com/18114210/98647180-2a9f6b00-233d-11eb-85c6-56c3ee847686.png)
