### ISSUE TITLE
[FxA-Settings] Bento menu content is gray

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6764]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the Bento Menu pictogram displayed in the header.
3. Check the Bento drop-down.

**Expected results**
Bento Menu is displayed without issues.

**Actual Results**
- All the Bento Menu elements are gray.
- Settings redesign links become gray when Bento Menu is opened (Firefox logo, Help icon,  Android and iOS badges).

![Screenshot_7](https://user-images.githubusercontent.com/18114210/97320454-7d295380-1876-11eb-93ef-c0ca73252d23.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2646)
┆Issue Number: FXA-2646

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

What is going on here!? Definitely has to do with the svg targeting, I'm going to go through each svg and comment them out one by one and see if we can narrow it down from there.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.193.0] under Windows 10 64-bit, Android 9 and iOS 13.6.  Bento Menu elements are no longer displayed as gray .(A separate issue was observed about the Google Play Badge that is incorrectly displayed while the Bento Menu is opened - issue tracked by #6866 )
![Screenshot_33](https://user-images.githubusercontent.com/18114210/98573020-ff763680-22be-11eb-85f5-9e1012c73c45.png)
