### ISSUE TITLE
[FxA-Settings] Firefox Monitor icon is not displayed in Bento Menu

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6765]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the Bento Menu pictogram displayed in the header.
3. Check the Firefox Monitor product.

**Expected results**
All the Firefox products displayed their icon.

**Actual Results**
Firefox Monitor icon is not displayed in the Bento Menu.

![Screenshot_8](https://user-images.githubusercontent.com/18114210/97321284-60415000-1877-11eb-83b6-fa88268a2115.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2645)
┆Issue Number: FXA-2645

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

This was fixed in https://github.com/mozilla/fxa/pull/6842, ( https://github.com/mozilla/fxa/pull/6842, ) will be in train 1.193

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.193.0] under Windows 10 64-bit. Firefox Monitor icon is successfully displayed but it is not colored - issue tracked by #6865 
![Screenshot_32](https://user-images.githubusercontent.com/18114210/98570276-f041b980-22bb-11eb-9128-6a1624cee64f.png)
