### ISSUE TITLE
[FxA-Settings] Pocket product is misaligned in Bento Menu

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6766]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the Bento Menu pictogram displayed in the header.
3. Check the Pocket product.

**Expected results**
All the Firefox products are correctly aligned.

**Actual Results**
Pocket element is misaligned compared with the other products from Bento Menu.

![Screenshot_9](https://user-images.githubusercontent.com/18114210/97321889-fbd2c080-1877-11eb-9d88-76feff6fcf26.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2647)
┆Issue Number: FXA-2647

**Comment by data-sync-user** [comment]
➤ bchen@mozilla.com commented:

This has been fixed by a patch for another issue.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.193.0] under Windows 10 64-bit. Pocket element is correctly aligned.
![Screenshot_29](https://user-images.githubusercontent.com/18114210/98567696-e5d1f080-22b8-11eb-912c-0c59e6d416bf.png)
