### ISSUE TITLE
[FxA-Settings] No message error displayed for a very long display name value

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6777]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2.  Click on the "Add" button from "Display name" area.
3. Copy a long text (ie https://whiletrue.neocities.org/lte.html) and paste it into the “Display name” field.
4. Click “Save” button.

**Expected results**
A proper error message saying that the display name is too long is correctly displayed.

**Actual Results**
A red arrow appears over the “Display name” field and there is no error message displayed.

![Screenshot_15](https://user-images.githubusercontent.com/18114210/97424734-d26a7100-1919-11eb-89f7-2539bc19c37c.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2650)
┆Issue Number: FXA-2650

**Comment by dannycoates** [comment]
This looks like some styles didn't build properly. We should start debugging in the build step.

**Comment by vasilicatamas** [comment]
I confirm that the tooltip errors are successfully displayed on Stage [Train 1.193.0] under Windows 10 64-bit, Android 9 and iOS 13.6. "Bad request" errors appears for a very long display name but this is tracked in a separate issue - #6886 

![Screenshot_40](https://user-images.githubusercontent.com/18114210/98681164-0bb7cd80-236b-11eb-961f-da831e73d61a.png)
