### ISSUE TITLE
[FxA-Settings] No error is displayed when inserting 2 different new passwords

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6790]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 x64
iOS 13.6
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Change" button from the Password section.
3. Insert the current password and two different new passwords.

**Expected results**
a) The validation is made inline and the “Passwords do not match” error is automatically displayed. 
b) “Save” button is enabled and the “Passwords do not match” error appears when clicking on the “Save” button.

**Actual Results**
“Save” button remains disabled and no error is displayed.

![Screenshot_20](https://user-images.githubusercontent.com/18114210/97573316-395b5900-19f2-11eb-8f8e-b74957313ff7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2655)
┆Issue Number: FXA-2655

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Preventing the form from being submitable in this case seems like an improvement not a bug. If we do want to show a message when they don't match it should be up with the other validation criteria.

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

we'll add a new item to the validation checklist above the form

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Changed to a Task since this is "new" ui that wasn't part of the original design

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.194.0] under Windows 10 64-bit, Android 9 and iOS 13.6.
![Screenshot_23](https://user-images.githubusercontent.com/18114210/100120603-cb833f80-2e80-11eb-8f49-aaff94c5fa62.png)
