### ISSUE TITLE
[FxA-Settings] Password bullets are displayed different for numbers, uppercase letters and special characters on Android

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6791]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Change" button from the Password section.
3. Type in a password field a password that contains lowercase letters, uppercase letters, numbers and special characters.

**Expected results**
The password bullets are displayed in the same position.

**Actual Results**
The password bullets that hide the numbers, uppercase letters and special characters are displayed for 2 seconds a bit above the lowercase bullets.

![issue23](https://user-images.githubusercontent.com/18114210/97579457-bee30700-19fa-11eb-9f0c-f56aa33111bb.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2656)
┆Issue Number: FXA-2656

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Interesting, but we don't have control over this, it's a browser issue.
