### ISSUE TITLE
FxA-16: UI affordance for devices that need to re-authenticate?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#68]
In the discussion over in #66, we determined that zapping a device's session token via password reset doesn't disconnect it from the account, so it should still show up in the list of devices.  Client-side, the device will enter the "needs reauth" state when it discovers that its session token has become invalid.  Should we show some affordance for such devices in the devices view?  (e.g. grayed out, a little warning icon overlay, whatever)

One wrinkle could be that the server will know the device needs to re-auth before the device itself discovers this, because of client-side caching issues like [1].  So you might see the warning in the devices view, dig out your other device, go to re-auth on there and it tells you that everything's fine.

Alternately, we can just could on such devices failing up update their "last connected" timestamp, and when the users sees "last connected 12 days ago" they'll think "oh, I need to go reconnect that device".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1206325

**Comment by ryanfeeley** [comment]
@rfk Questions:

Can a device still sync with a zapped session token? If no, it should not appear on the list.
If after a password reset, my devices are no longer syncing, can I even "delete" them from the list? Would the clients then stop asking the user to reconnect?

**Comment by rfk** [comment]
> Can a device still sync with a zapped session token?

No, it would be in the "needs to re-auth" state and would not continue syncing (once our various cache timeouts have expired).

> If after a password reset, my devices are no longer syncing, can I even "delete" them from the list?
> Would the clients then stop asking the user to reconnect?

If it's a device into which we build push-notification support, then it could still listen for an explicit "disconnect" message triggered by disconnecting it from the list.

It sounds like it's going to be simpler if we just don't show them in the list, and we can consider a more nuanced take on a "not syncing, but it's still your device" state in a future iteration.

**Comment by ryanfeeley** [comment]
Agreed. The list should contain devices that are syncing because the list is about managing risk.

**Comment by vladikoff** [comment]
ping @ryanfeeley

**Comment by ryanfeeley** [comment]
@vladikoff Ping what? There is no affordance because disconnected devices should not appear in list. Close issue?

**Comment by vladikoff** [comment]
@ryanfeeley sorry it was assigned to you and we were going through the bugs in the meeting. Closing...
