### ISSUE TITLE
[FxA-Settings] Refresh button not displayed for not set and verified secondary email states

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6803]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 16.3

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Check for the “Refresh” button in the secondary email section.
3. Add and verify a secondary email.
4. Check for the “Refresh” button in the secondary email section.

**Expected results**
“Refresh” button is permanently displayed in the secondary email section (as it is in the old Settings page).

**Actual Results**
“Refresh” button is displayed only for unverified state - this is how it was designed for the New Settings page based on [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792), but it would be helpful to have the “Refresh” button displayed all the time in Secondary email section, as there is displayed also for Recovery key and Two-step authentication.

![Screenshot_31](https://user-images.githubusercontent.com/18114210/97715624-4d26be00-1acb-11eb-9075-91bebd66ba17.png)
![Screenshot_32](https://user-images.githubusercontent.com/18114210/97715629-4e57eb00-1acb-11eb-890d-2e333e284913.png)
![Screenshot_33](https://user-images.githubusercontent.com/18114210/97715631-4e57eb00-1acb-11eb-8946-7bccb78b4376.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2662)
┆Issue Number: FXA-2662

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

The designs don't include the refresh button for validated emails. I don't think we're trying to exactly match the functionality of old settings.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~adavis@mozilla.com] confirmed once verified there will be no refresh button. WONTFIX
