### ISSUE TITLE
[FxA-Settings] Recovery key section is not visible while focused using the recovery key link

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6805]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the “Recovery key” link displayed in the “Secondary email” section.

**Expected results**
"Recovery Key" section is correctly displayed.

**Actual Results**
Most of the Recovery key section is not visible because it’s covered by the Settings page header.

![issue27](https://user-images.githubusercontent.com/18114210/97717344-5add4300-1acd-11eb-9c25-3fa07e38c131.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2664)
┆Issue Number: FXA-2664

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Windows 10 64-bit and Android 9, but it seems that is still reproducible on iOS 13.6. Reopening.
![issue32](https://user-images.githubusercontent.com/18114210/98645522-c67ba780-233a-11eb-9835-5385207b2135.gif)

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

im moving to v2 because ios is not high priority

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

oops assigned this to myself before noticing that it's an iOS issue.  /me doesn't have teh iOS

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

not a 1. ios safari doesn't properly support scroll-margin

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Good news! This bug is fixed for me on Firefox for iOS 14.3. Closing.
