### ISSUE TITLE
[fxa-event-broker] Persist events to data store

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#683]
* Blocked by #682.

Going to try BigQuery in the first instance. There is a [`google_bigquery2` crate](https://docs.rs/google-bigquery2), which might be useful. For local dev we'd need to authenticate with a [service account](https://cloud.google.com/docs/authentication/).

**Comment by philbooth** [comment]
@bbangert pointed out that rather than persisting the events to a dedicated store, we could just push them on to relier-specific queues instead and have the queue act as storage. The retry logic on the other end would then continue for as long as the queue retains the unprocessed events.

**Comment by bbangert** [comment]
AWS SQS has default retention of 4 days, but if the queue/message (not sure which) includes a flag, then the message retention can be 14 days. I should hope a RP can get back online to take events within that time period. If we move someday to GCP Pub/Sub, their max message retention is 7 days.

**Comment by bbangert** [comment]
Deprecated for #1268.
