### ISSUE TITLE
Can't change debugging server to stage for the firefox private network extension

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#6858]
#### Description

The QA team is blocked from testing how a new created subscription on stage environment works with the FPN Extension

The FPN extension, by default, points to the production server. We use a management extension to make the fpn extension point to the staging environment and to be able to use a subscription created in there.
At this moment that management extension does not work any more for us and we do not have another way to make the FPN extension point to stage.

We need a solution for this issue or we will not be able to cover some scenarios when running our fxa train tests. I'm adding the blocker label as this is currently blocking the QA team.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2671)
┆Issue Number: FXA-2671

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~amarchesini@mozilla.com] I understand this is something you are working to resolve, is that correct? Is there anything we need to do to assist from the FxA side?

**Comment by clouserw** [comment]
I think this needs to be filed in mozilla-extensions/secure-proxy.  I can't move it since it's a different org

**Comment by clouserw** [comment]
I manually refiled this at https://github.com/mozilla-extensions/secure-proxy/issues/938 and closing this
