### ISSUE TITLE
[FxA-Settings] Incorrect Google Play Icon while the Bento Menu is displayed

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6866]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 64-bit

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the Bento Menu.
2. Scroll down at the bottom of the page and check the Google Play badge.

**Expected results**
The correct Google Play Icon is displayed - see figma.

**Actual Results**
Google Play icon displays a pink triangle.
![issue31](https://user-images.githubusercontent.com/18114210/98572452-53345000-22be-11eb-8506-b442ffc5d381.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2674)
┆Issue Number: FXA-2674

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

😂

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

This one is pretty funny tbh. The cause is that we have svgs that each define gradients but use the same sequential naming scheme, a,b,c... so as new ones get added to the dom they change the gradients for all svgs on the page

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.194.0] under Windows 10 64-bit, Android 9 and iOS 13.6. Google Play logo is correctly displayed.
![issue45](https://user-images.githubusercontent.com/18114210/99998625-a5e62f80-2dc7-11eb-88cf-7c769e63e47d.gif)
