### ISSUE TITLE
/graphql endpoint uses non-standard Authorization without a type

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6870]
The GraphQL server accepts headers with the non-standard form:
 Authorization: <hex string session token> 
However, an additional type parameter is in [the standard form|
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization]:
Authorization: <type> <credentials>

Informational / no security risk. 

Recommendation:

Add a standard (e.g. Bearer) or custom type (e.g. Hawk) to the authorization header or use a different header

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2677)
┆Issue Number: FXA-2677

**Comment by dannycoates** [comment]
done
