### ISSUE TITLE
[FxA-Settings] Firefox logo changes its appearance in Bento Menu on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6885]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the Bento Menu.
3. Tap on one of the Firefox products displayed in Bento Menu.
4. Focus again the FxA Settings tab.

**Expected results**
a) The correct Firefox logo is displayed in Bento Menu.
b) Bento Menu is closed when a new page is opened in a different tab. (as it happens for Firefox Monitor Bento Menu)

**Actual Results**
The Firefox logo displays a blue circle at the bottom of the icon.

![issue34](https://user-images.githubusercontent.com/18114210/98658185-70633000-234b-11eb-81e9-7c3d0c16db84.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2687)
┆Issue Number: FXA-2687

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

fixed in https://github.com/mozilla/fxa/pull/6878

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.194.0] under iOS 13.6. The correct Firefox logo is displayed in Bento Menu.

![issue48](https://user-images.githubusercontent.com/18114210/100119158-3af82f80-2e7f-11eb-9b5d-738b59ba157b.gif)
