### ISSUE TITLE
Reinstate the precommit hooks

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#689]
In the auth server, there is a precommit hook that bumps the template version numbers when they change. Let's make sure it still works.

I don't know what other hooks we have, but we should check those are operating correctly too.

("operating correctly" includes not running when they don't have to)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-783)
┆Issue Number: FXA-783

**Comment by philbooth** [comment]
At least in the case of the temlate version-bumping hook, it's not working for me. Having a look now, although maybe it makes sense to do #694 before fixing this.

**Comment by philbooth** [comment]
So I've looked at the way husky works and essentially it puts our hooks in contention against one another. When run, it iterates the parent directories until it finds a git repo and installs the hooks there. That means, for instance, the content server linters are always run, even when you're doing auth server work.

Also, for a reason I haven't identified yet, the auth server `precommit` hook never runs for me. So for now we have to remember to manually bump the version numbers when we update a template.

I find this situation pretty annoying. We could try updating the content server hook so it takes `$PWD` into account. And we could try working out why the auth server hook never runs.

Or we could remove the hooks and spend time on more productive work. I lean towards the latter option.

**Comment by philbooth** [comment]
As these were removed in #758, let's use this issue for fixing them and bringing them back instead.

**Comment by shane-tomlinson** [comment]
@dannycoates says we need to move Husky to the top level.
