### ISSUE TITLE
[FxA-Settings] 2FA QR code is displayed with delay

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6891]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from "Two-step authentication" area.
3. Check the page elements.

**Expected results**
2FA QR code is instantly displayed.

**Actual Results**
2FA QR code appears after a few seconds.

![issue39](https://user-images.githubusercontent.com/18114210/98712292-cad1b000-238e-11eb-9997-f139c30fdedc.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2692)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15326/issue88.gif">issue88.gif</a>
┆Issue Number: FXA-2692

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

To fix this add a fixed height so the page doesn't jump around

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this issue on Stage [1.200.0] under Windows 10 64-bit, macOS 10.14.6 and iOS 13.6 and I can confirm that the 2FA Step 1 of 3 page is automatically displayed at its normal height but the QR code is still displayed with delay. Reopening

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

We concluded that the delay is acceptable. The existing behavior is as far as we're going with this issue.
