### ISSUE TITLE
[FxA-Settings] 2FA Step 2 of 3 page incorrectly displayed on mobile

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6892]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from "Two-step authentication" area.
3. Scan the OR and type the provided code.
4. Click “Continue” button.
5. Observe how the “2FA Step 2 of 2” separate page is displayed.

**Expected results**
The entire “2FA Step 2 of 3” form is in focus. 

**Actual Results**
The header of the “2FA Step 2 of 3” form is not visible.

![Screenshot_46](https://user-images.githubusercontent.com/18114210/98715544-fc4c7a80-2392-11eb-8253-d3acc06be256.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2693)
┆Issue Number: FXA-2693

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

WONTFIX - either solution in this case is not ideal, but we feel the current solution is better from a usability standpoint than the alternative.
