### ISSUE TITLE
[FxA-Settings] “Back” button displayed instead of “Cancel” button in 2FA Step 3 of 3 screen

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6898]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from "Two-step authentication" area.
3. Scan the OR and type the provided code.
4. Click “Continue” button.
5. Save the codes and click the “Continue” button.
6. Check the 2FA Step 3 of 3 page elements.

**Expected results**
“Cancel” button is successfully displayed - see [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792)

**Actual Results**
- “Back” button is displayed instead of "Cancel" button. There are actually 2 back buttons, the arrow one and the "Back" button that do different actions.
- This issue depends on #6897

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2695)
┆Issue Number: FXA-2695

**Comment by data-sync-user** [comment]
➤ bchen@mozilla.com commented:

The reason for this is that it'd match the steps currently in content server.  I thought the figma mockup was incorrect so I did not follow it.  The figma mockups seem to be have copy & pasted content that aren't always accurate.  But maybe I'm interpreting it too much.

[~pwalmsley@mozilla.com] on step two of the 2fa three step form, should that be a Back or Cancel button?

**Comment by vasilicatamas** [comment]
I would say that the mock-ups should be followed only if the #6897 will be fixed otherwise we should maintain the current implementation and keep the “Back” button.

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

The back arrow acts like the back button in the browser. It just steps back through the flow. The grey button next to the blue continue button should always read "Cancel" and that will return you back to the top level without saving or completing anything. Let me know if that is unclear or causes any issues.

**Comment by data-sync-user** [comment]
➤ bchen@mozilla.com commented:

I'm going to split out the back arrow part of this since that's part of the FlowContainer and it affects all the multi-step forms.  (There are only two so far: recovery key and 2fa.)  We need to refactor the forms and/or add more functionality to the FlowContainer to control the behavior of that back button.  Or hide it altogether?  Does it make sense to "go back" a step on the final step of the recovery key form anyway?

**Comment by data-sync-user** [comment]
➤ bchen@mozilla.com commented:

My bad, secondary email also has multiple steps.

**Comment by vasilicatamas** [comment]
This issue is verified as fixed in Stage [Train 1.194.0] under Windows 10 64-bit, Android 9 and iOS 13.6. "Cancel" button is successfully displayed in Step 3 of 3 2FA page.

![Screenshot_28](https://user-images.githubusercontent.com/18114210/100131678-068b7000-2e8d-11eb-901f-9f48b81ceec7.png)
