### ISSUE TITLE
[FxA-Settings] 2FA “Change” and “Disable” buttons are not correctly aligned on mobile

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6899]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Enable the 2FA.
3. Check how “Change” and “Disable” buttons are displayed.

**Expected results**
2FA “Change” and “Disable” buttons are correctly aligned compared with the other buttons from the Settings page.

**Actual Results**
- 2FA “Change” and “Disable” buttons are displayed a bit to the right.
- This might be regressed by #6795.

![Screenshot_49](https://user-images.githubusercontent.com/18114210/98796797-7709aa00-2414-11eb-9594-7e8d3e2f7586.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2697)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15365/Screenshot_14.png">Screenshot_14.png</a>
┆Issue Number: FXA-2697

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this issue on Stage [Train 1.201.0] under Android 9, Android 11 and iOS 13.6 and noticed that the 2FA Disable button is still misaligned compared to the others buttons. I am attaching a recent screenshot. Reopening
