### ISSUE TITLE
[FxA-Settings] Change recovery codes incorrect button text

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6900]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Enable the 2FA.
3. Click on “Change” button from 2FA section.
4. Check the buttons displayed in “Change recovery codes” modal.

**Expected results**
“Change codes” button is successfully displayed - see [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792)

**Actual Results**
“Codes” word is omitted from the “Change codes” button.

![Screenshot_50](https://user-images.githubusercontent.com/18114210/98798087-2004d480-2416-11eb-8a35-520d3305516d.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2696)
┆Issue Number: FXA-2696

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~adavis@mozilla.com] How much does it matter if the button says "Change" versus "Change codes"?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

This is fine since it aligns well with the headline. It can remain "Change".

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

thanks
