### ISSUE TITLE
[FxA-Settings] Avatar icon disappears after clicking on “Sign Out” button

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6918]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the avatar drop-down.
3. Click on the “Sign out” button.

**Expected results**
Avatar icon is successfully displayed in the Settings page header. 

**Actual Results**
Avatar icon disappears from the header during the sign out process.

![issue43](https://user-images.githubusercontent.com/18114210/98945276-fa9dc680-24fa-11eb-9c94-60d61274e105.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2706)
┆Issue Number: FXA-2706

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue was verified as fixed on Stage [Train 1.203.2] under Windows 10 64-bit, Android 9 and iOS 14.4. The avatar icon is successfully displayed in the Settings page header during the sign-out process.
