### ISSUE TITLE
entrypoint_experiment and entrypoint_variation query parameters not getting passed to amplitude

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#6925]
@rlr and Danica were trying to run an experiment on VPN/fxa using the `entrypoint_experiment` and `entrypoint_variation` query parameters, using URLS like this

```
https://accounts.firefox.com/oauth/signin?client_id=e6eb0d1e856335fc&redirect_uri=https%3A%2F%2Ffpn.firefox.com%2Foauth%2Fsuccess&scope=profile&response_type=code&state=redacted&access_type=offline&action=email&utm_content=cro&entrypoint_experiment=price-display&entrypoint_variation=under-cta
```

However I am no seeing [them in amplitude](https://analytics.amplitude.com/mozilla-corp/chart/new/vq0ooxx) and I am not seeing them [in the bigquery logs either](https://console.cloud.google.com/bigquery?sq=630180991450:1bef47309ba840c3b2f942d24c14a015).

The values for the query parameters seem like they meet the regex filters [described here](https://mozilla.github.io/ecosystem-platform/docs/relying-parties/metrics-for-relying-parties) so I'm not sure what else might be preventing them from being logged.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2711)
┆Issue Number: FXA-2711

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing.  It looks like the regex filter ( https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/flow-event.js#L43 ) is actually `/^[\w.-]+$/` but that shouldn't affect what you're trying to do.  I'll update the docs to be correct.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

[~loines@mozilla.com] I'm still digging around and trying to reproduce, we do have [filtering for doNotTrack](https://github.com/mozilla/fxa/blob/e922a95fa6a32a271356c531c1c1d8455aef8a3d/packages/fxa-auth-server/lib/metrics/context.js#L170) ( https://github.com/mozilla/fxa/blob/e922a95fa6a32a271356c531c1c1d8455aef8a3d/packages/fxa-auth-server/lib/metrics/context.js#L170) ) setup, which could be filtering out all of these metrics

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

I confirm that I don't see anything for that value of `entrypoint_experiment`:

https://analytics.amplitude.com/mozilla-corp/chart/new/2fe4j1d ( https://analytics.amplitude.com/mozilla-corp/chart/new/2fe4j1d )

TBH, marketing is the only one that uses that property normally and I only see them having used it a couple of times, in 2019.

When I look for some of the other parameters they're passing like `utm_content=cro`, I do see authentications for that value relating to VPN:
https://analytics.amplitude.com/mozilla-corp/chart/new/4ien2ec ( https://analytics.amplitude.com/mozilla-corp/chart/new/4ien2ec )

I see a couple of options. 
 1) We could fix the `entrypoint_experiment` if the VPN team plans to use it a lot. It's unclear when we could prioritize this.
 2) The utm parameters work so they could use those if they'd like a plan B that works now. (and perhaps until we fix it)

**Comment by chrismore** [comment]
Going forward, the VPN team will use be two main acquisition and activation optimization tactics:

1) Using attribution data from top of the funnel and all the way into the active customers, to tune and optimize marketing channels and paid media. The attribution data will give us the ability to do CAC:LTV ratio analysis for paid marketing and our paid product. The attribution data today uses UTM parameters as the key:value paid of how customers are coming to find our product.

2) A/B testing each step of the funnel to optimize for conversion rate, funnel rate, and retention. 

Given the two tactics above, we want to make sure that any A/B testing of the landing page and funnel doesn't impact our ability to do attribution with UTM parameters or that A/B testing doesn't clobber and overwrite those UTM parameters. Changing the UTM parameters will impact our ability to tune our performance marketing.

If there is another method to capture experiment data without impacting UTM parameters, it will be very helpful to the future growth strategies and tactics of the Mozilla VPN.

Thanks!

**Comment by Danica076** [comment]
To answer this question @davismtl. Are you referring to utm_source, utm_content, utm_campaign, utm_medium, utm_term? We cannot use these standard utms for experiments because it will override their original source of truth. That's why we requested the experiment metric parameters.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

> If by chance, you don't plan to use all of them [utm params], you could recycle the remaining ones for differentiating your landing pages. It's not ideal but maybe the best stopgap.

This is the key sentence. ⬆️

If you actively use all 5 utm parameters then this proposed temporary solution won't work for you. You are right, it will overwrite another value. 
But if you don't tend to use utm_term (for example), you could use it to specify an experiment and its variation (e.g. utm_term=experiment_[0-9]_[a-z]). This is what marketing did for years prior to us adding the experiment properties.

If you'd prefer to not do that then you'll have to wait until we fix the experiment properties. Again, just trying to provide a stopgap.

**Comment by Danica076** [comment]
@davismtl Sorry for the delay in reply, I thought I posted the comment but it seems like it didn't get sent out. We had some internal discussions and found that the Google Search campaign will use utm_term and the marketing team is planning to launch campaigns soon so we couldn't use this as well. We will have to wait until we fix the experiment properties. Thanks for providing some alternatives. Please let us know if there's an ETA on the fix.

**Comment by chrismore** [comment]
@davismtl given that the marketing team will be using all 5 UTM parameters for their campaigns, what are the next steps here on having a parameter that is passed through that we can segment cohorts without clobbering attribution? thanks!

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

I just opened a pr to fix this(thanks to [~vbudhram@mozilla.com] for helping me track it down), do we need to put this into a point release? or can it wait for next regular release?

https://github.com/mozilla/fxa/pull/7216

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is scheduled to go out on Jan 20 in Train 198.  Let's land it and assume that is fine.  If this needs to go out sooner please ping me on Slack to chat.  Thanks.
