### ISSUE TITLE
[settings] Missing sign out buttons for OAuth RPs on Connected Services

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6936]
STR (locally):

1. sign in
1. sign into 123Done
1. go to new settings

Expected: 123Done is listed and has a button for signing out

Actual: the sign out button is missing

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2713)
┆Issue Number: FXA-2713

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

I don't think we ever had an issue for hooking up this button, we had one for creating a dummy button https://jira.mozilla.com/browse/FXA-1760, maybe we should throw this into settingsv2 version

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.194.0] under Windows 10 64-bit, Android 9 and iOS 13.6. "Sign out" button is successfully displayed for 123Done.

![Screenshot_25](https://user-images.githubusercontent.com/18114210/100123183-e951a400-2e82-11eb-8fc9-ba4e4fdc1ddb.png)

**Comment by vasilicatamas** [comment]
Checked again the [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792) mock-ups and I'm not sure if the "Sign Out" button should be displayed. Filed #7002 for further discussions.
