### ISSUE TITLE
[Settings] Allow Override of FlowContainer's Back Button's Behavior

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6937]
From FXA-2695 (or maybe more specifically [https://github.com/mozilla/fxa/issues/6898#issuecomment-726893745](https://github.com/mozilla/fxa/issues/6898#issuecomment-726893745) in the issue), we learn that the FlowContainer's back button, when on a multiple step form, should move back a step in the form.

Since our multi-step forms are driven by the state within a component without any routing between the steps, that back button does not work as expected by QA and UX.

The simplest solution is probably to allow overriding the onclick behavior of that back button.

This task is for updating the FlowContainer to accept the overriding onclick function.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2714)
┆Issue Number: FXA-2714

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.194.0] under Windows 10 64-bit, Android 9 and iOS 13.6. “Back” arrow button successfully takes the user to the previous step.

![issue62](https://user-images.githubusercontent.com/18114210/100454933-86e8e580-30c6-11eb-8572-58179070ff84.gif)
