### ISSUE TITLE
Triage package.jsons' dependencies

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#694]
Which dependencies can be promoted to the parent package.json, removed, or updated? Should inter-dependencies within `packages` be symlinks, ala `npm link` or [lerna link](https://github.com/lerna/lerna/tree/master/commands/link#readme)?

**Comment by philbooth** [comment]
> removed

Related: #733.

**Comment by philbooth** [comment]
> Should inter-dependencies within `packages` be symlinks...

+1 if it's straightforward (I confess I have no idea what `npm link` or `lerna link` do and I'm too lazy to type `npm help link`)

**Comment by philbooth** [comment]
> removed

Related: #758

**Comment by philbooth** [comment]
Also, as part of this, should we replace `npm-shrinkwrap.json` with `package-lock.json` in those directories that have the shrinkwrap file?

**Comment by shane-tomlinson** [comment]
> Also, as part of this, should we replace npm-shrinkwrap.json with package-lock.json in those directories that have the shrinkwrap file?

Yes.

**Comment by dannycoates** [comment]
closing in favor of #2579
