### ISSUE TITLE
FxA Sign-in: "Use a different account" link doesn't appear on Fenix on a 3rd login

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla/fxa#6944]
## Description
Cannot change saved user credentials to login with a different account.
### Steps to reproduce
1. Login with an account on Fenix Android.
2. Sign out.
3. Go back to Turn on Sync and check that the user account is pre-filled.
4. On the Sign-in page, check if "Use a different account" is displayed. 
5. Proceed to sign in with the saved account. Sign out again.
6. Go back to Turn on Sync and try to sign in with a different email. Check again if "Use a different account" is displayed.

### Expected result

The option to change the user account is available every time.

### Actual result

"Use a different account" isn't displayed on a 3rd try to login. Cannot log in with a different account than the one saved.
Restarting the app solves the issue.

### Environment
Android, Fenix RC: 83.1.0-rc2

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2716)
┆Issue Number: FXA-2716

**Comment by 6a68** [comment]
@sv-ohorvath Hi, are you sure this is an FxA bug, and not a Fenix bug? CC @grigoryk for any input here

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~bfleming@mozilla.com] this doesn't feel like fxa-related to us, we're expecting it's on the Fenix side per our triage. Could you take a look?

**Comment by rfk** [comment]
It would be useful to find out if the URL loaded at step (4) is different from the one loaded at step (6), and if so how.

**Comment by vasilicatamas** [comment]
- "Use a different account" option is successfully displayed on the following page: https://accounts.firefox.com/oauth/signin?action=email&response_type=code&entrypoint=android-components&client_id=a2270f727f45f648&scope=profile%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync%2Bhttps%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&state=KXUiBTWPtqvgC4WhV6gDiw&code_challenge_method=S256&code_challenge=2B1ApoRGAI2LZa66ksjyTcl20rDHdy8peSQeqoarjmE&access_type=offline&keys_jwk=eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6IkF1SlhyODgtblpyZVlFbWlXS2RZekE4ZUVlT1hNeXpuRHdmN3pRNVpsSTAiLCJ5IjoiOHV5aTdSa1lpM3ZOQng2WkdJWnNpMS0xVFY3SnV6Ty01UDdjbnRZUGx6dyJ9&context=oauth_webchannel_v1

- "Use a different account" option does not appear when  the following URL is loaded:  https://accounts.firefox.com/oauth/force_auth?action=email&response_type=code&entrypoint=android-components&email=vtamas%2B244%40mozilla.com&client_id=a2270f727f45f648&scope=profile+https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync+https%3A%2F%2Fidentity.mozilla.com%2Ftokens%2Fsession&state=b-nei5QcfAYJ8KDPngcOQg&code_challenge_method=S256&code_challenge=gKG9v9pQ7HxIraqrHAfhxNQ6xlx9nI29M6r00JgrRig&access_type=offline&keys_jwk=eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6InFvSGw5V1kzbmFZSXpsTHNseVhxVC1iVklnbnRsRE84XzJwLWRreGIyNUkiLCJ5IjoiMHhIU3RsQ0hic3lmbE42cXdEMDc1V3ItaGE3RjBrLXNQaGdVYmEtQVpIcyJ9&context=oauth_webchannel_v1
