### ISSUE TITLE
[content-server][tests] Fix CI and failing server tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6955]
The content-server server tests have been failing for some time.  We have not noticed because the pairing tests that run after the server tests return an exit status 0.

There are two things to do here:

1. Fix the tests, if the failure are valid
1. Update CI script(s) so that we'd know about future failures

The test failures are reproducible locally.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2718)
┆Issue Number: FXA-2718

**Comment by chenba** [comment]
Closed by PR #6990
