### ISSUE TITLE
[content-server][metrics] Stop emitting 'client.metrics' metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6960]
These are logged to stderr on the content-server on "sampled users".  However, the feature's been disabled on our envs (env var: DISABLE_CLIENT_METRICS_STDERR).  We should remove them from the code to reduce confusion around our metrics.

This is a sibling issue of FXA-2598 / GH #6621.  They can be worked on together.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2719)
┆Issue Number: FXA-2719

**Comment by chenba** [comment]
@jbuck @davismtl @irrationalagent @6a68 Chime in here if I'm incorrect about client metrics here.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Seems like something we could lump in with settings v2
