### ISSUE TITLE
[FxA-Settings] Avatar needs email address?

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#6982]
## Description
Should the email address be included along with the username, or did we decide not to have it in addition to the username (if any)? I thought for security @davismtl included it as a requirement.

![Screenshot_2020-11-19 Firefox Accounts(3)](https://user-images.githubusercontent.com/6219141/99708606-0bef5180-2a6c-11eb-8563-ac79bf67c522.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2841)
┆Issue Number: FXA-2841

**Comment by davismtl** [comment]
Normally it would be important to put (and if we can add it to make sure it remains a best practice, great) but I don't have any concerns at this moment because the email is permanently visible elsewhere in the settings page.

And, welcome back @janiceahn !
