### ISSUE TITLE
[payments] react-stripe-elements called before Stripe.js is loaded

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#6993]
From https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/10024443/

> Error: Please load Stripe.js (https://js.stripe.com/v3/) on this page to use react-stripe-elements. If Stripe.js isn't available yet (it's loading asynchronously, or you're using server-side rendering),  ...

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2726)
┆Issue Number: FXA-2726

**Comment by chenba** [comment]
Note that we are not loading Stripe.js async.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/11391063/?query=is%3Aunresolved
