### ISSUE TITLE
Refactoring test code 

### ISSUE THREAD

**Issue by Cronus1007** [mozilla/fxa#6997]
- Operating System: N/A

- Operating System: N/A

- NPM Version: N/A

**Modification Proposal**
Currently, https://github.com/mozilla/fxa/blob/main/packages/fxa-profile-server/test/api.js  has almost 2000 lines. It's hard to read because test code has many {}. I want to divide it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2727)
┆Issue Number: FXA-2727

**Comment by Cronus1007** [comment]
cc @bbangert  @chenba

**Comment by chenba** [comment]
@Cronus1007 by "divide it" do you mean simply split the single file into multiple files?  Or do you plan to de-duplicate some of the code?  (If, in fact, there's duplicated code.)

**Comment by Cronus1007** [comment]
@chenba  We have multiple **describe** sections, and we can move each section to own file

**Comment by clouserw** [comment]
Hi @Cronus1007 .  Thanks for filing this issue.  This file might be unwieldy at first glance, but the length of the files isn't a top concern for us right now.  If there aren't duplicate tests in it, then it's best we focus on other functionality issues.  I'm going to close this.  

Please check out the good first issue label if you're looking for some other issues.  Thanks!  https://github.com/mozilla/fxa/labels/good%20first%20issue
