### ISSUE TITLE
The Mozilla VPN app is not listed correctly in FxA Manage Account-> Devices & Apps section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#7001]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.194.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with active subscription for the Mozilla VPN product;
- Have an Android device available.

 #### Steps to reproduce:
1. Open VPN on your Android device;
2. Tap “Get Started” and finalize sign in with success;
3. Go to VPN app and access Settings->“Manage account”;
4. Check out the “Devices & Apps” list;
5. Find the VPN app;

#### Expected result:
- The “Mozilla VPN” app is listed together with a specific icon and operating system.

#### Actual result:
- The “Firefox Private Network” name and specific icon is displayed instead.

#### Note:
- The Mozilla VPN app is not listed there, no matter from what operating system is turned on.
![Devices apps1](https://user-images.githubusercontent.com/15685960/100213038-ce307400-2f16-11eb-9edc-84e9e3244023.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2730)
┆Issue Number: FXA-2730

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Can this be reproduced in production?  I think this might be a staging naming issue.

**Comment by ValentinaPC** [comment]
@clouserw yeah, it seems you are right and this is happening only in staging.
Below you have a screenshot from production:
![image](https://user-images.githubusercontent.com/15685960/100878036-516f3e00-34b2-11eb-95e9-c9afc991720a.png)

**Comment by chenba** [comment]
There can be a disconnect between the subscription product, which has its name in Stripe, and an OAuth client, which has its name as part of its OAuth client config.  I think it's likely that the stage VPN client is using the FPN OAuth client config....

Now that I'm typing this out, I'm getting deja vu.  I think we have preciously closed a similar bug.

**Comment by chenba** [comment]
Got confirmation that the name of the OAuth client was not updated the product was re-branded to Mozilla VPN.
