### ISSUE TITLE
[FxA-Settings] “Sign out” button should not be displayed for Firefox Services

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7002]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
iOS 13.6
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Connect to several Firefox Services: AMO, VPN, Mozilla email preferences
3. Return to account settings page and select the Refresh button from Connected Services section.

**Expected results**
“Sign out” button is not displayed for Firefox services - as per [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792).
![Screenshot_33](https://user-images.githubusercontent.com/18114210/100214253-55cab280-2f18-11eb-9671-5cd669e16ed2.png)

**Actual Results**
“Sign out” button is displayed for Firefox services.

![Screenshot_32](https://user-images.githubusercontent.com/18114210/100214255-57947600-2f18-11eb-9060-cda33b94c79f.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2731)
┆Issue Number: FXA-2731

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] This seems like something we should change in Figma.  I think having a Sign Out button for all RPs is a good thing.  Thoughts?

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

Agreed! Sign out buttons for all RP is a good thing.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you.  Closing this
