### ISSUE TITLE
[FxA-Settings] Long Device name incorrectly displayed in Connected Services section

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7004]
**Build:**
Stage [Train 1.194.0]

**Affected platforms:**
Windows 10 x64
Android 9 
iOS 13.6

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox Account.
2. Navigate to about:preferences#sync and click on “Change Device Name...” button.
3. Type a long name and click on “Save” button.
4. Navigate to https://accounts.stage.mozaws.net/beta/settings/ 
5. Notice how device’s name is displayed in Connected Services section.

**Expected results:**
a) A long device name is displayed on multiple lines
b) A limited number of characters interrupted by ellipsis is displayed for device name in Devices & apps section.

**Actual Results:**
The device name is displayed outside the Connected Services section.

![Screenshot_35](https://user-images.githubusercontent.com/18114210/100218360-544fb900-2f1d-11eb-9a6d-a16d86823557.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2733)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16338/long+name+new+situation.PNG">long name new situation.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/16337/new+situation.png">new situation.png</a>
┆Issue Number: FXA-2733

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is no longer reproducible on Production [1.207.1] under Windows 10 64-bit, Android 11 and iOS 14.4. Closing.
