### ISSUE TITLE
[FxA-Settings] Different focus borders for “Google Play” and “App Store” badges

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7005]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Windows 10 x64
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the “Google Play” and “App Store” links in new tabs. 
3. Observe the badges focus borders. 

**Expected results**
Both badges have the same focus border shape.

**Actual Results**
 “Google Play” and “App Store” have different focus borders.

![Screenshot_38](https://user-images.githubusercontent.com/18114210/100227515-f1185380-2f29-11eb-8ac8-91c98f99b30a.png)
![Screenshot_39](https://user-images.githubusercontent.com/18114210/100227517-f1b0ea00-2f29-11eb-9168-04df568824a2.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2734)
┆Issue Number: FXA-2734

**Comment by chinmaym07** [comment]
Hey @vasilicatamas can I try this .?

**Comment by prianka01** [comment]
@vasilicatamas Hi, I would like to do it being new to the open source community.

**Comment by prianka01** [comment]
@vasilicatamas Hi, I would like to work on this issue, being new to the open-source community. I have looked at the code and found a solution. Can you please tell me how to proceed in it (like the tasks)?

**Comment by UTKARSH5038** [comment]
Hello everyone  I am a beginner , can anyone please suggest the folder in which the code is written as I am unable to find

**Comment by jodyheavener** [comment]
Some more context: The App Store image has a p-2 class, but the Play Store image doesn't. This creates different click areas and focus outlines, and also pushes the badges in from the right. I think the p-2 is just being used for spacing, so let's replace it with ml-2

**Comment by rustproofed** [comment]
Hello @jodyheavener I'm an Outreachy Applicant. If this still needs to be resolved I would love to work on it!

**Comment by jodyheavener** [comment]
@rustproofed Sounds good, I've assigned it to you.

**Comment by LZoog** [comment]
Hey @rustproofed, we'll go ahead and unassign you from this issue. If you're still interested in working on it please let us know, thanks!

**Comment by Deek9399** [comment]
Hi @LZoog, Can I try this?
