### ISSUE TITLE
[FxA-Settings] No difference between hover and click effects of Bento menu

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7008]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Hover using the mouse cursor over the Bento menu icon displayed in the header.
3. Click on the Bento menu.

**Expected results**
“Bento” menu successfully displays different effects for hover and click actions.

**Actual Results**
There is no difference between hover effect and click effect.

![issue51](https://user-images.githubusercontent.com/18114210/100243817-f764fa80-2f3e-11eb-9b8c-8f58a967afdc.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2737)
┆Issue Number: FXA-2737

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Does figma show different effects?  Otherwise this is by design, I think?

[~pwalmsley@mozilla.com] for comment

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

This is by design. When you click, the menu opens and the button state stays clicked until you navigate or click away from it.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks.  Closing.
