### ISSUE TITLE
[FxA-Settings] The icons are displayed with delay in Bento menu

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7009]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the Bento menu.
3. Observe how the Firefox Services icons are displayed.

**Expected results**
Firefox Services icons are automatically displayed when the Bento menu is opened.

**Actual Results**
Firefox Services icons from Bento menu are displayed with delay at first opening attempt. 

![issue52](https://user-images.githubusercontent.com/18114210/100246653-131dd000-2f42-11eb-8e15-6a1e97a23efa.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2738)
┆Issue Number: FXA-2738

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Lets fill in a width so the page doesn't jump around and then close this.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is still reproducible on Stage [Train 1.121.0] under Windows 10 64-bit, Android 9 and iOS 14.4. The Firefox Services icons from Bento menu are still displayed with delay at first opening attempt. Attaching a recent screencast. Reopening.
