### ISSUE TITLE
[FxA-Settings] FxA Bento menu content is different than Monitor Bento menu one

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7010]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the Bento menu displayed in the header.
3. Navigate to https://monitor.firefox.com/ and open the Bento menu.
4. Compare the Firefox Services displayed in both menus.

**Expected results**
The same Firefox Services are displayed in both Bento menus 

**Actual Results**
FxA bento menu displays “Firefox Lockwise” instead of “Mozilla VPN” service.

![Screenshot_40](https://user-images.githubusercontent.com/18114210/100251110-0fd91300-2f47-11eb-89d0-7773c10334a5.png)
![Screenshot_41](https://user-images.githubusercontent.com/18114210/100251112-1071a980-2f47-11eb-91ee-f5e9f6b334fd.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2739)
┆Issue Number: FXA-2739

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~adavis@mozilla.com] should we be promoting the VPN instead of lockwise?  /cc [~pwalmsley@mozilla.com]

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

We could. Lockwise is in a bit of a limbo state so the VPN would make sense.

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

Yep, agreed.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~adavis@mozilla.com] What should the URL for the link be?  We want some proper marketing related params in it I'd think?

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [1.200.0] under Windows 10 64-bit, macOS 10,14,6, Android 9 and iOS 13.6. FxA bento menu successfully displays "Mozilla VPN” instead of “Firefox Lockwise” .
