### ISSUE TITLE
[FxA-Settings] Incorrect pressing button state on Settings page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7011]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1.Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2.Click on any button from the page.

**Expected results**
The correct pressing button state is successfully displayed - gray button with dark gray borders.

![Screenshot_42](https://user-images.githubusercontent.com/18114210/100254746-5fb9d900-2f4b-11eb-9d63-c59005f95f75.png)

**Actual Results**
The buttons display a white color with dark gray borders on click. 

![Screenshot_43](https://user-images.githubusercontent.com/18114210/100254759-63e5f680-2f4b-11eb-958a-9a2d8c72a275.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2740)
┆Issue Number: FXA-2740

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

this seems to be working as of now
