### ISSUE TITLE
[FxA-Settings] Website Privacy Notice and Terms of Services clickable spaces are extended to the entire width of the footer

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7012]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Scroll down at the bottom of the page.
3. Tap near the “Website Privacy Notice” or “Terms of Services” links.
4. Return to Settings page and check the links focus borders.

**Expected results**
The clickable spaces only encompass the text of the link.

**Actual Results**
The clickable spaces are extended to the entire width of the footer.

![Screenshot_44](https://user-images.githubusercontent.com/18114210/100365317-fd72de00-3007-11eb-9b8d-e5f8caa46997.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2741)
┆Issue Number: FXA-2741

**Comment by vasilicatamas** [comment]
This issue also reproduces for "Forgot password" link from Change password page: 
![Screenshot_47](https://user-images.githubusercontent.com/18114210/100385288-dbd71e00-302a-11eb-8a41-dd4a3c574f95.png)

**Comment by chinmaym07** [comment]
Hey @vasilicatamas Can I try this ..?

**Comment by anandsoni143** [comment]
CAN SOMEONE GUIDE ME THROUGH IT 
HOW CAN U RESOLVE THIS ISSUE @chinmaym07 , if possible

**Comment by LZoog** [comment]
@chinmaym07 @anandsoni143 sorry for the late response! This issue is still valid, if either of you are still interested on working on it please feel free to put in a PR.

You can reproduce this by running FxA locally and navigating to `beta/settings` (see the `packages/fxa-settings` README for more info). To see the footer issue, reduce the screen size to mobile. To see the "Change password" issue, click on "Change" from this row:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/13018240/112688086-5d5a8380-8e46-11eb-8541-fa834db62795.png">

**Comment by Chiamaka-Uzuegbu** [comment]
Hello @LZoog , can I try this please?

**Comment by jodyheavener** [comment]
@Chiamaka-Uzuegbu sure thing, I've assigned you

**Comment by Chiamaka-Uzuegbu** [comment]
On it now. Thanks

**Comment by Chiamaka-Uzuegbu** [comment]
Hello @jodyheavener, I'm having a bit of a constraint reproducing the issue. The link I'm to navigate to is throwing an error "page not found". Please what can I do about this?

**Comment by LZoog** [comment]
Hi @Chiamaka-Uzuegbu, sorry about the confusion! We just recently changed the URL from `beta/settings` to `settings`. You can find this at https://accounts.stage.mozaws.net/settings/, and to run it locally, run the repo and create an account and you should be taken to `localhost:3030/settings`.

**Comment by Chiamaka-Uzuegbu** [comment]
Hello @LZoog. I'm finding a bit of challenge pushing my fix after branching out, to the repo on github. It says access denied. Please what can I do about this. I have fixed this issue, and I just need to push it and create a PR. Thank you.

**Comment by dhruva248** [comment]
> Hello @LZoog. I'm finding a bit of challenge pushing my fix after branching out, to the repo on github. It says access denied. Please what can I do about this. I have fixed this issue, and I just need to push it and create a PR. Thank you.

you could be pushing in the Mozilla repo, you should be working on the forked one, check it once

**Comment by Chiamaka-Uzuegbu** [comment]
@dhruva248 Thank you so much. Have gotten a hands on it and already created a PR.

**Comment by LZoog** [comment]
This issue was closed in #8385.
