### ISSUE TITLE
[FxA-Settings] “X” menu button displays an incorrect focus border

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7013]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Android 9
Windows 10 64-bit

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Tap on Menu button.
3. Observe the “X” button focus border.

**Expected results**
The focus border only encompasses the “X“ button.

**Actual Results**
The focus border encompasses also an empty space from the right side of the “X” button.

![Screenshot_45](https://user-images.githubusercontent.com/18114210/100369977-44fc6880-300e-11eb-8aa0-e8d81031c9d4.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2742)
┆Issue Number: FXA-2742

**Comment by chinmaym07** [comment]
Hey @vasilicatamas  can I try this .?

**Comment by shades-7** [comment]
Hey, can I work on this?

**Comment by LZoog** [comment]
@chinmaym07 @shades-7 Apologies for such a late response! I just double checked and this is still a valid issue:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/13018240/112687257-3baccc80-8e45-11eb-976d-6cf87d519c40.png">

Please feel free to work on it and open a PR if one of you is still interested. You can find this screen by running FxA locally, navigating to `beta/settings`, viewing the page in mobile or tablet width, and tabbing to it.

**Comment by shades-7** [comment]
@LZoog i am interested

**Comment by jodyheavener** [comment]
@shades-7 This change should be made to the button element found here: https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/HeaderLockup/index.tsx#L22:L41

**Comment by shades-7** [comment]
@jodyheavener Thank you

**Comment by dhruva248** [comment]
@jodyheavener Can I help solving this issue if there has been no action yet or any help is needed?

**Comment by LZoog** [comment]
Hey @shades-7, just following up here. Are you currently working on this? 🙂

**Comment by shades-7** [comment]
> Hey @shades-7, just following up here. Are you currently working on this?

yes will send the PR soon
