### ISSUE TITLE
[FxA-Settings] Hamburger menu and “X” buttons don't have tooltip

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7014]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Resize the window until the header navigation menu is displayed.
3. Hover using the mouse cursor over the navigation menu.
4. Click on the navigation menu.
5. Hover using the mouse cursor over the “X” button.

**Expected results**
Both menu buttons successfully display a tooltip.

**Actual Results**
No tooltip is displayed for navigation menu and “X” buttons.

![issue53](https://user-images.githubusercontent.com/18114210/100370766-6f025a80-300f-11eb-9313-254dc8769dc8.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2743)
┆Issue Number: FXA-2743

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] Should these have tooltips?  If so, what should they be?

/cc [~lzugai@mozilla.com] in case this is a11y related

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

They should!

The "X" should have a tooltip of "Close menu"

[~mwalkington@mozilla.com] Any suggestions as to what the tooltip should be for the hamburger menu? Do we have a best practice here?

**Comment by data-sync-user** [comment]
➤ Meridel Walkington commented:

These work for tooltips:

Close menu

Open menu

Also, the header on this page should be singular: Firefox account ( [~wclouser@mozilla.com] ). Thanks!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's do this with a title attribute on the buttons

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested on Stage  [Train 1.201.0] under Windows 10 64 bit and and macOS 10.14.6 and noticed the following tooltips:

  * Site navigation menu
  * Close menu

[~wclouser@mozilla.com] can you please confirm that these are the last tooltips that have been decided?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

That sounds appropriate for a11y but it's not in the thread.  [~dcoates@mozilla.com] did you get that string from somewhere?

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Those strings already existed on the page. I just made it show up on the tooltip

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Ok, thanks.  Let's stick with them then which will let us re-use the L10n.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Thanks for your confirmation! Based on this I will add the verified label.
