### ISSUE TITLE
[FxA-Settings] “Invalid parameter in request body” error received for an invalid secondary email address

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7017]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from the Secondary email section.
3. Type an invalid email address i.e: kkkk@k
4. Click on “Save” button.

**Expected results**
“Save” button is disabled.

**Actual Results**
“Invalid parameter in request body” error is displayed.

![Screenshot_48](https://user-images.githubusercontent.com/18114210/100416654-ad3b6080-3087-11eb-99e0-e5ae696f7574.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2746)
┆Issue Number: FXA-2746

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Once we resolve the save button, what are the chances of triggering that error message? Should it be more descriptive?

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

The `Invalid parameter...` error would imply that the form got submitted and the auth-server is rejecting the request. ISTM that the form should fail validation and show a more appropriate error.

Assigning myself to take a stab at it.

**Comment by vbudhram** [comment]
Fixed in https://github.com/mozilla/fxa/pull/7145

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.197.0] under Windows 10 64-bit, Android 11 and iOS 13.6.  “Save” button is disabled while typing an invalid email address.

![Screenshot_22](https://user-images.githubusercontent.com/18114210/103896847-433cbf00-50fb-11eb-8a9f-edb09ac4c3ac.png)
