### ISSUE TITLE
[Support] Deploy stub support panel

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#702]
The stub support panel (in #700) is specifically intended to be deployed with full authentication, so we can test the ZenDesk integration and authentication system.

The deployment should support:

- [x] Requiring login via auth0
- [x] Restrict users to a specific LDAP group
- [x] Include a request header that indicates the logged-in user
- [x] Is restricted to the VPN

The support system should then iframe in `https://url-where-it-is-deployed/?uid={uid}&requestTicket={ticket}` (`requestTicket` is optional, but is included in the logs in case we want to audit the reasons for access)

**Current status:**

Per comment below, it's partially deployed at https://fxa-support-panel.prod.mozaws.net/ and https://fxa-support-panel.stage.mozaws.net/
The request header is logged for the user as well.

**Remaining work**

Secure access behind VPN.

**Comment by juliemccracken** [comment]
@jbuck IT still needs the URL. Could you please make sure that Marty Ballard gets it?

**Comment by juliemccracken** [comment]
jrgm provided this link today: https://fxa-aupport-panel.prod.mozaws.net/

**Comment by marty331** [comment]
@jrgm is there a dev url??

**Comment by jrgm** [comment]
Stage is https://fxa-aupport-panel.stage.mozaws.net/

**Comment by jrgm** [comment]
actually, there was a typo in both URL's above: s/aup/sup/

https://fxa-support-panel.prod.mozaws.net/
https://fxa-support-panel.stage.mozaws.net/

**Comment by ianb** [comment]
@jrgm Thanks for getting this in place. I think the next thing we have to do is get appropriate authentication in place. Specifically the application should be protected by a VPN requirement, and LDAP login, and additionally there is a group requirement on the LDAP login (though the group requirement is probably something we could follow on with). I think @gdestuynder will setup the LDAP group.

**Comment by gdestuynder** [comment]
Hi, I believe this is where your group restrictions are currently setup: https://github.com/mozilla-iam/sso-dashboard-configuration/blob/master/apps.yml#L3567-L3578 (which currently restricts to staff)

However, I recommend that you also check these groups in your relying party (ie in fxa-support-panel.*) as well. See https://github.com/mozilla-iam/mozilla-iam#2-stage-access-validation for information on why/how the access control works
