### ISSUE TITLE
[FxA-Settings] “Cancel” and “Back” buttons take the user to the top of the Settings page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7020]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Tap on the "Add" button from the Secondary email section.
3. Tap on “Cancel” or “Back“ buttons.

**Expected results**
The user is taken to the last visited section from the Settings Page.

**Actual Results**
The top of the Settings page is always displayed no matter from what page the user returns.

**Additional notes**
- This issue also reproduces for Change Password, Recovery key, 2FA pages.
- This issue does not reproduce on Windows.

![issue56](https://user-images.githubusercontent.com/18114210/100419773-d6f78600-308d-11eb-8184-547c60d41120.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2749)
┆Issue Number: FXA-2749

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this issue on Stage [Train 1.201.0] under Android 9 and iOS 14.4. The last visited section is correctly displayed on Android but it is covered by header on iOS - issue tracked separately in FXA-3115
