### ISSUE TITLE
[FxA-Settings] “Verify” button from Secondary email page becomes enabled for an invalid data at the first typing attempt

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7021]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Tap on the "Add" button from the Secondary email section.
3. Insert a valid email address and click on the "Save" button.
4. Type an invalid verification code (6 letters, a code shorter/longer than 6 chars)

**Expected results**
“Verify” button is disabled.

**Actual Results**
- “Verify” button becomes enabled for an invalid data only if it happens at the first typing attempt after the Secondary email verification screen is displayed. 
- No error is displayed if clicking on the “Verify” button.
- Erasing the invalid code and typing again the same code will no longer enable the “Verify” button.

![issue58](https://user-images.githubusercontent.com/18114210/100422006-25a71f00-3092-11eb-95f8-818556665a4b.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2750)
┆Issue Number: FXA-2750

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Updating to the latest version of our form library might fix this
