### ISSUE TITLE
[FxA-Settings] “Continue” button becomes enabled after one char in 2FA page at the first typing attempt

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7023]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from 2FA section.
3. Click outside the “Enter security code” field in order to unfocus it.
4. Focus the field end type a single char.

**Expected results**
“Continue” button is disabled.

**Actual Results**
- “Continue” button becomes enabled after typing a single char and turns back into disabled while typing more chars.
- It only happens at the first typing attempt after the Two Step Authentication Step 1 of 3 screen is displayed. 

**Additional notes**
This issue does not reproduce on iOS.

![issue59](https://user-images.githubusercontent.com/18114210/100442134-39fa1480-30b0-11eb-8023-f644a218f8e5.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2752)
┆Issue Number: FXA-2752

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This will be the same fix as fxa-2750
