### ISSUE TITLE
[FxA-Settings] “Can’t scan code” page incorrectly opened

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7024]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from 2FA section.
3. Scroll the page a bit down.
4. Click on the “Can’t scan code” link.
5. Observe how the “Can’t scan code” page is displayed.

**Expected results**
 “Can’t scan code” page is displayed from the top.

**Actual Results**
 “Can’t scan code” page is displayed at the same position as the previous page was.

**Additional notes**
This issue does not reproduce on iOS.

![issue60](https://user-images.githubusercontent.com/18114210/100443782-ff45ab80-30b2-11eb-89d9-23d4935bba1b.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2753)
┆Issue Number: FXA-2753

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is because it's replacing the element on the page so wherever you are on the page is where it will stay.  I'm going to wontfix this.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

.
