### ISSUE TITLE
[FxA-Settings] Recovery code error does not disappear after going back and forward

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7027]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10
Android 9
iOS

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from 2FA section.
3. Enter the code received after the QR code was scanned and tap on "Continue".
4. Click on the "Continue" button.
5. Type an invalid recovery code and click the “Finish” button.
6. Click “Back” button.
7. Click on the “continue” button.

**Expected results**
The error is no longer displayed.

**Actual Results**
The error is still displayed and points to an empty field.

![issue63](https://user-images.githubusercontent.com/18114210/100457178-3ffcef00-30ca-11eb-8ab9-9f520aa8953b.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2756)
┆Issue Number: FXA-2756

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue was verified as fixed on Stage [Train 1.201.0] under Windows 10 64-bit, Android 11 and iOS 14.4. The Recovery code error is no longer displayed after going back and forward.
