### ISSUE TITLE
[FxA-Settings] No notification bar displayed for several processes

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7030]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1.Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2.Add a Display name/ Update the Display name/ Change the password/ Add a secondary email/ Add a recovery key/ Change 2FA codes

**Expected results**
The notification bar is displayed for all completed processes.

**Actual Results**
Several processes do not display a green confirmation bar.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2759)
┆Issue Number: FXA-2759

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

triggering the alertbar after navigating from a secondary page requires some refactoring of the alertbar component. prob more than a 3

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.201.0] under Windows 10 64-bit, Android 9 and iOS 14.4. I confirm that the green confirmation bar is displayed for all process, excepting the avatar setup and connected services sign-out process.
