### ISSUE TITLE
Device Manager - Last seen date is broken

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7039]
We no longer display accurately the date a device was last seen. This seems to align with the desktop migration to OAuth.

【 highlighted #172b4d 】Here are 2 devices. One is Nightly and the other is Beta. You can see when each device is detecting the other as having been active. Ultimately, it seems to detect that they were active prior to the migration to OAuth. Nightly was active 6 months ago. Beta was active 4 months ago. From these screenshots, you can see that each device is in fact actually still active.
 
 **I guess the main question is, are we migrating this bug to our new settings? If so, let's add it to our list of things to resolve with the new settings.**【 end highlighted 】

!image-2020-12-01-10-45-56-104.png!

!image-2020-12-01-10-51-02-171.png!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2764)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/14619/image-2020-12-01-10-45-56-104.png">image-2020-12-01-10-45-56-104.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14623/image-2020-12-01-10-51-02-171.png">image-2020-12-01-10-51-02-171.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14621/Screen+Shot+2020-12-01+at+10.36.13+AM.png">Screen Shot 2020-12-01 at 10.36.13 AM.png</a>
┆Issue Number: FXA-2764

**Comment by rfk** [comment]
Signing a certificate [bumps the last-accessed time on the sessionToken](https://github.com/mozilla/fxa/blob/c39f8790513657110a304eff108512a7f80b8349/packages/fxa-auth-server/lib/routes/sign.js#L80) but it looks like [granting an access token does not](https://github.com/mozilla/fxa/blob/c39f8790513657110a304eff108512a7f80b8349/packages/fxa-auth-server/lib/routes/oauth/index.js#L219).

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

[~dcoates@mozilla.com] and [~wclouser@mozilla.com] is this something that could/should be part of the OAuth maintenance sprint? It overlaps well with Settings too.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The OAuth maintenance sprint is already overfull.  It probably fits the category though.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Hmm, would be good to not propagate this error into new-settings. Pulling this into the post-beta epic.

**Comment by rfk** [comment]
Ref https://github.com/mozilla/fxa/issues/5432 which I expect to be an Android-specific special case of this issue.

**Comment by mhammond** [comment]
It seems possible [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1689037) is also caused by this?
