### ISSUE TITLE
[Support] Ensure database user is granted limited permissions

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#705]
We should ensure in the deployment that the database user only has read permissions on appropriate tables.

(This ticket should be amended to include the specific tables we want to access.)

**Comment by jrgm** [comment]
I wrote up notes in https://docs.google.com/document/d/1tprbomvsDXiinMeyl3QbHfYmsorb2fKPFzpSOpecQbI/edit?ts=5d43a2fd# (restricted, and if I didn't give you access, then ask me). Julien has had a look, and is good with the steps described there. I'm interested to know if @bbangert or @clouserw have and comments/questions in that doc.

**Comment by clouserw** [comment]
No comments from ben or myself

**Comment by jrgm** [comment]
Calling this closed. Limited permissions described in the document above.
