### ISSUE TITLE
Add a new event property to Checkout related Amplitude events

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7073]
This ticket covers events specific to Checkout.

--

We currently record metrics related to the funnel for subscriptions. We should record when a user signs up with PayPal.

A primer on metrics in FxA can be found at [https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-metrics.](https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-metrics.)  The type of metrics in discussion for this issue is Amplitude.  There's a list of these events at [https://docs.google.com/spreadsheets/d/1ttgV60YeurrMhmdlCZ5WNBJXa-PcnRmrGgOEow71E1U/edit#gid=0.](https://docs.google.com/spreadsheets/d/1ttgV60YeurrMhmdlCZ5WNBJXa-PcnRmrGgOEow71E1U/edit#gid=0.)

Amplitude allows a dictionary of "event properties" to be attached to each event.  For events where the user has the option of using Stripe or PayPal, we should add an event property of "payment_provider" with the value "Stripe" or "PayPal".

An example of such an event is the "fxa_pay_setup - success" event.  That event is emitted at [https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/lib/apiClient.ts#L239:L242, where you can see the event properties are directly passed into the function call.](https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/lib/apiClient.ts#L239:L242)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2789)
┆Issue Number: FXA-2789

**Comment by chenba** [comment]
@irrationalagent @davismtl The current plan is to add an event property of "payment_provider" with the possible values of "Stripe" and "PayPal" to some of the SubPlat related Amplitude events.  Let us know if you think we should do something different.
