### ISSUE TITLE
Implement new auth server API method to list active subscriptions

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#708]
Related to #706 
- [ ] fxa-auth-server API method to list user's active subscriptions

**Comment by bbangert** [comment]
A note that the subscription status will be one of the fields included in the profile-server API response, which it then gets from the auth-service. For now we will just include this for any RP that has visibility to email scope.

**Comment by lmorchard** [comment]
I think this issue is morphing a bit:

- There will indeed be a "list all subscriptions" resource in the Auth API, but that lists subscriptions & products. I'm not planning to expose this through the Profile server. This API is just for subscription management on the account settings page.

- I'm also building a "list subscription capabilities for client" resource that I *do* plan to expose through the Profile server as the subscription status. This will use [internal configured mappings](https://github.com/mozilla/fxa/blob/ab63dd1ea686eb905dcb49c0d898b6dc9b488569/packages/fxa-auth-server/config/dev.json#L38) to assemble a list of account capabilities from subscribed products, [then reveal a relevant subset of those capabilities to the particular client](https://github.com/mozilla/fxa/blob/ab63dd1ea686eb905dcb49c0d898b6dc9b488569/packages/fxa-auth-server/lib/routes/subscriptions.js#L31).
