### ISSUE TITLE
Store & manage webhook endpoints for notifications to Relying Parties

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#709]
Related to #706 
- [ ] Derived from or build atop the fxa_oauth.clients table?
- [ ] New auth DB table to store webhook URLs associated with RPs
- [ ] New DB stored procedures for CRUD on webhooks for RPs
- [ ] In-memory mock implementation for fxa-auth-db-mysql
- [ ] Real mysql implementation for fxa-auth-db-mysql
- [ ] Implement fxa-auth-db-mysql API changes for CRUD

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-786)
┆Issue Number: FXA-786

**Comment by shane-tomlinson** [comment]
Is there going to be one webhook per service or multiple? If only one per service, it seems to make sense just to add a new column to the [existing clients table](https://github.com/mozilla/fxa/blob/d95b7de38fa96f50c9236e077724195871f3b159/packages/fxa-auth-server/fxa-oauth-server/lib/db/mysql/schema.sql#L15)

**Comment by lmorchard** [comment]
:+1: I think it's safe to assume one webhook per client.

**Comment by clouserw** [comment]
Re-adding P1 due to blocking ben's work

**Comment by bbangert** [comment]
Moving back to P2 as described partly in ADR 0003. The event broker will store this.
