### ISSUE TITLE
Store & manage which Relying Parties a user has logged into as recipients for notifications

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#710]
Related to #706 
- [ ] Can this be derived from or built atop the fxa_oauth.tokens table?
  - Related https://github.com/mozilla/fxa/issues/459
- [ ] New auth DB table to store RPs associated with users
- [ ] New DB stored procedures for CRUD RPs associated with users
- [ ] In-memory mock implementation for fxa-auth-db-mysql
- [ ] Real mysql implementation for fxa-auth-db-mysql
- [ ] Implement fxa-auth-db-mysql API changes for CRUD

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-787)
┆Issue Number: FXA-787

**Comment by clouserw** [comment]
Re-adding this as a P1 because it blocks Ben's work

**Comment by bbangert** [comment]
This ticket should probably be done with #709 as they both involve similar storage and API work.

**Comment by bbangert** [comment]
Per ADR 0003, for MVP of subscription services the FxA event broker will track this.

**Comment by bbangert** [comment]
This is not necessary work for implementing the FxA Event Broker, so I'm removing it from that epic.
