### ISSUE TITLE
[FxA-Settings] UI issues around 2FA download/copy/print icons in production

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7126]
**Build**
Prod[Train 1.195.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from 2FA section.
3. Enter the code received after the QR code was scanned and tap on "Continue".

**Expected results**
2FA download/copy/print icons are correctly displayed.

**Actual Results**
- Windows and Android: 2FA download/copy/print icons are attached to the Cancel and Continue buttons.
- iOS: There is no space under the last recovery codes.

![Screenshot_10](https://user-images.githubusercontent.com/18114210/101920289-4b750d80-3bd4-11eb-83c0-f592e5648455.png)
![Screenshot_11](https://user-images.githubusercontent.com/18114210/101921290-83308500-3bd5-11eb-970a-ebc304c72501.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2816)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15467/Screenshot_10.png">Screenshot_10.png</a>
┆Issue Number: FXA-2816

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

The 2FA download/copy/print icons are now overlapping the Cancel/Continue buttons on Prod [Train 1.202.1] under Windows 10 64-bit and macOS 10.14.6. Increasing the severity.

**Comment by KartikSoneji** [comment]
I can still reproduce the issue on Chrome, Windows 10 x64

![image with overlapping icons](https://user-images.githubusercontent.com/25801283/117339282-31a6d080-aebd-11eb-8f70-d2c53a41cb28.png)

**Comment by KartikSoneji** [comment]
Although the `h-40` class was removed in commit 7221a02130f87dfad169b5323aa6de9db0546316, the fix doesn't seem to be in the deployed website:

![image](https://user-images.githubusercontent.com/25801283/117339896-ea6d0f80-aebd-11eb-8bd8-e0f4880b669c.png)
