### ISSUE TITLE
Update account subscriptions in reaction to SubHub notifications

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#713]
Related to #706 
Overlaps / interacts with epic #701 

Active subscriptions for FxA accounts need to be updated in reaction to subhub events - i.e. when a subscription lapses in payment, is cancelled some other way, etc.

**Comment by lmorchard** [comment]
Realized this issue was a bit confusingly described. Rephrasing it somewhat since it looked really overlapped with the event distribution / broker stuff. I think this issue is specifically for keeping the account subscriptions table in FxA up to date with changes in subscription status.

That is, if a subscription lapses or is cancelled outside calls to the FxA Auth Server, the DB table of active account subscriptions needs to be updated.

**Comment by bbangert** [comment]
Related to #970, as there's additional events to process and update other fields. But handling those requires db changes documented in #970.
