### ISSUE TITLE
Update Mozilla address in email footers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7131]
We will no longer have access to our E Evelyn address after Dec 31, 2020. With that, we need to update our address to the following, preferably before Dec 31, 2020. 

Mozilla Corporation
2 Harrison Street, #175
San Francisco, CA 94105

This new address should replace the Evelyn address in any emails sent by FxA.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2821)
┆Issue Number: FXA-2821

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Contact [~mfeldman@mozilla.com] with questions.

**Comment by vasilicatamas** [comment]
Verified the footer of the several FxA emails and I confirm that the new Mozilla address is successfully displayed:  "Mozilla. 2 Harrison St, #175, San Francisco, CA 94105".

![Screenshot_20](https://user-images.githubusercontent.com/18114210/103881716-7ffcbc00-50e3-11eb-84e1-49651a1ec0da.png)
