### ISSUE TITLE
"some times ago" not translated in Settings page in zh-TW locale

### ISSUE THREAD

**Issue by petercpg** [mozilla/fxa#7158]
## Description

"some times ago" not translated in Settings page in zh-TW locale

### Steps to reproduce

1. Make sure browser is sending zh-TW in `accept-languages` header (add zh-TW to the leftmost of `intl.accept_languages` in about:config)
2. Login [Firefox Accounts Dashboard](https://accounts.firefox.com/settings/clients?entrypoint=preferences), and open "Device & apps"  stub
3. Observe the "Last seen" time displayed

### Expected result

The time displayed shall be localized, eg.,
最後連線於 16 分鐘前

### Actual result

The time displayed is not localized, eg.,
最後連線於 16 minutes ago 前

Note: It seems this issue only affects `zh-*` locales like `zh-TW`, `zh-CN`, but not in `ja`, `ko`, or `es`

### Screenshot

![圖片](https://user-images.githubusercontent.com/205738/102189727-07467d80-3ef2-11eb-8dd8-13a3333c7fa5.png)

### Environment
Firefox nightly 86.0a1 20201214230337
Windows 10 20H2 x64 19042.685 (Locale: zh-TW)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3102)
┆Issue Number: FXA-3102

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This may be fixed with our new beta settings.

**Comment by petercpg** [comment]
The time is still appearing in English on latest production site:

![2021-04-03_000902](https://user-images.githubusercontent.com/205738/113433024-04c05300-9411-11eb-987a-c89bafb25fdb.jpg)
