### ISSUE TITLE
Disable New Settings/Settings Beta in production

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7167]
Per Product and Product Leadership, Settings should be disabled over the extended holiday and Wellness benefit break in late December 2020.

This action will be taken to avoid potential user impact over the extended period when teams are less available, and will avoid folks having to respond to urgent situations over holidays.

**Timeline:**

This should be disabled in production AFTER the completion of [~rbillings@mozilla.com] 's #foxfooding test effort, an internal invitation to test the Settings beta, which is scheduled between 12-2pm PT on December 17.

**Notes:**

* As noted by [~bchen@mozilla.com] , if the **opt-in link** is disabled on /settings, then too will beta/settings be disabled
* See request as follows per [~adavis@mozilla.com] :
  * @Wil Clouser @clewis In a meeting now with Mikal, he just said that we should turn it off on Thursday. Let’s capture the survey data for 3-4days but let’s not risk people’s holidays. Let’s just turn it off. CC @jbuck

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2858)
┆Issue Number: FXA-2858

**Comment by jbuck** [comment]
Done

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per [~jhirsch@mozilla.com] :
{quote}it looks like all that’s needed to hide the beta link is to flip the value of this config pref https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/configuration.js#L557 ( https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/server/lib/configuration.js#L557 )
{quote}
