### ISSUE TITLE
Update subscription management pages with final UX and visuals

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#718]
Related to #695 

- [ ] Implement final UX flows and visuals when available.
- [ ] Form validation & error messages
- [ ] Back-fill tests for components & store along the way
- [ ] Remove / hide multiple plan-per-product selection
- [ ] Remove the Home page component and links to index

**Comment by johngruen** [comment]
@lmorchard and I will bang this out when I get back before this sprint is ended

**Comment by clouserw** [comment]
See also #1163

**Comment by lmorchard** [comment]
Breaking this up into smaller replacement issues.
