### ISSUE TITLE
Unable to sign in through FxA Stage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#7181]
#### Affected FxA versions:
- 1.196.0;
 
#### Affected Platforms:
- macOS 10.15.7;
- Android 10;
- Linux Ubuntu 20.04;
- iOS 14.2;
 
#### Prerequisites:
- Have the VPN app installed;
- Have a FxA account;
 
#### Steps to reproduce:
1. Launch the VPN app;
2. Click/tap on “Get started”;
3. Sign in to FxA account
 
#### Expected result:
- You are signed in and the Quick access screen is displayed in the app.
 
#### Actual result:
- “System unavailable, try again soon” error message is displayed when attempting to sign in.

![image](https://user-images.githubusercontent.com/15685960/102474811-c40b1c80-4061-11eb-94c5-dd02f240e935.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2860)
┆Issue Number: FXA-2860

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Sorry for the downtime.  Fixed now.
