### ISSUE TITLE
Drop in December activity metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7214]
This is the part of FXA-2866 that wasn't a data processing bug:

- - -
See this chart:
 [https://analytics.amplitude.com/mozilla-corp/chart/atcni5e](https://analytics.amplitude.com/mozilla-corp/chart/atcni5e)

It's interesting to note that there was a drop earlier in December in this data too. (but for mobile only for some reason) Here's a screenshot for Fenix (blue line).

!image-2021-01-04-10-42-26-295.png!

And a zoom in on iOS (the green line)

!image-2021-01-04-10-43-48-641.png!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2870)
┆Issue Number: FXA-2870

**Comment by clouserw** [comment]
@6a68 I think the images are missing?
