### ISSUE TITLE
top level "npm test"

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#725]
It'd be nice to have `npm test` from the project root run all the unit tests across packages. `lerna run test` could do so but it currently fails. We'll need some more setup for that to work.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-790)
┆Issue Number: FXA-790

**Comment by LZoog** [comment]
This issue is noted in the docs per: https://github.com/mozilla/fxa/pull/1706

When this issue is addressed, please update the project root documentation as well.

**Comment by parshva-b** [comment]
Hey,

Has this issue been resolved? If not, can I claim this issue? Also, if you can provide some help for me to work on this issue, it would surely be of help.
