### ISSUE TITLE
docker image mozilla/fxa-content-server size doubled to 1GB since v1.134.0

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#726]
While fxa-auth-server and fxa-auth-db-mysql image size didn't change, fxa-content-server image size went from 475MB to 1GB.

Not so important with content server since it rarely autoscales (if ever). But if there's some unintended temporary/intermediate stuff being left around, it wouldn't hurt to clean it up.

**Comment by shane-tomlinson** [comment]
@jrgm - do you know what extra cruft is being included?

**Comment by jrgm** [comment]
docker run -u 0 -it --rm  mozilla/fxa-content-server:latest sh -c 'du -s -k /app/* | sort -rn   | head -10'

shows there are three big items left over from presumably the test run (i.e., firefox tarballs)

**Comment by jrgm** [comment]
Also, `node_modules` includes dev dependencies, for what those are worth in size.

**Comment by dannycoates** [comment]
seems fixed
