### ISSUE TITLE
Drop in Login and Registration Success Rate

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7268]
Since yesterday, our login and registration rates have dropped.

Registration rate:
[https://analytics.amplitude.com/mozilla-corp/chart/67f16ti](https://analytics.amplitude.com/mozilla-corp/chart/67f16ti)

With further investigation, it seems to be impacting desktop users, not mobile users:

[https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/3g3nshl](https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/3g3nshl)

Narrowing down further, it seems to be specifically Sync:
[https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/xk8m8iu](https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/xk8m8iu)

Please investigate and resolve problem.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2901)
┆Issue Number: FXA-2901

**Comment by 6a68** [comment]
It looks like the registration rate has recovered. Closing.
