### ISSUE TITLE
Long device name displayed outside the “Confirm pairing” screen

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7286]
**Build**
Stage [Train 1.198.1]

**Affected platforms**
iOS 13.6
Android 11

**Steps to reproduce**
1. Launch Firefox and login using a Firefox Account.
2. Navigate to about:preferences#sync and click on the “Change Device Name...” button.
3. Type a long name and click on the “Save” button.
4. Connect on a different device using pairing method.
5. Check how the device name is displayed in the “Confirm pairing” screen.

**Expected results:**
The Device name is divided on several lines. 

**Actual Results:**
The Device name is displayed outside the “Confirm pairing” screen.

![Screenshot_37](https://user-images.githubusercontent.com/18114210/104938428-bece2400-59b7-11eb-949e-5b08082a784d.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2910)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16339/long+name+new+situation.PNG">long name new situation.PNG</a>
┆Issue Number: FXA-2910

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is no longer reproducible on Production [1.207.1] on Android 11 and iOS 14.4. Closing.
