### ISSUE TITLE
[FxA-Settings] The current device last login status not displayed as “active now”

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7287]
**Build**
Stage [Train 1.198.1]

**Affected platforms**
Windows 10 64-bit
iOS 13.6
Android 11

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Check the current device status in Connected Services section.

**Expected results:**
First Connected service listed is the current device displaying the “active now” login status - as per [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1).

**Actual Results:**
The current device displays the last login value in minutes/hours/days as the other connected services.

![Screenshot_38](https://user-images.githubusercontent.com/18114210/105059915-7890c780-5a80-11eb-99b5-d4e3ebb4bcbd.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2911)
┆Issue Number: FXA-2911

**Comment by vasilicatamas** [comment]
Closing as a dupe of [7000](https://github.com/mozilla/fxa/issues/7000)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

marking duplicate
