### ISSUE TITLE
Create paypal handler for paypal-checkout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7325]
A Paypal handler should be created for /oauth/subscription/paypal-checkout per the linked issue references. This will call the paypal helper for checkout setup which returns a token back to the caller.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2937)
┆Issue Number: FXA-2937

**Comment by birdsarah** [comment]
Closed via #7387
