### ISSUE TITLE
Error: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.Service...

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#7333]
https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10321132/?referrer=github_plugin

```
Error: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

Server stack trace: 
   at System.ServiceModel.Ch...
  at Object.browserNotificationOpenUi (<anonymous>)
  at None (about:blank:134:167)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2939)
┆Issue Number: FXA-2939

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is an OS level error getting sent to our catch-all error handler.  There isn't a lot we can do about it, so I've set Sentry to ignore.
