### ISSUE TITLE
Invalid OAuth parameter: scope when trying to reset password

### ISSUE THREAD

**Issue by lobontiumira** [mozilla/fxa#734]
Environment: Samsung Galaxy S8 (Android 9)
Build: Stage server - Train 134

**STR:**
1. Go to https://addons.mozilla.org/en-US/android/ and log in.
2. Click "Forget password" button, enter email and "Begin reset" button.
3. Wait for 1hr and go to email and click on "Create new password".
4. Click on "Receive new link".
5. Go to email and click on "Create new password".

**Expected results:**
The user should be redirected to reset password page.

**Actual results:**
"Bad request - Invalid OAuth parameter: scope" page is displayed.

**Notes:**
1. I've attached a gif representing the error page displayed.
2. I have a logcat, but I'm not allowed to attach it.

![2019_04_04_16_35_41](https://user-images.githubusercontent.com/40694158/55560588-33f43a80-56f9-11e9-9de5-a6860b9c423d.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-791)
┆Issue Number: FXA-791

**Comment by clouserw** [comment]
The URL will timeout after some amount of time.  But we should change the error to say "Link Expired" or something.

**Comment by softvision-miralobontiu** [comment]
But after Step 4, we should be able to create a new password, right?

**Comment by mirunacurtean** [comment]
Update: Managed to reproduce this on Windows 10 64-bit on fxa Train 168 stage as well. 
![Resent password link bad request](https://user-images.githubusercontent.com/53306802/80208338-a99ab380-8638-11ea-993f-91a96fc8bf79.gif)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
