### ISSUE TITLE
new-settings storybook builds are broken

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#7343]
It looks like the addition of `fs` to the mocks (to load strings) has broken storybook. From discussion on Slack:

```
ERROR in ./src/models/_mocks.tsx
Module not found: Error: Can't resolve 'fs' in '/home/djustice/fxa/packages/fxa-settings/src/models'
 @ ./src/models/_mocks.tsx 19:0-20 165:45-47 166:45-47 167:42-44
 @ ./src/components/Avatar/index.stories.tsx
 @ ./src sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^/]*?\.stories\.tsx\/?)$
 @ ./.storybook/generated-entry.js
 @ multi /home/djustice/fxa/node_modules/@storybook/core/dist/server/common/polyfills.js /home/djustice/fxa/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js /home/djustice/fxa/node_modules/@storybook/addon-links/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

Based on some preliminary digging, the right answer might be to have webpack source those strings for testing, instead of doing it directly in the mocks, so that we can separately manage loading up the strings in the storybook webpack config. But I'm definitely not a webpack expert, so idk 🤷‍♂️

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2942)
┆Issue Number: FXA-2942

**Comment by 6a68** [comment]
@lmorchard pointed out in Slack that we should be able to pull strings into storybook just using the `AppLocalizationProvider` from `fxa-react`. It does take the path to the strings as the `baseDir` argument:

```
// https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/.storybook/components/MockApp.tsx#L92-L96
      <AppLocalizationProvider
        baseDir="./locales"
        userLocales={languages}
        bundles={['main']}
      >
```

**Comment by lmorchard** [comment]
Probably also need to add whatever webpack processing happens for FTL so that storybook gets the end-product static build just like normal site build... payments-server doesn't have that concern, iirc. AppLocationProvider will just be trying to fetch the FTL via http(s) on the client-side

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Assigning 2 points, since I took the easy way out here: I'm getting builds working again by yanking out the broken localization code, and planning to address localization in storybook separately, in FXA-3029.
