### ISSUE TITLE
[FxA-Settings] Sections title displayed over the confirmation green bar

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7349]
**Build**
Prod [Train 1.198.2]

**Affected platforms**
Windows 10 64-bit
iOS 13.6
Android 9

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Perform some changes in order to trigger the confirmation green bar. (I.e Delete a secondary email, remove the account recovery key, enable/disable 2FA, Sign out a device)
3. Scroll the page down and up while the confirmation bar is displayed.

**Expected results:**
There are no UI issues encountered.

**Actual Results:**
The section titles (Profile/Security/Connected Services) are not hidden behind the confirmation bar.

![Screenshot_1](https://user-images.githubusercontent.com/18114210/105723634-ac139c00-5f2f-11eb-8df1-a2fa4146e36d.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2945)
┆Issue Number: FXA-2945

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible, It may have been fixed together with FXA-3020
