### ISSUE TITLE
Remove travis-ci from fxa-content-server-l10n

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7354]
Travis-ci.org is shutting down in a few weeks. It looks like [fxa-content-server-l10n is still running tests there](https://travis-ci.org/github/mozilla/fxa-content-server-l10n).

The actual extract/merge work is already being done on circleci, and it looks like we check out the code on every commit but then [we don't actually do anything with it](https://github.com/mozilla/fxa-content-server-l10n/blob/master/.circleci/config.yml#L40).

This bug is to:

* Run `npm test` in circleci
* Remove .travis.yml
* Remove the travis badge from the readme
* [anything else relevant to this issue!]

We should make sure Peiying is notified of build failures (see current .travis.yml)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2949)
┆Issue Number: FXA-2949

**Comment by Komalmann** [comment]
I would like to work on this! Please assign it to me

**Comment by clouserw** [comment]
Hi @Komalmann.  Thanks for your offer.  Since this involves other systems behind logins we're going to have someone with access to those systems do it.  There are some other bugs tagged `help wanted` which might be a better fit.  Thanks.
