### ISSUE TITLE
The password cannot be changed on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7394]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
iOS 13.6

**Prerequisites**
2FA is enabled.

**Steps to reproduce**
1. Login using a valid Firefox account  on an iOS device
2. Navigate to menu - > FxA account -> Manage Account & Devices.
3. Go to the Password section and click on the “Change” button.
4. Add valid old and new password and click on the "Change" button.

**Expected results:**
The password is successfully updated.

**Actual Results:**
Nothing happens when clicking on the “Change” button. The password is not changed.

![issue78](https://user-images.githubusercontent.com/18114210/106489806-d3351500-64bd-11eb-9762-66cc678178f0.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2962)
┆Issue Number: FXA-2962

**Comment by dannycoates** [comment]
#7395 has more info

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

marking dup
