### ISSUE TITLE
Change password silent failure on Firefox iOS

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#7395]
## Description

Under some(?) conditions attempting to change the fxa password from the "Manage Account & Devices" menu on fxios will silently fail. The "Change" button doesn't appear to do anything and the password remains unchanged. An [HTTP dump](https://gist.github.com/dannycoates/3cb9425555f2dde8293ec3741b0d9d16) shows that the final call to `password/change/finish?keys=true` fails with errno 138 (Unverified session).

This doesn't seem to affect all accounts. The affected account has TOTP enabled. IDK if that's a factor or not.

### Steps to reproduce

1. Login to sync on fxios
2. Go to "Manage Account & Devices" (settings page)
3. Attempt to change the password

### Expected result

The password is changed.

### Actual result

The password isn't changed and there is no UI feedback.

### Environment

Firefox for iOS v30

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2963)
┆Issue Number: FXA-2963

**Comment by rfk** [comment]
I recall a recent bug about change-password not correctly copying 2fa verification state, possibly related? /cc @chenba who I think was working on that.

**Comment by chenba** [comment]
The bug I fixed (PR #7315) happens after a successful password change, and the fix was entirely on the server side, so I don't think it is related.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible in the new Settings page on Prod [Train 1.203.4] and Stage [Train 1.203.5] under iOS 14.4. Closing.
