### ISSUE TITLE
[Support] Log access to support tickets

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#740]
This is noted in another ticket, but to be more explicit, on every access we want to log:

- [ ] The customer support user who accessed the user
- [ ] The uid of the user being supported
- [ ] If we can, the ticket number in ZenDesk (if we can have the iframe loaded like `.../?uid=...&ticket_id=zendesk_id`)

**Comment by clouserw** [comment]
Ben verified we log all of this already.  closing.
