### ISSUE TITLE
[FxA-Settings] “Add” and ”Change” Avatar buttons are not correctly aligned

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7410]
**Build**
Stage [Train 1.199.0]

**Note**
This is a follow-up for #6792

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Observe how the “Add” and “Change” buttons from Picture section are aligned compared with the other buttons.

**Expected results**
All the buttons are correctly right aligned.

**Actual Results**
“Add” and “Change” buttons from the Picture section are displayed a bit to the right compared with the other buttons.

![97583063-2dc25f00-19ff-11eb-97be-b90327c18056](https://user-images.githubusercontent.com/18114210/106731034-b3b1ff80-6617-11eb-9c82-0ea8640d7baa.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2966)
┆Issue Number: FXA-2966

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.201.0] under Windows 10 64-bit, Android 9 and iOS 14.4. “Add” and “Change” buttons from the Picture section are correctly right aligned.
