### ISSUE TITLE
[FxA-Settings] Incorrect title for the Step 1 avatar separate page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7411]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add"/"Change" button displayed on the right side of the Picture section.

**Expected results:**
The Avatar separate  Step 1 page title is “Profile picture” - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1)

**Actual Results:**
The Avatar separate  Step 1 page title is “Avatar”.

![Screenshot_18](https://user-images.githubusercontent.com/18114210/106736438-21612a00-661e-11eb-992a-a98bee58c3c7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2968)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15397/Screenshot_24.png">Screenshot_24.png</a>
┆Issue Number: FXA-2968

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible on Stage [Train 1.201.1] under Windows 10 64-bit, macOS 10.14.6, Android 9 and iOS 14.4. The Avatar separate Step 1 page title that is displayed is “Profile picture”.
