### ISSUE TITLE
[FxA-Settings] “Close” button displayed instead of “Cancel” button in Step 1 Profile picture page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7412]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add"/"Change" button displayed on the right side of the Picture section.

**Expected results:**
The “Cancel” button is successfully displayed in Step 1 Profile picture page - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1)

**Actual Results:**
The “Close” button is displayed instead of the “Cancel” button.

![Screenshot_19](https://user-images.githubusercontent.com/18114210/106736971-c976f300-661e-11eb-8bee-6af0b7a1be89.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2967)
┆Issue Number: FXA-2967

**Comment by sardug10** [comment]
Hey, Can I work on this issue?

**Comment by LZoog** [comment]
Hey @sardug10, sorry for not getting back to you earlier. We have some contributors through the Outreachy program combing through our `good first issue`s. If you're still interested, please check back here in a few weeks, we may have some other `good first issue`s by then to look at too.

If an Outreachy contributor would like to pick this one up, the URL is `/settings` and no longer `beta/settings`.

**Comment by karinabk** [comment]
> Hey @sardug10, sorry for not getting back to you earlier. We have some contributors through the Outreachy program combing through our `good first issue`s. If you're still interested, please check back here in a few weeks, we may have some other `good first issue`s by then to look at too.
> 
> If an Outreachy contributor would like to pick this one up, the URL is `/settings` and no longer `beta/settings`.

I'm an Outreachy contributor that would like to pick this one up ;)

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.2] under Windows 10 64-bit, Android 9 and iOS 14.4. I confirm that "Cancel" button is successfully displayed in Step 1 Profile picture page.
