### ISSUE TITLE
[FxA-Settings] “Add Photo” and “Take Photo” buttons have incorrect font size

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7413]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add"/"Change" button displayed on the right side of the Picture section.
3. Check the “Add Photo” and “Take Photo” font size

**Expected results:**
The “Add Photo” and “Take Photo” text size is 11px and line-height is 15px - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A87)

**Actual Results:**
The “Add Photo” and “Take Photo” text size is 16px and line-height is 24px.

![Screenshot_20](https://user-images.githubusercontent.com/18114210/106756254-c63c3100-6637-11eb-8d37-11d716fb0143.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2969)
┆Issue Number: FXA-2969

**Comment by LZoog** [comment]
In case a contributor would like to pick this up, the URL is `/settings`, not `beta/settings`. Looks like right now, the font-size is 12px, and the line-height also seems fine.

We could add a `margin-top` to this though of 8px (`.5rem`) to more closely match the Figma design. We should use a Tailwind class to make that happen.

Figma:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/13018240/113740691-8db3e480-96c6-11eb-8c8b-2bb9f81ea756.png">

**Comment by karinabk** [comment]
@LZoog May I take this one? and could you kindly attach Figma screenshots?

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this fix on Stage [train 1.204.2] under Windows 10 64-bit, Android 9 and iOS 14.4 and noticed that the font-size is 12px and the line-height is 18 px. [~lzugai@mozilla.com] can you please confirm that these are the expected values?
