### ISSUE TITLE
[FxA-Settings] “Close” button displayed instead of “Cancel” button in Step 1 Delete Account page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7414]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Scroll down at the bottom of the page.
3. Click on the "Delete account" button.

**Expected results:**
The “Cancel” button is successfully displayed - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1)

**Actual Results:**
The “Close” button is displayed instead of the “Cancel” button in Step 1 Delete Account page.

![Screenshot_21](https://user-images.githubusercontent.com/18114210/106765284-4fa43100-6641-11eb-8340-3c96835c5aa7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2970)
┆Issue Number: FXA-2970

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage  [Train 1.204.2] under Windows 10 64-bit, Android 9 and iOS 14.4. I confirm that "Cancel" button is successfully displayed.
