### ISSUE TITLE
[FxA-Settings] Second checkbox sentence is incorrectly worded in Step 1 Delete Account page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7415]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Scroll down at the bottom of the page.
3. Click on the "Delete account" button.
4. Check the sentence which correspond to the second checkbox.

**Expected results:**
“*You* may lose saved information and features within Mozilla products” sentence is displayed - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1)

**Actual Results:**
“*Any* may lose saved information and features within ⁨Mozilla⁩ products“ sentence is displayed.

![Screenshot_22](https://user-images.githubusercontent.com/18114210/106768724-de667d00-6644-11eb-8798-787c650e7999.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2971)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15334/Screenshot_57.png">Screenshot_57.png</a>
┆Issue Number: FXA-2971

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible on Stage [Train 1.200.0] under Windows 10 64-bit, Android 9, iOS 13.6 and mac OS 10.14.6.  “You may lose saved information and features within Mozilla products” is correctly displayed.
