### ISSUE TITLE
[FxA-Settings] “Delete account“ button has an incorrect color in Step 2 Delete Account page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7417]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 64-bit
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Scroll down at the bottom of the page.
3. Click on the "Delete account" button.
4. Check all 4 available options and click on the "Continue" button
5. Check the “Delete account” button.

**Expected results:**
“Delete account” button has a red background - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A201)

**Actual Results:**
“Delete account” button is blue.

![Screenshot_25](https://user-images.githubusercontent.com/18114210/106771697-eb38a000-6647-11eb-9896-ceb904ebb863.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2974)
┆Issue Number: FXA-2974

**Comment by shivanisinghnitp** [comment]
Hello, Can you assign this issue to me? Thanks!

**Comment by LZoog** [comment]
Hi shivanisinghnitp, I realize your comment is 3 days old, sorry for missing it! Feel free to circle back here once the other issue you have assigned to you now is fixed, thank you! 😄

**Comment by LZoog** [comment]
The red background shown in the Figma link is #feb3bb in disabled state, but we should use whatever closest background-color is generated by our Tailwind files. The hovered disabled state should still show the disabled color.

A non-disabled button hover should show #FF4F5E or whatever closest background-color we have in our Tailwind config file.

**Comment by Deek9399** [comment]
Hello @LZoog, Can I work on this issue??

**Comment by LZoog** [comment]
Hey @Deek9399, since you've got a PR up for your other issue I'll go ahead and assign you, thanks! 🙂

**Comment by Deek9399** [comment]
@LZoog sorry for the delay on this task. I am unable to view the Figma link, getting "Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.". Checking the color codes, I think #FF9AA2 is more close to #feb3bb. Let me know what you think?
#FF4F5E is available in the config file.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on Stage [1.207.0] under Windows 10 64 bit, Android 11, iOS 14.4 and macOS 10.14. I confirm that 'Delete' button has a red background.
