### ISSUE TITLE
Linux platform can't be selected in the dropdown menu in the support form

### ISSUE THREAD

**Issue by madalincm** [mozilla/fxa#7422]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 x64

**Pre-requisites**
- The user has created a vpn subscription.

**Steps to reproduce**
1. Open the subscriptions page: https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions
2. Click on the Contact Support blue button
3. Select Mozilla VPN in the "What are you contacting us about" field
4. Click on the "Do you need help with a specific app or service? (optional)" field to open the drop down menu

**Expected results**
Linux(Ubuntu) option is displayed.

**Actual Results**
Only Android, iOS and Windows options are displayed, the user can't select Linux.

![image](https://user-images.githubusercontent.com/15685441/106782297-ab2aea80-6652-11eb-83b9-ec5c5e324470.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2978)
┆Issue Number: FXA-2978

**Comment by chenba** [comment]
This can be fixed by adding ubuntu to the VPN's Stripe product's metadata.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Stage's been updated.  Prod's in discussion; I'll leave that up to folk in charge of the product itself.

**Comment by madalincm** [comment]
I have checked both Prod and Stage environment.
In production we currently displayed the correct list: 
![image](https://user-images.githubusercontent.com/15685441/108202728-4085ae80-712a-11eb-9645-0df7f1099221.png)

For Stage we now have Linux but Mac is missing. Also can we have the same strings list in both environments (there are a few differences: Linux (Ubuntu) in stage, Linux in prod; Apple iOS in prod, iOS in Stage) 
![image](https://user-images.githubusercontent.com/15685441/108202818-5b582300-712a-11eb-85a2-cda20103658b.png)
