### ISSUE TITLE
[FxA-Settings] “Delete account” button from Step 2 page is displayed on 2 lines on Android

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7443]
**Build**
Prod [Train 1.199.0]

**Affected platforms**
Android 11

**Affected devices**
Motorola G6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Scroll down at the bottom of the page.
3. Click on the "Delete account" button.
4. Check all 4 available options and click on the "Continue" button.
5. Observe the “Delete account” button.

**Expected results**
"Delete account” button is displayed on a single line - See [Figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A201)

**Actual Results**
“Delete account” button is displayed on 2 lines.

![Screenshot_29](https://user-images.githubusercontent.com/18114210/107053607-aa6f9100-67d7-11eb-9985-95fdbd3627b0.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2988)
┆Issue Number: FXA-2988

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I think the problem here is that there's too much text from the width of the button.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

For English, changing the button text to "Delete" should work.  It probably works with most languages.

[~adavis@mozilla.com] what do you think?

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~adavis@mozilla.com] says "Delete" works for him

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.201.0] under Android 9, Android 11 and iOS 14.4. I confirm that 'Delete' button is correctly displayed on Step 2 of 2 Delete Account page on mobile devices but it has too small dimension on desktops (issue tracked separately in FXA-3110 ).
