### ISSUE TITLE
[fxa-auth-db-mysql] Drop the memory db

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#745]
Post-docker there's no utility in the memory db. Deleting would mean we don't have to implement everything twice and remove the possibility of behavioural discrepancies between the different db backends.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-792)
┆Issue Number: FXA-792

**Comment by shane-tomlinson** [comment]
We should also remove the memory databases in the oauth and profile servers while we are at it.

**Comment by shane-tomlinson** [comment]
@vbudhram mentions there may be some scripts that need to be updated before we can do this.
