### ISSUE TITLE
[prod] Subscriptions are not working for Mozilla VPN

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#7466]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.199.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Be in a region where Mozilla VPN is available;

#### Steps to reproduce:
1. Open Mozilla VPN page: https://vpn.mozilla.org/ 
2. Click “Try Mozilla VPN” button;
3. Sign up;

#### Expected result:
- You are redirected to the “Set up your subscription” page;

#### Actual result:
- An error is displayed.

#### Notes:
- Stage subscription page is loaded;
![image](https://user-images.githubusercontent.com/15685960/107378045-43fab380-6af4-11eb-90df-3fa7445f2546.png)

Console:
![image](https://user-images.githubusercontent.com/15685960/107377814-0ac24380-6af4-11eb-8a37-e2d39b5b7b39.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3001)
┆Issue Number: FXA-3001

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing this.  The deploy hadn't completed.  This is fixed now.

**Comment by ValentinaPC** [comment]
Verified as fixed on Windows 10, Firefox 85.0.1.
The prod subscription page is loaded with success.
![image](https://user-images.githubusercontent.com/15685960/107483938-6b03c480-6b8a-11eb-9ce0-e07b6e070638.png)
