### ISSUE TITLE
Update subscription handler for payment verification

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7468]
The stripe/paypal new subscription handlers on the backend need additional checks that verify the chosen plan is a match for the users payment source. This should use the verification function from FXA-3003.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3004)
┆Issue Number: FXA-3004

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

[~bbangert@mozilla.com] does https://github.com/mozilla/fxa/pull/7508 ( https://github.com/mozilla/fxa/pull/7508 ) cover this in the end.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Yup!

**Comment by birdsarah** [comment]
Closed via #7508
