### ISSUE TITLE
Update stripe setup intent handler for country verification

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7472]
The stripe setup intent handler used in new checkout and subscription management should be updated to use the source country / plan currency verification function and error appropriately if they don't match.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3006)
┆Issue Number: FXA-3006

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

[~bbangert@mozilla.com] does https://github.com/mozilla/fxa/pull/7508 ( https://github.com/mozilla/fxa/pull/7508 ) cover this?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Yes, it does look like it covers this.

**Comment by birdsarah** [comment]
Closed via #7508
