### ISSUE TITLE
[FxA-Settings] Horizontal scrolling on mobile when updating display name

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7477]
## Description

Unexpected horizontal scrolling on mobile when changing display name.
submitted by: Alex Davis

### Steps to reproduce

Click “Change” to change display name
Select the field to start typing

### Expected result

There’s no horizontal scrolling on mobile

### Actual result

When inputting text in a field, it zooms in and creates a horizontal scroll which makes for a weird experience.

### Environment

iOS 14.2
[rbillings: I was unable to repro on Android]

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3016)
┆Issue Number: FXA-3016

**Comment by rbillings** [comment]
<img width="207" alt="Screen Shot 2021-02-09 at 11 51 47 AM" src="https://user-images.githubusercontent.com/737878/107419968-3d0c7a80-6acd-11eb-97f5-958d467a4d3c.png">

**Comment by vasilicatamas** [comment]
I suspect that this is an iOS feature. It is reproducible even on Safari on nonrelated Firefox fields. Each time a field is focused and the typing cursor is enabled the textbox aria is zoomed in.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

This is potentially caused by our sticky header. We don't zoom back out due to sticky header when iOS zooms in to the field.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.201.0] under iOS 14.4. The textbox aria is no longer zoomed and the horizontal scrolling bar is no longer displayed.
