### ISSUE TITLE
Optimize favicon icon

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#748]
Found this while looking at https://github.com/mozilla/fxa/issues/675. Our favicon is 66 KB and 256x256. In FF 57, it was 15 KB and 48x48. 

Do we need a favicon this large? Seems like we could optimize and save some loading time.

@ryanfeeley Thoughts?

**Comment by ryanfeeley** [comment]
@vbudhram How hard core do you wanna get? https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/

**Comment by vbudhram** [comment]
@ryanfeeley What about supporting these 7 sizes below? Crossed out the ones that didn't really make sense to me. I don't think we need to be too hardcore here, just better than the 66 KB.

Size | name | Description
-- | -- | --
32×32 | favicon-32.png | Standard for most desktop browsers
57×57 | favicon-57.png | Standard iOS home screen (iPod Touch, iPhone first generation to 3G)
76×76 | favicon-76.png | iPad home screen icon
~96×96~ | favicon-96.png | GoogleTV icon
120×120 | favicon-120.png | iPhone retina touch icon (Change for iOS 7: up from 114×114)
128×128 | favicon-128.png | Chrome Web Store icon & Small Windows 8 Star Screen Icon*
144×144 | favicon-144.png | IE10 Metro tile for pinned site*
~152×152~ | favicon-152.png | iPad touch icon (Change for iOS 7: up from 144×144)
167×167 | favicon-167.png | iPad Retina touch icon (change for iOS 10: up from 152×152, not in action. iOS 10 will use 152×152)
~180×180~ | favicon-180.png | iPhone 6 plus
~192×192~ | favicon-192.png | Google Developer Web App Manifest Recommendation
~195×195~ | favicon-195.png | Opera Speed Dial icon (Not working in Opera 15 and later)
~196×196~ | favicon-196.png | Chrome for Android home screen icon
~228×228~ | favicon-228.png | Opera Coast icon

**Comment by ryanfeeley** [comment]
@vbudhram My hunch is that this got added when we started showing up on new tab, and looked very low resolution. I'll ask some of that team what is best.

**Comment by ryanfeeley** [comment]
@vbudhram  New Tab still uses 48×48. Any idea who is loading the 256px one?

**Comment by ryanfeeley** [comment]
@vbudhram  New Tab still uses 48×48. Any idea who is loading the 256px one?

**Comment by ryanfeeley** [comment]
Looks like 96 is the one we need, thanks to @k88hudson for sleuthing https://searchfox.org/mozilla-central/source/browser/components/newtab/lib/TopSitesFeed.jsm#38
