### ISSUE TITLE
[FxA-Settings] trash icon visible under mobile notification

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7481]
## Description

The trash icon is visible from under the notification bar which could be confusing since it can overlay with the X to dismiss the notification.
Submitted by: Alex Davis

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

Notification should be opaque

### Actual result

<img width="343" alt="Screen Shot 2021-02-09 at 12 07 27 PM" src="https://user-images.githubusercontent.com/737878/107421917-6cbc8200-6acf-11eb-97ba-882752e0096b.png">

### Environment

iOS 14.2

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3020)
┆Issue Number: FXA-3020

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

this is happening in various spaces with z index issues.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.201.0] under iOS 14.4 and Android 9. The notification bar is opaque and the trash icon, refresh icon or Sections title are no longer displayed over the confirmation green bar.
