### ISSUE TITLE
[FxA-Settings] Outdated nomenclature for macOS in Connected Services

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7482]
## Description

Connected Services says “Mac OS X”, which I don't think has been a thing in quite a while (2016, per https://en.wikipedia.org/wiki/MacOS) 

-  Apple shortened the name to "OS X" in 2012 and then changed it to "macOS" in 2016, adopting the nomenclature that they were using for their other operating systems, iOS, watchOS, and tvOS. In 2020, Apple incremented the major version number to 11 in macOS Big Sur, although it retains the same base as the previous versions of macOS.
- 
Submitted by: pdehaan

### Steps to reproduce

- Manage account
- Connected services

### Expected result

macOS

### Actual result

macOS X

### Environment

macOS

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3019)
┆Issue Number: FXA-3019

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Where do we get this from, user-agent?

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Yeah, this gets pulled out of the user agent in a complex regular expression in `fxa-auth-server/lib/userAgent`.

I don't think this should block, since it isn't a change introduced by new-settings.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

After discussing with [~clewis@mozilla.com], setting to lowest priority. This is not a blocker for release but a nice-to-have.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue was verified as fixed on Stage [Train 1.201.1] under macOS 10.14.6. "macOS" is successfully displayed instead of "Mac OS  X" in Connected Services list.
