### ISSUE TITLE
[FxA-Settings] bento box navigation different than on FF Monitor

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7486]
## Description

The bento box navigation is different than on Firefox Monitor (on Monitor we swapped Lockwise for the VPN).

Submitted by: pdehaan

### Steps to reproduce

Clear steps describing how to reproduce the issue. Providing a URL, screenshot.

### Expected result

Matching bento boxes between Settings and Monitor

### Actual result

Different bento boxes

### Environment

macOS

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3023)
┆Issue Number: FXA-3023

**Comment by vasilicatamas** [comment]
This issue is a dupe of #7010
