### ISSUE TITLE
[FxA-Settings] Suggest sidebar nav is sticky

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#7488]
## Description

Not a bug really, more of a UI nit thing… But since the page is now a lot longer, does it make sense for the sidebar nav (Settings, Paid Subscriptions, Newsletters) to be sticky instead of scrolling away?

Submitted by: pdehaan

### Actual result

<img width="332" alt="Screen Shot 2021-02-09 at 12 29 32 PM" src="https://user-images.githubusercontent.com/737878/107424617-be1a4080-6ad2-11eb-9f15-d91cae776995.png">

### Environment

macOS

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3025)
┆Issue Number: FXA-3025

**Comment by vasilicatamas** [comment]
This is a duplicate of [#6967](https://github.com/mozilla/fxa/issues/6967)
