### ISSUE TITLE
Incorrect Mozilla VPN invitation email content

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#7497]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.199.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Be in a region where Mozilla VPN is NOT available;
- Use a Mozilla account for testing purposes;

#### Steps to reproduce:
1. Open Mozilla VPN page: https://vpn.mozilla.org/ 
2. Click “Join to Waitlist” button (top-right page corner);
3. Fill all mandatory fields;
4. Click “Join the Waitlist”;
5. Go to your email client;
6. Check the invitation mail content;

#### Expected result:
- Email content is correct.

#### Actual result:
- Email content is incorrect:
-- only mentions Windows 10, Android, and iOS platforms - missing Linux and Mac;
-- only mentions the US region - missing the UK, Malaysia, New Zealand, Canada and Singapore.

#### Notes:
- even if these exact emails do not get to the users (as they are triggered for testing purposes) we have to make sure that the real invitation emails (when VPN is available in their country) have the correct content.
![image](https://user-images.githubusercontent.com/15685960/107483614-fe88c580-6b89-11eb-8a8a-cac83009205a.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3030)
┆Issue Number: FXA-3030

**Comment by clouserw** [comment]
This is not an FxA bug.  Please file with the VPN team at https://github.com/mozilla-services/guardian-website/issues

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

wontfix
