### ISSUE TITLE
[Epic] E1: Sync CTA when Bookmarking

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#750]
Further details at https://docs.google.com/document/d/1ZE6JF6jUZIkFEdPjyGuKGyw7noCp-kI7RgtRYFM9Yww/edit#

PRD:
https://docs.google.com/document/d/10kzM92hbzcNiydQjnOdC--XJPQ0yvqQACXaHBklDhKc/edit

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-793)
┆Issue Number: FXA-793

**Comment by davismtl** [comment]
@dannycoates I remember seeing this working. Did this ever ship? Or was it put on hold?

Thanks in advance for putting me up to speed.

**Comment by davismtl** [comment]
@dannycoates let's follow up on if this ended up shipping. It will help educate the other CFR ideas.

**Comment by davismtl** [comment]
This shipped, we can track performance here:
https://analytics.amplitude.com/mozilla-corp/chart/new/nszvva7

Jennifer said that UR demonstrated some banner blindness.

Let's see what else we can learn for future experiments.

**Comment by davismtl** [comment]
Need to update the PRD with results too:
https://docs.google.com/document/d/10kzM92hbzcNiydQjnOdC--XJPQ0yvqQACXaHBklDhKc/edit

**Comment by davismtl** [comment]
No update: Skyline is getting most of Leif's attention right now.

**Comment by clouserw** [comment]
epics are tracked in jira
