### ISSUE TITLE
Terms of Service is blank

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7516]
This page is blank for me:  https://accounts.stage.mozaws.net/legal/terms

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3036)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15406/image-2021-02-17-11-27-57-750.png">image-2021-02-17-11-27-57-750.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15348/issue91.gif">issue91.gif</a> | <a href="https://jira.mozilla.com/secure/attachment/15403/privacy.png">privacy.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15304/Screenshot_2021-02-11+Terms+of+Service.png">Screenshot_2021-02-11 Terms of Service.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15347/Screenshot_5.png">Screenshot_5.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15404/terms-rendering.png">terms-rendering.png</a>
┆Issue Number: FXA-3036

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

I'm not seeing this with the terms page, however I am seeing it with privacy. It appears to be an issue with loading the css, the content is in the dom.

!privacy.png!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

QA said they are having problems with the CDN.  jbuck just flushed it - maybe that was making this bug too.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

Cannot reproduce currently in Firefox stable or Edge browser, only seeing this on privacy page in Nightly leads me to believe my browser is doing some hardcore caching here. I saw we wait till monday and see if we can reproduce

**Comment by vasilicatamas** [comment]
"Term of Service" and "Privacy Notice" pages are still blank on Stage [Train 1.200.0] under Windows (Firefox 85.0.2), Android 9 and iOS 13.6.

![Screenshot_38](https://user-images.githubusercontent.com/18114210/107941005-be628200-6f91-11eb-85be-ac7da39a628e.png)

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

!image-2021-02-17-11-27-57-750.png!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I'm using nightly from yesterday.  I hard-refreshed (ctrl-F5 on linux) several times on the original link and it was still blank.  Then I cleared the cookie for stage and hard-refreshed again and the text appeared.  So, I agree this is probably client side.

**Comment by 6a68** [comment]
I just visited these pages for the first time and they loaded, though with a FOUC and some unprocessed slugs sprinkled throughout (note the string ` {: datetime="2019-09-10" }` in the screenshot)

<img width="585" alt="Screen Shot 2021-02-18 at 2 35 49 PM" src="https://user-images.githubusercontent.com/96396/108430724-ab9cb700-71f6-11eb-87fd-5001f3ea30c5.png">

Good to close? @vasilicatamas can you still reproduce the issue in a fresh profile?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Unprocessed slugs are not a problem

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

I am still able to reproduce this issue in a new profile when opening the Terms and Service and Privacy Notice pages in the current tab (left click), but the pages are successfully loaded when opened in a separate tab. After opening an empty page, the content will no longer be visible neither in separate tabs until the cookies are cleared. Tested on both Windows 10 and macOS 10.14.6. I am attaching a screenshot and a screencast with this issue.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thanks for the STR, [~vtamas@mozilla.com]! I can reproduce as well if I start from the login page and load in the same page.

**Comment by 6a68** [comment]
Note that I am seeing this in production. I'm also seeing some console errors that indicate something's wrong with the build process:

On production:
GET https://accounts.firefox.com/legal/%7B%7B%7B%20staticResourceUrl%20%7D%7D%7D/styles/0f28b76a.main.css
[HTTP/1.1 404 Not Found 43ms]

On stage:
GET https://accounts.stage.mozaws.net/legal/%7B%7B%7B%20staticResourceUrl%20%7D%7D%7D/styles/0f28b76a.main.css
[HTTP/1.1 404 Not Found 84ms]

Note that this URL, unescaped, is `https://accounts.firefox.com/legal/{{{ staticResourceUrl }}}/styles/of28b76a.main.css`.

So it looks like some variable isn't getting substituted correctly.

**Comment by 6a68** [comment]
It turns out there used to be two versions of the terms and privacy notices: one rendered as a partial template, and one rendered as a full html page. The partials were lost in some recent changes, so when the page is served up, a page is loaded into the bigger page. The terms / privacy pages appear blank because there's a fade-in effect applied to the content wrapper, `<div id="stage">`, but now that an html page is getting loaded into another page, there are actually two nested content wrapper els with that ID, and the fade-in animation is only getting applied to the outer one:

<img width="1153" alt="Screen Shot 2021-02-25 at 3 53 55 PM" src="https://user-images.githubusercontent.com/96396/109357276-d0b4a980-7836-11eb-85ce-ed66604cfb2d.png">

The fix is to update the l10n generator grunttasks to restore the missing partial templates. Working on a fix.

**Comment by 6a68** [comment]
Draft PR opened. I'll plan to land the fix early next week.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.201.1] under Windows 10 64-bit, macOS 10.14.6, Android 9 and iOS 14.4. I confirm that "Terms of Service" and "Privacy Notice" pages are successfully loaded in the same tab.
