### ISSUE TITLE
[Epic] E3: Sync / Lockbox CTA when Saving Password

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#752]
Further details at https://docs.google.com/document/d/1ZE6JF6jUZIkFEdPjyGuKGyw7noCp-kI7RgtRYFM9Yww/edit#

**Comment by davismtl** [comment]
This might not require anything from this team after all. Jim has mentioned that they are looking to do this entirely with Sandy and CFR.

**Comment by davismtl** [comment]
Being done by another team.

**Comment by clouserw** [comment]
We're not going to work on this, so closing.
