### ISSUE TITLE
Upload too large errors on avatar upload

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7536]
Seeing errors indicating that the image is too large for upload on stage, not seeing locally.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3045)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15502/greg-rakozy-oMpAz-DN-9I-unsplash.jpg">greg-rakozy-oMpAz-DN-9I-unsplash.jpg</a> | <a href="https://jira.mozilla.com/secure/attachment/15501/Screenshot_26.png">Screenshot_26.png</a>
┆Issue Number: FXA-3045

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

This should be fixed by https://github.com/mozilla/fxa/pull/7565

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this issue on Stage [Train 1.201.1] under Windows 10 64-bit and macOS 10.14.6 and I received the 'The image file size is too large to be uploaded.' error when uploading the attached image. This error was not encountered in the old Settings page and the picture was successfully uploaded. Reopening

**Comment by dannycoates** [comment]
this is prob fixed after #7924
