### ISSUE TITLE
[Epic] E5: FxA Onboarding Notifications (Phase 2)

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#754]
Further details at https://docs.google.com/document/d/1ZE6JF6jUZIkFEdPjyGuKGyw7noCp-kI7RgtRYFM9Yww/edit#

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-796)
┆Issue Number: FXA-796

**Comment by davismtl** [comment]
@davismtl  to dedupe this so that we consider within Q4 goals relating to CFR.
