### ISSUE TITLE
unhandled errors in settings page

### ISSUE THREAD

**Issue by minusf** [mozilla/fxa#7584]
## Description

I have no idea where to report bugs for accounts.firefox.com, I cannot find any contact information on any of the pages, which seems rather strange for a customer facing service.

I started using firefox sync with a gmail address.  Later I moved to a different mail provider and I added it as a new secondary email, which i changed to primary and deleted the old primary gmail address. Now I am not able to either change my password and/or delete my old account. The "change" and "delete" buttons seemingly do nothing.  The inspector reveals the returned and unhandled `400` and `429`, where the `400` is still referring to my the old gmail address:

https://api.accounts.firefox.com/v1/session/reauth

```
{"code":400,"errno":120,"error":"Bad Request","message":"Incorrect email case","info":"https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format","email":"...@gmail.com"}
```
and
```
{"code":429,"errno":114,"error":"Too Many Requests","message":"Client has sent too many requests","info":"https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format","retryAfter":900,"retryAfterLocalized":"in 15 minutes","verificationMethod":"email-captcha","verificationReason":"login"}
```

### Steps to reproduce

Create a firefox sync account, change the email address later.

### Expected result

Should be able to delete account and/or change password

### Actual result

Cannot do either.

### Environment

macOS Big Sur, firefox 85.0.2

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3067)
┆Issue Number: FXA-3067

**Comment by minusf** [comment]
i have tried again later and the password change went through.  is the issue on my side, and feedback for these errors exist in the account settings page?

**Comment by clouserw** [comment]
Thanks for trying again.  You can see in the second error message we began rate limiting due to too many requests.  As you found, that rate limit expires after a while.  Since this is working, I'm going to close this.  Thanks for getting in touch.

**Comment by minusf** [comment]
well... ok, but i think the lack of user feedback what's going on is rather poor UX...

**Comment by clouserw** [comment]
Thanks for your feedback.  A new major design is launching, hopefully, in mid-March.
