### ISSUE TITLE
Bring back GitCop (or something like it)

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#759]
There's been a noticeable (and totally understandable) drop in the quality of commit messages in recent weeks, with all of the activity that's been going on around Outreachy and GSoC. It's made me re-evaluate the benefit of GitCop, which might seem funny given how in favour I was of getting rid of it before.

Reinstating it would relieve us of the burden of reminding/linking to the contribution guidelines every time and hopefully it would reduce the occasions where we forget to check the commit message and they end up reaching our changelogs. The new release script works much better if the commit messages are uniform too.

Thoughts?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-797)
┆Issue Number: FXA-797

**Comment by shane-tomlinson** [comment]
It wasn't helping us then, but I think it could now with all the new contributors.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Our commit messages are pretty consistent now.  Closing this.
