### ISSUE TITLE
New Accounts having issues connecting to Sync Server on Stage and Latest

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#76]
cc @jrgm @rfk 

## STR

1. Setup fxa-local-dev
1. Run `FXA_ENV=stage npm start` - this will use Stage config and start a fresh Firefox
1. Create a new account and verify it in the same browser

## Expected

Sync should connect after verification

## Actual

Sync asks to reconnect
![](http://i.imgur.com/ba2xWiu.png)

## Info

Full Firefox log against `latest` here: https://gist.github.com/vladikoff/dd3a1ba2b9394d5b8c3d

Stage SHA: 

```
{
  "commit": "072e79a99c57466869b2342493701eb1c23290a3",
  "version": "0.49.2",
  "l10n": "5fcfa1c18f",
  "tosPp": "b86f95ea39",
  "source": "https://github.com/mozilla/fxa-content-server.git"
}
```

Stable SHA:
```
{
  "commit": "35797ad396353545c46af139144d8a8a37a4b02b",
  "version": "0.48.0",
  "l10n": "d5315da685",
  "tosPp": "262dbc7dab",
  "source": "https://github.com/mozilla/fxa-content-server.git"
}
```

This is broken for me on:
- local servers
- stage
- latest

This works for me in:
- production 
- stable

FF41 Screenshot:
![](http://i.imgur.com/qChtLMc.png)

**Comment by vladikoff** [comment]
cc'ing @mhammond on this as well. Maybe there is something obvious in the log? https://gist.github.com/vladikoff/dd3a1ba2b9394d5b8c3d

**Comment by rfk** [comment]
> Full Message: No keyFetchToken

To me, this suggests that we've accidentally refactored something in the content-server, and it's no longer generating the keyFetchToken and including it in the "signed in" message that gets sent to the browser.

**Comment by jrgm** [comment]
Syncing works for me on stage with Fx42.0 on osx configured to use stage urls.

**Comment by rfk** [comment]
STR for me:

* `FXA_ENV=stage npm start` to run a fresh profile against stage
* Sign up with a new account
* Open the verification link *in the same browser*
* The account gets verified, and the browser transitions to "reconnect to sync state".

On the other hand, this works fine:

* `FXA_ENV=stage npm start` to run a fresh profile against stage
* Sign up with a new account
* Open the verification link *in a different browser*
* The account gets verified and the browser correctly connects to sync

So I suspect some recent refactoring of cross-tab signalling may be the cause of this.

**Comment by rfk** [comment]
Using fxa-local-dev and `git bisect`, it tells me that this bug was introduced in https://github.com/mozilla/fxa-content-server/commit/ecebd942ee5672198d308d453982aae9f2b8f01f, corresponding to this PR:

  "synchronise signed-in state across tabs"
  https://github.com/mozilla/fxa-content-server/pull/3232

Which matches with the fact that it only happens when verifying in the same browser.

**Comment by jrgm** [comment]
I can reproduce using fxa-local-dev. However, it works fine if I create my own new profile, adjust settings to use stage urls and restart and sign up for a new sync account.

**Comment by rfk** [comment]
As far as I can tell the actual signin is working correctly and a keyFetchToken is being obtained by the browser.  Some subsequent message appears to be clobbering the state.  Here's an interesting snippet from a failed sync log (with harmless local-in-memory-only tokens etc):

```
1446774391736   FirefoxAccounts DEBUG   FxAccountsWebChannel message received: {"command":"fxaccounts:login","data":{"email":"ryan-12@rfk.id.au","lastLogin":1446774379150,"needsOptedInToMarketingEmail":false,"sessionToken":"ac300502042c394244e0e1b5cf72dd4026121cde05c63b31cff3bbe5e296d904","sessionTokenContext":"fx_desktop_v1","uid":"bf15e495f27f45889e61bbb9a14df709","verified":false},"messageId":null}
1446774391737   FirefoxAccounts DEBUG   setSignedInUser - aborting any existing flows
1446774391737   FirefoxAccounts DEBUG   Polling aborted; Another user signing in
1446774391737   FirefoxAccounts TRACE   StorageManager finalizing
1446774391737   FirefoxAccounts INFO    the wait for user verification was stopped: Error: Verification aborted; Another user signing in
1446774391738   FirefoxAccounts INFO    startVerifiedCheck promise was rejected: Error: Verification aborted; Another user signing in
1446774391738   FirefoxAccounts INFO    startVerifiedCheck promise was rejected: Error: Verification aborted; Another user signing in
1446774391738   FirefoxAccounts INFO    startVerifiedCheck promise was rejected: Error: Verification aborted; Another user signing in
1446774391738   Sync.BrowserIDManager   ERROR   Background fetch for key bundle failed: Error: Verification aborted; Another user signing in (resource://gre/modules/FxAccounts.jsm:96:1) JS Stack trace: abort@FxAccounts.jsm:96:1 < abortExistingFlow@FxAccounts.jsm:572:12 < setSignedInUser@FxAccounts.jsm:483:12 < login/<@FxAccountsWebChannel.jsm:231:14 < Handler.prototype.process@Promise-backend.js:934:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:813:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:747:1
1446774391738   Sync.BrowserIDManager   ERROR   Could not authenticate: Error: Verification aborted; Another user signing in (resource://gre/modules/FxAccounts.jsm:96:1) JS Stack trace: abort@FxAccounts.jsm:96:1 < abortExistingFlow@FxAccounts.jsm:572:12 < setSignedInUser@FxAccounts.jsm:483:12 < login/<@FxAccountsWebChannel.jsm:231:14 < Handler.prototype.process@Promise-backend.js:934:23 < this.PromiseWalker.walkerLoop@Promise-backend.js:813:7 < this.PromiseWalker.scheduleWalkerLoop/<@Promise-backend.js:747:1
```

When I open the verification link in another browser, this `"fxaccounts:login"` webchannel message is not received and the error does not occur.  So I suspect something in the linked commit is either causing this to be sent anew, or sent sooner than it was previously, and is causing FF to abort its keyFetch, clobber its local state, and freak out.

**Comment by rfk** [comment]
> So I suspect something in the linked commit is either causing this to be sent anew

Yip:

  https://github.com/mozilla/fxa-content-server/pull/3232/files#diff-0dc8124c36f55037d013efdc72d8eaa8R95

The signup-complete page is sending a new "login" message, that goes out over webchannel and causes the browser to reset its state.  Commenting out that line resolves this error for me in fxa-local-dev.

**Comment by mhammond** [comment]
Yeah, desktop really isn't expecting that login message - about:accounts is also doing its own thing to set the logged in state.

I'm 1.2 way through a review of https://bugzilla.mozilla.org/show_bug.cgi?id=1218022, and even though that's only about "choose what to sync", I was 1/2 expecting that patch to cause about:accounts to *not* handle the login notification and for the server to only send the webchannel login message when context=fx_desktop_v2

**Comment by mhammond** [comment]
hmm - also, if I'm reading that patch correctly, it looks a little like every tab open to the server might get the message, which would be bad as our singleton module would see all of them. If we do want the client to move to webchannel login messages, we'd only want 1 from that tab that actually did the login.

That might not be the case, but the repeated "startVerifiedCheck promise was rejected" messages in the log above makes me think it might be.

**Comment by rfk** [comment]
I filed https://github.com/mozilla/fxa-content-server/issues/3267 to surface this issue into the content-server repo.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-content-server/releases/tag/v0.49.3

Thanks for tracking this down Ryan, and thanks Shane and Phil for pushing the fix!
