### ISSUE TITLE
[Train-134] iOS not displayed as connected device on Android 9

### ISSUE THREAD

**Issue by lobontiumira** [mozilla/fxa#760]
**Environment:** Samsung Galaxy S8 (Android 9), iPhone SE (iOS 12.1.4), Windows 10
Build: Stage server - Train 134

**STR:**

1. Sign in on iOS, Android and Windows 10 with the same account.
2. Go to Manage Accounts - Devices & Apps and observe the connected devices.

**Expected results:**
All devices should be displayed.

**Actual results:**
On Android, the iOS device is not displayed, it appears that none is connected.

**Notes:**
1. I've attached a screenshot.
2. On iOS and Windows 10, all devices are displayed as connected.

![devicesnotdisplayed](https://user-images.githubusercontent.com/40694158/55614846-a2d3a100-5796-11e9-833f-3719c3bef3df.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-798)
┆Issue Number: FXA-798

**Comment by shane-tomlinson** [comment]
Something is up with iOS, it's registered as a Web Session on the left, indicating the device might not have registered itself.

**Comment by shane-tomlinson** [comment]
cc @justindarc
