### ISSUE TITLE
[Train-134] Cannot send a tab from Desktop to a connected Android device

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla/fxa#762]
**Environment:** Samsung Galaxy S8 (Android 9), Windows 10
Build: Stage server - Train 134

**STR:**
1. Sign in on iOS, Android and Windows 10 with the same account.
2. Go to Manage Accounts - Devices & Apps and observe the connected devices - on all three devices.
3. On Desktop right-click on an opened tab and select "Send tab to devices".

**Expected results:**
All devices should be displayed as connected.

**Actual results:**
Only iOS device appears connected, although on Synced tabs and on Manage accounts - Devices&Apps, Android is also connected. The user is unable to send a tab to an Android device.

**Note:**
 - I've attached a screenshot.

![Screenshot_3](https://user-images.githubusercontent.com/40694158/55626182-7aa66b00-57b3-11e9-87b9-848c0751f9ef.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-799)
┆Issue Number: FXA-799

**Comment by shane-tomlinson** [comment]
This seems like Firefox Desktop has not refreshed its list of devices. If you force a sync does the problem still occur?

**Comment by softvision-miralobontiu** [comment]
Hi Shane!
Yes, I tried several times to force sync, I even disconnected and reconnected to see if it is reproducible.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Does this still happen?  This does sound like it needed to sync and maybe things were just slow at this time.

**Comment by softvision-miralobontiu** [comment]
Hi all,
I've retested on Train 165 with OnePlus 5T (Android 9), Google Pixel (Android 10), and Windows 10.
I was able to connect all three devices, to send tabs between them.
I will close this issue.
