### ISSUE TITLE
Refactor goBack/goHome callback names

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#7630]
Review comment from https://github.com/mozilla/fxa/pull/7628:

> This is only a suggestion but what if we renamed goBack to goHome and goHome to something like alertSuccessAndGoHome

The `goBack` and `goHome` functions really do mean something like "go back to settings" and "go back to settings and show a success alert message".

The task here is just to search and replace the `goBack` and `goHome` function names with something clearer throughout the Page components in the fxa-settings package.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3093)
┆Issue Number: FXA-3093

**Comment by GuptaTanisha** [comment]
@6a68 Should I work on this issue?

**Comment by YashKamboj** [comment]
@6a68  hey this is my first contribution can you help me a little . Hope to hear from you soon

**Comment by 6a68** [comment]
Hey there 👋 

Advice for both of you: you can get started by going through the instructions in the top-level readme. Join us on [matrix](https://chat.mozilla.org/#/room/#fxa:mozilla.org) if you have any questions, or to ask for help if you get stuck for longer than 20 minutes.

@GuptaTanisha I've assigned this bug to you. You can ping me here if you have questions about the bug (matrix is also fine).

@YashKamboj Hi, there are many other issues with the good first bug label. Feel free to look through those and ping me if there's one you would like to work on, and I'll assign it to you.

**Comment by GuptaTanisha** [comment]
Hi, I want verification proof for my college resume that I have contributed in your open source project. Can you help you writing few lines on my contribution?
