### ISSUE TITLE
Update QA Test plan & tech spec when full multi-currency handling implementation is complete

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7631]
After multi-currency support is implemented, make sure QA test plan is updated to test the different possibilities.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3094)
┆Issue Number: FXA-3094

**Comment by birdsarah** [comment]
Completed via a google doc and email.

**Comment by data-sync-user** [comment]
➤ Sarah Bird commented:

Done. Emailed QA. The doc is here: https://docs.google.com/document/d/1ocg_Ete3lkOvms7rtDmF0uYP2s9Ru8JV89iZQFHhu2E/edit
