### ISSUE TITLE
[Train-134] Emails over 26 characters are not entirely visible on pop-up "Save" page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla/fxa#764]
**Environment:** Samsung Galaxy S8 (Android 9), Windows 10
Build: Stage server - Train 134

**STR:**
1. Sign in Android or Windows 10 with an account which has more than 26 characters.
2. Observe the "Save" pop-up page.

**Expected results:**
 The entire email should be visible

**Actual results:**
 The email is not visible entirely.

**Note:**
 It is reproducible on Android and Desktop.
 It is caused by [#7043](https://github.com/mozilla/fxa-content-server/pull/7043). 

![Screenshot_1](https://user-images.githubusercontent.com/40694158/55630182-c1995e00-57bd-11e9-8acf-de13a74d03a9.png)

**Comment by shane-tomlinson** [comment]
This is Firefox UI and FxA has no control over this.
