### ISSUE TITLE
[Train-134] Emails over 26 characters are not entirely visible on Manage account page

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla/fxa#765]
**Environment:** Samsung Galaxy S8 (Android 9), Windows 10
Build: Stage server - Train 134

**STR:**
1. Sign in Android or Windows 10 with an account which has more than 26 characters.
2. Go to Manage Account and observe the page.

**Expected results:**
The entire email should be visible

**Actual results:**
The email is not visible entirely.

**Notes:**
It is reproducible on Android and Desktop.
It is caused by #7043.

![Screenshot_2](https://user-images.githubusercontent.com/40694158/55630602-b98dee00-57be-11e9-838a-3dd8f0b7be0a.png)

**Comment by shane-tomlinson** [comment]
UX informs us this is as expected.
