### ISSUE TITLE
Add feature to administratively disable account

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#7651]
We should have the ability to administratively disable accounts that would prevent users from making any changes to their account, as well as signing in to their account or any reliers

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3101)
┆Issue Number: FXA-3101

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Does this map to a database field that we can just toggle?  If so, this is a small amount of work.

We should add a log line about who did it and when so we can dig into big query if we ever need it.

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

[~dcoates@mozilla.com] asked me in Slack:

> What should the disabled user see,
> 1) a generic "couldn't sign in" error, intentionally vague.
> 2) a descriptive message with some way to contact us (bugzilla, etc)
> 3) something else

I am open to input from others ([~adavis@mozilla.com]?) but I think an intentionally vague message is the way to go
