### ISSUE TITLE
Consider adding secondary email to profile data for OAuth clients

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa#7660]
I did not see an issue for this already, although I think we've discussed this before?

In Relay especially, I'd like to be able to access an FXA user's secondary email address.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3103)
┆Issue Number: FXA-3103

**Comment by 6a68** [comment]
We talked through a potential design on Slack:

* add a `secondary_emails` field to the profile data, making the user's emails visible to RPs requesting the `profile` scope 
* for consistency, add a `profile:secondary_emails` scope that's included in the `profile` read scope
* I'm not sure if we need to have a privacy discussion about exposing this additional data to RPs

@rfk, any thoughts on this approach?

Adding a scope involves a decent amount of boilerplate changes, between auth and profile servers, but we've done it recently for the subscriptions scope and the ecosystem_anon_id scope, so there are good recent examples to follow.

**Comment by rfk** [comment]
Sounds reasonable to me 👍 

> Adding a scope involves a decent amount of boilerplate changes, between auth and profile servers

Right, I guess this is another one of those situations where you're exposing data owned by the auth-server, so you've got to route it through the special "core profile" plumbing on profile-server. Bleh, but, manageable.
