### ISSUE TITLE
Can we reduce fxa-email-service build time in CI?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#767]
Currently ~20 minutes. Could we speed it up with a custom docker image or the ci cache (`restore_cache`)?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-800)
┆Issue Number: FXA-800

**Comment by vladikoff** [comment]
yeah, you can take out the rust build step out of the remote docker environment, see https://github.com/mozilla/fxa-email-service/pull/272 then the build is gonna be around 4 minutes
