### ISSUE TITLE
[FxA-Settings] "Save" button changes its dimensions while saving a profile picture

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7702]
**Build**
 Stage [Train 1.201.1]

**Affected platforms**
 iOS 14.4
 Android 9
macOS 10.14.6

**Steps to reproduce**

1. Navigate to [https://accounts.stage.mozaws.net/beta/settings/](https://accounts.stage.mozaws.net/beta/settings/) and login using an existing account.
1. Click on the "Add" button displayed on the right side of the Picture section.
1. Click on the "Add photo" button.
1. Select an image and click the "Open" button.
1. Click on the "Save" button.

**Expected results**
 "Save" button maintains its default sizes.

**Actual Results**
 "Save" button modifies its height during the saving process.

**Additional notes:**
 This issue is not reproducible on Windows 10 64-bit.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3120)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15393/gif14.gif">gif14.gif</a>
┆Issue Number: FXA-3120

**Comment by karinabk** [comment]
I implemented a simple fix here. If you have a more appropriate solution, please share! @jodyheavener @LZoog 
Also, I assumed that there is a mistake in the issue description since height doesn't change

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.2] under Windows 10 64-bit, macOS 10.14.6, Android 9 and iOS 14.4. I confirm that the "Save" button successfully maintains its default size during the saving process.
