### ISSUE TITLE
[FxA-Settings] The picture avatar is black when setting an image taken with the camera on iOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7705]
**Build**
 Stage [Train 1.201.1]

**Affected platforms**
 iOS 14.4

**Steps to reproduce**

1. Navigate to [https://accounts.stage.mozaws.net/beta/settings/](https://accounts.stage.mozaws.net/beta/settings/) and login using an existing account.
1. Tap on the "Add" button displayed on the right side of the Picture section.
1. Tap on the "Add photo" button.
1. Tap on the "Take photo" button.
1. Take the photo and tap on the "Use photo" option.
1. Tap on the "Save" button.

**Expected results**
 The picture captured with the camera is successfully displayed.

**Actual Results**
 The picture avatar is black.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3123)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15505/gif21.gif">gif21.gif</a>
┆Issue Number: FXA-3123

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~vtamas@mozilla.com] [~rbillings@mozilla.com] this has been added to next train (Fxa 203) as we do not see it as a blocker for release.

**Comment by dannycoates** [comment]
This is because we're creating too big of a canvas here and ios nopes out: https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/lib/canvas-utils.tsx#L37

We should refactor this function to be more efficient

**Comment by vbudhram** [comment]
> This is because we're creating too big of a canvas here and ios nopes out

Yea this is exactly what is going on, if you `maxSize/2` , then the picture gets uploaded properly. Seems like we could use something like https://github.com/jhildenbiddle/canvas-size, but maybe that is a bit overkill?

I'm not too familiar with this code, so a little uncertain how to make it more efficient.

**Comment by vbudhram** [comment]
Looks like there are a few issues with Safair when using the camera and cropping in general. It doesn't crop correctly on desktop.

<img width="601" alt="Screen Shot 2021-03-16 at 1 37 24 PM" src="https://user-images.githubusercontent.com/1295288/111354715-fa563900-865c-11eb-961d-1df37660d6c0.png">

New settings uses `react-easy-crop` library but I haven't narrowed down the cause. @meandavejustice do you recall any issues when working on avatar upload or have any pointers to tackle this bug?

**Comment by meandavejustice** [comment]
We are using react-easy-crop for uploads and captures to ensure it's the correct shape/dimension. Without digging into this issue locally, I would recommend taking a look at these functions:

- https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/PageAvatar/index.tsx#L122
- https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/PageAvatar/index.tsx#L114

Ping me on slack if you'd like to pair on this

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified on Stage [Train 1.203.2] under iOS 14.4. The picture captured with the camera is no longer displayed as black image.
