### ISSUE TITLE
[FxA-Settings] FxA Bento icon does not have a focus effect

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7706]
**Build**
Stage [Train 1.201.1]

**Affected platforms**
Windows 10 x64
macOS 10.14.6

**Steps to reproduce**

1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
1. Focus the Bento icon using the Tab key.

**Expected results**
Bento icon successfully displays a focus effect.

**Actual Results**
There is no focus effect displayed when the Bento icon is selected using the Tab key.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3124)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15506/gif22.gif">gif22.gif</a>
┆Issue Number: FXA-3124

**Comment by sunny775** [comment]
Hi! ✋ @LZoog . I am an Outreachy applicant and would love to work on this issue as my first contribution

**Comment by LZoog** [comment]
Hey @sunny775, since I just assigned another good first issue to you I'll leave this one open, but feel free to circle back here when the PR is merged for the other! :)

Here's the attached image:
![gif22](https://user-images.githubusercontent.com/13018240/113456484-f9e6cd80-93d2-11eb-9cdc-8ee41e219a5a.gif)

**Comment by sunny775** [comment]
Sure @LZoog . Thanks a lot :)

**Comment by flozender** [comment]
I'd love to pick this up!

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.2] under Windows 10 64-bit, Android 9 and iOS 14.4.  I confirm that the Bento icon successfully displays a focus effect while using the Tab key.
