### ISSUE TITLE
Fix Settings buttons in German

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#771]
STEPS TO REPRODUCE
1. Visit Settings in German

EXPECTED RESULTS
1. In German, buttons to cancellable dialogs are appended by a space AND an ellipsis (e.g. `Aktivieren …`)
2. Button text does not wrap, but buttons widen to fit the content when necessary

ACTUAL RESULTS
![18iU6DWOPI32CJvsWHHnfrl9jkbB4mQBSwYlSoVPNM9aBCTHeXGt7voEGENggAurAZ_W1V-TTitBoUThOymLz3Ub3XVRwU6iSihFTo0op9Br-Ygn_mM8UcN91EVIIF7md0yMnpP-rMwDI8tTP8LpA8q1hy3_520J_tIpCmj80EWk7seHpc3uGOC_jeBU0nFB_P4EDe6lsDZiagvzAWvVvYS0j24-QHOYC7](https://user-images.githubusercontent.com/68213/55671441-0a085880-585e-11e9-93f2-6c30139a6806.png)

**Comment by shane-tomlinson** [comment]
I thought we already resized the buttons based on text width, did we never do this?
