### ISSUE TITLE
[FxA-Settings] Too much white-space before and after "Resend verification code" text

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7724]
**Build:**
Stage [Train 1.201.1]

**Affected platforms:**
Windows 10 Enterprise
Android 8

**Preconditions:**
User has already added a secondary email address in Unverified state.

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and log in using an existing account.
1. Click on the 'Switch to new design' button.
1. Go to the Secondary email section and observe the "Resend verification code" text.

**Expected result:** 
Single white-space is displayed before and after 'Resend verification code' text.

**Actual result:** 
Too much white-space is displayed before and after 'Resend verification code' text.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3131)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15508/Screenshot_31.png">Screenshot_31.png</a>
┆Issue Number: FXA-3131

**Comment by LZoog** [comment]
If a contributor would like to pick this up, they can find this by running FxA locally and navigating to `beta/settings` (it doesn't have to be on staging). This should remain a button since that's semantically correct, but the fix is to remove the left/right padding.

**Comment by shivanisinghnitp** [comment]
I am an outreachy applicant! Can you sign this to me? Thanks!

**Comment by CarolVilarino** [comment]
Hi i'm an outreachy applicant ! I picked none issues until now, can this be assigned to me ? or another one ;)

**Comment by jodyheavener** [comment]
Hi @CarolVilarino! Sure thing, I've assigned you.

**Comment by CarolVilarino** [comment]
@jodyheavener  can you assign this to someone else, I had some issues with my computer

**Comment by dhruva248** [comment]
@jodyheavener If no one is interested, can I work on this?

**Comment by LZoog** [comment]
@dhruva248 are you still interested in picking this up? I can assign you if so 🙂

**Comment by dhruva248** [comment]
@LZoog, thanks for bringing into my notice, i actually named it incorrectly! and done :)

**Comment by LZoog** [comment]
Closed in #8233

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is still reproducible on Stage [Train 1.207.0] on all platforms.
