### ISSUE TITLE
[FxA-Settings] "Printed" tooltip message for recovery key is not displayed on Android

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7735]
**Build:**
 Stage [Train 1.201.1]

**Affected platforms:**
 Android 8

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in using an existing account.
1. Tap on the 'Switch to new design' button.
1. Go to the 'Recovery key' section and tap on the 'Create' button.
1. Enter the correct password and tap on the 'Continue' button.
1. Tap on the 'Print' option.
1. Go back to the 'Recovery key' tab and observe the message.

**Expected result:** 
 'Printed' message is displayed.

**Actual result:** 
 No 'Printed' tooltip message is displayed.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3134)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15516/recovery+key+Printed+message+Android.mp4">recovery key Printed message Android.mp4</a>
┆Issue Number: FXA-3134

**Comment by suyashchauhan** [comment]
I think it is something  browser specific check this 
 https://bugzilla.mozilla.org/show_bug.cgi?id=1247609 
  https://github.com/mozilla-mobile/fenix/issues/13214 
looks like firefox-android doesn't have support for window.print
