### ISSUE TITLE
[FXA-Settings] Category and Subcategory needs left-alignment

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7755]
## Description

Category (e.g., Profile) is not left-aligned with Sub-Category (e.g., Picture) within body of page.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6219141/110505428-248f8000-80cc-11eb-82f0-ad610384680a.png)

### Environment

Nightly

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3158)
┆Issue Number: FXA-3158

**Comment by Jane-Kotovich** [comment]
Hey! I'm an Outreachy applicant could I please grab this issue? thanks!

**Comment by shivanisinghnitp** [comment]
Hello @jodyheavener . Can I work on this? 
Thanks

**Comment by LZoog** [comment]
@Jane-Kotovich @rustproofed @shivanisinghnitp @karinabk I figured I'd give this to whomever didn't already have an issue assigned, but it looks like all 4 of you have an open one at the moment! Let's space it out and if what you're working on gets merged after you put a PR up, you’re more than welcome to comment back here and claim this one. 😛

**Comment by Jo-bot86** [comment]
Hi @LZoog! Can I work on this? I still have no issue to work on.

**Comment by Deek9399** [comment]
Hello @LZoog, I am an outreachy applicant. Can I work on this issue?

**Comment by jodyheavener** [comment]
Sure thing @Jo-bot86

**Comment by Jo-bot86** [comment]
thank you @jodyheavener

**Comment by Jo-bot86** [comment]
@janiceahn should the subcategories (e.g. picture) be aligned with the category Profile or should the category Profile be moved further to the right?

**Comment by Jo-bot86** [comment]
![grafik](https://user-images.githubusercontent.com/70321115/113309698-b4a99980-9307-11eb-92b3-aab118b486cf.png)
This is what it looks like with the first option
