### ISSUE TITLE
[FXA-Settings] Secondary email subcategory section missing descriptive copy and link

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7756]
## Description

Secondary email subcategory section missing descriptive copy and link.

### As staged

![image](https://user-images.githubusercontent.com/6219141/110505930-9f589b00-80cc-11eb-9a53-2fb66093202e.png)

### Figma spec
two states:

<img width="765" alt="Untitled 2" src="https://user-images.githubusercontent.com/6219141/110506475-1e4dd380-80cd-11eb-9cfe-487c262b7d39.png">

<img width="407" alt="Untitled 3" src="https://user-images.githubusercontent.com/6219141/110506632-44737380-80cd-11eb-9c5d-f815c5298cc7.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3157)
┆Issue Number: FXA-3157

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Closing as dupe of FXA-2984
