### ISSUE TITLE
[FXA-Settings] increase modal horizontal padding

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7762]
## Description

Modal padding (left, right) needs to be increased

### Steps to reproduce
<img width="491" alt="Untitled 2" src="https://user-images.githubusercontent.com/6219141/110516128-2d398380-80d7-11eb-9649-7014637c671f.png">

### Expected result

<img width="372" alt="Untitled 2" src="https://user-images.githubusercontent.com/6219141/110515871-df248000-80d6-11eb-8c64-118a3ead687d.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3151)
┆Issue Number: FXA-3151

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is a good first issue but we need to put the actual padding values we want to use here.  I assume it is in the spec.

**Comment by LZoog** [comment]
Looks like this should be 48px of padding on either side:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/13018240/112683283-4f553480-8e3f-11eb-97fb-932418286c31.png">


If a contributor would like to pick this up, they can find this modal on the Settings page. Be sure to use a Tailwind class.

**Comment by rustproofed** [comment]
Hello, I'm an Outreachy applicant. I would also like to fix this.

**Comment by Deek9399** [comment]
Hello! I'm an Outreachy applicant, Can I work on this issue? 
Thank You.

**Comment by jodyheavener** [comment]
Sure thing @Deek9399

**Comment by Deek9399** [comment]
Thank you @jodyheavener

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this issue on Stage [Train 1.204.2] and the result differs depending on the platforms:

  * iOS 14.4: the modal is correctly displayed as it appears in the "Expected results" screenshot
  * Android 9: the text is displayed on 4 lines 
  * Windows 10 and macOS: it seems that there is no 48px of padding as was suggested above

[~lzugai@mozilla.com] Any thoughts about these results?
