### ISSUE TITLE
Fix tests which broke from new Settings layout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7798]
With the change to the new Settings layout quite a few integration tests broke because we didn't update them.  Let's fix that.  This issue might need to be broken apart if there are a lot of them.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3172)
┆Issue Number: FXA-3172

**Comment by 6a68** [comment]
Closed by #7776
