### ISSUE TITLE
FxA-45: clarify handling of unknown device ids

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#78]
As noted in https://github.com/mozilla/fxa/pull/69#discussion_r43880260

When a device presents a device-id that we don't recognize, we can either return an error, or we can magic a new one into existence for it.  Let's pick one and apply it consistently across all endpoints.

**Comment by shane-tomlinson** [comment]
From IRC:

```
15:10 <stomlinson> thanks pb, what are your thoughts on https://github.com/mozilla/fxa/issues/78?
15:10 <stomlinson> pb: My thoughts haven't changed. I think if an invalid device `id` is presented, the endpoints should 400.
15:10 <pb> stomlinson: my open db pr will resolve it one way or the other. if it is accepted, as i hope it to be, then the condition described will be an error
15:11 <stomlinson> pb: perfect, thanks
```

Kicking back to @philbooth to update the docs. The endpoints will return a 400 error.
