### ISSUE TITLE
install_all.sh causes package-lock.json to be created for 123done, fxa-geodb

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#780]
Neither 123done nor fxa-geodb have a package-lock.json or npm-shrinkwrap.json file, running install_all.sh causes these to be written to disk. Once they are written to disk, working with git becomes more tedious.

We should probably create these files and check them in.

cc @farhan787

**Comment by farhan787** [comment]
@shane-tomlinson should I add those files then ?

**Comment by shane-tomlinson** [comment]
Looks like I took care of 123done last week, and @vladikoff did fxa-geodb a few days ago. Closing. Thanks for volunteering @farhan787!

**Comment by farhan787** [comment]
Your most welcome @shane-tomlinson :-)
