### ISSUE TITLE
Universal Practicality of 2FA Options

### ISSUE THREAD

**Issue by erosman** [mozilla/fxa#7803]
Current possibilities are not suited to all users.

### Desktop Application Options
Access is not available to all users

![Screenshot_2021-03-12 Access denied authy com used Cloudflare to restrict access2](https://user-images.githubusercontent.com/6458876/110898682-ee910c80-8314-11eb-85a1-243c851cfa0a.png)

### Mobile Application Options
Considerable risk or unavailability when mobile is lost, stolen, broken, or unavailable

**Google Authenticator**
![Screenshot_2021-03-12 Google Authenticator - Apps on Google Play](https://user-images.githubusercontent.com/6458876/110898789-226c3200-8315-11eb-9793-8582f4a04474.png)

**Duo Mobile**
![Screenshot_2021-03-12 Duo Mobile - Apps on Google Play](https://user-images.githubusercontent.com/6458876/110899248-fef5b700-8315-11eb-82c7-2b65b4cca41c.png)

**FreeOTP Authenticator**
![Screenshot_2021-03-12 FreeOTP Authenticator - Apps on Google Play](https://user-images.githubusercontent.com/6458876/110906569-5a797200-8321-11eb-9e0e-61baa4344a85.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3174)
┆Issue Number: FXA-3174

**Comment by clouserw** [comment]
Thanks for filling this issue.  We're having trouble understanding what this bug is about.  Can you add some clarification as to your request?  Thanks

**Comment by erosman** [comment]
> Can you add some clarification as to your request?

### ref [Secure your Firefox Account with two-step authentication](https://support.mozilla.org/en-US/kb/secure-firefox-account-two-step-authentication?utm_source=transactional&utm_medium=email&utm_campaign=2021-2fa-enforcement)

- **Authy 2-Factor Authentication** is not available to all users since `authy.com` blocks access from some countries
- **Mobile Options** is not available to users since some do not have mobiles and as reviews show users can run into problems if mobile is lost, stolen or broken

Therefore, options are not universally available to all users.

_PS. I managed to use **KeepassXC **._

**Comment by clouserw** [comment]
Thanks for the feedback.  We continue to support and expand our options as we can.  I'm glad you found a solution that worked for you.  :+1:
