### ISSUE TITLE
[subplat] Payment Error Message Text Color is Too Light

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7810]
It's very difficult to read.  Also according to [https://www.figma.com/file/ejDMYaKpm5bsYL5YvhItur/Payment-Integration?node-id=523%3A4575](https://www.figma.com/file/ejDMYaKpm5bsYL5YvhItur/Payment-Integration?node-id=523%3A4575) it should match the color of the plan details.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3179)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15560/screenshot-1.png">screenshot-1.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15561/screenshot-2.png">screenshot-2.png</a>
┆Issue Number: FXA-3179

**Comment by Yogita98** [comment]
The figma design link is not accessible. Can you look into it?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

It's not just the error message.  The spinner screen and some of the text on the subscription success page have the issue.  See attached img.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Latest screenshot is to show the inconsistency in font colors.
