### ISSUE TITLE
[fxa-email-service] Bring back api::send::test::unicode_email_field

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#782]
See discussion starting at https://github.com/mozilla/fxa/pull/776#issuecomment-481292496.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-801)
┆Issue Number: FXA-801

**Comment by philbooth** [comment]
In https://github.com/mozilla/fxa/pull/776#discussion_r273648324, @dannycoates pointed out we should upload the db logs as a build artifact. Tremendous suggestion, which reveals this error [from the logs](https://3221-36831081-gh.circle-artifacts.com/0/db-logs):

```
{"Timestamp":1554893831502000000,"Logger":"fxa-auth-db-server","Type":"bin.server.MySql.read","Severity":2,"Pid":6630,"EnvVersion":"2.0","Fields":{"sql":"CALL fetchEmailBounces_1(?)","id":"[\"시험@example.com\"]","err":"Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\\xEC\\x8B\\x9C\\xED\\x97\\x98...' for column 'inEmail' at row 1"}}
```

At the start of the run, you can see the character set info logged:

```
{"Timestamp":1554893807589000000,"Logger":"fxa-auth-db-server","Type":"bin.server.variables.SLAVE","Severity":6,"Pid":6630,"EnvVersion":"2.0","Fields":{"character_set_client":"utf8mb4","character_set_connection":"utf8mb4","character_set_database":"utf8mb4","character_set_filesystem":"binary","character_set_results":"utf8mb4","character_set_server":"latin1","character_set_system":"utf8","collation_connection":"utf8mb4_bin","collation_database":"utf8mb4_bin","collation_server":"latin1_swedish_ci","max_connections":"151","sql_mode":"IGNORE_SPACE,STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION","version":"5.6.43","wait_timeout":"28800"}}
{"Timestamp":1554893807592000000,"Logger":"fxa-auth-db-server","Type":"bin.server.variables.MASTER","Severity":6,"Pid":6630,"EnvVersion":"2.0","Fields":{"character_set_client":"utf8mb4","character_set_connection":"utf8mb4","character_set_database":"utf8mb4","character_set_filesystem":"binary","character_set_results":"utf8mb4","character_set_server":"latin1","character_set_system":"utf8","collation_connection":"utf8mb4_bin","collation_database":"utf8mb4_bin","collation_server":"latin1_swedish_ci","max_connections":"151","sql_mode":"IGNORE_SPACE,STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION","version":"5.6.43","wait_timeout":"28800"}}
```

This one in particular looked a bit surprising:

```
"collation_server":"latin1_swedish_ci"
```

**Comment by philbooth** [comment]
Although the docs say:

> The server character set and collation are used as default values if the database character set and collation are not specified in `CREATE DATABASE` statements. They have no other purpose.

So maybe those settings above are fine.

**Comment by philbooth** [comment]
Note that in #796 we spotted the same issue with auth server tests running in a Circle-provided Docker image, fixed by reverting to the image that we build with the in-tree `Dockerfile-test`. Might be easiest if we do the same thing here (although that may also increase the build time for this step even more).

**Comment by philbooth** [comment]
Just want to note that I spent a bit of time on this again today, in my effort to tie up loose ends before I leave. Wasn't successful, I thought that maybe there was some problem with the charset used in the cloned authdb repo based on the error details above. But that code seems pretty solid, and explicitly forcing the encoding didn't have any effect either.

It clearly is some kind of problem with the charset, and we should fix it so that we have test coverage again, but I don't know what the answer is.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
