### ISSUE TITLE
/.well-known/change-password 404s on CI

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#7834]
This redirects correctly for me locally, but on CI seems to 404: https://app.circleci.com/pipelines/github/mozilla/fxa/17302/workflows/9fe7b0d0-68bd-4403-b9b1-206aa1203d2c/jobs/224495

Let's get it working

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3190)
┆Issue Number: FXA-3190

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Vijay fixed this in #7849.
