### ISSUE TITLE
settings_change_email test failures

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#7836]
I had disabled settings_change_email functional test because we have a similar test file in settings_v2, but brought it back because it was in the list of functional smoke tests, and we're aiming for smoke test parity before landing new-settings by default.

I haven't looked closely at the errors, but so far it's mostly been:
* updating selectors in lib/selectors to use v2 selectors in place of old-settings selectors, doing this in lib/selectors rather than by changing the selectors in the tests themselves (with occasional exceptions where I just got frustrated)
* dealing with unclickable form elements because of an overlaid SVG (checkboxes) or overlaid label (password field), my solution in both cases has been to click the label, which uncovers the input, then click / type in the input
* updating stale sequences for logging out, which now require hitting the avatar menu rather than clicking a link

We could just delete tests in settings_change_email that duplicate existing v2 tests, then move the v2 tests into the functional_smoke file. That said, the goal here is to retain working smoke tests for the existing edge cases, so we may wind up hacking the old file to a passing state quickly, then doing some refactoring later to clean everything up.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3191)
┆Issue Number: FXA-3191

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

This is actually done.
