### ISSUE TITLE
Refactor CircleCI builds to save resources

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#785]
What if we only had one docker image and just ran each service as a different command/config at runtime?

inspired by #778

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-802)
┆Issue Number: FXA-802

**Comment by vladikoff** [comment]
hm, it might be huge, would this slow down the dev workflow when pushing to `feature` branches?

**Comment by dannycoates** [comment]
As is, yeah it'd be big. We should get the dependencies more aligned too.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~dcoates@mozilla.com] will break this up into smaller tasks
