### ISSUE TITLE
`npm run test-server` fails locally on the content server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#787]
STR

1. Run `npm run test-server` from the fxa-content-server directory

```
× node - ver.json - #get /__version__
AssertionError: The git hash actually looks like one: expected null to be truthy
  at <tests/server/ver.json.js:32:16>
× node - ver.json - #get /ver.json
AssertionError: The git hash actually looks like one: expected null to be truthy
  at <tests/server/ver.json.js:32:16>
```

Is this due to the monorepo and not being able to find the git hash?

cc @dannycoates and @philbooth

**Comment by shane-tomlinson** [comment]
Likely a dup of #783, just in a different environment.

**Comment by philbooth** [comment]
Debugging it for you now, but I'll just note that this is another case where using the appropriate assertion would have produced a more helpful error message than `expected null to be truthy`.

**Comment by philbooth** [comment]
This one is just because `version.js` needs a couple more `..` to get up to the `.git` directory now. Fix incoming.
