### ISSUE TITLE
Functional tests - investigate re-enabling tests other than smoke tests

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#7879]
Removing the old-settings code broke the old functional tests. To keep things moving, #7776 disabled all but the smoke tests and got those passing.

This bug's a placeholder to figure out how to slice up the remaining work to get the other tests running.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3209)
┆Issue Number: FXA-3209

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Since this bug was filed, I kicked off a test run of all tests (not quitting at the first failure), and [~ashrivastava@mozilla.com] went through test failures and filed lots of bugs for individual broken test files. Calling this one fixed by her. Closing.
