### ISSUE TITLE
Functional tests - abstract out label click trick

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#7885]
A lot of the new-settings form controls can't be clicked directly, because intern.js complains that the element isn't clickable because something else is on top of it (whether an SVG or a label that animates away on click/focus). I found a couple different workarounds in #7776:

* for text inputs / password inputs, click the label, then click the input, then type into the input
* for delete account checkboxes, this trick doesn't work, but it does work to just have the tests click the label shown next to each checkbox

It would be nice to extract these tricks into helper functions in fxa-content-server/tests/functional/lib/helpers.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3214)
┆Issue Number: FXA-3214

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

I tried doing this, but it wasn't a lot more expressive than just having the label click in there. Closing.
