### ISSUE TITLE
The loading spinner inside the “Cancel” button from the FxA Subscriptions page is poorly visible since its color is similar to the color of the button’s background

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7898]
**Build:**

* Stage [Train 1.202.3]

**Affected platforms:**

* Windows 10 x64

**Prerequisites:**

* You have at least 1 active subscription on the FxA Subscriptions page.

**Steps to reproduce:**
1. Navigate to your FxA Subscriptions page.
2. Select one active subscription.
3. Check the “Cancel my access..” tickbox and click the “Cancel” button.
4. Observe what happens next with the button.

**Expected results:**

* The button displays a visible loading spinner while the process of canceling is in progress.

**Actual Results:**

* The loading spinner is poorly visible since it has a color similar to the color of the button’s background.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3221)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15573/spinner+color.jpg">spinner color.jpg</a>
┆Issue Number: FXA-3221

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~jecook@mozilla.com] We have a couple other spinner images (https://github.com/mozilla/fxa/tree/main/packages/fxa-payments-server/src/components/AppLayout/images). ( https://github.com/mozilla/fxa/tree/main/packages/fxa-payments-server/src/components/AppLayout/images). )  One is blue and the other is grey (but png instead of svg for some reason).  Would either of those work?  Is there another spinner image we should use here?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

(setting this back to To Do until we have some ux input)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

The old Zeplin mocks I was able to find did not have any specs on spinners.

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

[~bchen@mozilla.com] lets use the blue spinner! That will have the most contrast.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Verified this on FxA Stage - Train 1.205.0 - and the "Cancel" spinner is still very white.
See screenshot below.
 !Screenshot 2021-05-06 12.12.14.png|thumbnail!

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

This was just merged yesterday and won't be on stage until train 206 is tagged.  Thanks for the quick response though!

**Comment by ValentinaPC** [comment]
@chenba Can we leave the issue open until it can be tastable? or have a label/comment with this? Thanks in advance!

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I'll add a label.   👍
