### ISSUE TITLE
Deploy docs from tags as well as master

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#790]
In #784, documentation builds were added, keyed from pushes to `master`.

As per the discussion in https://github.com/mozilla/fxa/pull/784#discussion_r273711825, it would really be nice if we also built documentation for tags and made them available under a version number "namespace" in the path. Then all our historical docs would still be available for anyone that wanted to refer to them.

**Comment by clouserw** [comment]
wontfix
