### ISSUE TITLE
[Feature Request] internal communication between fxa-graphql-api and fxa-auth-server

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#7915]
As a self hosting fxa user , I want `fxa-graphql-api` to use internal `AUTH_SERVER_URL` URL to communicate with `fxa-auth-server`. 

However `fxa-auth-client` used by `fxa-graphql-api` calculates hawk mac using host of internal URL which will fail to be verified in `fxa-auth-server` since `fxa-auth-server` use `PUBLIC_URL` as it's host.

So is it possible to 
1.  make `fxa-auth-client` **optionally**  (mostly used between two server side endpoints)  communicates with internal URL and calculates MAC with host of public URL .
2.  let `fxa-grahql-api` set two envs for auth server URL : one for communicating and another for calculating MAC . 

I found that `requests-hawk` which used in `PyFxA` can set a `server_url` (https://github.com/mozilla-services/requests-hawk/blob/717487c5b66ae5ea308598e7f4f86a9903f69623/requests_hawk/__init__.py#L33) which is really really useful for hawk when signing the requests under this situation.

Thanks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3230)
┆Issue Number: FXA-3230

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~dcoates@mozilla.com]

**Comment by dannycoates** [comment]
> As a self hosting fxa user , I want `fxa-graphql-api` to use internal `AUTH_SERVER_URL` URL to communicate with `fxa-auth-server`.

May I ask why? Both servers need to be publicly accessible for the fxa settings page to work so I don't understand why this would be useful.

**Comment by jackyzy823** [comment]
It will be useful if you host `fxa` with self signed certs in local lan network.

**Comment by dannycoates** [comment]
This isn't something we're interested in supporting. In the future fxa-graphql-api will not need to communicate with fxa-auth-server at all.
