### ISSUE TITLE
Storybook has couple broken tests

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#7922]
Noticed this locally on main too, there are a couple failing tests in storybook.

Ref: https://app.circleci.com/pipelines/github/mozilla/fxa/17485/workflows/0dc936ca-26ad-4541-91a4-12b0ccb02c43/jobs/225974

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3232)
┆Issue Number: FXA-3232

**Comment by lmorchard** [comment]
Hmm, one possibly relevant bit of context: After reviewing some permissions for the Storybook publisher users on Friday, we noticed that the user on FxA was a contributor with read/write access to the repo. Switched that to just "Read", assuming that the commit status API didn't require Write access to repo commits.

**Comment by lmorchard** [comment]
I just now switched that contributor role for FxaStorybooks back to Write. Maybe that'll fix it and we need to leave it with Write access?

**Comment by vbudhram** [comment]
Thanks @lmorchard, let me restart the tests and see if that fixes it 🤞🏽.

**Comment by vbudhram** [comment]
Yup looks like that was the fix! https://app.circleci.com/pipelines/github/mozilla/fxa/17485/workflows/263b9c81-f8c5-4de0-9d3e-f788370ebb09/jobs/226017
