### ISSUE TITLE
Auth server package.json still depends on github.com/mozilla/fxa-auth-db-mysql

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#793]
As per https://github.com/mozilla/fxa/pull/791#issuecomment-481640616, the auth server still points at the old db repo for running the tests against, so it's not going to pick up any new changes. We should fix that.

**Comment by vbudhram** [comment]
FWIW, here is my failed attempt at this and some of the issues we will run into

https://github.com/mozilla/fxa/pull/778

**Comment by philbooth** [comment]
If the current build succeeds for #776, we should be able to use the same approach I'm taking there:

```sh
DB_REPO=fxa-auth-db-mysql
if [ ! -e "$DB_REPO" ]; then
  git init "$DB_REPO"
  cd "$DB_REPO"
  git remote add origin https://github.com/mozilla/fxa.git
  git config core.sparseCheckout true
  echo "packages/$DB_REPO/*" > .git/info/sparse-checkout
  git pull --depth=1 origin master
  cd ..
fi

RUNNING_DB_SERVERS=`ps -ef | grep "[n]ode bin/server" | wc -l`
if [ "$RUNNING_DB_SERVERS" -eq "0" ]; then
  cd "$DB_REPO"
  npm ci
  node bin/db_patcher
  node bin/server 2>&1 > "../$DB_REPO.log" &
  cd ..
fi
```

...in combination with some extra jiggery-pokery in `.circleci/config.yml`.

**Comment by philbooth** [comment]
@mozilla/fxa-devs, question: should this issue be a blocker on landing db changes, e.g. @lmorchard's PR #775?

(not meaning to pick on you specifically there @lmorchard, but it just occurs to me we should probably make sure the auth tests are using the latest changes before we try to land stuff, even if the changes are mostly additive and seem innoccuous)

I'm fine if we don't think it should be a blocker btw, just wanted to ask the question.

**Comment by philbooth** [comment]
> should this issue be a blocker on landing db changes

Although actually, even with #796 in place it wouldn't test against the current changes, it would only test against `master`. So maybe ignore the question (and discuss the other thing in #796).

**Comment by philbooth** [comment]
> Although actually, even with #796 in place it wouldn't test against the current changes, it would only test against `master`.

This is not true any more, #796 uses `HEAD` now.
