### ISSUE TITLE
Functional tests: add page slug to top-level testid in new-settings

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#7966]
Each page in new-settings has a `data-testid=flow-container` inside a `div#root`. If we included the name of the page as a testid in either of these top-level container elements, it would be easier to work around missing testids lower in the page.

Maybe we could append the page slug to the flow-container testid, like we do for testids in the UnitRow component.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3249)
┆Issue Number: FXA-3249

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

I think we can just aim to add testids to lower components as needed instead (this has worked out well so far).
