### ISSUE TITLE
Red buttons lose their border on focus

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7970]
Refer to attached video. When you click or tab into a red button it loses its border causing the content to shift. It should either keep it's border or even just make the border transparent instead of removing it.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3252)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15597/Screen+Recording+2021-03-25+at+2.01.54+PM.mov">Screen Recording 2021-03-25 at 2.01.54 PM.mov</a>
┆Issue Number: FXA-3252

**Comment by Jane-Kotovich** [comment]
Hey! I'm Outreachy applicant, could I please work on this issue! Thanks!

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.3] under Windows 10 64-bit and Android 9. There are no UI issues when clicking/taping on the red buttons.
