### ISSUE TITLE
Logo in emails can take like 20 seconds to load

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7971]
I've been looking over our emails today and I noticed that our brand logo can take a really long time to load. TBH, I didn't think it was going to load at all it took so long.

Once it pulled it down though, it seems to be cached and showing up instantly everywhere so it's hard to replicate a second time.

!image-2021-03-25-11-09-21-701.png!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3253)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15599/image-2021-03-25-11-09-21-701.png">image-2021-03-25-11-09-21-701.png</a>
┆Issue Number: FXA-3253

**Comment by LZoog** [comment]
Here's the attached image:

![image](https://user-images.githubusercontent.com/13018240/112681083-3303c880-8e3c-11eb-8a35-0eb946375e32.png)

A tip on getting started for a contributor - let's check that the image is loaded similarly and from the same place as our other email images. Let's also check that the image isn't unusually large, maybe it just needs to be minified?

**Comment by Yogita98** [comment]
Hey @LZoog I'd like to pick up this issue. But before that, can you please tell me what exactly do you mean by the image isn't unusually large? Is it something to do with the height/width of the image?

**Comment by LZoog** [comment]
@Yogita98 Not necessarily the width/height of the image, but the image size. Images can be compressed with freeware like TinyPNG, and large SVGs with SVGO. I'm not sure if the image is unusually large or not or if that's what's happening, but could be worth checking. I can assign you if you'd like to look into it!

**Comment by Yogita98** [comment]
Okay, got it! Thanks

**Comment by Yogita98** [comment]
> Here's the attached image:
> 
> ![image](https://user-images.githubusercontent.com/13018240/112681083-3303c880-8e3c-11eb-8a35-0eb946375e32.png)
> 
> A tip on getting started for a contributor - let's check that the image is loaded similarly and from the same place as our other email images. Let's also check that the image isn't unusually large, maybe it just needs to be minified?

The image that you have attached above is from this URL 👉 http://localhost:3030/signin right?

**Comment by LZoog** [comment]
@Yogita98 this is actually coming from an email template. If you search "New sign-in to", you can see it in a `verifyLogin` file.

According to the issue description, this logo loading problem may be happening across all of our emails. See if you can reproduce it first, probably by running the mail-dev client (details on the home README), or maybe it's reproducible by running `yarn write-emails` and pulling up the `verifyLogin` generated HTML file. Sounds like you may need to clear your cache to keep reproducing.

**Comment by Yogita98** [comment]
Well I could reproduce the issue by pulling up the `verifyLogin.html` file and the logo did take a few seconds to load and upon further inspection, I saw that the logo is coming from Mozilla's hosted lib. However, I couldn't really gather any more info about it.
I was also trying to run `maildev` client but I observed that we need AWS SES access key and secret for sending mails. Am I in the right direction though? If yes, is the email client hosted in Amazon EC2? I'm guessing that the email service is probably running locally but just want to confirm in case I'm supposed to get a SES subscription.

**Comment by LZoog** [comment]
@Yogita98 So sorry for the late response here.

@vbudhram I'm curious if you have any input here. The filesize of the logo appears fine (16 KB) and it's hosted at `https://image.e.mozilla.org/lib/fe9915707361037e75/m/4/11c1e411-7dfe-4e04-914c-0f098edac96c.png`. Other image files are hosted here while others are at something like `https://accounts-static.cdn.mozilla.net/product-icons/firefox-logo-email.png`... when should we use one or the other? Also Vijay can you repro this? I see that it takes like 1/2 a second to load but it's an image so that seems acceptable, though Alex is reporting 20 seconds.

**Comment by vbudhram** [comment]
> I was also trying to run maildev client but I observed that we need AWS SES access key and secret for sending mails

Hey @Yogita98 are you following the instructions at https://github.com/mozilla/fxa#running-with-maildev? You don't need any AWS SES keys set because the email wont be using SES locally. We have a local service that sends the email.

**Comment by vbudhram** [comment]
> I'm curious if you have any input here. The filesize of the logo appears fine (16 KB) and it's hosted at https://image.e.mozilla.org/lib/fe9915707361037e75/m/4/11c1e411-7dfe-4e04-914c-0f098edac96c.png. Other image files are hosted here while others are at something like https://accounts-static.cdn.mozilla.net/product-icons/firefox-logo-email.png... when should we use one or the other?

Looked into this a little. I believe `image.e.mozilla` image is hosted by marketing team. Which was done to reduce our spam rating with email services. I'm not sure if we still need this and could use the `accounts-static-cdn` version.

Also, FWIW I didn't see a 20 second delay loading log.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It's worth putting everything on the same domain to reduce our spam scores.  We should file a task for that and if that's something you want to work on, Yogita, that would be great.

However, this specific issue we can't reproduce so I'm going to close it.  Thanks

**Comment by Yogita98** [comment]
@clouserw Thanks, I'd love to work on it as and when the issue gets filed.

**Comment by clouserw** [comment]
Filed at https://github.com/mozilla/fxa/issues/8574 .  Thanks!
