### ISSUE TITLE
Registration email Pre-header is Useless

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7973]
A pre-header in an email is a great way to provide additional context. We don't seem to be doing that with our Registration emails where we just see the end of a URL:

!image-2021-03-25-11-13-49-170.png!

I'd like us to display something in the pre-header like "Copy/paste this code into your registration form"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3254)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15600/image-2021-03-25-11-13-49-170.png">image-2021-03-25-11-13-49-170.png</a>
┆Issue Number: FXA-3254

**Comment by LZoog** [comment]
Here is the attached image:
![image](https://user-images.githubusercontent.com/13018240/112680610-96412b00-8e3b-11eb-998d-5373a66e7106.png)

The link in the pre-header is probably coming from the Firefox logo. We likely want to include the suggested text as the first paragraph of the email and hide it with CSS, but there may be some caveats around that. It's probably worth searching around for the best approach here if a contributor would like to pick this one up.

**Comment by claubatista** [comment]
hi, I'm outreach applicant, I would like to work on this. :)

**Comment by jodyheavener** [comment]
Hey @claubatista sounds good!

**Comment by claubatista** [comment]
Hey @jodyheavener, @LZoog, this is ready for review. :D

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this fix on Stage [Train 1.204.3] under Windows 10 64-bit and noticed that the expected pre-header "Copy/paste this code into your registration form" is displayed only for the "Read" state. For the "Unread" state appears the same pre-header as for the Sign in code email "Is this you signing in?
Firefox on Windows 10 Baia Mare, MM, Romania (estimated) IP address:....." 

[~adavis@mozilla.com] Any thoughts about this?
