### ISSUE TITLE
Update string in Registration email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7974]
In our login email, we tell users:

"Is this you signing up? 
If yes, use this verification code:"

It lacks a bit of context. Perhaps we move forward with something like:

"If yes, use this verification code in your registration form"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3255)
┆Issue Number: FXA-3255

**Comment by rukshan99** [comment]
Can I work on this?

**Comment by LZoog** [comment]
@rukshan99 I was about to say yes, but I see you have a PR up for this! Thank you.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.3] under Windows 10 64-bit. "If yes, use this verification code in your registration form" line is successfully displayed in the Registration email.
