### ISSUE TITLE
[Support] Create support form backend

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#798]
#797 describes the form, but the support form has to submit somewhere.

The backend will receive the form and submit it directly to ZenDesk

Question: where (in what server) should this backend be hosted? Note that this requires private configuration (API keys), but no state (the submission should happen immediately, and any errors reported back to the user so they can attempt to resubmit).

See also [technical description on ZenDesk API](https://docs.google.com/document/d/18EIf2tPT9FSN-4tnUg_qNcDXugYymhVox1956z7VfTQ/edit#heading=h.k91114u9ssqo) and [exact specifications of how the API call should happen](https://docs.google.com/document/d/19pw1rLH33tKWYtGmlGaNTbOwNKU1VZdXHA23YKExADc/edit#heading=h.5pvslv2bxwik).

**Comment by jackiemunroe** [comment]
To whomever ends up working on this ticket:
Please feel free to reach out to me to go over Zendesk ticket forms, so I can make sure that everything is defined and you have the field keys necessary to create the tickets via the API. :)
