### ISSUE TITLE
Functional test failures - oauth_permissions.js (3 tests failing)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7983]
┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3265)
┆Issue Number: FXA-3265

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

The failing test file is : oauth_permissions.js

and tests are:

  1. signin with new permission available b/c of new account information
  2. signin with additional requested permission - oauth permissions for untrusted reliers
  3. signin after deselecting a requested permission  oauth permissions for untrusted reliers

**Comment by jaredhirsch** [comment]
Fixed by https://github.com/mozilla/fxa/pull/8107, except for one followup issue #7983
