### ISSUE TITLE
Migrate to a single top-level .gitignore file

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#801]
Will `.gitignore` be easier to maintain if we just have one file at the top level?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-803)
┆Priority: Medium
┆Issue Number: FXA-803

**Comment by shane-tomlinson** [comment]
> Will .gitignore be easier to maintain if we just have one file at the top level?

I asked myself the same thing yesterday and the conclusion I came to w/o thinking about it too much is "yes." The point of the monorepo is to reduce housekeeping burdens like this.

**Comment by farhan787** [comment]
@shane-tomlinson and @philbooth what a coincidence, I also searched for the `.gitignore` file on the top level to add .DS_Store in it when we were having that problem.

**Comment by philbooth** [comment]
@farhan787, bit of a tangent but you probably want to add `.DS_Store` to your global `.gitignore` file, to prevent you from accidentally checking it in to other projects too (or having to add it individually to `.gitignore` in all your repos).

You can set one up like this:

```
git config --global core.excludesfile '~/.gitignore'
```

Then just add stuff to `~/.gitignore` like you would normally. This is also a good place to put anything else specific to your local set-up, like `.vscode` or whatever.

**Comment by farhan787** [comment]
@philbooth @shane-tomlinson has added it into the fxa-content-server package and I was thinking that it would be great if we had a .gitignore file in the root of this repo (fxa/)

**Comment by philbooth** [comment]
@farhan787, Shane added it to the root of this repo already.

My point still stands though fwiw: you'll save yourself time in the long run if you create a global `gitignore` and it will make it easier for you to work with other people's projects in the future too, if you're not accidentally committing things that you didn't intend to.

**Comment by farhan787** [comment]
@philbooth oh that way, yeah it's very helpful. Thanks for the suggestion, I'll add it there.
