### ISSUE TITLE
Settings - Two step auth new recovery codes styling issues

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#8010]
## Description

When I go to replace my recovery codes, there's a small green box before the codes are loaded and then the "Close" button sits behind the download/copy/print buttons.

### Steps to reproduce

Go to "Replace Recovery Codes".

![two-step-auth-codes](https://user-images.githubusercontent.com/13018240/112682766-93940500-8e3e-11eb-9f61-5cdeb9d924e9.gif)

### Expected result

The box should probably have its expected width/height (and perhaps we could use a loader?) and the "Close" button should sit lower than the download/copy/print buttons.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3277)
┆Issue Number: FXA-3277

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Prod [Train 1.204.4] under Windows 10 64-bit, Android 9 and iOS 14.4.  I confirm that the small green box was successfully replaced by the loader and the Download/Copy/Print buttons do not longer overlap the "Close" button.
