### ISSUE TITLE
Update copy in passwordChangeRequired email template

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#8011]
## Description

There are a couple areas we can improve the copy in [passwordChangeRequired](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/templates/passwordChangeRequired.html) email template.

1) Add a an header (h1, refer to other templates to see how it's done) titled "Password Change Required"
2) In the line that says, "Important: pick a different password", capitalize "Pick"
3) Change the line that says "The Firefox accounts team" to "the Firefox Accounts team"

Ensure these copy changes are reflected in the [text](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/templates/passwordChangeRequired.txt#L11:L11) version as well.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3278)
┆Issue Number: FXA-3278

**Comment by shivanisinghnitp** [comment]
May I take this issue?

**Comment by karinabk** [comment]
Hi Jody! I would like to take it too ;)

**Comment by jodyheavener** [comment]
Going to assign this one to @karinabk since @shivanisinghnitp you're assigned to #8012 🙂

**Comment by karinabk** [comment]
@jodyheavener Thank you for the feedback! Could you review it?
