### ISSUE TITLE
Change "Setup" to "Set up" in postVerify email template

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#8012]
## Description

The `postVerify` email template has a CTA with the [text](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/email.js#L1296:L1296) "Setup", change it to "Set up"

Ensure this change is reflected in the [text](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/senders/templates/postVerify.txt) version as well.

["Setup" is a noun, "set up" is a verb.](https://writingexplained.org/setup-vs-set-up-difference)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3279)
┆Issue Number: FXA-3279

**Comment by shivanisinghnitp** [comment]
Hello, I would love to  take this issue!

**Comment by jodyheavener** [comment]
Sure thing @shivanisinghnitp, all yours.

**Comment by shivanisinghnitp** [comment]
Kindly review the pull request! @jodyheavener  
Thanks!

**Comment by shivanisinghnitp** [comment]
@jodyheavener  I made all the required changes. The test cases were failing hence I had to make a new PR. 
Please review this! I have done both the tasks in one commit and also changed the review message!
Thank you!

**Comment by jodyheavener** [comment]
@shivanisinghnitp Sounds good, I will take a look. A see there are quite a few closed PRs with this issue, so just a tip: you can push new commits to the same branch and it will be reflected in the same Pull Request, and re-trigger CI, no need to close and open new Pull Requests. When you're feeling good about the changes you've made you can squash your commits into a single commit on that same branch.

**Comment by shivanisinghnitp** [comment]
@jodyheavener  Thank you so much! You have been quite helpful .Since I m new to open source contribution , I struggled a lot! This advice is gonna make my open source contribution journey relatively easier! :)
