### ISSUE TITLE
Login with another account on fxios

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#8014]
## Description

In the case where a device gets logged out remotely, you're seemingly unable to log back in with a different account.

https://user-images.githubusercontent.com/87619/112692074-93ded100-8e3b-11eb-82dc-d2756e71c4e2.mov

### Expected result

The 'Use a different account' link should be available

### Actual result

it isn't

### Environment

fxios settings menu

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3281)
┆Issue Number: FXA-3281

**Comment by clouserw** [comment]
testing. please ignore

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue was verified as fixed on Stage [1.206.0] under iOS 14.4. I can confirm that the 'Use a different account' link is available.
