### ISSUE TITLE
[FxA-Settings] Focus behavior for ‘Show/ Hide password’ eye is not consistent

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8025]
**Build:**
Stage (Train 1.203.2)

**Affected platforms:**
Windows 10

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and log in using an existing account.
1. Go to the ‘Password’ section and click the ‘Change’ button.
1. Type in a password in one of the fields.
1. Unfocus the password field and then click on the eye icon’s focus area.
1. Observe the eye icon’s focus behavior and compare it with the one from the ‘Sign in’ or  ‘Create a Firefox Account’ page.

**Actual result:**
The eye icon is colored in blue when it is focused. There is no consistency.

**Expected result:** 
The eye icon focus behavior is similar.

**Note:** Also the focus border is not fully visible.
The eye icon is also colored in blue in the 'The Recovery key' Step 1 of 2 page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3286)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15706/Eye+icon+focus+issue.PNG">Eye icon focus issue.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/15705/Eye+icon+focus+issue2.gif">Eye icon focus issue2.gif</a>
┆Issue Number: FXA-3286

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~dcoates@mozilla.com] I think you just patched this?

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

I haven't touched this

**Comment by karinabk** [comment]
@jodyheavener may Outreachy applicants take these issues? I would like to fix it

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

The issue was verified as Fixed on Stage [1.204.2] under Windows 10 64-bit. The focus border is not colored in blue anymore.
