### ISSUE TITLE
Subscription ”Thank your page” is loaded for an already subscribed VPN user

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8027]
**Affected versions:**

* All Firefox;

**Affected FxA versions:**

* 1.203.2;

**Affected Platforms:**

* Windows 10;

**Prerequisites:**

* Have an FxA account with subscription made for VPN;

**Steps to reproduce:**

1. Open VPN homepage https://www-dev.allizom.org/en-US/products/vpn/
1. Click on “Get Mozilla VPN” button;
1. Log in with an account that has a subscription for Mozilla VPN;

**Expected result:**

* User is redirected to the VPN download page;

**Actual result:**

* User is redirected to the subscription “Thank you” page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3288)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15945/thankyoupage.gif">thankyoupage.gif</a>
┆Issue Number: FXA-3288

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks for filing this; AFAIK this has been the default behavior for a long time. [~jecook@mozilla.com], [~byee@mozilla.com]: Do you think this is something that should change? If so, what is the expected behavior here?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Yes, this is the behavior for a while, but with the UI changes in the landing page (the "Already a subscriber?" string was added) would make more sense to redirect to /download page for those type of users (QA perspective).

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

[~bdanforth@mozilla.com] As the link form the STR1 is no longer in purpose, while loading the https://www-dev.allizom.org/en-US/products/vpn/ ( https://www-dev.allizom.org/en-US/products/vpn/ ) page and clicking the "Already a subscriber?" option, user gets redirected back to this page even if he logs in with and account with subscription.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

I've updated the STRs and added a video.

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

I agree with Valentina — the 'already subscriber' button/link should really solve this ... as in I imagine from a user perspective if I would click that instead of getting thrown into the 'Get VPN' flow... which either way even that does happen I feel like this thank you screen and that treatment is fine for that instance. 1 - because I dont believe this should happen as much anymore given the new link added and 2) its enough to show the user they have already purchases this and thats a good indicator for them to then go download if they havent already.

      * I do not see a need for creating a new screen or state that gets shown to users in this instance as it feels like an edge case.... perhaps if this issue arises again, or we hear negative feedback from users around this, or can get data that shows a good significant amount of users falling into this path – -then thats when we can take a second look at this. But for now this fine behavior IMO.

**Comment by biancadanforth** [comment]
Thanks Jess for weighing in. Closing for now, but we can always revisit.
