### ISSUE TITLE
Geolocation in emails is wrong when making changes on new settings page

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#8038]
See when I added a secondary email to my account

<img width="393" alt="Screen Shot 2021-03-29 at 9 20 00 PM" src="https://user-images.githubusercontent.com/578466/112919199-9e67c780-90d4-11eb-964f-9ab2b6d07087.png">

`34.222.241.233` is the IP address of the graphql server. Not sure how many other emails are affected by this bug

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3291)
┆Issue Number: FXA-3291

**Comment by jbuck** [comment]
Another user filed this issue and mentioned that it affected recovery key and password emails as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1700356

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Our plan is to add a header to the request from GQL > Auth server with the enduser IP

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue was verified as Fixed on Stage [Train 1.203.4] under Windows 10.
