### ISSUE TITLE
[FxA Settings] Sync options are not saved after returning to Create Account page from Terms of Service/ Privacy notice pages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8046]
**Build:**
Stage (Train 1.203.2)

**Affected platforms:**
Windows 10
Android 8
Android 11

**Steps to reproduce:**

1. Launch Firefox and click on the FxA toolbar menu button.
1. Click on ‘Sign in to Firefox (Turn on Sync)’ option.
1. Type a new email address which does not have associated a Firefox Account.
1. Un-select some of the sync options.
1. Click Terms of Service/ Privacy notice link.
1. Click Back button from the bottom of the page.
1. Observe the sync options.

**Actual result:** 
The changes made on sync options are not saved.

**Expected result:**
The changes made on sync options are saved.

**Note:** Same issue can be found for Newsletter options on the ‘Create a Firefox Account Continue to Account Settings’ page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3293)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15718/Sync+options+not+saved.gif">Sync options not saved.gif</a>
┆Issue Number: FXA-3293

**Comment by flozender** [comment]
@LZoog I'd like to try and fix this, may I?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing this but this would take some special case code to do and we'd need to maintain that forever and we don't think the trade off is worth it.
