### ISSUE TITLE
[FxA Settings] Blank Firefox Accounts page is displayed when user selects Manage devices option from Synced Tabs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8047]
**Build:**
Stage (Train 1.203.2)

**Affected platforms:**
Windows 10

**Preconditions:**
The user must be signed in to Firefox Sync with the same account on desktop and a mobile device which has a few open tabs.

**Steps to reproduce:**

1. On desktop click on the ‘Show sidebars’ button in the toolbar and select the ‘Synced Tabs’ option.
1. Right-click a synced device to trigger the context menu.
1. Select the ‘Manage devices’ option.

**Actual result:** 
Firefox Accounts page is displayed with no content.

**Expected result:** 
Firefox Accounts page is displayed with focus on Connected services.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3294)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15720/Manage+devices+-+Blank+settings+page+displayed.gif">Manage devices - Blank settings page displayed.gif</a>
┆Issue Number: FXA-3294

**Comment by flozender** [comment]
@LZoog is this a valid issue? Can I please pick this up?

**Comment by vbudhram** [comment]
Hey @flozender, I have an upcoming patch for this bug. You are welcome to work on another issue!

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

The issue was verified as Fixed on Stage [1.204.3] under Windows 10 64-bit. I confirm that Firefox Accounts page is displayed with focus on Connected services.
