### ISSUE TITLE
Wrong tooltip displayed for Eye icon when password is visible

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8068]
**Build:**
Stage (Train 1.203.2)

**Affected platforms:**
Windows 10

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/.
1. Type in a new email address which does not have associated a Firefox Account.
1. Click Continue.
1. Fill in the password field and then click on the Eye icon.
1. Hover over the Eye icon and observe the tooltip.

**Actual result:**
‘Show password’ tooltip is displayed.

**Expected result:**
‘Hide password’ tooltip is displayed.

**Note:** The same issue can be found on ‘Sign in’ page.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3298)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15810/Wrong+tooltip+for+eye+icon+state.PNG">Wrong tooltip for eye icon state.PNG</a>
┆Issue Number: FXA-3298

**Comment by CarolVilarino** [comment]
Hi! ✋  I'm an Outreachy applicant, this can be a good-first-issue to be assigned to me?

**Comment by LZoog** [comment]
Hi @CarolVilarino! Yes, I will assign you, thanks for finding this one.

Here's the screenshot for reference:
![image](https://user-images.githubusercontent.com/13018240/113320638-54e7ca00-92d8-11eb-9184-11a9f15df918.png)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue was verified as fixed on Stage [1.206.0] under Windows 10 64 bit and macOS 10.14.6. I confirm that the correct tooltip is displayed.
