### ISSUE TITLE
Replace tap with mocha in the customs server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#807]
The customs server uses the tap test runner whereas our other repos use mocha. We should standardize on mocha.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-804)
┆Issue Number: FXA-804

**Comment by vbudhram** [comment]
Another reason to do this 😬, https://github.com/mozilla/fxa/pull/2694

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
