### ISSUE TITLE
Standardize JS styles across packages

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#808]
This came up in today's retro. It's a bit of an annoyance to remember which style to use in which package. We should standardize our JS style across repos.

We could do it like so:

1. Pick a common set of ESLint rules, likely from [eslint-plugin-fxa's server set](https://github.com/mozilla/eslint-plugin-fxa/blob/master/lib/configs/server.js) for all server code (with the slight change that we'd use semi's everywhere) and [client](https://github.com/mozilla/eslint-plugin-fxa/blob/master/lib/configs/client.js) for all front-end code.
2. Use [eslint's --fix option](https://eslint.org/docs/user-guide/command-line-interface) to automatically update one repo at a time.
3. Have semi-common styles everywhere and win.

**Comment by lmorchard** [comment]
FWIW, there is also an [eslint-plugin-mozilla](https://www.npmjs.com/package/eslint-plugin-mozilla) that we were using on Test Pilot. Main good thing about that is trying to follow more org-wide conventions, but may or may not be what we want to do here

**Comment by lmorchard** [comment]
Noting that we should include fxa-payments-server here, rather than filing a separate issue.

**Comment by lmorchard** [comment]
Note from @ianb [on another PR](https://github.com/mozilla/fxa/pull/1357/files#r290053487):

> Oh... this is an eslint rule against unused variables? I don't like that rule, signatures aren't variable declarations, and giving the right signature (including variables you don't end up caring about) feels more proper to my languages-with-strict-arity-checking (everything but JS and shell?) background.

> Can we get rid of that rule?

**Comment by bbangert** [comment]
There's a tslint as well, which I used in fxa-event-broker as it seemed more focused on various typescript things. Does one use both or one at a time? I'd assume a package being migrated would need them both.

There's also the general coding style conventions, which I didn't see us defining anywhere, but generally we seem to follow fairly closely to:
https://basarat.gitbooks.io/typescript/docs/styleguide/styleguide.html

**Comment by lmorchard** [comment]
Commented in #1540 about the eslint config on fxa-payments-server for TypeScript. One thing I'd read is that eslint seems to be better than tslint in projects that mix JS & TS

**Comment by LZoog** [comment]
On the payments server, we have this rule: `Unary operator '!' must be followed by whitespace.`

@chenba and I would vote to have this removed.

**Comment by dannycoates** [comment]
done
