### ISSUE TITLE
[FxA-Settings] ‘Create new recovery key’ button from email opens a blank Settings page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8091]
**Build:**
Stage (Train 1.203.4)

**Affected platforms:**
Windows 10

**Preconditions:**
The user has the Recovery key enabled and the key is saved.

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and login using an existing account.
1. Go to ‘Password’ section and click on the ‘Change’ button.
1. Click on ‘Forgot password’ link and enter your email address.
1. Click the ‘Begin reset’ button.
1. Check the email inbox and click the ‘Create new password’ button from ‘Reset your password’ email.
1. Enter the saved recovery key and click the ‘Confirm recovery key’ button.
1. Create a new password.
1. Check the email inbox and click the ‘Create new recovery key’ button from ‘Password updated using recovery key’ email.

**Actual result:** 
A blank Settings page is displayed.

**Expected result:** 
The user is redirected to create a new Recovery key.

**Note:** The same issue can be found if you click the 'click here' link from 'Account recovery key generated' email.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3300)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15905/Generate+new+recovery+key+-+blank+settings+page.PNG">Generate new recovery key - blank settings page.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/15911/Recovery+key+email+-+blank+settings+page.PNG">Recovery key email - blank settings page.PNG</a>
┆Issue Number: FXA-3300

**Comment by Yogita98** [comment]
@LZoog @jodyheavener If I get the redirection link, then probably I can fix this? What are your thoughts?

**Comment by LZoog** [comment]
@Yogita98 I think it might be a little more complex, but I'm not sure. Since this issue is only 5 days old and the severity is set to "normal," I'd say we should leave this one in case the FxA team ends up assigning it and working on it in their next sprint planning session. 🙂

**Comment by Yogita98** [comment]
Yeah, that makes sense! Cool then I'll look for another issue to work on :)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jhirsch@mozilla.com] I think I might have filed a duplicate of the "Note..." at the bottom of this one.  If it's all fixed in one go, FXA-3330 should be marked as a dupe

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue was verified as fixed on Stage [1.205.0] under Windows 10 64-bit, Android 11 and iOS 14.4. I confirm that the user is redirected to create a new Recovery key when he clicks the ‘Create new recovery key’ button and also the "click here" link.
