### ISSUE TITLE
[FxA-Settings] "Replacing your recovery codes" 2FA link opens an incorrect page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8092]
**Build:**
Stage [Train 1.203.4]

**Affected platforms:**
Windows 10 64-bit
Android 9

**Prerequisites:**
The user has the 2FA enabled

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/settings/ and login using an existing account.
1. Click on the "Disable" button from the "Two-step authentication" section.
1. Click on the "replacing your recovery codes".

**Expected results:**
The user is redirected to a page where are described steps to change the recovery codes.

**Actual Results:**
The user is redirected to "Reset your Firefox Account password with Recovery Keys" [page](https://support.mozilla.org/en-US/kb/reset-your-firefox-account-password-recovery-keys), which is specific to Recovery key not 2FA codes.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3301)
┆Issue Number: FXA-3301

**Comment by Yogita98** [comment]
I'm an Outreachy applicant and I'd like to fix this issue if that's okay @LZoog @jodyheavener 
Well, I have done a bit of homework before giving this a shot :p
I tried to reproduce the issue locally and I can see that the href link for "replacing your recovery codes" has explicitly been set as [this](https://support.mozilla.org/en-US/kb/reset-your-firefox-account-password-recovery-keys). So does this issue only requires the link to be changed? If yes, can I also know where are we supposed to redirect the user?

**Comment by LZoog** [comment]
Hey @Yogita98, yes that is correct! Thanks for looking into this.

The link _should_ be: https://support.mozilla.org/en-US/kb/changing-your-two-step-authentication-device-firefox-account

I'm running this by someone to double check before you get started and will comment back here with confirmation, but I'll go ahead and assign you, thanks for finding this one!

**Comment by Yogita98** [comment]
Sure, no problem @LZoog

**Comment by LZoog** [comment]
@Yogita98 got confirmation that the link provided above is correct, thanks!

**Comment by Yogita98** [comment]
Alright, I will get started with this!

**Comment by Yogita98** [comment]
@LZoog I'm so sorry for the inconvenience. I accidentally closed the previous PR so I'm linking another PR with required changes. 
About the previous PR, I had to hard reset my last commit maybe which is why both the commits got included in this branch but now everything seems fine except for a little mess that I caused by making two PRs

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.3] under Windows 10 64-bit, Android 9 and iOS 14.4. I confirm that Changing your two-step authentication device for your Firefox Account ( https://support.mozilla.org/en-US/kb/changing-your-two-step-authentication-device-firefox-account ) page is successfully opened when clicking on "replacing your recovery codes" link.
