### ISSUE TITLE
%(productname)s showing up in credit card expiration emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8096]
I got an email from staging that my credit card was expiring.  I noticed it had a %(productname)s in it, but only in the text version.  The HTML version looked fine.  I'll add some screenshots

!image-2021-04-01-09-15-27-160.png|thumbnail! 

!image-2021-04-01-09-16-06-821.png|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3304)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16001/image-2021-04-01-09-15-27-160.png">image-2021-04-01-09-15-27-160.png</a> | <a href="https://jira.mozilla.com/secure/attachment/16000/image-2021-04-01-09-16-06-821.png">image-2021-04-01-09-16-06-821.png</a>
┆Issue Number: FXA-3304

**Comment by Yogita98** [comment]
@LZoog can I give this one a shot?
If yes, can I also get the screenshots since the links are not accessible to me?

**Comment by LZoog** [comment]
Hey @Yogita98, I actually don't think this one is a good one to work on for this week. While this is emails-related, working with the `productName` might be a little hairy without some context in the `fxa-payments-server` and digging around/testing. The Subscription Platform team, who would likely may want to prioritize and work on this issue too in their upcoming sprint.

**Comment by Yogita98** [comment]
Yeah, I completely understand. Thank you!
