### ISSUE TITLE
Update root README with minor changes

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#8097]
## Description

The front-page FxA README could use a few updates.

1) Update `./pm2` references to use `yarn pm2`, as the executable was removed when we switched to Yarn
2) Update `npm start` and `npm stop` references to `yarn start` and `yarn stop`
3) Update the FxA services image shown under [Workflow](https://github.com/mozilla/fxa#workflow); it's currently 6 years old and has changed significantly since then. Please make sure this image shows all services - at the time of writing, 3 of them should show as `stopped` and others should be `online`, and also (if you have transparency set on your terminal) make sure there's nothing distracting in the background. It might be a while before we update this image again. 😉

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3305)
┆Issue Number: FXA-3305

**Comment by dhruva248** [comment]
Hey I would like to work on this issue!

**Comment by jodyheavener** [comment]
Sure thing @dhruva248, I've assigned it to you

**Comment by Yogita98** [comment]
@LZoog Should we also mention using `node v14.15.1` specifically since currently it's stated as `node 14+`? What are your thoughts?

**Comment by LZoog** [comment]
@Yogita98 good question! We could potentially make a minor upgrade before we upgrade to `v15`, meaning our docs would go out of date pretty quickly. To my knowledge, FxA should still run on lower versions of node than `v14.15.1`, I've just been recommending contributors make sure they're running that specific version of Node since that's the one specified in the root `package.json`. 🙂

**Comment by Yogita98** [comment]
Ohhh okay! I wasn't aware of the reason why we're making use of that specific version. Thanks alot for letting me know :)

**Comment by Cronus1007** [comment]
@LZoog @Yogita98 In my opinion this one is not required since `.nvmrc` files has been maintained whenever fxa uses any specific version. Check out the `.nvmrc` file in the root directory.Also I guess you would be able to have a better understanding about `.nvmrc` via this PR https://github.com/mozilla/fxa/pull/7038

**Comment by Yogita98** [comment]
I see! Thanks @Cronus1007 that was very helpful :)

**Comment by Cronus1007** [comment]
@Yogita98 Make a PR for this issue asap.Since my few issues are stuck due to it.

**Comment by Yogita98** [comment]
Not sure if I can do so since it's already assigned to @dhruva248 
What's your status though @dhruva248 ?

**Comment by dhruva248** [comment]
@Yogita98 currently working on it
