### ISSUE TITLE
[FxA-Settings] No focus border for Download button

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8117]
**Build:**
Production (Train 1.203.4)

**Affected platforms:**
Windows 10

**Steps to reproduce:**

1. Navigate to https://accounts.firefox.com/ and login using an existing account.
1. Go to 'Recovery key' section and create a new recovery key.
1. Enter the password and click 'Continue'.
1. Click the 'Download' button.

**Actual result:** 
No focus border is displayed for the button.

**Expected result:**
Focus border is displayed.

**Note:** Compare with Copy and Print buttons.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3308)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15914/No+focus+border+for+Download+.gif">No focus border for Download .gif</a>
┆Issue Number: FXA-3308

**Comment by sunny775** [comment]
Hi @LZoog 👋. This could be a "good first issue" for me to work on, as an Outreacy applicant

**Comment by LZoog** [comment]
Hi @sunny775, yes this is a great one to grab! I'll assign you.

Here's the screenshot attached:
![No focus border for Download ](https://user-images.githubusercontent.com/13018240/113456381-c60ba800-93d2-11eb-89c9-d7f89bac421c.gif)

**Comment by sunny775** [comment]
Thanks @LZoog . I'm on it right away

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue was verified as Fixed on Stage [1.204.2] under Windows 10 64-bit and Android 11. Focus border is displayed for 'Download' button.
