### ISSUE TITLE
Enhance _scripts/check.sh to verify Ubuntu dependencies are installed

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#813]
I updated the list of dependencies on Ubuntu in docs in PR #799, but @shane-tomlinson [mentions](https://github.com/mozilla/fxa/pull/799#discussion_r274354355):

> We had a script that checked for installed dependencies at one point, I thought it was check.sh. It looks like OSX already checks for gmp and graphicsmagick, I wonder if we could do the same with Linux dependencies.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-805)
┆Issue Number: FXA-805

**Comment by Cronus1007** [comment]
@lmorchard  Since this issue is still open so shall I take over this issue?

**Comment by chenba** [comment]
Let's close this.  See comments at https://github.com/mozilla/fxa/pull/6826.  @Cronus1007 Thanks again.

I think as long as we keep the README reasonably up to date, setting up FxA on Ubuntu shouldn't be too much work.  🤞
