### ISSUE TITLE
Suggest adding Support info for VPN

### ISSUE THREAD

**Issue by rbillings** [mozilla/fxa#8134]
## Description
When in FxA Settings, there is no option to contact support for VPN subscribers.

# Steps
Clicking the Help > "Contact us" menu item opens the FxA settings page with no instructions for how to contact Mozilla about VPN. https://accounts.firefox.com/settings

Found by: cpeterson

### Expected result

Option to contact support for paid subscribers

### Actual result
Support options are only available on the VPN website.

### Environment

Windows

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3313)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16002/image-2021-04-05-16-41-14-619.png">image-2021-04-05-16-41-14-619.png</a> | <a href="https://jira.mozilla.com/secure/attachment/16003/image-2021-04-05-16-44-02-007.png">image-2021-04-05-16-44-02-007.png</a>
┆Issue Number: FXA-3313

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Where are you seeing "Help > Contact Us"?  The question mark in the top right goes to SUMO which has a VPN link on the front page.

The way this was designed was to click "Paid Subscriptions" in the FxA Settings menu and then contact support from there.  That still seems reasonable to me, but I don't think I'm starting in the same place as you.

**Comment by data-sync-user** [comment]
➤ Rebecca Billings commented:

[~cpeterson@mozilla.com] do you have any additional comments?

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

> Where are you seeing "Help > Contact Us"?

Right-click on the Mozilla VPN icon in the Windows system tray > Select "Help" > Select "Contact us". Here is a screenshot of the menu.

!image-2021-04-05-16-41-14-619.png!

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Clicking the "Contact us" menu item opens the https://accounts.firefox.com/settings ( https://accounts.firefox.com/settings ) page in a new Firefox tab with no mention of Mozilla VPN or support.

!image-2021-04-05-16-44-02-007.png!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Got it.  I can't move this since it's a different org on github, but please file at https://github.com/mozilla-mobile/mozilla-vpn-client/issues for client issues like this.  Thank you.

**Comment by data-sync-user** [comment]
➤ Chris Peterson commented:

Thanks. Rebecca filed a new client issue here: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/786
