### ISSUE TITLE
Update comments in terminal with minor changes

### ISSUE THREAD

**Issue by Jane-Kotovich** [mozilla/fxa#8146]
## Description

After running YARN START and starting all services terminal give you a hint to stop everything by running "npm stop"

### Steps to reproduce

<img width="774" alt="Screen Shot 2021-04-06 at 1 05 59 pm" src="https://user-images.githubusercontent.com/76935202/113663161-e72f0a00-96ec-11eb-90e3-ccff669fb5d3.png">

### Expected result

Words "Yarn stop" to stop all services

### Environment

macOS Catalina
Google Chrome

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3319)
┆Issue Number: FXA-3319

**Comment by LZoog** [comment]
Thank you for filing this @Jane-Kotovich! It probably wasn't easy to find since I wrote this in the description, but this ask should be taken care of in #8097 when we replace all `yarn stop` references. I'm going to close it as a dupe. :)

**Comment by LZoog** [comment]
Ah, you know what, it looks like _this_ one in particular is in `package-scripts.js`. Sorry about that, I'm going to go ahead and reopen this one since it touches a different file!

**Comment by Cronus1007** [comment]
@LZoog Shall I take over this issue.Since I am well aware about this bug.
