### ISSUE TITLE
Add Mozilla logo to responsive design

### ISSUE THREAD

**Issue by Jane-Kotovich** [mozilla/fxa#8150]
## Description

On sign in page if we apply responsive view from 520px and smaller Mozilla logo and link to page https://www.mozilla.org/en-GB/about/?utm_source=firefox-accounts&utm_medium=Referral disappears

### Steps to reproduce

1. Go to Login page
2. Open responsive version
3. Try iPhone X, iPhone 6/7/8/ & Plus or drag on responsive version

https://user-images.githubusercontent.com/76935202/113746771-0740e680-974a-11eb-9ebe-6db27182b2b9.mov

### Expected result

Logo stays on the page

### Actual result

Logo disappears

### Environment

macOS Catalina
Google Chrome

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3322)
┆Issue Number: FXA-3322

**Comment by clouserw** [comment]
Thanks for filing, but this is by design.
