### ISSUE TITLE
Are verification reminders running?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#816]
Yesterday morning I created a new account in prod and didn't confirm my email, to test verification reminders. I haven't received a reminder email yet but one should have been sent after 24 hours.

Is the script running on the `fxa-admin` node yet? Is it reporting any errors?

/cc @jrgm

**Comment by philbooth** [comment]
IRC transcript:


> 16:13:01 [pb] jrgm: morning, just wanted to draw your attention to question in https://github.com/mozilla/fxa/issues/816, when you have a moment
> 16:16:19 [jrgm] pb: yeah. So setting this up to run has proved to be difficult (requires some things on the admin host that it's not set up to do). I think I'm going to have to set this up on a single auth server (which we deploy as a canary).
> 16:16:49 [pb] jrgm: ah, sorry, that didn't even occur to me that the admin node wasn't all ready to do that stuff
> 16:16:58 jbuck|conference → jbuck
> 16:19:30 [pb] jrgm: i'll check with ADavis but we may also want to clear the existing reminders that have built up in redis before starting it, because the emails have copy that is time-sensitive from when the account was created
> 16:19:58 [pb] (although it's only 3 days since it was deployed at this point and the first email says "recently", so maybe that's fine)
> 16:20:12 [ADavis] pb: it won't make a difference. Just send them
> 16:20:25 [pb] 👍
> 16:20:28 [jrgm] pb: yeah, I can reset if needed.
> 16:24:19 [pb] jrgm: i guess the other question about resetting is whether you want to from an operational perspective, given the number of db.account calls and outbound email that first iteration is going to churn through
> 16:24:58 [jrgm] pb: yes, exactly.
> 16:28:40 [pb] jrgm: so commands to reset, in redis-speak:
> 16:28:44 [pb]https://irccloud.mozilla.com/pastebin/prxKdgiK/
 Plain Text • 2 lines raw | line numbers 
> 16:29:57 [jrgm] pb: or just delete the key, no?
> 16:30:13 [pb] jrgm: yep, that too
> 16:30:24 [jrgm] pb: ok
> 16:33:22 [pb] (and actually, that should have been ZREMRANGEBYRANK instead of ZREMRANGEBYSCORE anyway)

**Comment by jrgm** [comment]
This is running in production. Logs are here - https://console.cloud.google.com/bigquery?project=moz-fx-fxa-prod-0712&orgonly=true&supportedpurview=organizationId&organizationId=442341870013&j=bq:US:bquxjob_726e9f27_16a23f79a28&page=queryresults First actual emails will go about around 00:00Z (17:00 PDT)

**Comment by jrgm** [comment]
reminders are running fine, every hour

**Comment by philbooth** [comment]
And just to confirm them from the other end, I received my reminder this morning right on time:

<img width="974" alt="Screenshot of verification reminder email in inbox, with 'Confirm email' action visible" src="https://user-images.githubusercontent.com/64367/56265674-aee62980-60d9-11e9-9070-037746f75225.png" />

<img width="946" alt="Screenshot of verification reminder email body" src="https://user-images.githubusercontent.com/64367/56265706-c32a2680-60d9-11e9-9bec-d22fba3cef75.png" />
