### ISSUE TITLE
Recovery code link in email loads blank page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8174]
This was on stage, but is probably everywhere.

STR:

1) Enable a recovery code for your account
2) Get an email with subject "Account recovery key generated"
3) In that email is a link that says "If this was not you, click here."
4) Click on that link.  In my case the URL was https://accounts.stage.mozaws.net/settings/account_recovery/confirm_revoke?utm_medium=email&utm_campaign=fx-account-recovery-generated&utm_content=fx-report

The page that loads has a header and a footer, but the content is blank.  I'm on Nightly and I didn't see any failed requests in the console.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3330)
┆Issue Number: FXA-3330

**Comment by flozender** [comment]
Hi, is this up for grabs?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

If this needs UX, please ping me

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is fixed by https://jira.mozilla.com/browse/FXA-3300 ( #https://jira.mozilla.com/browse/FXA-3300 )
