### ISSUE TITLE
Point former iFrames to our email first form

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#818]
We killed the iFrame but we realize that many old browsers are still being installed and the old /firstrun page loaded the iFrame.

The outcome is that we're losing about ~1% of registrations per month and likely a similar amount of logins.

You can see that no-iframe experience here:
https://www.mozilla.org/en-US/firefox/59.0/firstrun/

Current experience:
We display a button the accounts product page. 

Proposed experience:
Let's just link directly to our email first form. It will remove funnel steps.

**Comment by hoosteeno** [comment]
Does this belong in bedrock?

**Comment by LaurenNiolet** [comment]
@davismtl What are we talking about here, when you say ~1% of registrations / logins per month? I'm being asked to choose between this and the improved landing page for email funnel.

**Comment by davismtl** [comment]
@hoosteeno If it was in Bedrock then it might belong there. I put it here to start an investigation.

@LaurenNiolet It's just a matter of swapping URLs. I'm not sure there is a trade-off to make with making an entire landing page. This is not a big job. Rather than linking to the product page, we should point people here:
https://accounts.firefox.com/?action=email&service=sync&context=fx_desktop_v3&entrypoint=firstrun

It'll remove 1-2 steps in the funnel and remove lots of funnel exits.

**Comment by hoosteeno** [comment]
Oh, but it *is* in bedrock. We have a fallback firstrun that a *lot* of old browsers go to: https://www.mozilla.org/en-US/firefox/firstrun/

**Comment by davismtl** [comment]
@hoosteeno then let's make sure that on the fallback the button isn't "Learn more about Firefox Account". Make it "Turn on Sync" and link to:
https://accounts.firefox.com/?action=email&service=sync&context=fx_desktop_v3&entrypoint=firstrun

Users are not converting well since the product page added 2 steps vs the iFrame. By linking directly to the form, we'll recover one step.

**Comment by shane-tomlinson** [comment]
email-first is the default flow now, all direct navigation to /signin and /signup should redirect to /. Closing.
