### ISSUE TITLE
Append email to filename when downloading recovery codes and keys

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#8180]
With the move to new settings it looks like we no longer append the email address to the filename when a user download a recovery key or code. While most browser are able to detect the file, with some extensions installed it could attempt to open as a PDF and fail.

ref https://bugzilla.mozilla.org/show_bug.cgi?id=1703519

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3333)
┆Issue Number: FXA-3333

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.204.3] under Windows 10 64-bit and Android 9. The email address is successfully included in the recovery key and 2fa codes files name.
