### ISSUE TITLE
Whitespace missing between words when German language is selected

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8199]
**Build:**

Stage

**Affected platforms:**

Windows 10 x64

**Preconditions:**

Have a FxA account that was never subscribed to a premium product with Paypal payment method.

VPN is activated for Germany.

**Steps to reproduce:**

1. Navigate to [https://www-dev.allizom.org/de/products/vpn](https://www-dev.allizom.org/en-US/products/vpn).
1. Click 'Get Mozilla VPN' button.
1. Select one of the plans and then on 'Set up your subscription' page observe the text under the Pay now button.

**Actual result:** 

'die[Datenschutzerklärung'](https://paypal.com/privacy) text is not separated. Whitespace is missing.

**Expected result:** 

Text is separated.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3344)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16010/whitespace+missing+between+words.PNG">whitespace missing between words.PNG</a>
┆Issue Number: FXA-3344

**Comment by clouserw** [comment]
It looks like we need a space in the pontoon string: https://pontoon.mozilla.org/de/firefox-accounts/main.ftl/?string=221341

/cc @peiying2 @koehlermichael

**Comment by peiying2** [comment]
Fixed.

**Comment by clouserw** [comment]
thanks

**Comment by koehlermichael** [comment]
Sorry for missing that and thanks for fixing it.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on Stage [1.204.7] under Windows 10 64-bit and Android 11. The text is separated.
