### ISSUE TITLE
Default avatar character is not centered

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8210]
!image-2021-04-08-19-35-46-456.png!

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3346)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15956/image-2021-04-08-19-35-46-456.png">image-2021-04-08-19-35-46-456.png</a> | <a href="https://jira.mozilla.com/secure/attachment/16015/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-3346

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This may be OS specific.  As a C-address, I've seen this too, but I can't reproduce it today on OS X. 

No one in this triage call has an idea for an easy fix for this.

**Comment by dannycoates** [comment]
What OS dave?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Can reproduce on linux w/ nightly  !screenshot-1.png|thumbnail!

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

Windows 10 w/nightly
