### ISSUE TITLE
Flaky test "click forgot password link - change password"

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#8218]
## Description

Regularly seeing `test-settings-server` test "click forgot password link - change password" failing during unrelated changes.

Output:

```
NoSuchElement: [POST http://localhost:4444/wd/hub/session/33970752-4973-4fc9-b405-8bb6a6de0a92/element / {"using":"css selector","value":"#fxa-enter-email-header"}] Unable to locate element: #fxa-enter-email-header
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'd69fbeff8ac8', ip: '172.30.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1092-aws', java.version: '11.0.6'
Driver info: driver.version: unknown
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:191:22
  at Command.<anonymous> @ tests/functional/lib/helpers.js:65:10
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:79:18
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:73:10
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:1464:30
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:1462:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:65:10
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:1468:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:65:10
  at runMicrotasks @ anonymous
  at Command.<anonymous> @ tests/functional/lib/helpers.js:73:10
  at runMicrotasks @ anonymous
  at helpersRemoteWrapped.<computed> @ tests/functional/lib/helpers.js:3072:19
  at Test.test @ tests/functional/settings_v2/change_password.js:102:11
  @ ../../src/lib/Test.ts:268:51
  at runMicrotasks @ anonymous
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3347)
┆Issue Number: FXA-3347

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is most commonly seen when the content-server doesn't come back up from a restart or something.  Are you sure everything is running when you see this?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Sorry, I should have been more clear that this occurs in CircleCI runs. It still regularly occurs (1 ( https://app.circleci.com/pipelines/github/mozilla/fxa/18407/workflows/db340794-dd0e-4a00-b441-c8fec32fb42d/jobs/233391 ), 2 ( https://app.circleci.com/pipelines/github/mozilla/fxa/18282/workflows/22770ecf-85e6-4c2a-8867-02b52fbba83a/jobs/232397 ))

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

This appears to have been fixed by [~vbudhram@mozilla.com] updating clearBrowserState in https://github.com/mozilla/fxa/pull/8221. ( https://github.com/mozilla/fxa/pull/8221. ) Closing as its no longer reproducible locally or on stage.
