### ISSUE TITLE
NODE_ENV is a mess

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#822]
Some of our projects use `dev` and `prod` for `NODE_ENV`, others use `development` and `production`. Then the email service was made to use a hybrid `dev`/`production` mix for it's env var, and I've now duplicated that into the event broker when I copied a bunch of code across in #794.

None of that's doing any harm of course, but it's one more paper-cut in the spirit of #808. Do we care enough to harmonise them across projects? I'm not sure if the changes would be entirely limited to this repo or if we'd need to change `cloudops-deployment` too, which might take this into too-messy-to-bother-fixing territory.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-806)
┆Issue Number: FXA-806

**Comment by shane-tomlinson** [comment]
YES! I've run into this problem when trying to develop locally, "which NODE_ENV value do I need here?"

**Comment by lmorchard** [comment]
FWIW, I think the ad-hoc standard for node these days is `development` vs `production`

That said, I don't think `staging` is much in use. Seems like folks use `production` for a staging build to enable production-like things like minification in webpack & etc. Whether the server or build is aimed at a staging server tends to be specified in some variable other than `NODE_ENV`
