### ISSUE TITLE
[fxa-auth-server] Annoying errors in logs for missingFlowId

### ISSUE THREAD

**Issue by enote-kane** [mozilla/fxa#8234]
## Description

As soon as health checks are performed, the logs show up error messages like these:
```json
{
  "Timestamp": 1618210363136000000,
  "Logger": "fxa-auth-server",
  "Type": "metricsEvents.emitFlowEvent",
  "Severity": 2,
  "Pid": 1,
  "EnvVersion": "2.0",
  "Fields": {
    "event": "route./__heartbeat__.200",
    "missingFlowId": true
  }
}
```

Although not resulting in functional misbehavior, this is annoying enough as it make troubleshooting harder than necessary.

### Steps to reproduce

Create a call to `/__heartbeat__`.

### Expected result

No error message is being logged.

### Actual result

Error message get's logged, resulting in increased log storage consumption and - to a little degree - waste of energy in log processing infrastructure.

### Environment

_n/a_

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3353)
┆Issue Number: FXA-3353

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

There are probably other routes which can ignore this too

**Comment by enote-kane** [comment]
I am not 100% sure about the actual intended use-case of these log messages and whether adding too many would cause some confusion in some log data processing pipeline, so I started a bit conservative here.

I'd be happy to make this configurable, though, using the following set as defaults (configuration would simply add more):
* `/` - the root doesn't have any functionality other than presenting the version
* `/__version__` - fetching the version with `curl` shouldn't log an error
* `/__heartbeat__` - integrating health checks (Docker, Kubernetes, ...)
* `/__lbheartbeat__` - integrating health checks (Docker, Kubernetes, ...)
* `/jwks` - queried by the tokenserver (at least in self-hosted environments)
* `/introspect` - standard integration resource for FxA-external clients
