### ISSUE TITLE
[FxA-Settings] 'Remove Photo' button is misplaced in Profile Picture screen

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8235]
**Build**
Stage [Train 1.203.7]

**Affected platforms**
Windows 10 64-bit
macOS 10.14.6
iOS 14.4
Android 9

**Steps to reproduce**

1. Navigate to https://accounts.stage.mozaws.net/settings/ and login using an existing account.
1. Click on the "Add" button displayed on the right side of the Picture section.
1. Click on the "Add photo" button.
1. Select an image and click the "Open" button.
1. Click on the "Save" button.
1. Click on the "Change" button
1. Observe how the "Remove Photo" button is displayed.

**Expected results**
Add Photo / Take Photo / Remove Photo buttons are displayed on the same line.

**Actual Results**
'Remove Photo' button is displayed a bit higher than the other buttons.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3354)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15965/Screenshot_51.png">Screenshot_51.png</a>
┆Issue Number: FXA-3354

**Comment by Yogita98** [comment]
Hey @jodyheavener I'd like to fix this issue.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage  [Train 1.205.0] under Windows 10 64-bit and Android 9. 'Remove Photo' button is correctly displayed on the same line with 'Add Photo' and 'Take Photo' buttons.
