### ISSUE TITLE
URIs in package.json files should be updated for directories under packages

### ISSUE THREAD

**Issue by farhan787** [mozilla/fxa#824]
After migrating all common fxa repositories to this monorepo, the following things should be updated in the package.json for all the old repositories like fxa-content-server, fxa-profile-server. This is the [link](https://github.com/mozilla/fxa/blob/7926e11e42030a46ec2e7389f97d0c130e6b4155/packages/fxa-content-server/package.json#L27-L30) for only [fxa-content-server](https://github.com/mozilla/fxa/tree/master/packages/fxa-content-server) package but it should be updated in all packages which have a package.json file.

**Comment by farhan787** [comment]
@shane-tomlinson @philbooth what do you think about it ?

**Comment by philbooth** [comment]
@farhan787, makes sense in the short term, yep.

Long term, depending on the outcome of #694 and #785, maybe we'll even have a single top-level `package.json` and delete the child ones completely. But that shouldn't prevent any fixes you want to make in the meantime.
