### ISSUE TITLE
[subplat] Handle internal server error in handleInvoiceOpenEvent

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8265]
We are getting `Internal Server Error`s in Sentry (#FXA-AUTH-STAGE-2Z) for Stripe `invoice.finalized` webhook events when there is no billing agreement id on the `customer`, because we don't explicitly handle this type of error in our `catch` block in `handleInvoiceOpenEvent`.

After some discussion, we decided to handle this scenario further upstream, since in this case, we don't actually want to process the invoice – we can't process the invoice if there is no billing agreement.

Instead, we should `sendSubscriptionPaymentFailedEmail` to let the customer know that we cannot process a payment.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3372)
┆Issue Number: FXA-3372

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-STAGE-2Z](https://sentry.prod.mozaws.net/operations/fxa-auth-stage/issues/11020480/?referrer=github_plugin)
