### ISSUE TITLE
Remove all references to trustedUI and reasonableUI in content server

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#827]
This is a holdover from FxOS days. `trustedUI` was < 320px wide. We should deprecate this breakpoint and all mentions of it.

We should also remove the `reasonableUI` breakpoint but keep the styles as default

**Comment by karansapolia** [comment]
> We should also remove the reasonableUI breakpoint but keep the styles as default

Just to be clear, this means putting the styles that are inside the breakpoints in the declaration blocks that enclose the breakpoints, right?

**Comment by shane-tomlinson** [comment]
@johngruen - Question for you above!
