### ISSUE TITLE
Remove Reference to Chromeless param in fxa query-params docs

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#828]
On line 81 of packages/fxa-content-server-docs-query-params.md

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-807)
┆Issue Number: FXA-807

**Comment by shane-tomlinson** [comment]
Ah yes, I forgot to remove that with the removal of the iframe.

**Comment by championshuttler** [comment]
Can i take this up?

**Comment by johngruen** [comment]
@championshuttler sure!

**Comment by smishra2903** [comment]
If this issue is still open, can I work on this? 
Also, i am beginning to work on issues can I get some help on how to start with this?

**Comment by vladikoff** [comment]
@smishra2903 Hey, yeap!

See https://github.com/mozilla/fxa/search?q=Chromeless&unscoped_q=Chromeless and in  packages/fxa-content-server-docs-query-params.md , there still might be references to it. Send a pull request removing that

**Comment by apsychogirl** [comment]
Is this issue open to work on?

**Comment by vladikoff** [comment]
@apsychogirl Yeap!

**Comment by apsychogirl** [comment]
@vladikoff I was not able to find the instance of Chromeless in the fxa query-params doc. Can you please help me in fixing this issue?

**Comment by vladikoff** [comment]
@apsychogirl hm this might be it: https://github.com/mozilla/fxa/search?q=chromeless&unscoped_q=chromeless&type=Code

**Comment by clouserw** [comment]
fixed in https://github.com/mozilla/fxa/pull/5000
