### ISSUE TITLE
Changing display name on new-settings should fire profile changed event

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#8281]
This is causing breakage in one of the oauth_permissions tests.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3377)
┆Issue Number: FXA-3377

**Comment by dannycoates** [comment]
it already does afaik https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/models/Account.ts#L378 
even before the refactor

it seems like something else is tripping up the other page
