### ISSUE TITLE
[subplat] PayPal account with insufficient funds does not influence the product billing details in Manage Subscription page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8295]
**Affected versions:**

* All Firefox;

**Affected FxA versions:**

* 1.203.7;

**Affected Platforms:**

* Windows 10;

**Prerequisites:**

* Have a subscription made for VPN product using the PayPal payment method;
* Have insufficient funds for the next billing cycle.

**Steps to reproduce:**

* Open VPN subscriptions page [https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions)
* Observe the product billing section;

**Expected result:**

* The subscription is canceled or/and the billing details are stopped after the first subscription.

**Actual result:**

* The subscription appears as active and recurrent (the next billing cycle is listed).
* If the subscription is “canceled”, the popup notification informs the user that he is able to use the VPN until the next billing cycle. (which is incorrect)

**Notes:**

* Present example details:
  * 1 day plan - 1$,
  * PayPal account with only 1$ and no other funds;
  * Subscription for VPN in 04/14 - success;
  * Next billing cycle in 04/15 - failed (insufficient funds)
  * Current billing cycle in 04/16 (incorrect)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3378)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15981/billingcycle.png">billingcycle.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15995/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-3378

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks for filing this bug. [~vvirlics@mozilla.com] can you clarify a few details?

1. You signed up successfully for a daily subscription.
2. You had insufficient funds for the next charge the next day...
  2.1. Did you receive an email the next day (i.e. "We're having trouble with your payment")?

This sounds like a bug to me either way if you are not seeing any error message in the Subscription Management page.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~vvirlics@mozilla.com] Which payment method did you use for the subscription?  With my sandbox personal account, I see credit union checking account and a VISA bank card.  I have not been able to find a way to set the fund level of those two methods.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Ah nevermind!  I can change it to use PayPal balance afterward.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

[~bdanforth@mozilla.com]
1. Yes.
2. Yes.
3. Nope, but started to receive mails (80 mails) starting from last night (9.23 PM - GMT+3)

  * vvirlics+USinsufounds@mozilla.com - used account
Also, today at noon, the subscription was no longer available in Manage Subscription page.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~vvirlics@mozilla.com] for 3., so you did receive email about the payment problem, but later than expected?

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

[~bchen@mozilla.com] Yes, later and too many. 😀
I've recreated the scenario and will provide additional info on Monday. (after the subscription expires)

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Repeated the scenario on Friday 04/16.
Received 11 mails with payment failed on Saturday (04/17) and 14 mails with payment failed on Sunday (04/18). 
My account is: vvirlics+nofunds1@mozilla.com.
Stripe looks like this:
 !screenshot-1.png|thumbnail! 
I did not get to see the billing details in 04/17, as I was out of office.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I also received 25 emails per PayPal paid subscription over the period of two days.

**Comment by biancadanforth** [comment]
This is likely because the PayPal processor script is now running in Stage.
It will have picked up and tried to process any remaining open invoices
that weren't paid when the invoice was initially created/finalized. I would
ignore those and start testing with new subscriptions.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Sorry Barry I didn't see your last comment; that sounds like a bug in the PayPal processor script.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

[~vvirlics@mozilla.com]  I got a little distracted by 50 payment failed emails in my inbox... does the original bug for this Jira still reproducible for you?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

This bug was filed before the PayPal processor was running on Stage (Bug 1702805 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1702805 ); this is the script that handles retrying failed charges for PayPal customers), so I would expect this to be resolved now.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

[~bchen@mozilla.com] [~bdanforth@mozilla.com] 

We have to wait until tomorrow to see if this is still reproducing. The mailing part is all good (I've added my comment in the other issue).

Will recheck tomorrow and add my results here.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I just verified this has been fixed by having the PayPal processor running in Stage.  I see the "Manage" link and message in the subscription management as expected.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

I can confirm that the message on a red banner is displayed on the Manage Subscription page, together with a red "Manage" button;
Also the subscription was removed if no action is taken via PayPal to fix the problem.
