### ISSUE TITLE
[subplat][emails] Customer's Invoice Emails Are in An Unexpected Language

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8299]
VPN customer support reported that a customer received VPN payment emails in Italian, while other FxA emails are in English.

The customer said that they have not signed into FxA from Italy but have used an Italian server on VPN.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3380)
┆Issue Number: FXA-3380

**Comment by biancadanforth** [comment]
This should be handled by #8307 . Closing.
