### ISSUE TITLE
./pm2 start mysql_servers.json errors on auth

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#831]
### STR

* `./pm2 start mysql_servers.json`
* sign up
* copy and paste auth URL from PM2 logs

### Expected
go to settings

### Actual
Settings page is blank and there's CORS console warning `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:9010/v1/authorization. (Reason: CORS request did not succeed).`

**Comment by wavepack3t** [comment]
What is the auth URL you are using? I can load the settings page at `http://127.0.0.1:3030`. Using a different hostname like `myhostname:3030` has given me troubles with this in the past.

**Comment by dannycoates** [comment]
fixed? can't repro
