### ISSUE TITLE
Remove deprecated images from content server

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#834]
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-808)
┆Issue Number: FXA-808

**Comment by shane-tomlinson** [comment]
Do you have a list of those we can remove?

**Comment by clouserw** [comment]
ping @johngruen for more info

**Comment by johngruen** [comment]
i mean, `grep` for images?

**Comment by smishra2903** [comment]
Hello, if this i still open, can I work on this?

**Comment by vladikoff** [comment]
@smishra2903 Yeap!

**Comment by LZoog** [comment]
@smishra2903 This may actually be mostly taken care of, I didn't see this issue before making #2554 last September which has been closed out. Feel free to look through our images in `fxa-content-server`, otherwise we can close this as a dupe. 🙂
