### ISSUE TITLE
[FxA-Settings] The date and time are not displayed in Verification Code email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8341]
**Build**
 Stage [Train 1.204.3]

**Affected platforms**
 Windows 10 64-bit

**Steps to reproduce**

1. Navigate to [https://accounts.stage.mozaws.net/settings/](https://accounts.stage.mozaws.net/settings/) and follow the account creation flow.
1. Go to the email address inbox and open the "Verification code: XXXXXX" email.
1. Check for the date and time.

**Expected results**
 The date and time is successfully displayed in the email under the IP address.

**Actual Results**
 The date and time is not displayed in the Verification code email.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3394)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16112/Screenshot_60.png">Screenshot_60.png</a>
┆Issue Number: FXA-3394

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We think this is correct and we don't think we've changed this email in a long time.  Is there something indicating we'd have a date/time there?

**Comment by Yogita98** [comment]
Hey @mozilla/fxa-devs
I'd like to work on this issue. I just pulled the `verifyLoginCode` email template and saw that we have a date field just below the IP address as shown below:
![image](https://user-images.githubusercontent.com/37609519/115582606-c36fe480-a2e6-11eb-8a0f-f29ec398bb6a.png)

But the email that user gets doesn't have one as shown:
![image](https://user-images.githubusercontent.com/37609519/115583038-25c8e500-a2e7-11eb-905c-eb7a1709931d.png)

**Comment by clouserw** [comment]
Thanks for your initiative.  That looks like an email for signing up a new account and an email for logging in to an existing one.

My original question for QA is still relevant though before we move forward on anything - is there a spec or document that says we should have a date code in this email?

**Comment by Yogita98** [comment]
Ohhh I see! My bad and sorry for that. I guess the template that is being used is `verifyShortCode` 

No problem I'll wait for the reply. Thanks for the guidance!

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

[~wclouser@mozilla.com] This issue was logged based on the consistency compared with the other emails. As the “Sign-in code for Firefox” email which contains the verification code with limited availability displays the date and time, it would be helpful also to display these time details in the Registration email too just to emphasize the activation limited time.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Got it, thanks.  I changed this from being a bug to being an enhancement request.  

Yogita - if you want to add the date in the same place as the other email, go for it.  Thanks!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~lzugai@mozilla.com] this is the issue we talked about

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Tested this fix on Stage [Train 1.206.0] under Windows 10 64-bit and I confirm that the date and time are successfully displayed in Verification Code email, but I noticed that the time is not expressed according to the user's location - issues tracked in FXA-3492.
