### ISSUE TITLE
[subplat] Error while trying to subscribe - with the same fxa account - for €-plan after a $-plan subscription expired

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8342]
**Affected versions:**

* All Firefox;

**Affected FxA versions:**

* 1.204.3;

**Affected Platforms:**

* Windows 10;

**Prerequisites:**

* Have a subscription made for Mozilla VPN product using the PayPal payment method and a 1 day $-plan;
* Cancel the subscription and wait until expires;

**Steps to reproduce:**

* Open VPN homepage https://www-dev.allizom.org/en-US/products/vpn/
* With the account from prerequisites, try to subscribe to VPN product using PayPal and a Euro-plan.

**Expected result:**

* User can subscribe to any plan.

**Actual result:**

* User cannot subscribe to a different plan.

**Notes:**

* tried with both PayPal and Stripe payment methods - same results;
* works if trying to subscribe to a plan with same currency;

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3395)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16118/FRafterUS.gif">FRafterUS.gif</a>
┆Issue Number: FXA-3395

**Comment by biancadanforth** [comment]
Based on the [Stripe docs](https://support.stripe.com/questions/setting-a-customers-default-currency), it is not possible to change the currency for a customer after they have subscribed in one currency.

It should be possible for Support staff to help a customer in this situation by going into the Stripe dashboard and deleting the Stripe customer record. Then the customer should be able to go through the Checkout process anew with a different currency payment method.

If this is a significant problem in production, we can re-examine this.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

I understand. Thanks for the info! [~bdanforth@mozilla.com]
We should, maybe, improve the messaging, with something that could let the user know what happened and in what direction to go to.

**Comment by biancadanforth** [comment]
Definitely true that we could potentially improve the error message here. We have talked in the past about possibly adding a link to Support during the Checkout flow ([RCA](https://docs.google.com/document/d/1XVR-zkm3sM2Ku5PQLOmy4CvCivdFAn9XrSXzKCSxf_E/edit#)) or changing the logic for access to the Subscription Management page so recent subscribers can still get there even after their subscription is no longer active (FXA-3239).

@jess-cook03 I don't expect this to be a common scenario, but I wanted to loop you in to get your thoughts, particularly as we think about funnel improvements (e.g. how we gate Support access and access to Subscription Management).

**Comment by jess-cook03** [comment]
@biancadanforth for now its hard for me to weigh in as we are currently working through what the improvements will be....but I think improving the error messaging would be a great start.
Can we get a screenshot of the current messaging? Then we can access from there

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

[~jecook@mozilla.com]
The current messaging is:
 !screenshot-1.png|thumbnail!

**Comment by biancadanforth** [comment]
Valentina, Jess: If you think we should update the error message in this scenario (which I don't imagine will be very common), please feel free to file a new ticket and reference this one.
