### ISSUE TITLE
Add statsd monitoring for Stripe API calls

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8358]
For example, failures to renew

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3404)
┆Issue Number: FXA-3404

**Comment by bbangert** [comment]
We have statsd monitoring of stripe and paypal calls and errors. They're on the auto-server dashboard.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Only the timing is reported to statsd, we should be reporting success/errors like we do for paypal.
