### ISSUE TITLE
Implement a locking version of the reminders script

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#837]
In https://github.com/mozilla-services/cloudops-deployment/pull/3102, @jrgm points out that verification reminders script sucks to run.

It can't simply be run on the admin node, as I naively assumed it could, because that doesn't have config or permissions etc to hook in to the auth db and the email service. For now it is running on the canary instance instead, which necessitated some bespoke config.

If we add a distributed locking mechanism, we could instead run it on the vanilla auth instances in prod, with the instance that acquires the lock having exclusivity to run the script. [Redlock](https://redis.io/topics/distlock) could be used for that synchronisation part.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-809)
┆Issue Number: FXA-809

**Comment by jrgm** [comment]
I don't think it was naive. Or, at least, I expected it to go on admin too, until I looked at what that would require.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
