### ISSUE TITLE
Enable Basque (eu) on production

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa#8378]
The community is making huge progress in the project, especially the high priority component Settings.ftl. They would like to see the product enabled on production while they keep working  on it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3414)
┆Issue Number: FXA-3414

**Comment by clouserw** [comment]
This is an fxa issue so I moved it to FxA for triage. It's a one line change though I think.
