### ISSUE TITLE
Account email is shown as first item in main menu, accidentally reveals private email to anyone looking over user's shoulder

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#8386]
This was reported via the community form for Foxfooding of MR1/Proton, but my guts tell me this isn't Proton specific, or even something they can fix and this belongs here somewhere.

---

**Firefox Version:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
**Window Size (inner width and height):** 1536x752

## Steps to Reproduce
1. Open hamburger menu
2. See issue

## Expected Behavior
Show some other text like "Firefox Account" if we haven't set any name for our account, or use the name if we have. 

## Actual Behavior
Shows the primary email used for the Firefox Sync account connected to the browser, which makes it easy for anyone looking over the user's shoulder to learn the user's email. This was an issue in the previous design too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3415)
┆Issue Number: FXA-3415

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing.  This menu's UI was designed the way it is on purpose so I'm going to wontfix this.
