### ISSUE TITLE
[FxA-Settings] Tooltip text is written differently for Bento menu icon vs. Account menu icon

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8387]
**Build:**
 Stage (Train 1.204.6)

**Affected platforms:**
 Windows 10 64-bit

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in using an existing account.
1. Hover over the Bento menu icon and observe the tooltip.
1. Hover over the Account menu icon and compare the tooltip with the Bento menu one.

**Actual result:** 
 The words in the Bento tooltip start all with uppercase letters. The words in the Account tooltip don't start all with uppercase letters. There is no consistency.

**Expected result:** 
 The tooltips for both Bento menu and Account menu icons are written similarly (with lowercase or uppercase).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3416)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16033/tooltip+text+difference.PNG">tooltip text difference.PNG</a>
┆Issue Number: FXA-3416

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

"Firefox Bento Menu" should be "Firefox apps and services"

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

When this is done it will need to be a new string in the ftl file.  You can append "-2" to the string

**Comment by amantayal6797** [comment]
Hey @LZoog and @data-sync-user , Can I take a look into this ?
