### ISSUE TITLE
in sync, cannot rename device

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#8395]
Originally reported via Foxfooding

---

**Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
**Window Size (inner width and height):** 1920x923

## Steps to Reproduce
1) login to firefox sync
2) go to https://accounts.firefox.com/settings
3) see list of devices

## Expected Behavior
there is no way to rename current device

## Actual Behavior
we should be able to rename current device

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3421)
┆Issue Number: FXA-3421

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing.  The way we've designed this is that device names are set on the devices and flow into FxA.
