### ISSUE TITLE
[FxA-Settings] Zoom in/Zoom out/Rotate tooltips are not translated when different languages are selected

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8404]
**Build:**
Stage (Train 1.204.7)

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**

1. Launch Firefox using a fr, ge, ar, sq, cy, etc. build (or set the desired language from about:preferences -> Choose your preferred language for displaying pages).
1. Navigate to https://accounts.stage.mozaws.net/ and log in using an existing account.
1. Go to Profile Picture section and click the 'Add/Change' button.
1. Add a new photo.
1. Hover over the Zoom in/Zoom out/Rotate buttons and observe the tooltip.

**Actual result:** 
Zoom in/Zoom out/Rotate tooltips are not translated in the selected language.

**Expected result:** 
Zoom in/Zoom out/Rotate tooltips are translated in the selected language.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3423)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16145/tooltip+not+translated.PNG">tooltip not translated.PNG</a>
┆Issue Number: FXA-3423

**Comment by dannycoates** [comment]
fixed in https://github.com/mozilla/fxa-content-server-l10n/pull/492
