### ISSUE TITLE
Pilcrow in message (bug in Fluent?)

### ISSUE THREAD

**Issue by psimonyi** [mozilla/fxa#8483]
## Description

On the Firefox Accounts Profile page, the Secondary Email note contains a pilcrow where it should just be a space:

> Note: a secondary email won’t restore your information — you’ll¶need a recovery key for that.

This message comes from the FTL for [se-content-note](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/UnitRowSecondaryEmail/en-US.ftl#L31), which looks like a correctly formatted line continuation according to the Fluent spec, so it's quite likely this is a bug in whatever Fluent implementation this page is using.

### Steps to reproduce

URL: https://accounts.firefox.com/settings#secondary-email

Add a secondary email to your account. Then open your account profile and look at the grey note in the Secondary email section.

### Expected result

The message should end with "you'll need a recovery key for that."

### Actual result

The message ends with "you’ll¶need a recovery key for that."

### Environment

Using Firefox 88, production Firefox Accounts.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3448)
┆Issue Number: FXA-3448

**Comment by clouserw** [comment]
Thanks for the write-up.  I filed this at https://bugzilla.mozilla.org/show_bug.cgi?id=1711736
