### ISSUE TITLE
Sign out seems to be broken

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#8493]
Not sure when this broke, maybe a dependency update that didn't run content server tests? If you try to log out it fails with the follow error:

<img width="534" alt="Screen Shot 2021-05-05 at 12 47 01 PM" src="https://user-images.githubusercontent.com/1295288/117178785-6709cc00-ada0-11eb-9582-258a2901ac09.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3452)
┆Issue Number: FXA-3452

**Comment by vbudhram** [comment]
Looks like this was broken when we upgraded `graphql-query-complexity` in https://github.com/mozilla/fxa/pull/8489. Checking if fix is easier than reverting..

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

That commit was reverted and never made it to staging/prod.
