### ISSUE TITLE
[subplat] Implement similar retry behavior in PayPal to Smart Retries

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8563]
FXA-3400 seeks to modify our existing failed payment emails to use language to indicate that we are using Smart Retries to retry failed payments over a period of days. Unfortunately, this feature is only available to Stripe customers, so we should consider applying a similar grace period for PayPal customers.

IIUC from Ben, this is a configurable value, though there may need to be additional tweaks to some of the PayPal processor code or email logic to accommodate this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4721)

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Ideally we'd like to have similar behavior to Stripe's smart retries, that takes into account why the payment attempt failed, tries them in the morning local time for the agreement id, etc.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
