### ISSUE TITLE
Choosing to sign-in via settings after opening the deep-link from SMS doesn't autofill the email

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#859]
Device: Huawei P9 Lite (Android 6.0);
Build: Release 66.0.2;

Prerequisites:
Send an install link via SMS from your desktop log-in flow;

Steps to reproduce:
1. Open the received SMS;
2. Open the link using Firefox;
3. Close the tab and then open the 3dots menu->Settings->Sign in;

Expected results:
The email is still pre-filled.

Actual results:
The email is not pre-filled.

Notes:
- [video](https://drive.google.com/file/d/0B-OVCGyglYi_T2pKWWNJTDJfRVFfQmVXZnJ3R01Lb3RVbzBV/view?usp=sharing)

**Comment by shane-tomlinson** [comment]
Oh, I see what you did here... We could... store the email and use it whenever we load the page again.

**Comment by clouserw** [comment]
This is a good idea, but not something we're going to prioritize.  Thanks!
