### ISSUE TITLE
Improve copy for proposed add a device CTA

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#86]
When users are in Sync preferences and click Manage, they will be taken to their account online. We are adding a Devices section that (ideally) lists all of the devices that are connected to Sync.

Most users will only have one device, and this is a shame because this means they are not really syncing, but only using a not-very-reliable backup. And beyond that it likely that they aren't aware that Firefox exists on other platforms.

We would like a call to action that best lets users know how (and why) to add other devices.

Here is an attempt that I know you can take to the next level:
![devices-disconnect-and-refresh-only](https://cloud.githubusercontent.com/assets/68213/11281252/d201f738-8ec7-11e5-986c-fffcc51499f7.png)
 
@mozmatej

**Comment by MozMatej** [comment]
I would flip the first line and tweak it slightly:

"Firefox is available for Windows, OSX, Android, iOS and Linux. You can manage your devices below."

I'd also change the link so it doesn't say "seeing:"

"Don't see all your devices?"

WDYT?

**Comment by ryanfeeley** [comment]
Great improvement again!

**Comment by vladikoff** [comment]
I will add a string PR so we can get this translated quickly...

Need to talk to @rfk about adding other / older devices. Chris told me we can use the verifier to add older devices.

**Comment by ryanfeeley** [comment]
@vladikoff I updated the spec (my original PR) already.

**Comment by rfk** [comment]
The current version of the feature card [1] suggests that we'll show all your active session tokens in that list.  Under that model you would definitely see all your devices, but you might also see other things that are not really a "device", e.g. sessions left over from a web login flow.

Sounds like that's not what we actually plan to ship, so let's iterate the definition it with a follow-up PR.  @vladikoff or @philbooth, who wants to drive that?

> might be able to use the verifier to add older devices.

FWIW my current position is that auto-magically creating a device record for older devices is a recipe for weirdness and pain.  Something needs to be responsible for keeping the record up-to-date, and it's not clear to me that anything but the device itself has all the info necessary to do so.

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-16-devices-view#what-is-a-device

**Comment by vladikoff** [comment]
> Under that model you would definitely see all your devices, but you might also see other things that are not really a "device", e.g. sessions left over from a web login flow.

> Sounds like that's not what we actually plan to ship, so let's iterate the definition it with a follow-up PR. @vladikoff or @philbooth, who wants to drive that?

Let's chat about this today in the 1:1 and I will drive the update to the spec from there

**Comment by vladikoff** [comment]
> Improve copy for proposed add a device CTA 

Otherwise the new copy is merged into features and we shall add it to the view
