### ISSUE TITLE
Downloading the app by opening the deep-link opens the Welcome screen instead of the log-in flow

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#861]
Device: Huawei P9 Lite (Android 6.0);
Build: Firefox Release 66.0.2;

Prerequisites:
- "Send an install link from your desktop log-in flow. 
- Make sure you don't have the app in your device.

Steps to reproduce:
1. Open the received SMS;
2. Choose a browser to open the link;
3. Download the app and then open it.

Expected results:
You are redirected to the login flow and the email used to log-in on Desktop is pre-filled.

Actual results:
You are not redirected to the login flow, instead of that, the welcome screen it's presented.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-812)
┆Issue Number: FXA-812

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
