### ISSUE TITLE
Discuss updating delete account warning

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#865]
Currently, instead of deleting users data on our various relying service, we present this text.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/68213/56308437-4f0d7400-6115-11e9-9368-abf9528de390.png">

> If you use this account for Mozilla apps and services like AMO, Pocket, and Screenshots you should first log in and remove any saved personal information. Once you delete your account here you may lose access to it everywhere.

This text is problematic for two reasons:
1. AMO is probably best known as Add-ons (easy fix)
1. This list of service changes frequently. Can we include the list dynamically or (easier) rewrite the copy to be more generic? (perhaps invoke "Mozilla apps and relying services")

Please share your thoughts.

**Comment by ryanfeeley** [comment]
Oh, and I just realized that we do know what services they have connected to their account (e.g. Send) so we might be able to present this very accurately (though sentence form is a nightmare for translators)

**Comment by shane-tomlinson** [comment]
First off, this text was specified by Legal, so we'll have to get their approval before making any changes.

> we do know what services they have connected to their account

This is only partially true. We only know the list of services a user is *currently signed in to*, we do not keep a historical list. See https://github.com/mozilla/fxa/issues/459 and https://github.com/mozilla/fxa/issues/710 for adding such ability.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Should we warn users when they revoke a service when it does not delete the data from the service? I'll file a new issue if so.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Should we warn users when they revoke a service when it does not delete the data from the service? I'll file a new issue if so.

Seems reasonable, I'm not sure how it'd look? A mock would be a good place to start a discussion from.

**Comment by clouserw** [comment]
There are related/similar mockups with the premium services stuff.  We should compare and sync-up

**Comment by davismtl** [comment]
Legal may also require us to update this copy. TBD.

**Comment by ryanfeeley** [comment]
This UX was updated in another issue for subscriptions.
