### ISSUE TITLE
Verification reminders script does not log metrics

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#866]
The script for verification reminders uses a NOP log object that means it doesn't log any flow or amplitude events when it runs. This means we can't measure the impact that it's having on sign-ups.

We can fix that easily, but then there is more work to do to get those logs feeding into our metrics pipeline. I'm not sure if we even want the canary instance logging into the metrics pipeline or not, if not we may have to fix #837 first too.

/cc @jrgm @davismtl @irrationalagent 

Really sorry Alex & Leif, I should have realised this ahead of time.

**Comment by philbooth** [comment]
Will be fixed with mozilla/fxa-amplitude-send#89.

**Comment by philbooth** [comment]
Note there is the start of a flow event dashboard here, although it's not very useful yet:

https://sql.telemetry.mozilla.org/dashboard/fxa-verification-reminders

**Comment by irrationalagent** [comment]
confused about one thing here - I noticed that these email events don't have a flow_id associated with them, is that going to be a problem going forward trying to tie email account verifications to these email templates specifically?

**Comment by philbooth** [comment]
> I noticed that these email events don't have a flow_id associated with them, is that going to be a problem going forward trying to tie email account verifications to these email templates specifically?

That's an artifact of a simple first implementation rather than a conscious long-term decision, sorry. We can absolutely store the `flow_id` in Redis along with the `uid`, which is the only thing that's in there at the moment. Same goes for anything else btw. I'll add it now.

**Comment by irrationalagent** [comment]
no worries, just making sure I wasn't missing something, but thanks for doing that!

**Comment by irrationalagent** [comment]
Sorry to keep asking, but any ETA on the amplitude events? Are they going out with the monday train?

**Comment by shane-tomlinson** [comment]
> @Sorry to keep asking, but any ETA on the amplitude events? Are they going out with the monday train?

@jbuck - are those going out now?

**Comment by vbudhram** [comment]
Per jbuck, events are being logged now via Stackdriver.

**Comment by jbuck** [comment]
Blocked on https://github.com/mozilla/fxa-amplitude-send/pull/90

**Comment by clouserw** [comment]
If this is 13 points, let's talk about it and now it relates to other priorities.

**Comment by philbooth** [comment]
> If this is 13 points, let's talk about it and now it relates to other priorities.

It's 13 points because of the work done so far rather than the work that isn't done yet. It's been open for over a month, and keeps getting punted from train to train. All that's remaining now is the deployment part, but I figured the estimate should still reflect the broader effort?

**Comment by clouserw** [comment]
Got it.  That sounds right, thanks.

**Comment by jbuck** [comment]
This is deployed and running in stage/prod as of yesterday!

🎊
