### ISSUE TITLE
Storybook story grouping is broken

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#8686]
Looks like Storybook is no longer grouping stories by components and pages:

<img width="333" alt="Screen Shot 2021-05-21 at 11 19 56 AM" src="https://user-images.githubusercontent.com/6392049/119164563-90765900-ba2a-11eb-9ada-d7eaf1464167.png">

I think the fix here is to replace the vertical pipe `|` with a forward slash `/` in all story names.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3575)
┆Issue Number: FXA-3575

**Comment by lmorchard** [comment]
Oh, yeah, thanks for filing this - I meant to after the upgrade but forgot. Looks like they revamped to support *only* `/` as hierarchy delimiter, but also added some options for sorting: https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy
