### ISSUE TITLE
Connected Services devices do not localize the word "on"

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#8687]
## Description

Connected Services devices do not localize the word "on".

<img width="380" alt="Screen Shot 2021-05-21 at 10 42 48 AM" src="https://user-images.githubusercontent.com/6392049/119165110-26aa7f00-ba2b-11eb-9860-09101a8dbac7.png">

### Steps to reproduce

- Connect a device to your Firefox Account, such that it lists it in the format of "[Application] on [Device name]"
- Open Firefox Accounts in a non-English locale

### Expected result

The word "on" in the device name string is localized

### Actual result

No localization

### Additional notes

It looks like this is due to the full device name coming directly from the server, and might not be something we can easily localize. If possible it might be nice to split up the application from the device name so the client can localize the joining word.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3576)
┆Issue Number: FXA-3576

**Comment by clouserw** [comment]
I don't think we can cleanly localize a joining word and then append 3 strings together.  We might be able to get away with a single localized string of `%app% on %device%' and a comment that says what the string is for and localizers could just make it a semi-colon or something if it doesn't flow correctly as a sentence.

@peiying2 - what is your recommendation?

**Comment by peiying2** [comment]
> I don't think we can cleanly localize a joining word and then append 3 strings together. We might be able to get away with a single localized string of `%app% on %device%' and a comment that says what the string is for and localizers could just make it a semi-colon or something if it doesn't flow correctly as a sentence.
> 
> @peiying2 - what is your recommendation?
I like your suggestion `%app% on %device%`. This will allow localizers rearrange the string in the order that is natural in the target language. If we break it up into three segments, we assume the flow of the sentence is the same as English, which is not the case.
