### ISSUE TITLE
[FxA-Settings] White-space can be added as display name

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8711]
**Build:**
Stage (Train 1.206.1)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14.6
Android 11
iOS 14.4

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and log in with an existing account.
1. Go to “Display name” section and click “Add” button.
1. Enter white-space in the display name field and click “Save”.

**Actual result:**
White-space is added as display name.

**Expected result:** 
White-space is not added as display name.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3590)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16312/Display+name+accepts+white-space.gif">Display name accepts white-space.gif</a>
┆Issue Number: FXA-3590

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

If we trim and length is zero we should remove the display name.

**Comment by kaushikjatin** [comment]
I would like to work on this issue, please assign this issue to me.
