### ISSUE TITLE
[FxA-Settings] “Connected services” section title is not aligned with the other section’s titles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8727]
**Build:**
Stage (Train 1.206.1)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14.6

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/ and log in with an existing account.
1. Scroll down the page and observe the alignment of the section’s titles.

**Actual result:** 
“Connected services” title is not aligned with the other ones.

**Expected result:** 
“Connected services” title is aligned with the other ones.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3596)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16415/Connected+services+txt+not+aligned.PNG">Connected services txt not aligned.PNG</a>
┆Issue Number: FXA-3596

**Comment by Jo-bot86** [comment]
Can I work on this?
