### ISSUE TITLE
MozillaVPN: accounts.firefox.com/support redirects to settings with no indication on getting support

### ISSUE THREAD

**Issue by rubenwardy** [mozilla/fxa#8794]
## Description

I subscribed to MozillaVPN over a week ago. The website crashed, but money was still taken and I received "Welcome to Mozilla VPN" and "Mozilla VPN payment received" emails.

However, I wasn't able to log into MozillaVPN even after a week, so I started looking for support.

Those emails contained the following link:

`https://accounts.firefox.com/support?utm_medium=email&utm_campaign=fx-new-subscription&utm_content=fx-subscription-support`

Clicking the link causes a redirect to https://accounts.firefox.com/settings/ with no error messages at all, presumably due to the subscription not existing.

I wasn't able to find any places to get support online. In the end, I had to join the Mozilla VPN matrix channel to ask.

### Steps to reproduce

I can reproduce it by clicking that link, I don't know how to reproduce the error to have those emails without the subscription

### Expected result

It should either fail gracefully, with an error message and information on getting support, or it should just work without a found subscription.

### Actual result

Clicking the link causes a redirect to https://accounts.firefox.com/settings/ with no error message, presumably due to the subscription not existing.

### Environment

Manjaro Linux, Firefox 88.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3616)
┆Issue Number: FXA-3616

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Thanks for filing this.  Opening up the support form to user without subscriptions is on our roadmap.
