### ISSUE TITLE
Issue short-lived OAuth tokens for use by subscriptions management pages

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#881]
Related to #695 
Eventually blocks #715 and #716?

The API resources used by the subscription management pages will require an OAuth token to use.

- [x] A new OAuth client ID should be created specifically for the subscription management pages.
- [x] The token should be created from the sessionToken available to content server pages.
- [x] Ensure the token is short-lived (i.e. 900 seconds)
- [x] Ensure the token is scoped such that it can read user profile details and use the read/write subscription API resources on the auth server
- [x] The scope for using read/write subscription API resources should only be allowed for tokens issued from sessionToken so that only the subscription management pages end up using it
- [ ]  Follow-up in #1694 ~If the payment page notices the oauth token is expired, it should also refresh the page. This will require some state to be preserved - i.e. what product ID was the user attempting to sign up for in #716~

In PR #819, the read/write subscriptions API scope is `https://identity.mozilla.com/apps/subscriptions` - we can change this as part of this issue if necessary

**Comment by lmorchard** [comment]
This may be enabled by PR #795 / Issue #531

**Comment by lmorchard** [comment]
Tagging @shane-tomlinson and @bbangert here for some thoughts.

**Comment by lmorchard** [comment]
Just as an exploration on top of PR #907, I tried generating an OAuth token when a new subscriptions "manage" button is clicked on the settings page:

https://github.com/lmorchard/fxa/commit/47e632b5020381082cdc3331f3398f4513e43ff8

Kind of messy, but it does seem to work and the payment pages can make calls to the auth API server.

I guess the main question is - am I at all on the right track here with [a modified call to `Account.createOAuthToken()`](https://github.com/lmorchard/fxa/commit/47e632b5020381082cdc3331f3398f4513e43ff8#diff-4f35524d57c29439fb76756a72730740R256)? Just because it works doesn't mean I'm doing the right thing in the right place, etc :)

**Comment by lmorchard** [comment]
Bumping up the estimate on this one because the fine details are exposing more effort

**Comment by clouserw** [comment]
@lmorchard to close this issue and split into appropriate issues

**Comment by lmorchard** [comment]
Filed #1694 for token expiration. Trying to find an existing issue for converting payment-server into a full OAuth RP, will file a new one if necessary...

**Comment by lmorchard** [comment]
Closing with followups in various phases of the project:

https://github.com/mozilla/fxa/issues/1694
https://github.com/mozilla/fxa/issues/1695
https://github.com/mozilla/fxa/issues/1696
