### ISSUE TITLE
Define and implement metrics events for subscription APIs

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#883]
Related to #706

The new subscription APIs from PR #819 will need metrics pings defined and implemented

**Comment by irrationalagent** [comment]
this is next in my queue, should be able to start on it in the next couple days.

**Comment by irrationalagent** [comment]
I started putting some notes and the draft of a spec linked [here](https://docs.google.com/document/d/1d39yRiYt4rhahtMae04Pwcx5vldNQJeF1grz_KO8qJw/edit#heading=h.7c4a6r3mex02)

**Comment by shane-tomlinson** [comment]
Ref https://docs.google.com/document/d/1d39yRiYt4rhahtMae04Pwcx5vldNQJeF1grz_KO8qJw/edit#

**Comment by lmorchard** [comment]
I think I'm going to just close this issue, since the new metrics are being defined and we have a slew of new broken-out issues for implementing metrics.
