### ISSUE TITLE
PayPalClientError: PayPal NVP returned a non-success ACK. See "this.raw" or "this.data" for more details. PayPal err...

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#8830]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11557150/?referrer=github_plugin

```
PayPalClientError: PayPal NVP returned a non-success ACK. See "this.raw" or "this.data" for more details. PayPal error code: 10414
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal-client.js", line 146, in PayPalClient.doRequest
    throw new PayPalClientError(result.text, resultObj);
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal.js", line 131, in async PayPalHelper.chargeCustomer
    const response = await this.client.doReferenceTransaction(doReferenceTransactionOptions);
  ?, in async Promise.all
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal.js", line 285, in async PayPalHelper.processInvoice
    [transactionResponse] = (await Promise.all(promises));
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/paypal-processor.js", line 171, in async PaypalProcessor.makePaymentAttempt
    await this.paypalHelper.processInvoice({
...
(4 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4065)

**Comment by chenba** [comment]
Sentry issue: [FXA-AUTH-PROD-BX](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11493484/?referrer=github_plugin)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

[~bchen@mozilla.com] Can you create a follow-up to better differentiate these different PayPal errors?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

This is not a SubPlat error – these errors were for the same user – they likely modified their BA max amount in PayPal.

**Comment by biancadanforth** [comment]
Going to re-open this and specify that we'd like to log `this.raw` or `this.data` for these errors to get more information. E.g. https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/13521058/?query=is%3Aunresolved just happened recently.

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-DV](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/13521058/?referrer=github_plugin)

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-BQ](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11352374/?referrer=github_plugin)

We need some more information here to see what the context of the refund was.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

We may be able to reproduce these errors locally with PayPal negative testing ( https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/13521058/?query=is%3Aunresolved ), but for the purpose of this ticket, we just want to expand this.raw/this.data.
