### ISSUE TITLE
Implement rate limiting for subscriptions/{plans,active}?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#884]
Related to #706 

PR #819 introduces two new API endpoints:
* `subscriptions/plans` which relays available subscription plans from subhub
* `subscriptions/active` which lists the user's current active subscriptions.

@shane-tomlinson [asks](https://github.com/mozilla/fxa/pull/819#discussion_r276178206):
> Should we rate limit the calling of both /subscriptions/plans and /subscriptions/active?

@lmorchard said:
> Maybe? Should be fairly static results for display on the management page though. If we do rate limit, is that a thing we do elsewhere or maybe in the customs server? (looking for an example)

**Comment by lmorchard** [comment]
@vbudhram [says](https://github.com/mozilla/fxa/pull/819#discussion_r276835959):
> FWIW, I think it is ok to not rate limiting here since we are using an authentication strategy. If the route was unauthenticated, we should definitely rate limit though.

Going to leave this issue open for now, though - maybe we want to nod heads before closing it at the next status / triage.

**Comment by clouserw** [comment]
Since these are behind auth, it's ok not to rate limit these.  -> closing
