### ISSUE TITLE
Implement better failure handling for subscription creation and cancellation?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#886]
Related to #706 

@shane-tomlinson [asks](https://github.com/mozilla/fxa/pull/819#discussion_r276180011):

> Is it possible for the subscription to be created on subhub but fail when being created in our DB? If so, how do we handle the SubHub subscription? Should it be deleted? Since these two calls are not atomic, it seems like we'll need to handle failures.

> Follow on: Similar to the comment below, the operations to update subhub and our local db are not atomic, meaning it's possible for the call to db.deleteAccountSubscription to fail and subhub.cancelSubscription to succeed. We'll want to think about how to handle those cases. Do we have to re-subscribe the user to subhub if the db.deleteAccountSubscription fails? Do we re-try? Do we alert loudly?

Maybe we can fall back to async events from subhub (#713) to ensure subscription status is updated? Creating this issue to call out the concern and decide what might need doing one way or another.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-817)
┆Issue Number: FXA-817

**Comment by rfk** [comment]
One option could be to have a boolean "dirty bit" on the subscription records in our db, and update the db in two phases.  So adding a subscription would look like:

* Write the subscription into the db, flagged as dirty=true
* Write the subscription into subhub
* Update the subscription in the db to set dirty=false

Deleting a subscription would go in the opposite order:

* Update the subscription in the db to set dirty=true
* Delete the subscription in subhub
* Delete the subscription in the db

When the user comes to exercise their subscriptions, you would check the dirty bit and, if true, do some reconciliation with their account state in subhub to see what the correct state is.

There would be nontrivial complexity involved here, not sure if it would be worth it in practice. But wanted to throw it out there as a suggestion.

**Comment by rfk** [comment]
(Another option is to just assume it will happen rarely, and clean it up by hand when users complain...which could in fact be the lowest-cost option overall)

**Comment by clouserw** [comment]
From our team discussion:
- Any communication with subhub should have the capability to resend/retry
- We expect Subhub to reply immediately (synchronously) with a success message

If we don't get a success message, then: 
- If 5xx: Data is resent immediately
- If 4xx: Data is not resent.  Log errors, I guess.
- If anything else: Data is resent immediately

Maximum number of retries: Default 3, but it should be a configuration variable.  This should include a backoff option for subsequent retries.  Subhub hasn't implemented a backoff header at this point.

If all retries fail, we need to surface an error to the user.  While we're at it, there are also several other error cases, including:
- Errors from Stripe: https://stripe.com/docs/error-codes
- Errors from Stripe API: https://stripe.com/docs/api/errors
- Errors from subhub
- Errors from auth server

Exposing an error to the end user will need some UX input.  @johngruen can you help us with this?  (Bonus question: if a user is in a trial period, they aren't at a webpage, so.... I guess it goes via email?)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

The SDK we're using currently has some retry logic built in to it.  That, in addition, to Architecture 2.0 means we're good to close this.
