### ISSUE TITLE
'None connected' devices are presented on 'Devices & apps' list when you disconnect all your devices

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#889]
Environment:
Platform: Android, W10;
Build: Production, [Train 135];

Prerequisites:
You need to be connected only with one device.

Steps to reproduce:
1. Go to https://accounts.firefox.com/settings;
2. Tap on  'Show' button from the Device & apps line;
3. Tap on 'disconnect' button;

Expected result:
Your device is automatically disconnected and you are redirected to the login flow.

Actual result:
You can see a none-conected android iOS device on your list first to be disconnected.

Note:
- [video](https://drive.google.com/file/d/0B-OVCGyglYi_cmc4dHJYOGx6a2ktX2l6blRtUWNPU2I0Wms0/view?usp=sharing);
- If you are doing those steps from the desktop, you will see those devices on 'Devices & apps': 
![Screenshot_6](https://user-images.githubusercontent.com/40264165/56423552-494e9480-62b5-11e9-82e7-1d95ef29d7dc.png)

- @shane-tomlinson Those 'none-connected' devices are intended here? I can't find any information regarding those.

**Comment by vladikoff** [comment]
Yeah this is by design from @ryanfeeley, it urges users to download the mobile apps
