### ISSUE TITLE
Delay for confirmation emails on mailinator.com

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#890]
Windows 10, Android 5.0.2
Stage server Train 135

Steps to reproduce:
1. Create an account (mailinator.com - public inbox).
2. Send the verification email ( 2-3 times).
2. Go to inbox.

Expected results: "Confirm your email and start to sync" email is received in the inbox. 

Actual results: No email is received. Only after 1-2 minutes.

Notes: 
- Not reproducible with @mozilla.com.
- Not reproducible on production.

**Comment by clouserw** [comment]
We're not doing anything to slow mail down to mailinator.com.  It's likely either an issue with their servers, or some server inbetween.
