### ISSUE TITLE
The buttons from manage account overwrite on text if you select multiple sections

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#891]
Environment:
Platform: Android, W10;
Build: Production, [Train 135];

Prerequisites:
You are connected with a valid account.

Steps to reproduce:
1. Go to https://accounts.firefox.com/settings;
2. Tap on 'Show' button from the Device & apps line;
3. Quick after that, tap 'Change' button from the Communication preferences line;
4. Quick after that, tap 'Enable' button from the 2FA;

Expected result:
The change from a section to other section is smooth;

Actual result:
The changes from a section to other section make the buttons to overwrite on the text.
The loading of 2FA section is blocked.

Note:
- [video](https://drive.google.com/file/d/0B-OVCGyglYi_YU5Ma19SU1dqNTVuNy1mWGhkZkJ6YVZLb2RR/view?usp=sharing)

**Comment by clouserw** [comment]
This might get fixed with one of @johngruen 's PRs.  Meanwhile, we'll backlog it

**Comment by sv-sdeiac** [comment]
Due to the fact that the 'Communication preferences' was changed, I retried to reproduce this issue and I am not able anymore.
Devices:
- Xiaomi Mi 8 Lite (Android 9).

Build:
 - Firefox Nightly 68.1a1 (2019-07-26) - Stage server [Train 142] and production.

Due to my findings, I'll close this ticket, thanks.
