### ISSUE TITLE
Invalid parameter: redirectTo

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8921]
I've got an "Invalid parameter: redirectTo"  here lately. (highlighted in red) for a new registration at my self-hosting (docker). And the registration doesn't work either. What's wrong anymore?

thanks

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2322)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I don't know about this particular case, but this will probably get resolved with https://github.com/mozilla/fxa/issues/3673

**Comment by data-sync-user** [comment]
➤ misterhsp commented:

And what exactly can I do now to complete the registration for my self-hosting? I don't really understand that.

...

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
