### ISSUE TITLE
“System unavailable, try again soon” is displayed instead of “The image file size is too large to be uploaded.”

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8925]
**Note:**
This is a follow-up issue for #5976

**Build:**
Stage [Train 1.181.0]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**

1. Launch Firefox and login into fxa using a mozilla account.
1. Go to https://accounts.stage.mozaws.net/settings/
1. Click "Add" button from the Account picture area.
1. Upload this picture.
1. Zoom it to maximum.
1. Drag down the picture at maximum.
1. Click “Change” button.

**Expected results:**
“The image file size is too large to be uploaded.” message is successfully displayed.

**Actual Results:**
”System unavailable, try again soon“ error message is displayed.

![Screenshot](https://user-images.githubusercontent.com/18114210/88413532-08143100-cde4-11ea-89a5-1660dd0220af.png)UNITO-UNDERSCORE!20!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2346)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
