### ISSUE TITLE
Impossible to login using SeaMonkey browser

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8926]
Details how to reproduce see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1634973)

Continuation on github [thundernest #143](https://github.com/thundernest/addons-server/issues/143) .

Of course I would like to be able to use SeaMonkey Browser for login to maintain my Add-ons.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2320)

**Comment by data-sync-user** [comment]
➤ RainerBielefeld commented:

Works for SM if I use IE11 User Agent String.

That's really unfriendly.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
