### ISSUE TITLE
Remove use of ROW_COUNT() in updateRecoveryKey_1

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8927]
Running `npm migration-lint` in `fxa-auth-db-mysql` tells me:

```
Warning: ROW_COUNT() in updateRecoveryKey_1!
SELECT ROW_COUNT() INTO @updateCount;
```

But it doesn't remind me why this is a problem. Searching git history leads me to [Bug 1499819](https://bugzilla.mozilla.org/show_bug.cgi?id=1499819), wherein we discovered that using `ROW_COUNT()` can cause MySQL replication lag. I think we should change this query to avoid using `ROW_COUNT()` as a preventative measure.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2330)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
