### ISSUE TITLE
Ensure support for multiple products per subscription

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#893]
On the road to #719, it now looks like a subscription can grant the user multiple products - rather than one product per subscription as I assumed in PR #775. So, we'll need to account for that.

One route is to relax the unique key on subscription ID, so that there can be multiple user/subscription/product rows. Then, cascade that change down through all the related APIs.

**Comment by lmorchard** [comment]
FWIW, this may be a false alarm of an issue pending some review at the subhub level

**Comment by clouserw** [comment]
A subscription can map only to a single product.
