### ISSUE TITLE
Prompt for a 2FA code before disabling 2FA

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8931]
This came in via a mailing list, I couldn't find a definitive bug (not even a RESOLVED/FIXED one) on this topic so I figured I'd file it as a new issue.

From the submitter:

"""
After opening my Firefox account's settings ( https://accounts.firefox.com/settings ) I was able to disable two factor authentication
without providing my 2fa code first. This poses a security risk and is in direct violation of the OWASP Application Security Verification Standard 4.0 [p. 31 f., 1].

Please consider changing this behavior.
"""

In other words, this user expected that they would need to enter a 2FA code to confirm they are in control of the 2FA device, before they would be allowed to disable 2FA on the account.

I wasn't able to find the specific advice mentioned in the OWASP standard (the things on page 31 don't _seem_ related from my initial read) but I'll admit I didn't try super hard.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2355)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
