### ISSUE TITLE
Device details are not center aligned in Reset your password email using Gmail on mobile

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8937]
**Build**
Stage [Train 1.183.1]

**Affected platforms**
Android 9
iOS 13.6

**Steps to reproduce**

1. Go to Sign In Page and tap on "Forget password?".
1. Insert the email and click on "Begin reset".
1. Go to Gmail app and open "Reset your password" email.
1. Observe the email format.

**Expected results**
The Email content is correctly displayed.

**Actual Results**
Device details section is displayed as left aligned.

**Additional notes**
This issue was reproduced using the following devices: Moto G6 and iPhone 11; Google Pixel 3a.

Same issue for other emails too (Account recovery key generated, 2FA enabled, etc).

![width=200,height=183](https://user-images.githubusercontent.com/18114210/89770754-de5b4980-db07-11ea-82f7-d7da76cc3a7f.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2412)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
