### ISSUE TITLE
Build a simple test product

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#894]
We should have a simple dummy product we can use with Subscription Services to ensure it is working.  The same idea as 123done

**Comment by lmorchard** [comment]
FWIW, I'm considering extending 123Done to add a "pro" feature - e.g. make the logo sparkly or add a "pro" starburst badge, along with a link to subscribe

**Comment by shane-tomlinson** [comment]
>  I'm considering extending 123Done to add a "pro" feature - e.g. make the logo sparkly or add a "pro" starburst badge, along with a link to subscribe

I so want to kill 123done... But hey, for testing it works.

**Comment by lmorchard** [comment]
If that's the case, I could build something separate & simpler that does nothing but sign-in and shows subscription status for the demo product

**Comment by shane-tomlinson** [comment]
> If that's the case, I could build something separate & simpler that does nothing but sign-in and shows subscription status for the demo product

Depends, it's a good test bed for ideas & functional tests, just not great reference to point people at.

**Comment by lmorchard** [comment]
FWIW, [I made some quick tweaks to 123Done](https://github.com/lmorchard/fxa/commit/18cb962abddd7a302f7af253c11fc5dd51cafa50) for my demo in the subscription services meeting yesterday. Very quick, very dirty.

I've got a notion to slap a minimal amount of polish on that commit and call it a fix for this issue. We could file a follow-up for something simpler as a proper stripped-down reference app.
