### ISSUE TITLE
A support ticket can be sent while What are you contacting us about? field is empty

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8942]
#### Affected versions:
* All Firefox;

#### Affected FxA versions:
* 1.183.1

#### Affected Platforms:
* Windows 10 (64-bit)

#### Preconditions
* existent FxA account with active subscription;

#### Steps to reproduce
1. Go to https://accounts.stage.mozaws.net/support page;
1. Leave the **What are you contacting us about?** field empty and complete the rest of the form;
1. Click the **Send** button;

      1. Expected result:

* The **Send** button is not clickable, the ticket can't be sent;

#### Actual result:
* The ticket is sent having the **What are you contacting us about?** field empty.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2411)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
