### ISSUE TITLE
Remove Portal component (or cleanup)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8945]
Some tweaks were made for a11y improvements when `Modal` was created for Settings and `if (id === 'modal') {` conditionals were introduced. This has gotten messy especially with the `if (id !== 'alert-bar-portal') {` conditional, and DOM elements in React shouldn't be directly accessed like they are in this file (especially the DOM element children). This brings up the question of if `Portal` is needed at all - React portals typically use an empty div adjacent to the root ([see the HTML structure here](https://reactjs.org/docs/portals.html#event-bubbling-through-portals)) but `Portal` was originally created to inject and cleanup this temporary empty div and make `createPortal` more convenient. It _may_ have also been created to mitigate content server styles looking funky in payments.

As it is more conventional to place an empty div adjacent to the main app root div anyway, let's add `<div id="portal"></div>` to settings and payments and work through the components to keep the a11y wins while removing Portal (bonus points if those a11y wins are also transferred to `DialogMessage`). If it can't be removed because of content server styles in Payments, we can probably at least stop using it in Settings and remove the changes to accommodate Settings `Modal`/`AlertBar` fallback, but **be sure all the accessibility improvements stay in place.**

[https://mozilla-hub.atlassian.net/browse/FXA-5272](https://mozilla-hub.atlassian.net/browse/FXA-5272|smart-link): 

* Payments `AlertBar`

* Settings `AlertBar` but only as a fallback if #alert-bar-root isn’t present

Moved to spike above: combine/refactor `AlertBar` in Settings and Payments to become the same component-, but that's a separate issue that can't be done until- [-payments uses Tailwind-](https://jira.mozilla.com/browse/FXA-2276)~~)~~  This was moved from this ticket as the two components may not be shared.

[https://mozilla-hub.atlassian.net/browse/FXA-5273](https://mozilla-hub.atlassian.net/browse/FXA-5273|smart-link): 

`DialogMessage` and `Modal` can become the same component.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2463)

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

I think we should defer this and remove it from the Post-beta cleanup epic. It isn't directly related to post-beta and there's other higher priority work. It's a more general refactor task.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Whomever works on this should probably also work on and close https://mozilla-hub.atlassian.net/browse/FXA-5117 ( https://mozilla-hub.atlassian.net/browse/FXA-5117|smart-link ) / #12922 at the same time since it’s all related. I’m not adding it to the Upgrade React-related Dependencies epic since it’s not technically related to or blocking anything there.

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Portal blocks the React dependency upgrade because it is causing the following CI error:

is not clickable at point (1004,814) because another element <body class="overflow-hidden">

overflow-hidden should not be added to body , only the sibling divs of the Portal component.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
