### ISSUE TITLE
No dark theme in https://accounts.firefox.com/

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8953]
¡Hola!

Please implement a dark theme for https://accounts.firefox.com/ and use it when a dark theme is in use in Firefox or the system settings.

Logging into a Firefox Account at night is hurtful to retinas.

¡Gracias!
Alex

- - -
:beetle: Issue is synchronized with Bugzilla [Bug 1661218](https://bugzilla.mozilla.org/show_bug.cgi?id=1661218)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2482)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Marking needs product

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for the suggestion.  I'd like to have a dark theme too!  

Unfortunately, this isn't on our roadmap and we won't have time to implement it in the foreseeable future so I'm going to close the issue.

**Comment by pdehaan** [comment]
Got another user request for dark mode as switching from dark mode on [redacted] site to the checkout process takes you to a light page.
