### ISSUE TITLE
[payments] Allow Only One Expansion of Subscription Management Panel at a Time

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8958]
This is sort of a follow-up to FXA-2442.

As long as we allow the customer to expand multiple subscription management panels to perform actions on them, we'd run into race conditions.  FXA-2442 fixes the scenario of canceling multiple subscriptions.  But the customer could still cancel a subscription and resubscribe to another "simultaneously".

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2497)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

John Gruen what do you think?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

John Gruen - any objections?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
