### ISSUE TITLE
AlertExternal does not use desired ref

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8966]
When you trigger an AlertExternal render it is not mounting to the root ref that is passed down through AlertBarContext. This results in it mounting to a new Portal and yields the error:

`Attempted to mount AlertBar on element ID "alert-bar-root" but it was not found in the document`

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2505)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
