### ISSUE TITLE
Old password field is not validated inline

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8969]
**Build**
Stage [Train 1.189.0]

**Affected platforms**
Windows 10 x64 

**Steps to reproduce**

1. Launch Firefox and login using an existing account.
1. Navigate to Settings page.
1. Click Change on the Password line.
1. Enter a password shorter than 8 characters in “Old Password” field.

**Expected results**
“Must be at least 8 characters” error is displayed.

**Actual Results**
“Incorrect password” error is displayed only after clicking on the “Change” button.

![issue14](https://user-images.githubusercontent.com/18114210/94557511-55d76a80-0267-11eb-8895-ad60d25d24c5.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2583)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15027/gif16.gif">gif16.gif</a>

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is also applicable in the New Settings page.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
