### ISSUE TITLE
Generate types from gql instead of duplicating

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8971]
https://www.leighhalliday.com/generating-types-apollo

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2573)

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

This was brought up in an fxa-settings review https://github.com/mozilla/fxa/pull/6537#discussion_r493963757

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
