### ISSUE TITLE
Don't hide Mozilla logo in footer on mobile

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8976]
We have a Mozilla logo in our footer but it gets hidden on mobile. This is not great for the Mozilla VPN on mobile. (even if not everyone will necessarily see it)

See screenshots:
!image-2020-09-22-10-42-13-174.png!

!image-2020-09-22-10-42-24-378.png!

CC [~accountid:60482f052b3f9a006a3b7147] & [~accountid:6047c7a8addbcd006ba89c4d]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2564)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/14795/image+(3).png">image (3).png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14794/image+(4).png">image (4).png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14793/image-2020-09-22-10-42-13-174.png">image-2020-09-22-10-42-13-174.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14792/image-2020-09-22-10-42-24-378.png">image-2020-09-22-10-42-24-378.png</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
