### ISSUE TITLE
Discontinue FxA Send Tab Events in Amplitude?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8980]
[~accountid:60482ca32b3f9a006a3b5522] recently walked me through Send Tab metrics and we noticed that what FxA is tracking is at least [10x smaller](https://analytics.amplitude.com/mozilla-corp/chart/new/buakkhg) than what she is tracking on the client-side.

Rather than fix the metric on our end, I was wondering if we should just kill it? Reasons:

* I am not getting lots of value out of it.

* It's a proxy metric since it just sees tab transiting and not whether users received them.
* It's not the source of truth for the Sync team.
* Normally AET will provide better coverage for this.

Thoughts?

CC [~accountid:60482d8cd7f56e00719a7fb9] [~accountid:60482cc3addbcd006bacfcfe]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2597)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
