### ISSUE TITLE
Document restmail behavior

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8991]
We have some special case code to allow restmail-based testing of certain flows. We should document this somewhere, at least for devs and QA.

ref: https://mozilla.slack.com/archives/CLV3KMZ8B/p1602257563319500

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2612)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

@6a68 This isn't documented as far as I can tell.

> We should document this somewhere, at least for devs and QA.

Agreed, in general we could have a some testing section that tells how you to force certain things locally, 2FA required, sign-in code, unverified sessions etc.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
