### ISSUE TITLE
Make all the github/travis bots chatter in their own separate channel

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#9]
The chatter in `#fxa` is useful but it often makes it hard to maintain human-to-human-conversations.  We should make a separate `#fxa-bots` or `#fxa-chatter` or something channel for them to talk into.

**Comment by chilts** [comment]
Is it as easy as just "/join #fxa-bot" or does the channel need to be registered somewhere?

**Comment by seanmonstar** [comment]
No need to register, unless you wish for the room to exist when empty, or to op people. If it disappears cause everyone leaves, it will be recreated upon first entry.

**Comment by rfk** [comment]
Mostly we just need to pick a name, and redirect all our travis/github integrations to use it.  I `/join`ed `#fxa-bots` so it'll be hanging out there ready for them to use.

**Comment by chilts** [comment]
Done:

* [x] fxa-auth-server
* [x] fxa-auth-db-server
* [x] fxa-auth-db-mem
* [x] fxa-auth-db-mysql
* [x] fxa-customs-server
* [x] fxa-auth-mailer
* [ ] fxa-oauth-server
* [ ] fxa-profile-server
* [ ] fxa-content-server
* [ ] fxa-js-client
* [ ] fxa-relier-client
* [ ] any others ...

**Comment by pdehaan** [comment]
Thanks @chilts!
I did the remaining repos from your checklist, and looks like all but 4 have been merged.
I didn't see any more fxa-* repos on https://github.com/mozilla?query=fxa-&utf8=%E2%9C%93 that have .travis.yml files and post to #fxa IRC channel. But if I see any Travis spam in #fxa we can investigate.

Imma gonna close this out.

**Comment by chilts** [comment]
Thanks for doing the rest @pdehaan. :)
