### ISSUE TITLE
"Create a Firefox Account" password field has 2 show/hide "eye" icons

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9000]
#### Affected versions:
* Edge - version 86.0.622.58; 

#### FxA version:
* 1.192.0;

#### Affected Platforms:
* Windows 10 x64;

#### Steps to reproduce:
1. Open FxA Stage page using Edge;
1. Create a new account;
1. Type a password and observe the eye “hide/show” button; 

#### Expected result:
* There is one “eye”- button at the end of each password field.

#### Actual result:
* There are two “eye”- buttons at the end of each password field.

#### Notes:
* only reproducing on Edge;
* Same issue for all password fields;
![width=200,height=183](https://user-images.githubusercontent.com/15685960/97717031-ff12ba00-1acc-11eb-825c-11213ae41bdc.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2663)

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Edge add their own reveal button. I guess we should hide ours in that case???

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
