### ISSUE TITLE
Remove BrowserID-related code and endpoints once traffic declines sufficiently

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9007]
As of Firefox 80, we expect all our major clients to have moved away from BrowserID and instead be using OAuth to access all account-related services. The next step in deprecating BrowserID is to wait for traffic from legacy clients to subside, then remove the BrowserID-related code from the FxA server.

First, we'll need to confirm that traffic using these routes has reached a sufficiently low level. Something like:

* Setup monitoring for traffic to the `/certificate/sign` endpoint, broken down by user-agent and version.
* Confirm that we're not seeing significant traffic from Firefox versions >= 80.
* Wait for the next Firefox ESR, which will include the new OAuth-based sync code from Firefox 80.
* Decide on an appropriate traffic threshold below which we'll disable the `/certificate/sign` route.
* Wait for traffic to drop below that threshold.

Once we're happy that there's a sufficiently low level of BrowserID-related traffic, we can remove the code including:

* Remove the [ability to trade a BrowserID assertion for an OAuth token](https://github.com/mozilla/fxa/blob/f8e61777e098f4aa9bf48918670f29058efe775e/packages/fxa-auth-server/lib/oauth/assertion.js#L114), and decomission the local instance of [`browserid-verifier`](https://github.com/mozilla/browserid-verifier/) that we currently run to support this.
* Remove the [`/certificate/sign` route](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/routes/sign.js) and the [`signer` module](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/signer.js) on which it depends.
* Remove the [`/.well-known` support routes](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/routes/idp.js) for being a BrowserID IdP.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2715)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/19265">image-20220112-222708.png</a>

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Leaving this out of the triaged pile so we can talk about it at our next team meeting

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It looks like we keep a year of data, so, I did a query for the past year and we are down to about 9r/s now.  I don’t see a way to break down by version though so I’ll ask for help.  Here is the current graph:

!image-20220112-222708.png|width=1493,height=492!

Jon Buckley are you able to get the versions out of the logs?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Yeah, I think we could do that with a query like:

SELECT jsonPayload.fields.path, jsonPayload.fields.agent, COUNT(*) FROM `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20220113` WHERE jsonPayload.fields.path = '/v1/certificate/sign' GROUP BY 1, 2 ORDER BY 3 DESC;

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Perfect!  Thanks Jon Buckley 

This is the query I ran, which covers all of 2022 (the past 2 weeks):

SELECT 
    jsonPayload.fields.path, 
    jsonPayload.fields.agent, 
    COUNT(*) 
FROM 
    `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_202201*` 
WHERE 
    jsonPayload.fields.path = '/v1/certificate/sign' 
GROUP BY 1, 2 ORDER BY 3 DESC
LIMIT 1000And the top 50 results are at https://docs.google.com/spreadsheets/d/1KdShbCm-G15nUQQngpg0BjjmkBPlvjG6dchym7Sj7Rk/edit#gid=0 ( https://docs.google.com/spreadsheets/d/1KdShbCm-G15nUQQngpg0BjjmkBPlvjG6dchym7Sj7Rk/edit#gid=0|smart-link ) 

The current release of Firefox is 96 and the ESR version is 91.5.  So, these are definitely all old and pre-80, as expected.  I’m trying to determine how often a browser would hit that endpoint in a normal day.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I’m working with David Durst on this.  It sounds like there are some things on the Push side to remove before we do this as well as getting Product approval for the whole plan.  So, TBD.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Noting here: we are continuing support for BrowserID with the upcoming Rust-based Tokenserver until we see continued use below the 100K barrier.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

June update:  We’re still not near the 100k barrier.  Still working on an auto-updating dashboard/spreadsheet but for now we run manual queries.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Numbers @ https://docs.google.com/spreadsheets/d/17oLiQe8XWnf-Vr0dDSOsUnAfXDhcbuNqyzdtXf74IMk/edit#gid=0 ( https://docs.google.com/spreadsheets/d/17oLiQe8XWnf-Vr0dDSOsUnAfXDhcbuNqyzdtXf74IMk/edit#gid=0|smart-link ) .  Thanks Durst

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
