### ISSUE TITLE
[L10n] The 'Done, recovery key saved' from Account recovery is not entirely visible on German language

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#901]
Build: Release 66.0.2;
Devices:  iPhone SE	(12.1.4);

Prerequisites:
Your FF is set on German (Deutsch) language;

Steps to reproduce:
1. Go to https://accounts.firefox.com/settings;
2. Tap on the 'Enable' button from the Account recovery line;
3. Tap on 'Generate' and write your password;
4. Tap on 'Continue';

Expected results:
The 'Done, recovery key saved' button is entirely visible and translated;

Actual results:
The 'Done, recovery key saved' button is translated but is not entirely visible;

Note:
- [screenshot](https://drive.google.com/open?id=0B-OVCGyglYi_eUk0UDFZbEgyUlpxU0JXS3ZtQldKM0JvQkRr)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-818)
┆Issue Number: FXA-818

**Comment by clouserw** [comment]
@ryanfeeley -- is there a shorter phrase we could use?

@flodolo -- is there a shorter word we can use in German?

**Comment by flodolo** [comment]
@peiying2 is in charge of localization for this project, I'll let her handle it

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Settings has been redesigned since this issue was filed so closing this.
