### ISSUE TITLE
[settings] "Unit Row" Buttons Should Allow Unique data-testid Attribute Values

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9012]
The ModalButton in UnitRow has a hard code data-testid.

Also, usually the `prefixDataTestId` prop isn't used, so all the "unit rows" have duplicated data-testid attribute, making (functional) tests more difficult to write.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2763)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Wil Clouser, Chelsea Lewis : if you are looking for new settings phase II issues to trim, this is a good candidate.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
