### ISSUE TITLE
[FxA-Settings] “X” menu button displays an incorrect focus border

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9014]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Android 9
Windows 10 64-bit

**Steps to reproduce**

1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
1. Tap on Menu button.
1. Observe the “X” button focus border.

**Expected results**
The focus border only encompasses the “X“ button.

**Actual Results**
The focus border encompasses also an empty space from the right side of the “X” button.

![Screenshot](https://user-images.githubusercontent.com/18114210/100369977-44fc6880-300e-11eb-8aa0-e8d81031c9d4.png)UNITO-UNDERSCORE!45!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2742)

**Comment by data-sync-user** [comment]
➤ Chinmay Mehta commented:

Hey vasilicatamas  can I try this .?

**Comment by data-sync-user** [comment]
➤ Saloni Gupta commented:

Hey, can I work on this?

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

chinmaym07 @shades-7 Apologies for such a late response! I just double checked and this is still a valid issue:

https://user-images.githubusercontent.com/13018240/112687257-3baccc80-8e45-11eb-976d-6cf87d519c40.png

Please feel free to work on it and open a PR if one of you is still interested. You can find this screen by running FxA locally, navigating to beta/settings, viewing the page in mobile or tablet width, and tabbing to it.

**Comment by data-sync-user** [comment]
➤ Saloni Gupta commented:

LZoog i am interested

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

@shades-7 I've assigned you, thanks! 😀

**Comment by data-sync-user** [comment]
➤ Saloni Gupta commented:

LZoog hey, can you help me in locating the file where changes need to be done?
Thank you.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

@shades-7 This change should be made to the button element found here: https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/HeaderLockup/index.tsx#L22:L41

**Comment by data-sync-user** [comment]
➤ Saloni Gupta commented:

jodyheavener Thank you

**Comment by data-sync-user** [comment]
➤ dhruva248 commented:

jodyheavener Can I help solving this issue if there has been no action yet or any help is needed?

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Hey @shades-7, just following up here. Are you currently working on this? 🙂

**Comment by data-sync-user** [comment]
➤ Saloni Gupta commented:

> Hey @shades-7, just following up here. Are you currently working on this?

yes will send the PR soon

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
