### ISSUE TITLE
[FxA-Settings] The current password value is removed if typing an incorrect password

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9019]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**

1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
1. Click on the "Change" button displayed on the "Password" section.
1. Insert an incorrect password in the current password field.
1. Type a valid password in the new password fields.
1. Click “Save” button.

**Expected results**
The current password field remains filled and an “Incorrect password” error is displayed.

**Actual Results**
The current password is erased and the “Incorrect password” error points to an empty field.

**Additional notes**
This issue also reproduces for password field from Recovery key page.

![Screenshot](https://user-images.githubusercontent.com/18114210/100437207-1bdce600-30a9-11eb-8879-e78acf9e91ec.png)UNITO-UNDERSCORE!50!
![Screenshot](https://user-images.githubusercontent.com/18114210/100437213-1ed7d680-30a9-11eb-9ff6-2a125413100b.png)UNITO-UNDERSCORE!51!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2751)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is this a functionality change with the new settings pages?  I thought this was a security feature.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

The "current password" field from the new settings page behaves differently compared to the "current password" field from the old page.

Screenshot!UNITO-UNDERSCORE!58 ( https://user-images.githubusercontent.com/18114210/100858293-78b81200-3496-11eb-9b77-2cb19dbaca16.png )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
