### ISSUE TITLE
[meta]L10n issues for FxA flow

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#902]
Build: Release 66.0.2;
Devices: iPhone SE	(12.1.4);

Prerequisites:
Your FF is set on French (Français) language;

Steps to reproduce:

1. Go to https://accounts.firefox.com/settings;
2. Tap on the 'Enable' button from the Account recovery line;
3. Tap on 'Generate' and write your password;
4. Tap on 'Continue';

Expected results:
A green pop-up is displayed with the text 'Account recovery enabled' in French;

Actual results:
The 'Account recovery enabled' pop-up is not translated;

Note:
- Also, when you disable the account recovery key, the pop-up is still not translated;
- screenshot [enabled ](https://drive.google.com/open?id=0B-OVCGyglYi_Z3lWQVI1amRoRXdtdU45dkZ6dDdSRjdZQzN3)and  [disabled](https://drive.google.com/open?id=0B-OVCGyglYi_SnJNTzBKUzZSOXhQMnVnSnNfT01sMHpfX2dF)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-819)
┆Issue Number: FXA-819

**Comment by SorinaFlorean** [comment]
Manage account page is not translated in Indian Gujarati / ગુજરાતી. All the options are in English. 
@shane-tomlinson  Should we file a new bug or this will be fixed by this one?

**Comment by shane-tomlinson** [comment]
> Manage account page is not translated in Indian Gujarati / ગુજરાતી. All the options are in English.

The entire page is not translated? If so, that sounds like we might not have the locale enabled.

**Comment by SorinaFlorean** [comment]
We made a folder to keep track of all l10n issues: https://drive.google.com/open?id=19aw-K5vResrSOTP8kgZfqZoxi79LoEO3. 

We found also for Catalan (not translated):
- remember password? Sign in
- Account recovery name and content
- 2FA - replace recovery codes/ info about the option
- Delete account GDPR
- password tooltip
- disconnect account message

For RTL languages:
- "Terms of Service" and "Privacy Notice" pages.
- Password field: the eye icon is placed with password content on the left side of the field.
- "Revoke" button is displayed on the grey key.

Common Password page from password tooltip/Account recovery article is not translated either. 

We will continue with the testing, and update the folder/leave comment here. Thanks!

**Comment by SorinaFlorean** [comment]
> > Manage account page is not translated in Indian Gujarati / ગુજરાતી. All the options are in English.
> 
> The entire page is not translated? If so, that sounds like we might not have the locale enabled.

Yes, the entire page is not translated. We will check to see if other languages are affected too.

**Comment by clouserw** [comment]
Thanks for filing this.  Once a locale is enabled, we generally don't disable it, even if it gets behind on translations.  You can see how complete each locale is at https://pontoon.mozilla.org/projects/firefox-accounts/ (eg. Catalan, mentioned above, is only 50% translated)

I'm going to close this issue as it's kind of a mix of different issues, but I think the incomplete translations addresses most of what is here.
