### ISSUE TITLE
[payments] react-stripe-elements called before Stripe.js is loaded

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9023]
From https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/10024443/

> Error: Please load Stripe.js (https://js.stripe.com/v3/) on this page to use react-stripe-elements. If Stripe.js isn't available yet (it's loading asynchronously, or you're using server-side rendering),  ...

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2726)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Note that we are not loading Stripe.js async.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/11391063/?query=is%3Aunresolved

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

https://sentry.prod.mozaws.net/operations/fxa-payments-prod/?query=Please+load+Stripe.js ( https://sentry.prod.mozaws.net/operations/fxa-payments-prod/?query=Please+load+Stripe.js )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
