### ISSUE TITLE
Investigate ECONNRESET errors talking to pushbox

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9024]
There is [a sentry issue](https://sentry.prod.mozaws.net/operations/auth-prod/issues/10024262/?query=is%3Aunresolved) for `EndpointError: pushbox.services.mozilla.com:443 error: read ECONNRESET` . @Micheletto has solved this for sync which also runs in GCP, so I'll see if I can follow the same steps he did to fix this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2775)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
