### ISSUE TITLE
[FxA-Settings] Incorrect last access value of the current device in “Connected Services” list

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9027]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10 64-bit
iOS 13.6
Android 9

**Steps to reproduce**

1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
1. Go to Connected Services Section.
1. Check the last access value of the current device.

**Expected results**
“Active now” status is displayed for the current device - as per [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792).

**Actual Results**
Last access value of the current device is measured in minutes as for the other Firefox instances.

![Screenshot](https://user-images.githubusercontent.com/18114210/100087236-1a1be400-2e57-11eb-85d0-52b9f4937e4f.png)UNITO-UNDERSCORE!20!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2729)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
