### ISSUE TITLE
Add state summary capability for settings sections

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#903]
While the layout is not yet ready, we will want to show a summary of the state of each settings section.

* Account picture
Set / Not set
* Display name
Ryan Feeley / Not set
* Secondary email
secondary@email.com / **Verification required** (likely in red) / Not set
* Account recovery
Configured / Not configured
* Two-step authentication
Configured / N recovery  codes remaining / Not configured
* Devices & apps
0 clients connected / 1 client connected / 2 clients connected / etc.
* Communication preferences
Subscribed / Not subscribed
* Password
Last changed 41 days ago / Never changed
* Delete account
Created December 3, 2017

Will likely be styled like this:
![image](https://user-images.githubusercontent.com/68213/56256402-8db01980-6096-11e9-84a8-1881d89488c8.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-820)
┆Issue Number: FXA-820

**Comment by clouserw** [comment]
We've redesigned the settings site
