### ISSUE TITLE
merge auth-server lib/oauth/validators into lib/routes/validators

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9030]
copy exports from the oauth impl into lib/routes/validators.js and update dependent imports

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2792)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
