### ISSUE TITLE
merge lib/oauth/error into lib/error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9035]
copy oauth-server errors into lib/errors, check for conflicting errnos, update the AppError.translate function and update imports

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2797)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
