### ISSUE TITLE
fxa-email-service: __heartbeat__ test fail on Circle

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#904]
See https://circleci.com/gh/mozilla/fxa/9304#artifacts/containers/5

`curl -s -o /dev/null --silent -w '%{http_code}' http://127.0.0.1:8001/__heartbeat__`

It tries 12 times and then gives up.

cc @philbooth and @jrgm

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-821)
┆Issue Number: FXA-821

**Comment by shane-tomlinson** [comment]
Blocks https://github.com/mozilla/fxa/pull/900

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

This no longer is occurring.
