### ISSUE TITLE
Use direct db call for loading session tokens in auth-server

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9040]
With a full session token implementation and db call in fxa-shared, auth-server should use that to load the session token instead of its auth-db-mysql call.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2827)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
