### ISSUE TITLE
Document learnings from GraphQL implementation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9042]
Let's document some of our learnings with the implementation of graphql, especially with regard to security operations learnings. Suggest partnering with [~accountid:6047cbd9ad0d2e0068412955] and [~accountid:557058:7bda658f-14bb-4099-ab71-2b705aa15e99] to document Operations learnings.

Hopefully this will be beneficial to teams outside of Firefox Accounts if and as they plan to leverage GraphQL in the future.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2790)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
