### ISSUE TITLE
Refactor redis class into fxa-shared

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9043]
To support use of Redis and caching between apps, it would be good to have our primary redis class we use in fxa-shared.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2829)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
