### ISSUE TITLE
[FxA-Settings] Recovery Key "data block" lacks notification

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9047]
## Description
Within the flow of creating a recovery key, when user clicks on the “data block” of the recovery key there is no notification. “Key copied!” notification should appear.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2835)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
