### ISSUE TITLE
[FxA-Settings] Main Navigation should "float"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9049]
## Description
Main Navigation should “float,” eg be visible as one scrolls down, and when one uses the anchor links (clicks on categories that will jump user within the page). Right now the main nav is locked to top of page and user loses access to it lower in the page, requiring scrolling back up.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2837)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
