### ISSUE TITLE
[FxA-Settings] Firefox accounts shoulk link to "home"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9050]
## Description
Describe the issue that you're seeing.
When one is on a form page, clicking LOGO Firefox accounts in top left corner currently does not link to "home, e.g. top of Profile section. Should take user "home," effectively functioning as cancel.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2838)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
