### ISSUE TITLE
[FxA-Settings] Two step auth title should be sentence case

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9052]
## Description
Currently, when user clicks "add," following pages (steps) title shows incorrect casing —Two step authorization" should be sentence case and not camel case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2839)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
