### ISSUE TITLE
[iOS] Device & apps list shows "Web session" for sign in via Email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9053]
### Steps to reproduce
1. Open Firefox
1. Tap "Sign in" from the hamburger menu
1. Type the received sign in code
1. Check the Device & apps list from Account management page

### Expected result
* Device & apps list shows only the current device.
    1. Actual result
* Device & apps list shows "Web session" and current device
    1. Environment
* iPhone XS (14.0)
* Firefox iOS 30.0 (3297)
    1. Note:
* Reproducible only on iOS

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2889)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
