### ISSUE TITLE
Rename DirectStripeRoutes to DirectSubscriptionRoutes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9065]
Code clean-up issue.

We're adding PayPal Support. So the new paypalHelper is going on the the class DirectStripeRoutes.

Renaming DirectStripeRoutes -> DirectSubscriptionRoutes will make things clearer moving forward.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2894)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
