### ISSUE TITLE
chore(deps): bump all sinon versions to the latest

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9091]
We are using multiple versions of sinon within the monorepo.  Let's update it so the latest is used everywhere.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2961)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

As of today:

% yarn why sinon
├─ fxa-auth-server@workspace:packages/fxa-auth-server
│  └─ sinon@npm:9.2.3 (via npm:^9.0.3)
│
├─ fxa-content-server@workspace:packages/fxa-content-server
│  └─ sinon@npm:4.5.0 (via npm:4.5.0)
│
├─ fxa-customs-server@workspace:packages/fxa-customs-server
│  └─ sinon@npm:9.2.3 (via npm:^9.0.3)
│
├─ fxa-geodb@workspace:packages/fxa-geodb
│  └─ sinon@npm:9.2.3 (via npm:^9.0.3)
│
├─ fxa-payments-server@workspace:packages/fxa-payments-server
│  └─ sinon@npm:9.2.3 (via npm:^9.0.3)
│
├─ fxa-profile-server@workspace:packages/fxa-profile-server
│  └─ sinon@npm:9.2.3 (via npm:^9.0.3)
│
├─ fxa-react@workspace:packages/fxa-react
│  └─ sinon@npm:9.2.3 (via npm:^9.2.3)
│
└─ fxa-shared@workspace:packages/fxa-shared
   └─ sinon@npm:9.2.3 (via npm:^9.0.3)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
