### ISSUE TITLE
chore(dep): upgrade to webpack 5

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9094]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2964)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Failed dependabot: https://github.com/mozilla/fxa/pull/12430 ( https://github.com/mozilla/fxa/pull/12430|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
