### ISSUE TITLE
[Sentry] Mask / Clean up URL query params and fragment in breadcrumbs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9095]
"... the browser JavaScript SDK will automatically record all location changes." per Sentry docs.  Sometimes we don't want all parts of the location in the breadcrumbs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2965)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
