### ISSUE TITLE
Maybe we should remove fortress

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9099]
We made https://github.com/mozilla/fxa/tree/main/packages/fortress to demonstrate an easily skinned subscription flow and one that wouldn't block on test failures, as I recall.

I think 123done has the same subscription functionality in it and I don't think we have a need for Fortress anymore.  

Anyone have other reasons to keep it around?  [~accountid:5e3400fb6bd5c40ca395d189] [~accountid:5bc74a61450d3b45135743c1]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2983)

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

It's been useful having two relying parties to test the paypal checkouts with. We may want to keep this around

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage:  What's useful about having two parties with paypal?

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

It's very minor, but it's nice to be able to run through the complete flow twice, without having to create and validate a new account.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

Also, I wouldn't have been able to test this error without 2 relying parties https://github.com/mozilla/fxa/pull/7771

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

An alternative to using Fortress, what I used to manually test https://github.com/mozilla/fxa/pull/7771 ( https://github.com/mozilla/fxa/pull/7771 ) was another fake productId and planId from the Stripe DEV server dashboard. You do have to manually assemble the link though, e.g. in local development:

http://localhost:3031/products/<productId>?plan=<planId>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

From triage: we're agreed we can remove this

**Comment by data-sync-user** [comment]
➤ Mill Soper commented:

I looked through this with help from Benjamin Bangert , and while we can remove fortress from the codebase pretty easily, it does still seem to be in use by depending parties that want to integrate into subplat (and is recommended in our documentation ( https://mozilla.github.io/ecosystem-platform/relying-parties/tutorials/integration-with-subscription-platform#demoing-subscription-flows ) for this purpose.) Removing it will require further discussion, and it might be preferable to instead update it. As such we’re reassigning it to subplat and moving it out of our current sprint.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
