### ISSUE TITLE
chore(deps): bump mocha to > 10.0.0

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9104]
It looks like the content-server frontend mocha tests need changes

from #7398

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2980)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Most recent failure was https://github.com/mozilla/fxa/pull/13153 ( https://github.com/mozilla/fxa/pull/13153|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
