### ISSUE TITLE
Terms of Service and Privacy Notice links are opening in the same tab

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9107]
#### Build
Stage [Train 1.200.0]

#### Affected platforms
Windows 10 x64

#### Steps to reproduce
1. Open the Mozilla VPN page and click the **Try Mozilla VPN** button.
1. In the **Set up your subscription** page click the **Terms of Service** and **Privacy Notice** 

#### Expected results
Both links are open in a new tab

#### Actual Results
The links are open in the same tab, the user is redirected from the Set subscription page

![termsLinksSetSubPage](https://user-images.githubusercontent.com/15685441/108198564-745dd580-7124-11eb-9c20-3bf6e22ef210.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3049)

**Comment by data-sync-user** [comment]
➤ samaksh02 commented:

hey madalincm  i would like to work on the issue.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
