### ISSUE TITLE
Privacy page is showing markdown anchor links

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9108]
The [privacy notice in production](https://accounts.firefox.com/legal/privacy) looks fine, and was last updated April 8, 2020.

The [privacy notice on stage](https://accounts.stage.mozaws.net/legal/privacy) is showing markdown anchor links and the content was last updated Sep 8, 2020 (which is current for the legal docs).

I think this is a bug on the FxA side though because if you [look at old copies of the privacy notice](https://github.com/mozilla/legal-docs/blob/38fe731fb830777e695986e0960f2ea2375410e6/firefox_privacy_notice/en-US.md) it had those anchors in it, and since they aren't showing up in production at the time of filing, we must have been ignoring them somehow.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3035)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16462">PNToS.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/14833">Screenshot_2021-02-11 Firefox Accounts Privacy Notice.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/14832">Screenshot_2021-02-11 Privacy Notice.png</a>

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

The initial issue is ALSO reproducible for Terms of Services page ( https://accounts.stage.mozaws.net/legal/terms ) in FxA Stage Train 215. 

Both PN ( https://accounts.firefox.com/legal/privacy ) and ToS ( https://accounts.firefox.com/en/legal/terms ) pages have the same issue in Production - FxA Train 214.

See below screenshots.

!PNToS.png|width=721,height=881!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Hello,

Anna Sobiepanek , we noticed that the issue that Valentina mentioned in the following comment: https://mozilla-hub.atlassian.net/browse/FXA-2550?focusedCommentId=525524 ( https://mozilla-hub.atlassian.net/browse/FXA-2550?focusedCommentId=525524|smart-link ), which was tracked in a separate one, was canceled as a “Duplicate” for this issue.

Could you please let us know if the fix for this issue will also include a fix for the “{: #markup }” strings displayed in the PN link from subscription emails.

Thank you!

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Seeing the {:datetime} {#someID} in the pdf is still an outstanding issue.

**Comment by data-sync-user** [comment]
➤ Gene Wood commented:

I encountered this today when I went to point someone to our privacy notice, only to find that it was malformed. I’d say this warrants fixing as it’s clearly broken and live on the site.

https://accounts.firefox.com/legal/privacy ( https://accounts.firefox.com/legal/privacy )

https://accounts.firefox.com/en/legal/terms ( https://accounts.firefox.com/en/legal/terms )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
