### ISSUE TITLE
Would like to control the "Continue to download" button text and href

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9109]
## Description
Would like to control the "Continue to download" button text and href. (Maybe via Stripe product metadata)

### Steps to reproduce
1. Create a new product in Stripe (e.g., https://dashboard.stripe.com/test/products/prod_IyCWnXUbkYjDgL)
1. Link to the payment flow for that product
1. Enter test payment data in the form
1. Scroll to the bottom of the Thank You page

### Expected result
Click "Continue to Mozilla One" takes me to a "Mozilla One" dashboard url.

### Actual result
Click "Continue to download" takes me to mozilla.org

### Environment
What browser and operating system are you using?
Firefox 87.0a1 (2021-02-18) (64-bit)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3065)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
