### ISSUE TITLE
[settings][l10n] Use page locale not browser locale for password created date

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9111]
The Profile component has a localized string for the user's password's creation date.  However it is using the default browser locale, not the locale for the page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3041)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
