### ISSUE TITLE
Email first form redirects with sync link

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9113]
## Description
I can login without distraction or am provided a helpful tip if we believe something is wrong.
submitted by: Alex Davis

### Steps to reproduce
* iOS 14.2
* Navigate directly to accounts.firefox.com/beta/settings
•	Encounter the email-first login form

### Expected result
I can login without distraction or am provided a helpful tip if we believe something is wrong.

### Actual result
We display “Looking for Firefox Sync? Get started here.”

That page will just link back to the email-first form so it’s an endless (UX) loop.

### Environment
iOS 14.2
[rbillings: I was unable to repro on MacOS or Android]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3014)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Per Alex Davis this is happening on mobile and desktop as well.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
