### ISSUE TITLE
Add alertTextExternal test for PageChangePassword and PageRecoveryKeyAdd

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9117]
It's seeming a little complicated to integrate reactive variables into our cache mocks, which is necessary in some cases to test the alertTextExternal behavior in #7593.

Deferring the alertTextExternal verification test for the PageChangePassword and PageRecoveryKeyAdd components. This behavior can be easily verified in end-to-end testing, and we can pick this up after we get the big release out.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3075)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
