### ISSUE TITLE
Alt text for .circledCheck  is unhelpful and not localized

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9119]
https://github.com/mozilla/fxa/blob/7978db0eb1cb288580bf51134a079ac0e49ea476/packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx#L63

We should either 1.) make this text more descriptive and localize it or 2.) Hide this image from screen readers since it could be considered decorative and non-essential.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3047)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
