### ISSUE TITLE
Restore localization in PageChangePassword render test

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9125]
In order to get storybook builds working again, I've removed the localization bits from the PageChangePassword test.

This is a bug to figure out how to integrate localization into storybook for fxa-settings, starting with the PageChangePassword test.

Followup from #7343.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3029)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
