### ISSUE TITLE
[subplat] Support Multiple Locales in Product/Plan Metadata

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9128]
UPDATE EDIT: I verified locally that the locale support does work for the product details on the subscription creation page.  It'd still require an exact match on the first requested language (i.e. 'fr' wouldn't work if the user requested 'fr-FR').  The bug I noticed was within the context of emails, where the list of language appeared to be passed in differently (string vs. array).

If we wish to support multiple languages in the same pricing plan, we should support multiple locales in the product/plan metadata.

There is already code that tries to provide some basic support on this but it does not work due to a bug.  (At least that's the case when I tried it.)  It also requires exact matches between the requested language and the supported language, e.g. 'en-US' will only work if the user asked for 'en-US' as the first language in the list, and will not match 'en-us', 'en', en-CA', etc.

At the very least we should fix the existing bug so that the simple, exact match will work.  But preferably it should work with a prioritized list of languages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3132)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/14942">image-2021-03-04-16-13-33-736.png</a>

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

!image-2021-03-04-16-13-33-736.png!

I attached an image to demo where the metadata is currently used.  The content in the bullet points and "Full-device VPN" are from the product/plan metadata.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

The priority of improving how we localize Stripe metadata will likely increase as we add more products, more supported countries/locales and more customization options (e.g. FXA-3589). FXA-3161 is an example of the current process.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

It's questionable whether we will be able to handle this all in metadata, Stripe has a limitation of 50 keys, key names up to 40 characters, and 500 characters for the value. If we had a single plan for all EU countries, the localization for the languages + existing metadata will likely exceed our 50 key limit. I think we should start looking at other places to store plan/product associated data we use for non-Stripe purposes, and try to reign in the use of Stripe metadata some.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

To expand a little more, if we want to move additional plan/product related data out of Stripe metadata, we have a few options on where to store it:

  1. Configuration data
  2. MySQL
  3. Firestore

This data is updated semi-frequently by product, so requiring re-deploys for updates as needed if we stored it as configuration data is probably not feasible.

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I filed the epic FXA-3655 to address the concern with Stripe's metadata limit.  Head there to continue the discussion on that.

This Jira is still necessary.  Regardless how we store and retrieve the localized strings, we still need to improve on how to determine which locale to use.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Following our triage discussion yesterday on https://mozilla-hub.atlassian.net/browse/FXA-4703 ( https://mozilla-hub.atlassian.net/browse/FXA-4703|smart-link ), we plan to move these product/plan-specific localized strings into Firestore along with other product/plan config.

Once that migration is complete, we can match the localized strings from the product/plan configs to the selected browser locale, just as the rest of our web content does.

Right now, there can be a mismatch, as the product/plan-specific localized strings (such as product details during checkout) are determined by which plan is passed into SubPlat from the RP’s website (the RP usually does an IP address look-up).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
