### ISSUE TITLE
UI - Update all body fonts to Inter

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9129]
Currently subplat uses system fonts. 
We want to remove all system fonts and replace them with the appropriate Mozilla/Firefox brand guidelines font families.

For body copy and all small labels, headings etc. the font should be = **Inter**
Inter is used for all copy sizes less than 22px.
Styles: Regular - Semi-Bold - Bold

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3126)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
