### ISSUE TITLE
Continue to *Fenix* should be *Firefox Sync*

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#913]
@ryanfeeley is suggesting we change the OAuth login such that the Fenix client name appears as "Firefox Sync" instead of "Fenix" (or whatever it will be called in the end). Thoughts?

Thoughts?

**Comment by vladikoff** [comment]
i think a better approach should be that it would say “Fenix” but also say that it will access your “Firefox Sync” data.

**Comment by ryanfeeley** [comment]
The client is connecting to the Sync service, and will access the Sync data. It should say **to continue to Firefox Sync** like it does for service=sync.

The jury rests! 👨‍⚖️

**Comment by vladikoff** [comment]
> The client is connecting to the Sync service, and will access the Sync data. 

by that logic, Lockbox should also say Firefox Sync because it access Sync data.

📚

**Comment by ryanfeeley** [comment]
It probably should, but Lockbox (now Lockwise) implies password store.

Continue to Fenix makes no sense because it doesn't provide the user any indication of where they are headed.

Please fix ASAP.

Related: https://github.com/mozilla-mobile/fenix/issues/2031

**Comment by vladikoff** [comment]
@shane-tomlinson given the comment above could someone please take a look at this and maybe pull this into your current train? Thanks

**Comment by shane-tomlinson** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1547251 to have the name changed on the OAuth server. We'll need to update the [CSS here to show a reasonable icon](https://github.com/mozilla/fxa/blob/614975687d3f69b462231a3a3bb4fecce6ecd4f1/packages/fxa-content-server/app/styles/modules/_settings.scss#L538).

**Comment by shane-tomlinson** [comment]
We should probably also update the emails to send the Sync emails rather than OAuth RP emails, that's a larger change that needs to be prioritized with other work.

**Comment by clouserw** [comment]
See linked issues for followups.
