### ISSUE TITLE
UI - Update heading fonts - Metropolis

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9130]
Across subplat heading and display fonts need to be updated to align with brand.

Metropolis should be used for heading, display, and button font.

* All fonts 22px and greater in size.
* The buttons need to be updated to Metropolis as well – 16px
* Styles used: Regular, Bold, Semi-bold

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3127)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
