### ISSUE TITLE
Checkout: take existing PayPal customer to appropriate page when PayPal billing agreement is in an error state

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9131]
When a customer with active subscription(s) paid through PayPal tries to subscribe to another product, there are two Billing Agreement (BA) related error state we need to handle:

1. Valid BA with issue with its funding source, or
1. Invalid BA

For 1 we show the customer a link to PayPal that will allow them to resolve the BA issue.  For 2 we'll take the user to the Subscription Management page to go through the PayPal flow of creating a new BA.

There are two places during the checkout process where the customer could encounter this error.  One is when they try to go to the product subscription checkout page.  If the BA is already in an error state, handle it accordingly.  The other is after the customer submitted the form to subscribe but the server informs the frontend of a bad BA state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3084)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

The logic for this is also needed in Subscription Management (see FXA-2806), so we should be able to reuse it here.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Jessica Cook I don't see any designs for this in the existing spec (not surprising, since we descoped this story for launch). Would you be able to give us some guidance and ideally some screens to display here?

These are the same PayPal errors that you designed screens for in Subscription Management. Now we want to alert the user here and prevent sign up in Checkout.

We will wait to add story points until we get some idea of the work involved to implement this.

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

Bianca Danforth I feel the pattern we worked on and documented around this might have a solution in there somewhere – I think we just need to review and look at this more closely together. I will set up time for next week for us to discuss this and some other outstanding issues I am tagged on across Jira for these upcoming epics

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Jessica Cook . Yeah I think we could use the error screen you had created with a more descriptive error message if they attempt to add another subscription.

This screen really only makes sense after they have submitted the form to create the subscription, but just having an improved error message and having the action button go to Subscription Management seems like a good improvement here for minimal effort. What do you think?

Here is the message we currently use for these errors in Subscription Management: "Invalid payment information; there is an error with your account."

Would that work for the error message here, Chris Rooney ?

Edit: Note the above solution means we would always require the user to attempt to submit the payment form before notifying them of an issue, even in the case that we know about an issue before they submit the form.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Per design-checkin, let's use the AlertBar before form submission and PaymentErrorView after submission with the same, more specific error message. The AlertBar would have a "Manage" link.

We should also probably disable the "Submit" button if one of these errors is present.

Jessica Cook: What do you think?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
