### ISSUE TITLE
UI - refine checkout product card layout

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9132]
See image below for refined UI design for desktop + mobile.

Also refer to Figma file and overall checkout layout spec:point_right:[https://www.figma.com/file/ejDMYaKpm5bsYL5YvhItur/Payment-Integration?node-id=683%3A4290](https://www.figma.com/file/ejDMYaKpm5bsYL5YvhItur/Payment-Integration?node-id=683%3A4290)

Increased sizing, smoothed corners, increased interior padding around element and extends to include total + price.

OLD/EXISTING is also attached to show differences.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3128)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/14904/Screen+Shot+2021-03-03+at+1.44.08+PM-1.png">Screen Shot 2021-03-03 at 1.44.08 PM-1.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14906/Screen+Shot+2021-03-03+at+1.45.23+PM.png">Screen Shot 2021-03-03 at 1.45.23 PM.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14905/Screen+Shot+2021-03-03+at+1.47.39+PM.png">Screen Shot 2021-03-03 at 1.47.39 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Jessica Cook commented:

When we want to consider multiple plan options - upgrades and coupons this change to this component is critical to the design patterns

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
