### ISSUE TITLE
[FxA-Settings] Secondary email section -'Email' in section's title is uppercase

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9138]
**Build:**
 Prod [Train 1.200.0]

**Affected platforms:**
 Windows 10 
 iOS 14.4
 Android 9

**Steps to reproduce:**

1. Navigate to [https://accounts.firefox.com/](https://accounts.firefox.com/) and log in using an existing account.
1. Click on the 'Switch to new design' button.
1. At 'Profile' observe the title of 'Secondary email' section.

**Expected result:**
 'Email' in section's title is written with lowercase - see [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A1)

**Actual result:** 
 'Email' in section's title is written with uppercase. 

**Note:**

* The bug is reproducible only if no secondary email is added.
* If a secondary email is added then 'email' is written correctly, with lowercase.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3089)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16857">2ndary email text.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/17995">2ndary email text issue.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/14861">Screenshot_9.png</a>

**Comment by data-sync-user** [comment]
➤ Karina Bekbayeva commented:

I don't have an access to the Jira, Figma, attachments but as I understood I just need to remove the upper case. May I take it? LZoog

**Comment by data-sync-user** [comment]
➤ Karina Bekbayeva commented:

I could not reproduce this issue. I tried to locally run it on both Firefox 86.0 (64-bit) and Chrome Version 89.0.4389.90 (Official Build) (64-bit), on the device XPS-13-9360. Do you have any ideas?
Screenshot from 2021-04-01 19-36-42 ( https://user-images.githubusercontent.com/35498147/113302453-e29bd780-9321-11eb-866c-2b0c9cf4b43b.png )

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Bianca Oltean the localization team fixed this. I checked staging it still looks broken but production looks good.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Anna Sobiepanek Thank you for the update. Did this fix make it to Train 219 or is it only in the next Train? I looked on Production [Train 219.5] and I got the following:

En-US, En-GB - The issue is still present - Email in section’s title is uppercase

!2ndary email text issue.PNG|width=329,height=109!

En-CA - Email in section’s title is lowercase which is correct

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

It appears that if you do not have a secondary email set then the heading is capitalized “Secondary Email” but if it is set then the heading is not capitalized “Secondary email”. this is odd.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Another update on this: 

  * if you open the settings page in En-US → the issue is not present - the heading is not capitalized “Secondary email“
  * if you change to En-GB → the issue is present - the heading is capitalized “Secondary Email“
  * if you change back to En-US → the issue is present again - the heading is capitalized “Secondary Email“
  * if you change to En-CA → the issue is not present - the heading is not capitalized “Secondary email“

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
