### ISSUE TITLE
[FxA-Settings] "Printed" tooltip message for recovery key is not displayed on Android

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9139]
**Build:**
 Stage [Train 1.201.1]

**Affected platforms:**
 Android 8

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in using an existing account.
1. Tap on the 'Switch to new design' button.
1. Go to the 'Recovery key' section and tap on the 'Create' button.
1. Enter the correct password and tap on the 'Continue' button.
1. Tap on the 'Print' option.
1. Go back to the 'Recovery key' tab and observe the message.

**Expected result:** 
 'Printed' message is displayed.

**Actual result:** 
 No 'Printed' tooltip message is displayed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3134)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/14943">recovery key Printed message Android.mp4</a>

**Comment by data-sync-user** [comment]
➤ Suyash Chauhan commented:

I think it is something  browser specific check this 

https://developer.mozilla.org/en-US/docs/Web/API/Window/print#browser_compatibility
 https://bugzilla.mozilla.org/show_bug.cgi?id=1247609 
  https://github.com/mozilla-mobile/fenix/issues/13214 
looks like firefox-android doesn't have support for window.print

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
