### ISSUE TITLE
Delete old-settings after we've stabilized in prod

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9141]
Once we are sure we can let go of old-settings, let's delete all that code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3118)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Also look for any references to “beta settings” and rename to “settings”

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
