### ISSUE TITLE
Allow AMO to trigger a reauth

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9148]
For critical things like deleting an add-on or an AMO account (when triggered from within AMO), having a way for AMO to trigger an FxA reauth would be a good security improvement.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3193)

**Comment by jdragojevic** [comment]
@wagnerand  - can you provide some more details about the behavior you are requesting and the outcome you want to have?

**Comment by data-sync-user** [comment]
➤ Daniel Veditz commented:

For an un-doable destructive action it would be extra good to verify that the person doing the action is the actual user, and not someone who has come upon their unlocked screen, or the library computer they forgot to log out of. Some sites do a similar confirmation by requiring the user to input their password again before being allowed to change sensitive information like the password itself or the account email, or, for example, Amazon requires it before proceeding to checkout (maybe only if you have a stored creditcard? haven’t tried without).

The AMO team’s understanding is that if they try to do something similar with FxA and the user is still logged in it will silently refresh the auth token. Is there a way for AMO to force the check to go through explicit FxA login UI?  Does FxA have any guidance or best practice for this situation?
