### ISSUE TITLE
[fxa-auth-server] README is missing scripts description

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9176]
## Description
`fxa-auth-server` has very useful scripts for setting up the environment. For example, `dump-users` to create mock users to play with. Maybe we should add a centralized document explaining what each script does and how to use them? 

Especially mentioning that we should use not `node` to run them, but `ts-node` [(link)](https://github.com/mozilla/fxa/issues/5261).

Related [issue](https://github.com/mozilla/fxa/issues/7757)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3303)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
