### ISSUE TITLE
Buttons in dashboard have different border on focus

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9182]
## Description
Refer to attach video. Buttons on dashboard have different border color and outline on focus: some are blue, some have no visual color. 

### Steps to reproduce
https://user-images.githubusercontent.com/76935202/113662841-3fb1d780-96ec-11eb-99df-f99bb5232805.mov

### Actual result
All buttons on focus have same ( blue?) color, unless they are btn for delete smth.

### Environment
macOS Catalina 
Google Chrome

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3318)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
