### ISSUE TITLE
update react-hook-form

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9186]
from #8231

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3360)

**Comment by data-sync-user** [comment]
➤ Cronus  commented:

dannycoates Is there any specific reason to close #8231. And I am willing to work upon this issue.

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Thanks @Cronus1007, you're welcome to take it.

**Comment by LZoog** [comment]
Documentation: https://react-hook-form.com/migrate-v6-to-v7/

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
