### ISSUE TITLE
Separate FxA staging environment for dependencies

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9187]
Currently there is one FxA staging environment used for FxA development, as well as its relying parties. Recommend keeping FxA staging for testing FxA, and using the most recently released version of FxA for staging envs for dependencies like VPN.

Related to https://github.com/mozilla/fxa/issues/3392

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3366)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
