### ISSUE TITLE
Event broker sentry must sanitize inputs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9190]
Just saw an unsanitized email address and uid in the event-broker sentry, emitted at this line: https://github.com/mozilla/fxa/blob/main/packages/fxa-event-broker/src/queueworker/service-notification.interface.ts#L66

It's critically important to strip out any PII before submitting errors to sentry.

I believe just using fxa-shared/lib/sentry will sanitize the submissions: https://github.com/mozilla/fxa/blob/main/packages/fxa-shared/lib/sentry.ts

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3321)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Dan Schomburg did you land a patch that fixed this?

**Comment by data-sync-user** [comment]
➤ Dan Schomburg commented:

Wil Clouser No, this has not been addressed.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
