### ISSUE TITLE
Automated tests for testing the utility functions in  must-change-password.ts

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9191]
## Description
This one is related to add the unit and integration test cases for testing the utility functions in `must-change-password.ts` in order to test the new functionality added by PR #8059

## Solution Approach 
Writing new tests under the test folder of the package `fxa-graphql-api` in order to test the `scripts/must-change-password.ts`. 

## Enviornment 
OS: Ubuntu
Browser: Chrome

@dannycoates Label this issue according.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3341)

**Comment by data-sync-user** [comment]
➤ Cronus  commented:

dannycoates Awaiting for your review upon this.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
