### ISSUE TITLE
[FxA-Settings] Settings page errors and notifications are displayed over the site navigation menu

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9194]
**Build**
Stage [Train 1.203.6]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 14.4

**Steps to reproduce**

1. Navigate to https://accounts.stage.mozaws.net/settings/ and login using an existing account.
1. Click on the "Change" button displayed on the "Password" section.
1. Insert an incorrect password in the current password field.
1. Type a valid password in the new password fields.
1. Click "Save" button.
1. Open the Site navigation menu.

**Expected results**
Settings page errors and notifications are not visible over the site navigation menu.

**Actual Results**
Settings page errors and notifications are not hidden while the Site navigation menu is opened.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3327)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15028/Screenshot_19.png">Screenshot_19.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15029/Screenshot_41.png">Screenshot_41.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15030/Screenshot_43.png">Screenshot_43.png</a>

**Comment by data-sync-user** [comment]
➤ Yogita Bhatia commented:

I wasn't able to repro this issue since on clicking the "Save" button, a popup with Incorrect password as text shows up.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This is reproducible if you open the change password page in mobile, get a tooltip to come up, then open the navigation.

https://user-images.githubusercontent.com/13018240/118513401-4a06be80-b6f9-11eb-8192-671fc0aabd78.png

**Comment by data-sync-user** [comment]
➤ Jatin commented:

@data-sync-user I would like to work on this issue.

**Comment by data-sync-user** [comment]
➤ Jatin commented:

LZoog , can I work on this issue? If yes please assign this to me..

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
