### ISSUE TITLE
Storybook does not use LTR or RTL-specific styles

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9195]
## Description
When running Storybook locally a contributor observed that `tailwindcss-dir` classes were not being applied for either "direction". 

### Steps to reproduce
* `yarn storybook`
* Go to a Story that has a directional class: `ltr:*` or `rtl:*`. LTR will be easier to see if that's your current direction.

### Expected result
Direction-specific styles should be applied.

### Actual result
They are not applied.

### Additional Notes
This is due to the Storybook story frame's `<html>` element not having the `dir` attribute. If you were to open Developer Tools and manually apply `dir="ltr"` to it, the LTR styles would become active.

**Bonus**:

If we get that dir attribute hooked up it would be wicked cool if we also hooked up a [toolbar](https://storybook.js.org/docs/react/essentials/toolbars-and-globals) to control the direction within Storybook. Something like this in `preview.js`:

```javascript
export const globalTypes = {
  direction: {
    name: "Text directionality",
    description: "Toggle text directionality",
    defaultValue: "ltr",
    toolbar: {
      icon: "transfer",
      items: ["ltr", "rtl"],
    },
  },
};
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3355)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is this a bug for FxA or for Storybook?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

It would be up to us. We could use something like https://storybook.js.org/addons/storybook-addon-root-attribute

**Comment by millsoper** [comment]
Just leaving a note to say that this has been mostly fixed in [this PR](https://github.com/mozilla/fxa/pull/12911) but we haven't added the toggle in. [This comment](https://github.com/mozilla/fxa/pull/12911#pullrequestreview-977718017) notes that we have another implementation in `fxa-auth-delivery` which does include the toggle, so probably good to keep that in mind when we _do_ add the toggle in.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
