### ISSUE TITLE
Document additional metadata set in Stripe as a result of PayPal for PayPal customers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9197]
https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#configuration

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3357)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
