### ISSUE TITLE
Plural name in page title

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9199]
## Description
When you log in to your personal page page title in browser shows up plural

### Steps to reproduce
![Screen Shot 2021-04-08 at 12 16 52 am](https://user-images.githubusercontent.com/76935202/113958838-18324a80-9865-11eb-982e-1508c7936544.jpg)

### Expected result
Page title same as page header name

### Actual result
Page title differs from Header name

### Environment
macOS Catalina
Google Chrome
(aus-en)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3335)

**Comment by data-sync-user** [comment]
➤ Jo-bot86 commented:

jodyheavener @LZoog, can I make this small change?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Alex Davis would you confirm the window title should be "Firefox account" like on the page?

**Comment by data-sync-user** [comment]
➤ Jo-bot86 commented:

Maybe we can change the window title and the page title into "Firefox Account". IMO it looks better when the "a " of  account is capitalized. What do you think about it?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

There are branding guidelines around this and I'm pretty sure it's a lower case 'a' these days, but verifying with Alex ^

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Related #8184

**Comment by data-sync-user** [comment]
➤ Ayush Anand commented:

Why this issue is still open? this is already fixed ig

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Ayushsunny we reopened the page header one here: https://github.com/mozilla/fxa/issues/7676#issuecomment-842418156

This issue addresses the page title.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
