### ISSUE TITLE
Remove fpn image fallbacks

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9200]
We should not be falling back to the fpn logo when we do not have `webIconURL` set.

* [https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx#L40](https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/ConfirmationDialog.tsx#L40)
* [https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx#L24](https://github.com/mozilla/fxa/blob/main/packages/fxa-payments-server/src/routes/Subscriptions/Reactivate/SuccessDialog.tsx#L24)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3359)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
