### ISSUE TITLE
[FxA-Settings] String not consistent in 2FA page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9211]
**Build:**
 Stage (Train 1.204.7)

**Affected platforms:**
 Windows 10 64-bit
 Android 11

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in with an existing account.
1. Go to 2FA section and click the ‘Add’ button.
1. Click the ‘Can’t scan code’ link and observe the strings ‘authenticator’ vs ‘authentication’.
1. Compare with other 2FA pages.

**Actual result:** 
 String ‘authenticator’ is displayed instead of ‘authentication’. No consistency.

**Expected result:** 
 String ‘authenticator’ is changed to ‘authentication’.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3432)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15076/word+not+consistent.PNG">word not consistent.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
