### ISSUE TITLE
[FxA-Settings] No focus border for ‘Show/ Hide password’ button

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9212]
**Build:**
 Stage (Train 1.204.2)

**Affected platforms:**
 Windows 10 64-bit

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/).
1. Enter your email address and click Continue.
1. Enter a password and click the ‘Show/ Hide password’ button.

**Actual result:** 
 No focus border is displayed for the ‘Show/ Hide password’ button.

**Expected result:** 
 Focus border is displayed for the ‘Show/ Hide password’ button.

**Note:** The same issue with no focus border can be found on ‘Create account’ page.
 On the ‘Change password’, ‘Recovery key’, ‘Delete account’ pages there is a focus border.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3391)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15096/no+focus+border+for+eye+icon.gif">no focus border for eye icon.gif</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15070/No+focus+border+for+eye+icon.PNG">No focus border for eye icon.PNG</a>

**Comment by data-sync-user** [comment]
➤ Ayush Anand commented:

Hely @data-sync-user I wanna work on this issue

**Comment by data-sync-user** [comment]
➤ amantayal6797 commented:

Hey LZoog and @data-sync-user , Can I take a look into this?

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Ayushsunny are you still interested in working on this? Go ahead and grab it if so! (sorry, data-sync-user is our sync integration with Jira and I don't think anyone gets notifications for that 🙂)

amantayal6797 I responded to you on another issue and assigned that one to you, thank you for your interest! ❤️

**Comment by data-sync-user** [comment]
➤ Ayush Anand commented:

Hey, LZoog Could you send those attachments here as I am unable to log in to see those images.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Ayushsunny here are the two attached photos

no focus border for eye icon ( https://user-images.githubusercontent.com/6392049/118640078-93611780-b7a6-11eb-8bcb-a2022fbf97d1.gif )

No focus border for eye icon ( https://user-images.githubusercontent.com/6392049/118640091-978d3500-b7a6-11eb-8733-648799239bd3.PNG )

**Comment by data-sync-user** [comment]
➤ Ayush Anand commented:

jodyheavener But when I type Pass it shows two 'show/hide' button 

Screenshot 2021-05-18 171628 ( https://user-images.githubusercontent.com/73520373/118646242-8facaf80-b7fd-11eb-8203-3914096e04b9.png )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
