### ISSUE TITLE
[admin-panel] Display and allow updates of the `locale` user property

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9217]
Sometimes we want to know what the saved `locale` is for a user, and might want to change it for support purposes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3385)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks Barry.  Really, any fields that are associated with the user and easy to display, let's do it.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

My last comment was for if this was added to the admin panel, but after talking with Danny we agreed this would be a good field to add to the Profile section so the user could modify their own preferred language.  If it's not set, we'd auto-detect, otherwise we'd use this.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
