### ISSUE TITLE
[L10n] email registered pop-up not translated in Hungarian

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#922]
Build: Release 66.0.2;
Devices: iPhone SE	(12.1.4);

Prerequisites:
Your FF is set on Hungarian (Magyar) language;

Steps to reproduce:

1. Create a valid account;
2. Tap on 'Create account' button;

Expected results:
A green pop-up is displayed with the text '[email] registered' in French;

Actual results:
The '[email] registered' pop-up is not translated;

Note:
- [photo](https://drive.google.com/file/d/0B-OVCGyglYi_Vlpka3VLODVsWFRUQ3Bwc0VuSGF1dDBRXzNn/view?usp=sharing)

**Comment by shane-tomlinson** [comment]
Cause is the same as #902, closing as a dup. Thanks @sv-sdeiac, keep these issues coming!
