### ISSUE TITLE
settings.ftl requests for en / en-US are returning wrong result

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9225]
They return the index.html instead of the ftl file

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Mon, 03 May 2021 19:01:28 GMT
ETag: W/"67b-8E4+ISIdnaMYVEx3nvsgPd8X7rY"
Content-Length: 765
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3442)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
