### ISSUE TITLE
[FxA-Settings] Button text is not centered for different languages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9227]
**Build:**
Stage (Train 1.204.3)

**Affected platforms:**
Windows 10 64-bit
Android 11

**Steps to reproduce:**

1. Launch Firefox using a fr, ge, estonian, dutch, spanish (es), frisian, georgian, etc build (or set the desired language from about:preferences -> Choose your preferred language for displaying pages).
1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in using an existing account.
1. Go to Picture section and click the ‘Add’ button.
1. Observe ‘Cancel’ and ‘Save’ buttons.

**Actual result:** 
Buttons text is not centered.

**Expected result:** 
Buttons text is centered.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3396)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15095">DE button text not centered.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23364">dutch - text not centered on buttons.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15093">FR button text not centered.PNG</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23361">frisian - text not centered.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23363">georgian - text not centered.png</a>

**Comment by data-sync-user** [comment]
➤ nerdsaywhat commented:

Can I work on this issue?

**Comment by Ayushsunny** [comment]
Hello, @data-sync-user Are you working on this? if not
Can I work on this issue?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
