### ISSUE TITLE
Create tests for delete-account script

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9232]
Our delete-account.js script to manually deleting users doe not have any tests in `packages/fxa-auth-server/test/scripts`.  That leads to issues like FXA-3453, where jbuck only notice a problem at the time he needs to use the script.  Perhaps we should to try add tests for the script?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3458)

**Comment by l-hedgehog** [comment]
Hi, we noticed the script is broken again, by changes in
https://github.com/mozilla/fxa/commit/07dfceb50c37604d68f9fc42f7281e19e5720109#diff-0352ea89ac02a9d40e96cb39d5a79447fce8763cdff17d27a4b966f1390b5702
https://github.com/mozilla/fxa/commit/22b7fd5d774fb525d1b041bd167b3b38fc84fd01#diff-0352ea89ac02a9d40e96cb39d5a79447fce8763cdff17d27a4b966f1390b5702
https://github.com/mozilla/fxa/commit/233de634204547fbe166f066faa46ebc1837ec13#diff-0352ea89ac02a9d40e96cb39d5a79447fce8763cdff17d27a4b966f1390b5702
etc.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

To be honest, I’d rather implement deleting accounts in the admin panel and remove the script completely.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
