### ISSUE TITLE
[deps] upgrade jwks-rsa to 2.x

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9233]
Originally: https://github.com/mozilla/fxa/pull/8548

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3481)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Danny Coates where should we prioritize this upgrade?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is only used in the event broker

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
