### ISSUE TITLE
Send access/refresh token revokation messages on SQS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9240]
To distribute access token revocation in the event-broker, the auth-server needs to emit SQS messages for the access token and refresh token revocation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3444)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
