### ISSUE TITLE
[emails M1] Set up state previewing solution

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9244]
FXA-3503 / #8600 decided what state previewing solution we should use.

We need to add this on top of the templating system added in FXA-3504 / #8601. A dummy "hello world!" state would be great to show for now.

If we _didn't_ choose Storybook in #8600, we may need an additional ticket for deployment (which might be done outside of this epic). Additionally, it would be great to play with a "preview in Mail client" solution here, mentioned in #8600. If it gets a little hairy, we should create a different ticket to explore that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3505)

**Comment by LZoog** [comment]
In #8765, we chose to use Storybook.

Storybook for EJS and MJML is a bit different than it is for React. Les created a fantastic [starter repo](https://github.com/lmorchard/mjml-in-storybook) for this kind of stack.

To close this ticket, we just need Storybook to run locally and show one template with state changes. Also, unless we need it for another reason, we can remove any related write-to-disk previewing stuff. We are likely going to need to create a "deploy EJS/MJML Storybook to GCP" follow up ticket and add it to a "nice to haves" emails epic - it's OK for us to do that later, after we implement it for development use.
