### ISSUE TITLE
Error: Invalid payload on PayPal IPN Handler.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9246]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11194757/?referrer=github_plugin

This needs additional logging so we know what the invalid payload was.  Also, who it is from.

```
Error: Invalid payload on PayPal IPN Handler.
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.js", line 143, in PayPalNotificationHandler.verifyAndDispatchEvent
    throw new Error('Invalid payload on PayPal IPN Handler.');
  ?, in runMicrotasks
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3446)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
