### ISSUE TITLE
Error: Unhandled Ipn message: new_case

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9250]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11188927/?referrer=github_plugin

Let's catch and ignore this in code

```
Error: Unhandled Ipn message: new_case
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.js", line 156, in PayPalNotificationHandler.verifyAndDispatchEvent
    sentry_1.reportSentryError(new Error('Unhandled Ipn message: ' + payload.txn_type), request);
  ?, in runMicrotasks
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3447)

**Comment by data-sync-user** [comment]
➤ Ben Bangert commented:

This should log the payload at warning level if the txn_type is undefined. Other txn_type's should be ignored.

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-BE](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11188927/?referrer=github_plugin)

**Comment by chenba** [comment]
Sentry issue: [FXA-AUTH-PROD-GB](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/15644444/?referrer=github_plugin)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
