### ISSUE TITLE
[emails M1] Convert `cadReminderFirst` to new stack

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9255]
The first template conversion is here, aww yeah!

Take `cadReminderFirst.html` and use the new stack/system set up thus far to convert the template which will also include adding a shared `cadReminder` component.  Convert tests and add states to the state previewing solution. Make sure it builds properly and that the new email is sent locally (by turning on the feature flag it sits behind).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3508)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

This ticket is basically going to be a catch-all for “convert anything remaining” to reach parity for cadReminderFirst.

  * Convert CadReminderFirst to MJML/EJS/CSS solution
  * Ensure significant states are represented in Storybook (it’s OK to move states from CadReminder into CadReminderFirst, I don’t know that we really need all states for partials)
  * Add doc property in Storybook, I’ll get back to you about what string to use here
  * Turn on feature flagging for yourself locally, and make sure you can receive the email locally in maildev (how to trigger this locally will be more clear once the string for doc is provided - may also need Vijay’s help here)
  * Copy tests over
  * Create plaintext files/solution, which I believe we mentioned in the ADR. This might be the most time consuming part of this ticket.

**Comment by Yogita98** [comment]
There are a few really small things which are supposed to be done as part of this ticket:
1. Things pending in [this comment](https://github.com/mozilla/fxa/pull/9779#issuecomment-881476444)
2. Padding of the button is supposed to be 12px or 16px or it has to be kept as is. Further context over [here](https://github.com/mozilla/fxa/pull/9779#discussion_r671335101)

**Comment by LZoog** [comment]
@Yogita98 asked our designer (Janice Cramer) and she said go with `16px`. :)

**Comment by LZoog** [comment]
Let's also be sure to address:
* [This](https://github.com/mozilla/fxa/pull/10005#discussion_r682041571) now famously annoying CI problem (well, it's now famously annoying between you, @jodyheavener, and I 😀)
* A member of the l10n team [got back to me here](https://github.com/mozilla/fxa/pull/10005/files#r681843257) and provided the following screenshot which shows what RTL languages there are, and also gave [this link](https://pontoon.mozilla.org/projects/firefox-accounts/) which shows what languages FxA supports. Let's double check that array all/only the RTL languages listed there.
![image](https://user-images.githubusercontent.com/13018240/128099977-a3be413c-44cc-4ac8-b24b-c7842fd27070.png)
