### ISSUE TITLE
Issue when removing avatar image

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9259]
As soon as the avatar image is removed, it navigates back to the settings page but the picture in both the profile section and the avatar drop down section displays 'Your avatar' text instead of the default profile picture icon.

Please see attached image for actual and expected.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3494)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15130/Actual.png">Actual.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15131/Expected.png">Expected.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Which test is this happening in?

**Comment by data-sync-user** [comment]
➤ Ankita Shrivastava commented:

I was creating a test for 'removing a profile pic' and manually tried this scenario where I delete an existing picture and found the issue. I added the test in avatar.js file.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
