### ISSUE TITLE
Create stable URL that will redirect to the payments page

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#926]
To actually use the payments page you have to come through accounts.firefox.com and get redirected with a token. We want to link directly to payments pages, which will require a page on accounts.firefox.com which redirects immediately (with a token) to the payments URL. This page should probably display a simple loading spinner while it attempts to redirect (redirection has to happen in the browser, as the account information is in the browser and not available to the server).

PRD requirements included in this:

* A 1.2 | FXA should allow users to sign in or sign up via a Firefox Account
* A 1.3 | If users are signing in, FXA should direct them to a payments UI

**Comment by shane-tomlinson** [comment]
@ianb is there a link to a diagram of how this should work? I'm having a hard time imagining the flow.

**Comment by lmorchard** [comment]
> is there a link to a diagram

There has been one going around, though I don't think I have good links to it. [A version was shared in Slack](https://mozilla.slack.com/archives/CG0AJ6E77/p1555362941064100) and appeared in [a private Google doc from a security review](https://docs.google.com/document/d/17PUUQyCseT39seTkK7CPlXVt07p9MDZoypJnSV-TVZs/edit?ts=5cb4a53e#heading=h.8hq3qvrfp4h4) with the flow sketched out. @bbangert might have a better link to an image.

**Comment by bbangert** [comment]
Yes, here's the mermaid code for it. I wish there was an easier way to share/codify these, I'm still looking for a better solution.
```
sequenceDiagram
participant UA as User-Agent<br>(Browser)
participant Svc as Service Offering
participant FxAC as FxA Content Svr<br>(accounts.firefox.com)
participant FxAP as FxA Content Svr<br>(payment.firefox.com)
participant FxA as FxA Auth<br>(api.accounts.f.c)
participant SB as SubHub
participant Stripe as Stripe

UA->>Svc: Click "buy" button
Svc->>UA: 302 accounts.firefox.com
UA->>FxAC: Enter sign-up logic
Note over FxAC: Varies depending on<br>user status, existing<br>account, etc.
FxAC->>FxAC: make short lived oauth token
Note over UA: User is sent to<br>dedicated site that<br>serves payment form,<br>isolated from FxA
FxAC->>UA: 302 payment.f.c {plan_id, oauth_token}
UA->>FxAP: Get stripe payment form {oauth_token}
Note over FxAP: is it useful to validate<br>the oauth token here?
FxAP->>SB: GET list_all_plans
SB->>Stripe: GET list_all_plans
Stripe->>SB: {plan_id, plan_id, ...}
SB->>FxAP: {Plan_id, plan_id, ...}
FxAP->>UA: payment page
UA->>Stripe: Credit Card data with Stripe account id
Note over Stripe: Validates Credit Card<br>data
Stripe->>UA: Payment_token
Note over UA: User selects plan_id<br> they would like (VPN)
UA->>FxA: POST {oauth_token, payment_token, plan_id}
Note over FxA: validate oauth_token
FxA->>SB:  {fxa_uid,Payment_token,plan_id }
SB->>Stripe: Create customer if not present in SB
Stripe->>SB: Customer_id
Note over SB: Stores:<br> fxa_uid to<br> customer_id
SB->>Stripe: Subscribe customer_id with plan_id
Stripe->>SB: Success or Errors
SB->>FxA: SubActive({subscription, ...}) or Error
Note over FxA: FxA adds in database<br>subscribed to plan for<br>the user if success
FxA->>UA: Success or Errors

```

**Comment by lmorchard** [comment]
FWIW, this should also accept a `plan_id` that carries through to a payments page dedicated to the plan so that third-party RPs can link to it from calls-to-action to subscribe.

Another wrinkle is that the user may not be logged in when they hit this link, so we'll need to retain all that on the way through login to resume the redirect

**Comment by lmorchard** [comment]
Hmm, looks like [the Mermaid editor has a super-gnarly URL to link to](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5wYXJ0aWNpcGFudCBVQSBhcyBVc2VyLUFnZW50PGJyPihCcm93c2VyKVxucGFydGljaXBhbnQgU3ZjIGFzIFNlcnZpY2UgT2ZmZXJpbmdcbnBhcnRpY2lwYW50IEZ4QUMgYXMgRnhBIENvbnRlbnQgU3ZyPGJyPihhY2NvdW50cy5maXJlZm94LmNvbSlcbnBhcnRpY2lwYW50IEZ4QVAgYXMgRnhBIENvbnRlbnQgU3ZyPGJyPihwYXltZW50LmZpcmVmb3guY29tKVxucGFydGljaXBhbnQgRnhBIGFzIEZ4QSBBdXRoPGJyPihhcGkuYWNjb3VudHMuZi5jKVxucGFydGljaXBhbnQgU0IgYXMgU3ViSHViXG5wYXJ0aWNpcGFudCBTdHJpcGUgYXMgU3RyaXBlXG5cblVBLT4-U3ZjOiBDbGljayBcImJ1eVwiIGJ1dHRvblxuU3ZjLT4-VUE6IDMwMiBhY2NvdW50cy5maXJlZm94LmNvbVxuVUEtPj5GeEFDOiBFbnRlciBzaWduLXVwIGxvZ2ljXG5Ob3RlIG92ZXIgRnhBQzogVmFyaWVzIGRlcGVuZGluZyBvbjxicj51c2VyIHN0YXR1cywgZXhpc3Rpbmc8YnI-YWNjb3VudCwgZXRjLlxuRnhBQy0-PkZ4QUM6IG1ha2Ugc2hvcnQgbGl2ZWQgb2F1dGggdG9rZW5cbk5vdGUgb3ZlciBVQTogVXNlciBpcyBzZW50IHRvPGJyPmRlZGljYXRlZCBzaXRlIHRoYXQ8YnI-c2VydmVzIHBheW1lbnQgZm9ybSw8YnI-aXNvbGF0ZWQgZnJvbSBGeEFcbkZ4QUMtPj5VQTogMzAyIHBheW1lbnQuZi5jIHtwbGFuX2lkLCBvYXV0aF90b2tlbn1cblVBLT4-RnhBUDogR2V0IHN0cmlwZSBwYXltZW50IGZvcm0ge29hdXRoX3Rva2VufVxuTm90ZSBvdmVyIEZ4QVA6IGlzIGl0IHVzZWZ1bCB0byB2YWxpZGF0ZTxicj50aGUgb2F1dGggdG9rZW4gaGVyZT9cbkZ4QVAtPj5TQjogR0VUIGxpc3RfYWxsX3BsYW5zXG5TQi0-PlN0cmlwZTogR0VUIGxpc3RfYWxsX3BsYW5zXG5TdHJpcGUtPj5TQjoge3BsYW5faWQsIHBsYW5faWQsIC4uLn1cblNCLT4-RnhBUDoge1BsYW5faWQsIHBsYW5faWQsIC4uLn1cbkZ4QVAtPj5VQTogcGF5bWVudCBwYWdlXG5VQS0-PlN0cmlwZTogQ3JlZGl0IENhcmQgZGF0YSB3aXRoIFN0cmlwZSBhY2NvdW50IGlkXG5Ob3RlIG92ZXIgU3RyaXBlOiBWYWxpZGF0ZXMgQ3JlZGl0IENhcmQ8YnI-ZGF0YVxuU3RyaXBlLT4-VUE6IFBheW1lbnRfdG9rZW5cbk5vdGUgb3ZlciBVQTogVXNlciBzZWxlY3RzIHBsYW5faWQ8YnI-IHRoZXkgd291bGQgbGlrZSAoVlBOKVxuVUEtPj5GeEE6IFBPU1Qge29hdXRoX3Rva2VuLCBwYXltZW50X3Rva2VuLCBwbGFuX2lkfVxuTm90ZSBvdmVyIEZ4QTogdmFsaWRhdGUgb2F1dGhfdG9rZW5cbkZ4QS0-PlNCOiAge2Z4YV91aWQsUGF5bWVudF90b2tlbixwbGFuX2lkIH1cblNCLT4-U3RyaXBlOiBDcmVhdGUgY3VzdG9tZXIgaWYgbm90IHByZXNlbnQgaW4gU0JcblN0cmlwZS0-PlNCOiBDdXN0b21lcl9pZFxuTm90ZSBvdmVyIFNCOiBTdG9yZXM6PGJyPiBmeGFfdWlkIHRvPGJyPiBjdXN0b21lcl9pZFxuU0ItPj5TdHJpcGU6IFN1YnNjcmliZSBjdXN0b21lcl9pZCB3aXRoIHBsYW5faWRcblN0cmlwZS0-PlNCOiBTdWNjZXNzIG9yIEVycm9yc1xuU0ItPj5GeEE6IFN1YkFjdGl2ZSh7c3Vic2NyaXB0aW9uLCAuLi59KSBvciBFcnJvclxuTm90ZSBvdmVyIEZ4QTogRnhBIGFkZHMgaW4gZGF0YWJhc2U8YnI-c3Vic2NyaWJlZCB0byBwbGFuIGZvcjxicj50aGUgdXNlciBpZiBzdWNjZXNzXG5GeEEtPj5VQTogU3VjY2VzcyBvciBFcnJvcnMiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ) - reminds me of the hacks I did on Firefox Color 😅

**Comment by bbangert** [comment]
@lmorchard I think you mean`product_id`, so that it can query for the valid plans to display.

**Comment by lmorchard** [comment]
Ah, yeah, if we have a `product_id`, then we can query & list all the related plans

**Comment by lmorchard** [comment]
For context, here's [a wireframe of the page we should support linking to here](https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/357410550).

<img width="321" alt="Capture" src="https://user-images.githubusercontent.com/21687/57026632-3f5b5880-6c08-11e9-86d6-6a21abc23364.PNG">
