### ISSUE TITLE
[emails M1] FxA emails docs update

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9260]
Assuming documentation isn't written alongside most PRs in this epic, the documentation around our emails could likely use an update. Some of this will be in the `fxa-auth-server` README, but if we end up creating a new directory for the templates, some of the other points can likely go in a README in that new directory.

We'd like to have:

* A quick explainer of the current state of the old system and new system behind feature flags (this should be really brief, as it's going to be removed later once all of the templates are in production and feature flags removed)
* A link to the ADR
* A small explainer of the stack (MJML + EJS + Fluent) with relevant links
* CSS guidelines with an explanation around the globals, the Tailwind-esq variables/mixins, using !important, etc.
* How to build Storybook and relevant docs there
* Anything else that may be relevant at this point

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3510)

**Comment by Yogita98** [comment]
Right okay, I understood most of the requirements but would like a little more elaboration on this:

> * A quick explainer of the current state of the old system and new system behind feature flags (this should be really brief, as it's going to be removed later once all of the templates are in production and feature flags removed)
