### ISSUE TITLE
Update metadata validator to require CDN hosts for images

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9283]
Images in the metadata should have their domain validated to ensure they're using the FxA CDN for assets.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3562)

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Barry Chen should we add this to the firestore epic?

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Actually I think this one can be marked as fulfilled by https://mozilla-hub.atlassian.net/browse/FXA-4667 ( https://mozilla-hub.atlassian.net/browse/FXA-4667|smart-link )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
