### ISSUE TITLE
Increase network fetch resiliency

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9287]
When loading resources in the client, occasionally a network glitch results in data not being loaded. These fetches should have additional retries around them to fail/retry more gracefully.

Sentry: https://sentry.prod.mozaws.net/operations/fxa-payments-prod/issues/7846548/

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3563)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
