### ISSUE TITLE
Orfox

### ISSUE THREAD

**Issue by orbot77** [mozilla/fxa#929]
The proxy server is refusing connections

Firefox is configured to use a proxy server that is refusing connections.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to make sure the proxy server is working.

**Comment by shane-tomlinson** [comment]
@orbot77 Is this an issue with the Firefox Accounts authentication system or something within Firefox or an addon?

**Comment by orbot77** [comment]
Это проблема при запуске приложения orfox
