### ISSUE TITLE
[subplat] Revert metadata changes on validation failure

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9292]
When validation is performed on metadata updates during a webhook event, programmatically revert the failing changes.  This helps to prevent someone inadvertently breaking all the plans in a product when editing a product's metadata.

Yes, it'll be confusing to the Stripe admin when their changes get reverted.  We need to document this.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3564)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

The previous metadata value(s) are reported as part of Stripe's webhook event when data is changed; if we fail validation, we can take the old value out of the webhook.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
