### ISSUE TITLE
Wrong email displayed in OAuth permissions after changing primary address

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#930]
STR

1. Sign up with email 1
2. In the settings page, add email 2, verify email.
3. Make email 2 the primary email.
4. Visit an "Untrusted" RP, e.g., Pocket
5. On the permissions screen, email 1 is shown.
6. Continue through, on the RP email 2 is used.

![wrong-email-address-in-permissions](https://user-images.githubusercontent.com/848085/56730226-4c330480-674f-11e9-9dad-11f76180a430.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-824)
┆Issue Number: FXA-824

**Comment by vbudhram** [comment]
This isn't reproducible in main anymore...closing

<img width="499" alt="Screen Shot 2020-12-18 at 12 07 26 PM" src="https://user-images.githubusercontent.com/1295288/102641241-c042cd00-4129-11eb-90f1-ea110f857b26.png">
