### ISSUE TITLE
Set up 123 and 321done in prod for smoke test suite

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9315]
Need to set up 123 and 321done; vijay has set this up on heroku so we can duplicate this for Prod.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3571)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
