### ISSUE TITLE
[subplat] WError: An internal server error occurred

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9317]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11408389/?referrer=github_plugin

```
WError: An internal server error occurred
  File "/fxa/node_modules/stripe/lib/Error.js", line 40, in Function.generate
    return new StripeInvalidRequestError(rawStripeError);
  File "/fxa/node_modules/stripe/lib/StripeResource.js", line 180, in IncomingMessage.<anonymous>
    err = StripeError.generate(response.error);
  File "events.js", line 482, in Object.onceWrapper
  File "events.js", line 388, in IncomingMessage.emit
  File "domain.js", line 470, in IncomingMessage.emit
...
(2 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3592)

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-BD](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11182334/?referrer=github_plugin)

**Comment by biancadanforth** [comment]
Looking at the most recent [error](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11182334/?query=is%3Aunresolved), this is associated with a [particular invoice](https://dashboard.stripe.com/logs?object=in_1JHsRQJNcmPzuWtRNDP7LE11), and when looking at the invoice's history, we look to be continually trying to pay the invoice several times over several days after it has already been paid.  This specific customer's subscription looks to be in order, so it is not urgent. However we should find out why we keep trying to pay these already paid invoices.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
