### ISSUE TITLE
“Show/ Hide password” tooltip text not translated in the corresponding language

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9318]
**Build:**
Production (Train 1.207.1)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Steps to reproduce:**

1. Launch Firefox using a fr, ge, ar, sq, cy, etc. build (or set the desired language from about:preferences -> Choose your preferred language for displaying pages).
1. Navigate to https://accounts.firefox.com and enter your email address.
1. Click ‘Continue’.
1. Enter password and then click on the eye icon.
1. Observe the tooltip.

**Actual result:** 
“Show/ Hide password” tooltip text is not translated in the corresponding language.

**Expected result:** 
“Show/ Hide password” tooltip text is translated in the corresponding language.

**Note:**
Same issue can be found on the Create a Firefox Account page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3617)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15170/eye+tooltip+-+no+translation.gif">eye tooltip - no translation.gif</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15171/tooltip+not+translated.PNG">tooltip not translated.PNG</a>

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg: vbudhram swears he fixed it, assigned to verify

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
