### ISSUE TITLE
Deleting an account causes Firefox "Save password" dropdown to display, without an email address

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#932]
<img width="730" alt="Screenshot 2019-04-25 at 12 04 05" src="https://user-images.githubusercontent.com/848085/56731409-50145600-6752-11e9-99fa-85c61884fbd5.png">

I imagine we need to cancel a form submit event.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-826)
┆Issue Number: FXA-826

**Comment by mirefly** [comment]
I tried to cancel form submit event by adding the following to  delete_account.js, but "Save password" dropdown still shows up in Firefox...
```javascript
events: _.extend({}, FormView.prototype.events, {
  'submit form': cancelEventThen('onFormSubmit')
})
````

**Comment by jodyheavener** [comment]
I suspect this may be related to #876 - the issue being a forward navigation with a changed password-type input.

**Comment by victorphoenix3** [comment]
Can I work on this?
