### ISSUE TITLE
We should not report sentry errors for non-paypal credit notes.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9323]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11528137/?referrer=github_plugin

    Error: Credit note issued for account balance: cn_1J08XjJNcmPzuWtR4JdJljia
      File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.js", line 131, in StripeWebhookHandler.handleCreditNoteEvent
        sentry_1.reportSentryError(new Error(`Credit note issued for account balance: ${creditNote.id}`), request);
      ?, in runMicrotasks
      File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/subscriptions/stripe-webhook.js", line 59, in async StripeWebhookHandler.handleWebhookEvent
        await this.handleCreditNoteEvent(request, event);
    ...
    (4 additional frame(s) were not displayed)We should ignore invoices with charge automatically, and if its send_invoice and not out_of_band, then we report it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3619)

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-C1](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11528137/?referrer=github_plugin)

**Comment by biancadanforth** [comment]
Quoting Ben: > If the invoice collection is NOT `send_invoice`, we should early return.

I can confirm the [latest event](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11528137/events/69865274/) from triage is also a Stripe customer.
