### ISSUE TITLE
Storybook story grouping is broken

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9326]
Looks like Storybook is no longer grouping stories by components and pages:

![](https://user-images.githubusercontent.com/6392049/119164563-90765900-ba2a-11eb-9ada-d7eaf1464167.png)

I think the fix here is to replace the vertical pipe `|` with a forward slash `/` in all story names.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3575)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Oh, yeah, thanks for filing this - I meant to after the upgrade but forgot. Looks like they revamped to support only / as hierarchy delimiter, but also added some options for sorting: https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
