### ISSUE TITLE
Upgrade fxa-react from React 16 to 18

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9332]
This requires some changes to Portal

see #8513 / #12736 for list of failed tests

We also have React as a dependency in fxa-content-server. I think this is because we have fxa-react and fxa-settings as workspace dependencies - if this ticket is finished after the fxa-settings React upgrade, let’s try to upgrade React in content-server here. If there’s hiccups, file a separate issue for it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3587)

**Comment by LZoog** [comment]
We should try to upgrade to the latest major version if we can, which at this moment is 18.

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Lauren Zugai  which package is this for?

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Just for posterity reasons to answer the previous comment, I’ve modified the title; this one’s for fxa-react.

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

In addition to the Portal component, I believe this also requires updates to the InputText component as well - see failing CI tests ( https://github.com/mozilla/fxa/pull/13203 ) (test-content-server-2, 3, and 4).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
