### ISSUE TITLE
Accept and handle 2FA push notification (Desktop client)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9335]
We will need to add support in the desktop [rust.rs]([https://searchfox.org/mozilla-central/source/third_party/rust/fxa-client/src/push.rs#10)](https://searchfox.org/mozilla-central/source/third_party/rust/fxa-client/src/push.rs#10)) to accept and process our 2FA push notifications. This will allow Firefox desktop clients to correctly verify these messages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3582)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Some additional notes that might help improve the user experience of this feature

  * Possible show users what devices were sent notifications
  * Only open tab if the user clicks notification
  * Have option for user to choose the verification method

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
