### ISSUE TITLE
“WebSocket unexpectedly closed” error displayed on “Pairing not successful” page on desktop

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9340]
**Build:**
Stage (Train 1.206.0)

**Affected platforms:**
Windows 10 64-bit
macOS 10.14.6

**Preconditions:**
The user must be signed in on Firefox Sync on a computer.

**Steps to reproduce:**

1. On a mobile device go to Settings -> Turn on Sync.
1. Tap on “Ready to scan“ button. 
1. Switch to the computer and navigate to https://accounts.stage.mozaws.net/pair.
1. Click on “Show code” button.
1. Scan the pairing code using the device.
1. On mobile tap on “Cancel” button.
1. Go to desktop and wait 5 minutes.

**Actual result:** 
“WebSocket unexpectedly closed” error message is displayed on desktop.

**Expected result:** 
A more intuitive message is displayed.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3591)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15147/error+pairing+not+successful.PNG">error pairing not successful.PNG</a>

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
