### ISSUE TITLE
Image in verification code screen is innaccurate

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9343]
The envelope in the image has a link but we send a code so it's not accurate. This is something that would drive a UX person crazy.

Not high priority but logging so that we fix this when we have UX resources.

!image-2021-06-02-15-37-52-272.png!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3612)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15151/image-2021-06-02-15-37-52-272.png">image-2021-06-02-15-37-52-272.png</a>

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg: Low priority and will need some ux

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
