### ISSUE TITLE
[subplat] Payment charges not found in subscription payment intent on subscription creation.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9344]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/8957034/?referrer=github_plugin

```
Payment charges not found in subscription payment intent on subscription creation.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3593)

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

Benjamin Bangert We saw this was marked as resolved during out subplat triage today, can you add some context to the issue here or close this issue if no longer valid. Thank You 😀

**Comment by clouserw** [comment]
Sentry issue: [FXA-AUTH-PROD-6R](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/8957034/?referrer=github_plugin)

**Comment by biancadanforth** [comment]
On the [latest of these errors](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/8957034/?query=is%3Aunresolved), it looks like the user had to do SCA. 

I picked [another error event](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/8957034/events/685b2078c5334760822742fbfc8e6030/) from this group in Sentry at random, and it looks to similarly have required SCA.

Is it possible we are throwing these errors every time someone has to do SCA to subscribe?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Possibly the same issue as FXA-4202?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

https://dashboard.stripe.com/payments/pi_3KsX4FJNcmPzuWtR1jL2fRSR ( https://dashboard.stripe.com/payments/pi_3KsX4FJNcmPzuWtR1jL2fRSR ) as an example shows the authentication succeeded but the bank declined the subscription.

This particular case seems like a legit reason. Are the previous errors also declined for legit reasons?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
