### ISSUE TITLE
Perform security audit for 2FA via push

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9346]
The last security aduit was done a couple years ago. Lets follow up with the team and make sure everything is still good to go.

Ref feature doc: https://docs.google.com/document/d/16fdARc6MC9XO7FBG9YJ4bpeqhHcv1G3ua0uzeS4EckY/edit#

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3586)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
