### ISSUE TITLE
Return JWTs for access tokens

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#935]
There is this new [draft spec to return JWT formatted access tokens](https://tools.ietf.org/html/draft-bertocci-oauth-access-token-jwt-00). 

JWT access tokens have a bunch of nice properties such as:

* The can be signed by us and can be validated by RPs without requiring a hit on our DB.
* They contain a bunch of metadata that can be used directly by the RP without involving us.
* In theory nothing would need to be stored in the DB, though revocation becomes more difficult.
* We can add arbitrary data in the access token w/o needing to add new fields in the DB.
* We could make usage more secure by combining them with [Proof-of-Possession Key Semantics for JSON Web Tokens (JWTs)](https://tools.ietf.org/html/rfc7800), though we might be able to do something similar w/o JWTs using the [OAuth 2.0 Proof-of-Possession: Authorization Server to Client Key Distribution](https://tools.ietf.org/html/draft-ietf-oauth-pop-key-distribution-07) spec.

Another downside to this if RPs do not need to hit one of our endpoints to verify an access token, [counting MAU](https://github.com/mozilla/fxa-auth-server/issues/2957) becomes more difficult. 

Perhaps both the counting and revocation problems can be worked around by making access tokens be short lived (on the order of minutes), forcing RPs to use a refresh token to get new access tokens.

**Comment by lmorchard** [comment]
Thing that came to mind when I thumbs-up'd this last week: Would this be an interesting place to someday include subscription capabilities as a claim? That way an RP wouldn't need to immediately follow up login with a request to userinfo on the profile server if they wanted to refresh their local understanding.

**Comment by shane-tomlinson** [comment]
> Would this be an interesting place to someday include subscription capabilities as a claim?

Possibly, yeah. JWT access tokens are modeled heavily on OIDC id_tokens which are allowed to have extra claims. I can see it being in both really.

**Comment by shane-tomlinson** [comment]
@dannycoates here's the original JWT access token bug.

**Comment by clouserw** [comment]
@dannycoates what's the status of this?  We're going to move it to Milestone 140
