### ISSUE TITLE
Prevent unverified deletes if the user has a stripe account.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9353]
Currently the /create account route will delete unverified accounts if the same email exists. We should prevent this behavior if there's an unverified account with a stripe account linked to ensure we don't delete paying customers that haven't finished setting up their account.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3601)

**Comment by biancadanforth** [comment]
Closed via #9775 . This got mixed up with the Jira cloud migration.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Bianca Danforth Is there a way for QA to check this? Thanks!
