### ISSUE TITLE
Unverified Account error in graphql-api

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9364]
Pretty sure we shouldn't be seeing these...

https://sentry.prod.mozaws.net/operations/fxa-graphql-prod/issues/10467421

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3638)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Benjamin Bangert is this something you can look at next sprint?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Sure.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Ben has added diagnostics in a related issue (see github link). Danny ran a functional test for this last week which worked, the graphql application error didn’t appear on main that time, so it would be interesting if this is fixed. Ben will continue to investigate.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Benjamin Bangert any change here?  Danny is thinking this may be fixed and he could verify/close this.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I think train 224 has a diagnostic addition. The error still seems to be happening in prod, so we should see what happens on the next release first.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Benjamin Bangert any updates here?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

It’s still happening, a few times a day. This could definitely be in the current sprint.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
