### ISSUE TITLE
WError: Email account hard bounced

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9367]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11127698/?referrer=github_plugin

```
WError: Email account hard bounced
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/error.js", line 773, in Function.AppError.emailBouncedHard
    return new AppError(
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/senders/email_service.js", line 76, in marshallBounceError
    return error.emailBouncedHard(bouncedAt);
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/senders/email_service.js", line 62, in marshallError
    return marshallBounceError(body.errno, body.bouncedAt || body.time);
  File "/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/senders/email_service.js", line 49, in Request._callback
    err = marshallError(res.statusCode, body);
...
(11 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3643)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

We investigated the Stripe events from the customer that triggered https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11127698/events/66932439/ and found that all the webhook events that could've caused that error had successful responses.

This means that:

  * we are not responding with an error when an email hard bounced occurred?
  * that particular customer might not have received his recurring payment invoice email ("SubsequentInvoice" in the email templates)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

In handleInvoicePaidEventwe return in a catchinstead of rethrowing, so Stripe didn't get an error response for the webhook event that had an email bounce.

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-B0](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11127698/?referrer=github_plugin)

**Comment by biancadanforth** [comment]
Reopening, as we want to follow-up with legal on what our policy is for hard bounced invoice emails. @clouserw

**Comment by biancadanforth** [comment]
Talking about this with Ben, ideally, we don't want to be throwing 400s for hard bounces here. In the case of a 400 from a Stripe webhook event, a 40x error implies that there is something wrong with Stripe's request, but there's nothing Stripe can do to fix this.

That does beg the question though -- how do we want to capture email bounces? @vbudhram or @dannycoates would either of you have insight into why this was a 400 in the first place and what alternatives might be? It's not a 500 either...

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Wil Clouser do we have next steps for this?

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

For the purposes of this issue, please ignore the first paragraph of my most recent comment ( https://mozilla-hub.atlassian.net/browse/FXA-3643?focusedCommentId=444264 ); we respond with a 200 for email hard bounces for Stripe webhooks already (and IIRC the error here is not from a Stripe webhook anyway). We do need to respond to email complaints with a 200, but that is handled by https://mozilla-hub.atlassian.net/browse/FXA-3777 ( https://mozilla-hub.atlassian.net/browse/FXA-3777|smart-link ).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I met with the legal team today.  We want to explore some UX options here and we’ll have some meetings to do that in the future.

The only action for this issue right now is that it would be nice to be able to see how many bounces we’re seeing for people with subscriptions.  Is there a dashboard for that?  (Will the Sentry report capture them all?)

**Comment by clouserw** [comment]
This is something we should address.  I wrote a document to collect the current context and group options together.  We should come up with a good path forward here and an engineer can lead the charge on getting this closed out.  

https://docs.google.com/document/d/1lXa6ZwxtyXbzB-YQOr0HuRRwtKzqE2etiWUwEN9IRok/edit#

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
