### ISSUE TITLE
Tracking Issue for Firefox Lockbox -> Firefox Lockwise

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#937]
_This issue is time sensitive_.

**Firefox Lockbox** will change to **Firefox Lockwise**. Team is targeting a launch day of **5/21**.

Current understanding that Lockwise will continue to use the FxA Client ID.

We will need to change the following FxA-side stuff for this update: 
- [ ] All references to the name Firefox Lockbox in all FxA repos will need to be updated.
- [ ] The Lockbox Icon used in Settings needs to be updated.

We should also consider doing a production deployment shortly before the Lockwise release to align with that team.

**Comment by shane-tomlinson** [comment]
> All references to the name Firefox Lockbox in all FxA repos will need to be updated.
> The Lockbox Icon used in Settings needs to be updated.

We'll want to add Lockwise icons/CSS while leaving Lockbox icons/CSS in place until after the migration. Having both available will smooth out the transition period and ensure an icon is always available. The train after the name has changed, we'll be able to remove the old CSS/icons.

**Comment by shane-tomlinson** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1547323 to change the names on the OAuth server associated with Lockbox to "Firefox Lockwise".

**Comment by johngruen** [comment]
@shane-tomlinson here's the lockwise SVG glpyh for settings

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32"><defs><symbol id="a" data-name="[Icon] Glyph" viewBox="0 0 80 80"><path d="M76.46 30.15A312.48 312.48 0 0 0 49.84 3.53a15.47 15.47 0 0 0-19.69 0A312.48 312.48 0 0 0 3.53 30.16a15.47 15.47 0 0 0 0 19.69 312.48 312.48 0 0 0 26.63 26.62A14.87 14.87 0 0 0 40 80a14.93 14.93 0 0 0 9.88-3.56c4.9-4.42 9.37-8.69 13.68-13.07a4.45 4.45 0 0 0-.34-6.11L50 44.93a15.18 15.18 0 0 0 5.08-12 15.4 15.4 0 0 0-14.4-14.64 15.2 15.2 0 0 0-11.36 4.16 15.28 15.28 0 0 0 .3 22.48l-4.78 4.33A3.86 3.86 0 0 0 30 55l5.29-4.8.14-.13a7.24 7.24 0 0 0 2.11-5.43A7.34 7.34 0 0 0 35 39.35a7.58 7.58 0 1 1 9.77 0 7.39 7.39 0 0 0-2.62 5.32 7.25 7.25 0 0 0 2.11 5.4l.09.09 11.1 10.4c-3.4 3.37-6.94 6.71-10.71 10.13a7.89 7.89 0 0 1-9.46 0 307.34 307.34 0 0 1-26-26 7.91 7.91 0 0 1 0-9.46 304.52 304.52 0 0 1 26-26 7.89 7.89 0 0 1 9.45 0 304.52 304.52 0 0 1 26 26 7.89 7.89 0 0 1 0 9.45c-1.33 1.5-2.66 3-4 4.37a3.85 3.85 0 1 0 5.67 5.22c1.32-1.43 2.68-2.93 4-4.47a15.47 15.47 0 0 0 .06-19.65z" fill="#20123a"/></symbol></defs><g data-name="Layer 2"><use width="80" height="80" transform="scale(.4)" xlink:href="#a" data-name="Layer 1"/></g></svg>
```
