### ISSUE TITLE
Remove support for verifying secondary email with a link

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9373]
With the migration to new settings, users no longer have a view where they can verify a secondary email using a link. Lets remove all the dead code. 

Routes impacted

* /recovery_emails/verify_code
* /recovery_email

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3633)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
