### ISSUE TITLE
profile-server - Error: Unspecified error

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9376]
https://sentry.prod.mozaws.net/operations/fxa-profile-prod/issues/7710627/?referrer=github_plugin

```
Error: Unspecified error
  File "/fxa/packages/fxa-profile-server/lib/error.js", line 50, in Function.from
    var err = new AppError(obj);
  File "/fxa/packages/fxa-profile-server/lib/batch.js", line 83, in null.<anonymous>
    throw AppError.from(res.result);
  ?, in runMicrotasks
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3639)

**Comment by clouserw** [comment]
Sentry issue: [FXA-PROFILE-PROD-15](https://sentry.prod.mozaws.net/operations/fxa-profile-prod/issues/7710627/?referrer=github_plugin)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
