### ISSUE TITLE
Make Pocket a trusted oauth client

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9377]
To support https://jira.mozilla.com/browse/FXA-3478, we need to set the `trusted` property for the client in db to true.

The pocket client ids are 

Pocket web

749818d3f2e7857f

Pocket mobile
7377719276ad44ee

Lets do this for FxA stage first and then verify that pocket works as expected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3642)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Jon Buckley when you get a chance can you change this for these clients in stage?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Done:
MySQL [fxa_oauth]> select name, hex(id), trusted from clients where id in (0x749818d3f2e7857f, 0x7377719276ad44ee);
+--------+------------------+---------+
| name   | hex(id)          | trusted |
+--------+------------------+---------+
| Pocket | 7377719276AD44EE |       0 |
| Pocket | 749818D3F2E7857F |       0 |
+--------+------------------+---------+
2 rows in set (0.01 sec)

MySQL [fxa_oauth]> update clients set trusted = 1 where id in (0x749818d3f2e7857f, 0x7377719276ad44ee);
Query OK, 2 rows affected (0.00 sec)
Rows matched: 2  Changed: 2  Warnings: 0

MySQL [fxa_oauth]> select name, hex(id), trusted from clients where id in (0x749818d3f2e7857f, 0x7377719276ad44ee);
+--------+------------------+---------+
| name   | hex(id)          | trusted |
+--------+------------------+---------+
| Pocket | 7377719276AD44EE |       1 |
| Pocket | 749818D3F2E7857F |       1 |
+--------+------------------+---------+
2 rows in set (0.00 sec)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Verified that pocket is indeed a trusted client and no longer gets prompted for permissions.

Jon Buckley could you set the redirectUrl to https://fxa-staging.web.readitlater.com/ff_auth ( https://fxa-staging.web.readitlater.com/ff_auth|smart-link ) for pocket on stage?

**Comment by vbudhram** [comment]
@jbuck We should be good to toggle the trusted client values in production 👍🏽

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

MySQL [fxa_oauth]> select hex(id), name, redirectUri ,trusted from clients where name = 'Pocket';
+------------------+--------+-------------------------------+---------+
| hex(id)          | name   | redirectUri                   | trusted |
+------------------+--------+-------------------------------+---------+
| 7377719276AD44EE | Pocket | pocket://oauth/fxa            |       0 |
| 749818D3F2E7857F | Pocket | https://getpocket.com/ff_auth |       0 |
+------------------+--------+-------------------------------+---------+
2 rows in set (0.00 sec)

MySQL [fxa_oauth]> update clients set trusted = 1 where name = 'Pocket';
Query OK, 2 rows affected (0.01 sec)
Rows matched: 2  Changed: 2  Warnings: 0

MySQL [fxa_oauth]> select hex(id), name, redirectUri ,trusted from clients where name = 'Pocket';
+------------------+--------+-------------------------------+---------+
| hex(id)          | name   | redirectUri                   | trusted |
+------------------+--------+-------------------------------+---------+
| 7377719276AD44EE | Pocket | pocket://oauth/fxa            |       1 |
| 749818D3F2E7857F | Pocket | https://getpocket.com/ff_auth |       1 |
+------------------+--------+-------------------------------+---------+
2 rows in set (0.00 sec)MySQL [fxa_oauth]> select hex(id), name, redirectUri from clients where name = 'Pocket';
+------------------+--------+---------------------------------------+
| hex(id)          | name   | redirectUri                           |
+------------------+--------+---------------------------------------+
| 7377719276AD44EE | Pocket | pocket://oauth/fxa                    |
| 749818D3F2E7857F | Pocket | https://staging.getpocket.com/ff_auth |
+------------------+--------+---------------------------------------+
2 rows in set (0.00 sec)
MySQL [fxa_oauth]> update clients set redirectUri = 'https://fxa-staging.web.readitlater.com/ff_auth' where id = 0x749818D3F2E7857F;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MySQL [fxa_oauth]> select hex(id), name, redirectUri from clients where name = 'Pocket';
+------------------+--------+-------------------------------------------------+
| hex(id)          | name   | redirectUri                                     |
+------------------+--------+-------------------------------------------------+
| 7377719276AD44EE | Pocket | pocket://oauth/fxa                              |
| 749818D3F2E7857F | Pocket | https://fxa-staging.web.readitlater.com/ff_auth |
+------------------+--------+-------------------------------------------------+
2 rows in set (0.00 sec)
