### ISSUE TITLE
Track CWTS screen view in Amplitude

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#938]
When a user sees the choose what to sync screen during a registration, we should log a view and the choices submitted.

**Add**
`fxa_reg - cwts_view`
`fxa_reg - cwts_submit`

I added them to the taxonomy doc with proposed properties:
https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055

I think the main _user property_ that would be different is `cwts_reg` for `fxa_reg - cwts_submit`. I would like to log an array of the engines left enabled when they submitted.

I'm filing this in response to a Slack conversation around confirmation codes between @ryanfeeley and @shane-tomlinson 

CC @irrationalagent -> Make alternative proposal to this taxonomy and event names.

**Comment by davismtl** [comment]
@irrationalagent do you think that this would help better understand the drop off in our funnel? Relevant to Trailhead?

**Comment by irrationalagent** [comment]
I'll look to see if we log in this in redshift

**Comment by irrationalagent** [comment]
Looks like we have [events for views but not for engage](https://sql.telemetry.mozilla.org/queries/62867/source#161319). If these are important to have in amplitude, I could probably look into it and put up a PR.

**Comment by ryanfeeley** [comment]
@irrationalagent It's great to know how users interact with this screen because verifying the email submits the form as is (or perhaps submits it with all checked).

**Comment by philbooth** [comment]
> If these are important to have in amplitude, I could probably look into it and put up a PR.

Fwiw I think there's three parts to this, if you do decide to tackle it:

- [ ] Import and use `FlowEventsMixin` in `app/scripts/views/choose_what_to_sync.js`. That should be sufficient to generate the engage and submit events on the client side.

- [ ] Optionally add `data-flow-event` attributes to `<a>` tags in `app/scripts/templates/choose_what_to_sync.mustache` if you want track clicks on them.

- [ ] Update the definition of `VIEW_ENGAGE_SUBMIT_EVENT_GROUPS` in `server/lib/amplitude.js`.

**Comment by irrationalagent** [comment]
thanks as always for the guidance @philbooth if I can clear my plate in the next few day's I'll assign this issue to myself.

**Comment by philbooth** [comment]
Put my face on this and opened some PRs because it was a small chunk of work and I'm trying not to leave anything big unfinished before going on PTO.

**Comment by irrationalagent** [comment]
I appreciate it @philbooth I just didn't have time to get to this. this will be very helpful

**Comment by philbooth** [comment]
So this landed in train 139, although I'm mildly suspicious about the data. According to Amplitude nobody has unselected any of the options (or if they have, it balances out so the aggregate totals are exactly the same for every case):

https://analytics.amplitude.com/mozilla-corp/chart/gudnhlq

**Comment by philbooth** [comment]
This is the funnel for the CWTS screen:

https://analytics.amplitude.com/mozilla-corp/chart/w1zjarn

**Comment by irrationalagent** [comment]
> So this landed in train 139, although I'm mildly suspicious about the data. According to Amplitude nobody has unselected any of the options (or if they have, it balances out so the aggregate totals are exactly the same for every case):
> 
> https://analytics.amplitude.com/mozilla-corp/chart/gudnhlq

might it be because of this 
https://github.com/mozilla/fxa/blob/bb3880cdc81758775fba69b3c8e7bcea03f123bf/packages/fxa-content-server/app/scripts/views/choose_what_to_sync.js#L98

I think `offeredSyncEngines` is a constant array that doesn't change contingent on what the user selects. Maybe you have to take set difference of `offeredSyncEngines` and `declinedSyncEngines` @philbooth

**Comment by philbooth** [comment]
> might it be because of this

Doh, you're right, thanks. I should have caught this at the time, sorry, I was rushing it before PTO.

Will fix.

**Comment by philbooth** [comment]
This was done in #1641, should be closed already.
