### ISSUE TITLE
[subplat] Use Stripe Prices API before Plans

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9381]
For the PR for FXA-3369, after much head scratching, we discovered (from Ben), that `this.stripe.plans.list` does not pull all plans in Stripe -- in particular, those plans that have price-specific fields (only found in the newer `Prices` API).

We need to move towards using Prices first instead of Plans.

[~accountid:5e3400fb6bd5c40ca395d189], you'd mentioned that you had attempted this in the past and things got tricksy -- do you recall anything in particular that complicated things?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3661)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
