### ISSUE TITLE
Respect Do Not Track in Amplitude Metrics Context

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9384]
We have [https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/metrics/context.js#L170-L183](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/metrics/context.js#L170-L183) to exclude some data from the request's metrics context.  However, we suspect that exclusion is not applied to the metrics context used by Amplitude in auth-server (https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/metrics/amplitude.js#L346).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3647)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg: Might not be a bug if we migrate to looker?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
