### ISSUE TITLE
Remove /confirm_signup

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9391]
With #3477, we converted most signup verifications to use verification codes instead of links. As soon as a fix for [signing in with unverified accounts](https://github.com/mozilla/fxa/issues/3459) lands, the /confirm_signup page will be obsolete and we should remove the route.

Ref #3559 to remove /confirm_signin

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-61)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@clouserw will check if this is still in use.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I looked through the last 10 days of auth server logs and didn’t see this URL hit at all.  Vijay Budhram is going to check the code also, but I think this is good to remove.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
