### ISSUE TITLE
Add "open webmail" link to signin/signup code confirmation pages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9393]
@ryanfeeley and I discussed this in Slack last week, and Ryan had a mockup already. Also pointed out by [@vbudhram in this comment](https://github.com/mozilla/fxa/pull/3477/files#r352644666).

As part of the new link, should re-add a test like the one that was removed here: https://github.com/mozilla/fxa/pull/3477/files#diff-fdd2b64cb5b6f38819d1cbedd73f8fe1L75

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-68)

**Comment by data-sync-user** [comment]
➤ John Gruen  commented:

@ryanfeeley can u add ur mockup to the issue?

**Comment by data-sync-user** [comment]
➤ Ryan Feeley commented:

Strangely I am not seeing the Open in Gmail button when I register a new account using a Gmail address. Is this feature busted @clouserw ?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
