### ISSUE TITLE
Allow users to revoke signup from verification email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9394]
There are probably some number of accounts that are created by people who do not own the address being signed up for, e.g., bots, attackers. Adding a link to the email that allows users to immediately revoke the signup would allow us to immediately delete the account as well as provide additional signals to customs/dataflow to minimize fraud.

ref #1038 as part of the same discussion

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-77)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

There will be some trade off to complexity of our emails (eg. will people click the wrong link?  or give up reading more text?).  Marking needs:ux to either support or close this.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
