### ISSUE TITLE
Remove /confirm_signin, complete_signin

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9400]
With #3536, signin codes are sent everywhere and signin links are no longer used. Is there any chance of users being sent to /confirm_signin? If not, we should remove the route!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-62)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I don’t see /confirm_signin anywhere but I do wee a link to /complete_signin in the verifyLogin email template and it looks like we still send those emails today.  

Vijay Budhram can you let us know what you find for these URLs and if they are safe to delete.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
