### ISSUE TITLE
[Train 137] Primary and the secondary account is the same after tapping on "refresh status"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9403]
Environment:
iOS - iPhone SE(12.1.4), Android, Win
Stage server - Train 137

Steps to reproduce:

1.Log in with a Firefox account on all platforms.

1. Go to manage account page -> Secondary email.
1. Add and verify the new secondary email.
1. Tap on "Make primary" on desktop.
1. On iOS and Android tap on "Refresh status".

Expected results: The secondary account is now the primary account.

Actual results: The primary and secondary account is the same.

Video:
https://drive.google.com/open?id=1Z0WX_At6AGZFkAfaWYwFg8EXbP59ZYFM

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-90)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@vbudhram to investigate.  Are we sure this wasn't just slow to change?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
