### ISSUE TITLE
[payments] Pass flowId and flowBeginTime through navigateToPaymentServer

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9409]
In `packages/fxa-content-server/app/scripts/views/subscriptions_product_redirect.js` the `navigateToPaymentServer` should pass through query string parameters `flowId` and `flowBeginTime`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-192)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
