### ISSUE TITLE
[fxa-content-server] support uid as parameter in the oauth force_auth flow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9415]
Ref: https://github.com/mozilla/application-services/pull/1414#discussion_r303688182

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-203)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
