### ISSUE TITLE
Primary email bounce records prevent secondary emails being set up

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9416]
If bounce records exist for a primary email address, attempts to set up secondary email addresses fail because of the primary bounce records. This prevents people that have lost access to their primary email address from setting up a secondary account. It can be worked round on a case-by-case basis by manually clearing bounce records from the db, but we should probably tweak the logic so that the primary bounces don't fail sending to the secondary address.

(fallout from https://bugzilla.mozilla.org/show_bug.cgi?id=1554631)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-105)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
