### ISSUE TITLE
Add a /products/ route with configured default productID to product pages?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9420]
[There's currently a `/product/:productId` route in the payment pages.](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/App.tsx#L48)

Might be useful to add a `/product/` route with a default productId supplied by server config.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-84)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
