### ISSUE TITLE
[fxa-content-server] allow use of totp recovery codes in pairing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9421]
Follow up from https://github.com/mozilla/fxa/pull/1242#discussion_r288430428

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-109)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Vijay Budhram

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
