### ISSUE TITLE
Set the default ttl for JWT access tokens to 6 hours

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9431]
JWT access tokens currently have the same TTL as legacy access tokens, which is currently 2 days. The server enforced PPID rotation period is 6 hours, and the first consumer of JWT access tokens requests passes a ttl of 6 hours.

Let's match reality to the expectations and set the default ttl for JWT access tokens to 6 hours.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-210)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
