### ISSUE TITLE
Document the PPID threat model and mitigations

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9433]
Follow on for #1679. The PPID documentation touches on the PPID threat models and mitigations but needs to go into more detail. Better documentation will be especially useful for performing a security review of an entire end to end integration.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-212)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

There are some existing docs about PPID in the auth-server docs that we might be able to steal from

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
