### ISSUE TITLE
latest: Clicking Subscriptions->Manage causes an "Invalid token" error to be displayed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9438]
![](https://user-images.githubusercontent.com/848085/61455280-00ad8280-a95b-11e9-8969-3d259c628934.png)

If you ssh into latest then tail the logs for the oauth server when this happens, the response contains `"code":401,"errno":104`, this corresponds to an invalidAssertion. The line this is being thrown is [here](https://github.com/mozilla/fxa/blob/db9677a0b2c04f387dbbde48a4c52f6a4dde332d/packages/fxa-auth-server/fxa-oauth-server/lib/grant.js#L107) when checking the grant. 

![](https://user-images.githubusercontent.com/848085/61455600-e6c06f80-a95b-11e9-9621-cb65c21cad26.png)

The [`https://identity.mozilla.com/account/subscriptions` scope](https://github.com/mozilla/fxa-dev/blob/docker/roles/oauth/templates/config.json.j2#L346:L347) is configured with `"hasScopedKeys": true`, and the session is not considered verified and the error is thrown.

It seems like there are two issues at play here:

* The session isn't considered verified, which I find curious since the user just verified their email.
* That scope doesn't need scoped keys, `hasScopedKeys` should be `false`. Doing this will still allow a token to be created even if the session token creates an assertion with `fxa-tokenVerified: false`.

If I ssh into the box and flip `hasScopedKeys` from `1` to `0`, tokens can be created and I am redirected to the payments server, and then immediately redirected back.

cc @bbangert and @lmorchard

Also cc @vbudhram and @rfk

* if a user that signs up just verifies their email address, that session should be considered verified, am I correct in this assumption?

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-221)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

> I am redirected to the payments server, and then immediately redirected back.

Do you mean that if you click the "manage" button, you end up back on the content-server settings page? If so, that sounds like the access token verification failed on the payments-server side ( https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/index.tsx#L91 ). You should end up on a view to manage subscriptions

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
