### ISSUE TITLE
Send Sync emails when a user signs up/in for Fenix

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#944]
In #913 and https://bugzilla.mozilla.org/show_bug.cgi?id=1547251, the name "Fenix" is being changed to "Firefox Sync". Going along with this theme, we should also send the Sync emails instead of the standard OAuth RP emails whenever a user signs up/in to Fenix.

ref #913

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-828)
┆Issue Number: FXA-828

**Comment by clouserw** [comment]
@vladikoff how important is this?  (what train should it be in?)

**Comment by vladikoff** [comment]
We should take a look at the current emails to check if it is at all confusing.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
