### ISSUE TITLE
Publish to the notification stream whenever an access token is destroyed

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9455]
So that the event broker can notify SPs whenever an access token is destroyed, a notification will need to be sent to the notification stream that the event broker can listen for. The catch is the event will have the access token embedded within it, so we only want this notification going to the event broker and not all the other SPs connected to the SQS stream.

blocks #2140 

cc @bbangert

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-284)

**Comment by data-sync-user** [comment]
➤ Shane Tomlinson commented:

I tentatively put a "5" estimate on this because the OAuth server would be responsible for issuing the events, and AFAICT, the OAuth server only listens to events from SQS, it doesn't publish. Once the OAuth and Auth servers are merged, then that issue goes away since the auth server does publish to SQS.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

It's possible we could filter this via SNS topic/subject filtering

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
