### ISSUE TITLE
Convert remaining fxa-shared files to typescript

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9458]
Files to convert

* [ ] metrics/amplitude.js @vbudhram 
* [ ] redis/index.js
* [ ] redis/connection.js @chenba 
* [ ] redis/pool.js
* [ ] l10n/supportedLanguages
* [ ] oauth/scopes.js @dannycoates 
* [ ] feature-flags/index.js @dannycoates 
* [ ] scripts/feature-flags.js @dannycoates

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-298)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
