### ISSUE TITLE
Advertise CDN and avatar domains in openid-configuration

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9459]
The secure proxy allows all FxA endpoints to bypass the proxy so that users are able to sign in to FxA while the proxy is enabled but before an access token has been created. Right now the values for the CDN and avatar domains are hard coded making it difficult for them to test against other FxA stacks, e.g., stable or stage. If we advertised these domains in our authorization server metadata, the proxy would not need to hard code the values.

While [the Authorization Server Metadata spec](https://tools.ietf.org/html/rfc8414#section-2) does not define any parameters for this purpose, it does say additional parameters are allowed:

> Additional authorization server metadata parameters MAY also be used.
   Some are defined by other specifications, such as OpenID Connect
   Discovery 1.0 [OpenID.Discovery].

cc @bakulf

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-318)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
