### ISSUE TITLE
Randomize the access token lifetime

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9464]
To reduce 'thundering herd' effects due to mass token expiration, we could introduce randomness into the access token lifetime.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-374)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
