### ISSUE TITLE
[fxa-auth-server] Clean up refresh_token and access_token if code exchange request fails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9466]
Ref https://github.com/mozilla/fxa/pull/2442#discussion_r323992677

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-349)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
