### ISSUE TITLE
escape should close select widget, not leave the Support page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9467]
Visit https://accounts.stage.mozaws.net/support focus the What do you need help with select widget, arrow down to an option in the select list and hit escape. Escape should collapse the options in the select list but instead it takes the user to their Settings page at https://accounts.stage.mozaws.net/settings

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-289)

**Comment by data-sync-user** [comment]
➤ asadotzler commented:

Just realized that hitting Escape leaves the page no matter what has focus so it's probably not an issue with the select widget.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
