### ISSUE TITLE
[fxa-auth-server] Check whether origSessionToken belongs to the same user

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9469]
Ref https://github.com/mozilla/fxa/pull/2442#discussion_r323993852

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-350)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
