### ISSUE TITLE
Log `info` level alerts via statsd instead of Sentry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9470]
This came up in our meeting today -- we have several events we log to Sentry at an `info` level which are, by far, the most active issues there  Eg.  "Wrong password entered".  That's interesting data, but it doesn't need to be in Sentry -- it would be better suited to be in Amplitude and Redshift.  Let's push `info` level events to one or both of them and stop logging them to Sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-293)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

* @jrgm @jbuck for visibility

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Let's use statsd to log these and they'll show up in influxdb/grafana.

/cc @meandavejustice

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Deleting these would be fine

**Comment by clouserw** [comment]
@vbudhram does this patch stop the events from going to Sentry?  I think this converts them to errors, but if they are non-actionable we should just drop them and not sent them anywhere.
