### ISSUE TITLE
Document any special permissions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9471]
Does the accounts.firefox.com domain (or related domains) have any special permissions or is it on any special allowlists (eg. in browser code)?  I don't know the answer, but it feels like something we should have written down if it does.  /cc @rfk @vladikoff

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-354)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Both Firefox Desktop and Fennec will listen for webchannel messages ( https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/docs/relier-communication-protocols/fx-webchannel.md ) from accounts.firefox.com and will update browser state accordingly. So it has the special ability to control the signed-in state of those browsers, a capability that is not available to other websites.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

test message.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
