### ISSUE TITLE
Document conventions for new code

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9473]
I also found an old note in our retrospective notes about wanting to document conventions for our new code.  Is that written down somewhere?  Or do our linters/typescript pretty much define that now?

I can pull this into the ecosystem docs if we have something.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-379)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
