### ISSUE TITLE
[fxa-auth-server] attach sessionTokenId to tokens and refreshTokens

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9477]
![image](https://user-images.githubusercontent.com/128755/64743001-4191c580-d4cc-11e9-9a97-e1c47f059681.png)

Ref: https://github.com/mozilla/fxa/pull/2442#pullrequestreview-286659709

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-346)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
