### ISSUE TITLE
[fxa-auth-server] attach refreshTokenId to tokens

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9478]
![image](https://user-images.githubusercontent.com/128755/64743024-54a49580-d4cc-11e9-9707-defa4e13d5be.png)

Ref: https://github.com/mozilla/fxa/pull/2442#pullrequestreview-286659709

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-347)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Right now access tokens don't know what refresh token they came from so if a person deletes a refresh token it doesn't delete the access token (we just have to wait for it to expire).

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

This change would be in service of https://github.com/mozilla/fxa/issues/1249, where we want to delete all the access tokens when deleting a refresh token.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
