### ISSUE TITLE
Document how caching works

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9479]
Lately we've hit some rough patches here.  Let's write down what we know (or what we think we know) so at least we're all starting on the same page.

* What are we caching?  Why?
* How do we invalidate the caches?
* How long before they expire?
* What platforms (redis?)?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-353)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
