### ISSUE TITLE
Review connection pooling

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9481]
It was noted during the downtime that FxA was reaching the database pool connection limits.

We are opening and maintaining a bunch of connections to the database pool.  That's probably by design, but let's make sure, and let's also note what the limits are.

@jbuck @jrgm can you tell us what the limits are set at and what you'd like us to limit the application to?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-442)

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

I think the most important change would be setting a queueLimit ( https://github.com/mysqljs/mysql#pool-options ), as it's currently set to queue an unlimited number of queries. If we limited that to something like... 100? (idk, I should really get some production data on this) the oauth server wouldn't fall over so hard

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
