### ISSUE TITLE
Run production build after compiling TypeScript

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9483]
The event-broker (and now the content-server) use TypeScript. To build our Dockerfiles, we removed the `--production` flag as a quick hack. What we should do is run the typescript build, then remove node_modules and run npm with the `--production` flag.

Note [some advice on building TypeScript lean containers](https://medium.com/@ankit.wal/the-why-and-how-of-multi-stage-docker-build-with-typescript-example-bcadbce2686c).

#2944 includes one quick-fix that should be undone to use this pattern.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-449)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
