### ISSUE TITLE
Add autofocus of password field on Android

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9485]
We recently accidentally enabled the autofocus of the password field on iOS. We were under the impression that it would be a bad user experience since it opens up the keyboard automatically.

To our surprise, we observed the opposite and it seems to have been quite beneficial. See:
https://github.com/mozilla/fxa/issues/3040#issuecomment-544722110

Let's learn from this accidental win and turn on the autofocus on Android too now.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-473)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

On my actual iPhone (X on iOS 13), it doesn't appear to pull up the keyboard automatically, just the focus and a prompt that covers part of the form. 🤔

https://user-images.githubusercontent.com/13018240/67299708-a1f42980-f4b2-11e9-8cf0-650c7947c425.jpg

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Need to dive back in to data because it doesn't seem like iOS is auto-focusing properly which makes me question why the rates improved on iOS.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
