### ISSUE TITLE
Audit published npm packages

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9487]
## Description
We should audit the published fxa npm packages to get rid of any out of date ones.

https://www.npmjs.com/search?q=fxa

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-479)

**Comment by vbudhram** [comment]
I've gone ahead and deprecated the repos I have access too (hapi-fxa-oauth, fxa-js-client, fxa-geodb, fxa-pairing-channel). It looks like rfk and danny have access to the others. I will see if I can get access.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks Vijay.  Closing others would be great, but I’m going to mark this as done.  We don’t need to track this anymore.
