### ISSUE TITLE
In Devices & Apps use the envelope icon for email preferences

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9490]
We currently don't have an icon for email preferences:
![image](https://user-images.githubusercontent.com/68213/66319029-640bd880-e8ea-11e9-9d82-28dc087c4cae.png)

But, lo and behold, we have something in the oven ready for just such an occasion:
https://design.firefox.com/icons/viewer/#mail

![image](https://user-images.githubusercontent.com/68213/66319160-9f0e0c00-e8ea-11e9-8f6b-05716de0a03c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-417)

**Comment by annasob** [comment]
it's all yours @untari

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

This issue is verified as fixed on Stage [Train 238] on Windows 10. There is an envelope icon displayed for Email preferences in 
Connected services section and there is also a link sending to Email preferences page (but on Prod).

!icon for email prefs.gif|width=1910,height=1018!
