### ISSUE TITLE
Document auth-server use of `tokenVerificationId`

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9491]
From https://github.com/mozilla/fxa/pull/2324/files#r337854336, we should really have some clear documentation around what `tokenVerificationId` is and how it is used.

Assignin myself so I don't lose track.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-491)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

If https://github.com/mozilla/ecosystem-platform/pull/39/files ( https://github.com/mozilla/ecosystem-platform/pull/39/files|smart-link )  lands, that would be a good place to add these docs.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
