### ISSUE TITLE
2FA flow is no longer prompted after returning from “Enter recovery code” page which was opened in a new tab

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9493]
**Build:**
Stage [Train 1.149.3]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**

1. Launch Firefox and attempt to log in with an account that has 2FA enabled.
1. Insert a valid email address and a valid password.
1. Click on “Sign in” button.
1. Right-Click on “Trouble entering code” link from “Enter security code” page and select to open it in a new tab
1. Click on “Back” link from “Enter recovery code” page.
1. Click on “Use a different account” link from “Enter security code” page.

**Expected results:**
“Sign in” page with an editable password field is displayed. 2FA flow starts after clicking “Sign in” button.

**Actual Results:**

* “Sign in” page with the password field hidden is displayed.
* “Confirm your account” page appears after clicking “Sign in” button. 
* The email is not received.

**Additional notes:**

* This issue also reproduces while opening “Enter recovery code” page in a new window
* This is a follow-up issue for #2764

![2FAissue](https://user-images.githubusercontent.com/18114210/67860049-a9a47580-fb25-11e9-9c5d-09dddf5fd3e0.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-502)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

@vasilicatamas thanks for report! I think there are a few things going on here. 

  * Looks like the tab should be opened with &service=synce in url but it isn't. If this is added, then it would show the correct continue to ...
  * Users that have TOTP should not have to confirm their account via email. This sounds similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1590444. It looks like a cached user is logging so maybe a weird interaction with TOTP and that.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
