### ISSUE TITLE
Reset password page is still displayed when opening “Remember password?Sign in” link in a new tab

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9495]
**Build:**
Stage [Train 1.149.3]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**

1. Launch Firefox and click on “Sign in to Firefox” option from Firefox account toolbar menu
1. Insert a valid email address and click “Continue” button.
1. Click on “Forgot password?” link 
1. Right-Click on “Remember password? Sign in” link and select ”Open Link In New Tab” option

**Expected results:**
The user is returned to “Sign in” page.

**Actual Results:**
“Reset password” page is displayed in a new tab.

**Additional notes:**
This issue also reproduces for “Open Link In New Window” option.

![reset password](https://user-images.githubusercontent.com/18114210/67956813-5b62a580-fbfd-11e9-9ac1-6bba1a3a2dc5.gif)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-508)

**Comment by data-sync-user** [comment]
➤ Shane Tomlinson commented:

This happens because we are using a link with an href of # and then doing history.popstate() to go back.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
