### ISSUE TITLE
(payments) Rethink subscription redirect page functionality for accessibility

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9496]
It is not best practice to show a page for a split second and automatically redirect the user without giving them the chance to read the page. It can be jarring for not only those with poor vision, but for users in general that are going to want to hit the "back" button to read context they think they may have missed.

a11y ref: https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-no-extreme-changes-context.html

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-467)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
