### ISSUE TITLE
Track login confirmation code events

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9500]
(forgive me if this is a dupe, I couldn't find this but I could have sworn that we had filed this already)

We don't track many metrics around the email confirmation codes. (or at least not in Amplitude)

* views of the screen to enter code
* engagement with the field to enter code
* submit of code
* error displayed
* clicks to resent code

I think that this could provide us with some valuable insights.

CC @vbudhram @irrationalagent

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-514)

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

I updated the title to login confirmation codes. We seem to have already done them for registrations:
https://github.com/mozilla/fxa/issues/3073

@vbudhram , am I correct that we just did for registrations so far?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Putting in Train 151 for the verification and investigation.  If there is work to do, we can do it in later milestones.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

> am I correct that we just did for registrations so far?

Yea this exists for registrations, https://analytics.amplitude.com/mozilla-corp/chart/nvzik06. However, it currently does not track resend events.

For login confirmations, it looks like we currently do not track the screen views and engagement in amplitude. I suspect that we do track this in redash though.

Adding the amplitude metrics for the login screen should be straight forward. I'll bump this issue to next train but can try to pick up earlier if I can.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Leaving this issue open to track resend events

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Unassigned myself but these metrics are not populated for signin confirmation codes.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
