### ISSUE TITLE
”Reconnect to Sync” notification does not appear on iOS

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9501]
**Build:**
Stage [Train 1.149.4]

**Affected platforms:**
iOS 13.1.2.

**Steps to reproduce:**

1. Login using a Firefox Account on 2 devices (desktop and iOS).
1. Change the FxA password from desktop. 
1. Check the FxA state on iOS.

**Expected results:**
The user is automatically logged out from FxA on iOS and the ”Reconnect to Sync” notification is displayed.

**Actual Results:**
The user is not automatically disconnected from Firefox for iOS and the notification is not displayed.

**Additional notes:**

* The login page is displayed when accessing the Manage Account page.
* On Firefox for iOS the user is still connected and sync does not work anymore. A logout and login using the new password solves this issue. 
* This issue was encountered during https://bugzilla.mozilla.org/show_bug.cgi?id=1589565 verification

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-524)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15025/gif15.gif">gif15.gif</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@davismtl is there a notification that should be shown in this scenario?  (Is the notification in iOS or in the browser?).  Maybe this is part of an old PRD we can reference?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

> The user is not automatically disconnected from Firefox for iOS and the notification is not displayed.

I believe that this may be because iOS is not disconnecting with push. I think it is pulling or waiting for session to expire. 

> @davismtl is there a notification that should be shown in this scenario? (Is the notification in iOS or in the browser?)

Normally there should be a notification. We do it on other devices. The disconnect is not instant though since it's not using push. That might be why it's not being seen.

I'm struggling to remember at what layer the notification is implemented. @eoger or @rfk do you happen to remember?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@eoger / @rfk  ping on this.  It sounds like there were recent (last week?) UX changes here that might be showing a different notification?  We're not sure 😀

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I don't know anything about this and I don't have the bandwidth to chase it up sorry; you could try reaching out in #firefox-ios

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Vasilica TamasIs this bug still reproducible on the current Firefox for iOS?

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Jared Hirsch the warning is still not automatically displayed neither in Prod [Train 1.203.4] but the difference is that the "Enter your password to connect" message appears after clicking on "Sync now" button. Same behavior is encountered also on Android.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
