### ISSUE TITLE
Privacy Notice from payments page is incorrectly highlighted after clicked

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9503]
#### Affected versions:
* All Firefox

#### Affected Platforms:
* Windows 10 (64-bit)
* macOS 10.14.6

#### Steps to reproduce
1. Go to the [Full-Device VPN](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page.
1. Click on the "Subscribe Now" button and make an account.
1. Click on the "Privacy Notice" or select it via the keyboard.

#### Expected result:
* The "Privacy Notice" is properly highlighted.

#### Actual result:
* The "Privacy Notice" is not properly highlighted.

![image](https://user-images.githubusercontent.com/17178945/68749934-b89c2500-0607-11ea-84a7-41322a1d7a4b.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-540)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21778">Screen Shot 2022-03-17 at 12.01.12 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

@juliastarkov can you clarify what this should look like?  It sounds like we want the border to look like that, but it needs some padding to keep the 'e' from running into the edge?

**Comment by data-sync-user** [comment]
➤ juliastarkov commented:

@clouserw I was pinged about this issues - is this still unresolved?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Hi @juliastarkov .  That shouldn't have pinged you and I don't know why it did.  We're experimenting with a syncing robot that apparently malfunctioned.  Sorry for the bother!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
