### ISSUE TITLE
Move content-server experiment base logic into fxa-shared

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9504]
While working on https://github.com/mozilla/fxa/issues/2595, I didn't want to duplicate the experiment grouping logic found in the [content-server](https://github.com/mozilla/fxa/blob/8701348cdd79dbdc9879b2b4a55a23a135a32bc1/packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/base.js#L35) to the auth-server.

I think it makes sense to pull this base class into fxa-shared and reused in both services. However, I still think the experiment rules should still live in the respective services.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-497)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

As mentioned in https://github.com/mozilla/fxa/pull/3183, I was not able to move over the base experiment.

If you pull down that PR and change https://github.com/mozilla/fxa/blob/8701348cdd79dbdc9879b2b4a55a23a135a32bc1/packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/is-sampled-user.js#L10

to be

const BaseGroupingRule = require('../../../../../../fxa-shared/dist/experiments/base');It should have in theory worked because it is loading the same javascript file. However, you will get an interesting error

Uncaught TypeError: BaseGroupingRule is not a constructorwhen you try to load the content-sever webpage. After some searching it seems to be related to https://github.com/babel/babel/issues/9367. Babel seems to fail loading the class that is outside the project causing the extends not to work correctly.

I tried updating our webpack config to ['@babel/preset-env', {modules: false}] since some posters said that worked for them, but it didn't work for us. If someone has some better webpack and babel chops is there anything obvious that I could be missing here?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
