### ISSUE TITLE
Unable to create a Firefox account using an email previously used as secondary on another account [bz1595852]

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9510]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1595852

Created attachment 9108175
firefox-new-account.jpg

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

Steps to reproduce:

Create an account and set a secondary email. Delete this secondary email and try to create a new account using it.

Actual results:

After entered the email and a new password, when I click on 'Create' the response is 'Primary account email required for signin'.

Expected results:

A new account should be created.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-538)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
