### ISSUE TITLE
Inconsistency in Expiration Date Format

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9512]
## Description
We need to keep the expiration dates consistent throughout the system. We also need them to closely match user expectation. 

### Steps to reproduce
After subscription, the subscription management page shows the expiration written out textually
![](https://user-images.githubusercontent.com/26334275/68794010-03676e00-0603-11ea-8519-57590ada290a.png)

### Expected result
We should have all expiration dates be presented in this format: XX/XXXX, so the above screenshot should say **Expires 08/2024**

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-545)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
