### ISSUE TITLE
"Reset Password" dead end flow for FxA services

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9515]
**Build:**
Prod [Train 1.150.4]

**Affected platforms:**
Windows 10 64-bit
Android 9 

**Steps to reproduce:**

1. Go to https://addons.mozilla.org/en-US
1. Click on “Register or Log in” button.
1. Click “Forgot password” button
1. Enter email and click “Begin reset”
1. Go to email and click on "Create new password".
1. Enter the same password in both fields and click on “Reset password”.

**Expected results:**
An opportunity to continue to accessed FxA service is successfully displayed on password reset confirmation page.

**Actual Results:**
Reset Password flow is a dead one when it is accessed from a FxA service.

**Notes:**
This issue also reproduces for the following entry points: Pocket, Monitor, Send, SUMO.

![Screenshot](https://user-images.githubusercontent.com/18114210/69232368-9b310300-0b93-11ea-92ea-5c6913a2d5a2.png)UNITO-UNDERSCORE!26!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-557)

**Comment by data-sync-user** [comment]
➤ Shane Tomlinson commented:

@vasilicatamas - did you verify in the same browser, or a different browser? If a different browser, redirecting back to the RP is impossible without breaking the security model of OAuth.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

> @vasilicatamas - did you verify in the same browser, or a different browser? If a different browser, redirecting back to the RP is impossible without breaking the security model of OAuth.

Both ways and the result is the same.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Update: When you click the “Create new password“ button from email the “Create new password” page is displayed in the browser in a new tab. If you complete the process then you get the dead end on that tab but on the other tab where you previously got the “Reset link was sent” page you are logged in to the correct page (Pocket, etc.)

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

“Reset password“ dead end flow happens only if the “Create new password“ page is opened in a new tab. But if the user switches tabs he can see that he is logged in to the correct page after pwd reset.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
