### ISSUE TITLE
Successfully consuming an unblockCode should mark the account as verified.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9519]
We punted on this for v1.

ref https://github.com/mozilla/fxa-content-server/pull/4154
ref https://github.com/mozilla/fxa-auth-server/pull/1471#issuecomment-251552928

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-693)

**Comment by data-sync-user** [comment]
➤ Vlad Filippov commented:

Not priority for now. We have a log for "how many people" would be affected by this.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
