### ISSUE TITLE
Change sessionStatus to request /session/status

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9522]
The reason here is that we want to clear up the semantics of finding out the status of a user's current session. There is already a route for exactly that purpose, let's use it!

Currently (in latest, not in prod), it will return these properties:

* uid
* state `'unverified' | 'verified'`

There is the expectation that the `state` will grow more states, like `bounced` or `reset`. Is there anything else that should be returned on this route?

I see that currently the `verificationMethod` and `Reason` are determined by the existence of a `emailVerified` property. Whether an account has verified their email isn't really relevant to a session, so it will no longer have that property (the existence of it is actually part of the confusion, and why we want to separate). That should probably be gotten from `/account/status` or similar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-780)

**Comment by data-sync-user** [comment]
➤ Vlad Filippov commented:

@seanmonstar @rfk please triage out of the backlog

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

@seanmonstar what do you think about bumping this out of the fxa-56 milestone?

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

@seanmonstar this is a P1 but it's in the backlog, can you please triage it out of one of those states as appropriate?

**Comment by data-sync-user** [comment]
➤ Shane Tomlinson commented:

For background, account.sessionStatus is called on any page where a "session" is required, e.g., /confirm, and /settings*. 

The verified and emailVerified response fields of /recovery_email/status are converted to verificationMethod and verificationReason so we can:

1. Determine whether the user must verify their email for any reason.
  2. If the user must verify, which "confirm your email" page should be displayed. If verificationReason===signup, the user is redirected to /confirm, if verificationReason===signin , they redirect to /confirm_signin. 
  3. Do this with one XHR request, minimizing startup load time.

The canonicalized email field returned by /recovery_email/status is also used to update the email stored in localStorage, in case the user typed in an address using incorrect casing.

I'm not against using two XHR requests for this, though it will have a slight performance hit. Most important to me is a clean mapping to existing functionality, there was a lot of grunt work getting things "just so".

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
