### ISSUE TITLE
Only ask for unblock code once in a flow

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9523]
In issue mozilla/fxa-content-server#5170 , it was mentioned that we can ask a user repeatedly to enter an unblock code if they mistype their password. Let's only ask the user once per flow/session. Perhaps it behaves like most 2FA flows and is valid for that device like 30 days. I'm open to hearing different arguments.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-690)

**Comment by data-sync-user** [comment]
➤ Sean McArthur commented:

It is a better experience.

It's a bit more complicated to do than what we do now. We have to store somewhere knowledge the user successfully answered the challenge, and that knowledge should only be valid for a short period of time, and possibly for only a certain device. So effort is high.

How often do people run in to this?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

According to the linked issue above, we got 3 reports just last week from Mozilla employees.

It's hard to tell exactly how often it is happening but it makes for a really horrible experience when it does.

The only reason I wouldn't put too much energy in this is if we expect Shane's email first flow to drastically reduce the likelihood of users encountering this flow.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

I might have some numbers. Proportionately, we seem to block the equivalent of 20% of logins [edit: this number is invalid. It was prior to April, currently 3-4%]. That seems pretty high!

Block volume: https://sql.telemetry.mozilla.org/queries/1626#2877
Signin volume: https://sql.telemetry.mozilla.org/queries/1751#3525

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> Proportionately, we seem to block the equivalent of 20% of logins

It didn't use to be anywhere near this high, have we broken something of which this uptick in reports is a symptom?

> We have to store somewhere knowledge the user successfully answered the challenge, and that
> knowledge should only be valid for a short period of time, and possibly for only a certain device

IIRC from a previous issue about this, someone suggest that we could achieve this by:

  * Making unblock codes multi-use, up to either a time threshold and/or a certain number of attempts
  * Making the content-server persist the unblock code locally and use it for all subsequent login attempts (until it actually succeeds)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> According to the linked issue above, we got 3 reports just last week from Mozilla employees

At one point we were explicitly forcing Mozilla employees through the unblock flow, but I think we've stopped that now.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Correction, it resembles more like 3-4% since April. Please ignore previous 20% mentioned.

Edit: Sigh of relief that it is not as high as I originally thought. (though, still not great)

**Comment by data-sync-user** [comment]
➤ Shane Tomlinson commented:

@rfk and @davismtl - can you triage this?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

@seanmonstar  I decided to dig in a bit more. While about 3-4% of signins are blocked, it seems like each person is getting blocked on average 2.9 times in the same flow. Although this doesn't mean they actually succeed at logging in.

https://sql.telemetry.mozilla.org/queries/5792/source (pls double check)

Seems like a pretty bad experience. Sean would you score this compared to our other things in our quality backlog? It feels like impact would be pretty low since it for a small volume of users but it would severely impact their experience.

Obviously, if we add this, we should remove something else from the backlog.

**Comment by data-sync-user** [comment]
➤ Sean McArthur commented:

Your point of people trying several times is definitely true. Trying multiple times is a poor experience.

Poking around in the signin counts ( https://sql.telemetry.mozilla.org/queries/1751/source#table ) vs sign blocks ( https://sql.telemetry.mozilla.org/queries/1626/source#table ), I see closer to a 2% block rate. That's if I look at the the count_signin_engage numbers. The difference from engage to the count_login numbers would include lots of people who failed to login, but not because they were blocked by customs.

So, I'd still weigh the impact at super low.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

I'll agree with this. Perhaps more numbers will come up that increase the priority but let's put it aside for now.

**Comment by data-sync-user** [comment]
➤ Vlad Filippov commented:

rough notes for this:

> on the auth-server add count to the unblockCodes table telling how many times they can be used, on the content-server have it remember the unblock code and re-use until it expires

**Comment by data-sync-user** [comment]
➤ Vlad Filippov commented:

WIP PR in https://github.com/mozilla/fxa-auth-db-mysql/pull/265

**Comment by data-sync-user** [comment]
➤ Vlad Filippov commented:

Also more code for this in https://github.com/mozilla/fxa-auth-server/pull/2032

**Comment by data-sync-user** [comment]
➤ Devin Reams commented:

Possibly related: while testing the OAuth flow, PI may have found a similar issue that prevents the user from signing in with an authorization code entirely (even after trying a second time): https://github.com/mozilla-lockbox/lockbox-ios/issues/662

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

There are two different problems surfaced in the bug @devinreams is linking to:
1) if you enter an unblock code following a bad password, you need to submit the password form again. We, however, keep the password field populated which means a user could repeatedly submit the bad password. (this is what QA did I believe) I believe we need to file different bug for this one. I am unsure though of the urgency of this one given a user needs to enter a bad password >10 times before experiencing this bad experience.

2) If a user gets blocked because of a bad password and enters the code we emailed, we ask them to enter their password. If you enter the RIGHT password this time, we still force you to go through an unblock flow again! This seems like a bug. In fact, I am unable to go through this flow and receive only one code. At a minimum, a user will need to unblock twice. This seems related to the theme of this github issue. This seems like a clear bug to me and penalizes people who actually successfully unblock themselves and enter the right password.

**Comment by data-sync-user** [comment]
➤ Shane Tomlinson commented:

> If a user gets blocked because of a bad password and enters the code we emailed, we ask them to enter their password. If you enter the RIGHT password this time, we still force you to go through an unblock flow again! This seems like a bug. In fact, I am unable to go through this flow and receive only one code. At a minimum, a user will need to unblock twice. This seems related to the theme of this github issue. This seems like a clear bug to me and penalizes people who actually successfully unblock themselves and enter the right password.

There was an entire discussion about this behavior when the feature was being developed, I can't find the bug now, I'll keep digging. Then there was this follow up too ( https://github.com/mozilla/fxa-auth-server/issues/1575 ). TL;DR - we've known about and discussed this behavior for a long time, just haven't done anything about it, promising ourselves we'd follow up in the future ( https://github.com/mozilla/fxa-auth-server/issues/1575#issuecomment-275500739 ).

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Ref https://github.com/mozilla-lockwise/lockwise-android/issues/849 for a user hitting this issue when signing in to Lockwise.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
