### ISSUE TITLE
Store & manage per-RP restriction on user account fields

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9524]
Related to #706 
maybe via fxa_oath.clients.allowedScopes?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-788)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
