### ISSUE TITLE
[fxa-payments-server] Add route/option that throws an error intended for Sentry to catch

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9531]
We have never had an error reported by Sentry in dev/stage/prod for payments-server, nor a way to intentionally cause an error we would expect to see. Other Mozilla projects have special URL routes that intentionally cause an error intended for Sentry to report so that QA can verify this works.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-877)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
