### ISSUE TITLE
Document the filtering properties for A/B tests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9541]
Logging a bug to capture the request from Vijay's A/B Testing workshop at All Hands Brrrlin to document all filtering properties for A/B tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-979)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
