### ISSUE TITLE
Allow Mozilla and Pocket employees to access subscriptions without paying

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9544]
We could do this in a number of ways, but the intent is as follows:

* To not force our employees to pay to test Mozilla products
* Optionally, to not force employees to have a US credit card to test Mozilla products

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-938)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
