### ISSUE TITLE
It is not clear when a user will be charged the adjusted amount for the next tier of a product

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9549]
#### Notes:
* While testing the upgrade, looking in stripe you are charged an initial 1.99 for the first tier subscription that was made. The next day when the renewal happened as we've also upgraded to the second tier a charge of 11.99 appears in Stripe, which makes sense.
* This enhancement is logged due to the fact that we are not sure if the adjusted amount is charged in the next billing cycle or is charged the next day.
* If the adjusted amount is charged in the next billing cycle this should be more clearly stated, as with the current wording users might expect for this to happen when they chose to upgrade to the next tier.

#### Affected versions:
* All Firefox

#### Affected Platforms:
* Ubuntu 19.04 (x64)
* Windows 10 (x64)

#### Preconditions
* Have a FxA account with a tier 1 subscription made on 123done.

#### Steps to reproduce
1. Open the [123done](https://123done-stage.dev.lcip.org/) page and sign into your account.
1. Upgrade to a tier 2 subscription.
1. Observe the UI.

#### Expected result:
* The wording is clear and reflects when any type of charge will be made.

#### Actual result:
* The wording does not state when the charge for an adjusted amount is made, only when he will be charged the full amount for the next tier version.

![image](https://user-images.githubusercontent.com/17178945/73923744-0907e380-48d4-11ea-9b53-e7d9e643c042.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1044)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21782">Screen Shot 2022-03-17 at 12.20.54 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

John Gruen do you want to change this text?

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Benjamin Bangert  is this charge also made immediately or is there a period of a couple of days ?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Anna Sobiepanek I believe Bianca Danforth was doing some testing of this, and we observed the following (which makes sense). If you upgrade to a more expensive plan with the same interval as your current one, the increase is tacked onto the next bill. However, if you are upgrading from a lower interval, to a higher interval (monthly -> yearly), you are charged immediately for the yearly, minus however much of the current plan you’ve used. Bianca switched from $5/mo to $50/yr, and it charged her $45, counting the $5 spent on the monthly against the yearly. I haven’t found a clear explanation of all scenarios and how Stripe determines what to do.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
