### ISSUE TITLE
Add optional link to product download page from subscription management

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9552]
Request from Dholbert that makes sense:

Let's give products the option to link back to their download pages from FxA subscription settings.

Some products have download url and some like Relay just have a web app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1131)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/21783">Screen Shot 2022-03-17 at 12.24.57 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

This will need UX once prioritized in the backlog. Removing label until then so that it doesn’t bog down the UX backlog. Thanks!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
