### ISSUE TITLE
[auth-server] Replace node-uap with ua-parser2

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9555]
The user agent string is parsed on every request, so let's replace node-upa with something that's (supposedly) faster.  There are also a few spots where regex is used to check for substrings when `includes` should work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1218)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Vladislav Filippov do you remember why auth server is using your fork of node-uap (https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/package.json#L77)?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
