### ISSUE TITLE
confidential issue [bz1619033]

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9556]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1619033

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1245)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
