### ISSUE TITLE
Account model shouldn't pass the relier into fxa-client (refactoring)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9557]
This is an optional refactoring: fxa-client really shouldn't have any knowledge of the relier object, which it currently does.

It would be cleaner not to instead have the account model extract useful keys from the relier, and pass those in as part of signinOptions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1231)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
