### ISSUE TITLE
Drop support for Firefox for iOS < 11

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#956]
The version number is somewhat arbitrary, but Firefox for IOS is now on v15. v11 was released on [April 12th, 2018](https://wiki.mozilla.org/Firefox_for_iOS_Train_Schedule), just over a year ago (from when this bug is written). v11 is the first version of Fx for iOS that supports Choose What To Sync. Let's remove support for anything below v11 and remove any supporting code.

Note, I'm not sure how we'd actually enforce this, our [checks for outdated browsers currently use the context query parameter](https://github.com/mozilla/fxa/blob/083d6e569d5b3e77c8b48b562ab2a1073552614c/packages/fxa-content-server/server/lib/routes/get-index.js#L70), maybe we'd need to check if the context is fx_ios_v1 and then do some UA sniffing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-830)
┆Issue Number: FXA-830

**Comment by clouserw** [comment]
Officially we only support the latest version: https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-dev-process#browser-support

We haven't had any reports complaining - if we get there then maybe we could update the site, but otherwise no need to worry about this right now.
