### ISSUE TITLE
The localization of the string "You've tried too many times. Try again in 14 minutes." cannot be displayed correctly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9562]
### Description
The localization of the string "You've tried too many times. Try again in 14 minutes." cannot be displayed correctly

### Steps to reproduce
1. Goto  https://accounts.firefox.com
1. Input wrong pwd for several times
1. Input wrong authorization code for several times

### Actual result
There is a tip saying "You've tried too many times. Try again in xx minutes."
This string has been localized in Pontoon, but cannot be displayed correctly on the page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1332)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/14980/Screenshot_22.png">Screenshot_22.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14981/Screenshot_25.png">Screenshot_25.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14982/Screenshot_26.png">Screenshot_26.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/14983/Screenshot_27.png">Screenshot_27.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Hi @bli-mozbj .  Thanks for filing this issue.  What are you seeing and what are you expecting to see?  What language are you using Firefox Accounts in?  Thanks.

**Comment by data-sync-user** [comment]
➤ bli-mozbj commented:

I'm using Simplified Chinese.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

No longer an issue due to Settings refresh.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is not only about the Settings page, it also includes the Sign in page where appears the "You've tried too many times. Try again in 15 minutes." message and it looks like is not translated at all in the Chinese (zh-cn) language, or partially translated in es, fr, de.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Apologies, thanks for re-opening!

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Vijay Budhram Is this related to the issue you're doing with the missing L10n?  Or maybe it's duped to that one?  We can't find it in triage 😀

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
