### ISSUE TITLE
Audit the way we are styling stripe elements in payment server

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9563]
https://github.com/mozilla/fxa/pull/4423#discussion_r388033216

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1308)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
