### ISSUE TITLE
Consider addng an auto-responder to subscription receipt emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9565]
This is not a blocker for FXA-1147, but we should consider adding an auto-responder for user responses to receipt emails and dumping emails into a google group accessable to PMs and support agents.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1380)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think this is more of an ops task than a dev task, to set up the email infra for an autoresponder. Do we have any other Mozilla sites that have an autoresponder as an example? What should the response look like?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
