### ISSUE TITLE
Oauth reliers don't update permissions in account model when using Rust Client

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9566]
The fix in https://github.com/mozilla/fxa/pull/4412 did not actually work in practice. It turns out that during the Oauth webchannel login flow the permissions don't seem to persist after login. 

Specifically for Firefox iOS, after you login, the view is dismissed. Afterwards, if you open the app and goto FxA settings, the page is loaded and the relier reports that it is not an Oauth client. The logic in #4412 fails because of this.

Note: This was tested with a local build of Firefox iOS, application services, and local FxA servers.

![](https://user-images.githubusercontent.com/1295288/76444098-d604b400-6399-11ea-8956-e3f4c7644e0f.png)

![](https://user-images.githubusercontent.com/1295288/76444320-28de6b80-639a-11ea-8210-3d16344cca4a.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1349)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
