### ISSUE TITLE
Ship Google/Apple Pay on payments page UI behind a feature flag

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9579]
This would be useful to get the UI out quickly for testing while addressing unknowns like settings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1520)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
