### ISSUE TITLE
[nav] Change the active nav tab on scroll

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9585]
When users scroll down and "Security" or "Connected Services" is primarily in view, the navigation should reflect where the user is on the page, and "Profile" when scrolling back up.

[edited by Lauren] We're using [react-scrollspy](https://www.npmjs.com/package/react-scrollspy) in Experimenter and it's working well so far. Maybe FxA Settings can use this as well?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1581)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
