### ISSUE TITLE
[nav] Allow smooth scrolling to header links

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9586]
When a user clicks on "Profile," "Security," or "Connected Services," the user should be scrolled down or up to that section smoothly.

The ideal solution would be for native CSS `scroll-behavior`, however, this [doesn't work with Safari](https://caniuse.com/#search=scroll-behavior). This likely means it doesn't work with Firefox on iOS. If this works on FF for iOS, we can move forward with this solution, however if it doesn't, we either need a JS polyfill for this behavior if it's not supported (preferred), or a JS solution all around.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1582)

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Circling back around to this issue, though I'm not sure I'm adding much more context:

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

This is a 1-liner change if we're OK with the smooth scroll not working for Safari/IE users. It's a 1 or 2-pointer if we want to add a small dependency like smooth-scroll ( https://www.npmjs.com/package/smooth-scroll ) that should work on all browsers/devices.

(I know we want to limit dependencies, but I'm sort of inclined to go with the latter)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
