### ISSUE TITLE
wrap 'import()'s in content-server app with a retry

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9588]
We see this in sentry periodically. Wrapping our dynamic `import()`s with a retry might improve this.

```
Loading chunk XX failed. (error: https://accounts-static.cdn.mozilla.net/bundle-fdac8446fb59e4d985ed1693009cebe0541f978d/vendors~fxa-common-password-list.bundle.js)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1571)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
