### ISSUE TITLE
[auth-server] Add Typescript to files in /lib/oauth/routes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9590]
This is part of a larger effort to [adopt Typescript in the Auth Server](https://jira.mozilla.com/browse/FXA-1500). It can be broken down into smaller issues if desired. This needs to be completed before [FXA-1589 (lib/oauth)](https://jira.mozilla.com/browse/FXA-1589) can be closed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1588)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
