### ISSUE TITLE
Work breakdown for FxA-49: CDN

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#96]
We have many hints that our code loads slowly for lots of users, and that moving to a CDN for our static resources would go a long way towards helping with that.  Let's figure out how to more precisely characterize the the wins we expect, and the technical approach we'll use to enable this.

Things we've talked about that need to be captured in the feature definition:

* Metrics - what will we measure right now to determine how slow things are, and what graphs will we watch to determine how things improve?
* Infrastructure details - will we use AWS cloudfront, what will this look like from our code's POV, what assets will or will not live in the CDN?
* Subresource integrity - can and will we use [1] to maintain the security of our application while putting our code outside our directly control?

[1] https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by philbooth** [comment]
If we're looking into this, should we also look into cache-friendly URLs for static assets?

If we add a hash of the contents to the file name, matching URLs can be served with a `Cache-Control: max-age=31536000` header and repeat visits to the content server would not need to download those resources at all. This may have a bigger overall effect than a CDN would (which is not to say I don't think we should move to a CDN too; we should).

**Comment by shane-tomlinson** [comment]
> If we're looking into this, should we also look into cache-friendly URLs for static assets?

Static resource URLs should be cache friendly already, and served with long lived cache headers:

![screen shot 2015-12-18 at 09 24 57](https://cloud.githubusercontent.com/assets/848085/11893531/4ed5af90-a569-11e5-9ce4-6bc1a57e35e0.png)

> This may have a bigger overall effect than a CDN would (which is not to say I don't think we should move to a CDN too; we should).

The caching is in place to help repeat visits, now we want to speed up the load time of first time visitors.

**Comment by philbooth** [comment]
Whoops, I'm sorry.

**Comment by shane-tomlinson** [comment]
@rfk - is the "work breakdown" portion of this already in progress?

**Comment by shane-tomlinson** [comment]
from mtg: @jrgm mentions that we'll have to use a subdomain to serve static resources and we should think about how we can continue to use the same RPM for both stage and prod, w/o performing a rewrite on all of the static HTML files.

**Comment by rfk** [comment]
> is the "work breakdown" portion of this already in progress?

nope, those high-level notes are as far as I got with it - this needs an owner to take on the task of actually figuring out and writing up all the details.

**Comment by rfk** [comment]
In the interests of clarity: the desired outcome for this issue is a feature card in https://github.com/mozilla/fxa/tree/master/features describing what we'll need to put in place to use a CDN, and how we'll measure its success.

@shane-tomlinson we took the liberty of assigning this to you during sprint planning meeting; don't hesitate to de-assign yourself if that doesn't seem appropriate :-)

**Comment by shane-tomlinson** [comment]
ref mozilla/fxa-content-server#3101, mozilla/fxa-content-server#3447, mozilla/fxa-content-server#3448, mozilla/fxa-content-server#3449
