### ISSUE TITLE
[header/footer] Hide header when scrolling down, show/sticky when scrolling up

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9601]
See the functionality of the header here: [https://demo2--mozilla-protocol.netlify.app/demos/navigation.html](https://demo2--mozilla-protocol.netlify.app/demos/navigation.html)

Similar to "Change the active nav tab on scroll," we will need an event listener. It would be ideal to have a single scroll event listener.

A11y note: if the header is in a hidden state and the user tabs around to an item in the header, we’ll need to make sure the header is effectively made visible. Bonus points if it doesn't trigger scrolling, and hides again when you tab back out. This can be a followup if it becomes to complicated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1690)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
