### ISSUE TITLE
[Production] accounts.firefox.com redirects to /signin instead of /settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9609]
**Affected Platforms:**
 MacOS Catalina 10.15.3

**Firefox version:**
 77.0a1 (2020-05-04) (64-bit)

**Preconditions:**
 Create an account and be signed in

**Steps to reproduce:**

1. Go directly to accounts.firefox.com
1. Observe redirect.

**Expected Results:**

User should be redirected to [https://accounts.firefox.com/settings](https://accounts.firefox.com/settings) as they are already logged in to their Firefox account

**Actual Results:**
 User is redirected to [https://accounts.firefox.com/signin.](https://accounts.firefox.com/) User must click "Sign In" to access settings.

**Notes:**

Issue initially reported by [~accountid:60482ca32b3f9a006a3b5522]. Reproduced by [~accountid:6047c5e143eac6006f71ff05] and [~accountid:6047c749ceccdd006a187c00] when testing in master, 169 and 168.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-1825)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
