### ISSUE TITLE
Create account flow does not work after changing the email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9610]
**Build:**
Prod [Train 1.169.1]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**

1. Launch Firefox with a new profile and click on the FxA toolbar menu button.
1. Click on "Sign in to Firefox (Turn on Sync)" option.
1. Type a new email address which does not have associated a Firefox Account.
1. Click “Change email” button.
1. Keep the same email address and click “Continue” button.

**Expected results:**
The user is redirected to the "Create a Firefox Account" page.

**Actual Results:**
“Continue” button loads for a few seconds but after that it becomes again available and the user is not forwarded to the next account creation step.

**Additional details:**

* This issue is also reproducible when a new email address that does not have a Firefox account associated is typed at step 5.
* This issue is not reproducible on Android 9 and iOS 13.4.1.

![account flow](https://user-images.githubusercontent.com/18114210/81048578-437a2000-8ec5-11ea-8fce-a9a154697c69.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1826)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

This is probably not major. I will try to produce the issue.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible on Prod [Train 1.170.3] under Windows 10 64bit. Closing it.

noerror ( https://user-images.githubusercontent.com/18114210/81913139-3b626480-95d8-11ea-9aab-52c864f494e7.gif )

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

I managed to reproduce this issue on FxA Stage [Train 1.172.0] using a fresh installed Fenix on Android 9. Did not encountered it on Windows and iOS. Reopening for further investigations.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

issue1 ( https://user-images.githubusercontent.com/18114210/82650787-df28c180-9c23-11ea-96f8-c0a897711003.gif )

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Update: Verified this issue on stage and production [Train 219.5] under Windows 10, Android 9 and Android 11. The issue is reproducible on all platforms but only when using email adresses with @mailinator.com domain. (Verified also with @gmail.com, @yahoo.com, @mozilla.com and these are working).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
