### ISSUE TITLE
2FA account state is not updated after 2FA is disabled

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9611]
Noticed this while testing the 2FA-required flow: if a user enables 2FA, then disables it, the acr_values=AAL2 check will still allow the user to log in until the user logs out of their account.

I suspect it's a profile caching issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1788)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Here's an earlier discussion on what sounds like the same topic: https://github.com/mozilla/fxa/issues/499

(The issue here is that the user's current login session was in fact authenticated with 2FA, so OAuth logins processed within that session do in fact meet the acr_values requirement. Probably we should downgrade the verification state of all existing sessions when the user disables 2FA on their account).

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> I suspect it's a profile caching issue.

(IOW, I'm not so sure this is a caching issue)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

Jared Hirsch is this something you wanted to  work on next sprint?

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I suggest we re-open this. #7155 fixes the issue for the sessionToken used to disable 2FA but there might still be other active sessionTokens that remain marked as being 2fa-verified.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
