### ISSUE TITLE
Let profile server verify it's own JWT access tokens

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9617]
Instead of calling out to the auth-server to verify JWT access tokens add the capability for the profile server to verify them itself. This should reduce load on the auth-server and improve request latency.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1864)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
