### ISSUE TITLE
Replace communication prefs with email prefs link

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#962]
As discussed with legal, we can remove the communication preferences section, and instead offer a link to email preferences at the bottom of fxa.
![email-preferences](https://user-images.githubusercontent.com/68213/56906871-1d7b9d80-6a71-11e9-9fc7-0f247b12689b.png)

Icon link:
https://design.firefox.com/icons/viewer/#open%20in

Position 20px to the right of the link, vertically aligned to the center of the text as depicted here:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/68213/56907140-a85c9800-6a71-11e9-873a-0a55e1151696.png">

**Comment by dannycoates** [comment]
@ryanfeeley I noticed you already changed the title of "Communication preferences" to "Email preferences". Afaict we can only link directly to the newsletter prefs on `https://www.mozilla.org/en-US/newsletter/existing/...` if the user has previously opted in (and has a record in basket). What should we do when they haven't? The current behavior has a "Subscribe" or "Manage" button depending on their state.

**Comment by shane-tomlinson** [comment]
I had a chat with @pmac about doing this. The TL;DR, is we can't really do this for the reason @dannycoates described. There is nowhere we can link to if the user hasn't already subscribed to a newsletter.

**Comment by pmac** [comment]
@shane-tomlinson I'm doing some work related to this soon that will cause a toggle to show in the email pref center to opt out of accounts related email (separate from the newsletter). It's possible I can do some other work to allow what you need... we'd have to figure out a way to allow this to happen, but it is something we could potentially do. This is all an issue because we're in a strange state where the FxA data isn't in the same place as the rest of our Salesforce stuff, but that should be resolved later this year as well. In the interim we can discuss some solutions if you'd like.

**Comment by shane-tomlinson** [comment]
> In the interim we can discuss some solutions if you'd like.

@pmac sent an invite for Monday the 13th!

**Comment by shane-tomlinson** [comment]
ref https://docs.google.com/document/d/1kl8HQtjdUy0EcT0lid1idx4Q0k0l0_9erxHuP_VStKg

**Comment by shane-tomlinson** [comment]
Some more context from [the basket bug](https://github.com/mozmeao/basket/issues/167#issuecomment-493567809):

@vbudhram is going to take over this work. Copying some context from the email:

> I think there is a path forward that provides the security we want with a reasonable UI. If we add support for [`prompt=none`](https://github.com/mozilla/fxa/issues/640), we could have users bounce off of an endpoint on Basket that sets up the OAuth state token and binds it to the session, then redirects to FxA with ?prompt=none. If the user is signed into FxA, we redirect back to Basket with OAuth credentials without requiring user interaction. I have put added a new diagram below with this flow. There are a lot of redirects, but this approach could work as a generic solution to other problems we have too (securing the payments page).
>
> FxA->Basket (setup OAuth CSRF protection)->FxA w/ prompt=none->Basket w/ OAuth credentials.
>
> There are some details that are being glossed over, but I really think it could work. 


![basket-from-communication-prefs-real-state-token](https://user-images.githubusercontent.com/848085/57950846-4fe62100-78e0-11e9-9549-44fb7ed971b5.png)
