### ISSUE TITLE
Share flow-event library between Payments and Settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9628]
The flow-events.ts libraries in Payments and Settings share common functionality, so we should allow them to be shared between the two. Currently they have some subtle differences that prevent immediate sharing, but it shouldn't be too hard.

More in this [GH discussion.](https://github.com/mozilla/fxa/pull/5303#discussion_r424783096)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1886)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
