### ISSUE TITLE
Use "fuzzy" amplitude metrics where possible in content-server

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9634]
From https://github.com/mozilla/fxa/pull/5378#discussion_r428209366 I had to introduce manual events instead of fuzzy ones. This doesn't hurt anything but using fuzzy events could reduce lines of codes. I'm sure there are other events we could update to fuzzy as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1926)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We don’t use Amplitude anymore.  Vijay Budhram is this issue still valid?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
