### ISSUE TITLE
Small glitch when navigating back to Subscriptions from Contact Support page using the breadcrumb menu

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9638]
#### Affected versions:
* All Firefox;

#### Affected FxA versions:
* 1.171.0;

#### Affected Platforms:
* Windows 10 (64-bit)

#### Preconditions
* existent FxA account with active subscription;

#### Steps to reproduce
1. Open Contact Support page:  https://accounts.stage.mozaws.net/support 
1. Click on the “Subscription” link from the breadcrumb menu.

#### Expected result:
* The user is redirected to the subscriptions page without any display issues.

#### Actual result:
* The breadcrumb menu is moved, for a few seconds above the contact support form.
![menu](https://user-images.githubusercontent.com/15685960/82455432-9c4bda00-9abb-11ea-8063-ffefff622e05.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-1923)

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

This is also reproducible when clicking on the ToS and PN links from the Contact Support page.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
