### ISSUE TITLE
Resume sign in process after interrupting it at TOTP

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9640]
### Steps to reproduce
Configure TOTP as the second factor in your Firefox Account. Then do everything below in a private window (simulating sign in from a new device).

1. Go to https://accounts.firefox.com/.
1. Enter your email, press “Continue”.
1. Enter your password, press “Sign in”.
1. When asked for a TOTP code, do not enter it. Close the tab.
1. Go to https://accounts.firefox.com/.
1. Your email is shown automatically, press “Sign in”.

### Actual result
The “Confirm your account” page is displayed and it says “Check your email for the verification link sent to \<my email>”. The email is not actually sent (supposedly, because the second factor configured is TOTP, not email link).

### Expected result
Instead of showing the “check your email” page, it should ask for the TOTP code again.

### Environment
Firefox 76.0.1.

- - -
I think this is essentially the same as #3185, however that other issue also mentions the “trouble entering code page”, so I thought I’d open a new one for clarity.

The comments in that other issue also mention https://bugzilla.mozilla.org/show_bug.cgi?id=1590444, but it is private.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-1989)

**Comment by data-sync-user** [comment]
➤ Kirill Elagin commented:

I would also be interested in a work around for this, as I am now stuck in this state on my phone, and I don’t think I can selectively clean cookies in mobile Firefox :/.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

You can go to accounts.firefox.com/clear ( http://accounts.firefox.com/clear ) to clear FxA cookies and local storage

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
