### ISSUE TITLE
Add check to Storybook publishing to skip if a build already exists for current commit

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9644]
If we retry tests, the Storybook publishing script will push a new build and post a new comment to a PR. Should probably add a quick check for existing build for a commit. Probably a good assumption that that build was a success and should skip.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-1995)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This sounds like a good optimization to save us CI credits

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
