### ISSUE TITLE
Long display name causes confusions in subscription confirmation page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9660]
#### Affected versions:
* All Firefox;

#### Affected FxA versions:
* 1.174.0;

#### Affected Platforms:
* Windows 10 (64-bit)

#### Preconditions
* existent FxA account with a long display name set;

#### Steps to reproduce
1. Go to https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn  page.
1. Click the “Subscribe Now” button.
1. Fill all mandatory fields and finalize subscription.
1. Observe the “Billed to” section.

      1. Expected result:

* The strings are clear and intuitive. Maybe with a separator between display name and email address.

#### Actual result:
* Account display name and email address are not separated.

![long display name](https://user-images.githubusercontent.com/15685960/84263671-92e8e700-ab28-11ea-8e3b-389e8595607c.png)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-2086)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/16330/image-20210907-142257.png">image-20210907-142257.png</a>

**Comment by data-sync-user** [comment]
➤ ValentinaPC commented:

For display name without spaces, things look very bad, even if, and edge case.
image ( https://user-images.githubusercontent.com/15685960/84360739-40183980-abd3-11ea-99bf-af6725b29050.png )

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Philip Walmsley - is there anything you want to change here?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Zachery Sutton any ideas to fix this?

**Comment by data-sync-user** [comment]
➤ Zachery Sutton commented:

Hi Wil,

I have a few suggestions. Please let me know if you have any questions. 

Video Here ( https://cln.sh/LF8dRQ )

!image-20210907-142257.png|width=825,height=701!

Thanks

Zachery

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
