### ISSUE TITLE
Update master/slave language in mysql code and configs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9663]
Followup from #5695: update our configs to stop using master and slave, but also make sure we don't break anything in MySQL / percona that requires the use of that terminology.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2135)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

John Morrison Jon Buckley  - are you able to help with this?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Yeah, we can help, but I don't think our help is needed - we don't use the mysql replica to serve production traffic so this might be a straight code removal in mozilla/fxa. Happy to review any PRs though

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
