### ISSUE TITLE
Difficult to diagnose error when db-patch-level is inconsistent

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9668]
## Description
In #5708 FxA stage was not working because the db patch level in the oauth database was lower than required. This displayed an error on start-up, but otherwise there was no indication from the logs that anything was wrong with the database. It would've been easier to debug if the error showed up in the logs, perhaps with a new errno. Or alternatively, have the server exit immediately if the db-patch-level doesn't match.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2147)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We could have the __heartbeat__ URL monitor this also, unless it’s a slow operation.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
