### ISSUE TITLE
Display a message in settings UI when a user’s payment method is out of date

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#970]
Things that probably need gluing together for this:

- [ ] Event handling for [`invoice.payment_action_required`](https://stripe.com/docs/billing/webhooks#action-required) webhook from Stripe or similar from subhub
- [ ] DB table or column to record that payment method is out of date
- [ ] auth server API additions to report the payment out of date status
- [ ] content server UI to display the payment out of date status
- [ ] clear the out of date status at the when updating payment method in our UI?

**Comment by lmorchard** [comment]
Just noticed this point in the PRD for which we had no corresponding issue. Filing and estimating high for the unknowns in event handling.

**Comment by johngruen** [comment]
@clouserw confirming that we should do this, but we can backload it in the end of the milestone. @juliastarkov can you add this screen to your wires. 

It should be a persistent warning in settings that says something like "Your payment method is expired. Please update your credit card to continue using %{service}" with a link to the payments update page.

**Comment by juliastarkov** [comment]
@johngruen Yes I will add that.

**Comment by juliastarkov** [comment]
@johngruen @lmorchard Here is the persistent notice screen: https://mozilla.invisionapp.com/share/K2RBDY3VU9X#/362078565_Firefox_Accounts_In_Browser_-Expired_CC-

(I feel like this should be sufficient for every screen, but please let me know if you want something more explicit in the Billing Information section on the Subscriptions page)

**Comment by clouserw** [comment]
Ben says it's possible (or should be) that we can query subhub from the auth server when a user hits their settings page

**Comment by bbangert** [comment]
Linking to mozilla/subhub#45, as it will track any subhub work needed for this.

**Comment by bbangert** [comment]
Per the subhub issue, I don't think we should be storing this in our system. The SubHub API should indicate when we query for the users subscription that it needs updating.

**Comment by lmorchard** [comment]
There's both `/customer/{uid}/subscriptions` and `/customer/{uid}` routes in the API.

The latter (`/customer/{uid}`) is probably a good place for it, since we query that to get current payment info for display anyway.

**Comment by lmorchard** [comment]
Taking a look at recent subhub updates: https://github.com/mozilla/subhub/commit/51ffbf88bd39f260d8a47de5ab31a704e14d2e42

Looks like `failure_code` and `failure_message` will be optionally included per-subscription in both the [subscription list](https://github.com/mozilla/subhub/blob/master/subhub/subhub_api.yaml#L92) and the subscriptions list in [customer detail](https://github.com/mozilla/subhub/blob/master/subhub/subhub_api.yaml#L219) resources. These new properties will need to be threaded through the subhub client & APIs on auth-server, then used on both fxa-content-server and fxa-payment-server to display the message(s)

**Comment by clouserw** [comment]
@philbooth is this something you have time to look at?

**Comment by lmorchard** [comment]
> @philbooth is this something you have time to look at?

If he doesn't, I can take a look

**Comment by lmorchard** [comment]
[Related concern](https://github.com/mozilla/fxa/pull/1801/files#r304170835) - we probably need to add the plumbing to fetch the customer record in content-server. That lists the `failure_code` and `failure_message` properties for each active subscription.

**Comment by philbooth** [comment]
Just noting that  I'm doing this in such a way as to take a small step towards #1808, creating a new gestalt-status endpoint that includes the subscription data we're interested in here. The other part of that issue, replacing direct hits to the auth server from child views, can happen as and when.

**Comment by philbooth** [comment]
@meandavejustice, so I think what's left for this is to call the `account` method that was added to the js client in #1824 from a `beforeRender` method in `app/scripts/views/settings.js` in the content server, then check the `failure_code` property for the value [`expired-card`](https://stripe.com/docs/error-codes#expired-card). Then display the new UI if it's set.

We can chat about it in zoom or slack if anything's not clear, whichever you prefer.

**Comment by philbooth** [comment]
Bumped to 143.
