### ISSUE TITLE
Error: Header If-None-Match or If-Match is required to perform the request

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#9702]
Related to ecosystemAnonID

https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/10987462/?referrer=github_plugin

```
Error: Header If-None-Match or If-Match is required to perform the request
  at _viewModelStack (./lib/errors.js:122:39)
  at zn/i[n]</< (./lib/router.js:427:19)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3679)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
