### ISSUE TITLE
TypeError: this.broker.get(...) is null

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#9703]
Related to pairing flow, somehow the signed in user is not being set.

https://sentry.prod.mozaws.net/operations/fxa-content-client-prod/issues/6325299/?referrer=github_plugin

```
TypeError: this.broker.get(...) is null
  at apply (./views/pair/auth_allow.js:22:26)
  at getContext (./views/base.js:479:12)
  at renderTemplate (./views/base.js:320:12)
  at render/</< (./views/base.js:287:34)
...
(2 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3680)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Link to error in new sentry: https://sentry.io/organizations/mozilla/issues/3211280413/?project=6231069 ( https://sentry.io/organizations/mozilla/issues/3211280413/?project=6231069 )

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
