### ISSUE TITLE
Difficult to find 2fa reset instructions via Google search

### ISSUE THREAD

**Issue by oremj** [mozilla/fxa#972]
It's really difficult to find instructions on how to reset firefox accounts 2fa devices. Searching Google for "firefox accounts mfa reset" returns nothing useful.

<img width="865" alt="Screen Shot 2019-04-30 at 11 29 44 AM" src="https://user-images.githubusercontent.com/45590/56984617-4f593680-6b3b-11e9-9354-dc6c069ee673.png">

Searching for "firefox accounts locked out" does not return the correct support article, even though it's in the title https://support.mozilla.org/en-US/kb/what-if-im-locked-out-two-step-authentication.

In general, it's hard to find a link to https://accounts.firefox.com/ or instructions on how to get there.

Is there anything we can do to improve SEO here?

**Comment by philips** [comment]
The thing I found most frustrating was the product landing page doesn't even clearly link to settings: https://www.mozilla.org/en-US/firefox/accounts/

**Comment by philips** [comment]
Any update on this? It is super unfortunate having a lame product discovery for a good product.

**Comment by shane-tomlinson** [comment]
Hi @philips - Are you looking for instructions on how to disable 2FA if you have lost your 2FA device, or are you already signed in? If you are not signed in anywhere, at the moment there is no way to disable 2FA so other than signing in using the "recovery codes" which were displayed at the end of the 2FA setup process. 

In other news, https://www.mozilla.org/firefox/accounts/ now has a very prominent "join Firefox" section that allows the user to sign in. While this doesn't go to settings, it at least allows the user to sign in. Firefox itself also has a little icon that allows users that are signed into Firefox to open FxA's settings page, here is what it looks like in my browser:

<img width="373" alt="Screenshot 2019-06-06 at 11 57 34" src="https://user-images.githubusercontent.com/848085/59027993-58cc7180-8852-11e9-94b7-db77feeef667.png">

Clicking on Manage account takes the user to FxA's settings page where they can disable 2FA.

**Comment by philips** [comment]
hooray, this new landing page is exactly what I was expecting.

FWIW, I was using Chrome on my desktop at the time when I needed to reset MFA for a new mobile device.

I think this can be closed.

**Comment by shane-tomlinson** [comment]
Thanks @philips!
