### ISSUE TITLE
Adding or updating OAuth relying parties is difficult.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#973]
1. First, a client_id needs to be registered.
2. Next, [an icon needs to be added to the content server](https://github.com/mozilla/fxa/blob/3fd7d05191185bb7c5d5f6a9b8a31b336826a96c/packages/fxa-content-server/app/styles/modules/_settings.scss#L528) to show in the devices and apps list.
3. [A short name needs to be added to the cloudops-deployment](https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/fxa/puppet/yaml/app/fxa.prod.yaml#L1) to use in Amplitude.
4. And scoped key scopes [need added to this config](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/configuration.js#L498) and the scope name added to the "allowedScopes" list for the client_id in the OAuth db.

We always manage to do 1, and often forget to do 2, 3, and 4.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-832)
┆Issue Number: FXA-832

**Comment by vbudhram** [comment]
This could be part of a documentation OKR or epic.

**Comment by shane-tomlinson** [comment]
> This could be part of a documentation OKR or epic.

I was hoping to have a more technical solution that involved declaring all the stuff in 1 place.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa/issues/2478 for scope checking.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We don't need a technical solution for this, but we should improve our documentation.  It's currently at https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa
