### ISSUE TITLE
Wrong browser displayed in emails when managing the account using Edge

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9739]
**Build:**
Production (Train 1.208.1)

**Affected platforms:**
Windows 10 64-bit
Android 11
macOS 10.14

**Steps to reproduce:**

1. Navigate to https://accounts.firefox.com and log in with an existing account.
1. Go to “Recovery key” section and generate a recovery key.
1. Go to your email inbox and observe the email text.

**Actual result:** 
Chrome browser is mentioned in the email text instead of Edge.

**Expected result:** 
Edge browser is mentioned in the email text.

**Note:** This issue involves all emails.
Same issue for Connected Services section.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3692)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15546/wrong+browser+displayed+in+Connected+services.PNG">wrong browser displayed in Connected services.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15548/wrong+browser+in+email.gif">wrong browser in email.gif</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Edge is based on Chrome now and our detection looks at the User Agent string.  So, this isn’t wrong but yeah, it could be better.  Thanks for filing.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
