### ISSUE TITLE
Support OIDC "offline_access" scope

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#974]
Right now to get an access token, an RP has to call the /authorization endpoint with [`?access_type=offline`](https://github.com/mozilla/fxa/blob/3fd7d05191185bb7c5d5f6a9b8a31b336826a96c/packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorization.js#L77). [The OAuth spec](https://tools.ietf.org/html/rfc6749) doesn’t have any mention of “access_type”, and [the OpenID Connect spec defines an additional scope “offline_access”](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess). `access_type=offline` is [Google's OAuth 2.0 implementation way of doing things](https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient), which we copied. 

Let's support the OIDC standard too.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-833)
┆Issue Number: FXA-833

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

rfk mentioned that this might be a lower priority, since we aren't onboarding any RPs in the near term that need OIDC integration. moving back to the backlog.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
