### ISSUE TITLE
[subplat] Include Error Code in PayPalClientError Name

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9745]
When available, we should include the error code returned by PayPal in the name of PayPalClientError.  This will help us to distinguish these errors in Sentry.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3694)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Example error where the PayPal error code meant our account was restricted: https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11352374/?query=is%3Aunresolved ( https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11352374/?query=is%3Aunresolved ) .

**Comment by biancadanforth** [comment]
Specifically, there is a `name` attribute on the error object. We want to do this, so that Sentry doesn't group all our PayPal errors with different codes into the same bucket.
E.g. "PayPalClientError:10001"

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
