### ISSUE TITLE
Accept and handle 2FA push notification (iOS Mobile client)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9746]
We need to update the Firefox of iOS client to support opening these messages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3695)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
