### ISSUE TITLE
[subplat][content-server] Create New View for Finishing Sign Up

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9749]
The new subscription checkout flow will allow people who are not yet FxA users to create an account and subscription prior to setting a password.  Then the customer is offered the option to follow a link in an email to finish setting up their Firefox account.  This view is to handle that link in the email.

This view should be very similar to the sign up password view.  The difference is that this view will not have the newsletter selection content.

Note that some of this description here is intentionally vague until other parts of the flow is defined.

This view needs to:

#### Parse and Verify Parameters
The email will pass in various values through the URL.

One of the values will be a verifiable code.  This value must be verified with the auth-server.  If this code is invalid, immediately redirect the content server home page.

The other values passed in should at least include the user's email address used to sign up, the redirect url, and the subscription product name.

The email address will be used to look up the account.  If the account is not found, redirect to the content server home page.

The redirect url is the location to send the new user after a successful sign up.  We should limit the domains of these to an allowed list.

The product name is simply used as content.

#### Display Passwords Form
This page displays a form similar to the sign up password view, with the newsletter selection removed.  The product name that is passed in through the URL is used in place of the Relying Party / service name.

The validation for the password inputs must be identical to the sign up password view.

#### Complete Account Setup And Redirect
Once the user entered valid passwords and submitted the form, we need to use a new auth-server endpoint to finish the sign up.  We will need to update the FxA client to use the new endpoint.  Aside from the new endpoint, this process should like that of the sign up process.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3565)

**Comment by vbudhram** [comment]
This is fixed in https://github.com/mozilla/fxa/pull/9851.
