### ISSUE TITLE
Support OIDC "nonce" parameter

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#975]
The OpenID Connect spec [defines a `nonce` query parameter](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) and response in the ID token:

> String value used to associate a Client session with an ID Token, and to mitigate replay attacks. The value is passed through unmodified from the Authentication Request to the ID Token. If present in the ID Token, Clients MUST verify that the nonce Claim Value is equal to the value of the nonce parameter sent in the Authentication Request. If present in the Authentication Request, Authorization Servers MUST include a nonce Claim in the ID Token with the Claim Value being the nonce value sent in the Authentication Request. Authorization Servers SHOULD perform no other processing on nonce values used. The nonce value is a case sensitive string. 

I'm not yet sure what all is involved in making this happen. It might be that we need to store and propagate the nonce with any grants and refresh tokens so that any id_tokens that are generated contain the nonce.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-815)
┆Issue Number: FXA-815

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
