### ISSUE TITLE
Support OIDC auth_time when returning ID token

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#976]
The OpenID Connect spec [defines an `auth_time` claim](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) in the ID token:

> Time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. When a max_age request is made or when auth_time is requested as an Essential Claim, then this Claim is REQUIRED; otherwise, its inclusion is OPTIONAL. (The auth_time Claim semantically corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] auth_time response parameter.) 

While we aren't returning this in the id_token, we are returning `auth_at` in [the /token response](https://github.com/mozilla/fxa/blob/3fd7d05191185bb7c5d5f6a9b8a31b336826a96c/packages/fxa-auth-server/fxa-oauth-server/lib/routes/token.js#L172) and [/authorization response for implicit grants](https://github.com/mozilla/fxa/blob/3fd7d05191185bb7c5d5f6a9b8a31b336826a96c/packages/fxa-auth-server/fxa-oauth-server/lib/routes/authorization.js#L116), and it's the same info.

Adding it to the id_token should be as easy as propagating the value to [generateIdToken](https://github.com/mozilla/fxa/blob/3fd7d05191185bb7c5d5f6a9b8a31b336826a96c/packages/fxa-auth-server/fxa-oauth-server/lib/grant.js#L152) and adding a new claim.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-811)
┆Issue Number: FXA-811

**Comment by clouserw** [comment]
@rfk is this something that we need to do?

**Comment by rfk** [comment]
I don't think we need to do it with any particular urgency; adding it might help future integrations get this information more easily if they're using an off-the-shelf OIDC library, but I can count the number of times that's happened in the past on no hands.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
