### ISSUE TITLE
[subplat] Surface any messaging from PayPal received by Accounting to the supporting teams

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9763]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3700)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Requested action from ngrammater

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
