### ISSUE TITLE
Support request mail received in English regardless of browser language : Ensure fxa user language is set correctly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9774]
**Affected versions:**

* All Safari;
* All Firefox;

**Affected FxA versions:**

* 1.209.0;

**Prerequisites:**

* Have the VPN set to one of the regions: Spain/Italy/Belgium/Austria/Switzerland and the language browser set to one of the following languages: Spanish/Italian/Netherlands/French/Deutsch;
* Be logged into a FxA account and have an active subscription paid via Paypal payment account or Stripe;
* Be on the Subscription management page.

**Steps to reproduce:**
1. Click on the “Contact Support” blue button placed on the right side of the page; 
2. Fill in all the mandatory fields;
3. Click the “Send” button.
4. Check mail with the same account from the prerequisites;
5. Observe the received email regarding the support request.

**Expected result:**

* The email is translated in the browser language;

**Actual result:**

* The email is displayed in English and not translated in the browser language.

**QA NOTE**: also check the flow from the Mozilla VPN app

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3703)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22999">Bildschirmfoto 2022-04-20 um 09.30.19.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22998">Bildschirmfoto 2022-04-20 um 09.30.52.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23061">Captura de pantalla 2022-04-21 a las 10.04.40.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/16672">image_2021_09_30T13_49_59_256Z.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23033">image-20220420-164901.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22859">Schermafbeelding 2022-04-14 om 12.18.20.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22858">Schermafbeelding 2022-04-14 om 12.36.27.png</a>

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

I have noticed today that, in the email received regarding the support ticket, besides not being translated, the Firefox icon seems to be broken. See attached screenshot.

!image_2021_09_30T13_49_59_256Z.png|width=809,height=828!

Thank you.

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

We have logged a different issue for the above mentioned logo problem here ( https://mozilla-hub.atlassian.net/browse/FXA-4619 )

Thank you.

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Hi Anna Sobiepanek Support emails are localized based on the users FXA language since thats what Zendesk draws from. If their FXA is in English, then the support emails will be as well unless we manually change their language in the Zendesk profile.

Hope that helps.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Anna Sobiepanek , verified this on Train 1.230.2 - Staging. I submitted a support request while using FXA accounts that were created in a non English language (ES, DE, IT, FR, NL), and the support emails are still displayed in English (attaching ss).

However, if submitting a second support request from a FXA account that was created in ES/DE/IT/FR, the email is displayed in the appropriate language. (attaching ss). 

For the account that was created in NL language, the email is displayed in English, regardelss of the number of the submitted support requests. 

!Schermafbeelding 2022-04-14 om 12.18.20.png|width=1481,height=400!

!Schermafbeelding 2022-04-14 om 12.36.27.png|width=1867,height=757!

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Madalin Cotetiu Could you submit additional tickets and let Joseph Anthony Cuevas  know the ticket numbers please?  Thanks!

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Barry Chen / Joseph Anthony Cuevas , Please see bellow the submitted ticket numbers (while on Train 1.230.3 - staging): 

  * 61190 (account created while having the language set to ES)
  * 61192 (account created while having the language set to DE)
  * 61193 (account created while having the language set to FR)
  * 61194 (account created while having the language set to IT)
  * 61196 (account created while having the language set to NL)

The received emails are displayed in English.

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Thanks Bianca Hidecuti  How are you submitting these tickets? Are you using the FXA form or sending directly to email?

  * 61190 (account created while having the language set to ES) - Thereis  a misconfiguration on Zendesk where we had 2 Spanish languages and only had localization loaded for 1. It has been corrected so now there should only be one Spanish for all regional variations.  Can you retest this?
  * 61192 (account created while having the language set to DE) - Ticket was Deleted by our team before I could verify.  Can you resend a ticket for DE?
  * 61193 (account created while having the language set to FR) - Profile was set to FR. Trigger shows the macro was sent but I can’t confirm from my end what language was sent. Based on how the system works, it should have sent FR.
  * 61194 (account created while having the language set to IT) - Profile was set to IT. Trigger shows the macro was sent but I can’t confirm from my end what language was sent. Based on how the system works, it should have sent FR.
  * 61196 (account created while having the language set to NL) - This is an unsupported language so responses will return in English.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Joseph Anthony Cuevas , I am submitting the tickets from the FXA form. 

I have submitted some tickets again: 

  * 61307 - (account created while having the language set to ES) - email is displayed in English (regardless of the number of the submitted tickets); 
  * 61311 - (account created while having the language set to DE) - email is displayed in English for the first submitted ticket for this account. However, if I submit a second support request for this account, the email received is displayed in German - ticket number - 61312 (see the attached ss); 
  * 61313 - (account created while having the language set to FR) - email is displayed in English for the first submitted ticket for this account. If submitting a second support request, the email received is displayed in French - see ticket number 61314;
  * 61315 - (account created while having the language set to IT) - email is displayed in English for the first submitted ticket for this account. If submitting a second support request, the email received is displayed in Italian - see ticket number 61316;

Also, the footer of the email is displayed in English even when the content of the email is displayed in the user’s language.

Hope this helps. 

!Bildschirmfoto 2022-04-20 um 09.30.52.png|width=1362,height=717!

!Bildschirmfoto 2022-04-20 um 09.30.19.png|width=1363,height=750!

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Bianca Hidecuti 

  * 61307 - User account shows as English for this ticket. Not Spanish. (see screenshot below)

!image-20220420-164901.png|width=290,height=309!

  * Footer is not localized. So this would not display in a localized language.

The fact that the issue is with the very first ticket submitted after an FXA is created seems to be indicative of another factor unrelated to Zendesk. I’m not sure if this is anything I can debug further.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Joseph Anthony Cuevas , I created other accounts while having the language set to Spanish (ES-es), and I got the same result. The emails are still displayed in English. Ticket numbers: 

61435 / 61436 - account: bhidecuti+cses2@mozilla.com ( mailto:bhidecuti+cses2@mozilla.com )

61437 / 61438 - account: bhidecuti+firefoxes@mozilla.com ( mailto:bhidecuti+firefoxes@mozilla.com )

!Captura de pantalla 2022-04-21 a las 10.04.40.png|width=1118,height=574!

**Comment by data-sync-user** [comment]
➤ Joseph Anthony Cuevas commented:

Thanks Bianca Hidecuti. It would seem what I changed earlier didn’t resolve the issue with Spanish from Spain. I’ve reverted that change and now at the very least the behavior should mimic the other languages where the second request should receive a localized response after creating a new account.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
