### ISSUE TITLE
[FxA-Settings] Security code field from “Enter security code” page could be improved by limiting the number of digits allowed to 6 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9780]
**Build:**
Stage (Train 1.209.0)

**Affected platforms:**
Windows 10 64-bit
Android 11
iOS 14.6
macOS 10.14

**Preconditions:**
The user has the 2FA enabled.

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net and log in with an existing account.
1. At “Enter security code” page enter a code longer than 6 digits.

**Actual result:** 
A code longer than 6 digits can be entered.

**Expected result:** 
The code is limited to only 6-digits. (Compare with 2FA Step 1 of 3 page)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3706)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15559">2FA security code field.gif</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Are you running into a situation where you needed to enter more than 6 characters?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I misread the bug - you’re saying we should be limiting the field to 6 to be consistent with the login experience.

**Comment by BamBamboozled** [comment]
Should this be closed?

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
