### ISSUE TITLE
Cancelling a subscription should not immediately delete it

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#981]
On reviewing [subscription termination flow in wireframes](https://mozilla.invisionapp.com/share/K2RBDY3VU9X#/screens/360130692/comments), it occurred to me that there's a mismatch in my implementation so far. That is, when a user cancels a subscription, the code immediately deletes it. This is incorrect - the subscription should continue to be active until the duration has ended.

Additionally, the wireframes show the time when the cancellation happened:

<img width="315" alt="Capture" src="https://user-images.githubusercontent.com/21687/57025610-9f043480-6c05-11e9-9830-16072e0dd5b7.PNG">

So, some proposed changes:

- [x] Do not delete subscription record on cancellation
- [x] Add column to record cancellation timestamp
- [ ] Only delete on receiving an event from subhub that subscription has ended (e.g. only events in issue #713 can actually delete subscription records)
- [ ] Find out if there's a way to "resubscribe" via subhub? (i.e. undo a cancellation?)

**Comment by lmorchard** [comment]
Adding a needs:product, since it looks like we don't have this in the PRD or subhub API yet

**Comment by johngruen** [comment]
@lmorchard @bbangert I agree with @lmorchard's suggestion here since it makes our story about refunds (there is no story) easier to digest. I would like to see this moved into the MVP Milestone

**Comment by clouserw** [comment]
This has a database change in it, so might be good to get in early. /cc @philbooth

**Comment by philbooth** [comment]
I just went to make a start on the outstanding piece of this:

> - [ ] Only delete on receiving an event from subhub that subscription has ended (e.g. only events in issue #713 can actually delete subscription records)

But it looks like it's already implemented, to my untrained eye:

https://github.com/mozilla/fxa/blob/fd995fb804fd320081a32b2bfdc8ccbda41e861f/packages/fxa-auth-server/lib/subhub/updates.js#L61-L62

@lmorchard, does that ^ do what I think it does?

**Comment by lmorchard** [comment]
> does that ^ do what I think it does?

I *think* so? That's some event processing that @ian and @bbangert have been working on, but I haven't had a chance to catch up on their work yet.

**Comment by philbooth** [comment]
Closing this, I think we're all good on this issue now (but please re-open if there's something I've missed).

**Comment by lmorchard** [comment]
We still have to implement the "reactivate" button, but maybe that's worth a separate issue
