### ISSUE TITLE
[subplat] “Set up your subscription” page has a white section for some browser dimensions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9814]
**FxA version:**

* 1.210.0;

**Affected Platforms:**

* Windows 10;

**Affected browser:**

* Firefox Release;

**Prerequisites:**

* Have one FxA account without subscription;
* Be in a country where VPN is available;
* Be “Set up your subscription” page;

**Steps to reproduce:**
1. Resize the browser until the width is 1024px and height between 100->480px;
2. Observe the page layout;

**Expected result:**

* There are no display or layout issues;

**Actual result:**

* An empty space is displayed between title and paypal button;

**Notes:**

* Reproducing in different subscription pages;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3727)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15775">Screen Recording 2021-07-26 at 14.36.56.mov</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/15586">Untitled.png</a>

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

This issue is reproducible on the Subscription upgrade page too, on Safari/Chrome on MacOS, and on Chrome on Windows 10, when resizing the Window in the following intervals: 300-750 width x 200-650 height px. See the attached video. 

!Screen Recording 2021-07-26 at 14.36.56.mov|width=586,height=542!

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
