### ISSUE TITLE
[subplat] Check for deleted subscriptions before creating a new subscription

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9815]
A subscription could be deleted e.g. [if the initial setup of a subscription during checkout fails](https://github.com/mozilla/fxa/blob/e3810e0a95575d7415ec15555e45a830a005d607/packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts#L215-L220).

We post to [`/oauth/subscriptions/active/new`](https://github.com/mozilla/fxa/blob/e3810e0a95575d7415ec15555e45a830a005d607/packages/fxa-auth-server/lib/routes/subscriptions/stripe.ts#L913), which calls [`this.stripe.subscriptions.create`](https://github.com/mozilla/fxa/blob/e3810e0a95575d7415ec15555e45a830a005d607/packages/fxa-auth-server/lib/payments/stripe.ts#L336), but we could instead call `this.stripe.subscriptions.list` to see if a subscription with that ID was deleted first.

This would help resolve some "No such subscription" errors. Though the scenario in question here is where a customer attempts to subscribe, fails, re-attempts to subscribe with the same idempotency key (FXA-3625), and fails again, so closing that issue should largely preempt this one.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3728)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
