### ISSUE TITLE
[subplat] Mark an invoice associated with a deleted subscription or customer as uncollectible

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9816]
See also FXA-3728, FXA-3625.

If we fail to collect initial payment when creating a new subscription, we [delete the subscription and perform other teardown steps](https://github.com/mozilla/fxa/blob/e3810e0a95575d7415ec15555e45a830a005d607/packages/fxa-auth-server/lib/routes/subscriptions/paypal.ts#L215-L220).

Part of this teardown should include marking the invoice as "uncollectible", that way, we will issue a refund in [`handleMerchPayment`](https://github.com/mozilla/fxa/blob/21e80ce3192ddbd2b9ce6acf8ada9b5ea34f6bbe/packages/fxa-auth-server/lib/routes/subscriptions/paypal-notifications.ts#L37-L44) if a payment processor (e.g. PayPal) comes around later and tells us the user has paid anyway.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3729)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
