### ISSUE TITLE
[subplat] add paypalTransactionId to the invoice if there isn't one in handleMerchPayment

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9817]
See also FXA-3728, FXA-3729 and FXA-3626.

In some scenarios, say if a PayPal subscriber's PayPal account is on a temporary hold, it's possible an invoice for their subscription is missing a transaction ID. If we receive a PayPal notification of payment (`handleMerchPayment`), and the invoice doesn't have this ID, we should add it from the notification details.

Not having a `paypalTransactionId` on an invoice is one reason a PayPal refund issued by Support could fail.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3730)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
