### ISSUE TITLE
WError: An internal server error occurred

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#9818]
https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11778104/?referrer=github_plugin

```
WError: An internal server error occurred
  File "/fxa/node_modules/stripe/lib/Error.js", line 48, in Function.generate
    return new StripeIdempotencyError(rawStripeError);
  File "/fxa/node_modules/stripe/lib/StripeResource.js", line 180, in IncomingMessage.<anonymous>
    err = StripeError.generate(response.error);
  File "events.js", line 481, in Object.onceWrapper
  File "events.js", line 387, in IncomingMessage.emit
  File "domain.js", line 470, in IncomingMessage.emit
...
(2 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3731)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

This looks similar to FXA-3625.

The error is:

	

Error: Keys for idempotent requests can only be used for the same endpoint they were first used for ('/v1/payment_methods/pm_1J7HBmJNcmPzuWtRCAkSvUBS/attach' vs '/v1/payment_methods/pm_1J7HB5JNcmPzuWtROUM7fW9m/attach'). Try using a key other than 'f83a0cb8-ea38-44da-99e7-64006963fef3-retryInvoice' if you meant to execute a different request."Let’s look up the error ids to figure out what the implications are for the customer.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
