### ISSUE TITLE
[subplat] Expand 'L' Array on NVP Payload for PayPal Sentry Errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9819]
It might help with debugging with the error code is generic.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3732)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

We need to expand the field and JSON.stringify the message before logging.

Note: Sentry also has limits on field size, though it probably won’t be an issue.

If there’s an L attribute, we could log this as a separate object in Sentry.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
