### ISSUE TITLE
[subplat] Consider removing SigninLayout component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9826]
While working on FXA-3676, I encountered a wrapper component called `SigninLayout`, which looks to have been added in PR#1387.

Talking with Dave, it seems like this only determines [whether or not we hide the Firefox logo in any child components](https://github.com/mozilla/fxa/blob/9485b2dec7b7d9e412757637fa9d83aca0a148b2/packages/fxa-payments-server/src/components/AppLayout/index.tsx#L38).

[~accountid:6047c6aa79f9a90070e8ff1d], do you have any additional context or strong feelings here? It looks like the `hide-logo` class is always false.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3735)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Les.

Barry noted that we may be able to repurpose this to differentiate signed in/signed out UI.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
