### ISSUE TITLE
 Downloaded receipt is not translated in the system language

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9847]
Edit: Elevating the fix per Ben’s comment below:

> Ah, ok, I see. It appears Stripe only generates PDF’s in the language for the stripe user. We default those all to English at the moment. Creating a stripe customer takes a `preferred_locales` argument we should use to pass along the browser locale.

(We would also need to update existing customers, which is trickier, as we would get this from the browser language, so the user needs to come to the website.)

**Affected versions:**

* All Safari;
* All Firefox;

**Affected FxA versions:**

* 1.210.1;

**Prerequisites:**

* Have the VPN set to Belgium/Austria/Italy/Spain/Swiss and the language browser set to French/Netherlands/Deutsch/Italian/Spanish;
* Have an FxA account with an active subscription for Mozilla VPN;
* Have your client email opened and the payment confirmation email for the account;

**Steps to reproduce:**
1. Click the “View your invoice” link ;
2. Click the “Download receipt” button from the stripe invoice website;
3. Open the receipt (pdf);
4. Observe the content of the receipt.

**Expected result:**

* The content of the receipt (pdf) is displayed in user language.

**Actual result:**

* The content of the receipt (pdf) is displayed in english.

**Notes:**

* Reproducible for all languages.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3745)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15656/Schermata+2021-07-15+alle+09.48.52.png">Schermata 2021-07-15 alle 09.48.52.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15655/Schermata+2021-07-15+alle+09.49.32.png">Schermata 2021-07-15 alle 09.49.32.png</a>

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

This is purely an effect of how our L10n process currently works.  After we merge some code, on that week’s Friday, the original English strings are extracted, and then we wait for localizers to translate them, then we pulled in any new translated strings in the next release.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

This is a page hosted on Stripe. Maybe we need to set a locale on e.g. the Stripe customer?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I loaded the hosted stripe invoice website, and changed my preferred language and hit reload. The stripe website properly translated the page, and the downloaded PDF’s. I am unable to reproduce this.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Note that these are the supported languages:

https://support.stripe.com/questions/language-recognition-for-invoices-with-stripe-billing ( https://support.stripe.com/questions/language-recognition-for-invoices-with-stripe-billing|smart-link )

**Comment by data-sync-user** [comment]
➤ Madalin Cotetiu commented:

The stripe webpage and invoice content (on site and pdf) is properly translated in the language browser, but the Receipt (pdf) is displayed in English regardless of the browser language (see the attached screenshots).

!Schermata 2021-07-15 alle 09.48.52.png|width=1124,height=892!

!Schermata 2021-07-15 alle 09.49.32.png|width=1120,height=897!

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Madalin Cotetiu The first PDF you’re showing there appears to be localized.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

Benjamin Bangert The first yes, we post it to compare it. We were talking about the receipt not being translated. Thanks!

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Ah, ok, I see. It appears Stripe only generates PDF’s in the language for the stripe user. We default those all to English at the moment. Creating a stripe customer takes a preferred_locales argument we should use to pass along the browser locale.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Barry noted that we may want to also add this property for existing customers, not just new customers. Should that be in scope for this ticket as well?

There are a number of ways we could obtain locale information, for example by looking at the subscription or from the account locale (which can’t be modified currently after an account is created).

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Yes, we will need a script to go back and update all existing Stripe customer to set their local based on their FxA locale.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
