### ISSUE TITLE
[subplat] Disambiguate "WErrorFunction.generate(stripe.lib:Error)" Sentry errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9849]
There are currently 260 events for this error in Sentry ([https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/11182334/?query=is%3Aunresolved](http://example.com)), but this actually conflates different kinds of errors into the same one.

For example the error above can be safely ignored, while others under this error cannot. If we had more descriptive error names, we could more easily filter out and ignore such errors and focus on the important ones.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3746)

**Comment by biancadanforth** [comment]
This ticket should look at disambiguating other errors as well potentially for example https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/13061601/?query=is%3Aunresolved .

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
