### ISSUE TITLE
Subscription request for MDN

### ISSUE THREAD

**Issue by escattone** [mozilla/fxa#9867]
The MDN team would like to set-up a subscription (product and plan) on SubPlat.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3754)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15675/image-20210715-223623.png">image-20210715-223623.png</a>

**Comment by clouserw** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1719636

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I can add some of these to our stage environment for testing. There’s multiple fields that we’ll need data for to set this up. Currently we have a variety of metadata we add that is used during the checkout process to display the appropriate information about the product. Here is what the VPN products metadata looks like:

!image-20210715-223623.png|width=1122,height=642!

We will need a similar set of fields and values for the MDN product. Localization is currently handled by individual plans per locale/currency/interval. So 3 plans are needed for English with USD, for a monthly, semi-annual, and annual plan. The product details there become the bullet points shown for the product on the checkout page. The rest should be fairly self-explanatory. Let me know if you have any other questions!

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Thanks Benjamin Bangert – I have a question regarding billing plans. Can we limit our billing plans for our MDN Plus product to just monthly, so no semi-annual or yearly plans?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Of course, how many plans you want is entirely up to you. VPN started with just a monthly as well.

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Benjamin Bangert What are the dimensions or range of dimensions that the icon (that’s part of our product details) should be or stay within?

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

FYI, I’m collecting all the product detail information for MDN Plus in this Google doc ( https://docs.google.com/document/d/1cIJ1MHibUpeS-QDPbvIGCtP5mH_R95gxUzjo6-9IfBc/edit?usp=sharing ).

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Looks like the icon is 188x188.

Here is an example: https://accounts-static.cdn.mozilla.net/product-icons/mozilla-vpn-web.svg ( https://accounts-static.cdn.mozilla.net/product-icons/mozilla-vpn-web.svg )

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Benjamin Bangert Wil Clouser How do we get testing credentials? Is there a minimal set of product details you need for a test environment?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Ryan Johnson I’m going to use the capability name of ‘mdn_plus’ for this product. Has a stage oauth client id been created for you yet? Once you have an FxA oauth client ID setup, then you can integrate with the subscription platform after I provide the product/plan id’s, which are:
Product: prod_Jtbg9tyGyLRuB0

Plan: price_1JFoTYKb9q6OnNsLalexa03p

There’s an additional setup for the webhook to receive notifications about subscription state changes as well, per:

https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events ( https://mozilla.github.io/ecosystem-platform/docs/process/integration-with-fxa#webhook-events|smart-link )

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Benjamin Bangert Thanks! Yes, we have FxA OAuth client ID’s for our local development, stage, and iOS/Android app environments. Do you need those?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Ryan Johnson Yep, can you put them on the Google doc?

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Benjamin Bangert Sorry for the delay! I added our FxA OAuth client ID’s to the Google doc.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Ryan Johnson I’ve updated the stage product listed before for MDN. You should now get the subscription capability returned from our profile server after someone has purchased MDN Plus. Did you need any other setup information to test with?

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Thanks Benjamin Bangert! Could you please point me to your docs that explain how we can begin testing our product on your stage instance? I’m not sure what the endpoints are for doing things like making a product purchase or getting a FxA user’s current active products.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Are you setup for FxA Oauth with login yet? If so, to send a user to the right product you want to redirect to:

https://accounts.stage.mozaws.net/subscriptions/products/PRODUCT_ID?plan= ( https://accounts.stage.mozaws.net/subscriptions/products/prod_FfiuDs9u11ESbD?plan=plan_FfiupsKXZ3mMZ6 )PLAN_ID

Just replace the two values with the prdocut/plan id’s from below. We’ll need to add some config for the webhooks. To retrieve active subscriptions, a query to the profile server (userinfo_endpoint) is all thats needed. A capability list will be returned that indicates valid subscriptions.

Stage URL’s that show the userinfo endpoint, etc. can be seen at:

https://accounts.stage.mozaws.net/.well-known/openid-configuration ( https://accounts.stage.mozaws.net/.well-known/openid-configuration )

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Benjamin Bangert Yes, I think we’re all setup for using FxA OAuth, and on my team, Peter B. is currently working on FxA OAuth login to MDN. So, for authorization when using the endpoints you mentioned (for example, https://profile.stage.mozaws.net/v1/profile), we use the access token we get for the FxA user from the OAuth dance, is that right?

**Comment by data-sync-user** [comment]
➤ Ryan Johnson commented:

Benjamin Bangert I get a 500 error when trying +https://accounts.stage.mozaws.net/subscriptions/products/prod_Jtbg9tyGyLRuB0?plan=price_1JFoTYKb9q6OnNsLalexa03p+ ( https://accounts.stage.mozaws.net/subscriptions/products/prod_Jtbg9tyGyLRuB0?plan=price_1JFoTYKb9q6OnNsLalexa03p ) – Is that not active yet on stage?

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Closing this as its now working and verified. Another issue will be opened later for webhook integration finishing touches.
