### ISSUE TITLE
Add support for a new top of funnel event

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#988]
Event Name = `fxa_subscribe - view`
Event Properties = `product_id`
User Properties = none

@irrationalagent  on Slack says "right now we log those types of events by having the relying party ping this endpoint https://github.com/mozilla/fxa/blob/627380f39ceda34c77cd9c5f65c1ab6f6051581f/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js and then we log an event on our side in response. but we only log one type of event currently, so we will need to add support for the fxa_subscribe - view event there"

See the [product requirements](https://docs.google.com/document/d/1d39yRiYt4rhahtMae04Pwcx5vldNQJeF1grz_KO8qJw/edit#)

See a [breakdown of events and properties](https://docs.google.com/spreadsheets/d/1ttgV60YeurrMhmdlCZ5WNBJXa-PcnRmrGgOEow71E1U/edit#gid=0)

**Comment by shane-tomlinson** [comment]
Which entity emits these events, the RP, the subscription page, or other?

**Comment by clouserw** [comment]
I think the RP, but @irrationalagent can confirm

**Comment by irrationalagent** [comment]
by understanding of the flows is that it would be the RP, so that we can log views of whatever they use as their entrypoint to the signin/up flow (be it a button or an email form or whatever, i tried to keep the event name deliberately vague).

if the relier has multiple entrypoints, we will be able to segment by the `entrypoint` parameter.

**Comment by clouserw** [comment]
When the RP loads their page, they retrieve 3 values from our endpoint.  They then pass these values back (with any other data) and we emit the event.  @irrationalagent will paste an example below

**Comment by irrationalagent** [comment]
An example of the [whatsnew](https://www.mozilla.org/en-US/firefox/68.0/whatsnew/) providing the utm_ parameters to the FxA metrics endpoint and receiving flow_id, flow_begin_time and device_id:

https://github.com/mozilla/bedrock/blob/3408b459a178c62fa3463818cfee1b866beee4d1/media/js/base/mozilla-fxa-form.js#L44

On the fxa side, the get-metrics-flow endpoint is here, it logs an event when the above fetch is done:

https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js

We will need to modify that ^ to start logging events other than `fxa_email_first - view`

**Comment by irrationalagent** [comment]
Here documents the regex that the query params/utm params have to pass through:
https://mozilla.github.io/application-services/docs/accounts/metrics.html
