### ISSUE TITLE
Allow Partial Refund ability for Paypal users.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9887]
Currently, There is no ability to partially refund or credit a users subscription. 

Use Case: I subscribed to the 12 month subscription and I have not been able to use the product for X amount of time. I want a partial refund to compensate for the time I have not been able to use the product. 

For Users subscribed in stripe with CC, Support can process a credit note, provided the credit does not exceed the Subscription payment amount. 
For Paypal users, there is no way to process a partial refund at this time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3757)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
