### ISSUE TITLE
Add event properties to existing Account Creation funnel

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#989]
These events already exist, but the properties are new.

- [ ] Add `product_id` property to the `fxa_subscribe - view` event
- [x] Add `product_id, plan_id` properties to the `fxa_reg - view` event
- [x] Add `product_id, plan_id` properties to the `fxa_reg - engage` event
- [x] Add `product_id, plan_id` properties to the `fxa_reg - submit` event
- [ ] Add `email_type=registration, email_template=downloadSubscription` properties to the `fxa_email - sent` event
- [ ] Add `email_type=registration, email_template=??` properties to the `fxa_email - click` event
- [x] Add `product_id, plan_id` properties to the `fxa_reg - email_confirmed` event
- [ ] Add `product_id, plan_id` properties to the `fxa_reg - complete` event

See the [product requirements](https://docs.google.com/document/d/1d39yRiYt4rhahtMae04Pwcx5vldNQJeF1grz_KO8qJw/edit#)

See a [breakdown of events and properties](https://docs.google.com/spreadsheets/d/1ttgV60YeurrMhmdlCZ5WNBJXa-PcnRmrGgOEow71E1U/edit#gid=0)

**Comment by clouserw** [comment]
We shouldn't overwrite properties.  New values should be appended (amplitude supports arrays).  Fxa_services_used is an example of this existing today.

**Comment by clouserw** [comment]
@bbangert are you working with someone on this already?

**Comment by philbooth** [comment]
I said I'd take this on, sorry, putting my face on it now.

**Comment by johngruen** [comment]
@vbudhram Shane thinks you are working on this. is that true?
