### ISSUE TITLE
403 CORS errors are present in the network at login on all AMO servers

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9946]
STR:
1. From AMO dev try to login 
2. Open Web developer tools and observe the Network

Result:
fxA page throws 403 errors before login 

Note:
the login is successful but every time these errors are displayed in the network
this is only reproducible on AMO dev 

!errors on dev.png|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3796)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15751/CORS+in+COnsole.png">CORS in COnsole.png</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15750/errors+on+dev.png">errors on dev.png</a>

**Comment by data-sync-user** [comment]
➤ Ioana Rusiczki commented:

I initially thought it’s an AMO -dev issue but it is not, I could reproduce it on AMO stage and prod as well

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This looks like a Sentry bug if it’s not setting the proper headers.  Jon Buckley is there a place we can file this in bugzilla?

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

I changed https://sentry.prod.mozaws.net/settings/operations/projects/fxa-content-client-stage/ ( https://sentry.prod.mozaws.net/settings/operations/projects/fxa-content-client-stage/ ) to allow https://accounts.stage.mozaws.net ( https://accounts.stage.mozaws.net ) . Lets see if that fixes this CORS error

**Comment by lmorchard** [comment]
FWIW, I think we're seeing this error over on Experimenter too. If it *is* the same error, it's not a CORS issue so much as Sentry is responding with a text/html error page about CSRF validation failure and that page happens not to include CORS headers.

https://github.com/mozilla/experimenter/issues/6013

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Ioana Rusiczki  Is this fixed on stage?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I can’t reproduce this anymore on addons-dev, but when I try to sign in to production AMO I see CORS errors to Sentry.  Jon Buckley - is accounts.firefox.com ( http://accounts.firefox.com ) on the list too?  For that matter, what is the list - maybe there are other sites that should be on there (eg. experimenter).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
