### ISSUE TITLE
Add new events and properties for Subscription Cancel funnel

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#995]
- [ ] Add `product_id, plan_id` event properties to a new `fxa_subscribe_cancel - view` event
- [ ] Add `product_id, plan_id` event properties to a new `fxa_subscribe_cancel - engage` event
- [ ] Add `product_id, plan_id` event properties to a new `fxa_subscribe_cancel - submit` event
- [ ] Add `product_id, plan_id` event properties and `product_id, plan_id` user properties to a new `fxa_subscribe_cancel - success` event
- [ ] Add `reason, product_id, plan_id` event properties to a new `fxa_subscribe_cancel - fail` event
- [ ] Add `product_id, plan_id` event properties and `product_id, plan_id` user properties to a new `fxa_subscribe_cancel - complete` event

See additional details in the [product requirements](https://docs.google.com/document/d/1d39yRiYt4rhahtMae04Pwcx5vldNQJeF1grz_KO8qJw/edit#)

See a [breakdown of events and properties](https://docs.google.com/spreadsheets/d/1ttgV60YeurrMhmdlCZ5WNBJXa-PcnRmrGgOEow71E1U/edit#gid=0)

**Comment by philbooth** [comment]
Fwiw, it will be the same bit of code that fixes this as fixes #988, #989, #991, #992, #993 and #994. So we could close those as dups and track it all in one if issue, if that makes sense from a project managment perspective.

**Comment by clouserw** [comment]
I get your point, but I'd like to leave them separate, and when the code lands we can just close all of them.

This is the difference between tracking the engineering work or tracking the product work and I've never found a way to do it where there isn't a tension there.  Maybe jira has some magic sauce.
