### ISSUE TITLE
Clean up onValidate / onValidatePromise props in payments-server Input component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9959]
I added `onValidatePromise` in https://github.com/mozilla/fxa/commit/678c6f720874c250ed293fdad252bf2c05d97c17.

This is a follow up / maintenance issue to cleanup the props, ideally we would have `onValidate` handle both promises and the existing signature.

More context on this can be found in the pr => https://github.com/mozilla/fxa/pull/9924#discussion_r675002880

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3802)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
