### ISSUE TITLE
Login panel shifts down after opening onscreen keyboard on iPad

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9983]
When logging into Pocket via FxA on iPad, the login panel shifts down after using the onscreen keyboard. This happened on a 6th gen iPad running iOS version 14.6.

!IMG_0006.PNG|thumbnail!  !IMG_0007.PNG|thumbnail!  !IMG_0008.PNG|thumbnail!  !IMG_0009.PNG|thumbnail!  !IMG_0010.PNG|thumbnail!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-3810)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15823/IMG_0006.PNG">IMG_0006.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15822/IMG_0007.PNG">IMG_0007.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15821/IMG_0008.PNG">IMG_0008.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15820/IMG_0009.PNG">IMG_0009.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15819/IMG_0010.PNG">IMG_0010.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15873/IMG_0425.PNG">IMG_0425.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15872/IMG_0426.PNG">IMG_0426.PNG</a> | <a href="https://mozilla-hub.atlassian.net/secure/attachment/15874/IMG_0427.PNG">IMG_0427.PNG</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Turns out none of us have ipads but Vijay Budhram is going to try to reproduce this in a simulator.  Or maybe Chelsea Lewis can let us borrow one out of her stack of ipads!

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Confirmed that I’m able to reproduce on an iPad Pro 12.9 running 14.6. Every time you close the on-screen keyboard, the FxA login moves down the page. Moved to “To Do” and moved up on the backlog.

!IMG_0425.PNG|width=2732,height=2048!

!IMG_0426.PNG|width=2732,height=2048!

!IMG_0427.PNG|width=2732,height=2048!

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

So... I too can reproduce this on my iPad. Problem is this is occurring only within an iOS Webview, which cannot be inspected unless you are running a version of the app via XCode (on-device or simulator). It's possible this is being caused by our use of flexbox somehow, but unless I can inspect it's hard to debug. I also tried to repro this behavior when logging into Firefox iOS and Mozilla VPN for iOS, which present the same flow in a Webview, but was unable to, so this could very well be a bug in Pocket for iOS itself. Unless someone can suggest a different approach to debugging my next suggestion would be to get someone from Pocket to help set me up with the app in XCode.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

🚩 Flag added

On hold while we wait to hear from a Pocket person

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
