### ISSUE TITLE
Add ability for user to resend the `Finish Account Setup` email

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9985]
To help reduce UX friction around password forgot token expiration, we should add a new endpoint that can allow a user to resend the code and email.

Additionally, we can also resend the `Finish Account Setup` email if the user attempts to reset password but had never set one in the first place.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/FXA-3811)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
