### ISSUE TITLE
[subplat] Consider removing references to Amplitude in metrics code

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9988]
As of June 2021, we [migrated from Amplitude to Looker](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=130920045#LookerDeployWorkingGroup-Roadmap) for data analytics. Thankfully, the way we record metrics (at least on the payments server) means that Looker can consume our existing events without any changes. However, it can be confusing that much of our metrics code, our event labels and even some metrics-related file names have "amplitude" in them.

Ideally, we can rename these files/methods/events to something more tool-agnostic.

┆Issue is synchronized with this [Jiraserver Task](https://mozilla-hub.atlassian.net/browse/FXA-3814)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Barry noted, this also affects the strings we query for when querying for events. Probably a bigger change than just changing variable/file names.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
